parent/pom.xml

Upgrade Icu4j to version 73.2

---

parent/pom.xml

Upgrade Graphql Java to version 21.0

---

parent/pom.xml

Upgrade Compress LZF to version 1.1.2

---

components/camel-caffeine/src/test/java/org/apache/camel/component/caffeine/processor/idempotent/CaffeineIdempotentRepositoryTest.java

Camel-19445. Simplified assertion in CaffeineIdempotentRepositoryTest

---

components/camel-amqp/src/test/java/org/apache/camel/component/amqp/AMQPRouteTest.java
components/camel-amqp/src/test/java/org/apache/camel/component/amqp/AMQPRouteTraceFrameTest.java
components/camel-amqp/src/test/java/org/apache/camel/component/amqp/AMQPToDSendDynamicTest.java
components/camel-amqp/src/test/java/org/apache/camel/component/amqp/AMQPToDTest.java
components/camel-amqp/src/test/java/org/apache/camel/component/amqp/artemis/AMQPEmbeddedBrokerTest.java

- Added final where possible
- Deleted redundant exception throws
- Fixed outdated concatenation with empty strings

CAMEL-19598: Test code cleanups

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.102

---

parent/pom.xml

Upgrade Rest Assured to version 5.3.1

---

parent/pom.xml

Ref: https://www.cve.org/CVERecord?id=CVE-2023-37582

Upgrade RocketMQ to version 4.9.7

---

parent/pom.xml

Upgrade Libphonenumber to version 8.13.16

---

parent/pom.xml

Upgrade Avro to version 1.11.2

---

parent/pom.xml

Upgrade Cassandra Driver to version 4.17.0

---

core/camel-core/src/test/java/org/apache/camel/component/file/FileConsumerFailureHandledTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FileConsumerMoveFailureOnCompletionTest.java

- add a small timeout on a few tests for less flakiness on slower hosts

(chores) camel-core: test fixes

---

components/camel-xchange/pom.xml
components/camel-xchange/src/main/java/org/apache/camel/component/xchange/XChange.java
components/camel-xchange/src/main/java/org/apache/camel/component/xchange/XChangeEndpoint.java
components/camel-xchange/src/test/java/org/apache/camel/component/xchange/XChangeTestSupport.java
components/camel-xchange/src/test/java/org/apache/camel/component/xchange/account/AccountProducerTest.java
components/camel-xchange/src/test/java/org/apache/camel/component/xchange/metadata/MetaDataProducerTest.java
parent/pom.xml

https://issues.apache.org/jira/browse/CAMEL-19605

[CAMEL-19605] camel-xchange - Upgrade to xchange 5.1.0

---

parent/pom.xml

Upgrade Rome tools to version 2.1.0

---

pom.xml

https://issues.apache.org/jira/browse/CAMEL-19465

CAMEL-19465 - Move Apache snapshots repository to a separate Maven profile for better build reproducibility

---

test-infra/camel-test-infra-infinispan/src/test/java/org/apache/camel/test/infra/infinispan/services/InfinispanLocalContainerService.java

Use Infinispan 14.0.12.Final image for testing in test-infra

---

parent/pom.xml

Remove Templating Maven plugin property placeholder

---

components/camel-dhis2/camel-dhis2-component/src/test/java/org/apache/camel/component/dhis2/Dhis2ResourceTablesIT.java

CAMEL-19550: camel-dhis2

---

components/camel-telegram/src/test/java/org/apache/camel/component/telegram/TelegramConsumerMappingTest.java
components/camel-telegram/src/test/java/org/apache/camel/component/telegram/integration/TelegramServiceIT.java
components/camel-telegram/src/test/java/org/apache/camel/component/telegram/integration/TelegramServiceProxyIT.java

- Added assertions where possible
- Simplified assertions where possible

CAMEL-19556: camel-telegram

---

parent/pom.xml

Obs.: I'm waiting for the full tests on my own CI, so I'll merge when it's complete there.

CAMEL-19589: upgraded testcontainers to 1.18.3

---

components/camel-irc/src/test/unrealircd/unrealircd.conf
components/camel-telegram/src/test/java/org/apache/camel/component/telegram/integration/TelegramServiceProxyIT.java
core/camel-core/src/test/java/org/apache/camel/processor/ResequenceStreamNotIgnoreInvalidExchangesTest.java
parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.105

---

components/camel-aws/camel-aws2-kinesis/pom.xml
components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/Kinesis2Configuration.java
components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/Kinesis2Consumer.java
components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/Kinesis2Endpoint.java
components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/client/KinesisAsyncInternalClient.java
components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/client/KinesisClientFactory.java
components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/client/impl/KinesisAsyncClientIAMOptimizedImpl.java
components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/client/impl/KinesisAsyncClientIAMProfileOptimizedImpl.java
components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/client/impl/KinesisAsyncClientStandardImpl.java
components/camel-aws/camel-aws2-kinesis/src/test/java/org/apache/camel/component/aws2/kinesis/KinesisClientFactoryTest.java
parent/pom.xml

CAMEL-19584 : add KinesisAsyncClient to the camel component

---

camel-dependencies/pom.xml
parent/pom.xml

Pick up a fix for an embedded Netty CVE - https://nvd.nist.gov/vuln/detail/cve-2021-21409

Upgrade Kudu to 1.16.0 (#8919)

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaAutowireTest.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaComponentTest.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaConsumerTest.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaProducerTest.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/MockConsumerInterceptor.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/MockProducerInterceptor.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/consumer/OffsetCacheTest.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerAsyncManualCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerAuthIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerAuthInvalidIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerAuthInvalidWithReconnectIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerAuthManualTest.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerFullIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentGroupIdIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentWithCustomSerializerIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentWithProcessorIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerRebalanceIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaProducerFullIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaTransactionIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/commit/KafkaConsumerAsyncWithOffsetRepoCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/commit/KafkaConsumerSyncWithOffsetRepoCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/pause/KafkaPausableConsumerCircuitBreakerIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/pause/KafkaPausableConsumerIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/serde/DefaultKafkaHeaderDeserializerTest.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/serde/DefaultKafkaHeaderSerializerTest.java
components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryEagerIT.java
components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryNonEagerIT.java
components/camel-kafka/src/test/java/org/apache/kafka/clients/producer/KafkaProducerTest.java

- Fixed string concatenation
- Added final where possible
- Deleted unused throws
- Fixed grammar issues

CAMEL-19447: camel-kafka test cleanups 

---

camel-dependencies/pom.xml
parent/pom.xml

Same reasoning as https://github.com/apache/camel/pull/10722

Upgrade batik version to 1.16 (#9718) (#10722)

---

camel-dependencies/pom.xml
parent/pom.xml

Same reasoning as https://github.com/apache/camel/pull/10724

Upgrade batik version to 1.16 (#9718) (#10722) (#10724)

---

components/camel-aws/camel-aws2-kinesis/pom.xml
components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/Kinesis2Consumer.java
components/camel-aws/camel-aws2-kinesis/src/test/java/org/apache/camel/component/aws2/kinesis/KinesisConsumerClosedShardWithSilentTest.java

integrate multi-shard consumer with async client

---

camel-dependencies/pom.xml
parent/pom.xml

Same reasons for https://github.com/apache/camel/pull/10746

Updating Hazelcast to 5.2.4 (#10746)

---

camel-dependencies/pom.xml
parent/pom.xml

Same reasons as https://github.com/apache/camel/pull/10748

Updating Hazelcast to 5.2.4 (#10746) (#10748)

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.107

---

parent/pom.xml

Upgrade zookeeper 3.8.2

---

parent/pom.xml

Upgrade google-cloud 26.19.0

---

components/camel-google/camel-google-calendar/pom.xml
components/camel-google/camel-google-drive/pom.xml
components/camel-google/camel-google-mail/pom.xml
components/camel-google/camel-google-sheets/pom.xml

Upgrade google http client 1.43.3

---

camel-dependencies/pom.xml
parent/pom.xml

Same as for https://github.com/apache/camel/pull/10752

Updating drill to 1.21.1 (#10752)

---

camel-dependencies/pom.xml
parent/pom.xml

* Upgrade Drill to version 1.20.2
* Upgrade Drill to version 1.21.0
* Upgrade Drill to version 1.21.1
* Updating drill to 1.21.1
---------

Updating drill to 1.21.1 (#10752) (#10755)

---

camel-dependencies/pom.xml
parent/pom.xml

Same as https://github.com/apache/camel/pull/10763

Upgrade Johnzon JsonB to version 1.2.21 (#10763)

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.108

---

parent/pom.xml

Removed Amazon Kinesis Common property placeholder, not in use

---

components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/Kinesis2Consumer.java
components/camel-aws/camel-aws2-kinesis/src/test/java/org/apache/camel/component/aws2/kinesis/KinesisConsumerClosedShardWithSilentTest.java
parent/pom.xml

add the capability of consume only a single shard or more

---

camel-dependencies/pom.xml
parent/pom.xml

Same as for https://github.com/apache/camel/pull/10764

Upgrade Johnzon JsonB to version 1.2.21 (#10763) (#10764)

---

components/camel-aws/camel-aws2-kinesis/src/main/docs/aws2-kinesis-component.adoc

Kinesis doc update

---

components/camel-aws/camel-aws2-lambda/src/test/java/org/apache/camel/component/aws2/lambda/integration/LambdaAliasesIT.java
components/camel-aws/camel-aws2-lambda/src/test/java/org/apache/camel/component/aws2/lambda/integration/LambdaCreateFunctionIT.java
components/camel-aws/camel-aws2-lambda/src/test/java/org/apache/camel/component/aws2/lambda/integration/LambdaDeleteFunctionIT.java
components/camel-aws/camel-aws2-lambda/src/test/java/org/apache/camel/component/aws2/lambda/integration/LambdaGetFunctionIT.java
components/camel-aws/camel-aws2-lambda/src/test/java/org/apache/camel/component/aws2/lambda/integration/LambdaListFunctionsIT.java
components/camel-aws/camel-aws2-lambda/src/test/java/org/apache/camel/component/aws2/lambda/integration/LambdaPublishVersionIT.java
components/camel-aws/camel-aws2-sns/src/test/java/org/apache/camel/component/aws2/sns/integration/SnsTopicProducerWithSubscriptionIT.java
test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSContainer.java

Upgrade Localstack container image to version 2.2.0

---

components/camel-aws/camel-aws2-kinesis/src/main/docs/aws2-kinesis-component.adoc
components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/Kinesis2Consumer.java
components/camel-aws/camel-aws2-kinesis/src/test/java/org/apache/camel/component/aws2/kinesis/KinesisConsumerClosedShardWithSilentTest.java
parent/pom.xml

Aws2 kinesis doc update

---

dsl/camel-xml-io-dsl/pom.xml

(chores) camel-xml-dsl-io: run sequentially

---

parent/pom.xml
test-infra/camel-test-infra-infinispan/src/test/java/org/apache/camel/test/infra/infinispan/services/InfinispanLocalContainerService.java

Upgrade Infinispan 14.0.13

---

parent/pom.xml

Upgrade to Netty 4.1.95

---

components/camel-elytron/pom.xml
parent/pom.xml

Upgrade javax json-api 1.1.4

---

parent/pom.xml

Upgrade huaweicloud-sdk-core 3.1.49

---

parent/pom.xml

Upgrade maven-shared-utils 3.4.2

---

components/camel-jetty/pom.xml
components/camel-olingo2/camel-olingo2-component/pom.xml
components/camel-salesforce/camel-salesforce-component/pom.xml
parent/pom.xml

Remove duplicate version for okclient

---

components/camel-jcr/pom.xml
components/camel-jdbc/pom.xml
components/camel-jpa/pom.xml
components/camel-mybatis/pom.xml
components/camel-quartz/pom.xml
components/camel-spring-jdbc/pom.xml
components/camel-spring-xml/pom.xml
components/camel-sql/pom.xml
components/camel-sql/src/test/java/org/apache/camel/processor/aggregate/jdbc/AbstractJdbcAggregationTestSupport.java
components/camel-sql/src/test/java/org/apache/camel/processor/aggregate/jdbc/JdbcAggregationRepositoryAlotDataTest.java
parent/pom.xml
tests/camel-itest/pom.xml

Upgrade derby 10.16.1.1

---

parent/pom.xml

Go back to etcd 0.7.5 as it works with unit tests.

---

core/camel-core-model/src/main/java/org/apache/camel/builder/FlexibleAggregationStrategy.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/MulticastProcessor.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/SendProcessor.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/Throttler.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/aggregate/AggregateProcessor.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/saga/SagaProcessor.java
core/camel-core-xml/src/main/java/org/apache/camel/core/xml/AbstractCamelContextFactoryBean.java
core/camel-main/src/main/java/org/apache/camel/main/BaseMainSupport.java
core/camel-management/src/main/java/org/apache/camel/management/mbean/ManagedProcessor.java
core/camel-util/src/main/java/org/apache/camel/util/FileUtil.java
core/camel-xml-io-util/src/main/java/org/apache/camel/xml/io/util/XmlStreamInfo.java
core/camel-xml-jaxp/src/main/java/org/apache/camel/converter/jaxp/XMLStreamReaderInputStream.java
core/camel-xml-jaxp/src/main/java/org/apache/camel/converter/jaxp/XMLStreamReaderReader.java

(chores) core: use final when possible

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.109

---

parent/pom.xml

Upgrade Caffeine to version 3.1.7

---

core/camel-core/src/test/java/org/apache/camel/component/file/AntPathMatcherGenericFileFilterTest.java

Fix flaky test

---

Jenkinsfile.deploy

The issues preventing deployment seem to have been fixed

INFRA-24713: remove the deployment work-around

---

components/camel-aws/camel-aws2-ec2/src/main/java/org/apache/camel/component/aws2/ec2/AWS2EC2Endpoint.java

CAMEL-19642: camel-aws2-ec2 - Should not be scheduled poll endpoint

---

core/camel-api/src/main/java/org/apache/camel/CamelContextAware.java

CAMEL-16592: camel-api - CamelContextAware should extend HasCamelContext

---

components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyConsumerClientModeReconnectTest.java

Replacing Thread.sleep in tests using Awaitility in camel-netty component. Using Threads.sleep is bug prone and can introduce flakiness when running on environments with different capacities.
https://issues.apache.org/jira/browse/CAMEL-19539

CAMEL-19539: Replace Thread.sleep in tests

---

docs/user-manual/modules/ROOT/pages/using-propertyplaceholder.adoc

Fix typo "month" to "mount" in using-propertyplaceholder.adoc

---

components/camel-azure/camel-azure-files/src/main/java/org/apache/camel/component/file/azure/FilesConsumer.java
components/camel-azure/camel-azure-files/src/main/java/org/apache/camel/component/file/azure/FilesPath.java
components/camel-azure/camel-azure-files/src/main/java/org/apache/camel/component/file/azure/FilesToken.java
components/camel-azure/camel-azure-files/src/main/java/org/apache/camel/component/file/azure/FilesURIStrings.java
components/camel-azure/camel-azure-files/src/main/java/org/apache/camel/component/file/azure/NormalizedOperations.java
components/camel-azure/camel-azure-files/src/test/java/org/apache/camel/component/file/azure/FilesConfigurationTests.java

Some checkstyle violations prevent the build to pass and must be fixed
* Applies checkstyle recommendations

CAMEL-19279: Fix checkstyle violations

---

parent/pom.xml

Upgrade smallrey fault tolerance 6.2.6

---

components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Consumer.java

CAMEL-19562: aws sqs visibility extender is running forever

---

components/camel-azure/camel-azure-files/src/main/java/org/apache/camel/component/file/azure/FilesConsumer.java
components/camel-azure/camel-azure-files/src/main/java/org/apache/camel/component/file/azure/FilesPath.java
components/camel-azure/camel-azure-files/src/main/java/org/apache/camel/component/file/azure/FilesToken.java
components/camel-azure/camel-azure-files/src/main/java/org/apache/camel/component/file/azure/FilesURIStrings.java
components/camel-azure/camel-azure-files/src/main/java/org/apache/camel/component/file/azure/NormalizedOperations.java
components/camel-azure/camel-azure-files/src/test/java/org/apache/camel/component/file/azure/FilesConfigurationTests.java

Some checkstyle violations prevent the build to pass and must be fixed
* Applies checkstyle recommendations

CAMEL-19279: Fix checkstyle violations (#10829)

---

components/camel-aws/camel-aws-secrets-manager/src/main/java/org/apache/camel/component/aws/secretsmanager/SecretsManagerEndpoint.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaComponent.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaProducer.java
components/camel-quartz/src/test/java/org/apache/camel/routepolicy/quartz/SpringScheduledRoutePolicyTest.java
dsl/camel-componentdsl/src/generated/java/org/apache/camel/builder/component/dsl/AzureServicebusComponentBuilderFactory.java
dsl/camel-componentdsl/src/generated/java/org/apache/camel/builder/component/dsl/GoogleMailStreamComponentBuilderFactory.java
dsl/camel-componentdsl/src/generated/java/org/apache/camel/builder/component/dsl/KafkaComponentBuilderFactory.java
dsl/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/dsl/KafkaEndpointBuilderFactory.java
parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.112

---

components/camel-kubernetes/src/generated/java/io/fabric8/kubernetes/client/ConfigFluentImplConfigurer.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/cluster/utils/LockTestServer.java
parent/pom.xml

Upgrade Kubernetes Client to version 6.8.0

---

parent/pom.xml

CAMEL-19661: camel-kafka - Upgrade to Kafka 3.5.1

---

components/camel-mail/src/main/java/org/apache/camel/component/mail/MailComponent.java
parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.113

---

core/camel-api/src/main/java/org/apache/camel/DynamicRouter.java
core/camel-api/src/main/java/org/apache/camel/RecipientList.java
core/camel-api/src/main/java/org/apache/camel/RoutingSlip.java
core/camel-core-model/src/main/java/org/apache/camel/model/DynamicRouterDefinition.java
core/camel-core-model/src/main/java/org/apache/camel/model/EnrichDefinition.java
core/camel-core-model/src/main/java/org/apache/camel/model/PollEnrichDefinition.java
core/camel-core-model/src/main/java/org/apache/camel/model/RecipientListDefinition.java
core/camel-core-model/src/main/java/org/apache/camel/model/RoutingSlipDefinition.java
core/camel-core-model/src/main/java/org/apache/camel/model/ToDynamicDefinition.java
core/camel-core-model/src/main/java/org/apache/camel/model/WireTapDefinition.java

correct "turn of" to "turn off"

correct "turn of" to "turn off"

---

components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/Kinesis2Consumer.java
components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/Kinesis2Endpoint.java
components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/consumer/KinesisConnection.java
components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/consumer/KinesisHealthCheck.java
components/camel-aws/camel-aws2-kinesis/src/test/java/org/apache/camel/component/aws2/kinesis/KinesisConsumerClosedShardWithFailTest.java
components/camel-aws/camel-aws2-kinesis/src/test/java/org/apache/camel/component/aws2/kinesis/KinesisConsumerClosedShardWithSilentTest.java
components/camel-aws/camel-aws2-kinesis/src/test/java/org/apache/camel/component/aws2/kinesis/integration/KinesisConsumerIT.java
components/camel-aws/camel-aws2-kinesis/src/test/java/org/apache/camel/component/aws2/kinesis/integration/KinesisConsumerResumeIT.java
components/camel-aws/camel-aws2-kinesis/src/test/java/org/apache/camel/component/aws2/kinesis/integration/KinesisProducerIT.java

kinesis connection retry mechanism added into the current consumer

---

components/camel-mllp/src/main/java/org/apache/camel/component/mllp/MllpProtocolConstants.java

We recently received HL7 messages with `MSH-18` = `UNICODE UTF-8`
This is currently not supported in camel-mllp, which we only became aware of because of a user complaint regarding garbled characters. This is because [`MllpCharsetHelper` falls back to a default charset](https://github.com/apache/camel/blob/camel-3.21.0/components/camel-mllp/src/main/java/org/apache/camel/component/mllp/MllpCharsetHelper.java#L56-L58) (ISO-8859-2).
We expected `MSH-18` to be respected if set, but the current behavior might just be according to spec ...
Anyway; for our use case this simple change suffices.
(this generated some unrelated changes that I could push, but would rather not)

support more MLLP charsets

---

dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

CAMEL-19683: camel-jbang - Use RC2 as new default version.

---

core/camel-api/src/main/java/org/apache/camel/Exchange.java
core/camel-api/src/main/java/org/apache/camel/spi/BacklogTracerEventMessage.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/debugger/DefaultBacklogTracerEventMessage.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/CamelInternalProcessor.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultChannel.java
core/camel-support/src/main/java/org/apache/camel/support/HealthCheckComponent.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/CamelTraceAction.java

Jbang trace

---

parent/pom.xml
test-infra/camel-test-infra-opensearch/src/test/java/org/apache/camel/test/infra/opensearch/services/OpenSearchLocalContainerService.java

This PR upgrades OpenSearch to v2.9.0.
No corresponding JIRA issue since it's just a minor dependency upgrade.

camel-opensearch - Upgrade to OpenSearch 2.9.0

---

test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/StrimziContainer.java

CAMEL-19661: upgrade Strimzi container to use Kafka 3.5.1

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.115

---

parent/pom.xml

Upgrade InfluxDB 2.x Driver to version 6.10.0

---

components/camel-attachments/src/test/java/org/apache/camel/attachment/MulticastAggregationStrategyTest.java

Test case for attachment being removed from the Exchange after AggregationStrategy

CAMEL-19675: added test case for aggregation strategy with attachment

---

components/camel-kubernetes/src/generated/java/io/fabric8/kubernetes/client/ConfigFluentImplConfigurer.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/cluster/utils/LockTestServer.java
parent/pom.xml

Discussed here: https://camel.zulipchat.com/#narrow/stream/364655-camel-v4-work-in-progress/topic/kubernetes-client.20.206.2E8.20upgrade

Revert "Upgrade Kubernetes Client to version 6.8.0 (#10852)"

---

core/camel-core-model/src/main/java/org/apache/camel/builder/NotifyBuilder.java

I am adding an extra layer of logs to the notify builder so we can check how spread the problem with the latch not counting down is. It also adds a comment based on a discussing I had with @davsclaus yesterday.

(chores) camel-core-model: added debugging and comments

---

components/camel-stomp/src/test/java/org/apache/camel/component/stomp/StompConsumerHeaderFilterStrategyTest.java

Emulate STOMP tests strategy, like other stomp tests seems like this, the test is more stable

CAMEL-19684: Stabilize Stomp test

---

components/camel-zipfile/src/test/java/org/apache/camel/dataformat/zipfile/ZipFileSplitAndDeleteTest.java
parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.117

---

parent/pom.xml

Upgrade Netty to version 4.1.96.Final

---

test-infra/camel-test-infra-hashicorp-vault/src/test/java/org/apache/camel/test/infra/hashicorp/vault/services/HashicorpVaultLocalContainerService.java

Use latest Hashicorp Vault container image 1.13.3 for test-infra module

---

components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/integration/XmppMultiUserChatIT.java
components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/integration/XmppRouteChatIT.java

CAMEL-19547: removed Thread.sleep in camel-xmpp

---

components/camel-google/camel-google-storage/pom.xml
components/camel-google/camel-google-storage/src/test/java/org/apache/camel/component/google/storage/localstorage/FakeStorageRpc.java
parent/pom.xml

Updates to `FakeStorageRpc` are just a sync from it's original [source](https://github.com/googleapis/java-storage-nio/blob/master/google-cloud-nio/src/main/java/com/google/cloud/storage/contrib/nio/testing/FakeStorageRpc.java).

Upgrade Google Cloud libraries-bom to 26.21.0

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConfiguration.java

Issue link - https://issues.apache.org/jira/browse/CAMEL-19691

CAMEL-19691: camel-kafka - Allow sslKeystorePassword to be blank.

---

parent/pom.xml

AWS upgrade (Enjoy PTO Andrea)

---

parent/pom.xml

Upgrade to Azure 1.2.15

---

parent/pom.xml

Upgrade grpc 1.57.1

---

parent/pom.xml

Upgrade commons-lang 3.13.0

---

parent/pom.xml

Upgrade google cloud functions/secrets-manager

---

parent/pom.xml

Upgrade elasticsearch 8.9.0

---

components/camel-jcr/pom.xml

(chores) camel-jcr: try reusing forks to reduce test duration

---

components/camel-jcr/src/test/java/org/apache/camel/component/jcr/JcrAuthTestBase.java
components/camel-jcr/src/test/java/org/apache/camel/component/jcr/JcrRouteTestSupport.java

(chores) camel-jcr: avoid recreating the repository for every single test

---

components/camel-optaplanner/src/test/resources/org/apache/camel/component/optaplanner/solverConfig.xml

(chores) camel-optaplanner: reduce the time spent trying to solve the problems

---

components/camel-quartz/src/test/java/org/apache/camel/routepolicy/quartz/CronScheduledRoutePolicyTest.java

camel-quartz - Fix flaky test

---

components/camel-mock/src/main/java/org/apache/camel/component/mock/MockEndpoint.java

- removed unused throws
- use final variables whenever possible
- cleanup duplicated code

(chores) camel-mock: code cleanups

---

components/camel-mock/src/main/java/org/apache/camel/component/mock/MockEndpoint.java

- cleanup typos
- fix other minor documentation issues

(chores) camel-mock: documentation cleanup

---

apache-camel/src/main/descriptors/src.xml
components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/XmppDeferredConnectionIT.java
components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/integration/XmppMultiUserChatIT.java
components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/integration/XmppProducerConcurrentIT.java
components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/integration/XmppRouteChatIT.java
components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/integration/XmppRouteIT.java
components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/integration/XmppRouteMultipleProducersSingleConsumerIT.java
pom.xml
tooling/maven/bom-generator-maven-plugin/src/main/java/org/apache/camel/maven/bom/generator/BomGeneratorMojo.java

Add apache-camel to release so we build source tarball

---

components/camel-platform-http-main/pom.xml
components/camel-platform-http-main/src/main/java/org/apache/camel/component/platform/http/main/MainHttpServer.java
components/camel-platform-http-main/src/test/java/org/apache/camel/component/platform/http/main/MainHttpFakeHealthCheck.java
components/camel-platform-http-main/src/test/java/org/apache/camel/component/platform/http/main/MainHttpServerTest.java

- Added unity test to verify changes

 CAMEL-19647: use 503 for health check DOWN

---

components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/CamelRouteCoverageDumper.java
components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/params/ParameterizedExtension.java
components/camel-test/camel-test-junit5/src/test/java/org/apache/camel/test/junit5/patterns/AsyncSendMockTest.java

- simplified assertion
- simplify other complex operations

(chores) camel-test-junit5: code cleanups:

---

components/camel-jms/src/test/java/org/apache/camel/component/jms/TwoConsumerOnSameQueueTest.java

When two consumers are reading from the same queue, it may not always be possible to reliably determine which one may receive the message.
As such, tests both mock endpoints to ensure that in combination, all expected data was received.

CAMEL-19669: fixed non-deterministic assertion

---

core/camel-api/src/generated/java/org/apache/camel/spi/annotations/YamlProperty.java
core/camel-api/src/generated/java/org/apache/camel/spi/annotations/YamlType.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/ModelDeserializers.java
dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/src/main/java/org/apache/camel/maven/dsl/yaml/GenerateYamlDeserializersMojo.java
dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/src/main/java/org/apache/camel/maven/dsl/yaml/GenerateYamlSchemaMojo.java
dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/src/main/java/org/apache/camel/maven/dsl/yaml/support/Schema.java
dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/src/main/java/org/apache/camel/maven/dsl/yaml/support/YamlProperties.java
dsl/camel-yaml-dsl/camel-yaml-dsl/pom.xml
dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camel-yaml-dsl.json
dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camelYamlDsl.json
tooling/spi-annotations/src/main/java/org/apache/camel/spi/annotations/YamlProperty.java
tooling/spi-annotations/src/main/java/org/apache/camel/spi/annotations/YamlType.java

[CAMEL-19709] yaml dsl: include additional information such as description and title in the jscon schema

---

parent/pom.xml

camel-aws - Upgrade to latest SDK 121

---

parent/pom.xml

Upgrade to aws client .122

---

components/camel-spring-batch/pom.xml
components/camel-spring-batch/src/test/java/org/apache/camel/component/spring/batch/SpringBatchEndpointTest.java

camel-spring-batch - Make test faster

---

components/camel-spring-ws/pom.xml
components/camel-spring-ws/src/main/java/org/apache/camel/component/spring/ws/bean/CamelDirectConnection.java

camel-spring-ws - Make testing much faster

---

dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/kamelet-action.yaml.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/kamelet-sink.yaml.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/kamelet-source.yaml.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/step-kamelet.yaml.tmpl
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/KameletBindingLoaderTest.groovy
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/KameletLoaderDependenciesTest.groovy
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/KameletLoaderTest.groovy
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/issues/KameletTemplatingTest.groovy
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/resources/kamelets/error-handler.kamelet.yaml
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/resources/kamelets/log-action.kamelet.yaml
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/resources/kamelets/log-sink.kamelet.yaml
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/resources/kamelets/mySetBody.kamelet.yaml
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/resources/kamelets/prefix-action.kamelet.yaml
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/resources/kamelets/route-timer-source.kamelet.yaml
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/resources/kamelets/timer-source.kamelet.yaml

Camel K 2.0.0 has changed the api version from camel.apache.org/v1alpha1 to camel.apache.org/v1 for Kamelet kind

CAMEL-19733 - update apiVersion in CRDs for Kamelet

---

components/camel-dhis2/camel-dhis2-component/src/main/docs/dhis2-component.adoc

Remove duplication in DHIS2 component docs

docs: remove duplication in DHIS2 component docs

---

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_1.adoc

Updated camel 4_1 upgrade doc

---

core/camel-core/src/test/java/org/apache/camel/component/file/FileConsumerIdempotentKeyChangedIssue2Test.java
core/camel-core/src/test/java/org/apache/camel/impl/engine/DefaultSupervisingRouteControllerTest.java

CAMEL-19684: Fix flaky test

---

components/camel-jcr/src/test/resources/repository-simple-security.xml

camel-jcr - Test a little bit faster

---

components/camel-jetty/pom.xml
components/camel-jetty/src/test/java/org/apache/camel/component/jetty/InterfacesTest.java
components/camel-jetty/src/test/java/org/apache/camel/component/jetty/JettySuspendWhileInProgressTest.java
components/camel-jetty/src/test/java/org/apache/camel/component/jetty/rest/RestJettyRemoveAddRestAndRouteTest.java
components/camel-jetty/src/test/resources/org/apache/camel/component/jetty/JettyComponentSpringConfiguredTest.xml
components/camel-jetty/src/test/resources/org/apache/camel/component/jetty/jetty-https.xml
components/camel-jetty/src/test/resources/org/apache/camel/component/jetty/jetty-noconnection-redelivery.xml
components/camel-jetty/src/test/resources/org/apache/camel/component/jetty/jetty-noconnection.xml

camel-jetty - Make testing faster

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/models/beans.json
catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd
core/camel-core-model/src/generated/resources/org/apache/camel/model/app/beans.json
core/camel-core-model/src/main/java/org/apache/camel/model/app/BeansDefinition.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/ModelDeserializers.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camel-yaml-dsl.json
dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camelYamlDsl.json

Fix typo `groupping` --> `grouping`

---

core/camel-core/src/test/java/org/apache/camel/component/file/cluster/FileLockClusteredRoutePolicyFactoryTest.java

camel-core - Run test faster

---

components/camel-freemarker/pom.xml
components/camel-mvel/pom.xml
components/camel-ognl/pom.xml
components/camel-stringtemplate/pom.xml
components/camel-velocity/pom.xml

Some more components can test in parallel

---

tests/camel-itest/src/test/java/org/apache/camel/itest/jms/JmsConsumerShutdownTest.java
tests/camel-itest/src/test/java/org/apache/camel/itest/jms/JmsJettyAsyncTest.java

camel-test - Make jms test faster

---

components/camel-mail/src/test/java/org/apache/camel/component/mail/MailConvertersTest.java

camel-mail - Attempt to fix flaky test

---

parent/pom.xml
test-infra/camel-test-infra-pulsar/src/test/java/org/apache/camel/test/infra/pulsar/services/PulsarLocalContainerService.java

Upgrade to Apache Pulsar 3.0.1

---

core/camel-core/src/test/java/org/apache/camel/component/file/strategy/FileChangedReadLockZeroTimeoutTest.java
core/camel-core/src/test/java/org/apache/camel/impl/ScheduledPollConsumerTest.java

camel-core - Make test go faster and reformat

---

parent/pom.xml

Upgrade reactor-core 3.5.9

---

parent/pom.xml

Upgrade micrometer 1.11.3 and tracing 1.1.4

---

components/camel-stub/src/main/java/org/apache/camel/component/stub/StubConsole.java
core/camel-console/src/main/java/org/apache/camel/impl/console/EndpointDevConsole.java
core/camel-console/src/main/java/org/apache/camel/impl/console/SourceDevConsole.java
dsl/camel-cli-connector/src/main/java/org/apache/camel/cli/connector/LocalCliConnector.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelJBangMain.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/CamelSourceTop.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/CamelStubAction.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/CamelThreadDump.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/MessageTableHelper.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/RouteControllerAction.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/ListEndpoint.java

CAMEL-19747: camel-jbang - Add command to browse stub queues

---

components/camel-jetty/src/test/java/org/apache/camel/component/jetty/async/MyAsyncComponent.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/async/MyAsyncComponent.java
components/camel-sjms/src/test/java/org/apache/camel/component/sjms/support/MyAsyncComponent.java
components/camel-xchange/src/main/java/org/apache/camel/component/xchange/XChangeHelper.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/IntrospectionSupport.java
core/camel-core/src/test/java/org/apache/camel/processor/async/MyAsyncComponent.java
core/camel-xml-io/src/test/java/org/apache/camel/xml/out/ModelWriterTest.java

Adjusted the code to use the StringHelper capitalize method

(chores) cleanup duplicated capitalization code

---

components/camel-servicenow/camel-servicenow-maven-plugin/src/main/java/org/apache/camel/maven/CamelServiceNowGenerateMojo.java
tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/Strings.java
tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/srcgen/Property.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointDslMojo.java

Adjusted the code to use the StringHelper or the Strings capitalize method

(chores) cleanup duplicated capitalization code in tooling

---

components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FromFileToFtpSplitParallelIT.java

FromFileToFtpSplitParallelIT tests works fine without any changes

CAMEL-18998: removed @Disabled in camel-ftp test

---

parent/pom.xml

Upgrade google-cloud stuff

---

components/camel-openapi-java/src/main/java/org/apache/camel/openapi/OpenAPI3to2.java
components/camel-openapi-java/src/main/java/org/apache/camel/openapi/RestOpenApiReader.java

CAMEL-19764: fix generation for basic and bearer security schemes

---

components/camel-jdbc/src/main/java/org/apache/camel/component/jdbc/JdbcProducer.java
dsl/camel-cli-connector/src/main/java/org/apache/camel/cli/connector/LocalCliConnector.java
dsl/camel-jsh-dsl/src/main/java/org/apache/camel/dsl/jsh/JshLoaderDelegate.java

* camel-jdbc
* dsl/camel-cli-connector
* dsl/camel-jsh-dsl

CAMEL-19770: fixed catching Throwables in components

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade versions to match spring-boot-dependencies 2.7.14 (trying to upgrade camel-spring-boot to that version of spring-boot)

Version upgrades (maven-war-plugin, spring-integration, spring-batch)

---

components/camel-infinispan/camel-infinispan/src/main/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteAggregationRepository.java
parent/pom.xml
test-infra/camel-test-infra-infinispan/src/test/java/org/apache/camel/test/infra/infinispan/services/InfinispanLocalContainerService.java

Upgrade infinispan 14.0.14

---

components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Consumer.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/AmazonSQSClientMock.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cluster/ConsulClusteredRoutePolicyFactoryIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cluster/ConsulClusteredRoutePolicyIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cluster/ConsulMasterIT.java
components/camel-mail/src/test/java/org/apache/camel/component/mail/RawMailMessageTest.java
components/camel-opensearch/src/test/java/org/apache/camel/component/opensearch/integration/OpensearchSizeLimitIT.java
components/camel-sjms/src/test/java/org/apache/camel/component/sjms/AsyncStartStopListenerTest.java
components/camel-sjms/src/test/java/org/apache/camel/component/sjms/JmsSelectorTest.java
components/camel-sjms/src/test/java/org/apache/camel/component/sjms/SjmsEndpointConnectionSettingsTest.java
components/camel-sjms/src/test/java/org/apache/camel/component/sjms/SjmsEndpointTest.java
components/camel-sjms/src/test/java/org/apache/camel/component/sjms/SjmsSendDynamicAwareTest.java
components/camel-sjms/src/test/java/org/apache/camel/component/sjms/consumer/InOutConsumerTempQueueAsyncTest.java
components/camel-sjms/src/test/java/org/apache/camel/component/sjms/consumer/InOutConsumerTempQueueTest.java
components/camel-sjms/src/test/java/org/apache/camel/component/sjms/consumer/InOutSynchronousConsumerTest.java
components/camel-sjms/src/test/java/org/apache/camel/component/sjms/consumer/JmsPollingConsumerTest.java
components/camel-sjms/src/test/java/org/apache/camel/component/sjms/jms/DestinationNameParserTest.java
core/camel-api/src/main/java/org/apache/camel/spi/DumpRoutesStrategy.java
dsl/camel-cli-connector/src/main/java/org/apache/camel/cli/connector/LocalCliConnector.java
dsl/camel-componentdsl/src/generated/java/org/apache/camel/builder/component/dsl/Aws2S3ComponentBuilderFactory.java
dsl/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/dsl/AWS2S3EndpointBuilderFactory.java
parent/pom.xml
test-infra/camel-test-infra-rocketmq/src/test/java/org/apache/camel/test/infra/rocketmq/services/RocketMQServiceFactory.java

Upgrade AWS SDK v2 to version 2.20.130

---

parent/pom.xml

Upgrade Hazelcast to version 5.3.2

---

components/camel-bean/src/main/java/org/apache/camel/component/bean/AbstractBeanProcessor.java

This should provide better reports in profilers

(chores) camel-bean: break the process method

---

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/VersionHolder.java
core/camel-main/src/main/java/org/apache/camel/main/MainDurationEventNotifier.java
parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.131

---

parent/pom.xml

Upgrade Minio to version 8.5.5

---

components/camel-dhis2/camel-dhis2-component/src/main/java/org/apache/camel/component/dhis2/Dhis2Converters.java

Moved non-generated class to correct directory and finalised static reference

Moved non-generated class to correct directory

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.132

---

parent/pom.xml

Upgrade Jnats to version 2.16.14

---

parent/pom.xml

Upgrade FOP to version 2.9 and remove batik property placeholder

---

components/camel-olingo4/camel-olingo4-api/src/test/java/org/apache/camel/component/olingo4/Olingo4AppAPITest.java
components/camel-olingo4/camel-olingo4-component/src/test/java/org/apache/camel/component/olingo4/Olingo4ComponentProducerTest.java

I updated and re-enabled some tests in camel-olingo4 to reflect the namespace change in the olingo4 test server [1]
Thanks !
\[1\] https://github.com/OData/ODataSamples/commit/8f5c88e2b68853ccc29d03aae4a77e2b609104ca#diff-91abda81ad84851342abefa545baea5944112244f45271487ec6301b47ae38a2L349

Re-enable and fix some tests in camel-olingo4

---

parent/pom.xml

Upgrade Netty to version 4.1.97.Final

---

components/camel-sap-netweaver/src/main/docs/sap-netweaver-component.adoc

Camel-SAP-Netweaver: We are using different parameters to test and check

---

parent/pom.xml

Upgrade OWASP Maven Plugin to version 8.4.0

---

core/camel-core/src/test/java/org/apache/camel/support/PropertyBindingSupportTest.java
core/camel-support/src/main/java/org/apache/camel/support/PropertyBindingSupport.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/BeansDeserializer.java

Ctr mandatory

---

parent/pom.xml

Upgrade Ivy to version 2.5.2

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.135

---

core/camel-api/src/main/java/org/apache/camel/ValueHolder.java

(chores) camel-api: replace duplicated code

---

core/camel-support/src/main/java/org/apache/camel/support/ExchangeHelper.java

(chores) camel-api: cleanup setting the message history

---

core/camel-api/src/main/java/org/apache/camel/spi/ExtendedRoutesBuilderLoader.java
core/camel-api/src/main/java/org/apache/camel/spi/ModelineFactory.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultRoutesLoader.java
core/camel-main/src/main/java/org/apache/camel/main/RoutesConfigurer.java
dsl/camel-java-joor-dsl/src/main/java/org/apache/camel/dsl/java/joor/JavaJoorClassLoader.java
dsl/camel-java-joor-dsl/src/main/java/org/apache/camel/dsl/java/joor/JavaRoutesBuilderLoader.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/IntegrationLoaderDependenciesTest.groovy

Java dsl eager

---

core/camel-main/src/main/java/org/apache/camel/main/RoutesConfigurer.java
parent/pom.xml

Upgrade Snakeyaml engine to version 2.7

---

core/camel-xml-io/src/main/java/org/apache/camel/xml/in/BaseParser.java
core/camel-xml-jaxb/src/main/java/org/apache/camel/xml/jaxb/JaxbModelToXMLDumper.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/KameletMain.java
dsl/camel-xml-io-dsl/src/main/java/org/apache/camel/dsl/xml/io/XmlModelParser.java
dsl/camel-xml-io-dsl/src/main/java/org/apache/camel/dsl/xml/io/XmlRoutesBuilderLoader.java
dsl/camel-xml-io-dsl/src/test/java/org/apache/camel/dsl/xml/io/XmlSpringBeansLoadTest.java
dsl/camel-xml-io-dsl/src/test/resources/org/apache/camel/dsl/xml/io/springBeans.xml

Spring xml

---

components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/NoopTracingStrategy.java
components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/OpenTelemetryTracingStrategy.java
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/CamelOpenTelemetryTestSupport.java
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/OpenTelemetryTracingStrategyTest.java

…sors
Migrated https://github.com/apache/camel/pull/11213 for main branch

CAMEL-19776 for main(camel-4)

---

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/EntityParser.java
components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2ClientManagerIT.java

... when request's header dispositionNotificationTo isn't set
Added a unit test for this case. The existing tests are green

CAMEL-19731 AS2: Fixed null pointer exception 

---

components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/NoopTracingStrategy.java
components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/OpenTelemetryTracingStrategy.java
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/CamelOpenTelemetryTestSupport.java
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/OpenTelemetryTracingStrategyTest.java

…sors
Migrated https://github.com/apache/camel/pull/11213 for camel-4.0.x
We need it to not block migration to spring boot 3

CAMEL-19776 for camel-4.0.x

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/AbstractGenerateConfigurerMojo.java

Just an innocent cleanup because I want to check something on this code on Github

(chores) camel-package-maven-plugin: minor cleanup

---

test-infra/camel-test-infra-infinispan/src/test/java/org/apache/camel/test/infra/infinispan/common/InfinispanProperties.java
test-infra/camel-test-infra-infinispan/src/test/java/org/apache/camel/test/infra/infinispan/services/InfinispanLocalContainerService.java

In order to support usage of the camel-test-infra-infinispan with testcontainers + podman, we need to run container with network mode host according to [Infinispan doc](https://github.com/infinispan/infinispan-images#server)

CAMEL-19810: Infinispan container in network host mode

---

core/camel-xml-io/src/main/java/org/apache/camel/xml/in/BaseParser.java
parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.137

---

parent/pom.xml

Upgrade Spring Rabbit to version 3.0.8

---

parent/pom.xml

Upgrade RSSReader to version 3.4.6

---

parent/pom.xml

Upgrade Optaplanner to version 9.43.0.Final

---

components/camel-seda/src/main/java/org/apache/camel/component/seda/SedaEndpoint.java

This partially reverts the changes introduced on 23542fc5b65f33cde0f74f71876fe80d8c8c853f and b70584ddb3545a87acc1732f0e89b9cea704c461

CAMEL-19815: avoid using invalid QueueReferences

---

parent/pom.xml

Upgrade Tika to version 2.9.0

---

components/camel-openapi-java/src/main/java/org/apache/camel/openapi/RestOpenApiReader.java
components/camel-openapi-java/src/test/java/org/apache/camel/openapi/RestOpenApiReaderModelTest.java

This includes in arrays or other nested schema references.

CAMEL-19818: handle all schema references in response types.

---

components/camel-openapi-java/src/main/java/org/apache/camel/openapi/RestOpenApiReader.java
components/camel-openapi-java/src/test/java/org/apache/camel/openapi/RestOpenApiReaderModelTest.java

CAMEL-19818: handle all schema references in response types. (#11262)

---

parent/pom.xml

Upgrade Vertx to version 4.4.5

---

components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/stream/AWS2S3StreamUploadProducer.java
components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/utils/AWS2S3Utils.java
components/camel-aws/camel-aws2-s3/src/test/java/org/apache/camel/component/aws2/s3/integration/S3StreamUploadTimeoutIT.java
components/camel-mllp/src/main/java/org/apache/camel/component/mllp/MllpTcpClientProducer.java
components/camel-seda/src/main/java/org/apache/camel/component/seda/SedaEndpoint.java
parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.138

---

components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/NoopTracingStrategy.java
components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/OpenTelemetryTracingStrategy.java
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/CamelOpenTelemetryTestSupport.java
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/OpenTelemetryTracingStrategyTest.java

This task https://issues.apache.org/jira/browse/CAMEL-19776 was implemented for 3.22.0, 4.0.1, and 4.1.0 versions. 
But we need these changes to be released as soon as possible to unblock our migration from OpenTracing to OpenTelemetry.
Therefore, I created an additional PR for 3.21.x. I suppose this version should be released faster than others.

CAMEL-19776 for 3.21.x

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Init.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogKamelet.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/VersionHelper.java
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/run-custom-camel-version.tmpl
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/KameletMain.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/DependencyDownloaderKamelet.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/DependencyDownloaderRoutesLoader.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/KnownKameletRoutesBuilderLoader.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/util/VersionHelper.java

- Avoids inconsistent versions on camel-kamelets dependencies (e.g. camel-kamelets-utils library)
- Make sure to use same version for camel-kamelets and camel-kamelets-utils dependency
- Add --kamelets-version setting on Camel JBang run command
- Propagate camel-kamelets version to KameletMain as initial property and use this version in Kamelet dependency downloader
- Fallback to deriving the camel-kamelets version from classpath only if version has not been set
- Support camel-kamelets: prefix when referencing dependencies in Kamelets and Pipe/KameletBinding resources and resolve with proper camel-kamelets version

CAMEL-19798: Consistently set camel-kamelets version in Camel JBang

---

components/camel-azure/camel-azure-files/src/main/java/org/apache/camel/component/file/azure/FilesOperations.java

CAMEL-19822 fix
merge to Camel 4, please
- [ x] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes
for the component only

CAMEL-19822: must not ensure relative because target expects absolute

---

parent/pom.xml

Upgrade Fastjson to version 2.0.39

---

components/camel-azure/camel-azure-files/src/main/java/org/apache/camel/component/file/azure/FilesOperations.java
components/camel-dhis2/camel-dhis2-component/src/test/java/org/apache/camel/component/dhis2/Dhis2GetIT.java
components/camel-jpa/src/main/java/org/apache/camel/component/jpa/TransactionStrategy.java
core/camel-core/src/test/java/org/apache/camel/processor/ConvertBodyTest.java
parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.140

---

parent/pom.xml

Upgrade Caffeine to version 3.1.8

---

parent/pom.xml

Upgrade JT400 to version 20.0.2

---

parent/pom.xml
test-infra/camel-test-infra-pulsar/src/test/java/org/apache/camel/test/infra/pulsar/services/PulsarLocalContainerService.java

Upgrade Pulsar to version 3.1.0

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PrepareExampleMojo.java

Improve generation of README for camel-examples

---

parent/pom.xml
test-infra/camel-test-infra-azure-common/src/test/java/org/apache/camel/test/infra/azure/common/services/AzuriteContainer.java

CAMEL-19831 - Camel-Azure: Upgrade Azure SDK BOM to version 1.2.16

---

components/camel-twilio/src/generated/java/org/apache/camel/component/twilio/TwilioConverterLoader.java
components/camel-twilio/src/main/java/org/apache/camel/component/twilio/TwilioConverter.java
components/camel-twilio/src/test/java/org/apache/camel/component/twilio/TwilioEndpointTest.java

Issue: https://issues.apache.org/jira/browse/CAMEL-19828
Workaround solution, fixing behavior in the same was as was before.
JUnit test is included.

CAMEL-19828 - twilio - gneralization of Phone converter

---

components/camel-rocketmq/src/test/java/org/apache/camel/component/rocketmq/RocketMQRequestReplyRouteTest.java
components/camel-rocketmq/src/test/java/org/apache/camel/component/rocketmq/RocketMQRouteTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FileProducerCharsetUTFtoISOConvertBodyToTest.java
parent/pom.xml

CAMEL-19838 - Upgrade Debezium to version 2.0.33.Final

---

parent/pom.xml

Upgrade JGit to version 6.6.1.202309021850-r

---

parent/pom.xml

CAMEL-19841 - Upgrade Testcontainers to version 1.19.0

---

camel-dependencies/pom.xml
parent/pom.xml

Updating Kudu to 1.17.0 (#11323)

---

camel-dependencies/pom.xml
parent/pom.xml

CVE fixes, same reason as on main. I checked tests pass manually.

Updating Kudu to 1.17.0 (#11323) (#11324) (#11326)

---

components/camel-servicenow/camel-servicenow-maven-plugin/pom.xml
components/camel-servicenow/camel-servicenow-maven-plugin/src/test/java/org/apache/camel/maven/CamelServiceNowGenerateMojoTest.java

Camel-Servicenow: remove deprecated maven plugin artifacts

---

camel-dependencies/pom.xml
parent/pom.xml

Backmerge from main to fix https://avd.aquasec.com/nvd/2023/cve-2023-35887/

Upgrade sshd 2.10.0

---

camel-dependencies/pom.xml
parent/pom.xml

Backmerge to fix https://avd.aquasec.com/nvd/2023/cve-2023-35887/

Upgrade sshd 2.10.0 (#11338)

---

camel-dependencies/pom.xml
parent/pom.xml

Final backmerge to fix https://avd.aquasec.com/nvd/2023/cve-2023-35887/

Upgrade sshd 2.10.0 (#11338) (#11340)

---

components/camel-box/camel-box-component/src/test/java/org/apache/camel/component/box/BoxUsersManagerIT.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyRedeliveryTest.java
components/camel-undertow/src/test/java/org/apache/camel/component/undertow/UndertowHttp2Test.java
components/camel-zookeeper-master/src/test/java/org/apache/camel/component/zookeepermaster/group/GroupIT.java

* camel-box
* camel-zookeeper-master
* camel-netty
* camel-undertow

CAMEL-19770: cleanup remaining catches of Throwables in components

---

components/camel-bean/src/main/java/org/apache/camel/component/bean/BeanInfo.java
components/camel-openapi-java/src/main/java/org/apache/camel/openapi/OpenApiRestProducerFactory.java
components/camel-optaplanner/src/main/java/org/apache/camel/component/optaplanner/OptaPlannerProducer.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/SalesforceProducer.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/SalesforceSession.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/processor/QueryResultIterator.java
components/camel-zeebe/src/main/java/org/apache/camel/component/zeebe/processor/AbstractBaseProcessor.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportSpringBoot.java
dsl/camel-yaml-dsl/camel-yaml-dsl-common/src/main/java/org/apache/camel/dsl/yaml/common/YamlDeserializerSupport.java
dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/src/main/java/org/apache/camel/maven/dsl/yaml/GenerateYamlDeserializersMojo.java
tooling/camel-tooling-maven/src/main/java/org/apache/camel/tooling/maven/support/DIRegistry.java

- delete unused variables
- delete unused code

(chores) removed code

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointDslMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/UpdateSensitizeHelper.java

- delete unused variables
- delete unused code

(chores) camel-package-maven-plugin: removed unused code

---

components/camel-bindy/src/test/java/org/apache/camel/dataformat/bindy/fixed/link/BindyRaceConditionLinkTest.java
components/camel-openapi-java/src/main/java/org/apache/camel/openapi/OpenApiRestProducerFactory.java
components/camel-zeebe/src/main/java/org/apache/camel/component/zeebe/processor/AbstractBaseProcessor.java
core/camel-util/src/main/java/org/apache/camel/util/ObjectHelper.java
parent/pom.xml
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/UpdateSensitizeHelper.java

Upgrade AWS SDK v2 to version 2.20.144

---

components/camel-aws/camel-aws2-cw/src/test/java/org/apache/camel/component/aws2/cw/CwComponentConfigurationTest.java
components/camel-aws/camel-aws2-cw/src/test/java/org/apache/camel/component/aws2/cw/CwComponentRegistryClientTest.java
components/camel-aws/camel-aws2-cw/src/test/java/org/apache/camel/component/aws2/cw/CwComponentTest.java

Camel-AWS2-CW: Fixed tests after CAMEL-19833

---

components/camel-jcache/src/test/java/org/apache/camel/component/jcache/JCacheConfigurationTest.java

Camel-Jcache: Fixed tests after CAMEL-19833

---

pom.xml

CAMEL-19844 - Add SBOM to release

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.145

---

parent/pom.xml
test-infra/camel-test-infra-infinispan/src/test/java/org/apache/camel/test/infra/infinispan/services/InfinispanLocalContainerService.java

Upgrade Infinispan to version 14.0.17.Final

---

parent/pom.xml

Upgrade JsonApi to version 0.13

---

parent/pom.xml

Upgrade Jgroups to version 5.3.0.Final

---

camel-dependencies/pom.xml
parent/pom.xml

Backporting CVE fix for https://github.com/advisories/GHSA-v6w3-2prq-h95f

Updating Jakarta El to 3.0.4 (#11370)

---

dsl/camel-kotlin-dsl/src/main/kotlin/org/apache/camel/dsl/kotlin/KotlinCompilationConfiguration.kt

fix(dsl): Kotlin compiler options

---

camel-dependencies/pom.xml
parent/pom.xml

Backporting CVE fix for https://github.com/advisories/GHSA-v6w3-2prq-h95f

Updating Jakarta El to 3.0.4 (#11370) (#11371)

---

dsl/camel-kotlin-dsl/src/main/kotlin/org/apache/camel/dsl/kotlin/KotlinCompilationConfiguration.kt

[Backport] fix(dsl): Kotlin compiler options

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.146

---

parent/pom.xml

Upgrade Libphonenumber to version 8.13.20

---

Jenkinsfile.ppc64le

Revert back to label power9 on ppc64le

---

components/camel-debezium/camel-debezium-db2/src/main/docs/debezium-db2-component.adoc
components/camel-debezium/camel-debezium-mongodb/src/main/docs/debezium-mongodb-component.adoc
components/camel-debezium/camel-debezium-mysql/src/main/docs/debezium-mysql-component.adoc
components/camel-debezium/camel-debezium-oracle/src/main/docs/debezium-oracle-component.adoc
components/camel-debezium/camel-debezium-postgres/src/main/docs/debezium-postgres-component.adoc
components/camel-debezium/camel-debezium-sqlserver/src/main/docs/debezium-sqlserver-component.adoc

Fix spelling error in 4.1.x DEBEZIUM doc

Fix spelling error in 4.1.x DEBEZIUM doc

---

components/camel-cassandraql/pom.xml

Enable cassandra on ppc64le

---

components/camel-telegram/src/main/java/org/apache/camel/component/telegram/service/TelegramServiceRestBotAPIAdapter.java
components/camel-telegram/src/test/java/org/apache/camel/component/telegram/TelegramChatBotTest.java
pom.xml
tooling/maven/camel-api-component-maven-plugin/src/test/java/org/apache/camel/maven/AbstractGeneratorMojoTest.java

Upgrade Groovy to version 4.0.15

---

parent/pom.xml

Upgrade Classgraph to version 4.8.162

---

core/camel-util/src/main/java/org/apache/camel/util/FileUtil.java

The newer method Files#delete provides better error messages and we have a few components where it should be safe to replace. Check the [full list](https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS4042&id=apache_camel&open=AX4xQ6AE2wn0z3gD8Di1) for code that could be changed.

CAMEL-19493:cleanups: review and replace File#delete with Files#delete

---

Jenkinsfile.ppc64le

Use label as ppc64le

---

Jenkinsfile.ppc64le

Use label as power-for-camel

---

components/camel-jooq/pom.xml

Revert "CAMEL-19871: camel-jooq - Set the proper scope to all test dependencies"

---

components/camel-ldap/src/main/docs/ldap-component.adoc

Moved Spring-specific content into dedicated tabs, and added a equivalent tabs for Camel Quarkus.

Refactored LDAP docs

---

components/camel-spring-rabbitmq/src/main/java/org/apache/camel/component/springrabbit/DefaultMessagePropertiesConverter.java
components/camel-spring-rabbitmq/src/main/java/org/apache/camel/component/springrabbit/MessagePropertiesConverter.java
components/camel-spring-rabbitmq/src/main/java/org/apache/camel/component/springrabbit/SpringRabbitMQComponent.java

Backports #11404. Probably better to wait for the ASF CI build to complete before merging ...

Backport CAMEL-19859 to 4.0.x

---

components/camel-spring-ws/src/main/java/org/apache/camel/component/spring/ws/SpringWebserviceConfiguration.java
core/camel-core-catalog/src/main/java/org/apache/camel/catalog/impl/CatalogHelper.java
core/camel-util/src/main/java/org/apache/camel/util/FileUtil.java
dsl/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/dsl/SpringWebserviceEndpointBuilderFactory.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.149

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/health/KafkaConsumerHealthCheckIT.java

[CAMEL-19875]HealthCheck is broken for KafkaConsumer

---

.github/workflows/depsreview.yaml

Bump Action Checkout to v4 in deps review

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/health/KafkaConsumerHealthCheckIT.java

4.0.x camel 19875

---

dsl/camel-componentdsl/src/generated/java/org/apache/camel/builder/component/dsl/KafkaComponentBuilderFactory.java
parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.150

---

tests/camel-itest-jms2/src/test/java/org/apache/camel/itest/jms2/Jms2DeliveryDelayTest.java

Cleanup tests that are highly susceptible to flakiness as they verify the results based on duration.
Also, ensure they use the monotonic clock instead of the system clock to avoid the risk of going back in time in rare circumstances.

(chores) camel-jms: cleanup deliveryDelay tests

---

core/camel-base/src/main/java/org/apache/camel/impl/converter/ConverterStatistics.java
core/camel-base/src/main/java/org/apache/camel/impl/converter/CoreTypeConverterRegistry.java
core/camel-base/src/main/java/org/apache/camel/impl/converter/TypeConverterStatistics.java

Move the statistics code to separate classes and interfaces

CAMEL-19398: cleanup type statistics

---

parent/pom.xml

CAMEL-19884: Upgrade pooled-jms to 3.1.3

---

components/camel-consul/src/main/java/org/apache/camel/component/consul/cluster/ConsulClusterView.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cluster/ConsulClusteredRoutePolicyFactoryIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cluster/ConsulClusteredRoutePolicyIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cluster/ConsulMasterIT.java
components/camel-hdfs/src/main/java/org/apache/camel/component/hdfs/HdfsProducer.java
components/camel-infinispan/camel-infinispan-embedded/src/test/java/org/apache/camel/component/infinispan/embedded/cluster/AbstractInfinispanEmbeddedClusteredTest.java
components/camel-jgroups/src/test/java/org/apache/camel/component/jgroups/cluster/JGroupsLockMasterTest.java
components/camel-master/src/test/java/org/apache/camel/component/master/MasterComponentTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/UnsharableCodecsConflicts2Test.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/UnsharableCodecsConflictsTest.java
components/camel-zookeeper-master/src/main/java/org/apache/camel/component/zookeepermaster/group/internal/ZooKeeperGroup.java
components/camel-zookeeper/src/main/java/org/apache/camel/component/zookeeper/cloud/ZooKeeperServiceRegistry.java
components/camel-zookeeper/src/main/java/org/apache/camel/component/zookeeper/cluster/ZooKeeperClusterView.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/cluster/integration/ZooKeeperClusteredRoutePolicyFactoryIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/cluster/integration/ZooKeeperClusteredRoutePolicyIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/cluster/integration/ZooKeeperMasterIT.java
core/camel-core/src/test/java/org/apache/camel/component/file/cluster/FileLockClusteredRoutePolicyFactoryTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/cluster/FileLockClusteredRoutePolicyTest.java

Logging the exception message should provide better information when debugging or reading logs

(chores) do log exception messages

---

parent/pom.xml

Upgrade Spring-security to version 6.1.4

---

parent/pom.xml

Upgrade Spring Security to version 5.8.7

---

components/camel-stomp/src/test/java/org/apache/camel/component/stomp/StompConsumerTest.java
parent/pom.xml

Upgrade ActiveMQ Artemis 2.31.0

---

parent/pom.xml

Upgrade Google Cloud Functions BOM to version 2.26.0

---

parent/pom.xml

Upgrade Google Secretmanager BOM to version 2.24.0

---

core/camel-core/src/test/java/org/apache/camel/component/xslt/XsltFromHeaderOverrideEndpointUriTest.java
core/camel-util/src/main/java/org/apache/camel/util/ObjectHelper.java
parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.152

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/DependencyCopy.java

`camel dependency copy` command

CAMEL-19895 - Fix to respect absolute path for output directory for

---

Jenkinsfile.jdk21

Added a Jenkinsfile for building with JDK21

---

pom.xml

Fix jdk21 jenkins

---

parent/pom.xml

Upgrade Braintree Java to version 3.26.0

---

parent/pom.xml

Upgrade Jetty to version 11.0.16

---

parent/pom.xml

Upgrade commons-dbcp2 2.10.0

---

parent/pom.xml

Upgrade qpid broker 9.1.0

---

parent/pom.xml
test-infra/camel-test-infra-artemis/src/test/java/org/apache/camel/test/infra/artemis/services/ArtemisMQTTService.java
tooling/openapi-rest-dsl-generator/src/main/java/org/apache/camel/generator/openapi/RestDslSourceCodeGenerator.java

Upgrade Huawei Cloud Core SDK to version 3.1.60

---

parent/pom.xml

Upgrade Huawei Cloud OBS to version 3.23.5

---

parent/pom.xml

CAMEL-19903 - Upgrade Debezium to 2.3.4.Final

---

components/camel-http-common/src/main/java/org/apache/camel/http/common/DefaultHttpBinding.java
components/camel-servlet/src/test/java/org/apache/camel/component/servlet/MultipartUploadTest.java
components/camel-servlet/src/test/java/org/apache/camel/component/servlet/ServletCamelRouterTestSupport.java

https://issues.apache.org/jira/browse/CAMEL-19899

CAMEL-19899: Process attachments before reading the request body for HttpServletRequest

---

components/camel-jaxb/src/main/java/org/apache/camel/converter/jaxb/FallbackTypeConverter.java

Add debug message for missing JAXB XmlRootElement annotation

Add debug message for missing JAXB XmlRootElement annotation

---

core/camel-core/src/test/java/org/apache/camel/impl/StopTimeoutRouteTest.java
core/camel-core/src/test/java/org/apache/camel/impl/engine/CamelPostProcessorHelperSedaConsumePredicateTest.java
core/camel-core/src/test/java/org/apache/camel/processor/aggregator/AggregateLostGroupIssueTest.java

- CamelPostProcessorHelperSedaConsumePredicateTest

(chores) camel-core: disable flaky test on GitHub

---

Jenkinsfile.jdk17
Jenkinsfile.jdk21
Jenkinsfile.ppc64le
Jenkinsfile.s390x
tooling/maven/camel-package-maven-plugin/pom.xml
tooling/maven/camel-restdsl-openapi-plugin/pom.xml

(chores) tooling/maven: fixes 

---

docs/main/modules/contributing/pages/index.adoc

(chores) doc: minor adjustments to the contribution documentation

---

camel-dependencies/pom.xml
parent/pom.xml

CAMEL-19891: Upgrade CXF to 3.4.10

---

tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/SupportLevel.java
tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/JavadocHelper.java
tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/srcgen/GenericType.java
tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/srcgen/JavaClass.java
tooling/camel-util-json/src/main/java/org/apache/camel/util/json/Jsoner.java
tooling/maven/bom-generator-maven-plugin/src/main/java/org/apache/camel/maven/bom/generator/DependencyMatcher.java
tooling/maven/camel-api-component-maven-plugin/src/main/java/org/apache/camel/maven/HashHelper.java
tooling/maven/camel-api-component-maven-plugin/src/main/java/org/apache/camel/maven/JavaSourceParser.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/AbstractGenerateConfigurerMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointDslMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/ModelWriterGeneratorMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/ModelXmlParserGeneratorMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PackageDataFormatMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PackageLanguageMojo.java
tooling/openapi-rest-dsl-generator/src/main/java/org/apache/camel/generator/openapi/RestDefinitionEmitter.java

- use static inner classes
- use chained append calls
- remove unnecessary transient modifier
- remove unnecessary call to toString
- use simpler generics expressions
- use isEmpty instead of checking for length

(chores) tooling: use final when possible

---

test-infra/camel-test-infra-artemis/src/test/java/org/apache/camel/test/infra/artemis/services/ArtemisContainer.java
test-infra/camel-test-infra-dispatch-router/src/test/java/org/apache/camel/test/infra/dispatch/router/services/DispatchRouterContainer.java

(chores) camel-test-infra: upgrade Fedora image to 38

---

dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

backport of https://github.com/apache/camel/pull/11550

Update CamelJBang.java to 4.0.1

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd
core/camel-core-model/src/main/java/org/apache/camel/model/app/RegistryBeanDefinition.java
core/camel-xml-io/src/generated/java/org/apache/camel/xml/in/ModelParser.java
core/camel-xml-io/src/generated/java/org/apache/camel/xml/out/ModelWriter.java
core/camel-xml-io/src/main/java/org/apache/camel/xml/LwModelToXMLDumper.java
core/camel-xml-io/src/test/java/org/apache/camel/xml/in/ModelParserTest.java
core/camel-xml-io/src/test/resources/beansWithFactoryMethod.xml
core/camel-xml-jaxb/src/main/java/org/apache/camel/xml/jaxb/JaxbModelToXMLDumper.java
core/camel-yaml-io/src/generated/java/org/apache/camel/yaml/out/ModelWriter.java
core/camel-yaml-io/src/main/java/org/apache/camel/yaml/LwModelToYAMLDumper.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/xml/blueprint/BlueprintXmlBeansHandler.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/xml/spring/SpringXmlBeansHandler.java
dsl/camel-xml-io-dsl/src/main/docs/java-xml-io-dsl.adoc
dsl/camel-xml-io-dsl/src/main/java/org/apache/camel/dsl/xml/io/XmlRoutesBuilderLoader.java
dsl/camel-xml-io-dsl/src/test/java/org/apache/camel/dsl/xml/io/XmlLoadAppTest.java
dsl/camel-xml-io-dsl/src/test/java/org/apache/camel/dsl/xml/io/beans/MyFacBean.java
dsl/camel-xml-io-dsl/src/test/resources/org/apache/camel/dsl/xml/io/camel-app6.xml
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/ModelDeserializers.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/BeansDeserializer.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camelYamlDsl.json
dsl/camel-yaml-dsl/camel-yaml-dsl/src/main/docs/yaml-dsl.adoc
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/BeansTest.groovy
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/support/model/MyFacBean.groovy

CAMEL-19912: camel-core-model - Add factory-method parameter

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.154

---

components/camel-jaxb/src/main/java/org/apache/camel/converter/jaxb/FallbackTypeConverter.java
components/camel-jaxb/src/test/java/org/apache/camel/converter/jaxb/JAXBElementFallbackTypeConverterTest.java

There is no direct conversion from `JAXBElement<Type>` to `Type`:
`Caused by: org.apache.camel.InvalidPayloadException: No body available of type: org.apache.camel.converter.jaxb.person.Person but has type: jakarta.xml.bind.JAXBElement on: Message. Caused by: No type converter available to convert from type: jakarta.xml.bind.JAXBElement to the required type: org.apache.camel.converter.jaxb.person.Person. Exchange[]. Caused by: [org.apache.camel.NoTypeConversionAvailableException - No type converter available to convert from type: jakarta.xml.bind.JAXBElement to the required type: org.apache.camel.converter.jaxb.person.Person]`
This PR adds the required conversion to `FallbackTypeConverter`.

Add conversion from JAXBElement<X> to X

---

core/camel-base/src/main/java/org/apache/camel/impl/converter/AnnotationTypeConverterLoader.java
core/camel-core-engine/src/main/java/org/apache/camel/impl/DefaultModel.java
core/camel-management/src/main/java/org/apache/camel/management/mbean/ManagedExchangeFactoryManager.java
core/camel-support/src/main/java/org/apache/camel/support/jndi/JndiContext.java
core/camel-util/src/main/java/org/apache/camel/util/UnsafeUriCharactersEncoder.java
core/camel-xml-io/src/main/java/org/apache/camel/xml/in/BaseParser.java
core/camel-xml-jaxp/src/main/java/org/apache/camel/converter/jaxp/XmlConverter.java

(chores) camel-core: use final where possible

---

core/camel-management/src/test/java/org/apache/camel/management/ManagedThrottlerTest.java

(chores) camel-core: disable flaky test on GitHub Actions

---

parent/pom.xml

CAMEL-19920 - camel-mina - Upgrade to newer versions - version 2.2.3

---

parent/pom.xml

CAMEL-19920 - camel-mina - Upgrade to newer versions - version 2.1.8

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/serde/ToStringKafkaHeaderDeserializer.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/serde/ToStringKafkaHeaderDeserializerTest.java

[CAMEL-19919] camel-kafka: provided an out of the box byte[] to String header deserializer

---

core/camel-core-processor/src/main/java/org/apache/camel/processor/PausableProcessor.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/Throttler.java
core/camel-core-reifier/src/main/java/org/apache/camel/reifier/PausableReifier.java
core/camel-core/src/test/java/org/apache/camel/processor/IdempotentConsumerConcurrentTest.java
core/camel-core/src/test/java/org/apache/camel/processor/SplitterPojoTest.java
core/camel-core/src/test/java/org/apache/camel/processor/WireTapAbortPolicyTest.java
core/camel-management/src/main/java/org/apache/camel/management/mbean/ManagedStep.java

- use final when possible
- removed unused variable
- use java-style array declaration
- fixed malformed junit test

(chores) camel-core: code cleanups

---

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultComponentResolver.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultConfigurerResolver.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultPackageScanResourceResolver.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultSupervisingRouteController.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultUriFactoryResolver.java
core/camel-cloud/src/main/java/org/apache/camel/impl/cloud/DefaultServiceCallProcessor.java
core/camel-cloud/src/main/java/org/apache/camel/impl/cloud/ServiceCallProcessorFactory.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/Resequencer.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/RestBindingAdvice.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/SendDynamicAwareResolver.java
core/camel-core-reifier/src/main/java/org/apache/camel/reifier/rest/RestBindingReifier.java
core/camel-core-xml/src/main/java/org/apache/camel/core/xml/AbstractCamelContextFactoryBean.java
core/camel-main/src/main/java/org/apache/camel/main/BaseMainSupport.java

Removed unused exception declarations in private methods

(chores) camel-core: remove unused exceptions

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/serde/ToStringKafkaHeaderDeserializer.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/serde/ToStringKafkaHeaderDeserializerTest.java

[CAMEL-19919] camel-kafka: provided an out of the box byte[] to String header deserializer (#11562)

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.156

---

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_1.adoc

CAMEL-19921 - Added note in migration guide.

---

core/camel-xml-io/src/test/java/org/apache/camel/xml/in/ModelParserTest.java

Fix ModelParserTest on Windows

---

core/camel-core/src/test/java/org/apache/camel/impl/engine/DefaultPackageScanResourceResolverTest.java

Fix DefaultPackageScanResourceResolverTest on Windows

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelJBangMain.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/SBOMGenerator.java

CAMEL-19644 - camel-jbang - Add command to generate SBOM report

---

tooling/maven/sync-properties-maven-plugin/src/main/java/org/apache/camel/maven/sync/properties/SyncPropertiesMojo.java
tooling/maven/sync-properties-maven-plugin/src/main/resources/camel-dependencies-template.xml

Use correct property for the license plugin version.

CAMEL-19862: align Apache parent with Camel.

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.157

---

parent/pom.xml

Upgrade to CXF 4.0.3

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade to CXF 3.6.2

---

pom.xml

Upgrade license plugin 4.3

---

dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

CAMEL-19930 - Camel-Jbang: Upgrade to Camel-Kamelets 4.0.1

---

dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

CAMEL-19930 - Camel-Jbang: Upgrade to Camel-Kamelets 4.0.1 (#11610)

---

components/camel-slack/src/test/java/org/apache/camel/component/slack/SlackConsumerTest.java

- [] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).
This resolves this https://github.com/apache/camel/security/code-scanning/5608

Slack incoming webhook URLs should not be disclosed

---

parent/pom.xml

This PR upgrades Avro's version to 1.11.3 so that we can ensure the current code works with the latest version of Avro.
It doesn't need a JIRA issue since it's just a minor dependency upgrade.

Upgrade Avro to 1.11.3

---

parent/pom.xml

Upgrade JT400 to version 20.0.3

---

parent/pom.xml

Upgrade Commons Io to version 2.14.0

---

components/camel-json-validator/src/main/docs/json-validator-component.adoc

Camel-Json-Validator: Added the updated supported schemas

---

parent/pom.xml

Upgrade Commons Pool to version 2.12.0

---

core/camel-util/src/main/java/org/apache/camel/util/IOHelper.java
core/camel-xml-io/src/main/java/org/apache/camel/xml/in/BaseParser.java
core/camel-xml-io/src/main/java/org/apache/camel/xml/io/XmlPullParserLocationException.java
core/camel-xml-io/src/test/java/org/apache/camel/xml/in/ModelParserTest.java
core/camel-xml-io/src/test/resources/invalid/convertBodyParseError.xml

CAMEL-19936: camel-xml-io - Parsing error with line precise error

---

parent/pom.xml

CAMEL-19944 - Upgrade Azure SDK BOM to version 1.2.17

---

components/camel-saxon/src/test/resources/org/apache/camel/language/xpath/XPathLanguageDefaultSettingsTest.xml
components/camel-xpath/src/main/java/org/apache/camel/language/xpath/XPathLanguage.java

CAMEL-19918: camel-saxon - Using saxon=true does not work.

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.159

---

parent/pom.xml
test-infra/camel-test-infra-nats/src/test/java/org/apache/camel/test/infra/nats/services/NatsLocalContainerService.java

Upgrade JNats to version 2.17.0 and Nats container image to 2.10.1

---

pom.xml

License Maven Plugin: Remove deprecation and fixed configuration

---

parent/pom.xml

Upgrade Picocli to version 4.7.5

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.160

---

components/camel-dhis2/camel-dhis2-component/src/main/docs/dhis2-component.adoc

Correct DSL in DHIS2 component examples

docs: correct DSL examples

---

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc

Camel-JBang SBOM subcommand: Docs

---

components/camel-spring-main/src/test/java/org/apache/camel/spring/MainDummyTest.java
components/camel-spring-main/src/test/java/org/apache/camel/spring/MainExampleTest.java
components/camel-spring-main/src/test/java/org/apache/camel/spring/MainVetoTest.java
components/camel-spring-main/src/test/java/org/apache/camel/spring/MultipleCamelContextTest.java
components/camel-spring-main/src/test/java/org/apache/camel/spring/SpringMainStartFailedIssueTest.java

CAMEL-19555: added assertions to the camel-spring-main tests

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.161

---

parent/pom.xml

CAMEL-19638 : Mockito core version update

---

.mvn/wrapper/maven-wrapper.properties

Upgrade to maven wrapper 3.9.5

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.162

---

components/camel-plc4x/pom.xml
components/camel-plc4x/src/main/java/org/apache/camel/component/plc4x/Plc4XConsumer.java
components/camel-plc4x/src/main/java/org/apache/camel/component/plc4x/Plc4XEndpoint.java
components/camel-plc4x/src/main/java/org/apache/camel/component/plc4x/Plc4XPollingConsumer.java
components/camel-plc4x/src/main/java/org/apache/camel/component/plc4x/Plc4XProducer.java
parent/pom.xml

CAMEL-19965 - Camel-Plc4x: Upgrade to 0.11.0

---

parent/pom.xml

CAMEL-19966 - Upgrade Testcontainers to version 1.19.1

---

components/camel-pgevent/src/test/java/org/apache/camel/pgevent/PgEventConsumerTest.java
components/camel-pgevent/src/test/java/org/apache/camel/pgevent/PgEventProducerTest.java

Tests: Fix mockito tests for Camel-PgEvent

---

parent/pom.xml

Upgrade Box Java SDK to version 4.6.0

---

parent/pom.xml

Upgrade Minio to version 8.5.6

---

parent/pom.xml

Upgrade Spring Rabbit to version 3.0.9

---

parent/pom.xml

Upgrade Netty to version 4.1.100.Final

---

parent/pom.xml

Upgrade Vertx to version 4.4.6

---

parent/pom.xml

Upgrade Vertx to version 4.4.6 (#11692)

---

parent/pom.xml
test-infra/camel-test-infra-infinispan/src/test/java/org/apache/camel/test/infra/infinispan/services/InfinispanLocalContainerService.java

Upgrade Infinispan and related container image to version 14.0.18.Final

---

parent/pom.xml

Upgrade jetty to 11.0.17

---

parent/pom.xml
test-infra/camel-test-infra-zookeeper/src/test/java/org/apache/camel/test/infra/zookeeper/services/ZooKeeperContainer.java

Upgrade to zookeeper 3.9.1

---

parent/pom.xml

Upgrade Jackrabbit to version 2.21.20

---

parent/pom.xml

Upgrade Jetty to version 9.4.53.v20231009

---

components/camel-ldap/src/main/docs/ldap-component.adoc

Moved Spring-specific content into dedicated tabs, and added a equivalent tabs for Camel Quarkus.
This is a cherry-pick of https://github.com/apache/camel/pull/11420.

Refactored LDAP docs - backport from main to camel-4.0.x branch

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.21.0

---

parent/pom.xml

Upgrade Spring to version 6.0.13

---

parent/pom.xml

Upgrade micrometer 1.11.5 and tracing 1.1.6

---

parent/pom.xml

Upgrade undertow 2.3.9

---

catalog/camel-report-maven-plugin/pom.xml
components/camel-box/camel-box-component/pom.xml
parent/pom.xml

Upgrade to Mockito 5.6.0

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd
components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/OpenTelemetryTracingStrategy.java

CAMEL-19968: The Tracing Strategy is failing when using pollEnrich

---

parent/pom.xml
test-infra/camel-test-infra-infinispan/src/test/java/org/apache/camel/test/infra/infinispan/services/InfinispanLocalContainerService.java

Upgrade Infinispan to version 14.0.19.Final

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.21.1

---

components/camel-kubernetes/src/generated/java/io/fabric8/kubernetes/client/ConfigFluentImplConfigurer.java
parent/pom.xml

Upgrade Kubernetes Client to version 6.9.0

---

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultCamelContextExtension.java

- cleanup type converter APIs
- cleanup type converter registry APIs

CAMEL-19998: move more private APIs to the Extension

---

parent/pom.xml

Upgrade undertow 2.3.10

---

parent/pom.xml

Upgrade to log4j 2.21.0

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.21.2

---

parent/pom.xml

CAMEL-20003 - Upgrade Google Cloud BOM to version 26.25.0

---

parent/pom.xml

CAMEL-20005 - Upgrade Google Secrets Manager BOM to version 2.28.0

---

components/camel-stax/src/main/java/org/apache/camel/component/stax/StAXProcessor.java

Javadoc explanation:
```
Deprecated.
This method propagates any exception thrown by the nullary constructor,
including a checked exception. Use of this method effectively bypasses
the compile-time exception checking that would otherwise be performed by
the compiler. The Constructor.newInstance method avoids this problem by
wrapping any exception thrown by the constructor in a (checked)
InvocationTargetException.
The call
clazz.newInstance()
can be replaced by
clazz.getDeclaredConstructor().newInstance()
The latter sequence of calls is inferred to be able to throw the
additional exception types InvocationTargetException and
NoSuchMethodException. Both of these exception types are subclasses of
ReflectiveOperationException.
```

Remove deprecated Class.newInstance usage in StaxProcessor

---

parent/pom.xml

CAMEL-20006 - Upgrade Google Cloud Functions BOM to version 2.30.0

---

components/camel-disruptor/src/main/java/org/apache/camel/component/disruptor/DisruptorConsumer.java
components/camel-disruptor/src/main/java/org/apache/camel/component/disruptor/DisruptorProducer.java

This should help profilers to provide better reports and help JVM to inline methods when possible

(chores) camel-disruptor: reduce method size

---

parent/pom.xml

Upgrade spring-security to align with spring-boot 3.1.5

Upgrade spring-security to align with spring-boot 3.1.5

---

parent/pom.xml

Upgrade SSHD to version 2.11.0

---

components/camel-stax/src/test/java/org/apache/camel/language/xtokenizer/XMLTokenExpressionIteratorGroupingTest.java
components/camel-stax/src/test/java/org/apache/camel/language/xtokenizer/XMLTokenizeExpressionIteratorWModeTest.java
components/camel-stax/src/test/java/org/apache/camel/language/xtokenizer/XMLTokenizeLanguageGroupingTest.java
components/camel-stax/src/test/java/org/apache/camel/language/xtokenizer/XMLTokenizeLanguageStreamingFileTest.java
components/camel-stax/src/test/java/org/apache/camel/language/xtokenizer/XMLTokenizeLanguageTest.java
components/camel-stax/src/test/java/org/apache/camel/language/xtokenizer/XMLTokenizeWrapLanguageGroupingTest.java
components/camel-stax/src/test/java/org/apache/camel/language/xtokenizer/XMLTokenizeWrapLanguageTest.java

Yes its not as pretty as Aureliens PRs but this does not affect camel-mock or any other library.
There are JIRAs for looking at better APIs on camel-mock but in more general and wider perspective.

CAMEL-20008 - Improve assertion to compare xml (java 21 fix)

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade undertow to 2.2.28.Final on camel-3.x

Upgrade undertow to 2.2.28.Final

---

parent/pom.xml

Sshd 2.11.0 4.0.x

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.21.5

---

parent/pom.xml

Upgrade Santuario XMLSec to version 2.2.6

---

parent/pom.xml

Upgrade Spring Rabbit to version 3.0.10

---

parent/pom.xml

Upgrade Spring Rabbitmq to version 3.0.10

---

dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/ModelDeserializers.java
dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/src/main/java/org/apache/camel/maven/dsl/yaml/GenerateYamlDeserializersMojo.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camelYamlDsl.json

CAMEL-20032: camel-yaml-dsl - Choice should not have steps in schema

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.21.6

---

dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camel-yaml-dsl.json

chore: regen YAML schema file

---

core/camel-core-languages/src/main/java/org/apache/camel/language/simple/ast/BinaryExpression.java
core/camel-support/src/main/java/org/apache/camel/support/ObjectHelper.java
core/camel-util/src/main/java/org/apache/camel/util/ObjectHelper.java

This should help inlining and provide better profiling information

(chores) camel-core: reduce method size

---

components/camel-micrometer/src/main/docs/micrometer-component.adoc

fixes https://issues.apache.org/jira/browse/CAMEL-20043
Minor change in the doc. Adds explanation where to find information about using thread pool factory.

Micrometer threadPoolFactory doc configuration change

---

dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/CustomResolver.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/SetPropertyTest.groovy

Backporting CAMEL-20022 / https://github.com/apache/camel/pull/11823 to 4.0.x branch.
Also see: CAMEL-20018
https://issues.apache.org/jira/browse/CAMEL-20022

4.0.x backport: CAMEL-20022: camel-yaml-dsl: Add WARN log if kebab-case is detected

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.21.7

---

parent/pom.xml

Upgrade Hazelcast to version 5.3.5

---

components/camel-aws/camel-aws2-ec2/pom.xml
components/camel-aws/camel-aws2-ec2/src/generated/resources/META-INF/services/org/apache/camel/component.properties

CAMEL-19973 - Camel-AWS components: Revisit description - EC2 component

---

components/camel-aws/camel-aws2-ecs/pom.xml
components/camel-aws/camel-aws2-ecs/src/generated/resources/META-INF/services/org/apache/camel/component.properties

CAMEL-19973 - Camel-AWS components: Revisit description - ECS Component

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.21.8

---

parent/pom.xml

CAMEL-20049: camel-activemq - Upgrade to latest releases

---

components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpConsumer.java
components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpSupport.java
core/camel-support/src/main/java/org/apache/camel/support/DefaultHeaderFilterStrategy.java
core/camel-support/src/main/java/org/apache/camel/support/ObjectHelper.java

This should help obtain better information when profiling the code

(chores) camel-platform-http-vertx: break large methods

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java

Fix typo for name of Maven settings.xml file

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.21.10

---

parent/pom.xml

Upgrade Tika to version 2.9.1

---

parent/pom.xml

Upgrade Commons Io to version 2.15.0

---

parent/pom.xml

Upgrade Commons Text to version 1.11.0

---

core/camel-support/src/main/java/org/apache/camel/support/ObjectHelper.java

This prioritizes faster type checks for most common and/or simple types whenever possible/safe to do so

(chores) core: use faster type checks when possible

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.21.11

---

pom.xml

Upgrade CycloneDX Maven Plugin to version 2.7.10

---

components/camel-azure/camel-azure-storage-blob/src/main/docs/azure-storage-blob-component.adoc

CAMEL-20060 - Add Azure SAS support for azure blob storage - Docs

---

dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

CAMEL-20063 - camel-jbang - Upgrade to kamelets 4.1.0

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.21.13

---

parent/pom.xml

Upgrade Flink to version 1.18.0

---

parent/pom.xml

CAMEL-20069 - Upgrade Azure SDK BOM to version 1.2.18

---

test-infra/camel-test-infra-azure-common/src/test/java/org/apache/camel/test/infra/azure/common/services/AzuriteContainer.java

Upgrade Azurite container image to version 3.27.0

---

dsl/camel-jbang/camel-jbang-container/Dockerfile

Upgrade Camel version in Camel JBang docker file to 4.1.0

---

parent/pom.xml

CAMEL-20072 - Upgrade Google Cloud BOM to version 26.26.0

---

parent/pom.xml

CAMEL-20073 - Bump google-cloud-functions-bom to version 2.31.0

---

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc

Fix typo in doc for Maven settings.xml

---

parent/pom.xml

CAMEL-20074 - Bump google-cloud-secretmanager-bom to version 2.29.0

---

parent/pom.xml

CAMEL-20075 - camel-kubernetes - upgrade to 6.9.2

---

parent/pom.xml

Upgrade Graal JS to version 23.0.2

---

components/camel-dhis2/camel-dhis2-component/src/generated/java/org/apache/camel/component/dhis2/Dhis2Converters.java
components/camel-dhis2/camel-dhis2-component/src/main/docs/dhis2-component.adoc
components/camel-dhis2/camel-dhis2-component/src/test/java/org/apache/camel/component/dhis2/Dhis2GetIT.java

Backport doc corrections and other minor changes from main branch

chore: backport doc corrections and other minor changes from main branch

---

parent/pom.xml
test-infra/camel-test-infra-pulsar/src/test/java/org/apache/camel/test/infra/pulsar/services/PulsarLocalContainerService.java

This PR upgrades Pulsar to v3.1.1 so that we can ensure the existing code works with the latest version of Pulsar.
No corresponding JIRA issue since it only introduces patch version upgrade to Pulsar.

Upgrade Pulsar to version 3.1.1

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.21.15

---

parent/pom.xml
test-infra/camel-test-infra-nats/src/test/java/org/apache/camel/test/infra/nats/services/NatsLocalContainerService.java
test-infra/camel-test-infra-smb/pom.xml
test-infra/camel-test-infra-smb/src/test/java/org/apache/camel/test/infra/smb/services/SmbContainer.java
test-infra/camel-test-infra-smb/src/test/java/org/apache/camel/test/infra/smb/services/SmbService.java
test-infra/camel-test-infra-smb/src/test/resources/org/apache/camel/test/infra/smb/services/smb.conf

Upgrade JNats to version 2.17.1 and related container to 2.10.4

---

parent/pom.xml

Upgrade SMBJ to version 0.12.2

---

parent/pom.xml

Upgrade Lucene to version 9.8.0

---

parent/pom.xml

Upgrade Optaplanner to version 9.44.0.Final

---

parent/pom.xml

Upgrade Jetty to version 11.0.18

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.21.16

---

parent/pom.xml
test-infra/camel-test-infra-elasticsearch/src/test/java/org/apache/camel/test/infra/elasticsearch/services/ElasticSearchLocalContainerService.java

Upgrade Elasticsearch and related container image to version 2.10.4

---

docs/user-manual/modules/ROOT/pages/camel-component-maven-plugin.adoc
docs/user-manual/modules/faq/pages/how-do-i-disable-jmx.adoc

Move some bits of Documentation from 'in Camel 3.x' to since 'Camel 3.x'

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.21.17

---

test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSContainer.java

Upgrade Localstack Container Image to version 2.3.2

---

parent/pom.xml

Upgrade Pubnub-gson to version 6.4.1

---

docs/user-manual/modules/ROOT/pages/spring.adoc

Fixed typo in Spring support docs

Fixed typo in Spring support docs

---

components/camel-snakeyaml/src/main/java/org/apache/camel/component/snakeyaml/SnakeYAMLDataFormat.java
parent/pom.xml
tooling/maven/camel-restdsl-openapi-plugin/src/main/java/org/apache/camel/maven/generator/openapi/AbstractGenerateMojo.java

Upgrade SnakeYAML to 2.1

---

parent/pom.xml

Upgrade Hazelcast to version 5.3.6

---

components/camel-hazelcast/pom.xml

Fix Validation for Maven Surefire Plugin in Camel-hazelcast component

---

parent/pom.xml
test-infra/camel-test-infra-infinispan/src/test/java/org/apache/camel/test/infra/infinispan/services/InfinispanLocalContainerService.java

Upgrade Infinispan to version 14.0.20.Final

---

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_2.adoc

This pull request is a simple update to the 4.2 upgrade doc to notify users of the changes in the dynamic router eip component.

CAMEL-20081: Added an entry for Dynamic Router EIP changes to the 4.2 upgrade doc.

---

parent/pom.xml

Upgrade Minio to version 8.5.7

---

tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/PackageHelper.java
tooling/maven/camel-eip-documentation-enricher-maven-plugin/src/main/java/org/apache/camel/maven/EipDocumentationEnricherMojo.java

CAMEL-20094: camel-catalog: camel-spring.xsd keeps being regenerated.

---

components/camel-spring-redis/src/test/java/org/apache/camel/component/redis/RedisRemoveEndpointTest.java
components/camel-spring-redis/src/test/java/org/apache/camel/component/redis/RedisRemoveRouteTest.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java
core/camel-core/src/test/java/org/apache/camel/impl/DefaultEndpointRegistryTest.java

Remove endpoint

---

parent/pom.xml

Upgrade Olingo4 to version 4.10.0

---

parent/pom.xml

Upgrade GraphQL Java to version 21.3

---

components/camel-aws/camel-aws2-eks/pom.xml
components/camel-aws/camel-aws2-eks/src/generated/resources/META-INF/services/org/apache/camel/component.properties

CAMEL-19973 - Camel-AWS components: Revisit description - EKS Component

---

components/camel-aws/camel-aws2-iam/pom.xml
components/camel-aws/camel-aws2-iam/src/generated/resources/META-INF/services/org/apache/camel/component.properties

CAMEL-19973 - Camel-AWS components: Revisit description - IAM Component

---

components/camel-box/camel-box-api/pom.xml
components/camel-box/camel-box-component/pom.xml
parent/pom.xml

Upgrade Box Java SDK to version 4.6.1

---

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_2.adoc

relates to https://github.com/apache/camel/commit/a7c819007682fb7ba96777f1c980b58ba839fd11 and https://github.com/apache/camel/commit/0c925cdc52712d0314bc51a0830aeb13f5f4d368

Update Migration guide to 4.2 related to BacklogDebugger class removal

---

core/camel-base-engine/src/main/java/org/apache/camel/impl/debugger/DefaultBacklogDebugger.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultChannel.java
core/camel-console/src/main/java/org/apache/camel/impl/console/DebugDevConsole.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Debug.java

Kamelet debug

---

dsl/camel-jbang/camel-jbang-container/Dockerfile
dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

Upgrade default version for Camel in Camel JBang to 4.2.0

---

components/camel-kafka/src/main/docs/kafka-component.adoc
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConfiguration.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/AbstractCommitManager.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/KafkaRecordProcessor.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/KafkaRecordProcessorFacade.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/ProcessingResult.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorOffUsingKafkaManualCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorReplayOldMessagesIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorSeekIssueIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorWithBatchUsingAsynchCommitManagerIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorWithBatchUsingKafkaManualCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorWithBatchUsingKafkaManualCommitRetryIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorWithBatchUsingSynchCommitManagerIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/testutil/CamelKafkaUtil.java
docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_21.adoc

Backport BreakOnFirstError fix to 3.x
camel-3.x
CAMEL-20044

CAMEL-20044 Backport BreakOnFirstError fix to 3.x

---

components/camel-tarfile/src/main/java/org/apache/camel/processor/aggregate/tarfile/TarAggregationStrategy.java
parent/pom.xml

Upgrade Commons-compress to version 1.25.0

---

components/camel-jsonb/pom.xml
parent/pom.xml

CAMEL-20117 - Johnzon-jsonb: Update to 2.0.0

---

catalog/camel-route-parser/src/main/java/org/apache/camel/parser/RestDslParser.java
catalog/camel-route-parser/src/main/java/org/apache/camel/parser/RouteBuilderParser.java

CAMEL-20093: cleaned up duplicated code in camel-route-parser

---

parent/pom.xml

Upgrade Shiro to version 1.13.0 and regen

---

parent/pom.xml

Upgrade smallrye stuff

---

parent/pom.xml

Upgrade to jackson 2.15.3

---

test-infra/camel-test-infra-consul/src/test/java/org/apache/camel/test/infra/consul/services/ConsulLocalContainerService.java

Updates the container to 1.15.4

(chores) camel-test-infra-consul: update Consul container to the latest version

---

test-infra/camel-test-infra-hashicorp-vault/src/test/java/org/apache/camel/test/infra/hashicorp/vault/services/HashicorpVaultLocalContainerService.java

Updates the container to 1.15.2

(chores) camel-test-infra-hashicorp-vault: update container to the latest version

---

test-infra/camel-test-infra-mosquitto/src/test/java/org/apache/camel/test/infra/mosquitto/services/MosquittoLocalContainerService.java

Updates the container to 2.0.18

(chores) camel-test-infra-mosquitto: update container to the latest version

---

test-infra/camel-test-infra-nats/src/test/java/org/apache/camel/test/infra/nats/services/NatsLocalContainerService.java

Updates the container to 2.10.5

(chores) camel-test-infra-nats: update container to the latest version

---

test-infra/camel-test-infra-microprofile-lra/src/test/java/org/apache/camel/test/infra/microprofile/lra/services/MicroprofileLRALocalContainerService.java

Updates the container to 5.13.1.Final-2.16.6.Final

(chores) camel-test-infra-microprofile-lra: update container to the latest version

---

test-infra/camel-test-infra-postgres/src/test/java/org/apache/camel/test/infra/postgres/services/PostgresLocalContainerService.java

Updates the container to 13.13

(chores) camel-test-postgres: update container to the latest version

---

test-infra/camel-test-infra-rabbitmq/src/test/java/org/apache/camel/test/infra/rabbitmq/services/RabbitMQLocalContainerService.java

(chores) camel-test-rabbitmq: update container to the latest version

---

test-infra/camel-test-infra-smb/src/test/java/org/apache/camel/test/infra/smb/services/SmbServiceFactory.java

(chores) camel-test-infra-smb: fixed invalid test service name

---

core/camel-core-languages/src/main/docs/modules/languages/pages/csimple-language.adoc
core/camel-core-languages/src/main/docs/modules/languages/pages/simple-language.adoc
core/camel-core-languages/src/main/java/org/apache/camel/language/csimple/CSimpleHelper.java
core/camel-core-languages/src/main/java/org/apache/camel/language/simple/SimpleExpressionBuilder.java
core/camel-core-languages/src/main/java/org/apache/camel/language/simple/ast/SimpleFunctionExpression.java
core/camel-core/src/test/java/org/apache/camel/language/simple/MyAttachmentMessage.java
core/camel-core/src/test/java/org/apache/camel/language/simple/SimpleTest.java
core/camel-support/src/main/java/org/apache/camel/support/builder/ExpressionBuilder.java

CAMEL-20127: Add messageAs function to simple language

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogDoc.java
dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

Update default kamelet catalog to 4.2.0 in Camel JBang

---

components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/transform/AWS2SQSCloudEventDataTypeTransformer.java
test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSContainer.java

CAMEL-20129 - Upgrade Localstack to version 3.0.0

---

parent/pom.xml

Upgrade Reactor Netty to version 1.13

---

parent/pom.xml
test-infra/camel-test-infra-rocketmq/src/test/java/org/apache/camel/test/infra/rocketmq/services/RocketMQContainer.java

Updates the container to 5.1.4

(chores) camel-test-rocketmq: update container to the latest version

---

parent/pom.xml

Upgrade Google Cloud Function BOM to version 2.32.0

---

docs/eips-nav.adoc.template
docs/gulpfile.js

CAMEL-20135: regenerate nav.adoc for the eips

---

components/camel-http/pom.xml

fixes https://issues.apache.org/jira/browse/CAMEL-20142

CAMEL-20142 Camel-http: brings transitively 2 core versions

---

parent/pom.xml

Upgrade AWS SDK to version 2.21.28

---

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java
core/camel-core-model/src/main/java/org/apache/camel/model/ProcessorDefinition.java
core/camel-core-model/src/main/java/org/apache/camel/model/RouteDefinition.java
core/camel-core/src/test/java/org/apache/camel/util/DumpModelAsXmlSourceLocationStandbyTest.java

CAMEL-20136: Enable source location if debug or tracing in standby mode

---

components/camel-aws/camel-aws2-kms/pom.xml
components/camel-aws/camel-aws2-kms/src/generated/resources/META-INF/services/org/apache/camel/component.properties

CAMEL-19973 - Camel-AWS components: Revisit description - KMS Component

---

parent/pom.xml

Upgrade Owasp Maven Plugin to version 9.0.0

---

components/camel-aws/camel-aws2-mq/pom.xml
components/camel-aws/camel-aws2-mq/src/generated/resources/META-INF/services/org/apache/camel/component.properties

CAMEL-19973 - Camel-AWS components: Revisit description - MQ Component

---

components/camel-aws/camel-aws2-msk/pom.xml
components/camel-aws/camel-aws2-msk/src/generated/resources/META-INF/services/org/apache/camel/component.properties

CAMEL-19973 - Camel-AWS components: Revisit description - MSK Component

---

components/camel-aws/camel-aws2-redshift/pom.xml
components/camel-aws/camel-aws2-redshift/src/generated/resources/META-INF/services/org/apache/camel/component.properties

CAMEL-19973 - Camel-AWS components: Revisit description - Redshift Component

---

components/camel-aws/camel-aws2-s3/pom.xml
components/camel-aws/camel-aws2-s3/src/generated/resources/META-INF/services/org/apache/camel/component.properties

CAMEL-19973 - Camel-AWS components: Revisit description - S3 Component

---

components/camel-aws/camel-aws2-ses/pom.xml
components/camel-aws/camel-aws2-ses/src/generated/resources/META-INF/services/org/apache/camel/component.properties

CAMEL-19973 - Camel-AWS components: Revisit description - SES Component

---

components/camel-aws/camel-aws2-sns/pom.xml
components/camel-aws/camel-aws2-sns/src/generated/resources/META-INF/services/org/apache/camel/component.properties

CAMEL-19973 - Camel-AWS components: Revisit description - SNS Component

---

components/camel-aws/camel-aws2-sqs/pom.xml
components/camel-aws/camel-aws2-sqs/src/generated/resources/META-INF/services/org/apache/camel/component.properties

CAMEL-19973 - Camel-AWS components: Revisit description - SQS Component

---

components/camel-aws/camel-aws2-sts/pom.xml
components/camel-aws/camel-aws2-sts/src/generated/resources/META-INF/services/org/apache/camel/component.properties

CAMEL-19973 - Camel-AWS components: Revisit description - STS Component

---

test-infra/camel-test-infra-infinispan/src/test/java/org/apache/camel/test/infra/infinispan/services/InfinispanLocalContainerService.java

Upgrade Infinispan Container Image to 14.0.21.Final

---

parent/pom.xml

Upgrade Braintree Java to version 3.29.0

---

parent/pom.xml

Upgrade Spring Vault to version 3.1.0

---

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_3.adoc
docs/user-manual/modules/ROOT/pages/camel-jbang.adoc
dsl/camel-cli-connector/src/main/java/org/apache/camel/cli/connector/LocalCliConnector.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelJBangMain.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/TransformCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/TransformRoute.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/TransformMessageAction.java

Transform message command

---

core/camel-api/src/main/java/org/apache/camel/NamedNode.java
core/camel-api/src/main/java/org/apache/camel/NamedRoute.java
core/camel-api/src/main/java/org/apache/camel/Route.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultRoute.java
core/camel-console/src/main/java/org/apache/camel/impl/console/RouteDevConsole.java
core/camel-core-engine/src/main/java/org/apache/camel/impl/DefaultModel.java
core/camel-core-model/src/main/java/org/apache/camel/model/OptionalIdentifiedDefinition.java
core/camel-core-reifier/src/main/java/org/apache/camel/reifier/RouteReifier.java
core/camel-management-api/src/main/java/org/apache/camel/api/management/mbean/ManagedProcessorMBean.java
core/camel-management-api/src/main/java/org/apache/camel/api/management/mbean/ManagedRouteMBean.java
core/camel-management/src/main/java/org/apache/camel/management/DefaultManagementObjectNameStrategy.java
core/camel-management/src/main/java/org/apache/camel/management/mbean/ManagedProcessor.java
core/camel-management/src/main/java/org/apache/camel/management/mbean/ManagedRoute.java
core/camel-management/src/test/java/org/apache/camel/management/ManagedRouteNodePrefixIdTest.java
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_3.adoc
dsl/camel-componentdsl/src/generated/java/org/apache/camel/builder/component/ComponentsBuilderFactory.java
dsl/camel-componentdsl/src/generated/java/org/apache/camel/builder/component/dsl/SmbComponentBuilderFactory.java
dsl/camel-componentdsl/src/generated/resources/metadata.json
dsl/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/StaticEndpointBuilders.java
dsl/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/dsl/SmbEndpointBuilderFactory.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/CamelProcessorStatus.java

Node prefix

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.21.31

---

components/camel-aws/camel-aws-config/src/main/docs/aws-config-component.adoc

Camel-AWS-Config: Added SB Starter docs

---

components/camel-aws/camel-aws-cloudtrail/src/main/docs/aws-cloudtrail-component.adoc

Camel-AWS-Cloudtrail: Added SB Starter docs

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Debug.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/MessageTableHelper.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/CamelCommandHelper.java

camel-jbang - Add --output option to debug command.

---

components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpSupport.java
parent/pom.xml

Align with the Vert.x version forced on Camel Quarkus.

Downgrade Vert.x to 4.4.6

---

components/camel-aws/camel-aws-config/pom.xml
components/camel-aws/camel-aws-config/src/test/java/org/apache/camel/component/aws/config/integration/AWSConfigBase.java
components/camel-aws/camel-aws-config/src/test/java/org/apache/camel/component/aws/config/integration/AWSConfigProducerIT.java
test-infra/camel-test-infra-aws-v2/pom.xml
test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/clients/AWSSDKClientUtils.java
test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSConfigLocalContainerService.java
test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSServiceFactory.java

CAMEL-20159 - Camel-AWS-Config: Add Test-infra module

---

components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Console.java

AWS S3 Console more fields for consumers

---

core/camel-console/src/main/java/org/apache/camel/impl/console/ConsumerDevConsole.java
core/camel-console/src/main/java/org/apache/camel/impl/console/ContextDevConsole.java
core/camel-console/src/main/java/org/apache/camel/impl/console/RouteDevConsole.java
core/camel-management-api/src/main/java/org/apache/camel/api/management/mbean/ManagedPerformanceCounterMBean.java
core/camel-management/src/main/java/org/apache/camel/management/mbean/ManagedPerformanceCounter.java

CAMEL-20179: camel-core - Add idleSince attribute to JMX

---

parent/pom.xml

Upgrade jsch 0.2.13

---

components/camel-http/src/test/java/org/apache/camel/component/http/HttpNoConnectionTest.java

Disable a test causing trouble on PR #12208. I have seen it flaky on other changes as well.

CAMEL-19991: disabled flaky test on GitHub Actions

---

parent/pom.xml

Upgrade Lucene to version 9.9.0

---

components/camel-kubernetes/src/main/docs/kubernetes-cronjob-component.adoc

Added Kubernetes Cronjob component SB docs

---

parent/pom.xml

Upgrade AWS SDK to version 2.21.39

---

parent/pom.xml

Upgrade JGit to version 6.8.0.202311291450-r

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/hdfs.json
components/camel-hdfs/pom.xml
components/camel-hdfs/src/generated/resources/META-INF/services/org/apache/camel/component.properties
components/camel-hdfs/src/generated/resources/org/apache/camel/component/hdfs/hdfs.json
components/camel-hdfs/src/main/docs/hdfs-component.adoc
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_3.adoc

CAMEL-20196 - Deprecate camel-hdfs

---

components/camel-cassandraql/pom.xml

This partially reverts commit a058dfcdc8cc0d76ad975532bbff422d2ed54563

INFRA-25195: Cassandra tests do not run reliably on ppc64le

---

components/camel-platform-http-vertx/src/test/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpEngineTest.java

Demonstrate Vert.x server cookie support allowing cookies to be added, removed, and replaced per Camel route.

CAMEL-20019 demo cookie handling

---

test-infra/camel-test-infra-elasticsearch/src/test/resources/org/apache/camel/test/infra/elasticsearch/services/container.properties

Updates the container to 8.11.1

(chores) camel-test-infra-elasticsearch: update ElasticSearch container to the latest version

---

docs/user-manual/modules/ROOT/pages/commercial-camel-offerings.adoc

Update commercial-camel-offerings.adoc for Red Hat

---

core/camel-support/src/main/java/org/apache/camel/support/MessageHelper.java

CAMEL-19734: fixing the elapsed time to message history

---

core/camel-support/src/main/java/org/apache/camel/support/MessageHelper.java

CAMEL-19734: fixing the elapsed time to message history 

---

parent/pom.xml

Upgrade Azure SDK BOM to version 1.2.19

---

test-infra/camel-test-infra-azure-common/src/test/resources/org/apache/camel/test/infra/azure/common/services/container.properties

Upgrade Azurite container image to version 3.28.0

---

parent/pom.xml

Upgrade Google Libraries BOM to version 26.28.0

---

parent/pom.xml

Upgrade Google Functions BOM to version 2.33.0

---

components/camel-azure/camel-azure-key-vault/src/main/docs/azure-key-vault-component.adoc
components/camel-azure/camel-azure-key-vault/src/main/java/org/apache/camel/component/azure/key/vault/KeyVaultConfiguration.java
components/camel-azure/camel-azure-key-vault/src/main/java/org/apache/camel/component/azure/key/vault/KeyVaultEndpoint.java
docs/user-manual/modules/ROOT/pages/security.adoc

CAMEL-20220 - Camel Azure Key Vault: Support Azure Identity in the component and secrets function - Docs

---

test-infra/camel-test-infra-hashicorp-vault/src/test/resources/org/apache/camel/test/infra/hashicorp/vault/services/container.properties

Use Latest Vault container image 1.15.4

---

docs/user-manual/modules/ROOT/pages/release-guide.adoc
dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
etc/scripts/release-sbom.sh
etc/scripts/sign.sh
pom.xml

Add SBOM to release and release-sbom script to LTS 4.0.x

---

core/camel-core-languages/src/main/docs/modules/languages/pages/simple-language.adoc
core/camel-core-languages/src/main/java/org/apache/camel/language/simple/SimpleExpressionBuilder.java
core/camel-core-languages/src/main/java/org/apache/camel/language/simple/ast/SimpleFunctionExpression.java
core/camel-core/src/test/java/org/apache/camel/language/simple/SimpleTest.java
core/camel-util/src/main/java/org/apache/camel/util/StringHelper.java

CAMEL-17825: Hash generator in the Simple language

---

components/camel-bean/src/main/java/org/apache/camel/component/bean/AbstractCamelInvocationHandler.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/PooledExchangeFactory.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/PooledProcessorExchangeFactory.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/PrototypeExchangeFactory.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/PrototypeProcessorExchangeFactory.java
core/camel-core/src/test/java/org/apache/camel/component/dataset/DataSetTestEndpointTest.java
core/camel-core/src/test/java/org/apache/camel/issues/PopulateInitialHeadersFailedIssueTest.java
core/camel-core/src/test/java/org/apache/camel/support/component/ApiMethodPropertiesHelperTest.java
core/camel-support/src/main/java/org/apache/camel/support/AbstractExchange.java
core/camel-support/src/main/java/org/apache/camel/support/DefaultEndpoint.java
core/camel-support/src/main/java/org/apache/camel/support/DefaultExchange.java
core/camel-support/src/main/java/org/apache/camel/support/DefaultPooledExchange.java

Just cleaning up things a bit.

CAMEL-20234: consolidate and simplify exchange constructors

---

parent/pom.xml

Upgrade Owasp Maven Plugin Dependency Check to version 9.0.6

---

components/camel-cloudevents/src/main/java/org/apache/camel/component/cloudevents/CloudEvent.java
components/camel-knative/camel-knative-component/src/main/java/org/apache/camel/component/knative/ce/AbstractCloudEventProcessor.java
core/camel-api/src/main/java/org/apache/camel/Clock.java
core/camel-management/src/main/java/org/apache/camel/management/mbean/ManagedBacklogDebugger.java
core/camel-support/src/main/java/org/apache/camel/support/LanguageHelper.java
core/camel-support/src/main/java/org/apache/camel/support/MonotonicClock.java
core/camel-support/src/main/java/org/apache/camel/support/ResetableClock.java
core/camel-util/src/main/java/org/apache/camel/util/TimeUtils.java

Consolidate more code. 
Depends on #12475.

CAMEL-20225: additional Clock API cleanups / consolidation

---

components/camel-http/src/main/docs/http-component.adoc

https://issues.apache.org/jira/browse/CAMEL-20261
Thanks !

CAMEL-20261 - camel-http: update doc on httpClient.cookieSpec option

---

components/camel-http/src/main/java/org/apache/camel/component/http/HttpCredentialsHelper.java
components/camel-http/src/main/java/org/apache/camel/component/http/HttpEndpoint.java
components/camel-http/src/main/java/org/apache/camel/component/http/PreemptiveAuthExecChainHandler.java

CAMEL-20254: camel-http - pre-emptive authentication breaks basic auth

---

components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/FtpSoTimeoutTest.java
parent/pom.xml

Upgrade Jsch to version 0.2.15

---

dsl/camel-yaml-dsl/camel-yaml-dsl/src/main/docs/yaml-dsl.adoc

fix(docs): Update Camel YAML DSL GitHub link

---

components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsDeliveryDelayTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsTopicDurableSharedTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsTopicSharedTest.java

CAMEL-20113: fixed broken JMS tests

---

components/camel-csv/src/main/java/org/apache/camel/dataformat/csv/CsvRecordConverter.java
components/camel-cxf/camel-cxf-rest/src/main/java/org/apache/camel/component/cxf/jaxrs/DefaultCxfRsBinding.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/FtpSoTimeoutTest.java
components/camel-http-base/src/main/java/org/apache/camel/http/base/HttpHelper.java
components/camel-jackson-avro/src/test/java/org/apache/camel/component/jackson/avro/transform/AvroPojoDataTypeTransformerTest.java
components/camel-jasypt/src/test/java/org/apache/camel/component/jasypt/JasytPropertiesParserCustomAlgTest.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaComponent.java
components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/messagehistory/MicrometerMessageHistory.java
components/camel-rest-openapi/src/test/java/org/apache/camel/component/rest/openapi/WireMockJettyServerFactory.java
components/camel-stream/src/main/java/org/apache/camel/component/stream/StreamConsumer.java
components/camel-thrift/src/main/java/org/apache/camel/component/thrift/server/ThriftMethodHandler.java
components/camel-vertx/camel-vertx-http/src/main/java/org/apache/camel/component/vertx/http/VertxHttpEndpoint.java
docs/components/modules/others/nav.adoc
dsl/camel-componentdsl/src/generated/java/org/apache/camel/builder/component/dsl/AzureStorageQueueComponentBuilderFactory.java
dsl/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/dsl/CosmosDbEndpointBuilderFactory.java
dsl/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/dsl/DataLakeEndpointBuilderFactory.java
dsl/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/dsl/EventHubsEndpointBuilderFactory.java
dsl/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/dsl/FilesEndpointBuilderFactory.java
dsl/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/dsl/QueueEndpointBuilderFactory.java
dsl/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/dsl/ServiceBusEndpointBuilderFactory.java
etc/scripts/sign.sh
tests/camel-itest/src/test/java/org/apache/camel/itest/nettyhttp/NettyHttpClientChunkedResponseTest.java

Merging files that are being reformatted during 'mvn install'

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Export.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/KameletMain.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/DependencyDownloaderComponentResolver.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/DependencyDownloaderDataFormatResolver.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/DependencyDownloaderLanguageResolver.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/stub/StubDataFormat.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/stub/StubLanguage.java

CAMEL-20273: camel-jbang - Stub dataformat and language during export

---

components/camel-arangodb/src/main/java/org/apache/camel/component/arangodb/ArangoDbProducer.java
components/camel-aws/camel-aws2-ec2/src/main/java/org/apache/camel/component/aws2/ec2/AWS2EC2Producer.java
components/camel-aws/camel-aws2-iam/src/main/java/org/apache/camel/component/aws2/iam/IAM2Producer.java
components/camel-aws/camel-aws2-kms/src/main/java/org/apache/camel/component/aws2/kms/KMS2Producer.java
components/camel-aws/camel-aws2-lambda/src/main/java/org/apache/camel/component/aws2/lambda/Lambda2Producer.java
components/camel-aws/camel-aws2-mq/src/main/java/org/apache/camel/component/aws2/mq/MQ2Producer.java
components/camel-aws/camel-aws2-sns/src/main/java/org/apache/camel/component/aws2/sns/Sns2Producer.java
components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2MessageHelper.java
components/camel-azure/camel-azure-cosmosdb/src/main/java/org/apache/camel/component/azure/cosmosdb/operations/CosmosDbClientOperations.java
components/camel-azure/camel-azure-cosmosdb/src/main/java/org/apache/camel/component/azure/cosmosdb/operations/CosmosDbContainerOperations.java
components/camel-azure/camel-azure-cosmosdb/src/main/java/org/apache/camel/component/azure/cosmosdb/operations/CosmosDbDatabaseOperations.java
components/camel-azure/camel-azure-key-vault/src/main/java/org/apache/camel/component/azure/key/vault/KeyVaultProducer.java
components/camel-azure/camel-azure-storage-blob/src/main/java/org/apache/camel/component/azure/storage/blob/operations/BlobOperations.java
components/camel-azure/camel-azure-storage-queue/src/main/java/org/apache/camel/component/azure/storage/queue/operations/QueueOperations.java
components/camel-bean/src/main/java/org/apache/camel/component/bean/AbstractCamelInvocationHandler.java

- camel-arangodb
- camel-aws
- camel-azure

(chores) catalog: remove string literal duplications

---

components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxCollaborationsManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxCommentsManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxEventLogsManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxEventsManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxFilesManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxFoldersManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxGroupsManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxHelper.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxSearchManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxTasksManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxUsersManager.java

- remove string literal duplications
- cleanup duplicated code

(chores) camel-box: remove duplications

---

components/camel-cxf/camel-cxf-spring-transport/src/main/java/org/apache/camel/component/cxf/spring/transport/AbstractCamelContextBeanDefinitionParser.java
components/camel-djl/src/main/java/org/apache/camel/component/djl/model/AbstractPredictor.java
components/camel-djl/src/main/java/org/apache/camel/component/djl/model/CustomImageClassificationPredictor.java
components/camel-djl/src/main/java/org/apache/camel/component/djl/model/CustomObjectDetectionPredictor.java
components/camel-djl/src/main/java/org/apache/camel/component/djl/model/ZooImageClassificationPredictor.java
components/camel-djl/src/main/java/org/apache/camel/component/djl/model/ZooObjectDetectionPredictor.java
components/camel-docker/src/main/java/org/apache/camel/component/docker/producer/AsyncDockerProducer.java
components/camel-docker/src/main/java/org/apache/camel/component/docker/producer/DockerProducer.java
components/camel-huawei/camel-huaweicloud-dms/src/main/java/org/apache/camel/component/huaweicloud/dms/DmsMeta.java
components/camel-lra/src/main/java/org/apache/camel/service/lra/LRAClient.java
components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/CamelTestSupport.java
components/camel-test/camel-test-main-junit5/src/main/java/org/apache/camel/test/main/junit5/CamelMainExtension.java

- camel-cxf
- camel-djl
- camel-docker
- camel-huawei
- camel-lra
- camel-test

(chores) components: remove string literal duplications

---

components/camel-jcache/src/main/java/org/apache/camel/component/jcache/policy/JCachePolicyProcessor.java

Initialize bypassExpression as well

[CAMEL-20280] JCachePolicy: initialize bypassExpression

---

components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/DynamicRouterFilterService.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/DynamicRouterRecipientListHelper.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/control/DynamicRouterControlChannelSendDynamicAware.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/control/DynamicRouterControlConfiguration.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/control/DynamicRouterControlConstants.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/control/DynamicRouterControlEndpoint.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/routing/DynamicRouterConstants.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/routing/DynamicRouterProcessor.java
components/camel-dynamic-router/src/test/java/org/apache/camel/component/dynamicrouter/control/DynamicRouterControlChannelSendDynamicAwareTest.java
components/camel-dynamic-router/src/test/java/org/apache/camel/component/dynamicrouter/integration/DynamicRouterBasicSynchronousIT.java
components/camel-dynamic-router/src/test/java/org/apache/camel/component/dynamicrouter/integration/DynamicRouterSendDynamicAwareIT.java
components/camel-dynamic-router/src/test/java/org/apache/camel/component/dynamicrouter/integration/DynamicRouterSingleRouteTwoParticipantsIT.java
components/camel-dynamic-router/src/test/java/org/apache/camel/component/dynamicrouter/integration/DynamicRouterTwoRoutesIT.java
components/camel-dynamic-router/src/test/java/org/apache/camel/component/dynamicrouter/routing/DynamicRouterProcessorTest.java

This is a minor pull request to address some things that I somehow missed in the original pull request.  E.g., sonar findings, and a test class that was commented out and not fixed for some reason.

CAMEL-00000: Fixed a few bugs and sonar findings that I somehow missed.

---

components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsTopicDurableSharedTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsTopicSharedTest.java

it seems that sometimes publication happens before artemis finishes creating consumers
https://issues.apache.org/jira/browse/CAMEL-20276

﻿CAMEL-20276 fixing jms shared topic tests

---

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_4.adoc

Added entry in 4.4 upgrade guide to describe dynamic router eip component changes.

CAMEL-20247: Created entry in upgrade guide for 4.4

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/dataformats/parquetAvro.json
catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/models/parquetAvro.json
components/camel-parquet-avro/src/generated/resources/org/apache/camel/dataformat/parquet/avro/parquetAvro.json
components/camel-parquet-avro/src/main/java/org/apache/camel/dataformat/parquet/avro/ParquetAvroDataFormat.java
core/camel-core-model/src/generated/resources/org/apache/camel/model/dataformat/parquetAvro.json
core/camel-core-model/src/main/java/org/apache/camel/model/dataformat/ParquetAvroDataFormat.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/ModelDeserializers.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camelYamlDsl.json

CAMEL-19143: parquet avro dataformat - Add enum for compression levels.

---

core/camel-support/src/main/java/org/apache/camel/support/builder/ExpressionBuilder.java

camel-core: expression should call super.init

---

core/camel-support/src/main/java/org/apache/camel/support/ExtendedExchangeExtension.java

- Added missing @Override
- Fixed formatting

(chores): code cleanup in ExtendedExchangeExtension

---

components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsDeliveryDelayTest.java

testInOnlyWithDelay was flacky because sometimes message is not received from artemis before .assertIsSatisfied(context) is called.
testInOutWithDelay was missing assertions of mock endpoint condition and of response contents.

JmsDeliveryDelayTest fix flackiness

---

components/camel-paho-mqtt5/src/test/java/org/apache/camel/component/paho/mqtt5/integration/PahoMqtt5ComponentMqtt5IT.java
components/camel-paho-mqtt5/src/test/java/org/apache/camel/component/paho/mqtt5/integration/PahoMqtt5ITSupport.java
components/camel-paho-mqtt5/src/test/java/org/apache/camel/component/paho/mqtt5/integration/PahoMqtt5OverrideTopicMqtt5IT.java
components/camel-paho-mqtt5/src/test/java/org/apache/camel/component/paho/mqtt5/integration/PahoMqtt5ToDIT.java
components/camel-paho-mqtt5/src/test/java/org/apache/camel/component/paho/mqtt5/integration/PahoMqtt5ToDSendDynamicIT.java

(chores) camel-paho-mqtt5: fix integration/unit test mismatch

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorOffUsingKafkaManualCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorReplayOldMessagesIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorSeekIssueIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorWithBatchUsingAsynchCommitManagerIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorWithBatchUsingKafkaManualCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorWithBatchUsingKafkaManualCommitRetryIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/health/KafkaConsumerHealthCheckIT.java

(chores) camel-kafka: disable flaky tests on ppc64le

---

components/camel-mllp/src/test/java/org/apache/camel/component/mllp/MllpTcpServerConsumerOptionalEndOfDataWithValidationTest.java
components/camel-mllp/src/test/java/org/apache/camel/component/mllp/TcpServerConsumerEndOfDataAndValidationTestSupport.java

- Removed commented code
- Removed usage of deprecated methods
- Use lambdas

(chores) camel-mllp: minor cleanups

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/robotframework.json
components/camel-robotframework/src/generated/resources/org/apache/camel/component/robotframework/robotframework.json
components/camel-robotframework/src/main/docs/robotframework-component.adoc
components/camel-robotframework/src/main/java/org/apache/camel/component/robotframework/RobotFrameworkEndpoint.java

Camel-Robotframework: Fixed typo in docs

---

Jenkinsfile.jdk11.ppc64le

Hi @oscerd to enable JDK11 jobs for power for camel- 3.x request to review and merge it

Adding Jenkins file for PPC64LE JDK11

---

core/camel-core-engine/src/main/docs/modules/eips/pages/step-eip.adoc

Fix type acitvemq to activemq step-eip.adoc

---

parent/pom.xml

Revert "Bump org.apache.camel.k:camel-k-crds from 2.1.0 to 2.2.0"

---

docs/user-manual/modules/faq/pages/how-do-i-configure-endpoints.adoc

fix(docs): Update "how-do-i-configure-endpoints.adoc"

---

components/camel-cassandraql/src/main/docs/cql-component.adoc
components/camel-cassandraql/src/main/java/org/apache/camel/processor/aggregate/cassandra/CassandraAggregationRepository.java
components/camel-cassandraql/src/main/java/org/apache/camel/processor/aggregate/cassandra/CassandraCamelCodec.java
components/camel-cassandraql/src/test/java/org/apache/camel/processor/aggregate/cassandra/CassandraCamelCodecTest.java
components/camel-cassandraql/src/test/java/org/malicious/example/Employee.java

CAMEL-20306 - Camel-CassandraQL: Add ObjectInputFilter String pattern parameter in CassandraAggregationRepository to be used in unmarshall operations

---

parent/pom.xml

Get Back to Spring 6.1.2 until Spring Boot release

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/TransformRoute.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/ActionBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/CamelRouteDumpAction.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/CamelSendAction.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/CamelSourceAction.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/CamelSourceTop.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/CamelStartupRecorderAction.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/CamelStubAction.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/CamelThreadDump.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/RouteControllerAction.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/TransformMessageAction.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/Hawtio.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/PluginHelper.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/DownloadThreadPool.java

Also consolidate duplicated interrupt-aware code.

CAMEL-20297 camel-jbang: do not swallow interrupted exceptions

---

pom.xml

Upgrade CycloneDX Maven Plugin to version 2.7.11

---

components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/control/DynamicRouterControlChannelSendDynamicAware.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/control/DynamicRouterControlComponent.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/control/DynamicRouterControlConfiguration.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/control/DynamicRouterControlConstants.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/control/DynamicRouterControlEndpoint.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/control/DynamicRouterControlMessage.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/control/DynamicRouterControlProducer.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/control/DynamicRouterControlService.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/filter/DynamicRouterFilterService.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/filter/PrioritizedFilter.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/filter/PrioritizedFilterStatistics.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/routing/DynamicRouterComponent.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/routing/DynamicRouterConfiguration.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/routing/DynamicRouterConstants.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/routing/DynamicRouterEndpoint.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/routing/DynamicRouterProcessor.java
components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/routing/DynamicRouterRecipientListHelper.java
components/camel-dynamic-router/src/test/java/org/apache/camel/component/dynamicrouter/control/DynamicRouterControlChannelSendDynamicAwareTest.java
components/camel-dynamic-router/src/test/java/org/apache/camel/component/dynamicrouter/control/DynamicRouterControlComponentTest.java
components/camel-dynamic-router/src/test/java/org/apache/camel/component/dynamicrouter/control/DynamicRouterControlEndpointTest.java
components/camel-dynamic-router/src/test/java/org/apache/camel/component/dynamicrouter/control/DynamicRouterControlProducerTest.java
components/camel-dynamic-router/src/test/java/org/apache/camel/component/dynamicrouter/control/DynamicRouterControlServiceTest.java
components/camel-dynamic-router/src/test/java/org/apache/camel/component/dynamicrouter/filter/DynamicRouterFilterServiceTest.java
components/camel-dynamic-router/src/test/java/org/apache/camel/component/dynamicrouter/routing/DynamicRouterComponentTest.java
components/camel-dynamic-router/src/test/java/org/apache/camel/component/dynamicrouter/routing/DynamicRouterEndpointTest.java
components/camel-dynamic-router/src/test/java/org/apache/camel/component/dynamicrouter/routing/DynamicRouterProcessorTest.java
components/camel-dynamic-router/src/test/java/org/apache/camel/component/dynamicrouter/routing/DynamicRouterRecipientListHelperTest.java
components/camel-dynamic-router/src/test/resources/org/apache/camel/component/dynamicrouter/integration/DynamicRouterJmxIT-context.xml

The dynamic router eip component functionality remains the same with this pull request, but I wanted to address a couple of code quality concerns that I had, and I wanted to ensure that there was very comprehensive test coverage.  So, there are quite a few changes, but they are definitely "functionally minor", though they provide better assurance that changes won't break things without indications from testing.

Dynamic Router EIP Component: Code quality improvements and more test coverage.

---

dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/console/DependencyDownloaderConsole.java

Fixed 2 mistakenly inverted boolean flags

CAMEL-20292 fixed inverted flags

---

docs/components/modules/ROOT/examples/json/facebook.json

CAMEL-20294: remove camel-facebook

---

core/camel-core/src/test/java/org/apache/camel/component/file/DirectoryCreateIssueTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FileConsumeNoopIdempotentEnabledTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FileConsumePollEnrichFileIdleEventTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FileConsumePollEnrichFileTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FileConsumerIdempotentKeyChangedIssue2Test.java
core/camel-core/src/test/java/org/apache/camel/component/file/FileConsumerIdempotentRefTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FileConsumerIdempotentTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FileConsumerPollStrategyNotBeginTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FilePollingConsumerTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FilerConsumerDoneFileNameDeleteTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FilerConsumerDoneFileNamePrefixTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FilerConsumerDoneFileNameSimplePrefixTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FilerConsumerDoneFileNameSuffixTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FilerConsumerDoneFileNameTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FilerConsumerDualDoneFileNameTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FilerConsumerPreMoveDoneFileNameTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FilerConsumerShouldSkipDoneFilePrefixTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FilerConsumerShouldSkipDoneFileSuffixTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FilerConsumerShouldSkipDoneFileTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/cluster/FileLockClusteredRoutePolicyFactoryTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/cluster/FileLockClusteredRoutePolicyTest.java

Issue - https://issues.apache.org/jira/browse/CAMEL-19519

CAMEL-19519 - camel-file: replace Thread.sleep in tests.

---

parent/pom.xml

CAMEL-20344 - Upgrade to Spring 6.1.3

---

components/camel-file/src/main/java/org/apache/camel/component/file/FileEndpoint.java
components/camel-file/src/main/java/org/apache/camel/component/file/FileOperations.java
components/camel-file/src/main/java/org/apache/camel/component/file/GenericFileEndpoint.java
components/camel-file/src/main/java/org/apache/camel/component/file/GenericFileSendDynamicAware.java

- fix code duplications
- cleanup duplicated string literals

(chores) camel-file: cleanup code duplications

---

dsl/camel-jbang/camel-jbang-it/README.adoc
dsl/camel-jbang/camel-jbang-it/pom.xml
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/DevModeITCase.java
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/RunCommandITCase.java
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/RunCommandOnMqttITCase.java
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/VersionCommandITCase.java
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/InVersion.java
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/JBangTestSupport.java
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/JiraIssue.java
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/JiraUtil.java
dsl/camel-jbang/camel-jbang-it/src/test/resources/jbang/it/helloName.xml
dsl/camel-jbang/camel-jbang-it/src/test/resources/jbang/it/joke.yaml
dsl/camel-jbang/camel-jbang-it/src/test/resources/jbang/it/local.properties
dsl/camel-jbang/camel-jbang-it/src/test/resources/jbang/it/mqttConsumer.yaml
dsl/camel-jbang/camel-jbang-it/src/test/resources/jbang/it/route2.yaml
dsl/camel-jbang/camel-jbang-it/src/test/resources/logback-test.xml
test-infra/camel-test-infra-cli/README.adoc
test-infra/camel-test-infra-cli/pom.xml
test-infra/camel-test-infra-cli/src/test/java/org/apache/camel/test/infra/cli/common/CliProperties.java
test-infra/camel-test-infra-cli/src/test/java/org/apache/camel/test/infra/cli/services/CliBuiltContainer.java
test-infra/camel-test-infra-cli/src/test/java/org/apache/camel/test/infra/cli/services/CliLocalContainerService.java
test-infra/camel-test-infra-cli/src/test/java/org/apache/camel/test/infra/cli/services/CliService.java
test-infra/camel-test-infra-cli/src/test/java/org/apache/camel/test/infra/cli/services/CliServiceFactory.java
test-infra/camel-test-infra-cli/src/test/resources/org/apache/camel/test/infra/cli/services/99-ssh-jbang.conf
test-infra/camel-test-infra-cli/src/test/resources/org/apache/camel/test/infra/cli/services/Dockerfile
test-infra/camel-test-infra-cli/src/test/resources/org/apache/camel/test/infra/cli/services/entrypoint.sh
test-infra/pom.xml

CAMEL-19338: JBang it tests

---

components/camel-freemarker/src/main/java/org/apache/camel/component/freemarker/FreemarkerEndpoint.java
components/camel-freemarker/src/test/resources/org/apache/camel/component/freemarker/example.ftl
components/camel-groovy/src/main/docs/groovy-language.adoc
components/camel-groovy/src/test/java/org/apache/camel/language/groovy/GroovyLanguageTest.java
components/camel-stringtemplate/src/main/java/org/apache/camel/component/stringtemplate/StringTemplateEndpoint.java
components/camel-thymeleaf/src/main/java/org/apache/camel/component/thymeleaf/ThymeleafEndpoint.java
components/camel-velocity/src/main/java/org/apache/camel/component/velocity/VelocityEndpoint.java
core/camel-support/src/main/java/org/apache/camel/support/ExchangeHelper.java

Exchange properties

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/RuntimeUtil.java

Find out that `Configurator` accepts `URI` as path to logging configuration. Dont know how to test it automatically though.

CAMEL-19956 camel-jbang: added support for custom logging configuration

---

components/camel-google/camel-google-calendar/pom.xml
components/camel-google/camel-google-drive/pom.xml
components/camel-google/camel-google-mail/pom.xml
components/camel-google/camel-google-sheets/pom.xml
parent/pom.xml

Upgade google http client 1.44.1

---

catalog/camel-csimple-maven-plugin/pom.xml
catalog/camel-csimple-maven-plugin/src/main/docs/camel-csimple-maven-plugin.adoc
catalog/camel-csimple-maven-plugin/src/main/java/org/apache/camel/maven/GenerateMojo.java
catalog/camel-report-maven-plugin/pom.xml
components/camel-debezium/camel-debezium-common/camel-debezium-maven-plugin/pom.xml
dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/pom.xml
tooling/maven/bom-generator-maven-plugin/pom.xml
tooling/maven/camel-api-component-maven-plugin/pom.xml
tooling/maven/camel-component-maven-plugin/pom.xml
tooling/maven/camel-eip-documentation-enricher-maven-plugin/pom.xml
tooling/maven/camel-maven-plugin/pom.xml
tooling/maven/camel-package-maven-plugin/pom.xml
tooling/maven/camel-restdsl-openapi-plugin/pom.xml
tooling/maven/sync-properties-maven-plugin/pom.xml

maven-plugin-plugin - Add goalPrefix

---

test-infra/camel-test-infra-aws-v2/src/test/resources/org/apache/camel/test/infra/aws2/services/container.properties

Upgrade Localstack container image to version 3.1.0

---

components/camel-ical/src/main/java/org/apache/camel/component/ical/ICalDataFormat.java
components/camel-ical/src/test/java/org/apache/camel/component/ical/ICalDataFormatTest.java

fixes https://issues.apache.org/jira/browse/CAMEL-20375

Fix of NPE in IcalDatsFormat (Camel-20375)

---

components/camel-kafka/src/main/java/org/apache/camel/processor/idempotent/kafka/KafkaConsumerUtil.java
components/camel-kafka/src/main/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepository.java
components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaConsumerUtilsTest.java
components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryPersistenceIT.java

Same as https://github.com/apache/camel/pull/12948 but for the 3.22.x branch.
3.22.x
https://issues.apache.org/jira/browse/CAMEL-20373
- [ v] I checked that each commit in the pull request has a meaningful subject line and body.
- [ v] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes

CAMEL-20218: On startup populate local cache synchronously - branch 3.22.x

---

components/camel-azure/camel-azure-storage-queue/src/main/java/org/apache/camel/component/azure/storage/queue/QueueConsumer.java
components/camel-azure/camel-azure-storage-queue/src/test/java/org/apache/camel/component/azure/storage/queue/integration/StorageQueueConsumerIT.java

Prefer the toStream method over the toString method on the BinaryData

CAMEL-20202: Read Azure BinaryData as stream

---

components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/client/impl/AWS2S3ClientSessionTokenImpl.java

Camel 20281 s3 refine

---

components/camel-bean/src/main/java/org/apache/camel/language/bean/BeanLanguage.java
components/camel-datasonnet/src/main/java/org/apache/camel/language/datasonnet/DatasonnetLanguage.java
components/camel-joor/src/main/java/org/apache/camel/language/joor/JavaLanguage.java
components/camel-jq/src/main/java/org/apache/camel/language/jq/JqLanguage.java
components/camel-jsonpath/src/main/java/org/apache/camel/jsonpath/JsonPathLanguage.java
components/camel-jsonpath/src/test/java/org/apache/camel/jsonpath/JsonPathLanguageTest.java
components/camel-saxon/src/main/java/org/apache/camel/language/xquery/XQueryLanguage.java
components/camel-stax/src/main/java/org/apache/camel/language/xtokenizer/XMLTokenExpressionIterator.java
components/camel-stax/src/main/java/org/apache/camel/language/xtokenizer/XMLTokenizeLanguage.java
components/camel-wasm/src/main/java/org/apache/camel/language/wasm/WasmExpression.java
components/camel-wasm/src/main/java/org/apache/camel/language/wasm/WasmLanguage.java
components/camel-xpath/src/main/java/org/apache/camel/language/xpath/XPathLanguage.java
core/camel-core-languages/src/main/java/org/apache/camel/language/tokenizer/TokenizeLanguage.java
core/camel-core-model/src/main/java/org/apache/camel/builder/ExpressionClause.java
core/camel-core-model/src/main/java/org/apache/camel/builder/ExpressionClauseSupport.java
core/camel-core-reifier/src/main/java/org/apache/camel/reifier/language/MethodCallExpressionReifier.java
core/camel-core-reifier/src/main/java/org/apache/camel/reifier/language/WasmExpressionReifier.java
core/camel-core/src/test/java/org/apache/camel/language/TokenizerTest.java
core/camel-core/src/test/java/org/apache/camel/support/CustomizersTest.java
core/camel-support/src/main/java/org/apache/camel/support/SingleInputLanguageSupport.java
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_4.adoc
dsl/camel-kotlin-dsl/src/test/kotlin/org/apache/camel/dsl/kotlin/KotlinRoutesBuilderLoaderTest.kt
dsl/camel-kotlin-dsl/src/test/resources/routes/routes-with-languages-configuration.kts

Configuration of languages should be consistent (part 1)

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/batching/KafkaRecordBatchingProcessor.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/batching/BatchingProcessingITSupport.java

~This cannot be merged yet. Auto-commit is broken now. Just sending to simplify Andrea's testing ...~
Should be fine now.

CAMEL-20380: fixed incomplete batching on poll timeout

---

test-infra/camel-test-infra-hashicorp-vault/src/test/resources/org/apache/camel/test/infra/hashicorp/vault/services/container.properties

Upgrade Vault image to 1.15.5

---

components/camel-dhis2/camel-dhis2-component/src/test/java/org/apache/camel/component/dhis2/Dhis2GetIT.java
components/camel-dhis2/pom.xml

Keep DHIS2 component backwards compatible

Keep DHIS2 component backwards compatible

---

Jenkinsfile.ppc64le.jdk21

Hi @oscerd to enable JDK21 jobs for power for camel- 4.x request to review and merge it

Adding Jenkins file for PPC64LE JDK21

---

dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationRunTest.java
parent/pom.xml

camel-jbang - Upgrade to camel-k 2.2.0 apis

---

docs/main/modules/contributing/pages/building.adoc
docs/main/modules/contributing/pages/index.adoc
docs/main/modules/contributing/pages/testing-camel.adoc

- Added a Testing Camel page
- Updated building details
- Added basic information about adjusting the code when required
- Fixed outdated links

(doc) Updated the contributing guide

---

pom.xml

Fixes a typo originally found on CAMEL-20337 by Craig Ziesman <craig.ziesman@gmail.com>

CAMEL-20377: fixes a confusing typo in the pom file

---

docs/main/modules/contributing/pages/index.adoc

- about build changes
- about missing assertions

(chores) doc: minor contributions clarifications

---

components/camel-kafka/src/main/docs/kafka-component.adoc

This was likely causing the website build to fail

(chores) camel-kafka: fixed an out-of-order section

---

core/camel-api/src/main/java/org/apache/camel/VariableAware.java
core/camel-api/src/main/java/org/apache/camel/spi/VariableRepository.java
core/camel-api/src/main/java/org/apache/camel/spi/VariableRepositoryFactory.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultVariableRepositoryFactory.java
core/camel-console/src/main/java/org/apache/camel/impl/console/VariablesDevConsole.java
core/camel-core-languages/src/main/java/org/apache/camel/language/simple/SimpleExpressionBuilder.java
core/camel-core-model/src/main/java/org/apache/camel/builder/ExpressionClause.java
core/camel-core/src/test/java/org/apache/camel/processor/SetRouteVariableTest.java
core/camel-core/src/test/java/org/apache/camel/processor/SetRouteVariableTransferTest.java
core/camel-main/src/main/java/org/apache/camel/main/MainSupportModelConfigurer.java
core/camel-management/src/test/java/org/apache/camel/management/ManagedNonManagedServiceTest.java
core/camel-management/src/test/java/org/apache/camel/management/ManagedProducerRouteAddRemoveRegisterAlwaysTest.java
core/camel-management/src/test/java/org/apache/camel/management/ManagedRouteAddRemoveTest.java
core/camel-support/src/main/java/org/apache/camel/support/ExchangeHelper.java
core/camel-support/src/main/java/org/apache/camel/support/RouteVariableRepository.java
core/camel-support/src/main/java/org/apache/camel/support/builder/ExpressionBuilder.java
docs/user-manual/modules/ROOT/pages/variables.adoc
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/ListVariable.java

Route scoped variables

---

components/camel-joor/src/main/java/org/apache/camel/language/joor/CompilationUnit.java
components/camel-olingo4/camel-olingo4-component/src/main/java/org/apache/camel/component/olingo4/Olingo4Endpoint.java
components/camel-xchange/src/main/java/org/apache/camel/component/xchange/XChangeComponent.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/CamelInternalProcessor.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultRuntimeEndpointRegistry.java
core/camel-core-languages/src/main/java/org/apache/camel/language/csimple/CSimpleLanguage.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/injection/AnnotationDependencyInjection.java

Implements https://issues.apache.org/jira/browse/CAMEL-20384.
There are three results from [the SonarCloud report](https://sonarcloud.io/project/issues?resolved=false&rules=java%3AS3824&id=apache_camel) which this PR does not address:
1. core/.../apache/camel/converter/jaxp/XMLReaderPool.java#setFeature
2. dsl/.../joor/JavaRoutesBuilderLoader.java#preParseRoutes
3. dsl/.../joor/JavaRoutesBuilderLoader.java#doLoadRouteBuilder
This is because these throw checked exceptions and to use the modernized map functions would require throwing unchecked exceptions from the Lambda functions instead. This involves core code, so figured I would check before making such changes to those ones.

CAMEL-20384: Modernize map operations

---

parent/pom.xml

Upgrade Google Secrets Manager BOM to version 2.35.0

---

components/camel-azure/camel-azure-cosmosdb/src/main/docs/azure-cosmosdb-component.adoc

CAMEL-20410: documentation fixes for camel-azure-cosmosdb

---

components/camel-azure/camel-azure-cosmosdb/src/main/docs/azure-cosmosdb-component.adoc

Revert "Generated sources regen"

---

components/camel-azure/camel-azure-eventhubs/src/main/docs/azure-eventhubs-component.adoc
components/camel-azure/camel-azure-files/src/main/docs/azure-files-component.adoc

CAMEL-20410: documentation fixes for camel-azure-eventhubs

---

docs/user-manual/modules/ROOT/pages/camel-jbang-k.adoc
docs/user-manual/modules/ROOT/pages/camel-jbang.adoc

- Describe how to manage the command plugins
- Add instructions to enable the plugin first before using the Camel K subcommands

docs: Add JBang plugin documentation

---

test-infra/camel-test-infra-azure-common/src/test/resources/org/apache/camel/test/infra/azure/common/services/container.properties

Upgrade Azurite container to version 3.29.0

---

components/camel-knative/camel-knative-component/src/main/java/org/apache/camel/component/knative/KnativeComponent.java
components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpConsumer.java
components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpConsumerFactory.java
components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpProducerFactory.java
components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpSupport.java
components/camel-platform-http-main/src/main/java/org/apache/camel/component/platform/http/main/MainHttpServer.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/DependencyDownloaderComponentResolver.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/util/CamelJBangSettingsHelper.java

- KnativeHttpConsumer needs the main http server in order to provide a Http endpoint route that is supposed to be called by the Knative broker subscription
- Initialize platform main http server when Knative component is used in Camel JBang
- Use default port 8080 only if camel.jbang.platform-http.port setting has not been set
- Add KnativeHttpConsumer and KnativeHttpProducer factory as a service to the Camel context so init() and start() methods are called properly
Closes #13095

camel-jbang: Automatically load main http server for Knative component

---

test-infra/camel-test-infra-infinispan/src/test/resources/org/apache/camel/test/infra/infinispan/services/container.properties

Upgrade Infinispan container image to version 14.0.24.Final

---

test-infra/camel-test-infra-nats/src/test/resources/org/apache/camel/test/infra/nats/services/container.properties

Upgrade Nats container to version 2.10.10

---

components/camel-datasonnet/src/main/docs/datasonnet-language.adoc

CAMEL-20410: documentation fixes for camel-datasonnet

---

components/camel-barcode/src/main/docs/barcode-dataformat.adoc

CAMEL-20410: documentation fixes for camel-barcode

---

components/camel-bean/src/main/docs/bean-component.adoc
components/camel-bean/src/main/docs/bean-language.adoc
components/camel-bean/src/main/docs/class-component.adoc

CAMEL-20410: documentation fixes for camel-bean

---

components/camel-bindy/src/main/docs/bindy-dataformat.adoc

CAMEL-20410: documentation fixes for camel-bindy

---

components/camel-webhook/src/main/docs/webhook-component.adoc

CAMEL-20410: documentation fixes for camel-webhook

---

components/camel-mock/src/main/docs/mock-component.adoc

CAMEL-20410: documentation fixes for camel-mock

---

components/camel-cxf/camel-cxf-rest/src/main/docs/cxfrs-component.adoc

CAMEL-20410: documentation fixes for camel-cxf-rest

---

components/camel-cxf/camel-cxf-soap/src/main/docs/cxf-component.adoc

CAMEL-20410: documentation fixes for camel-cxf-soap

---

core/camel-core-engine/src/main/docs/modules/eips/pages/pipeline-eip.adoc

Fixed typos in route examples.

CAMEL-20410: documentation fixes for pipeline eip

---

components/camel-seda/src/main/docs/seda-component.adoc

CAMEL-20410: documentation fixes for camel-seda

---

components/camel-irc/src/main/docs/irc-component.adoc
components/camel-ironmq/src/main/docs/ironmq-component.adoc
components/camel-jasypt/src/main/docs/jasypt.adoc
components/camel-jolt/src/main/docs/jolt-component.adoc
components/camel-paho-mqtt5/src/main/docs/paho-mqtt5-component.adoc
components/camel-paho/src/main/docs/paho-component.adoc
components/camel-rocketmq/src/main/docs/rocketmq-component.adoc
components/camel-weather/src/main/docs/weather-component.adoc

CAMEL-20410: documentation fixes for camel-paho

---

components/camel-plc4x/src/main/java/org/apache/camel/component/plc4x/Plc4XEndpoint.java
components/camel-plc4x/src/test/java/org/apache/camel/component/plc4x/MockDriver.java
parent/pom.xml

Upgrade plc4x to version 0.12.0

---

parent/pom.xml

Bumps org.apache.commons:commons-compress from 1.25.0 to 1.26.0.
---
updated-dependencies:
- dependency-name: org.apache.commons:commons-compress dependency-type: direct:production update-type: version-update:semver-minor ...
CVE-2024-26308 and CVE-2024-25710

Bump org.apache.commons:commons-compress from 1.25.0 to 1.26.0 (#13183)

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/zeebe.json
components/camel-zeebe/src/generated/resources/org/apache/camel/component/zeebe/zeebe.json
components/camel-zeebe/src/main/docs/zeebe-component.adoc
components/camel-zeebe/src/main/java/org/apache/camel/component/zeebe/ZeebeEndpoint.java

- Fixed a typo in the component description

CAMEL-20410: documentation fixes for camel-zeebe

---

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc

Fix typos doc camel j bang

---

docs/user-manual/modules/ROOT/pages/camel-4-migration-guide.adoc
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_3.adoc
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_4.adoc

Fix typos in 4.x Migration guides

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/jslt.json
components/camel-jslt/src/generated/resources/org/apache/camel/component/jslt/jslt.json
components/camel-jslt/src/main/docs/jslt-component.adoc
components/camel-jslt/src/main/java/org/apache/camel/component/jslt/JsltEndpoint.java

CAMEL-20410: documentation fixes for camel-jslt

---

components/camel-microprofile/camel-microprofile-config/src/main/docs/microprofile-config.adoc

CAMEL-20410: fixed website build for camel-microprofile-config

---

core/camel-core-engine/src/main/docs/modules/eips/pages/aggregate-eip.adoc
core/camel-core-engine/src/main/docs/modules/eips/pages/bean-eip.adoc
core/camel-core-engine/src/main/docs/modules/eips/pages/change-data-capture.adoc
core/camel-core-engine/src/main/docs/modules/eips/pages/channel-adapter.adoc
core/camel-core-engine/src/main/docs/modules/eips/pages/choice-eip.adoc

CAMEL-20459: documentation fixes for the EIPs

---

catalog/camel-report-maven-plugin/pom.xml
components/camel-micrometer-prometheus/src/main/java/org/apache/camel/component/micrometer/prometheus/MicrometerPrometheus.java
components/camel-platform-http-main/src/main/java/org/apache/camel/component/platform/http/main/MainHttpServer.java
components/camel-platform-http-main/src/test/resources/log4j2.properties
components/camel-platform-http/src/main/java/org/apache/camel/component/platform/http/HttpEndpointModel.java
components/camel-platform-http/src/main/java/org/apache/camel/component/platform/http/PlatformHttpComponent.java
components/camel-platform-http/src/main/java/org/apache/camel/component/platform/http/PlatformHttpConsumer.java

Output log from example:
```
[l.example.MyApplication.main()] MainHttpServer                 INFO  HTTP endpoints summary
[l.example.MyApplication.main()] MainHttpServer                 INFO      http://0.0.0.0:8080/ (POST) accept: application/json produce: application/json
[l.example.MyApplication.main()] MainHttpServer                 INFO      http://0.0.0.0:8080/q/dev produce: text/plain,application/json
[l.example.MyApplication.main()] MainHttpServer                 INFO      http://0.0.0.0:8080/q/health produce: application/json
[l.example.MyApplication.main()] MainHttpServer                 INFO      http://0.0.0.0:8080/q/jolokia produce: text/plain,application/json
```

CAMEL-20460: Improve platform http log

---

components/camel-aws/camel-aws-bedrock/src/generated/resources/META-INF/org/apache/camel/component/aws2/bedrock/aws-bedrock.json
components/camel-aws/camel-aws-bedrock/src/main/java/org/apache/camel/component/aws2/bedrock/BedrockEndpoint.java

Camel-AWS-Bedrock: Align Category in Endpoint

---

components/camel-aws/camel-aws-bedrock/src/main/java/org/apache/camel/component/aws2/bedrock/BedrockProducer.java

Camel-AWS-Bedrock: Set result body as invoke model Message body

---

components/camel-aws/camel-aws-bedrock/src/main/docs/aws-bedrock-component.adoc

Camel-AWS-Bedrock: Documentation and json schema for supported model

---

components/camel-platform-http-main/src/main/java/org/apache/camel/component/platform/http/main/MainHttpServer.java

```
[l.example.MyApplication.main()] MainHttpServer                 INFO      http://0.0.0.0:8080/   (POST) (accept:application/json produce:application/json)
[l.example.MyApplication.main()] MainHttpServer                 INFO      http://0.0.0.0:8080/q/dev    (produce:text/plain,application/json)
[l.example.MyApplication.main()] MainHttpServer                 INFO      http://0.0.0.0:8080/q/health    (produce:application/json)
[l.example.MyApplication.main()] MainHttpServer                 INFO      http://0.0.0.0:8080/q/jolokia    (produce:text/plain,application/json)
```

align output log

---

components/camel-aws/camel-aws-bedrock/src/main/java/org/apache/camel/component/aws2/bedrock/BedrockProducer.java
components/camel-aws/camel-aws-bedrock/src/test/java/org/apache/camel/component/aws2/bedrock/integration/BedrockProducerIT.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/TransformRoute.java

Camel-AWS-Bedrock: Make image model return an array of images

---

components/camel-jetty/src/test/java/org/apache/camel/component/jetty/rest/RestJettyInvalidContentTypeClientRequestValidationTest.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/RestBindingAdvice.java

Cherry-picked fix from Camel 4.3.0 to Camel 3.22.x version for CAMEL-20210

CAMEL-20210: camel-core - Rest DSL Narrow content-type with charset fails clientRequestValidation

---

components/camel-quartz/src/test/java/org/apache/camel/component/quartz/DelegateEndpointQuartzTest.java
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzCronRouteTest.java
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzCronRouteWithSmallCacheTest.java
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzCronRouteWithStartDateEndDateTest.java
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzCustomCalendarFireTest.java
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzCustomCalendarNoFireTest.java
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzInterruptTest.java
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzNameCollisionTest.java
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzOneCamelContextSuspendResumeTest.java
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzPropertiesTest.java
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzSimpleRouteTest.java
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzStatefulJobRouteTest.java
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzSuspendRouteTest.java
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzTwoCamelContextRestartTest.java
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzTwoCamelContextSameNameClashTest.java
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzTwoCamelContextSuspendResumeTest.java
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzTwoCamelContextTest.java
components/camel-quartz/src/test/java/org/apache/camel/routepolicy/quartz/SimpleScheduledRoutePolicyTest.java

Issue https://issues.apache.org/jira/browse/CAMEL-19553

CAMEL-19553: camel-quartz ensure tests have assertions

---

core/camel-main/src/main/java/org/apache/camel/main/DefaultConfigurationConfigurer.java
core/camel-main/src/test/java/org/apache/camel/main/MainCustomizerTest.java

Invoke CamelContextCustomizer as part of DefaultConfigurationConfigurer::afterConfigure

---

components/camel-mongodb/src/generated/java/org/apache/camel/component/mongodb/converters/MongoDbBasicConvertersLoader.java
components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/converters/MongoDbBasicConverters.java

Adds MongoDB converter from  java.io.InputStream to org.bson.conversions.Bson

CAMEL-20530: Adds converter from IS to Bson

---

parent/pom.xml
test-infra/camel-test-infra-pulsar/src/test/resources/org/apache/camel/test/infra/pulsar/services/container.properties

Upgrade to pulsar 3.2.1

---

components/camel-shiro/pom.xml
components/camel-shiro/src/main/java/org/apache/camel/component/shiro/security/ShiroSecurityHelper.java
components/camel-shiro/src/main/java/org/apache/camel/component/shiro/security/ShiroSecurityPolicy.java
components/camel-shiro/src/main/java/org/apache/camel/component/shiro/security/ShiroSecurityProcessor.java
components/camel-shiro/src/main/java/org/apache/camel/component/shiro/security/ShiroSecurityTokenInjector.java
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_5.adoc
parent/pom.xml

CAMEL-20491: camel-shiro - Upgrade to 2.0 that is jakarta ee compatible

---

core/camel-core-engine/src/main/docs/modules/eips/pages/message-broker.adoc

Update message-broker.adoc and changed link from s3 to sqs to match text.
Existing documentation link was pointing to S3 where as note was for sqs.

Update message-broker.adoc and changed link from s3 to sqs to match text

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConfiguration.java

CAMEL-20549: camel-kafka - Using sslKeystoreType should work with PEM

---

core/camel-core-engine/src/main/docs/modules/eips/pages/message-broker.adoc

Update message-broker.adoc and fixed link to sqs

Update message-broker.adoc and fixed link to sqs (#13435)

---

docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_19.adoc

Adds camel-http entry for changed redirect behaviour to 3.19 upgrade guide

fix(docs): Adds camel-http entry for changed redirect behaviour to 3.19 upgrade guide

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/aws-secrets-manager.json
catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/azure-key-vault.json
catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/google-secret-manager.json
catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/hashicorp-vault.json
components/camel-aws/camel-aws-secrets-manager/src/generated/resources/META-INF/org/apache/camel/component/aws/secretsmanager/aws-secrets-manager.json
components/camel-aws/camel-aws-secrets-manager/src/main/java/org/apache/camel/component/aws/secretsmanager/SecretsManagerEndpoint.java
components/camel-azure/camel-azure-key-vault/src/generated/resources/META-INF/org/apache/camel/component/azure/key/vault/azure-key-vault.json
components/camel-azure/camel-azure-key-vault/src/main/java/org/apache/camel/component/azure/key/vault/KeyVaultEndpoint.java
components/camel-google/camel-google-secret-manager/src/generated/resources/META-INF/org/apache/camel/component/google/secret/manager/google-secret-manager.json
components/camel-google/camel-google-secret-manager/src/main/java/org/apache/camel/component/google/secret/manager/GoogleSecretManagerEndpoint.java
components/camel-hashicorp-vault/src/generated/resources/META-INF/org/apache/camel/component/hashicorp/vault/hashicorp-vault.json
components/camel-hashicorp-vault/src/main/java/org/apache/camel/component/hashicorp/vault/HashicorpVaultEndpoint.java
dsl/camel-componentdsl/src/generated/resources/metadata.json

Vault: Added Metadata annotations to show support for vault in catalog

---

components/camel-xslt/src/main/java/org/apache/camel/component/xslt/XsltBuilder.java

https://issues.apache.org/jira/browse/CAMEL-20564

CAMEL-20654: camel-xslt: Make variables available as xsl:param

---

components/camel-aws/camel-aws-bedrock/src/main/docs/aws-bedrock-component.adoc
components/camel-aws/camel-aws-bedrock/src/test/java/org/apache/camel/component/aws2/bedrock/runtime/integration/BedrockProducerIT.java
components/camel-azure/camel-azure-servicebus/src/main/java/org/apache/camel/component/azure/servicebus/client/ServiceBusClientFactory.java

Camel-AWS-Bedrock: Add documentation for models

---

parent/pom.xml
pom.xml

fixes https://issues.apache.org/jira/browse/CAMEL-20566

Jaxb properties should be present in parent/pom.xml CAMEL-20566

---

NOTICE.txt

Update year in NOTICE.txt

---

dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/CustomResolver.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/ErrorHandlerDeserializer.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/RouteDefinitionDeserializer.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camelYamlDsl.json
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/RoutesTest.groovy

Allow to set error handler on route level in Camel YAML DSL
See CAMEL-20568

CAMEL-20568: Set error handler on route level in YAML DSL

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/PluginHelper.java

(cherry picked from commit cc8a3f85356a535e2a5dc2c6c5326607c30aea24)

[backport 4.4.x] CAMEL-20517 camel-jbang-plugin-k doesn't recognize command (#13397)

---

core/camel-xml-jaxb/src/main/java/org/apache/camel/xml/jaxb/JaxbHelper.java
dsl/camel-xml-io-dsl/src/main/java/org/apache/camel/dsl/xml/io/XmlRoutesBuilderLoader.java
dsl/camel-xml-io-dsl/src/test/java/org/apache/camel/dsl/xml/io/XmlLoadAppTest.java
dsl/camel-xml-io-dsl/src/test/resources/org/apache/camel/dsl/xml/io/camel-app12.xml
dsl/camel-xml-jaxb-dsl-test/definition/src/test/java/org/apache/camel/dsl/xml/jaxb/definition/LoadRestConfigurationFromXmlTest.java
dsl/camel-xml-jaxb-dsl-test/definition/src/test/resources/org/apache/camel/dsl/xml/jaxb/definition/restConfiguration.xml
dsl/camel-xml-jaxb-dsl/src/main/java/org/apache/camel/dsl/xml/jaxb/JaxbXmlRoutesBuilderLoader.java

Done in a similar way as the yaml-dsl, hope this is ok! Not sure why it's possible to define [multiple](https://github.com/apache/camel/blob/e6cede73c02c88d83ffd5876090e0072f9ea8e7b/core/camel-core-model/src/main/java/org/apache/camel/model/app/BeansDefinition.java#L92) restConfigurations in xml. It also seems that the xml-io-dsl can handle a root \<camel\> tag while the xml-jaxb-dsl cannot. Thanks !

Camel 20567 make it possible to define restconfiguration in xml-io-dsl and xml-jaxb-dsl

---

components/camel-ai/camel-langchain-embeddings/pom.xml
components/camel-ai/camel-langchain-embeddings/src/test/java/org/apache/camel/component/langchain/embeddings/LangchainEmbeddingsComponentMilvusTargetIT.java
components/camel-ai/camel-langchain-embeddings/src/test/java/org/apache/camel/component/langchain/embeddings/LangchainEmbeddingsTestSupport.java

Camel-AI: Langchain Embeddings component testing with Camel Milvus

---

catalog/camel-catalog/src/main/java/org/apache/camel/catalog/CamelCatalog.java
catalog/camel-catalog/src/main/java/org/apache/camel/catalog/DefaultCamelCatalog.java
catalog/camel-catalog/src/main/java/org/apache/camel/catalog/DefaultRuntimeProvider.java
catalog/camel-catalog/src/main/java/org/apache/camel/catalog/RuntimeProvider.java
catalog/camel-catalog/src/main/resources/org/apache/camel/catalog/capabilities.properties
catalog/camel-catalog/src/test/java/org/apache/camel/catalog/CamelCatalogTest.java
tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/EntityRef.java
tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/Kind.java

CAMEL-20548: include a capability section to advertise which artifact provides a specific feature

---

components/camel-milvus/src/test/java/org/apache/camel/component/milvus/MilvusTestSupport.java
test-infra/camel-test-infra-milvus/src/test/java/org/apache/camel/test/infra/milvus/common/MilvusProperties.java
test-infra/camel-test-infra-milvus/src/test/java/org/apache/camel/test/infra/milvus/services/MilvusLocalContainerService.java
test-infra/camel-test-infra-milvus/src/test/java/org/apache/camel/test/infra/milvus/services/MilvusRemoteService.java
test-infra/camel-test-infra-milvus/src/test/java/org/apache/camel/test/infra/milvus/services/MilvusService.java
test-infra/camel-test-infra-milvus/src/test/java/org/apache/camel/test/infra/milvus/services/MilvusServiceFactory.java

Camel-Milvus Test Infra: Improved options

---

dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/KubernetesHelper.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationRunTest.java

https://issues.apache.org/jira/browse/CAMEL-20559

CAMEL-20559 camel-jbang-plugin-k run command error on a multi-valued trait property

---

dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/KubernetesHelper.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationRunTest.java

https://issues.apache.org/jira/browse/CAMEL-20559
(cherry picked from commit 988e4cafc702f86199061e11924ebad73d9c65ab)

[backport 4.4] CAMEL-20559 camel-jbang-plugin-k run command error on a multi-valued trait property (#13521)

---

components/camel-hazelcast/pom.xml
components/camel-hazelcast/src/test/java/org/apache/camel/component/hazelcast/HazelcastConfigurationTest.java
components/camel-hazelcast/src/test/java/org/apache/camel/component/hazelcast/HazelcastListProducerTest.java
components/camel-hazelcast/src/test/java/org/apache/camel/component/hazelcast/HazelcastSedaTransferExchangeTest.java
components/camel-hazelcast/src/test/java/org/apache/camel/component/hazelcast/HazelcastSetProducerTest.java
components/camel-hazelcast/src/test/java/org/apache/camel/processor/aggregate/hazelcast/HazelcastAggregationRepositoryCamelTestSupport.java
components/camel-hazelcast/src/test/java/org/apache/camel/processor/idempotent/hazelcast/HazelcastIdempotentRepositoryTest.java
test-infra/camel-test-infra-hazelcast/pom.xml
test-infra/camel-test-infra-hazelcast/src/test/java/org/apache/camel/test/infra/hazelcast/common/HazelcastProperties.java
test-infra/camel-test-infra-hazelcast/src/test/java/org/apache/camel/test/infra/hazelcast/services/HazelcastEmbeddedService.java
test-infra/camel-test-infra-hazelcast/src/test/java/org/apache/camel/test/infra/hazelcast/services/HazelcastRemoteService.java
test-infra/camel-test-infra-hazelcast/src/test/java/org/apache/camel/test/infra/hazelcast/services/HazelcastService.java
test-infra/camel-test-infra-hazelcast/src/test/java/org/apache/camel/test/infra/hazelcast/services/HazelcastServiceFactory.java
test-infra/pom.xml

CAMEL-16660 - Hazelcast : tests : create camel-test-infra-Hazelcast.

---

dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/TraitHelper.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationRunTest.java

https://issues.apache.org/jira/browse/CAMEL-20576

CAMEL-20576 camel-jbang-plugin-k run command kebab-case parsing invalid

---

dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/TraitHelper.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationRunTest.java

https://issues.apache.org/jira/browse/CAMEL-20576
ref: (#13536)
(cherry picked from commit de91375c6a8f80f9aac4f0e961425ef379ec2f95)

[backport 4.4] CAMEL-20576 camel-jbang-plugin-k run command kebab-case parsing invalid 

---

core/camel-core-xml/src/main/java/org/apache/camel/core/xml/AbstractCamelContextFactoryBean.java

Avoid rest routes dupes

---

core/camel-util/src/main/java21/org/apache/camel/util/concurrent/ThreadType.java

CAMEL-20583: Java 21 - Reduce the noise from the ThreadType logger

---

dsl/camel-jbang/camel-jbang-plugin-k/pom.xml
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/Agent.java
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/KubePlugin.java
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/support/Capability.java
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/support/RuntimeType.java
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/support/RuntimeTypeConverter.java
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/support/SourceMetadata.java
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/support/StubComponentResolver.java
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/support/StubDataFormatResolver.java
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/support/StubLanguageResolver.java
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/support/StubTransformerResolver.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/AgentTest.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/resources/route-i.yaml

feat(jbang): camel-k agent sub-command

---

catalog/camel-report-maven-plugin/src/main/docs/camel-report-maven-plugin.adoc
catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/ValidateMojo.java

Camel Validate Plugin, make extra dependencies that contain camel routes configurable.

Camel validate transitive dependency

---

components/camel-milvus/pom.xml
parent/pom.xml

Add Milvus Client SDK version to parent POM

---

dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/ProcessTest.groovy

yaml-dsl: add a test with processor referenced by class name

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogDoc.java
dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

Update Kamelet catalog version used by JBang to 4.4.1

---

components/camel-aws/camel-aws2-ddb/src/main/java/org/apache/camel/component/aws2/ddbstream/transform/Ddb2StreamCloudEventDataTypeTransformer.java

Fixed DDB Stream transform prefix for event source
