apache/camel

core/camel-core/src/test/java/org/apache/camel/component/file/FileExclusiveReadLockCopyTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FileExclusiveReadManuelTest.java
Windows
it is based on readlock parameter which is mentioned as not supported in the documentation.
The code is throwing when used on Windows:
```
Caused by: java.lang.IllegalArgumentException: The readLock=fileLock
option is not supported on Windows
at org.apache.camel.component.file.GenericFileEndpoint.doInit(GenericFileEndpoint.java:1763)
```
=> Disable FileExclusiveReadManuelTest and FileExclusiveReadLockCopyTest on

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultComponentNameResolver.java
When some Components are loaded in development mode, the path is a file system one. On Windows, the separator is a backslash.
=> Fix DefaultComponentNameResolver on Windows

core/camel-core/src/test/java/org/apache/camel/language/simple/SimpleTest.java
The test was requesting a platform dependent line separator but the production code is not doing that. I adapted the test. I'm not sure if we want to adapt the test or change the runtime behavior to use platform dependent end of line for the pretty print of expressions
=> Fix SimpleTest pretty print of expression on Windows

components/camel-cassandraql/pom.xml, components/camel-zookeeper-master/pom.xml, components/camel-zookeeper/pom.xml
Re-enabling cassandraql component since the test suite is using `cassandra:4.1.2` and multi-arch support on s390x started with `cassandra:4.0.4`. Similar to the zookeeper components, multi-arch support on s390x for `zookeeper` started with zookeeper:3.8.1. 
I have tested all 3 components locally on s390x and they have passed.  
Also would like this to be backported to `4.0.x` if possible.
=> Enable Camel components on s390x

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/DependencyCopy.java
Fixes https://issues.apache.org/jira/browse/CAMEL-19939
Instead of export and invoking mvn copy dependency plugin, then we can see if we can use camels own camel-tooling-maven, and resolve dependencies, and gather urls to the local m2 files, which we can then copy directly from.
We need to include transitive dependencies, to ensure all JARs are included.
* Gets the list of direct dependencies by extending `DependencyList`
* Resolves each direct dependency and the transitive dependencies using the Maven API
On a simple project created with `camel init hello.java`, if we launch the next 2 commands:
```
$ jbang -Dcamel.jbang.version=4.0.1 camel@apache/camel dependency copy --output-directory lib.4.0
[jbang] Resolving dependencies...
[jbang]    org.apache.camel:camel-bom:4.0.1@pom
[jbang] …
```
=> CAMEL-19939: camel-jbang - dependency copy - Use camel-tooling-maven

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
Fixes https://issues.apache.org/jira/browse/CAMEL-19949
The JVM debugging port is currently hard-coded to 4004, we would like to add the ability to set a custom port
* Allow to set an integer as value of the argument ` --jvm-debug` to set a custom port
=> CAMEL-19949: camel-jbang - Allow to set a custom remote debugging port

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AdviceIterator.java
Move the state index out of the loop to avoid confusing it with the loop conditions
=> (chores) camel-core: code cleanup

components/camel-micrometer/pom.xml, components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/eventnotifier/MicrometerExchangeEventNotifierTest.java
Replaced Thread.sleep() with Awaitility class. Don't know if it's the right way to do this, however it's the only working scenario I could find
=> CAMEL-19536: replaced Thread.sleep() in camel-micrometer

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
extension in same folder
when using JBang and that we let auto-detect routes, the files without extensions were added as potential routes and, as expected, no RouteLoader were found. An IllegalArgumentExeption was thrown at this time.
Note that the regression is a side effect. Previously it was part of Routes but there wasn't `pre-parsing` and so there was no error (at least when doing an export)
=> CAMEL-19970 - Avoid IllegalArgumentException for file without

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
extension in same folder
when using JBang and that we let auto-detect routes, the files without extensions were added as potential routes and, as expected, no RouteLoader were found. An IllegalArgumentExeption was thrown at this time.
=> [4.0.x] 19970 backport fix illegal argument exception for file without extension

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
extension in same folder
when using JBang and that we let auto-detect routes, the files without extensions were added as potential routes and, as expected, no RouteLoader were found. An IllegalArgumentExeption was thrown at this time.
=> [3.21.x] CAMEL-19970 - Avoid IllegalArgumentException for file without

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
extension in same folder
when using JBang and that we let auto-detect routes, the files without extensions were added as potential routes and, as expected, no RouteLoader were found. An IllegalArgumentExeption was thrown at this time.
=> [3.x] Camel 3.x 19970 backport fix illegal argument exception when file without extension

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelCommand.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
Fixes https://issues.apache.org/jira/browse/CAMEL-19982
When `--jvm-debug` is used as last parameter in a run command like `camel run MyKafka.java --jvm-debug`, it fails with the next error `Error: missing required parameter`
* Allow to prevent throwing exception when there are no arguments left in `ParameterConsumer`
* Add support of empty arguments in `DebugConsumer`
=> CAMEL-19982: camel-jbang - Allow --jvm-debug as last parameter

core/camel-base/src/main/java/org/apache/camel/impl/converter/CoreTypeConverterRegistry.java
In most cases, the type checks will be false, which causes the JVM to hit its slow path checking the type.
This already happens subsequently, so adjust it to check only for equality at first.
=> (chores) camel-core: avoid hitting the JVM slow path

.github/actions/component-test/component-test.sh
When we have a component that has submodules, for now, we need to specify explicitly the list of submodules to test when using the GH `component-test` which leads to https://github.com/apache/camel/pull/11716#issuecomment-1761062508. Let's try to generate the list. 
* Auto-detect the pom files in subdirectories and include their directory to the list of projects to test
* Support the use case where the provided component name is incorrect
=> (chore) ci: auto-generate list of submodules

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java, core/camel-core/src/test/java/org/apache/camel/impl/DefaultEndpointRegistryTest.java, core/camel-support/src/main/java/org/apache/camel/support/EndpointHelper.java, core/camel-support/src/main/java/org/apache/camel/support/PatternHelper.java
=> Optimize EndpointHelper.matchEndpoint

core/camel-core-processor/src/main/java/org/apache/camel/processor/saga/SagaProcessor.java
This PR is about to avoid a NullPointerException during the errorHandling of creating a new saga.
Maybe we also need to check, if there is a backport needed
=> CAMEL-19996 avoid NPE when handling exception without coordinator

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/CamelInternalProcessor.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultReactiveExecutor.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultStreamCachingStrategy.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/SharedCamelInternalProcessor.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/StreamCachingHelper.java, core/camel-core-processor/src/main/java/org/apache/camel/processor/errorhandler/RedeliveryErrorHandler.java, core/camel-main/src/main/java/org/apache/camel/main/MainDurationEventNotifier.java, core/camel-support/src/main/java/org/apache/camel/support/ExchangeHelper.java, core/camel-support/src/main/java/org/apache/camel/support/MessageSupport.java, core/camel-support/src/main/java/org/apache/camel/support/UnitOfWorkHelper.java
Reduce the size of a few hot methods, so that their byte code size is smaller than 325 bytes, to increase the chance that the JVM will inline them when possible.
=> (chores) camel-core: reduce method size to force inlining

core/camel-core-processor/src/main/java/org/apache/camel/processor/errorhandler/RedeliveryErrorHandler.java
- Remove unnecessary variables
- Use final when possible
- Consolidate code
=> (chores) camel-core: minor cleanup in the RedeliveryErrorHandler

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java
Volatile only guarantees visibility, but not atomicity. This could mislead maintainers into thinking it's thread-safe when it's not.
This aligns this variable with the rest of the other member variables in this class.
=> (chores) camel-core: remove unnecessary volatile

components/camel-quartz/src/test/java/org/apache/camel/component/quartz/SpringQuartzConsumerTwoAppsClusteredFailoverTest.java, components/camel-quartz/src/test/java/org/apache/camel/component/quartz/SpringQuartzConsumerTwoAppsClusteredRecoveryTest.java, components/camel-quartz/src/test/java/org/apache/camel/routepolicy/quartz/SimpleScheduledCombinedRoutePolicyTest.java, components/camel-quartz/src/test/java/org/apache/camel/routepolicy/quartz/SpringQuartzTwoAppsClusteredFailoverTest.java
Replaced Thread.sleep() in camel-quartz, however CronTest8 in CronScheduledRoutePolicyTest is still unstable in some cases. Sometimes it throws CamelExecutionException even if you catch it. I would be glad of any advice.
=> CAMEL-19541: replaced Thread.sleep() in camel-quartz

docs/user-manual/modules/faq/pages/how-do-i-name-my-routes.adoc
Added the same example used for naming a route as YAML DSL
=> Added route naming example for YAML

components/camel-stax/pom.xml, components/camel-stax/src/test/java/org/apache/camel/language/xtokenizer/XMLTokenExpressionIteratorTest.java
* With Java 21, the order of attributes are different but it does not change the semantic
* factorize the xml-unit version in parent pom
=> CAMEL-20008 - Improve assertion to compare xml and not string in XMLTokenExpressionIteratorTest

components/camel-lra/src/main/java/org/apache/camel/service/lra/LRASagaService.java, components/camel-lra/src/test/java/org/apache/camel/service/lra/LRAClientTest.java, components/camel-lra/src/test/java/org/apache/camel/service/lra/LRASagaCoordinatorTest.java, components/camel-lra/src/test/java/org/apache/camel/service/lra/LRASagaServiceTest.java
Add additional unit-tests to increase test-coverage.
=> camel-lra: provide additional unit tests

dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/CustomResolver.java, dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/SetPropertyTest.groovy
https://issues.apache.org/jira/browse/CAMEL-20022
Now it emits the following:
```
2023-10-24 16:09:45,536 [main           ] WARN  CustomResolver                 - The kebab-case 'set-body' is deprecated and it will be removed in the next version. Use the camelCase 'setBody' instead.
2023-10-24 16:09:45,536 [main           ] WARN  CustomResolver                 - The kebab-case 'set-header' is deprecated and it will be removed in the next version. Use the camelCase 'setHeader' instead.
2023-10-24 16:09:48,669 [main           ] WARN  CustomResolver                 - The kebab-case 'set-property' is deprecated and it will be removed in the next version. Use the camelCase 'setProperty' instead.
```
=> CAMEL-20022: camel-yaml-dsl: Add WARN log if kebab-case is detected

components/camel-http/src/main/java/org/apache/camel/component/http/HttpProducer.java, components/camel-http/src/main/java/org/apache/camel/component/http/OAuth2ClientConfigurer.java, components/camel-http/src/test/java/org/apache/camel/component/http/HttpProducerContentTypeWithCharsetTest.java, components/camel-http/src/test/java/org/apache/camel/component/http/HttpProducerWithSpecialCharsBodyTest.java
A fix for [CAMEL-20037](https://issues.apache.org/jira/browse/CAMEL-20037) camel-http builds StringEntity with wrong contentEncoding.
camel-http must not create StringEntity having charset as content encoding
There was a change to a non related source file OAuth2ClientConfigurer.java.
=> [CAMEL-20037] camel-http builds StringEntity with wrong contentEncoding

components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/TestSupport.java
example of using:
```
executeSlowly(size, 3, TimeUnit.MILLISECONDS, (i) -> template.sendBody(url, "Message " + i));
```
=> CAMEL-19986: created throttling executor in camel-test

test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/common/KafkaProperties.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/ContainerLocalAuthKafkaService.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/ContainerLocalKafkaService.java
Add property _kafka.container_ to _camel-kafka-test-infra_ in order to externalize the image used. Otherwise, the default one is selected
- [ main ]
=> [kafka] Add infra property for custom image

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogBaseCommand.java
it allows to align with compatibility matrix of Camel Quarkus Notice the version scheme has been modified. there is no more `.Final`
I tested locally manually the basic use case on Fedora:
```
jbang --fresh -Dcamel.jbang.version=4.2.0-SNAPSHOT camel@apache/camel export --runtime=quarkus --gav=com.test:test-quarkus:1.0.0-SNAPSHOT --directory=exportdir Test.java
cd exportdir
./mvnw clean install
./mvnw quarkus:dev
```
=> CAMEL-20052 - Upgrade default Quarkus version to 3.5.0 in Camel JBang

components/camel-jms/src/main/docs/jms-component.adoc
This fixes the docs for the JMS component to show that e.g. `-` is converted to `_HYPHEN_` and not `HYPHEN` (in italics) as it was showing
Before: 
After:
https://github.com/josephearl/camel/blob/main/components/camel-jms/src/main/docs/jms-component.adoc#message-header-mapping
=> Fix message header mapping docs to show underscores

core/camel-core/src/test/java/org/apache/camel/support/cache/SimpleLRUCacheTest.java, core/camel-core/src/test/java/org/apache/camel/support/cache/SimpleSoftCacheTest.java, core/camel-support/src/main/java/org/apache/camel/support/DefaultLRUCacheFactory.java, core/camel-support/src/main/java/org/apache/camel/support/cache/SimpleLRUCache.java, core/camel-support/src/main/java/org/apache/camel/support/cache/SimpleSoftCache.java
Fix for https://issues.apache.org/jira/browse/CAMEL-20039
To prevent OOME, we need to provide a soft cache.
* Convert the static inner class `SimpleLRUCache` into a main class to be able to reuse it easily
* Add a decorator of Map called `SimpleSoftCache` to convert a map into a soft cache
* Modify the `DefaultLRUCacheFactory` to return a soft cache when calling methods `createLRUWeakCache` and `createLRUSoftCache`
=> CAMEL-20039: camel-core - SimpleLRUCache add support for soft cache

.github/actions/component-test/action.yaml, .github/actions/component-test/component-test.sh
* Use environment variables to avoid injections
The injection is no longer possible, the Github action simply fails
=> (chore) ci: convert component-test parameters to env vars

.gitmodules
To avoid potential vulnerabilities due to exposure of the `GITHUB_TOKEN`, it is recommended to use the Github action [create-or-update-comment](https://github.com/peter-evans/create-or-update-comment)
* Add the action as a git submodule since the action has not been approved at the Apache organization level
=> (chore) ci: add github action create-or-update-comment

.github/actions/component-test/action.yaml, .github/workflows/pr-comment.yml
To avoid potential vulnerabilities due to exposure of the `GITHUB_TOKEN`, it is recommended to use the Github action [create-or-update-comment](https://github.com/peter-evans/create-or-update-comment)
* Use the local github action create-or-update-comment
=> (chore) ci: avoid token exposure in pr-comment workflow

core/camel-api/src/main/java/org/apache/camel/converter/TypeConvertible.java
This avoids unnecessary costly comparisons when we can eagerly determine that the types won't match. We can avoid these comparisons when both the from types are the same, but their to type are not, because we only use the from types to compute the match.
=> CAMEL-20070: avoid unnecessary costly comparisons

parent/pom.xml, test-infra/camel-test-infra-opensearch/src/test/java/org/apache/camel/test/infra/opensearch/services/OpenSearchLocalContainerService.java
This PR upgrades OpenSearch and its Java client to v2.11.0 and v2.8.0 respectively so that we can ensure the existing code works with the latest version of them.
No corresponding JIRA issue since it just introduces minor version upgrade to OpenSearch.
=> Upgrade OpenSearch to 2.11.0 and its Java client to 2.8.0

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
Avoids losing the `--kamelets-version` setting when the user also specifies a custom Camel version with `--camel-version`
=> CAMEL-20086: Avoid losing kamelets-version setting in Camel JBang

components/camel-jackson/src/main/java/org/apache/camel/component/jackson/converter/JacksonTypeConverters.java, core/camel-base/src/main/java/org/apache/camel/impl/converter/TypeResolverHelper.java, core/camel-core/src/test/java/org/apache/camel/impl/converter/TypeResolverHelperTest.java
This is a fix to what looks like an accidental regression in Camel 3 -> Camel 4.
Fix for https://issues.apache.org/jira/browse/CAMEL-19828
Closes #CAMEL-19828
=> Converter lookup once again matches subclass converters like in Camel 3

components/camel-jackson/src/generated/java/org/apache/camel/component/jackson/converter/JacksonTypeConvertersLoader.java, components/camel-jackson/src/main/java/org/apache/camel/component/jackson/converter/JacksonTypeConverters.java
Also restore previous behavior for handling JsonNode
=> CAMEL-19828: added missing direct converter

docs/user-manual/modules/ROOT/pages/camel-4-migration-guide.adoc
Put the API changes of migration guide into a table and also add the removal of the getExtensions() method on the CamelContext.
=> CAMEL-20080 Update camel-4-migration-guide.adoc

components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/ThrottlingExecutor.java
Improved ThrottlingExecutor, so it can execute more different tasks. 
Usage: 
```
slowly().repeat(count_of_repetitions).awaiting(interval, TimeUnit.MILLISECONDS).beforeWait()
.beforeEach((i) -> task1)
.afterEach((i) -> task2)
.execute();
```
=> CAMEL-19986-1: Improved ThrottlingExecutor

core/camel-support/src/main/java/org/apache/camel/support/ScheduledPollConsumer.java
ScheduledPollConsumerHealthCheck uses the error count to determine if  the consumer is healthy or not. After polling messages, we know that  the consumer is healthy, and it is safe to reset the error markers.
=> CAMEL-20092: reset error counter before greedy poll

components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Consumer.java
Before this change, the exception would be logged in UnitOfWorkHelper  which catches any Throwable as the last option. The proper solution is  to catch it already in the consumer and let it be handled by the  exception handler.
=> CAMEL-20085: aws2-sqs - catch any SdkException when deleting message

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
Avoids losing the `--kamelets-version` setting when the user also specifies a custom Camel version with `--camel-version`
Manual backport of CAMEL-20086 to 4.0.x
=> [BACKPORT-4.0.x] CAMEL-20086: Avoid losing kamelets-version setting in Camel JBang

core/camel-support/src/main/java/org/apache/camel/support/ScheduledPollConsumer.java
ScheduledPollConsumerHealthCheck uses the error count to determine if  the consumer is healthly or not. After polling messages, we know that  the consumer is healthy, and it is safe to reset the error markers.
=> CAMEL-20092: reset error counter before greedy poll (BACKPORT #11937 to 3.x)

core/camel-support/src/main/java/org/apache/camel/support/ScheduledPollConsumer.java
ScheduledPollConsumerHealthCheck uses the error count to determine if  the consumer is healthly or not. After polling messages, we know that  the consumer is healthy, and it is safe to reset the error markers.
=> CAMEL-20092: reset error counter before greedy poll (BAKCPORT #11937 to 4.0.x)

core/camel-support/src/main/java/org/apache/camel/support/ScheduledPollConsumer.java
ScheduledPollConsumerHealthCheck uses the error count to determine if  the consumer is healthly or not. After polling messages, we know that  the consumer is healthy, and it is safe to reset the error markers.
=> CAMEL-20092: reset error counter before greedy poll (BACKPORT #11937 to 3.21.x)

.github/actions/component-test/component-test.sh, .github/actions/incremental-build/incremental-build.sh
When using the `component-test` Github action, in case of a failure, we would like to have the list of tests that failed to avoid having to look into the log file if possible.
* Reuse the same approach as the one used with the `incremental-build` to parse and list the errors in case of a build failure
* Update the `incremental-build` to parse and list the errors only in case of a failure
=> (chore) ci: add failing tests list on error

core/camel-api/src/main/java/org/apache/camel/support/jsse/BaseSSLContextParameters.java, core/camel-api/src/main/java/org/apache/camel/support/jsse/SSLContextParameters.java
Fix a typo in the javadocs, and also fix a visibility issue on `BaseSSLContextParameters` class hierarchy
=> Fix typo on SSLContextParameters javadocs

components/camel-jms/src/test/java/org/apache/camel/component/jms/AggregatedJmsRouteTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsInOnlyDisableTimeToLiveTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsProducerWithJMSHeaderTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsSimpleRequestCustomReplyToTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsSimpleRequestLateReplyTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/ManagedJmsSelectorTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/async/MyAsyncProducer.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsInOutExclusiveTopicRecipientListTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsInOutExclusiveTopicTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsSendToAlotOfDestinationWithSameEndpointTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/TempReplyToIssueTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/temp/JmsReconnectManualTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/temp/JmsRequestReplyTemporaryRefreshFailureOnStartupTest.java
Replaced Thread.sleep() in camel-jms.
=> CAMEL-19526: replaced the Thread.sleep with the best option or removed it.

components/camel-kafka/src/main/docs/kafka-component.adoc, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConfiguration.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/KafkaRecordProcessor.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/KafkaRecordProcessorFacade.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorOffUsingKafkaManualCommitIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorReplayOldMessagesIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorSeekIssueIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorWithBatchUsingAsynchCommitManagerIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorWithBatchUsingKafkaManualCommitIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorWithBatchUsingKafkaManualCommitRetryIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorWithBatchUsingSynchCommitManagerIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/testutil/CamelKafkaUtil.java, docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_21.adoc
This PR offers a fix for breakOnFirstError where the incorrect partition:offset when a forceCommit is done 
This PR is off the camel-3.21.x branch
CAMEL-20044 
CAMEL-19894
=> CAMEL-20044 fix to handle commit on breakOnFirstError

components/camel-stream/src/main/java/org/apache/camel/component/stream/StreamEndpoint.java
The documentation for the `httpHeaders` parameter of the `stream` component is ambiguous about how to format the parameter. It appears from the documentation that one would use `HEADER: VALUE`; but the code requires using `HEADER=VALUE`
Having issues getting this to run as there are other modules preventing the build.
=> [WIP] Improve the documentation for httpHeaders parameter.

test-infra/camel-test-infra-etcd3/src/test/java/org/apache/camel/test/infra/etcd3/services/Etcd3LocalContainerService.java
Updated to version 3.5.10
While looking at #12037 I noticed that our container image is outdated. This should bump to the latest version available (tested manually, it should be fine).
=> (chores) camel-test-infra-etcd3: updated test image to the latest version

components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbFindOperationIT.java
Due to [CAMEL-15604] we need to make use of Mongo container 4.4 version. BTW, minor versions (i.e. 4.4.6) should be used as multi-arch image (_x86, ppc64le, s390x_). Forcing the 4.4 version pull from docker hub, makes the test _MongoDbFindOperationIT_ fail
- [main]
=> [mongodb] Select right container image on find-operation test

test-infra/camel-test-infra-arangodb/src/test/java/org/apache/camel/test/infra/arangodb/services/ArangoDbContainer.java
Updates the container to 3.11.5
=> (chores) camel-test-infra-arangodb: update ArangoDB container to the latest version

test-infra/camel-test-infra-fhir/src/test/java/org/apache/camel/test/infra/fhir/services/FhirLocalContainerService.java
Updates the container to 6.8.3
=> (chores) camel-test-infra-fhir: update HAPI container to the latest version

components/camel-netty/src/main/java/org/apache/camel/component/netty/ChannelHandlerFactories.java, components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyBinaryProxyTest.java
Currently, using `ByteArrayDecoder` got through `ChannelHandlerFactories.newByteArrayDecoder()` twice or more in the same route causes Netty error indicating unsharable decoder reuse. This PR fixes this problem in accordance with the following document: https://camel.apache.org/components/4.0.x/netty-component.html#_using_non_shareable_encoders_or_decoders
=> CAMEL-20124: camel-netty - Fix ChannelHandlerFactories' usage of unsharable ByteArrayDecoder

components/camel-netty/src/main/docs/netty-component.adoc
This PR fixes an obsolete classname in the camel-netty document replaced in 00b64c8ad617e86de6be005f939f354d598bc92e.
=> Replace obsolete classname in the camel-netty document

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/smb.json, components/camel-smb/pom.xml, components/camel-smb/src/generated/resources/org/apache/camel/component/smb/smb.json, components/camel-smb/src/main/docs/smb-component.adoc, components/camel-smb/src/main/java/org/apache/camel/component/smb/SmbConfiguration.java, components/camel-smb/src/main/java/org/apache/camel/component/smb/SmbEndpoint.java
The first version of the SMB component is set to a snapshot version instead of a final version.
* Change the first version to 4.3
* Remove the logging dependencies as they are inherited from the direct parent pom file
* Set the scope of `camel-test-infra-smb` to `test`
=> CAMEL-19997: camel-smb - Update first version

core/camel-core-processor/src/main/java/org/apache/camel/processor/aggregate/AggregateProcessor.java, core/camel-core/src/test/java/org/apache/camel/processor/aggregator/AggregateCompletionByBatchConsumerTest.java
fix for
[[CAMEL-20139](https://issues.apache.org/jira/browse/CAMEL-20139)]: aggregate EIP: wrong correlation key set for the first aggregate exchange
When completing aggregation, original message of the completing message was passed as original messages for all batches. Now the completing message is passed as the original message only for its batch; for others, the aggregate message in the repository is passed as the original message.
=> [CAMEL-20139]: fix for incorrect correlation key in first aggregated message

components/camel-azure/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BlobChangeFeedOperationsIT.java, components/camel-azure/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BlobConsumerIT.java, components/camel-azure/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BlobOperationsIT.java, components/camel-azure/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BlobProducerIT.java
This is related to the following JUnit change https://github.com/junit-team/junit5/issues/3498
=> tearDown overload inherits @AfterEach  instead of the declared @AfterAll

components/camel-xmlsecurity/src/test/java/org/apache/camel/component/xmlsecurity/XmlSignatureTest.java, parent/pom.xml
The removed test was useless because now secureValidation is enabled by default.
=> Upgrade XMLSecurity to version 4.0.0

components/camel-quartz/src/main/docs/quartz-component.adoc, components/camel-quartz/src/main/java/org/apache/camel/component/quartz/CamelJob.java, components/camel-quartz/src/main/java/org/apache/camel/component/quartz/QuartzEndpoint.java, components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzCronRouteWithStartDateEndDateTest.java
Cherry-pick of https://github.com/apache/camel/pull/12089
- [ x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL-20115) filed for the change (usually before you start working on it).
- [x ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes
=> CAMEL-20115: Support for Start Date and End Date in camel-quartz

docs/user-manual/modules/ROOT/pages/camel-4-migration-guide.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_3.adoc
Added examples to the migration guide showing changes required to throttle EIP expressions now that throttle uses the number of concurrent requests as the throttling measure.
=> Camel 16099: add throttle changes to migration guide

components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpSupport.java, components/camel-platform-http-vertx/src/test/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpEngineTest.java
Optimize the code by avoiding creating multiple Objects and iterating several times on the inner structures supporting the MultiMap.
Also adds a simple test that uses duplicated parameters when calling the service
=> (chores) camel-platform-http-vertx: simplify applying headers

components/camel-jetty-common/src/main/java/org/apache/camel/component/jetty/JettyHttpComponent.java
Fixes https://issues.apache.org/jira/browse/CAMEL-20152 for 3.21
In the case of multipart, the content is kept in memory which can lead to an OOME, it is due to the fact that the `fileSizeThreshold` is set to `0` by default which should mean that the content is stored on disk according to the Jakarta Javadoc but it is not what the Jetty code expects.
* Set the default file size threshold to 10 MB by default
=> CAMEL-20152: camel-jetty - Fix a file size threshold

components/camel-spring-xml/src/test/java/org/apache/camel/spring/processor/SpringThrottlerGroupingTest.java, components/camel-spring-xml/src/test/java/org/apache/camel/spring/processor/SpringThrottlerMethodCallTest.java, components/camel-spring-xml/src/test/java/org/apache/camel/spring/processor/SpringThrottlerTest.java, components/camel-spring-xml/src/test/resources/org/apache/camel/spring/processor/ThrottlerGroupingTest.xml, components/camel-spring-xml/src/test/resources/org/apache/camel/spring/processor/ThrottlerMethodCallTest.xml, components/camel-spring-xml/src/test/resources/org/apache/camel/spring/processor/throttler.xml, core/camel-core/src/test/java/org/apache/camel/processor/ThrottlerMethodCallTest.java, core/camel-core/src/test/java/org/apache/camel/processor/ThrottlerTest.java, core/camel-core/src/test/java/org/apache/camel/processor/ThrottlingGroupingTest.java
Updated camel-spring-xml throttle tests to use max number of concurrent requests instead of requests per time period as per changes to the throttle eip.
=> CAMEL-20158: enable camel-spring-xml throttle tests

parent/pom.xml
Upgrade spring-* versions to match the versions in 2.7.18 spring-boot-dependencies
=> Upgrades to match versions in 2.7.18 spring-boot-dependencies

core/camel-core/src/test/java/org/apache/camel/processor/ThrottlerTest.java, core/camel-core/src/test/java/org/apache/camel/processor/ThrottlingGroupingTest.java
In throttle tests, wait until tasks have completed before shutting down executors to avoid producing warning messages in the logs due to thread interruption.
=> CAMEL-20158: wait till tasks finish before shutting down executors

components/camel-file/pom.xml, components/camel-file/src/main/java/org/apache/camel/component/file/GenericFileEndpoint.java, components/camel-file/src/main/java/org/apache/camel/component/file/GenericFileProducer.java, core/camel-core/src/test/java/org/apache/camel/component/file/FileProducerChecksumFileAlgorithmTest.java
Hi @davsclaus, JIRA issue (CAMEL-20172) and PR as requested.
=> CAMEL-20172: Add checksum feature to camel-file/ftp

core/camel-core/src/test/java/org/apache/camel/processor/ThrottlerTest.java, core/camel-core/src/test/java/org/apache/camel/processor/ThrottlingGroupingTest.java
Shutdown the executor cleanly so that it doesn't produce any warnings due to thread interruption.
=> CAMEL-20158: await executor termination after shutdown

Jenkinsfile.jdk21, core/camel-core/src/test/java/org/apache/camel/impl/DefaultExecutorServiceManagerTest.java, core/camel-core/src/test/java/org/apache/camel/processor/WireTapAbortPolicyTest.java, core/camel-core/src/test/java/org/apache/camel/processor/aggregator/AggregateTimeoutWithNoExecutorServiceTest.java, core/camel-management/src/test/java/org/apache/camel/management/DualManagedThreadPoolProfileTest.java, core/camel-management/src/test/java/org/apache/camel/management/DualManagedThreadPoolWithIdTest.java, core/camel-management/src/test/java/org/apache/camel/management/ManagedRouteRemoveWireTapTest.java, core/camel-management/src/test/java/org/apache/camel/management/ManagedThreadPoolProfileTest.java, core/camel-management/src/test/java/org/apache/camel/management/ManagedThreadPoolTest.java, core/camel-management/src/test/java/org/apache/camel/management/ManagedThreadPoolWithIdTest.java, core/camel-support/pom.xml, core/camel-support/src/main/java21/org/apache/camel/support/DefaultThreadPoolFactory.java, core/camel-util/pom.xml, core/camel-util/src/main/java/org/apache/camel/util/concurrent/ThreadFactoryTypeAware.java, core/camel-util/src/main/java/org/apache/camel/util/concurrent/ThreadType.java, core/camel-util/src/main/java21/org/apache/camel/util/concurrent/CamelThreadFactory.java, core/camel-util/src/main/java21/org/apache/camel/util/concurrent/ThreadType.java, docs/user-manual/modules/ROOT/pages/threading-model.adoc
Fixes https://issues.apache.org/jira/browse/CAMEL-20187
Java 21 brings virtual threads and we would like to have a preview of it in Camel.
* Propose a Java 21 version of `DefaultThreadPoolFactory` and `CamelThreadFactory` inside multi-release jars
=> Add basic support of virtual threads

core/camel-core/src/test/java/org/apache/camel/TestSupport.java, core/camel-core/src/test/java/org/apache/camel/component/file/FileProducerCharsetUTFtoISOConvertBodyToTest.java
In slow systems, the interval between the exchange completion and the data being written to the disk may cause the test to read an empty file. This should give an extra time for that to happen.
=> (chores) core: wait for I/O to reduce flakiness

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/dataformats/parquetAvro.json, catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/models/parquetAvro.json, catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd, components/camel-parquet-avro/src/generated/java/org/apache/camel/dataformat/parquet/avro/ParquetAvroDataFormatConfigurer.java, components/camel-parquet-avro/src/generated/resources/org/apache/camel/dataformat/parquet/avro/parquetAvro.json, components/camel-parquet-avro/src/main/java/org/apache/camel/dataformat/parquet/avro/ParquetAvroDataFormat.java, components/camel-parquet-avro/src/main/java/org/apache/camel/dataformat/parquet/avro/ParquetIterator.java, components/camel-parquet-avro/src/main/java/org/apache/camel/dataformat/parquet/avro/ParquetUnmarshalOnCompletion.java, components/camel-parquet-avro/src/test/java/org/apache/camel/dataformat/parquet/avro/ParquetAvroDataFormatUnmarshalLazyLoadTest.java, core/camel-core-model/src/generated/resources/org/apache/camel/model/dataformat/parquetAvro.json, core/camel-core-model/src/main/java/org/apache/camel/model/dataformat/ParquetAvroDataFormat.java, core/camel-xml-io/src/generated/java/org/apache/camel/xml/in/ModelParser.java, core/camel-xml-io/src/generated/java/org/apache/camel/xml/out/ModelWriter.java, core/camel-yaml-io/src/generated/java/org/apache/camel/yaml/out/ModelWriter.java, dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/ModelDeserializers.java, dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camelYamlDsl.json
Currently, the parquet-avro data format will read all records at once in to memory. This PR adds an option `lazyLoad` that reads records one by one via an iterator. This avoids some potential memory issues when processing large parquet files.
There is no JIRA issue for this PR, I'm not sure the process to have one created. I'll gladly help get one created and update anything I need to on this PR.
=> camel-parquet-avro: Add the capability to lazy load records during unmarshal

test-infra/camel-test-infra-mongodb/src/test/java/org/apache/camel/test/infra/mongodb/services/MongoDBLocalContainerService.java
without `asCompatibleSubstituteFor` the substitution was not working.
=> Fix to configurable mongodb image

components/camel-cloudevents/src/main/java/org/apache/camel/component/cloudevents/CloudEvent.java, components/camel-csimple-joor/src/test/java/org/apache/camel/language/csimple/joor/OriginalSimpleTest.java, components/camel-knative/camel-knative-component/src/main/java/org/apache/camel/component/knative/ce/AbstractCloudEventProcessor.java, core/camel-api/src/main/java/org/apache/camel/Clock.java, core/camel-api/src/main/java/org/apache/camel/Exchange.java, core/camel-api/src/main/java/org/apache/camel/Message.java, core/camel-api/src/main/java/org/apache/camel/PooledExchange.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/CamelInternalProcessor.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultInflightRepository.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/PooledExchangeFactory.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/PooledProcessorExchangeFactory.java, core/camel-core/src/test/java/org/apache/camel/component/mock/MockEndpointTimeClauseTest.java, core/camel-core/src/test/java/org/apache/camel/impl/event/EventNotifierExchangeCompletedTest.java, core/camel-core/src/test/java/org/apache/camel/language/simple/SimpleTest.java, core/camel-core/src/test/java/org/apache/camel/processor/ExchangeCreatedTimestampTest.java, core/camel-core/src/test/java/org/apache/camel/support/AbstractExchangeTest.java, core/camel-management/src/main/java/org/apache/camel/management/mbean/ManagedBacklogDebugger.java, core/camel-support/src/main/java/org/apache/camel/support/AbstractExchange.java, core/camel-support/src/main/java/org/apache/camel/support/DefaultExchange.java, core/camel-support/src/main/java/org/apache/camel/support/DefaultPooledExchange.java, core/camel-support/src/main/java/org/apache/camel/support/LanguageHelper.java, core/camel-support/src/main/java/org/apache/camel/support/MessageHelper.java, core/camel-support/src/main/java/org/apache/camel/support/MonotonicClock.java, core/camel-support/src/main/java/org/apache/camel/support/ResetableClock.java, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_4.adoc
This is the first part of the task. At this moment, it still relies on System.currentTimeMillis to compute the elapsed time in order to retain the current behavior and ensure the refactoring is solid. A subsequent PR will then add a new field to track the duration separatelly from the real clock part.
=> CAMEL-20225: move time-related information to a separate abstraction

core/camel-management/src/main/java/org/apache/camel/management/mbean/ManagedBacklogDebugger.java, core/camel-support/src/main/java/org/apache/camel/support/MonotonicClock.java, core/camel-support/src/main/java/org/apache/camel/support/ResetableClock.java, core/camel-util/src/main/java/org/apache/camel/util/TimeUtils.java
This brings a few additional improvements:
1. Use a monotonic clock for calculating duration
2. Consolidate more code into the `elapsed` method 
3. Deprecate ad-hoc duration calculations
=> CAMEL-20225: use the clock API when possible for exchange duration calculations

README.md, core/camel-core-engine/src/main/docs/modules/eips/pages/change-data-capture.adoc, core/camel-core-engine/src/main/docs/modules/eips/pages/kamelet-eip.adoc, docs/user-manual/modules/ROOT/pages/bean-integration.adoc, docs/user-manual/modules/ROOT/pages/health-check.adoc, docs/user-manual/modules/ROOT/pages/route-configuration.adoc, docs/user-manual/modules/ROOT/pages/route-reload.adoc, dsl/camel-kamelet-main/src/main/docs/kamelet-main.adoc
Since https://github.com/apache/camel-examples/pull/129 some links are broken in docs.
=> Fix examples links in docs

docs/user-manual/modules/ROOT/nav.adoc, docs/user-manual/modules/ROOT/pages/camel-jbang-k.adoc, docs/user-manual/modules/ROOT/pages/camel-jbang.adoc, dsl/camel-jbang/camel-jbang-core/pom.xml, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelCommand.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelJBangMain.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/CompressionHelper.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationDelete.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationGet.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationLogs.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationRun.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/KubeBaseCommand.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/KubeCommand.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/KubernetesHelper.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/SourceScheme.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/TraitHelper.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/TraitProfile.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/version/VersionGet.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/Printer.java, dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/StringPrinter.java, dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationDeleteTest.java, dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationGetTest.java, dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationLogsTest.java, dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationRunTest.java, dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/KubeBaseTest.java, dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/KubeCommandMainTest.java, dsl/camel-jbang/camel-jbang-core/src/test/resources/org/apache/camel/dsl/jbang/core/commands/k/integration.yaml, dsl/camel-jbang/camel-jbang-core/src/test/resources/pod.yaml, dsl/camel-jbang/camel-jbang-core/src/test/resources/route.yaml, parent/pom.xml
- Adds new subcommands to Camel JBang that allow to manage Camel K integrations
- run command to create Integrations on Kubernetes
- list command to list all Integrations on the cluster namespace
- delete command to remove Integrations
- logs command to print log output of a running Integration
Users are able to manage Camel K integrations running on Kubernetes.
The implementation uses the fabric8 Kubernetes client and the Camel K Integration CRDs to manage the integrations on the cluster.
Users are able to call
```
camel k run route.groovy
```
Where `k` provides a set of new subcommands related to running Camel routes on Kubernetes in the form of Camel K integrations.
Not included in this PR is documentation of the new commands. I wanted to get feedback on this first. Also I am …
=> CAMEL-20251: Add Camel K commands to Camel JBang

components/camel-jms/src/test/java/org/apache/camel/component/jms/BrowsableQueueTest.java, core/camel-api/src/main/java/org/apache/camel/CamelContext.java, core/camel-api/src/main/java/org/apache/camel/ContextEvents.java, core/camel-api/src/main/java/org/apache/camel/Exchange.java, core/camel-api/src/main/java/org/apache/camel/clock/Clock.java, core/camel-api/src/main/java/org/apache/camel/clock/ContextClock.java, core/camel-api/src/main/java/org/apache/camel/clock/EventClock.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java, core/camel-core/src/test/java/org/apache/camel/support/AbstractExchangeTest.java, core/camel-support/src/main/java/org/apache/camel/support/DefaultExchange.java, core/camel-support/src/main/java/org/apache/camel/support/DefaultPooledExchange.java, core/camel-support/src/main/java/org/apache/camel/support/ResetableClock.java
This also makes the clock API more generic and usable for other use cases besides tracking exchanges
=> CAMEL-20257: convert AbstractContext to the clock API

components/camel-platform-http-vertx/pom.xml, components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpServer.java, components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpServerConfiguration.java, components/camel-platform-http-vertx/src/test/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpSessionTest.java, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_4.adoc
Draft code demonstrating a Vertx server handler implementation that manages server-side sessions and session cookie handling.
=> CAMEL-20019: demo session handler implementation

core/camel-api/src/main/java/org/apache/camel/ValidationException.java
Fix a typo on `ValidationException` javadoc
Building locally with `Apache Maven 4.0.0-alpha-9` gives the following error:
```
[INFO] Scanning for projects...
[INFO] Loaded 7 groupId for remote repository atlassian
[ERROR] Some problems were encountered while processing the POMs
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.apache.camel:camel-report-maven-plugin:4.4.0-SNAPSHOT (~/work/camel/catalog/camel-report-maven-plugin/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.apache.camel:camel-catalog-common:jar -> version ${project.version} vs 4.4.0-SNAPSHOT @ line 232, column 9
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the '-e' switch
[ERROR] …
```
=> Javadoc typo

.github/actions/component-test/component-test.sh
Fixes https://issues.apache.org/jira/browse/CAMEL-20296
The GitHub action component-test tries to build maven projects that are integration tests while it should ignore them.
* Exclude folders related to integration tests when trying to autodetect the root of sub-projects.
=> CAMEL-20296: component-test - Exclude IT folders

components/camel-paho-mqtt5/pom.xml
There are no mosquitto containers for this platform
=> (chores) camel-paho-mqtt5: disable tests on s390x

test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSLocalContainerService.java, test-infra/camel-test-infra-hashicorp-vault/src/test/java/org/apache/camel/test/infra/hashicorp/vault/services/HashicorpVaultLocalContainerService.java
Some containers are known to be flaky during startup, provide a "reasonable" retry number (5) attempts to workaround it and not affect the tests.
=> CAMEL-20279 - provide retry attempts for known flaky container start during tests

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorWithBatchUsingSynchCommitManagerIT.java
KafkaBreakOnFirstErrorWithBatchUsingSynchCommitManagerIT (should also be skipped)
=> (chores) camel-kafka: disable flaky tests on ppc64le

components/camel-paho-mqtt5/src/test/java/org/apache/camel/component/paho/mqtt5/PahoMqtt5ReconnectAfterFailureIT.java
=> (chores) camel-paho-mqtt5: fix another integration/unit test mismatch

core/camel-core-engine/src/main/docs/modules/eips/pages/step-eip.adoc
=> Fix typo acitvemq in step-eip.adoc

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/KafkaRecordProcessor.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/KafkaRecordProcessorFacade.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/ProcessingResult.java
With merge of PR #11959  can consider removing the passing of `lastResult` 
It isn't used and may make future refactors and debugging more difficult
Target
[camel-3](https://issues.apache.org/jira/browse/CAMEL-3).21.x
Tracking
[CAMEL-20044](https://issues.apache.org/jira/browse/CAMEL-20044)
=> CAMEL-20044 remove lastResult from Kafka Camel component

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultRoute.java
This should prevent running out of memory due to constantly increasing the service list
=> CAMEL-20231: clear the services on initialization

components/camel-seda/src/main/java/org/apache/camel/component/seda/SedaProducer.java
Leftover from 1c73ce90679ab0cc5e5bdb36b4e221462af7ef56
=> CAMEL-20297 camel-seda: do not swallow interrupted exceptions (leftover)

components/camel-spring-xml/src/test/java/org/apache/camel/spring/interceptor/TransactedStackSizeBreakOnExceptionTest.java
Use a more lenient check due to test being flaky on shared CI environments
=> (chores) camel-spring-xml: try to reduce flakiness in test

components/camel-cassandraql/src/main/docs/cql-component.adoc, components/camel-cassandraql/src/main/java/org/apache/camel/processor/aggregate/cassandra/CassandraAggregationRepository.java, components/camel-cassandraql/src/main/java/org/apache/camel/processor/aggregate/cassandra/CassandraCamelCodec.java, components/camel-cassandraql/src/test/java/org/apache/camel/processor/aggregate/cassandra/CassandraCamelCodecTest.java, components/camel-cassandraql/src/test/java/org/malicious/example/Employee.java, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_4.adoc
=> CAMEL-20306 - Camel-CassandraQL: Add ObjectInputFilter String pattern parameter in CassandraAggregationRepository to be used in unmarshall operations

core/camel-api/src/main/java/org/apache/camel/spi/TransformerResolver.java, core/camel-core/src/test/java/org/apache/camel/processor/transformer/ByteArrayDataTypeTransformerTest.java, core/camel-core/src/test/java/org/apache/camel/processor/transformer/StringDataTypeTransformerTest.java, dsl/camel-yaml-dsl/camel-yaml-dsl/src/main/java/org/apache/camel/dsl/yaml/YamlRoutesBuilderLoader.java, dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/PipeLoaderTest.groovy
- Support default data type prefix "camel:" when resolving transformers
- Support for optional "scheme" property in YAML DSL on dataTypes/in and dataTypes/out nodes
Enables users to reference data types in Pipes like this:
```yaml
dataTypes:
out:
scheme: aws2-s3
format: application-cloudevents
```
Enables users to use the default data type scheme prefix
```yaml
dataTypes:
out:
scheme: camel
format: text-plain
```
=> Improve data type resolving in YAML Pipe loader

components/camel-cloudevents/src/test/java/org/apache/camel/component/cloudevents/transformer/CloudEventJsonDataTypeTransformerTest.java
=> Camel-CloudEvents: Fixed failing test

dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationRunTest.java
The value of the enum must not be fully uppercase anymore, even though it is then written with full uppercase in the resulting yaml. I guess it is the result of upgrade from kubernetes client java 6.9.2 to 6.10.0
to fix main branch failing with:
```
org.apache.camel.RuntimeCamelException: Failed to parse trait options
at org.apache.camel.dsl.jbang.core.commands.k.TraitHelper.parseTraits(TraitHelper.java:81)
at org.apache.camel.dsl.jbang.core.commands.k.IntegrationRun.doCall(IntegrationRun.java:237)
at org.apache.camel.dsl.jbang.core.commands.k.IntegrationRunTest.shouldAddTraits(IntegrationRunTest.java:70)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at java.base/java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:194)
at …
```
=> Fix main branch for Jbang Camel K IntegrationRunTest

components/camel-etcd3/src/main/java/org/apache/camel/component/etcd3/processor/aggregate/Etcd3AggregationRepository.java
This retains previous behavior, but does restore the interrupt status.
=> CAMEL-20297 camel-etcd3: do not swallow interrupted exceptions

components/camel-kafka/src/main/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepository.java
Use a single Kafka consumer with `assign()` call to consume all cached entries from the beginning of the Kafka topic.
The existing implementation of `KafkaIdempotentRepository` may fail to restore the cached entries on application restart. This implementation is based on `KafkaConsumer.subscribe()` method and KafkaConsumer rebalancing. It navigates the Kafka consumer to the beginning of the Kafka topic using `ConsumerRebalanceListener.onPartitionsAssigned()` callback. However, the rebalancing occurs asynchronously. Therefore there is a chance, that first few calls to `KafkaConsumer.poll()` will be done before the consumer gets navigated to the beginning of the KafkaTopic. Hence, KafkaConsumer gets zero records from the Kafka topic and `KafkaIdempotentRepository` gets initialized with …
=> CAMEL-20218: Use a single Kafka consumer with assign() call

.github/actions/component-test/component-test.sh
Fixes https://issues.apache.org/jira/browse/CAMEL-20335
The GitHub Action `component-test` doesn't work as expected with components like `camel-spring-xml` because it tries to build projects in the target folder.
* Exclude the target folders when trying to autodetect the root of sub-projects.
=> CAMEL-20335: component-test - Exclude target folders

components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppConsumer.java, components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppProducer.java, components/camel-smpp/src/test/java/org/apache/camel/component/smpp/SmppConsumerTest.java, components/camel-smpp/src/test/java/org/apache/camel/component/smpp/SmppProducerTest.java, parent/pom.xml
The SMPP peer I am using Camel against sends an Unbind after an inactivity period of 60 seconds on the connection. This means that the logical connection has been terminated and (as I understand the SMPP spec) the peer that received the Unbind is supposed to terminate the connection as the session cannot be recovered.
SmppProducer/SmppConsumer don't react on this event and trying to send a SMS after receiving the Unbind ends up in exceptions (`org.apache.camel.component.smpp.SmppException: java.io.IOException: Cannot submitShortMessage while session 0f46dc52 in state UNBOUND`)
This PR adds code to catch the UNBOUND event in both SmppProducer/SmppConsumer and also closes the previous test gap of the internalSessionStateListener being uncovered in tests.
=> CAMEL-20121 reconnect SMPP session after receiving Unbound

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
avoid file name analysis if the name is a github link, there are some duplicated lines for github links checks.
=> github links are handled later on

components/camel-rest-openapi/src/test/java/org/apache/camel/component/rest/openapi/RestOpenApiRequestValidationTest.java
The swagger-parse upgrade broke this test.
Ref: 394084605ec909f1aed514734166dd45da35af97
=> CAMEL-20353: disabled camel-rest-openapi test

components/camel-json-validator/src/test/java/org/apache/camel/component/jsonvalidator/JsonValidationExceptionTest.java
The way the hashcode for ValidationMessage is computed changed after the upgrade. Therefore, ensure every message has a different key to allow them to be included in the set.
Ref: 9dc9af6bf78dc3aa2ce253fee4cb86de06ee8d2a
=> (chores) camel-json-validator: fix test

parent/pom.xml
I'd like to suggest reverting log4j to version 2.21.1 to match the version in spring-boot-dependencies 3.2.1.       It looks like the upgrades to 2.22.1 were done via dependabot
https://github.com/apache/camel/pull/12613
https://github.com/apache/camel/pull/12110
The camel-spring-boot itests are reporting library version mismatches with 2.22.1
[INFO] Running org.apache.camel.itest.springboot.CamelActivemqTest
WARN>>> Library version mismatch found.
Found mismatch for dependency org.apache.logging.log4j:log4j:
- org.apache.logging.log4j:log4j-api:jar: --> [2.21.1, 2.22.1]
- org.apache.logging.log4j:log4j-to-slf4j:jar: --> [2.21.1]
=> Revert log4j to version 2.21.1 to match spring-boot-dependencies

components/camel-elytron/pom.xml, parent/pom.xml
Wildfly-elytron 2.2.x has migrated from the deprecated javax.json to jakarta.json:
https://github.com/wildfly-security/wildfly-elytron/blame/2.2.x/auth/realm/token/src/main/java/org/wildfly/security/auth/realm/token/validator/JwtValidator.java#L30
Camel uses jakarta.json v2.1.3, and `parson` is the default provider:  
https://github.com/jakartaee/jsonp-api/blob/2.1.3/api/src/main/java/jakarta/json/spi/JsonProvider.java#L79.
=> CAMEL-20278: upgrade wildfly-elytron to 2.x

components/camel-kafka/src/main/java/org/apache/camel/processor/idempotent/kafka/KafkaConsumerUtil.java, components/camel-kafka/src/main/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepository.java, components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaConsumerUtilsTest.java, components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryPersistenceIT.java
Make sure that the local cache of KafkaIdempotentRepository has been fully initialized on application startup. This is needed to prevent duplicates from occurring after the application has restarted.
The main branch
https://issues.apache.org/jira/browse/CAMEL-20373
- [ v] I checked that each commit in the pull request has a meaningful subject line and body.
- [v ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes
=> CAMEL-20218: On startup populate local cache synchronously

dsl/camel-jbang/camel-jbang-it/README.adoc, dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/JBangTestSupport.java, test-infra/camel-test-infra-cli/README.adoc, test-infra/camel-test-infra-cli/src/test/java/org/apache/camel/test/infra/cli/common/CliProperties.java, test-infra/camel-test-infra-cli/src/test/java/org/apache/camel/test/infra/cli/services/CliBuiltContainer.java, test-infra/camel-test-infra-cli/src/test/java/org/apache/camel/test/infra/cli/services/CliLocalContainerService.java, test-infra/camel-test-infra-cli/src/test/resources/org/apache/camel/test/infra/cli/services/Dockerfile, test-infra/camel-test-infra-cli/src/test/resources/org/apache/camel/test/infra/cli/services/entrypoint.sh
It is possible to set external maven repositories, custom trusted certificates and set custom hosts file entries. Moreover the JBang downloaded JDK has been replaced by the system JDK
=> CAMEL-20379: Camel CLI infra, add maven repos config

components/camel-joor/src/main/java/org/apache/camel/language/joor/JavaJoorClassLoader.java, components/camel-platform-http-main/src/main/java/org/apache/camel/component/platform/http/main/jolokia/JolokiaHttpRequestHandlerSupport.java, components/camel-rest-openapi/src/main/java/org/apache/camel/component/rest/openapi/RestOpenApiValidationException.java, components/camel-ssh/src/main/java/org/apache/camel/component/ssh/SshUtils.java, core/camel-core-engine/src/main/java/org/apache/camel/impl/DefaultDumpRoutesStrategy.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
- Use platform-specific new line characters
- Use format-specifiers instead of concatenating strings
=> (chores) minor code cleanups

components/camel-google/camel-google-calendar/src/test/java/org/apache/camel/component/google/calendar/stream/GoogleCalendarStreamConsumerIT.java, components/camel-google/camel-google-mail/src/test/java/org/apache/camel/component/google/mail/stream/GoogleMailStreamConsumerIT.java, components/camel-google/camel-google-sheets/src/test/java/org/apache/camel/component/google/sheets/SheetsSpreadsheetsIT.java, components/camel-google/camel-google-sheets/src/test/java/org/apache/camel/component/google/sheets/SheetsSpreadsheetsValuesIT.java, components/camel-google/camel-google-sheets/src/test/java/org/apache/camel/component/google/sheets/stream/SheetsStreamConsumerIT.java
Fix a few integration tests that were named incorrectly - as I pointed on one of the comments on PR #12966. 
This only affects camel-google-calendar, camel-google-mail and camel-google-sheets.
=> CAMEL-20389: fix incorrectly named Integration tests

components/camel-tracing/src/main/java/org/apache/camel/tracing/ExtractAdapter.java, components/camel-tracing/src/main/java/org/apache/camel/tracing/propagation/CamelHeadersExtractAdapter.java, components/camel-tracing/src/main/java/org/apache/camel/tracing/propagation/CamelMessagingHeadersExtractAdapter.java, components/camel-tracing/src/test/java/org/apache/camel/tracing/propagation/CamelMessagingHeadersExtractAdapterTest.java
See https://camel.zulipchat.com/#narrow/stream/257298-camel/topic/Micrometer.20Observation
When a camel-application is called with tracing-headers (http-request) that are not exactly in the same case as the implementation of the propagation demands (eg "X-B3-TraceId" / "traceparent") - then the implementation can not find these header values.
=> CAMEL-20387: tracing-headers should be case insensitive

.github/actions/component-test/action.yaml, .github/workflows/pr-comment.yml
=> Make component-test runnable only by organization members

test-infra/camel-test-infra-cli/src/test/java/org/apache/camel/test/infra/cli/services/CliLocalContainerService.java
In camel-test-infra-cli module, it fixes the version info retrieved when a custom Camel is used (User configuration)
=> Camel JBang test infra: fix version info

core/camel-base/src/generated/java/org/apache/camel/converter/CamelBaseBulkConverterLoader.java, core/camel-core/src/test/java/org/apache/camel/impl/converter/TypeConvertersTest.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/TypeConverterLoaderGeneratorMojo.java
String to short type conversion fails with:
`NoTypeConversionAvailable No type converter available to convert from type: java.lang.String to the required type: short`
to reproduce it just test:
`assertEquals(Short.parseShort("1"), context.getTypeConverter().mandatoryConvertTo(short.class, "1"));`
=> CAMEL-20399: String to short type conversion fails

dsl/camel-yaml-dsl/camel-yaml-dsl/src/main/java/org/apache/camel/dsl/yaml/YamlRoutesBuilderLoader.java, dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/PipeLoaderTest.groovy, dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/support/YamlTestSupport.groovy
- Pipes may reference a Knative broker as a source/sink. 
- Properly configure the Knative component endpoint URI (knative:event/my-event-type?kind=Broker&name=default) on the resulting route definition when the Pipe uses a Knative broker reference
Example Pipe:
```yaml
apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
  name: timer-event-source                  
spec:
  source:
    ref:
      kind: Kamelet
      apiVersion: camel.apache.org/v1
      name: timer-source
    properties:
      message: "Hello world!"
  sink:
    ref:
      kind: Broker
      apiVersion: eventing.knative.dev/v1
      name: foo-broker
    properties:
      type: org.apache.camel.event.foo
```
- Make sure to always use Locale.ENGLISH when performing schema validation in YAML DSL unit tests (avoids assertion …
=> CAMEL-20403: Support Knative Broker reference in Pipe YAML

components/camel-zeebe/pom.xml
Remove unnecessary profile to avoid polluting/over-complicating the build
=> (chores) camel-zeebe: avoid polluting the build

components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpConsumerFactory.java, components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpProducerFactory.java, components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpSupport.java
- Lookup router and vertx instance when not explicitly set on the factory
- Avoids Nullpointer exception when for instance running the Knative component with Camel JBang
=> camel-knative-http: Avoid Nullpointer on KnativeHttpProducer/Consumer factory

components/camel-jms/src/main/docs/jms-component.adoc
- Fixed section order
- Grammar fixes
=> CAMEL-20410: documentation fixes for camel-jms

core/camel-core/src/test/java/org/apache/camel/util/ObjectHelperTest.java, core/camel-util/src/main/java/org/apache/camel/util/ObjectHelper.java
This reverts commit c7b8f0c6fea02ffd5194c7abd33b92c9c8dc6f3c.
This was a mistake. Let's revert it to avoid confusion.
=> Revert "(chores) camel-core: added the ability to provide a cause to ObjectHelper.notNull"

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/DevModeITCase.java, dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/RunCommandITCase.java, dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/RunCommandOnMqttITCase.java, dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/VersionCommandITCase.java, dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/JBangTestSupport.java, dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/JiraIssue.java, test-infra/camel-test-infra-cli/src/test/java/org/apache/camel/test/infra/cli/services/CliLocalContainerService.java, test-infra/camel-test-infra-cli/src/test/java/org/apache/camel/test/infra/cli/services/CliService.java
- Skip headless incompatible test, conditionally
- Run specific version test conditionally, due to CAMEL-20426
- Make the file writeble for external user in dev mode
- Add generic command execution in container
- Split version tests for custom setup
- Move JBang IT classes in correct package
=> [jbang-it] Fixes and improves Camel CLI tests

docs/components/modules/ROOT/partials/component-configure-options.adoc, docs/components/modules/ROOT/partials/component-endpoint-options.adoc
=> CAMEL-20410: documentation fixes for base files

components/camel-file/src/main/docs/file-component.adoc
- Converted to use tabs
- Fixed out-of-order elements
- Cleaned up duplicated elements
=> CAMEL-20410: documentation fixes for camel-file

dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationRun.java, dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationRunTest.java, dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/KubeBaseTest.java, dsl/camel-jbang/camel-jbang-plugin-k/src/test/resources/Sample.java, dsl/camel-jbang/camel-jbang-plugin-k/src/test/resources/route-deps.yaml
For use in camel-k jbang plugin, infer the dependencies of a route and set them into the `Integration` object.
=> camel-jbang-plugin-k: infer the dependencies by inspecting the route

components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/csv/BindyCsvDataFormat.java, components/camel-bindy/src/test/java/org/apache/camel/dataformat/bindy/csv/BindyEscapedCsvTest.java
=> Handle quote escape in bindy

components/camel-http/src/main/java/org/apache/camel/component/http/OAuth2ClientConfigurer.java, components/camel-http/src/test/java/org/apache/camel/component/http/HttpOAuth2AuthenticationTest.java
Fixes bug as described in https://issues.apache.org/jira/browse/CAMEL-20498
> When using the OAuth2 support for camel-http, it is not adding the prefix text "Bearer " before the access token in the Authorization header as per the OAuth2 specification: https://datatracker.ietf.org/doc/html/rfc6750#section-2.1
=> [CAMEL-20498] Fix bug with camel-http HTTP OAuth2 Authorization header

components/camel-file/src/main/java/org/apache/camel/component/file/strategy/MarkerFileExclusiveReadLockStrategy.java, core/camel-core/src/test/java/org/apache/camel/component/file/MarkerFileExclusiveReadLockStrategyRecursiveCleanupTest.java
Honors min/max depth when cleaning up camel lock files.  This resolves an issue where users have a large number of directories and files in subdirectories that do not need to be scanned when cleaning up marker files.
=> CAMEL-20482: use min/max depth during markerfile cleanup

components/camel-jsonpath/src/test/java/org/apache/camel/jsonpath/JsonPathSplitSingleListOptionTest.java, core/camel-core-model/src/main/java/org/apache/camel/model/language/JsonPathExpression.java, core/camel-core-model/src/main/java/org/apache/camel/model/language/MethodCallExpression.java, core/camel-core-model/src/main/java/org/apache/camel/model/language/XMLTokenizerExpression.java, core/camel-core-model/src/main/java/org/apache/camel/model/language/XPathExpression.java
Fixes https://issues.apache.org/jira/browse/CAMEL-20507
The expression builders that have fields whose possible values are limited, only support String as type of argument while we could expect to use an enumeration instead.
* Adds an enum to all expression classes where a field has only limited possible values
* Uses the internal enum in an existing test case to ensure that it works as expected
* Fixes the setter of `resultQName` in the builder of `XPathExpression`
=> CAMEL-20507: camel-core - Add enums to expression builders

core/camel-core/src/test/java/org/apache/camel/support/DefaultRegistryTest.java, core/camel-support/src/main/java/org/apache/camel/support/DefaultRegistry.java
Fixes https://issues.apache.org/jira/browse/CAMEL-20551
In case we have several bean repositories defined in the default registry and a bean is defined in one of the first bean repositories, the method findSingleByType won't return any result while we expect to retrieve a bean.
* Avoid ignoring the result of `findSingleByType` on the first bean repositories
=> CAMEL-20551: camel-core - Avoid ignoring beans when using several repos

catalog/camel-catalog/src/main/java/org/apache/camel/catalog/DefaultCamelCatalog.java, catalog/camel-catalog/src/main/java/org/apache/camel/catalog/DefaultRuntimeProvider.java
=> chore: minor camel-catalog cleanup

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/PluginHelper.java
Instead to spawn a new process, this fix downloads the camel-jbang plugin and run it as part of the same camel-jbang OS process.
The change in `DefaultClassResolver.java` was motivated as when searching for a resource file from the downloaded maven artifact it's not available from the classloader in `getApplicationContextClassLoader()` , so it has to search in the list of `classloaders`
I will add some tests, but in the meantime I would like some preliminary review.
https://issues.apache.org/jira/browse/CAMEL-20517
=> CAMEL-20517 camel-jbang-plugin-k doesn't recognize command

components/camel-aws/camel-aws-bedrock/src/main/java/org/apache/camel/component/aws2/bedrock/BedrockModels.java, components/camel-aws/camel-aws-bedrock/src/main/java/org/apache/camel/component/aws2/bedrock/runtime/BedrockProducer.java, components/camel-aws/camel-aws-bedrock/src/test/java/org/apache/camel/component/aws2/bedrock/runtime/integration/BedrockProducerIT.java
=> CAMEL-20560 - Camel-AWS-Bedrock: Support Anthropic models

dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/CustomResolver.java, dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/ErrorHandlerDeserializer.java, dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/RouteDefinitionDeserializer.java, dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camelYamlDsl.json, dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/RoutesTest.groovy
Allow to set error handler on route level in Camel YAML DSL
(cherry picked from commit c0228d4f12c6a34859e69337bd0017a855fe195c)
=> [BACKPORT-4.4.x] CAMEL-20568: Set error handler on route level in YAML DSL (#13489)

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Debug.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
Add full path of `camel` script when Camel JBang is used on a Windows machine.
=> [CAMEL-20512] Add full path for camel jbang process if using Windows

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorReleaseResourcesIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaTransactionIT.java
Close existing consumer to release resources (like heartbeat-thread) before creating new ones. Fix for KafkaTransactionIT, close consumer, was affecting other tests.
=> CAMEL-20563: shutdown existing consumer instance.

catalog/camel-catalog/src/main/java/org/apache/camel/catalog/DefaultCamelCatalog.java, core/camel-core-catalog/src/main/java/org/apache/camel/catalog/impl/AbstractCachingCamelCatalog.java, core/camel-core-catalog/src/main/java/org/apache/camel/catalog/impl/AbstractCamelCatalog.java, core/camel-core-catalog/src/main/java/org/apache/camel/catalog/impl/DefaultRuntimeCamelCatalog.java, tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/BaseModel.java, tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/ComponentModel.java, tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/DataFormatModel.java, tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/DevConsoleModel.java, tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/EipModel.java, tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/Kind.java, tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/LanguageModel.java, tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/OtherModel.java, tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/TransformerModel.java
=> catalog: make catalog more type safe

core/camel-core-xml/src/main/java/org/apache/camel/core/xml/AbstractCamelContextFactoryBean.java
In the case of a Camel Spring Boot application that defines rest routes in camel-xml-io-dsl, rest routes in java dsl, and rest routes spring beans xml, the rest routes are loaded twice in the context and the application cannot start.
I noticed that rests defined in camel-xml-io-dsl and java route configuration are loaded first, together, without issues, but when the rests defined in the spring beans xml are loaded into the camel context, the getContext().getRestDefinitions() contains both the rests defined in the spring beans xml and the rests defined via java or camel-xml, this is why they are loaded twice, getRests() contains only rests defined in the beans xml dsl.
I'm opening the PR in draft, I'd like to execute more tests.
=> [CAMEL-20577] Avoid rest routes dupes

parent/pom.xml
This reverts commit 6fe4706f1ff4051bebe109f6bdd28fd35d737f77.
=> CAMEL-20584: Revert "Bump mongo-java-driver-version from 4.11.1 to 5.0.0 (#13476)"

parent/pom.xml
The Set-Cookie "Expires" cookie attribute is being incorrectly parsed by the version `8.0.0.beta1` `cometd-java-client-http-jetty` library. This results in the request headers growing indefinitely, eventually leading to a "java.lang.IllegalArgumentException: Request header too large" exception being thrown by Salesforce auth servers. This issue seems to have been resolved in `8.0.0.beta2` by this PR: https://github.com/cometd/cometd/pull/1631
This issue resides in the `JettyHttpClientTransport`  class which is called from the  `SubscriptionHelper`, and stems from the use of the `HttpField.getValueList` method, which uses the `QuotedCSV` class that extends `QuotedCSVParser`. Unfortunately, `QuotedCSVParser` does not appropriately handle the "Expires" cookie attribute, and splits the …
=> fix(camel-salesforce): bump cometd-java-client-version to 8.0.0.beta2 [CAMEL-20588]

.github/workflows/pr-build-main.yml, .github/workflows/push-build-main.yml
As Java 21 becomes more common, I think we should start checking the PRs with it. It would help us catch issues earlier.
=> (chores) ci: start checking PRs with Java 21

catalog/camel-report-maven-plugin/src/main/docs/camel-report-maven-plugin.adoc, catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/ValidateMojo.java
Backport of https://github.com/apache/camel/pull/13567/
=> Validate routes in transitive dependencies

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/processor/RawProcessor.java
When value is not set in the header but declared, a null check is missing which results in NPE.
[CAMEL-20597](https://issues.apache.org/jira/browse/CAMEL-20597)
=> [CAMEL-20597]: Fix NullPointerException when query header is not set

core/camel-support/src/main/java/org/apache/camel/support/DefaultTimeoutMap.java
As described on the issue, the https://github.com/apache/camel/blob/camel-3.21.x/components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/reply/ReplyManagerSupport.java#L217 is executing the get excessively. This delay occurs because the ReplyHandler has already been removed by the RabbitMQReplyManagerTimeoutChecker. The contains avoid getting locked when the TimeoutMapEntry does not exist.
=> CAMEL-20590: avoiding delay to execute timeout to Camel RabbitMQ (InOut)

dsl/camel-jbang/camel-jbang-core/pom.xml
Backport #13585 to 4.4.x LTS. 4.0.x doesn't have the issue.
=> Fix command `camel jolokia` fails to attach JVM agent (4.4.x)

components/camel-ai/camel-langchain-chat/pom.xml, components/camel-ai/camel-langchain-embeddings/pom.xml, components/camel-ai/pom.xml
=> CAMEL-20599: camel-ai - pom.xml should be clean

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Bind.java, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/error-handler-log.yaml.tmpl, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/error-handler-sink-kamelet.yaml.tmpl, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/error-handler-sink-uri.yaml.tmpl, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/pipe-kamelet-kamelet.yaml.tmpl, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/pipe-kamelet-uri.yaml.tmpl, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/pipe-uri-kamelet.yaml.tmpl, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/pipe-uri-uri.yaml.tmpl, dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/BindTest.java
CAMEL-20601
- Allow to add error handler to the Pipe resource
- Support different error handler types (sink, uri, log, none)
- Support user properties on the error handlers
User can add the error handler with new command option `--error-handler`:
```
camel bind timer-to-http --source timer-source --sink http-sink --error-handler log-sink
```
It results in a error handler specification set on the Pipe:
```yaml
apiVersion: camel.apache.org/v1
kind: Pipe
metadata:
name: timer-to-log
spec:
source:
ref:
kind: Kamelet
apiVersion: camel.apache.org/v1
name: timer-source
properties:
message: "hello world"
sink:
ref:
kind: Kamelet
apiVersion: camel.apache.org/v1
name: http-sink
properties:
url: http://localhost:8080
errorHandler:
sink:
endpoint:
ref:
kind: Kamelet
apiVersion: camel.apache.org/v1 …
```
=> CAMEL-20601: Support error handler on Camel JBang bind command

components/camel-jms/src/main/java/org/apache/camel/component/jms/reply/QueueReplyManager.java, components/camel-jms/src/main/java/org/apache/camel/component/jms/reply/ReplyManagerSupport.java, components/camel-jms/src/main/java/org/apache/camel/component/jms/reply/TemporaryQueueReplyManager.java, components/camel-sjms/src/main/java/org/apache/camel/component/sjms/reply/QueueReplyManager.java, components/camel-sjms/src/main/java/org/apache/camel/component/sjms/reply/TemporaryQueueReplyManager.java, core/camel-support/src/main/java/org/apache/camel/support/DefaultTimeoutMap.java
=> jms inout concurrency issue

components/camel-http/src/main/java/org/apache/camel/component/http/OAuth2ClientConfigurer.java
Uses HttpRequest `setHeader` instead of `addHeader` to ensure that duplicate of "Authorization" header will not be created when using camel-http's OAuth2 support.  See: https://hc.apache.org/httpcomponents-core-5.1.x/current/httpcore5/apidocs/org/apache/hc/core5/http/HttpMessage.html#setHeader(org.apache.hc.core5.http.Header)
=> CAMEL-20624: Fix bug in camel-http to avoid duplicate OAuth2 Authorization headers

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/Jolokia.java
Fix originally found by @grgrzybek.
Original issue: https://github.com/hawtio/hawtio/issues/3320
=> camel-jbang - Fix jolokia 2.0.x not discoverable by default

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/Jolokia.java
=> camel-jbang - Fix jolokia 2.0.x not discoverable by default (4.4.x)

components/camel-cdi/src/main/java/org/apache/camel/cdi/CdiCamelExtension.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/CdiEventNotifier.java
- remove deprecated BeanManager.fireEvent
- this will allow the library to be used in also with cdi api 4 after transforming it with eclipse transformer.
fireEvent method was removed in cdi api 4 version. This means the camel-cdi library cannot be used in jakarta app servers even after transforming it using eclipse transformer tool.
=> camel-cdi remove deprecated fireEvent method

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/AS2MessageDispositionNotificationEntity.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/util/DispositionNotificationContentUtils.java, components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/entity/EntityParserTest.java
The body part fields of a parsed MDN are written out to an output stream when a signature needs to be verified.  Any (ordering/formatting) changes introduced when the entity is parsed and written mean that the signature verification will fail.  One approach is to write out a direct copy of the body part fields of the received entity instead of trying to parse and recreate each field.
=> CAMEL-18017: return body part fields copied from parsed MDN entity to avoid corruption

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/DispositionNotificationMultipartReportEntity.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/EntityParser.java, components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/entity/EntityParserTest.java
The `contentTransferEncoding` needs to be included in the DispositionNotificationMultipartReportEntity constructor when parsing the entity body.  Previously this was set via a 'setter' but with the upgrade to Apache HTTP client v5 it was changed to an attribute that must be set via the constructor: https://github.com/apache/camel/blob/camel-4.4.x/components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/EntityParser.java#L713
=> CAMEL-20659: include contentTransferEncoding on parsed Report

components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/seda/HazelcastSedaConsumer.java
If **transacted** is enabled for a **hazelcast-seda** queue, the transaction never gets committed if body is _null_. This is often the case when polling from an empty queue. This leads to "Camel Exception cause:  java.lang.IllegalStateException: Nested transactions are not allowed!". We found this issue as our Hazelcast txBackupLogs consumed a large amount of memory.
Camel 4. 
Older versions are also affected. It would be nice to merge down to Camel 3 LTS versions.
=> hazelcast-seda: Nested transactions are not allowed!

.github/actions/incremental-build/incremental-build.sh
This should ensure that the incremental script will proceed when there are only core changes.
=> (chores) ci: avoid skipping core tests

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/streaming/SubscriptionHelper.java
The issue is related to https://github.com/cometd/cometd/issues/1600, salesforce server replies with Set-Cookie values that are wrong or deprecated, and the latest setCookieParser implementation in Jetty 12 `RFC6265SetCookieParser` ignore some of the cookies, therefore, when the /connect endpoint is invoked, some cookies are missing and we get `403::Unknown client`.
This PR simply restores the old setCookie and cookieParser strategy.
=> CAMEL-20388: Restore the old cookieStore Strategy

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultCamelContextExtension.java
CAMEL-20613: set AbstractCamelContext#endpointStrategies to ConcurrentHashSet to prevent ConcurrentModificationException
If a thread iterates over the list of strategies while another thread adds a new strategy, ConcurrentModificationException is thrown. To fix this issue, AbstractCamelContext#endpointStrategies can be set to a thread-safe collection.
=> CAMEL-20613: set AbstractCamelContext#endpointStrategies to ConcurrentHashSet

components/camel-kamelet/src/test/java/org/apache/camel/component/kamelet/KameletMultiThreadedTest.java, core/camel-core-model/src/main/java/org/apache/camel/model/CopyableProcessorDefinition.java, core/camel-core-model/src/main/java/org/apache/camel/model/NoOutputDefinition.java, core/camel-core-model/src/main/java/org/apache/camel/model/OptionalIdentifiedDefinition.java, core/camel-core-model/src/main/java/org/apache/camel/model/ProcessorDefinition.java, core/camel-core-model/src/main/java/org/apache/camel/model/RouteTemplateDefinition.java, core/camel-core-model/src/main/java/org/apache/camel/model/SendDefinition.java, core/camel-core-model/src/main/java/org/apache/camel/model/ToDefinition.java, core/camel-core-model/src/main/java/org/apache/camel/model/ToDynamicDefinition.java, core/camel-core/src/test/java/org/apache/camel/model/RouteTemplateDefinitionTest.java
CAMEL-20614: deep-copy output processors during instantiation of a route template
When multiple threads try to instantiate and send an exchange to the same kamelet in parallel, org.apache.camel.component.kamelet.KameletConsumerNotAvailableException may be thrown because the underlying RouteTemplateDefinition is shallow-copied and changes to the RouteDefinition are reflected in the RouteTemplateDefinition.
=> CAMEL-20614: deep-copy output processors during instantiation of a route template

components/camel-pg-replication-slot/src/main/java/org/apache/camel/component/pg/replication/slot/PgReplicationSlotConsumer.java
Calling `super.doStart()` before initializing the consumer might cause `poll()` being called before the consumer is ready. This can happen if `connect()` takes relatively long time.
=> pg-replication-slot FIX: Calling super.doStart() after initializing the consumer to avoid poll() being called before the Consumer is initialized

catalog/camel-catalog/src/test/java/org/apache/camel/catalog/CamelCatalogTest.java
- [CAMEL-20093] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).
=> CAMEL-20093 : Replaced 3 test cases with a single parameterized one.

dsl/camel-endpointdsl/pom.xml
The org.wildfly.security:wildfly-elytron jar dependency of camel-elytron includes the SLF4J 1.x classes and there was a logback provider in the classpath.
=> CAMEL-19713: Fix logging by ensuring use of SLF4J 2.0

core/camel-xml-jaxp/src/main/java/org/apache/camel/util/xml/SourceCache.java
CAMEL-20714 Added public no-arg constructor for SourceCache
It throws an exception since I can't set a proper value to 
private final int length;
=> CAMEL-20714 Added public no-arg constructor for SourceCache

components/camel-azure/camel-azure-servicebus/src/main/java/org/apache/camel/component/azure/servicebus/ServiceBusConfiguration.java, components/camel-azure/camel-azure-servicebus/src/main/java/org/apache/camel/component/azure/servicebus/ServiceBusConsumer.java, components/camel-azure/camel-azure-servicebus/src/main/java/org/apache/camel/component/azure/servicebus/ServiceBusHeaderFilterStrategy.java
Fix propagation of Azure ServiceBus broker properties to the Camel Exchange.
Discovered whilst developing new integration tests for #13862.
=> CAMEL-20699, CAMEL-20691: Fix Azure ServiceBus header propagation

core/camel-core-model/src/main/java/org/apache/camel/model/Copyable.java, core/camel-core-model/src/main/java/org/apache/camel/model/EnrichDefinition.java, core/camel-core-model/src/main/java/org/apache/camel/model/ExpressionNode.java, core/camel-core-model/src/main/java/org/apache/camel/model/PollEnrichDefinition.java, core/camel-core-model/src/main/java/org/apache/camel/model/RouteTemplateDefinition.java, core/camel-core-model/src/main/java/org/apache/camel/model/ToDefinition.java, core/camel-core-model/src/main/java/org/apache/camel/model/ToDynamicDefinition.java, core/camel-core/src/test/java/org/apache/camel/model/RouteTemplateDefinitionTest.java
CAMEL-20614: deep-copy enrich and poll-enrich processors during instantiation of a route template
This pull request updates Enrich and PollEnrich to be deep-copied during instantiation of a route template as requested in the [comment](https://github.com/apache/camel/pull/13823#issuecomment-2063654951).
=> CAMEL-20614: deep-copy enrich and poll-enrich processors during instantiation of a route template

components/camel-jms/src/test/java/org/apache/camel/component/jms/RestartBrokerBeforeCommitIT.java
This test was added as part of #13403, but it seems to be failing quite often. Disabling it for now ...
=> CAMEL-20521: disable flaky/unstable test

components/camel-quickfix/src/main/java/org/apache/camel/component/quickfixj/MessagePredicate.java
CAMEL-20712 Throw created exception in MessagePredicate
=> CAMEL-20712 Throw created exception in MessagePredicate

docs/user-manual/modules/ROOT/pages/camel-catalog.adoc
Add Kaoto and Hawtio links to the [Camel Catalog website](https://camel.apache.org/manual/camel-catalog.html)
=> chore(docs): Add Kaoto and Hawtio to Catalog page

core/camel-core/src/test/java/org/apache/camel/impl/ScheduledPollConsumerBackoffTest.java, core/camel-support/src/main/java/org/apache/camel/support/ScheduledPollConsumer.java
I'd like a review on this one. 
What's the problem here: ScheduledPollConsumer does non-atomic operations on volatile fields. For instance: 
```
backoffCounter++
```
That's a non-atomic operation because it does more than one operation (i.e.: fetch, add, update). So when multiple threads are watching for this value, there is a risk they may see corrupted values (as they may see the memory contents half-way in the operation). 
This changes the code to use `AtomicInteger` and `AtomicLong` instead. 
It also adjusts a test that seemed to wait for an specific number of cycles in the run loop (which is not clear to me why those numbers where chosen, hence the request for the review) . It should fix the flakiness on the test, but I left it isolated for now.
=> CAMEL-20705: fix non-atomic operations on volatile fields on the ScheduledPollConsumer

core/camel-support/src/main/java/org/apache/camel/support/component/AbstractApiComponent.java
I'm sending this one separately because this field seems unused, but it would be good to have a double check.
=> (chores) camel-core: removed unused field

components/camel-jms/src/test/java/org/apache/camel/component/jms/integration/consumers/SingleMessageSameTopicIT.java
The testRemoveOneRoute test removes the route and causes NPEs and other problems if it runs before other tests
=> (chores) camel-jms: fix test that needs an specific order

components/camel-saxon/src/main/java/org/apache/camel/language/xquery/XQueryLanguage.java, components/camel-saxon/src/test/java/org/apache/camel/builder/saxon/XQueryHeaderNameResultTypeAndNamespaceTest.java, core/camel-core-reifier/src/main/java/org/apache/camel/reifier/language/XQueryExpressionReifier.java
Fixes xquery namespaces usage.
This is a regression starting from 4.4.0.
Should be also merged to 4.4.x, 4.5.x.
=> CAMEL-20724: camel-saxon - Fix xquery namespaces usage

core/camel-core-model/pom.xml, core/camel-core-model/src/main/java/org/apache/camel/model/rest/RestDefinition.java, core/camel-core-model/src/test/java/org/apache/camel/model/rest/RestDefinitionTest.java
Generation of string representation for arrays relies on getName() as a workaround to properly support nested classes. However, this results in "null[]" for array of primitives.
```java
package my.example;
public class MyRoutes extends org.apache.camel.builder.RouteBuilder {
@Override
public void configure() throws Exception {
rest()
.get("/test")
.outType(byte[].class)  // <-- this is the problematic argument
.produces("application/octet-stream")
.route()
.log("test me");
}
} 
```
The problem is that `asTypeName(byte[].class)` returns `"null[]"` before this fix, because `byte[].class.getName()` equals `"[B"` and the logic is looking for `"[L...;"` only.
Rework (and simplify) the logic and introduce a unit test, so we can handle such types properly again.
=> CAMEL-20732: fix parsing primitive array types in RestDefinition

components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/stream/AWS2S3StreamUploadProducer.java, components/camel-aws/camel-aws2-s3/src/test/java/org/apache/camel/component/aws2/s3/integration/S3StreamUploadS3MultipartIT.java
See: https://issues.apache.org/jira/browse/CAMEL-20728
This PR aims to provide camel-aws2s3 producer for support for multipart upload in combination with streaming mode. Actually, today's streaming mode agregates messages into S3 objects, but each object is sent as a whole, which can be an issue if it is huge (memory failure). This PR enables multipart (S3 API multipart) for each object upload.
multiPartUpload must be enabled, and partSize will specify chunk sizes.
=> [CAMEL-20728] add S3 multipart upload support for stream producer in camel-aws2-s3

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/protocol/ResponseMDN.java
Although Camel-AS2 doesn't currently produce any 'failure' disposition, read the disposition type from the HttpContext instead of the request allowing for future disposition handling improvements.
=> CAMEL-17829 read disposition-type from HttpContext

components/camel-bonita/pom.xml, components/camel-debezium/camel-debezium-mysql/pom.xml, components/camel-debezium/camel-debezium-mysql/src/main/docs/debezium-mysql-component.adoc, components/camel-ftp/pom.xml, components/camel-oaipmh/pom.xml, components/camel-openstack/pom.xml, components/camel-platform-http-vertx/pom.xml, components/camel-pubnub/pom.xml, components/camel-rest-openapi/pom.xml, components/camel-salesforce/camel-salesforce-maven-plugin/pom.xml, components/camel-thymeleaf/pom.xml, components/camel-xchange/pom.xml, dsl/camel-kamelet-main/src/main/resources/camel-main-known-dependencies.properties
The following artefact moved:
```
mysql:mysql-connector-java -> com.mysql:mysql-connector-j 
xyz.rogfam:littleproxy -> io.github.littleproxy:littleproxy 
com.github.tomakehurst:wiremock -> org.wiremock:wiremock
```
Updated the dependencies coordinates accordingly, kept same versions
=> Updated dependency coordinates for artifacts moved elsewhere

catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/RouteCoverageMojo.java, catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/htmlxlsx/process/CoverageResultsProcessor.java, catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/htmlxlsx/process/FileUtil.java
Fix HTML route coverage report generation on Windows machines
=> Fix HTML route coverage report generation on Windows machines

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorOffUsingKafkaManualCommitIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorSeekIssueIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorWithBatchUsingAsyncCommitManagerIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorWithBatchUsingKafkaManualCommitIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorWithBatchUsingKafkaManualCommitRetryIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorWithBatchUsingSyncCommitManagerIT.java
CAMEL-20722 - disabled on ppc64le due to consistent failure on ppc64le
CAMEL-20722 - disabled 6 tests on ppc64le due to consistent failure on ppc64le
=> CAMEL-20722 - disabled on ppc64le due to consistent failure

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorOffUsingKafkaManualCommitIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorReleaseResourcesIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorReplayOldMessagesIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorSeekIssueIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorWithBatchUsingAsyncCommitManagerIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorWithBatchUsingKafkaManualCommitIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorWithBatchUsingKafkaManualCommitRetryIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorWithBatchUsingSyncCommitManagerIT.java
These tests are constantly flaky on those platforms in our CI, although they may run fine on environments less resource-constrained
=> CAMEL-20722: prevent certain camel-kafka tests from running on Power and s390x

components/camel-salesforce/pom.xml
The `camel-salesforce` component cannot build on Windows running on ARM because there is no gRPC library available. In order to build successfully on Windows/ARM, this PR disables the build on that environment.
In general, adding profiles is discouraged, but since there is no way to disable a module via properties, adding profiles to the `camel-salesforce` parent pom was the only way to make this work.
- [ x] I checked that each commit in the pull …
=> Updated pom to skip build on Windows running on ARM

components/camel-jms/src/test/resources/org/apache/camel/component/jms/integration/spring/tx/security/artemis-security.xml
The lack of address policy may cause the JMS tests to hang indefinitely if there is insufficient disk space available on the host running the tests
=> (chores) camel-jms: fix misconfigured Artemis broker instance

core/camel-core/src/test/java/org/apache/camel/component/file/FileProducerExpressionTest.java
Try to avoid using a path that may have different permissions, which tends to lead to failures in CI environments
=> (chores) camel-file: avoid using a restricted directory

components/camel-rest/src/main/java/org/apache/camel/component/rest/DefaultRestRegistry.java, components/camel-stub/src/main/java/org/apache/camel/component/stub/StubComponent.java, core/camel-api/src/main/java/org/apache/camel/CamelContext.java, core/camel-api/src/main/java/org/apache/camel/spi/EndpointRegistry.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultEndpointRegistry.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/ProvisionalEndpointRegistry.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/SimpleCamelContext.java, core/camel-console/src/main/java/org/apache/camel/impl/console/EndpointDevConsole.java, core/camel-core/src/test/java/org/apache/camel/impl/DefaultEndpointRegistryTest.java, core/camel-core/src/test/java/org/apache/camel/impl/engine/DefaultCamelContextTest.java, core/camel-management/src/main/java/org/apache/camel/management/JmxManagementLifecycleStrategy.java, core/camel-management/src/main/java/org/apache/camel/management/mbean/ManagedEndpointRegistry.java, core/camel-management/src/main/java/org/apache/camel/management/mbean/ManagedRuntimeEndpointRegistry.java
Change the `CamelContext.getEndpointRegistry()` to return an `EndpointRegistry<NormalizedEndpointUri>` instead of an `EndpointRegistry<? extends ValueHolder<String>>`.  
This is a small incompatible change.
=> Make EndpointRegistry extends Map<NormalizedEndpointUri, Endpoint>

core/camel-support/src/main/java/org/apache/camel/support/RestConsumerContextPathMatcher.java, core/camel-support/src/test/java/org/apache/camel/support/RestConsumerContextPathMatcherTest.java
Ensure that any hypens or underscores in parameters in REST templates are removed before being parsed into a regular expression
The code will remove (using a regular expression match) any hyphens or underscores in REST template parameter names.  This is required as the parameter name are parsed into regular expression named groups which support only letters and numbers as group names.
https://issues.apache.org/jira/browse/CAMEL-20763
=> CAMEL-20763: camel-support Handle special characters in REST templates

.github/actions/incremental-build/action.yaml, .github/actions/incremental-build/incremental-build.sh
Make incremental-build action generic in order to be reused in camel-spring-boot repository
=> Make incremental-build action generic

.github/actions/incremental-build/action.yaml, .github/actions/incremental-build/incremental-build.sh, core/camel-core/src/test/java/org/apache/camel/support/jsse/FilterParametersTest.java, core/camel-core/src/test/java/org/apache/camel/support/jsse/KeyManagersParametersTest.java, core/camel-core/src/test/java/org/apache/camel/support/jsse/KeyStoreParametersTest.java, core/camel-core/src/test/java/org/apache/camel/support/jsse/SSLContextParametersTest.java, core/camel-core/src/test/java/org/apache/camel/support/jsse/SecureRandomParametersTest.java, core/camel-core/src/test/java/org/apache/camel/support/jsse/TrustManagersParametersTest.java, core/camel-core/src/test/resources/org/apache/camel/support/jsse/test.properties, test-infra/camel-test-infra-mongodb/src/test/resources/org/apache/camel/test/infra/mongodb/services/container.properties
=> Upgrade mongodb container to 7.0.9

core/camel-core-processor/src/main/java/org/apache/camel/processor/MulticastProcessor.java, core/camel-core-processor/src/main/java/org/apache/camel/processor/Splitter.java, core/camel-core/src/test/java/org/apache/camel/issues/SplitterParallelWithIteratorThrowingExceptionTest.java
If the last element of the iterable is null, the last message will not contain the final informations such as splitter-size, multicast-complete
=> Fix multicast iterator to be lazy again

core/camel-api/src/main/java/org/apache/camel/ExtendedCamelContext.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultCamelContextExtension.java, core/camel-core-engine/src/main/java/org/apache/camel/impl/DefaultCamelContext.java, core/camel-support/src/main/java/org/apache/camel/support/component/AbstractApiEndpoint.java, core/camel-support/src/main/java/org/apache/camel/support/processor/idempotent/FileIdempotentRepository.java, core/camel-support/src/main/java/org/apache/camel/support/processor/idempotent/MemoryIdempotentRepository.java, core/camel-support/src/main/java/org/apache/camel/support/processor/state/FileStateRepository.java, core/camel-util/src/main/java/org/apache/camel/util/URISupport.java
- **Make model field final in DefaultCamelContext, deprecate the disposeModel method which was used with the lightweight mode**
- **Fix wrong synchronization pattern**
- **Do not synchronize on non final fields**
- **Remove unwanted warning for regex**
=> Various code cleanups

core/camel-api/src/main/java/org/apache/camel/spi/InterceptableProcessor.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultChannel.java, core/camel-core-processor/src/main/java/org/apache/camel/processor/CatchProcessor.java, core/camel-core-processor/src/main/java/org/apache/camel/processor/FinallyProcessor.java, core/camel-core-processor/src/main/java/org/apache/camel/processor/TryProcessor.java, core/camel-core-reifier/src/main/java/org/apache/camel/reifier/InterceptReifier.java, core/camel-core/src/test/java/org/apache/camel/processor/intercept/InterceptDoTryCatchTest.java
Cherry-pick 5f5481ea08a89516ff929b78552c3316abbfb634
Backport from `main` to the latest 4.4.x LTS
=> CAMEL-20778: intercept EIP should not intercept doTry/doCatch/doFinally.

components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/Kinesis2Consumer.java, components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/Kinesis2Producer.java
Kinesis consumer set InputStream on the body. The InputStream is not a common record type and may not be natively supported by many data or messaging systems.
For better compatibility, we change body type to ByteArray.
=> Change aws2 kinesis record body type to byte array

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorOffUsingKafkaManualCommitIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorReleaseResourcesIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorWithBatchUsingSyncCommitManagerIT.java
Changes to address flakiness:
- most likely cause is resource crunch on CI causing some tests to time out.
- more unique test-specific topic names approach might be needed later (after observation)
=> CAMEL-20722 - changes to address flakiness observed on CI

docs/main/modules/contributing/pages/expectations.adoc, docs/main/modules/contributing/pages/index.adoc
The recent attacks to open source projects, by malicious actors trying to obtain privileged access to the repositories and injecting malicious code has been pretty frightening. Just recently we had an influx of short-lived accounts (just a few days old and likely fake) trying to submit "cleanups" to the code base without any discussion with the community. 
I think it would be important for us to clarify what we expect from anyone contributing to Apache Camel and what other committers should look when reviewing contributions. 
Please note that many of the additions to the document are things that we already expect, but have never been formalized before. 
I have discussed with a few others about this (@davsclaus, @oscerd) and I think it's time to bring it to the community for review and …
=> RFC: adjustments to the contributing guide

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultShutdownStrategy.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DurationRoutePolicy.java, core/camel-base/src/main/java/org/apache/camel/impl/converter/CachingInjector.java, core/camel-core-model/src/main/java/org/apache/camel/model/dataformat/FhirDataformat.java, core/camel-core-model/src/main/java/org/apache/camel/model/dataformat/UniVocityAbstractDataFormat.java, core/camel-core-model/src/main/java/org/apache/camel/model/language/ExpressionDefinition.java, core/camel-core-model/src/main/java/org/apache/camel/model/language/NamespaceAwareExpression.java, core/camel-core-processor/src/main/java/org/apache/camel/processor/ConcurrentRequestsThrottler.java, core/camel-core-processor/src/main/java/org/apache/camel/processor/StreamResequencer.java, core/camel-core-processor/src/main/java/org/apache/camel/processor/TotalRequestsThrottler.java, core/camel-core-processor/src/main/java/org/apache/camel/processor/aggregate/AggregateProcessor.java, core/camel-core-processor/src/main/java/org/apache/camel/processor/errorhandler/RedeliveryErrorHandler.java, core/camel-core-processor/src/main/java/org/apache/camel/processor/resequencer/ResequencerEngine.java, core/camel-main/src/main/java/org/apache/camel/main/PropertyOptionKey.java, core/camel-support/src/main/java/org/apache/camel/support/cache/ServicePool.java, core/camel-xml-io/src/main/java/org/apache/camel/xml/in/BaseParser.java
* Fix visibility issues
* Fix busy-wait loop issues
=> Another set of code related warnings fixes

components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/CamelTestSupport.java
Recent changes (part of https://issues.apache.org/jira/browse/CAMEL-20785)  in CamelTestSupport made impossible for Camel-quarkus to overridyethe _unsupportedCheck_. This PR brings temporarily solution.
=> CAMEL-20875 allow modify unsupportedCheck temporarily

components/camel-rocketmq/src/test/java/org/apache/camel/component/rocketmq/RocketMQRequestReplyRouteIT.java, components/camel-rocketmq/src/test/java/org/apache/camel/component/rocketmq/RocketMQRouteIT.java, test-infra/camel-test-infra-rocketmq/src/test/java/org/apache/camel/test/infra/rocketmq/services/RocketMQContainerService.java
Unless there is someone willing to help maintain these, it's not worth the effort to keep running these as they are very slow and unreliable. 
As such, disable them by default on any CI environment (ASF, GH and others).
=> CAMEL-19832: fully disable camel-rocketmq tests due to unreliability and slowness

Dockerfile, builder, pom.xml
Description
This allows you to `./builder mvn install` on a unixish system with only docker installed to do a camel build.  This has the added benefit of using a consistent JDK/Maven version which should aid in build reproducibility.
https://issues.apache.org/jira/browse/CAMEL-20814
=> CAMEL-20814: Publish buildinfo and provide a build container to improve release reproducibility.

components/camel-smb/src/main/java/org/apache/camel/component/smb/SmbConsumer.java
https://issues.apache.org/jira/browse/CAMEL-20823
From my read of the code, I think the intention is to only list files in the poll of the consumer?    If it is preferable to list both files and folders, we could have a separate if path here which handles Directory dir = share.openDirectory() at 
https://github.com/apache/camel/blob/main/components/camel-smb/src/main/java/org/apache/camel/component/smb/SmbConsumer.java#L75
Getting an exception now if the share has directories in it.
=> CAMEL-20823 Filter out folders when listing files

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorSeekIssueIT.java
CAMEL-20680 - fixed root cause of slow publish to partition 1. 
- Added a wait in `setupTopics ()` to ensure that required number of partitions are actually created
- Restored the loop in  `publishMessagesToKafka()` that publishes to partition 1
- Change the position of errored record from 5 to 6 _(to ensure that something is actually read from partition 1 as well)_
After these, the test continues to execute in under 45 sec even after adding back the loop that sends to partition 1  _(the long delay in `publishMessagesToKafka` when CAMEL-20680  was created was because partition 1 was being used before it was even created!)_
CAMEL-20722 - re-enabled test for CI, as the symptom from build 96 **might** go away as a side effect of this
=> CAMEL-20680 - fix root cause of slow publish to partition 1 + CAMEL-20722 re-enable

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/AS2MessageDispositionNotificationEntity.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/EntityParser.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/exception/AS2AuthenticationException.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/exception/AS2DecryptionException.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/exception/AS2ErrorDispositionException.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/exception/AS2InsufficientSecurityException.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/protocol/ResponseMDN.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/util/HttpMessageUtils.java, components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/AS2MessageTest.java, components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/AS2MessageTestBase.java, components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/AS2UnencryptedMessageTest.java, components/camel-as2/camel-as2-component/src/main/java/org/apache/camel/component/as2/AS2Consumer.java, components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2AsyncMDNServerManagerIT.java, components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2ClientManagerIT.java, components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2ServerManagerEncryptedIT.java, components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2ServerManagerIT.java, components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2ServerManagerITBase.java, components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2ServerSecEncryptedIT.java, components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2ServerSecEncryptedSignedIT.java, components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2ServerSecSignedIT.java, components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2ServerSecTestBase.java, components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2ServerSecUnsignedUnencryptedIT.java, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_7.adoc
When the AS2 server is configured with a decryption key all received messages will require encryption, and only messages with valid encryption will be successfully processed.  Similarly, when the AS2 server is configured with a message signature validation certificate chain all received messages will require a signature.
Only messages with valid encryption or signature configured as required will be successfully processed otherwise the server will return an 'insufficient-message-security' error disposition [1]. 
Additionally messages that cannot be decrypted will return a 'decryption-failed' error, and messages failing signature validation will return an 'authentication-failed' error [2].
[1] https://datatracker.ietf.org/doc/html/rfc4130#section-7.4.3
[2] …
=> CAMEL-18962: encryption and signature handling with server config

core/camel-support/src/main/java/org/apache/camel/support/cache/ServicePool.java
As we've seen in recent PRs, ServicePool is over-synchronized, as when upgrading the cache
to use concurrent data structures, the old mechanism using a look was left in place.
Also, the lock when stopping was caused by trying to stop the service before removing
it from the queue (that was fix in a recent commit).
=> [CAMEL-20829] Streamline ServicePool synchronization

.github/actions/component-test/action.yaml, .github/actions/incremental-build/action.yaml, .github/actions/quick-test/action.yaml, .github/workflows/pr-build-camel-3.yml, .github/workflows/pr-build-camel-40x.yml, .github/workflows/pr-build-main.yml, .github/workflows/pr-comment.yml
it is mandatory to not override artifact since v4. To avoid clash, passing specific suffix for matrix jobs
=> chore: Specify a suffix for GitHub Actions upload artifact

.github/actions/component-test/action.yaml, .github/actions/incremental-build/action.yaml, .github/actions/quick-test/action.yaml
to fix main branch
avoids this error:
```
GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. /home/runner/work/camel/camel/./.github/actions/incremental-build/action.yaml (Line: 58, Col: 15): Unrecognized named-value: 'artifact-upload-suffix'. Located at position 1 within expression: artifact-upload-suffix,/home/runner/work/camel/camel/./.github/actions/incremental-build/action.yaml (Line: 59, Col: 15): Unrecognized named-value: 'artifact-upload-suffix'. Located at position 1 within expression: artifact-upload-suffix
```
https://github.com/apache/camel/actions/runs/9365595243/job/25781118249?pr=14329#step:9:3
follow-up to https://github.com/apache/camel/pull/14339
=> Use correct notation variable input for GitHub Actions

tests/camel-itest/pom.xml
mockito
I think that the dependency is no more needed since this refactor https://github.com/apache/camel/commit/8a2207e0904c0dcd879eb75fe66425a61356688d
=> chore: remove no more used test infra dependencies ftpmockserver and

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorSeekIssueIT.java
Changed base class for KafkaBreakOnFirstErrorSeekIssueIT
- `BaseKafkaTestSupport` calls `KafkaServiceFactory.createSingletonService` whereas the previous one called `createService()`
- The `NoSuchElementException `occurs at `KafkaService.beforeAll(KafkaService.java:47)` even though the actual test case succeeds consistently. With the new base class, this method is avoided altogether
- Other Kafka integration tests that call `BaseKafkaTestSupport `,  and don't show the `NoSuchElementException `
=> CAMEL-20722: Changed base class for KafkaBreakOnFirstErrorSeekIssueIT

components/camel-rest-openapi/src/main/java/org/apache/camel/component/rest/openapi/RestOpenApiProcessor.java, components/camel-rest-openapi/src/main/java/org/apache/camel/component/rest/openapi/validator/DefaultRequestValidator.java, core/camel-api/src/main/java/org/apache/camel/spi/RestClientRequestValidator.java, core/camel-support/src/main/java/org/apache/camel/support/processor/DefaultRestClientRequestValidator.java, core/camel-support/src/main/java/org/apache/camel/support/processor/RestBindingAdvice.java, core/camel-support/src/main/java/org/apache/camel/support/processor/RestBindingAdviceFactory.java
=> rest client validator

dsl/camel-jbang/camel-jbang-container/Dockerfile
- Use specific image instead of jbang-action image which was initially designed for GitHub actions which is not actively maintained as jabg-action is no more the recommended way
- Upgrade from JDK 11 to JDK 21
- Upgrade to JBang 0.116.0
- Added a line to warm up the dependencies which is drastically reduce the time to execute the docker image
The `version` call is now almost instant versus 2'30" for me with 4.6.0 as it was downloading a valid JDK (17) and downloading dependencies 
Remaining issues specific to this PR:
* empty JBang version line is printed when calleing the `version`
* the Dockerfile is repeating the Camel version at 2 places (not found how to use an env/variable in the entrypoint
Important issues impacting previous versions too:
* with `run` the file is not found (an be …
=> CAMEL-20608 - Improve Docker image for JBang

components/camel-pubnub/src/test/java/org/apache/camel/component/pubnub/PubNubTestBase.java, components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/AbstractTestSupport.java, components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/CamelTestSupport.java, components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/CommonTestSupport.java, components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/TestExecutionConfiguration.java, components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/TestSupport.java, components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/util/CamelContextTestHelper.java, components/camel-test/camel-test-main-junit5/src/main/java/org/apache/camel/test/main/junit5/CamelMainExtension.java, components/camel-test/camel-test-spring-junit5/src/main/java/org/apache/camel/test/spring/junit5/CamelAnnotationsHandler.java
- Move the legacy test/context setup methods to the AbstractTestSupport
- Moved most of the helper logic to the TestSupport
- Cleaned up one affected test
- Added documentation and comments
- Deprecated a few more methods
=> CAMEL-20843: further split the CamelTestSupport responsibilities

components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/CamelContextConfiguration.java, components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/TestExecutionConfiguration.java
Follows https://issues.apache.org/jira/browse/CAMEL-20843
I tried to use the `AbstractTestSupport` in CQ project. I found that I was missing access to several configuration methods. This PR adds `public` to all of them.
=> Making several configuration ehtods for TestSupport public

dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/spring-boot-pom.tmpl
When an exported application is delpoyed on OCP via jkube, camel-spring-boot-engine-starter is not enough, camel-spring-boot-starter is needed
=> Use the correct camel spring boot starter for camel export

catalog/camel-catalog/src/test/java/org/apache/camel/catalog/CamelCatalogTest.java
The build is failing because of the test CamelCatalogTest since the addition of an option within the context of CAMEL-20852
* Adapt the test consequently
=> CAMEL-20852: Fix CamelCatalogTest

core/camel-core/src/test/java/org/apache/camel/support/cache/SimpleLRUCacheTest.java, core/camel-support/src/main/java/org/apache/camel/support/cache/SimpleLRUCache.java
Fix for https://issues.apache.org/jira/browse/CAMEL-20850
When the queue of changes is full, some entries can be evicted while the cache is not, which is not expected.
* Compress the changes by removing duplicates before the eviction
* Add a minimum size for the queue of changes
=> CAMEL-20850: camel-core - compress changes in SimpleLRUCache

components/camel-sql/src/main/docs/sql-component.adoc
Currently, the `body` reference in the sql-component `.adoc` file is breaking the camel-website build.
Related PR: https://github.com/apache/camel-website/pull/1190
=> fix(sql-component): Fix sql component adoc

components/camel-protobuf/pom.xml, parent/pom.xml
Reverts apache/camel#14496
[ERROR] /home/oscerd/workspace/apache-camel/camel/components/camel-qdrant/src/main/java/org/apache/camel/component/qdrant/QdrantConverter.java:[64,45] cannot access com.google.protobuf.GeneratedMessageV3
[ERROR]   class file for com.google.protobuf.GeneratedMessageV3 not found
[ERROR] /home/oscerd/workspace/apache-camel/camel/components/camel-qdrant/src/main/java/org/apache/camel/component/qdrant/QdrantConverter.java:[62,37] cannot access com.google.protobuf.GeneratedMessageV3
[ERROR]   class file for com.google.protobuf.GeneratedMessageV3 not found
[ERROR] /home/oscerd/workspace/apache-camel/camel/components/camel-qdrant/src/main/java/org/apache/camel/component/qdrant/QdrantConverter.java:[65,33] cannot access com.google.protobuf.GeneratedMessageV3.Builder …
=> Revert "Upgrade protobuf 4.27.1"

parent/pom.xml
camel-spring-boot 4.4.x is using spring-boot 3.2.6 https://github.com/apache/camel-spring-boot/blob/camel-spring-boot-4.4.x/pom.xml#L111 : align json-smart, netty, spring-data-redis, spring-rabbitmq, and spring-ws to the versions used in spring-boot 3.2.6 to avoid classpath issues in camel-spring-boot.
(not a large change)
- [x ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes
=> Align versions to spring-boot 3.2.6

components/camel-mllp/src/test/java/org/apache/camel/component/mllp/MllpTcpServerConsumerOptionalEndOfDataWithValidationTest.java
It was previously failing with JDK 21. it is now passing, surely due to a fix upstream a the library mllp
=> CAMEL-20215 - reactivate MllpTcpServerConsumerOptionalEndOfDataWithValidationTest

.github/workflows/pr-build-camel-3.yml, .github/workflows/pr-build-camel-40x.yml, .github/workflows/pr-build-main.yml
Fetching the full history was added mentioning as recommended by SonarCloud template. Sonar is not used anymore in PR jobs. It is used on Jenkins. There is no more reasons to checkout the full history. It will almost gain 1 minute per PR Build job.
=> chore: Do not fetch full Git history on PR jobs

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/RunCommandITCase.java
Describing, setting error message or adding a comparator in AssertJ must be done before calling the assertion, otherwise, settings will not be taken into account.
as reported by Sonar:
https://sonarcloud.io/project/issues?impactSeverities=MEDIUM&resolved=false&rules=java%3AS5833&types=BUG&id=apache_camel&open=AY09HX_CckbFrvopLnIW
=> Add an assertion predicate after calling as AssertJ method.

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/SpiGeneratorMojo.java
Recreating in-memory the Java Object Index from the jandex.idx was done approximately 9 times per components. This action is relatively long. In fact, only a few different jars require this operation.
It was representing 25% of the time spent in camel classes when calling `mvn clean install -D quickly`
To give an order of magnitude, locally build time with timestamped went from 9'45" to 8'23" globally. The time spent in camel-package Maven plugin reported decreased from 54" to 39"
before:
after:
=> CAMEL-20884 - Cache Index from jandex.idx defined in jar

components/camel-cxf/camel-cxf-spring-soap/src/test/java/org/apache/camel/component/cxf/CxfRecipientListTest.java, components/camel-cxf/camel-cxf-spring-soap/src/test/java/org/apache/camel/component/cxf/CxfRecipientListWithUrlParamsTest.java, components/camel-jsonpath/src/test/java/org/apache/camel/jsonpath/JsonPathSplitSingleListOptionTest.java, components/camel-knative/camel-knative-component/src/main/java/org/apache/camel/component/knative/KnativeConfiguration.java, core/camel-core-engine/src/main/docs/modules/eips/nav.adoc, parent/pom.xml
Align camel-4.4.x branch with dependencies in spring-boot-dependencies 3.2.7 to prevent dependency clashes
Not a large change
- [x ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes
=> Align camel-4.4.x branch with dependencies from spring-boot 3.2.7

components/camel-ai/camel-djl/src/main/docs/djl-component.adoc, components/camel-ai/camel-djl/src/main/java/org/apache/camel/component/djl/model/CustomImageClassificationPredictor.java, components/camel-ai/camel-djl/src/main/java/org/apache/camel/component/djl/model/ZooImageClassificationPredictor.java, components/camel-ai/camel-djl/src/main/java/org/apache/camel/component/djl/model/ZooObjectDetectionPredictor.java, components/camel-ai/camel-djl/src/test/java/org/apache/camel/component/djl/ImageClassificationLocalTest.java, components/camel-ai/camel-djl/src/test/java/org/apache/camel/component/djl/ImageClassificationTest.java, components/camel-ai/camel-djl/src/test/java/org/apache/camel/component/djl/ObjectDetectionTest.java
https://issues.apache.org/jira/browse/CAMEL-20895
The predictors should return the Classifications provided from DJL as-is for the responses.
=> CAMEL-20895: camel-djl - The image classification predictors should not round the resulted probabilities

core/camel-core/src/test/java/org/apache/camel/component/file/FileProducerMoveExistingTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FileProducerTempFileExistsIssueTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FilerProducerDoneFileNameTest.java
Initial change set for CAMEL-20686
Changed three test files which had the maximum number of static filename usage (hello.txt etc.)
Appended `UUID `to make these more unique
```
- core/camel-core/src/test/java/org/apache/camel/component/file/FileProducerMoveExistingTest.java
- core/camel-core/src/test/java/org/apache/camel/component/file/FileProducerTempFileExistsIssueTest.java
- core/camel-core/src/test/java/org/apache/camel/component/file/FilerProducerDoneFileNameTest.java
```
=> CAMEL-20686 - changed file resources in tests to more unique & dynamic UUID

components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/Kinesis2Producer.java, components/camel-aws/camel-aws2-kinesis/src/test/java/org/apache/camel/component/aws2/kinesis/integration/KinesisProducerIT.java
Current kinesis producer can only send on record each time. It neither supports sending records in batch, nor supports async sending. Therefore, the throughput of kinesis producer is extremely low.
In this PR, kinesis producer added supporting for sending batch. This can significantly improve the throughput.
=> CAMEL-20794: AWS2 Kinesis producer supports sending batch

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd, components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/CamelTestSupport.java
Affects camel-test component. Related to https://issues.apache.org/jira/browse/CAMEL-20838
Fixes errors like:
```
java.lang.NullPointerException: Cannot invoke "org.apache.camel.test.junit5.CamelContextManager.setGlobalStore(org.junit.jupiter.api.extension.ExtensionContext$Store)" because "this.contextManager" is null
at org.apache.camel.test.junit5.CamelTestSupport.beforeAll(CamelTestSupport.java:148)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Suppressed: java.lang.NullPointerException: Cannot invoke "org.apache.camel.test.junit5.CamelContextManager.stop()" because "this.contextManager" is null
at org.apache.camel.test.junit5.CamelTestSupport.afterAll(CamelTestSupport.java:153)
... 1 more
```
when running camel tests.
https://issues.apache.org/jira/browse/CAMEL-20838
=> Avoid NPE on Camel Tests

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
- When using --fresh option we need to propagate all versions to the run command in order to not lose the information in the export
- Fresh run command will set the versions to the .camel-jbang-run.properties and this will influence the export that follows after the fresh run
=> camel-jbang: Propagate versions when using --fresh option in export

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelCommand.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportCamelMain.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportQuarkus.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportSpringBoot.java, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/main-pom.tmpl, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-pom.tmpl, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/spring-boot-pom.tmpl
Camel JBang export seemed to not use `--additional-properties` export option in default Maven POM templates.
- Maven POM templates support setting of additional properties during export
- Properties get added to the Maven POM properties section
- Support it in Quarkus, Spring Boot and Camel Main export
=> camel-jbang: Use additional properties during export to add Maven POM properties

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/OpenApiITCase.java, dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/JBangTestSupport.java
the commit adds the following tests :
- run routes from openapi definition and implementation
- run routes using contract first approach, tested with mock response
- export code using openapi
- generate routes and DTOs using plugin generate (enabled from 4.7)
=> CAMEL-20943: camel-jbang - Add openapi generate integration test

pom.xml
After successfully building the 4.7.0 release with maven-release-plugin 3.1.0, let's bump the version on `main` again.
=> Update maven-release-plugin to 3.1.0 again

components/camel-kafka/src/main/docs/kafka-component.adoc, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/errorhandler/KafkaConsumerListener.java, core/camel-api/src/main/java/org/apache/camel/resume/ConsumerListener.java, core/camel-core-model/src/main/java/org/apache/camel/model/ProcessorDefinition.java
Hey @davsclaus, this is more or less what I was thinking about in my comment on https://github.com/apache/camel/pull/14745#issuecomment-2212350669. 
I'm wondering if we should add a log on to inform that we are not calling the `afterConsumeEval.test(null)` because it has not been paused (I have not done so yet, as I think it would flood the log with those messages, because it would be called after every `poll`).
=> CAMEL-20227: avoid calling the consumer test unless Kafka consumer has been paused

components/camel-knative/camel-knative-component/src/main/java/org/apache/camel/component/knative/ce/AbstractCloudEventProcessor.java, components/camel-knative/camel-knative-component/src/test/java/org/apache/camel/component/knative/KnativeComponentTest.java, components/camel-knative/camel-knative-component/src/test/resources/environment.json, components/camel-knative/camel-knative-component/src/test/resources/environment_classic.json, components/camel-knative/camel-knative-http/src/test/java/org/apache/camel/component/knative/http/KnativeHttpTest.java
- Makes sure that CloudEvent attributes use dash style keys even with YAML DSL where key get converted to camelCase style
- Also support property placeholders when setting ceOverrides option for CloudEvent attributes
- Add some unit tests
See CAMEL-20981
=> CAMEL-20981: Fix ceOverrides option with YAML DSL

components/camel-spring-rabbitmq/src/main/java/org/apache/camel/component/springrabbit/SpringRabbitMQProducer.java
getInOnlyTemplate is checking if inOutTemplate is null to determine whether or not it should initialize inOnlyTemplate.  It should check inOnlyTemplate.  This change fixes that.
- [ X ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)
- [ N/A ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).
- [ X ] I checked that each commit in the pull request has a meaningful subject line and body.
- [ X ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes
=> Fix getInOnlyTemplate in SpringRabbitMQProducer.java

components/camel-spring-rabbitmq/src/main/java/org/apache/camel/component/springrabbit/SpringRabbitMQProducer.java
getInOnlyTemplate is checking if inOutTemplate is null to determine whether or not it should initialize inOnlyTemplate.  It should check inOnlyTemplate.  This change fixes that.
=> fix getInOnlyTemplate in SpringRabbitMQProducer.java (#14823)

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Export.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/RuntimeUtil.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
This PR build on top of https://github.com/apache/camel/pull/14789
It pays attention to not breaking the comma separated `--deps` option. You can now do ...
```
camel kubernetes export timer-log-route.yaml \
--gav=examples:timer-log:1.0.0 \
--deps=io.quarkus:quarkus-container-image-docker,io.quarkus:quarkus-minikube \
--runtime=quarkus
```
or 
```
camel kubernetes export timer-log-route.yaml \
--gav=examples:timer-log:1.0.0 \
--dep=io.quarkus:quarkus-container-image-docker \
--dep=io.quarkus:quarkus-minikube \
--runtime=quarkus
```
The code would be a lot simpler when we got rid of `--deps`
Not sure whether we can do this any time soon.
=> [CAMEL-20976] camel-jbang: Consolidate export dependencies

components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowHost.java, components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowProducer.java, components/camel-undertow/src/main/java/org/apache/camel/component/undertow/handlers/CamelWebSocketHandler.java, components/camel-undertow/src/main/java/org/apache/camel/component/undertow/spi/UndertowSecurityProvider.java
=> Undertow component javadocs typos fixes

components/camel-google/camel-google-storage/src/main/java/org/apache/camel/component/google/storage/GoogleCloudStorageProducer.java, components/camel-google/camel-google-storage/src/test/java/org/apache/camel/component/google/storage/unit/ProducerStoreFileTest.java
Fixes https://issues.apache.org/jira/browse/CAMEL-20998
The `GoogleCloudStorageConstants.OBJECT_NAME` was previously prioritized over the endpoint configuration. This led to unexpected behavior, particularly when using the producer and consumer in the same route (I have documented more details about this in the Jira ticket).
I fixed this by checking for the `objectName` in the configuration first, and only if it is not specified there does it fall back to the header value.
=> CAMEL-20998: Prioritize objectName configuration over headers

components/camel-azure/camel-azure-storage-blob/src/main/java/org/apache/camel/component/azure/storage/blob/client/BlobClientWrapper.java
Azure Blob upload is support retry  if upload is facing some network issue.
For now Azure SDK is supporting it if input stream support mark/reset. 
Patch is enabling this feature. 
- [ X] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)
- [X ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue]
- [ X] I checked that each commit in the pull request has a meaningful subject line and body.
- [X ] I have run `mvn clean install -DskipTests` locally and I have committed all auto-generated changes
=> [CAMEL-20995] Fix bug in azure-blob. Enable retry during upload if input stream support mark/reset

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/VersionHelper.java, dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/Agent.java, dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationRun.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/pom.xml, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/CatalogHelper.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/MetadataHelper.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/support/Capability.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/support/SourceMetadata.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/support/StubComponentResolver.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/support/StubDataFormatResolver.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/support/StubLanguageResolver.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/support/StubTransformerResolver.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/ContainerTrait.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/ServiceTrait.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitCatalog.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitContext.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRunTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/MetadataHelperTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/resources/PlatformHttpServer.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/resources/route-service.yaml, dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/KameletMain.java, dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/DependencyDownloaderRoutesLoader.java, dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/KnownKameletRoutesBuilderLoader.java, dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/util/VersionHelper.java
- Add service trait to auto configure service Kubernetes resource for the export
- Only configure service resource when route exposed Http service
- Use metadata source inspection from Camel K agent command to retrieve routes that expose Http service
- Use Maven dependency download routes resolver and loader to dynamically load missing dependencies during metadata code inspection
See CAMEL-20982
=> CAMEL-20982: Add Camel JBang Kubernetes service trait

parent/pom.xml
I released a few bug fixes yesterday. This includes a fix for dependency management that may affect users  using ehcache in their projects, and a fix for the plugin pulling in the wrong dependency scope when analysing dependencies.
Apache CLA has been signed for work on previous projects.
=> Update protobuf-maven-plugin to v2.4.0

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/StreamingApiConsumer.java, components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/streaming/ReplayExtension.java, components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/streaming/SubscriptionHelper.java, components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/internal/streaming/ReplayExtensionTest.java, components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/internal/streaming/StubServer.java, components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/internal/streaming/SubscriptionHelperManualIT.java, components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/internal/streaming/SubscriptionHelperTest.java
[CAMEL-20918](https://issues.apache.org/jira/browse/CAMEL-20918): fix exception handling for Salesforce Streaming API:
- execute subscriptionListener in a separate thread similarly to handshakeListener and connectListener,
- fix SubscriptionHelper#listenerMap remaining empty when an exception occurs while subscribing to a channel,
- remove SubscriptionHelper#handshake as there is always a thread hanging in this method as per [CAMEL-20388](https://issues.apache.org/jira/browse/CAMEL-20388),
- remove the call to closeChannel for topic listeners as they will be removed on SubscriptionHelper#unsubscribe,
- fix replay extension not to overwrite ReplayId per channel if already set.
=> Camel-20918: fix exception handling for Salesforce Streaming API

components/camel-kafka/src/main/docs/kafka-component.adoc
Use better example how to subscribe to multiple topics based on the pattern. As it is Java Pattern when we want to allow arbitrary suffix, we want to use .* instead of just * as that means just arbitrary number of the last character.
- this is a trivial documentation change
=> camel-kafka: Better pattern subscribe documentation sample

core/camel-core-model/src/main/java/org/apache/camel/model/TryDefinition.java, core/camel-core-model/src/test/java/org/apache/camel/model/TryDefinitionTest.java
In the TryDefinition class, the following condition is always true when copyDefinition is used:
if (finallyClause != null && output != finallyClause) {
throw new IllegalArgumentException(
"Multiple finally clauses added: " + finallyClause + " and " + output);
}
Added src/test/java/org/apache/camel/model/TryDefinitionTest.java:
* tryDefinition with only one doFinally
* copyDefinition
* no exception is expected
* tryDefinition with two doFinally
* copyDefinition
* exception is expected
c44620258ef9c82b1e84bb34cff8f68734517cde
TryDefinitionTest: reproduced IllegalArgumentException with only one doFinally clause
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0
Fix: removed if (finallyClause != null && output != finallyClause) and added doFinally clause counter …
=> CAMEL-21014: Fixed doFinally clause with route template

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesCommandTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRunTest.java
- Cluster type specifies the target cluster Kind, Minikube, OpenShift and enables cluster specific configuration options on the export
- Image builder option allows to choose the container image builder technology: jib, docker, podman, s2i
=> CAMEL-21013: Add cluster-type and image-builder export command option

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc, dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationRun.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitHelper.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java
- Use single command option --open-api
- Kubernetes trait configures ConfigMap volume mount for values starting with prefix "configmap:"
- Arbitrary export command adds OpenAPI specification as source to exported project for values without "configmap:" prefix
=> CAMEL-21017: Consolidate open-api options for Camel JBang export command

components/camel-aws/camel-aws-secrets-manager/src/main/docs/aws-secrets-manager-component.adoc, docs/user-manual/modules/ROOT/pages/security.adoc
=> CAMEL-21024 - Camel-AWS-Secrets-Manager: Eventbridge/SQS notifications documentation

core/camel-core/src/test/java/org/apache/camel/support/PropertyBindingSupportConfigurerTest.java, core/camel-support/src/main/java/org/apache/camel/support/PropertyBindingSupport.java
- Make sure to get the map instance from the component when initializing the map via component configurer
- Avoids to lose the 1st value being set on a wrong map instance when component uses its own map instance in the setter
- See Knative ceOverride map
See CAMEL-21035
=> CAMEL-21035: Fix property binding support for map typed values

core/camel-core-model/src/main/java/org/apache/camel/builder/ExpressionClauseSupport.java, core/camel-core-model/src/main/java/org/apache/camel/model/language/TokenizerExpression.java, core/camel-core/src/test/java/org/apache/camel/language/TokenizeLanguageTest.java
Sets `regex` property on `tokenizer()` method on `ExpressionClauseSupport`.
=> Missing regex parameter for TokenizerExpression on ExpressionClauseSupport

tooling/maven/camel-eip-documentation-enricher-maven-plugin/src/main/java/org/apache/camel/maven/EipDocumentationEnricherMojo.java
camel-spring.xsd is being updated quite a bit when devs do builds and devs are having to remove it from their commits quite a bit.     The changes that keep sneaking in look like they are because there are two bean.json's - we need to filter the app/bean.json out when doing documentation enrichment and then the camel-spring.xsd generation will be consistent.
CAMEL-21038 Filter out app/bean.json so that EIPDocumentationEnricher produces consistent results
- [x ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working …
=> CAMEL-21038 Filter out app/bean.json so that EIPDocumentationEnricher produces consistent results

components/camel-as2/camel-as2-component/src/generated/java/org/apache/camel/component/as2/internal/AS2ApiCollection.java, components/camel-box/camel-box-component/src/generated/java/org/apache/camel/component/box/internal/BoxApiCollection.java, components/camel-braintree/src/generated/java/org/apache/camel/component/braintree/internal/BraintreeApiCollection.java, components/camel-dhis2/camel-dhis2-component/src/generated/java/org/apache/camel/component/dhis2/internal/Dhis2ApiCollection.java, components/camel-fhir/camel-fhir-component/src/generated/java/org/apache/camel/component/fhir/internal/FhirApiCollection.java, components/camel-google/camel-google-calendar/src/generated/java/org/apache/camel/component/google/calendar/internal/GoogleCalendarApiCollection.java, components/camel-google/camel-google-drive/src/generated/java/org/apache/camel/component/google/drive/internal/GoogleDriveApiCollection.java, components/camel-google/camel-google-mail/src/generated/java/org/apache/camel/component/google/mail/internal/GoogleMailApiCollection.java, components/camel-google/camel-google-sheets/src/generated/java/org/apache/camel/component/google/sheets/internal/GoogleSheetsApiCollection.java, components/camel-olingo2/camel-olingo2-component/src/generated/java/org/apache/camel/component/olingo2/internal/Olingo2ApiCollection.java, components/camel-olingo4/camel-olingo4-component/src/generated/java/org/apache/camel/component/olingo4/internal/Olingo4ApiCollection.java, components/camel-twilio/src/generated/java/org/apache/camel/component/twilio/internal/TwilioApiCollection.java, components/camel-zendesk/src/generated/java/org/apache/camel/component/zendesk/internal/ZendeskApiCollection.java, tooling/maven/camel-api-component-maven-plugin/src/main/resources/api-collection.vm
* Uses the [initialization-on-demand holder idiom](https://en.wikipedia.org/wiki/Initialization-on-demand_holder_idiom) to avoid using synchronized blocks in Api Collections
=> CAMEL-20199: Remove synchronized block from Api Collections

dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/main-kubernetes-pom.tmpl, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/spring-boot-kubernetes-pom.tmpl, dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/CamelKBaseTest.java, dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationExportTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/ContainerTrait.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/ServiceTrait.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitHelper.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/resources/route-service.yaml
https://issues.apache.org/jira/browse/CAMEL-21032
=> [CAMEL-21032] Generate k8s service for health endpoint

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc, docs/user-manual/modules/ROOT/pages/camel-jbang.adoc, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java, dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationExport.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitHelper.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitHelperTest.java
Add property based trait config in camel-jbang-kuberntes plugin
* support properties traits configuration in `application.properties` with prefix `camel.jbang.trait.*`
* support profile properties trait configuration in `application-<profile>.properties` with prefix `camel.jbang.trait.*`
* define override order in trait configuration: command traits > annotation traits > profile properties traits > properties traits
=> CAMEL-20964: Add property based trait config in camel-jbang-kubernetes

components/camel-python/src/main/java/org/apache/camel/language/python/PythonExpression.java, components/camel-python/src/main/java/org/apache/camel/language/python/PythonLanguage.java, components/camel-python/src/test/java/org/apache/camel/language/python/PythonScriptingLanguageTest.java, components/camel-python/src/test/java/org/apache/camel/language/python/PythonTest.java, components/camel-python/src/test/resources/mypython.py
Instead of calling `PythonInterpreter`'s `eval(String s)` method each time we evaluate python expression, we can call `compile(String script)` method, cache the `PyCode` result and call `eval(PyObject code)`. This way we avoid making unnecessary `Py.compile_flags` calls.
This is also needed for camel-quarkus-python extension (https://github.com/apache/camel-quarkus/issues/4408) because if we're compiling expressions each time on evaluation, there is nothing to pre-process at the build stage.
=> make PythonLanguage and PythonExpression cache compiled PyCode objects

components/camel-azure/camel-azure-servicebus/src/main/java/org/apache/camel/component/azure/servicebus/client/ServiceBusClientFactory.java
The Azure Service Bus client requires that a FQNS be specified when not using a connection string. This was not being done in all applicable configurations.
=> CAMEL-21044: Fix missing Azure Service Bus FQNS configuration

components/camel-mllp/src/main/java/org/apache/camel/component/mllp/internal/Hl7Util.java, components/camel-mllp/src/test/java/org/apache/camel/component/mllp/internal/Hl7UtilTest.java
When using Camel MLLP an ACK is sent for each message received. Each ACK contains a timestamp in MSH-7.1. The ACK being sent was using an invalid pattern for this timestamp: yyyyMMddHHmmssSSSZZZZ instead of yyyyMMddHHmmss.SSSZZZZ (see: https://hl7-definition.caristix.com/v2/HL7v2.5.1/DataTypes/DTM)
main
[https://issues.apache.org/jira/browse/CAMEL-21048](https://issues.apache.org/jira/browse/CAMEL-21048)
=> CAMEL-21048: Add required dot in MLLP ACK timestamp pattern.

dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/Bind.java, dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationLogs.java, dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationRun.java, dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationLogsTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesDelete.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/PodLogs.java
- Support file path as a command parameter and automatically derive the integration name from the file name
- Support --name and --label arguments in Camel K plugin logs command
=> Improve JBang Kubernetes plugin logs command parameter

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/AS2DispositionModifier.java
=> CAMEL-21064: camel-as2: Parse HTTP headers case-insensitive

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/IngressTrait.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitCatalog.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitContext.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitHelper.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesCommandTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRunTest.java, parent/pom.xml
* Implement Ingress trait that is capable of configuring the Kubenetes Ingress resource
* Fix parsing of annotations in traits
* Complete bump fabric8 version from 6.13.1 to 6.13.2
=> CAMEL-21000: camel-jbang Kubernetes - Add Ingress trait

dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationExportTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/ClusterType.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesDelete.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesHelper.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java
- Fix deploy to OpenShift for runtime Quarkus
- Use cluster specific Kubernetes manifest to deploy to OpenShift (kubernetes.yml or openshift.yml)
- Make sure generated manifest includes OpenShift specific resources such as ImageStream or BuildConfig
- Fix image builder name for S2i (use openshift instead of s2i)
=> CAMEL-21013: Fix JBang kubernetes plugin deployment to OpenShift

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
No need to pin the kubernetes-client version anymore as Camel uses Quarkus 3.13.1
=> chore(camel-jbang): Remove obsolete kubernetes-client workaround

components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/TestExecutionConfiguration.java
Preventing enabling adviceWith is overly restrictive and blocks usage of a valid user feature.
=> CAMEL-21078: allow enabling adviceWith

components/camel-platform-http/src/main/java/org/apache/camel/component/platform/http/PlatformHttpEndpoint.java, components/camel-platform-http/src/test/java/org/apache/camel/component/platform/http/JettyCustomPlatformHttpConsumer.java, components/camel-platform-http/src/test/java/org/apache/camel/component/platform/http/PlatformHttpReturnHttpRequestHeadersTest.java
- fix typo in PlatformHttpEndpoint that was calling applyFilterToExternalHeaders in place where applyFilterToCamelHeaders must be called; added test that covers this behavior
https://issues.apache.org/jira/browse/CAMEL-20638
=> CAMEL-20638: camel-platform-http - Do not return http request headers - FIX

components/camel-fhir/camel-fhir-api/pom.xml, components/camel-fhir/camel-fhir-component/pom.xml
fhir transitive dependency rely on 2.11.0. Some components like camel-csv can use API which appeared in newer versions of commons-io (for instance Uncheck in 2.12.0).
=> CAMEL621093 - align commons-io for fhir component

parent/pom.xml, test-infra/camel-test-infra-azure-common/src/test/resources/org/apache/camel/test/infra/azure/common/services/container.properties
Update azure-sdk-bom to 1.2.26 and upgrade the azurite container to 3.31.0 on 4.4.x
Built -DskipTests successfully and ran azure tests locally.
=> Update azure-sdk-bom to 1.2.26

dsl/camel-jbang/camel-jbang-core/pom.xml, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelJBangMain.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/exceptionhandler/MissingPluginParameterExceptionHandler.java, dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/exceptionhandler/ParameterExceptionHandlerTest.java
when a plugin might not be installed and is required
see documentation in picocli https://picocli.info/#_handling_errors it is providing the example providing the same message than the default handler
This can be further improved if we have access to the list of installable plugins and providing the exact command to do it.
=> CAMEL-21011 - improve error message with Camel JBang

test-infra/camel-test-infra-rabbitmq/src/test/java/org/apache/camel/test/infra/rabbitmq/services/RabbitMQLocalContainerService.java
to stabilize build on CI
less chance to hit https://ci-builds.apache.org/job/Camel/job/Camel%20Core%20(Build%20and%20test)/job/main/315/testReport/junit/org.apache.camel.component.springrabbit.integration/RabbitMQProducerToDIT/BuildAndTest___Matrix___JDK_NAME____jdk_17_latest___PLATFORM____ppc64le____Test______/
```
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image rabbitmq:3.13-management
at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:359)
at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:330)
at org.apache.camel.test.infra.rabbitmq.services.RabbitMQLocalContainerService.initialize(RabbitMQLocalContainerService.java:100)
at org.apache.camel.test.infra.common.services.TestServiceUtil.tryIn …
```
=> Configure test container rabbitMQ with several startup attempt

test-infra/camel-test-infra-solr/src/test/java/org/apache/camel/test/infra/solr/services/SolrLocalContainerService.java
to stabilize build on CI
it shoudl avoid this kind of errors:
```
[ERROR] org.apache.camel.component.solr.integration.SolrCloudProducerIT -- Time elapsed: 93.50 s <<< ERROR!
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image solr:9.6.1
at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:359)
at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:330)
at org.apache.camel.test.infra.solr.services.SolrLocalContainerService.initialize(SolrLocalContainerService.java:41)
at org.apache.camel.test.infra.common.services.TestServiceUtil.tryInitialize(TestServiceUtil.java:43)
at org.apache.camel.test.infra.solr.services.SolrService.beforeAll(SolrService.java:36)
at …
```
=> Configure test container Solr with several startup attempt

catalog/camel-csimple-maven-plugin/src/main/java/org/apache/camel/maven/GenerateMojo.java, components/camel-test/camel-test-spring-junit5/src/main/java/org/apache/camel/test/spring/junit5/CamelSpringTestSupport.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/AbstractGenerateConfigurerMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojo.java
StringWriter uses the StringBuffer under the hood, so it's good to avoid if possible.
=> (chores) avoid using StringWriter if possible

components/camel-tahu/pom.xml, components/camel-tahu/src/test/java/org/apache/camel/component/tahu/TahuEdgeProducerIT.java, components/camel-tahu/src/test/java/org/apache/camel/component/tahu/TahuHostConsumerIT.java, components/camel-tahu/src/test/java/org/apache/camel/component/tahu/handlers/TahuEdgeClientManualIT.java, components/camel-tahu/src/test/java/org/apache/camel/component/tahu/handlers/TahuHostApplicationManualIT.java
Some Tahu tests are requiring a container to be started. Moved them to IT tests. It allows to not play them on s390x and ppc64le architecture as these containers require HiveMQ container which is not available on these platforms.
fix main branch, see https://ci-builds.apache.org/job/Camel/job/Camel%20Core%20(Build%20and%20test)/job/main/327/testReport/org.apache.camel.component.tahu/
=> Do not play some tests of Tahu on s390x and ppc64le

core/camel-base/src/generated/java/org/apache/camel/converter/CamelBaseBulkConverterLoader.java, core/camel-base/src/main/java/org/apache/camel/converter/IOConverter.java, core/camel-base/src/main/java/org/apache/camel/converter/NIOConverter.java, core/camel-core/src/test/java/org/apache/camel/language/simple/SimpleOverrideMethodTest.java, core/camel-support/src/main/java/org/apache/camel/support/ExchangeHelper.java, core/camel-support/src/main/java/org/apache/camel/support/MessageHelper.java, core/camel-util/src/main/java/org/apache/camel/util/FileUtil.java, core/camel-util/src/main/java/org/apache/camel/util/IOHelper.java, core/camel-xml-jaxp/src/generated/java/org/apache/camel/converter/jaxp/CamelXmlJaxpBulkConverterLoader.java, core/camel-xml-jaxp/src/main/java/org/apache/camel/converter/jaxp/XmlConverter.java
Provides better support for conveying `java.nio.file.Path` objects in messages with the same converters that are registered for `java.io.File` objects.
JIRA issue: https://issues.apache.org/jira/browse/CAMEL-21119
=> [CAMEL-21119] Improve support for java.nio.file.Path

apache-camel/pom.xml, catalog/camel-allcomponents/pom.xml, components/camel-jaxb/pom.xml, components/camel-jmx/pom.xml, components/camel-parquet-avro/pom.xml, components/camel-salesforce/camel-salesforce-component/pom.xml, components/camel-soap/pom.xml, components/camel-swift/pom.xml, docs/pom.xml, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_8.adoc, dsl/camel-componentdsl/pom.xml, dsl/camel-endpointdsl/pom.xml, pom.xml, tests/camel-itest/pom.xml, tooling/enforcer-rules/pom.xml, tooling/enforcer-rules/src/main/resources/camel-banned-dependencies.xml, tooling/pom.xml
org.glassfish.jaxb:jaxb-runtime is the new Jakarta implementation of JAXB. It should be preferred to the old com.sun.xml.bind:jaxb-impl
No Jira, because this is just housekeeping. But I can create one, if needed.
=> Ban com.sun.xml.bind:jaxb-impl, replace it with jaxb-runtime where needed

components/camel-tahu/pom.xml, components/camel-tahu/src/test/java/org/apache/camel/component/tahu/TahuEdgeProducerIT.java, components/camel-tahu/src/test/resources/logback-test.xml
This should fix test instabilities caused by Tahu (introduced in #15088):
- Set a max upper limit for the execution
- Disable unstable tests
=> CAMEL-21143: disable unstable camel-tahu tests + set execution limit

core/camel-util/src/main/java/org/apache/camel/util/StringHelper.java, tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/Strings.java
Adjust String-related copied/pasted code in tooling to match that of
camel-util so that our sins can get flagged by IDEs and SCA tools, so it
can be fixed in the future
=> (chores) make copy/pasted code consistent

components/camel-soap/pom.xml
it was previously excluded because the dependency was coming from jaxb-api->jaxb-runtime, in
https://github.com/apache/camel/commit/651957d7083e8915a14120539d393681d97717ba jaxb-api has been removed, so we now need to get the transitive dependency from saaj-impl
=> CAMEL-21146 - remove exclusion in soap component to stax-ex

docs/user-manual/modules/ROOT/pages/camel-3-migration-guide.adoc, docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_11.adoc, docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_14.adoc, docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_18.adoc, docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_20.adoc, docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_21.adoc, docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_22.adoc, docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_7.adoc, docs/user-manual/modules/ROOT/pages/camel-4-migration-guide.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_1.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_2.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_3.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_4.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_5.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_6.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_7.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide.adoc
Fix typos and grammar issues on the upgrade guides
Added a special focus on recent versions, but also a few of the LTSs
from 3.x + the migration guides.
=> (chores) upgrade guides: fixed typos and grammar issues

components/camel-dhis2/camel-dhis2-component/src/main/java/org/apache/camel/component/dhis2/Dhis2Component.java, components/camel-direct/src/main/java/org/apache/camel/component/direct/DirectComponent.java, components/camel-disruptor/src/main/java/org/apache/camel/component/disruptor/DisruptorComponent.java, components/camel-disruptor/src/main/java/org/apache/camel/component/disruptor/DisruptorEndpoint.java, components/camel-disruptor/src/main/java/org/apache/camel/component/disruptor/DisruptorReference.java, components/camel-elasticsearch/src/main/java/org/apache/camel/component/es/ElasticsearchProducer.java, components/camel-etcd3/src/main/java/org/apache/camel/component/etcd3/cloud/Etcd3WatchServiceDiscovery.java, components/camel-etcd3/src/main/java/org/apache/camel/component/etcd3/policy/Etcd3RoutePolicy.java, components/camel-file/src/main/java/org/apache/camel/component/file/FileOperations.java, components/camel-file/src/main/java/org/apache/camel/component/file/GenericFileProducer.java, components/camel-file/src/main/java/org/apache/camel/component/file/cluster/FileLockClusterService.java, components/camel-file/src/main/java/org/apache/camel/component/file/cluster/FileLockClusterView.java, components/camel-freemarker/src/main/java/org/apache/camel/component/freemarker/FreemarkerComponent.java, components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/SftpOperations.java, core/camel-api/src/main/java/org/apache/camel/support/service/BaseService.java
* Replace mutex with locks
* Use locks instead of synchronized blocks in case of a potentially long locking
=> CAMEL-20199: Remove synchronized block from components D to F

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/protocol/ResponseMDN.java, components/camel-as2/camel-as2-component/src/main/java/org/apache/camel/component/as2/internal/AS2PropertiesHelper.java, components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/KinesisConnection.java, components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Consumer.java, components/camel-bean/src/main/java/org/apache/camel/component/bean/AbstractCamelInvocationHandler.java, components/camel-box/camel-box-component/src/main/java/org/apache/camel/component/box/internal/BoxPropertiesHelper.java, components/camel-braintree/src/main/java/org/apache/camel/component/braintree/BraintreeConfiguration.java, components/camel-braintree/src/main/java/org/apache/camel/component/braintree/internal/BraintreePropertiesHelper.java, components/camel-coap/src/main/java/org/apache/camel/coap/CoAPComponent.java, components/camel-coap/src/main/java/org/apache/camel/coap/CoAPProducer.java, components/camel-consul/src/main/java/org/apache/camel/component/consul/ConsulEndpoint.java, components/camel-controlbus/src/main/java/org/apache/camel/component/controlbus/ControlBusComponent.java, components/camel-dhis2/camel-dhis2-component/src/main/java/org/apache/camel/component/dhis2/internal/Dhis2PropertiesHelper.java, components/camel-dropbox/src/main/java/org/apache/camel/component/dropbox/util/DropboxPropertyManager.java, components/camel-fhir/camel-fhir-component/src/main/java/org/apache/camel/component/fhir/internal/FhirPropertiesHelper.java, components/camel-google/camel-google-bigquery/src/main/java/org/apache/camel/component/google/bigquery/GoogleBigQueryConnectionFactory.java, components/camel-google/camel-google-calendar/src/main/java/org/apache/camel/component/google/calendar/internal/GoogleCalendarPropertiesHelper.java, components/camel-google/camel-google-drive/src/main/java/org/apache/camel/component/google/drive/internal/GoogleDrivePropertiesHelper.java, components/camel-google/camel-google-mail/src/main/java/org/apache/camel/component/google/mail/internal/GoogleMailPropertiesHelper.java, components/camel-google/camel-google-sheets/src/main/java/org/apache/camel/component/google/sheets/internal/GoogleSheetsPropertiesHelper.java, components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/policy/HazelcastRoutePolicy.java, components/camel-http-common/src/main/java/org/apache/camel/http/common/DefaultHttpRegistry.java, components/camel-http/src/main/java/org/apache/camel/component/http/HttpEndpoint.java, components/camel-iec60870/src/main/java/org/apache/camel/component/iec60870/AbstractConnectionMultiplexor.java, components/camel-iec60870/src/main/java/org/apache/camel/component/iec60870/AbstractIecComponent.java, components/camel-iec60870/src/main/java/org/apache/camel/component/iec60870/client/ClientConnection.java, components/camel-infinispan/camel-infinispan-embedded/src/main/java/org/apache/camel/component/infinispan/embedded/cluster/InfinispanEmbeddedClusterView.java, components/camel-infinispan/camel-infinispan/src/main/java/org/apache/camel/component/infinispan/remote/cluster/InfinispanRemoteClusterView.java, components/camel-irc/src/main/java/org/apache/camel/component/irc/IrcComponent.java, tests/camel-itest/src/test/java/org/apache/camel/itest/utils/extensions/JmsServiceExtension.java
* Replace mutex with locks
* Use locks instead of synchronized blocks
* Use ConcurrentHashMap instead of HashMap when possible
=> CAMEL-20199: Remove synchronized block from components G to I

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/DevModeITCase.java, dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/JBangTestSupport.java
Adds tests for [this part of documentation](https://camel.apache.org/manual/camel-jbang.html#_uploading_files_to_source_directory_via_http)
Also an additional set of methods to check logs don't contain a string and debug prints when a command fails inside host.
=> CAMEL-20367: Adds tests for file management via http in dev mode

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/RouteTrait.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/knative/KnativeServiceTrait.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesCommandTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRunTest.java
- Route trait only applies to OpenShift clusters
- Not all services should be exposed via Route resource
- Users need to explicitly enable the route trait because of that
- Avoids to add Route resource to non OpenShift clusters
=> chore(camel-jbang): Fix route trait

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/LoggingLevelsITCase.java
Adds tests for [this part of documentation](https://camel.apache.org/manual/camel-jbang.html#_configuring_logging_levels)
We have decided to not add more frameworks, therefore the subchapter "Configuring individual logging levels" is not covered by these tests.
=> CAMEL-20367: Adds logging levels tests

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/PodLogs.java
- File watch directory has been set to "null" by accident when running a single source file
- Avoid to lose pod log tracker when pods are terminating due to deployment update
=> chore(camel-jbang): Fix dev mode in Kubernetes run command

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/IngressTrait.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesCommandTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRunTest.java
- Users need to explicitly enable the ingress trait as it is optional to many environments and the getting-started experience
=> chore(camel-jbang): Disable ingress trait by default

components/camel-kafka/pom.xml, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/common/KafkaProperties.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/ContainerLocalKafkaService.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/KafkaServiceFactory.java, test-infra/camel-test-infra-kafka/src/test/resources/org/apache/camel/test/infra/kafka/services/container.properties
Kafka 2.x has reached end of life on June 2023
It allows to simplify codebase and will ease migration of containers from Confluent to Apache ones. see https://issues.apache.org/jira/browse/CAMEL-20593
It will also reduce time execution of build. For me locally, it went from 13 minutes to 7 minutes to build and test the Camel Kafka component.
=> Remove tests for kafka 2

components/camel-azure/camel-azure-servicebus/pom.xml, components/camel-azure/camel-azure-servicebus/src/main/java/org/apache/camel/component/azure/servicebus/ServiceBusHeaderFilterStrategy.java, components/camel-azure/camel-azure-servicebus/src/test/java/org/apache/camel/component/azure/servicebus/ServiceBusHeaderFilterStrategyTest.java
The default `HeaderFilterStrategy` created when automatic header propagation was implemented for the Service Bus did not take steps to ensure that propagated headers are of a Java type that can be encoded as an application property by the underlying client libraries.
This would lead to errors of the form: `com.azure.messaging.servicebus.ServiceBusException: No encoding is known for map entry value of type: <unmappable class name>`
=> CAMEL-21211: Azure Service Bus - filter unknown header types

components/camel-platform-http-jolokia/src/test/java/org/apache/camel/component/platform/http/plugin/DefaultJolokiaPlatformHttpPluginTest.java
This breaks the tests whenever there is an upgrade
=> (chores) camel-platform-http: do not test for Jolokia version

components/camel-univocity-parsers/pom.xml, components/camel-univocity-parsers/src/generated/resources/META-INF/services/org/apache/camel/dataformat.properties, components/camel-univocity-parsers/src/main/java/org/apache/camel/dataformat/univocity/AbstractUniVocityDataFormat.java, components/camel-univocity-parsers/src/main/java/org/apache/camel/dataformat/univocity/HeaderRowProcessor.java, components/camel-univocity-parsers/src/main/java/org/apache/camel/dataformat/univocity/UniVocityCsvDataFormat.java, components/camel-univocity-parsers/src/main/java/org/apache/camel/dataformat/univocity/UniVocityFixedDataFormat.java, components/camel-univocity-parsers/src/main/java/org/apache/camel/dataformat/univocity/UniVocityTsvDataFormat.java, parent/pom.xml
* remove locking for lazy initialized fields, as those are not very expensive to create, so worst case, we have double initiatization, which is not a problem
* move the TLS into the HeaderRowProcessor
* remove 'or not' in 'whether or not'
=> Use the newly maintained univocity parsers

components/camel-zipfile/src/main/java/org/apache/camel/processor/aggregate/zipfile/ZipAggregationStrategy.java, components/camel-zipfile/src/test/java/org/apache/camel/dataformat/zipfile/ZipFileSplitAndDeleteTest.java, components/camel-zipfile/src/test/java/org/apache/camel/dataformat/zipfile/ZipFileSplitOneFileTest.java, components/camel-zipfile/src/test/java/org/apache/camel/dataformat/zipfile/ZipSplitterRouteIssueTest.java, components/camel-zipfile/src/test/java/org/apache/camel/processor/aggregate/zipfile/AggregationStrategyWithFilenameHeaderTest.java, components/camel-zipfile/src/test/java/org/apache/camel/processor/aggregate/zipfile/AggregationStrategyWithPreservationTest.java, components/camel-zipfile/src/test/java/org/apache/camel/processor/aggregate/zipfile/ZipAggregationStrategyEmptyFileTest.java, components/camel-zipfile/src/test/java/org/apache/camel/processor/aggregate/zipfile/ZipAggregationStrategyNullBodyTest.java, components/camel-zipfile/src/test/java/org/apache/camel/processor/aggregate/zipfile/ZipAggregationStrategySplitTest.java, components/camel-zipfile/src/test/java/org/apache/camel/processor/aggregate/zipfile/ZipAggregationStrategyTest.java
See https://camel.zulipchat.com/#narrow/stream/257298-camel/topic/Idiomatic.20way.20to.20pollEnrich.20until.20there.20are.20no.20more.20items: In case one of the incoming bodies is null, this change should avoid failure of ZipAggregationStrategy.
I also addressed SonarQube warnings about cognitive complexity and removed deprecated annotations from test code while I was at it.
Viewing the three commits individually is probably best to see what changed in terms of functionality and what was just refactoring.
=> Zipsplitter null body

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/CmdStartStopITCase.java, dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/JBangTestSupport.java
Adds tests for [this part of documentation](https://camel.apache.org/manual/camel-jbang.html#_starting_and_stopping_routes)
=> CAMEL-20367: Adds Cmd start stop route tests

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/PlatformHttpITCase.java, dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/JBangTestSupport.java, dsl/camel-jbang/camel-jbang-it/src/test/resources/jbang/it/server.yaml
Adds test for [this part of documentation](https://camel.apache.org/manual/camel-jbang.html#_using_the_platform_http_component)
=> CAMEL-20367: Adds platform-http component test

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/ListServiceITCase.java
Adds test for [this part of documentation](https://camel.apache.org/manual/camel-jbang.html#_listing_services)
Please note that this should be merged after https://github.com/apache/camel/pull/15648 as it uses resources added in that commit.
=> CAMEL-20367: Adds list service test

components/camel-lra/src/main/java/org/apache/camel/service/lra/LRASagaRoutes.java, components/camel-lra/src/main/java/org/apache/camel/service/lra/LRAUrlBuilder.java, components/camel-lra/src/test/java/org/apache/camel/service/lra/LRASagaRoutesTest.java
Enable Oracle MicroTX lra-coordinator compatibility (https://issues.apache.org/jira/browse/CAMEL-21216).
1) While joining an LRA Transaction, the payload sent by Apache Camel is URL encoded (fix in: LRAUrlBuilder.java)
2) The Query parameter sent by Oracle LRA coordinator are url encoded, but will not be decoded by Apache Camal LRA (see also: CAMEL-21197) (workaround in: LRASagaRoutes.java)
The changes are backwards compatible to Narayana lra-coordinator.
=> CAMEL-21216: Apache Camel LRA does not work with Oracle MicroTX LRA coordinator

camel-dependencies/pom.xml, components/camel-zeebe/pom.xml, docs/user-manual/modules/ROOT/pages/camel-report-maven-plugin.adoc, parent/pom.xml, tests/camel-itest/pom.xml, tooling/maven/sync-properties-maven-plugin/src/main/java/org/apache/camel/maven/sync/properties/SyncPropertiesMojo.java
Noticed today that sync-properties-maven-plugin will not sync a property where the format is `<project>.<version>`, but only syncs `<project>-<version>`.      Added a check to sync-properties-maven-plugin that errors if a property is added to camel-parent of the "project.version" format with an explanation so we can catch these, and changed the two properties that are not being synced from camel-parent to camel-dependencies to match the correct version.
=> CAMEL-21252 Add checking for non .*-versions to sync-properties-maven-plugin

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc
While creating tests it was noticed that some options listed in documentation are incorrect. These corrected options were listed in camel cli help prints.
=> Update options in camel-jbang.adoc

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Export.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportCamelMain.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportQuarkus.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportSpringBoot.java, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/main-pom.tmpl, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-pom.tmpl, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/spring-boot-pom.tmpl, dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/ExportTest.java
Added a build propertues required as specified in https://maven.apache.org/guides/mini/guide-reproducible-builds.html
=> feat(jbang): make export reproducible

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc
`camel dependency` works, however `camel dependency --output=maven` (or when passing any options) does not and requires the `list` command. I included it in the command without options as well for the sake of consistency.
=> Update commands in camel-jbang.adoc

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/DependencyListITCase.java
Adds tests for [gathering](https://camel.apache.org/manual/camel-jbang.html#_gathering_list_of_dependencies) and [copying](https://camel.apache.org/manual/camel-jbang.html#_copying_dependency_jars_to_a_specific_directory) dependencies
=> CAMEL-20367: Adds dependency listing tests

parent/pom.xml
This reverts commit 8e3e4847eb101c9234625bc232037e796f78eb46.
=> Revert "chore(deps): Bump swagger-openapi3-version from 2.2.23 to 2.2.24"

components/camel-github/src/main/java/org/apache/camel/component/github/consumer/CommitConsumer.java, components/camel-github/src/test/java/org/apache/camel/component/github/consumer/CommitConsumerLastTest.java
I encountered an issue using startingSha=last with a repository with a large history.  The last sha is not correctly resolved.   [CAMEL-17473](https://issues.apache.org/jira/browse/CAMEL-17473) did not resolve this issue.  
The following issues were discovered from real-world testing and a unit test:
1. it appears that the first commit returned from the GitHub API is the most recent and the sha from that should be used as the lastSha variable.
2. There is a threading issue where CommitConsumer.poll() can be called concurrently with CommitConsumer.doStart().  In some situations lastSha can be null in the poll() method, producing the same behavior as startingSha=beginning, which is undesired.
=> CAMEL-21256: camel-github startingSha=last does not work with large history

components/camel-tarfile/src/main/java/org/apache/camel/processor/aggregate/tarfile/TarAggregationStrategy.java, components/camel-tarfile/src/test/java/org/apache/camel/dataformat/tarfile/SpringTarFileDataFormatTest.java, components/camel-tarfile/src/test/java/org/apache/camel/dataformat/tarfile/SpringTarSplitterRouteTest.java, components/camel-tarfile/src/test/java/org/apache/camel/dataformat/tarfile/TarFileDataFormatTest.java, components/camel-tarfile/src/test/java/org/apache/camel/dataformat/tarfile/TarFileSplitAndDeleteTest.java, components/camel-tarfile/src/test/java/org/apache/camel/dataformat/tarfile/TarFileSplitIteratorCorruptTest.java, components/camel-tarfile/src/test/java/org/apache/camel/dataformat/tarfile/TarSplitterRouteIssueTest.java, components/camel-tarfile/src/test/java/org/apache/camel/processor/aggregate/tarfile/AggregationStrategyWithFilenameHeaderTest.java, components/camel-tarfile/src/test/java/org/apache/camel/processor/aggregate/tarfile/AggregationStrategyWithPreservationTest.java, components/camel-tarfile/src/test/java/org/apache/camel/processor/aggregate/tarfile/TarAggregationStrategyEmptyFirstFileTest.java, components/camel-tarfile/src/test/java/org/apache/camel/processor/aggregate/tarfile/TarAggregationStrategyNullBodyTest.java, components/camel-tarfile/src/test/java/org/apache/camel/processor/aggregate/tarfile/TarAggregationStrategyTest.java
Same as https://github.com/apache/camel/pull/15638, just for the tar component, this time: Avoid exception in TarAggregationStrategy when one of the bodies is null.
=> Tar aggregation strategy null bodies

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_8.adoc, docs/user-manual/modules/ROOT/pages/camel-jbang.adoc, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Export.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java
To stay coherent with other commands and keep working when using --camel-version using a previous version.
Removed the --repository option which would require a bunch of other changes to support it correctly
=> CAMEL-21283 - Switch back to repos parameter in Camel JBang run and export commands

components/camel-jsonpath/src/main/java/org/apache/camel/jsonpath/JsonPathEngine.java, components/camel-jsonpath/src/test/java/org/apache/camel/jsonpath/JsonPathNullHeaderTest.java
=> CAMEL-21306: camel-jsonpath - Null should be accepted return value

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/knative/KnativeTrait.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/Knative.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportBaseTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportKnativeTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java
* Implement knative trait filters option in camel jbang kubernetes plugin
* Separate knative export tests and some clean code
* Add documentation on knative trait
=> CAMEL-21295: Add knative trait filters to camel jbang kubernetes plugin

test-infra/camel-test-infra-opensearch/src/test/java/org/apache/camel/test/infra/opensearch/common/OpenSearchProperties.java, test-infra/camel-test-infra-opensearch/src/test/java/org/apache/camel/test/infra/opensearch/services/OpenSearchLocalContainerService.java, test-infra/camel-test-infra-opensearch/src/test/resources/org/apache/camel/test/infra/opensearch/services/container.properties
the ppc64le image is provided separately. The "official" OpenSearch container does not support ppc64le
it will fix tests on main branch
note that I do not have access to a ppc64le machine so cannot test that it is really fixing the issue
=> CAMEL-21334 - use specific ppc64le container image for OpenSearch Integration tests

components/camel-kamelet/src/main/java/org/apache/camel/component/kamelet/Kamelet.java, components/camel-kamelet/src/main/java/org/apache/camel/component/kamelet/KameletComponent.java, core/camel-api/src/main/java/org/apache/camel/RouteTemplateContext.java, core/camel-core-engine/src/main/java/org/apache/camel/impl/DefaultModel.java, core/camel-core-model/src/main/java/org/apache/camel/model/DefaultRouteTemplateContext.java, core/camel-util/src/main/java/org/apache/camel/util/IOHelper.java
- Consider environment variables when validating Kamelet parameter configuration
- Avoids errors due to missing required Kamelet parameter validation when parameter is configured via environment variables
See CAMEL-21336
=> CAMEL-21336: Allow Kamelets configured by EnvVars only

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java, core/camel-core-model/src/main/java/org/apache/camel/model/rest/ParamDefinition.java, dsl/camel-kamelet-main/pom.xml, dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/reload/OpenApiGeneratorReloadStrategy.java, tooling/openapi-rest-dsl-generator/pom.xml, tooling/openapi-rest-dsl-generator/src/main/java/org/apache/camel/generator/openapi/RestDslGenerator.java, tooling/openapi-rest-dsl-generator/src/main/java/org/apache/camel/generator/openapi/RestDslXmlGenerator.java, tooling/openapi-rest-dsl-generator/src/main/java/org/apache/camel/generator/openapi/RestDslYamlGenerator.java
=> CAMEL-21342: camel-kamelet-main - openapi generator should be optional and downloaded dynamically

components/camel-seda/src/main/java/org/apache/camel/component/seda/SedaConsumer.java
Fix for https://issues.apache.org/jira/browse/CAMEL-21343 (4.8)
The component camel-vm is still frequently used by the community so even if it has been decided to remove it from camel, we need to provide a way to mimic its behavior to ease the migration to recent camel versions.
* Add methods meant to be overridden to mimic the behavior of camel-vm
=> CAMEL-21343: camel-seda - Allow to mimic the behavior of camel-vm

.github/actions/install-packages/action.yml, components/camel-jackson-avro/pom.xml
@davsclaus the tests are successful, but with this PR we are going to upgrade avro from `1.8.2` to `1.11.4`
=> Fix Avro CVE In Jackson Databind Avro

components/camel-jetty-common/src/main/java/org/apache/camel/component/jetty/JettyHttpComponent.java, components/camel-jetty/src/main/java/org/apache/camel/component/jetty12/JettyHttpComponent12.java
When using camel 4.4.x, I found that the Jetty component cannot flexibly configure sniHostCheck and turn off SNI verification.I need to inherit and rewrite the httpConfig.addCustomizer(new SecureRequestCustomizer()) in the createConnectorJettyInternal method of JettyHttpComponent in the project and replace it with httpConfig.addCustomizer(new SecureRequestCustomizer(false)); this is quite troublesome! So I submit the following changes: JettyHttpComponent adds the secureRequestCustomizer attribute, which can be customized in the project and flexibly loaded into the Jetty component
- [4.4.x]
- [main]
=> [Jetty] custom SecureRequestCustomizer configuration

components/camel-opensearch/pom.xml, test-infra/camel-test-infra-opensearch/src/test/java/org/apache/camel/test/infra/opensearch/common/OpenSearchProperties.java, test-infra/camel-test-infra-opensearch/src/test/java/org/apache/camel/test/infra/opensearch/services/OpenSearchLocalContainerService.java, test-infra/camel-test-infra-opensearch/src/test/resources/org/apache/camel/test/infra/opensearch/services/container.properties
kudos to @anushkajuli
tested on a PowerPC machine https://issues.apache.org/jira/browse/CAMEL-21334?focusedCommentId=17889437&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17889437
=> CAMEL-21334 - Open search ppc64le integration tests activation

core/camel-core/src/test/java/org/apache/camel/impl/engine/DefaultSupervisingRouteControllerTest.java
the 2 exhausted failure collected were not always the last two. So adapting the assertion to check in the full list the right number of exhausted failure instead of the last 2 elements.
Based on what I understand from the codebase, the order is not important (but if it the case, we need to fix something in runtime code and not the test)
Note that this test was failing very often on different architecture (so usually marked with a last failure of 1)
For instance:
https://ci-builds.apache.org/job/Camel/job/Camel%20Core%20(Build%20and%20test)/job/main/475/testReport/junit/org.apache.camel.impl.engine/DefaultSupervisingRouteControllerTest/BuildAndTest___Matrix___JDK_NAME____jdk_21_latest___PLATFORM____ubuntu_avx____Test___testSupervising_2/ …
=> chore: avoid flakiness of DefaultSupervisingTest

core/camel-core/src/test/java/org/apache/camel/impl/engine/DefaultSupervisingRouteControllerTest.java
Previous improvement of assertion was when the list of failure was not arriving always in the same order. But the test is still flaky, there are 2 reasons:
* the exception was not set yet as all retries were not finished
* the lists used in test to collect events and failures were not synchronized and can be called in different threads. It seems that it was causing some elements to not be added correctly. I suspected a caught ConcurrentModificationException but in debug mode it is not hit. So not sure the root reason using syncehonizedList seems to do the trick.
Using @RepeatedTest locally, I had between 5 and 15 tests in error on 50 attempts before. Now I hit 100% success.
last falky failure on Ci https://ci-builds.apache.org/job/Camel/job/Camel%20Core%20(Build%20and%20test)/job/main/last …
=> chore: stabilizing DefaultSupervisingRouteControllerTest

core/camel-main/src/main/java/org/apache/camel/main/Main.java, core/camel-main/src/main/java/org/apache/camel/main/MainCommandLineSupport.java
super constructor in MainSupport use `Class<? extends CamelConfiguration>`, but in MainCommandLineSupport and Main use `Class<CamelConfiguration>`.
=> Changed Main constructor in camel-main to use instances CamelConfiguration

components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FtpRecursiveDepth2IT.java
this test failed several times in a row on Jenkins Ci with slightly different errors.
```
mock://result Message with body a2 was expected but not found in [b2,
b3, b2, a3]
```
```
mock://result Message with body a3 was expected but not found in [b3,
b2]
```
When playing locally with @RepeatedTest(100), I do not reproduce the error but noticed that 4 or 5 tests took more than 5 seconds although others took 1 second. When I tried to set a low timeout locally, it is failing the test with similar kind of errors.
So trying with an higher timeout, even though it seems strange that there can be that much variation in route execution.
=> chore: stabilize FtpRecursiveDepth2IT

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/JolokiaITCase.java, dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/JBangTestSupport.java
Adds tests for [Jolokia and Hawtio](https://camel.apache.org/manual/camel-jbang.html#_using_jolokia_and_hawtio).
The `hawtio` command does not support a `--background` option and capturing the output of the command is not really possible until it terminates, so in the hawtio test the assertion is made on the expected output of `curl` and Jolokia being attached.
=> CAMEL-20367: Adds Jolokia and Hawtio tests

core/camel-core/src/test/java/org/apache/camel/processor/MulticastParallelStreamingTest.java
The test is flaky on CI.
Locally, I was able to have it flaky locally with a delay of 3 milliseconds (1 failure out of 100). It was previously 250 milliseconds delay. it seems to not be always enough on Jenkins CI. Which is a bit weird as it is quite huge gap.
Trying with a more important delay.
The order of received message is only based on this delay but if the second route is not executing in this delay, the test is failing. There is no other controls on that, there is no guarantee at Camel level to respect a specific order.
it was causing this kind of error:
```
java.lang.AssertionError: Caught exception on mock://result due to: expected: <BA> but was: <AB>
at org.apache.camel.component.mock.MockEndpoint.fail(MockEndpoint.java:2013)
at …
```
=> chore: stabilize MulticastParallelStreamingTest.testMulticastParallel()

components/camel-knative/camel-knative-http/src/main/docs/knative-http-component.adoc, docs/components/modules/ROOT/nav.adoc, docs/components/modules/ROOT/pages/knative-http-component.adoc, docs/components/modules/others/nav.adoc, docs/components/modules/others/pages/knative-http.adoc
- Move knative-http docs from Miscellaneous to Components section
- Fix broken xref in knative-http docs
This makes `camel-knative-http` live right next to the `camel-knative` description in the Components sections of the docs. I have never done such a docs refactoring before so please let me know if this is the right way.
I was executing `docs/local-build.sh quick` locally with success. Is there anything else required?
=> chore(docs): Move Knative Http to components

core/camel-core/src/test/java/org/apache/camel/component/file/FileProducerCharsetUTFtoUTFTest.java
the test is flaky on Jenkins CI. It could help to investigate what is the issue
previous message on test error:
```
org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
at org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)
at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:183)
at org.apache.camel.component.file.FileProducerCharsetUTFtoUTFTest.testFileProducerCharsetUTFtoUTF(FileProducerCharsetUTFtoUTFTest.java:49)
```
example of …
=> chore: Improve test assertion in FileProducerCharsetUTFtoUTFTest

components/camel-grpc/pom.xml, components/camel-grpc/src/test/java/org/apache/camel/component/grpc/GrpcProducerStreamingTest.java
before while using @RepeatedTest locally, I had 4 kind of failures and it was around 40 out of 100 tests failing
Now, it remains 2 kinds of error which occurs 5 out of 100 times:
```
org.opentest4j.AssertionFailedError: List should be of size: 1 but is:
[] ==> expected: <1> but was: <0>
at org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
at org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
at org.junit.jupiter.api.AssertEquals.failNotEqual(AssertEquals.java:197)
at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:150)
at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:563)
at org.apache.camel.test.junit5.TestSupport.assertListSize(TestSupport.java:288)
at …
```
=> chore: reduce flakiness of GrpcProducerStreamingTest

core/camel-core-processor/src/main/java/org/apache/camel/processor/aggregate/UseOriginalAggregationStrategy.java
Null pointer exception fix in UseOriginalAggregationStrategy.
On the first aggregation the oldest exchange is null (there is only the new exchange)
Details can be found in the jira link below.
https://issues.apache.org/jira/browse/CAMEL-21376
=> CAMEL-21376 - null pointer exception fix in UseOriginalAggregationStrategy 

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_9.adoc
Fixes https://issues.apache.org/jira/browse/CAMEL-21395
The project camel-debezium-common shares the same package with the other camel-debezium sub-projects, which causes issues on environments like OSGI.
* Add a note to the upgrade guide
=> CAMEL-21395: camel-debezium - Add a note to the upgrade guide

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_8.adoc
Fixes https://issues.apache.org/jira/browse/CAMEL-21395 (v 4.8)
The project camel-debezium-common shares the same package with the other camel-debezium sub-projects, which causes issues on environments like OSGI.
* Add a note to the upgrade guide
=> CAMEL-21395: camel-debezium - Add a note to the upgrade guide for v 4.8

components/camel-fury/pom.xml, components/camel-fury/src/main/docs/fury-dataformat.adoc
there was this error:
```
org.apache.camel.CamelExecutionException: Exception occurred during execution on the exchange: Exchange[21534DE353D2A93-0000000000000000]
at org.apache.camel.CamelExecutionException.wrapCamelExecutionException(CamelExecutionException.java:45)
at org.apache.camel.support.ExchangeHelper.extractResultBody(ExchangeHelper.java:698)
at org.apache.camel.impl.engine.DefaultProducerTemplate.extractResultBody(DefaultProducerTemplate.java:591)
at org.apache.camel.impl.engine.DefaultProducerTemplate.extractResultBody(DefaultProducerTemplate.java:587)
at org.apache.camel.impl.engine.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:189)
at org.apache.camel.impl.engine.DefaultProducerTemplate.sendBody(DefaultProducerTemplate.java:195)
at …
```
=> fix: Apache Fury is not supporting architecture using Big Endian

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd, dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationRun.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesHelper.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/BaseTrait.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/RouteTrait.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/Trait.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitCatalog.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitContext.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java
Use quarkus extensions openshift to configure route with properties. This does not solve the openshift manifest merge issue [CAMEL-21365](https://issues.apache.org/jira/browse/CAMEL-21365) but at least allow the Route openshift Resource to be present on camel-jbang kubernetes run command.
=> CAMEL-21369: camel-jbang kubernetes - add quarkus extensions configuration for Route trait

components/camel-ai/camel-pinecone/src/main/java/org/apache/camel/component/pinecone/PineconeVectorDbEndpoint.java, components/camel-ai/camel-qdrant/src/main/java/org/apache/camel/component/qdrant/QdrantEndpoint.java, components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/NettyHttpComponent.java, components/camel-netty/src/main/java/org/apache/camel/component/netty/SharedSingletonObjectPool.java, components/camel-olingo2/camel-olingo2-component/src/main/java/org/apache/camel/component/olingo2/Olingo2AppWrapper.java, components/camel-olingo2/camel-olingo2-component/src/main/java/org/apache/camel/component/olingo2/Olingo2Component.java, components/camel-olingo2/camel-olingo2-component/src/main/java/org/apache/camel/component/olingo2/Olingo2Endpoint.java, components/camel-olingo2/camel-olingo2-component/src/main/java/org/apache/camel/component/olingo2/internal/Olingo2PropertiesHelper.java, components/camel-olingo4/camel-olingo4-component/src/main/java/org/apache/camel/component/olingo4/Olingo4AppWrapper.java, components/camel-olingo4/camel-olingo4-component/src/main/java/org/apache/camel/component/olingo4/Olingo4Component.java, components/camel-olingo4/camel-olingo4-component/src/main/java/org/apache/camel/component/olingo4/Olingo4Endpoint.java, components/camel-olingo4/camel-olingo4-component/src/main/java/org/apache/camel/component/olingo4/internal/Olingo4PropertiesHelper.java, components/camel-opensearch/src/main/java/org/apache/camel/component/opensearch/OpensearchProducer.java, components/camel-optaplanner/src/main/java/org/apache/camel/component/optaplanner/OptaPlannerEndpoint.java, components/camel-platform-http/src/main/java/org/apache/camel/component/platform/http/PlatformHttpComponent.java, components/camel-printer/src/main/java/org/apache/camel/component/printer/PrintDocument.java, components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarProducer.java, components/camel-quickfix/src/main/java/org/apache/camel/component/quickfixj/QuickfixjComponent.java, components/camel-quickfix/src/main/java/org/apache/camel/component/quickfixj/QuickfixjEndpoint.java
* Replace mutex with locks
* Use locks instead of synchronized blocks
* Use ConcurrentHashMap instead of HashMap when possible
=> CAMEL-20199: Remove synchronized block from components N to Q

components/camel-jetty-common/src/main/java/org/apache/camel/component/jetty/JettyHttpComponent.java
The PR https://github.com/apache/camel/pull/16134 causes some regressions in the pipeline https://ci-builds.apache.org/job/Camel/job/Camel%20Core%20(Build%20and%20test)/job/main/512/ 
* Propagate properly the exceptions for backward compatibility reasons
=> CAMEL-20199: camel-jetty - Propagate exception

docs/user-manual/modules/ROOT/pages/variables.adoc
=> Fix typo on variables.adoc

components/camel-plc4x/src/main/java/org/apache/camel/component/plc4x/Plc4XEndpoint.java, components/camel-plc4x/src/main/java/org/apache/camel/component/plc4x/Plc4XProducer.java
When Camel can not establish the connection to the S7 PLC, the component is throwing follow-up exceptions which are causing the application start up to fail and which hide the real connection issue.
- Added isConnected() to endpoint which checks if connection is null. This method is public to allow external logic to check if endpoint is really connected.
- Moved canWrite() call to be checked only when connected.
- Added additional canWrite() check after reconnectIfNeeded().
Steps to reproduce:
- Add Camel route with S7 driver
- PLC is not available
- Connection failure
- Additional NullPointerExceptions are thrown
=> fix(components/plc4x): fix NPE when Camel can not establish connection

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/main-kubernetes-pom.tmpl, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/spring-boot-kubernetes-pom.tmpl, dsl/camel-jbang/camel-jbang-plugin-kubernetes/pom.xml, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/ClusterType.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/DeploymentTrait.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitContext.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/Container.java
https://issues.apache.org/jira/browse/CAMEL-21392
=> [CAMEL-21392] Add support for --cluster-type=k3s

dsl/camel-jbang/camel-jbang-plugin-kubernetes/pom.xml, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesBaseTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesCommandTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesDeleteTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportBaseTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportKnativeTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRunTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/PodLogsTest.java
- Prevent resource-intensive tests from running on CI envs
- Ensure they are only executed if required resources are in place
=> (chores) camel-jbang: disable resource intensive tests

components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/util/MicUtilsTest.java, components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2AsyncMDNServerManagerIT.java
For a message containing non ASCII chars the length of the message byte array may be longer than the EDI message string length since non ASCII chars can be more that one byte. 
Also fixes one of the Integration tests that appeared a bit flaky.
=> CAMEL-21403: retrieve full message for content containing non ASCII chars

components/camel-etcd3/src/test/java/org/apache/camel/component/etcd3/AggregateEtcd3ManualTest.java, components/camel-plc4x/src/test/java/org/apache/camel/component/plc4x/ManualTest.java
This blocks the test on multiple architectures
=> (chores) camel-etcd3: prevent manual test from running

core/camel-core-model/src/main/java/org/apache/camel/model/language/NamespaceAwareExpression.java, core/camel-xml-io/pom.xml, core/camel-xml-io/src/main/java/org/apache/camel/xml/in/BaseParser.java, core/camel-xml-io/src/main/java/org/apache/camel/xml/out/BaseWriter.java, core/camel-xml-io/src/test/java/org/apache/camel/xml/out/ModelWriterTest.java, core/camel-xml-io/src/test/resources/beansWithFactoryMethod.xml, core/camel-xml-io/src/test/resources/resequencerStream.xml, core/camel-xml-io/src/test/resources/routeXPathAndXmlNamespaces.xml, core/camel-xml-io/src/test/resources/routingSlip.xml, core/camel-xml-io/src/test/resources/routingSlipHeaderSet.xml, core/camel-yaml-io/pom.xml, core/camel-yaml-io/src/generated/java/org/apache/camel/yaml/out/ModelWriter.java, core/camel-yaml-io/src/main/java/org/apache/camel/yaml/io/YamlWriter.java, core/camel-yaml-io/src/test/java/org/apache/camel/yaml/out/XPathNamespacesTest.java, tooling/maven/camel-package-maven-plugin/src/main/resources/velocity/model-writer.vm
=> CAMEL-21420: XML and YAML DSL should better support languages with namespaces such as xpath when parsing and writing outputs

components/camel-rest-openapi/src/main/java/org/apache/camel/component/rest/openapi/RestOpenApiProcessor.java, test-infra/camel-test-infra-minio/src/test/resources/org/apache/camel/test/infra/minio/services/container.properties
Fix/Update org.apache.camel.component.rest.openapi.RestOpenApiProcessor.java
When RestOpenApiProcessor tries to process the path variables in the request,  HttpHelper.evalPlaceholders  throws an ArrayIndexOutOfBoundsException because consumerPath  from the openApi spec starts with a "/" but the uri of the request does not start with a "/".
=> Fix for RestOpenApiProcessor for parsing path variables from the http request uri succesfully. 

components/camel-etcd3/pom.xml
Recent etcd3 seems very unstable on s390x and have been causing crashes and failures
=> (chores) camel-etcd3: skip tests in s390x and ppc64le

components/camel-rest-openapi/src/main/java/org/apache/camel/component/rest/openapi/OpenApiUtils.java, components/camel-rest-openapi/src/test/java/org/apache/camel/component/rest/openapi/OpenApiUtilsTest.java
Changed the behavior to include media types from all existing responses when generating produces string. Information about previous behavior can be seen in [issue 6776](https://github.com/apache/camel-quarkus/issues/6766).
Of some reason, I wasn't able to download artifacts from https://repository.apache.org/snapshots so I have not been able to run `mvn clean install -DskipTests`.
=> CAMEL-6766 Generated produces string now includes media types from all responses

core/camel-core-processor/src/main/java/org/apache/camel/processor/MulticastProcessor.java, core/camel-core/src/test/java/org/apache/camel/support/cache/SimpleLRUCacheTest.java, core/camel-support/src/main/java/org/apache/camel/support/cache/SimpleLRUCache.java
Fix for https://issues.apache.org/jira/browse/CAMEL-21432
The splitter and multicast EIPs set the cache size to 0 by default which causes endless evictions
1. Prevent to set 0 as cache size at the cache level
2. Use the value of `CamelContextHelper.getMaximumCachePoolSize` as the default cache size for the splitter and multicast EIPs
=> CAMEL-21432: camel-core - Prevent 0 as cache size for multicast EIP

core/camel-core-processor/src/main/java/org/apache/camel/processor/MulticastProcessor.java, core/camel-core/src/test/java/org/apache/camel/support/cache/SimpleLRUCacheTest.java, core/camel-support/src/main/java/org/apache/camel/support/cache/SimpleLRUCache.java
Fix for https://issues.apache.org/jira/browse/CAMEL-21432 (v 4.4)
The splitter and multicast EIPs set the cache size to 0 by default which causes endless evictions
1. Prevent to set 0 as cache size at the cache level
2. Use the value of `CamelContextHelper.getMaximumCachePoolSize` as the default cache size for the splitter and multicast EIPs
=> CAMEL-21432: camel-core - Prevent 0 as cache size for multicast EIP (4.4)

core/camel-core-processor/src/main/java/org/apache/camel/processor/MulticastProcessor.java, core/camel-core/src/test/java/org/apache/camel/support/cache/SimpleLRUCacheTest.java, core/camel-support/src/main/java/org/apache/camel/support/cache/SimpleLRUCache.java
Fix for https://issues.apache.org/jira/browse/CAMEL-21432 (v 4.8)
The splitter and multicast EIPs set the cache size to 0 by default which causes endless evictions
1. Prevent to set 0 as cache size at the cache level
2. Use the value of `CamelContextHelper.getMaximumCachePoolSize` as the default cache size for the splitter and multicast EIPs
=> CAMEL-21432: camel-core - Prevent 0 as cache size for multicast EIP (4.8)

components/camel-dhis2/camel-dhis2-api/src/test/java/org/apache/camel/component/dhis2/api/Dhis2GetTestCase.java, components/camel-dhis2/camel-dhis2-component/src/test/java/org/apache/camel/component/dhis2/Dhis2GetIT.java, components/camel-dhis2/pom.xml
Solve pagination exception in DHIS2 component caused by Jackson update. See https://github.com/dhis2/dhis2-java-sdk/issues/209
=> fix: solve pagination exception in DHIS2 component caused by Jackson update

bom/camel-bom/pom.xml, catalog/camel-allcomponents/pom.xml, components/camel-observability-services/pom.xml, components/camel-observability-services/src/main/docs/observability-services.adoc, components/camel-observability-services/src/main/resources/observability-services.properties, components/pom.xml, core/camel-main/src/main/java/org/apache/camel/main/BaseMainSupport.java, core/camel-main/src/main/java/org/apache/camel/main/MainConstants.java, docs/components/modules/others/nav.adoc, docs/components/modules/others/pages/observability-services.adoc, parent/pom.xml
With this PR we're adding a new component which serves as an adapter and helper to expose a set of opinionated observability services. This first MVP adds `camel-micrometer-prometheus` components and a default configuration for it. Once this is onboarded I'll proceed with creating the proper extension/starter for the other runtimes.
Iteratively we'll be adding into this adapter a few more components in order to expose other sensitive observability metrics (telemetry, health, ...). The main goal is to provide services required when running a microservice oriented architecture on cloud, but the component can be used outside cloud as well with the same meaning.
Closes CAMEL-21384
=> feat(components): add camel-observability-services

components/camel-observability-services/src/main/docs/observability-services.adoc, components/camel-observability-services/src/main/resources/observability-services.properties
=> chore(components): observability services change default

parent/pom.xml
https://github.com/apache/camel-spring-boot/pull/1293 updated camel-spring-boot-4.8.x to spring-boot 3.3.6.     This PR is a number of micro release upgrades to match the versions within spring-boot-dependencies 3.3.6.
Ran the tests locally for all of the components where a dependency was upgraded (netty, infinispan, jackson, groovy, micrometer)
=> Align versions with spring-boot 3.3.6

components/camel-platform-http-jolokia/src/test/java/org/apache/camel/component/platform/http/plugin/DefaultJolokiaPlatformHttpPluginTest.java, parent/pom.xml
Upgrade jolokia to 2.1.2 and cherry-pick over Otavio's commit that removes the assert checking agent version - the hard coded check on agent 2.1.0 will fail once we upgrade jolokia to 2.1.2.
Ran mvn -DskipTests clean install and test in camel-platform-http-jolokia
=> Upgrade jolokia to 2.1.2

components/camel-quartz/src/main/java/org/apache/camel/component/quartz/QuartzEndpoint.java, components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzCronRouteWithEmptyStartDateExpiredEndDateTest.java
Fix for [CAMEL-21471](https://issues.apache.org/jira/browse/CAMEL-21471)
camel-quartz ignores ignoreExpiredNextFireTime when endAt is expired
=> CAMEL-21471: camel-quartz ignores ignoreExpiredNextFireTime when endAt is expired

core/camel-core/src/test/java/org/apache/camel/support/cache/SimpleLRUCacheTest.java, core/camel-support/src/main/java/org/apache/camel/support/cache/SimpleLRUCache.java
Fix for https://issues.apache.org/jira/browse/CAMEL-21467
In some specific use cases, the eviction of the entries never ends
* Use `AtomicReference` instead of `volatile` to keep the changes
* No longer compute cache changes size
=> CAMEL-21467: camel-core - No longer compute cache changes size

docs/user-manual/modules/ROOT/pages/security.adoc
fixes https://issues.apache.org/jira/browse/CAMEL-21492
=> fixes CAMEL-21492 - lists a component usable for payload security

docs/user-manual/modules/ROOT/pages/security.adoc
fixes https://issues.apache.org/jira/browse/CAMEL-21492
Addition  of `XMLSecurityDataformat` as suitable payload security  provider. (I missed it in the previous PR - https://github.com/apache/camel/pull/16408) 
…
=> fixes CAMEL-21492 - added XMLSecurityDsataformat as a possible provider of payload security into the doc

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelCommand.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
=> camel-jbang - Run background should wait

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/client/DefaultRawClient.java, components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/internal/client/DefaultRawClientTest.java
When performing raw requests using the `raw` endpoint in the salesforce component, if there's an error without body the `DefaultRawClient` is unable to create a `SalesforceException` because it throws a `NullPointerException`, I see other internal clients implementations, and there the null response body is handled correctly.
[This following branch can be used to see the current wrong behavior.](https://github.com/baconberry/camel/blob/reproduce-salesforce-raw-client-npe/components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/RawPayloadTest.java)
Is this trivial enough?
=> Fixed NPE when no response body in DefaultRawClient

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/RuntimeUtil.java
[CAMEL-21532](issues.apache.org/jira/browse/CAMEL-21532): Camel JBang --logging-category is not respected on Windows
This pull request fixes "java.lang.IllegalArgumentException: URI has an authority component" thrown by Camel JBang because of the incorrect Log4j2 config.
=> CAMEL-21532: fix the Log4j2 config file not being respected in Camel JBang

components/camel-smooks/pom.xml, components/camel-smooks/src/main/docs/smooks-component.adoc, components/camel-smooks/src/main/java/org/apache/camel/component/smooks/routing/BeanRouter.java, components/camel-smooks/src/main/java/org/apache/camel/component/smooks/routing/BeanRouterObserver.java, components/camel-smooks/src/main/resources/META-INF/xsd/smooks/camel-1.5.xsd, components/camel-smooks/src/main/resources/META-INF/xsd/smooks/camel-1.5.xsd-smooks.xml, components/camel-smooks/src/test/java/org/apache/camel/component/smooks/routing/BeanRouterFunctionalTest.java, components/camel-smooks/src/test/java/org/apache/camel/component/smooks/routing/BeanRouterObserverTest.java, components/camel-smooks/src/test/java/org/apache/camel/component/smooks/routing/BeanRouterTest.java, components/camel-smooks/src/test/java/org/apache/camel/component/smooks/routing/gender/Gender.java, components/camel-smooks/src/test/java/org/apache/camel/component/smooks/routing/gender/GenderTypeConverterFactory.java, components/camel-smooks/src/test/java/org/apache/camel/dataformat/smooks/SmooksDataFormatTest.java, components/camel-smooks/src/test/resources/META-INF/services/org.smooks.api.converter.TypeConverterFactory, components/camel-smooks/src/test/resources/bean-routing-smooks-config.xml, components/camel-smooks/src/test/resources/xml/customer.xml, components/camel-smooks/src/test/resources/xml/expected-customer.xml
Migrate bean routing functionality from Smooks Cartridge to Smooks Component.
=> CAMEL-21547: Migrate bean routing functionality from Smooks Cartridge to Smooks Component

core/camel-core/src/test/java/org/apache/camel/component/file/FileConcurrentWriteAppendSameFileTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FileConsumerIdempotentKeyChangedIssueTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FileConsumerIdempotentOnExceptionHandledTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FileConsumerNoopTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FileMarkerFileRecursiveDoNotDeleteOldLockFilesTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FilePollEnrichNoWaitTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FilePollEnrichTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FileProduceAppendCharsEmptyMessageTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FileProduceAppendCharsSingleMessageTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FileProduceAppendCharsTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FileProduceOverruleOnlyOnceTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FileProduceTempPrefixTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FileProducerFileExistAppendNoFileBeforeTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FileProducerFileExistOverrideNoFileBeforeTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FileProducerRenameUsingCopyTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FilerConsumerDoneFileNameDeleteTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FilerConsumerDoneFileNoopTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FilerConsumerDualDoneFileNameTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FilerProducerDoneFileNameRouteTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FromFilePollThirdTimeOkTest.java
- [x ] If this is a large change, bug fix, or code improvement, I checked there is a [CAMEL-20686](https://issues.apache.org/jira/browse/CAMEL-20686) filed for the change (usually before you start working on it).
=> (WIP) CAMEL-20682 - review File tests for incorrectly shared resources - set 6

components/camel-smooks/src/main/java/org/apache/camel/component/smooks/SmooksProcessor.java, components/camel-smooks/src/test/java/org/apache/camel/component/smooks/SmooksProcessorTest.java
By default do not lazily start Smooks and use the `lazyStartProducer` option to lazily start Smooks.
=> CAMEL-21555: By default do not lazily start Smooks

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc
Fixing typos in Camel JBang documentation as the camel export `--deps` was replaced by `--dep`. Not every occurrence of `--deps` was replaced. 
- [] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)
=> chore(docs): Fix Camel JBang --dep option typos

components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/MongoDbProducer.java, components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbOperationsIT.java
The current implementation of the mongodb save operation forces mongodb to scan the whole collection when a document is saved without _id. This change makes an insert if no _id is given, instead of making an upsert with a filter condition that can never be satisfied. The behaviour for the save operation _with_ _id remains untouched.
See also https://camel.zulipchat.com/#narrow/channel/257298-camel/topic/mongodb.20save.20operation.20performance
=> CAMEL-21559, mongodb: insertOne instead of replaceOne when saving without _id

tooling/maven/sync-properties-maven-plugin/src/main/java/org/apache/camel/maven/sync/properties/SyncPropertiesMojo.java
Backport of https://github.com/apache/camel/pull/16610
=> [4.8.x] Allow propagating -version properties from the top pom to camel-dependencies

components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Endpoint.java
The AWS2S3Endpoint tries to do a HeadBucket request, which may not be permitted. This is only a problem if the endpoint is also configured to create the bucket if it does not exist.
Otherwise it may simply be that other actions on the bucket will succeed, and there is not reason to fail if just the HeadBucket request is not permitted.
I though this would be CAMEL-18022, but  I think it is different. 
Now:
https://issues.apache.org/jira/browse/CAMEL-21562
=> CAMEL-21562. It's not a problem if the client is not allowed to do HeadBucket

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/ListProcess.java
Backport 4.8.x of [CAMEL-21563](https://issues.apache.org/jira/browse/CAMEL-21563)
=> CAMEL-21563 : camel-jbang ps option output in JSON

parent/pom.xml
This reverts commit 0624c499d0d657c9c034d21281164622fc27a679.
This breaks `camel-mina` and needs to be fixed: https://mina.apache.org/mina-project/
=> Revert "chore(deps): Bump org.apache.mina:mina-core from 2.2.3 to 2.2.4 (#16647)"

core/camel-support/src/main/java/org/apache/camel/support/builder/ExpressionBuilder.java
[CAMEL-21572](https://issues.apache.org/jira/browse/CAMEL-21572): fix java.lang.NullPointerException when using SetHeader and Stub
SetHeader with a simple expression causes NullPointerException to be thrown because for runtime other than default (kamelet-main) JBang uses Stub instead of the actual component which produces null.
```
- setHeader: 
id: setHeader-c0db
name: SampleUUID
expression: 
simple: 
id: simple-536b
expression: >-
This is a sample UUID: 
${bean:type:java.util.UUID?method=randomUUID}
```
=> CAMEL-21572: fix java.lang.NullPointerException when using SetHeader and Stub

components/camel-aws/camel-aws2-s3/src/test/java/org/apache/camel/component/aws2/s3/integration/S3CopyObjectCustomerKeyIT.java
This got broken due to 711dbba142306b960f85b576a1370d6774461d7e or cf3ed2e21884b31ff757d797ac3425edb533ed27
=> Disable S3 test that broke after AWS SDK upgrade

components/camel-robotframework/pom.xml, parent/pom.xml
* it is already aligned in another module (camel-python https://github.com/apache/camel/blob/3050d41878242dbb53ba0400b4bc69578fef213e/components/camel-python/pom.xml#L46 )
* there was always a corresponding version provided so far
* currently dependabot has an error when trying to upgrade jython-standalone `updater | 2025/01/01 06:48:55 ERROR <job_941207218> Error processing org.python:jython-standalone (RuntimeError)`
=> chore: align jython-standalone version with jython version

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/OpenApiTrait.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitHelper.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/AddonsBuilder.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/CamelBuilder.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/ContainerBuilder.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/EnvironmentBuilder.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/IngressBuilder.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/KnativeBuilder.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/KnativeServiceBuilder.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/MountBuilder.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/OpenapiBuilder.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/RouteBuilder.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/ServiceBindingBuilder.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/ServiceBuilder.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/TraitsBuilder.java
Part of CAMEL-21278: Add builder classes to facilitate handling Traits object.
=> CAMEL-21278 : Camel Jbang Kubernetes plugin -  add builders to model

components/camel-kubernetes/pom.xml, components/camel-kubernetes/src/generated/java/io/fabric8/kubernetes/client/ConfigFluentImplConfigurer.java, components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/deployments/KubernetesDeploymentsProducer.java, components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/replication_controllers/KubernetesReplicationControllersProducer.java, components/camel-kubernetes/src/main/java/org/apache/camel/component/openshift/deploymentconfigs/OpenshiftDeploymentConfigsProducer.java, components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/cluster/utils/LockTestServer.java, components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/consumer/integration/KubernetesEventsConsumerIT.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/pom.xml, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/knative/KnativeTrait.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesBaseTest.java, parent/pom.xml
* Unit / integration tests on k8s and OpenShift pass
* Removed duplicate version properties
* Removed bouncycastle from `camel-jbang-plugin-kubernetes`. Apparently, it is [no longer required](https://github.com/fabric8io/kubernetes-client/blob/main/doc/MIGRATION-v7.md#bouncy-castle-is-no-longer-needed-).
=> CAMEL-21509: Upgrade kubernetes-client to 7.0.1

catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/ValidateMojo.java
Camel route validation mojo fails if it depends on external sources without cleaning the target folder
=> CAMEL-21606 - Camel route validation mojo fails if it depends on external sources without cleaning the target folder

dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/main-kubernetes-pom.tmpl, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-kubernetes-pom.tmpl, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/spring-boot-kubernetes-pom.tmpl
generated by Camel JBang
it avoids this kind of warnings in build log of the generated project:
```
[WARNING] Some problems were encountered while building the effective
model for org.example.project:test-from-vscode:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for
org.apache.maven.plugins:maven-resources-plugin is missing. @ line 153,
column 21
[WARNING]
[WARNING] It is highly recommended to fix these problems because they
threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support
building such malformed projects.
[WARNING]
```
=> CAMEL-21578 - Provide version for the Maven resources plugin for project

core/camel-support/src/main/java/org/apache/camel/support/cache/SimpleLRUCache.java
Fix for https://issues.apache.org/jira/browse/CAMEL-21614 (4.8)
In some specific use cases, the eviction of the entries never ends
* Improve the way to swap the queue of change to avoid the race condition that could cause cache changes miss by leveraging a `ReadWriteLock` to only prevent change additions during the swap
=> CAMEL-21614: camel-core - Prevent cache change miss on queue swap - 4.8

.github/dependabot.yml
There are 2 different versions produced for each of these groups of dependencies but that are always released at the same time and which corresponds to each other. I think it would make sense to update them in the same Pull Request.
see previous updates:
* https://github.com/apache/camel/pull/16799
* https://github.com/apache/camel/pull/16797
* https://github.com/apache/camel/pull/16792
* https://github.com/apache/camel/pull/16791
=> chore: Group dependabot update for micrometer and opentelemetry

components/camel-jpa/src/test/java/org/apache/camel/component/jpa/JpaWithNamedQueryTest.java, components/camel-jpa/src/test/java/org/apache/camel/component/jpa/JpaWithNativeQueryTest.java, components/camel-jpa/src/test/java/org/apache/camel/component/jpa/JpaWithQueryTest.java, components/camel-jpa/src/test/java/org/apache/camel/processor/jpa/JpaProducerWithQueryTest.java
Sometimes these tests hang indefinitely
=> (chores) camel-jpa: enforce a timeout for some thread-unsafe tests

components/camel-rest-openapi/src/main/java/org/apache/camel/component/rest/openapi/OpenApiUtils.java, components/camel-rest-openapi/src/test/java/org/apache/camel/component/rest/openapi/OpenApiUtilsTest.java
This commit introduces support for resolving response body types from OpenAPI 3.1 specifications in addition to the existing support for OpenAPI 3.0.
If an openApi are parsed with the OpenAPIV3Parser types are handled differently 
* OpenAPI 3.1 schema type are stored into a list (Schema.types)
* OpenApi 3.0 schema types are stored in a single type value (Schama.type)
=> Fixing bug in camel-rest-openapi OpenApiUtils to support parsed OpenAPI 3.1 files.

catalog/camel-catalog/pom.xml, catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/test-infra/metadata.json, dsl/camel-jbang/camel-jbang-core/pom.xml, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/infra/InfraBaseCommand.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/infra/InfraRun.java, test-infra/camel-test-infra-all/src/generated/resources/META-INF/metadata.json, test-infra/camel-test-infra-ignite/src/main/java/org/apache/camel/test/infra/ignite/services/IgniteEmbeddedInfraService.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/CamelTestInfraGenerateMetadataMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/UpdateTestInfraMetadataMojo.java
- Updated the test infra metadata.json generation with maven coordinates information
- Removed camel-test-infra-all from camel-jbang-core, instead, Download the required dependency programmatically
- Update the Camel Catalog with the test-infra metadata.json
- Use the Camel Catalog to retrieve test-infra metadata
=> Use Camel Catalog and remove camel-test-infra-all from camel-jbang

components/camel-google/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubConsumer.java, components/camel-grpc/src/main/java/org/apache/camel/component/grpc/client/GrpcStreamingExchangeForwarder.java, components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/AsyncInputStream.java, components/camel-sjms/src/main/java/org/apache/camel/component/sjms/reply/TemporaryQueueReplyManager.java, components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppSplitter.java, components/camel-thymeleaf/src/main/java/org/apache/camel/component/thymeleaf/ThymeleafEndpoint.java, components/camel-timer/src/main/java/org/apache/camel/component/timer/TimerComponent.java, components/camel-twilio/src/main/java/org/apache/camel/component/twilio/internal/TwilioPropertiesHelper.java, components/camel-undertow/src/main/java/org/apache/camel/component/undertow/DefaultUndertowHost.java, components/camel-undertow/src/main/java/org/apache/camel/component/undertow/handlers/CamelMethodHandler.java, components/camel-undertow/src/main/java/org/apache/camel/component/undertow/handlers/CamelPathHandler.java, components/camel-undertow/src/main/java/org/apache/camel/component/undertow/handlers/CamelPathTemplateHandler.java, components/camel-undertow/src/main/java/org/apache/camel/component/undertow/handlers/CamelRootHandler.java, components/camel-undertow/src/main/java/org/apache/camel/component/undertow/handlers/CamelWebSocketHandler.java, components/camel-univocity-parsers/src/main/java/org/apache/camel/dataformat/univocity/Marshaller.java, components/camel-velocity/src/main/java/org/apache/camel/component/velocity/VelocityEndpoint.java, components/camel-vertx/camel-vertx-websocket/src/main/java/org/apache/camel/component/vertx/websocket/VertxWebsocketResultHandler.java, components/camel-wal/src/main/java/org/apache/camel/component/wal/LogWriter.java, components/camel-wasm/src/main/java/org/apache/camel/wasm/WasmFunction.java, components/camel-xchange/src/main/java/org/apache/camel/component/xchange/XChangeComponent.java, components/camel-xmpp/src/main/java/org/apache/camel/component/xmpp/XmppEndpoint.java, components/camel-xmpp/src/main/java/org/apache/camel/component/xmpp/XmppGroupChatProducer.java, components/camel-xmpp/src/main/java/org/apache/camel/component/xmpp/XmppPrivateChatProducer.java, components/camel-xpath/src/main/java/org/apache/camel/language/xpath/XPathBuilder.java, components/camel-xslt/src/main/java/org/apache/camel/component/xslt/XsltBuilder.java, components/camel-zendesk/src/main/java/org/apache/camel/component/zendesk/internal/ZendeskPropertiesHelper.java
* Replace mutex with locks
* Use locks instead of synchronized blocks
* Leverage ConcurrentMap methods to get rid of synchronized blocks
=> CAMEL-20199: Remove synchronized blocks from components T to Z

dsl/camel-jbang/camel-jbang-container/Dockerfile, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogDoc.java, dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java, dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java
=> Upgrade to Camel kamelets 4.8.3

components/camel-elasticsearch/pom.xml, components/camel-elasticsearch/src/test/java/org/apache/camel/component/es/integration/ElasticsearchTestSupport.java
=> [CAMEL-21638]: Enable ppc64le support for camel-elasticsearch

parent/pom.xml
Align the versions of activemq6 and spring-batch to the versions used in spring-boot-dependencies 3.3.8
This change coincides with the spring-boot 3.3.8 upgrade PR in camel-spring-boot https://github.com/apache/camel-spring-boot/pull/1351
No JIRA, small change
=> Align versions with spring-boot-dependencies 3.3.8

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Export.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportQuarkus.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java, dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/ExportMainApplicationProperties.java, dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/ExportTest.java, dsl/camel-jbang/camel-jbang-core/src/test/resources/sample-application.properties
You can now use `camel export --property xyz=abc`
Closes CAMEL-21645
=> feat(dsl): camel jbang export property

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/ExportITCase.java, dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/JBangTestSupport.java
Adds tests covering [camel export](https://camel.apache.org/manual/camel-jbang.html#_creating_projects)
Tests covering exporting with Java Agent, JMX and Camel-cli will be added in another PR.
=> CAMEL-20367: Adds export related tests

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java
The picocli parameter "property" is duplicated in ExportBaseCommand and KubernetesExport causing CommandLine$DuplicateOptionAnnotationsException: Option name '--property' is used by both field
The `catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd` is from the catalog, probably from some previous unrelated change.
=> Fix duplicate property in KubernetesExport of camel-jbang-plugin-kubernetes

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
Make sure the log directory exists during the logging configuration
=> CAMEL-21668 : Force the creation of the parent log dir

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/ExportITCase.java
Adds tests for [exporting with JMX manager](https://camel.apache.org/manual/camel-jbang.html#_exporting_with_jmx_management_included), [exporting with cli-connector](https://camel.apache.org/manual/camel-jbang.html#_exporting_with_camel_cli_included) and [exporting with Java agent](https://camel.apache.org/manual/camel-jbang.html#_exporting_with_java_agent_included)
=> CAMEL-20367: Adds exporting with dependencies tests

test-infra/camel-test-infra-cli/README.adoc, test-infra/camel-test-infra-cli/pom.xml, test-infra/camel-test-infra-cli/src/test/java/org/apache/camel/test/infra/cli/common/CliProperties.java, test-infra/camel-test-infra-cli/src/test/java/org/apache/camel/test/infra/cli/it/CliConfigITCase.java, test-infra/camel-test-infra-cli/src/test/java/org/apache/camel/test/infra/cli/services/CliBuiltContainer.java, test-infra/camel-test-infra-cli/src/test/java/org/apache/camel/test/infra/cli/services/CliLocalContainerService.java
Adds the parameter to mount the local maven repository, it may be useful to improve the tests execution time, avoiding to download the maven artifacts on each container
=> camel-test-infra-cli: Adds the parameter to mount local maven repository

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/knative/KnativeServiceTrait.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/knative/KnativeTrait.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportKnativeTest.java
If the knative trait is enabled by default, the MetadataHelper loads the route, resulting in the following error
```
IllegalStateException: Cannot find RestConsumerFactory in Registry or as a Component to use 
```
when there is an http consumer.
=> camel-jbang-plugin-kubernetes disable the knative by default

test-infra/camel-test-infra-cli/src/test/java/org/apache/camel/test/infra/cli/it/AbstractTestSupport.java, test-infra/camel-test-infra-cli/src/test/java/org/apache/camel/test/infra/cli/it/CliConfigITCase.java, test-infra/camel-test-infra-cli/src/test/java/org/apache/camel/test/infra/cli/it/RunITCase.java, test-infra/camel-test-infra-cli/src/test/java/org/apache/camel/test/infra/cli/services/CliLocalContainerService.java
Since the output from the execution in background can be different based on `background-wait` parameter, it is necessary to update the way the PID is retrieved
=> camel-test-infra-cli: Reads PID in case of background-wait=true

dsl/camel-jbang/camel-jbang-it/pom.xml, dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/OpenApiITCase.java, dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/RunCommandITCase.java, dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/TransformMessageITCase.java, dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/JBangTestSupport.java, dsl/camel-jbang/camel-jbang-it/src/test/resources/logback-test.xml, test-infra/camel-test-infra-cli/pom.xml, test-infra/camel-test-infra-cli/src/test/java/org/apache/camel/test/infra/cli/services/CliService.java
Update jbang IT module in order to:
- run tests with the current version of Camel JBang (in main it will be the current snapshot)
- improve/fix parallel exuctions
- use common maven local repository to avoid to download all the dependencies on each running container
- fix tests, make them compatible with the latest jbang commands
=> camel-jbang-it: Fixes/Updates jbang tests

components/camel-jetty/src/test/java/org/apache/camel/component/jetty/HttpsRouteTest.java
=> (chores) camel-jetty: isolate HTTPS tests to reduce flakiness

dsl/camel-jbang/camel-jbang-it/pom.xml
by default it now uses target folder, instead of local maven repository folder, since the user running process in the container can be different compared to the user running maven process in the host
=> camel-jbang-it: Change default maven local repo folder

components/camel-salesforce/camel-salesforce-component/src/main/docs/salesforce-component.adoc
Updating documentation by adding OAuth 2.0 Client Credentials Flow as a supported OAuth authentication flow.
=> [docs] Client Credentials Flow added to the list of supported OAuth authentication flow

components/camel-aws/camel-aws-secrets-manager/src/main/java/org/apache/camel/component/aws/secretsmanager/vault/CloudTrailReloadTriggerTask.java
follows https://github.com/apache/camel/pull/17052
The override endpoint url is missing also for `CloudTrailClient`.
The localstack cloudtrail lookup is not implemented yet, therefore endpoint url override cannot be  used now in this case. But I think that it is better to have the code prepared for the future.
=> extends fix of  CAMEL-21713: endpoint url override to aws-secret-manager

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/main-kubernetes-pom.tmpl, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-kubernetes-pom.tmpl, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/spring-boot-kubernetes-pom.tmpl, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java
- Set basic settings on JIB image builder
- Introduce configurable base image (default is still eclipse-temurin:17)
- Set image platforms on JKube properties
- Set proper image push registry on JKube properties
Fixes CAMEL-21716
=> CAMEL-21716: Improve JBang Kubernetes plugin container image options

components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/cluster/lock/KubernetesLeadershipController.java, components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/cluster/KubernetesClusterServiceTest.java, components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/cluster/utils/LockTestServer.java
I am not super familiar with the k8s clustering stuff with camel-master. So would be good to have a second pair of eyes (or more) on this.
=> CAMEL-21720: Filter candidate Kubernetes cluster members by whether they are in running and ready states

components/camel-azure/camel-azure-key-vault/src/main/java/org/apache/camel/component/azure/key/vault/KeyVaultComponent.java, components/camel-azure/camel-azure-key-vault/src/test/java/org/apache/camel/component/azure/key/vault/KeyVaultConfigurationTest.java
fixes https://issues.apache.org/jira/browse/CAMEL-21721
=> fixes CAMEL-21721: azure-key-vault: fixing identity validation

dsl/camel-jbang/camel-jbang-it/pom.xml, dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/DevModeITCase.java, dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/JBangTestSupport.java, test-infra/camel-test-infra-cli/pom.xml, test-infra/camel-test-infra-cli/src/test/java/org/apache/camel/test/infra/cli/services/CliBuiltContainer.java, test-infra/camel-test-infra-cli/src/test/resources/org/apache/camel/test/infra/cli/services/Dockerfile
- build the camel-test-infra-cli container with the same uid and gid owner of the current maven process to avoid permissions issues
- revert the usage of the maven repo with the one defined in the maven settings, to allow to use the current snapshot version if it is compiled in the host
- allow the rerun configuration in the camel-test-infra-cli module
- minor fixes in camel-jbang-it module
=> camel-jbang-it: Use current uid/gid to run processes in the container

dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/KnownDependenciesResolver.java, dsl/camel-kamelet-main/src/test/java/org/apache/camel/main/download/KnownDependenciesResolverTest.java, dsl/camel-kamelet-main/src/test/resources/camel-main-known-dependencies.properties
This pull request enhances KnownDependenciesResolver to match the well known dependencies against packages up to the root package, so that a single entry in the camel-main-known-dependencies.properties file is sufficient to load any class from this jar, instead of having a separate entry for each class.
This is a cherry-pick from #17034
=> KnownDependenciesResolver to support packages

components/camel-openapi-java/src/main/java/org/apache/camel/openapi/BeanConfig.java, components/camel-openapi-java/src/main/java/org/apache/camel/openapi/RestOpenApiSupport.java, components/camel-openapi-java/src/test/java/org/apache/camel/openapi/RestOpenApiLicenseInfoTest.java, docs/user-manual/modules/ROOT/pages/rest-dsl.adoc
Make it possible to reference external Open API docs via `.apiProperty(..)`
```
restConfiguration()
.apiProperty("externalDocs.url", "https://openweathermap.org/api")
.apiProperty("externalDocs.description", "API Documentation"); 
```
=> CAMEL-21731: Adding reference to external Open API docs

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/client/PubSubApiClient.java
https://issues.apache.org/jira/browse/CAMEL-21740
https://lists.apache.org/thread/vdnzjcsmc0plxz558mqkvp6r19zxc1hl
My fix from the user mailing list.
This is my first pull request, so please be patient :)
=> [CAMEL-21740] camel-salesforce - pub/sub API corrupt replay id causes infinite resubscribe loop fix

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/DependencyListITCase.java, dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/InVersion.java
since DependencyListITCase test causes unexpected errors with snapshot version, it is skipped just for this case
=> camel-jbang-it: exclude dependency tests for snapshot versions

dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/KnownDependenciesResolver.java
This pull request improves KnownDependenciesResolver to load all camel-main-known-dependencies.properties files present in the classpath. Currently, only the first found file is loaded. This will allow clients to add custom mappings additionally to the predefined ones coming from camel-kamelet-main.
=> Improve KnownDependenciesResolver to load all properties files

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/ScriptingWithPipesITCase.java
Adds tests for [scripting with pipes](https://camel.apache.org/manual/camel-jbang.html#_scripting_from_terminal_using_pipes)
One thing to note is that when there are multiple lines of comments, the Java script seems to fail to compile. I got around this issue by adding the script into the data folder from the test itself rather than creating a resource file for it.
=> CAMEL-20367: Adds scripting with pipes test

components/camel-activemq6/src/main/docs/activemq6-component.adoc
There is a mistake in the artifact id of activemq6 dependency in the documentation
=> Correct the artifact id of activemq6 dependency in the documentation

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/CamelDebugITCase.java
Adds test for [camel debug](https://camel.apache.org/manual/camel-jbang.html#_camel_route_debugging). 
Unfortunately I don't think JVM debug tests can be practically implemented since capturing the command output using the tools available is not possible because the process will never finish without interaction (hence the use of nohup in camel debug test).
=> CAMEL-20367: Adds camel debug test

components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/config_maps/vault/ConfigmapsReloadTriggerTask.java
Follow up to #17240. I missed `ConfigmapsReloadTriggerTask`.
=> CAMEL-21770: Avoid closing autowired KubernetesClient in ConfigmapsReloadTriggerTask

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc, dsl/camel-jbang/camel-jbang-plugin-kubernetes/pom.xml, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesHelper.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesBaseTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRunCustomTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/resources/log4j2.properties
Set parameters when connected to specific cluster
https://issues.apache.org/jira/browse/CAMEL-21710
=> CAMEL-21710 camel-jbang-plugin-kubernetes - automatic cluster detection

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/RunCommandOnMqttITCase.java, dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/ScriptingWithPipesITCase.java, dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/JBangTestSupport.java, dsl/camel-jbang/camel-jbang-it/src/test/resources/jbang/it/StubRoute.java
Adds test for [stubbing components](https://camel.apache.org/manual/camel-jbang.html#_stub_components_that_should_not_be_active).
A small change to avoid use of `execInHost()` also included.
=> CAMEL-20367: Adds stub test

parent/pom.xml
Upgrade to jboss-xnio 3.8.16.Final; did a mvn -skipTests clean install
Note - this is to the 4.10.x branch and I was hoping to sneak this in before 4.10.1
=> Upgrade to jboss-xnio 3.8.16.Final

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/PubSubApiConsumer.java, components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/client/PubSubApiClient.java, components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/PubSubApiTest.java
I have added a new checkInitialReplayIdValidity method that gets executed once during the consumer startup if the provided ReplayPreset is CUSTOM.
If the provided intial replay id is corrupt/invalid an exception is thrown and Camel shuts down. (The same behaviour as when a null initialReplayId is provided.)
This workaround is just suggestion. It feels a bit hacky to me, but seems to be the best solution.
I think the error handling of this commit https://github.com/apache/camel/commit/546a5016f05ce7bfc5a663bfd6ae6a0bf1d4d3e0 will not work like intended because the method resubscribeOnError() will always set the ReplayPreset to CUSTOM if replayId is not null.
Sorry for being a bit late :)
=> [CAMEL-21740] Check initial replay id validity on consumer startup

components/camel-smooks/src/main/resources/META-INF/xsd/smooks/camel-1.5.xsd-smooks.xml
Remove untested and undocumented way for declaring route conditions in element text content. Route conditions should be declared in the `if` attribute.
=> CAMEL-21821: drop support for declaring route condition in element text

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_11.adoc, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java, dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/KameletMain.java
Introduce a new flag (`--observe`) which will include the deprecated `--health` and `--metrics` when running Camel via JBang.
=> feat(dsl/jbang): Run --observe to replace --metrics and --health

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/CamelDocITCase.java
Adds a simple test to check [camel documentation is displayed](https://camel.apache.org/manual/camel-jbang.html#_displaying_component_documentation)
=> CAMEL-20367: Adds camel doc test

dsl/camel-jbang/camel-jbang-plugin-kubernetes/pom.xml, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesBaseCommand.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesDelete.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesHelper.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesCommandTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesDeleteTest.java
Do not use the camel-jbang temporary directory
The "run" op sets labels used in the "del" op
Use a single KubernetesClient instance in the KubernetesHelper
=> camel-jbang-plugin-kubernetes: make the delete op to delete from the k8s resources

components/camel-chunk/src/main/docs/chunk-component.adoc
This PR fixes the broken link in the camel-chunk documentation. The previous URL
`http://www.x5software.com/chunk/examples/ChunkExample?loc=en_US`
is no longer valid and redirects users incorrectly. I have updated the URL to point to the new, maintained repository at:
`https://github.com/tomj74/chunk-templates`
=> Update camel-chunk documentation: Replace outdated URL with Correct one

bom/camel-bom/pom.xml, parent/pom.xml
Align with netty/spring redis with spring-boot 3.3.9; refresh
Note - this is for the 4.8.x branch.    
Also : due to the branch being dirty, this PR will collide with https://github.com/apache/camel/pull/17421 - both PRs include a refresh of the branch - I can rebase once one of these PRs gets merged
=> Align with netty/spring redis with spring-boot 3.3.9; refresh

docs/user-manual/modules/ROOT/pages/event-notifier.adoc
Clarified that timestamps by default are not included, and need to be enabled explicitly.
=> Update event-notifier.adoc for using timestamps

parent/pom.xml
On 4.8.x branch, netty version is set to 4.1.119.Final, but reactor-netty 1.1.22 points to netty 4.1.118.Final.    Upgrade reactor-netty version to 1.1.28 (most recent) to match netty 4.1.119.Final.
=> Upgrade reactor-netty to 1.1.28 to match the version of netty in camel (4.1.119.Final)

components/camel-smooks/pom.xml
=> Move smooks-edi-cartridge dependency from test scope.

parent/pom.xml
Align versions in the camel parent to the versions used in spring-boot 3.3.10 for spring-* dependencies and jetty/slf4j.    Did a mvn -DskipTests clean install and ran the tests in camel-jetty; everything passed.
=> Align versions to spring-boot 3.3.10

components/camel-servicenow/camel-servicenow-component/src/main/java/org/apache/camel/component/servicenow/AbstractServiceNowProcessor.java
When updating a ServiceNow resource (e.g. incident) the body is compared to be a subtype of the allowed model. The implementation had a bug that tests "the model is a subtype of the body" - this PR fixes the bug by reversing the order or comparison, i.e. it tests whether the model is a parent/super type of the supplied body.
JIRA Issue: https://issues.apache.org/jira/browse/CAMEL-21877
=> [CAMEL-21877] fix body comparison - model is the parent/super type of body

core/camel-support/src/main/java/org/apache/camel/support/cache/SimpleLRUCache.java
Fix for https://issues.apache.org/jira/browse/CAMEL-21888
Iterating over all the changes to get size is very costly in case of a big cache size. Using a counter to have the size of changes was initially avoided for consistency issues reason, but the addition lately of a ReadWriteLock allows us to put it back
* Avoid an O(N) to get the size of the changes by counting them using an AtomicInteger.
=> CAMEL-21888: camel-core - Compute cache changes size

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/health/KafkaConsumerHealthCheckIT.java
Similar to https://github.com/apache/camel/pull/8107/commits/98284afe7ab3a557cf2b718d7089576eb99c1328. 
Skipping newer Kafka health test when using Strimzi. Would like to backport to `4.10.x` after as well.
=> Skip Kafka health test when using Strimzi

core/camel-core-engine/src/main/java/org/apache/camel/impl/DefaultModel.java
- Make sure to use the property set via environment variables when the Kamelet property has a default value
- Only use the default Kamelet property value as a fallback when not set explicitly
See CAMEL-21893
=> CAMEL-21893: EnvVar settings should overwrite default Kamelet properties

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesDelete.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesCommandTest.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesDeleteTest.java
https://issues.apache.org/jira/browse/CAMEL-21855
=> CAMEL-21855: camel-jbang - k8s delete may not work any more

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitContext.java
- Add OpenShift specific runtime label on Kubernetes deployment when doing the Camel JBang project export to OpenShift cluster
- Makes sure to display the Camel logo as part of the Deployment in OpenShift
=> CAMEL-21904: Use cluster specific labels on Kubernetes deployment

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/ContainerTrait.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitHelper.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java
- Do not set container image name on Kubernetes deployment
- Use `jkube.container-image.name` setting in the generated Maven project instead
- Allows users to overwrite the container image name in Maven builds (e.g. when using a CI/CD pipeline)
See CAMEL-21903
=> CAMEL-21903: camel-jbang: Adjustable container image name on Kubernetes export

components/camel-observation/src/main/resources/META-INF/services/org.apache.camel.tracing.SpanDecorator, components/camel-opentelemetry/src/main/resources/META-INF/services/org.apache.camel.tracing.SpanDecorator, components/camel-tracing/src/main/java/org/apache/camel/tracing/decorators/AzureStorageDataLakeSpanDecorator.java, components/camel-tracing/src/test/java/org/apache/camel/tracing/decorators/AzureStorageDataLakeSpanDecoratorTest.java
Added azure-storage-queue Span decorator.
=> CAMEL-20937 add azure-storage-datalake span decorator

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelCommand.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelJBangMain.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/config/ConfigGet.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/config/ConfigList.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/config/ConfigSet.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/config/ConfigUnset.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/version/VersionGet.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/version/VersionSet.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/CommandLineHelper.java, dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/UserConfigHelper.java, dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/config/BaseConfigTest.java, dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/config/ConfigGetTest.java, dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/config/ConfigListTest.java, dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/config/ConfigSetTest.java, dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/config/ConfigUnsetTest.java, test-infra/camel-test-infra-cli/src/test/resources/org/apache/camel/test/infra/cli/services/Dockerfile
Added the following options:
* `--mergeConfigurations` loads the configurations default one _~/.camel-jbang-user.properties_ and the one in the current directory (if exists) _./.camel-jbang-user.properties_, the latter is prioritized. This config is a bit hacky, it is used to preload the configuration before the actual picocli execution, if the argument mergeConfigurations exists, the configurations are merged, and the argument removed before passing the args to Picocli.
* `--local` Use the configuration in current directory (to be used with `camel config` commands)
=> CAMEL-21896: camel-jbang - Allow configuration preset per directory

components/camel-http/src/main/java/org/apache/camel/component/http/OAuth2ClientConfigurer.java, components/camel-http/src/test/java/org/apache/camel/component/http/HttpOAuth2ScopeTest.java, components/camel-http/src/test/java/org/apache/camel/component/http/handler/OAuth2ScopeRequestHandler.java
Updated OAuth2ClientConfigurer to set the parameter values for oauth2Scope on the request body instead of a query parameter when using client_credentials as grant_type. This should be done according to OAuth2 [documentation](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-client-creds-grant-flow) provided by Microsoft.
=> CAMEL-21907: Set OAuth2 scope on request body

components/camel-http/src/main/java/org/apache/camel/component/http/OAuth2ClientConfigurer.java, components/camel-http/src/test/java/org/apache/camel/component/http/HttpOAuth2ScopeTest.java, components/camel-http/src/test/java/org/apache/camel/component/http/handler/OAuth2ScopeRequestHandler.java
Backport for [CAMEL-21907](https://issues.apache.org/jira/browse/CAMEL-21907) to Camel 4.10.x
Updated OAuth2ClientConfigurer to set the parameter values for oauth2Scope on the request body instead of a query parameter when using client_credentials as grant_type. This should be done according to OAuth2 [documentation](https://learn.microsoft.com/en-us/entra/identity-platform/v2-oauth2-client-creds-grant-flow) provided by Microsoft.
=> CAMEL-21907: Backport of set OAuth2 scope on request body to Camel 4.10.x

components/camel-attachments/src/main/java/org/apache/camel/attachment/DefaultAttachmentMessage.java, components/camel-attachments/src/test/java/org/apache/camel/attachment/AttachmentRemovalTest.java
…
Updated the remove attachment logic: remove ATTACHMENTS trait when last attachment is removed.
=> CAMEL-21926 camel-attachment fix inconsistent behaviour when last attachment is removed

core/camel-core/src/test/java/org/apache/camel/impl/health/ContextHealthCheckTest.java, core/camel-health/src/main/java/org/apache/camel/impl/health/ContextHealthCheck.java
Fixes the health check once the Camel context has started, otherwise the result was DOWN even if the status is started
=> health-check: Fixes Camel context health check

components/camel-jolt/src/main/java/org/apache/camel/component/jolt/JoltComponent.java
Added call to setProperties before appending the remaining params to the http resourceUri.
[CAMEL-21938](https://issues.apache.org/jira/browse/CAMEL-21938)
=> [CAMEL-21938] camel-jolt - inputType & outputType can't be set for http uris

components/camel-salesforce/camel-salesforce-maven-plugin/src/main/java/org/apache/camel/maven/AbstractSalesforceMojo.java
Bug does not affect old logic with username password auth but prevents using new JWT Authentication
removing required flag from camelSalesforce.password and camelSalesforce.clientSecret property is necessary but validated later on. Logic for that was already in place.
No existing BugTicket for this
=> camel-salesforce-maven-plugin: fix JWT authentication

components/camel-master/src/main/java/org/apache/camel/component/master/MasterComponent.java
I noticed that the condition to cleanup the thread pool is wrong, so it actually never gets cleaned up when stopping the component.
=> Fix thread pool cleanup in MasterComponent

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/CmdStartStopITCase.java, dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/TransformMessageITCase.java
Adds tests for [watching camel integrations](https://camel.apache.org/manual/camel-jbang.html#_watching_local_camel_integrations) and [transforming route DSL](https://camel.apache.org/manual/camel-jbang.html#_transforming_routes_dsl)
=> CAMEL-20367: Adds Camel watch and Route DSL transformation tests

components/camel-kafka/pom.xml, dsl/camel-kamelet-main/pom.xml
I think that the best practice here, would be that users create a `dev` maven profile with camel-console dependency.
I do not think we need documentation here since in camel-console documentation there is already
```
== Using Camel Console
The `camel-console` must be added to the classpath, and enabled either via...
...
```
But if this PR makes sense, and is merged, I'll open a jira issue for the release notes
=> Camel-Console is not needed in production, make it provided

components/camel-dhis2/camel-dhis2-component/src/main/java/org/apache/camel/component/dhis2/Dhis2Component.java, components/camel-dhis2/camel-dhis2-component/src/test/java/org/apache/camel/component/dhis2/Dhis2ComponentTestCase.java
Allow empty credentials in DHIS2 component since it's possible that one set of credentials defaults to an empty string when the auth type is not known ahead of time
=> Allow empty credentials in DHIS2 component

core/camel-core-model/src/main/java/org/apache/camel/model/ChoiceDefinition.java, core/camel-core-model/src/main/java/org/apache/camel/model/ProcessorDefinition.java, core/camel-core/src/test/java/org/apache/camel/processor/NestedChoiceIssueTest.java, core/camel-core/src/test/java/org/apache/camel/processor/NestedChoiceOtherwiseIssueTest.java, core/camel-core/src/test/java/org/apache/camel/processor/TripleNestedChoiceIssueTest.java, core/camel-core/src/test/java/org/apache/camel/processor/async/AsyncNestedTripleChoiceIssueTest.java, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_12.adoc
=> CAMEL-21958: camel-core: Java DSL. Fix endChoice() to reuse end() and scope to current/nearest choice.

components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/CamelContextConfiguration.java
This would be convenient to replace the deprecated org.apache.camel.test.junit5.AbstractTestSupport.replaceRouteFromWith(String, String)
A workaround avoiding deprecated API is currently to use:
```
@Override
public void configureContext(CamelContextConfiguration
camelContextConfiguration) {
super.configureContext(camelContextConfiguration);
camelContextConfiguration.fromEndpoints().put(routeId,
"direct:in");
}
```
for instance, could be replaced then here https://github.com/apache/camel-examples/blob/218836af4251d9ecb70f18dedb3b2e4511925767/kafka/src/test/java/org/apache/camel/example/kafka/KafkaTest.java#L60-L64
=> feat: Expose CamelContextConfiguration.replaceRouteFromWith(String, String) as API

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/test-infra/metadata.json, test-infra/camel-test-infra-all/src/generated/resources/META-INF/metadata.json, test-infra/camel-test-infra-kafka/src/main/java/org/apache/camel/test/infra/kafka/common/KafkaProperties.java, test-infra/camel-test-infra-kafka/src/main/java/org/apache/camel/test/infra/kafka/services/ConfluentContainer.java, test-infra/camel-test-infra-kafka/src/main/java/org/apache/camel/test/infra/kafka/services/ConfluentInfraService.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/KafkaServiceFactory.java
Since parameters between apache-kafka server (the default one) and cp-kafka (confluent) differ a bit, need to create a separate instance that would be activated by:
`-Dkafka.instance.type=local-confluent-container`
=> Adding confluent kafka instance type

components/camel-sql/src/main/java/org/apache/camel/component/sql/SqlProducer.java
Add-on to the optimization from CAMEL-21845. Commit or rollback should only be called if auto commit has not been set to false before. This might be intended to control the transaction for whatever reason! In cases of XA transactions, for example, calling commit or rollback would cause exceptions.
=> CAMEL-21845: camel-sql - Only commit/rollback if auto commit has been true

core/camel-main/src/main/java/org/apache/camel/main/BaseMainSupport.java
COPY_PASTE_ERROR (CWE-398)
Looks like there is a wrong value used when copying configuration.
=> Copy paste typo fix

core/camel-support/src/main/java/org/apache/camel/converter/stream/FileInputStreamCache.java
RESOURCE_LEAK (CWE-404)
The out variable leaks if exception GeneralSecurityException is thrown
=> Resource leak in FileInputStreamCache

components/camel-file/src/main/java/org/apache/camel/component/file/GenericFileConverter.java
RESOURCE_LEAK (CWE-404)
Resource leak. Input stream _is_ is not closed anywhere.
=> Resource leak in GenericFileConverter

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
RESOURCE_LEAK (CWE-404)
Resource leak. Input stream _is_ is not closed after use.
=> Resource leak in JBang Run

parent/pom.xml
camel-4.8.x LTS branch change - align camel spring versions to the versions in spring-boot 3.3.11.     camel-spring-boot-4.8.x was upgraded to spring-boot 3.3.11 in this commit : https://github.com/apache/camel-spring-boot/commit/d6c7b984d56f1ad77ec58dbf8d2b0e5329621bc1
A large number of files were refreshed in the mvn -DskipTests clean install
parent/pom.xml versions changed here --
groovy 4.0.25 -> 4.0.26
jetty 12.0.18 -> 12.0.19
spring-ldap 3.2.11 -> 3.2.12
spring 6.1.18 -> 6.1.19 
- [x ] I have run `mvn clean install -DskipTests` locally from root folder and I have committed all auto-generated …
=> Align spring properties and jetty to match versions in spring-boot-dependencies

components/camel-optaplanner/pom.xml
Enabling support for camel-optaplanner on power
Test Results :
[ppc64le_optaplanner_build.txt](https://github.com/user-attachments/files/19905736/ppc64le_optaplanner_build.txt)
[x86optaplanner_build.txt](https://github.com/user-attachments/files/19905738/x86optaplanner_build.txt)
=> Enable ppc64le Support for Camel-optaplanner

components/camel-micrometer-prometheus/src/main/java/org/apache/camel/component/micrometer/prometheus/MicrometerPrometheus.java, components/camel-platform-http-main/src/main/java/org/apache/camel/component/platform/http/main/MainHttpServer.java, components/camel-platform-http-main/src/main/java/org/apache/camel/component/platform/http/main/MainHttpServerUtil.java, components/camel-platform-http-main/src/main/java/org/apache/camel/component/platform/http/main/ManagementHttpServer.java, components/camel-platform-http/src/main/java/org/apache/camel/component/platform/http/PlatformHttpComponent.java
* Reverted the change done in b19a5f690b920b0936f00f560c6be6b82dec48f8
* Added a data structure to hold management endpoints
After the PR, the printout will result like:
```
2025-04-30 11:47:04.050  INFO 168627 --- [           main] e.camel.impl.engine.AbstractCamelContext : Apache Camel 4.12.0-SNAPSHOT (camel-1) started in 458ms (build:0ms init:0ms start:458ms boot:1s740ms)
2025-04-30 11:47:04.052  INFO 168627 --- [           main] nt.platform.http.main.MainHttpServerUtil : HTTP endpoints summary
2025-04-30 11:47:04.053  INFO 168627 --- [           main] nt.platform.http.main.MainHttpServerUtil :     http://0.0.0.0:8080/hello              (GET)    
2025-04-30 11:47:04.053  INFO 168627 --- [           main] nt.platform.http.main.MainHttpServerUtil :     http://0.0.0.0:8080/observe/health …
```
=> chore(components): platform http endpoints resume

components/camel-jsonata/src/main/java/org/apache/camel/component/jsonata/JsonataEndpoint.java, components/camel-jsonata/src/test/java/org/apache/camel/component/jsonata/JsonataJacksonOutputTest.java
Changing the body output type to JsonNode when jsonata component output type is Jackson.
- [ X] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).
- [ X] I checked that each commit in the pull request has a meaningful subject line and body.
- [ X] I have run `mvn clean install -DskipTests` locally from root folder and I have committed all auto-generated changes.
=> CAMEL-22062: Using JsonNode for output when outputType is Jackson

test-infra/camel-test-infra-ftp/src/main/java/org/apache/camel/test/infra/ftp/services/FtpInfraService.java, test-infra/camel-test-infra-ftp/src/main/java/org/apache/camel/test/infra/ftp/services/embedded/FtpEmbeddedInfraService.java, test-infra/camel-test-infra-ftp/src/main/java/org/apache/camel/test/infra/ftp/services/embedded/SftpEmbeddedInfraService.java
When using `camel infra run $SERVICE` the resulting json properties should match the Camel ones. For example, right now `camel infra run ftp` print
```
{
"getFtpRootDir" : "file:///private/tmp/test/target/ftp/camel-test-infra-test-directory/camel-test-infra-configuration-test-directory",
"getPort" : 49894
} 
```
This json has some issues:
* Wrong naming convention, getPort should be port to match the property in Camel
* The hostname is missing (in this case can be a constant, localhost)
* The directoryName is missing as well (any constant string would be ok)
* Username and password are needed as well since the underlying implementation needs those.
This way, the command will be tool-friendly and tools may automagically configure routes for fast prototyping.
With the fix, the following is …
=> CAMEL-22083: FTP

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/PluginHelper.java
JIRA issue: [CAMEL-21981](https://issues.apache.org/jira/browse/CAMEL-21981)
When invoking the shell command, commands from plugins are ignored.
=> [CAMEL-21981] camel-jbang: when running in shell mode, plugins cannot be used

components/camel-arangodb/src/test/java/org/apache/camel/component/arangodb/integration/ArangoCustomVertxIT.java, components/camel-arangodb/src/test/java/org/apache/camel/component/arangodb/integration/BaseArangoDb.java, test-infra/camel-test-infra-arangodb/pom.xml, test-infra/camel-test-infra-arangodb/src/main/java/org/apache/camel/test/infra/arangodb/services/ArangoDBInfraService.java, test-infra/camel-test-infra-arangodb/src/main/java/org/apache/camel/test/infra/arangodb/services/ArangoDBLocalContainerInfraService.java, test-infra/camel-test-infra-arangodb/src/main/java/org/apache/camel/test/infra/arangodb/services/ArangoDBRemoteInfraService.java, test-infra/camel-test-infra-arangodb/src/test/java/org/apache/camel/test/infra/arangodb/services/ArangoDBServiceFactory.java
Creates a database and a collection during `camel infra run arangodb` startup resulting in:
```
{
"database" : "myDatabase",
"documentCollection" : "myCollection",
"getHost" : "localhost",
"getPort" : 8529,
"getServiceAddress" : "localhost:8529",
"host" : "localhost",
"port" : 8529
}
```
that can be used as:
```
from("timer:java?period=1000")
.process(ex -> {
com.arangodb.entity.BaseDocument myObject = new com.arangodb.entity.BaseDocument();
myObject.addAttribute("a", "Foo");
myObject.addAttribute("b", 42);
ex.getIn().setBody(myObject);
})
.to("arangodb:myDatabase?documentCollection=myCollection&operation=SAVE_DOCUMENT&host=localhost&port=8529")
.log("${body}");
```
=> CAMEL-22083: ArangoDB

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/test-infra/metadata.json, test-infra/camel-test-infra-all/src/generated/resources/META-INF/metadata.json, test-infra/camel-test-infra-artemis/src/main/java/org/apache/camel/test/infra/artemis/services/ArtemisAMQPInfraService.java, test-infra/camel-test-infra-artemis/src/main/java/org/apache/camel/test/infra/artemis/services/ArtemisInfraService.java, test-infra/camel-test-infra-artemis/src/main/java/org/apache/camel/test/infra/artemis/services/ArtemisMQTTInfraService.java, test-infra/camel-test-infra-artemis/src/main/java/org/apache/camel/test/infra/artemis/services/ArtemisPersistentVMInfraService.java, test-infra/camel-test-infra-artemis/src/main/java/org/apache/camel/test/infra/artemis/services/ArtemisVMInfraService.java
AMQP usage where `amqp://0.0.0.0:56142` is `remoteURI`:
```
///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS org.apache.camel:camel-amqp:4.12.0-SNAPSHOT
//DEPS org.apache.qpid:qpid-jms-client:2.7.0
import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.Exchange;
public class MyRoute extends RouteBuilder {
@Override
public void configure() throws Exception {
org.apache.qpid.jms.JmsConnectionFactory connectionFactory =
new org.apache.qpid.jms.JmsConnectionFactory("amqp://0.0.0.0:56142");
getCamelContext().getRegistry().bind("connectionFactory", connectionFactory);
from("timer:java?period=1000")
.setBody()
.simple("Hello Camel from ${routeId}")
.to("amqp:test?connectionFactory=#connectionFactory");
from("amqp:test?connectionFactory=#connectionFactory")
.log("${body}");
}
}
```
=> Camel 22083 artemis

test-infra/camel-test-infra-aws-common/src/main/java/org/apache/camel/test/infra/aws/common/services/AWSInfraService.java, test-infra/camel-test-infra-aws-v2/src/main/java/org/apache/camel/test/infra/aws2/services/AWSLocalContainerInfraService.java, test-infra/camel-test-infra-aws-v2/src/main/java/org/apache/camel/test/infra/aws2/services/AWSRemoteInfraService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSServiceFactory.java
SQS Example usage:
```
///usr/bin/env jbang "$0" "$@" ; exit $?
//DEPS org.apache.camel:camel-aws2-sqs:4.12.0-SNAPSHOT
import org.apache.camel.builder.RouteBuilder;
import org.apache.camel.Exchange;
public class MyRoute extends RouteBuilder {
@Override
public void configure() throws Exception {
from("timer:java?period=1000")
.setBody()
.simple("Hello Camel from ${routeId}")
.to("aws2-sqs:test?amazonAWSHost=localhost:32775&autoCreateQueue=true&region=us-east-1&protocol=http&accessKey=accessKey&secretKey=secretKey");
from("aws2-sqs:test?amazonAWSHost=localhost:32775&autoCreateQueue=true&region=us-east-1&protocol=http&accessKey=accessKey&secretKey=secretKey")
.log("${body}");
}
}
```
Where `amazonAWSHost`, `region`, `protocol`, `accessKey` and `secretKey` are taken from the console output …
=> CAMEL-22083: AWS

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Nano.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Shell.java, dsl/camel-jbang/camel-jbang-core/src/main/resources/nano/asciidoc.nanorc, dsl/camel-jbang/camel-jbang-core/src/main/resources/nano/java.nanorc, dsl/camel-jbang/camel-jbang-core/src/main/resources/nano/jnanorc, dsl/camel-jbang/camel-jbang-core/src/main/resources/nano/json.nanorc, dsl/camel-jbang/camel-jbang-core/src/main/resources/nano/markdown.nanorc, dsl/camel-jbang/camel-jbang-core/src/main/resources/nano/properties.nanorc, dsl/camel-jbang/camel-jbang-core/src/main/resources/nano/xml.nanorc, dsl/camel-jbang/camel-jbang-core/src/main/resources/nano/yaml.nanorc, dsl/camel-jbang/camel-jbang-plugin-edit/src/main/java/org/apache/camel/dsl/jbang/core/commands/edit/EditCommand.java, parent/pom.xml, pom.xml
JIRA issue: [CAMEL-22077](https://issues.apache.org/jira/browse/CAMEL-22077)
This PR provides syntax highlighting for the nano, less and edit commands with support for: asciidoc, java, json, markdown, properties, xml and yaml languages.
The coloring could be modified and enhanced (I don't like much the xml syntax coloring fwiw).
=> [CAMEL-22077] Provide syntax highlighting for came-jbang shell commands

.mvn/extensions.xml, pom.xml
Switch to Nisse extension and make sure the `os.detected.classifier` is a project property, so that it can be overriden by profiles (as user properties cannot).
=> chore: fix build for Maven 4

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportQuarkus.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportSpringBoot.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
This should fix https://issues.apache.org/jira/browse/CAMEL-22087
`--verbose` option should be fixed too
- [main]
=> CAMEL-22087: Make name and port camel CLI option working on CSB and CEQ

parent/pom.xml
This commit on camel-spring-boot-4.10.x upgraded spring-boot to 3.4.6 - https://github.com/apache/camel-spring-boot/commit/71af2bb0c679920ead0ff12aae8b16c64859a6d3 
Align the spring-* versions in camel to the versions used in spring-boot 3.4.6
=> Align spring* versions to the versions used in spring-boot 3.4.6

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/JolokiaTrait.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitCatalog.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/Jolokia.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/JolokiaBuilder.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/Traits.java, dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java
Add the Jolokia trait to allow to enrich the kubernetes manifests. It exposes the Jolokia port in the Container and Service.
=> CAMEL-21087: Add jolokia trait to Camel Jbang Kubernetes plugin

components/camel-http/src/main/java/org/apache/camel/component/http/BasicAuthenticationHttpClientConfigurer.java
Set NTLM as preferred scheme
[CAMEL-22073](https://issues.apache.org/jira/browse/CAMEL-22073): camel-http - NTLM authentication doesn't work over http
=> camel-http - NTLM authentication doesn't work over http - Set NTLM as preferred scheme

components/camel-openapi-validator/src/main/java/org/apache/camel/component/rest/openapi/validator/client/OpenApiRestClientRequestValidator.java, components/camel-openapi-validator/src/test/java/org/apache/camel/component/rest/openapi/validator/client/OpenApiRestClientRequestValidatorTest.java, components/camel-openapi-validator/src/test/resources/petstore-v3.json
Fix for CAMEL-22117: camel-openapi-validator doesn't use query params or headers for validation
=> CAMEL-22117: Include query params and headers in validation context.

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java, dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/TransformTest.java
* one part was a regression for the test introduced with
https://github.com/apache/camel/commit/e732f61286f69bd9aec5802cff8ececf51a78377
. It emphasizes a potential lock remaining on the log file related to
the pid of a process started with Camel Jbang. Solution consists in
reusing the FileUtil method which has been already updated to use
java.nio anyway.
* one part was that it never passed because of end of line not
considered in the test
=> Fix Camel Jbang TransformTest on Windows

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_12.adoc, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
used
* Checking if the path starts with classpath: before using it with Path.of
* Use Path.of instead of Paths.get as the javadoc is recommending it this way
it allows to get down from 34 failures and 2 errors to 2 errors and 2 failures on Windows
=> Fix several Camel Jbang functionalities on Windows when classpath url is

components/camel-infinispan/camel-infinispan/pom.xml
https://issues.apache.org/jira/browse/CAMEL-22137
Seems the infinispan annotation processor needs to be set in the maven compiler plugin ?
=> CAMEL-22137: camel-infinispan : add Infinispan annotation processor

components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/OpenTelemetrySpanAdapter.java, components/camel-opentelemetry2/src/main/java/org/apache/camel/opentelemetry2/OpenTelemetrySpanAdapter.java
This pull requests changes the OpenTelemetrySpanAdapter so that it sets the span status code to either OK or ERROR on the setError method.
=> feat: setting span statusCode based on error indicator

components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/MicrometerConstants.java, components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/eventnotifier/MicrometerExchangeEventNotifier.java, components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/eventnotifier/MicrometerExchangeEventNotifierDynamicTest.java, components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/eventnotifier/MicrometerExchangeEventNotifierStaticTest.java
Added a new meter to include the timestamp of the last executed exchange. The value is backed by a thread-safe static variable and it's the way suggested by the framework to mutate the values of any meter.
After the merge, the new metrics will be like:
```
camel_exchanges_last_timestamp 1.749824808777E12
```
Closes CAMEL-22153
=> feat(components): camel-micrometer exchanges last timestamp

components/camel-smb/src/main/java/org/apache/camel/component/smb/SmbConsumer.java
During debugging, I noticed that asGenericFile() in SmbConsumer sets a different last modified timestamp compared to the camel-file component for the same file.
The Java File API's lastModified() returns the LastWriteTime field, which is also the timestamp displayed in Windows Explorer, so i aligned the SmbConsumer to use the same timestamp as the FileConsumer.
=> camel-smb: Align last modified timestamp in SmbConsumer with camel-file component behavior

Jenkinsfile
The Jenkins slave is often corrupted failing the build with this error message:
```
Caused by: org.eclipse.aether.RepositoryException: Could not parse
metadata /home/jenkins/.m2/repository/org/apache/camel/camel-buildtools/maven-metadata-local.xml:
in epilog non whitespace content is not allowed but got a (position:
END_TAG seen ...</metadata>\na... @34:2)
```
So when cleaning the workspace, deleting the parent folder. Not deleting the whole .m2 as this would slow down too much the build. Deleting the whole folder to avoid having data not in phase inside the folder.
=> INFRA-26918 - Clean often corrupted folder on Jenkins

core/camel-support/src/main/java/org/apache/camel/support/cache/SimpleLRUCache.java
Fix for https://issues.apache.org/jira/browse/CAMEL-22176 (4.10)
We can have a lot of CPU consumption in case of a big cache that is frequently updated
* Make the cache eviction blocking to prevent the addition of new changes/entries in parallel, which could quickly fill up the cache, to avoid spending our time evicting changes
=> CAMEL-22176: camel-core - make the cache eviction blocking (4.10)

parent/pom.xml
Align spring-* versions and a few others to the versions used in spring-boot 3.4.7.       In the camel-spring-boot project, https://github.com/apache/camel-spring-boot/pull/1452 changes the spring-boot version to 3.4.7 in the camel-spring-boot-4.10.x branch.
(not a large change, no JIRA)
=> Align versions to spring-boot 3.4.7 versions

parent/pom.xml
camel-4.8.x branch
Upgrade spring.* versions to align with spring-boot 3.3.13 - most are spring.* version upgrades but other notable updates here to align with spring-boot 3.3.13 versions are jetty 12.0.19 -> 12.0.22 and cometd update to match jetty update, groovy from 4.0.26->4.0.27 and netty 4.1.119 -> 4.1.122.   
=> Upgrade versions to align with spring-boot 3.3.13

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/update/UpdateList.java
it doesn't fix the potential root cause, so maybe an update version will be missing but at least it avoids to break existing feature when the list of upgrade recipes is modified (in some ways that I have not defined yet)
=> CAMEL-22184 - avoid IndexOutBoundException in Camel Jbang update list

Jenkinsfile
as unfortunately, it seems that corrupted repo can happen on different Camel metadata files, the new one:
```
Caused by: org.eclipse.aether.RepositoryException: Could not parse
metadata /home/jenkins/.m2/repository/org/apache/camel/camel-util/maven-metadata-local.xml:
in epilog non whitespace content is not allowed but got a (position:
END_TAG seen ...</metadata>\na... @34:2)
```
=> INFRA-26918 - clean whole .m2 org/apache/camel on Jenkins slave

components/camel-spring-parent/camel-spring-rabbitmq/src/test/java/org/apache/camel/component/springrabbit/integration/RabbitMQITSupport.java, test-infra/camel-test-infra-ftp/src/main/java/org/apache/camel/test/infra/ftp/services/FtpInfraService.java, test-infra/camel-test-infra-ftp/src/main/java/org/apache/camel/test/infra/ftp/services/embedded/FtpEmbeddedInfraService.java, test-infra/camel-test-infra-ftp/src/main/java/org/apache/camel/test/infra/ftp/services/embedded/SftpEmbeddedInfraService.java, test-infra/camel-test-infra-kafka/src/main/java/org/apache/camel/test/infra/kafka/services/ConfluentInfraService.java, test-infra/camel-test-infra-kafka/src/main/java/org/apache/camel/test/infra/kafka/services/ContainerLocalKafkaInfraService.java, test-infra/camel-test-infra-kafka/src/main/java/org/apache/camel/test/infra/kafka/services/KafkaInfraService.java, test-infra/camel-test-infra-kafka/src/main/java/org/apache/camel/test/infra/kafka/services/RedpandaInfraService.java, test-infra/camel-test-infra-kafka/src/main/java/org/apache/camel/test/infra/kafka/services/RemoteKafkaInfraService.java, test-infra/camel-test-infra-kafka/src/main/java/org/apache/camel/test/infra/kafka/services/StrimziInfraService.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/ContainerLocalAuthKafkaService.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/KafkaServiceFactory.java, test-infra/camel-test-infra-milvus/src/main/java/org/apache/camel/test/infra/milvus/services/MilvusInfraService.java, test-infra/camel-test-infra-milvus/src/main/java/org/apache/camel/test/infra/milvus/services/MilvusLocalContainerInfraService.java, test-infra/camel-test-infra-milvus/src/main/java/org/apache/camel/test/infra/milvus/services/MilvusRemoteInfraService.java, test-infra/camel-test-infra-milvus/src/test/java/org/apache/camel/test/infra/milvus/services/MilvusServiceFactory.java, test-infra/camel-test-infra-qdrant/src/main/java/org/apache/camel/test/infra/qdrant/services/QdrantInfraService.java, test-infra/camel-test-infra-qdrant/src/main/java/org/apache/camel/test/infra/qdrant/services/QdrantLocalContainerInfraService.java, test-infra/camel-test-infra-qdrant/src/main/java/org/apache/camel/test/infra/qdrant/services/QdrantRemoteInfraService.java, test-infra/camel-test-infra-qdrant/src/test/java/org/apache/camel/test/infra/qdrant/services/QdrantServiceFactory.java, test-infra/camel-test-infra-rabbitmq/src/main/java/org/apache/camel/test/infra/rabbitmq/services/RabbitMQInfraService.java, test-infra/camel-test-infra-rabbitmq/src/main/java/org/apache/camel/test/infra/rabbitmq/services/RabbitMQLocalContainerInfraService.java, test-infra/camel-test-infra-rabbitmq/src/main/java/org/apache/camel/test/infra/rabbitmq/services/RabbitMQRemoteInfraService.java, test-infra/camel-test-infra-rabbitmq/src/main/resources/org/apache/camel/test/infra/rabbitmq/services/container.properties
```
$ camel infra run rabbitmq --json
{
"connectionProperties" : { },
"getAmqpUrl" : "amqp://localhost:5672",
"getHttpPort" : 15672,
"initialize" : null,
"managementPassword" : "guest",
"managementUri" : "http://localhost:15672",
"managementUsername" : "guest",
"shutdown" : null,
"uri" : "amqp://localhost:5672"
}
```
```
CachingConnectionFactory cachingConnectionFactory = new CachingConnectionFactory();
cachingConnectionFactory.setUri("amqp://localhost:5672");
getCamelContext().getRegistry().bind("rabbitConnectionFactory", cachingConnectionFactory);
from("timer:java?period=1000")
.setBody()
.simple("Hello Camel from ${routeId}")
.to("spring-rabbitmq:cheese?routingKey=cheese");
from("spring-rabbitmq:cheese?routingKey=cheese")
.log("${body}");
```
The Management GUI is accessible at …
=> Align properties for camel infra command

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc, dsl/camel-jbang/camel-jbang-plugin-generate/pom.xml, dsl/camel-jbang/camel-jbang-plugin-generate/src/main/java/org/apache/camel/dsl/jbang/core/commands/generate/CodeSchemaGenerator.java, dsl/camel-jbang/camel-jbang-plugin-generate/src/main/java/org/apache/camel/dsl/jbang/core/commands/generate/GeneratePlugin.java, parent/pom.xml
Example usage:
```
$ camel generate-schema milvus io.milvus.param.dml.InsertParam
Schema saved to: ./io.milvus.param.dml.InsertParam-schema.json
```
The resulting schema can be used to marshal/unmarshal Java objects instead of a custom Camel processor. This is an enabler for low-code scenarios.
=> generate-schema Camel CLI command

components/camel-smb/src/main/java/org/apache/camel/component/smb/SmbOperations.java
When the query parameter `disconnect=true` is set, the exception thrown in `connectIfNecessary()` is an `SMBRuntimeException` from `Connection.authenticate()`, instead of an `IOException` from `SMBClient.connect()`. As a result, `disconnect()` is never called, and the consumer fails to recover from the broken connection. 
I also added that the connection is always closed on disconnect, so `disconnect=true` now fully disconnects the connection and not just the session.
@cunningt Could you take a look and see if this makes sense?
Kind regards,
jubar
Example stacktrace:
```
com.hierynomus.smbj.common.SMBRuntimeException: com.hierynomus.protocol.transport.TransportException: java.net.SocketException: Connection reset by peer
at com.hierynomus.smbj.connection.SMBSessionBuilder.establish(SMBSess …
```
=> CAMEL-22174  catch SMBRuntimeExceptions on connect and always close connection on disconnect

core/camel-core-languages/src/main/docs/modules/languages/pages/simple-language.adoc, core/camel-core-languages/src/main/java/org/apache/camel/language/simple/SimpleExpressionBuilder.java, core/camel-core-languages/src/main/java/org/apache/camel/language/simple/ast/SimpleFunctionExpression.java, core/camel-core/src/test/java/org/apache/camel/impl/RandomUuidGeneratorTest.java, core/camel-support/src/main/java/org/apache/camel/support/RandomUuidGenerator.java, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_13.adoc, docs/user-manual/modules/ROOT/pages/uuidgenerator.adoc
Add a new uuid generator type named random which implements type 4 (pseudo randomly generated) UUID. Base on java utils package UUID.
As discussed in Zulip Channel https://camel.zulipchat.com/#narrow/channel/257298-camel/topic/Simple.20UUID.20Generator/with/526396456
=> CAMEL-22210: Add UUIDv4 option to simple uuid function

dsl/camel-jbang/camel-launcher/README.md, dsl/camel-jbang/camel-launcher/pom.xml, tooling/maven/camel-repackager-maven-plugin/README.md, tooling/maven/camel-repackager-maven-plugin/pom.xml, tooling/maven/camel-repackager-maven-plugin/src/main/java/org/apache/camel/maven/RepackageMojo.java, tooling/maven/camel-repackager-maven-plugin/src/test/java/org/apache/camel/maven/RepackageMojoTest.java, tooling/maven/pom.xml
This PR introduces a new Maven plugin `camel-repackager-maven-plugin` that creates self-executing JARs using Spring Boot's loader tools, replacing the traditional maven-shade-plugin approach in the Camel JBang launcher.
The current Camel JBang launcher uses maven-shade-plugin to create "fat JARs" where all dependencies are unpacked and merged into a single JAR. This approach has several drawbacks:
- **Slower startup**: All classes are loaded into memory at startup
- **Higher memory usage**: All classes remain in memory even if unused
- **Classpath conflicts**: Overlapping files from different JARs can cause issues
- **Debugging difficulties**: Hard to identify which JAR a class came from
- **Resource conflicts**: Need complex transformers to handle META-INF conflicts
This PR implements …
=> Add camel-repackager-maven-plugin for self-executing JARs using Spring Boot loader

components/camel-debezium/camel-debezium-common/camel-debezium-common-component/src/main/java/org/apache/camel/component/debezium/configuration/EmbeddedDebeziumConfiguration.java, components/camel-debezium/camel-debezium-common/camel-debezium-common-component/src/test/java/org/apache/camel/component/debezium/configuration/EmbeddedDebeziumConfigurationTest.java, components/camel-debezium/camel-debezium-db2/src/test/java/org/apache/camel/component/debezium/db2/configuration/Db2ConnectorEmbeddedDebeziumConfigurationTest.java, components/camel-debezium/camel-debezium-mongodb/src/test/java/org/apache/camel/component/debezium/mongodb/configuration/MongodbConnectorEmbeddedDebeziumConfigurationTest.java, components/camel-debezium/camel-debezium-mysql/src/test/java/org/apache/camel/component/debezium/mysql/configuration/MySqlConnectorEmbeddedDebeziumConfigurationTest.java, components/camel-debezium/camel-debezium-oracle/src/test/java/org/apache/camel/component/debezium/oracle/configuration/OracleConnectorEmbeddedDebeziumConfigurationTest.java, components/camel-debezium/camel-debezium-postgres/src/test/java/org/apache/camel/component/debezium/postgres/configuration/PostgresConnectorEmbeddedDebeziumConfigurationTest.java, components/camel-debezium/camel-debezium-sqlserver/src/test/java/org/apache/camel/component/debezium/sqlserver/configuration/SqlserverConnectorEmbeddedDebeziumConfigurationTest.java
based on https://debezium.io/releases/3.2/release-notes
The mentioned class EmbeddedEngine will be removed https://issues.redhat.com/browse/DBZ-8029 in 3.2 (after being deprecated for several versions)
needs to use AsyncEmbeddedEngine instead
https://github.com/debezium/debezium/pull/5645/files
Doing the update here will allow an easier transition between Debezium 3.1 and 3.2 and alignment with Quarkus
=> Use AsyncEmbeddedEngine replacing deprecated EmbeddedEngine for Debezium

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaProducer.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaProducerMultipleMessagesInTransactionWithSplitTest.java
This PR fix an issue with sending multiple messages from a Split EIP to Kafka with a transaction as a fix form issue [CAMEL-22261](https://issues.apache.org/jira/browse/CAMEL-22261).
Before fix of issue [CAMEL-22259](https://issues.apache.org/jira/browse/CAMEL-22259) this cased messages to be sent in separate transaction. After applying fix for CAMEL-22259 this caused a IllegalStateException with message "Transaction already started"
=> CAMEL-22261 Reuse existing transaction if already transacted

parent/pom.xml
Upgrade infinispan and netty versions to align with spring-boot 3.5.4.     Ran mvn -DskipTests clean install and mvn test and mvn verify in camel-netty and camel-infinispan.
=> Upgrade infinispan and netty versions (spring-boot 3.5.4 alignment)

dsl/camel-yaml-dsl/camel-yaml-dsl/pom.xml
Cherry pick from main - use the parent/pom.xml defined property for postgresql version
=> Use parent/pom.xml defined property for postgresql version (#18734)

dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/ExportTest.java
Replaced get() with getProperty() for config access.
get() comes from Hashtable and returns a generic Object, while getProperty() is type-safe and clearer.
This improves readability and avoids unnecessary casting.
=> minor: Replaced get() with getProperty() for type safety and clarity

components/camel-http-common/src/main/java/org/apache/camel/http/common/HttpConfiguration.java, components/camel-http/src/main/java/org/apache/camel/component/http/HttpComponent.java, components/camel-http/src/main/java/org/apache/camel/component/http/OAuth2ClientConfigurer.java, components/camel-http/src/test/java/org/apache/camel/component/http/HttpOAuth2AuthenticationTest.java, components/camel-http/src/test/java/org/apache/camel/component/http/handler/OAuth2TokenRequestHandler.java
Adds a toggle for authentication using the POST body method defined in [rfc6749 section-2.3.1](https://www.rfc-editor.org/rfc/rfc6749.html#section-2.3.1) for OAuth 2.0. This enables camel-http to speak to OAuth2 authorization servers requiring the client credentials in the HTTP body.
=> CAMEL-22276: camel-http OAuth2.0 body authentication

components/camel-http/src/main/java/org/apache/camel/component/http/HttpProducer.java
In case of spring boot binding the raw http path is appended to the bridged endpoint
=> CAMEL-22282: Removes CamelHttpPath header from http producer on bridge

parent/pom.xml
(cherry pick of logback upgrade -> 1.5.18 from main -> camel-4.10.x branch)
Ran mvn -DskipTests clean install
Bumps `logback-version` from 1.5.17 to 1.5.18.
Updates `ch.qos.logback:logback-core` from 1.5.17 to 1.5.18
- [Release notes](https://github.com/qos-ch/logback/releases)
- [Commits](https://github.com/qos-ch/logback/compare/v_1.5.17...v_1.5.18)
Updates `ch.qos.logback:logback-classic` from 1.5.17 to 1.5.18
- [Release notes](https://github.com/qos-ch/logback/releases)
- [Commits](https://github.com/qos-ch/logback/compare/v_1.5.17...v_1.5.18)
---
updated-dependencies:
- dependency-name: ch.qos.logback:logback-core dependency-type: direct:production update-type: version-update:semver-patch
- dependency-name: ch.qos.logback:logback-classic dependency-type: direct:production …
=> chore(deps): Bump logback-version from 1.5.17 to 1.5.18 (#17495)

components/camel-zipfile/pom.xml, components/camel-zipfile/src/main/java/org/apache/camel/dataformat/zipfile/ZipFileDataFormat.java, components/camel-zipfile/src/main/java/org/apache/camel/dataformat/zipfile/ZipIterator.java, components/camel-zipfile/src/test/java/org/apache/camel/processor/aggregate/zipfile/ZipSplitAggregateTransactedStreamingIssueTest.java
Ticket: https://issues.apache.org/jira/browse/CAMEL-22216
It is about the camel-zipfile component. The changes which have been added for this ticket: https://issues.apache.org/jira/browse/CAMEL-22147 are causing this problem.
A transacted route with ZipSplitter and Aggregation Strategy in streaming mode does not aggregate the last zip file entry.
Changes: Using the apache.commons.compress for the Zip handling, change the availableDataInCurrentEntry to check if the currantEntry is not null, Re-enable the test ZipSplitAggregateTransactedStreamingIssueTest in stream caching mode, To have unified ZIP handling align ZipFileDataFormat using apache.commons.compress
=> CAMEL-22216: Fix ZipIterator using apache.commons.compress

parent/pom.xml
Align versions with spring-boot 3.5.5 (camel-4.14.x branch)- the only version spring-* version I could find that needed upgrading was spring-security (6.5.2 -> 6.5.3)
=> Align spring-security with spring-boot 3.5.5

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/update/UpdateList.java
The code didn't handle camel-upgrade-recipes micro versions, ex. 4.14.0.1
=> Handle Micro versions in camel jbang update list

components/camel-openapi-java/src/main/java/org/apache/camel/openapi/RestOpenApiSupport.java, components/camel-openapi-java/src/test/java/org/apache/camel/openapi/RestOpenApiReaderTest.java
Backport of https://github.com/apache/camel/commit/71edff010d98c9ad4425d50700bcfc314befa9c8
=> [4.14.x] CAMEL-22408: OpenAPI Description showing wrong allowable dates depending on system timezone

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportSpringBoot.java
Apply camel.springboot only if source (4.4.0) is greater than the actual version (not lower)
=> Fix export condition for Camel Spring Boot

docs/user-manual/modules/ROOT/pages/_migration-app-note.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_1.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_10.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_11.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_12.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_13.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_14.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_15.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_2.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_3.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_4.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_5.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_6.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_7.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_8.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_9.adoc, docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide.adoc
Fix for the following documentation build error:
```
[build:antora  ] [build:antora-perf] (node:189) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
--
  |   |   | [build:antora  ] [build:antora-perf] (Use `node --trace-deprecation ...` to show where the warning was created)
  |   |   | [build:antora  ] [build:antora-perf] [08:20:19.781] ERROR (asciidoctor): level 0 sections can only be used when doctype is book
  |   |   | [build:antora  ] [build:antora-perf]     file: docs/user-manual/modules/ROOT/pages/migration-app-note.adoc:1
  |   |   | [build:antora  ] [build:antora-perf]     source: https://github.com/apache/camel.git (branch: main \| start path: docs/user-manual)
  |   |   | [build:antora  ] [build:antora-perf]     stack:
  |   |   | [build:antora  ] …
```
=> Prefix note file with underscore to prevent standalone publication

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/RuntimeType.java, parent/pom.xml
Alignment to spring-boot 3.4.10 for the camel-4.10.x branch
=> Align spring-*, jetty, http-* versions to the versions used in spring-boot 3.4.10

etc/scripts/regen.sh
This script is used during github check. When the first maven execution fails, it continues to the second. It is convenient to stop immediately instead.
Additionally with this PR avoid the developer to download the build log file in case of error. He can now have a sneak peak at the workflow log to understand what was wrong.
=> fix(ci): exit on error 
