components/camel-ai/camel-langchain-chat/src/main/docs/langchain-chat-component.adoc
docs/components/modules/ROOT/nav.adoc
docs/components/modules/ROOT/pages/langchain-chat-component.adoc

CAMEL-20632- Fix documentation for Camel Langchain4j chat component

---

catalog/camel-catalog/src/main/java/org/apache/camel/catalog/CamelCatalog.java

Fixup fdf997b5938b76b5b4bd893f9bd76ae7d8c42773
Adding some missing case statements

Fixup catalog: make catalog more type safe

---

components/camel-master/pom.xml
components/camel-master/src/test/java/org/apache/camel/component/master/MasterComponentTest.java

Issue link - https://issues.apache.org/jira/browse/CAMEL-19535

CAMEL-19535 - camel-master: replace Thread.sleep in tests.

---

components/camel-aws/camel-aws-bedrock/src/main/java/org/apache/camel/component/aws2/bedrock/agent/BedrockAgentConstants.java
components/camel-aws/camel-aws-bedrock/src/main/java/org/apache/camel/component/aws2/bedrock/agent/BedrockAgentIngestionJobConsumer.java
components/camel-aws/camel-aws-bedrock/src/main/java/org/apache/camel/component/aws2/bedrock/agent/BedrockAgentProducer.java

CAMEL-20641 - Camel-AWS-Bedrock-Agent: Add information about failures in ingestion job as header

---

components/camel-platform-http/src/main/java/org/apache/camel/component/platform/http/PlatformHttpConsumer.java
components/camel-platform-http/src/main/java/org/apache/camel/component/platform/http/PlatformHttpEndpoint.java
components/camel-rest-openapi/src/main/java/org/apache/camel/component/rest/openapi/DefaultRestOpenapiProcessorStrategy.java
components/camel-rest-openapi/src/main/java/org/apache/camel/component/rest/openapi/RestOpenApiEndpoint.java
components/camel-rest-openapi/src/main/java/org/apache/camel/component/rest/openapi/RestOpenApiProcessor.java
components/camel-rest-openapi/src/main/java/org/apache/camel/component/rest/openapi/RestOpenapiProcessorStrategy.java
core/camel-support/src/main/java/org/apache/camel/support/processor/RestBindingAdvice.java

rest-dsl - binding part 4

---

components/camel-aws/camel-aws-bedrock/src/main/java/org/apache/camel/component/aws2/bedrock/BedrockModels.java
components/camel-aws/camel-aws-bedrock/src/main/java/org/apache/camel/component/aws2/bedrock/runtime/BedrockProducer.java
components/camel-aws/camel-aws-bedrock/src/test/java/org/apache/camel/component/aws2/bedrock/runtime/integration/BedrockProducerIT.java

CAMEL-20562 - Camel-AWS-Bedrock: Support Mistral AI models - Mistral 8x7B Instruct

---

components/camel-sjms2/src/test/java/org/apache/camel/component/sjms2/consumer/InOnlyTopicDurableConsumerTest.java

Issue link - https://issues.apache.org/jira/browse/CAMEL-19543

CAMEL-19543 - camel-sjms2: replace Thread.sleep in tests.

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogDoc.java
dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

Upgrade Camel Kamelets to version 4.5.0

---

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/AS2MessageDispositionNotificationEntity.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/util/DispositionNotificationContentUtils.java
components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/entity/EntityParserTest.java

Backport of https://github.com/apache/camel/pull/13708

Camel-18017: mdn content corruption

---

test-infra/camel-test-infra-aws-v2/src/test/resources/org/apache/camel/test/infra/aws2/services/container.properties

Upgrade Localstack container image to version 3.3.0

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorSeekIssueIT.java

Camel-Kafka: Added missing imports in integration test

---

test-infra/camel-test-infra-hashicorp-vault/src/test/resources/org/apache/camel/test/infra/hashicorp/vault/services/container.properties

Camel-Hashicorp-Vault: Use latest Vault container image version 1.16.1

---

test-infra/camel-test-infra-nats/src/test/resources/org/apache/camel/test/infra/nats/services/container.properties

Upgrade Nats container image version to 2.10.14

---

components/camel-milvus/src/main/java/org/apache/camel/component/milvus/MilvusAction.java
components/camel-milvus/src/main/java/org/apache/camel/component/milvus/MilvusProducer.java
components/camel-milvus/src/test/java/org/apache/camel/component/milvus/it/MilvusComponentIT.java

CAMEL-20574 - Camel-Milvus: Add more producer operation - Query

---

parent/pom.xml

Downgrade Milvus SDK to 2.3.4

---

components/camel-validator/src/main/java/org/apache/camel/component/validator/DefaultValidatorResourceResolverFactory.java
parent/pom.xml

upgrade spring 6.1.6

---

catalog/camel-report-maven-plugin/pom.xml
catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/RouteCoverageMojo.java
catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/ValidateMojo.java
docs/user-manual/modules/ROOT/pages/camel-report-maven-plugin.adoc

Add properties to skip execution of the validate and route coverage mojos

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/Hawtio.java

camel-jbang - Upgrade to hawtio 4.0.0

---

core/camel-base/src/generated/java/org/apache/camel/converter/CamelBaseBulkConverterLoader.java
core/camel-base/src/main/java/org/apache/camel/converter/DateTimeConverter.java
core/camel-base/src/main/java/org/apache/camel/impl/converter/CoreTypeConverterRegistry.java
core/camel-base/src/main/java/org/apache/camel/impl/converter/EnumTypeConverter.java
core/camel-core/src/test/java/org/apache/camel/converter/DateTimeConverterTest.java

CAMEL-20673: camel-core - Add type converter for string to TimeUnit

---

parent/pom.xml

Upgrade kubernetes client 6.12.0 and remove unused version

---

parent/pom.xml

Upgrade debezium 2.6.1

---

test-infra/camel-test-infra-infinispan/src/test/resources/org/apache/camel/test/infra/infinispan/services/container.properties

Upgrade Infinispan Container Image to version 15.0.1.Final

---

test-infra/camel-test-infra-infinispan/src/test/resources/org/apache/camel/test/infra/infinispan/services/container.properties

Upgrade Infinispan container image to version 15.0.2.Final

---

dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/OutputAwareFromDefinitionDeserializer.java

fixed 2 typos in a null check

---

catalog/camel-route-parser/src/main/java/org/apache/camel/parser/RouteBuilderParser.java

Please review this PR. It's my first contribution.
- [ x ] I checked that the commit is targeting the correct branch (note that Camel 3 uses `camel-3.x`, whereas Camel 4 uses the `main` branch)
- [ x ] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).
- [ x ] I checked that each commit in the pull request has a meaningful subject line and body.
not required for this type of change I believe
- I have run the unit tests of the module locally and faced no extra failing test.
Is it normal that some unit tests are failing?

CAMEL-20206: split overly complex method in RouteBuilderParser

---

components/camel-netty/src/main/java/org/apache/camel/component/netty/NettyServerBootstrapConfiguration.java

CAMEL-20710 Implemented Objects.equals() for comparison of strings

CAMEL-20710 Implemented Objects.equals() for comparison of strings

---

core/camel-console/src/main/java/org/apache/camel/impl/console/RouteDevConsole.java
core/camel-main/src/main/java/org/apache/camel/main/BaseMainSupport.java
docs/user-manual/modules/ROOT/pages/camel-jbang.adoc
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
dsl/camel-jbang/camel-jbang-core/src/main/resources/spring-boot-logback.xml

camel-jbang - run with spring-boot or quarkus

---

components/camel-quickfix/src/test/java/org/apache/camel/component/quickfixj/examples/routing/FixMessageRouter.java

CAMEL-20716 Throw created exception in FixMessageRouter

CAMEL-20716 Throw created exception in FixMessageRouter

---

test-infra/camel-test-infra-milvus/src/test/resources/org/apache/camel/test/infra/milvus/services/container.properties

Upgrade Milvus container image to version v2.4.0

---

dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/BindTest.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationRunTest.java
parent/pom.xml

CAMEL-20720: Update Camel K plugin command to CK 2.3.0

---

catalog/camel-route-parser/src/main/java/org/apache/camel/parser/XmlRouteParser.java
catalog/camel-route-parser/src/main/java/org/apache/camel/parser/helper/CamelJavaRestDslParserHelper.java
components/camel-ai/camel-langchain4j-chat/pom.xml
components/camel-ai/camel-langchain4j-embeddings/pom.xml
components/camel-milvus/pom.xml
components/camel-pinecone/pom.xml
components/camel-qdrant/pom.xml
parent/pom.xml

Rename Langchain4j property placeholder to follow the traditional syntax

---

components/camel-milvus/src/main/docs/milvus-component.adoc

CAMEL-20575 - Camel-Milvus: Improve documentation

---

core/camel-core-processor/src/main/java/org/apache/camel/processor/ClaimCheckProcessor.java

else-if blocks have been converted to switch

ClaimCheckProcessor.java cleanup

---

components/camel-aws/camel-aws-xray/pom.xml

fixes https://issues.apache.org/jira/browse/CAMEL-20734
Excluding a dependency, which is brought transitively with a newer version.

Exclude ws-java-sdk-core in camel-aws-xray to avoid conflict

---

components/camel-file/src/main/java/org/apache/camel/component/file/FileConsumer.java
components/camel-file/src/main/java/org/apache/camel/component/file/FileEndpoint.java
components/camel-file/src/main/java/org/apache/camel/component/file/GenericFile.java

- break large and complex methods
- fixed logging

(chores) camel-file: code cleanup

---

components/camel-rest-openapi/pom.xml
parent/pom.xml

Wiremock303

---

catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/RouteCoverageMojo.java
catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/ValidateMojo.java

- break large and complex methods
- fixed logging

(chores) camel-report-maven-plugin: code cleanup

---

components/camel-salesforce/pom.xml

Revert "Updated pom to skip build on Windows running on ARM"

---

parent/pom.xml

Upgrade parquet 1.14.0

---

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_7.adoc

debugger is created twice

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd
components/camel-pinecone/src/main/java/org/apache/camel/component/pinecone/PineconeVectorDbConfiguration.java

Camel-Pinecone: Fixed import and type of the Pinecone client

---

components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/AvailablePortFinder.java
components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/CamelRouteCoverageDumper.java
components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/ExcludingPackageScanClassResolver.java
components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/CamelTestSupport.java
components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/EndpointUriFactoryTestSupport.java
components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/TestSupport.java
components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/ThrottlingExecutor.java
components/camel-test/camel-test-junit5/src/test/java/org/apache/camel/test/junit5/CamelTestSupportTest.java
components/camel-test/camel-test-junit5/src/test/java/org/apache/camel/test/junit5/patterns/DebugJUnit5Test.java
components/camel-test/camel-test-junit5/src/test/java/org/apache/camel/test/junit5/patterns/DebugNoLazyTypeConverterTest.java
components/camel-test/camel-test-junit5/src/test/java/org/apache/camel/test/junit5/patterns/DebugTest.java
components/camel-test/camel-test-main-junit5/src/main/java/org/apache/camel/test/main/junit5/CamelMainTest.java
components/camel-test/camel-test-main-junit5/src/main/java/org/apache/camel/test/main/junit5/CamelMainTestSupport.java
components/camel-test/camel-test-spring-junit5/src/main/java/org/apache/camel/test/spring/junit5/CamelAnnotationsHandler.java
components/camel-test/camel-test-spring-junit5/src/main/java/org/apache/camel/test/spring/junit5/CamelSpringBootExecutionListener.java
components/camel-test/camel-test-spring-junit5/src/main/java/org/apache/camel/test/spring/junit5/CamelSpringTestContextLoader.java
components/camel-test/camel-test-spring-junit5/src/main/java/org/apache/camel/test/spring/junit5/CamelSpringTestContextLoaderTestExecutionListener.java
components/camel-test/camel-test-spring-junit5/src/main/java/org/apache/camel/test/spring/junit5/CamelSpringTestHelper.java
components/camel-test/camel-test-spring-junit5/src/main/java/org/apache/camel/test/spring/junit5/CamelSpringTestSupport.java
components/camel-test/camel-test-spring-junit5/src/main/java/org/apache/camel/test/spring/junit5/DisableJmx.java
components/camel-test/camel-test-spring-junit5/src/main/java/org/apache/camel/test/spring/junit5/StopWatchTestExecutionListener.java
components/camel-test/camel-test-spring-junit5/src/test/java/org/apache/camel/test/issues/AdviceWithOnExceptionMultipleIssueTest.java
components/camel-test/camel-test-spring-junit5/src/test/java/org/apache/camel/test/issues/AdviceWithOnExceptionTransactedTest.java
components/camel-test/camel-test-spring-junit5/src/test/java/org/apache/camel/test/patterns/DebugSpringTest.java
components/camel-test/camel-test-spring-junit5/src/test/java/org/apache/camel/test/spring/CamelSpringProvidesBreakpointTest.java
components/camel-test/camel-test-spring-junit5/src/test/java/org/apache/camel/test/spring/CamelSpringTestSupportActiveProfileTest.java
components/camel-test/camel-test-spring-junit5/src/test/java/org/apache/camel/test/spring/CamelSpringTestSupportTest.java
components/camel-test/camel-test-spring-junit5/src/test/java/org/apache/camel/test/spring/SpringTestExecutionListenerSorterTest.java

- fixed typos
- minor documentation cleanups

(chores) camel-test: multiple fixes and cleanups

---

catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/ValidateMojo.java

Please review this PR. It's my second contribution.

CAMEL-20206: split overly complex method in ValidateMojo

---

core/camel-core/src/test/java/org/apache/camel/support/jsse/FilterParametersTest.java
core/camel-core/src/test/java/org/apache/camel/support/jsse/KeyManagersParametersTest.java
core/camel-core/src/test/java/org/apache/camel/support/jsse/KeyStoreParametersTest.java
core/camel-core/src/test/java/org/apache/camel/support/jsse/SSLContextParametersTest.java
core/camel-core/src/test/java/org/apache/camel/support/jsse/SecureRandomParametersTest.java
core/camel-core/src/test/java/org/apache/camel/support/jsse/TrustManagersParametersTest.java
core/camel-core/src/test/resources/org/apache/camel/support/jsse/test.properties

camel-core - Isolate some tests that are flaky on CI

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogDoc.java
dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

Upgrade Camel-Kamelets for Camel-Jbang to version 4.6.0

---

components/camel-csv/src/test/java/org/apache/camel/dataformat/csv/CsvDataFormatCustomRecordConverterTest.java
components/camel-csv/src/test/java/org/apache/camel/dataformat/csv/CsvMarshalTest.java
components/camel-csv/src/test/java/org/apache/camel/dataformat/csv/CsvUnmarshalStreamTest.java
components/camel-csv/src/test/java/org/apache/camel/dataformat/csv/TestUtils.java

(chores) camel-csv: test code cleanups

---

components/camel-jpa/pom.xml
components/camel-jpa/src/main/docs/jpa-component.adoc
parent/pom.xml

camel-jpa - Cleanup

---

components/camel-mail/src/test/java/org/apache/camel/component/mail/MailDisconnectTest.java

Also wait more time before kicking off the test

(chores) camel-mail: separate test setup from execution

---

components/camel-hashicorp-vault/src/test/java/org/apache/camel/component/hashicorp/vault/integration/HashicorpVaultPropertiesSourceNoEnvTestIT.java
components/camel-hashicorp-vault/src/test/java/org/apache/camel/component/hashicorp/vault/integration/HashicorpVaultPropertiesSourceTestIT.java

CAMEL-20775 - Added some tests for Hashicorp Vault and multiple engines

---

.github/dependabot.yml

Jandex should be managed manually

---

components/camel-jpa/pom.xml
components/camel-jpa/src/main/docs/jpa-component.adoc
parent/pom.xml

This reverts commit e2783234e32535d5f06e30c0c48232385e773fe0.
Upgrading JPA needs additional work to make the build and tests stable.

CAMEL-20792: Revert "camel-jpa - Cleanup (#14182)"

---

test-infra/camel-test-infra-infinispan/src/test/resources/org/apache/camel/test/infra/infinispan/services/container.properties

Use latest Infinispan container image for test-infra module, 15.0.4.Final

---

components/camel-cxf/camel-cxf-spring-soap/src/test/java/org/apache/camel/component/cxf/CXFWsdlOnlyTest.java
components/camel-cxf/camel-cxf-spring-soap/src/test/java/org/apache/camel/component/cxf/CxfNonWrapperTest.java
components/camel-infinispan/camel-infinispan-common/src/test/java/org/apache/camel/component/infinispan/InfinispanConsumerTestSupport.java
components/camel-infinispan/camel-infinispan-common/src/test/java/org/apache/camel/component/infinispan/InfinispanIdempotentRepositoryTestSupport.java
components/camel-infinispan/camel-infinispan-embedded/src/test/java/org/apache/camel/component/infinispan/embedded/InfinispanEmbeddedConsumerTest.java
components/camel-infinispan/camel-infinispan-embedded/src/test/java/org/apache/camel/component/infinispan/embedded/InfinispanEmbeddedCustomListenerTest.java
components/camel-infinispan/camel-infinispan-embedded/src/test/java/org/apache/camel/component/infinispan/embedded/InfinispanEmbeddedIdempotentRepositoryTest.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteConsumerIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteCustomListenerIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteIdempotentRepositoryIT.java
components/camel-mail/src/test/java/org/apache/camel/component/mail/MailComponentTest.java
components/camel-mail/src/test/java/org/apache/camel/component/mail/MailMessageTest.java
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzEndpointConfigureTest.java
components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/CamelTestSupport.java
components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/util/CamelContextTestHelper.java
components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/util/ExtensionHelper.java

Preparing the ground for bigger cleanups by moving and cleaning up things a bit

CAMEL-20785: more cleanup work to the CamelTestSupport class

---

parent/pom.xml

This reverts commit 60ad51f7d69c3d7f6ccf7443e436500da61ba658.

CAMEL-20800: Revert Gson upgrade

---

Jenkinsfile

Cleanup before checkout to fix errors on some CI nodes

CI: Jenkins fixes

---

test-infra/camel-test-infra-hashicorp-vault/src/test/resources/org/apache/camel/test/infra/hashicorp/vault/services/container.properties

Upgrade Vault container image to version 1.16.2

---

test-infra/camel-test-infra-nats/src/test/resources/org/apache/camel/test/infra/nats/services/container.properties

Nats 2.10.16

---

.github/workflows/pr-comment.yml
.gitmodules

(chores) ci: fix vulnerability by using directly referenced action

---

components/camel-arangodb/src/main/java/org/apache/camel/component/arangodb/ArangoDbEndpoint.java
components/camel-asterisk/src/main/java/org/apache/camel/component/asterisk/AsteriskEndpoint.java
components/camel-debezium/camel-debezium-db2/src/main/java/org/apache/camel/component/debezium/DebeziumDb2Endpoint.java
components/camel-debezium/camel-debezium-mongodb/src/main/java/org/apache/camel/component/debezium/DebeziumMongodbEndpoint.java
components/camel-debezium/camel-debezium-mysql/src/main/java/org/apache/camel/component/debezium/DebeziumMySqlEndpoint.java
components/camel-debezium/camel-debezium-oracle/src/main/java/org/apache/camel/component/debezium/DebeziumOracleEndpoint.java
components/camel-debezium/camel-debezium-postgres/src/main/java/org/apache/camel/component/debezium/DebeziumPostgresEndpoint.java
components/camel-debezium/camel-debezium-sqlserver/src/main/java/org/apache/camel/component/debezium/DebeziumSqlserverEndpoint.java
components/camel-infinispan/camel-infinispan/src/main/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteEndpoint.java
components/camel-irc/src/main/java/org/apache/camel/component/irc/IrcEndpoint.java
components/camel-mail/src/main/java/org/apache/camel/component/mail/MailEndpoint.java
components/camel-milvus/src/main/java/org/apache/camel/component/milvus/MilvusEndpoint.java
components/camel-paho/src/main/java/org/apache/camel/component/paho/PahoEndpoint.java
components/camel-sap-netweaver/src/main/java/org/apache/camel/component/sap/netweaver/NetWeaverEndpoint.java
components/camel-smb/src/main/java/org/apache/camel/component/smb/SmbEndpoint.java
components/camel-ssh/src/main/java/org/apache/camel/component/ssh/SshEndpoint.java
components/camel-twilio/src/main/java/org/apache/camel/component/twilio/TwilioEndpoint.java
components/camel-workday/src/main/java/org/apache/camel/component/workday/WorkdayEndpoint.java
components/camel-zeebe/src/main/java/org/apache/camel/component/zeebe/ZeebeEndpoint.java
test-infra/camel-test-infra-opensearch/src/test/resources/org/apache/camel/test/infra/opensearch/services/container.properties

Opensearch 2.14.0

---

parent/pom.xml
test-infra/camel-test-infra-pulsar/src/test/resources/org/apache/camel/test/infra/pulsar/services/container.properties

Upgrade apache pulsar 3.2.3

---

components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/CamelOpenTelemetryTestSupport.java

Applies the same approach as 4b747b8367cadb317bc4cd3aad5827b2e425e10c

Fix camel-opentelemetry test

---

.github/actions/component-test/action.yaml
.github/actions/incremental-build/action.yaml
.github/actions/quick-test/action.yaml

it will avoid this message:
Deprecation notice: v1, v2, and v3 of the artifact actions The following artifacts were uploaded using a version of actions/upload-artifact that is scheduled for deprecation: "build.log", "tests.log".
Please update your workflow to use v4 of the artifact actions. Learn more:
https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/
It wasn't updated automatically by dependabot because it is inside reusable actions.
It doesn't seem that this action are used in matrix jobs that can upload several times the same artifact so we should be fine just by upgrading the number

chore: Use actions/upload-artifact v4

---

.github/actions/component-test/action.yaml
.github/actions/incremental-build/action.yaml

provided specific suffix for some of the paths but it is only for the name that we need it
follow-up to https://github.com/apache/camel/pull/14340

chore: adjust uploaded artifact configuration

---

components/camel-micrometer-prometheus/pom.xml

given that there are no specific unit tests at all

chore: remove unused test dependencies in Micrometer Prometheus

---

components/camel-platform-http-main/pom.xml

chore: Remove unused test dependencies in Platform Http main

---

components/camel-knative/camel-knative-api/pom.xml
components/camel-knative/camel-knative-component/pom.xml

chore: Remove unused test dependencies in Knative

---

components/camel-joor/pom.xml

note: I found no trace of hamcrest dependency neither but the build is failing when removed, so removing only assertj for which it is causing no problem

chore: Remove unused test dependencies in Joor

---

components/camel-jgroups/pom.xml

chore: Remove unused test dependencies in Jgroup

---

components/camel-hashicorp-vault/pom.xml

chore: remove unused test dependencies in Hashicorp vault

---

components/camel-google/camel-google-functions/pom.xml
components/camel-google/camel-google-secret-manager/pom.xml
components/camel-google/camel-google-storage/pom.xml

chore: remove unused test dependencies in google

---

components/camel-azure/camel-azure-files/pom.xml
components/camel-azure/camel-azure-key-vault/pom.xml
components/camel-azure/camel-azure-servicebus/pom.xml
components/camel-azure/camel-azure-storage-blob/pom.xml

chore: remove unused test dependencies in Azure

---

components/camel-aws/camel-aws-bedrock/pom.xml
components/camel-aws/camel-aws-cloudtrail/pom.xml
components/camel-aws/camel-aws2-ec2/pom.xml
components/camel-aws/camel-aws2-eks/pom.xml
components/camel-aws/camel-aws2-iam/pom.xml
components/camel-aws/camel-aws2-msk/pom.xml
components/camel-aws/camel-aws2-ses/pom.xml
components/camel-aws/camel-aws2-sns/pom.xml

chore: remove unused test dependencies in Aws

---

components/camel-atom/pom.xml

chore: remove unused test dependencies in Atom

---

components/camel-jq/pom.xml

chore: remove unused test dependencies in jq

---

components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/CamelTestSupport.java
components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/ContextManagerFactory.java

This is to make CEQ's life easier with these refactorings.

CAMEL-20785: provide a way to create context managers when needed

---

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc

Fix documentation for Docker image for Camel JBang using run target

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerFullIT.java

changes to address flakiness of KafkaConsumerFullIT test:
- unique topic & route names
- ensure topic is actually deleted in `@AfterEach` 
These changes are intended to prevent clashes between different tests producing & consuming from the same topic

CAMEL-19358 - changes to address flakiness of KafkaConsumerFullIT test

---

.github/dependabot.yml

- used weekly interval as it is less important than core Camel
- wondering if ti can be done without synchronization with other parts of the Camel website

Automate version update of documentation

---

components/camel-plc4x/src/main/docs/plc4x-component.adoc

doc: Improve PLC4X documentation by adding most common supported

---

components/camel-openapi-validator/src/test/java/org/apache/camel/component/rest/openapi/validator/client/OpenApiRestClientRequestValidatorTest.java
components/camel-rest-openapi/src/main/java/org/apache/camel/component/rest/openapi/DefaultRestOpenapiProcessorStrategy.java
components/camel-rest-openapi/src/main/java/org/apache/camel/component/rest/openapi/RestOpenapiProcessorStrategy.java
components/camel-smb/src/main/java/org/apache/camel/component/smb/SmbConfiguration.java
components/camel-smb/src/main/java/org/apache/camel/component/smb/SmbConsumer.java
components/pom.xml
core/camel-support/src/main/java/org/apache/camel/support/processor/RestBindingAdvice.java

Added Camel-Openapi-validator to kit

---

docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_18.adoc

Migration guide updates, packages changes in camel cxf 3.18

Add package updates for CXF split happened in 3.18

---

core/camel-api/src/main/java/org/apache/camel/spi/BacklogTracerEventMessage.java
core/camel-api/src/main/java/org/apache/camel/spi/EndpointServiceLocation.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/debugger/DefaultBacklogTracerEventMessage.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/CamelInternalProcessor.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Debug.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/CamelSendAction.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/CamelStubAction.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/CamelTraceAction.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/MessageTableHelper.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/TransformMessageAction.java

Add endpoint service location to backlog tracing

---

components/camel-ai/camel-langchain4j-chat/src/main/java/org/apache/camel/component/langchain4j/chat/LangChain4jChatProducer.java

fixes https://issues.apache.org/jira/browse/CAMEL-20863

camel-langchain4j-chat -  NPE if only producer is used

---

core/camel-core/src/test/java/org/apache/camel/support/cache/SimpleLRUCacheTest.java
core/camel-support/src/main/java/org/apache/camel/support/cache/SimpleLRUCache.java

Fix for https://issues.apache.org/jira/browse/CAMEL-20850 in Camel 4.4
When the queue of changes is full, some entries can be evicted while the cache is not, which is not expected.
* Compress the changes by removing duplicates before the eviction
* Add a minimum size for the queue of changes

CAMEL-20850: camel-core - compress changes in SimpleLRUCache

---

docs/.gitignore

as recommended in official yarn documentation
https://yarnpkg.com/getting-started/qa#which-files-should-be-gitignored
> .yarn/install-state.gz is an optimization file that you shouldn't ever have to commit. It simply stores the exact state of your project so that the next commands can boot without having to resolve your workspaces all over again.
it will also allows to have dependabot PRs workign out of the box

chore: do not commit the install-state.gz file

---

components/camel-smb/src/main/java/org/apache/camel/component/smb/SmbConsumer.java

Cherry pick the fix for CAMEL-20823 over to 4.4.x branch, mentioned on zulip today by David Zingg

CAMEL-20823 Filter out folders when listing files

---

test-infra/camel-test-infra-couchbase/src/test/java/org/apache/camel/test/infra/couchbase/services/CouchbaseLocalContainerService.java

it was to point to an issue mentioning to take care when upgrading the container version; The container version has already been upgraded and is now specified in another file (container.properties)

CAMEL-19228 - Remove leftover comment

---

core/camel-util/src/main/java/org/apache/camel/util/SensitiveUtils.java

Regen: fix SensitiveUtils

---

components/camel-protobuf/pom.xml
parent/pom.xml

Upgrade protobuf 4.27.1

---

components/camel-disruptor/src/main/java/org/apache/camel/component/disruptor/DisruptorProducer.java
components/camel-seda/src/main/java/org/apache/camel/component/seda/SedaProducer.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/WireTapProcessor.java
core/camel-util/src/main/java/org/apache/camel/util/SensitiveUtils.java
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_7.adoc

seda stream cache copy

---

core/camel-core/src/test/java/org/apache/camel/processor/OnCompletionModeBeforeConsumerExceptionSuppressedTest.java

Swap 2 arguments so they are in the correct order: expected value,

---

test-infra/camel-test-infra-mongodb/src/test/resources/org/apache/camel/test/infra/mongodb/services/container.properties

Update MongoDB container used for IT tests to 7.0.11

---

components/camel-iec60870/src/test/java/org/apache/camel/component/iec60870/ConnectionTest.java

this one seems not relevant. Played 20 times locally and no issue.

CAMEL-19523 - remove Thread.sleep in iec60870 test

---

components/camel-tarfile/pom.xml
components/camel-tarfile/src/test/java/org/apache/camel/processor/aggregate/tarfile/AggregationStrategyWithFilenameHeaderTest.java
components/camel-tarfile/src/test/java/org/apache/camel/processor/aggregate/tarfile/AggregationStrategyWithPreservationTest.java
components/camel-tarfile/src/test/java/org/apache/camel/processor/aggregate/tarfile/TarAggregationStrategyTest.java

Gained almost 1.5 seconds during execution of tests

CAMEL-19546 - remove Thread.sleep in Tarfile component test

---

components/camel-tarfile/src/main/java/org/apache/camel/dataformat/tarfile/TarFileDataFormat.java
components/camel-tarfile/src/main/java/org/apache/camel/dataformat/tarfile/TarIterator.java
components/camel-tarfile/src/main/java/org/apache/camel/processor/aggregate/tarfile/TarAggregationStrategy.java
components/camel-tarfile/src/test/java/org/apache/camel/dataformat/tarfile/TarFileDataFormatTest.java

chore: remove usage of deprecated methods in tarfile component

---

components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirCapabilitiesIT.java
components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirConfigurationIT.java
components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirCreateIT.java
components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirCustomClientConfigurationIT.java
components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirDeleteIT.java
components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirExtraParametersIT.java
components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirHistoryIT.java
components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirLoadPageIT.java
components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirMetaIT.java
components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirOperationIT.java
components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirPatchIT.java
components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirReadIT.java
components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirSearchIT.java
components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirSimpleIT.java
components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirTransactionIT.java
components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirUpdateIT.java
components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirValidateIT.java
components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/Hl7v2PatientToFhirPatientIT.java
test-infra/camel-test-infra-fhir/src/test/java/org/apache/camel/test/infra/fhir/services/FhirLocalContainerService.java
test-infra/camel-test-infra-fhir/src/test/resources/org/apache/camel/test/infra/fhir/services/container.properties

- upgrade container version, locally gained 20 seconds on 2 minutes test execution
- provide a retry startup attempt to improve stability

CAMEL-19659 - reactivate FHIR Integration tests

---

docs/pom.xml

it was already skipped for yarn gulp, yarn install was added recently, it needs to be skipped similarly

chore: do not call yarn install for doc on unsupported platforms

---

components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/RemoteFilePollingConsumerPollStrategy.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/LimitedPollingConsumerPollStrategy.java
core/camel-support/src/main/java/org/apache/camel/support/DefaultPollingConsumerPollStrategy.java
core/camel-support/src/main/java/org/apache/camel/support/ScheduledPollConsumer.java
core/camel-support/src/main/java/org/apache/camel/support/ScheduledPollEndpoint.java

CAMEL-20881: Only create DefaultPollingConsumerPollStrategy when needed.

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/AbstractGenerateConfigurerMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/ModelWriterGeneratorMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/ModelXmlParserGeneratorMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/TypeConverterLoaderGeneratorMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/UpdateSensitizeHelper.java

it won't gain a lot but they are no brainer

20884 follow sonar recommendation to improve performance of camel-package-maven-plugin

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/others/kotlin-api.json
catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/others/kotlin-dsl.json
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_7.adoc
dsl/camel-kotlin-api/pom.xml
dsl/camel-kotlin-api/src/generated/resources/META-INF/services/org/apache/camel/other.properties
dsl/camel-kotlin-api/src/generated/resources/kotlin-api.json
dsl/camel-kotlin-api/src/main/docs/kotlin-api.adoc
dsl/camel-kotlin-dsl/pom.xml
dsl/camel-kotlin-dsl/src/generated/resources/META-INF/services/org/apache/camel/other.properties
dsl/camel-kotlin-dsl/src/generated/resources/kotlin-dsl.json
dsl/camel-kotlin-dsl/src/main/docs/kotlin-dsl.adoc

CAMEL-20885 - deprecate Kotlin

---

core/camel-support/src/main/java/org/apache/camel/support/RouteVariableRepository.java
core/camel-support/src/main/java/org/apache/camel/support/scan/PackageScanHelper.java

it improves performance in case there are a lot of beans and routes registered

Iterate over the "entrySet" instead of the "keySet"

---

components/camel-azure/camel-azure-storage-datalake/src/test/java/org/apache/camel/component/azure/storage/datalake/component/DataLakeComponentTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsDeliveryDelayTest.java
components/camel-platform-http-vertx/src/test/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpSessionTest.java
core/camel-support/src/test/java/org/apache/camel/support/RestConsumerContextPathMatcherTest.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/KubeCommandMainTest.java

chore: Swap assertion test argument to be in correct order: expected

---

core/camel-api/src/main/java/org/apache/camel/Message.java

Regen to fix main branch PR

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/AbstractGeneratorMojo.java

- use a single RuntimeInstance of Velocity given that it is initialized always with the same parameters It was retrieved at least 2 times per component.
- use a cache to retrieve Velocity Template. It was retrieved at least 2 times per component. So now there is only 15 calls.
- Initialize the VelocityContext with the map of parameter in the constructor instead of iterating on each element of the map and adding them one by one
it was using around 10% of the time spent in org.apache.camel.** classes during a `mvn clean install -D quickly`. Locally went from around 10'05" to around 9'20" to execute previously mentioned command

CAMEL-20884 - improve Velocity usage in Camel package Maven plugin

---

components/camel-ai/camel-djl/pom.xml
parent/pom.xml

Since DJL 0.14.0 the engines can automatically resolve the appropriate native library for the platform and no need for including the -native-auto libraries in the Camel component.
https://docs.djl.ai/engines/pytorch/pytorch-engine/index.html#installation

camel-djl - Remove discontinued -native-auto dependencies

---

components/camel-knative/camel-knative-component/src/main/java/org/apache/camel/component/knative/KnativeEndpoint.java
components/camel-knative/camel-knative-component/src/main/java/org/apache/camel/component/knative/ce/AbstractCloudEventProcessor.java
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/Bind.java
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationRun.java
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/KubernetesHelper.java
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/TraitHelper.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/BindTest.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationRunTest.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/KubeCommandMainTest.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/resources/org/apache/camel/dsl/jbang/core/commands/k/integration.yaml
dsl/camel-jbang/camel-jbang-plugin-k/src/test/resources/route.yaml

CAMEL-20645: Support trait addons in Camel K JBang plugin

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelJBangMain.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/plugin/PluginAdd.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/CamelJBangPlugin.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/Plugin.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/PluginHelper.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/PluginType.java
dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/plugin/PluginAddTest.java
dsl/camel-jbang/camel-jbang-plugin-generate/src/main/java/org/apache/camel/dsl/jbang/core/commands/generate/GeneratePlugin.java
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/KubePlugin.java

CAMEL-20903: camel-jbang - Only load custom plugin if in use

---

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/PrototypeExchangeFactory.java
core/camel-core/src/test/java/org/apache/camel/support/component/RawParameterHelperTest.java
core/camel-support/src/main/java/org/apache/camel/support/DefaultComponent.java
core/camel-support/src/main/java/org/apache/camel/support/component/RawParameterHelper.java
core/camel-support/src/main/java/org/apache/camel/support/component/SendDynamicAwareSupport.java
core/camel-util/src/main/java/org/apache/camel/util/URISupport.java
docs/user-manual/modules/faq/pages/how-do-i-configure-endpoints.adoc

CAMEL-20897: Allow to use {xxx} inside RAW(xxx) for more power

---

core/camel-api/src/main/java/org/apache/camel/spi/InflightRepository.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultInflightRepository.java
core/camel-console/src/main/java/org/apache/camel/impl/console/ConsumerDevConsole.java
core/camel-console/src/main/java/org/apache/camel/impl/console/ContextDevConsole.java
core/camel-console/src/main/java/org/apache/camel/impl/console/EndpointDevConsole.java
core/camel-console/src/main/java/org/apache/camel/impl/console/InflightConsole.java
core/camel-console/src/main/java/org/apache/camel/impl/console/RouteDevConsole.java
core/camel-management-api/src/main/java/org/apache/camel/api/management/mbean/ManagedCamelContextMBean.java
core/camel-management-api/src/main/java/org/apache/camel/api/management/mbean/ManagedConsumerMBean.java
core/camel-management-api/src/main/java/org/apache/camel/api/management/mbean/ManagedEndpointMBean.java
core/camel-management-api/src/main/java/org/apache/camel/api/management/mbean/ManagedProducerMBean.java
core/camel-management-api/src/main/java/org/apache/camel/api/management/mbean/ManagedRouteMBean.java
core/camel-management/src/main/java/org/apache/camel/management/mbean/ManagedCamelContext.java
core/camel-management/src/main/java/org/apache/camel/management/mbean/ManagedConsumer.java
core/camel-management/src/main/java/org/apache/camel/management/mbean/ManagedProducer.java
core/camel-management/src/main/java/org/apache/camel/management/mbean/ManagedRoute.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/CamelContextStatus.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/CamelRouteStatus.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/CamelRouteTop.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/ListInflight.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/ListProcess.java

remote vs local counter to better observe how many internal and external messages is being processed

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaBreakOnFirstErrorSeekIssueIT.java

On repeat local runs, about 5 out of 100 runs resulted in similar symptoms as main CI  (but on CI, recent failures had a higher frequency)
After these chnges, got 250 clean runs:
- restored wait using Availability with an extra until condition
- moved topic setup from `@BeforeAll` to `@BeforeEach` (as this wasn't being invoked during test repeat runs)
- increased consumersCount, added heartbeatIntervalMs -----

CAMEL-20722 - increase consumer count, add Availability.wait

---

components/camel-mail/src/main/java/org/apache/camel/component/mail/MailConverters.java
components/camel-mail/src/test/java/org/apache/camel/component/mail/MailAttachmentPollEnrichTest.java

camel-mail - Fix stream caching with pollEnrich and attachment

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/PluginHelper.java

Also comes with a minor code cleanup

CAMEL-20917: avoid using hard-coded groups and versions

---

components/camel-etcd3/pom.xml

camel-etcd: Lets see if CI tests can pass this

---

docs/main/modules/advanced-camel-core-guides/pages/index.adoc
docs/user-manual/modules/ROOT/pages/event-notifier.adoc
docs/user-manual/modules/ROOT/pages/index.adoc

Patch 5 (Add documentation for EventNotifier)

---

components/camel-aws/camel-aws2-kinesis/src/main/docs/aws2-kinesis-component.adoc

Add AWS Kinesis batch producer description in Kinesis component doc.

Add AWS Kinesis batch producer description in Kinesis component doc.

---

components/camel-http/src/main/docs/http-component.adoc
components/camel-http/src/main/java/org/apache/camel/component/http/HttpComponent.java
components/camel-http/src/main/java/org/apache/camel/component/http/OAuth2ClientConfigurer.java

CAMEL-20924: camel-http - add oauth2scope parameter

---

components/camel-csimple-joor/src/test/java/org/apache/camel/language/csimple/joor/OriginalSimpleTest.java
core/camel-core-languages/src/main/docs/modules/languages/pages/csimple-language.adoc
core/camel-core-languages/src/main/docs/modules/languages/pages/simple-language.adoc
core/camel-core-languages/src/main/java/org/apache/camel/language/csimple/CSimpleHelper.java
core/camel-core-languages/src/main/java/org/apache/camel/language/simple/ast/SimpleFunctionExpression.java
core/camel-core/src/test/java/org/apache/camel/language/simple/SimpleTest.java
core/camel-support/src/main/java/org/apache/camel/support/builder/ExpressionBuilder.java

CAMEL-20926: simple language - Add fromRouteId as function.

---

components/camel-csimple-joor/src/test/java/org/apache/camel/language/csimple/joor/OriginalSimpleTest.java
core/camel-core-languages/src/main/docs/modules/languages/pages/simple-language.adoc
core/camel-core-languages/src/main/java/org/apache/camel/language/csimple/CSimpleHelper.java
core/camel-core-languages/src/main/java/org/apache/camel/language/simple/SimpleExpressionBuilder.java
core/camel-core-languages/src/main/java/org/apache/camel/language/simple/ast/SimpleFunctionExpression.java
core/camel-core/src/test/java/org/apache/camel/language/simple/SimpleTest.java
core/camel-support/src/main/java/org/apache/camel/support/builder/ExpressionBuilder.java

CAMEL-20931: camel-core - Add substring function to simple language

---

dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationRun.java
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/KubeCommand.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationRunTest.java

CAMEL-20900: Add integration-profile command option on Camel K JBang

---

test-infra/camel-test-infra-aws-v2/src/test/resources/org/apache/camel/test/infra/aws2/services/container.properties
test-infra/camel-test-infra-azure-common/src/test/resources/org/apache/camel/test/infra/azure/common/services/container.properties
test-infra/camel-test-infra-cassandra/src/test/resources/org/apache/camel/test/infra/cassandra/services/container.properties
test-infra/camel-test-infra-consul/src/test/resources/org/apache/camel/test/infra/consul/services/container.properties
test-infra/camel-test-infra-couchbase/src/test/resources/org/apache/camel/test/infra/couchbase/services/container.properties
test-infra/camel-test-infra-elasticsearch/src/test/resources/org/apache/camel/test/infra/elasticsearch/services/container.properties
test-infra/camel-test-infra-hashicorp-vault/src/test/resources/org/apache/camel/test/infra/hashicorp/vault/services/container.properties
test-infra/camel-test-infra-infinispan/src/test/resources/org/apache/camel/test/infra/infinispan/services/container.properties
test-infra/camel-test-infra-kafka/src/test/resources/org/apache/camel/test/infra/kafka/services/container.properties
test-infra/camel-test-infra-milvus/src/test/resources/org/apache/camel/test/infra/milvus/services/container.properties
test-infra/camel-test-infra-mongodb/src/test/resources/org/apache/camel/test/infra/mongodb/services/container.properties
test-infra/camel-test-infra-nats/src/test/resources/org/apache/camel/test/infra/nats/services/container.properties
test-infra/camel-test-infra-ollama/src/test/resources/org/apache/camel/test/infra/ollama/services/container.properties
test-infra/camel-test-infra-postgres/src/test/resources/org/apache/camel/test/infra/postgres/services/container.properties
test-infra/camel-test-infra-pulsar/src/test/resources/org/apache/camel/test/infra/pulsar/services/container.properties
test-infra/camel-test-infra-qdrant/src/test/resources/org/apache/camel/test/infra/qdrant/services/container.properties
test-infra/camel-test-infra-rabbitmq/src/test/resources/org/apache/camel/test/infra/rabbitmq/services/container.properties

I'll merge this once I validate it on my own CI.

Lots of container upgrades

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/PluginHelper.java

- Maven GAV dependency from the plugin configuration can be empty
- Avoid Nullpointer when plugin needs to be resolved by naming convention defaults instead

chore(jbang): Fix plugin helper

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java

chore(jbang): Fix runtime type checks in run command

---

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/DevModeITCase.java
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/RunCommandITCase.java

update jbang tests according to the new api and specification

camel-jbang-it: update it

---

components/camel-whatsapp/src/main/java/org/apache/camel/component/whatsapp/WhatsAppWebhookProcessor.java

BugFix removed write only object

BugFix removed write only object

---

.github/actions/component-test/action.yaml
.github/workflows/pr-comment.yml
.gitmodules

chore(ci): Fix vulnerability by using directly referenced action (4.4)

---

.github/actions/component-test/action.yaml
.github/workflows/pr-comment.yml
.gitmodules

chore(ci): Fix vulnerability by using directly referenced action (4.0)

---

dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-pom.tmpl

configuration
with "newer" version of Camel Quarkus 2 parameters are required to have the Camel debug working

CAMEL-20946: Generate Quarkus project with correct Camel Debug

---

tooling/camel-util-json/src/main/java/org/apache/camel/util/json/JsonArray.java
tooling/camel-util-json/src/main/java/org/apache/camel/util/json/JsonObject.java
tooling/camel-util-json/src/main/java/org/apache/camel/util/json/Jsoner.java

[CAMEL-20948] Handle proper streaming with camel-util-json (no unnecessary StringWriter)

---

camel-sbom/camel-sbom.vex.json

Added VEX file from CycloneDX SBOM

---

bom/camel-bom/pom.xml
parent/pom.xml

CAMEL-20955: Add JBang plugin modules to camel-bom

---

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc
dsl/camel-jbang/camel-jbang-plugin-k/pom.xml

- chore(camel-jbang): Fix table layout in Kubernetes plugin docs
- chore(camel-jbang): Remove explicit dependency version as module is now part of camel-bom

chore(camel-jbang): Fix table layout in Kubernetes plugin docs

---

dsl/camel-jbang/README.md

Document how to use the local camel-jbang build

---

.mvn/rrf/groupId-atlassian.txt
parent/pom.xml

camel-jira - Upgrade to jira client 6.0.1

---

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesCommandTest.java

chore(camel-jbang): Kubernetes plugin command test

---

components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2ServerManagerIT.java

Just a minor cleanup because I want to test something ...

(chores) camel-as2: minor test code cleanup

---

dsl/camel-jbang/camel-jbang-container/Dockerfile
dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

Camel-Jbang: Upgrade to Camel 4.7.0

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/YamlHelper.java
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/Bind.java
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/CamelKPlugin.java
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationExport.java
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationRun.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationExportTest.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/resources/org/apache/camel/dsl/jbang/core/commands/k/integration.yaml
dsl/camel-jbang/camel-jbang-plugin-k/src/test/resources/org/apache/camel/dsl/jbang/core/commands/k/pipe.yaml
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesHelper.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitCatalog.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitHelper.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/main/java/org/apache/camel/dsl/yaml/YamlRoutesBuilderLoader.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/IntegrationLoaderTest.groovy
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/KameletBindingLoaderIntegrationSpecTest.groovy
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/PipeLoaderIntegrationSpecTest.groovy

- Add new subcommand to export Camel K integrations/pipes to arbitrary project
- This enables the user to export the integration custom resource as normal project that can be run without the Camel K operator being installed on the Kubernetes cluster
- Export automatically configures the Kubernetes deployment manifest with the Camel K integration traits
- chore(camel-jbang): Fix classloader for downloaded plugin dependencies
- chore(camel-yaml-dsl): Support new trait configurations
Subcommand is run as follows:
```
camel k export integration.yaml --dir export-dir
```
In `export-dir` you can then call
```
./mvnw package -Dquarkus.container-image.build=true -Dquarkus.container-image.push=true -Dquarkus.kubernetes.deploy=true
```
This builds a container image and runs the Camel K integration …

CAMEL-20985: Camel K integration export

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogDoc.java
dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

Camel-JBang: Upgrade to Camel Kamelets 4.7.0

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportQuarkus.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportSpringBoot.java
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/spring-boot-kubernetes-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/SpringBootExportTest.java
dsl/camel-jbang/camel-jbang-core/src/test/resources/route.yaml
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationExport.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java

https://issues.apache.org/jira/browse/CAMEL-20990
To test this, you can use the sample project [here](https://github.com/tdiesler/camel-cloud-examples/tree/main/spring-boot/timer-log).

[CAMEL-20962] camel-jbang: SpringBoot support in Kubernetes plugin

---

catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/ValidateMojo.java

Include `disruptor` and `disruptor-vm` on pair check of `camel-report-maven-plugin`'s `validate` goal

Include disruptor and disruptor-vm on validation mojo

---

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesHelper.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/ContainerTrait.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java

* Add missing container trait options to Kubernetes plugin: `container.request-cpu`, `container.request-memory`, `container.limit-cpu`, `container.limit-memory`
* Fix parsing to be able to map kebab case command option to  camel case containing an uppercase part (like CPU or SSL): `request-cpu` => `requestCPU`

CAMEL-20984: Add Camel JBang Kubernetes trait container missing options

---

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc
dsl/camel-jbang/camel-jbang-plugin-kubernetes/pom.xml
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/AnnotationTrait.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/ContainerTrait.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/DeploymentTrait.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/ServiceTrait.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitCatalog.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitContext.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitHelper.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/knative/KnativeBaseTrait.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/knative/KnativeServiceTrait.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java
parent/pom.xml

- Add Knative service trait to autoconfigure Knative serving service resource
- Add service and Knative service trait options documentation
See CAMEL-2083

CAMEL-20983: Add JBang Knative service trait

---

components/camel-graphql/src/main/docs/graphql-component.adoc

add content to bookByIdQuery.graphql in graphql-component.adoc

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportCamelMain.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportQuarkus.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportSpringBoot.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationExportTest.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitHelper.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java

https://issues.apache.org/jira/browse/CAMEL-21006

[CAMEL-21006] Allow kubernetes export without image registry

---

components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/KclKinesis2Consumer.java

CAMEL-21009 - Camel-AWS2-Kinesis: CloudWatchAsyncClient and DynamoDbAsyncClient parameters are ignored from KCL Consumer

---

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/MetadataHelper.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/support/StubComponentResolver.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/CamelTrait.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitCatalog.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitContext.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitHelper.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/knative/KnativeTrait.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/resources/knative-channel-sink.yaml
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/resources/knative-channel-source.yaml
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/resources/knative-endpoint-sink.yaml
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/resources/knative-event-sink.yaml
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/resources/knative-event-source.yaml
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/DependencyDownloaderRoutesLoader.java

- When applicable add Knative trigger to Kubenretes manifest
- When applicable add Knative channel subscription to Kubernetes manifest
- When applicable add Knative sink binding for endpoint URI injection
- Auto configure Knative Camel component with proper resources in environment config (knative.json)
- Auto configure application.properties in exported project to hold Knative environment configuration

CAMEL-20983: Add JBang Knative trait support

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Export.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportCamelMain.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportQuarkus.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportSpringBoot.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/RuntimeUtil.java
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/main-kubernetes-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/main-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/spring-boot-kubernetes-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/spring-boot-pom.tmpl
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java

https://issues.apache.org/jira/browse/CAMEL-21016
You can now do ...
```
camel kubernetes export timer-log-route.yaml \
--gav=examples:timer-log:1.0.0 \
--trait container.imagePullPolicy=IfNotPresent \
--build-property=jkube.enricher.jkube-service.type=NodePort \
--runtime=spring-boot
```

[CAMEL-21016] Add support for multiple build properties in jbang export

---

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Export.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportCamelMain.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportQuarkus.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportSpringBoot.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/version/VersionList.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/CatalogLoader.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/RuntimeUtil.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/KameletMain.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/console/DependencyDownloaderConsole.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/DependencyDownloader.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/MavenDependencyDownloader.java
tooling/camel-tooling-maven/src/main/java/org/apache/camel/tooling/maven/MavenDownloaderImpl.java

https://issues.apache.org/jira/browse/CAMEL-21016

[CAMEL-21016] camel-jbang: Add support for multiple --exclude, --repository

---

parent/pom.xml

Align camel-4.4.x branch with dependencies from spring-boot 3.2.8.

---

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc

Camel-Jbang documentation: Removed missing fragment reference

---

parent/pom.xml

https://github.com/apache/camel/pull/14804 may be unappealing to camel-quarkus because of https://github.com/apache/camel/pull/14499#issuecomment-2209206550 - we can temporarily increase to 4.11.2 in the meantime

Upgrade mongodb driver to 4.11.2

---

components/camel-bindy/src/main/docs/bindy-dataformat.adoc
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/annotation/CsvRecord.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/annotation/FixedLengthRecord.java
components/camel-grpc/src/main/docs/grpc-component.adoc
components/camel-infinispan/camel-infinispan-embedded/src/main/docs/infinispan-embedded-component.adoc
components/camel-infinispan/camel-infinispan/src/main/docs/infinispan-component.adoc
components/camel-spring-redis/src/main/docs/spring-redis-component.adoc
core/camel-base/src/main/docs/properties-component.adoc
core/camel-core-engine/src/main/docs/modules/eips/pages/bean-eip.adoc
core/camel-core-languages/src/main/docs/modules/languages/pages/file-language.adoc
core/camel-core-languages/src/main/docs/modules/languages/pages/simple-language.adoc

- incorrect samples
- invalid formatting
- grammar, typos and other small mistakes

CAMEL-21040: more documentation fixes

---

components/camel-crypto/pom.xml

fixes https://issues.apache.org/jira/browse/CAMEL-21047

Removal of bouncycastle dependencies from camel-crypto.

---

core/camel-core-engine/src/main/docs/modules/eips/pages/transform-eip.adoc

CAMEL-21040: minor typo fixes

---

components/camel-ai/camel-djl/src/main/docs/djl-component.adoc
components/camel-ai/camel-langchain4j-chat/src/main/docs/langchain4j-chat-component.adoc
components/camel-ai/camel-langchain4j-web-search/src/main/docs/langchain4j-web-search-component.adoc
components/camel-ai/camel-pinecone/src/main/docs/pinecone-component.adoc
components/camel-debezium/camel-debezium-postgres/src/main/docs/debezium-postgres-component.adoc
components/camel-debezium/camel-debezium-sqlserver/src/main/docs/debezium-sqlserver-component.adoc
components/camel-digitalocean/src/main/docs/digitalocean-component.adoc
components/camel-disruptor/src/main/docs/disruptor-component.adoc
components/camel-dns/src/main/docs/dns-component.adoc
components/camel-docker/src/main/docs/docker-component.adoc
components/camel-drill/src/main/docs/drill-component.adoc
components/camel-dropbox/src/main/docs/dropbox-component.adoc
components/camel-dynamic-router/src/main/docs/dynamic-router-component.adoc
components/camel-ehcache/src/main/docs/ehcache-component.adoc
components/camel-elasticsearch-rest-client/src/main/docs/elasticsearch-rest-client-component.adoc
components/camel-elasticsearch/src/main/docs/elasticsearch-component.adoc
components/camel-etcd3/src/main/docs/etcd3-component.adoc
components/camel-exec/src/main/docs/exec-component.adoc
components/camel-file-watch/src/main/docs/file-watch-component.adoc
components/camel-file/src/main/docs/file-component.adoc
components/camel-flatpack/src/main/docs/flatpack-component.adoc
components/camel-flatpack/src/main/docs/flatpack-dataformat.adoc
components/camel-flink/src/main/docs/flink-component.adoc
components/camel-fop/src/main/docs/fop-component.adoc
components/camel-freemarker/src/main/docs/freemarker-component.adoc

- Also fix typos
- Minor issues with examples

CAMEL-21040: ensure more consistency in the document sections

---

components/camel-saxon/src/main/java/org/apache/camel/component/xquery/XQueryBuilder.java
components/camel-xslt/src/main/java/org/apache/camel/component/xslt/XsltBuilder.java

CAMEL-21053: camel-xslt - All exchange properties should be avaiabl

---

components/camel-ai/camel-milvus/src/main/docs/milvus-component.adoc

Camel-Milvus: Fixed docs with reference to qdrant

---

components/camel-ai/camel-milvus/src/main/docs/milvus-component.adoc

Camel-Milvus: Relation with Langchain4j-embeddings in docs

---

components/camel-google/camel-google-secret-manager/src/main/docs/google-secret-manager-component.adoc

Camel-Google-Secret-Manager: Fixed names of application.properties

---

dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-pom.tmpl

pom template for Camel JBang
It allows to ease usage of Remote Camel debugger, for instance when deployed on Kubernetes or OpenShift. For instance, it removes this step of this tutorial https://camel.apache.org/blog/2024/08/camel-quarkus-remote-debug-to-openshift-from-vscode/#pom-configuration

CAMEL-20947 - Add Jolokia config in camel.debug profile of Camel Quarkus

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/ExportTest.java

https://issues.apache.org/jira/browse/CAMEL-21059

CAMEL-21059 Cannot run or export when --repository is set before the integration file

---

dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/spring-boot-kubernetes-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/spring-boot-pom.tmpl

SpringBoot pom template for Camel JBang
It allows to ease usage of Remote Camel debugger, for instance when deployed on Kubernetes or OpenShift

CAMEL-21065 - Add Jolokia config in camel.debug profile of Camel

---

components/camel-mongodb/src/main/docs/mongodb-component.adoc

a title was changed in
https://github.com/apache/camel/commit/2ff6db4492b6ad0f48e2bb05603d42b5f8940351#diff-814cb1d25fca6d9701ed69cac5bc181f928412040b2f24c892aa11c94abce8e3R269 , internal links must be updated too

Fix documentation mongodb

---

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java

- Print error details when export fails for some reason

Improve JBang Kubernetes export to print failure details

---

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
parent/pom.xml

- Align with kubernetes-client version and fixes Jbang Kubernetes plugin tests

chore(deps): Bump knative-client-version from 6.13.1 to 6.13.2

---

.github/pull_request_template.md

chore(doc): info to compile from root project

---

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc

- Add missing export command option description
- Add deploy to OpenShift explanations
- Add some links to further information

chore(docs): Improve JBang Kubernetes plugin documentation

---

components/camel-rest-openapi/src/main/java/org/apache/camel/component/rest/openapi/RestOpenApiEndpoint.java

Backport CAMEL-21057 to 4.4.x

---

components/camel-infinispan/camel-infinispan/pom.xml
components/camel-infinispan/camel-infinispan/src/main/java/org/apache/camel/component/infinispan/remote/protostream/DefaultExchangeHolderInitializer.java
parent/pom.xml

not sure that it is the direction we want to go but at least it allows to see which modifications are needed to integrate protostream 5.0.8

Protostream version 5.0.8.final manual upgrade

---

components/camel-as2/camel-as2-component/src/main/java/org/apache/camel/component/as2/internal/AS2Constants.java
components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2AsyncMDNServerManagerIT.java
components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2ClientManagerIT.java
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_8.adoc

CAMEL-21090: camel-as2 fix wrong header name prefix.

---

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Init.java
dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/InitTest.java

creating a new Camel integration files with Camel JBang init

CAMEL-21082 - do not delete existing file sin target folder when

---

.mvn/wrapper/maven-wrapper.properties

Upgrade maven wrapper 3.9.9

---

components/camel-azure/camel-azure-servicebus/src/main/java/org/apache/camel/component/azure/servicebus/ServiceBusConsumer.java
components/camel-azure/camel-azure-servicebus/src/test/java/org/apache/camel/component/azure/servicebus/ServiceBusConsumerTest.java

Complete, abandon and dead-letter operations are not available when the Azure Service Bus receive mode is RECEIVE_AND_DELETE; do not attempt these operations in this scenario.

CAMEL-20992: Do not complete, abandon or dead-letter messages in RECEIVE_AND_DELETE receive mode

---

core/camel-api/src/main/java/org/apache/camel/cloud/DiscoverableService.java
core/camel-api/src/main/java/org/apache/camel/cloud/ServiceCallConstants.java
core/camel-api/src/main/java/org/apache/camel/cloud/ServiceChooser.java
core/camel-api/src/main/java/org/apache/camel/cloud/ServiceChooserAware.java
core/camel-api/src/main/java/org/apache/camel/cloud/ServiceChooserFactory.java
core/camel-api/src/main/java/org/apache/camel/cloud/ServiceDefinition.java
core/camel-api/src/main/java/org/apache/camel/cloud/ServiceDiscovery.java
core/camel-api/src/main/java/org/apache/camel/cloud/ServiceDiscoveryAware.java
core/camel-api/src/main/java/org/apache/camel/cloud/ServiceDiscoveryFactory.java
core/camel-api/src/main/java/org/apache/camel/cloud/ServiceExpressionFactory.java
core/camel-api/src/main/java/org/apache/camel/cloud/ServiceFactory.java
core/camel-api/src/main/java/org/apache/camel/cloud/ServiceFilter.java
core/camel-api/src/main/java/org/apache/camel/cloud/ServiceFilterAware.java
core/camel-api/src/main/java/org/apache/camel/cloud/ServiceFilterFactory.java
core/camel-api/src/main/java/org/apache/camel/cloud/ServiceHealth.java
core/camel-api/src/main/java/org/apache/camel/cloud/ServiceLoadBalancer.java
core/camel-api/src/main/java/org/apache/camel/cloud/ServiceLoadBalancerFactory.java
core/camel-api/src/main/java/org/apache/camel/cloud/ServiceLoadBalancerFunction.java
core/camel-api/src/main/java/org/apache/camel/cloud/ServiceRegistry.java

package
camel-cloud component was deprecated in 4.7.0, these packages need also to be deprecated

CAMEL-20804 - mark classes as deprecated  in camel-api o.a.c.cloud

---

components/camel-platform-http-main/src/main/java/org/apache/camel/component/platform/http/main/MainHttpServer.java
core/camel-api/src/main/java/org/apache/camel/console/DevConsole.java
core/camel-console/src/main/java/org/apache/camel/impl/console/RouteDevConsole.java
core/camel-console/src/main/java/org/apache/camel/impl/console/RouteDumpDevConsole.java
core/camel-console/src/main/java/org/apache/camel/impl/console/SourceDevConsole.java
core/camel-console/src/main/java/org/apache/camel/impl/console/TopDevConsole.java
core/camel-support/src/main/java/org/apache/camel/support/LoggerHelper.java
core/camel-support/src/main/java/org/apache/camel/support/console/AbstractDevConsole.java

dev console - source to be able to download using raw mode

---

components/camel-tracing/src/main/java/org/apache/camel/tracing/ActiveSpanManager.java
core/camel-api/src/generated/java/org/apache/camel/ExchangeConstantProvider.java
core/camel-api/src/main/java/org/apache/camel/Exchange.java
core/camel-api/src/main/java/org/apache/camel/ExchangePropertyKey.java
core/camel-support/src/main/java/org/apache/camel/saga/InMemorySagaCoordinator.java

Add a `ExchangePropertyKey` constant for "OpenTracing.activeSpan"

Add `ExchangePropertyKey` for active tracing span property

---

test-infra/camel-test-infra-aws-v2/src/test/resources/org/apache/camel/test/infra/aws2/services/container.properties

Upgrade aws container used in tests from 3.5.0 to 3.6.0

---

test-infra/camel-test-infra-elasticsearch/src/test/resources/org/apache/camel/test/infra/elasticsearch/services/container.properties

Upgrade elasticsearch container used in test to 8.15.0

---

components/camel-rest-openapi/src/main/java/org/apache/camel/component/rest/openapi/DefaultRestOpenapiProcessorStrategy.java
components/camel-rest-openapi/src/test/java/org/apache/camel/component/rest/openapi/RestOpenapiProcessorStrategyTest.java
components/camel-rest-openapi/src/test/resources/missing-opid.yaml

base on the path and the http method. This allows the user to add a route if the OpenAPI specification is not modifiable.

CAMEL-20979: if no operationId is specified, generate an id

---

components/camel-spring-xml/src/test/java/org/apache/camel/spring/processor/SpringStreamCachingStrategyTest.java

Fix style in SpringStreamCachingStrategyTest

---

components/camel-amqp/pom.xml

this is a workaround to fix main branch
https://junit.org/junit5/docs/5.11.0/release-notes/#release-notes-5.11.0-junit-platform-deprecations-and-breaking-changes https://junit.org/junit5/docs/5.11.0/user-guide/index.html#extensions-supported-utilities-search-semantics

CAMEL-21108 - use legacy JUnit search algorithm

---

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_7.adoc

https://camel.apache.org/components/next/file-component.html#_endpoint_query_option_idempotent
https://camel.apache.org/components/next/file-component.html#_endpoint_query_option_idempotentEager

Update camel-4x-upgrade-guide-4_7.adoc - fix typo idempontent

---

components/camel-bindy/src/test/java/org/apache/camel/dataformat/bindy/model/fix/complex/onetomany/Order.java
components/camel-exec/src/test/java/org/apache/camel/component/exec/ExecEndpointTest.java
components/camel-exec/src/test/java/org/apache/camel/component/exec/ExecJavaProcessRecipientListTest.java
components/camel-exec/src/test/java/org/apache/camel/component/exec/ExecJavaProcessTest.java
components/camel-exec/src/test/java/org/apache/camel/component/exec/ExecScriptTest.java
components/camel-exec/src/test/java/org/apache/camel/component/exec/impl/ExecDocumentationExamplesTest.java
components/camel-snmp/src/main/java/org/apache/camel/component/snmp/SnmpConverters.java
core/camel-management/src/main/java/org/apache/camel/management/DefaultManagementObjectNameStrategy.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PackageModelMojo.java

(chores) Fix StringBuilder append misuses

---

tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/JavadocHelper.java
tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/Strings.java
tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/srcgen/Annotation.java
tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/srcgen/GenericType.java
tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/srcgen/JavaClass.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/AbstractGenerateConfigurerMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/ComponentDslMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointDslMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PackageDataFormatMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PackageLanguageMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PackageModelMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PrepareCamelMainDocMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PrepareComponentMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/SchemaHelper.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/SpiGeneratorMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/UpdateSensitizeHelper.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/generics/JavadocUtil.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/generics/PackagePluginUtils.java

(chores) tooling: use more adequately sized buffers

---

test-infra/camel-test-infra-nats/src/test/resources/org/apache/camel/test/infra/nats/services/container.properties

Upgrade Nats container image to version 2.10.18

---

components/camel-kubernetes/src/main/docs/kubernetes-config-maps-component.adoc

to fix camel-website main branch
```
[build:antora  ] [build:antora-perf] [10:04:03.659] WARN (asciidoctor): section title out of sequence: expected level 2, got level 3
[build:antora  ] [build:antora-perf]     file: docs/components/modules/ROOT/pages/kubernetes-config-maps-component.adoc:123
[build:antora  ] [build:antora-perf]     source: https://github.com/apache/camel.git (branch: main | start path: docs/components)
[build:antora  ] ERROR: "build:antora-perf" exited with 1.
```

Fix section level in doc for kubernetes

---

components/camel-tracing/src/main/java/org/apache/camel/tracing/ActiveSpanManager.java

Addresses the double closing of Scopes discussed in https://github.com/apache/camel/pull/15182
Technically I don't think this is a bug [1] [2] but should be fixed nonetheless.
Thanks !
[1] https://github.com/apache/camel/blob/main/components/camel-tracing/src/main/java/org/apache/camel/tracing/Tracer.java#L273
[2] https://github.com/open-telemetry/opentelemetry-java/blob/main/context/src/main/java/io/opentelemetry/context/ThreadLocalContextStorage.java#L48

camel-tracing close scope only once

---

core/camel-util/src/main/java/org/apache/camel/util/StringHelper.java
core/camel-util/src/test/java/org/apache/camel/util/StringHelperTest.java

Just a bunch of pretty small micro-optimizations in StringHelper, along with increased test coverage.

(chores) micro-opt in StringHelper

---

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/RouteFromDirITCase.java
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/JBangTestSupport.java
dsl/camel-jbang/camel-jbang-it/src/test/resources/jbang/it/from-source-dir/FromDirectoryRoute.java

Adds test for [this part of documentation](https://camel.apache.org/manual/camel-jbang.html#_running_routes_from_source_directory)

CAMEL-20367: Adds running routes from source directory test

---

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc

Add note about proxy configuration when using Camel JBang in doc

---

components/camel-consul/src/main/java/org/apache/camel/component/consul/ConsulRegistry.java
core/camel-api/src/main/java/org/apache/camel/BindToRegistry.java
core/camel-api/src/main/java/org/apache/camel/spi/CamelDependencyInjectionAnnotationFactory.java
core/camel-api/src/main/java/org/apache/camel/spi/Registry.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultCamelBeanPostProcessor.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultDependencyInjectionAnnotationFactory.java
core/camel-core/src/test/java/org/apache/camel/impl/BindToRegistryBeanInitDestroyMethodTest.java
core/camel-support/src/main/java/org/apache/camel/support/DefaultRegistry.java
core/camel-support/src/main/java/org/apache/camel/support/SimpleRegistry.java
core/camel-support/src/main/java/org/apache/camel/support/scan/PackageScanHelper.java
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_8.adoc
dsl/camel-xml-io-dsl/src/main/java/org/apache/camel/dsl/xml/io/XmlRoutesBuilderLoader.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/BeansDeserializer.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/main/java/org/apache/camel/dsl/yaml/YamlRoutesBuilderLoaderSupport.java

Add init and destroy methods to @BindToRegistry (part 1)

---

dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/injection/AnnotationDependencyInjection.java

Respect style to fix PR build on main branch

---

test-infra/camel-test-infra-solr/src/test/resources/org/apache/camel/test/infra/solr/services/container.properties

this image is enough for our tests and it divides size by 2

Use slim container image of Solr

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java

camel-jbang: comma separated should also be supported with --dep option

---

core/camel-console/src/main/java/org/apache/camel/impl/console/TraceDevConsole.java
core/camel-main/src/main/java/org/apache/camel/main/ProfileConfigurer.java
core/camel-management/src/test/java/org/apache/camel/management/BacklogDebuggerTest.java
core/camel-support/src/main/java/org/apache/camel/support/MessageHelper.java
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_8.adoc
docs/user-manual/modules/ROOT/pages/camel-jbang.adoc
dsl/camel-cli-connector/src/main/java/org/apache/camel/cli/connector/LocalCliConnector.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/CamelTraceAction.java

CAMEL-21150: camel-jbang - Make tracer in standby as default

---

components/camel-ai/camel-langchain4j-chat/src/main/docs/langchain4j-chat-component.adoc
components/camel-ai/camel-langchain4j-chat/src/main/java/org/apache/camel/component/langchain4j/chat/tool/CamelSimpleToolParameter.java
components/camel-ai/camel-langchain4j-chat/src/main/java/org/apache/camel/component/langchain4j/chat/tool/CamelToolExecutorCache.java
components/camel-ai/camel-langchain4j-chat/src/main/java/org/apache/camel/component/langchain4j/chat/tool/CamelToolSpecification.java
components/camel-ai/camel-langchain4j-chat/src/main/java/org/apache/camel/component/langchain4j/chat/tool/NamedJsonSchemaProperty.java

CAMEL-21153: deprecate chat with tools feature in camel-langchain4j-chat

---

components/camel-jms/src/main/java/org/apache/camel/component/jms/JmsEndpoint.java
components/camel-sql/src/main/java/org/apache/camel/component/sql/DefaultSqlEndpoint.java
components/camel-sql/src/main/java/org/apache/camel/component/sql/stored/SqlStoredEndpoint.java
core/camel-util/src/main/java/org/apache/camel/util/UnwrapHelper.java

CAMEL-21163: unwrap the synthetic ClientProxy beans

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/main/camel-main-configuration-metadata.json
core/camel-api/src/main/java/org/apache/camel/vault/HashicorpVaultConfiguration.java
core/camel-main/src/generated/resources/META-INF/camel-main-configuration-metadata.json
core/camel-main/src/main/docs/main.adoc
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PrepareCamelMainMojo.java

Camel-Hashicorp-vault: Added to PrepareCamelMainMojo

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java

- Kubernetes run command should support all export command options that make sense
- Run command delegates the options to the nested export command
See CAMEL-21088

CAMEL-21088: Support all export options on Kubernetes run command

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Init.java
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/java.tmpl
dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/InitTest.java

when the file is created in a subfolder of a src/main/java directory

CAMEL-21175 - Create package name for file created with Camel Jbang

---

components/camel-tracing/src/main/java/org/apache/camel/tracing/ActiveSpanManager.java

Should fix the flaky tests. Component will need some rewriting (working on it).
Thanks !

Fix flaky tests

---

test-infra/camel-test-infra-kafka/src/test/resources/org/apache/camel/test/infra/kafka/services/container.properties

readme from https://hub.docker.com/r/vectorized/redpanda indicates the deprecation and new image to use

chore: Move from deprecated redpandata container used in test

---

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/ManagePluginsITCase.java
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/JBangTestSupport.java

Adds tests for [this part of documentation](https://camel.apache.org/manual/camel-jbang.html#_manage_plugins)

CAMEL-20367: Adds plugin management tests

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportCamelMain.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java

https://issues.apache.org/jira/browse/CAMEL-21063

[CAMEL-21063] Provide health endpoint for k8s export main

---

components/camel-solr/src/test/java/org/apache/camel/component/solr/SolrCloudFixture.java
test-infra/camel-test-infra-solr/src/test/resources/org/apache/camel/test/infra/solr/services/container.properties

Upgrade solr container image used in test to 9.7.0

---

components/camel-activemq/pom.xml

[CAMEL-21200] OSGi javax.jms range is wrong

---

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_9.adoc

CAMEL-20888- Mention removed jars related to kotlin in migration guide

---

components/camel-opensearch/src/main/java/org/apache/camel/component/opensearch/OpensearchProducer.java
components/camel-opensearch/src/main/java/org/apache/camel/component/opensearch/aggregation/OpensearchBulkRequestAggregationStrategy.java

Camel-opensearch: Use ObjectHelper where it makes sense

---

test-infra/camel-test-infra-redis/src/test/resources/org/apache/camel/test/infra/redis/services/container.properties

and also use the alpine version which is lighter and enough for our test case

Upgrade redis container in test to 7.4.0

---

components/camel-groovy/src/main/docs/groovy-language.adoc
components/camel-groovy/src/test/java/org/apache/camel/language/groovy/GroovyExpressionTest.java
components/camel-groovy/src/test/java/org/apache/camel/language/groovy/GroovyLanguageTest.java
components/camel-groovy/src/test/java/org/apache/camel/language/groovy/GroovyListMapTest.java
components/camel-groovy/src/test/java/org/apache/camel/language/groovy/GroovySetHeaderTest.java
components/camel-groovy/src/test/java/org/apache/camel/language/groovy/LanguageGroovyRouteTest.java
components/camel-groovy/src/test/java/org/apache/camel/processor/groovy/GroovySetHeaderConcurrentIssueTest.java
components/camel-groovy/src/test/java/org/apache/camel/processor/groovy/GroovySetHeaderIssueTest.java
components/camel-groovy/src/test/resources/org/apache/camel/processor/groovy/groovyFilter.xml
core/camel-core/src/test/java/org/apache/camel/util/ExchangeHelperTest.java
core/camel-support/src/main/java/org/apache/camel/support/ExchangeHelper.java
core/camel-util/src/main/java/org/apache/camel/util/URISupport.java

CAMEL-21213: camel-groovy - Align variables to use same naming as simple

---

test-infra/camel-test-infra-postgres/src/test/resources/org/apache/camel/test/infra/postgres/services/container.properties

also move to alpine image which is lighter and enough for our testing

Upgrade Postgres Container used in tests to 16.4

---

test-infra/camel-test-infra-cassandra/src/test/resources/org/apache/camel/test/infra/cassandra/services/container.properties

Upgrade Cassandra container used in tests to 5.0.0

---

camel-dependencies/pom.xml
parent/pom.xml

CAMEL-21225: Upgrade to pulsar 2.10.6

---

components/camel-cxf/camel-cxf-soap/src/main/docs/cxf-component.adoc

Refactor and fix camel-cxf-soap first example

---

docs/user-manual/modules/ROOT/pages/using-propertyplaceholder.adoc

chore(doc): scan cloud configuration as properties

---

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesHelper.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesBaseTest.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRunTest.java

https://issues.apache.org/jira/browse/CAMEL-21227

[CAMEL-21227] camel k8s run ignores output format

---

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java

https://issues.apache.org/jira/browse/CAMEL-21236

[CAMEL-21236] Explicitly enable/disable quarkus image push

---

components/camel-mock/src/main/java/org/apache/camel/component/mock/MockEndpoint.java
core/camel-core/src/test/java/org/apache/camel/component/dataset/DataSetProducerTest.java

https://issues.apache.org/jira/browse/CAMEL-19767

CAMEL-19767: Improve test handling AssertionError

---

components/camel-jsonpath/src/test/java/org/apache/camel/jsonpath/JsonStreamTest.java
components/camel-mail/src/test/java/org/apache/camel/component/mail/MailSorterTest.java
core/camel-core/src/test/java/org/apache/camel/support/jsse/SSLContextParametersTest.java

https://issues.apache.org/jira/browse/CAMEL-19767

CAMEL-19767: Light refactoring on test using AssertionError

---

docs/user-manual/modules/ROOT/pages/camel-report-maven-plugin.adoc
dsl/camel-jbang/camel-jbang-plugin-generate/pom.xml
dsl/camel-jbang/camel-jbang-plugin-generate/src/main/java/org/apache/camel/dsl/jbang/core/commands/generate/GeneratePlugin.java

Camel-Jbang-generate plugin: Move to 4.8.0

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogDoc.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/PluginType.java
dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

Upgrade Camel-Kamelets to version 4.8.0 for Camel-Jbang

---

test-infra/camel-test-infra-hashicorp-vault/src/test/resources/org/apache/camel/test/infra/hashicorp/vault/services/container.properties

Upgrade Hashicorp Vault image to version 1.17.5

---

test-infra/camel-test-infra-nats/src/test/resources/org/apache/camel/test/infra/nats/services/container.properties

Upgrade Nats Container image version 2.10.20

---

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/MetricsObservabilityITCase.java
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/JBangTestSupport.java
dsl/camel-jbang/camel-jbang-it/src/test/resources/jbang/it/CircuitBreakerRoute.java

Adds tests for [observability with metrics](https://camel.apache.org/manual/camel-jbang.html#_observability_with_metrics) and [listing states of circuit breakers](https://camel.apache.org/manual/camel-jbang.html#_listing_state_of_circuit_breakers).

CAMEL-20367: Adds observability tests

---

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/CustomJarsITCase.java

Adds test for [adding custom jars](https://camel.apache.org/manual/camel-jbang.html#_adding_custom_jars)

CAMEL-20367: Adds adding custom jar test

---

parent/pom.xml

Revert "chore(deps): Bump org.apache.httpcomponents.client5:httpclient5 from 5.2.1 to 5.4"

---

parent/pom.xml

Revert "chore(deps): Bump org.apache.thrift:libthrift from 0.20.0 to 0.21.0"

---

components/camel-opentelemetry/pom.xml
components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/OpenTelemetryTracer.java

https://issues.apache.org/jira/browse/CAMEL-21261
Thanks !

Context propagators

---

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/PodLogs.java

https://issues.apache.org/jira/browse/CAMEL-21238

[CAMEL-21238] Reloading in k8s run does not change route behaviour

---

components/camel-opentelemetry/pom.xml
components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/OpenTelemetryTracer.java

backport for https://issues.apache.org/jira/browse/CAMEL-21261
Thanks !

Backport 4.8.x

---

components/camel-opentelemetry/pom.xml
components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/OpenTelemetryTracer.java

backport for https://issues.apache.org/jira/browse/CAMEL-21261
Thanks !

Backport 4.4.x

---

dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/ExportMainJibTest.java
dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/ExportMainJkubeTest.java
dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/ExportTest.java

The test is now creating the generic exporting class which is initialized correctly with its runtime

fix(jbang): parameterized export test

---

dsl/camel-jbang/README.md
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportCamelMain.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportSpringBoot.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesBaseCommand.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesHelper.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/PodLogs.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesBaseTest.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRunTest.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/PodLogsTest.java

https://issues.apache.org/jira/browse/CAMEL-21267

Camel 21267 4.8.x

---

tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/JsonMapper.java

Fix typo issue when generating bean json

---

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_8.adoc

guide
for reference, it was changed in this commit
https://github.com/apache/camel/commit/23da1eb48096fed69fbf8becfc72b3541e33c9dd

Add breaking change note for Camel JBang repos parameter in Migration

---

docs/user-manual/modules/ROOT/pages/camel-jbang-k.adoc
dsl/camel-jbang/camel-jbang-plugin-k/pom.xml
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/CamelKCommand.java
dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/CamelKPlugin.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/AgentTest.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/BindTest.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/CamelKBaseTest.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/CamelKCommandTest.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationDeleteTest.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationExportTest.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationGetTest.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationLogsTest.java
dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationRunTest.java

CAMEL-21272: deprecated camel-k jbang plugin. Use kamel CLI instead.

---

dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/KameletMain.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/SagaDownloader.java

CAMEL-21273: camel-jbang - Detect saga dsl

---

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesBaseCommand.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesDelete.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/PodLogs.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRunTest.java

https://issues.apache.org/jira/browse/CAMEL-21235

[CAMEL-21235] Cannot run k8s app in namespace other than default

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Export.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportCamelMain.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportQuarkus.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportSpringBoot.java
dsl/camel-jbang/camel-jbang-core/src/main/resources/quarkus-docker/Dockerfile.native
dsl/camel-jbang/camel-jbang-core/src/main/resources/quarkus-docker/Dockerfile.native-micro
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/Dockerfile.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/readme.md.tmpl
dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/ExportTest.java

* All the runtimes have a Dockerfile when we export the application
* Added a simple readme.md to show quickly how to build and run an application
Closes CAMEL-21259

feat(jbang): harmonize Dockerfile presence

---

parent/pom.xml

Upgrade jboss-nio-version to 3.8.14.Final

Upgrade jboss-nio-version to 3.8.14.Final

---

dsl/camel-kotlin-api/src/generated/kotlin/org/apache/camel/kotlin/components/Aws2KinesisUriDsl.kt
parent/pom.xml

Upgrade jboss-xnio-version to 3.8.14.Final

Upgrade jboss-xnio-version to 3.8.14.Final; refresh

---

components/camel-azure/camel-azure-files/src/main/java/org/apache/camel/component/file/azure/FilesOperations.java
components/camel-azure/camel-azure-files/src/test/java/org/apache/camel/component/file/azure/FilesOperationsTest.java

CAMEL-21280: azure-files: Only CredentialType.SHARED_ACCOUNT_KEY is handled

---

parent/pom.xml

Upgrade maven-archetype-plugin and maven-archetype-packaging to 3.3.0; built and ran olingo2 tests and archetype tests

Upgrade maven-archetype-plugin and maven-archetype-packaging to 3.3.0

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportCamelMain.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportQuarkus.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportSpringBoot.java
dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/ExportTest.java
dsl/camel-jbang/camel-jbang-core/src/test/resources/counter.yaml
dsl/camel-jbang/camel-jbang-core/src/test/resources/user-source.kamelet.yaml
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/DependencyDownloaderRoutesLoader.java

jbang - Fix export with kamelets

---

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_8.adoc
docs/user-manual/modules/ROOT/pages/camel-jbang.adoc
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Export.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java

backport of https://github.com/apache/camel/pull/15717

Backport 4.8.x - CAMEL-21283 - Switch back to repos parameter in Camel JBang run and

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportQuarkus.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/ExportTest.java

We are now validating the content produced by the export to make sure the most important resources are where they are expected
Closes CAMEL-21285

fix(jbang): strenghten unit test

---

components/camel-jetty/src/test/java/org/apache/camel/component/jetty/HttpHeaderTest.java

Update test now that `Http1Config` sets its version to HTTP1.1 following the upgrade to httpcore v5.3

camel-jetty - Fix failing unit test

---

components/camel-graphql/src/test/java/org/apache/camel/component/graphql/server/GraphqlServer.java
components/camel-http/src/test/java/org/apache/camel/component/http/HttpsAuthenticationTest.java
components/camel-wordpress/src/test/java/org/apache/camel/component/wordpress/api/test/WordpressMockServerTestSupport.java
parent/pom.xml

Upgrade the httpclient version to 5.4 following the recent upgrade of httpcore to version 5.3.

Upgrade httpclient version to 5.4

---

components/camel-smb/src/main/docs/smb-component.adoc
components/camel-smb/src/main/java/org/apache/camel/component/smb/SmbProducer.java
components/camel-smb/src/test/java/org/apache/camel/component/smb/SmbComponentConnectionIT.java

fixes https://issues.apache.org/jira/browse/CAMEL-21291

Fixed Smb producer issues with required headers and default FileExist param

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportQuarkus.java
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/spring-boot-pom.tmpl

only when necessary
Closes CAMEL-21294

fix(jbang): include platform-http dependency

---

components/camel-spring-ws/src/test/resources/org/apache/camel/component/spring/ws/ConsumerEndpointMappingByBeanNameRouteTest-context.xml
components/camel-spring-ws/src/test/resources/org/apache/camel/component/spring/ws/ConsumerEndpointMappingResponseHandlingRouteTest-context.xml
components/camel-spring-ws/src/test/resources/org/apache/camel/component/spring/ws/ProducerLocalRouteTest-context.xml
components/camel-spring-ws/src/test/resources/org/apache/camel/component/spring/ws/SoapHeaderTest-context.xml
components/camel-spring-ws/src/test/resources/org/apache/camel/component/spring/ws/SoapResponseAttachmentTest-context.xml
components/camel-spring-ws/src/test/resources/org/apache/camel/component/spring/ws/addresing/CamelDirectSenderTest-context.xml
components/camel-spring-ws/src/test/resources/org/apache/camel/component/spring/ws/addresing/ConsumerWSAParamsActionTests-context.xml
components/camel-spring-ws/src/test/resources/org/apache/camel/component/spring/ws/addresing/ConsumerWSAParamsTOTests-context.xml
components/camel-spring-ws/src/test/resources/org/apache/camel/component/spring/ws/addresing/ProducerParamsBasicTest-context.xml
components/camel-spring-ws/src/test/resources/org/apache/camel/component/spring/ws/addresing/ProducerParamsPrecedenceTest-context.xml

Some tests were failing + align tests to have same structure (processor instead of bean)

Fix and update spring ws tests

---

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc

Fix typo Kubenetes --> Kubernetes

---

components/camel-cxf/camel-cxf-rest/src/main/java/org/apache/camel/component/cxf/jaxrs/CxfRsProducer.java
components/camel-cxf/camel-cxf-soap/src/main/java/org/apache/camel/component/cxf/jaxws/CxfProducer.java

CAMEL-21309: camel-cxf - Force using sync client when using tracing/opentelemetry as otherwise spans are not working correctly.

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportCamelMain.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportSpringBoot.java

Tested all the runtime combinations with run and export. All running now.
Closes CAMEL-21301

fix(dsl): jbang run/export contract first API

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportCamelMain.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportSpringBoot.java

Verified with 4.8.x branch resources.
Closes CAMEL-21301

[Backport 4.8.x] fix(dsl): jbang run/export contract first API

---

test-infra/camel-test-infra-azure-common/src/test/resources/org/apache/camel/test/infra/azure/common/services/container.properties

will avoid this kind of test to afail https://ci-builds.apache.org/job/Camel/job/Camel%20Core%20(Build%20and%20test)/job/main/433/testReport/junit/org.apache.camel.component.azure.storage.blob.integration/BlobChangeFeedOperationsIT/BuildAndTest___Matrix___JDK_NAME____jdk_21_latest___PLATFORM____ubuntu_avx____Test______/
with this kind of error:
```
Status code 400, "<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
<Code>InvalidHeaderValue</Code>
<Message>The API version 2024-11-04 is not supported by Azurite. Please upgrade Azurite to latest version and retry. If you are using Azurite in Visual Studio, please check you have installed latest Visual Studio patch. Azurite command line parameter "--skipApiVersionCheck" or Visual Studio Code configuration "Skip Api Version …
```

Upgrade test container for Azure to fix test on main branch

---

test-infra/camel-test-infra-infinispan/src/test/resources/org/apache/camel/test/infra/infinispan/services/container.properties

Upgrade Infinispan Container image to version 15.0.9.Final

---

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc

… traits
Update documentation to match the actual behavior.

CAMEL-21317: Camel jbang kubernetes documentation fix route/ingress

---

components/camel-hashicorp-vault/src/test/java/org/apache/camel/component/hashicorp/vault/integration/HashicorpVaultPropertiesSourceNoEnvTestIT.java

Enable automated property function test

---

components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Operations.java
components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Producer.java
components/camel-aws/camel-aws2-s3/src/test/java/org/apache/camel/component/aws2/s3/integration/S3HeadBucketIT.java
components/camel-aws/camel-aws2-s3/src/test/java/org/apache/camel/component/aws2/s3/integration/S3HeadObjectIT.java

CAMEL-21262 - Camel-AWS2-S3: Explicitly add Producer operations HeadObject and HeadBucket

---

components/camel-ai/camel-torchserve/pom.xml

The TorchServer container is provided for amd64 and arm64 architecture only
see https://hub.docker.com/layers/pytorch/torchserve/0.12.0-cpu/images/sha256-f1a6527977567c1f12cbf93e5bf955387ea0f40eaf8c32480b297915359b1652?context=explore
it was causing test failures pn main branch build, for instance see https://ci-builds.apache.org/job/Camel/job/Camel%20Core%20(Build%20and%20test)/job/main/lastCompletedBuild/testReport/org.apache.camel.component.torchserve.it/InferenceIT/

Skip IT tests for TorchServe on s390x and ppc64le

---

test-infra/camel-test-infra-fhir/src/test/resources/org/apache/camel/test/infra/fhir/services/container.properties

Upgrade hapi (fhir) container to 7.4.0 in tests

---

camel-dependencies/pom.xml
components/camel-zeebe/pom.xml
core/camel-util/src/main/java/org/apache/camel/util/SensitiveUtils.java
docs/user-manual/modules/ROOT/pages/camel-report-maven-plugin.adoc
parent/pom.xml
tests/camel-itest/pom.xml
tooling/maven/sync-properties-maven-plugin/src/main/java/org/apache/camel/maven/sync/properties/SyncPropertiesMojo.java

Cherry pick of CAMEL-21252 to 4.8.x branch

CAMEL-21252 Add checking for non .*-versions to sync-properties-maven-plugin (#15653)

---

parent/pom.xml

Issue: https://issues.apache.org/jira/browse/CAMEL-21310

[CAMEL-21310] camel-jackson - Upgrade to 2.18

---

components/camel-kamelet/src/main/java/org/apache/camel/component/kamelet/Kamelet.java
components/camel-kamelet/src/main/java/org/apache/camel/component/kamelet/KameletComponent.java
core/camel-api/src/main/java/org/apache/camel/RouteTemplateContext.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/debugger/DefaultBacklogDebugger.java
core/camel-base/src/main/java/org/apache/camel/component/properties/EnvPropertiesFunction.java
core/camel-base/src/main/java/org/apache/camel/component/properties/ServiceHostPropertiesFunction.java
core/camel-base/src/main/java/org/apache/camel/component/properties/ServicePortPropertiesFunction.java
core/camel-base/src/main/java/org/apache/camel/component/properties/ServicePropertiesFunction.java
core/camel-core-engine/src/main/java/org/apache/camel/impl/DefaultModel.java
core/camel-core-model/src/main/java/org/apache/camel/model/DefaultRouteTemplateContext.java
core/camel-main/src/main/java/org/apache/camel/main/MainHelper.java
core/camel-support/src/main/java/org/apache/camel/support/LanguageHelper.java
core/camel-util/pom.xml
core/camel-util/src/main/java/org/apache/camel/util/FilePathResolver.java
core/camel-util/src/main/java/org/apache/camel/util/IOHelper.java
core/camel-util/src/test/java/org/apache/camel/util/IOHelperTest.java

camel-core: Lookup ENV variable should use IOHelper to be consistent, and also support camelCase style to have more human readable keys and still match ENV variables that are UPPER_CASE with underscores only.
Allow Kamelets configured by EnvVars only
- Consider environment variables when validating Kamelet parameter configuration
- Avoids errors due to missing required Kamelet parameter validation when parameter is configured via environment variables

[BACKPORT-4.8.x] CAMEL-21276, CAMEL-21336

---

components/camel-seda/src/main/java/org/apache/camel/component/seda/SedaConsumer.java

Fix for https://issues.apache.org/jira/browse/CAMEL-21343
The component camel-vm is still frequently used by the community so even if it has been decided to remove it from camel, we need to provide a way to mimic its behavior to ease the migration to recent camel versions.
* Add methods meant to be overridden to mimic the behavior of camel-vm

CAMEL-21343: camel-seda - Allow to mimic the behavior of camel-vm

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerAutoInstResumeRouteStrategyIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentGroupIdIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentWithCustomSerializerIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentWithProcessorIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/common/KafkaTestUtil.java
components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryEagerIT.java
components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryNonEagerIT.java
components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryPersistenceIT.java
test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/ContainerLocalAuthKafkaService.java
test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/ContainerLocalKafkaService.java
test-infra/camel-test-infra-kafka/src/test/resources/org/apache/camel/test/infra/kafka/services/container.properties

Updated the kafka test infrastructure to use the Apache Kafka docker image v3.8.0.
The latest Kafka module in Testcontainers has no option to use zookeeper.  (Kafka introduced KRaft to remove it's dependence on zookeeper for metadata management.)
Topics were created explicitly in a number of tests since relying 'autocreation' to create new topics while retrieving topic metatdata often returned no partition information even thought the topic had been created.

CAMEL-20593: use ASF docker image

---

components/camel-opensearch/pom.xml
test-infra/camel-test-infra-opensearch/src/test/java/org/apache/camel/test/infra/opensearch/common/OpenSearchProperties.java
test-infra/camel-test-infra-opensearch/src/test/java/org/apache/camel/test/infra/opensearch/services/OpenSearchLocalContainerService.java
test-infra/camel-test-infra-opensearch/src/test/resources/org/apache/camel/test/infra/opensearch/services/container.properties

given that it was still failing on CI, reverting changes related to activating them on ppc64le

Revert open search ppc64 le not working

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportSpringBoot.java
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/main-kubernetes-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/spring-boot-kubernetes-pom.tmpl
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java

https://issues.apache.org/jira/browse/CAMEL-21349

[CAMEL-21349] Add support for camel spring-boot on OpenShift

---

components/camel-solr/pom.xml

despite the architecture being provided on Docker hub https://hub.docker.com/layers/library/solr/9.7.0-slim/images/sha256-e474e41543c8a0f9d6c112656b3bc26c5ded6e7c7c877387fa247afe2dfdb728?context=explore , the image seems to never successfully start on Jenkins CI. Even if it is marked with failed only one time in a row by jenkins, it is in failed state in all available builds so I suspect it never worked.
https://ci-builds.apache.org/job/Camel/job/Camel%20Core%20(Build%20and%20test)/job/main/lastCompletedBuild/testReport/org.apache.camel.component.solr.integration/SolrCloudProducerIT/BuildAndTest___Matrix___JDK_NAME____jdk_17_latest___PLATFORM____ppc64le____Test______/

chore: deactivate solr Integration tests on ppc64le

---

core/camel-core/src/test/java/org/apache/camel/impl/engine/DefaultSupervisingRouteControllerTest.java

it is a test which is regularly failing on CI, the intent is to help on investigation. (failed 2 times in a row on latest build: https://ci-builds.apache.org/job/Camel/job/Camel%20Core%20(Build%20and%20test)/job/main/lastCompletedBuild/testReport/org.apache.camel.impl.engine/DefaultSupervisingRouteControllerTest/BuildAndTest___Matrix___JDK_NAME____jdk_17_latest___PLATFORM____s390x____Test___testSupervising_2/ )

chore: provide more details in assertion message for DefaultSupervisingRouteControllerTest.testSupervising()

---

tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/CamelVersionHelper.java
tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/JavadocHelper.java
tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/PackageHelper.java
tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/ReflectionHelper.java
tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/Strings.java

CAMEL-21356 - Javadoc compliance with doclint for Java 17 in camel-tooling-util

---

core/camel-api/src/generated/java/org/apache/camel/spi/ApiMethod.java
core/camel-api/src/generated/java/org/apache/camel/spi/ApiParam.java
core/camel-api/src/generated/java/org/apache/camel/spi/ApiParams.java
core/camel-api/src/generated/java/org/apache/camel/spi/AsEndpointUri.java
core/camel-api/src/generated/java/org/apache/camel/spi/AsPredicate.java
core/camel-api/src/generated/java/org/apache/camel/spi/Metadata.java
core/camel-api/src/generated/java/org/apache/camel/spi/UriEndpoint.java
core/camel-api/src/generated/java/org/apache/camel/spi/UriParam.java
core/camel-api/src/generated/java/org/apache/camel/spi/UriPath.java
core/camel-api/src/generated/java/org/apache/camel/spi/annotations/HealthCheck.java
core/camel-api/src/generated/java/org/apache/camel/spi/annotations/Language.java
tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/Strings.java
tooling/camel-util-json/src/main/java/org/apache/camel/util/json/Jsoner.java
tooling/spi-annotations/src/main/java/org/apache/camel/spi/ApiMethod.java
tooling/spi-annotations/src/main/java/org/apache/camel/spi/ApiParam.java
tooling/spi-annotations/src/main/java/org/apache/camel/spi/ApiParams.java
tooling/spi-annotations/src/main/java/org/apache/camel/spi/AsEndpointUri.java
tooling/spi-annotations/src/main/java/org/apache/camel/spi/AsPredicate.java
tooling/spi-annotations/src/main/java/org/apache/camel/spi/Metadata.java
tooling/spi-annotations/src/main/java/org/apache/camel/spi/UriEndpoint.java
tooling/spi-annotations/src/main/java/org/apache/camel/spi/UriParam.java
tooling/spi-annotations/src/main/java/org/apache/camel/spi/UriPath.java
tooling/spi-annotations/src/main/java/org/apache/camel/spi/annotations/HealthCheck.java
tooling/spi-annotations/src/main/java/org/apache/camel/spi/annotations/Language.java

CAMEL-21356 - Javadoc compliance with doclint for Java 17 in spi-annotations, tooling-model and util-json

---

docs/user-manual/modules/ROOT/pages/building.adoc

Point changes from #15993 to the correct link and adjust description.

Fix building Camel from source link

---

components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpProducer.java

- Add root cause error details in exception message when Http connection to Knative broker has failed
- Includes SSL handshake error details for better failure analysis when using secure Http connections

chore: Improve Knative Http connection error details

---

components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpProducer.java

- Add root cause error details in exception message when Http connection to Knative broker has failed
- Includes SSL handshake error details for better failure analysis when using secure Http connections

[BACKPORT-4.8.x] chore: Improve Knative Http connection error details

---

test-infra/camel-test-infra-qdrant/src/test/resources/org/apache/camel/test/infra/qdrant/services/container.properties

chore: update qdrant container used for integration tests to 1.12.1

---

test-infra/camel-test-infra-cassandra/src/test/resources/org/apache/camel/test/infra/cassandra/services/container.properties

chore: Update container image used in test for cassandra to 5.0.2

---

components/camel-cxf/camel-cxf-rest/src/main/java/org/apache/camel/component/cxf/jaxrs/CxfRsProducer.java
components/camel-cxf/camel-cxf-soap/src/main/java/org/apache/camel/component/cxf/jaxws/CxfProducer.java
components/camel-direct/src/main/java/org/apache/camel/component/direct/DirectProducer.java
components/camel-opentelemetry/pom.xml
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/AsyncCxfTest.java
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/CurrentSpanTest.java
components/camel-tracing/src/main/java/org/apache/camel/tracing/ActiveSpanManager.java
core/camel-api/src/generated/java/org/apache/camel/ExchangeConstantProvider.java
core/camel-api/src/main/java/org/apache/camel/Exchange.java
core/camel-api/src/main/java/org/apache/camel/ExchangePropertyKey.java

Camel 21302

---

components/camel-jsonpath/src/test/java/org/apache/camel/jsonpath/JsonPathChoiceReaderTest.java
core/camel-base/src/generated/java/org/apache/camel/converter/CamelBaseBulkConverterLoader.java
core/camel-base/src/main/java/org/apache/camel/converter/IOConverter.java

CAMEL-21371: camel-core - Add converter for Reader to InputStream

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogKamelet.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/KameletCatalogHelper.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/pom.xml
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesBaseCommand.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesHelper.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesClientTest.java

https://issues.apache.org/jira/browse/CAMEL-21361
The root cause was a convoluted TCCL issue. In general, when you work with TCCL, you SHOULD reset it to its original value, like so ...
```
var tccLoader = Thread.currentThread().getContextClassLoader();
try {
ClassLoader cl = createClassLoader();
Thread.currentThread().setContextClassLoader(cl);
// do stuff
} finally {
Thread.currentThread().setContextClassLoader(tccLoader);
}
```

[CAMEL-21361] fabric8 kubernetes-client fails to connect to openshift

---

components/camel-aws/camel-aws-secrets-manager/src/main/docs/aws-secrets-manager-component.adoc
components/camel-azure/camel-azure-key-vault/src/main/docs/azure-key-vault-component.adoc
components/camel-google/camel-google-secret-manager/src/main/docs/google-secret-manager-component.adoc
components/camel-hashicorp-vault/src/main/docs/hashicorp-vault-component.adoc

Adding some documentation best practice to enhance vault security on cloud platforms.

chore(doc): suggest best security practice on cloud environments

---

components/camel-ai/camel-langchain4j-tools/src/main/docs/langchain4j-tools-component.adoc
components/camel-ai/camel-langchain4j-tools/src/main/java/org/apache/camel/component/langchain4j/tools/LangChain4jTools.java
components/camel-ai/camel-langchain4j-tools/src/main/java/org/apache/camel/component/langchain4j/tools/LangChain4jToolsProducer.java
components/camel-ai/camel-langchain4j-tools/src/test/java/org/apache/camel/component/langchain4j/tools/LangChain4jTooNoToolsIT.java

- stop throwing an exception
- set a header if no tool was called

CAMEL-21355: refine no tools called scenario

---

components/camel-opentelemetry/src/main/docs/opentelemetry.adoc

https://issues.apache.org/jira/browse/CAMEL-21387
Just some documentation about OpenTelemetry on Spring Boot
Thanks !

CAMEL-21387: camel-opentelemetry add some documentation for Spring Boot

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/CamelThreadDump.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/PluginHelper.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesDelete.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesHelper.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/PodLogs.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/PodLogsTest.java

https://issues.apache.org/jira/browse/CAMEL-21386
You can now do ...
```
[camel-cloud-examples]$ make k8s-run RUN_MODE=dev
```
or
```
[camel-cloud-examples]$ make oce-run RUN_MODE=dev
```
for all runtimes

[CAMEL-21386] camel k8s run --dev does not work on openshift

---

components/camel-knative/camel-knative-http/src/main/docs/knative-http-component.adoc
components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpProducer.java
components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpSupport.java
components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeOidcClientOptions.java
components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeOidcInterceptor.java
components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeSslClientOptions.java
components/camel-knative/camel-knative-http/src/test/java/org/apache/camel/component/knative/http/KnativeHttpServer.java
components/camel-knative/camel-knative-http/src/test/java/org/apache/camel/component/knative/http/KnativeHttpTest.java
components/camel-knative/camel-knative-http/src/test/resources/oidc/renewed_token.txt
components/camel-knative/camel-knative-http/src/test/resources/oidc/token.txt

- Adds OpenID Connect support to Knative Http client
- Autoconfigure options via system property or environment variables
- Sets proper Authorization headers with access token on each request
- Renew OIDC tokens on forbidden response
- Disable token cache
See CAMEL-21383

CAMEL-21383: Add Knative client OIDC support

---

parent/pom.xml

CAMEL-21393: Upgrade to Jackson 2.18.1

---

dsl/camel-jbang/camel-jbang-plugin-k/src/main/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationRun.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/BaseTrait.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/RouteTrait.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/Trait.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitCatalog.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitContext.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java

CAMEL-21369: camel-jbang kubernetes - add quarkus extensions configuration for Route trait

---

parent/pom.xml

[CAMEL-20883] Remove addPluginArtifactMetadata mojo usage

---

components/camel-ai/camel-djl/src/test/java/org/apache/camel/component/djl/CvImageEnhancementLocalTest.java
components/camel-minio/pom.xml
components/camel-smb/src/test/java/org/apache/camel/component/smb/SmbComponentIT.java
core/camel-core/src/test/java/org/apache/camel/component/controlbus/ControlBusFailRouteTest.java
core/camel-core/src/test/java/org/apache/camel/processor/MulticastParallelTimeoutStreamCachingTest.java

Disable some tests that are unreliable in some specific conditions.

(chores) disable unreliable tests

---

components/camel-smooks/src/main/java/org/apache/camel/component/smooks/SmooksProcessor.java
components/camel-smooks/src/test/java/org/apache/camel/component/smooks/SmooksProcessorTest.java

* Allow byte array in body to be processed in Smooks component
* Require body to be source

Allow byte array in body to be processed in Smooks component

---

components/camel-jetty/src/test/java/org/apache/camel/component/jetty/JettySessionSupportTest.java

CAMEL-21417: Fix JettySessionSupportTest

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Debug.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Export.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportSpringBoot.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/CamelReceiveAction.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/CamelSourceTop.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/action/MessageTableHelper.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/CamelProcessorTop.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/CamelRouteTop.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/ListCircuitBreaker.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/ListHealth.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/ListProperties.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/MetadataHelper.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/support/StubComponentResolver.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/MountTrait.java

- Simplify switch expressions
- Break a few large methods
- Use simpler methods/expressions
- Use lambdas
- Use more efficient operations

(chores) camel-jbang: minor cleanups

---

components/camel-opentelemetry/src/main/docs/opentelemetry.adoc

Updates broken link to agent documentation

camel-opentelemetry: Updates broken link in doc

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogDoc.java
dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

Upgrade Camel Kamelets to version 4.8.1

---

test-infra/camel-test-infra-aws-v2/src/test/resources/org/apache/camel/test/infra/aws2/services/container.properties

Upgrade Localstack test infra image to version 3.8.1

---

components/camel-ai/camel-pinecone/src/main/java/org/apache/camel/component/pinecone/PineconeVectorDbProducer.java
components/camel-ai/camel-pinecone/src/test/java/org/apache/camel/component/pinecone/it/PineconeComponentIT.java
parent/pom.xml

Upgrade Pinecone Client to version 3.0.0

---

components/camel-rest-openapi/src/main/java/org/apache/camel/component/rest/openapi/RestOpenApiProcessor.java

Changed the behavior to include media types from all existing responses when generating produces string. [CAMEL-21430](https://issues.apache.org/jira/browse/CAMEL-21430) links to information about previous behavior.

CAMEL-21430 Generated produces string now includes media types from all responses.

---

components/camel-smooks/src/main/java/org/apache/camel/component/smooks/SmooksProcessor.java
components/camel-smooks/src/test/java/org/apache/camel/component/smooks/SmooksProcessorTest.java
parent/pom.xml

Allow CamelContext to be inherited in Smooks pipeline

Allow CamelContext to be inherited in Smooks pipeline

---

components/camel-jpa/pom.xml
components/camel-paho/src/test/java/org/apache/camel/component/paho/PahoComponentTest.java

This PR enables camel-JPA and camel-paho tests on s390x

Enable camel-JPA and camel-paho tests on s390x

---

parent/pom.xml

Removed dead property placeholder for opensearch

---

components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/properties/BasePropertiesFunction.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/properties/ConfigMapPropertiesFunctionTest.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/properties/SecretPropertiesFunctionTest.java

CAMEL-21446: Fixes key resolution with default

---

components/camel-opentelemetry/src/main/docs/opentelemetry.adoc

chore(doc): local testing collector server

---

components/camel-observability-services/pom.xml
components/camel-observability-services/src/main/docs/observability-services.adoc
components/camel-observability-services/src/main/resources/observability-services.properties

Ref https://issues.apache.org/jira/browse/CAMEL-21462

feat(components): add opentelemetry into observability services

---

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/TransformMessageITCase.java
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/JBangTestSupport.java
dsl/camel-jbang/camel-jbang-it/src/test/resources/jbang/it/data-mapping/components/data.xml
dsl/camel-jbang/camel-jbang-it/src/test/resources/jbang/it/data-mapping/components/transform.xml
dsl/camel-jbang/camel-jbang-it/src/test/resources/jbang/it/data-mapping/data-formats/data.csv
dsl/camel-jbang/camel-jbang-it/src/test/resources/jbang/it/data-mapping/src/data.json
dsl/camel-jbang/camel-jbang-it/src/test/resources/jbang/it/data-mapping/src/transform.yaml

Adds tests for [message transformation](https://camel.apache.org/manual/camel-jbang.html#_transforming_message_data_mapping).

CAMEL-20367: Adds data mapping tests

---

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/knative/KnativeServiceTrait.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportKnativeTest.java

Camel-21457: Add knative service timeout on jbang plugin kubernetes

---

components/camel-dhis2/camel-dhis2-component/src/main/docs/dhis2-component.adoc

Add YAML route examples for DHIS2 component

Add YAML route examples for DHIS2 component

---

components/camel-platform-http-jolokia/src/main/docs/platform-http-jolokia.adoc
components/camel-platform-http-jolokia/src/main/java/org/apache/camel/component/platform/http/plugin/DefaultJolokiaPlatformHttpPlugin.java
tests/camel-itest/src/test/java/org/apache/camel/itest/security/GreeterClientTest.java

chore(components): add a warning when missing jolokia policies

---

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java

https://issues.apache.org/jira/browse/CAMEL-21464

[CAMEL-21464] camel k8s run ... may lead to exec format error

---

components/camel-observability-services/pom.xml
components/camel-observability-services/src/main/docs/observability-services.adoc
components/camel-observability-services/src/main/resources/observability-services.properties

feat(components): add health to observability services

---

.github/dependabot.yml
parent/pom.xml

Some background here: https://github.com/apache/camel-quarkus/issues/6813.

Downgrade software.amazon.kinesis:amazon-kinesis-client to 2.6.0

---

components/camel-observability-services/pom.xml
components/camel-observability-services/src/main/docs/observability-services.adoc
docs/user-manual/modules/ROOT/pages/jmx.adoc

feat(components): add management to observability services

---

components/camel-datasonnet/pom.xml
parent/pom.xml

CAMEL-21470: camel-datasonnet - Upgrade to 3.0.0

---

dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-kubernetes-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/spring-boot-kubernetes-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/spring-boot-pom.tmpl

chore: Upgrade Jolokia version in Camel JBang exported project

---

components/camel-opentelemetry/src/main/docs/opentelemetry.adoc

[Camel 4.8.x] chore(doc): spring boot configuration required

---

dsl/camel-jbang/camel-jbang-core/src/main/resources/quarkus-docker/Dockerfile.jvm
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/Dockerfile.tmpl

chore: Update docker base image version for Camel JBang exported project

---

dsl/camel-jbang/camel-jbang-plugin-k/src/test/java/org/apache/camel/dsl/jbang/core/commands/k/IntegrationExportTest.java

chore(test): Deactivate failing k plugin test

---

core/camel-core-engine/src/main/java/org/apache/camel/impl/DefaultModel.java
core/camel-core-model/src/main/java/org/apache/camel/model/RouteTemplateDefinition.java
core/camel-core/src/test/java/org/apache/camel/builder/RouteTemplateDuplicateIdIssueTest.java
core/camel-core/src/test/java/org/apache/camel/builder/RouteTemplateStepIdTest.java
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_8.adoc
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_9.adoc

CAMEL-21475: camel-yaml-dsl - Using route templates with hardcoded ids problem

---

components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/OpenTelemetrySpanAdapter.java
components/camel-tracing/src/main/java/org/apache/camel/tracing/ActiveSpanManager.java
components/camel-tracing/src/main/java/org/apache/camel/tracing/Tracer.java

Useful to debug tracing components.
Ref CAMEL-21472

chore(components): add debugging traces

---

core/camel-api/src/main/java/org/apache/camel/spi/ReloadStrategy.java
core/camel-console/src/main/java/org/apache/camel/impl/console/ContextDevConsole.java
core/camel-console/src/main/java/org/apache/camel/impl/console/ReloadDevConsole.java
core/camel-support/src/main/java/org/apache/camel/support/DefaultContextReloadStrategy.java
core/camel-support/src/main/java/org/apache/camel/support/FileWatcherResourceReloadStrategy.java
core/camel-support/src/main/java/org/apache/camel/support/ResourceReloadStrategySupport.java
core/camel-support/src/main/java/org/apache/camel/support/RouteOnDemandReloadStrategy.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/CamelContextStatus.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/ListProcess.java

CAMEL-21481: camel-jbang - Capture reload error when doing route reloads

---

components/camel-azure/camel-azure-key-vault/src/main/docs/azure-key-vault-component.adoc

- [] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).

Camel-Azure-Key-Vault: Docs updated

---

components/camel-azure/camel-azure-key-vault/src/main/docs/azure-key-vault-component.adoc
components/camel-opentelemetry/src/main/docs/opentelemetry.adoc
core/camel-core-engine/src/main/docs/modules/eips/pages/aggregate-eip.adoc
docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc
docs/user-manual/modules/ROOT/pages/security.adoc

Minor review of some of the docs changed during 4.9 development.

(chores) docs: minor grammar fixes for documents updated in 4.9

---

components/camel-ai/camel-langchain4j-tools/src/main/docs/langchain4j-tools-component.adoc

CAMEL-21502: fixed incorrect reference to the chat component

---

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/IngressTrait.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java

CAMEL-21456 : camel-jbang-kubernetes - Add TLS support to ingress trait

---

parent/pom.xml

Revert "chore(deps): Bump io.fabric8:knative-model from 6.13.4 to 7.0.0"

---

core/camel-core-reifier/src/main/java/org/apache/camel/reifier/ProcessorReifier.java
core/camel-core/src/test/java/org/apache/camel/util/DumpModelAsYamlTransformRouteTest.java
core/camel-core/src/test/resources/org/apache/camel/util/transform2.yaml
core/camel-yaml-io/src/main/java/org/apache/camel/yaml/io/ModelJSonSchemaResolver.java
core/camel-yaml-io/src/main/java/org/apache/camel/yaml/io/YamlWriter.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/TransformRoute.java
dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/TransformTest.java
dsl/camel-jbang/camel-jbang-core/src/test/resources/transform-out.yaml
dsl/camel-jbang/camel-jbang-core/src/test/resources/transform.xml
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/KameletMain.java

camel-jbang - Fix transform route

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/google-pubsub-lite.json
components/camel-google/camel-google-pubsub-lite/pom.xml
components/camel-google/camel-google-pubsub-lite/src/generated/resources/META-INF/org/apache/camel/component/google/pubsublite/google-pubsub-lite.json
components/camel-google/camel-google-pubsub-lite/src/generated/resources/META-INF/services/org/apache/camel/component.properties
components/camel-google/camel-google-pubsub-lite/src/main/docs/google-pubsub-lite-component.adoc
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_10.adoc
dsl/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/StaticEndpointBuilders.java
dsl/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/dsl/GooglePubsubLiteEndpointBuilderFactory.java

CAMEL-21517: Deprecate camel-google-pubsub-lite

---

dsl/camel-jbang/camel-jbang-container/Dockerfile
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogDoc.java
dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

Upgrade default versions in Camel JBang to 4.9.0

---

core/camel-xml-jaxb/pom.xml

[CAMEL-21520] OSGi ErrorHandler package missing in import package

---

components/camel-openapi-java/src/test/java/org/apache/camel/openapi/RestOpenApiReaderTest.java

[CAMEL-21531]RestOpenApiReaderTest is broken for some locations

---

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportBaseTest.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportKnativeTest.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java

https://issues.apache.org/jira/browse/CAMEL-21533

CAMEL-21533: camel-jbang - Backport Knative test coverage to 4.8.x

---

components/camel-mongodb/pom.xml
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbFindOperationIT.java
test-infra/camel-test-infra-mongodb/src/test/java/org/apache/camel/test/infra/mongodb/common/MongoDBProperties.java
test-infra/camel-test-infra-mongodb/src/test/java/org/apache/camel/test/infra/mongodb/services/MongoDBLocalContainerService.java
test-infra/camel-test-infra-mongodb/src/test/resources/org/apache/camel/test/infra/mongodb/services/container.properties

[CAMEL-21537]: Enable ppc64le support for mongodb

---

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesDelete.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesDeleteTest.java

https://issues.apache.org/jira/browse/CAMEL-21466

CAMEL-21466: camel-jbang - camel k8s delete may not cleanup properly

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogDoc.java
dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

Upgrade Kamelets to 4.8.2

---

core/camel-api/src/main/java/org/apache/camel/spi/CompilePreProcessor.java
dsl/camel-dsl-support/src/main/java/org/apache/camel/dsl/support/RouteBuilderLoaderSupport.java
dsl/camel-java-joor-dsl/src/main/java/org/apache/camel/dsl/java/joor/Helper.java
dsl/camel-java-joor-dsl/src/main/java/org/apache/camel/dsl/java/joor/JavaRoutesBuilderLoader.java
dsl/camel-java-joor-dsl/src/test/java/org/apache/camel/dsl/java/joor/HelperTest.java
dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/ExportTest.java
dsl/camel-jbang/camel-jbang-core/src/test/resources/MyKafkaRepo.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/KameletMain.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/JavaKnownImportsDownloader.java
tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/ArtifactModel.java

CAMEL-21542: camel-jbang - Detect known beans from Java imports

---

components/camel-opentelemetry/src/main/docs/opentelemetry.adoc

doc(component): OpenTelemetry zero code SDK autoconfiguration

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Export.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesBaseCommand.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesDelete.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesHelper.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesPlugin.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesPodLogs.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesPodLogsTest.java

https://issues.apache.org/jira/browse/CAMEL-21510

CAMEL-21510: camel-jbang - Kubernetes plugin support for parameter name

---

components/camel-observation/src/main/docs/observation.adoc
components/camel-opentelemetry/src/main/docs/opentelemetry.adoc
components/camel-tracing/src/main/docs/tracing.adoc
components/camel-tracing/src/main/java/org/apache/camel/tracing/ActiveSpanManager.java
components/camel-tracing/src/main/java/org/apache/camel/tracing/Tracer.java
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_10.adoc
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide.adoc

Favoring instead the instrumentation provided into each specific tracing framework.
Closes CAMEL-21538

feat(components): deprecate tracing MDC

---

components/camel-hashicorp-vault/src/main/java/org/apache/camel/component/hashicorp/vault/HashicorpVaultPropertiesFunction.java
core/camel-main/src/main/java/org/apache/camel/main/BaseMainSupport.java
core/camel-main/src/main/java/org/apache/camel/main/DefaultConfigurationConfigurer.java
dsl/camel-kamelet-main/src/main/resources/camel-main-known-dependencies.properties

hashicorp vault

---

parent/pom.xml

There is a CVE in version 0.29.0

Upgrade DJL to version 0.31.0

---

components/camel-ai/camel-milvus/pom.xml
test-infra/camel-test-infra-milvus/src/test/java/org/apache/camel/test/infra/milvus/common/MilvusProperties.java
test-infra/camel-test-infra-milvus/src/test/java/org/apache/camel/test/infra/milvus/services/MilvusLocalContainerService.java
test-infra/camel-test-infra-milvus/src/test/resources/org/apache/camel/test/infra/milvus/services/container.properties

This pull request is to provide ppc64le support to camel-milvus component. Tested all changes on a PowerPC machine and x86 machine also. Log is attached bellow.
[camel-milvus test-infra log for ppc64le.txt](https://github.com/user-attachments/files/18207279/camel-milvus.test-infra.log.for.ppc64le.txt)
[camel-milvus log for ppc64le.txt](https://github.com/user-attachments/files/18207282/camel-milvus.log.for.ppc64le.txt)
[camel-milvus test-infra log for x86.txt](https://github.com/user-attachments/files/18207283/camel-milvus.test-infra.log.for.x86.txt)
[camel-milvus log for x86.txt](https://github.com/user-attachments/files/18207286/camel-milvus.log.for.x86.txt)

milvus ppc64le integration tests activation

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/ListProcess.java

[CAMEL-21563](https://issues.apache.org/jira/browse/CAMEL-21563)

CAMEL-21563 : camel-jbang ps option output in JSON

---

core/camel-base-engine/src/main/java/org/apache/camel/impl/debugger/DefaultBacklogDebugger.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/debugger/DefaultDebugger.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/MulticastProcessor.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Debug.java

camel-jbang - Debug to work with split eip

---

core/camel-core/src/test/java/org/apache/camel/component/file/FileConsumeFilesAndDeleteTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FromFileDoNotDeleteFileIfProcessFailsTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FromFileDoNotMoveFileIfProcessFailsTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/NewFileConsumeTest.java
core/camel-core/src/test/java/org/apache/camel/converter/NIOConverterTest.java
core/camel-core/src/test/java/org/apache/camel/issues/FilePollingConsumerIssueTest.java
core/camel-core/src/test/java/org/apache/camel/language/FileLanguageTest.java

CAMEL-20686 - set 7: review File tests for incorrectly shared resource

CAMEL-20686 - set 7: review File tests for incorrectly shared resource

---

core/camel-support/src/main/java/org/apache/camel/support/builder/ExpressionBuilder.java

[CAMEL-21572](https://issues.apache.org/jira/browse/CAMEL-21572): fix java.lang.NullPointerException when using SetHeader and Stub
SetHeader with a simple expression causes NullPointerException to be thrown because for runtime other than default (kamelet-main) JBang uses Stub instead of the actual component which produces null.
```
- setHeader: 
id: setHeader-c0db
name: SampleUUID
expression: 
simple: 
id: simple-536b
expression: >-
This is a sample UUID: 
${bean:type:java.util.UUID?method=randomUUID}
```

CAMEL-21572: fix java.lang.NullPointerException when using SetHeader and Stub

---

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/AS2MessageDispositionNotificationEntity.java
components/camel-cxf/camel-cxf-spring-soap/src/test/java/org/apache/camel/component/cxf/CxfOneWayRouteTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyProducerHangTest.java
components/camel-oaipmh/src/test/java/org/apache/camel/oaipmh/utils/MockOaipmhServer.java
tooling/camel-util-json/src/main/java/org/apache/camel/util/json/Yylex.java

Fix spelling

---

components/camel-azure/camel-azure-files/src/main/java/org/apache/camel/component/file/azure/FilesConsumer.java
components/camel-file/src/main/java/org/apache/camel/component/file/AntFilter.java
components/camel-file/src/main/java/org/apache/camel/component/file/FileConsumer.java
components/camel-file/src/main/java/org/apache/camel/component/file/GenericFileConsumer.java
components/camel-file/src/main/java/org/apache/camel/component/file/GenericFileEndpoint.java
components/camel-file/src/main/java/org/apache/camel/component/file/OptimizedFileFilter.java
components/camel-file/src/main/java/org/apache/camel/component/file/strategy/MarkerFileExclusiveReadLockStrategy.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpConsumer.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpUtils.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/RemoteFile.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/SftpConsumer.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/RemoteFileIgnoreDoPollErrorTest.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpMoveWithOutMessageTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FileConsumerFileFilterOptimizedTest.java
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_10.adoc

optimize camel-file when filtering files by name

---

NOTICE.txt

Updated year in NOTICE

---

components/camel-hashicorp-vault/pom.xml
test-infra/camel-test-infra-hashicorp-vault/src/test/java/org/apache/camel/test/infra/hashicorp/vault/common/HashicorpVaultProperties.java
test-infra/camel-test-infra-hashicorp-vault/src/test/java/org/apache/camel/test/infra/hashicorp/vault/services/HashicorpVaultLocalContainerService.java
test-infra/camel-test-infra-hashicorp-vault/src/test/resources/org/apache/camel/test/infra/hashicorp/vault/services/container.properties

[CAMEL-21581]: Enable ppc64le support for hashicorp-vault tests with dynamic container image selection

---

components/camel-microprofile/camel-microprofile-config/src/main/java/org/apache/camel/component/microprofile/config/CamelMicroProfilePropertiesSource.java

fixes https://issues.apache.org/jira/browse/CAMEL-21582
partially reverts some changes from https://github.com/apache/camel/pull/16661/

fixes CAMEL-21582, makes microprofiles properties loadable

---

components/camel-consul/pom.xml
components/camel-infinispan/camel-infinispan-embedded/src/test/java/org/apache/camel/component/infinispan/embedded/InfinispanEmbeddedClusteredConsumerTest.java
components/camel-zookeeper-master/pom.xml
components/camel-zookeeper/pom.xml
test-infra/camel-test-infra-common/src/test/java/org/apache/camel/test/infra/common/LocalPropertyResolver.java
test-infra/camel-test-infra-consul/src/test/resources/org/apache/camel/test/infra/consul/services/container.properties
test-infra/camel-test-infra-hashicorp-vault/src/test/java/org/apache/camel/test/infra/hashicorp/vault/common/HashicorpVaultProperties.java
test-infra/camel-test-infra-hashicorp-vault/src/test/java/org/apache/camel/test/infra/hashicorp/vault/services/HashicorpVaultLocalContainerService.java
test-infra/camel-test-infra-milvus/src/test/java/org/apache/camel/test/infra/milvus/common/MilvusProperties.java
test-infra/camel-test-infra-milvus/src/test/java/org/apache/camel/test/infra/milvus/services/MilvusLocalContainerService.java
test-infra/camel-test-infra-mongodb/src/test/java/org/apache/camel/test/infra/mongodb/common/MongoDBProperties.java
test-infra/camel-test-infra-mongodb/src/test/java/org/apache/camel/test/infra/mongodb/services/MongoDBLocalContainerService.java
test-infra/camel-test-infra-opensearch/src/test/java/org/apache/camel/test/infra/opensearch/common/OpenSearchProperties.java
test-infra/camel-test-infra-opensearch/src/test/java/org/apache/camel/test/infra/opensearch/services/OpenSearchLocalContainerService.java
test-infra/camel-test-infra-tensorflow-serving/src/test/java/org/apache/camel/test/infra/tensorflow/serving/common/TensorFlowServingProperties.java
test-infra/camel-test-infra-tensorflow-serving/src/test/java/org/apache/camel/test/infra/tensorflow/serving/services/TensorFlowServingLocalContainerService.java
test-infra/camel-test-infra-tensorflow-serving/src/test/resources/org/apache/camel/test/infra/tensorflow/serving/services/container.properties
test-infra/camel-test-infra-zookeeper/src/test/resources/org/apache/camel/test/infra/zookeeper/services/container.properties

Consolidate resolving platform-specific containers (ref.: #16688).

CAMEL-21585: resolve platform containers automatically

---

components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbFindOperationIT.java

CAMEL-21585: do not override containers in tests

---

components/camel-smb/src/test/java/org/apache/camel/component/smb/FromSmbFileSortByExpressionIT.java
components/camel-smb/src/test/java/org/apache/camel/component/smb/FromSmbRemoteFileFilterDirectoryIT.java
components/camel-smb/src/test/java/org/apache/camel/component/smb/FromSmbRemoteFileFilterIT.java
components/camel-smb/src/test/java/org/apache/camel/component/smb/FromSmbRemoteFileSorterIT.java
components/camel-smb/src/test/java/org/apache/camel/component/smb/SmbConsumerDirectoriesNotMatchedIT.java
components/camel-smb/src/test/java/org/apache/camel/component/smb/SmbConsumerExcludeExtIT.java
components/camel-smb/src/test/java/org/apache/camel/component/smb/SmbConsumerExcludeNameIT.java
components/camel-smb/src/test/java/org/apache/camel/component/smb/SmbConsumerIdempotentKeyChangedIssueIT.java
components/camel-smb/src/test/java/org/apache/camel/component/smb/SmbConsumerIncludeExtIT.java
components/camel-smb/src/test/java/org/apache/camel/component/smb/SmbRecursiveMaxDepthIT.java
components/camel-smb/src/test/java/org/apache/camel/component/smb/SmbRecursiveMinDepthIT.java
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_10.adoc

- Added note to 4.10 upgrade guide for SMB changes.
- Updated tests that create a number of remote files prior to execution so that there's a delay before the consumer starts polling.

CAMEL-21352: smb update housekeeping

---

.github/dependabot.yml
parent/pom.xml

Some background here: https://github.com/apache/camel-quarkus/issues/6813#issuecomment-2575158914.
(reverts https://github.com/apache/camel/commit/844cbbf30473a263619206047ff74a5f49ccd00d)

Downgrade amazon-kinesis-client to 2.6.0

---

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/OpenApiTrait.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/TraitHelper.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/AddonsBuilder.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/CamelBuilder.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/ContainerBuilder.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/EnvironmentBuilder.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/IngressBuilder.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/KnativeBuilder.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/KnativeServiceBuilder.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/MountBuilder.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/OpenapiBuilder.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/RouteBuilder.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/ServiceBindingBuilder.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/ServiceBuilder.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/TraitsBuilder.java

Backport of https://github.com/apache/camel/pull/16720

CAMEL-21278 : Camel Jbang Kubernetes plugin -  add builders to model

---

components/camel-solr/pom.xml
test-infra/camel-test-infra-solr/src/test/java/org/apache/camel/test/infra/solr/services/SolrContainer.java

This pull request is to provide ppc64le support to camel-solr component. 
It was giving error that java thread stack size is to small at time of container startup. That's why increased thread stack size.
Tested all changes on a PowerPC machine and x86 machine also. Log is attached bellow.
[camel-solr log on ppc64le.txt](https://github.com/user-attachments/files/18346487/camel-solr.log.on.ppc64le.txt)
[camel-solr test-infra log on ppc64le.txt](https://github.com/user-attachments/files/18346510/camel-solr.test-infra.log.on.ppc64le.txt)
[camel-solr test-infra x86 logs.txt](https://github.com/user-attachments/files/18346513/camel-solr.test-infra.x86.logs.txt)
[camel-solr x86 log.txt](https://github.com/user-attachments/files/18346515/camel-solr.x86.log.txt)

solr ppc64le integration tests activation

---

parent/pom.xml

Upgrade logback-version to 1.5.16 (same version that main is using).    Ran tests on rocketmq component (only component using logback-version)

Upgrade logback-version to 1.5.16

---

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc

This trivial PR fixes 3 wrong phrasings in the documentation.

fixed 3 wrong wordings

---

components/camel-wasm/pom.xml
components/camel-wasm/src/main/java/org/apache/camel/component/wasm/WasmProducer.java
components/camel-wasm/src/main/java/org/apache/camel/language/wasm/WasmExpression.java
components/camel-wasm/src/main/java/org/apache/camel/wasm/WasmFunction.java
parent/pom.xml

Since Chicory 1.0.0 has been released, I took the chance to update the integration.
Reference issue:
https://issues.apache.org/jira/browse/CAMEL-21569

CAMEL-21569 - Bump Chicory to 1.0.0

---

components/camel-aws/camel-aws-bedrock/src/main/java/org/apache/camel/component/aws2/bedrock/BedrockModels.java

CAMEL-21598 - Camel AWS Bedrock: Update supported models

---

components/camel-tracing/src/main/docs/tracing.adoc

This is the actual design and should be useful to understand any potential compatibility changes as described in #16753

doc(components): tracing actual design

---

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc

Add Minikube deployment example for Camel 4.9 with Camel JBang

---

core/camel-support/src/main/java/org/apache/camel/support/cache/SimpleLRUCache.java

Fix for https://issues.apache.org/jira/browse/CAMEL-21614
In some specific use cases, the eviction of the entries never ends
* Improve the way to swap the queue of change to avoid the race condition that could cause cache changes miss by leveraging a `ReadWriteLock` to only prevent change additions during the swap

CAMEL-21614: camel-core - Prevent cache change miss on queue swap

---

dsl/camel-jbang/camel-jbang-plugin-kubernetes/pom.xml
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesHelper.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java

https://issues.apache.org/jira/browse/CAMEL-21621

CAMEL-21621: camel-jbang - k8s-httpclient-vertx fails in shutdown hook

---

components/camel-kafka/src/main/docs/kafka-component.adoc
components/camel-quickfix/src/main/docs/quickfix-component.adoc
components/camel-salesforce/camel-salesforce-component/src/main/docs/salesforce-component.adoc
components/camel-saxon/src/main/docs/xquery-component.adoc
components/camel-xchange/src/main/docs/xchange-component.adoc
core/camel-api/src/main/java/org/apache/camel/cloud/ServiceHealth.java

docs: fix spelling

---

components/camel-tracing/src/main/java/org/apache/camel/tracing/TagConstants.java
components/camel-tracing/src/main/java/org/apache/camel/tracing/decorators/AbstractSpanDecorator.java
components/camel-tracing/src/test/java/org/apache/camel/tracing/decorators/AbstractSpanDecoratorTest.java

CAMEL-21622: Adds route id in the span tags

---

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesHelper.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java

https://issues.apache.org/jira/browse/CAMEL-21625

CAMEL-21625: camel k8s run may not cleanup properly on openshift

---

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc

Fixed Camel-JBang manual typo

---

components/camel-aws/camel-aws2-s3/pom.xml
components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/stream/AWS2S3StreamUploadProducer.java

CAMEL-21631 - Enable Checksum algorithm on S3 streaming upload producer

---

components/camel-elasticsearch-rest-client/pom.xml
components/camel-elasticsearch-rest-client/src/test/java/org/apache/camel/component/elasticsearch/rest/client/integration/ElasticsearchRestClientITSupport.java
test-infra/camel-test-infra-elasticsearch/src/main/java/org/apache/camel/test/infra/elasticsearch/services/ElasticSearchLocalContainerInfraService.java
test-infra/camel-test-infra-elasticsearch/src/main/resources/org/apache/camel/test/infra/elasticsearch/services/container.properties

[CAMEL-21633]: Enable ppc64le support for camel-elasticsearch-rest-client

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd
components/camel-spring-xml/pom.xml
components/camel-spring-xml/src/test/java/org/apache/camel/spring/CamelSpringXSDValidateTest.java
core/camel-api/src/generated/java/org/apache/camel/spi/annotations/ExternalSchemaElement.java
core/camel-core-model/src/main/java/org/apache/camel/model/app/BeansDefinition.java
core/camel-xml-io/src/generated/java/org/apache/camel/xml/in/ModelParser.java
core/camel-xml-io/src/generated/java/org/apache/camel/xml/out/ModelWriter.java
core/camel-xml-io/src/test/java/org/apache/camel/xml/in/ModelParserTest.java
core/camel-yaml-io/src/generated/java/org/apache/camel/yaml/out/ModelWriter.java
dsl/camel-xml-io-dsl/src/main/java/org/apache/camel/dsl/xml/io/XmlRoutesBuilderLoader.java
dsl/camel-xml-io-dsl/src/test/resources/org/apache/camel/dsl/xml/io/springBeans.xml
tooling/maven/camel-package-maven-plugin/src/main/resources/velocity/model-parser.vm
tooling/spi-annotations/src/main/java/org/apache/camel/spi/annotations/ExternalSchemaElement.java

Fix XSD to not have duplicate entry

---

components/camel-hashicorp-vault/src/main/docs/hashicorp-vault-component.adoc
components/camel-hashicorp-vault/src/main/java/org/apache/camel/component/hashicorp/vault/HashicorpVaultPropertiesFunction.java
docs/user-manual/modules/ROOT/pages/security.adoc

CAMEL-21640 - Camel-Hashicorp-Vault: Support Hashicorp Cloud deployment in properties function - Docs

---

test-infra/camel-test-infra-infinispan/src/main/resources/org/apache/camel/test/infra/infinispan/services/container.properties

Upgrade infinispan server for docker tests

---

components/camel-xslt-saxon/src/main/docs/xslt-saxon-component.adoc
components/camel-xslt/src/main/docs/xslt-component.adoc

Follwoing up https://issues.apache.org/jira/browse/CAMEL-20564, adding usage example to use a variable as an XSLT param.

CAMEL-20564: follow-up: adding variable usage example in component adoc

---

components/camel-hashicorp-vault/src/main/docs/hashicorp-vault-component.adoc

Camel-Hashicorp-Vault: Add more documentation for Hashicorp Vault Cloud

---

components/camel-platform-http-jolokia/src/main/java/org/apache/camel/component/platform/http/plugin/DefaultJolokiaPlatformHttpPlugin.java
parent/pom.xml

[CAMEL-21651] Upgrade to Jolokia 2.2.1

---

components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Consumer.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/AmazonSQSClientMock.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/SqsBatchConsumerConcurrentConsumersIT.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/SqsConsumerExtendMessageVisibilityTest.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/integration/SqsComponentLocalstackIT.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/integration/SqsComponentSendInOnlyLocalstackIT.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/integration/SqsProducerSendByteArrayLocalstackIT.java

Add a `deadline` to each entry to be extended via `TimeoutExtender`. This timeout is set to now plus 80% duration of the visibility timeout. Any message that would reach this deadline by the next execution of the TimeoutExtender is extended.
This cuts down the number of extend requests dramatically as the previous implementation would extend ALL messages, including those polled shortly before the execution of the extender.
This PR also changes the logging behavior in case the message could not be extended due to `ReceiptHandleIsInvalid`. This effectively aligns the logic to how it worked prior to using the batched operation where it would catch the exception `ReceiptHandleIsInvalidException`. The batch operation however does not throw this exception, instead the collection of failed …

CAMEL-21659: introduce deadline concept to TimeoutExtender

---

components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Consumer.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/AmazonSQSClientMock.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/SqsBatchConsumerConcurrentConsumersIT.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/SqsConsumerExtendMessageVisibilityTest.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/integration/SqsComponentSendInOnlyLocalstackIT.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/integration/SqsProducerSendByteArrayLocalstackIT.java

CAMEL-21659: introduce deadline concept to TimeoutExtender (#16945)

---

core/camel-core-engine/src/main/docs/modules/eips/pages/sample-eip.adoc

Fix the sample-eip doc examples, which had incorrectly used sample EIP. The correct way is: 
```xml 
<route>
<from uri="direct:sample"/>
<sample/>
<to uri="direct:sampled"/>
</route>
```

doc(sample-eip): correct XML examples

---

test-infra/camel-test-infra-kafka/src/main/resources/org/apache/camel/test/infra/kafka/services/container.properties

Upgrade strimzi kafka to 3.8.1

---

components/camel-cxf/camel-cxf-rest/src/main/java/org/apache/camel/component/cxf/jaxrs/CxfRsComponent.java
components/camel-cxf/camel-cxf-rest/src/test/java/org/apache/camel/component/cxf/jaxrs/CxfRsConsumerWithBeanTest.java

This fixes https://camel.zulipchat.com/#narrow/channel/257301-camel-spring-boot/topic/How.20to.20implement.20rest.20and.20soap.20routes.20in.20the.20same.20project/near/496322324

CAMEL-21683: Configure jax-rs consumer via CxfRsEndpoint bean

---

core/camel-api/src/main/java/org/apache/camel/FailedToCreateConsumerException.java
core/camel-api/src/main/java/org/apache/camel/FailedToCreateProducerException.java
core/camel-api/src/main/java/org/apache/camel/NoSuchEndpointException.java
core/camel-api/src/main/java/org/apache/camel/ResolveEndpointFailedException.java

feat(api): strengthen endpoint exceptions

---

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java

https://issues.apache.org/jira/browse/CAMEL-21686

CAMEL-21686: camel-jbang - Remove dependency on camel-kamelets-utils

---

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc
dsl/camel-jbang/camel-jbang-core/src/test/resources/application-jkube.properties
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/Container.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/ContainerBuilder.java

- Most of the Kubernetes environments require the container image push as part of the Kubernetes run command
- Set --image-push=true as a default value
- Remove container.image-push trait option in favor of using --image-push command option (the container trait is primarily to configure the container spec in the Kubernetes deployment Manifest)
- Skip image build and image push when printing the Kubernetes Manifest with --output option
Successfully executed the camel-jbang-plugin-kubernetes unit tests locally with these changes
Fixes CAMEL-21690

CAMEL-21690: Fix image-push option on Kubernetes run command

---

dsl/camel-jbang/camel-jbang-it/src/test/resources/jbang/it/joke.yaml

update test resources according to the new [KCRD](https://camel.apache.org/manual/camel-jbang.html#_running_camel_k_integrations_or_pipes)

camel-jbang-it: Update CRD on Camel K run

---

components/camel-aws/camel-aws-secrets-manager/src/main/java/org/apache/camel/component/aws/secretsmanager/vault/CloudTrailReloadTriggerTask.java

fixes https://issues.apache.org/jira/browse/CAMEL-21713

fixes CAMEL-21713: add endpoint url override to aws-secret-manager

---

components/camel-groovy/pom.xml
components/camel-groovy/src/main/docs/groovy-language.adoc
components/camel-groovy/src/main/java/org/apache/camel/language/groovy/GroovyExpression.java
components/camel-groovy/src/test/data/message1.xml
components/camel-groovy/src/test/java/org/apache/camel/language/groovy/GroovyLanguageTest.java

CAMEL-21717: camel-groovy - Make it easier to work with attachments

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/Hawtio.java

camel-jbang - Upgrade to hawtio 4.3.0

---

components/camel-csv/src/main/java/org/apache/camel/dataformat/csv/CsvMarshaller.java
components/camel-csv/src/test/java/org/apache/camel/dataformat/csv/CsvMarshalHeaderFromCsvFormatTest.java

https://issues.apache.org/jira/browse/CAMEL-21734

CAMEL-21734: camel-csv - Allow to configurer header via CsvFormat reference

---

components/camel-infinispan/camel-infinispan-embedded/src/test/resources/log4j2.component.properties

It fixes the unexpected folder `${sys:infinispan.server.log.path})` creation when compiling the `camel-infinispan-embedded`.

Ignoring log4j2-test.xml in infinispan-common test jar

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/smooks.json
components/camel-ai/camel-torchserve/pom.xml
components/camel-flowable/pom.xml
components/camel-fury/pom.xml
components/camel-observability-services/pom.xml
components/camel-smooks/pom.xml
components/camel-smooks/src/generated/resources/META-INF/org/apache/camel/component/smooks/smooks.json
components/camel-smooks/src/main/docs/smooks-component.adoc
parent/pom.xml

Ref https://github.com/netplex/json-smart-v2/issues/240

fix(ci): missing dependency workaround

---

components/camel-platform-http-main/src/main/java/org/apache/camel/component/platform/http/main/MainHttpServer.java

fix(components/platform-http-main): sanitize potential user input

---

components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/deployments/KubernetesDeploymentsProducer.java

fix(camel-kubernetes): Use the namespace header in deployments operations

---

components/camel-platform-http-main/src/main/java/org/apache/camel/component/platform/http/main/MainHttpServer.java

[Release 4.10.x] fix(components/platform-http-main): sanitize potential user input

---

components/camel-jetty-common/src/main/java/org/apache/camel/component/jetty/CamelContinuationServlet.java

fix(components/jetty-common): don't use user provided character encoding

---

components/camel-jetty-common/src/main/java/org/apache/camel/component/jetty/CamelContinuationServlet.java

[Release 4.10.x] fix(components/jetty-common): don't use user provided character encoding

---

components/camel-http-common/src/main/java/org/apache/camel/http/common/DefaultHttpBinding.java
components/camel-http-common/src/main/java/org/apache/camel/http/common/HttpHelper.java
components/camel-jetty/src/main/java/org/apache/camel/component/jetty12/AttachmentHttpBinding.java

fix(components): sanitize user values before logging

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelJBangMain.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Edit.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Shell.java

Adds edit command to camel-jbang cc @gnodet 
Thanks!

CAMEL-21723: camel-jbang add edit command

---

core/camel-main/src/main/java/org/apache/camel/main/BaseMainSupport.java

fixes https://issues.apache.org/jira/browse/CAMEL-21746

Removes second call to  DefaultConfigurationConfigurer.configureVaultRefresh

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogDoc.java
dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

CAMEL-21748 - Upgrade to Camel-Kamelets 4.10.0 in camel-jbang

---

dsl/camel-jbang/camel-jbang-it/pom.xml

Adds the possibility to configure the repo/branch for the jbang to install in the container, using `cli.jbang.repo` and `cli.service.branch` properties

camel-jbang-it: Configures repo/branch for the jbang installation

---

.gitignore
.mvn/develocity.xml
.mvn/extensions.xml

INFRA-26486: re-enable develocity

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java

CAMEL-21662: Use absolute location of pom.xml with "camel run"

---

components/camel-kamelet/src/main/docs/kamelet-component.adoc

chore(doc): adding a note to explain a Kamelet calling another Kamelet

---

tooling/camel-tooling-maven/src/main/java/org/apache/camel/tooling/maven/MavenDownloaderImpl.java

[CAMEL-21761] Use model cache for maven-resolver based downloader

---

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/CamelCatalogITCase.java

Adds tests for [camel catalog](https://camel.apache.org/manual/camel-jbang.html#_listing_what_camel_components_are_available)

CAMEL-20367: Adds camel catalog tests

---

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/LocalKameletsITCase.java
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/JBangTestSupport.java
dsl/camel-jbang/camel-jbang-it/src/test/resources/jbang/it/user-source.kamelet.yaml

Adds test for [running local Kamelets](https://camel.apache.org/manual/camel-jbang.html#_running_local_kamelets).

CAMEL-20367: Adds local Kamelets test

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaProducer.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/producer/support/DelegatingCallback.java

CAMEL-21788: DelegatingCallback invokes completion in wrong order.

---

components/camel-consul/src/main/java/org/apache/camel/component/consul/ConsulRegistry.java
core/camel-api/src/main/java/org/apache/camel/spi/Registry.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultDependencyInjectionAnnotationFactory.java
core/camel-core/src/test/java/org/apache/camel/impl/BindToRegistrySupplierBeanInitDestroyMethodTest.java
core/camel-support/src/main/java/org/apache/camel/support/DefaultRegistry.java
core/camel-support/src/main/java/org/apache/camel/support/SimpleRegistry.java
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_10.adoc
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_11.adoc
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/ExportTest.java
dsl/camel-xml-io-dsl/src/main/java/org/apache/camel/dsl/xml/io/XmlRoutesBuilderLoader.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/BeansDeserializer.java

CAMEL-21794: camel-jbang - Export bean with lazy-bean should not initialize the bean if not needed

---

components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/config_maps/KubernetesConfigMapsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/cronjob/KubernetesCronJobProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/deployments/KubernetesDeploymentsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/events/KubernetesEventsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/hpa/KubernetesHPAProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/job/KubernetesJobProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/persistent_volumes_claims/KubernetesPersistentVolumesClaimsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/pods/KubernetesPodsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/replication_controllers/KubernetesReplicationControllersProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/resources_quota/KubernetesResourcesQuotaProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/secrets/KubernetesSecretsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/service_accounts/KubernetesServiceAccountsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/services/KubernetesServicesProducer.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/producer/KubernetesConfigMapsProducerTest.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/producer/KubernetesCronJobProducerTest.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/producer/KubernetesDeploymentsProducerTest.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/producer/KubernetesEventsProducerTest.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/producer/KubernetesHPAProducerTest.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/producer/KubernetesJobProducerTest.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/producer/KubernetesPersistentVolumesClaimsProducerTest.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/producer/KubernetesPodsProducerTest.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/producer/KubernetesReplicationControllersProducerTest.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/producer/KubernetesResourcesQuotaProducerTest.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/producer/KubernetesSecretsProducerTest.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/producer/KubernetesServiceAccountsProducerTest.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/producer/KubernetesServicesProducerTest.java

Fix CAMEL-21738 - for namespaced resources, `list` and `listByLabels` operation now support either listing from all namespaces (when namespace header is empty) or in given namespace.

CAMEL-21738: camel-kubernetes: Use a common approach to listing namespaced resources

---

components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Consumer.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/Sqs2ConsumerTest.java

Change will stop exchange from extending after an error occurred in processing.

CAMEL-21769: camel-aws-sqs - Error is causing the sqs message to be extended forever

---

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc

Fix quotes for Camel Jbang deploy command example in documentation

---

dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/main-kubernetes-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/main-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-kubernetes-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/spring-boot-pom.tmpl

This PR enables by default the presence of [`camel-observability-services` component](https://camel.apache.org/components/next/others/observability-services.html) in all exported applications.

feat(dsl): jbang export default observability services

---

components/camel-ibm-secrets-manager/src/main/java/org/apache/camel/component/ibm/secrets/manager/IBMSecretsManagerPropertiesFunction.java
components/camel-ibm-secrets-manager/src/test/java/org/apache/camel/component/ibm/secrets/manager/integration/operations/IBMSecretsManagerNoEnvPropertiesSourceTestIT.java

CAMEL-21820 - Camel-IBM-Secrets-manager: Support Arbitrary secrets type in properties function

---

components/camel-salesforce/camel-salesforce-codegen/src/main/java/org/apache/camel/component/salesforce/codegen/AbstractSalesforceExecution.java
components/camel-salesforce/camel-salesforce-maven-plugin/README.md
components/camel-salesforce/camel-salesforce-maven-plugin/src/main/java/org/apache/camel/maven/AbstractSalesforceMojo.java
components/camel-salesforce/camel-salesforce-maven-plugin/src/test/java/org/apache/camel/maven/AbstractSalesforceMojoTest.java

This PR aims to add JWT Authentication in addition to the existing Username Password Authentication for the Camel Salesforce Maven Plugin.
There was an open Issue ( CAMEL-20118 ) regarding the same topic, therefore i used it as a reference in this PR.
Changes involve adjustments to the following modules:
- camel-salesforce-codegen
- accept keystoreParameters and jwtAudience
- camel-salesforce-maven-plugin
- update README.md
- add properties:
- jwtAudience
- keystoreResource
- keystorePassword
- keystoreType
- adjustment of property requirement flag ( password and clientSecret not marked as required anymore ) 
- custom validation to validate correct properties are provided

CAMEL-20118: Support JWT Authentication for Camel Salesforce Maven Plugin

---

components/camel-observability-services/src/main/docs/observability-services.adoc

chore(docs): remove temporary warning

---

docs/user-manual/modules/ROOT/pages/security.adoc

Camel-IBM-Secrets-Manager: Adding documentation in Security Asciidoc too

---

core/camel-main/src/main/java/org/apache/camel/main/DefaultConfigurationConfigurer.java

Camel-IBM-Secrets-Manager: Added configuration to Default Configurer

---

components/camel-minio/src/main/java/org/apache/camel/component/minio/MinioComponentVerifierExtension.java

CAMEL-19731 Implemented try-with-resources for MinioClient

CAMEL-19731 Implemented try-with-resources for MinioClient

---

core/camel-api/src/main/java/org/apache/camel/component/extension/ComponentExtension.java
core/camel-api/src/main/java/org/apache/camel/component/extension/ComponentVerifierExtension.java
core/camel-api/src/main/java/org/apache/camel/component/extension/ComponentVerifierExtensionHelper.java
core/camel-api/src/main/java/org/apache/camel/component/extension/MetaDataExtension.java

CAMEL-21837 - camel-api - Deprecate component.extension

---

components/camel-http/src/main/java/org/apache/camel/component/http/HttpProducer.java
components/camel-http/src/test/java/org/apache/camel/component/http/HttpQueryTest.java
components/camel-http/src/test/java/org/apache/camel/component/http/handler/BasicValidationHandler.java

Pull Request contains a fix for CAMEL-21840 and unit-tests showing the problem.

CAMEL-21840: Testcases and fix for CAMEL-21840.

---

components/camel-dhis2/camel-dhis2-component/src/main/docs/dhis2-component.adoc

Remove duplicate code example in DHIS2 component.

Remove duplicate code example in DHIS2 component

---

components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpConsumer.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/SftpConsumer.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpSimpleConsumeWithAntIncludeIT.java

Hi @davsclaus,
follow-up bug fix to CAMEL-21739 which could cause leading slashes to get produced accidentally. If a new issue is needed, I'll open it.
Regards,
Benjamin

CAMEL-21739: camel-ftp - Fix leading / in some cases

---

components/camel-rest-openapi/src/test/resources/openapi.json
components/camel-rest-openapi/src/test/resources/openapi.yaml
components/camel-tahu/src/test/java/org/apache/camel/component/tahu/TahuConfigurationTest.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/resources/openapi.json
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/resources/routes/rest-dsl.yaml
tooling/maven/camel-restdsl-openapi-plugin/src/it/customized-v3/src/main/resources/petstore.json
tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-dto-v3/src/spec/openapi.json
tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-v3/src/spec/openapi.json
tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-xml-dto-v3/src/spec/openapi.json
tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-xml-v3/src/spec/openapi.json
tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-yaml-dto-v3/src/spec/openapi.json
tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-yaml-kamelet-v3/src/spec/openapi.json
tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-yaml-v3/src/spec/openapi.json
tooling/openapi-rest-dsl-generator/src/test/resources/MyRestRouteFilterV3.txt
tooling/openapi-rest-dsl-generator/src/test/resources/MyRestRouteV3.txt
tooling/openapi-rest-dsl-generator/src/test/resources/OpenApiV3Petstore.txt
tooling/openapi-rest-dsl-generator/src/test/resources/OpenApiV3PetstoreWithModelYaml.txt
tooling/openapi-rest-dsl-generator/src/test/resources/OpenApiV3PetstoreWithRestComponent.txt
tooling/openapi-rest-dsl-generator/src/test/resources/OpenApiV3PetstoreWithRestComponentXml.txt
tooling/openapi-rest-dsl-generator/src/test/resources/OpenApiV3PetstoreWithRestComponentYaml.txt
tooling/openapi-rest-dsl-generator/src/test/resources/OpenApiV3PetstoreXml.txt
tooling/openapi-rest-dsl-generator/src/test/resources/OpenApiV3PetstoreYaml.txt
tooling/openapi-rest-dsl-generator/src/test/resources/org/apache/camel/generator/openapi/openapi-spec.json

Fix typo; Muliple -> Multiple

---

bom/camel-bom/pom.xml
components/camel-spring-ws/src/test/resources/org/apache/camel/component/spring/ws/ConsumerEndpointMappingByBeanNameRouteTest-context.xml
components/camel-spring-ws/src/test/resources/org/apache/camel/component/spring/ws/ConsumerEndpointMappingResponseHandlingRouteTest-context.xml
components/camel-spring-ws/src/test/resources/org/apache/camel/component/spring/ws/ProducerLocalRouteTest-context.xml
components/camel-spring-ws/src/test/resources/org/apache/camel/component/spring/ws/SoapHeaderTest-context.xml
components/camel-spring-ws/src/test/resources/org/apache/camel/component/spring/ws/SoapResponseAttachmentTest-context.xml
components/camel-spring-ws/src/test/resources/org/apache/camel/component/spring/ws/addresing/CamelDirectSenderTest-context.xml
components/camel-spring-ws/src/test/resources/org/apache/camel/component/spring/ws/addresing/ConsumerWSAParamsActionTests-context.xml
components/camel-spring-ws/src/test/resources/org/apache/camel/component/spring/ws/addresing/ConsumerWSAParamsTOTests-context.xml
components/camel-spring-ws/src/test/resources/org/apache/camel/component/spring/ws/addresing/ProducerParamsBasicTest-context.xml
components/camel-spring-ws/src/test/resources/org/apache/camel/component/spring/ws/addresing/ProducerParamsPrecedenceTest-context.xml

Cherry pick changes from https://github.com/apache/camel/commit/d079c85ea5912a0e90727bc864bc5df36b2ce9d7 over from main to 4.8.x @Croway 
Have run mvn -DskipTests clean install
Note : due to the branch being dirty, this PR will collide with https://github.com/apache/camel/pull/17420 - both PRs include a refresh of the branch - I can rebase once one of these PRs gets merged

Fix and update spring ws tests (#15801)

---

docs/user-manual/modules/ROOT/pages/mdc.adoc
proposals/mdc.adoc

Ref CAMEL-21827
* Add documentation for MDC usage
* Add a proposal for enhancing the MDC design

chore(doc): MDC documentation and proposal

---

components/camel-oauth/src/test/java/org/apache/camel/test/oauth/AbstractKeycloakTest.java
test-infra/camel-test-infra-common/src/main/java/org/apache/camel/test/infra/common/services/InfrastructureService.java

https://issues.apache.org/jira/browse/CAMEL-21860

CAMEL-21860: IntelliJ cannot run camel k8s tests

---

components/camel-observation/src/main/java/org/apache/camel/observation/MicrometerObservationSpanAdapter.java

Instead of a log event for each different log message.
Closes CAMEL-21854

fix(observation): create a generic log event

---

components/camel-observation/src/main/java/org/apache/camel/observation/MicrometerObservationSpanAdapter.java

Instead of a log event for each different log message.
Closes CAMEL-21854

[Backport 4.8.x] fix(observation): create a generic log event

---

components/camel-activemq6/src/main/docs/activemq6-component.adoc

## Fix activemq6-component.adoc

---

components/camel-smooks/pom.xml

[ CAMEL-21881 ] : Move smooks-edi-cartridge dependency from test scope.

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaHeaderFilterStrategy.java

CAMEL-21880 - camel-kafka - add lowerCase to header filter strategy

---

components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/MicrometerConstants.java
components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/eventnotifier/AbstractMicrometerEventNotifier.java
components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/json/AbstractMicrometerService.java
components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/eventnotifier/MicrometerExchangeEventNotifierDynamicTest.java
components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/eventnotifier/MicrometerExchangeEventNotifierStaticTest.java
components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/messagehistory/ExceptionRouteMicrometerMessageHistoryTest.java
components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/messagehistory/ManagedMessageHistoryTest.java
components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/messagehistory/MicrometerMessageHistoryTest.java
components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/messagehistory/SpringMicrometerMessageHistoryTest.java
components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/routepolicy/ManagedMicrometerRoutePolicyTest.java
components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/routepolicy/MicrometerRoutePolicyConfigurationTest.java
components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/routepolicy/MicrometerRoutePolicyMulticastSubRouteTest.java
components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/routepolicy/MicrometerRoutePolicySubRouteTest.java
components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/routepolicy/ZMicrometerRoutePolicyExcludePatternTest.java

Add some logic that attempts to scan the runtime and provide such information as an additional metric
If the component is used, the application startup will register a new metric including the information related to the runtime. The output will be like:
```
app_info{camel_context="camel-1",camel_runtime_provider="Spring-Boot",camel_runtime_version="3.4.3",camel_version="4.10.2"} 1
```
This can turn very useful to scrape this information at runtime without needing to know which is the runtime provider in advance.

feat(components): include a micrometer metric gauge for app

---

docs/user-manual/modules/ROOT/pages/health-check.adoc

doc(healt): how to consume endpoints

---

components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/json/AbstractMicrometerService.java

camel-micrometer: Avoid registering app.info gauge multiple times

---

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/ClusterType.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesDelete.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesHelper.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/ContainerTrait.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/DeploymentTrait.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/knative/KnativeServiceTrait.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesDeleteTest.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportKnativeTest.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRunCustomTest.java

CAMEL-21835 CAMEL-21841 knative service not working in camel-jbang-plugin-kubernetes

---

components/camel-telemetry/src/main/java/org/apache/camel/telemetry/Tracer.java
components/camel-tracing/src/main/java/org/apache/camel/tracing/Tracer.java

With this PR the runtime detects the presence of conflicting tracing services, warning the user and avoiding to register more than one service:
```
2025-03-21T12:00:43.253+01:00  WARN 281523 --- [main] [] org.apache.camel.tracing.Tracer : Could not add class org.apache.camel.opentelemetry.OpenTelemetryTracer tracer type. Another tracer type, class org.apache.camel.observation.MicrometerObservationTracer,  was already registered. Make sure to include only one tracing dependency type.
```
Closes [CAMEL-21868](https://issues.apache.org/jira/browse/CAMEL-21868)

fix(components): warn when more tracing types

---

core/camel-core/src/test/java/org/apache/camel/support/cache/SimpleLRUCacheTest.java
core/camel-support/src/main/java/org/apache/camel/support/cache/SimpleLRUCache.java

Related to https://issues.apache.org/jira/browse/CAMEL-21888
When the cache size is big, compressing the changes is costly in terms of CPU so it needs to be avoided when possible
* Only compress changes when the queue is full
* Add a value holder to uniquely identify each key/value pair to avoid evicting a key/value pair that has been added multiple times to the cache

CAMEL-21888: camel-core - Compress changes only if needed

---

components/camel-opentelemetry/src/main/docs/opentelemetry.adoc

doc(components): opentelemetry 2 note

---

components/camel-observability-services/pom.xml
components/camel-observability-services/src/main/docs/observability-services.adoc
components/camel-observability-services/src/main/resources/observability-services.properties
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_11.adoc

feat(components): use otel2 instead of otel

---

components/camel-tracing/src/main/java/org/apache/camel/tracing/decorators/AzureStorageQueueSpanDecorator.java
components/camel-tracing/src/test/java/org/apache/camel/tracing/decorators/AzureStorageQueueSpanDecoratorTest.java

CAMEL-20937: add azure-storage-queue span decorator

---

core/camel-core/src/test/java/org/apache/camel/support/cache/SimpleLRUCacheTest.java
core/camel-support/src/main/java/org/apache/camel/support/cache/SimpleLRUCache.java

Related to https://issues.apache.org/jira/browse/CAMEL-21888 fix for 4.8
When the cache size is big, compressing the changes is costly in terms of CPU so it needs to be avoided when possible
* Only compress changes when the queue is full
* Add a value holder to uniquely identify each key/value pair to avoid evicting a key/value pair that has been added multiple times to the cache
* Avoid an O(N) to get the size of the changes by counting them using an AtomicInteger.

CAMEL-21888: camel-core - Compress changes only if needed - 4.8

---

core/camel-core/src/test/java/org/apache/camel/support/cache/SimpleLRUCacheTest.java
core/camel-support/src/main/java/org/apache/camel/support/cache/SimpleLRUCache.java

Related to https://issues.apache.org/jira/browse/CAMEL-21888 fix for 4.10
When the cache size is big, compressing the changes is costly in terms of CPU so it needs to be avoided when possible
* Only compress changes when the queue is full
* Add a value holder to uniquely identify each key/value pair to avoid evicting a key/value pair that has been added multiple times to the cache
* Avoid an O(N) to get the size of the changes by counting them using an AtomicInteger.

CAMEL-21888: camel-core - Compress changes only if needed - 4.10

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java

https://issues.apache.org/jira/browse/CAMEL-21753

CAMEL-21753: camel-jbang - Generates duplicate application.property entries

---

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/CamelConfigITCase.java
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/ExportITCase.java

Adds tests for [Camel Config](https://camel.apache.org/manual/camel-jbang.html#_configuration).

CAMEL-20367: Adds Camel Config tests

---

components/camel-aws/camel-aws2-sns/src/main/docs/aws2-sns-component.adoc

Camel-Aws2-SNS: Docs for Batching Support

---

components/camel-knative/camel-knative-component/src/main/java/org/apache/camel/component/knative/KnativeEndpoint.java
components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpConsumer.java
components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpConsumerFactory.java
components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpServiceOptions.java
components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpSupport.java
components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeOidcServiceOptions.java
components/camel-knative/camel-knative-http/src/test/java/org/apache/camel/component/knative/http/KnativeHttpTest.java

- Add Knative service options to enable OIDC support when receiving Knative events
- OIDC service options define OIDC token path
- Enhance Knative Http service to verify OIDC Authorization headers to match given token
- Make Knative OIDC service options configurable via environment settings
- Respond with 401 FORBIDDEN when token verification fails
See CAMEL-21900

CAMEL-21900: Verify OIDC token on Knative service endpoint

---

test-infra/camel-test-infra-nats/src/main/resources/org/apache/camel/test/infra/nats/services/container.properties

Upgrade Nats test infra image to 2.11.0

---

test-infra/camel-test-infra-elasticsearch/src/main/resources/org/apache/camel/test/infra/elasticsearch/services/container.properties

Upgrade Test infra Elasticsearch image to version 8.17.4

---

.github/actions/component-test/action.yaml
.github/actions/incremental-build/action.yaml
.github/actions/install-mvnd/action.yml

(chore) ci: enable apache-snapshots profile

---

components/camel-observation/src/main/resources/META-INF/services/org.apache.camel.tracing.SpanDecorator
components/camel-opentelemetry/src/main/resources/META-INF/services/org.apache.camel.tracing.SpanDecorator

enlist the missing decorators

---

components/camel-telemetry/src/main/java/org/apache/camel/telemetry/SpanDecoratorManagerImpl.java
components/camel-telemetry/src/main/java/org/apache/camel/telemetry/decorators/AbstractSpanDecorator.java
components/camel-telemetry/src/main/resources/META-INF/services/org.apache.camel.telemetry.SpanDecorator
components/camel-telemetry/src/test/java/org/apache/camel/telemetry/URIDecoratorTest.java
components/camel-tracing/src/main/java/org/apache/camel/tracing/Tracer.java
components/camel-tracing/src/main/java/org/apache/camel/tracing/decorators/AbstractSpanDecorator.java
components/camel-tracing/src/test/java/org/apache/camel/tracing/URIDecoratorTest.java

fix(components): compute properly endpoints with no name

---

dsl/camel-jbang/camel-jbang-container/Dockerfile
dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

Camel-Jbang: Bump to Camel 4.10.3

---

components/camel-ibm-secrets-manager/src/main/docs/ibm-secrets-manager-component.adoc

CAMEL-21918 - Camel-IBM-Secret-Manager: Document Refresh feature

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogDoc.java
dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

Upgrade Camel Kamelets to version 4.10.3 in camel-jbang

---

components/camel-infinispan/camel-infinispan-embedded/src/test/resources/log4j2.component.properties

Backport - [4.10.x] Ignoring log4j2-test.xml in infinispan-common test jar (#17106)

---

parent/pom.xml

Bump AWS SDK v2 to 2.31.16

---

components/camel-ai/camel-pinecone/pom.xml

Enabling support for camel-pinecone on power
Test Results : 
[x86_pinecone_build_logs.txt](https://github.com/user-attachments/files/19637097/x86_pinecone_build_logs.txt)
[ppc64le_pinecone_build_logs.txt](https://github.com/user-attachments/files/19637098/ppc64le_pinecone_build_logs.txt)

Enabling ppc64le support for camel-pinecone

---

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Export.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportCamelMain.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportQuarkus.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportSpringBoot.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
dsl/camel-jbang/camel-jbang-core/src/main/resources/log4j2-export.properties
dsl/camel-jbang/camel-jbang-core/src/main/resources/log4j2-script.properties

CAMEL-21939: camel-jbang: Fix export to not run twice, and also fix camel-export.log, and be able to log to console and add the verbose option also.

---

test-infra/camel-test-infra-postgres/src/main/resources/org/apache/camel/test/infra/postgres/services/container.properties

Upgrade Postgres container used in test from 16.4 to 17.4

---

dsl/camel-jbang/camel-jbang-container/Dockerfile
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogDoc.java
dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

CAMEL-21941 - Upgrade Camel Kamelets and Camel Jbang to version 4.11.0

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java

- [] I have run `mvn clean install -DskipTests` locally from root folder and I have committed all auto-generated changes.

camel-jbang: fix export not respecting --quarkus-group-id parameter

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/Hawtio.java

This finally fixes the issue with `camel hawtio`.

camel-jbang - Upgrade to hawtio 4.4.0

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/Hawtio.java

camel-jbang - Upgrade to hawtio 4.4.0 (4.10.x)

---

parent/pom.xml
test-infra/camel-test-infra-pulsar/src/main/resources/org/apache/camel/test/infra/pulsar/services/container.properties

CAMEL-21951 - Bump Pulsar to 4.x

---

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesHelper.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRunCustomTest.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/resources/log4j2.properties

This improved way to detect openshift cluster, given the previous mechanism required permission to read from cluster wide apis

camel-jbang-plugin-kubernetes: change the openshift cluster detection

---

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/IngressTrait.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/Ingress.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/IngressBuilder.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/model/Traits.java

https://issues.apache.org/jira/browse/CAMEL-21911

CAMEL-21911: camel-bang: kubernetes add support for ingress class

---

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_10.adoc

see https://github.com/apache/camel-examples/pull/145

docs: document API breaking change in camel-test-infra in Camel 4.10

---

components/camel-oauth/helm/README.md
components/camel-oauth/helm/etc/camel-realm.json
components/camel-oauth/src/main/java/org/apache/camel/oauth/AbstractOAuthProcessor.java
components/camel-oauth/src/main/java/org/apache/camel/oauth/InMemorySessionStore.java
components/camel-oauth/src/main/java/org/apache/camel/oauth/OAuthCodeFlowCallback.java
components/camel-oauth/src/main/java/org/apache/camel/oauth/OAuthCodeFlowProcessor.java
components/camel-oauth/src/main/java/org/apache/camel/oauth/OAuthLogoutProcessor.java
components/camel-oauth/src/test/java/org/apache/camel/test/oauth/SSLCertTrustTest.java
docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/IngressTrait.java

https://issues.apache.org/jira/browse/CAMEL-21899

CAMEL-21899: camel-oauth - openshift does not maintain http session

---

components/camel-pqc/src/main/java/org/apache/camel/component/pqc/PQCComponent.java
components/camel-pqc/src/main/java/org/apache/camel/component/pqc/crypto/PQCDefaultLMSMaterial.java
components/camel-pqc/src/main/java/org/apache/camel/component/pqc/crypto/PQCDefaultMLDSAMaterial.java
components/camel-pqc/src/main/java/org/apache/camel/component/pqc/crypto/PQCDefaultSLHDSAMaterial.java
components/camel-pqc/src/main/java/org/apache/camel/component/pqc/crypto/PQCDefaultXMSSMaterial.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignatureFalconNoSignerAutowiredTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignatureFalconTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignatureLMSNoAutowiredTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignatureLMSTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignatureMLDSANoAutowiredTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignatureNoAutowiredSignatureTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignaturePicnicTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignatureRainbowTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignatureSLHDSANoAutowiredTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignatureSLHDSATest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignatureTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignatureWrongKeyPairSignatureTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignatureXMSSNoAutowiredTest.java

CAMEL-21971 - camel-pqc - Provide default KeyPair and Signature

---

docs/user-manual/modules/ROOT/pages/camel-jbang-kubernetes.adoc
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/resources/maven-wrapper/mvnw.cmd
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/CamelCatalogITCase.java
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/CamelDebugITCase.java
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/LocalKameletsITCase.java
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/MavenGradleITCase.java
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/RunCommandOnMqttITCase.java
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/ScriptingWithPipesITCase.java
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/JBangTestSupport.java
dsl/camel-jbang/camel-jbang-it/src/test/resources/jbang/it/StubRoute.java
dsl/camel-jbang/camel-jbang-it/src/test/resources/jbang/it/user-source.kamelet.yaml
dsl/camel-jbang/camel-jbang-plugin-kubernetes/pom.xml
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesHelper.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesBaseTest.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesCommandTest.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesDeleteTest.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRunCustomTest.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRunTest.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/resources/log4j2.properties

Backport jbang fixes from main to 4.10.x

---

test-infra/camel-test-infra-hashicorp-vault/src/main/resources/org/apache/camel/test/infra/hashicorp/vault/services/container.properties

Upgrade Hashicorp Vault container image version to 1.19.1

---

components/camel-pqc/src/main/docs/pqc-component.adoc

CAMEL-21968 - Add Camel-PQC Documentation and show algorithms

---

dsl/camel-jbang/camel-jbang-plugin-edit/src/main/java/org/apache/camel/dsl/jbang/core/commands/edit/CamelNanoLspEditor.java
dsl/camel-jbang/camel-jbang-plugin-edit/src/main/resources/org/apache/camel/dsl/jbang/core/commands/edit/edit-help.txt

Fixes help promts cc @davsclaus

CAMEL-21945: camel-jbang fix help prompts in edit plugin

---

components/camel-pqc/src/main/java/org/apache/camel/component/pqc/PQCKeyEncapsulationAlgorithms.java
components/camel-pqc/src/main/java/org/apache/camel/component/pqc/PQCProducer.java
components/camel-pqc/src/main/java/org/apache/camel/component/pqc/PQCSignatureAlgorithms.java
components/camel-pqc/src/main/java/org/apache/camel/component/pqc/PQCSymmetricAlgorithms.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCCMCEGenerateEncapsulationAESTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCFRODOGenerateEncapsulationAESTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCHQCGenerateEncapsulationAESTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCMLKEMGenerateEncapsulationAESTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCMLKEMGenerateEncapsulationRC5Test.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCNTRUGenerateEncapsulationAESTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCNTRULPRGenerateEncapsulationAESTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSABERGenerateEncapsulationAESTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignatureFalconNoSignerAutowiredTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignatureFalconTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignatureLMSTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignatureNoAutowiredSignatureTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignaturePicnicTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignatureRainbowTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignatureSLHDSATest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignatureTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignatureWrongKeyPairSignatureTest.java
components/camel-pqc/src/test/java/org/apache/camel/component/pqc/PQCSignatureXMSSTest.java

CAMEL-21992 - Camel-PQC: Support more KEM Algorithms

---

components/camel-ai/camel-weaviate/src/test/java/org/apache/camel/component/weaviate/it/WeaviateComponentIT.java

Tokenize the host / scheme in the camel-weaviate integration test for substitution, add ID to queryById test

CAMEL-21997 Tokenize the host / scheme in the camel-weaviate integration test for substitution, add ID to queryById test

---

components/camel-knative/camel-knative-http/src/test/java/org/apache/camel/component/knative/http/KnativeHttpTest.java
components/camel-netty/src/main/java/org/apache/camel/component/netty/NettyServerBossPoolBuilder.java
parent/pom.xml

CSB-21999: Downgrade Netty

---

core/camel-core-engine/src/main/docs/modules/eips/pages/pipeline-eip.adoc

Fixes a simple typo in the documentation example where activemq was spelled incorrectly.

Fixed typo in Java example

---

test-infra/camel-test-infra-opensearch/src/main/resources/org/apache/camel/test/infra/opensearch/services/container.properties

Upgrade Opensearch container image to version 2.19.1 for test-infra

---

components/camel-ai/camel-weaviate/pom.xml
components/camel-ai/camel-weaviate/src/test/java/org/apache/camel/component/weaviate/WeaviateTestSupport.java
components/camel-ai/camel-weaviate/src/test/java/org/apache/camel/component/weaviate/it/WeaviateContainerIT.java
test-infra/camel-test-infra-weaviate/pom.xml
test-infra/camel-test-infra-weaviate/src/main/java/org/apache/camel/test/infra/weaviate/common/WeaviateProperties.java
test-infra/camel-test-infra-weaviate/src/main/java/org/apache/camel/test/infra/weaviate/services/WeaviateInfraService.java
test-infra/camel-test-infra-weaviate/src/main/java/org/apache/camel/test/infra/weaviate/services/WeaviateLocalContainerInfraService.java
test-infra/camel-test-infra-weaviate/src/main/java/org/apache/camel/test/infra/weaviate/services/WeaviateRemoteInfraService.java
test-infra/camel-test-infra-weaviate/src/main/resources/org/apache/camel/test/infra/weaviate/services/container.properties
test-infra/camel-test-infra-weaviate/src/test/java/org/apache/camel/test/infra/weaviate/services/WeaviateService.java
test-infra/camel-test-infra-weaviate/src/test/java/org/apache/camel/test/infra/weaviate/services/WeaviateServiceFactory.java
test-infra/pom.xml

Add a test-infra for camel-weaviate and an integration test that runs against it.

CAMEL-22012 Add a test-infra for camel-weaviate

---

components/camel-observation/src/main/resources/META-INF/services/org.apache.camel.tracing.SpanDecorator
components/camel-opentelemetry/src/main/resources/META-INF/services/org.apache.camel.tracing.SpanDecorator

CAMEL-20937: backport the missing bits of the reviewed PR

---

components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpEngine.java
components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpRouter.java

chore(comp/platfomr-http-vertx): use constant instead of port hardcode

---

components/camel-mongodb-gridfs/pom.xml

Enabling support for camel-mongodb-gridfs on power
**Test Results :**
[x86_camel-mongodb-gridfs_build.txt](https://github.com/user-attachments/files/19907244/x86_camel-mongodb-gridfs_build.txt)
[ppc64le_camel-mongodb-gridfs_build.txt](https://github.com/user-attachments/files/19907245/ppc64le_camel-mongodb-gridfs_build.txt)

Enable ppc64le Support for camel-mongodb-gridfs

---

dsl/camel-jbang/camel-jbang-plugin-edit/src/main/java/org/apache/camel/dsl/jbang/core/commands/edit/CamelNanoLspEditor.java

Should fix the issue @davsclaus , port of https://github.com/jline/jline3/pull/1202 thanks!

CAMEL-21945: camel-jbang edit plugin - fix ctrl + space in Mac

---

dsl/camel-jbang/camel-jbang-plugin-kubernetes/pom.xml
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesPodLogs.java
test-infra/camel-test-infra-jetty/pom.xml

https://issues.apache.org/jira/browse/CAMEL-22032

CAMEL-22032: camel-jbang - Regression with k8s pod logs

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Export.java

https://issues.apache.org/jira/browse/CAMEL-22028

CAMEL-22028: camel-jbang - Regression with missing routes file

---

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesDelete.java

https://issues.apache.org/jira/browse/CAMEL-21956

CAMEL-21956: camel-jbang - k8s plugin does not delete the ingress

---

components/camel-as2/camel-as2-api/pom.xml
parent/pom.xml

CAMEL-22034: Upgrade to Bouncycastle 1.80

---

components/camel-ai/camel-pinecone/pom.xml
components/camel-ai/camel-pinecone/src/main/java/org/apache/camel/component/pinecone/PineconeVectorDbProducer.java
components/camel-ai/camel-pinecone/src/test/java/org/apache/camel/component/pinecone/PineconeTestSupport.java
components/camel-ai/camel-pinecone/src/test/java/org/apache/camel/component/pinecone/it/PineconeComponentIT.java
components/camel-ai/camel-pinecone/src/test/java/org/apache/camel/component/pinecone/it/PineconeLocalContainerIT.java
test-infra/camel-test-infra-pinecone/pom.xml
test-infra/camel-test-infra-pinecone/src/main/java/org/apache/camel/test/infra/pinecone/common/PineconeProperties.java
test-infra/camel-test-infra-pinecone/src/main/java/org/apache/camel/test/infra/pinecone/services/PineconeIndexContainer.java
test-infra/camel-test-infra-pinecone/src/main/java/org/apache/camel/test/infra/pinecone/services/PineconeInfraService.java
test-infra/camel-test-infra-pinecone/src/main/java/org/apache/camel/test/infra/pinecone/services/PineconeLocalContainerInfraService.java
test-infra/camel-test-infra-pinecone/src/main/java/org/apache/camel/test/infra/pinecone/services/PineconeRemoteInfraService.java
test-infra/camel-test-infra-pinecone/src/main/resources/org/apache/camel/test/infra/pinecone/services/container.properties
test-infra/camel-test-infra-pinecone/src/test/java/org/apache/camel/test/infra/pinecone/services/PineconeService.java
test-infra/camel-test-infra-pinecone/src/test/java/org/apache/camel/test/infra/pinecone/services/PineconeServiceFactory.java
test-infra/pom.xml

Add a test-infra for camel-pinecone
https://issues.apache.org/jira/browse/CAMEL-22046

CAMEL-22046 Add test-infra for camel-pinecone

---

components/camel-aws/camel-aws2-kinesis/src/main/docs/aws2-kinesis-component.adoc
components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/KclKinesis2Consumer.java
components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/Kinesis2Endpoint.java

CAMEL-22049: Use Kinesis async client if already set

---

components/camel-aws/camel-aws2-kinesis/src/main/docs/aws2-kinesis-component.adoc
components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/KclKinesis2Consumer.java
components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/Kinesis2Endpoint.java

CAMEL-22049: Use Kinesis async client if already set (#17970)

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Shell.java

- Add syntax highlighting with custom ReplHighlighter
- Add persistent command history in user's home directory
- Improve terminal styling and color configuration
- Fix parser initialization and exception handling

feat(jbang): Improve shell experience with syntax highlighting and command history

---

components/camel-elasticsearch/src/main/java/org/apache/camel/component/es/ElasticsearchProducer.java
components/camel-elasticsearch/src/test/java/org/apache/camel/component/es/integration/ElasticsearchGetSearchDeleteExistsUpdateIT.java
parent/pom.xml
test-infra/camel-test-infra-elasticsearch/src/main/resources/org/apache/camel/test/infra/elasticsearch/services/container.properties

CAMEL-21976 - camel-elasticsearch - Upgrade to v9

---

dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-kubernetes-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/spring-boot-kubernetes-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/spring-boot-pom.tmpl

chore: Update Jolokia agent jvm to 2.2.9 in Camel JBang generated projects

---

dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-kubernetes-pom.tmpl

there was one case which was not updated. The other cases were already updated

chore: update maven-dependency-plugin to 3.8.1 in Camel Jbang genrated project

---

dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-kubernetes-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-pom.tmpl

chore: update maven-compiler-plugin to 3.14.0 in Camel Jbang generated

---

components/camel-aws/camel-aws2-sts/src/test/java/org/apache/camel/component/aws2/sts/integration/StsAssumeRoleIT.java
test-infra/camel-test-infra-aws-v2/src/main/resources/org/apache/camel/test/infra/aws2/services/container.properties

Upgrade Localstack container image to version 4.4.0

---

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_12.adoc

CAMEL-21573 camel-spring-boot - Deprecate camel-jetty-starter
https://issues.apache.org/jira/browse/CAMEL-21573

doc upgrade 4.12: deprecation of csb jetty and undertow

---

test-infra/camel-test-infra-consul/src/main/resources/org/apache/camel/test/infra/consul/services/container.properties

Upgrade Consul Container image to version 1.21

---

test-infra/camel-test-infra-milvus/src/main/resources/org/apache/camel/test/infra/milvus/services/container.properties

Upgrade Milvus container image to version v2.5.11

---

components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/csv/BindyCsvDataFormat.java
components/camel-bindy/src/test/java/org/apache/camel/dataformat/bindy/csv/BindySimpleCsvFunctionWithExternalMethodTest.java

CAMEL-22068: camel-bindy - Fix the escaped double quotes in CSV data

---

dsl/camel-componentdsl/src/generated/java/org/apache/camel/builder/component/dsl/RestOpenapiComponentBuilderFactory.java
tooling/openapi-rest-dsl-generator/src/test/java/org/apache/camel/generator/openapi/RestDslXmlGeneratorV3Test.java

chore: Fix RestDslXmlGeneratorV3Test and regen camel-componentdsl

---

dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-kubernetes-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-pom.tmpl

chore: update maven-surefire-plugin to 3.5.3 in Camel Jbang generated project

---

components/camel-opensearch/src/main/java/org/apache/camel/component/opensearch/OpensearchComponent.java
components/camel-opensearch/src/main/java/org/apache/camel/component/opensearch/OpensearchConfiguration.java
components/camel-opensearch/src/main/java/org/apache/camel/component/opensearch/OpensearchProducer.java
components/camel-opensearch/src/test/java/org/apache/camel/component/opensearch/integration/OpensearchClusterIndexIT.java
components/camel-opensearch/src/test/java/org/apache/camel/component/opensearch/integration/OpensearchTestSupport.java
parent/pom.xml
test-infra/camel-test-infra-opensearch/src/main/resources/org/apache/camel/test/infra/opensearch/services/container.properties

CAMEL-22052 - Camel-opensearch: Upgrade to 3.x

---

components/camel-ai/camel-neo4j/src/test/resources/log4j2.properties

Upgrade Neo4j Container image to version 5.26-community-ubi9

---

docs/user-manual/modules/ROOT/pages/backlog-tracer.adoc

I think this meant on, not off

Fixing mistake in documentation

---

parent/pom.xml

CAMEL-22024: Upgrade to Jackson 2.19.0

---

test-infra/camel-test-infra-cassandra/src/main/java/org/apache/camel/test/infra/cassandra/services/CassandraInfraService.java
test-infra/camel-test-infra-cassandra/src/main/java/org/apache/camel/test/infra/cassandra/services/CassandraLocalContainerInfraService.java

Match https://camel.apache.org/components/4.8.x/cql-component.html#_endpoint_options

CAMEL-22083: CQL

---

parent/pom.xml

fixes https://issues.apache.org/jira/browse/CAMEL-22091

Bump of swagger-core to 2.2.32

---

docs/user-manual/modules/ROOT/pages/route-template.adoc

fix: Remove usage of dashed attribute in route template documentation

---

docs/user-manual/modules/ROOT/pages/route-template.adoc

doc: Use tabs to render same routes in various DSLs

---

components/camel-http/src/main/docs/http-component.adoc

CAMEL-22088 - Camel-HTTP: Document httpClient.* possible values

---

docs/user-manual/modules/ROOT/pages/backlog-tracer.adoc
docs/user-manual/modules/ROOT/pages/tracer.adoc

Related: https://github.com/hawtio/hawtio/pull/3917
Updates the trace properties in the examples to use current 4.5 property camel.trace.enabled
https://camel.apache.org/manual/camel-4x-upgrade-guide-4_5.html#_camel_spring_boot
No related Jira issue
No related Jira issue
Doesn't apply (I think?)

Update docs to include updated trace property

---

components/camel-ai/camel-pinecone/pom.xml

given that no Docker image is provided for this architecture
for reference https://github.com/orgs/pinecone-io/packages/container/pinecone-local/364460294?tag=v1.0.0.rc0
test has failed at least the last 47 build https://ci-builds.apache.org/job/Camel/job/Camel%20Core%20(Build%20and%20test)/job/main/999/testReport/org.apache.camel.component.pinecone.it/PineconeLocalContainerIT/BuildAndTest___Matrix___JDK_NAME____jdk_17_latest___PLATFORM____ppc64le____Test______/
```
org.testcontainers.containers.ContainerLaunchException: Container startup failed for image ghcr.io/pinecone-io/pinecone-local:v1.0.0.rc0
at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:351)
at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:322)
at …
```

Fix: do not play IT tests for Pinecone on ppc64le

---

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/JolokiaTrait.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/JolokiaTraitTest.java

Fix for missing code in #18159

CAMEL-21087: Fix jolokia trait service exposure to Camel Jbang Kubernetes plugin

---

components/camel-elasticsearch-rest-client/src/test/java/org/apache/camel/component/elasticsearch/rest/client/integration/ElasticsearchRestClientComponentIT.java

ElasticsearchRestClientComponentIT.testProducer
It avoids this kind of error:
```
Caused by: org.elasticsearch.client.ResponseException: method [PUT],
host [https://localhost:47378], URI [/my_index], status line [HTTP/1.1
401 Unauthorized]
```
There is already a specific waitStrategy for the container to be ready. Maybe there could be a way to ensure that everything is ready correctly with a more precise/different pattern
org.apache.camel.test.infra.elasticsearch.services.ElasticSearchLocalContainerInfraService.initContainer(String)
Locally got 50% success wit 1s sleep and 100% with 2s, so putting 5 seconds to take a margin on the CI and potentially slower machine

CAMEL-22111 - workaround for ElasticsearchRestClientComponentIT.testProducer

---

etc/scripts/release-website.sh

Add the Camel XML IO schema to the website artifacts during the release process.

Add camel-xml-io to website artifacts

---

dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/ExportITCase.java

Added a new test case to Camel JBang export integration tests. When user specifies `quarkusGroupId` and `quarkusVersion` custom properties, it tests that `export` command produces a Quarkus app with this custom Quarkus build.

Camel JBang: Add test for custom Quarkus version

---

core/camel-core/src/test/java/org/apache/camel/processor/NestedChoiceWithEndChoiceIssueTest.java
core/camel-core/src/test/java/org/apache/camel/util/DumpModelAsYamlTransformChoiceRouteTest.java

Fix tests on Windows no taking care of end of lines in camel-core

---

components/camel-nats/src/main/java/org/apache/camel/component/nats/NatsConsumer.java

JetstreamManagement::addStream menthod call addOrUpdateStream. So, it is safe to call addStream method even if there is an existing stream with the same name.

Camel-16483 remove unwanted code

---

components/camel-jackson/pom.xml
components/camel-jackson/src/test/java/org/apache/camel/component/jackson/converter/JacksonJSonNodeConverterTest.java

Fix Jackson test on windows normalizing end of line in comparison

---

components/camel-openapi-java/pom.xml
components/camel-openapi-java/src/test/java/org/apache/camel/openapi/ComplexTypesTest.java

Fix OpenAPI test on windows normalizing end of line in comparison

---

.github/workflows/pr-comment.yml

Use .head.repo.pushed_at in pr-comment workflow instead of .pushed_at

---

test-infra/camel-test-infra-kafka/src/main/resources/org/apache/camel/test/infra/kafka/services/container.properties

CAMEL-21429: camel-kafka: Upgrade test-infra to Kafka 3.9.1

---

core/camel-core-model/src/main/java/org/apache/camel/model/rest/RestConfigurationDefinition.java

after change in
https://github.com/apache/camel/commit/853e94510bfedf06b4fbf6f9bfd0f1ded18d581f

Fix style in RestConfigurationDefintion

---

components/camel-mllp/src/test/java/org/apache/camel/component/mllp/MllpTcpServerConsumerOptionalEndOfDataWithValidationTest.java

the test was flaky, very often. In fact, the test was checking the bad things. it was passing by error just because 22 messages are sent and the second one was taking too much time.
Technically, the test should expect two completed message because org.apache.camel.component.mllp.MllpTcpServerConsumerOptionalEndOfDataWithValidationTest.requireEndOfData() method is returning false. So in
org.apache.camel.component.mllp.TcpServerConsumerEndOfDataAndValidationTestSupport.runMessageWithoutEndOfDataByte(), even the second message sent without end of data is valid.

CAMEL-22152 - Fix test mllpTcp

---

components/camel-mllp/src/test/java/org/apache/camel/component/mllp/TcpServerConsumerEndOfDataAndValidationTestSupport.java

replace deprecated doPostTearDown by cleanupResources in mllp test

---

components/camel-smb/src/main/java/org/apache/camel/component/smb/SmbOperations.java

https://issues.apache.org/jira/browse/CAMEL-22174
This was brought up on the userlist - camel-smb has trouble recovering from TransportExceptions thrown by smbj if there is a network outage that affects the SMB share.   If we catch the exception and disconnect(), camel-smb can recover by reconnecting once the share is again reachable.
I've tested this both with the camel-smb consumer and the producer and it seems to work - once the connection to the SMB share can be reestablished, camel-smb will continue to poll / consume.
- [ x] If this is a large change, bug fix, or code improvement, I checked there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually …

CAMEL-22174 Catch TransportExceptions and disconnect share calls so we can recover from network outage

---

test-infra/camel-test-infra-hashicorp-vault/src/main/resources/org/apache/camel/test/infra/hashicorp/vault/services/container.properties

Upgrade Hashicorp Vault container image to version 1.19.5

---

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_13.adoc

CAMEL-22193 - Camel-fury renamed to camel-fory: add migration note

---

dsl/camel-jbang/camel-jbang-plugin-edit/src/main/java/org/apache/camel/dsl/jbang/core/commands/edit/CamelNanoLspEditor.java

Requires: https://github.com/camel-tooling/camel-language-server/pull/1286
Nice to have but not required: https://github.com/jline/jline3/pull/1327
camel-jbang edit plugin display extra information on camel options like _group_, _required_, _possible values_ and _default value_:
Thanks !

camel-jbang edit plugin display extra information on camel options

---

dsl/camel-jbang/camel-jbang-container/Dockerfile
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogDoc.java
dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

Upgrade Kamelets to version 4.10.6

---

components/camel-kudu/pom.xml
parent/pom.xml

Upgrade Kudu to version 1.18.0

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaWithDBTransactionIT.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/CamelRouteStatus.java

Fix camel-kafka KafkaWithDBTransactionIT test

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/DependencyUpdate.java

before:
```xml
<dependencies>
<dependency>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-actuator</artifactId>
</dependency>
<dependency>
<groupId>org.apache.camel.springboot</groupId>
<artifactId>camel-spring-boot-starter</artifactId>
</dependency>
<dependency>
<groupId>org.apache.camel.springboot</groupId>
<artifactId>camel-observability-services-starter</artifactId>
</dependency>
<dependency>
<groupId>org.apache.camel.springboot</groupId>
<artifactId>camel-timer-starter</artifactId>
</dependency>
<dependency>
<groupId>org.apache.camel.springboot</groupId>
<artifactId>camel-yaml-dsl-starter</artifactId>
</dependency>
<dependency>
<groupId>org.apache.camel</groupId>
<artifactId>camel-main</artifactId>
</dependency>        <dependency> …
```

Improve return to line with Camel Jbang update dependency

---

parent/pom.xml

Cherry pick of https://github.com/apache/camel/commit/ba75e463a6849295be2e72174c416e736416f373 over to 4.10.x branch.       Tested that it builds with mvn -DskipTests clean install.
Bumps org.apache.commons:commons-lang3 from 3.17.0 to 3.18.0.
---
updated-dependencies:
- dependency-name: org.apache.commons:commons-lang3 dependency-version: 3.18.0 dependency-type: direct:production update-type: version-update:semver-minor ...

chore(deps): Bump org.apache.commons:commons-lang3 from 3.17.0 to 3.18.0 (#18575)

---

parent/pom.xml

Upgrade camel-jackrabbit to 2.22.1.     Ran build (mvn -DskipTests clean install), ran tests on camel-jcr.     This is targeted for camel-4.10.x

Upgrade jackrabbit to 2.22.1

---

components/camel-google/camel-google-drive/src/main/java/org/apache/camel/component/google/drive/BatchGoogleDriveClientFactory.java

Google Drive Component: Fix error message

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/ListGroovy.java

Fix Style on ListGroovy

---

components/camel-lra/pom.xml
test-infra/camel-test-infra-microprofile-lra/src/main/resources/org/apache/camel/test/infra/microprofile/lra/services/container.properties

This pull request is to provide ppc64le support to camel-lra component.
Tested all changes on a PowerPC machine and x86 machine also. Log is attached bellow.
[camel-lra ppc64le log.txt](https://github.com/user-attachments/files/20943108/camel-lra.ppc64le.log.txt)
[camel-lra x86 log.txt](https://github.com/user-attachments/files/20943114/camel-lra.x86.log.txt)

Lra ppc64le integration tests activation

---

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_14.adoc

CAMEL-22247: Add migration notes

---

docs/user-manual/modules/ROOT/pages/camel-jbang-test.adoc
dsl/camel-jbang/camel-jbang-plugin-test/src/main/java/org/apache/camel/dsl/jbang/core/commands/test/TestPlugin.java
dsl/camel-jbang/camel-jbang-plugin-test/src/main/resources/templates/jbang-properties.tmpl

- Automatically use test subfolder for creating new tests and running tests
- Automatically create jbang.properties with the init command in order to add mandatory Citrus Camel dependencies

CAMEL-22238: Improve Camel JBang test plugin

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Export.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportSpringBoot.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/CatalogLoader.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/VersionHelper.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/KameletFallbackResourceResolver.java

Handle Camel Spring Boot versions that are not equal to Camel

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/DependencyRuntime.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportQuarkus.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/RunHelper.java
dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/DependencyUpdateTest.java
dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/ExportTest.java

- The major chunk is to take care of the correct directory and not assume the program is launched from the same level than the pom.xml is
- Another point is to not pick the dependencies from dependency management. Thus, still need them for the Camel JBang Runtime Dependency command as it is looking to the bom for the version and runtime type, so introduced a parameter when computing the dependencies.
- avoid setting `camel.main.routes-include-pattern` for Quarkus project. It was added when implementing Quarkus native support but I think the real needed value is the `quarkus.native.resources.includes` parameter. And it was causing trouble to Update command as it was not finding the specified Camel file in classpath

CAMEL-22227 - Fix Camel JBang update dependency for Spring Boot and Quarkus

---

components/camel-consul/src/main/java/org/apache/camel/component/consul/ConsulClientConfiguration.java
components/camel-consul/src/main/java/org/apache/camel/component/consul/cloud/ConsulServiceDiscovery.java
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_14.adoc

CAMEL-17339 - Avoid List<String> as configuration parameter types in Endpoint configurations - Camel Consul tags

---

core/camel-support/src/main/java/org/apache/camel/support/ObjectHelper.java

extract from Javadoc of AccessibleObject.canAcces:
```
* Test if the caller can access this reflected object. If this
reflected
* object corresponds to an instance method or field then this
method tests
* if the caller can access the given {@code obj} with the reflected
object.
* For instance methods or fields then the {@code obj} argument must
be an
* instance of the {@link Member#getDeclaringClass() declaring
class}. For
* static members and constructors then {@code obj} must be {@code
null}.
```

Method.canAccess for static method should be called without instance parameter

---

test-infra/camel-test-infra-fhir/src/main/resources/org/apache/camel/test/infra/fhir/services/container.properties

tested build locally of camel-test-infra-fhir then camel-fhir

deps: Update test container for Fhir to 8.2.0

---

parent/pom.xml

Upgrade jetty to 12.0.22 (camel-4.10.x commit)

Upgrade jetty to 12.0.22

---

components/camel-spring-parent/camel-spring-rabbitmq/src/main/java/org/apache/camel/component/springrabbit/SpringRabbitMQProducer.java
components/camel-spring-parent/camel-spring-rabbitmq/src/test/java/org/apache/camel/component/springrabbit/integration/RabbitMQProducerIT.java

CAMEL-22278: Improve rabbitmq producer performance

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Debug.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/RunHelper.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/infra/InfraRun.java
dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/infra/InfraTest.java

CAMEL-22279: camel-jbang - infra run to have --background option

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/infra/InfraRun.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/infra/InfraStop.java
dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/infra/InfraTest.java

CAMEL-22283: camel-jbang - infra stop to be similar to camel stop

---

components/camel-mail-microsoft-oauth/src/main/docs/mail-microsoft-oauth.adoc

fixes https://issues.apache.org/jira/browse/CAMEL-22286
Makes a requirement for the component clearer.

[doc] Mail-microsoft-oauth: make component requirements easier to understand

---

test-infra/camel-test-infra-opensearch/src/main/resources/org/apache/camel/test/infra/opensearch/services/container.properties

Bump Opensearch container image version for test-infra to 3.1.0

---

test-infra/camel-test-infra-rabbitmq/src/main/resources/org/apache/camel/test/infra/rabbitmq/services/container.properties

RabbitMQ Test infra module switch the container image version to 4.x

---

components/camel-rest-openapi/src/main/java/org/apache/camel/component/rest/openapi/RestOpenApiEndpoint.java

fixes https://issues.apache.org/jira/browse/CAMEL-22296
partial backport of https://github.com/apache/camel/commit/5fb8a20ef623616bafc355990f05a4e3472c0854
There are 2 options:
1.  partial backport of the https://github.com/apache/camel/commit/5fb8a20ef623616bafc355990f05a4e3472c0854 - which fixes the problem I encountered in CQ, therefore allows users to configure the context-path together with `from` (for the rest) in case they are the same
2.  full backport of https://github.com/apache/camel/commit/5fb8a20ef623616bafc355990f05a4e3472c0854. But as the commit brings a change mentioned in the upgrade guide (see the [guide](https://camel.apache.org/manual/camel-4x-upgrade-guide-4_12.html#_rest_dsl)) I don't think we want this to be backported into 4.10.7.
Therefore the PR implements the …

[4.10.x] Rest-openapi: avoid duplicated context paths

---

components/camel-ai/camel-weaviate/pom.xml
test-infra/camel-test-infra-weaviate/src/main/resources/org/apache/camel/test/infra/weaviate/services/container.properties

- This pull request is to provide ppc64le support to camel-weaviate component.
- Tested all changes on a PowerPC machine and x86 machine also. Log is attached bellow.
[camel-weaviate_x86_log.txt](https://github.com/user-attachments/files/21523434/camel-weaviate_x86_log.txt)
[camel-weaviate_ppc64le_log.txt](https://github.com/user-attachments/files/21523440/camel-weaviate_ppc64le_log.txt)

Weaviate ppc64le integration tests activation

---

test-infra/camel-test-infra-pulsar/src/main/resources/org/apache/camel/test/infra/pulsar/services/container.properties

Upgrade Pulsar test-infra container version to 4.0.5

---

test-infra/camel-test-infra-elasticsearch/src/main/resources/org/apache/camel/test/infra/elasticsearch/services/container.properties

Upgrade Elasticsearch container image version for test-infra to 9.1.0

---

components/camel-ai/camel-langchain4j-agent/pom.xml
components/camel-ai/camel-langchain4j-agent/src/test/java/org/apache/camel/component/langchain4j/agent/BaseLangChain4jAgent.java
components/camel-ai/camel-langchain4j-agent/src/test/java/org/apache/camel/component/langchain4j/agent/LangChain4jAgentWithMemoryServiceTest.java
components/camel-ai/camel-langchain4j-agent/src/test/java/org/apache/camel/component/langchain4j/agent/integration/AbstractRAGIT.java
components/camel-ai/camel-langchain4j-agent/src/test/java/org/apache/camel/component/langchain4j/agent/integration/LangChain4jAgentGuardrailsIntegrationIT.java
components/camel-ai/camel-langchain4j-agent/src/test/java/org/apache/camel/component/langchain4j/agent/integration/LangChain4jAgentNaiveRagIT.java
components/camel-ai/camel-langchain4j-agent/src/test/java/org/apache/camel/component/langchain4j/agent/integration/LangChain4jAgentServiceIT.java
components/camel-ai/camel-langchain4j-agent/src/test/java/org/apache/camel/component/langchain4j/agent/integration/LangChain4jAgentWithMemoryIT.java
components/camel-ai/camel-langchain4j-agent/src/test/java/org/apache/camel/component/langchain4j/agent/integration/LangChain4jAgentWithMemoryServiceIT.java
components/camel-ai/camel-langchain4j-agent/src/test/java/org/apache/camel/component/langchain4j/agent/integration/LangChain4jAgentWithToolsIT.java
components/camel-ai/camel-langchain4j-agent/src/test/java/org/apache/camel/component/langchain4j/agent/integration/LangChain4jSimpleAgentIT.java
test-infra/camel-test-infra-openai-mock/src/main/java/org/apache/camel/test/infra/openai/mock/MockExpectation.java
test-infra/camel-test-infra-openai-mock/src/main/java/org/apache/camel/test/infra/openai/mock/OpenAIMockBuilder.java
test-infra/camel-test-infra-openai-mock/src/main/java/org/apache/camel/test/infra/openai/mock/RequestContext.java
test-infra/camel-test-infra-openai-mock/src/main/java/org/apache/camel/test/infra/openai/mock/RequestHandler.java
test-infra/camel-test-infra-openai-mock/src/main/java/org/apache/camel/test/infra/openai/mock/ResponseBuilder.java
test-infra/camel-test-infra-openai-mock/src/test/java/org/apache/camel/test/infra/openai/mock/OpenAIMockConversationHistoryTest.java
test-infra/camel-test-infra-openai-mock/src/test/java/org/apache/camel/test/infra/openai/mock/OpenAIMockReplyWithAfterToolTest.java
test-infra/camel-test-infra-openai-mock/src/test/java/org/apache/camel/test/infra/openai/mock/OpenAIMockReplyWithToolContentTest.java
test-infra/camel-test-infra-openai-mock/src/test/java/org/apache/camel/test/infra/openai/mock/OpenAIMockSimpleAssertionTest.java

I've migrated the `LangChain4jAgentWithMemoryServiceIT.java` provided by @zbendhiba (great tests) to use OpenAIMock, and it works as expected, I hope `LangChain4jAgentWithMemoryServiceTest.java` can be used as an example, how unit tests can be created for this component.

Camel langchain4j Agent Unit Test

---

test-infra/camel-test-infra-infinispan/src/main/resources/org/apache/camel/test/infra/infinispan/services/container.properties

Upgrade Infinispan Container Version to 15.2.5.Final

---

components/camel-opensearch/src/main/java/org/apache/camel/component/opensearch/OpensearchProducer.java

This pull request addresses CAMEL-22321 by adding SSL fallback support to the OpenSearch component. Currently, when enableSSL=true but no custom certificate path is provided, the component doesn't configure any SSL context, which is inconsistent with other Camel components like HTTP that have proper fallback handling.

CAMEL-22321 | TLS fallback to default for opensearch.

---

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRunTest.java

https://issues.apache.org/jira/browse/CAMEL-22331

CAMEL-22331 camel-jbang-plugin-kubernetes: wrong container probes port

---

core/camel-core-engine/src/main/docs/modules/eips/pages/enterprise-integration-patterns.adoc
docs/user-manual/antora.yml
docs/user-manual/modules/ROOT/references.adoc

- Use "EIPs" as doc title, because "Enterprise Integration Patterns" is too long and breaks the nav layout
- Use proper indentation for reference docs
- Move FAQs to the very end of the user manual navigation

chore(docs): Improve docs navigation

---

components/camel-exec/src/main/java/org/apache/camel/component/exec/impl/ExecParseUtils.java
components/camel-exec/src/test/java/org/apache/camel/component/exec/impl/ExecParseUtilsTest.java

CAMEL-22362: camel-exec - Use quote safe arg parser

---

components/camel-azure/camel-azure-eventhubs/src/main/java/org/apache/camel/component/azure/eventhubs/EventHubsConsumer.java

EventHubsConsumer#processEvents is initially equal to zero hence the condition checking the batch size in EventHubsConsumer#processCheckpoint will always be met. As a consequence, the checkpoint is updated after processing every event.

Fix EventHubsConsumer updating the checkpoint on every event.

---

parent/pom.xml

Align versions to spring-boot 3.4.9 - meant for camel-4.10.x branch.

Align versions to spring-boot 3.4.9

---

components/camel-micrometer-observability/src/generated/java/org/apache/camel/micrometer/observability/MicrometerObservabilityTracerConfigurer.java
components/camel-micrometer-observability/src/main/java/org/apache/camel/micrometer/observability/MicrometerObservabilityTracer.java

chore(components): include micrometer observability accessors

---

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide.adoc
docs/user-manual/modules/ROOT/pages/camel-upgrade-recipes-tool.adoc

Related to https://issues.apache.org/jira/browse/CAMEL-22357
Suggests use of camel upgrade recipes project to assist with migrations.

Involve upgrade recipe tool in the upgrade guide

---

components/camel-observation/src/main/java/org/apache/camel/observation/MicrometerObservationSpanAdapter.java

* Will work in conjunction with https://github.com/apache/camel-spring-boot/pull/1493
Revert #17445
Ref CAMEL-22349

fix(components): Bring observability log event back

---

dsl/camel-jbang/camel-jbang-container/Dockerfile
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogDoc.java
dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/DependencyRuntimeTest.java
dsl/camel-jbang/camel-jbang-core/src/test/resources/pom-xml-files/main-pom.xml
dsl/camel-jbang/camel-jbang-core/src/test/resources/pom-xml-files/springboot-pom.xml
dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java
dsl/camel-jbang/camel-launcher/pom.xml

Camel Kamelets 4.14.0

---

components/camel-ai/camel-langchain4j-chat/pom.xml
components/camel-ai/camel-langchain4j-tokenizer/pom.xml
components/camel-ai/camel-langchain4j-tools/pom.xml
parent/pom.xml

(chores) camel-ai: replace langchain4j RC versions with their final versions

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/infra/InfraBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/infra/InfraPs.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/infra/InfraRun.java

Make Camel Infra command more tool friendly

---

components/camel-telemetry-dev/src/main/java/org/apache/camel/telemetrydev/DevSpanAdapter.java
components/camel-telemetry-dev/src/main/java/org/apache/camel/telemetrydev/DevTrace.java
components/camel-telemetry-dev/src/main/java/org/apache/camel/telemetrydev/DevTraceFormat.java

Async format is now rendering correctly:
```
| f701b9c048cb4dd2822a505235eb7d45
├── | timer://java?period=5000 (camel-timer) [6b00e4de67db45f98a015b41e982182c] [2 millis] <--
├── | seda://x (camel-seda) [4fd5fd23f13d41058ef1f854b3e78820] [0 millis] -->
├── | seda://x (camel-seda) [9781db1ab5bf47e082f6a1dc7482d761] [1 millis] <--
└── | log://multiX (camel-log) [b938bdfd887a48ba8e97f4ab18512200] [0 millis] -->
└── | seda://y (camel-seda) [26958ee26e6640f794520c4fbbee0e70] [0 millis] -->
├── | seda://y (camel-seda) [37eb2153b77147868d76acf04ef3af5c] [0 millis] <--
└── | log://multiY (camel-log) [90b9e8e025e34ee6adf66ba0d188823d] [0 millis] -->
```
Closes CAMEL-22388

fix(components): telemetry-dev async

---

components/camel-telemetry-dev/src/main/java/org/apache/camel/telemetrydev/DevSpanAdapter.java
components/camel-telemetry-dev/src/main/java/org/apache/camel/telemetrydev/DevTrace.java
components/camel-telemetry-dev/src/main/java/org/apache/camel/telemetrydev/DevTraceFormat.java

[Release 4.14.x] fix(components): telemetry-dev tracer NPE

---

components/camel-telemetry/src/main/java/org/apache/camel/telemetry/Tracer.java
components/camel-telemetry/src/main/java/org/apache/camel/telemetry/WrapPollsInterceptStrategy.java

Use an empty InterceptStrategy in order to include any component polling requests under the correct trace.
Closes CAMEL-22385

[Release 4.14.x] fix(components): Telemetry polling requests

---

components/camel-ai/camel-qdrant/pom.xml
test-infra/camel-test-infra-qdrant/src/main/resources/org/apache/camel/test/infra/qdrant/services/container.properties

Enabling support for camel-qdrant on power
**Test Results :**
[ppc64le_camel-qdrant_build_logs.txt](https://github.com/user-attachments/files/22233046/ppc64le_camel-qdrant_build_logs.txt)
[ppc64le_camel-qdrant_infra_logs.txt](https://github.com/user-attachments/files/22233049/ppc64le_camel-qdrant_infra_logs.txt)
[x86_camel-qdrant_build_logs.txt](https://github.com/user-attachments/files/22233050/x86_camel-qdrant_build_logs.txt)
[x86_camel-qdrant_infra_logs.txt](https://github.com/user-attachments/files/22233051/x86_camel-qdrant_infra_logs.txt)

Enable ppc64le support for camel-qdrant

---

components/camel-activemq/pom.xml
components/camel-activemq6/pom.xml
test-infra/camel-test-infra-artemis/src/main/resources/org/apache/camel/test/infra/artemis/services/container.properties

This pull request is to provide ppc64le support to camel-activemq and camel-activemq6 components.
Tested all changes on a PowerPC machine and x86 machine also. Log is attached bellow.
[camel-activemq-ppc64le.txt](https://github.com/user-attachments/files/22235138/camel-activemq-ppc64le.txt)
[camel-activemq6-ppc64le.txt](https://github.com/user-attachments/files/22235144/camel-activemq6-ppc64le.txt)
[camel-activemq-x86.txt](https://github.com/user-attachments/files/22235150/camel-activemq-x86.txt)
[camel-activemq6-x86.txt](https://github.com/user-attachments/files/22235154/camel-activemq6-x86.txt)

Activemq and Activemq6 ppc64le integration tests activation

---

parent/pom.xml

Upgrade undertow to 2.3.19.Final

Update undertow to 2.3.19.Final

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/models/kamelet.json
catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd
catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-xml-io.xsd
core/camel-core-engine/src/main/docs/modules/eips/pages/kamelet-eip.adoc
core/camel-core-model/src/generated/resources/META-INF/org/apache/camel/model/kamelet.json
core/camel-core-model/src/main/java/org/apache/camel/model/KameletDefinition.java

Add explanation about when Kamelet EIP should be used instead of Kamelet component, and suggest to use Kamelet component in other cases. 
https://issues.apache.org/jira/browse/CAMEL-22413

CAMEL-22413: Explain the situation to use Kamelet EIP in the catalog

---

components/camel-aws/camel-aws2-textract/src/main/docs/aws2-textract-component.adoc
docs/components/modules/ROOT/nav.adoc
docs/components/modules/ROOT/pages/aws2-textract-component.adoc

CAMEL-22178 - Added docs for AWS Textract

---

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_1.adoc
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_10.adoc
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_11.adoc
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_12.adoc
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_13.adoc
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_14.adoc
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_15.adoc
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_2.adoc
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_3.adoc
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_4.adoc
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_5.adoc
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_6.adoc
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_7.adoc
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_8.adoc
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_9.adoc
docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide.adoc
docs/user-manual/modules/ROOT/pages/migration-app-note.adoc

Related to https://issues.apache.org/jira/browse/CAMEL-22357
The note about migration tool, should be added into each specific upgrade guide as well. Because users:
1 - won't probably scroll down in general 4.x upgrade page to notice the note
2 - users might bookmark or manually set the url for specific page, thus skipping the note in general 4.x upgrade page

Add upgrade recipe tool note into relevant migration guides

---

components/camel-micrometer-observability/src/main/docs/micrometer-observability.adoc
components/camel-opentelemetry2/src/main/docs/opentelemetry2.adoc
components/camel-telemetry-dev/src/main/docs/telemetry-dev.adoc
components/camel-telemetry/src/main/docs/telemetry.adoc

fix(docs): amend wrong parameter description

---

components/camel-opentelemetry2/src/main/docs/opentelemetry2.adoc
components/camel-telemetry-dev/src/main/docs/telemetry-dev.adoc
components/camel-telemetry/src/main/docs/telemetry.adoc

[Release 4.14.x] fix(docs): amend wrong parameter description

---

components/camel-mllp/src/main/java/org/apache/camel/component/mllp/internal/Hl7Util.java
components/camel-mllp/src/test/java/org/apache/camel/component/mllp/MllpTcpServerConsumerAutoAcknowledgementWithBridgeErrorHandlerTest.java
components/camel-mllp/src/test/java/org/apache/camel/component/mllp/MllpTcpServerConsumerAutoAcknowledgementWithoutBridgeErrorHandlerTest.java
components/camel-mllp/src/test/java/org/apache/camel/component/mllp/TcpServerConsumerAcknowledgementTestSupport.java
components/camel-mllp/src/test/java/org/apache/camel/component/mllp/internal/Hl7UtilTest.java

CAMEL-22421: sending ACK in MSH-9.3 when receiving message structure

---

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/RunCommandITCase.java
dsl/camel-jbang/camel-jbang-it/src/test/java/org/apache/camel/dsl/jbang/it/support/JBangTestSupport.java
dsl/camel-jbang/camel-jbang-it/src/test/resources/jbang/it/route-props.properties
dsl/camel-jbang/camel-jbang-it/src/test/resources/jbang/it/route-props.yaml
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/traits/MountTrait.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRunCustomTest.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/resources/test-configmap.yaml
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/resources/test-multiple-config.yaml
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/resources/test-secret.yaml
test-infra/camel-test-infra-cli/src/test/java/org/apache/camel/test/infra/cli/services/CliLocalContainerService.java

Fix kubernetes run --config as the it was overwriting previous keys

camel-jbang: Add more tests for run and kubernetes run commands

---

components/camel-flink/src/main/java/org/apache/camel/component/flink/FlinkComponent.java

fixing main branch style check at build time

Remove unused import

---

dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-kubernetes-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-pom.tmpl

chore: Update Maven Surefire plugin to 3.5.4 in Camel JBang export

---

dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-kubernetes-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/quarkus-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/spring-boot-kubernetes-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/spring-boot-pom.tmpl
dsl/camel-jbang/camel-jbang-core/src/test/resources/pom-xml-files/springboot-pom.xml

chore: Update Jolokia version to 2.3.0 in Camel JBang export

---

components/camel-keycloak/src/main/java/org/apache/camel/component/keycloak/security/KeycloakSecurityHelper.java
components/camel-keycloak/src/main/java/org/apache/camel/component/keycloak/security/KeycloakSecurityPolicy.java
components/camel-keycloak/src/main/java/org/apache/camel/component/keycloak/security/KeycloakSecurityProcessor.java
components/camel-keycloak/src/test/java/org/apache/camel/component/keycloak/security/KeycloakSecurityHelperTest.java
components/camel-keycloak/src/test/java/org/apache/camel/component/keycloak/security/KeycloakSecurityIT.java
components/camel-keycloak/src/test/resources/log4j2.properties

CAMEL-22447 - Camel-Keycloak: Adding publicKey to the access token verification

---

components/camel-keycloak/src/main/docs/keycloak.adoc
components/camel-keycloak/src/main/java/org/apache/camel/component/keycloak/security/KeycloakSecurityHelper.java
components/camel-keycloak/src/main/java/org/apache/camel/component/keycloak/security/KeycloakSecurityProcessor.java
components/camel-keycloak/src/test/java/org/apache/camel/component/keycloak/security/KeycloakSecurityHelperTest.java
components/camel-keycloak/src/test/java/org/apache/camel/component/keycloak/security/KeycloakSecurityIT.java

CAMEL-22459 - Camel-Keycloak: Support permission based policies

---

components/camel-keycloak/pom.xml
components/camel-keycloak/src/test/java/org/apache/camel/component/keycloak/KeycloakTestInfraIT.java
components/camel-keycloak/src/test/java/org/apache/camel/component/keycloak/security/KeycloakSecurityTestInfraIT.java
test-infra/camel-test-infra-keycloak/pom.xml
test-infra/camel-test-infra-keycloak/src/main/java/org/apache/camel/test/infra/keycloak/common/KeycloakProperties.java
test-infra/camel-test-infra-keycloak/src/main/java/org/apache/camel/test/infra/keycloak/services/KeycloakInfraService.java
test-infra/camel-test-infra-keycloak/src/main/java/org/apache/camel/test/infra/keycloak/services/KeycloakLocalContainerInfraService.java
test-infra/camel-test-infra-keycloak/src/main/java/org/apache/camel/test/infra/keycloak/services/KeycloakRemoteInfraService.java
test-infra/camel-test-infra-keycloak/src/main/resources/org/apache/camel/test/infra/keycloak/services/container.properties
test-infra/camel-test-infra-keycloak/src/test/java/org/apache/camel/test/infra/keycloak/KeycloakInfraServiceTest.java
test-infra/camel-test-infra-keycloak/src/test/java/org/apache/camel/test/infra/keycloak/services/KeycloakService.java
test-infra/camel-test-infra-keycloak/src/test/java/org/apache/camel/test/infra/keycloak/services/KeycloakServiceFactory.java
test-infra/pom.xml

CAMEL-22470 - Camel-Keycloak: Add test-infra module for Keycloak

---

components/camel-mail-microsoft-oauth/src/main/docs/mail-microsoft-oauth.adoc

fixes https://issues.apache.org/jira/browse/CAMEL-22473

CAMEL-22473 - added quarkus example to mail-microsoft-oath doc

---

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_15.adoc
docs/user-manual/modules/ROOT/pages/mdc.adoc

Suggestion notes to start using the new mdc component vs the older implementation. We may think to deprecate the older in 4.16 if we see this new component adoption is good.

chore(doc): camel-mdc notes

---

components/camel-ai/camel-langchain4j-agent-api/src/main/java/org/apache/camel/component/langchain4j/agent/api/AgentConfiguration.java
components/camel-ai/camel-langchain4j-agent-api/src/main/java/org/apache/camel/component/langchain4j/agent/api/AgentWithMemory.java
components/camel-ai/camel-langchain4j-agent-api/src/main/java/org/apache/camel/component/langchain4j/agent/api/AgentWithoutMemory.java
components/camel-ai/camel-langchain4j-agent/src/main/docs/langchain4j-agent-component.adoc
components/camel-ai/camel-langchain4j-agent/src/test/java/org/apache/camel/component/langchain4j/agent/integration/LangChain4jAgentCustomToolsIT.java
components/camel-ai/camel-langchain4j-agent/src/test/java/org/apache/camel/component/langchain4j/agent/integration/LangChain4jAgentMixedToolsIT.java
components/camel-ai/camel-langchain4j-agent/src/test/java/org/apache/camel/component/langchain4j/agent/pojos/CalculatorTool.java
components/camel-ai/camel-langchain4j-agent/src/test/java/org/apache/camel/component/langchain4j/agent/pojos/StringTool.java
components/camel-ai/camel-langchain4j-agent/src/test/java/org/apache/camel/component/langchain4j/agent/pojos/WeatherTool.java

CAMEL-22475: Camel LangChain4j Agent: custom tools feature

---

components/camel-sql/src/main/java/org/apache/camel/processor/idempotent/jdbc/JdbcMessageIdRepository.java

Avoid rolledbackonly transaction during idempotent table creation

---

core/camel-main/src/main/java/org/apache/camel/main/BaseMainSupport.java
core/camel-main/src/test/java/org/apache/camel/main/MainPropertyPlaceholderTest.java
core/camel-main/src/test/resources/k8s/etc/camel/conf.d/_configmaps/my.properties
core/camel-main/src/test/resources/k8s/etc/camel/conf.d/_secrets/my.properties

Enable the possibility to include a .properties file
Closes CAMEL-22489

feat(core): scan .properties in cloud configuration

---

dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java

https://issues.apache.org/jira/browse/CAMEL-22484

CAMEL-22484 camel-jbang-kubernetes fails to deploy to openshift when using custom GAV

---

dsl/camel-jbang/camel-jbang-container/Dockerfile
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportCamelMain.java
dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/ExportMainJibTest.java
dsl/camel-jbang/camel-jbang-core/src/test/java/org/apache/camel/dsl/jbang/core/commands/ExportMainJkubeTest.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExport.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesHelper.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/main/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRun.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesExportTest.java
dsl/camel-jbang/camel-jbang-plugin-kubernetes/src/test/java/org/apache/camel/dsl/jbang/core/commands/kubernetes/KubernetesRunCustomTest.java

Backport camel-jbang fixes to 4.14.x CAMEL-22456 CAMEL-22455 CAMEL-22484 

---

components/camel-milo/pom.xml
parent/pom.xml

Upgrade Milo version to 1.0.6

---

components/camel-micrometer-observability/src/test/java/org/apache/camel/micrometer/observability/AsyncCXFTest.java
components/camel-micrometer-observability/src/test/java/org/apache/camel/micrometer/observability/AsyncDirectTest.java
components/camel-micrometer-observability/src/test/java/org/apache/camel/micrometer/observability/AsyncTest.java
components/camel-micrometer-observability/src/test/java/org/apache/camel/micrometer/observability/AsyncWiretapTest.java
components/camel-micrometer-observability/src/test/java/org/apache/camel/micrometer/observability/DisableEndpointTest.java
components/camel-micrometer-observability/src/test/java/org/apache/camel/micrometer/observability/EnableProcessorsTest.java
components/camel-micrometer-observability/src/test/java/org/apache/camel/micrometer/observability/MicrometerObservabilityTracerPropagationTestSupport.java
components/camel-micrometer-observability/src/test/java/org/apache/camel/micrometer/observability/MicrometerObservabilityTracerTest.java

fix(components): micrometer observability assert Instant
