components/camel-aws/src/main/java/org/apache/camel/component/aws/s3/S3Producer.java

@WillemJiang @davsclaus 
The S3 Producer component does not take the ObjectMetaData set into account when the type of the exchange is a File. It does takes it into account when the exchange in an InputStream. This is a serious problem because a lot of S3 metadata set in camel headers are not considered at all.

[master][CAMEL-8247] AWS S3 Producer does not use ObjectMetaData when exchange is a File

---

components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpConsumer.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/RemoteFileConsumer.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/SftpConsumer.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/RemoteFileIgnoreDoPollErrorTest.java

@davsclaus 
This adds ignoring read directory permission error using the same flag 'ignoreFileNotFoundOrPermissionError'.

CAMEL-8266 Allows ignoring directories for SFTP/FTP having no read permission using ignoreFileNotFoundOrPermissionError

---

components/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/CamelAutoConfiguration.java
components/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/CamelConfigurationProperties.java
components/camel-spring-boot/src/test/java/org/apache/camel/spring/boot/CamelAutoConfigurationTest.java

Add Name for Camel Context in camel-spring-boot Configuration
Properties. 
Its required to set the Camel Context Name before run the RouteBuilder. 
After the RouteBuilder ran, can't change the Camel Context Name fully in
all JMX Management Beans.

CAMEL-8295

---

components/camel-scala/pom.xml

@davsclaus 
ScalaTestSupport needs to be published so that others can depend on test jar for camel-scala and access this.

CAMEL-8427 Publish scala test jar to expose ScalaTestSupport

---

parent/pom.xml

Hi all,
This PR is related to:
https://issues.apache.org/jira/browse/CAMEL-8608
Tests are ok for all the components affected by this change.
Thanks.
Bye,
Andrea

CAMEL-8608 Update async-http-client version from 1.9.8 to 1.9.17

---

components/camel-cache/src/main/java/org/apache/camel/component/cache/CacheProducer.java

Fix to avoid potential race condition which can cause NPE. An element is retrieved from the cache to perform a null check and if not null, retrieved once again to perform object retrieval. If the object is either removed from the cache or TTL expires, can result in NPE.

CAMEL-8758: Fix to Camel Cache producer to avoid NPE in race condition

---

components/camel-aws/src/main/java/org/apache/camel/component/aws/sqs/SqsProducer.java

Logging events like `WARN  org.apache.camel.component.aws.sqs.SqsProducer  - Cannot put the message header key={0}, value={1} into Sqs MessageAttribute` are not particularly helpful, this change fixes the logging event to use the SLF4J placeholders correctly, displaying the key/value that it could not add to the message.

Fix the logging event to use placeholders correctly.

---

components/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/CamelAutoConfiguration.java
components/camel-spring-boot/src/test/java/org/apache/camel/spring/boot/CamelNonInvasiveCamelContextTest.java
components/camel-spring-boot/src/test/resources/externalCamelContext.xml

Only instantiate a CamelContext bean if one does not already exist.  Same with ConsumerTemplate and ProducerTemplate.

CAMEL-8801 Make spring-boot auto-configuration defer to existing beans

---

components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQComponent.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQConsumer.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQEndpoint.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQMessageConverter.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQProducer.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/reply/CorrelationTimeoutMap.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/reply/ReplyHolder.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/reply/ReplyManager.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/reply/ReplyManagerSupport.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/reply/TemporaryQueueReplyHandler.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/reply/TemporaryQueueReplyManager.java
components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/RabbitMQEndpointTest.java
components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/RabbitMQInOutIntTest.java
components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/testbeans/TestSerializableObject.java

This will fix all but 4 issues in the camel-rabbitmq component reported by checkstyle. The remaining issues are due to maven-checkstyle-plugin version 2.9.1 not supporting java 7 syntax.
What is the projects stance on using java 7 syntax (specifically try with resources)?  I also posted this question on http://camel.465427.n5.nabble.com/Java7-syntax-and-checkstyle-td5768041.html

Checkstyle fixes in camel-rabbitmq component.

---

components/camel-undertow/src/test/java/org/apache/camel/component/undertow/BaseUndertowTest.java
components/camel-undertow/src/test/java/org/apache/camel/component/undertow/UndertowComponentTest.java
components/camel-undertow/src/test/java/org/apache/camel/component/undertow/UndertowError500Test.java
components/camel-undertow/src/test/java/org/apache/camel/component/undertow/UndertowHeaderTest.java
components/camel-undertow/src/test/java/org/apache/camel/component/undertow/UndertowHttpProducerTest.java
components/camel-undertow/src/test/java/org/apache/camel/component/undertow/UndertowHttpsSpringTest.java
components/camel-undertow/src/test/java/org/apache/camel/component/undertow/UndertowMethodRestricTest.java
components/camel-undertow/src/test/java/org/apache/camel/component/undertow/UndertowPrefixMatchingTest.java
components/camel-undertow/src/test/java/org/apache/camel/component/undertow/UndertowProducerTest.java
components/camel-undertow/src/test/java/org/apache/camel/component/undertow/UndertowSharedPortTest.java
components/camel-undertow/src/test/resources/SpringTest.xml

Follow-up to https://github.com/apache/camel/pull/562

camel-undertow: refactor unit tests to use dynamic ports

---

camel-core/src/main/java/org/apache/camel/model/rest/RestOperationParamDefinition.java

Hey,
It seems that this was removed somehow... 
Without a default value an exception is thrown when generating the swagger models:
```
15-08-07 15:50:45 WARN  ServletHandler:563 - /api-docs
java.lang.IllegalArgumentException: Flat hash tables cannot contain null elements.
at scala.collection.mutable.FlatHashTable$HashUtils$class.elemHashCode(FlatHashTable.scala:390)
at scala.collection.mutable.HashSet.elemHashCode(HashSet.scala:41)
at scala.collection.mutable.FlatHashTable$class.addEntry(FlatHashTable.scala:136)
at scala.collection.mutable.HashSet.addEntry(HashSet.scala:41)
at scala.collection.mutable.HashSet.$plus$eq(HashSet.scala:60)
at com.wordnik.swagger.core.util.ModelUtil$$anonfun$modelsFromApis$1$$anonfun$apply$1$$anonfun$apply$4.apply(ModelUtil.scala:93)
at …
```

readding defaulting logic for parameter data type

---

components/camel-optaplanner/pom.xml
components/camel-optaplanner/src/test/java/org/apache/camel/component/optaplanner/OptaPlannerDaemonSolverTest.java

The master code currently suffers from PLANNER-468 and a corrupted test case.
This PR fixes the test case. It also ignores the test case temporary, because PLANNER-468 makes it fail. It clearly comments when it can and should be unignored.
This PR is better than the current master state. An additional improvement(?) could be to revert optaplanner from 6.3 to 6.2 to fix the deamon mode until optaplanner 6.3.1+ is out, but I am not sure if that's desired as it would impact the drools & jbpm version too. I'd rather see this merged and deal with it as a known issue until it's fixed upstream.

Fix test corruption by6 3 upgrade + ignore test due to upstream issue

---

components/camel-optaplanner/src/main/java/org/apache/camel/component/optaplanner/OptaPlannerProducer.java
components/camel-optaplanner/src/test/java/org/apache/camel/component/optaplanner/OptaPlannerDaemonSolverTest.java

Also fix async solving deamon test that broke after upgrade to 6.3
PS: It's a PITA (which cost me some time) that the log4j.properties of the components don't log ERRORs to the console by default. (I can understand they don't do INFO to reduce build verbosity, but they should show errors by default in the console (and intentional errors that are being tested can be filtered out). Anyway, that's a different issue. :)

camel-optaplanner should not eat exceptions

---

components/camel-elasticsearch/src/main/java/org/apache/camel/component/elasticsearch/ElasticsearchConstants.java
components/camel-elasticsearch/src/main/java/org/apache/camel/component/elasticsearch/converter/ElasticsearchActionRequestConverter.java

it is currently not possible to use camel-elasticsearch to send index requests for children in parent-child relationships, since the ?parent=<id> property isn't set. see: https://www.elastic.co/guide/en/elasticsearch/guide/current/indexing-parent-child.html

[CAMEL-9279] add parent to Elasticsearch IndexRequest

---

components/camel-aws/src/main/docs/aws-kinesis.adoc
components/camel-aws/src/main/java/org/apache/camel/component/aws/kinesis/KinesisConstants.java
components/camel-aws/src/main/java/org/apache/camel/component/aws/kinesis/KinesisProducer.java
components/camel-aws/src/test/java/org/apache/camel/component/aws/kinesis/KinesisConsumerTest.java
components/camel-aws/src/test/java/org/apache/camel/component/aws/kinesis/KinesisProducerTest.java

Fixed one of the headers, even though it means something similar its a discreet value from Kinesis.
- The key for shard id was changed.  The values that these two headers represent are functionally different, the value of partition key calculated which shard id data will be written to.
- There was a unit test expecting these to be the same which I removed.
- The docs indicate that partition key must be present when sending to kinesis so made it required.

CAMEL-9603 Documentation for Kinesis producer.

---

components/camel-jetty8/pom.xml

The camel-jetty8 component fails to compile for me because of a problem with a missing dependency, described here: [CAMEL-9819](https://issues.apache.org/jira/browse/CAMEL-9819)

CAMEL-9819: add httpclient to camel-jetty9 test dependencies

---

components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/BindyAbstractDataFormat.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/csv/BindyCsvDataFormat.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/fixed/BindyFixedLengthDataFormat.java
components/camel-bindy/src/test/java/org/apache/camel/dataformat/bindy/fixed/link/BindySimpleFixedLengthWithLinkTest.java

Patch for CAMEL-9982. Added unittest and added fields with "Link"  annotation to model for Fixed Length.

CAMEL-9982

---

components/camel-smpp/pom.xml
components/camel-smpp/src/test/java/org/apache/camel/component/smpp/SmppDataSmCommandTest.java
components/camel-smpp/src/test/java/org/apache/camel/component/smpp/SmppReplaceSmCommandTest.java
components/camel-smpp/src/test/java/org/apache/camel/component/smpp/SmppSubmitMultiCommandTest.java
components/camel-smpp/src/test/java/org/apache/camel/component/smpp/SmppSubmitSmCommandTest.java
components/camel-smpp/src/test/java/org/apache/camel/component/smpp/SmppUtilsTest.java
parent/pom.xml
platforms/karaf/features/src/main/resources/bundles.properties
platforms/karaf/features/src/main/resources/features.xml

Test changes were necessary because of two jsmpp changes: https://github.com/opentelecoms-org/jsmpp/commit/fcb495f09b97738796548069b2c60050be7892e3 and https://github.com/opentelecoms-org/jsmpp/commit/d50fbd7e9b76e292459858b26c1397e6d2c69c9e
My osgi/service-mix knowledge is almost non-existent, so please forgive if I made a mistake.

CAMEL-8219: camel-smpp - use jsmpp version 2.2.4

---

components/camel-salesforce/camel-salesforce-maven-plugin/src/main/java/org/apache/camel/maven/CamelSalesforceMojo.java
components/camel-salesforce/camel-salesforce-maven-plugin/src/main/resources/sobject-picklist.vm
components/camel-salesforce/camel-salesforce-maven-plugin/src/main/resources/sobject-pojo.vm

This allows multiple objects to have similarly named picklist fields (e.g. `Type`) without causing name conflicts (practically a race condition on the contents of the picklist enum class).
@davsclaus We've discussed this feature a long time ago - the patches will finally be rolling in now :smile:
Signed-off-by: Sune Keller <absukl@almbrand.dk>

Prefix picklist enum names with owning SObjectDescription name

---

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/StringMultiSelectPicklistConverter.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/StringMultiSelectPicklistDeserializer.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/StringMultiSelectPicklistSerializer.java
components/camel-salesforce/camel-salesforce-maven-plugin/src/main/java/org/apache/camel/maven/CamelSalesforceMojo.java
components/camel-salesforce/camel-salesforce-maven-plugin/src/main/resources/sobject-pojo.vm

Fixes issue mentioned in https://github.com/apache/camel/pull/1029#issuecomment-225815020.
- Introduces `String` based variants of `MultiSelectPicklistConverter`, `MultiSelectPicklistDeserializer` and `MultiSelectPicklistSerializer`.
- Fixes `CamelSalesforceMojo.GeneratorUtility#getFieldType()` which I broke for multi select picklists in #1029.
- Checks for the value of `$useStringsForPicklists` in the right parts of `sobject-pojo.vm`.
Signed-off-by: Sune Keller <absukl@almbrand.dk>

Fix multi select picklist fields

---

camel-core/src/main/java/org/apache/camel/util/jsse/BaseSSLContextParameters.java
camel-core/src/main/java/org/apache/camel/util/jsse/SSLContextClientParameters.java
components/camel-core-xml/src/main/java/org/apache/camel/core/xml/util/jsse/AbstractSSLContextClientParametersFactoryBean.java
components/camel-core-xml/src/main/java/org/apache/camel/core/xml/util/jsse/SNIHostNamesDefinition.java
components/camel-http4/pom.xml
components/camel-http4/src/test/java/org/apache/camel/component/http4/HttpSNIHostNameTest.java
components/camel-http4/src/test/resources/org/apache/camel/component/http4/CamelHttp4Context.xml

Introduced SNIHostName in sslContextParameters.
Added a test to https://www.mnot.net which throws 403 or 421 when SNIHostName is not used.
Eventually it might be needed to ignore this test. I didn't find a simple way to test this.

CAMEL-9638: Introduced SNIHostName config in sslContextParameters

---

tests/camel-itest-spring-boot/pom.xml
tests/camel-itest-spring-boot/src/main/java/org/apache/camel/itest/springboot/ITestApplication.java
tests/camel-itest-spring-boot/src/main/java/org/apache/camel/itest/springboot/ITestConfigBuilder.java
tests/camel-itest-spring-boot/src/main/java/org/apache/camel/itest/springboot/command/UnitTestCommand.java
tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/CamelOptaplannerTest.java
tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/CamelSjmsTest.java
tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/CamelZipkinStarterTest.java
tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/util/ArquillianPackager.java
tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/util/DependencyResolver.java
tests/camel-itest-spring-boot/src/test/resources/spring-boot-itest.properties

I fixed the framework and some modules that failed. I also moved the configuration from the properties file to the surefire pom section.
Now the configuration defaults to "run-unit-tests" when running the tests from IDE, while unit tests are disabled in surefire (many of them fail, it will be next step).

CAMEL-10118 modules fix

---

components/camel-aws/src/main/java/org/apache/camel/component/aws/swf/CamelSWFWorkflowClient.java

The defaults as part of above bug are not used by AWS client before
starting a workflow

https://issues.apache.org/jira/browse/CAMEL-8598

---

components/camel-mina2/src/main/java/org/apache/camel/component/mina2/Mina2UdpProtocolCodecFactory.java

We replaced "convertTo()" invocations to "mandatoryConvertTo()" because the same changes were conducted in the past commits. 
commit ID: b605eb032b080c8c697ea69ceb588e3d4bab9d48
https://apache.googlesource.com/camel/+/b605eb032b080c8c697ea69ceb588e3d4bab9d48%5E%21/#F1
commit ID: ec1509662bf567e277e7d67b33732660e52d1b6c
https://apache.googlesource.com/camel/+/ec1509662bf567e277e7d67b33732660e52d1b6c%5E%21/#F1
commit ID: e7487d332d01a86a757c0d89fd6d6eb0a1bbbfcb
https://apache.googlesource.com/camel/+/e7487d332d01a86a757c0d89fd6d6eb0a1bbbfcb%5E%21/#F1
The change pattern we found is replacing "convertTo(byte[].class, in)"
invocations with "mandatoryConvertTo(byte[].class, in)" invocations.
The difference between the two methods seems whether they can return
null or not. …

replacing convertTo() with mandatoryConvertTo()

---

components/camel-schematron/src/main/docs/schematron.adoc
components/camel-schematron/src/main/java/org/apache/camel/component/schematron/SchematronEndpoint.java
components/camel-schematron/src/main/java/org/apache/camel/component/schematron/processor/ClassPathURIResolver.java
components/camel-schematron/src/test/java/org/apache/camel/component/schematron/SchematronProducerTest.java
components/camel-schematron/src/test/java/org/apache/camel/component/schematron/processor/SchematronProcessorTest.java
components/camel-schematron/src/test/java/org/apache/camel/component/schematron/processor/TemplatesFactoryTest.java
components/camel-schematron/src/test/resources/custom-resolver/title-rules.sch
components/camel-schematron/src/test/resources/sch/schematron-3.sch
components/camel-schematron/src/test/resources/xml/article-3.xml

Allows a user to supply a custom URIResolver to be used to resolve imports in his/her schematron rules files.
Fix now applied to master. But we would really need to have this back ported to the 2.16.x and 2.17.x branches if possible.

Fix for CAMEL-8287

---

components/camel-cxf/src/main/java/org/apache/camel/component/cxf/CxfConsumer.java
components/camel-cxf/src/main/java/org/apache/camel/component/cxf/jaxrs/CxfRsInvoker.java

setobject done earlier and exception set on camelExchange.
isExpired method call thru Continuation interface is cancelled and
below issues became invalid as discussed in CXF-7011
https://issues.apache.org/jira/browse/CXF-7002
https://issues.apache.org/jira/browse/CXF-7011
instead
such block means the same;
https://issues.apache.org/jira/browse/CXF-7011?focusedCommentId=15422696&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15422696

CAMEL-10171 memory leak when continuation expires

---

components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQDeclareSupport.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQEndpoint.java
components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/RabbitMQEndpointTest.java

Fix for https://issues.apache.org/jira/browse/CAMEL-10131
This is replacing #1138
Exclusive queues are used by only one connection and the queue will be deleted when that connection closes. This is an important feature to have, especially when using fanout exchanges, since the generated queues will not autodelete when the client disconnects, leaving queues with no consumers behind, which require manual/scripted intervention.

CAMEL-10131 added exclusive queues support

---

camel-core/src/main/java/org/apache/camel/main/Main.java
camel-core/src/test/java/org/apache/camel/main/MainExample.java
camel-core/src/test/resources/example.properties

I added a setPropertyPlaceholderLocations() method to Main, as suggested by the ticket: 
https://issues.apache.org/jira/browse/CAMEL-10255
I also made a change to the test class "MainExample" and added a test file example.properties.
Not sure if a test is worth having in this case, but added it, just in case.

CAMEL-10255 - Make it easy to configure property placeholder

---

platforms/karaf/features/src/main/resources/features.xml

qpid-jms-client 0.8.0 is incompatible with proton-j 0.10 so we need to
bump up the proton-j to compatible 0.12.0.
more details: https://issues.apache.org/jira/browse/CAMEL-10278

Fix qpid versions in camel-amqp feature

---

components-starter/camel-jetty9-starter/src/main/java/org/apache/camel/component/jetty9/springboot/JettyHttpComponentConfiguration9.java
components/camel-jetty-common/src/main/java/org/apache/camel/component/jetty/JettyHttpComponent.java
components/camel-jetty9/src/main/docs/jetty-component.adoc

I saw that I didn't correct a typo in the documentation.

Jetty9: fixed typos and documentation in X-Forwarded-For

---

components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQMessageConverter.java
components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/RabbitMQConsumerIntTest.java
components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/RabbitMQProducerTest.java

See bug report https://issues.apache.org/jira/browse/CAMEL-10291

CAMEL-10291: support java.util.date for timestamps in rabbitmq messages

---

components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowComponent.java

When running on Spring, the `doStop` is called by the spring framework before the default strategy unregisters the consumers, so the registry is cleared and the undertow servers remain bound to their port when the context is closed.
We should not clear the registry (change added in https://github.com/apache/camel/commit/cdd64e10a6c761ccfba4b6d605c53df1250bb9eb) because it is automatically cleared when the last consumer is unregistered.
This issue prevent using livereload with undertow (port already used). I'm working on a feature for dynamically changing the configuration on Kubernetes that is also be impacted.

CAMEL-10358: do not clear the registry too early

---

components/camel-jsch/src/main/docs/scp-component.adoc
components/camel-jsch/src/main/java/org/apache/camel/component/scp/ScpConfiguration.java
components/camel-jsch/src/main/java/org/apache/camel/component/scp/ScpOperations.java

This is a simple change to pass a new config option through to JSch. We need to set the 'preferredAuthentications' option to override the default order on our servers, specifically to prevent a kerberos password prompt being shown.
More details here...
http://stackoverflow.com/questions/29669459/skipping-kerberos-authentication-prompts-with-jsch
Regards,
James

Added 'preferredAuthentications' option to camel-jsch

---

components/camel-aws/src/main/java/org/apache/camel/component/aws/s3/S3Endpoint.java

Use Case:
When AWS access key only has permission to specific path under bucket, the bucket check will fail.

add prefix when initialize the s3endpoint and bucket check. 

---

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/SalesforceComponent.java
components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/SalesforceComponentIntegrationTest.java

This commit adds a warning message if the used JSSE implementation does
not support TLS version 1.1 or newer. TLS version 1.0 is disabled by
default and additionaly all SSL versions are disabled -- which is done
by default in BaseSSLContextParameters, so its added here so that the
new default configuration does not override and allow SSL versions.
The main purpose of this commit is to allow users that are using Java 7
without support for TLS version 1.1 or newer, i.e. not using Oracle or
IBM Java or using custom SSL configuration with custom JSSE provider
that is configured or does not support TLS version 1.1 or newer --
to get an early warning (before March, 2017 when Salesforce disables TLS
version 1.0). And to set default enabled SSL protocols to TLS version
1.1 and onward.

CAMEL-10519 Disable TLSv1.0 in camel-salesforce

---

components/camel-stream/src/main/java/org/apache/camel/component/stream/StreamProducer.java

Set `doOutput` flag to true to handle streaming using URLConnection.

CAMEL-10534-Update StreamProducer to handle streaming using URLConnection

---

components/camel-cxf/src/main/java/org/apache/camel/component/cxf/CxfProducer.java
components/camel-cxf/src/test/java/org/apache/camel/component/cxf/noparam/NoParamEndpoint.java
components/camel-cxf/src/test/java/org/apache/camel/component/cxf/noparam/NoParamTest.java
components/camel-cxf/src/test/resources/org/apache/camel/component/cxf/noparam/camel-cxf.xml
components/camel-cxf/src/test/resources/org/apache/camel/component/cxf/noparam/camel-route.xml

I think getParams should return empty array when body is null.
This solves https://issues.apache.org/jira/browse/CAMEL-10607

CAMEL-10607

---

components/camel-test-blueprint/src/test/resources/org/apache/camel/test/blueprint/configadmin-endpoint-no-defaults.xml

Let me skip filing a JIRA as the fix is so tiny.

Fix blueprint-cm schema location to v1.1.0 for a camel-test-blueprint test

---

camel-core/pom.xml
camel-core/src/main/java/org/apache/camel/ComponentVerifier.java
camel-core/src/main/java/org/apache/camel/ComponentVerifierHelper.java
camel-core/src/main/java/org/apache/camel/impl/verifier/DefaultComponentVerifier.java
camel-core/src/main/java/org/apache/camel/impl/verifier/DefaultResult.java
camel-core/src/main/java/org/apache/camel/impl/verifier/DefaultResultVerificationError.java
camel-core/src/main/java/org/apache/camel/impl/verifier/ResultBuilder.java
camel-core/src/main/java/org/apache/camel/impl/verifier/ResultErrorBuilder.java
camel-core/src/main/java/org/apache/camel/impl/verifier/ResultErrorHelper.java
camel-core/src/test/java/org/apache/camel/ComponentVerifierTest.java
camel-core/src/test/java/org/apache/camel/LoggingLevelTest.java
camel-core/src/test/java/org/apache/camel/impl/verifier/DefaultComponentVerifierTest.java
components/camel-http/src/main/java/org/apache/camel/component/http/HttpComponentVerifier.java
components/camel-http/src/test/java/org/apache/camel/component/http/CamelComponentVerifierTest.java
components/camel-http4/src/main/java/org/apache/camel/component/http4/HttpComponentVerifier.java
components/camel-http4/src/test/java/org/apache/camel/component/http4/CamelComponentVerifierTest.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/SalesforceComponentVerifier.java
components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/SalesforceComponentVerifierTest.java
components/camel-servicenow/src/main/java/org/apache/camel/component/servicenow/ServiceNowComponentVerifier.java
components/camel-servicenow/src/test/java/org/apache/camel/component/servicenow/ServiceNowComponentVerifierTest.java
components/camel-twitter/src/main/java/org/apache/camel/component/twitter/TwitterComponentVerifier.java
components/camel-twitter/src/test/java/org/apache/camel/component/twitter/CamelComponentVerifierTest.java
connectors/camel-connector/src/main/java/org/apache/camel/component/connector/DefaultConnectorComponent.java

The following major changes are suggested:
* Using of interfaces and enums instead of string constants for error fields. This has the advantage of being typesafe but still extensible (custom fields can be easily added)
* Renamed Error to VerificationError as it conflicts with java.lang.Error which is allways imported
* Documentation to the interface
* Consolidation of provided constants, together with @lburgazzoli
* Adapted the using components (mainly http, http4, twitter, salesforce)
The initial work and discussion happened on https://github.com/rhuss/camel/pull/1 please refer to the discussion there, too.
The natural starting point is [ComponentVerifier](https://github.com/rhuss/camel/blob/2db634b81b8511217b0053a20dd888866e9fc662/camel-core/src/main/java/org/apache/camel/ComponentVerifi …

Polished ComponentVerifier interface

---

components/camel-grpc/src/main/java/org/apache/camel/component/grpc/GrpcProducer.java

missed callback.done(true) in catch block

camel-grpc: hangs on async invocation with exception

---

components/camel-elasticsearch5/src/test/java/org/apache/camel/component/elasticsearch5/ElasticsearchBaseTest.java
components/camel-elasticsearch5/src/test/java/org/apache/camel/component/elasticsearch5/ElasticsearchBulkTest.java
components/camel-elasticsearch5/src/test/java/org/apache/camel/component/elasticsearch5/ElasticsearchClusterBaseTest.java
components/camel-elasticsearch5/src/test/java/org/apache/camel/component/elasticsearch5/ElasticsearchClusterIndexTest.java
components/camel-elasticsearch5/src/test/java/org/apache/camel/component/elasticsearch5/ElasticsearchGetSearchDeleteExistsUpdateTest.java
components/camel-elasticsearch5/src/test/java/org/apache/camel/component/elasticsearch5/ElasticsearchIndexTest.java

The component test was hardcoded with number of ES ports (http, transport, etc.) and can to lead conflicts on CI server

camel-elasticsearch5: use dynamic ports in test

---

components/camel-grpc/pom.xml

Check if the running OS platform supports the protobuf generator plugin.
If the platform doesn't support, the protobuf test code generation, their  assembly and launch will be skipped. This prevents fails when build without "fastinstall" profile will run on unsupported by protoc plugin platform.

camel-grpc: Check if the OS supports the protoc/grpc generator plugin

---

camel-core/src/main/java/org/apache/camel/impl/FileWatcherReloadStrategy.java
camel-core/src/main/java/org/apache/camel/main/MainSupport.java
examples/camel-example-reload/src/main/java/org/apache/camel/example/reload/CamelReloadRecursivelyMain.java
examples/camel-example-reload/src/main/resources/META-INF/spring/bar/barContext.xml
examples/camel-example-reload/src/main/resources/META-INF/spring/camel-context.xml

FileWatcherReloadStrategy will watch sub-directories for a given path. This implementation will help if you have xml based routes configuration and for a given camelContext and if you have routeContexts imported and those imported xml routes are part of subdirectory of the camelContext. (see camel-example-reload)
isRecursive flag is defaulted to be false to avoid potential Shutdown problems if you have multiple xml route configurations and none are imported and somehow they are nested under the same path.

CAMEL-11275 FileWatcherReloadStrategy watches sub directories as well if isRecursive is true

---

components/camel-hipchat/src/main/java/org/apache/camel/component/hipchat/HipchatProducer.java
components/camel-hipchat/src/test/java/org/apache/camel/component/hipchat/integration/HipchatProducerIntegrationTest.java

This allows messages to be sent to room names containing spaces or other URL-unsafe characters.

CAMEL-11520 URL-encode hipchat room names

---

parent/pom.xml

Java Mail 1.6.0 should be binary compatible to 1.5.x according to https://javaee.github.io/javamail/docs/COMPAT.txt
Camel-mail tests pass.

Upgrade Java Mail to version 1.6.0

---

components/camel-milo/src/main/java/org/apache/camel/component/milo/client/internal/SubscriptionManager.java

When the sampling interval is unset in the Camel component, then it is passed to milo as `null`. Which is acceptable to the milo API, however internally milo automatically unboxes the value from `Double` to `double` and may run into a NPE by doing so.
This patch assures that, although theoretically acceptable, `null` is never passed in to the Milo API.
Signed-off-by: Jens Reimann <jreimann@redhat.com>

CAMEL-11559: Work around a NPE in milo 0.1.3

---

components/camel-spring-boot/src/test/java/org/apache/camel/spring/boot/cloud/CamelCloudServiceCallGlobalConfigurationTest.java
components/camel-spring-boot/src/test/java/org/apache/camel/spring/boot/cloud/CamelCloudServiceCallRefExpressionTest.java
components/camel-spring-boot/src/test/java/org/apache/camel/spring/boot/cloud/CamelCloudServiceCallSimpleExpressionTest.java
components/camel-spring-boot/src/test/java/org/apache/camel/spring/boot/cloud/CamelCloudServiceCallTest.java
components/camel-spring-boot/src/test/java/org/apache/camel/spring/boot/cloud/SpringBootPropertyUtil.java

  "CAMEL-11617:spring-boot - service-call tests uses hardcoded port numbers"

 "CAMEL-11617:spring-boot - service-call tests uses hardcoded port numbers"

---

components/camel-docker/pom.xml
components/camel-docker/src/test/java/org/apache/camel/component/docker/consumer/DockerEventsConsumerTest.java
components/camel-docker/src/test/java/org/apache/camel/component/docker/consumer/DockerStatsConsumerTest.java
components/camel-docker/src/test/java/org/apache/camel/component/docker/headers/BaseDockerHeaderTest.java

Since I was already working in this area. This is a start towards https://issues.apache.org/jira/browse/CAMEL-11845.

CAMEL-11845: Remove powermock from camel-docker

---

components/camel-jpa/pom.xml

With this, `mvn clean install` builds successfully on entire Apache Camel project with JDK9 GA.
Thanks!

Fix camel-jpa on JDK9 GA

---

tests/camel-itest/pom.xml

Skip only CXF integration test.

Enable more tests that now pass on JDK9 GA

---

components/camel-sip/src/main/java/org/apache/camel/component/sip/SipConfiguration.java

It is more efficient to use the static parseXXX method to extract unboxed primitive value from a String.
http://findbugs.sourceforge.net/bugDescriptions.html#DM_BOXED_PRIMITIVE_FOR_PARSING

Replace the Number.valueOf method with the Number.parseXXX method.

---

camel-core/src/main/java/org/apache/camel/impl/MessageSupport.java
camel-core/src/test/java/org/apache/camel/impl/DefaultMessageTest.java

After upgrade camel 2.20.0, some operations fail with a NullPointerException:
```
Caused by: java.lang.NullPointerException
at org.apache.camel.impl.MessageSupport.setBody(MessageSupport.java:122)
```
The issue seems to be introduced with the change CAMEL-11380.
The issue could be easily reproduced by using the deprecated constructor, where no camelContext is set:
```
Message message = new DefaultMessage();
message.setBody("something");
```
To remain better backward compatibility, i would suggest a nullcheck in the setBody for cases where the CamelContext is not set.

CAMEL-11948  NPE on DefaultMessage setBody if deprecated constructor was used

---

components/camel-twilio/src/main/docs/twilio-component.adoc

It fixes one missing url in camel-twilio doc.

camel-twilio - Update Twilio Java SDK API url

---

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/streaming/SubscriptionHelper.java

clearing salesforce session when bayeux client receive 403 
https://issues.apache.org/jira/browse/CAMEL-11980

clearing salesforce session when bayeux client receive 403 

---

components/camel-cdi/src/test/resources/camel-context-errorHandler.xml
components/camel-cdi/src/test/resources/camel-context-routeContextRef-import.xml

This was caused by [CAMEL-11822](https://issues.apache.org/jira/browse/CAMEL-11822). Looks like jaxb 2.3.0 is stricter with namespace declarations. Tested on Java 9 GA as well.

Fix tests in camel-cdi

---

components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/MongoDbTailingProcess.java

Is it still possible to include this fix into v2.20.1. It would be very good if so.

CAMEL-11977: MongoDB Tailable cursor consumer fails to stop on shutdown

---

camel-core/src/main/docs/xslt-component.adoc

The contents have been given an overhaul. I have corrected grammar and clarified instructions. The original requirements were:
broken link to Exchange in deleteOutputFile option
these sentences should probably we reworked a bit:
"Then in Camel 2.10.3 and older, then Camel will use "classpath:" as the default prefix, and load the resource from the classpath."
"You can still though explicit configure a prefix, and then mix and match."
I have updated a fair bit more than that, though.

FUSEDOC-2074 - update contents

---

components/camel-rabbitmq/src/main/docs/rabbitmq-component.adoc

Corrected an error in routing URIs of Samples Section. 
the URI in Samples should be C instead of B.

Corrected an error in routing URIs

---

components/camel-cxf/src/main/docs/cxf-component.adoc
components/camel-cxf/src/main/docs/cxfrs-component.adoc

There are old or missing links in:
https://github.com/apache/camel/blob/master/components/camel-cxf/src/main/docs/cxfrs-component.adoc
Also part of the listing structure is broken in cxf-component.adoc.

Fix broken layout and links in camel-cxf docs

---

components/camel-netty4/src/main/java/org/apache/camel/component/netty4/NettyProducer.java

* Since 2.17.4, ChannelFuture was never release when a connection error occurs.
https://issues.apache.org/jira/browse/CAMEL-12016

CAMEL-12016 : ChannelFuture is not clearly erased from the pool on connection error

---

components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQConstants.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQMessageConverter.java
components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/RabbitMQEndpointTest.java

This fix sets REDELIVERY_TAG header on exchanges that were already delivered once by rabbitmq. https://www.rabbitmq.com/reliability.html

CAMEL-12014: Added support for redelivered tag for RabbitMQ

---

components/camel-spring/pom.xml

This fix makes the build succeed on windows.

CAMEL-11942: Switched to jaxb2-maven-plugin for camel-spring schemagen

---

camel-core/src/main/docs/file-component.adoc
camel-core/src/main/java/org/apache/camel/component/file/FileConsumer.java
camel-core/src/main/java/org/apache/camel/component/file/GenericFileEndpoint.java
components/camel-ftp/src/main/docs/ftp-component.adoc
components/camel-ftp/src/main/docs/ftps-component.adoc
components/camel-ftp/src/main/docs/sftp-component.adoc
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpConsumer.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/SftpConsumer.java

even though i believe this issue is not related to sorting file list beforehand, i am just opening the PR to discuss further and revise...
@davsclaus could you review?

CAMEL-11656 - add preSort option

---

camel-core/src/main/java/org/apache/camel/processor/idempotent/FileIdempotentRepository.java

Also consider moving this initalization block to a default constructor.

CAMEL-12037 Idempotent repository cache initialization fix.

---

components/camel-jpa/src/main/docs/jpa-component.adoc

I've amended some of the grammar.
Integration with JPA isn't in the upstream content. Looking at it, I think the Camel on EAP deployment section is specific to Fuse content.
The broken links have been upated to provide the full URL to the Camel source (e.g. http://camel.apache.org/tracer-example.html). The first part was omitted, I think because they would have originally been called from inside the Apache Camel website. Expanding them should make them work for Camel and Fuse.
I couldn't find a reference to 'maximumResults' in the upstream topic, so I guess it's been removed.

FUSEDOC-2096 - Update links and correct grammar

---

components/camel-rss/src/main/docs/rss-component.adoc

I've updated some of the grammar here and there. 
The section called 'Using the JPA based idempotent repository' particularly needs to be looked at because:
- The instructions were not clear. The language was very strange and sometimes incomprehensible. I've rewritten it as best as I can but it needs a review.
- It seemed that assumptions were made about the level of prior knowledge as far as this subject goes. A straw poll of developers here shows that they know the concept, but not necessarily that terminology. 
- The examples were missing. Asciidoc doesn't seem to handle snippets at all.

FUSEDOC-2094 - update snippets links and grammar

---

camel-core/src/main/java/org/apache/camel/builder/NotifyBuilder.java
camel-core/src/test/java/org/apache/camel/builder/NotifyBuilderTest.java

+ Java 7 tidy up
Note I used the eventNotifier status in create() to determine "isDestroyed" rather than an explicit field. We could use the same to replace `created` and integrate both concepts together.. (I can amend PR if requested)

CAMEL-12056 Add NotifyBuilder.destroy() method

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaComponent.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaEndpoint.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaProducer.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaProducerTest.java

If topic property was not received from configuration or header parameters take it from the remaining URI. Also some minor code style fixes are applied.

CAMEL-12076: Specified topic is ignored when KafkaConfiguration is used

---

components/camel-olingo4/camel-olingo4-component/src/test/java/org/apache/camel/component/olingo4/Olingo4ComponentTest.java

This code adds filter test for camel-olingo4 and shows that encoding for query params is implemented inside olingo4 library

CAMEL-12084: Test encoding for query params in camel-olingo4

---

components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQConsumer.java

Suspend calls closeConnectionAndChannel() which calls this.consumers.clear(); thus leaving no consumers to reconnect on resume.  This used to work because the reconnect was creating consumers a second time with the startConsumers() call in StartConsumerCallable.call() but that was creating twice the required number of consumers in other normal use cases.  In this case because clear is called we need to create those consumers again on resume hence the code changes here.  All integration tests passing now.

CAMEL-12129: fix broken integration test from CAMEL-12111

---

components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxFoldersManager.java
components/camel-box/camel-box-component/src/main/docs/box-component.adoc
components/camel-box/camel-box-component/src/test/java/org/apache/camel/component/box/BoxFoldersManagerIntegrationTest.java

Add possibility to specify folder by path as String[] when creating folders in Box, similarly to getFolder. It makes creation of nested folders in routes much easier.
Note that createFolder(String, String[]) doesn't throw exception when folders exists unlike createFolder(String, String). This can be argued, but mimics the behaviour of, e.g., mkdir on Linux.

CAMEL-11885: Add support for creating folder by path in camel-box

---

components/camel-sql/src/main/java/org/apache/camel/processor/idempotent/jdbc/JdbcMessageIdRepository.java

To use a custom table name you have to define custom queries, but the _clearString_ field is private and cannot be set.
PR contents:
- exposed accessor methods for _clearString_ field
- access configurable queries through getters instead than accessing private fields (reducing the coupling to private fields, i.e. could be extracted an interface defining the getters)

Jdbc idempotent enhancements (clearString accessors + internally use getters)

---

parent/pom.xml

CXF logging interceptors are now in a separate module.
See also http://cxf.apache.org/docs/message-logging.html

BOM: add cxf-rt-features-logging

---

parent/pom.xml

Upgrade Braintree Java SDK to version 2.75.0. Previous versions used the org.json library, whose license has been deemed x-category by the ASF, and cannot be used at all.

CAMEL-12180 - upgrade Braintree Java SDK to version 2.75.0

---

components/camel-xchange/src/main/docs/xchange-component.adoc
components/camel-xchange/src/main/java/org/apache/camel/component/xchange/XChangeAccountProducer.java
components/camel-xchange/src/main/java/org/apache/camel/component/xchange/XChangeComponent.java
components/camel-xchange/src/main/java/org/apache/camel/component/xchange/XChangeConfiguration.java
components/camel-xchange/src/main/java/org/apache/camel/component/xchange/XChangeEndpoint.java
components/camel-xchange/src/main/java/org/apache/camel/component/xchange/XChangeMarketDataProducer.java
components/camel-xchange/src/test/java/org/apache/camel/component/xchange/account/AccountProducerTest.java
components/camel-xchange/src/test/java/org/apache/camel/component/xchange/market/MarketDataProducerTest.java
components/camel-xchange/src/test/java/org/apache/camel/component/xchange/metadata/MetaDataProducerTest.java
parent/pom.xml

[XChange] Add initial support for account management

---

components/camel-slack/src/main/java/org/apache/camel/component/slack/SlackProducer.java

http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/HttpClientBuilder.html

SlackProducer should be able to use a HTTP proxy to reach Slack in a secured environnement

---

camel-core/src/main/java/org/apache/camel/processor/RedeliveryPolicy.java
components/camel-core-xml/src/main/java/org/apache/camel/core/xml/AbstractCamelRedeliveryPolicyFactoryBean.java

this synchronizes the attributes present in two similar classes:
- RedeliveryPolicyDefinition
- RedeliveryPolicyFactoryBean
the latter was missing: `logNewException` and `logExhaustedMessageBody`, making it impossible to use it in xml routes definitions.

add missing attributes in RedeliveryPolicyFactoryBean

---

components/camel-milo/src/main/docs/milo-client-component.adoc
components/camel-milo/src/main/java/org/apache/camel/component/milo/client/MiloClientConfiguration.java
components/camel-milo/src/main/java/org/apache/camel/component/milo/client/internal/SubscriptionManager.java
platforms/spring-boot/components-starter/camel-milo-starter/src/main/java/org/apache/camel/component/milo/client/springboot/MiloClientComponentConfiguration.java

This change adapts the client to the changed behavior of
Eclipse Milo 0.2.x. It does an explicit call to connect and also allows
to configure the allowed security policies in order to still support
anonymous access when no keys are used.

CAMEL-12286: Fix camel-milo client component

---

camel-core/src/main/java/org/apache/camel/processor/aggregate/BatchAggregationStrategy.java
camel-core/src/main/java/org/apache/camel/util/toolbox/AggregationStrategies.java

I mostly found myself having the need to group the bodies (only) in a List (not Exchange or Message), so I think it will be useful to have this generic "batch" aggregation strategy in the Camel core.
Maybe the more proper naming could be GroupedBodyAggregationStrategy or GroupedInputBodyAggregationStrategy, but they're quite long :-). So I leave the naming change consideration up to you.

Added BatchAggregationStrategy

---

docs/user-manual/en/building.adoc

The previous memory limit for Eclipse is too low and old. this value was obsolete.
I suggest after some tests to use 4GB or 8GB for some use cases.

Updating Java memory when using Eclipse

---

components/camel-dropbox/src/main/java/org/apache/camel/component/dropbox/core/DropboxAPIFacade.java

Specifically the bug was in class DropboxAPIFacade.java lines 114, 115, 142, 143. The exception thrown is about upload a file into a not file path or a folder into a not folder path, but the new version of dropbox java sdk don't provides the method entry.isFile() or entry.isFolder(), and the code as is now, is throwing erroneous exceptions, if the file exists remotely, a exception will be thrown, and in config, we have the force mode, i think this snipped of code should be erased or the mode=force param needs to be verified.

Fix DropboxAPIFacade.java

---

components/camel-olingo4/camel-olingo4-api/pom.xml

This should please be ported to `camel-2.21.x` too

CAMEL-12407: camel-olingo4-api should explicitly depend on commons-io

---

components/camel-cxf/src/main/java/org/apache/camel/component/cxf/CxfConsumer.java
components/camel-cxf/src/main/java/org/apache/camel/component/cxf/jaxrs/CxfRsInvoker.java
components/camel-cxf/src/test/java/org/apache/camel/component/cxf/CxfConsumerContinuationTimeoutTest.java

https://issues.apache.org/jira/browse/CAMEL-12409
This should be un-reverted for Camel 2.22.0
This reverts commit c789e1f6b09b57d1b0882268ebbe8fecfa9c05b2.
@davsclaus could you please review?

CAMEL-12409 Temporary revert CAMEL-12104 Unintuitive default cxf timeout

---

components/camel-elasticsearch-rest/src/main/java/org/apache/camel/component/elasticsearch/ElasticsearchProducer.java
components/camel-elasticsearch-rest/src/test/java/org/apache/camel/component/elasticsearch/ElasticsearchBulkTest.java

Currently, when bulk indexing requests are used, only document ids are returned in the exchange body.
That not enough if you really want a good indexing failure management.
Instead, it should return the complete bulk item response.
This way, we could get the exact error messages.

CAMEL-12419: camel-elasticsearch-rest should return complete bulk response instead of just ids

---

components/camel-aws-xray/src/main/java/org/apache/camel/component/aws/xray/XRayTracer.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/ABCRouteTest.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/BeanTracingTest.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/ClientRecipientListRouteTest.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/ComprehensiveTrackingTest.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/CustomComponentTest.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/EIPTracingTest.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/ErrorHandlingTest.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/ErrorTest.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/MulticastParallelRouteTest.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/MulticastRouteTest.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/Route2ConcurrentTest.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/RouteConcurrentTest.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/SpringAwsXRaySimpleRouteTest.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/TestUtils.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/TwoService2Test.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/TwoServiceTest.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/TwoServiceWithExcludeTest.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/bean/ProcessingCamelBean.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/bean/SomeBackingService.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/component/CommonEndpoints.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/component/TestXRayComponent.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/component/TestXRayEndpoint.java
components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/component/TestXRayProducer.java
components/camel-aws-xray/src/test/resources/META-INF/services/org/apache/camel/component/xray-test

Currently when invoking a route asynchronously via Camel there is a chance that the processing of that code doesn't occur before the current thread was able to complete its task and therefore allowing XRay to emit the segment. On processing of the asynchronous route and its beans or processors, the segment was already emitted and thus XRay does not allow to send that information to AWS. In that case an `AlreadyEmittedException` is thrown.
This PR will catch these exceptions and convert them to a warn-log. A further test using a custom compoent which uses a backing service for certain states that sends data to a further route asynchronously was added to showcase the cases when this issue may occur.
Other XRay based tests also got updated slightly in order to use `NotifyBuilder` in order to …

AWS XRay - suppress exception on already emitted segments

---

examples/camel-example-spring-boot-rest-swagger/pom.xml

missing servlet-api dependendency

CAMEL-12445: spring-boot-rest-swagger example does not compile due to

---

components/camel-consul/src/main/java/org/apache/camel/component/consul/cloud/ConsulServiceDiscovery.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cloud/ConsulServiceDiscoveryTest.java

In Consul catalog registered two instances of one service. Health check for first instance have "passed" state, and for second instance - "critical". Camel returns both service instances with healty checks, which method "isHealthy" returns "false".

CAMEL-12448  - camel-consul: filter health checks by service id

---

camel-core/src/main/java/org/apache/camel/impl/cloud/DefaultServiceLoadBalancer.java
camel-core/src/test/java/org/apache/camel/impl/cloud/LoadBalancerTest.java

If no services remains after applying ServiceFilter in DefaultServiceLoadBalancer, expecting exception RejectedExecutionException("No active services with name " + serviceName), but throws IndexOutOfBoundsException.

CAMEL-12449: DefaultServiceLoadBalancer throws IndexOutOfBoundsException

---

components/camel-consul/src/main/java/org/apache/camel/component/consul/endpoint/ConsulEventConsumer.java

I believe that scheduledExecutorService with schedule method will be a little better then Thread.sleep(mills) (maybe i'm wrong).
Also, i didn't add default value as proposed in description of this problem because as i found in `ConsulClientConfiguration` the default value of  `blockSeconds` is 10:
```
@UriParams
public class ConsulClientConfiguration implements Cloneable {
. . . 
@UriParam(label = "consumer,watch", defaultValue = "10")
private Integer blockSeconds = 10;
. . . 
}
```
Result of `mvn clean install -Psourcecheck`:
```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Camel :: Consul 2.22.0-SNAPSHOT
[INFO] …
```

CAMEL-12418: High CPU load on events watching

---

archetypes/camel-archetype-spring-boot/src/main/resources/archetype-resources/readme.adoc
archetypes/camel-archetype-spring-boot/src/main/resources/archetype-resources/src/main/resources/application.properties
components/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/actuate/endpoint/CamelRoutesEndpoint.java
components/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/actuate/endpoint/CamelRoutesEndpointAutoConfiguration.java
components/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/actuate/endpoint/CamelRoutesEndpointProperties.java
components/camel-spring-boot/src/main/resources/META-INF/additional-spring-configuration-metadata.json
examples/camel-example-spring-boot-supervising-route-controller/pom.xml
examples/camel-example-spring-boot-supervising-route-controller/readme.adoc
examples/camel-example-spring-boot-supervising-route-controller/src/main/resources/application.properties
examples/camel-example-spring-boot/readme.adoc
examples/camel-example-spring-boot/src/main/resources/application.properties
parent/pom.xml

Also extracted CamelRoutesEndpointProperties as a separated class from CamelRoutesEndpoint
I wanted to make sure if it's OK to add `-parameters` javac option in parent POM.
https://github.com/apache/camel/pull/2307/files#diff-04dc5d029560773ac79faaf3da0fbb22
This option preserves method parameter names in class file, which is required for SB2 actuator endpoint to map path parameters.
https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-endpoints.html
> To allow the input to be mapped to the operation method’s parameters, Java code implementing an endpoint should be compiled with -parameters
Hopefully nothing depends on class file format, so that this option doesn't break anything.

CAMEL-12460 Fix camel actuator endpoints to get it working with SB2

---

examples/camel-example-ceylon/.gitignore
examples/camel-example-ceylon/ReadMe.md
examples/camel-example-ceylon/pom.xml
examples/camel-example-ceylon/src/main/ceylon/org/apache/camel/example/MyRouteBuilder.ceylon
examples/camel-example-ceylon/src/main/ceylon/org/apache/camel/example/package.ceylon
examples/camel-example-ceylon/src/main/ceylon/org/apache/camel/example/run.ceylon
examples/camel-example-ceylon/src/main/resources/log4j2.properties
examples/camel-example-ceylon/src/main/resources/module/module.ceylon
examples/pom.xml

Adding Camel example for Ceylon 1.3.3. 
Followed the path of the Kotlin example as instructed on the ticket. 
Compile/Runs without errors and I'm able to access Jetty's localhost:8080 for the welcome message.
Things I couldn't get around: 
1.  The module.ceylon file cannot refer to Maven POM versions/properties unfortunately needing a hardcoded version of the used libs ([double-checked on the Ceylon Gitter channel too](https://gitter.im/ceylon/user?at=5adda26e62316e0505eceb43))
2. I had to hardcode the version of camel-http-common since the 2.22.0-SNAPSHOT does not exist

CAMEL-10671: Adding Camel example project for the Ceylon JVM language

---

components/camel-kafka/src/main/docs/kafka-component.adoc
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConfiguration.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaHeaderFilterStrategy.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaProducer.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaConsumerFullTest.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaProducerFullTest.java
platforms/spring-boot/components-starter/camel-kafka-starter/src/main/java/org/apache/camel/component/kafka/springboot/KafkaComponentConfiguration.java

Since 0.11.0 Kafka support headers, and it would be awesome to have such feature available also in camel component.
By default it filters camel related headers and propagate filtered kafka headers to camel and vice versa.

CAMEL-12503: added support for propagating camel headers to kafka and vice versa

---

camel-core/src/main/docs/rest-dsl.adoc
camel-core/src/main/java/org/apache/camel/model/rest/RestBindingDefinition.java
camel-core/src/main/java/org/apache/camel/model/rest/RestConfigurationDefinition.java
camel-core/src/main/java/org/apache/camel/model/rest/RestDefinition.java
camel-core/src/main/java/org/apache/camel/model/rest/VerbDefinition.java
camel-core/src/main/java/org/apache/camel/processor/RestBindingAdvice.java
camel-core/src/main/java/org/apache/camel/spi/RestConfiguration.java
components/camel-jetty9/src/test/java/org/apache/camel/component/jetty/rest/RestJettyAcceptTest.java
components/camel-jetty9/src/test/java/org/apache/camel/component/jetty/rest/RestJettyContentTypeTest.java
components/camel-jetty9/src/test/java/org/apache/camel/component/jetty/rest/RestJettyRequiredBodyTest.java
components/camel-jetty9/src/test/java/org/apache/camel/component/jetty/rest/RestJettyRequiredHttpHeaderTest.java
components/camel-jetty9/src/test/java/org/apache/camel/component/jetty/rest/RestJettyRequiredQueryParameterTest.java
platforms/spring-boot/components-starter/camel-core-starter/src/main/java/org/apache/camel/model/rest/springboot/RestConfigurationDefinitionProperties.java

So we check whether required data is included in the client http request when being processed by rest-dsl consumer. 
We now check for missing
- query parameters
- http headers
- body
The context-path is already handled in the uri path matcher, so it will fail already for invalid context-path.
This can be turned on in the rest configuration.

CAMEL-11162: rest-dsl add client request validation

---

parent/pom.xml

In 2.4.8, mockito and hamcrest were in compile scope instead of test
scope

Upgrade Async http client to version 2.4.9

---

components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpEndpoint.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpsEndpoint.java

I found that always `timeout` parameter wins and `ftpClient.dataTimeout` is neglected although the doc suggests it should be honoured.

camel-ftp - Fix ftpClient.dataTimeout parameter is not honoured

---

components/camel-jms/src/main/docs/jms-component.adoc

These updates are based on the review by Viliam Kasala that is captured in this issue:
https://issues.jboss.org/browse/FUSEDOC-1918 
An update that I did NOT make was to delete the reference to Torsten Mielke's blog. I asked Torsten about whether the information was still relevant, but he did not reply. He wrote the blog in 2012, and updated it in 2017. It has to do with using the JMS component with transactions. Let me know if you want me to remove the reference. Or, of course, please remove it if you think that's best. 
Also, Fintan says: "when submitting the PR, ask the reviewer to cherry-pick the fix to the camel-2.21.x upstream branch."
Hope I did this right!

user doc: FUSEDOC-1918, updates from Viliam Kasala review

---

camel-core/src/main/java/org/apache/camel/processor/aggregate/AggregateProcessor.java

When a Aggregator route is stopped, only the AggregateRecoveryChecker threads are stopped and not the AggregateTimeoutChecker threads. They keep lingering around. - CAMEL-12588

Cleanup TimeOutChecker threads

---

Jenkinsfile

The deploy profile attaches javadoc and sources: https://github.com/apache/camel/blob/master/pom.xml#L591
Note that I can't test this myself since this runs on Jenkins and publishes to the ASF repo, neither of which I can access :)
https://issues.apache.org/jira/browse/CAMEL-12593

[CAMEL-12593] Active deploy profile when deploying

---

pom.xml

Some modules use custom Javadoc tags that cause the build to break
when the Javadoc linter checks the sources. This had been disabled
by providing additional parameters to the maven-javadoc-plugin.
The element name for providing additional parameters has changed
since maven-javadoc-plugin version 3.0.0, therefore the previous
fix didn't work anymore.
This commit fixes this problem and disables Javadoc linting by
using the correct element `additionalParamaeters`.

Fix Javadoc linting issues

---

camel-core/src/main/java/org/apache/camel/processor/DefaultExchangeFormatter.java

DefaultExchangeFormatter: Add a NOP method that can be used by child classes to filter headers and properties.
I

CAMEL-12609: Filter Headers/Properties in DefaultExchangeFormatter

---

components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitConsumer.java

The description of the problem:
https://issues.apache.org/jira/browse/CAMEL-12643
I added a full stack trace information to the logging statement, so that the exception type can be generated to the logs.

CAMEL-12643: Inadequate information for handling catch clauses

---

camel-core/src/main/java/org/apache/camel/impl/ConsumerCache.java
components/camel-atomix/src/main/java/org/apache/camel/component/atomix/client/value/AtomixValueConsumer.java
components/camel-aws/src/main/java/org/apache/camel/component/aws/mq/MQProducer.java
components/camel-digitalocean/src/main/java/org/apache/camel/component/digitalocean/producer/DigitalOceanDropletsProducer.java
components/camel-docker/src/main/java/org/apache/camel/component/docker/producer/DockerProducer.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpsEndpoint.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/deployments/KubernetesDeploymentsProducer.java
components/camel-netty4/src/main/java/org/apache/camel/component/netty4/handlers/ClientChannelHandler.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQProducer.java
components/camel-sip/src/main/java/org/apache/camel/component/sip/listener/SipPresenceAgentListener.java
components/camel-wordpress/src/main/java/org/apache/camel/component/wordpress/producer/WordpressUserProducer.java
platforms/camel-catalog-nexus/src/main/java/org/apache/camel/catalog/nexus/ConnectorCatalogNexusRepository.java

The description of the issue:
https://issues.apache.org/jira/browse/CAMEL-12650
There are some possible copy and paste errors in the log messages (The logging statement was copied from an old place to a new place, but the message wasn't changed to adapt to the function of the new place. The issue report shows the pairs of original places where the logging statements might be copied from, and the new places that copied to) which may cause confusion when operators are reading the log messages.  I changed the logging messages to make them more adaptive

CAMEL-12650 Log messages that do not match with their method function

---

components/camel-braintree/pom.xml
components/camel-braintree/src/main/docs/braintree-component.adoc
components/camel-braintree/src/test/java/org/apache/camel/component/braintree/ReportGatewayIntegrationTest.java
parent/pom.xml

Upgraded Braintree Java SDK to 2.83.1 and exposed transaction level fees API

CAMEL-12649: camel-braintree - Upgraded Braintree Java SDK to 2.83.1 and exposed transaction level fees API

---

camel-core/src/main/java/org/apache/camel/builder/xml/XsltUriResolver.java
camel-core/src/main/java/org/apache/camel/component/xslt/XsltEndpoint.java
camel-core/src/test/java/org/apache/camel/component/xslt/XsltIncludeRelativeNestedTest.java
camel-core/src/test/resources/org/apache/camel/component/xslt/included/staff_included_nested_level_1.xsl
camel-core/src/test/resources/org/apache/camel/component/xslt/staff_include_relative_nested.xsl
camel-core/src/test/resources/org/apache/camel/component/xslt/staff_included_nested_level_2.xsl

If an XSLT A includes XSLT B which includes XSLT C using relative references, XSLT C is resolved relative to A instead of B.
An example is added in unit test XsltIncludeRelativeNestedTest.
This PR changes this behavior to the expected one, i.e. resolve relative references based on the location of the direct parent XSLT.

CAMEL-12685: fix xslt nested relative refs

---

components/camel-zipkin/src/main/java/org/apache/camel/zipkin/ZipkinTracer.java

https://issues.apache.org/jira/browse/CAMEL-12656
I have added screenshots in Jira already.
Camel-Zipkin does not report traces with root span id when there are multiple routes. 
For example: 
```
from("direct:foo")
.delay(1000)
.to("direct:bar")
.to("direct:moo")
.to("direct:tar");
from("direct:bar")
.delay(2000);
from("direct:moo")
.delay(1000);
from("direct:tar")
.delay(3000);
```
Root SpanId(TraceId) should be for service-name = direct:foo and the trace in UI should show all the 4 routes in one sequence. But it breaks. Check the attached screenshot: Traces Breaking.png
I looked into the code and figured out why its happening. Here is the code which is breaking the functionality.
Class Name: ZipkinTracer.ZipkinRoutePolicy
Inside onExchangeBegin() method 
```
// add on completion after …
```

CAMEL-12656: Fixed root span id for multiple routes.

---

camel-core/pom.xml
components/camel-atomix/pom.xml
components/camel-cdi/pom.xml
components/camel-ehcache/pom.xml
components/camel-hipchat/pom.xml
components/camel-jcache/pom.xml
components/camel-metrics/pom.xml
components/camel-micrometer/pom.xml
components/camel-pdf/pom.xml
components/camel-tika/pom.xml
components/camel-yql/pom.xml
examples/camel-example-cdi-metrics/pom.xml
examples/camel-example-cdi-properties/pom.xml
examples/camel-example-cdi-rest-servlet/pom.xml
examples/camel-example-cdi-test/pom.xml
examples/camel-example-cdi-xml/pom.xml
tooling/maven/camel-eip-documentation-enricher-maven-plugin/pom.xml

Check [CAMEL-12710](https://issues.apache.org/jira/browse/CAMEL-12710) out for more.

CAMEL-12710: Kept a single version of hamcrest classes on the classpath

---

camel-core/src/main/java/org/apache/camel/builder/xml/XsltUriResolver.java
camel-core/src/test/java/org/apache/camel/builder/xml/XsltUriResolverTest.java

fix for CAMEL-12713
FileUtil.compactPath() is used to calculate the relative URI, but this call ignores the colon separator and considers "classpath:directory" as a single path part. 
This patch passes the URI without its scheme to FileUtil.compactPath() and attaches it again to the result.

CAMEL-12713 - XsltUriResolver fix: relative imports can ignore URI scheme 

---

components/camel-cxf/src/main/java/org/apache/camel/component/cxf/CxfEndpoint.java
components/camel-cxf/src/main/java/org/apache/camel/component/cxf/CxfSpringEndpoint.java
components/camel-cxf/src/main/java/org/apache/camel/component/cxf/WSDLServiceFactoryBean.java
components/camel-cxf/src/test/java/org/apache/camel/component/cxf/CxfPayloadWsdlWithoutSEITest.java
components/camel-cxf/src/test/resources/org/apache/camel/component/cxf/CxfPayloadWsdlWithoutSEI.xml

Support JAX-WS handlers for cxf endpoint in payload mode with a WSDL specified and without service class by using a JaxWsEndpointImpl instead of EndpointImpl and removing some checks that avoid the handlers being set.
I removed the CxfSpringEndpoint.getSEIClass() method as it did the same as getServiceClass().

CAMEL-12714 - support handlers in cxf payload mode without SEI

---

components/camel-ftp/src/main/docs/sftp-component.adoc
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/SftpConfiguration.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/SftpOperations.java

Add configuration property 'bindAddress' for SFTP to specify the local interface to which the SFTP connection should bind.
Because the underlying SFTP library JSch does not support setting the bind address directly, I have configured the JSch Session with an own ConnectionFactory which opens a Socket by specifying the bindAddress.

[CAMEL-12711] Add configuration property 'bindAddress' for SFTP

---

examples/camel-example-zipkin/service1/src/main/resources/application.properties

I also encountered the same issue while running the camel-zipkin example quickstart. Made changes as per this issue, https://github.com/spring-projects/spring-boot/issues/13506 we can see the quickstart working as expected.

CAMEL-12587: camel-zipkin-starter fails mapping service names

---

camel-core/src/main/java/org/apache/camel/processor/Throttler.java

FindBugs-3.0.1 ([http://findbugs.sourceforge.net/](http://findbugs.sourceforge.net/)) reported 2 RC_REF_COMPARISON warnings on master:
```
H C RC: Suspicious comparison of Integer references in org.apache.camel.processor.Throttler.calculateAndSetMaxRequestsPerPeriod(Exchange)  At Throttler.java:[line 312]
H C RC: Suspicious comparison of Integer references in org.apache.camel.processor.Throttler.calculateAndSetMaxRequestsPerPeriod(DelayQueue, Exchange, Integer)  At Throttler.java:[line 360]
```
The description of the bug is as follows:
> **RC: Suspicious reference comparison (RC_REF_COMPARISON)**
> This method compares two reference values using the == or != operator, where the correct way to compare instances of this type is generally with the equals() method. It is possible to create …

CAMEL-12730: Fix FindBugs warnings: Suspicious reference comparison

---

components/camel-cdi/src/main/java/org/apache/camel/cdi/CdiCamelExtension.java
components/camel-cdi/src/test/java/org/apache/camel/cdi/bean/FirstCamelContextConvertingRoute.java
components/camel-cdi/src/test/java/org/apache/camel/cdi/bean/SecondCamelContextConvertingRoute.java
components/camel-cdi/src/test/java/org/apache/camel/cdi/test/InjectedTypeConverterMultipleContextsTest.java

while loading discovered type converters into the camel context a single instance of `CdiTypeConverterLoader` was used for all context, but the it only loads classes the first time and then caches the results.
Changed to use one loader per context

CAMEL-12739: fix camel-cdi multi context type converter registration

---

components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/services/KubernetesServicesConsumer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/services/KubernetesServicesProducer.java

https://issues.apache.org/jira/browse/CAMEL-12746
This is a fix for the above issue of temporary reply queues getting stale un-acked messages. The fix ensures that temp reply queues will be always created with the autoAck setting set to true.

Fix for CAMEL-12746 (temp reply queue autoAck)

---

components/camel-spring-boot/src/main/docs/spring-boot.adoc

Based on the issue raised in https://issues.apache.org/jira/browse/CAMEL-11687, here's an addition to the Spring Boot docs page, which introduces testing, along with an example test class.
Comments/feedback welcome :-)

Adding docs section on Spring Boot testing with example

---

docs/user-manual/en/async.adoc

a link was there in the current published version, but references seem to be missing in current iteration.  I have moved the appropriate code samples into the documentation so it makes a little more sense.

CAMEL-12781: Re-adding missing code samples to documentation

---

components/camel-reactive-streams/pom.xml
components/camel-reactive-streams/src/test/java/org/apache/camel/component/reactive/streams/DirectClientAPITest.java

there is no expected order from product side. The tests were checking
them in a particular order.
i'm not sure if it was a bug in Camel which is not enforcing the order in the list or if it is that the test should not expect a specific order.
This PR took the party that the retrived list can be done in any order and then updates the tests.

Check message received in queue in no particular order

---

components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/SftpConsumerDisconnectTest.java

I think it will be better to mark this test case as ignore.
the reason for this is that the error case is simulated with processor to disconnect all sessions and exchange often does not reach to an end and session is closed and leaving with closed input stream as indicated in the log entry of the issue. Because in 
https://github.com/apache/camel/blob/master/camel-core/src/main/java/org/apache/camel/component/file/GenericFileOnCompletion.java#L127
where the deletion is handle over GenericFileDeleteProcessStrategy which runs after exchange is completed and ftp sessions are disconnected before it really does moving or deleting.
Even though test almost fails on Linux VM (whereas it sometimes flakes and passes), it almost run with no failure on windows. Apparently it also runs on CI as well. …

CAMEL-12853 - disable SftpConsumerDisconnectTest

---

components/camel-mongodb3/src/main/docs/mongodb3-component.adoc

The documentation says one can return a `DBCursor` but doesn't show an example how to iterate over it in order to work with the actual data. I found this way of doing it based on [this gist](https://gist.github.com/padewitte/1e159475b0ae7a9b6b8e) and thought future readers might appreciate the concrete example.
If the correct way to iterate is different I'll gladly update the PR or close this one if a different PR solves my case.

mongodb3 - adds example of iterating over a DBCursor

---

components/camel-mongodb3/src/main/docs/mongodb3-component.adoc

As discussed in #2560 this removes `DBCursor` from the `mongodb3` documentation and tries to cleanly demonstrate how to return and process a `MongoIterable` correctly.

mongodb3 - update docs about streaming data, remove DBCursor

---

components/camel-kafka/src/main/docs/kafka-component.adoc

Included &securityProtocol=SSL for SSL configuration, as required by Kafka 1.0.  SSL configuration does not work unless this param is explicitly set

Included securityProtocol=SSL parameter

---

components/camel-atom/src/main/java/org/apache/camel/component/atom/AtomUtils.java

PR for https://issues.apache.org/jira/browse/CAMEL-12880. 
Setting a timeout value of 60 seconds to throw exception if connection not successful so that the scheduled poll consumer restart polling.
Thanks,
Saravanakumar

CAMEL-12880 : Atom consumer stops polling

---

components/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/RoutesCollector.java
components/camel-spring/src/main/java/org/apache/camel/spring/SpringCamelContext.java

CAMEL-12905: The trigger that starts the SpringCamelContext and that collect to routes to the camel context, needs to be a expected ContextRefreshedEvent that has been emitted by the ApplicationContext that instantiated the SpringCamelContext instance. 
https://issues.apache.org/jira/browse/CAMEL-12905

CAMEL-12905: Camel context inconsistencies in Spring Cloud Environment 

---

components/camel-schematron/src/main/java/org/apache/camel/component/schematron/SchematronProducer.java
components/camel-schematron/src/main/java/org/apache/camel/component/schematron/processor/SchematronProcessor.java
components/camel-schematron/src/test/java/org/apache/camel/component/schematron/SchematronProducerTest.java

We use the Schematron component in one of our projects - and I'd like to micro-optimize on this code.
Our XMLs came in the [Fast InfoSet](https://en.wikipedia.org/wiki/Fast_Infoset) format as a byte array, and it's more efficient to create a `javax.xml.transform.Source` object from the byte array and let the Schematron run on that than unmarshal the XML to String and let Schematron parse that String again.

Schematron component supports class `javax.xml.transform.Source`

---

components/camel-box/camel-box-component/src/main/docs/box-component.adoc

Shorthand Alias will remain nonfunctional until changes are made on backend mapping. 
The real working endpoint is downloadPreviousFileVersion (singular form), on backend downloadVersion is mapped with downloadPreviousFileVersions (plural form) which not exists.

Change download previous file version endpoint

---

examples/camel-example-aggregate/src/main/resources/features.xml
examples/camel-example-cafe/src/main/resources/features.xml
examples/camel-example-cxf-blueprint/README.md
examples/camel-example-loan-broker-cxf/src/main/resources/features.xml
examples/camel-example-loan-broker-jms/src/main/resources/features.xml
examples/camel-example-management/src/main/resources/features.xml
examples/camel-example-pojo-messaging/src/main/resources/features.xml
examples/camel-example-route-throttling/src/main/resources/features.xml
examples/camel-example-spring-jms/src/main/resources/features.xml
examples/camel-example-spring-xquery/src/main/resources/features.xml
examples/camel-example-spring/src/main/resources/features.xml

Most cases wrong groupId. Changed from org.apache.camel to org.apache.camel.example.

Updated documentation and feature files for examples

---

components/camel-azure/src/main/docs/azure-blob-component.adoc

The example in the docs only has a single slash after `azure-blob:` when there should be two.

Fixed typo in Azure blob storage URI example

---

components/camel-core-osgi/src/main/java/org/apache/camel/core/osgi/OsgiServiceRegistry.java

This showed comparable performance to using the service cache and thread in my previous PR.  The leak does not occur since the Queue has been replaced with a map of AtomicLongs to count usage.

CAMEL-12969 : Map based Service Usage counting to remove memory leak

---

components/camel-headersmap/pom.xml

Exclude log4j-core coming in from com.cedarsoftware:java-util, different version is specified in camel-headersmap

---

camel-core/src/main/java/org/apache/camel/reifier/ToDynamicReifier.java
camel-core/src/main/java/org/apache/camel/runtimecatalog/impl/Pair.java
camel-core/src/main/java/org/apache/camel/runtimecatalog/impl/URISupport.java
camel-core/src/main/java/org/apache/camel/runtimecatalog/impl/UnsafeUriCharactersEncoder.java
camel-core/src/main/java/org/apache/camel/support/DefaultComponent.java
camel-core/src/test/java/org/apache/camel/issues/EndpointWithRawUriParameterTest.java
camel-util/src/main/java/org/apache/camel/util/Pair.java
camel-util/src/main/java/org/apache/camel/util/URIScanner.java
camel-util/src/main/java/org/apache/camel/util/URISupport.java
camel-util/src/main/java/org/apache/camel/util/UnsafeUriCharactersEncoder.java
camel-util/src/test/java/org/apache/camel/util/URISupportTest.java

https://issues.apache.org/jira/browse/CAMEL-12982
Hi guys, please review it before merging it. I refactored the RAW handling part of the code a bit, so if we decide to support fancier syntax like `RAW[[[...]]]` and `RAWaaa...aaa` in the future, it should still serve such enhancements.

CAMEL-12982: Support RAW{} syntax in URISupport

---

components/camel-linkedin/camel-linkedin-component/src/main/docs/linkedin-component.adoc

This update adds information about using a LinkedIn access token to work around the username/password login procedure for LinkedIn, which returns a CAPTCHA. Dhiraj Bokde provided the information in response to 
https://issues.jboss.org/browse/ENTESB-8088. 
This doc update is required to resolve 
https://issues.jboss.org/browse/FUSEDOC-2912

FUSEDOC-2912 Add info about accessToken parameter.

---

components/camel-olingo4/camel-olingo4-component/src/main/java/org/apache/camel/component/olingo4/Olingo4Consumer.java

* ApiConsumerHelper does not recognise ClientEntitySets and thus defaults
to return a constant 1. This means that the scheduling polling is never
concluded to be idle and the backoffXXX consumer properties do not work.
* If the ClientEntitySet is empty then return 0 to allow for backoffXXX
properties to correctly handle the scheduling of the polling.

CAMEL-13077: Fix polling return for empty OData ClientEntitySets

---

buildingtools/camel-checkstyle.xml

By default property "separated" is false.
As I see (latests code style fix commits), import groups have to be separated.
Without that property I get errors like "Extra separation in import group..." when using IntelliJ IDEA Checkstyle plugin.
Looks like maven checkstyle plugin ignores that property.

Add checkstyle "separated" property

---

camel-core/src/main/java/org/apache/camel/builder/ExpressionBuilder.java
camel-core/src/test/java/org/apache/camel/language/simple/SimpleTest.java

Command **_property_** is deprecated since v2.15

CAMEL-13150: Add command "exchangeProperty" for dateExpression in ExpressionBuilder

---

components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/MongoDbEndpoint.java

CAMEL-13125 : Endpoint shutdown closes mongo connection, killing the connection for everyone.

Camel 2.23.x : CAMEL-13125

---

core/camel-util/src/main/java/org/apache/camel/util/URISupport.java
core/camel-util/src/test/java/org/apache/camel/util/URISupportTest.java

Created Ticket https://issues.apache.org/jira/browse/CAMEL-13191
For this issue I have created this minor patch. 
The pattern stops colon search after the first colon, so the sanitizeUri method will hide the complete password part.

CAMEL-13191: Fix Regex Pattern to hide passwords in URI 

---

camel-core/src/main/java/org/apache/camel/util/URISupport.java
camel-core/src/test/java/org/apache/camel/util/URISupportTest.java

CAMEL-13191: Fix Regex Pattern to hide passwords in URI

---

components/camel-salesforce/camel-salesforce-maven-plugin/src/main/java/org/apache/camel/maven/GenerateMojo.java
components/camel-salesforce/camel-salesforce-maven-plugin/src/test/java/org/apache/camel/maven/GenerateMojoTest.java

Picklist/Multipicklists can be now exclusively enforced to be of type String/enum.
This cleans up #2779 and it is based on #2785 to have fewer merge conflicts.
@przemeklenik can you please take a look and see if I missed anything, this should incorporate your changes and in addition some clean up work I wanted to do.

CAMEL-13186: camel-salesforce-maven-plugin additional customizations missing

---

core/camel-core/src/main/java/org/apache/camel/model/ProcessorDefinition.java

Fix typo at javadoc in ProcessorDefinition#onCompletion method javadoc.

Fix typo at javadoc in ProcessorDefinition#onCompletion

---

components/camel-linkedin/camel-linkedin-api/pom.xml
components/camel-linkedin/camel-linkedin-api/src/main/java/org/apache/camel/component/linkedin/api/LinkedInOAuthRequestFilter.java
components/camel-linkedin/camel-linkedin-api/src/test/java/org/apache/camel/component/linkedin/api/AbstractResourceIntegrationTest.java
components/camel-linkedin/camel-linkedin-component/pom.xml
components/camel-linkedin/camel-linkedin-component/src/main/java/org/apache/camel/component/linkedin/LinkedInComponent.java
components/camel-linkedin/camel-linkedin-component/src/main/java/org/apache/camel/component/linkedin/LinkedInEndpoint.java
platforms/karaf/features/src/main/resources/features.xml

Issue https://issues.apache.org/jira/browse/CAMEL-13293
Refactor of camel-linkedin component to replace HtmlUnit with Jsoup which allows to remove dependency to Jetty and therefor to allow use of servlet-api 4.0

[CAMEL-13293] Camel-linkedin, switch to JSoup to not rely on Jetty

---

components/camel-twitter/src/main/java/org/apache/camel/component/twitter/util/TwitterConverter.java

https://issues.apache.org/jira/browse/CAMEL-13319

CAMEL-13319 - TwitterConverter calls deprecated getSenderScreenName, throws UnsupportedOperationException

---

.gitignore
bom/camel-bom/pom.xml
components/camel-ipfs/pom.xml
components/camel-nagios/pom.xml
components/camel-paho/pom.xml
components/camel-restlet/pom.xml
examples/camel-example-restlet-jdbc/pom.xml
pom.xml

Uses `flatten-maven-plugin` to flatten the deployed the POMs. Any POM that includes a `<repository>` has additional configuration to keep it.
To test run `./mvnw -Pdeploy flatten:flatten` and compare `pom.xml`s with `.flattened-pom.xml`s or `./mvnw -Pdeploy install` and take a look in the `$HOME/.m2/repository`.

CAMEL-13331: Deploy flat Maven POMs

---

core/camel-core/src/main/docs/simple-language.adoc

Prevent rendering of `:key:` as `key` emoji. Slightly deviates from the style guide but better than rendering an image I believe.

Prevent rendering of `:key:` as `key` emoji

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaConsumerRebalancePartitionRevokeTest.java

In message processing loop introduced saved last offset processed in map and used the last processed offset from the map when partition revoke called by Kafka broker

CAMEL-13339 - Fix to use last processed offset maintained by Camel KafkaConsumer to avoid message loss upon partition revoke

---

components/camel-mllp/src/main/java/org/apache/camel/component/mllp/MllpConfiguration.java
components/camel-mllp/src/test/java/org/apache/camel/component/mllp/MllpEndpointTest.java

- Closes CAMEL-13355
- This change would allow maxConcurrentConsumers property set at component level to be used during endpoint instance creation.
- Refactored unit tests to remove code not in use and added unit tests related to this change.

CAMEL-13355: copy method updated to include maxConcurrentConsumers

---

components/camel-mllp/src/main/java/org/apache/camel/component/mllp/MllpEndpoint.java
components/camel-mllp/src/test/java/org/apache/camel/component/mllp/MllpMaxConcurrentConsumersTest.java

- Closes CAMEL-13366
- This change would allow to specify `maxConcurrentConsumers` property on the endpoint URI (docs already specify that)
- Unit tests to assert property behavior when specified on the endpoint URI.

CAMEL-13366: support maxConcurrentConsumers configuration on the endpoint URI

---

components/camel-spark-rest/src/main/java/org/apache/camel/component/sparkrest/CamelSpark.java
components/camel-spark-rest/src/main/java/org/apache/camel/component/sparkrest/SparkComponent.java
components/camel-spark-rest/src/main/java/org/apache/camel/component/sparkrest/SparkConsumer.java
components/camel-spark-rest/src/main/java/org/apache/camel/component/sparkrest/SparkEndpoint.java

This PR aims to solve [CAMEL-12323](https://issues.apache.org/jira/browse/CAMEL-12323) :
- An instance of Spark is created using Service.ignite() in the component.
- The classes SparkEndpoint and SparkConsumer use that instance instead of the Spark singleton.

CAMEL-12323 - camel-spark-rest - Avoid singleton spark instance

---

components/camel-docker/src/main/java/org/apache/camel/component/docker/consumer/DockerEventsConsumer.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/strategy/SftpChangedExclusiveReadLockStrategy.java
components/camel-mail/src/main/java/org/apache/camel/component/mail/NowSearchTerm.java

new Date() is just a thin wrapper around System.currentTimeMillis(). Using System.currentTimeMillis() can help avoid to create a new Date object and the system can speed up

CAMEL-13414 use System.currentTimeMillis()

---

apache-camel/src/main/descriptors/src.xml
apache-camel/src/main/descriptors/unix-bin.xml
apache-camel/src/main/descriptors/windows-bin.xml
pom.xml

This makes sure that Maven Flatten plugin is run in all profiles not just for `release` and changes the `properties` element processing to `keep` in contrast to the previous setting (`expand`) it should not replace property placeholders with expanded properties that might contain values specific to the machine the build is running.
Also makes sure that the distribution archives do not hold the `.flattened-pom.xml` file.

CAMEL-13386: Maven Flatten plugin refinements

---

components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowConsumer.java

https://issues.apache.org/jira/browse/CAMEL-13428
Explicit sender close is not needed as the `sender()` without callback automatically closes it for you:
http://undertow.io/undertow-docs/undertow-docs-1.4.0/#undertow-handler-authors-guide

CAMEL-13428: camel-undertow - Response with large data gets truncated on cloud

---

examples/camel-example-artemis/README.md
examples/camel-example-artemis/pom.xml
examples/camel-example-artemis/src/data/order1.xml
examples/camel-example-artemis/src/data/order2.xml
examples/camel-example-artemis/src/main/java/org/apache/camel/example/artemis/ArtemisMain.java
examples/camel-example-artemis/src/main/java/org/apache/camel/example/artemis/CreateOrderRoute.java
examples/camel-example-artemis/src/main/java/org/apache/camel/example/artemis/WidgetGadgetRoute.java
examples/camel-example-artemis/src/main/resources/META-INF/LICENSE.txt
examples/camel-example-artemis/src/main/resources/META-INF/NOTICE.txt
examples/camel-example-artemis/src/main/resources/log4j2.properties
examples/pom.xml

Introduces a widget-gadget example that uses Apache ActiveMQ Artemis
message broker, instead of the classic ActiveMQ, and uses the the Artemis Core
protocol for the data exchange with JMS.

CAMEL-9589: adds an example using Apache ActiveMQ Artemis Broker

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConfiguration.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaComponentTest.java

When creating consumer or producer properties, fix KafkaConfiguration to put truststore password into
the correct property field.

fix: Correctly set up truststore password property in KafkaConfiguration

---

components/camel-cdi/pom.xml
components/camel-cdi/src/test/java/org/apache/camel/cdi/rule/ExpectedDeploymentException.java
components/camel-cdi/src/test/java/org/apache/camel/cdi/test/UriWithWrongContextTest.java

Test were failed because they run with different maven profiles: weld-1.0, weld-1.2, weld-2.0.
Different versions of WELD have different exception messages.
Failing tests:
1. UriWithWrongContextTest - removed unnesesary checks, checking only error code and injection point
1. UnsatisfiedContextForEndpointInjectTest - fixed by adding cause exception message at ExpectedDeploymentException

CAMEL-12834: Fix failing CDI tests

---

examples/camel-example-cdi-cassandraql/README.md

Working on CAMEL-13234 I had to run `camel-example-cdi-cassandraql` example, so run into problem with memory limits.
Added information about limiting memory to Cassandra docker container.

Improve camel-example-cdi-cassandraql readme

---

components/camel-netty4-http/pom.xml
components/camel-netty4-http/src/main/docs/netty4-http-component.adoc
components/camel-netty4-http/src/main/java/org/apache/camel/component/netty4/http/DefaultNettyHttpBinding.java
components/camel-netty4-http/src/main/java/org/apache/camel/component/netty4/http/NettyHttpComponent.java
components/camel-netty4-http/src/main/java/org/apache/camel/component/netty4/http/NettyHttpConfiguration.java
components/camel-netty4-http/src/main/java/org/apache/camel/component/netty4/http/handlers/HttpServerChannelHandler.java
components/camel-netty4-http/src/main/java/org/apache/camel/component/netty4/http/handlers/HttpServerMultiplexChannelHandler.java
components/camel-netty4-http/src/test/java/org/apache/camel/component/netty4/http/ProxyProtocolTest.java
core/camel-api/src/main/java/org/apache/camel/Exchange.java
platforms/spring-boot/components-starter/camel-netty4-http-starter/src/main/java/org/apache/camel/component/netty4/http/springboot/NettyHttpComponentConfiguration.java

This adds support for reverse proxy functionality in `camel-netty4-http` component.
While testing this I can see that the latency on the 99 percentile is ~50msec on my machine, would love to know if that can be optimized even further. Transfer rate is definitely something that could be looked at.
In my tests I used a route like:
```java
from("netty-http:proxy://0.0.0.0:8080")
.toD("netty-http:"
+ "${headers." + Exchange.HTTP_SCHEME + "}://"
+ "${headers." + Exchange.HTTP_HOST + "}:"
+ "${headers." + Exchange.HTTP_PORT + "}")
```
I did notice some string/lambda allocations in the Pipeline that we might want to take a look at also.
After some warmup here's a test I run with 1000 requests with concurrency of 100:
```shell
$ ab -c 100 -n 1000 -k -X localhost:8080 http://localhost:8000/hello …
```

CAMEL-13521: Add reverse proxy option in camel-netty4-http

---

components/camel-test-cdi/pom.xml
examples/camel-example-cdi-aws-s3/pom.xml
examples/camel-example-cdi-cassandraql/pom.xml
examples/camel-example-cdi-kubernetes/pom.xml
examples/camel-example-cdi-metrics/pom.xml
examples/camel-example-cdi-properties/pom.xml
examples/camel-example-cdi-rest-servlet/pom.xml
examples/camel-example-cdi-test/pom.xml
examples/camel-example-cdi-xml/pom.xml
examples/camel-example-cdi/pom.xml
examples/camel-example-fhir/pom.xml
examples/camel-example-opentracing/client/pom.xml
examples/camel-example-swagger-cdi/pom.xml
examples/camel-example-transformer-cdi/pom.xml
examples/camel-example-widget-gadget-cdi/pom.xml
examples/camel-example-zipkin/client/pom.xml

1. Double checked all modified examples to work with weld3.
1. There are more things that use weld2: camel-archetype-cdi, etc.

CAMEL-13234: Use weld3 instead of weld2 at CDI example projects

---

components/camel-netty4-http/src/main/java/org/apache/camel/component/netty4/http/DefaultNettyHttpBinding.java
components/camel-netty4-http/src/main/java/org/apache/camel/component/netty4/http/NettyHttpConstants.java
components/camel-netty4-http/src/main/java/org/apache/camel/component/netty4/http/handlers/HttpServerChannelHandler.java

`DefaultNettyHttpBinding::toNettyRequest` could allocate a new Netty `ByteBuf` (e.g. via `NettyConverter::toByteBuffer`) which in turn might or might not be passed to the `FullHttpRequest` depending on the resulting buffer size: if it's 0 it will not be set as content of the request. In that case this causes a memory leak.
The buffer having the size of 0 is quite common for `GET` or `OPTIONS` HTTP method requests, so releasing the buffer if the incoming request is received when acting as a proxy will cause the any downstream Netty requests (say in a scenario `from("netty-http:proxy:...").toD("netty-http:...")`) to block.
So additional optimization was added to store the proxy HTTP request in the `Exchange` property and to check if the current request in the `NettyHttpMessage` has the same …

CAMEL-13545: fix netty4-http memory issues

---

components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpConsumer.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/SftpConsumer.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/FromFtpRecursiveNotStepwiseNoBasePath.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/FromSftpRecursiveNotStepwiseNoBasePath.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/SftpServerTestSupport.java

-Check empty base path before adding '/' (FtpConsumer) .
-Add a new test.

CAMEL-13400 Camel FTP Cannot list directory with 'File not found' prepending additional '/' in front of directory automatically

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/SpringBootAutoConfigurationMojo.java

bypass if type starts with java.util.

CAMEL-13546 - as < and > is invalid in windows

---

components/camel-sql/src/main/docs/sql-component.adoc

This pull request adds an instruction to Camel's SQL component documentation.
Implementing the Idempotent Consumer pattern with the JDBC based idempotent repository from Camel's SQL component requires a unique constraint on the database when there are concurrent consumers. Otherwise it is possible to consume duplicate messages.

Add instruction to create unique constraint for JDBC idempotent repository

---

camel-core/src/main/java/org/apache/camel/MessageHistory.java
camel-core/src/main/java/org/apache/camel/impl/DefaultInflightRepository.java

CAMEL-13587: Inflight repository browse should compute elapsed if themessage is still inflight at a given node. Thanks to Barbara De Vido for reporting.
Backporting from master

Camel 2.x - CAMEL-13587 backporting from master

---

components/camel-mongodb3/src/main/java/org/apache/camel/component/mongodb3/converters/MongoDbBasicConverters.java
components/camel-mongodb3/src/test/java/org/apache/camel/component/mongodb3/MongoDbConversionsTest.java

InputStream with spaces at the begining cause infinite loop.

Fix MongoDB InputStream conversion bug

---

components/camel-couchbase/src/main/docs/couchbase-component.adoc

I struggled a bit with the couchbase component, where it constantly complained about authentication failure. Once I discovered that the camel component is utilizing an older version of the couchbase sdk (1.4.13), I thought I won't be able to use the component until it is upgraded to version 2.4+. But with the notes on using the legacy SDK, I managed to utilize this couchbase component with my current version of couchbase.

Added compatibility notes for server 5 and beyond

---

components/camel-file/src/main/docs/file-component.adoc
components/camel-grok/src/main/docs/grok-dataformat.adoc
core/camel-base/src/main/docs/constant-language.adoc
docs/components/modules/ROOT/pages/file-component.adoc
docs/components/modules/ROOT/pages/grok-dataformat.adoc
docs/user-manual/modules/ROOT/pages/constant-language.adoc
tests/camel-itest-karaf/README.adoc
tests/camel-itest-osgi/README.adoc

- camel-file ant matcher does not need camel-spring, as it is part of camel-util
- constant-language: Added missing section about resource prefix - http://camel.465427.n5.nabble.com/Possible-bug-in-netty-http-characters-in-body-get-unescaped-td5835669.html
- itest-karaf, itest-osgi fixed command name
- camel-grok typo

Improved docs: file, constant-language, itest-karaf, itest-osgi

---

components/camel-opentracing/pom.xml
components/camel-opentracing/src/main/docs/opentracing.adoc
examples/README.adoc
examples/camel-example-opentracing/README.md
examples/camel-example-opentracing/service2/pom.xml
examples/camel-example-opentracing/service2/src/main/java/sample/camel/Service2Application.java
examples/camel-example-opentracing/service2/src/main/java/sample/camel/Service2Route.java
parent/pom.xml

This PR also removes use of the opentracing-contrib/opentracing-agent, which is no longer in active development, from the opentracing component tests and the examples.
There is another java agent project in development, that could be used in the future to provide the same capability - but probably better that camel is not tightly coupled with it (even for tests and examples). Use of this agent could be described in a blog post or somewhere.

Upgrade to OpenTracing java API 0.33

---

components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQEndpoint.java

change thread name of rabbitmq routes from "RabbitMQConsumer" to  its endpoint uri

CAMEL-13685 : camel-rabbitmq Thread name for route set to endpoint uri

---

components/camel-jdbc/src/main/java/org/apache/camel/component/jdbc/ResultSetIterator.java
components/camel-jdbc/src/test/java/org/apache/camel/component/jdbc/JdbcColumnTypeTest.java
components/camel-jdbc/src/test/resources/sql/init.sql

Problem:
> Caused by: java.sql.SQLException: Tipo de coluna inválido: getString/getNString not implemented for class oracle.jdbc.driver.T4CBlobAccessor
>         at oracle.jdbc.driver.Accessor.unimpl(Accessor.java:296)
>         at oracle.jdbc.driver.BlobAccessor.getString(BlobAccessor.java:238)
>         at oracle.jdbc.driver.GeneratedStatement.getString(GeneratedStatement.java:287)
>         at oracle.jdbc.driver.GeneratedScrollableResultSet.getString(GeneratedScrollableResultSet.java:374)
>         at com.zaxxer.hikari.pool.HikariProxyResultSet.getString(HikariProxyResultSet.java)
>         at org.apache.camel.component.jdbc.ResultSetIterator$BlobColumn.getValue(ResultSetIterator.java:210)
>         at org.apache.camel.component.jdbc.ResultSetIterator.next(ResultSetIterator.java:86) …

using the correct result set method to get value from blob-type column

---

components/camel-websocket-jsr356/src/main/java/org/apache/camel/websocket/jsr356/JSR356Endpoint.java

Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>

CAMEL-13717 - fixed wrong syntax for websocket-jsr356 endpoints

---

camel-core/src/main/java/org/apache/camel/component/bean/MethodInfo.java
camel-core/src/main/java/org/apache/camel/util/ObjectHelper.java
camel-core/src/test/java/org/apache/camel/util/ObjectHelperTest.java

This happens only for a call with no args that raise an IllegalAccessException,
for example using an inner private class in a CamelTest.
In Camel 3 we have the same bug, but it is mitigated by a call to
org.apache.camel.support.ObjectHelper.invokeMethodSafe
which I also included in this fix.

Fix NPE at component.bean.MethodInfo.invoke

---

camel-core/src/main/java/org/apache/camel/util/IOHelper.java
components/camel-undertow/src/main/docs/undertow-component.adoc
components/camel-undertow/src/main/java/org/apache/camel/component/undertow/DefaultUndertowHttpBinding.java
components/camel-undertow/src/main/java/org/apache/camel/component/undertow/RestUndertowHttpBinding.java
components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowClientCallback.java
components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowComponent.java
components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowConsumer.java
components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowEndpoint.java
components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowProducer.java
components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowStreamingClientCallback.java

https://issues.apache.org/jira/browse/CAMEL-13734
Should we not backport this to 2.x?  If not, please just ignore and close it unmerged. Thanks.

CAMEL-13734: camel-undertow - Support streaming of large data for HTTP endpoints (2.x)

---

components/camel-mongodb3/src/main/java/org/apache/camel/component/mongodb3/MongoDbTailingThread.java
components/camel-mongodb3/src/test/java/org/apache/camel/component/mongodb3/MongoDbTailableCursorConsumerTest.java

Fixed the autoclosable cursor issue discovered and enabled Junit test related that should now work as expected. From now on, the consumer should be able correctly to resume any tracking stored previously. Also, any stopped consumer will be catched trying to provide a graceful shutdown of the consumer thread.

CAMEL-13776 - fixing autoclosable cursor issue

---

examples/camel-example-zipkin/README.md

The group ID has changed (from `io.zipkin.java` to `io.zipkin`) in recent versions, so the previous download link would not download the latest version.
See https://github.com/openzipkin/openzipkin.github.io/issues/136

Update the Zipkin Server jar coordinates

---

components/camel-ahc/src/main/java/org/apache/camel/component/ahc/DefaultAhcBinding.java
components/camel-ahc/src/test/java/org/apache/camel/component/ahc/AhcProducerSessionTest.java

Fix and enable previously skipped tests (PR #2971)

CAMEL-13563: Fix AHC tests after Jetty upgrade

---

components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/CompositeApiBatchIntegrationTest.java

Assertion was looking for "15000". My org happened to return "50000". These limits change over time, and salesforce customers can buy limits increases, so we really never know what number to expect, other than it's non-zero.

Camel-Salesforce: Fix integration test.

---

archetypes/camel-archetype-component/src/main/resources/archetype-resources/src/main/java/EventBusHelper.java
archetypes/camel-archetype-component/src/main/resources/archetype-resources/src/main/java/__name__Consumer.java
archetypes/camel-archetype-component/src/main/resources/archetype-resources/src/main/java/__name__Endpoint.java
archetypes/camel-archetype-component/src/main/resources/archetype-resources/src/test/java/__name__ComponentTest.java

Per the title, this will fix the generated `camel-archetype-component` project to inherit from `DefaultConsumer` instead of `ScheduledPollConsumer`

CAMEL-13783: Fix the camel-archetype-component to inherit from DefaultConsumer instead of ScheduledPollConsumer

---

components/camel-salesforce/camel-salesforce-component/pom.xml
components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/LoginConfigHelper.java

Integration tests ignore the salesforce endpoint setting, so if your endpoint is not https://login.salesforce.com, the tests fail to connect to salesforce.

Camel-Salesforce: Fix - Integration tests ignore salesforce.login.url.

---

components/camel-pulsar/src/main/docs/pulsar-component.adoc
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/DefaultPulsarMessageReceipt.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/DefaultPulsarMessageReceiptFactory.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarComponent.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarEndpoint.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarMessageListener.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarMessageReceipt.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarMessageReceiptFactory.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/configuration/PulsarConfiguration.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/utils/consumers/CommonCreationStrategyImpl.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarComponentTest.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarConsumerAcknowledgementTest.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarConsumerNoAcknowledgementTest.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarCustomMessageReceiptTest.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarNegativeAcknowledgementTest.java
core/camel-endpointdsl/src/main/java/org/apache/camel/builder/endpoint/dsl/PulsarEndpointBuilderFactory.java
platforms/spring-boot/components-starter/camel-pulsar-starter/src/main/java/org/apache/camel/component/pulsar/springboot/PulsarComponentConfiguration.java

Addresses [CAMEL-13841](https://issues.apache.org/jira/browse/CAMEL-13841)
Pulsar messages are currently acknowledged immediately upon consumption. This could lead to lost messages if the application crashes or does not finish its unit of work. In such situations, it may be desirable to leave these messages unacknowledged so that they can be redelivered to another consumer.
Changed the `PulsarMessageListener`'s received method to not acknowledge the message if `allowManualAcknowledgement` is true. Instead, we add an instance of `PulsarMessageReceipt` as a header on the `Exchange` so that the user can manually acknowledge the message at the appropriate time.
Added `allowManualAcknowledgement`, `ackTimeoutMillis`, and `ackGroupTimeMillis` as URI parameters. The latter two are Pulsar …

CAMEL-13841: Allow manual Pulsar message acknowledgments

---

components/camel-olingo2/camel-olingo2-component/src/main/java/org/apache/camel/component/olingo2/Olingo2Consumer.java
components/camel-olingo2/camel-olingo2-component/src/test/java/org/apache/camel/component/olingo2/Olingo2ComponentConsumerTest.java
components/camel-olingo4/camel-olingo4-component/src/main/java/org/apache/camel/component/olingo4/Olingo4Consumer.java
components/camel-olingo4/camel-olingo4-component/src/test/java/org/apache/camel/component/olingo4/Olingo4ComponentConsumerTest.java

* Olingo[*]Consumer
* Tests for null results as well as empty collections. Return 0 accordingly
* Adds and updates tests to assume no empty messages unless the
consumer.sendEmptyMessageWhenIdle property has been configured

CAMEL-13861: Fixes missing logic producing empty messages

---

components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/AbstractSalesforceTestBase.java

fix typo in salesforce component test

---

components/camel-aws-ddb/src/main/java/org/apache/camel/component/aws/ddb/DdbComponentVerifierExtension.java
components/camel-aws-ddb/src/test/java/org/apache/camel/component/aws/ddb/integration/DdbComponentIntegrationTest.java

Extended the (ignored by default) integration test on DynamoDB to do a minimal lifecycle: create, update, get and delete an item.
Still needs proper credentials, region, table name and key column to run. Also, fix the problem with non raw passwords (if the password contained something like "/", the test was broken).

[DynamoDB] Improve Integration Tests

---

components/camel-rest/src/main/java/org/apache/camel/component/rest/RestProducer.java
core/camel-core/src/main/java/org/apache/camel/model/rest/RestDefinition.java
core/camel-core/src/test/java/org/apache/camel/component/rest/FromRestGetPlaceholderParamTest.java
core/camel-core/src/test/java/org/apache/camel/component/rest/RestProducerPathTest.java
docs/user-manual/modules/ROOT/pages/rest-dsl.adoc

Improved REST DSL route definition and REST Producer.
I have doubts about:
1. Using regex to iterate over placeholders "{}".
1. New function `resolveHeaderPlaceholders` at `camel-rest` that replaces placeholders with header values. Maybe there is a way to reuse some code from camel-properties component.
Also unit-tests for `camel-rest` component are located at `camel-core`. Maybe it would be better to move them?

CAMEL-13429: Support expressions in path parameters at REST DSL

---

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/StringMultiSelectPicklistDeserializer.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/StringMultiSelectPicklistSerializer.java
components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/api/MultiSelectPicklistJsonTest.java
components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/dto/generated/StringMSPTest.java
components/camel-salesforce/camel-salesforce-maven-plugin/README.md

Serialization/deserialization failed when using Strings instead of
enumerations for multiselect pick lists. You can reproduce by running the new test cases without the changes to the Serializer/Deserializer classes.
The error you'd see is: 
```com.fasterxml.jackson.databind.JsonMappingException: 
Class org.apache.camel.component.salesforce.api.StringMultiSelectPicklistDeserializer has no default (no arg) constructor
at [Source: (String)"{"attributes":{"type":"MSPTest"},"MspField":"Value1;Value2;Value3"}"; line: 1, column: 1]
at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:306)
```
I added default constructors for the affected classes and it seems to fix things.

Camel-Salesforce: Fix serialization for string MPLs

---

components/camel-file/src/main/java/org/apache/camel/component/file/cluster/FileLockClusterView.java
core/camel-api/src/main/java/org/apache/camel/Service.java
core/camel-core/src/test/java/org/apache/camel/AutoCloseableTest.java

Based on previous discussion[1][2] I would like to suggest that we take the opportunity to make Services AutoCloseable in 3.x.
[1] https://mail-archives.apache.org/mod_mbox/camel-dev/201703.mbox/%3CCABD_Zr-V6QVXAMr3xYi0ZfKpSx9YpsZb9iEW4FpCjR6L6SQO7w%40mail.gmail.com%3E  (follow the thread)
[2] https://github.com/apache/camel/pull/1537

CAMEL-11011: Make all Services AutoCloseable

---

core/camel-core-osgi/pom.xml
core/camel-core-xml/pom.xml
core/camel-endpointdsl/pom.xml
core/camel-management-impl/pom.xml

Revert "CAMEL-13938: core artifacts should not depend con camel-core but camel-core-engine"

---

docs/user-manual/modules/ROOT/pages/karaf.adoc

`features:install` corrected to `feature:install`. 
Please review and accept the change.
Regards,
Sunil Chandra

features:install corrected to feature:install

---

docs/user-manual/modules/ROOT/pages/camel-maven-archetypes.adoc

Formatting on this page was a bit stuffed. I tried to make it consistent with formatting in the component docs.
Btw `[line-through]` is [deprecated](https://asciidoctor.org/docs/user-manual/#migrate-deprecated) (and not rendering anyway). Is there a global role I should be applying instead?

Fix inconsistent doc formatting and wording in Maven Archetype page

---

components/camel-snmp/src/main/java/org/apache/camel/component/snmp/SnmpEndpoint.java
components/camel-snmp/src/main/java/org/apache/camel/component/snmp/SnmpProducer.java
components/camel-snmp/src/test/java/org/apache/camel/component/snmp/WalkOIDTest.java

camel-snmp: add support to snmp walk, use snmp4j GET_NEXT

camel-snmp: add support to snmp walk, use snmp4j GET_NEXT

---

components/camel-facebook/src/main/docs/facebook-component.adoc

Simply updated the Facebook 4J link in the [facebook-component documentation](https://github.com/apache/camel/blob/master/components/camel-facebook/src/main/docs/facebook-component.adoc).

newLinkAdded-FacebookComponentDocs

---

docs/user-manual/modules/ROOT/pages/camel-3-migration-guide.adoc

Convert migration guide do AsciiDoc and move it to docs/user-manual/modules/ROOT/pages/camel-3-migration-guide.adoc

CAMEL-13916: website - Add migration guide page

---

components/camel-file-watch/src/main/java/org/apache/camel/component/file/watch/FileWatchComponent.java
components/camel-file-watch/src/test/java/org/apache/camel/component/file/watch/FileWatchComponentTest.java
components/camel-file-watch/src/test/java/org/apache/camel/component/file/watch/FileWatchComponentTestBase.java
components/camel-file-watch/src/test/java/org/apache/camel/component/file/watch/SpringFileWatcherTest.java

**Scope of changes**
- Due to [CAMEL-13954](https://issues.apache.org/jira/browse/CAMEL-13954), the auto generated property configurator will use the wrong method which is expected due to the param type. However, instead of that, we just set events manually using the correct method.
- Change junit testing directory from the default to the `target` folder. 
- Make sure to delete spring testing files after the tests.
- Add and modify some testing cases

CAMEL-13954: Set file-watch events explicitly instead of relying on relying on the the auto generated property configurator

---

components/camel-activemq/pom.xml
components/camel-ahc/pom.xml
components/camel-atomix/pom.xml
components/camel-aws-xray/pom.xml
components/camel-cdi/pom.xml
components/camel-ehcache/pom.xml
components/camel-hipchat/pom.xml
components/camel-jcache/pom.xml
components/camel-metrics/pom.xml
components/camel-micrometer/pom.xml
components/camel-pdf/pom.xml
components/camel-tika/pom.xml
components/camel-wordpress/pom.xml
core/camel-cloud/pom.xml
core/camel-core/pom.xml
core/camel-endpointdsl/pom.xml
core/camel-management-impl/pom.xml
core/camel-util/pom.xml
examples/camel-example-cdi-metrics/pom.xml
examples/camel-example-cdi-properties/pom.xml
examples/camel-example-cdi-rest-servlet/pom.xml
examples/camel-example-cdi-test/pom.xml
examples/camel-example-cdi-xml/pom.xml
parent/pom.xml
platforms/spring-boot/spring-boot-dm/camel-spring-boot-dependencies/pom.xml
tooling/maven/camel-eip-documentation-enricher-maven-plugin/pom.xml

>Hamcrest is now a single jar: hamcrest-2.1.jar
See: https://github.com/hamcrest/JavaHamcrest/releases/tag/v2.1

Upgrade Hamcrest to version 2.1

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/model/ComponentOptionModel.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/model/EipOptionModel.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/model/EndpointOptionModel.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/model/OtherOptionModel.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/model/SpringBootAutoConfigureOptionModel.java
tooling/maven/camel-package-maven-plugin/src/main/resources/component-options.mvel
tooling/maven/camel-package-maven-plugin/src/main/resources/eip-options.mvel
tooling/maven/camel-package-maven-plugin/src/main/resources/endpoint-options.mvel
tooling/maven/camel-package-maven-plugin/src/main/resources/spring-boot-auto-configure-options.mvel

This will remove watermarks from the model files as we don't need them anymore and deprecated it the old functions.

CAMEL-13980: Deprecate watermarks in model files and change return unchanged javaType

---

components/camel-sql/src/main/docs/sql-component.adoc

Clarified the `update` operation and formatted some sloppy tables.

DOCS-clarified-update-asHeaderOperation-formatted-tables

---

components/camel-aws-s3/src/main/docs/aws-s3-component.adoc

This fixes the first example URI in the AWS S3 component documentation, adding two forward-slashes, as is specified in the format for the URI a few lines above. Leaving out the slashes may potentially cause difficult to diagnose Access Denied errors when trying to access the bucket.

Fix examples in aws-s3 component documentation

---

components/camel-metrics/src/main/docs/metrics-component.adoc

In https://github.com/apache/camel/commit/4a84f061f74f759e77d45c369a95b704f38c1a92#diff-7dccb1916e4f48ce43acf6ebc21fbbb9 `TimerAction` was replaced by `MetricsTimerAction`.

Docs update - TimerAction should be MetricsTimerAction

---

components/camel-zipkin/src/main/docs/zipkin.adoc
components/camel-zipkin/src/main/java/org/apache/camel/zipkin/ZipkinClientRequestAdapter.java
parent/pom.xml
platforms/karaf/features/src/main/resources/features.xml

Provide clients with capability to send custom tags to Zipkin server.
Client needs to add a map of tags to exchange property camel.custom.tags and camel-zipkin will automatically add these tags to Zipkin span.

Allow clients to send custom tags to Zipkin server

---

components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/DefaultNettyHttpBinding.java
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/HttpClientInitializerFactory.java
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/HttpServerInitializerFactory.java
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/HttpServerSharedInitializerFactory.java
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/InboundStreamHttpRequest.java
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/InboundStreamHttpResponse.java
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/NettyHttpBinding.java
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/NettyHttpEndpoint.java
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/OutboundStreamHttpRequest.java
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/OutboundStreamHttpResponse.java
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/RestNettyHttpBinding.java
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/handlers/HttpClientChannelHandler.java
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/handlers/HttpInboundStreamHandler.java
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/handlers/HttpOutboundStreamHandler.java
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/handlers/HttpServerChannelHandler.java
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/handlers/HttpServerMultiplexChannelHandler.java
components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpStreamTest.java

- Add the HttpInboundStreamHandler
- Refactor the CustomWriterHandler to HttpOutboundStreamHandler
- fix an issue in the writer handler to create a new promise after writing the request/response headers
- create the NettyHttpStreamTest
https://issues.apache.org/jira/browse/CAMEL-14017

CAMEL-14017 - Update to support the full streaming on both inbound and outbound

---

components/camel-protobuf/src/main/docs/protobuf-dataformat.adoc
components/camel-protobuf/src/main/java/org/apache/camel/dataformat/protobuf/ProtobufConverter.java
components/camel-protobuf/src/main/java/org/apache/camel/dataformat/protobuf/ProtobufDataFormat.java
components/camel-protobuf/src/test/java/org/apache/camel/dataformat/protobuf/ProtobufConverterTest.java
components/camel-protobuf/src/test/java/org/apache/camel/dataformat/protobuf/ProtobufMarshalAndUnmarshalMapTest.java
components/camel-protobuf/src/test/proto/addressbook.proto

This PR intends to add the support data of Map using data converters. It will convert Map to Proto Message using message descriptors. 
**Note**: This PR **is not** breaking change as intends not to break any existing integration.

CAMEL-13988: Add Map data input support to Protobuf dataformat

---

components/camel-bindy/src/main/docs/bindy-dataformat.adoc

I have provided the documentation with a short description of the `columnName` annotation.
I hope it is accurate enough!
M

Missing `columnName` description

---

components/camel-undertow/src/main/docs/undertow-component.adoc
components/camel-undertow/src/main/java/org/apache/camel/component/undertow/DefaultUndertowHttpBinding.java
components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowConsumer.java
components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowEndpoint.java
components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowHttpBinding.java
components/camel-undertow/src/test/java/org/apache/camel/component/undertow/UndertowMuteExceptionTest.java
core/camel-endpointdsl/src/main/java/org/apache/camel/builder/endpoint/dsl/UndertowEndpointBuilderFactory.java

This pull request adds the "muteException" option to the Camel Undertow component.
If enabled and an Exchange fails processing on the consumer side the response's body won't contain the exception's stack trace. Instead it will simply return the body "Exception".
I hope that this implements the idea described in https://issues.apache.org/jira/browse/CAMEL-14023.

CAMEL-14025: add muteException option on camel-undertow component

---

components/camel-pulsar/src/main/docs/pulsar-component.adoc
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarProducer.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/configuration/PulsarConfiguration.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarComponentTest.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarProducerUndefinedProducerNameInTest.java
core/camel-endpointdsl/src/main/java/org/apache/camel/builder/endpoint/dsl/PulsarEndpointBuilderFactory.java

Addresses [CAMEL-14047](https://issues.apache.org/jira/browse/CAMEL-14047)
Current default producerName value causes a `null` `producerName` to be impossible when configuring from URI. This causes the code [regarding a null producerName in the PulsarProducer](https://github.com/apache/camel/blob/10de4bab2e76046b9535128bf38bf67b80c3f3f4/components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarProducer.java#L60-L62) to be impossible to get to from a URI. This forces anyone wanting to start 2 producers on the same topic in Camel to generate unique IDs and append them to each `producerName` value.
The fix proposed in this PR is defaulting `producerName` to null and, instead of generating a `producerName` on a null within Camel, to use Pulsar `ProducerBuilder`'s automatic …

CAMEL-14047: Allow unset producerName to get unique name from Pulsar

---

components/camel-pulsar/src/main/docs/pulsar-component.adoc
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarProducer.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/configuration/PulsarConfiguration.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarComponentTest.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarProducerUndefinedProducerNameInTest.java

Porting https://github.com/apache/camel/pull/3237 to `camel-2.x` by request.

CAMEL-14047: 2.x port - Allow unset producerName to get unique name from Pulsar

---

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/SalesforceComponent.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/utils/SecurityUtils.java
components/camel-salesforce/camel-salesforce-maven-plugin/src/main/java/org/apache/camel/maven/AbstractSalesforceMojo.java

Issue: https://issues.apache.org/jira/browse/CAMEL-14023
Jetty client (for security reasons) disables all ciphers, which starts with "SSL_".
In IBM java it removes all ciphers, because every cipher starts with SSL, even ciphers for TLS 1.2
(see issue reported on jetty https://github.com/eclipse/jetty.project/issues/2921).
This fix changes excluded ciphers, for IBM jdk only, to contain also SSL_* ones.

[CAMEL-14023] Camel-salesforce-maven-plugin generate fails on IBM jdk

---

components/camel-http-common/src/main/java/org/apache/camel/http/common/DefaultHttpBinding.java
components/camel-http-common/src/main/java/org/apache/camel/http/common/HttpBinding.java
components/camel-http-common/src/main/java/org/apache/camel/http/common/HttpCommonEndpoint.java
components/camel-servlet/src/main/docs/servlet-component.adoc
components/camel-servlet/src/main/java/org/apache/camel/component/servlet/ServletComponent.java
components/camel-servlet/src/main/java/org/apache/camel/component/servlet/ServletEndpoint.java
components/camel-servlet/src/test/java/org/apache/camel/component/servlet/ServletMuteExceptionTest.java

This pull request implements the "muteException" option for the camel-servlet component (see [CAMEL-14025](https://issues.apache.org/jira/browse/CAMEL-14025).
If enabled the response body will simply contain the text "Exception" instead of a full stack trace (in case an exception is thrown).

CAMEL-14025: add muteException option to camel-servlet component

---

components/camel-jetty/src/main/java/org/apache/camel/component/jetty9/JettyHttpEndpoint9.java
components/camel-jetty/src/test/java/org/apache/camel/component/jetty/JettyMuteExceptionTest.java

This pull request implements the "muteException" option for the jetty component (see [CAMEL-14025](https://issues.apache.org/jira/browse/CAMEL-14025)).
If enabled the response body will simply contain the text "Exception" instead of a full stack trace (in case an exception is thrown). 
Since the jetty component seems to inherit from camel-http-common (just like camel-servlet) most of the work has already been implemented in #3251.

CAMEL-14025: add muteException option to camel-jetty component

---

components/camel-as2/camel-as2-component/src/main/java/org/apache/camel/component/as2/AS2Producer.java
components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2ClientManagerIntegrationTest.java
components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2ServerManagerIntegrationTest.java

Issue: https://issues.apache.org/jira/browse/CAMEL-14071
- One class was missing in if condition of AS2Producer in interception method (https://github.com/apache/camel/commit/30192d63f0290639e815df21ae37c9bc85f184d4#diff-090142443d23c06921786a5181ad7517R44), which become evident during fixation of tests. I've added MultipartSignedEntity into if condition (this entity contains signature entity). Without this change all responses containing MultipartSignedEntity won't be added into body of exchange.
- Added closing connection into @AfterClass method of AS2ClientManagerIntegrationTest.
- There were changes in AS2Producer (https://github.com/apache/camel/commit/30192d63f0290639e815df21ae37c9bc85f184d4#diff-090142443d23c06921786a5181ad7517R40-R48) and AS2Consmer …

[CAMEL-14071] [Camel-as2] Integration tests are not working

---

core/camel-core-engine/src/main/docs/eips/pollEnrich-eip.adoc

Added one XML DSL example for pollEnrich in the middle of a GET REST endpoint connecting to an S3 endpoint to download a file.

added documentation example for pollEnrich as consumer for S3 in REST API

---

parent/pom.xml

https://issues.apache.org/jira/browse/CAMEL-14094

CAMEL-14094 Bump jira-rest-java-client dependency for camel-jira component to 5.1.6

---

components/camel-file/src/main/java/org/apache/camel/component/file/FileOperations.java
core/camel-core/src/test/java/org/apache/camel/component/file/FileProducerFileExistAppendTest.java

When file producer applies file based optimization it ignores
fileExist=Append mode and always replaces target file.
This change avoids file based optimization when fileExist=Append.

CAMEL-14127: avoid file by file target replacement when fileExist=Append

---

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/dto/composite/SObjectCompositeResult.java

The `@JsonProperty("headers")` was the problem. Should be `@JsonProperty("httpHeaders")`. Oddly, it still worked, probably due to a Jackson matching algorithm. Other than that, cleaned up formatting a little.
Here's an example of what it's unmarshalling from:
```
{
"compositeResponse": [
{
"body": {
"id": "0037A00000OF7cZQAT",
"success": true,
"errors": []
},
"httpHeaders": {
"Location": "/services/data/v38.0/sobjects/Contact/0037A00000OF7cZQAT"
},
"httpStatusCode": 201,
"referenceId": "P1"
}
]
}
```

Camel-Salesforce: Fixed incorrect JsonProperty name.

---

components/camel-exec/src/main/docs/exec-component.adoc
components/camel-exec/src/main/java/org/apache/camel/component/exec/ExecBinding.java
components/camel-exec/src/main/java/org/apache/camel/component/exec/ExecCommand.java
components/camel-exec/src/main/java/org/apache/camel/component/exec/ExecEndpoint.java
components/camel-exec/src/main/java/org/apache/camel/component/exec/ExecProducer.java
components/camel-exec/src/main/java/org/apache/camel/component/exec/impl/DefaultExecBinding.java

Issue: https://issues.apache.org/jira/browse/CAMEL-14150
Adds configuration parameter (logCommandsAtLevelDebug) to set legging level DEBUG for logging of executed commands (for the scenario, when commands contains some sensitive information). Default value is false, so there is no change of behavior if parameter is not defined.

[CAMEL-14150] Camel-exec: option to hide sensitive information in log

---

components/camel-cxf/src/main/java/org/apache/camel/component/cxf/CxfEndpoint.java

I was able to manually verify this fix works against 2.25.0-SNAPSHOT but couldn't figure out how to write a unit test. Happy to do that if given some hints on how to (successfully) get at log output in a unit test or access the underlying CXF LoggingFeature from a CxfEndpoint.

CAMEL-14172: when loggingSizeLimit is -1 it should do what the docs say it does

---

CONTRIBUTING.md

1. 2xlinks with broken MD syntax has been corrected.
2. Incorrect reference to ActiveMQ committer guide has been fixed.

Fix broken/incorrect links

---

camel-core/src/main/java/org/apache/camel/component/file/FileOperations.java
camel-core/src/test/java/org/apache/camel/component/file/FileProducerFileExistAppendTest.java

When file producer applies file based optimization it ignores
fileExist=Append mode and always replaces target file.
This change avoids file based optimization when fileExist=Append.

CAMEL-14127: (2.x port) avoid file by file target replacement when fileExist=Append (#3309)

---

components/camel-pulsar/src/main/docs/pulsar-component.adoc
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarProducer.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/utils/message/PulsarMessageHeaders.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarProducerHeadersInTest.java

Addresses [CAMEL-14184](https://issues.apache.org/jira/browse/CAMEL-14184)
Setting properties on a message is a useful feature for passing along metadata. It was possible to set before https://github.com/apache/camel/commit/3487139d32eb153c30699ce68e5da559f5398082#diff-78ab2639e805ed21d4a401cab24e768a , but was removed. Key is required for key-shared subscription modes. And event_time is useful metadata that can be used for deduping. 
The fix proposed in this PR is to pull the values from the Camel message headers (documented in the adoc) using a naming scheme similar to other header values and using the TypedMessageBuilder to add them to the Pulsar message object. I've also documented the headers coming in from the consumer, since they were missing from the documentation and potentially …

CAMEL-14184: Allow setting Pulsar Message properties, event_time, key fields

---

components/camel-pulsar/src/main/docs/pulsar-component.adoc
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarProducer.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/utils/message/PulsarMessageHeaders.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarProducerHeadersInTest.java

Back-port to 2.x of: https://github.com/apache/camel/pull/3340

CAMEL-14184: (Backport to 2.x) Allow setting Pulsar Message properties, event_time, key fields

---

components/camel-pulsar/src/main/docs/pulsar-component.adoc
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/DefaultPulsarMessageReceipt.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/DefaultPulsarMessageReceiptFactory.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarComponent.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarEndpoint.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarMessageListener.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarMessageReceipt.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarMessageReceiptFactory.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/configuration/PulsarConfiguration.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/utils/consumers/CommonCreationStrategyImpl.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarComponentTest.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarConsumerAcknowledgementTest.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarConsumerNoAcknowledgementTest.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarCustomMessageReceiptTest.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarNegativeAcknowledgementTest.java
platforms/spring-boot/components-starter/camel-pulsar-starter/src/main/java/org/apache/camel/component/pulsar/springboot/PulsarComponentConfiguration.java

Back-port to 2.x of: [#3094](https://github.com/apache/camel/pull/3094)

CAMEL-13841: (Backport to 2.x) Allow manual Pulsar message acknowledgments

---

components/camel-protobuf/src/main/docs/protobuf-dataformat.adoc
components/camel-protobuf/src/main/java/org/apache/camel/dataformat/protobuf/ProtobufConverter.java
components/camel-protobuf/src/main/java/org/apache/camel/dataformat/protobuf/ProtobufDataFormat.java
components/camel-protobuf/src/main/java/org/apache/camel/dataformat/protobuf/ProtobufTypeConverter.java
components/camel-protobuf/src/test/java/org/apache/camel/dataformat/protobuf/ProtobufConverterTest.java
components/camel-protobuf/src/test/java/org/apache/camel/dataformat/protobuf/ProtobufMarshalAndUnmarshalMapTest.java

This will add a data type converter to the protobuf data format to convert from proto message to Map. 
*Note:* This addition won't break any existing functionality.

CAMEL-14192: Add a toMap data type converter to ProtobufDataFormat

---

components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxFilesManager.java
components/camel-box/camel-box-component/src/test/java/org/apache/camel/component/box/BoxFilesManagerIntegrationTest.java

The previous check used the box search api but it relied on a folder index, that was reindexed every couple of minutes, so the check just failed for recently uploaded files. The fix is to use the folder.canUpload() and folder list api.

Fix box upload overwrite. 

---

components/camel-xmpp/src/main/java/org/apache/camel/component/xmpp/XmppPrivateChatProducer.java

A proposed fix to the issue where invalid JID's are generated for private chat messages.
I could not find any reason for the message thread to be appended to the JID and the thread is set in the message, and have removed the thread.
Tested using Openfire 4.4.3.

CAMEL-14194: Message thread name removed from JID

---

components/camel-metrics/src/main/docs/metrics-component.adoc
components/camel-micrometer/src/main/docs/micrometer-component.adoc

Fix asciidoc warnings related to the inline reference

CAMEL-14187: Fix asciidoc warnings related to the inline reference

---

core/camel-main/src/main/java/org/apache/camel/main/BaseMainSupport.java
core/camel-main/src/test/java/org/apache/camel/main/MainTest.java
core/camel-main/src/test/resources/application.properties

Even if tracing is disabled using `camel.main.tracing = false`, it may be re-enabled by some other property (i.e. `camel.context.tracer.exchange-formatter.show-headers`). The problem shows up regardless of the value of the `*.tracer.*` property.

Disable tracing fix

---

components/camel-stomp/src/main/java/org/apache/camel/component/stomp/StompConfiguration.java
components/camel-stomp/src/main/java/org/apache/camel/component/stomp/StompEndpoint.java

The STOMP version is hardcoded in the org.fusesource.stomp.client.Stomp class. Though the org.fusesource.stomp.client.Stomp class has setter method for version, the Camel-Stomp Component has not exposed that option to be set by the users.

CAMEL-14221: Stomp Component has no option to set version

---

components/camel-stomp/src/main/java/org/apache/camel/component/stomp/StompConsumer.java
components/camel-stomp/src/main/java/org/apache/camel/component/stomp/StompEndpoint.java

The response from the Exchange contains only Body. The STOMP headers are missing in the response.

CAMEL-14229: STOMP headers are missing in the Exchange

---

docs/user-manual/modules/ROOT/pages/exchange-pattern.adoc

use the fully qualified name so that users can find the enumeration easily as the information is no more available from the link that is removed.

Remove dead link to javadoc of ExchangePattern

---

core/camel-core-osgi-activator/pom.xml
tests/camel-itest-karaf/pom.xml
tests/camel-itest-karaf/src/test/java/org/apache/camel/itest/karaf/main/BundleIT.java
tests/camel-itest-karaf/src/test/java/org/apache/camel/itest/karaf/main/PaxExamOptions.java

Since OSGI activator depends on Karaf features it can only be built
after it, and since Karaf features include OSGI activator it fails as
the activator is not present in the Maven reactor at that point -- it
will be built right after it. This moves the tests, the only part that
depends on the Karaf features to the Karaf integration tests to prevent
this situation.

Move camel-core-osgi-activator tests to Karaf itests

---

components/camel-http4/src/main/docs/http4-component.adoc
components/camel-http4/src/main/java/org/apache/camel/component/http4/HttpEndpoint.java
components/camel-http4/src/main/java/org/apache/camel/component/http4/HttpGetWithBodyMethod.java
components/camel-http4/src/main/java/org/apache/camel/component/http4/HttpProducer.java
components/camel-http4/src/main/java/org/apache/camel/component/http4/helper/HttpMethodHelper.java
components/camel-http4/src/test/java/org/apache/camel/component/http4/HttpMethodsTest.java
components/pom.xml

Added support for GET with body content on camel-http4. This is triggered with the 'getWithBody=true' uri parameter.

Http4+get with body

---

components/camel-csv/src/main/docs/csv-dataformat.adoc

Documentation did explains how to skip the first line on header for versions until 2.15, but did not when version is 2.16.5. Method is different. 
I added an example and a message to avoid test with an outdated method.

Put the example of skipHeaderRecord csv unmarshal

---

core/camel-base/src/main/docs/simple-language.adoc

Differentiate between "not equals" and "not equals ignore case" symbol.

Correct "not equals" symbol

---

components/camel-mongodb/src/main/docs/mongodb-component.adoc
components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/MongoDbComponent.java
components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/MongoDbEndpoint.java
components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/MongoDbProducer.java
components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/MongoDbTailTrackingManager.java
components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/meta/MongoDBMetaExtension.java
components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/processor/idempotent/MongoDbIdempotentRepository.java
components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/verifier/MongoComponentVerifierExtension.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/AbstractMongoDbTest.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/EmbedMongoConfiguration.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/MongoDbConnectionBeansTest.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/MongoDbIndexTest.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/MongoDbOperationsTest.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/MongoDbReadPreferenceOptionTest.java

* switching com.mongodb.MongoClient to com.mongodb.client.MongoClient
* Adding support for explicit WriteConcern and ReadPreferences
* Updated unit test to fit new client

CAMEL-14258: switching old MongoClient to new interface

---

components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/NettyHttpComponent.java
core/camel-support/src/main/java/org/apache/camel/support/RestComponentHelper.java

Given the duplication on the consumer creation for the REST DSL components I wanted to propose some refactoring to make it more maintainable with the matchOnUriPrefix change.  Can apply to the other components, add tests and appropriate api documentation but I wanted to solicit feedback on the refactor before adding any polish.

CAMEL-14303: Refactor Rest Component Common code into helper.

---

components/camel-hbase/src/main/java/org/apache/camel/component/hbase/HBaseProducer.java
components/camel-swagger-java/src/main/java/org/apache/camel/swagger/RestSwaggerReader.java
components/camel-xslt/src/main/java/org/apache/camel/component/xslt/XsltBuilder.java
tooling/apt/src/main/java/org/apache/camel/tools/apt/EndpointAnnotationProcessor.java

This is the last patch of errors reported by lgtm, mostly removing unused variables or incompatible types equality. Some I have neglected as I think it could be false positive

CAMEL-14312: Fix issues reported by lgtm

---

components/camel-univocity-parsers/src/main/java/org/apache/camel/dataformat/univocity/AbstractUniVocityDataFormat.java
core/camel-base/src/main/java/org/apache/camel/impl/engine/ServicePool.java

As reported by https://lgtm.com/projects/g/apache/camel/alerts/?mode=tree&ruleFocus=1507076816054

Fix race conditions in double-checked locking object initializations.

---

docs/user-manual/modules/ROOT/pages/async.adoc

This is apparently how the list should be formatted: https://github.com/apache/camel/blame/master/docs/user-manual/modules/ROOT/pages/async.adoc#L94

doc: fix numbered list in async documentation

---

docs/user-manual/modules/ROOT/examples/components/camel-jms/src/test/resources/org/apache/camel/component/jms/jmsRouteUsingSpring.xml
docs/user-manual/modules/ROOT/pages/configuring-camel.adoc

The include was missing a tags, this PR fixes it.
Current version online: https://camel.apache.org/manual/latest/configuring-camel.html
Before: 
After:

include relevant snippets from configuration file in configuring-camel.adoc

---

docs/user-manual/modules/ROOT/pages/advanced-configuration-of-camelcontext-using-spring.adoc

This fixes the spelling of "documentes" -> "documents"

fixing typo in documentation for advanced-configuration-of-camelcontext-using-spring.adoc

---

docs/user-manual/modules/ROOT/pages/async.adoc

This uses the enumeration on async.adoc. Please feel free to disagree and close the PR (or to agree and merge it).
Live (old) content: https://camel.apache.org/manual/latest/async.html
Before:
After:

use the enumeration functionality of AsciiDoc

---

docs/components/modules/ROOT/pages/azure-blob-component.adoc
docs/components/modules/ROOT/pages/debezium-mongodb-component.adoc
docs/components/modules/ROOT/pages/debezium-mysql-component.adoc
docs/components/modules/ROOT/pages/debezium-postgres-component.adoc
docs/components/modules/ROOT/pages/debezium-sqlserver-component.adoc
docs/user-manual/modules/ROOT/pages/camel-3-migration-guide.adoc

This fixes the warnings created when rendering the contents via Antora.
While this PR fixes them for the camel git repo, the same problems occur in camel-k and camel-quarkus and should be fixed there as well.
```
asciidoctor: WARNING: skipping reference to missing attribute: camel-version
asciidoctor: WARNING: skipping reference to missing attribute: server-name
asciidoctor: WARNING: skipping reference to missing attribute: database-name
asciidoctor: WARNING: skipping reference to missing attribute: table-name
asciidoctor: WARNING: skipping reference to missing attribute: server-name
asciidoctor: WARNING: skipping reference to missing attribute: database-name
asciidoctor: WARNING: skipping reference to missing attribute: table-name
asciidoctor: WARNING: skipping reference to missing …
```

escape placeholders in text that would otherwise be treated as AsciiDoc attributes

---

components/camel-aws-ddb/src/main/java/org/apache/camel/component/aws/ddb/AbstractDdbCommand.java
components/camel-aws-ddb/src/main/java/org/apache/camel/component/aws/ddb/QueryCommand.java
components/camel-aws-ddb/src/main/java/org/apache/camel/component/aws/ddb/ScanCommand.java

The limit and start key headers were not being used by the component. This has been corrected. They are key features of the operation as documented here https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Scan.html.
Also, I would need this fix relatively soon. I can backport it to the 3.0.x branch if needed.

Fix DynamoDB Scan Operation.

---

components/camel-http4/src/main/docs/http4-component.adoc

The doc change discussed here: https://issues.apache.org/jira/browse/CAMEL-7410 is not in the published version of this page. Here it is again. cookiePolicy --> cookieSpec.
Tested on camel 2.13

Changed 'cookiePolicy' to 'cookieSpec'

---

components/camel-netty4/src/main/java/org/apache/camel/component/netty4/handlers/ClientChannelHandler.java
components/camel-netty4/src/test/java/org/apache/camel/component/netty4/NettyRequestTimeoutTest.java

Issue: https://issues.apache.org/jira/browse/CAMEL-14373
Master issue: https://issues.apache.org/jira/browse/CAMEL-14363
Master PR: https://github.com/apache/camel/pull/3460
Backported 1c8fd20ba01c4beebc7e8b4a87b00e09d4298361

[ENTESB-12590] Camel netty4 requestTimeout doesn't work as expected

---

components/camel-irc/src/main/docs/irc-component.adoc
components/camel-irc/src/main/java/org/apache/camel/component/irc/IrcComponent.java
components/camel-irc/src/main/java/org/apache/camel/component/irc/IrcConfiguration.java
components/camel-irc/src/main/java/org/apache/camel/component/irc/IrcConsumer.java
components/camel-irc/src/main/java/org/apache/camel/component/irc/IrcEndpoint.java
components/camel-irc/src/main/java/org/apache/camel/component/irc/IrcProducer.java
components/camel-irc/src/test/java/org/apache/camel/component/irc/CodehausIrcChat.java
components/camel-irc/src/test/java/org/apache/camel/component/irc/IrcConfigurationTest.java
components/camel-irc/src/test/java/org/apache/camel/component/irc/IrcConsumerTest.java
components/camel-irc/src/test/java/org/apache/camel/component/irc/IrcEndpointTest.java
components/camel-irc/src/test/java/org/apache/camel/component/irc/IrcProducerTest.java
core/camel-endpointdsl/src/main/java/org/apache/camel/builder/endpoint/dsl/IrcEndpointBuilderFactory.java
docs/components/modules/ROOT/pages/irc-component.adoc
docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide.adoc

Issue: https://issues.apache.org/jira/browse/CAMEL-14374
Method sanitaze(), which contained a lot of logic about handling the uri, was removed.
Compo model was used instead.
This change led to remove one of the uri syntaxes (irc:nick@host[:port]/#room[?options])
Doc was updated and note to the upgrade guide was added.

[CAMEL-14374] Camel-irc validation of endpoint's url fails for url

---

components/camel-kafka/src/main/docs/kafka-component.adoc
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaComponent.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConfiguration.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaComponentTest.java
core/camel-endpointdsl/src/main/java/org/apache/camel/builder/endpoint/dsl/KafkaEndpointBuilderFactory.java

My first PR after my holidays and to kick my brain on again :). 
Per [CAMEL-14250](https://issues.apache.org/jira/browse/CAMEL-14250), this will add new optional called `additionalProperties.` to Kafka component to allow properties that are not covered by `KafkaConfigurations`

CAMEL-14250: Allow custom configurations into Kafka component

---

components/camel-jira/src/main/docs/jira-component.adoc

AttachFile isn't in the list of enums at org.apache.camel.component.jira.JiraType and it wants a File, not a GenericFile.

Doc update

---

core/camel-base/src/main/java/org/apache/camel/impl/engine/DefaultConsumerTemplate.java

`receiveBody()` methods are duplicated.
This PR extracts a private method from the `receiveBody()` methods and simplifies codes.

receiveBody methods are extracted

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PackageComponentMojo.java

Changed it to `Set` in order to keep all json files with the same name (but with different path) for a component. I think this was the original behavior, to expect a Set instead of Map

Fix PackageComponentMojo when generates json files

---

components/camel-test-spring/src/main/docs/test-spring.adoc

Completely removed a partially deleted row for class org.apache.camel.test.spring.LazyLoadTypeConverters.
LazyLoadTypeConverters has been deprecated and removed from at least version 2.20.2

Minor cleanup for camel-test-spring documentation 

---

components/camel-salesforce/camel-salesforce-component/src/main/docs/salesforce-component.adoc
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/SalesforceComponent.java

This commit allows the user to overwrite the default http client max content length of 4 MB.

CAMEL-14424: HTTP responses over 4 MB fail

---

parent/pom.xml

This configures `-XX:+ExitOnOutOfMemoryError` for JVM spun by Maven
Surefire plugin. So now when JVM launched by Surefire signals
`OutOfMemoryError` it will abruptly exit the JVM, skipping any failing
test rerun and it will not generate the JUnit XML/TXT report.
Instead `target/surefire-reports/*.dumpstream` needs to be consulted to
find errors like:
```
Corrupted STDOUT by directly writing to native stream in forked JVM 1. Stream 'Terminating due to java.lang.OutOfMemoryError: Java heap space'.
```
So the downside of this is that troubleshooting test issues when
`OutOfMemoryError` occurs is more difficult; the plugin stops executing
and fails the module build with:
```
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
```
Newer version of …

CAMEL-14428: add `-XX:+ExitOnOutOfMemoryError` to surefire

---

docs/user-manual/modules/ROOT/pages/json.adoc

The include option in the example should have the value "NON_NULL" instead of "NO**T**_NULL:
<json id="json" library="Jackson" include="NON_NULL" />

Fix for XML DSL example: Setting Serialization Include Option for Jackson Marshal

---

components/camel-smpp/pom.xml
components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppConnectionFactory.java
platforms/karaf/features/src/main/resources/features.xml

camel-smpp: Remove commons-codec dependency.

---

components/camel-debezium-common/camel-debezium-common-component/src/main/java/org/apache/camel/component/debezium/DebeziumComponent.java
components/camel-debezium-common/camel-debezium-common-component/src/main/java/org/apache/camel/component/debezium/configuration/EmbeddedDebeziumConfiguration.java
components/camel-debezium-common/camel-debezium-common-component/src/test/java/org/apache/camel/component/debezium/DebeziumComponentTest.java
components/camel-debezium-common/camel-debezium-common-component/src/test/java/org/apache/camel/component/debezium/configuration/EmbeddedDebeziumConfigurationTest.java
components/camel-debezium-mongodb/src/main/docs/debezium-mongodb-component.adoc
components/camel-debezium-mysql/src/main/docs/debezium-mysql-component.adoc
components/camel-debezium-postgres/src/main/docs/debezium-postgres-component.adoc
components/camel-debezium-sqlserver/src/main/docs/debezium-sqlserver-component.adoc

Per title. Similar to [camel-kafka](https://github.com/apache/camel/pull/3468), users can set additional properties using prefix `additionalProperties.`. E.g: 
`debezium-mysql:test?offsetStorage=test&additionalProperties.schema.url=localhost:1246`

CAMEL-14420: Support additional properties on Debezium components

---

components/camel-master/src/main/java/org/apache/camel/component/master/MasterComponent.java
components/camel-master/src/test/java/org/apache/camel/component/master/EndpointUriEncodingTest.java

https://issues.apache.org/jira/browse/CAMEL-14456

CAMEL-14456: camel-master - RAW() parameter value in delegated URI gets encoded

---

components/camel-netty/src/main/docs/netty-component.adoc
components/camel-netty/src/main/java/org/apache/camel/component/netty/NettyComponent.java

Looks like pool-size formula  javadoc is displayed wrong in the documentation.
Changed the format.
Relates to #3529

Josetesan patch 1

---

docs/user-manual/modules/ROOT/pages/configuring-camel.adoc

Old Javadoc location at `http://camel.apache.org/maven/*` appears to be broken.
Can we point to `javadoc.io` instead?
Linked adjusted for 3.x changes - Splitting classess from `camel-core` into `camel-api` and `camel-support`.

Fix broken links to Javadoc

---

components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitConsumer.java
components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/RabbitMQRequeueIntTest.java

If header `'rabbitmq.REQUEUE'` has non-boolean value, message will never be rejected (`channel.basicReject(...)`), because of exception.

Fix RabbitMQ requeue header handling

---

docs/user-manual/modules/ROOT/pages/architecture.adoc
docs/user-manual/modules/ROOT/pages/async.adoc
docs/user-manual/modules/ROOT/pages/book-getting-started.adoc
docs/user-manual/modules/ROOT/pages/browsable-endpoint.adoc
docs/user-manual/modules/ROOT/pages/camelcontext.adoc
docs/user-manual/modules/ROOT/pages/dead-letter-channel.adoc
docs/user-manual/modules/ROOT/pages/endpoint.adoc
docs/user-manual/modules/ROOT/pages/error-handler.adoc
docs/user-manual/modules/ROOT/pages/eventDrivenConsumer-eip.adoc
docs/user-manual/modules/ROOT/pages/exception-clause.adoc
docs/user-manual/modules/ROOT/pages/expression.adoc
docs/user-manual/modules/ROOT/pages/faq/how-does-the-camel-api-compare-to.adoc
docs/user-manual/modules/ROOT/pages/faq/running-camel-standalone.adoc
docs/user-manual/modules/ROOT/pages/injector.adoc
docs/user-manual/modules/ROOT/pages/jmx.adoc
docs/user-manual/modules/ROOT/pages/jndi.adoc
docs/user-manual/modules/ROOT/pages/lifecycle.adoc
docs/user-manual/modules/ROOT/pages/message-endpoint.adoc
docs/user-manual/modules/ROOT/pages/message.adoc
docs/user-manual/modules/ROOT/pages/predicate.adoc
docs/user-manual/modules/ROOT/pages/process-eip.adoc
docs/user-manual/modules/ROOT/pages/processor.adoc
docs/user-manual/modules/ROOT/pages/rollback-eip.adoc
docs/user-manual/modules/ROOT/pages/spring.adoc
docs/user-manual/modules/ROOT/pages/transactional-client.adoc
docs/user-manual/modules/ROOT/pages/type-converter.adoc

Broken javadoc links will be pointed towards appropriate entries on `javadoc.io`.
This commit fixes all ASCIIDoc files under `docs/user-manual/`
This is **not** a blind find-replace commit. It takes care of API Changes in Camel 3.x, where camel-core was split into several sub modules.
There are 11 files under `docs/components/` that need similar fixes. I'll keep pushing them one by one.

[CAMEL-14482] Fix broken javadoc links

---

components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpOperations.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/FtpSimpleConsumeStreamingPartialReadTest.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/FtpSimpleConsumeStreamingStepwiseFalseTest.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/FtpSimpleConsumeStreamingStepwiseTrueTest.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/FtpSimpleConsumeStreamingWithMultipleFilesTest.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/FtpStreamingMoveTest.java
docs/components/modules/ROOT/pages/ftp-component.adoc
docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide.adoc

Issue: https://issues.apache.org/jira/browse/CAMEL-14506
Stepwise and stream download are not supported together. 
Combination of these two parameters in ftp component is strictly forbidden (could cause freeze). IllegalArgumentException is now thrown when this options are used together.
A new test covering this change is introduced: FtpSimpleConsumeStreamingStepwiseTrueTest
Doc is updated.

CAMEL-14506 came-ftp - streamDownload and stepwise could cause deadlock

---

components/camel-bindy/pom.xml
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/BindyFixedLengthFactory.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/UnicodeHelper.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/annotation/FixedLengthRecord.java
components/camel-bindy/src/test/java/org/apache/camel/dataformat/bindy/UnicodeHelperTest.java
parent/pom.xml

See Issue https://issues.apache.org/jira/browse/CAMEL-14521

Bindy unicode patch

---

docs/user-manual/modules/ROOT/pages/index.adoc

Changing the hyper link reference from Git page to actual camel page

Changing the hyper link to actual camel page

---

components/camel-bean/src/main/docs/bean-component.adoc
components/camel-cxf/src/main/docs/cxfrs-component.adoc
components/camel-dataset/src/main/docs/dataset-component.adoc
components/camel-dataset/src/main/docs/dataset-test-component.adoc
components/camel-jpa/src/main/docs/jpa-component.adoc
components/camel-jsch/src/main/docs/scp-component.adoc
components/camel-log/src/main/docs/log-component.adoc
components/camel-mock/src/main/docs/mock-component.adoc
components/camel-stomp/src/main/docs/stomp-component.adoc
components/camel-xpath/src/main/docs/xpath-language.adoc
docs/components/modules/ROOT/pages/bean-component.adoc
docs/components/modules/ROOT/pages/cxfrs-component.adoc
docs/components/modules/ROOT/pages/dataset-component.adoc
docs/components/modules/ROOT/pages/dataset-test-component.adoc
docs/components/modules/ROOT/pages/jpa-component.adoc
docs/components/modules/ROOT/pages/log-component.adoc
docs/components/modules/ROOT/pages/mock-component.adoc
docs/components/modules/ROOT/pages/scp-component.adoc
docs/components/modules/ROOT/pages/stomp-component.adoc
docs/components/modules/ROOT/pages/xpath-language.adoc

Follow up on [PR#3561](https://github.com/apache/camel/pull/3561)
Based on the advise from @oscerd the PR has been updated.
Steps followed
1. Links fixed in `<component-root>/src/main/docs/<doc-file>.adoc`
2. Rebuild the project with `mvn clean install -Pfastinstall`
3. Output files (*.adoc) produced by the build process has been committed as well.
No changes observed on dynamic Javadoc content tables produced as a part of build process

CAMEL-14482: Fix broken Javadocs on Camel Components

---

docs/user-manual/modules/ROOT/pages/camelcontext.adoc

Changed CamelContext hyperlink from https://www.javadoc.io/doc/org.apache.camel/camel-api/current/org/apache/camel/CamelContext.html (error - PAGE NOT FOUND) to https://www.javadoc.io/doc/org.apache.camel/camel-api/latest/org/apache/camel/CamelContext.html

Updated reference to javadoc.io CamelContext

---

components/camel-sjms/src/main/java/org/apache/camel/component/sjms/AggregatedExceptionListener.java
components/camel-sjms/src/main/java/org/apache/camel/component/sjms/SjmsConsumer.java
components/camel-sjms/src/main/java/org/apache/camel/component/sjms/SjmsEndpoint.java
components/camel-sjms/src/main/java/org/apache/camel/component/sjms/SjmsProducer.java
components/camel-sjms/src/main/java/org/apache/camel/component/sjms/producer/InOutProducer.java
components/camel-sjms/src/test/java/org/apache/camel/component/sjms/ReconnectConsumerTest.java
components/camel-sjms/src/test/java/org/apache/camel/component/sjms/ReconnectInOutProducerTest.java
components/camel-sjms/src/test/java/org/apache/camel/component/sjms/ReconnectProducerTest.java
components/camel-sjms/src/test/java/org/apache/camel/component/sjms/support/JmsTestSupport.java

Two tests of reconnect logic.
Reconnect for Producer is really simple, because it's based on GenericObjectPool capabilities. Providing session validation and testOnBorrow is enough to seamless reconnect.
Consumer is much worse case and I'm not so very proud about this solution. Because objects in pool are never pooled, there is no chance to test them on borrow. I'm catching exception on JMS connection and I'm doing a full reset of whole consumer (stop/start on executor). I'm opened for better ideas, that will probably need a small refactoring of MessageListener's creation.

CAMEL-6950 camel-sjms: Lacks reconnection logic in case of exception

---

components/camel-dozer/src/main/java/org/apache/camel/component/dozer/DozerEndpoint.java

I appreciate this potentially breaks any existing users that ALWAYS expect the default `dozerBeanMapping.xml` to be loaded, when no files were mentioned. 
Currently there are NO tests that fail or expect the existing behaviour.
This is probably a breaking change and I appreciate that it might get dismissed.

if BeanMappingBuilders defined skip dozerBeanMapping.xml

---

docs/user-manual/modules/ROOT/pages/book-getting-started.adoc

Fix tiny typo on https://camel.apache.org/manual/latest/book-getting-started.html page.

Fix typo on getting started page.

---

components/camel-servlet/src/main/java/org/apache/camel/component/servlet/DefaultHttpRegistry.java

added synchronized blocks so that registry is now thread-safe
[CAMEL-14639](https://issues.apache.org/jira/browse/CAMEL-14639)

DefaultHttpRegistry thread safety

---

docs/user-manual/modules/ROOT/pages/index.adoc

To the user manual page, a brief introduction is provided about `Apache Camel` and the link to the `Introduction` is provided as well along with the paragraph. 
Hence, from the `Overview` section, the link to `Introduction` is removed as it can be easily accessed before the list of chapters itself.

CAMEL-11492: offer an introduction to user manual page

---

docs/user-manual/modules/ROOT/pages/contributing.adoc

Updated content to reflect the new issue tracker JIRA used by Apache Camel, instead of Subversion, which was used earlier.

[CAMEL-14689] Update contributing guide to include JIRA instead of Subversion

---

docs/user-manual/modules/ROOT/pages/java-dsl.adoc

* Observed that the code snippets were given spaces to match the indentation of the previous code block. However, before each code snippets, it was provided with a paragraph that specifies where the code snippet is to be placed within the main code block.
* Hence, to improve readability and to increase the ease in reading documentation, I have removed the spaces within the code snippets and highlighted the methods to which the particular code snippets belong to in the paragraph.

Reformat the structure for the documentation on Java DSL

---

core/camel-base/src/main/docs/properties-component.adoc
docs/components/modules/ROOT/pages/properties-component.adoc
docs/user-manual/modules/ROOT/pages/properties-component.adoc

* The `properties-component.adoc` had a few redundant spaces in the code snippets. Hence, I removed the redundant spaces from the `core/camel-base`, `docs/user-manual`, `docs/components` so that the code snippets have a similar structure format.

Remove all redundant space from each properties-components documents

---

components/camel-mongodb-gridfs/pom.xml
components/camel-mongodb/pom.xml
components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/MongoDbEndpoint.java
components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/MongoDbProducer.java
components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/meta/MongoDBMetaExtension.java
components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/verifier/MongoComponentVerifierExtension.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/MongoDbIndexTest.java
parent/pom.xml
platforms/karaf/features/src/main/resources/features.xml

I was thinking of creating a separate mongo4 component for this but the changes required to the existing component turned out to be fairly minimal. Hence I amended it. Hope that's ok.
The `mongo-gridfs` component is trickier to upgrade, so I left it untouched for now.

CAMEL-14726: Upgrade MongoDB client to 4.0.0

---

components/camel-jpa/src/main/java/org/apache/camel/processor/idempotent/jpa/JpaMessageIdRepository.java

Fix for: [CAMEL-14761](https://issues.apache.org/jira/browse/CAMEL-14761)
Issue: When using the JpaMessageIdRepository for an idempotent repo (or inProgressRepo) for file processing it holds onto connections on contains() method.  Other methods add(), remove(), etc. were fixed in CAMEL-11630.
PR: code fixed in the same way as it was fixed for methods add(), remove(), etc. in: [CAMEL-11630](https://issues.apache.org/jira/browse/CAMEL-11630), [PR](https://github.com/apache/camel/pull/1883)

CAMEL-14761 JPAMessageIdRepository.contains() release db connection fix

---

core/camel-core/src/test/java/org/apache/camel/processor/TransformTest.java
core/camel-core/src/test/java/org/apache/camel/processor/TransformViaDSLTest.java

* I observed that for the **Content Enricher** docs within the EIP, two of the code snippets are linked to a part of the code within the **TransformTest.java** and **TransformViaDSLTest.java** using the tag. However, the tags are used in such a manner that the indentation space is also taken into account and is seen in the documentation. This doesn't fit with the structure of the entire documentation.
* Hence, I came up with a solution that if we used inline comments it would avoid the unnecessary initial indentation and the format of code snippets would remain structured for the documentation.

remove the redundant space from docs and include whitespace after ; for content-richer based code-snippets

---

components/camel-rabbitmq/pom.xml
components/camel-rabbitmq/readme.txt
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/reply/TemporaryQueueReplyManager.java
components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/RabbitMQTemporaryQueueAutoRecoveryIntTest.java

- Add QueueRecoveryListener to update replyTo and rebind the new temporary queue
- Add integration test using RabbitMQ Management HTTP API

CAMEL-14789: camel-rabbitmq - Automatic recovery of temporary reply queue

---

components/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubConnectionFactory.java
components/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubConsumer.java
components/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubEndpoint.java
components/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubProducer.java
components/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/consumer/PubsubAcknowledgement.java

I'm still seeing this issue in 2.25.0: https://issues.apache.org/jira/browse/CAMEL-14292
I have removed the remaining references to `com.google.api.client.repackaged.com.google.common.base.Strings`
which is the main problem.
Also decided to remove the remaining calls to `com.google.api.client.util.Strings` and instead use `org.apache.camel.util.ObjectHelper` as it seemed natural to me to use an internal string util.
For the GooglePubsubConnectionFactory we're using so many com.google.api.client imports anyways that I was in doubt - but made the same change there.
Let me know if you want any modifications and I'll push it right away. Tested locally and my app now loads without the exception I got before:
```
java.lang.NoClassDefFoundError: …
```

[CAMEL-14292] Fixes NoClassDefFoundError in camel-google-pubsub, references util class from google-http-client

---

components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/UnicodeHelper.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/annotation/FixedLengthRecord.java
components/camel-bindy/src/test/java/org/apache/camel/dataformat/bindy/UnicodeHelperTest.java

See issue: https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-14825

Bugfix for UnicodeHelper in Bindy component

---

components/camel-caffeine/src/main/docs/caffeine-cache-component.adoc
components/camel-cbor/src/main/docs/cbor-dataformat.adoc
components/camel-chunk/src/main/docs/chunk-component.adoc
components/camel-hl7/src/main/docs/hl7terser-language.adoc
components/camel-ognl/src/main/docs/ognl-language.adoc

* I have observed that the code snippets aren't properly indentation and structured well. This is present for various documentation pages. Hence, I have resolved this issue by structuring the indentation and removing any redundant spaces for a few documentation pages.

CAMEL-14827: Site Documentation Improvement within Camel 

---

docs/user-manual/modules/ROOT/pages/camel-3-migration-guide.adoc
docs/user-manual/modules/ROOT/pages/graceful-shutdown.adoc

Minor documentation update for setting the new `DefaultShutdownStrategy` package. I'm also adding a small note about this in the migration guide.

Update DefaultShutdownStrategy documented package and add migration note

---

camel-core/src/main/docs/modules/ROOT/pages/properties-component.adoc
camel-core/src/main/docs/modules/ROOT/pages/timer-component.adoc
camel-core/src/main/docs/modules/ROOT/pages/xslt-component.adoc
components/camel-beanstalk/src/main/docs/beanstalk-component.adoc
components/camel-jetty9/src/main/docs/jetty-component.adoc
components/camel-spring/src/main/docs/spring.adoc
components/camel-undertow/src/main/docs/undertow-component.adoc
components/camel-zipkin/src/main/docs/zipkin.adoc
docs/components/modules/ROOT/pages/beanstalk-component.adoc
docs/components/modules/ROOT/pages/jetty-component.adoc
docs/components/modules/ROOT/pages/spring.adoc
docs/components/modules/ROOT/pages/undertow-component.adoc
docs/components/modules/ROOT/pages/zipkin.adoc

Changing xref links for splitting FAQ into a separate module within user-manual. Changes are corresponding to PR #3693 on master.

Change xref links for splitting FAQ in camel-2.x

---

components/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubConsumer.java

[CAMEL-14861] fixed bug in GooglePubsubConsumer by initialized subscribers

---

components/camel-spring/src/main/java/org/apache/camel/spring/CamelBeanPostProcessor.java

This avoids issues e.g. described in https://github.com/spring-projects/spring-framework/issues/24058 and additionally according to Spring it is best practice to have BeanPostProcessors implement Ordered interface.

CAMEL-14883 CamelBeanPostProcessor implements Ordered interface provided by Spring with lowest precedence

---

components/camel-grpc/src/main/java/org/apache/camel/component/grpc/server/GrpcMethodHandler.java

I reported to jira about error handling in grpc component and it was fixed.
https://issues.apache.org/jira/browse/CAMEL-14893
I am also using camel 2.25.x version in my project.
So I modified the source code in the 2.25.x branch for this issue.

Fixes CAMEL-14893: fix 2.25.x branch

---

components/camel-influxdb/src/main/java/org/apache/camel/component/influxdb/InfluxDbProducer.java
components/camel-influxdb/src/test/java/org/apache/camel/component/influxdb/AbstractInfluxDbTest.java
components/camel-influxdb/src/test/java/org/apache/camel/component/influxdb/InfluxDbEnsureDatabaseExistsTest.java

Issue: https://issues.apache.org/jira/browse/CAMEL-14892
2 depricated calls are replaced with the correct ones. (queries with `SHOW DATABASES` and `CREATE DATABASE ` are called instead of depricated method on `InfluxDB`).
Test covering call is added. …

CAMEL-14892 Camel-influxdb uses deprecated methods in doInsert action

---

docs/user-manual/modules/ROOT/pages/index.adoc

Remove the exhaustive list of components contents from user manual index page, replacing by a link.

Fixes CAMEL-14906: point to components docs, don't list it all

---

docs/components/modules/ROOT/pages/index.adoc

Split the components table into core and non-core components.  Bring back the counts which somehow disappeared during the previous commits.

Fixes CAMEL-14907: separate core and non core components in index page tables

---

components/camel-platform-http/src/main/java/org/apache/camel/component/platform/http/PlatformHttpComponent.java

https://issues.apache.org/jira/browse/CAMEL-14922
This is fixing the immediate issue reported in CAMEL-14922. However it does not solve the problem that the platform-http component offers no real support for CORS beyond enabling the OPTIONS method handling.

CAMEL-14922: Cannot enable cors on platform-http

---

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/SalesforceComponent.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/SalesforceProducer.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/client/AbstractClientBase.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/client/DefaultAnalyticsApiClient.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/client/DefaultBulkApiClient.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/client/DefaultCompositeApiClient.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/client/DefaultRestClient.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/processor/AbstractSalesforceProcessor.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/processor/AnalyticsApiProcessor.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/processor/BulkApiProcessor.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/processor/CompositeApiProcessor.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/streaming/SubscriptionHelper.java
components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/internal/client/AbstractClientBaseTest.java
components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/internal/streaming/SubscriptionHelperTest.java
components/camel-salesforce/camel-salesforce-maven-plugin/src/main/java/org/apache/camel/maven/AbstractSalesforceMojo.java

This PR is an attempt to fix the lazy-login bug in the camel-salesforce component, which was logged in [CAMEL-14744](https://issues.apache.org/jira/browse/CAMEL-14744).
I would like some feedback on the chosen approach :
1. Passing around SalesforceLoginConfig instead of a boolean value indicating lazyLogin
2. "JIT" login in the SalesforceProducer#process method
This fix was tested against an actual Salesforce instance, via the DefaultRestClient implementation. I am unable to verify the other ApiClient implementations and things like the SubscriptionHelper, AbstractSalesforceMojo.

CAMEL-14744: fix camel-salesforce lazy-login

---

catalog/camel-catalog/src/main/java/org/apache/camel/catalog/CamelCatalog.java
catalog/camel-catalog/src/main/java/org/apache/camel/catalog/Kind.java

This change makes it easier to perform the following tasks:
* Given some artifactId, list all components, languages, dataformats, etc. implemented in the associated artifact. This is useful when scaffolding Camel Quarkus extensions.
* Save some code when Docs pages form Camel Catalog
With this change in place, I can do something like
```
for (Kind kind: Kind.values()) {
for (String name : catalog.findNames(kind)) {
BaseModel model = catalog.model(kind, name);
}
}
```

Introduce Catalog methods to allow iterating over all parts

---

components/camel-ftp/src/main/docs/ftp-component.adoc

option was still called `isImplicit` (Camel 2.x). Changed to `implicit`.

Fixed doc: option 'isImplicit' in FTPS implicit sample

---

docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide.adoc

sources for type converter loaders were generated too late in the Maven
build cycle. The result is that the source would be generated after the
compile, test compile, and test phases, so they would not be available
to unit tests.
~~The fix is to run the maven plugin in the `pre-compile` phase rather
than `process-classes`.~~
The fix is to have Maven re-compile after type converter loaders have been generated. The PR documents how to configure maven-compiler-plugin to do so.

[CAMEL-14818] fixes documentation for Camel Package Maven plugin

---

components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/RemoteFileEndpoint.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/SftpOperations.java

CAMEL-14947 check for existence of remote directory using ls very slow

---

components/camel-undertow/pom.xml
components/camel-undertow/src/main/java/org/apache/camel/component/undertow/DefaultUndertowHost.java
components/camel-undertow/src/main/java/org/apache/camel/component/undertow/spi/UndertowSecurityProvider.java
components/camel-undertow/src/test/java/org/apache/camel/component/undertow/spi/AbstractProviderServletTest.java
components/camel-undertow/src/test/java/org/apache/camel/component/undertow/spi/ProviderWithServletTest.java
components/camel-undertow/src/test/java/org/apache/camel/component/undertow/spi/ProviderWithoutServletTest.java

Issue: https://issues.apache.org/jira/browse/CAMEL-14950
To allow usage of spring security 5 with camel-undertow, it has to be allowed to execute servlet filters, which are used to secure endpoints. 
This change adds property 'requireServletContext'  into 'UndertowSecurityProvider'. This change allows to use spring security 5 with camel-undertow. The exact useage of spring security 5 is covered by following issue:  https://issues.apache.org/jira/browse/CAMEL-14962
[ ] Each commit in the pull request should …

CAMEL-14950 camel-undertow: secure with spring-security 5 

---

components/camel-undertow/src/test/java/org/apache/camel/component/undertow/spi/ProviderWithServletTest.java

Issue: https://issues.apache.org/jira/browse/CAMEL-14950
@davsclaus , @oscerd 
I've noticed small error with big impact. Test for scenario with servlet was testing scenario without servlet. This simple change it fixes, but there is a problem.
By  previous commit version of servlet-api was set to 3.1.0.Final to be consistent with camel - correct move. *But undertow is not able to start servlet without 4.0 api.*
So with this fix, test will show an error *NoClassDefFoundError: javax/servlet/http/MappingMatch*
(error will be solved in case of servlet-api org.jboss.spec.javax.servlet:jboss-servlet-api_4.0_spec)
Which seems to be blocker for this change. What do you think?
Only solution I see is to keep servlet-api required for undertow in pom. 
[ ] Make sure there is a [JIRA …

fix of test for CAMEL-14950

---

components/camel-jira/src/main/java/org/apache/camel/component/jira/oauth/JiraOAuthAuthenticationHandler.java

Jira component uses a repackaged commons-codec package to use the Base64 class.
We should use the java.util.Base64 class instead.
https://issues.apache.org/jira/browse/CAMEL-14983

CAMEL-14983: jira component: Replace commons Base64 for JDK Base64

---

components/camel-mongodb/src/main/docs/mongodb-component.adoc
components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/converters/MongoDbBasicConverters.java

* Adding a method to allow conversion to ObjectId type, used as default by MongoDB as _id field type.
* Adding some doc to explain how to use it
Closes CAMEL-14989

CAMEL-14989 camel-mongo: add a converter to ObjectId

---

tooling/maven/camel-restdsl-openapi-plugin/src/main/docs/camel-restdsl-openapi-plugin.adoc
tooling/maven/camel-restdsl-openapi-plugin/src/main/java/org/apache/camel/maven/generator/openapi/AbstractGenerateMojo.java

https://issues.apache.org/jira/browse/CAMEL-15023
There are a lot of useful options [1].
Usage:
```
<configuration>
<configOptions>
<library>jersey2</library>
<dateLibrary>java8</dateLibrary>
</configOptions>
...
</configuration>
```
1.   https://github.com/swagger-api/swagger-codegen/issues/7795

CAMEL-15023 camel-restdsl-openapi-plugin: pass configOptions to swagger-codegen-maven-plugin

---

tooling/maven/camel-restdsl-openapi-plugin/src/main/docs/camel-restdsl-openapi-plugin.adoc
tooling/maven/camel-restdsl-openapi-plugin/src/main/java/org/apache/camel/maven/generator/openapi/AbstractGenerateMojo.java

pass correct value to swagger-codegen-maven-plugin and set default value to 'false' for backward compatibility
https://issues.apache.org/jira/browse/CAMEL-15025

CAMEL-15025 camel-restdsl-openapi-plugin: fix 'modelWithXml' parameter propagation

---

components/camel-splunk-hec/pom.xml
components/camel-splunk-hec/src/main/java/org/apache/camel/component/splunkhec/SplunkHECEndpoint.java
components/camel-splunk-hec/src/test/java/org/apache/camel/component/splunkhec/SplunkHECEndpointTest.java
parent/pom.xml

This PR fixes https://issues.apache.org/jira/browse/CAMEL-15031 and allows FQHNs on splunk-hec endpoints.
This PR introduces a dependancy to the Apache commons-validator lib. Even though I'm not completely happy with pulling in a new dependancy I decided to go this route, because any own implementation would be a (ugly?) clone of that code. Nevertheless I'm more than happy to change the implementation if anyone has something more suitable at hand.

CAMEL-15031: Accept FQHN for splunk-hec endpoint

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaHeaderFilterStrategy.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaConsumerFullTest.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaEndpointTest.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaProducerFullTest.java

This prevents propagation of `kafka.` headers when consuming from Kafka or producing back to Kafka. The values of these headers are populated by the `KafkaEndpoint` from values specific to a consumed Kafka record, such as the timestamp or topic, and do not make sense once going to the scope of a new produced Kafka record which has its own values for topic and timestamp.

[CAMEL-15027] Do not propagate record specific Kafka headers

---

components/camel-bam/src/main/docs/bam-example.adoc
components/camel-kubernetes/src/main/docs/openshift-build-configs-component.adoc
components/camel-scala/src/main/docs/scala-eip.adoc
components/camel-shiro/src/main/docs/shiro.adoc
components/camel-spring-security/src/main/docs/spring-security.adoc
components/camel-spring/src/main/docs/spring-summary.adoc
components/camel-test-cdi/src/main/docs/test-cdi.adoc
components/camel-test-spring/src/main/docs/test-spring.adoc
components/camel-urlrewrite/src/main/docs/urlrewrite.adoc
docs/components/modules/ROOT/pages/openshift-build-configs-component.adoc
docs/components/modules/ROOT/pages/spring-summary.adoc
docs/components/modules/others/pages/bam-example.adoc
docs/components/modules/others/pages/scala-eip.adoc
docs/components/modules/others/pages/shiro.adoc
docs/components/modules/others/pages/spring-security.adoc
docs/components/modules/others/pages/test-cdi.adoc
docs/components/modules/others/pages/test-spring.adoc
docs/components/modules/others/pages/urlrewrite.adoc

This fixes the xref problems (locally) and there are no link check errors, but I see 
```
✖ 26017 problems (26017 errors, 0 warnings)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "check:html" exited with 1.
```
These don't immediately appear to relate to the antora-build pages.

Resolves CAMEL-15033: fix xrefs

---

components/camel-google-mail/pom.xml
components/camel-google-mail/src/main/docs/google-mail-component.adoc

Google mail users API is restricted to method getProfile. This pull request opens access to two other useful methods: watch and stop.
See here:
https://developers.google.com/gmail/api/v1/reference/users/watch
===
[ x] Each commit in the pull request should have a meaningful subject line and body.
[x ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
[ x ] Write a pull request …

CAMEL-15052: Cannot watch user with Google Mail component

---

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/SalesforceComponent.java

This is a proposed fix for the issue described on the 
Jira ticket CAMEL-15063. Upon creation, set the shared
Jetty HTTP client to the config instance to avoid an 
NPE.
[x] Write a pull request description that is detailed enough to understand what …

CAMEL-15063: Set the HTTP client in the config instance

---

camel-dependencies/pom.xml
components/camel-sql/src/main/docs/sql-component.adoc
components/camel-sql/src/main/java/org/apache/camel/processor/aggregate/jdbc/JdbcAggregationRepository.java
components/camel-sql/src/main/java/org/apache/camel/processor/aggregate/jdbc/PostgresAggregationRepository.java
components/camel-sql/src/test/java/org/apache/camel/processor/aggregate/jdbc/AbstractJdbcAggregationTestSupport.java
components/camel-sql/src/test/java/org/apache/camel/processor/aggregate/jdbc/JdbcAggregateLoadAndRecoverTest.java
components/camel-sql/src/test/java/org/apache/camel/processor/aggregate/jdbc/JdbcAggregateNotLostTest.java
components/camel-sql/src/test/java/org/apache/camel/processor/aggregate/jdbc/JdbcAggregationRepositoryAlotDataTest.java
components/camel-sql/src/test/java/org/apache/camel/processor/aggregate/jdbc/JdbcAggregationRepositoryMultipleRepoTest.java
components/camel-sql/src/test/java/org/apache/camel/processor/aggregate/jdbc/JdbcAggregationRepositoryRecoverExistingTest.java
components/camel-sql/src/test/java/org/apache/camel/processor/aggregate/jdbc/JdbcAggregationRepositoryTest.java
components/camel-sql/src/test/java/org/apache/camel/processor/aggregate/jdbc/JdbcExchangeSerializationTest.java
components/camel-sql/src/test/java/org/apache/camel/processor/aggregate/jdbc/JdbcGrowIssueTest.java
components/camel-sql/src/test/java/org/apache/camel/processor/idempotent/jdbc/JdbcMessageIdRepositoryCustomTableNameTest.java
components/camel-sql/src/test/java/org/apache/camel/processor/idempotent/jdbc/JdbcMessageIdRepositoryTest.java
components/camel-sql/src/test/resources/sql/init.sql
components/camel-sql/src/test/resources/sql/init2.sql
components/camel-sql/src/test/resources/sql/init3.sql
docs/components/modules/ROOT/pages/sql-component.adoc
docs/user-manual/modules/ROOT/pages/camel-3-migration-guide.adoc
docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_4.adoc

Running JdbcAggregationRepository on a distributed environment (multiple independent
threads or multiple JVMs) we have silently dropped exchanges. This PR aims at introducing
a version identifier to avoid the lost update problem (overwrites when updating the
aggregate row) as stated by the OptimisticLockingAggregationRepository SPI.
Tested running 100 threads to aggregate 10k messages on MySQL 5.7 and PostgreSQL 11.5.
**Do not merge yet.** I'm having some problems running [my test application](https://github.com/fvaleri/integ-examples/blob/master/standalone/distributed-aggr/src/main/java/it/fvaleri/integ/Application.java) with the new routing engine. Will look at it later and once fixed we could add it as an example or test.

[CAMEL-7810] Fix JdbcAggregationRepository optimistic locking feature (master)

---

components/camel-hazelcast/src/main/java/org/apache/camel/processor/aggregate/hazelcast/HazelcastAggregationRepository.java
components/camel-hazelcast/src/main/java/org/apache/camel/processor/aggregate/hazelcast/ReplicatedHazelcastAggregationRepository.java

Hi, I'm facing a situation in which I have many replicas of the same camel application in Kubernetes. I've been able to create a Hazelcast cluster between these replicas, using the feature cellar-kubernetes in Karaf. In this application I'm using the aggregation pattern to aggregate response messages received, but even if the hazelcast cache is shared, the data aren't replicated in all cluster nodes, so to avoid lose cached data in case one of these replicas dies, I was thinking if it could be a good idea to use replicated maps also for the aggregation. For this reason I've created a new class which extends HazelcastAggregationRepository and uses replicated maps instead of maps. I don't know if this change is useless and I'm wrong. Thanks.

Changes in HazelcastAggregationRepository to use replicated maps

---

components/camel-sql/src/main/java/org/apache/camel/processor/aggregate/jdbc/DefaultJdbcOptimisticLockingExceptionMapper.java
components/camel-sql/src/main/java/org/apache/camel/processor/aggregate/jdbc/JdbcAggregationRepository.java

To trigger optimistic locking handling in case of version conflicts, we need to raise `OptimisticLockingException` not just `RuntimeCamelException`. With this change my test application works also on master. I'm going to create the same PR for 2.25.x branch and another PR to contribute the app to the example repository.

[CAMEL-7810] Use OptimisticLockingException for version conflicts

---

components/camel-iota/pom.xml

This component has a transitive dependency on java-md-doclet which
depends on logback-classic but looking at the gode on the github repo,
it does seem that they depends only on the slf4j API thus we can exclude
logback as it may cause some issues on the runtime as there may be
multiple slf4j binding.
[ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you …

camel-iota: remove dependency on logback

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaProducer.java

In camel-kafka the two filter methods of HeaderFilterStrategy where used interchanged.

CAMEL-15121: Fix interchanged method calls of HeaderFilterStrategy

---

core/camel-core-engine/src/main/java/org/apache/camel/model/ProcessorDefinition.java

The setProperty DSL currently does not allow for the usage of a java.util.function.Supplier like the setHeader DSL already does. This PR adds this functionality to the setProperty DSL.

CAMEL-15125: introduce setProperty DSL with supplier parameter

---

archetypes/camel-archetype-spring-boot/src/main/resources/archetype-resources/pom.xml

Those spaces cause extra spaces in autogenerated `pom.xml`.
Before `<project>` node.
For example:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
```
So now it is the same as in [camel-spring-archetype](https://github.com/apache/camel/blob/f257e16d100b14c0a24b748d9df997f32497f823/archetypes/camel-archetype-spring/src/main/resources/archetype-resources/pom.xml#L2)

Fix spring boot archetype spacing

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java

On partition-revoke, do the clearing of the offset inside a finally.
That way, it will happen even if the commit failed. CAMEL-14935

Camel 14935 2.25.x

---

components/camel-file/src/main/java/org/apache/camel/component/file/strategy/FileIdempotentChangedRepositoryReadLockStrategy.java
components/camel-file/src/main/java/org/apache/camel/component/file/strategy/FileIdempotentRenameRepositoryReadLockStrategy.java
components/camel-file/src/main/java/org/apache/camel/component/file/strategy/FileIdempotentRepositoryReadLockStrategy.java

Pass exchange to IdempotentRepository methods so it can be used if necessary.

CAMEL-15150: Pass exchange as parameter to idempotentRepository methods

---

tooling/maven/camel-restdsl-openapi-plugin/src/it/expanded-v3-yaml/pom.xml
tooling/maven/camel-restdsl-openapi-plugin/src/it/expanded-v3-yaml/src/spec/openapi.yaml
tooling/maven/camel-restdsl-openapi-plugin/src/it/expanded-v3-yaml/verify.groovy
tooling/openapi-rest-dsl-generator/src/main/java/org/apache/camel/generator/openapi/OperationVisitor.java

When generating routes for the OpenAPI spec provided by OAS as a sample here https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/petstore-expanded.yaml the plugin fails with an NPE because a parameter is of style = form, but the explode flag is not set explicitly. According to OAS 3.0.3 the explode field is optional and should default to true when style = form.

[CAMEL-15180] Fixes handling missing param.explode when style=form

---

core/camel-main/src/main/java/org/apache/camel/main/BaseMainSupport.java
core/camel-main/src/test/java/org/apache/camel/main/MainRoutesCollectorPackageScanTest.java
core/camel-main/src/test/java/org/apache/camel/main/scan/MyAbstractRouteBuilder.java
core/camel-main/src/test/java/org/apache/camel/main/scan/MyConcreteRouteBuilder.java

This PR updates the "stand-alone" package scanning algorithm in camel-main to exclude abstract classes which extend Route Builder.

CAMEL-15183: Exclude abstract classes from package scanning in stand-alone apps

---

components/camel-aws-cw/src/main/docs/aws-summary.adoc
components/camel-aws2-cw/src/main/docs/aws2-summary.adoc
components/camel-azure/src/main/docs/azure-summary.adoc
components/camel-google-bigquery/src/main/docs/google-summary.adoc
components/camel-hazelcast/src/main/docs/hazelcast-summary.adoc
components/camel-ignite/src/main/docs/ignite-summary.adoc
components/camel-kubernetes/src/main/docs/kubernetes-summary.adoc
components/camel-openstack/src/main/docs/openstack-summary.adoc
components/camel-spring/src/main/docs/spring-summary.adoc
docs/components/modules/ROOT/nav.adoc
docs/components/modules/ROOT/pages/aws-summary.adoc
docs/components/modules/ROOT/pages/aws2-summary.adoc
docs/components/modules/ROOT/pages/azure-storage-blob-component.adoc
docs/components/modules/ROOT/pages/azure-summary.adoc
docs/components/modules/ROOT/pages/google-summary.adoc
docs/components/modules/ROOT/pages/hazelcast-summary.adoc
docs/components/modules/ROOT/pages/ignite-summary.adoc
docs/components/modules/ROOT/pages/kubernetes-summary.adoc
docs/components/modules/ROOT/pages/openstack-summary.adoc
docs/components/modules/ROOT/pages/spring-summary.adoc

Replaces the hardcoded summary lists with generated dlists, and uniformizes the layout a bit.
Note that https://github.com/apache/camel-website/pull/395 needs to be applied first to get the updated indexer extension that can generated lists.

Resolves CAMEL-15182: use generated dlist in summary pages

---

components/camel-jsonpath/src/main/java/org/apache/camel/jsonpath/JsonPathEngine.java
components/camel-jsonpath/src/test/java/org/apache/camel/jsonpath/JsonPathStreamCachingCBRTest.java

When using jsonpath as a predicate in a CBR the StreamCache is not reset and therefore the content is lost. The first commit adds a failing JsonPathStreamCachingCBRTest which is just a copy of JsonPathCBRTest with streaming. The second commit adds `StreamCache.reset()`s wherever it seemed appropriate after content is read.

[CAMEL-15187] fixes bug in camel-jsonpath StreamCache not reset

---

.gitignore
docs/.eslintignore
docs/.eslintrc.js
docs/gulpfile.js
docs/package.json
docs/yarn.lock

* As discussed in PR#3879, the basic syntax and styling were overlooked for the `gulpfile.js`. I have replaced the usage of **==** with **===** and **!=** with **!==** to create a strict comparison. 
* Apart from that, I observed that there were statements that included semicolons and a few that didn't hence to bring consistency, I included semicolons for each statement.

Re-style the javascript for gulpfile

---

components/camel-netty/src/main/java/org/apache/camel/component/netty/NettyProducer.java
components/camel-netty/src/main/java/org/apache/camel/component/netty/handlers/ClientChannelHandler.java

* add back the codes which removes the "timeout" handler after receiving the response
* add the "timeout" handler when activating from the connection pool
https://issues.apache.org/jira/browse/CAMEL-15195

CAMEL-15195: Camel-netty - RequestTimeout seems not working as expected

---

docs/components/modules/ROOT/pages/mina-component.adoc

Replaced duplicate mention of "Mina2" in deprecation warning to advise the use of Mina2 or *Netty*

Fix duplicate Mina2 in deprecation warning

---

components/camel-jt400/src/main/docs/jt400-component.adoc
components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400Configuration.java
components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400Constants.java
components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400Endpoint.java
components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400MsgQueueConsumer.java
components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400MsgQueueProducer.java
components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400MsgQueueService.java
components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400Type.java

**Comments**
This is a work in progress, but opening a Draft PR to welcome comments. This pass has somewhat basic support, sufficient for my current needs. I propose we land this functionality (when no longer WIP) and queue up individual features for future goals (for which I will gladly itemize as issues in Jira)
Currently, the behavior is as follows (this is also included in the doc):
When configured as a message queue consumer endpoint, the endpoint will poll
a message queue on a remote system. For every entry on the queue, a new
`Exchange` is sent with the entry's data in the _In_ message's body. The
data is always formatted as a `String`. Note that only new messages will
be processed. That is, any existing messages on the queue that have already
been handled by another program will …

[CAMEL-15170] initial commit (add message queue support to JT400 component)

---

components/camel-jt400/src/main/docs/jt400-component.adoc
components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400Component.java
components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400Configuration.java
components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400DataQueueProducer.java
components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400Endpoint.java

**Description**
The current documentation for the JT400 component references AS/400 systems throughout. AS/400 no longer exists in any suppported capacity. AS/400 was rebranded in 2000, with its successor being fully discontinued on [Sep 30, 2013](https://en.wikipedia.org/wiki/IBM_System_i). In 2008, AS/400 was replaced by [IBM i](https://en.wikipedia.org/wiki/IBM_i) on Power Systems.
However, since the IBM i system supports many of the same constructs as AS/400 and has the ability to run AS/400 programs, people (understandably) have a tendency to incorrectly identify IBM i systems as "AS/400."
This trivial PR simply intends to correct the server name accordingly, to properly reflect reality.

[CAMEL-15204] Correct IBM i naming/branding in the jt400 component

---

.gitignore
core/camel-core-engine/src/main/docs/modules/eips/pages/content-enricher.adoc

* There is a particular warning regarding the `content-enricher.adoc` related to the example tag while building the camel-website. 
```
asciidoctor: WARNING: content-enricher.adoc: line 48: tag 'example' not found in include file: modules/eips/examples/core/camel-core/src/test/java/org/apache/camel/processor/TransformViaDSLTest.java
asciidoctor: WARNING: content-enricher.adoc: line 56: tag 'example' not found in include file: modules/eips/examples/core/camel-core/src/test/java/org/apache/camel/processor/TransformTest.java
```
I observed that within the camel repo for the master branch, this warning is already dealt with however the warning still persist 'cause in the `antora-playbook.yml` for the camel-website, it also extracts the docs from the `camel-3.3.x` branch and the change weren't …

CAMEL-15216 : Omit the warning for example tag from camel 3.3.x

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/resequence-eip.adoc
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsBatchResequencerJMSPriorityTest.java
components/camel-testcontainers-spring-junit5/src/main/docs/testcontainers-spring-junit5.adoc
components/camel-testcontainers-spring/src/main/docs/testcontainers-spring.adoc
components/camel-testcontainers/src/main/docs/testcontainers.adoc

Fixes typos in documentation to use correct form: `3rd`.

Fix typo across docs: '3rd' instead of '3th'

---

components/camel-jt400/src/main/docs/jt400-component.adoc

fixup of #3936. Sorry for the mistake! I didn't realize that the `:description:` doesn't end up on the web rendering. With this trivial PR, I'm taking the advice of @davsclaus in [this comment](https://github.com/apache/camel/pull/3936#issuecomment-646947807) and updating the component-header field as well to have the "AS/400" reference for web searchability. 
Also a minor grammatical enhancement (`allows you to exchanges messages` -> `allows you to exchange messages`) and adding mention of the message queue and program call support.

(camel-jt400) Add "AS/400" reference to component header

---

components/camel-zookeeper/src/main/java/org/apache/camel/component/zookeeper/ZooKeeperCuratorHelper.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/ZooKeeperCuratorHelperTest.java

Fix reversed order of arguments maxRetries and maxSleepMs in constructor
call of ExponentialBackoffRetry in ZooKeeperCuratorHelper.createCurator
(same as PR #3963 )
[ ] Write a pull request description that is detailed enough to understand what the …

[CAMEL-15262] Fix argument order in new ExponentialBackoffRetry call in ZooKeeperCuratorHelper

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/aggregate-eip.adoc
core/camel-core-engine/src/main/docs/modules/eips/pages/aggregate-eip.adoc

I've updated the documentation to describe how to set an aggregation strategy in pre-completion mode since version 3.0.0. If I didn't massively misunderstand something , then the `PreCompletionAwareAggregationStrategy` interface was removed in `camel-core` 3.0.0 (see commit e441457951b7d7cb6ede65a62fd8460a6485e322) and `AggregationStrategy` new default methods replace the removed methods.
So you'll need to implement the `canPreComplete` method by your own, it's not possible to implement/extend `PreCompletionAwareAggregationStrategy`.

Update documentation for aggregation strategies in pre-completion mode

---

components/camel-jira/src/test/java/org/apache/camel/component/jira/producer/TransitionIssueProducerTest.java
parent/pom.xml

I believe this should be also in 3.4.x especially because of camel-k. Jira will be used as a quickstart for knative camel event sources and it'd be good to have it working also with JIRA-cloud.

CAMEL-15272 Bump version for jira-rest-client-api

---

docs/user-manual/modules/faq/pages/how-can-i-stop-a-route-from-a-route.adoc

This adds back in examples which were accidentally removed from the `docs/user-manual/modules/faq/pages/how-can-i-stop-a-route-from-a-route.adoc` page.

CAMEL-15271: Add examples back to "how to stop a route" docs

---

components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/MicrometerConstants.java
components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/eventnotifier/MicrometerExchangeEventNotifier.java
components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/eventnotifier/MicrometerExchangeEventNotifierNamingStrategy.java
components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/routepolicy/MicrometerRoutePolicy.java
components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/routepolicy/MicrometerRoutePolicyNamingStrategy.java
components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/eventNotifier/MicrometerExchangeEventNotifierTest.java
components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/routepolicy/ManagedMicrometerRoutePolicyTest.java
components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/routepolicy/MicrometerRoutePolicyExchangeStatusTest.java
components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/routepolicy/MicrometerRoutePolicyMulticastSubRouteTest.java
components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/routepolicy/MicrometerRoutePolicySubRouteTest.java

**Description**
The camel-micrometer component currently includes a `RoutePolicy`, `EventNotifier`s and a `MessageHistory`, which provides a set of metrics. This PR introduces some additional metrics, by expanding `MicrometerRoutePolicy` and `MicrometerExchangeEventNotifier`.
New metrics are:
- Total count of exchanges succeeded, per route
- Total count of exchanges failed, per route
- Current count of exchanges inflight, per route

[CAMEL-15255] Extend set of metrics provided by the camel-micrometer component

---

components/camel-slack/src/main/docs/slack-component.adoc

This note will help users configure the required permissions to access messages written in channels.

Note specifying the OAuth scope required to view messages in a channel

---

archetypes/camel-archetype-api-component/src/main/resources-filtered/META-INF/maven/archetype-metadata.xml
archetypes/camel-archetype-api-component/src/main/resources/archetype-resources/__artifactId__-component/pom.xml
archetypes/camel-archetype-api-component/src/main/resources/archetype-resources/__artifactId__-component/src/main/java/__name__Endpoint.java
archetypes/camel-archetype-api-component/src/main/resources/archetype-resources/__artifactId__-component/src/main/java/__name__Producer.java
archetypes/camel-archetype-api-component/src/main/resources/archetype-resources/__artifactId__-component/src/main/java/internal/__name__PropertiesHelper.java
archetypes/camel-archetype-component/src/main/resources-filtered/META-INF/maven/archetype-metadata.xml
archetypes/camel-archetype-component/src/main/resources/archetype-resources/pom.xml
archetypes/camel-archetype-dataformat/src/main/resources-filtered/META-INF/maven/archetype-metadata.xml
archetypes/camel-archetype-dataformat/src/main/resources/archetype-resources/pom.xml

This is related to CAMEL-15043
**camel-archetype-api-component**
- Add `camel-test-junit5` test dependency  to fix build failures
in generated test sources
- Remove deprecated `log4j.version` property (CAMEL-14317)
- The generated component was broken due to a missing argument in
constuctor of the PropertiesHelper class due to a change in the
ApiMethodPropertiesHelper parent class
**camel-archetype-component** and **camel-archetype-dataformat**
- Fix missing plugin version WARNING for `build-helper-maven-plugin`
by adding a new property `build-helper-maven-plugin-version`

Fix minor issues in camel maven archetypes

---

archetypes/camel-archetype-api-component/src/main/resources-filtered/META-INF/maven/archetype-metadata.xml
archetypes/camel-archetype-api-component/src/main/resources/archetype-resources/__artifactId__-component/pom.xml
archetypes/camel-archetype-component/src/main/resources-filtered/META-INF/maven/archetype-metadata.xml
archetypes/camel-archetype-component/src/main/resources/archetype-resources/pom.xml
archetypes/camel-archetype-dataformat/src/main/resources-filtered/META-INF/maven/archetype-metadata.xml
archetypes/camel-archetype-dataformat/src/main/resources/archetype-resources/pom.xml

This the same as #3995 but for the 3.4.x branch (relates to CAMEL-15043)
**camel-archetype-api-component**
- Add `camel-test-junit5` test dependency  to fix build failures in generated test sources
- Remove deprecated `log4j.version` property (CAMEL-14317)
**camel-archetype-component** and **camel-archetype-dataformat**
- Fix missing plugin version WARNING for `build-helper-maven-plugin`
by adding a new property `build-helper-maven-plugin-version`

Fix minor issues in camel maven archetypes in 3.4.x

---

core/camel-core-engine/src/main/java/org/apache/camel/model/TryDefinition.java

to get rid of "unchecked generics array creation for varargs parameter" compiler warning
[ ] Run `mvn clean install -Psourcecheck` in …

fix unchecked generic for varargs compiler warning

---

core/camel-core-engine/src/main/java/org/apache/camel/model/TryDefinition.java

* fix unchecked generic for varargs compiler warning
to get rid of "unchecked generics array creation for varargs parameter" compiler warning
* make SafeVarargs annotated method final
By requiring that the method is final, the developer can guarantee that the declaration he made (namely that its varargs use is safe) is actually always true (provided of course that the developer actually provided a safe varargs method), and that it wasn't actually broken by a subclass incorrectly re-implementing the method. …

fix unchecked generic for varargs compiler warning (#3997)

---

core/camel-api/src/main/java/org/apache/camel/AggregationStrategy.java

CAMEL-15244 AggregationStrategy - default timeout method should be empty

---

components/camel-zipkin/pom.xml
components/camel-zipkin/src/main/java/org/apache/camel/zipkin/CamelRequest.java
components/camel-zipkin/src/main/java/org/apache/camel/zipkin/ZipkinTracer.java
components/camel-zipkin/src/test/java/org/apache/camel/zipkin/CamelRequestTest.java
components/camel-zipkin/src/test/java/org/apache/camel/zipkin/ZipkinProducerSpanKindTest.java
components/camel-zipkin/src/test/java/org/apache/camel/zipkin/ZipkinTracerTest.java

setting span kind as producer/consumer depending on the type of component in the route. If the span kind if producer then this changes the tracing header being set to b3 single format. Original PR https://github.com/apache/camel/pull/4022

[CAMEL-15316] Fixes bug in camel zipkin trace headers, backporting pr#4022 to camel 3.4.x

---

core/camel-base/src/main/java/org/apache/camel/impl/engine/DefaultTracer.java

In order to make the default tracer fully customizable, method `dumpTrace` should be called from all places traces are written. This fixes the fact that `dumpTrace` was not being called from `traceBeforeRoute`.

CAMEL-15311: calling dumpTrace from traceBeforeRoute

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointDslMojo.java

Call setPublic on methods used for the static builders in StaticEndpointBuilders (camel-endpointdsl)
(backport of #4046)

[CAMEL-15314] Maven tooling: make dsl static builders public in EndpointDslMojo

---

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/streaming/SubscriptionHelper.java

removed hardcoded suffix for salesforce Platform Event Channel.
API names of standard platform events, such as AssetTokenEvent, don’t include a suffix. See https://developer.salesforce.com/docs/atlas.en-us.platform_events.meta/platform_events/platform_events_define_ui.htm
Hardcoding the suffix in channel name results in subscription failure for standard salesforce events.

CAMEL-15338 salesforce Standard Platform Events support

---

components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/OpenTelemetryTracer.java
components/camel-opentracing/pom.xml
components/camel-opentracing/src/main/java/org/apache/camel/opentracing/OpenTracingTracer.java
components/camel-opentracing/src/test/java/org/apache/camel/opentracing/CamelOpenTracingTestSupport.java
components/camel-opentracing/src/test/java/org/apache/camel/opentracing/EIPTracingActiveSpanTest.java
components/camel-opentracing/src/test/java/org/apache/camel/opentracing/OpentracingSpanCollectorInRegistryTest.java
components/camel-opentracing/src/test/java/org/apache/camel/opentracing/integration/InterprocessTest.java
components/camel-tracing/src/main/java/org/apache/camel/tracing/Tracer.java

This fixes a regression introduced with https://github.com/apache/camel/pull/4001 spotted by @valdar here https://github.com/apache/camel/pull/4001#issuecomment-662892861
This change makes the tracer fall back to camel's header extract adapter when a span is not found for the exchange. That's a span that would be there when utilizing instrumentation. So this would work with instrumentation, or without as it worked before the regression. It also introduces an integration test to prevent issues in the future.
@valdar let me know if this satisfies the issue for you and I'll mark the PR as ready.

CAMEL-15260 - opentracing: fixes header extraction regression

---

components/camel-xmpp/src/main/java/org/apache/camel/component/xmpp/XmppConsumer.java
components/camel-xmpp/src/main/java/org/apache/camel/component/xmpp/XmppEndpoint.java

Updated the XmppConsumer to "chatWith" the Participant instead of the ChatId. This solves an error when configuring a route to consume from a participant with a domain id and without a room defined the call to 'JidCreate.entityBareFrom(endpoint.getChatId())' would throw and exception because of the ill-formed JID returned by getChatId.
Added a function to XmppEndpoint to resolved the Fully qualified JID of the configured participant. This function when used by the XmppConsumer for direct chats will allow route participants to be defined without their domain and assume the domain of the server being connected too. This solves an error when configuring a route to consume from a participant without a domain id and without a room defined the call to …

Camel 15349

---

components/camel-xmpp/src/main/java/org/apache/camel/component/xmpp/XmppConsumer.java
components/camel-xmpp/src/main/java/org/apache/camel/component/xmpp/XmppEndpoint.java

* Added function to resolve fully qualified JID for participants
Changed the consumer to get the entityBareFrom the resolved participant
JID
* Fixed formatting issues outlined by sourcecheck
[ ] Write a pull request description that is detailed …

Backport Camel-15349

---

docs/components/modules/ROOT/pages/properties-component.adoc

Reused examples from `using-propertyplaceholder.adoc`.
[x] Trivial changes like typos do not require a JIRA issue.

Add missing examples to Properties component doc

---

components/camel-opentelemetry/src/main/docs/opentelemetry.adoc

Adding a little bit more documentation about opentelemetry.
For now there is no support for spring, so is not mentioned in the docs as an example of a way to initialize the tracer

[CAMEL-15359] opentelemetry docs

---

components/camel-flatpack/src/main/java/org/apache/camel/component/flatpack/FlatpackEndpoint.java

exchange.getIn().getMandatoryBody(Reader.class); was getting called twice in the case of DelimitedParser. And the BufferedReader is not getting closed the issue of this cause of file locking in the case of DelimitedParser.
[ ] Write a pull request …

CAMEL-15378: File gets locked When using camel-flatpack delimited parser

---

components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/OpenTelemetryTracer.java
components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/propagators/OpenTelemetryGetter.java

This fixes the injection/extraction logic of opentelemetry
The previous approach didn't work as it doesn't extract or inject the context.

[CAMEL-15382] Fix opentelemetry injection/extraction

---

core/camel-core/src/test/java/org/apache/camel/support/IntrospectionSupportTest.java
core/camel-core/src/test/java/org/apache/camel/support/PropertyBindingSupportArrayTest.java
core/camel-core/src/test/java/org/apache/camel/support/PropertyBindingSupportMapTest.java
core/camel-support/src/main/java/org/apache/camel/support/IntrospectionSupport.java
core/camel-support/src/main/java/org/apache/camel/support/PropertyBindingSupport.java
core/camel-support/src/main/java/org/apache/camel/support/PropertyConfigurerHelper.java

This PR adds support for arrays in PropertyBindingSupport and fix issues when binding to list when properties have gaps.
See tests in:
- PropertyBindingSupportArrayTest
- PropertyBindingSupportListTest
see:
- https://issues.apache.org/jira/browse/CAMEL-15396
- https://issues.apache.org/jira/browse/CAMEL-15397

Inprove PropertyBindingSupport

---

components/camel-platform-http/pom.xml
components/camel-platform-http/src/test/java/org/apache/camel/component/platform/http/JettyCustomPlatformHttpConsumer.java
components/camel-platform-http/src/test/java/org/apache/camel/component/platform/http/JettyCustomPlatformHttpEngine.java
components/camel-platform-http/src/test/java/org/apache/camel/component/platform/http/JettyServerTest.java
components/camel-platform-http/src/test/java/org/apache/camel/component/platform/http/PlatformHttpTest.java
components/camel-platform-http/src/test/resources/log4j2.properties

A test of platform-http using jetty server. For the test, I needed to create a custom Consumer.

CAMEL-14826: Add unit tests to the platform-http component

---

components/camel-cdi/src/main/docs/cdi.adoc

Changed API doc link to javadoc.io
Also updated the CDI doc link to version 2.0 (which is the version used by the component)

camel-cdi: Fix dead link in adoc

---

tests/camel-itest-jms2/src/test/java/org/apache/camel/itest/jms2/BaseJms2TestSupport.java

Replaced embedded deprecated JMS broker with EmbeddedActiveMQ since the embedded one is deprecated since Artemis 2.0.
Reference: https://activemq.apache.org/components/artemis/documentation/javadocs/javadoc-latest/

camel-itest-sjms2: fix deprecation warnings

---

components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/eventnotifier/MicrometerExchangeEventNotifier.java

**Description**
MicrometerExchangeEventNotifier indirectly caused NullPointer exceptions in some circumstances, though they are caught and logged as "WARN".
[A fix](https://github.com/apache/camel/commit/df0dfddeb205bf29a8148cb2862308f7a5b8a853#diff-4725dcf446a342f1473a8228e42dfa48) was implemented. Unfortunately, the fix is somewhat incompatible with prometheus, as it potentially tries to register multiple metrics with the same name but different tags, which prometheus doesn't allow.
This PR solves this by implementing a check so that we dont create inflight metrics unless we can extract fromEndpoint and fromRouteId from the ExchangeEvent.

CAMEL-15457: Ensure exchange has fromRouteId and fromEndpoint

---

components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpOperations.java

https://issues.apache.org/jira/browse/CAMEL-15460
Call of completePendingCommand() will read the Stream which potentially still contains a success message from the file retrieval. Afterwards the NOOP will be executed and the result (read from Stream) is interpreted correctly. Also respect the NOOP to return false instead of relying on exception.
Removed redundant reconnectIfNeccessary during rename(), as it will try to delete as first step during execution. The delete will ensure the connection is still alive.

CAMEL-15460: FTP reconnect to handle pending command and noop result

---

tests/camel-itest/src/test/java/org/apache/camel/itest/TransactionSupport.java
tests/camel-itest/src/test/java/org/apache/camel/itest/async/HttpJmsAsyncTimeoutTest.java
tests/camel-itest/src/test/java/org/apache/camel/itest/jetty/JettyJmsShutdownInProgressTest.java
tests/camel-itest/src/test/java/org/apache/camel/itest/jetty/JettySimulateFailoverRoundRobinTest.java
tests/camel-itest/src/test/java/org/apache/camel/itest/jms/JmsHttpPostIssueTest.java
tests/camel-itest/src/test/java/org/apache/camel/itest/sql/FromJmsToJdbcIdempotentConsumerToJmsTest.java
tests/camel-itest/src/test/java/org/apache/camel/itest/tx/JmsToHttpRoute.java
tests/camel-itest/src/test/java/org/apache/camel/itest/tx/JmsToHttpWithOnExceptionAndNoTransactionErrorHandlerConfiguredRoute.java
tests/camel-itest/src/test/java/org/apache/camel/itest/tx/JmsToHttpWithOnExceptionRoute.java
tests/camel-itest/src/test/java/org/apache/camel/itest/tx/JmsToHttpWithRollbackRoute.java

Includes:
- replaced deprecated usages of HttpOperationFailedException
- replaced usages of new Integer with Integer.valueOf
- stop using Exchange.ERRORHANDLER_HANDLED
- replaced usages of SpringRouteBuilder with RouteBuilder

camel-itest: fixed deprecation warnings

---

components/camel-sjms2/src/test/java/org/apache/camel/component/sjms2/support/Jms2TestSupport.java

Replaced embedded deprecated JMS broker with EmbeddedActiveMQ since the embedded one is deprecated since Artemis 2.0

camel-sjms2: fix deprecation warnings

---

components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxTasksManager.java

Calling the getID during log would throw a NPE

camel-box: fix a possible NPE when dereferencing BoxUser information

---

components/camel-cdi/src/main/java/org/apache/camel/cdi/CdiCamelExtension.java

This fixes a NPE that intermittently occurs in a TomEE 8 microprofile environment on container startup. I prepared a test case that reproduces the issue in a separate branch ([CAMEL-15493-Test](https://github.com/kentfung/camel/tree/CAMEL-15493-Test)) but decided not to include it in this PR as it introduces quite a few dependencies (although all test scoped).
-  [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.

CAMEL-15493 - Fixes NPE thrown in camel-cdi when attempting to inject an array property using Microprofile Config

---

components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/integration/RabbitMQInOutIntTest.java
components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/integration/RabbitMQLoadIntTest.java
components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/integration/RabbitMQReConnectionIntTest.java
components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/integration/RabbitMQRequeueHandledExceptionIntTest.java
components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/integration/RabbitMQRequeueIntTest.java
components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/integration/RabbitMQRequeueUnhandledExceptionIntTest.java

camel-rabbitmq: fixed deprecation warnings in test code

---

docs/components/modules/ROOT/pages/azure-storage-queue-component.adoc

1. Remove parameter accountName from query parameters
2. Add tip for use url encoding for accessKey because it can contain special chars like `=` or `+`. So `URLEncoder.encode` should solve this problem

Fix azure-storage-queue example

---

components/camel-rest-openapi/src/main/java/org/apache/camel/component/rest/openapi/RestOpenApiEndpoint.java

Since operationId is an optional parameter as defined by OpenApi 3 standard, I think that improving the component to be able to auto generate missing operationIds from operation path and http method would benefit users of camel-rest-openapi component.

CAMEL-15514: Add auto generation of operation IDs

---

components/camel-test-spring-junit5/src/main/java/org/apache/camel/test/spring/junit5/CamelSpringBootExecutionListener.java

CAMEL-15486 Move skipping of context start to method `beforeTestClass` to have the settings earlier in the test lifecycle.
Some other libraries (for example:  `spring-cloud-contract-wiremock` ) are starting up the context already in this phase of the test lifecycle and prevent camel of setting up the mocking of endpoints.

CAMEL-15486 Move skipping of context start to method `beforeTestClass`

---

components/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Consumer.java

fix getDestinationBucketSuffix() empty check
currently when using `destinationBucketPrefix` only a `null` suffix will be appended to the s3 file after moved.

Fixes small bug in camel-aws2-s3 component in destinationBucketSuffix configuration attribute

---

.github/workflows/master-pr-build.yml
.github/workflows/master-push-build.yml

If this step fails, it is currently missing information about the reason. Switched to my fork of has-changes-action temporarilly until https://github.com/UnicornGlobal/has-changes-action/pull/2 gets merged. 
Sample output - https://github.com/bedlaj/camel/runs/1134623405 :
```
Maven build will override some files, which are not commited as part of this PR. Please run maven build and commit generated sources.
M catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/box-component.adoc
M catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/twilio-component.adoc
M catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/others/microprofile-fault-tolerance.json
M components/camel-box/camel-box-component/src/generated/resources/org/apache …
```

CAMEL-15552: Print dirty files in workflow step

---

.github/workflows/master-push-build.yml

Result can be seen here https://github.com/bedlaj/test-github-bot/pull/3
Please do not delete branch `regen_bot`. Github forbids modifying workflow from github action authenticated by `GITHUB_TOKEN`, so it would fail. If this will be limiting, we would need to create personal access token secret - probably with INFRA, or can we do this for repo?
[ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] …

CAMEL-15556: Create automated PR for regen

---

core/camel-core/src/test/java/org/apache/camel/processor/MulticastParallelTimeoutStreamCachingTest.java
core/camel-support/src/main/java/org/apache/camel/converter/stream/FileInputStreamCache.java

If you have a route with a Multicast with parallel processing and a
timeout and a sub-route in the multicast which is creating an
OutputStreamCache before the timeout and is writing to the
OutputStreamCache after the timeout then the created file is never
deleted from the file system.
[ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace …

CAMEL-15557: Stream Cache file not deleted

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/constant-language.adoc
catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/exchangeProperty-language.adoc
catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/file-language.adoc
catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/header-language.adoc
catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/ref-language.adoc
catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/simple-language.adoc
catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/tokenize-language.adoc
catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/xtokenize-language.adoc
core/camel-core-languages/src/main/docs/modules/languages/pages/constant-language.adoc
core/camel-core-languages/src/main/docs/modules/languages/pages/exchangeProperty-language.adoc
core/camel-core-languages/src/main/docs/modules/languages/pages/file-language.adoc
core/camel-core-languages/src/main/docs/modules/languages/pages/header-language.adoc
core/camel-core-languages/src/main/docs/modules/languages/pages/ref-language.adoc
core/camel-core-languages/src/main/docs/modules/languages/pages/simple-language.adoc
core/camel-core-languages/src/main/docs/modules/languages/pages/tokenize-language.adoc
core/camel-xml-jaxp/src/main/docs/modules/languages/pages/xtokenize-language.adoc

This reverts 66ac2609171cf581b5fadee5a64003eaa5e6f870 and
24c6e0e7f08cccb56f7a9fa25f5219d930f83aa8 except for the antora.yml
files. The problem of duplicate Antora resources the two commits
attempted to solve, is solvable by removing the antora.yml files which
this commit effectively does. We keep the adoc files which are still
important.

Restore core languages .adoc files

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/string-template-component.adoc
components/camel-stringtemplate/src/main/docs/string-template-component.adoc
components/camel-stringtemplate/src/main/java/org/apache/camel/component/stringtemplate/StringTemplateConstants.java
components/camel-stringtemplate/src/main/java/org/apache/camel/component/stringtemplate/StringTemplateEndpoint.java
components/camel-stringtemplate/src/test/java/org/apache/camel/component/stringtemplate/StringTemplateViaHeaderTest.java
docs/components/modules/ROOT/pages/string-template-component.adoc

Issue: https://issues.apache.org/jira/browse/CAMEL-15577
Allowing of template via header (based on approach used in velocity component)

CAMEL-15577 Camel-stringtemplate: Misleading and incorrect implementation of parameter 'allowTemplateFromHeader'

---

components/camel-attachments/src/main/java/org/apache/camel/attachment/CamelFileDataSource.java
components/camel-http-common/src/main/java/org/apache/camel/http/common/DefaultHttpBinding.java
components/camel-platform-http-vertx/pom.xml
components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpConsumer.java
components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpEngine.java
components/camel-platform-http-vertx/src/test/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpEngineTest.java
docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_6.adoc

Note: I moved `CamelFileDataSource` out of `camel-http-common` and into `camel-attachments`, as it's a bit friendlier for camel-quarkus to not have to deal with `servlet-api` and other stuff that `camel-http-common` depends on.

CAMEL-15608: Add support for multipart uploads to platform-http-vertx

---

components/camel-consul/src/main/java/org/apache/camel/component/consul/cluster/ConsulClusterView.java
components/camel-cxf/src/main/java/org/apache/camel/component/cxf/CxfEndpoint.java
components/camel-disruptor/src/main/java/org/apache/camel/component/disruptor/MultipleConsumerSynchronizedExchange.java
components/camel-etcd/src/main/java/org/apache/camel/component/etcd/policy/EtcdRoutePolicy.java
components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/policy/HazelcastRoutePolicy.java
components/camel-hdfs/src/main/java/org/apache/camel/component/hdfs/HdfsOutputStream.java
components/camel-hdfs/src/main/java/org/apache/camel/component/hdfs/HdfsProducer.java
components/camel-infinispan/src/main/java/org/apache/camel/component/infinispan/policy/InfinispanRoutePolicy.java
components/camel-jira/src/main/java/org/apache/camel/component/jira/consumer/WatchUpdatesConsumer.java
components/camel-jms/src/main/java/org/apache/camel/component/jms/JmsProducer.java
components/camel-jms/src/main/java/org/apache/camel/component/jms/reply/TemporaryQueueReplyManager.java
components/camel-quartz/src/main/java/org/apache/camel/component/quartz/QuartzEndpoint.java
components/camel-quickfix/src/main/java/org/apache/camel/component/quickfixj/QuickfixjEngine.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQProducer.java
components/camel-reactive-streams/src/main/java/org/apache/camel/component/reactive/streams/engine/DelayedMonoPublisher.java
components/camel-saxon/src/main/java/org/apache/camel/component/xquery/XQueryBuilder.java
components/camel-sjms/src/main/java/org/apache/camel/component/sjms/batch/SjmsBatchConsumer.java
core/camel-base/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java
core/camel-base/src/main/java/org/apache/camel/impl/engine/DefaultSupervisingRouteController.java
core/camel-base/src/main/java/org/apache/camel/impl/engine/RouteService.java
core/camel-base/src/main/java/org/apache/camel/throttling/ThrottlingExceptionRoutePolicy.java
core/camel-cluster/src/main/java/org/apache/camel/impl/cluster/ClusteredRoutePolicy.java
core/camel-core-engine/src/main/java/org/apache/camel/builder/RouteBuilder.java
core/camel-core-engine/src/main/java/org/apache/camel/model/RouteDefinition.java
core/camel-core-languages/src/main/java/org/apache/camel/language/simple/SimplePredicateParser.java
core/camel-main/src/main/java/org/apache/camel/main/SimpleMainShutdownStrategy.java

The constructor new AtomicBoolean(false) causes a volatile write that can be saved as the constructor parameter is the default value.
This saves a volatile write but makes the code (a bit) less readable. Not sure if this is worth it.

Avoid explicit initialization of AtomicBoolean with its default value

---

components/camel-wordpress/src/generated/java/org/apache/camel/component/wordpress/WordpressComponentConfigurer.java
components/camel-wordpress/src/main/docs/wordpress-component.adoc
components/camel-wordpress/src/main/java/org/apache/camel/component/wordpress/WordpressComponent.java
components/camel-wordpress/src/main/java/org/apache/camel/component/wordpress/WordpressConfiguration.java
components/camel-wordpress/src/main/java/org/apache/camel/component/wordpress/WordpressEndpoint.java
components/camel-wordpress/src/main/java/org/apache/camel/component/wordpress/consumer/AbstractWordpressConsumer.java
components/camel-wordpress/src/main/java/org/apache/camel/component/wordpress/producer/AbstractWordpressProducer.java
components/camel-wordpress/src/test/java/org/apache/camel/component/wordpress/WordpressPostOperationTest.java
components/camel-wordpress/src/test/java/org/apache/camel/component/wordpress/WordpressUserOperationTest.java

Refactoring WordpressComponentConfiguration.java to WordpressConfiguration.java
This name is conflicted with auto generated camel-wordpress-starter
component configuration. By current document,
WordpressConfiguration should be correct name and it resolves the
conflicting issue on starter module. I updated doc accordingly.

CAMEL-15624 : Refactoring camel-wordpress Configuration class name to avoid conflict with camel-workpress-starter Configuration

---

test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/services/kafka/StrimziContainer.java
test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/services/kafka/StrimziService.java
test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/services/kafka/ZookeeperContainer.java

This works around sporadic errors raised by docker during the tear
up/down cycle of the tests. This seems to happen because, although the
containers are reportedly terminated, some of their resources may still
be utilized at the time of the start of the new test.
This is likely a problem elsewhere, but this patch adds a work-around
for this.
---
Obs.: it sourcecheck seems to complain about StrimziService class formatting without giving much details about the failure. I tried reformating it several times without success. I am trying a PR in the hope it is a problem w/ the check and not w/ the file formatting itself.

Throttles strimzi startup to prevent resource reuse errors

---

components/camel-shiro/src/main/java/org/apache/camel/component/shiro/security/ShiroSecurityHelper.java
components/camel-shiro/src/main/java/org/apache/camel/component/shiro/security/ShiroSecurityProcessor.java
components/camel-shiro/src/main/java/org/apache/camel/component/shiro/security/ShiroSecurityTokenInjector.java
components/camel-shiro/src/test/java/org/apache/camel/component/shiro/security/ShiroSecurityHelperTest.java

Issue: https://issues.apache.org/jira/browse/CAMEL-15619
I'm replacing serialization of `ShiroSecurityToken` with custom written serialization. (without `ObjectOutputStream.writeObject()`).
This change allows creation of camel-quarkus extension for this component (because serialization is not possible in native, see https://github.com/oracle/graal/issues/460)

CAMEL-15619 camel-shiro: allow custom implementation of serialization

---

camel-dependencies/pom.xml
components/camel-google-pubsub/pom.xml
components/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubComponent.java
components/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubConstants.java
components/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubProducer.java
components/camel-google-pubsub/src/test/java/org/apache/camel/component/google/pubsub/PubsubTestSupport.java
components/camel-google-pubsub/src/test/java/org/apache/camel/component/google/pubsub/integration/DeadLetterTest.java
parent/pom.xml

When Camel receives a PubSub message with reserved Google PubSub attributes these are set on a Camel header and passed on to any message sender. These reserved attributes are not allowed to be set on an outgoing message so this throws an error.
This filters out these reserved attributes before sending.
https://issues.apache.org/jira/browse/CAMEL-15617

CAMEL-15617: Fix filter Google PubSub reserved attributes

---

components/camel-kafka/pom.xml
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/BaseEmbeddedKafkaTest.java
test-infra/camel-test-infra-kafka/pom.xml
test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/services/kafka/KafkaServiceFactory.java

Switches to the infra provided by camel-test-infra-kafka instead of
directly using the KafkaContainer.
This removes the need of camel-testcontainers-junit5 and allows
targetting remote kafka instances as part of the test execution.

Replaces the kafka container in camel-kafka test

---

components/camel-mail/src/main/docs/mail-component.adoc
docs/components/modules/ROOT/pages/mail-component.adoc

Update documentation for camel 3.x related to attachments as there is no exchange.getIn().getAttachments() method anymore.
Fix for the Issue [CAMEL-15484](https://issues.apache.org/jira/browse/CAMEL-15484?filter=12348073)

CAMEL-15484 - UPDATE Documentation for Camel 3.x

---

components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitConsumer.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQConsumer.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQMessageConverter.java
components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/RabbitMQProducerTest.java

Hi,
We met a condition in production where the Connection Factory of Rabbitmq won't recover (when isAutomaticRecoveryEnabled is set to true). It's easily reproducible by calling the ".close()" method on it. 
It's explained here : https://www.rabbitmq.com/api-guide.html#recovery
The current code would always returns the same connection, not re-establishing it, if isAutomaticRecoveryEnabled is enabled.
Our solution, based on the fact we just have "isOpen" to check the state of the channel/connection was to re-establish the connection in the RabbitMQConsumer even if "isAutomaticRecoveryEnabled" is enabled.
What's your thought about it ?

AutomaticRecovery from RabbitMQ Connection Factory doesn't recover from everything

---

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/AS2ServerManager.java
components/camel-aws-swf/src/main/java/org/apache/camel/component/aws/swf/SWFActivityConsumer.java
components/camel-aws-swf/src/main/java/org/apache/camel/component/aws/swf/SWFActivityProducer.java
components/camel-aws-swf/src/main/java/org/apache/camel/component/aws/swf/SWFWorkflowConsumer.java
components/camel-aws-swf/src/main/java/org/apache/camel/component/aws/swf/SWFWorkflowProducer.java
components/camel-bean/src/main/java/org/apache/camel/component/bean/DefaultBeanProcessorFactory.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxCollaborationsManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxCommentsManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxEventLogsManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxEventsManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxFilesManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxFoldersManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxGroupsManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxTasksManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxUsersManager.java

- Fixed typos
- Removed unecessary concatenations
Modules: camel-as2, camel-aws-swf, camel-bean, camel-box

(chore) Cleaned up log messages

---

camel-dependencies/pom.xml
components/camel-djl/src/test/java/org/apache/camel/component/djl/training/MnistTraining.java
parent/pom.xml

Implementation of https://issues.apache.org/jira/browse/CAMEL-15687
Upgrade Deep Java Library to the latest version (0.8.0)

CAMEL-15687: Upgrade to Deep Java Library 0.8.0

---

components/camel-aws-sqs/README.md
components/camel-aws-sqs/pom.xml
components/camel-aws-sqs/src/test/java/org/apache/camel/component/aws/sqs/integration/SqsComponentIntegrationTest.java
components/camel-aws-sqs/src/test/java/org/apache/camel/component/aws/sqs/integration/SqsConsumerMessageIntegrationTest.java
components/camel-aws-sqs/src/test/java/org/apache/camel/component/aws/sqs/integration/SqsProducerBatchSendFifoIntegrationTest.java
components/camel-aws-sqs/src/test/java/org/apache/camel/component/aws/sqs/integration/SqsProducerBatchSendIntegrationTest.java
components/camel-aws-sqs/src/test/java/org/apache/camel/component/aws/sqs/integration/SqsProducerDeleteMessageIntegrationTest.java
components/camel-aws-sqs/src/test/java/org/apache/camel/component/aws/sqs/integration/TestSqsConfiguration.java
test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/clients/AWSClientUtils.java
test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/common/SystemPropertiesAWSCredentialsProvider.java
test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/common/TestAWSCredentials.java
test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/common/TestAWSCredentialsProvider.java
test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSLocalContainerService.java
test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSRemoteService.java
test-infra/camel-test-infra-common/src/test/java/org/apache/camel/test/infra/common/SharedNameGenerator.java
test-infra/camel-test-infra-common/src/test/java/org/apache/camel/test/infra/common/SharedNameRegistry.java
test-infra/camel-test-infra-common/src/test/java/org/apache/camel/test/infra/common/TestEntityNameGenerator.java

Migrates the camel-aws-sqs integration tests to the shared test infra

---

docs/user-manual/modules/faq/pages/how-do-i-configure-endpoints.adoc

Escape ampersand twice so that it is displayed as &amp;amp; in the browser

Update how-do-i-configure-endpoints.adoc to display ampersand correctly

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/azure-storage-blob-component.adoc
components/camel-azure-storage-blob/pom.xml
components/camel-azure-storage-blob/src/main/docs/azure-storage-blob-component.adoc
components/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/BlobTestUtils.java
components/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BaseIT.java
components/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BlobConsumerITTest.java
components/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BlobContainerOperationsITTest.java
components/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BlobOperationsITTest.java
components/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BlobProducerITTest.java
components/camel-azure-storage-blob/src/test/resources/azurite.properties
docs/components/modules/ROOT/pages/azure-storage-blob-component.adoc

Integration tests now run by default using Azurite.
There is a bug at integration test, that was introduced recently #4480
Disabled that integration test. Created a ticket CAMEL-15747.

CAMEL-15661: use Testcontainers and Azurite at integration tests

---

components/camel-paho/src/main/java/org/apache/camel/component/paho/PahoConsumer.java
components/camel-paho/src/main/java/org/apache/camel/component/paho/PahoProducer.java
components/camel-paho/src/test/java/org/apache/camel/component/paho/PahoReconnectAfterFailureTest.java

When restarting a route with a paho consumer or using a paho producer
after a connection failure to the broker the mqtt client was not
reconnected. This patch sets consumer and producer internl mqtt  client
instance to null os stop, so that a restart will create a new instance
and connect to the broker again.

[CAMEL-15748] nullify mqtt client on producer and consumer stop

---

components/camel-lumberjack/src/main/java/org/apache/camel/component/lumberjack/io/LumberjackSessionHandler.java
components/camel-lumberjack/src/test/java/org/apache/camel/component/lumberjack/LumberjackComponentGlobalSSLTest.java
components/camel-lumberjack/src/test/java/org/apache/camel/component/lumberjack/LumberjackComponentSSLTest.java
components/camel-lumberjack/src/test/java/org/apache/camel/component/lumberjack/LumberjackDisconnectionTest.java
components/camel-lumberjack/src/test/java/org/apache/camel/component/lumberjack/LumberjackMultiThreadTest.java
components/camel-lumberjack/src/test/java/org/apache/camel/component/lumberjack/LumberjackUtil.java
components/camel-lumberjack/src/test/java/org/apache/camel/component/lumberjack/io/LumberjackChannelInitializerTest.java

PR to resolve the problem of wrong ACKs or incomplete while processing multiple parallel windows within the same session. 
Each channel/session is thread safe in Netty. However, while using lumberjack component, one single session can process multiple windows in parallel, and that causes mess while updating session data.
My solution to that : for each Lumberjack session, a new window to process has to wait the ACK sent from the previous one, if exists. In that way, we can assure that session data are not changed by another process.

CAMEL-15718: Camel lumberjack server component not thread safe

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/mllp-component.adoc
components/camel-mllp/src/main/docs/mllp-component.adoc
components/camel-mllp/src/main/java/org/apache/camel/component/mllp/MllpTcpClientProducer.java
components/camel-mllp/src/main/java/org/apache/camel/component/mllp/MllpTcpServerConsumer.java
components/camel-mllp/src/test/java/org/apache/camel/component/mllp/MllpProducerConsumerLoopbackInOnlyTest.java
components/camel-mllp/src/test/java/org/apache/camel/component/mllp/MllpTcpServerConsumerManualAcknowledgementWithBridgeErrorHandlerInOnlyTest.java
components/camel-mllp/src/test/java/org/apache/camel/component/mllp/TcpServerConsumerAcknowledgementTestSupport.java
docs/components/modules/ROOT/pages/mllp-component.adoc

This change allows sending and receiving HL7 messages using MLLP without waiting or sending back any acknowledgment. This is possible when autoAck=false and exchangePattern=InOnly.

CAMEL-15731: Add support for InOnly exchange pattern to camel-mllp

---

components/camel-cxf/src/main/java/org/apache/camel/component/cxf/common/AbstractSslEndpointConfigurer.java
components/camel-cxf/src/main/java/org/apache/camel/component/cxf/jaxrs/CxfRsEndpoint.java

Create the configured SSLSocketFactory once  and cache it in the endpoint instead of recreating it on every request.

CAMEL-15794: don't recreate SSL socket factory for every invocation

---

components/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Consumer.java

covers cases where the s3Object contentType is coming from s3 as "application/x-directory; charset=UTF-8"

[CAMEL-15797] Update isIncludeFolders check in AWS2S3Consumer to cover folders with charset

---

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultConfigurerResolver.java
core/camel-core/src/test/java/org/apache/camel/impl/engine/DefaultConfigurerResolverTest.java

DefaultConfigurerResolver fallbacks to ExtendedCamelContext FQCN
for names containing "CamelContext".
This change restricts fallback mechanims checking also that name
starts with "org.apache.camel".

[CAMEL-15801] Restrict DefaultConfigurerResolver fallback resolution

---

catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/RouteCoverageMojo.java

Launching route-coverage goal from root directory of a multi module
project does not work because the directory passed to
RouteCoverageHelper.parseDumpRouteCoverageByRouteId
missed project base directory.
This change adds project base directory to the relative path
of route coverage data.

[CAMEL-15805] Prefix coverage directory with project base dir

---

core/camel-support/src/main/java/org/apache/camel/support/builder/PredicateBuilder.java

Used expressions/predicates should be initialized.

CAMEL-15809: properly initialize compound predicates

---

components/camel-jsonpath/src/main/docs/jsonpath-language.adoc
docs/components/modules/languages/pages/jsonpath-language.adoc

typo error, should be expressions instead of exceptions

Update typo in jsonpath language documentation

---

components/camel-jsonpath/src/test/java/org/apache/camel/jsonpath/JsonPathSplitTest.java

This PR addresses a request in CAMEL-15769 to add test cases within camel-jsonpath for the new 'false' split delimiter.
https://issues.apache.org/jira/browse/CAMEL-15769?focusedCommentId=17230827&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17230827
I appended test cases to an existing test file, but I'd be happy to break them out into a separate test file if that's preferred.
Thanks

CAMEL-15769: add camel-jsonpath tests for new 'false' tokenizer

---

components/camel-salesforce/camel-salesforce-maven-plugin/src/main/java/org/apache/camel/maven/GenerateMojo.java

If the user is only using strings for picklist values, don't generate
java enum files.

CAMEL-15859: camel-salesforce: Don't generate unnecessary enums

---

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/SalesforceEndpointConfig.java
docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_7.adoc

Current default is 34, which is ancient and causes issues that either don't have a good error message, or the underlying error message from salesforce never makes it to the user.

camel-salesforce: Change default API version to 50.

---

components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpOperations.java

Set the FTPClient default socket timeout to allow it to, in turn, set a socket timeout before starting the implicit TLS handshake which can currently hang permanently.
Related commons-net fix: https://github.com/apache/commons-net/pull/70
This solves a problem where our routes hang permanently because an FTPS provider intermittently hangs during the TLS handshake, and no socket timeout is set yet.
Let me know if this needs a Jira ticket. :)

Set FTPClient default socket timeout to avoid permanent hang during implicit TLS handshake

---

components/camel-ahc/src/main/java/org/apache/camel/component/ahc/DefaultAhcBinding.java

The issue is due to a mistake done by async-http-client team.
Commit : https://github.com/AsyncHttpClient/async-http-client/commit/d47c56e7ee80b76a4cffd4770237239cfea0ffd6#diff-5247ce5d437efdde629533d6239bf0c24358bdf0157fa204050e908c48a8c1f3
They made the ByteArrayBodyGenerator constructor package level.
Due to this change, camel had to adapt and for String type of body, they changed their implementation from ByteArrayBodyGenerator to InputStreamBodyGenerator.
In InputStreamBodyGenerator, the content length is by default set to -1.
Since, content length was less than 0, NettyRequestFactory in async-http-client was using Transfer-Encoding header instead of Content-Length header.
Solution :
Async-http-client team corrected their mistake in the following commit : …

[CAMEL-15891]ByteArrayBodyGenerator for String body

---

docs/user-manual/modules/ROOT/pages/json.adoc

According to source the default is actually Jackson, not XStream. I confirmed this by debugging a route that included `.unmarshal().json()`.
The default is set in JsonDataFormat.java

Fixes incorrect mention of default JsonLibrary in documentation

---

components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/list/HazelcastListConsumer.java
components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/map/HazelcastMapConsumer.java
components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/multimap/HazelcastMultimapConsumer.java
components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/replicatedmap/HazelcastReplicatedmapConsumer.java
components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/set/HazelcastSetConsumer.java
components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/topic/HazelcastTopicConsumer.java

The following exception occurs if the camelroute with a hazel cast topic is restarted  
```
WARNUNG: Error processing exchange for hazelcast consumer on object 'null' in cache 'server.trace.event'.. Exchange[ID-1605875260724-0-338]. Caused by: [java.util.concurrent.RejectedExecutionException - null]
java.util.concurrent.RejectedExecutionException
at org.apache.camel.processor.RedeliveryErrorHandler.process(RedeliveryErrorHandler.java:435)
at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
at org.apache.camel.processor.CamelInternalProcessor.process(CamelInternalProcessor.java:201)
at org.apache.camel.processor.DelegateAsyncProcessor.process(DelegateAsyncProcessor.java:97)
at org.apache.camel.component.hazelcast.listener.CamelListener.sendExchange( …
```

[CAMEL-15899] Hazelcast consumer listeners not removed after use

---

docs/user-manual/modules/ROOT/pages/camel-3-migration-guide.adoc

Fixed typo in camel-3-migration-guide. Changed `JndiRegisty` to `JndiRegistry`.

Fixed minor typo

---

components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarConsumerReadCompactedTest.java

It seems a bit hard to spot this one unless compaction is slow. In such case, it could throw a "Compaction already in progress" exception.
This change ensures it does wait for the compaction to finish.

Fix not waiting for the compaction completeness on Pulsar tests

---

components/camel-openapi-java/src/main/java/org/apache/camel/openapi/RestModelConverters.java
components/camel-openapi-java/src/main/java/org/apache/camel/openapi/RestOpenApiReader.java
components/camel-openapi-java/src/test/java/org/apache/camel/openapi/RestOpenApiReaderFileResponseModelTest.java
components/camel-swagger-java/src/main/java/org/apache/camel/swagger/RestSwaggerReader.java
components/camel-swagger-java/src/test/java/org/apache/camel/swagger/RestSwaggerReaderFileResponseModelTest.java

Fixes CAMEL-15919 by setting schema type to 'file' if responseMessage class is 'java.io.File'.

CAMEL-15919: map java.io.File to swagger response schema type 'file'

---

components/camel-opentracing/src/main/docs/opentracing.adoc
components/camel-opentracing/src/main/java/org/apache/camel/opentracing/OpenTracingSpanAdapter.java
components/camel-opentracing/src/main/java/org/apache/camel/opentracing/OpenTracingTracer.java
components/camel-opentracing/src/main/java/org/apache/camel/opentracing/OpenTracingTracingStrategy.java
components/camel-opentracing/src/test/java/org/apache/camel/opentracing/ThirdPartyInstrumentationIntegrationTest.java

In order to enable extending camel-created spans in processors, PR https://github.com/apache/camel/pull/4497 introduced functionality that was already present through a configurable `InterceptStrategy` though it was undocumented (my fault).This PR takes care of reverting those changes and adds documentation, while preserving the added test in order to prove the functionality is the same.
@orange-buffalo please take a look. You'll notice that the only modification to the test is that now we have one extra span for each route execution, this is the span for the single processor in the route.
@oscerd I know you guys are preparing the 3.7 release, I'm hoping we can squeeze in this fix.

revert CAMEL-15710

---

components/camel-spring/src/test/resources/org/apache/camel/component/properties/CamelSpringPropertyPlaceholderConfigurerTest.xml
core/camel-base/src/main/docs/properties-component.adoc

Re-adds missing bean configuration examples for spring to camel properties bridge.
I did not run `mvn clean install -Psourcecheck` as it fails on OSX with
```
[ERROR] Unrecognized VM option 'ExitOnOutOfMemoryError'
[ERROR] Did you mean 'OnOutOfMemoryError=<value>'?
[ERROR] Error: Could not create the Java Virtual Machine.
[ERROR] Error: A fatal exception has occurred. Program will exit.
``` 
The [working example page](https://camel.apache.org/manual/latest/using-propertyplaceholder.html#UsingPropertyPlaceholder-BridgingSpringandCamelPropertyPlaceholders-1) actually embeds the snippet, which seems like more prone to becoming out of date. 
But I did not verify that the tags work in XML on the website as building the camel website fails on OSX.
```
➤ YN0000: [17:18:49] Starting 'build'...
➤ …
```

[CAMEL-15935] Update Properties docs (Spring -> Camel bridge examples)

---

core/camel-main/src/main/java/org/apache/camel/main/SimpleMain.java

SimpleMain is used in CamelKafkaConnector and this oversight could cause problems in case we decide to implement doStop or doStart in BaseMainSupport.

Fix SimpleMain oversight on doStop method (master)

---

components/camel-google-calendar/src/main/java/org/apache/camel/component/google/calendar/stream/GoogleCalendarStreamConsumer.java

Added a simple null check to prevent `NullPointerException` in case event update datetime is missing. 
```
[2020-12-09 11:14:19,110] WARN Consumer Consumer[google-calendar-stream://gcalstream?accessToken=xxxxxx] failed polling endpoint: google-calendar-stream://gcalstream?accessToken=xxxxxx. Will try again at next poll. Caused by: [java.lang.NullPointerException - null] (org.apache.camel.component.google.calendar.stream.GoogleCalendarStreamConsumer)
java.lang.NullPointerException
at org.apache.camel.component.google.calendar.stream.GoogleCalendarStreamConsumer.poll(GoogleCalendarStreamConsumer.java:91)
at org.apache.camel.support.ScheduledPollConsumer.doRun(ScheduledPollConsumer.java:190)
at org.apache.camel.support.ScheduledPollConsumer.run(ScheduledPollConsumer.java:107)
at …
```

Avoid NPE on missing event update datetime [google-calendar-stream]

---

components/camel-google-calendar/src/main/java/org/apache/camel/component/google/calendar/stream/GoogleCalendarStreamConsumer.java

Backport: avoid NPE on missing event update datetime

---

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/streaming/SubscriptionHelper.java
components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/internal/streaming/StubServer.java
components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/internal/streaming/SubscriptionHelperIntegrationTest.java

Adds a stub server implemented in Jetty, as it is already pulled in as a
dependency, and a integration test for the testing streaming resiliency.
Two cases are added in the integration test: server closing the
TCP connection (e.g. in a abrupt server shutdown), and restarting the
`SubscriptionHelper` service (e.g. when route is restarted).
When SubscriptionHelper is stopped we need to remove all listeners and
close channels this helper is listening on.
If we can't connect and perform the handshake, disconnecting will
trigger client restart with back-off. Also when restarting as the signal
to restart can occur on multiple threads we need to guard against
restart happening in parallel.

CAMEL-12871: Salesforce streaming reliability

---

docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_7.adoc

Plus sign is rendering to nothing. I don't know much about asciidoc. Will this work?

Escape plus sign in 3.7 upgrade guide.

---

core/camel-util/src/main/java/org/apache/camel/util/URISupport.java

[JIRA issue]https://issues.apache.org/jira/browse/CAMEL-15983
Did not set prev with key after compareTo, and prev value is always the first item of parameter.keySet(), if keyset like this: a, c, b, and the value of sort after for loop is false, but its shoud be true.

[CAMEL-15983] Fixes bug in camel-util URISupport

---

components/camel-resilience4j/src/main/java/org/apache/camel/component/resilience4j/ResilienceProcessor.java
components/camel-resilience4j/src/test/java/org/apache/camel/component/resilience4j/ResilienceExistingCircuitBreakerTest.java
components/camel-resilience4j/src/test/java/org/apache/camel/component/resilience4j/ResilienceInheritErrorHandlerTest.java
components/camel-resilience4j/src/test/java/org/apache/camel/component/resilience4j/ResilienceManagementTest.java
components/camel-resilience4j/src/test/java/org/apache/camel/component/resilience4j/ResilienceRouteBulkheadFallbackTest.java
components/camel-resilience4j/src/test/java/org/apache/camel/component/resilience4j/ResilienceRouteBulkheadOkTest.java
components/camel-resilience4j/src/test/java/org/apache/camel/component/resilience4j/ResilienceRouteFallbackTest.java
components/camel-resilience4j/src/test/java/org/apache/camel/component/resilience4j/ResilienceRouteOkTest.java
components/camel-resilience4j/src/test/java/org/apache/camel/component/resilience4j/ResilienceRouteRejectedTest.java
components/camel-resilience4j/src/test/java/org/apache/camel/component/resilience4j/SpringResilienceRouteFallbackTest.java
components/camel-resilience4j/src/test/java/org/apache/camel/component/resilience4j/SpringResilienceRouteOkTest.java
components/camel-resilience4j/src/test/resources/org/apache/camel/component/resilience4j/SpringResilienceRouteFallbackTest.xml
components/camel-resilience4j/src/test/resources/org/apache/camel/component/resilience4j/SpringResilienceRouteOkTest.xml

Fix not invoking fallback for resilience4j circuit breaker and not triggering circuit breaker for timeout exceptions
Detailed explanation of fix and test cases can be found in ticket itself - https://issues.apache.org/jira/browse/CAMEL-15928
You can start reading from - https://issues.apache.org/jira/browse/CAMEL-15928?focusedCommentId=17251773&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17251773

CAMEL-15928: TimeoutException does not trigger Resilience4j circuit

---

components/camel-resilience4j/src/main/java/org/apache/camel/component/resilience4j/ResilienceProcessor.java
components/camel-resilience4j/src/test/java/org/apache/camel/component/resilience4j/ResilienceExistingCircuitBreakerTest.java
components/camel-resilience4j/src/test/java/org/apache/camel/component/resilience4j/ResilienceInheritErrorHandlerTest.java
components/camel-resilience4j/src/test/java/org/apache/camel/component/resilience4j/ResilienceManagementTest.java
components/camel-resilience4j/src/test/java/org/apache/camel/component/resilience4j/ResilienceRouteBulkheadFallbackTest.java
components/camel-resilience4j/src/test/java/org/apache/camel/component/resilience4j/ResilienceRouteBulkheadOkTest.java
components/camel-resilience4j/src/test/java/org/apache/camel/component/resilience4j/ResilienceRouteFallbackTest.java
components/camel-resilience4j/src/test/java/org/apache/camel/component/resilience4j/ResilienceRouteOkTest.java
components/camel-resilience4j/src/test/java/org/apache/camel/component/resilience4j/ResilienceRouteRejectedTest.java
components/camel-resilience4j/src/test/java/org/apache/camel/component/resilience4j/SpringResilienceRouteFallbackTest.java
components/camel-resilience4j/src/test/java/org/apache/camel/component/resilience4j/SpringResilienceRouteOkTest.java
components/camel-resilience4j/src/test/resources/org/apache/camel/component/resilience4j/SpringResilienceRouteFallbackTest.xml
components/camel-resilience4j/src/test/resources/org/apache/camel/component/resilience4j/SpringResilienceRouteOkTest.xml

Fix not invoking fallback for resilience4j circuit breaker and not triggering circuit breaker for timeout exceptions
Detailed explanation of fix and test cases can be found in ticket itself - https://issues.apache.org/jira/browse/CAMEL-15928
You can start reading from - https://issues.apache.org/jira/browse/CAMEL-15928?focusedCommentId=17251773&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17251773

CAMEL-15928: TimeoutException does not trigger Resilience4j circuit breaker

---

components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/HazelcastComponentHelper.java
components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/atomicnumber/HazelcastAtomicnumberProducer.java
components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/list/HazelcastListProducer.java
components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/map/HazelcastMapProducer.java
components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/multimap/HazelcastMultimapProducer.java
components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/queue/HazelcastQueueProducer.java
components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/replicatedmap/HazelcastReplicatedmapConsumer.java
components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/ringbuffer/HazelcastRingbufferProducer.java
components/camel-hazelcast/src/test/java/org/apache/camel/component/hazelcast/HazelcastCamelTestSupport.java
components/camel-hazelcast/src/test/java/org/apache/camel/component/hazelcast/HazelcastReplicatedmapConsumerTest.java

This PR : 
- Fixes the bug of HazelcastReplicatedConsumer not receiving events on ReplicatedMap
- Adds an integration test for HazelcastReplicatedConsumer
- Fixes the warnings for deprecated Exchange.getOut(), Exchange.hasOut() and MockitoAnnotations.initMocks.

CAMEL-16018: HazelcastReplicatedConsumer not receiving events

---

components/camel-minio/src/main/java/org/apache/camel/component/minio/MinioComponent.java
components/camel-minio/src/test/java/org/apache/camel/component/minio/MinioComponentConfigurationTest.java

Issue: https://issues.apache.org/jira/browse/CAMEL-16037
If autowired is disabled it doesn't make sense to load client from registry.
Junit test is added.

CAMEL-16037 Minio: if autowiredEnabled is set to false on camelContext, minioClient is still autowired

---

catalog/camel-catalog/pom.xml

Add a licenceHeader property (the pom properties already have properties set).
https://issues.apache.org/jira/browse/CAMEL-16047

[CAMEL-16047] Add a licenceHeader property (the pom properties already have properties set).

---

components/camel-json-validator/src/main/java/org/apache/camel/component/jsonvalidator/JsonValidatorEndpoint.java

Reuse ObjectMapper because it's thread safe.

CAMEL-16049: Reuse ObjectMapper in camel-json-validator

---

components/camel-consul/src/main/java/org/apache/camel/component/consul/cluster/ConsulClusterView.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cluster/ConsulClusterViewTest.java

The session lock is on the full key path, not on the root path. As far as I can tell, the result of this method isn't actually used anywhere, but this fix at least makes it correct.
I discovered this issue due to my Consul ACL policy. My application has access to the full key path, but does not have access to the configured root path, so I was getting an error at startup.

Fix Consul key path used when determining leader.

---

components/camel-azure-storage-queue/src/main/java/org/apache/camel/component/azure/storage/queue/QueueConsumer.java

After message was consumed from Azure Storage Queue camel-azure-storage-queue add addOnCompletion trigger that delete message after all. If we want to download file in this route with Azure Storage Blob we will lose MessageId & PopReceipt header. Without this headers we can not remove message from queue.
Issue: https://issues.apache.org/jira/browse/CAMEL-16092

CAMEL-16092: Add fix for header override by Azure Storage Blob download consumer

---

components/camel-cxf-transport/src/main/java/org/apache/camel/component/cxf/common/header/CxfHeaderHelper.java
components/camel-cxf/src/test/java/org/apache/camel/component/cxf/jaxrs/CxfRsProducerHttpMethodHeaderTest.java

Don't leak internal CXF `QUERY_STRING` header.

CAMEL-16110: don't leak internal QUERY_STRING header

---

components/camel-huaweicloud-smn/src/main/docs/hwcloud-smn-component.adoc

- Code snippets and description added for bean based authentication parameter setting in the route 
- Added code snippets for publishAsPlainText operation
- Updated list of supported smn services and operations into a tabular representation making placeholder for additional services coming in future

huaweicloud smn - component documentation updates

---

core/camel-api/src/main/java/org/apache/camel/spi/PackageScanResourceResolver.java
core/camel-api/src/main/java/org/apache/camel/spi/Resource.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultComponentNameResolver.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultPackageScanResourceResolver.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultResource.java
core/camel-core/src/test/java/org/apache/camel/impl/engine/DefaultPackageScanResourceResolverTest.java
core/camel-main/src/main/java/org/apache/camel/main/DefaultRoutesCollector.java
docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_8.adoc

CAMEL-16127: Revisit PackageScanResourceResolver

---

catalog/camel-report-maven-plugin/src/main/docs/camel-report-maven-plugin.adoc
catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/RouteCoverageMojo.java

Added the missing @Parameter annotation in RouteCoverageMojo.java of the camel-report-maven-plugin

CAMEL-16145: Made coverageThreshold configurable in camel-report-maven-plugin

---

catalog/camel-report-maven-plugin/src/main/docs/camel-report-maven-plugin.adoc
catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/RouteCoverageMojo.java

Added an overall coverage threshold to the camel-report-maven-plugin. It takes into account all nodes across all routes. Thus, we do not have to fail if every route is reasonably covered except a small minority of simple helper routes. 
E.g. set coverageThreshold per route to 60% but overallCoverageThreshold should still be 90% in total.

CAMEL-16153: Added overall coverage threshold (across all routes) to camel-report-maven-plugin

---

core/camel-main/src/main/java/org/apache/camel/main/BaseMainSupport.java
core/camel-support/src/main/java/org/apache/camel/support/PropertyBindingSupport.java

- remove the name parameter as it was not used
- ensure the value is a string instead of rely to .toString() as it may
produce false results if the .toString() method is crafted to generate
a value starting with #bean:, #class:, #type:

core: tidy up PropertyBindingSupport::resolveBean

---

test-infra/camel-test-infra-artemis/src/test/java/org/apache/camel/test/infra/artemis/services/ArtemisContainer.java
test-infra/camel-test-infra-artemis/src/test/resources/org/apache/camel/test/infra/artemis/services/Dockerfile
test-infra/camel-test-infra-common/src/test/java/org/apache/camel/test/infra/common/TestUtils.java
test-infra/camel-test-infra-dispatch-router/src/test/java/org/apache/camel/test/infra/dispatch/router/services/DispatchRouterContainer.java
test-infra/camel-test-infra-dispatch-router/src/test/resources/org/apache/camel/test/infra/dispatch/router/services/Dockerfile
test-infra/camel-test-infra-hdfs/src/test/java/org/apache/camel/test/infra/hdfs/v2/services/HadoopBaseContainer.java
test-infra/camel-test-infra-hdfs/src/test/resources/org/apache/camel/test/infra/hdfs/v2/services/Dockerfile

fix CAMEL-16182: test-infra modules don't support testcontainers hub.image.name.prefix configuration.

---

components/camel-kafka/src/main/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepository.java
components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryEagerTest.java
components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryPersistenceTest.java

Jira ticket: https://issues.apache.org/jira/browse/CAMEL-16181
This PR fixes an issue where the `KafkaIdempotentRepository` flags its cache as ready before it has finished consuming all records in the backing Kafka repository

[CAMEL-16181] Fix KafkaIdempotentRepository flagging cache as ready incorrectly

---

components/camel-kamelet/src/main/java/org/apache/camel/component/kamelet/Kamelet.java

Prevents StringHelper from throwing a NullPointerException.

Kamelet: prevent null from being passed to StringHelper.

---

components/camel-netty/src/main/java/org/apache/camel/component/netty/NettyProducer.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyReuseChannelCallbackTest.java

With this fix NettyReuseChannelTest in PR #5093 should pass.

CAMEL-16227: Netty with reuseChannel invokes wrong callback

---

components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpRedeliveryTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettySSLTest.java

On Windows when the port is not opened one gets connection timeout instead of connection refused (may depend on firewall configuration). Made `NettyHttpRedeliveryTest` to work as intended in this case.
`NettySSLTest` used deprecated API which threw: `java.lang.UnsupportedOperationException: This method is deprecated and marked for removal. Use the getPeerCertificates() method instead.`

Fixed some camel-netty and camel-netty-http tests failing on Windows

---

components/camel-nats/src/main/java/org/apache/camel/component/nats/NatsEndpoint.java

Mark `NatsEndpoint` as supporting `MultipleConsumers`.
Per nats documentation:
NATS implements a publish-subscribe message distribution model for one-to-many communication.

Mark NatsEndpoint as supporting MultipleConsumers.

---

components/camel-kamelet/src/main/java/org/apache/camel/component/kamelet/Kamelet.java

Kamelet: remove null check for unused tid variable.

---

components/camel-kamelet/src/main/java/org/apache/camel/component/kamelet/Kamelet.java

Kamelet: Ensure camel route input is not null.

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/nats-component.adoc
components/camel-nats/src/main/docs/nats-component.adoc
docs/components/modules/ROOT/pages/nats-component.adoc

Looks like I missed this in #5034.

Nats: document that the producer now supports request/reply.

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/netty-component.adoc
catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/netty-http-component.adoc
components/camel-netty-http/src/generated/java/org/apache/camel/component/netty/http/NettyHttpEndpointUriFactory.java
components/camel-netty-http/src/generated/resources/org/apache/camel/component/netty/http/netty-http.json
components/camel-netty-http/src/main/docs/netty-http-component.adoc
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/NettyHttpEndpoint.java
components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpEndpointUriAssemblerTest.java
components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpEndpointUriFactoryTest.java
components/camel-netty/src/generated/java/org/apache/camel/component/netty/NettyEndpointUriFactory.java
components/camel-netty/src/generated/resources/org/apache/camel/component/netty/netty.json
components/camel-netty/src/main/docs/netty-component.adoc
components/camel-netty/src/main/java/org/apache/camel/component/netty/NettyEndpoint.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyEndpointUriFactoryTest.java
components/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/EndpointUriFactoryTestSupport.java
core/camel-componentdsl/src/generated/resources/metadata.json
core/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/StaticEndpointBuilders.java
core/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/dsl/NettyEndpointBuilderFactory.java
core/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/dsl/NettyHttpEndpointBuilderFactory.java
docs/components/modules/ROOT/pages/netty-component.adoc
docs/components/modules/ROOT/pages/netty-http-component.adoc

https://issues.apache.org/jira/browse/CAMEL-16280

CAMEL-16280: NettyEndpointUriFactory#buildUri() not compatible with Netty endpoint URL

---

components/camel-vertx-http/src/main/java/org/apache/camel/component/vertx/http/VertxBufferConverter.java
components/camel-vertx-http/src/test/java/org/apache/camel/component/vertx/http/VertxHttpBufferConverterTest.java

Backport for 3.7.x.
I took the easier (maybe safer?) option of not including the `camel-vertx-common` refactoring and just fixing the affected code. Hope that's ok.

CAMEL-16282: Fix VertxBufferConverter charset encoding for 3.7.x

---

components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/converters/MongoDbBasicConverters.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/MongoDbConversionsTest.java

Checking that the value to be converted from a String to List is an array in order to avoid a BsonInvalidOperationException when the method is called.
With this PR we fix a minor issue caused when we try to convert to a List, ie:
```
if (exchange.getIn().getBody(List.class) != null) {
List<?> body = exchange.getIn().getBody(List.class);
...
```
The above call would fail with a single document as the method assumes it's going to be an array of them. We should therefore return `null` if the passed in value is not an array and not proceed to the conversion.

fix(mongodb): converter failure

---

components/camel-slack/pom.xml
components/camel-slack/src/main/java/org/apache/camel/component/slack/CustomSlackHttpClient.java
components/camel-slack/src/main/java/org/apache/camel/component/slack/SlackConsumer.java
components/camel-slack/src/test/java/org/apache/camel/component/slack/SlackConsumerTest.java

- Forcing the v3.x in the pom.xml. You can see the discussion in Zulip here: https://camel.zulipchat.com/#narrow/stream/257298-camel/topic/CustomSlackHttpClient
- Mistake on SlackConsumer while checking if the cursor is empty or not (**isNotEmpty** => **isEmpty**)
- The dependency:tree is correctly displaying the v3.14.7
```
$ mvn dependency:tree 
[INFO] BuildTimeEventSpy is registered.
[INFO] Scanning for projects...
[INFO] 
[INFO] --------------------< org.apache.camel:camel-slack >--------------------
[INFO] Building Camel :: Slack 3.9.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.1:tree (default-cli) @ camel-slack ---
[INFO] org.apache.camel:camel-slack:jar:3.9.0-SNAPSHOT
[INFO] +- …
```

CAMEL-16336 Make CustomSlackHttpClient compatible with okhttp 3.x

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaConsumerManualCommitTest.java

This will make camel-kafka commits offsets onPartitionsRevoked only if autoCommitOffsets is true and thus the use will have the full control on manual offset commit. Also, previously the manual commit offsets test was disabled and now is fixed with this PR

CAMEL-16343: Avoid committing offsets on onPartitionsRevoked in case the user committing offsets

---

components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Component.java

Noticed a missing rename of 'useIAMCredentials' as 'useDefaultCredentialsProvider' with the 3.7 migration.

Missing one rename of 'useIAMCredentials' as 'useDefaultCredentialsProvider' with the rename in 3.7

---

core/camel-core-processor/src/main/java/org/apache/camel/processor/MulticastProcessor.java

Fix for issue CAMEL-16295, added the aggregate call after the accept of the result in the same function, this allows for the aggregation to occur when in a transacted route.

CAMEL-16295: fix aggregation when in transacted route

---

components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400Configuration.java

Current username/password parsing in the jt400 has two very minor bugs. Both should be fixed with a simple one-line change. 
**Bug 1: using an empty password results in an exception**
An empty password is allowed when the username is `*CURRENT`. However, specifying `*CURRENT:` as the `uid:pwd` string results in an exception
```pascal
Caused by: java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 1
at org.apache.camel.component.jt400.Jt400Configuration.<init> (Jt400Configuration.java:130)
at org.apache.camel.component.jt400.Jt400Endpoint.<init> (Jt400Endpoint.java:68)
at org.apache.camel.component.jt400.Jt400Component.createEndpoint (Jt400Component.java:77)
at org.apache.camel.support.DefaultComponent.createEndpoint (DefaultComponent.java:237)
at …
```

[MINOR] password parsing bugfix in jt400 component

---

components/camel-splunk/src/generated/java/org/apache/camel/component/splunk/SplunkEndpointConfigurer.java
components/camel-splunk/src/generated/java/org/apache/camel/component/splunk/SplunkEndpointUriFactory.java
components/camel-splunk/src/main/docs/splunk-component.adoc
components/camel-splunk/src/main/java/org/apache/camel/component/splunk/SplunkConfiguration.java
components/camel-splunk/src/main/java/org/apache/camel/component/splunk/SplunkProducer.java
components/camel-splunk/src/main/java/org/apache/camel/component/splunk/support/TcpDataWriter.java
components/camel-splunk/src/test/java/org/apache/camel/component/splunk/ProducerTest.java
components/camel-splunk/src/test/java/org/apache/camel/component/splunk/RawProducerTest.java

fixes https://issues.apache.org/jira/browse/CAMEL-16357
Added parameter `tcpLocalReceiverPort`, which could be used in case that port for tcp receiver differs in splunk server and real value used for connection (e.g. when port is mapped via docker)
Junit test is present.

CAMEL-16357: Camel-splunk define tcpLocalReceiver port

---

components/camel-google/camel-google-drive/src/test/java/org/apache/camel/component/google/drive/DriveChangesIntegrationTest.java

**Problem:**
Conditions within the test method may produce a false test outcome. Once a condition is not met, and the code block inside the condition is not executed, a false 'passed' outcome can be produced without the test ever being executed.
**Solution:**
Instead of using a conditional to control the test execution, we propose using JUnit Assumptions — a failed assumption results in a test being aborted. Assumptions are typically used whenever it does not make sense to continue executing a given test method. 
**Result:**
_Before:_
```
...
if (!items.isEmpty()) {
...
assertNotNull(result, "get result");
}
```
_After:_
```
...
assumeFalse(items.isEmpty());
...
assertNotNull(result, "get result");
```

Improved conditional test execution

---

components/camel-microprofile/camel-microprofile-fault-tolerance/src/main/java/org/apache/camel/component/microprofile/faulttolerance/FaultToleranceProcessor.java
components/camel-resilience4j/src/main/java/org/apache/camel/component/resilience4j/ResilienceProcessor.java

Fixes https://issues.apache.org/jira/browse/CAMEL-16418 
LEAK: ByteBuf.release() results when using circuit breaker with netty http producer
Using circuit breaker pattern with camel netty http will result in memory leaks. Netty will report ByteBuff leak as noted in the below stack trace. This can be reproduced very easily with a simple route definition (code sample attached). Note that the leak has nothing to do with actual circuit breaker timeouts and will result irrespectively and every time the netty http producer is called. Also it occurs with implementation of camel-reslience4j and camel-microprofile
LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.
Recent access records: 
#1:
**#2: …

Fixing LEAK: ByteBuf.release() when using circuit breaker with netty http producer

---

components/camel-seda/src/main/docs/seda-component.adoc

Example is shown twice the same.

Polish seda docs

---

components/camel-zipkin/src/main/java/org/apache/camel/zipkin/ZipkinState.java
components/camel-zipkin/src/main/java/org/apache/camel/zipkin/ZipkinTracer.java
components/camel-zipkin/src/test/java/org/apache/camel/zipkin/ZipkinStateTest.java

Fixes CAMEL-16453. Update the Exchange object in serverRequest with the new span so that it is visible downstream via Exchange headers. In clientRequest do not assume the last server span is the parent for the current traceContext, as this will not be true in case of parallelProcessing. Modify ZipkinState to use Deque instead of Stack to allow retrieval of matching spanId.

Incorrect parentId span set when using camel-zipkin with recipientList or multicast and parallelProcessing CAMEL-16453

---

core/camel-core-model/src/main/java/org/apache/camel/builder/BuilderSupport.java

Adding this method allows to check if any errorHandlerBuilder exists, before to be initialized by the getErrorHandlerBuilder method (which set a default one if it does not exists).
We are implementing a mechanism to [enable error handling in KameletBinding](https://github.com/apache/camel-k/issues/1941) and we need to check if any exists in the BuilderSupport prior to its default setting.

feat(core): hasErrorHandlerBuilder helper method

---

tooling/maven/camel-restdsl-openapi-plugin/src/main/docs/camel-restdsl-openapi-plugin.adoc
tooling/maven/camel-restdsl-openapi-plugin/src/main/java/org/apache/camel/maven/generator/openapi/AbstractGenerateMojo.java
tooling/maven/camel-restdsl-openapi-plugin/src/main/java/org/apache/camel/maven/generator/openapi/GenerateMojo.java
tooling/maven/camel-restdsl-openapi-plugin/src/main/java/org/apache/camel/maven/generator/openapi/GenerateXmlMojo.java
tooling/openapi-rest-dsl-generator/src/main/java/org/apache/camel/generator/openapi/RestDslDefinitionGenerator.java
tooling/openapi-rest-dsl-generator/src/main/java/org/apache/camel/generator/openapi/RestDslGenerator.java
tooling/openapi-rest-dsl-generator/src/main/java/org/apache/camel/generator/openapi/RestDslSourceCodeGenerator.java
tooling/openapi-rest-dsl-generator/src/main/java/org/apache/camel/generator/openapi/RestDslXmlGenerator.java
tooling/openapi-rest-dsl-generator/src/test/java/org/apache/camel/generator/openapi/RestDslGeneratorTest.java

CAMEL-16502: This pull request add an optional basepath parameter to allow developers override the basepath evaluated from the first server entry in the openapi document.
Behaviour:
- If the basepath parameter is not set, the restdsl-generator behaves like before.
- In case the basepath parameter is set (e.g. in the according maven plugin mojos) it takes precedence over the basepath from the server entry.
Changes:
- The logic is implemented in a new method in the RestDslGenerator.
- Generators extended from the base RestDslGenerator are changed to call the new method.
- Maven plugins using the RestDslGenerator are extended to set the parameter if set in the plugin config.
- The documentation for the maven plugins is updated with the new parameter.
- Unit tests are extended with checks for …

CAMEL-16502: add optional basepath parameter to restdsl-generator

---

components/camel-braintree/README.md
components/camel-braintree/src/test/java/org/apache/camel/component/braintree/DisputeGatewayIntegrationTest.java
components/camel-braintree/src/test/java/org/apache/camel/component/braintree/ReportGatewayIntegrationTest.java
components/camel-braintree/src/test/java/org/apache/camel/component/braintree/TransactionGatewayIntegrationTest.java

- do not reuse amount values otherwise the test fails due to duplicates
- log result messages for easier debug
- skip certain tests when environment variables are not provided
- added documentation

camel-braintree: test fixes and improvements

---

components/camel-ribbon/pom.xml
components/camel-ribbon/src/main/java/org/apache/camel/component/ribbon/cloud/RibbonServiceLoadBalancer.java
components/camel-ribbon/src/test/java/org/apache/camel/component/ribbon/cloud/RibbonServerListTest.java
core/camel-api/src/main/java/org/apache/camel/cloud/ServiceFilter.java
core/camel-api/src/main/java/org/apache/camel/cloud/ServiceLoadBalancer.java
core/camel-cloud/src/main/java/org/apache/camel/impl/cloud/BlacklistServiceFilter.java
core/camel-cloud/src/main/java/org/apache/camel/impl/cloud/CombinedServiceFilter.java
core/camel-cloud/src/main/java/org/apache/camel/impl/cloud/DefaultServiceCallProcessor.java
core/camel-cloud/src/main/java/org/apache/camel/impl/cloud/DefaultServiceFilter.java
core/camel-cloud/src/main/java/org/apache/camel/impl/cloud/DefaultServiceLoadBalancer.java
core/camel-cloud/src/main/java/org/apache/camel/impl/cloud/HealthyServiceFilter.java
core/camel-cloud/src/main/java/org/apache/camel/impl/cloud/PassThroughServiceFilter.java
core/camel-cloud/src/test/java/org/apache/camel/impl/cloud/CombinedServiceFilterTest.java
core/camel-cloud/src/test/java/org/apache/camel/impl/cloud/LoadBalancerTest.java
core/camel-cloud/src/test/java/org/apache/camel/impl/cloud/ServiceCallConfigurationTest.java
core/camel-core-engine/src/main/docs/modules/eips/pages/serviceCall-eip.adoc
core/camel-core-model/src/main/java/org/apache/camel/model/cloud/CombinedServiceCallServiceFilterConfiguration.java
docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_10.adoc
parent/pom.xml

fixes https://issues.apache.org/jira/browse/CAMEL-16449
Main goal: pass the current exchange to `ServiceFilter.apply` without breaking existing `ServiceFilter` and `ServiceLoadBalancer` implementations. Make it as convenient as possible to implement service filters with access to the current exchange.
Trade-off: the old method cannot be executed upwards-compatibly on the new `ContentBasedServiceFilter`. Hence the implementation is a bit more convoluted than I would like it to be.
Implementation steps:
1. ​Introduce new `ServiceFilter.apply(exchange, services)` method with default impl that calls the old apply method without passing the exchange
2. Introduce new ServiceLoadBalancer.process(exchange, serviceName, serviceLoadBalancerFunction) method with default impl that calls the old …

[CAMEL-16449]: Introduces ContentBasedServiceFilter

---

components/camel-aws/camel-aws2-ec2/src/test/java/org/apache/camel/component/aws2/ec2/integration/EC2ComponentManualIT.java
components/camel-aws/camel-aws2-ecs/src/test/java/org/apache/camel/component/aws2/ecs/integration/ECS2ProducerManualIT.java
components/camel-aws/camel-aws2-eventbridge/src/test/java/org/apache/camel/component/aws2/eventbridge/integration/EventbridgePutRuleManualIT.java
components/camel-aws/camel-aws2-eventbridge/src/test/java/org/apache/camel/component/aws2/eventbridge/integration/EventbridgePutRuleSqsManualIT.java
components/camel-aws/camel-aws2-lambda/src/test/java/org/apache/camel/component/aws2/lambda/integration/LambdaComponentManualIT.java
components/camel-aws/camel-aws2-s3/src/test/java/org/apache/camel/component/aws2/s3/integration/S3ComponentManualIT.java
components/camel-aws/camel-aws2-s3/src/test/java/org/apache/camel/component/aws2/s3/integration/S3ConsumerManualIT.java
components/camel-aws/camel-aws2-s3/src/test/java/org/apache/camel/component/aws2/s3/integration/S3CopyObjectOperationManualIT.java
components/camel-aws/camel-aws2-s3/src/test/java/org/apache/camel/component/aws2/s3/integration/S3ObjectRangeOperationManualIT.java
components/camel-aws/camel-aws2-sns/src/test/java/org/apache/camel/component/aws2/sns/integration/SnsComponentFifoManualIT.java
components/camel-aws/camel-aws2-sns/src/test/java/org/apache/camel/component/aws2/sns/integration/SnsComponentManualIT.java
components/camel-aws/camel-aws2-sns/src/test/java/org/apache/camel/component/aws2/sns/integration/SnsTopicWithKmsEncryptionManualIT.java

This avoids the manual tests from being inadvertdly triggered in CI due
to automated tests injecting the the same properties during integration test
initialization.

camel-16400: rename properties used for triggering AWS manual tests

---

test-infra/camel-test-infra-aws-common/src/test/java/org/apache/camel/test/infra/aws/common/AWSProperties.java
test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSLocalContainerService.java

- fixed incorrect property name for the localstack container
- ensure the localstacl container can be properly overridden

camel-test-infra-aws-v2: minor fixes

---

components/camel-aws/camel-aws2-sns/src/test/java/org/apache/camel/component/aws2/sns/integration/SnsTopicProducerWithSubscriptionIT.java

camel-aws2-sns: added SNS test with subscription to SQS

---

dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/pom.xml
parent/pom.xml

No JIRA issue, but the version of camel-yaml-dsl-maven-plugin should be moved into the parent/pom.xml into the pluginManagement and removed from camel-yaml-dsl-deserializers.

Move version of camel-yaml-dsl-maven-plugin into parent pom

---

components/camel-consul/src/main/java/org/apache/camel/component/consul/endpoint/ConsulCatalogProducer.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/ConsulCatalogIT.java

fixes https://issues.apache.org/jira/browse/CAMEL-16559
- replaces erroneous call to `CatalogClient.getNodes` by `CatalogClient.getServices`

[CAMEL-16559] fixes catalog LIST_SERVICES

---

components/camel-consul/src/generated/java/org/apache/camel/component/consul/endpoint/ConsulAgentProducerInvokeOnHeaderFactory.java
components/camel-consul/src/main/docs/consul-component.adoc
components/camel-consul/src/main/java/org/apache/camel/component/consul/ConsulConstants.java
components/camel-consul/src/main/java/org/apache/camel/component/consul/endpoint/ConsulAgentActions.java
components/camel-consul/src/main/java/org/apache/camel/component/consul/endpoint/ConsulAgentProducer.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/ConsulAgentIT.java

fixes https://issues.apache.org/jira/browse/CAMEL-16561
- added REGISTER and DEREGISTER agent actions
- introduced and documented new header `CamelConsulServiceId` to specify a service to deregister
- enhanced documentation, explaining the relationship between apiEndpoint, action and the component
- also mentioned `ServiceRegistrationRoutePolicy`

[CAMEL-16561]: Add support for agent REGISTER/DEREGISTER

---

components/camel-cxf/src/main/docs/cxf-component.adoc
components/camel-cxf/src/test/java/org/apache/camel/component/cxf/CxfConsumerPayLoadConverterTest.java

fixes CAMEL-16583
* Removed the manual table of contents at the beginning, the generated TOC is sufficient
* Added back the code samples which used to be there, with links to the tests where they came from
* Renamed CxfConsumerPayLoadConvertorTest to CxfConsumerPayLoadConverterTest

CAMEL-16583: Reintroduce code samples in camel-cxf docs

---

components/camel-openstack/src/main/java/org/apache/camel/component/openstack/swift/producer/ObjectProducer.java

The code adds the ability to modify the behavior of getAll in the swift client by putting "path"=value in the header.
The result is that a list of objects whose path starts with value are returned.
If the "path" is not set it has the usual behavior.

[CAMEL-16595] Swift getall filter path

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/bindy-dataformat.adoc
components/camel-bindy/src/main/docs/bindy-dataformat.adoc
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/annotation/CsvRecord.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/annotation/DataField.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/annotation/FixedLengthRecord.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/annotation/KeyValuePairField.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/annotation/Link.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/annotation/Message.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/annotation/OneToMany.java
docs/components/modules/dataformats/pages/bindy-dataformat.adoc
tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/AnnotationModel.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/UpdateReadmeMojo.java
tooling/maven/camel-package-maven-plugin/src/main/resources/annotation-options.mvel

https://issues.apache.org/jira/browse/CAMEL-16517
This pull req introduces the following new notation for adoc update to `camel-package:update-readme` maven plugin task so that docs with mentions to annotation options can be up-to-date with code.
```
// annotation interface: <FQCN for the annotation interface to be processed>
// annotation options: START
// annotation options: END
```
To minimise the impact of this new introduction currently it's activated only for camel-bindy.

CAMEL-16517 - Add annotation processing feature to camel-package:update-readme

---

pom.xml

We want to skip running integration tests during release building.

Skip integration tests for release building

---

pom.xml

Disable the `enable-schemagen` profile for release building. Seems like this profile has been removed a while back and only produces noise/warnings during the release process.

Remove `enable-schemagen` in release profile

---

components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQProducer.java
components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/RabbitMQProducerTest.java

camel-rabbitmq - Producer destroys rabbit channels when returns it back to the pool
- for RabbitMQProducer specify `GenericObjectPool._maxIdle` property of channel pool with `RabbitMQEndpoint.channelPoolMaxSize` value

CAMEL-16619: change channel pool configuration in RabbitMQProducer

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java

Ticket: https://issues.apache.org/jira/browse/CAMEL-16640 . 
It is about the plain camel-kafka component as in 3.10. The changes which have been added for this ticket: https://issues.apache.org/jira/browse/CAMEL-14980 are causing this problem.
In KafkaConsumer class in the run() method if the thread is sleeping and an Interrupted Exception occurs, then the thread will leave the loop, which is fine. But, if before the thread enters the sleeping, something happens then the thread will remain running without caring about the stopping state(Zombie Thread). 
In the doPollRun() method, the retry flag is set to false only when the consumer wakeup method throws an exception which  causes the thread again to keep running in the loop without stopping which leaves the thread to be zombie.

CAMEL-16640 camel-kafka race conditions during shut down

---

parent/pom.xml

Move the camel-dsl-support dependency above the autogeneration point so it isn't removed by the camel catalog autogeneration.

Move the camel-dsl-support dependency entry above the autogeneration point

---

components/camel-undertow/pom.xml
components/camel-undertow/src/test/java/org/apache/camel/component/undertow/UndertowHttp2Test.java

I actually wanted to use 
```
@BindToRegistry("undertowHostOptions")
private UndertowHostOptions undertowHostOptions = new UndertowHostOptions();
```
and a route like
```
from("undertow:http://localhost:{{port}}/myapp?hostOptions=#undertowHostOptions")
```
but it's not working, maybe I'm missing something
Uncomment and fill this section if your PR is not trivial

Test undertow http2 protocol

---

components/camel-http/src/main/java/org/apache/camel/component/http/HttpComponent.java

Camel-http component creates unimportant log entries on INFO level. Change it to debug so it can be activated to those who really need it by enabling debug logging.

Change "Created ClientConnectionManager" log level to debug

---

components/camel-google/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubConsumer.java

In the synchronous consumer, catch and log retryable ApiException-s in addition to IOExcepion-s.
The synchronous consumer will still die on all other exceptions.

CAMEL-16263 camel-google-pubsub - Consumer does not recover from 500 series error from Google

---

tooling/maven/camel-restdsl-openapi-plugin/src/main/java/org/apache/camel/maven/generator/openapi/GenerateMojo.java

Instead of configuring RequestMapping with "/**" this change allows inserting custom paths. Usually the "/**" conflicts with /actuator/hawtio. On the other hand, there may be paths that we don't want to be handled by the Controller. ** This change depends on the acceptance of the change in class https://github.com/apache/camel/blob/main/tooling/openapi-rest-dsl-generator/src/main/java/org/apache/camel/generator/openapi /SpringBootProjectSourceCodeGenerator.java from the openapi-rest-dsl-generator project.

Allow customizing SpringBoot @RequestMapping paths

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaComponent.java

If a KafkaConfiguration is used (see code in jira ticket) and no topic is defined in the configuration, the parameter from the URI is not taken over, but a null value is set.
This leads to a consumer not having a valid topic name, but null being provided as a value.
Therefore, the topic is only set after this method if the topic is still null.
It looks like setProperties(endpoint, parameters); overrites the topic with null.

CAMEL-16701: Set topic value after setProperties method

---

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/util/EntityUtils.java
components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/util/EntityUtilsTest.java

I mean the string like 
"application/edifact" as opposed to "application/edifact; charset=US-ASCII"
Currently I can see the passed content-type "application/edifact" with null Charset gets transformed to "application/edifact; charset=US-ASCII" anyway.
Added two unit-tests to test the cases when passed charset is null and non-null.

Respect the user's intention to send content-type header without appended charset

---

components/camel-huawei/camel-huaweicloud-functiongraph/src/test/java/org/apache/camel/InvokeFunctionCombinedFunctionalTest.java
components/camel-huawei/camel-huaweicloud-functiongraph/src/test/java/org/apache/camel/InvokeFunctionExchangeFunctionalTest.java
components/camel-huawei/camel-huaweicloud-functiongraph/src/test/java/org/apache/camel/InvokeFunctionFunctionalTest.java
components/camel-huawei/camel-huaweicloud-functiongraph/src/test/java/org/apache/camel/InvokeFunctionServiceKeyFunctionalTest.java

Added more functional test cases to HuaweiCloud FunctionGraph component.
1. Testing functionality options through exchange properties
2. Testing functionality options through both exchange properties and endpoint (exchange parameters should carry precedence over endpoint options)
3. Testing standard functionality with region instead of endpoint url
4. Testing authentication with service keys
JIRA: https://issues.apache.org/jira/browse/CAMEL-16674

CAMEL-16674 : More functional test cases

---

components/camel-http/src/main/java/org/apache/camel/component/http/HttpProducer.java
components/camel-http/src/test/java/org/apache/camel/component/http/HttpProducerBridgeEndpointTest.java
components/camel-http/src/test/java/org/apache/camel/component/http/handler/HeaderValidationHandler.java

Added unit test that reproduces error and applied fix included in version 3.9.0 (cherry-pick [031ea4b4](https://github.com/apache/camel/commit/031ea4b4098834d72390d9c699fcb45e6838f57c)).

[CAMEL-16699] Fix HttpProducer bridged endpoint skipRequestHeaders for common type headers

---

components/camel-aws/camel-aws2-lambda/src/main/java/org/apache/camel/component/aws2/lambda/Lambda2Producer.java

according to the lambda docs, the source code zip can be in message body or in `CamelAwsLambdaZipFile` header, but the header isn't checked in the code and it fails at runtime with
```
java.lang.IllegalArgumentException: At least S3 bucket/S3 key or zip file must be specified
at org.apache.camel.component.aws2.lambda.Lambda2Producer.createFunction(Lambda2Producer.java:277)
```

[Lambda] Also check CamelAwsLambdaZipFile in createFunction

---

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/AS2ServerConnection.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/protocol/ResponseMDN.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/util/EntityUtils.java
components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/AS2MessageTest.java
components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/util/EntityUtilsTest.java
components/camel-as2/camel-as2-component/src/main/java/org/apache/camel/component/as2/internal/AS2ConnectionHelper.java
components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2ClientManagerIT.java

Currently there is no means to specify custom mdn template. Here I mean that I can call the corresponding setter, but the specified template isn't passed deeper and I still get hardcoded template DEFAULT_MDN_MESSAGE_TEMPLATE from the class ResponseMDN - I can see it from my testing.
My changes allow tp pick up the template from the class AS2Configuration along with many other settings.

Do not ignore mdn template from AS2 server configuration

---

components/camel-aws/camel-aws2-ddb/src/test/java/org/apache/camel/component/aws2/ddb/localstack/AWS2BatchGetItemsRuleIT.java
components/camel-aws/camel-aws2-ddb/src/test/java/org/apache/camel/component/aws2/ddb/localstack/AWS2QueryRuleIT.java
components/camel-aws/camel-aws2-ddb/src/test/java/org/apache/camel/component/aws2/ddb/localstack/AWS2ScanRuleIT.java
components/camel-aws/camel-aws2-ddb/src/test/java/org/apache/camel/component/aws2/ddb/localstack/Aws2DDBBase.java

These tests needed specific table creation, so added a table create before and a table delete after the test.
They are very simple tests, but at least they make sure we can do a basic operation on BatchGetItems, Query and Scan.

feature(camel-aws-ddb): Add BatchGetItems, Query and Scan tests

---

components/camel-bean/src/main/java/org/apache/camel/component/bean/ConstantTypeBeanHolder.java
core/camel-core/src/test/java/org/apache/camel/component/bean/MethodCallByTypeRefExistingBeanTest.java

Fixing https://issues.apache.org/jira/browse/CAMEL-16733.
Search the registry and if single bean is found matching the given type, then use it rather than creating a new instance.

Use an existing bean from the registry if a single candidate of the given type is available, rather than creating a new one

---

components/camel-aws/camel-aws2-ddb/src/main/java/org/apache/camel/component/aws2/ddb/QueryCommand.java

Switch to use the existing parent class's method to determine the exclusive start key, only set it once in the builder.
---
Side note, the following line will set the LAST_EVALUATED_KEY to an SdkAutoConstructMap when no last evaluated key is present.
```java
tmp.put(Ddb2Constants.LAST_EVALUATED_KEY, result.lastEvaluatedKey());
```
I'm not sure if this is intentional, or the component should check for this and return null. Currently, dependent applications have to reimplement this logic available in the sdk.
```java
public final boolean hasLastEvaluatedKey() {
return lastEvaluatedKey != null && !(lastEvaluatedKey instanceof SdkAutoConstructMap);
}
```
If an always-null if not present is desired, I could put up another pull request.

(aws2-ddb) Set exclusive start key only once.

---

components/camel-zipkin/src/main/java/org/apache/camel/zipkin/ZipkinClientRequestAdapter.java
components/camel-zipkin/src/main/java/org/apache/camel/zipkin/ZipkinTracer.java

Added method ZipkinTracer#setClientCustomTags() to allow specifying custim tags which should be attached to all spans automatically by ZipkinClientRequestAdapter.

CAMEL-16605 camel-zipkin custom tags should be attached to exchange automatically

---

dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/KameletMain.java

Removing the static instance makes it easier to embedded it in
applications instantiating the KameletMain directly, as it avoids them
having to specialize it to override the instance variable.

CAMEL-16612: simplify KameletMain object lifecycle

---

components/camel-sjms/src/main/java/org/apache/camel/component/sjms/SjmsProducer.java
components/camel-sjms/src/main/java/org/apache/camel/component/sjms/jms/JmsMessageHelper.java
components/camel-sjms/src/main/java/org/apache/camel/component/sjms/reply/ReplyManagerSupport.java

Addresses issue [CAMEL-16763](https://issues.apache.org/jira/browse/CAMEL-16763).
This PR replaces `getJMSCorrelationIDAsBytes()` calls with `getJMSCorrelationID`. Using `getJMSCorrelationIDAsBytes()` to determine correlation ID is not compatible with Artemis JMS Client as the Artemis implementation of `Message` only returns a correlation ID from `getJMSCorrelationIDAsBytes()` if the correlation ID is a byte array, otherwise it returns null. Because camel sets the correlation ID explicitly as a string, the correlation ID retrieved from `getJMSCorrelationIDAsBytes()` was always null.

CAMEL-16763: Fixes JMS Correlation ID bug in camel-sjms

---

components/camel-xpath/src/main/docs/xpath-language.adoc

Trivial change to documentation only

Fix incorrect example class links in xpath documentation

---

core/camel-support/src/main/java/org/apache/camel/support/ResourceHelper.java

I noticed that isHttpUri() recognizes "https:" as a scheme, so it seems to me that hasScheme() ought to recognise it as well.

ResourceHelper.hasScheme() now recognizes "https:" scheme

---

components/camel-elasticsearch-rest/src/main/java/org/apache/camel/component/elasticsearch/converter/ElasticsearchActionRequestConverter.java

When a specific index is not given in the searchrequest object, the index name in camel dsl should be taken.
`.setBody(constant(new SearchRequest())) .to("elasticsearch-rest://elasticsearch?operation=Search&indexName=camel&useScroll=true&scrollKeepAliveMs=30000")`
In this scenario, a query is made with an empty index and documents related to the index are sent to me. If we change the code like this, it will search the camel index.

Elasticsearch-rest empty index name problem

---

components/camel-elasticsearch-rest/src/main/docs/elasticsearch-rest-component.adoc

types method was removed in 7 version at 2018 november

Deprecated Elastic methods removed

---

components/camel-opentelemetry/src/main/docs/opentelemetry.adoc
components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/OpenTelemetrySpanAdapter.java
components/camel-opentracing/src/main/docs/opentracing.adoc
components/camel-opentracing/src/main/java/org/apache/camel/opentracing/OpenTracingSpanAdapter.java
components/camel-opentracing/src/main/java/org/apache/camel/opentracing/OpenTracingTracer.java
components/camel-opentracing/src/test/java/org/apache/camel/opentracing/MDCSupportTest.java
components/camel-tracing/src/main/java/org/apache/camel/tracing/ActiveSpanManager.java
components/camel-tracing/src/main/java/org/apache/camel/tracing/SpanAdapter.java
components/camel-tracing/src/test/java/org/apache/camel/tracing/ActiveSpanManagerTest.java
components/camel-tracing/src/test/java/org/apache/camel/tracing/MockSpanAdapter.java

Adds traceId and spanId string methods to SpanAdapter
Adds and removes MDC fields when activating, deactivating a span
Rebased version of #4914

implement logging mdc support CAMEL-12879

---

components/camel-sql/src/main/java/org/apache/camel/processor/idempotent/jdbc/JdbcCachedMessageIdRepository.java

Switched to column index methods to avoid case sensitivity issues on certain SQL implementations

[CAMEL-16798] Fix JDBC Cached Repo case sensitivity

---

components/camel-file/src/main/java/org/apache/camel/component/file/strategy/FileChangedExclusiveReadLockStrategy.java

This reverts parts of the commit [1] which broke the read-lock behavior for files.
[1] https://github.com/apache/camel/commit/c5bbbd5b58569fbbd00d2936223f4d52ed23f78d

[CAMEL-16795] Fix read-lock behavior

---

components/camel-http/src/main/java/org/apache/camel/component/http/HttpEndpoint.java

Fix an unlikely but possible inconsistency when multiple threads are reading/writing the http client object instance. The missing lock on setHttpClient could lead to subtle bugs if multiple threads try to get/set the instance at the same time.

camel-http: fix possible concurrency issue

---

core/camel-core-engine/pom.xml
core/camel-management-api/pom.xml

Remove the AIX maven profile from camel-core-engine and
camel-management-api because it was only used to skip test on that
platform, but there are no tests in those modules.

(chores) Remove unused AIX profiles

---

components/camel-websocket/src/main/java/org/apache/camel/component/websocket/WebsocketComponent.java
components/camel-websocket/src/main/java/org/apache/camel/component/websocket/WebsocketEndpoint.java

Moving the endpoint initialization code from the component into the endpoint constructor makes it considerably easier to extend WebsocketEndpoint with your own customized endpoint.

camel-websocket: safe extension of endpoint
