components/camel-kafka/src/generated/resources/META-INF/services/org/apache/camel/component.properties
components/camel-kafka/src/generated/resources/org/apache/camel/component/kafka/kafka.json
components/camel-kafka/src/main/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepository.java
components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryNonEagerTest.java
components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryPersistenceTest.java
core/camel-componentdsl/src/generated/resources/metadata.json

Jira ticket: https://issues.apache.org/jira/browse/CAMEL-16181
Backport to 3.7.x for #5066

[CAMEL-16181] Fix KafkaIdempotentRepository flagging cache as ready incorrectly

---

components/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Producer.java
components/camel-aws2-s3/src/test/java/org/apache/camel/component/aws2/s3/localstack/Aws2S3BaseTest.java
components/camel-aws2-s3/src/test/java/org/apache/camel/component/aws2/s3/localstack/S3SimpleEncryptedUploadOperationLocalstackTest.java

CAMEL-16189 - AWS2S3Producer not setting serverside encryption values

---

components/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Producer.java
components/camel-aws2-s3/src/test/java/org/apache/camel/component/aws2/s3/localstack/Aws2S3BaseTest.java
components/camel-aws2-s3/src/test/java/org/apache/camel/component/aws2/s3/localstack/S3SimpleEncryptedUploadOperationLocalstackTest.java

Camel 16189 3.7.x

---

components/camel-sql/src/main/java/org/apache/camel/component/sql/SqlProducer.java
components/camel-sql/src/test/java/org/apache/camel/component/sql/SqlGeneratedKeysTest.java

...when CamelSqlRetrieveGeneratedKeys == true
Also refactored out some duplicate code.

CAMEL-16206: camel-sql: Preserve message body

---

components/camel-optaplanner/src/main/java/org/apache/camel/component/optaplanner/OptaPlannerConstants.java
components/camel-optaplanner/src/main/java/org/apache/camel/component/optaplanner/OptaPlannerProducer.java
components/camel-optaplanner/src/test/java/org/apache/camel/component/optaplanner/OptaPlannerAsyncSolverTest.java
components/camel-optaplanner/src/test/java/org/apache/camel/component/optaplanner/OptaPlannerDaemonSolverTest.java
parent/pom.xml

CAMEL-16194- upgrade Optaplanner to 8.x

---

core/camel-management/src/main/java/org/apache/camel/management/DefaultManagementObjectNameStrategy.java

[CAMEL-16225] Use camel context from route instead from endpoint

---

core/camel-core-engine/src/main/docs/modules/eips/pages/message-expiration.adoc
core/camel-core-engine/src/main/docs/modules/eips/pages/polling-consumer.adoc

Fix xref for 3.8.x

---

core/camel-core-engine/src/main/docs/modules/eips/pages/message-expiration.adoc
core/camel-core-engine/src/main/docs/modules/eips/pages/polling-consumer.adoc

Fix 3.7.x xref

---

core/camel-core-engine/src/main/docs/modules/eips/pages/message-expiration.adoc
core/camel-core-engine/src/main/docs/modules/eips/pages/polling-consumer.adoc

Fix 3.4.x xref

---

test-infra/camel-test-infra-artemis/src/test/resources/org/apache/camel/test/infra/artemis/services/Dockerfile

camel-test-infra-artemis: updated Artemis version in container to 2.17.0

---

components/camel-netty/pom.xml
components/camel-netty/src/main/java/org/apache/camel/component/netty/NettyCamelState.java
components/camel-netty/src/main/java/org/apache/camel/component/netty/handlers/ClientChannelHandler.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/BaseNettyTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/EnrichWithoutRestResponseTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/ErrorDuringGracefullShutdownTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/LogCaptureAppender.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/LogCaptureTest.java
components/camel-netty/src/test/resources/log4j2.properties

CAMEL-16178: camel-netty should invoke callback exactly once even when there was no UnitOfWork

---

components/camel-debezium-common/camel-debezium-common-component/src/main/java/org/apache/camel/component/debezium/DebeziumTypeConverter.java
components/camel-debezium-common/camel-debezium-common-component/src/test/java/org/apache/camel/component/debezium/DebeziumTypeConverterTest.java

CAMEL-16254: Add nested Structs support

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/polling-consumer.adoc
core/camel-core-engine/src/main/docs/modules/eips/pages/polling-consumer.adoc
docs/user-manual/modules/ROOT/pages/batch-consumer.adoc

Xref Alignment

---

components/camel-azure-storage-blob/src/main/docs/azure-summary.adoc
docs/components/modules/ROOT/nav.adoc
docs/components/modules/ROOT/pages/azure-summary.adoc

I have deleted it when I removed the legacy Azure component, brining it back now

Add Azure summary docs

---

components/camel-aws2-lambda/src/main/docs/aws2-lambda-component.adoc

Fix a broken link to the integration test mentioned on this page: https://camel.apache.org/components/latest/aws2-lambda-component.html

camel-aws2-lambda: fixed broken link in component documentation

---

test-infra/camel-test-infra-artemis/src/test/resources/org/apache/camel/test/infra/artemis/services/Dockerfile
test-infra/camel-test-infra-hdfs/src/test/resources/org/apache/camel/test/infra/hdfs/v2/services/Dockerfile

Ensure curl retries the downloads on the custom containers in the test-infra

---

components/camel-azure-storage-blob/src/main/java/org/apache/camel/component/azure/storage/blob/BlobStreamAndLength.java
components/camel-azure-storage-blob/src/main/java/org/apache/camel/component/azure/storage/blob/BlobUtils.java
components/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BlobOperationsITTest.java

CAMEL-16252: Remove the unnecessary explicit stream mark check in camel-azure-storage-blob 

---

components/camel-azure-storage-blob/src/generated/resources/META-INF/services/org/apache/camel/component.properties
components/camel-azure-storage-blob/src/generated/resources/org/apache/camel/component/azure/storage/blob/azure-storage-blob.json
components/camel-azure-storage-blob/src/main/java/org/apache/camel/component/azure/storage/blob/BlobStreamAndLength.java
components/camel-azure-storage-blob/src/main/java/org/apache/camel/component/azure/storage/blob/BlobUtils.java
components/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BlobOperationsITTest.java

CAMEL-16252: Remove the unnecessary explicit stream mark check

---

components/camel-xstream/pom.xml

Set scope of junit-vintage-engine to test.

CAMEL-16268, set scope of junit-vintage-engine

---

components/camel-vertx-common/src/main/java/org/apache/camel/component/vertx/common/VertxBufferConverter.java
components/camel-vertx-http/src/test/java/org/apache/camel/component/vertx/http/VertxHttpBufferConverterTest.java
components/camel-vertx-kafka/camel-vertx-kafka-component/src/test/java/org/apache/camel/component/vertx/kafka/VertxKafkaBufferConverterTest.java

CAMEL-16282: Fix VertxBufferConverter charset encoding

---

components/camel-lra/src/main/java/org/apache/camel/service/lra/LRAClient.java

CAMEL-16253: Improve the way that the LRA client determines the new LRA URL

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/couchbase-component.adoc
components/camel-couchbase/src/generated/java/org/apache/camel/component/couchbase/CouchbaseEndpointUriFactory.java
components/camel-couchbase/src/generated/resources/org/apache/camel/component/couchbase/couchbase.json
components/camel-couchbase/src/main/docs/couchbase-component.adoc
components/camel-couchbase/src/main/java/org/apache/camel/component/couchbase/CouchbaseEndpoint.java
core/camel-componentdsl/src/generated/resources/metadata.json
core/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/StaticEndpointBuilders.java
core/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/dsl/CouchbaseEndpointBuilderFactory.java
docs/components/modules/ROOT/pages/couchbase-component.adoc

CAMEL-16284: fix incorrect URI for couchbase

---

core/camel-core/src/test/java/org/apache/camel/impl/engine/DefaultPackageScanResourceResolverTest.java
core/camel-core/src/test/java/org/apache/camel/model/LoadRestFromXmlTest.java
core/camel-core/src/test/java/org/apache/camel/model/LoadRouteFromXmlTest.java
dsl/camel-xml-io-dsl/src/test/java/org/apache/camel/dsl/xml/io/XmlLoadRestTest.java
dsl/camel-xml-io-dsl/src/test/java/org/apache/camel/dsl/xml/io/XmlLoadTest.java
dsl/camel-xml-io-dsl/src/test/java/org/apache/camel/dsl/xml/io/XmlMainTest.java
dsl/camel-xml-io-dsl/src/test/resources/org/apache/camel/dsl/xml/io/barRest.xml
dsl/camel-xml-io-dsl/src/test/resources/org/apache/camel/dsl/xml/io/barRoute.xml
dsl/camel-xml-jaxb-dsl/src/test/java/org/apache/camel/dsl/xml/jaxb/JaxbXmlLoadRestTest.java
dsl/camel-xml-jaxb-dsl/src/test/java/org/apache/camel/dsl/xml/jaxb/JaxbXmlLoadTest.java
dsl/camel-xml-jaxb-dsl/src/test/java/org/apache/camel/dsl/xml/jaxb/JaxbXmlMainTest.java
dsl/camel-xml-jaxb-dsl/src/test/resources/org/apache/camel/dsl/xml/jaxb/barRest.xml
dsl/camel-xml-jaxb-dsl/src/test/resources/org/apache/camel/dsl/xml/jaxb/barRoute.xml

core: move route builder loader tests from core to dsl

---

components/camel-google-pubsub/src/test/java/org/apache/camel/component/google/pubsub/integration/DeadLetterTest.java

camel-google-pubsub: fixed incorrect creation of the dead-letter topic

---

core/camel-core-engine/src/main/docs/modules/eips/pages/idempotentConsumer-eip.adoc

Added links to hbase idempotent repository.

Update idempotentConsumer-eip.adoc : Added hbase idempotent repository link

---

components/camel-azure-storage-datalake/pom.xml
components/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/client/DataLakeFileClientWrapper.java
components/camel-azure-storage-datalake/src/test/java/org/apache/camel/component/azure/storage/datalake/integration/DataLakeProducerIT.java
core/camel-util/src/main/java/org/apache/camel/util/SkipLastByteInputStream.java
core/camel-util/src/test/java/org/apache/camel/util/SkipLastNewlineInputStreamTest.java

CAMEL-16307 azure-storage-datalake:...?operation=getFile appends newline

---

components/camel-splunk/src/main/java/org/apache/camel/component/splunk/SplunkConnectionFactory.java
components/camel-splunk/src/test/java/org/apache/camel/component/splunk/SplunkComponentConfigurationTest.java

fixes https://issues.apache.org/jira/browse/CAMEL-16313

CAMEL-16313 camel-splunk: allow anonymous access

---

components/camel-slack/src/main/java/org/apache/camel/component/slack/SlackComponentVerifierExtension.java
components/camel-slack/src/main/java/org/apache/camel/component/slack/SlackConsumer.java
components/camel-slack/src/main/java/org/apache/camel/component/slack/SlackProducer.java
components/camel-slack/src/main/java/org/apache/camel/component/slack/helper/SlackHelper.java
components/camel-slack/src/test/java/org/apache/camel/component/slack/SlackHelperTest.java

CAMEL-16328: Restore support for Slack custom server URL

---

components/camel-mongodb3/src/main/java/org/apache/camel/component/mongodb3/converters/MongoDbBasicConverters.java
components/camel-mongodb3/src/test/java/org/apache/camel/component/mongodb3/MongoDbConversionsTest.java

Backporting an issue fixed via #5177

[Backport] fix(mongodb): converter failure

---

test-infra/camel-test-infra-google-pubsub/src/test/java/org/apache/camel/test/infra/google/pubsub/services/GooglePubSubLocalContainerService.java

camel-test-infra-google-pubsub: fixed missing property registration

---

components/camel-azure/camel-azure-eventhubs/pom.xml
components/camel-azure/camel-azure-storage-blob/pom.xml
components/camel-azure/camel-azure-storage-datalake/pom.xml
components/camel-azure/camel-azure-storage-queue/pom.xml
parent/pom.xml
test-infra/camel-test-infra-azure-storage-blob/pom.xml
test-infra/camel-test-infra-azure-storage-datalake/pom.xml
test-infra/camel-test-infra-azure-storage-queue/pom.xml

CAMEL-16278: Migrate Azure dependencies to central Bom management

---

components/camel-bindy/src/main/docs/bindy-dataformat.adoc

FUSEDOC - 3102 - Made changes to CSVrecord section of bindy data format

Changes made to CSVrecord section

---

components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/BindyAbstractFactory.java
components/camel-cdi/src/main/java/org/apache/camel/cdi/CdiCamelExtension.java
components/camel-csv/src/main/java/org/apache/camel/dataformat/csv/CsvMarshaller.java
components/camel-cxf/src/main/java/org/apache/camel/component/cxf/CxfPayload.java
components/camel-dns/src/main/java/org/apache/camel/component/dns/policy/DnsActivationPolicy.java
components/camel-http-common/src/main/java/org/apache/camel/http/common/HttpServletResolveConsumerStrategy.java
components/camel-jetty-common/src/main/java/org/apache/camel/component/jetty/JettyHttpComponent.java
components/camel-olingo2/camel-olingo2-api/src/main/java/org/apache/camel/component/olingo2/api/impl/ODataPathSegmentImpl.java
components/camel-resteasy/src/main/java/org/apache/camel/component/resteasy/servlet/ResteasyCamelServlet.java
components/camel-splunk/src/main/java/org/apache/camel/component/splunk/event/SplunkEvent.java
components/camel-spring-ws/src/main/java/org/apache/camel/component/spring/ws/bean/CamelEndpointMapping.java
components/camel-spring-ws/src/main/java/org/apache/camel/component/spring/ws/bean/WSACamelEndpointMapping.java
components/camel-stomp/src/main/java/org/apache/camel/component/stomp/StompEndpoint.java
components/camel-undertow/src/main/java/org/apache/camel/component/undertow/DefaultUndertowHttpBinding.java
components/camel-xmlsecurity/src/main/java/org/apache/camel/component/xmlsecurity/processor/XmlSignatureProcessor.java
core/camel-health/src/main/java/org/apache/camel/impl/health/RoutesHealthCheckRepository.java
core/camel-main/src/main/java/org/apache/camel/main/BaseMainSupport.java
core/camel-xml-jaxb/src/main/java/org/apache/camel/xml/jaxb/JaxbModelToXMLDumper.java
init/camel-bundle-plugin/src/main/java/org/apache/felix/bundleplugin/VersionCleanerPlugin.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/ComponentDslMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointDslMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/GenerateEndpointUriFactoryMojo.java

Avoid the additional overhead caused by hashCode and equals when using Map's keySet and get altogether

(chores): rework the calls to Map's keySet

---

components/camel-activemq/src/test/java/org/apache/camel/component/activemq/AMQ2240Test.java
components/camel-activemq/src/test/java/org/apache/camel/component/activemq/AMQ2611Test.java
components/camel-activemq/src/test/java/org/apache/camel/component/activemq/ActiveMQJmsHeaderRouteTest.java
components/camel-activemq/src/test/java/org/apache/camel/component/activemq/AdvisoryConsumerExample.java
components/camel-activemq/src/test/java/org/apache/camel/component/activemq/ComplexRequestReplyTest.java
components/camel-activemq/src/test/java/org/apache/camel/component/activemq/DlqTest.java
components/camel-activemq/src/test/java/org/apache/camel/component/activemq/InvokeRequestReplyUsingJmsReplyToHeaderTest.java
components/camel-activemq/src/test/java/org/apache/camel/component/activemq/JmsBridge.java
components/camel-activemq/src/test/java/org/apache/camel/component/activemq/JmsConsumeSendTransacted.java
components/camel-activemq/src/test/java/org/apache/camel/component/activemq/JmsJdbcXARollbackTest.java
components/camel-activemq/src/test/java/org/apache/camel/component/activemq/JmsJdbcXATest.java
components/camel-activemq/src/test/java/org/apache/camel/component/activemq/JmsSimpleRequestReplyTest.java
components/camel-activemq/src/test/java/org/apache/camel/component/activemq/MyBean.java
components/camel-activemq/src/test/java/org/apache/camel/component/activemq/SetHeaderTest.java
components/camel-activemq/src/test/java/org/apache/camel/component/activemq/TransactedConsumeTest.java
components/camel-activemq/src/test/java/org/apache/camel/component/activemq/converter/ConsumerBean.java
components/camel-activemq/src/test/java/org/apache/camel/component/activemq/converter/InvokeMessageListenerTest.java

- remove unused exceptions
- cleanup tests that check for exceptions thrown
- use log markers for the test log messages
- use simpler assertions when possible
- minor test cleanups: use lambdas when cleaner, fixed typos
- ensure tests have assertions

(chores): cleanup camel-activemq tests

---

core/camel-core-engine/src/main/docs/modules/eips/pages/change-data-capture.adoc

Updated link to Camel Debezium example

---

components/camel-hdfs/src/test/java/org/apache/camel/component/hdfs/integration/HdfsAppendTest.java

To avoid failing for users on Mac OS until we have time to identify the root cause

camel-hdfs: temporarily disabled the HDFS Append Test due to CAMEL-16387

---

core/camel-core-model/src/main/java/org/apache/camel/builder/RouteBuilder.java
core/camel-core-model/src/main/java/org/apache/camel/model/RouteTemplatesDefinition.java
core/camel-core/src/test/java/org/apache/camel/builder/RouteTemplateErrorHandlerTest.java

CAMEL-16401: Ensure Route Templates inherit the error handler from the RouteBuilder

---

components/camel-sql/src/main/java/org/apache/camel/processor/idempotent/jdbc/JdbcMessageIdRepository.java

Logged:
ERROR org.apache.camel.processor.idempotent.jdbc.JdbcMessageIdRepository - Can't create table for JdbcMessageIdRepository with query 'CREATE TABLE CAMEL_MESSAGEPROCESSED (processorName VARCHAR(255), messageId VARCHAR(100), createdAt TIMESTAMP)' because of: StatementCallback; bad SQL grammar [SELECT 1 FROM CAMEL_MESSAGEPROCESSED WHERE 1 = 0]; nested exception is org.postgresql.util.PSQLException: ERROR: relation "camel_messageprocessed" does not exist
Position: 15. This may be a permissions problem. Please create this table and try again.
Actual cause:
StatementCallback; uncategorized SQLException for SQL [CREATE TABLE CAMEL_MESSAGEPROCESSED (processorName VARCHAR(255), messageId VARCHAR(100), createdAt TIMESTAMP)]; SQL state [25P02]; error code [0]; ERROR: current transaction is …

Fix wrong cause logged in JdbcMessageIdRepository

---

components/camel-djl/src/test/java/org/apache/camel/component/djl/ImageClassificationTest.java
components/camel-djl/src/test/java/org/apache/camel/component/djl/ObjectDetectionTest.java
components/camel-djl/src/test/java/org/apache/camel/component/djl/training/MnistTraining.java
parent/pom.xml

Implementation of https://issues.apache.org/jira/browse/CAMEL-16416
Upgrade Deep Java Library to the latest version (0.10.0)

CAMEL-16416. Upgrade DJL to 0.10.0

---

core/camel-core-engine/src/main/docs/antora.yml
docs/components/antora.yml

Docs 3.9.x

---

components/camel-kafka/src/main/docs/kafka-component.adoc

(chores) minor typo fix in camel-kafka documentation

---

components/camel-seda/src/main/docs/seda-component.adoc

I'm just not sure about the sentence with `@Consume`.

Polish seda multipleConsumers docs

---

components/camel-couchbase/src/main/java/org/apache/camel/component/couchbase/CouchbaseCollectionOperation.java
components/camel-couchbase/src/main/java/org/apache/camel/component/couchbase/CouchbaseConsumer.java
components/camel-couchbase/src/main/java/org/apache/camel/component/couchbase/CouchbaseEndpoint.java
components/camel-couchbase/src/main/java/org/apache/camel/component/couchbase/CouchbaseProducer.java

CAMEL-16439: improve timeout and retry strategy

---

components/camel-sql/src/main/java/org/apache/camel/component/sql/stored/SqlStoredComponent.java
components/camel-sql/src/main/java/org/apache/camel/component/sql/stored/TemplateStoredProcedure.java

CAMEL-16405 Added support for query timeout in sql-stored component

CAMEL-16405 Added statement query timeout in sql-stored component

---

test-infra/camel-test-infra-common/src/test/java/org/apache/camel/test/infra/common/services/ContainerEnvironmentUtil.java

CAMEL-16400: conditionally determine test execution based on environment availability

---

components/camel-jsonpath/pom.xml
components/camel-jsonpath/src/main/java/org/apache/camel/jsonpath/JsonPathEngine.java
components/camel-jsonpath/src/test/java/org/apache/camel/jsonpath/JsonPathPlatformHttpTest.java
docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_10.adoc

Issue: https://issues.apache.org/jira/browse/CAMEL-16459

CAMEL-16459 jsonpath and platform-http-vertx causes PathNotFoundException

---

components/camel-sql/src/main/docs/sql-stored-component.adoc
components/camel-sql/src/main/java/org/apache/camel/component/sql/stored/SqlStoredEndpoint.java

CAMEL-1640 query timeout option is added in the documentation.

CAMEL-1640 Added documentation to set query timeout in sql-stored

---

components/camel-arangodb/pom.xml
components/camel-arangodb/src/test/java/org/apache/camel/component/arangodb/integration/ArangoCollectionDeleteIT.java
components/camel-arangodb/src/test/java/org/apache/camel/component/arangodb/integration/ArangoCollectionFindByKeyIT.java
components/camel-arangodb/src/test/java/org/apache/camel/component/arangodb/integration/ArangoCollectionQueryIT.java
components/camel-arangodb/src/test/java/org/apache/camel/component/arangodb/integration/ArangoCollectionSaveIT.java
components/camel-arangodb/src/test/java/org/apache/camel/component/arangodb/integration/ArangoCollectionUpdateIT.java
components/camel-arangodb/src/test/java/org/apache/camel/component/arangodb/integration/ArangoGraphEdgeIT.java
components/camel-arangodb/src/test/java/org/apache/camel/component/arangodb/integration/ArangoGraphQueriesIT.java
components/camel-arangodb/src/test/java/org/apache/camel/component/arangodb/integration/ArangoGraphVertexIT.java
components/camel-arangodb/src/test/java/org/apache/camel/component/arangodb/integration/BaseArangoDb.java
components/camel-arangodb/src/test/java/org/apache/camel/component/arangodb/integration/BaseCollection.java
components/camel-arangodb/src/test/java/org/apache/camel/component/arangodb/integration/BaseGraph.java
components/camel-arangodb/src/test/java/org/apache/camel/component/arangodb/integration/TestDocumentEntity.java
components/camel-arangodb/src/test/java/org/apache/camel/component/arangodb/integration/TestEntity.java

CAMEL-16400: split unit and integration tests for camel-arangodb

---

test-infra/camel-test-infra-common/src/test/java/org/apache/camel/test/infra/common/services/SimpleTestServiceBuilder.java

camel-test-infra-common: fixed incorrect exception message

---

components/camel-jpa/src/main/java/org/apache/camel/component/jpa/JpaHelper.java

CAMEL-16470 - fix for reuse EntityManager

---

components/camel-azure/camel-azure-eventhubs/pom.xml
components/camel-azure/camel-azure-eventhubs/src/test/java/org/apache/camel/component/azure/eventhubs/integration/EventHubsConsumerIT.java
components/camel-azure/camel-azure-eventhubs/src/test/java/org/apache/camel/component/azure/eventhubs/integration/EventHubsProducerIT.java
components/camel-azure/camel-azure-eventhubs/src/test/java/org/apache/camel/component/azure/eventhubs/integration/EventProcessorIT.java
components/camel-azure/camel-azure-eventhubs/src/test/java/org/apache/camel/component/azure/eventhubs/integration/operations/EventHubsProducerOperationsIT.java
components/camel-azure/camel-azure-storage-blob/pom.xml
components/camel-azure/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/Base.java
components/camel-azure/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BlobConsumerIT.java
components/camel-azure/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BlobContainerOperationsIT.java
components/camel-azure/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BlobOperationsIT.java
components/camel-azure/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BlobProducerIT.java
components/camel-azure/camel-azure-storage-datalake/pom.xml
components/camel-azure/camel-azure-storage-datalake/src/test/java/org/apache/camel/component/azure/storage/datalake/integration/Base.java
components/camel-azure/camel-azure-storage-datalake/src/test/java/org/apache/camel/component/azure/storage/datalake/integration/DataLakeConsumerIT.java
components/camel-azure/camel-azure-storage-datalake/src/test/java/org/apache/camel/component/azure/storage/datalake/integration/DataLakeFileOperationIT.java
components/camel-azure/camel-azure-storage-datalake/src/test/java/org/apache/camel/component/azure/storage/datalake/integration/DataLakeFileSystemOperationIT.java
components/camel-azure/camel-azure-storage-datalake/src/test/java/org/apache/camel/component/azure/storage/datalake/integration/DataLakeProducerIT.java
components/camel-azure/camel-azure-storage-queue/pom.xml
components/camel-azure/camel-azure-storage-queue/src/test/java/org/apache/camel/component/azure/storage/queue/QueueTestUtils.java
components/camel-azure/camel-azure-storage-queue/src/test/java/org/apache/camel/component/azure/storage/queue/integration/QueueConsumerIT.java
components/camel-azure/camel-azure-storage-queue/src/test/java/org/apache/camel/component/azure/storage/queue/integration/QueueProducerIT.java
components/camel-azure/camel-azure-storage-queue/src/test/java/org/apache/camel/component/azure/storage/queue/operations/integration/QueueOperationsIT.java
components/camel-azure/camel-azure-storage-queue/src/test/java/org/apache/camel/component/azure/storage/queue/operations/integration/QueueServiceOperationsIT.java

* split unit and integration tests for camel-azure-eventhubs
* split unit and integration tests for camel-azure-storage-blob
* split unit and integration tests for camel-azure-storage-datalake
* split unit and integration tests for camel-azure-storage-queue
Similar to other ones provided earlier. Like the ones for aws, it removes the needs for profiles to trigger the manual tests (they are managed by JUnit 5 @EnabledIf conditions).

CAMEL-16400: split unit and integration tests (azure components)

---

components/camel-cassandraql/pom.xml
components/camel-cassandraql/src/test/java/org/apache/camel/component/cassandra/integration/BaseCassandra.java
components/camel-cassandraql/src/test/java/org/apache/camel/component/cassandra/integration/CassandraComponentBeanRefIT.java
components/camel-cassandraql/src/test/java/org/apache/camel/component/cassandra/integration/CassandraComponentConsumerIT.java
components/camel-cassandraql/src/test/java/org/apache/camel/component/cassandra/integration/CassandraComponentProducerIT.java
components/camel-cassandraql/src/test/java/org/apache/camel/component/cassandra/integration/CassandraComponentProducerUnpreparedIT.java
components/camel-cassandraql/src/test/java/org/apache/camel/processor/aggregate/cassandra/CassandraAggregationIT.java
components/camel-cassandraql/src/test/java/org/apache/camel/processor/aggregate/cassandra/CassandraAggregationRepositoryIT.java
components/camel-cassandraql/src/test/java/org/apache/camel/processor/aggregate/cassandra/CassandraAggregationSerializedHeadersIT.java
components/camel-cassandraql/src/test/java/org/apache/camel/processor/aggregate/cassandra/NamedCassandraAggregationRepositoryIT.java
components/camel-cassandraql/src/test/java/org/apache/camel/processor/idempotent/cassandra/CassandraIdempotentIT.java
components/camel-cassandraql/src/test/java/org/apache/camel/processor/idempotent/cassandra/CassandraIdempotentRepositoryIT.java
components/camel-cassandraql/src/test/java/org/apache/camel/processor/idempotent/cassandra/NamedCassandraIdempotentRepositoryIT.java

CAMEL-16400: split unit and integration tests for camel-cassandraql

---

components/camel-consul/pom.xml
components/camel-consul/src/test/java/org/apache/camel/component/consul/ConsulCatalogIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/ConsulClientKeyValueIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/ConsulCoordinatesIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/ConsulEventIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/ConsulEventWatchIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/ConsulHealthIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/ConsulKeyValueIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/ConsulKeyValueWatchIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/ConsulRegistryIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/ConsulSessionIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cloud/ConsulDefaultServiceCallRouteIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cloud/ConsulRibbonServiceCallRouteIR.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cloud/ConsulServiceCallWithRegistrationIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cloud/ConsulServiceDiscoveryIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cloud/ConsulServiceRegistrationWithRoutePolicyAndMetadataIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cloud/ConsulServiceRegistrationWithRoutePolicyFactoryIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cloud/ConsulServiceRegistrationWithRoutePolicyIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cloud/ConsulServiceRegistrationWithServiceComponentIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cloud/ConsulServiceRegistryIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cloud/SpringConsulDefaultServiceCallRouteIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cloud/SpringConsulExpressionServiceCallRouteIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cloud/SpringConsulRibbonServiceCallRouteIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cluster/ConsulClusterViewIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cluster/ConsulClusteredRoutePolicyFactoryIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cluster/ConsulClusteredRoutePolicyIT.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/cluster/ConsulMasterIT.java

CAMEL-16400: split unit and integration tests for camel-consul

---

components/camel-kafka/src/main/docs/kafka-component.adoc
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConstants.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaProducer.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaProducerTest.java

"CAMEL-16414:camel-kafka set custom timestamp"

---

core/camel-core-engine/src/main/docs/modules/eips/pages/choice-eip.adoc

Need to add proper endChoice() and end() blocks to show correct way to work with choices(as a best practice).
Since this is quite fundamental requirement, it is necessary to have complete documentation stating all facts.
Also not sure about following:
1. Do we need to add endChoice() after otherwise()?
2. Do we need to make any changes in xml based configuration or it ends by default?(I suppose it works by default)?
3. Do we also need to document meaning of endChoice() and end()?
4. Additionally, should we mention limitation on loop nesting in documentation, an example would also add value.

Add proper endChoice() and end() blocks

---

components/camel-couchbase/pom.xml
components/camel-couchbase/src/test/java/org/apache/camel/component/couchbase/integration/ConsumeMessagesWithLimitIT.java
components/camel-couchbase/src/test/java/org/apache/camel/component/couchbase/integration/CouchbaseIntegrationTestBase.java
components/camel-couchbase/src/test/java/org/apache/camel/component/couchbase/integration/ProduceMessagesSimpleIT.java
components/camel-couchbase/src/test/java/org/apache/camel/component/couchbase/integration/ProduceMessagesWithAutoIDIT.java
components/camel-couchbase/src/test/java/org/apache/camel/component/couchbase/integration/RemoveMessagesIT.java

CAMEL-16400: split unit and integration tests for camel-couchbase

---

components/camel-couchdb/pom.xml
components/camel-couchdb/src/test/java/org/apache/camel/component/couchdb/integration/CouchDbCrudIT.java
components/camel-couchdb/src/test/java/org/apache/camel/component/couchdb/integration/CouchDbTestSupport.java

CAMEL-16400: split unit and integration tests for camel-couchdb

---

components/camel-elasticsearch-rest/pom.xml
components/camel-elasticsearch-rest/src/test/java/org/apache/camel/component/elasticsearch/integration/ElasticsearchBulkIT.java
components/camel-elasticsearch-rest/src/test/java/org/apache/camel/component/elasticsearch/integration/ElasticsearchClusterIndexIT.java
components/camel-elasticsearch-rest/src/test/java/org/apache/camel/component/elasticsearch/integration/ElasticsearchGetSearchDeleteExistsUpdateIT.java
components/camel-elasticsearch-rest/src/test/java/org/apache/camel/component/elasticsearch/integration/ElasticsearchIndexIT.java
components/camel-elasticsearch-rest/src/test/java/org/apache/camel/component/elasticsearch/integration/ElasticsearchPingIT.java
components/camel-elasticsearch-rest/src/test/java/org/apache/camel/component/elasticsearch/integration/ElasticsearchScrollSearchIT.java
components/camel-elasticsearch-rest/src/test/java/org/apache/camel/component/elasticsearch/integration/ElasticsearchSizeLimitIT.java
components/camel-elasticsearch-rest/src/test/java/org/apache/camel/component/elasticsearch/integration/ElasticsearchTestSupport.java

CAMEL-16400: split unit and integration tests for camel-elasticsearch-rest

---

components/camel-etcd/pom.xml
components/camel-etcd/src/test/java/org/apache/camel/component/etcd/cloud/integration/EtcdServiceCallRouteIT.java
components/camel-etcd/src/test/java/org/apache/camel/component/etcd/cloud/integration/EtcdServiceDiscoveryIT.java
components/camel-etcd/src/test/java/org/apache/camel/component/etcd/cloud/integration/SpringEtcdServiceCallDefaultRouteIT.java
components/camel-etcd/src/test/java/org/apache/camel/component/etcd/cloud/integration/SpringEtcdServiceCallRouteIT.java
components/camel-etcd/src/test/java/org/apache/camel/component/etcd/integration/EtcdKeysIT.java
components/camel-etcd/src/test/java/org/apache/camel/component/etcd/integration/EtcdStatsIT.java
components/camel-etcd/src/test/java/org/apache/camel/component/etcd/integration/EtcdWatchIT.java

CAMEL-16400: split unit and integration tests for camel-etcd

---

components/camel-aws/camel-aws-secrets-manager/src/test/java/org/apache/camel/component/aws/secretsmanager/SecretsManagerComponentConfigurationTest.java

(chores) camel-aws-secret-manager: fix checkstyle issue

---

components/camel-fhir/camel-fhir-component/pom.xml
components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/Hl7v2PatientToFhirPatientIT.java

CAMEL-16400: split unit and integration tests for camel-fhir

---

components/camel-google/camel-google-pubsub/pom.xml
components/camel-google/camel-google-pubsub/src/test/java/org/apache/camel/component/google/pubsub/integration/AckModeNoneIT.java
components/camel-google/camel-google-pubsub/src/test/java/org/apache/camel/component/google/pubsub/integration/AcknowledgementIT.java
components/camel-google/camel-google-pubsub/src/test/java/org/apache/camel/component/google/pubsub/integration/BodyTypesIT.java
components/camel-google/camel-google-pubsub/src/test/java/org/apache/camel/component/google/pubsub/integration/CustomSerializerIT.java
components/camel-google/camel-google-pubsub/src/test/java/org/apache/camel/component/google/pubsub/integration/DeadLetterIT.java
components/camel-google/camel-google-pubsub/src/test/java/org/apache/camel/component/google/pubsub/integration/GroupedExchangeRoundtripIT.java
components/camel-google/camel-google-pubsub/src/test/java/org/apache/camel/component/google/pubsub/integration/MessageOrderingIT.java
components/camel-google/camel-google-pubsub/src/test/java/org/apache/camel/component/google/pubsub/integration/SingleExchangeRoundtripIT.java

CAMEL-16400: split unit and integration tests for camel-google-pubsub

---

components/camel-hbase/pom.xml
components/camel-hbase/src/test/java/org/apache/camel/component/hbase/CamelHBaseFilterIT.java
components/camel-hbase/src/test/java/org/apache/camel/component/hbase/HBaseComponentIT.java
components/camel-hbase/src/test/java/org/apache/camel/component/hbase/HBaseConsumerIT.java
components/camel-hbase/src/test/java/org/apache/camel/component/hbase/HBaseConvertionsIT.java
components/camel-hbase/src/test/java/org/apache/camel/component/hbase/HBaseProducerIT.java
components/camel-hbase/src/test/java/org/apache/camel/component/hbase/processor/idempotent/HBaseIdempotentRepositoryIT.java

CAMEL-16400: split unit and integration tests for camel-hbase

---

components/camel-hdfs/pom.xml
components/camel-hdfs/src/test/java/org/apache/camel/component/hdfs/integration/HdfsAppendIT.java
components/camel-hdfs/src/test/java/org/apache/camel/component/hdfs/integration/HdfsConsumerIntegrationIT.java
components/camel-hdfs/src/test/java/org/apache/camel/component/hdfs/integration/HdfsProducerConsumerIntegrationIT.java

CAMEL-16400: split unit and integration tests for camel-hdfs

---

components/camel-vertx-kafka/camel-vertx-kafka-component/src/main/docs/vertx-kafka-component.adoc
components/camel-vertx-kafka/camel-vertx-kafka-component/src/main/java/org/apache/camel/component/vertx/kafka/VertxKafkaConfigurationOptionsProxy.java
components/camel-vertx-kafka/camel-vertx-kafka-component/src/main/java/org/apache/camel/component/vertx/kafka/VertxKafkaConstants.java
components/camel-vertx-kafka/camel-vertx-kafka-component/src/main/java/org/apache/camel/component/vertx/kafka/operations/VertxKafkaProducerOperations.java
components/camel-vertx-kafka/camel-vertx-kafka-component/src/test/java/org/apache/camel/component/vertx/kafka/operations/VertxKafkaProducerOperationsTest.java

"CAMEL-16481:camel-vertx-kafka set custom timestamp"

---

components/pom.xml
pom.xml

Work-around SUREFIRE-1831 which affects the execution of some integration tests

---

components/camel-infinispan/camel-infinispan/pom.xml
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteAggregationRepositoryIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteAggregationRepositoryOperationsIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteConfigurationIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteConsumerIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteCustomListenerIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteIdempotentRepositoryIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteProducerIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteQueryConsumerIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteQueryProducerIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/cluster/AbstractInfinispanRemoteClusteredIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/cluster/InfinispanRemoteClusteredViewIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/spring/SpringInfinispanRemoteIdempotentRepositoryCamelIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/spring/SpringInfinispanRemoteIdempotentRepositorySpringIT.java

CAMEL-16400: split unit and integration tests for camel-infinispan

---

components/camel-kafka/pom.xml
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/BaseEmbeddedKafkaTestSupport.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerBatchSizeIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerFullIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerLastRecordHeaderIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerManualCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerRebalanceIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerTopicIsPatternIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaProducerFullIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaToDIT.java
components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryEagerIT.java
components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryNonEagerIT.java
components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryPersistenceIT.java

CAMEL-16400: split unit and integration tests for camel-kafka

---

components/camel-minio/pom.xml
components/camel-minio/src/test/java/org/apache/camel/component/minio/integration/MinioComponentIT.java
components/camel-minio/src/test/java/org/apache/camel/component/minio/integration/MinioConsumerIT.java
components/camel-minio/src/test/java/org/apache/camel/component/minio/integration/MinioCopyObjectOperationIT.java
components/camel-minio/src/test/java/org/apache/camel/component/minio/integration/MinioDeleteBucketOperationIT.java
components/camel-minio/src/test/java/org/apache/camel/component/minio/integration/MinioIntegrationTestSupport.java
components/camel-minio/src/test/java/org/apache/camel/component/minio/integration/MinioListObjectsOperationIT.java
components/camel-minio/src/test/java/org/apache/camel/component/minio/integration/MinioObjectRangeOperationIT.java

CAMEL-16400: split unit and integration tests for camel-minio

---

components/camel-pg-replication-slot/pom.xml
components/camel-pg-replication-slot/src/test/java/org/apache/camel/component/pg/replication/slot/integration/PgReplicationITSupport.java
components/camel-pg-replication-slot/src/test/java/org/apache/camel/component/pg/replication/slot/integration/PgReplicationSlotCamelIT.java

CAMEL-16400: split unit and integration tests for camel-pq-replication-slot

---

components/camel-mongodb/pom.xml
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/AbstractMongoDbITSupport.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbAggregateOperationIT.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbBigDecimalConverterIT.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbBulkWriteOperationIT.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbChangeStreamsConsumerIT.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbConnectionBeansIT.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbConversionsIT.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbDynamicityIT.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbExceptionHandlingIT.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbFindOperationIT.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbHeaderHandlingIT.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbIndexIT.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbInsertBatchIT.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbOperationsIT.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbOutputTypeIT.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbReadPreferenceOptionIT.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbSpringDslOperationsIT.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbStopEndpointIT.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbTailableCursorConsumerIT.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/meta/integration/MongoDbMetaExtensionIT.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/processor/idempotent/integration/MongoDbIdempotentRepositoryIT.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/verifier/integration/MongoDbVerifierExtensionIT.java

CAMEL-16400: split unit and integration tests for camel-mongodb

---

components/camel-mongodb-gridfs/pom.xml
components/camel-mongodb-gridfs/src/test/java/org/apache/camel/component/mongodb/gridfs/integration/AbstractMongoDbITSupport.java
components/camel-mongodb-gridfs/src/test/java/org/apache/camel/component/mongodb/gridfs/integration/GridFsConsumerIT.java
components/camel-mongodb-gridfs/src/test/java/org/apache/camel/component/mongodb/gridfs/integration/GridFsProducerOperationsIT.java

CAMEL-16400: split unit and integration tests for camel-mongodb-gridfs

---

components/camel-nsq/pom.xml
components/camel-nsq/src/test/java/org/apache/camel/component/nsq/integration/NsqConsumerIT.java
components/camel-nsq/src/test/java/org/apache/camel/component/nsq/integration/NsqITSupport.java
components/camel-nsq/src/test/java/org/apache/camel/component/nsq/integration/NsqProducerIT.java

CAMEL-16400: split unit and integration tests for camel-nsq

---

components/camel-cxf/pom.xml
components/camel-cxf/src/main/resources/META-INF/spring.schemas
components/camel-spring-integration/src/main/resources/META-INF/spring.schemas
components/camel-spring-security/pom.xml
components/camel-spring-security/src/main/resources/META-INF/spring.schemas
components/camel-spring-xml/pom.xml
components/camel-spring-xml/src/main/resources/META-INF/spring.schemas

Perviously the generated schemes will have unresolved camel version, e.g: 
```
http\://camel.apache.org/schema/spring=org.apache.camel.spring.xml.handler.CamelNamespaceHandler
http\://camel.apache.org/schema/spring/v${camel.schema.version}=org.apache.camel.spring.xml.handler.CamelNamespaceHandler
```
and 
```
http\://camel.apache.org/schema/spring/camel-spring.xsd=camel-spring.xsd
http\://camel.apache.org/schema/spring=camel-spring.xsd
http\://camel.apache.org/schema/spring/v${camel.schema.version}=camel-spring-v${camel.schema.version}.xsd
http\://camel.apache.org/schema/spring/camel-spring-2.0-M1.xsd=camel-spring.xsd
http\://camel.apache.org/schema/spring/camel-spring-2.0-M2.xsd=camel-spring.xsd
http\://camel.apache.org/schema/spring/camel-spring-2.0-M3.xsd=camel-spring.xsd …
```

CAMEL-16503: Fix unresolved camel version in the generated spring schemas

---

components/camel-redis/pom.xml
components/camel-redis/src/test/java/org/apache/camel/component/redis/processor/aggregate/integration/AggregateRedisIT.java
components/camel-redis/src/test/java/org/apache/camel/component/redis/processor/aggregate/integration/MyAggregationStrategy.java

CAMEL-16400: split unit and integration tests for camel-redis

---

components/camel-xmpp/pom.xml
components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/GoogleTalkTest.java
components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/integration/XmppBaseIT.java
components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/integration/XmppMultiUserChatIT.java
components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/integration/XmppProducerConcurrentIT.java
components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/integration/XmppRouteChatIT.java
components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/integration/XmppRouteIT.java
components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/integration/XmppRouteMultipleProducersSingleConsumerIT.java

CAMEL-16400: split unit and integration tests for camel-xmpp

---

core/camel-core-model/src/main/java/org/apache/camel/model/KameletDefinition.java
dsl/camel-yaml-dsl/camel-yaml-dsl-common/src/main/java/org/apache/camel/dsl/yaml/common/YamlDeserializationContext.java
dsl/camel-yaml-dsl/camel-yaml-dsl-common/src/main/java/org/apache/camel/dsl/yaml/common/YamlDeserializationMode.java
dsl/camel-yaml-dsl/camel-yaml-dsl-common/src/main/java/org/apache/camel/dsl/yaml/common/YamlDeserializerBase.java
dsl/camel-yaml-dsl/camel-yaml-dsl-common/src/main/java/org/apache/camel/dsl/yaml/common/YamlDeserializerSupport.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/pom.xml
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/ModelDeserializers.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/ModelDeserializersResolver.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/CustomResolver.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/KameletDeserializer.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/RouteDefinitionDeserializer.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/RouteFromDefinitionDeserializer.java
dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/src/main/java/org/apache/camel/maven/dsl/yaml/GenerateYamlDeserializersMojo.java
dsl/camel-yaml-dsl/camel-yaml-dsl/pom.xml
dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/camel-yaml-dsl.json
dsl/camel-yaml-dsl/camel-yaml-dsl/src/main/java/org/apache/camel/dsl/yaml/YamlRoutesBuilderLoader.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/AggregateTest.groovy
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/KameletTest.groovy
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/LoopTest.groovy
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/SplitTest.groovy
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/support/YamlTestSupport.groovy

see:
- https://issues.apache.org/jira/browse/CAMEL-16504
- https://issues.apache.org/jira/browse/CAMEL-16510

[CAMEL-16504] YAML Dsl : support for "flow" like route definition

---

components/camel-zookeeper/pom.xml
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/cloud/integration/SpringZooKeeperServiceCallRouteIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/cloud/integration/ZooKeeperServiceCallRouteIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/cloud/integration/ZooKeeperServiceDiscoveryIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/cloud/integration/ZooKeeperServiceRegistrationITBase.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/cloud/integration/ZooKeeperServiceRegistrationWithRoutePolicyAndMetadataIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/cloud/integration/ZooKeeperServiceRegistrationWithRoutePolicyFactoryIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/cloud/integration/ZooKeeperServiceRegistrationWithRoutePolicyIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/cloud/integration/ZooKeeperServiceRegistrationWithServiceComponentIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/cluster/integration/ZooKeeperClusteredRoutePolicyFactoryIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/cluster/integration/ZooKeeperClusteredRoutePolicyIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/cluster/integration/ZooKeeperMasterIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/integration/ConsumeChildrenIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/integration/ConsumeDataIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/integration/ZooKeeperITSupport.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/integration/ZooKeeperManagedEndpointIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/integration/ZooKeeperProducerIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/integration/ZookeeperConnectionManagerIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/operations/integration/AnyOfOperationIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/operations/integration/ChildrenChangedOperationIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/operations/integration/CreateOperationIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/operations/integration/DataChangedOperationIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/operations/integration/ExistenceChangedOperationIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/operations/integration/ExistenceOperationIT.java
components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/operations/integration/SetDataOperationIT.java

CAMEL-16400: split unit and integration tests for camel-zookeeper

---

components/camel-zookeeper-master/pom.xml
components/camel-zookeeper-master/src/test/java/org/apache/camel/component/zookeepermaster/integration/MasterEndpointFailoverIT.java

CAMEL-16400: split unit and integration tests for camel-zookeeper-master

---

components/camel-pulsar/pom.xml
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/integration/PulsarConcurrentConsumerInIT.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/integration/PulsarConcurrentProducerInIT.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/integration/PulsarConsumerDeadLetterPolicyIT.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/integration/PulsarConsumerInAsynchronousIT.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/integration/PulsarConsumerInIT.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/integration/PulsarConsumerNoAcknowledgementIT.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/integration/PulsarConsumerPatternInIT.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/integration/PulsarConsumerReadCompactedIT.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/integration/PulsarCustomMessageReceiptIT.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/integration/PulsarITSupport.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/integration/PulsarProducerHeadersInIT.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/integration/PulsarProducerInIT.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/integration/PulsarProducerUndefinedProducerNameInIT.java

CAMEL-16400: split unit and integration tests for camel-pulsar

---

components/camel-spring-rabbitmq/pom.xml
components/camel-spring-rabbitmq/src/test/java/org/apache/camel/component/springrabbit/integration/RabbitMQBasicIT.java
components/camel-spring-rabbitmq/src/test/java/org/apache/camel/component/springrabbit/integration/RabbitMQConsumerIT.java
components/camel-spring-rabbitmq/src/test/java/org/apache/camel/component/springrabbit/integration/RabbitMQConsumerPooledExchangeIT.java
components/camel-spring-rabbitmq/src/test/java/org/apache/camel/component/springrabbit/integration/RabbitMQConsumerQueuesIT.java
components/camel-spring-rabbitmq/src/test/java/org/apache/camel/component/springrabbit/integration/RabbitMQConsumerRoutingKeyIT.java
components/camel-spring-rabbitmq/src/test/java/org/apache/camel/component/springrabbit/integration/RabbitMQConsumerTopicIT.java
components/camel-spring-rabbitmq/src/test/java/org/apache/camel/component/springrabbit/integration/RabbitMQITSupport.java
components/camel-spring-rabbitmq/src/test/java/org/apache/camel/component/springrabbit/integration/RabbitMQInOutIT.java
components/camel-spring-rabbitmq/src/test/java/org/apache/camel/component/springrabbit/integration/RabbitMQPollingConsumerIT.java
components/camel-spring-rabbitmq/src/test/java/org/apache/camel/component/springrabbit/integration/RabbitMQProducerIT.java
components/camel-spring-rabbitmq/src/test/java/org/apache/camel/component/springrabbit/integration/RabbitMQProducerNullBodyIT.java
components/camel-spring-rabbitmq/src/test/java/org/apache/camel/component/springrabbit/integration/RabbitMQProducerToDIT.java

CAMEL-16400: split unit and integration tests for camel-spring-rabbitmq

---

components/camel-atom/pom.xml
components/camel-atom/src/test/java/org/apache/camel/component/atom/AtomEndpointTest.java
components/camel-atom/src/test/java/org/apache/camel/component/atom/AtomEntryPollingConsumerTest.java
components/camel-atom/src/test/java/org/apache/camel/component/atom/AtomEntryPollingConsumerWithBasicAuthTest.java
components/camel-atom/src/test/java/org/apache/camel/component/atom/AtomEntrySortTest.java
components/camel-atom/src/test/java/org/apache/camel/component/atom/AtomGoodBlogsTest.java
components/camel-atom/src/test/java/org/apache/camel/component/atom/AtomHttpConsumerTest.java
components/camel-atom/src/test/java/org/apache/camel/component/atom/AtomHttpNoCamelParametersTest.java
components/camel-atom/src/test/java/org/apache/camel/component/atom/AtomPollingConsumerIdleMessageTest.java
components/camel-atom/src/test/java/org/apache/camel/component/atom/AtomPollingConsumerTest.java
components/camel-atom/src/test/java/org/apache/camel/component/atom/AtomPollingConsumerWithBasicAuthTest.java
components/camel-atom/src/test/java/org/apache/camel/component/atom/AtomPollingLowDelayTest.java
components/camel-atom/src/test/java/org/apache/camel/component/atom/AtomPollingUnthrottledTest.java
components/camel-atom/src/test/java/org/apache/camel/component/atom/AtomProducerTest.java
components/camel-atom/src/test/java/org/apache/camel/component/atom/AtomRouteTest.java
components/camel-atom/src/test/java/org/apache/camel/component/atom/JettyTestServer.java
components/camel-atom/src/test/java/org/apache/camel/component/atom/UpdatedDateFilterTest.java
components/camel-iota/pom.xml
components/camel-iota/src/test/java/org/apache/camel/component/iota/IOTAProducerTest.java
components/camel-printer/pom.xml
components/camel-printer/src/test/java/org/apache/camel/component/printer/PrinterPrintTest.java

removes OS-specific profiles for camel-atom, camel-iota and camel-printer

(chores): use JUnit's 5 @DisabledOnOs for disabling tests on specific OSes

---

components/camel-docker/pom.xml

CAMEL-16400: split unit and integration tests for camel-docker

---

components/camel-google/camel-google-bigquery/ReadMe.md
components/camel-google/camel-google-bigquery/pom.xml
components/camel-google/camel-google-bigquery/src/test/java/org/apache/camel/component/google/bigquery/integration/AsyncIT.java
components/camel-google/camel-google-bigquery/src/test/java/org/apache/camel/component/google/bigquery/integration/BigQueryITSupport.java
components/camel-google/camel-google-bigquery/src/test/java/org/apache/camel/component/google/bigquery/integration/DynamicTableIdIT.java
components/camel-google/camel-google-bigquery/src/test/java/org/apache/camel/component/google/bigquery/integration/InsertIdIT.java
components/camel-google/camel-google-bigquery/src/test/java/org/apache/camel/component/google/bigquery/integration/SingleRowIT.java
components/camel-google/camel-google-bigquery/src/test/java/org/apache/camel/component/google/bigquery/integration/sql/SqlQueryFromResourceIT.java
components/camel-google/camel-google-bigquery/src/test/java/org/apache/camel/component/google/bigquery/integration/sql/SqlQueryIT.java
components/camel-google/camel-google-bigquery/src/test/java/org/apache/camel/component/google/bigquery/unit/sql/GoogleBigQuerySQLProducerWithParamersTest.java

CAMEL-16400: split unit and integration tests for camel-google-bigquery

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaComponent.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaEndpoint.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaProducer.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaAutowireTest.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaConsumerTest.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaProducerTest.java
components/camel-vertx-kafka/camel-vertx-kafka-component/src/main/java/org/apache/camel/component/vertx/kafka/VertxKafkaComponent.java
components/camel-vertx-kafka/camel-vertx-kafka-component/src/test/java/org/apache/camel/component/vertx/kafka/VertxKafkaAutowireTest.java
components/camel-vertx-kafka/camel-vertx-kafka-component/src/test/java/org/apache/camel/component/vertx/kafka/VertxKafkaComponentTest.java

Fix autowiring for kafka components

---

components/camel-google/camel-google-calendar/pom.xml
components/camel-google/camel-google-calendar/src/test/java/org/apache/camel/component/google/calendar/AbstractGoogleCalendarTestSupport.java
components/camel-google/camel-google-calendar/src/test/java/org/apache/camel/component/google/calendar/integration/CalendarAclIT.java
components/camel-google/camel-google-calendar/src/test/java/org/apache/camel/component/google/calendar/integration/CalendarCalendarListIT.java
components/camel-google/camel-google-calendar/src/test/java/org/apache/camel/component/google/calendar/integration/CalendarCalendarsIT.java
components/camel-google/camel-google-calendar/src/test/java/org/apache/camel/component/google/calendar/integration/CalendarColorsIT.java
components/camel-google/camel-google-calendar/src/test/java/org/apache/camel/component/google/calendar/integration/CalendarEventsIT.java
components/camel-google/camel-google-calendar/src/test/java/org/apache/camel/component/google/calendar/integration/CalendarFreebusyIT.java
components/camel-google/camel-google-calendar/src/test/java/org/apache/camel/component/google/calendar/integration/CalendarSettingsIT.java

CAMEL-16400: split unit and integration tests for camel-google-calendar

---

components/camel-google/camel-google-drive/pom.xml
components/camel-google/camel-google-drive/src/test/java/org/apache/camel/component/google/drive/AbstractGoogleDriveTestSupport.java
components/camel-google/camel-google-drive/src/test/java/org/apache/camel/component/google/drive/integration/DriveAboutIT.java
components/camel-google/camel-google-drive/src/test/java/org/apache/camel/component/google/drive/integration/DriveAppsIT.java
components/camel-google/camel-google-drive/src/test/java/org/apache/camel/component/google/drive/integration/DriveChangesIT.java
components/camel-google/camel-google-drive/src/test/java/org/apache/camel/component/google/drive/integration/DriveChildrenIT.java
components/camel-google/camel-google-drive/src/test/java/org/apache/camel/component/google/drive/integration/DriveCommentsIT.java
components/camel-google/camel-google-drive/src/test/java/org/apache/camel/component/google/drive/integration/DriveFilesIT.java
components/camel-google/camel-google-drive/src/test/java/org/apache/camel/component/google/drive/integration/DrivePermissionsIT.java
components/camel-google/camel-google-drive/src/test/java/org/apache/camel/component/google/drive/integration/DrivePropertiesIT.java
components/camel-google/camel-google-drive/src/test/java/org/apache/camel/component/google/drive/integration/DriveRepliesIT.java
components/camel-google/camel-google-drive/src/test/java/org/apache/camel/component/google/drive/integration/DriveRevisionsIT.java
components/camel-google/camel-google-drive/src/test/java/org/apache/camel/component/google/drive/integration/FileConverterIT.java
components/camel-google/camel-google-drive/src/test/java/org/apache/camel/component/google/drive/integration/FilesConsumerIT.java

CAMEL-16400: split unit and integration tests for camel-google-drive

---

components/camel-google/camel-google-functions/ReadMe.md
components/camel-google/camel-google-functions/pom.xml
components/camel-google/camel-google-functions/src/test/java/org/apache/camel/component/google/functions/integration/GoogleCloudIT.java

CAMEL-16400: split unit and integration tests for camel-google-functions

---

components/camel-google/camel-google-mail/pom.xml
components/camel-google/camel-google-mail/src/test/java/org/apache/camel/component/google/mail/AbstractGoogleMailTestSupport.java
components/camel-google/camel-google-mail/src/test/java/org/apache/camel/component/google/mail/integration/GmailUsersIT.java
components/camel-google/camel-google-mail/src/test/java/org/apache/camel/component/google/mail/integration/GmailUsersLabelsIT.java
components/camel-google/camel-google-mail/src/test/java/org/apache/camel/component/google/mail/integration/GmailUsersMessagesConsumerIT.java
components/camel-google/camel-google-mail/src/test/java/org/apache/camel/component/google/mail/integration/GmailUsersMessagesIT.java
components/camel-google/camel-google-mail/src/test/java/org/apache/camel/component/google/mail/integration/GmailUsersThreadsIT.java

CAMEL-16400: split unit and integration tests for camel-google-mail

---

components/camel-google/camel-google-sheets/pom.xml
components/camel-google/camel-google-sheets/src/test/java/org/apache/camel/component/google/sheets/integration/SheetsSpreadsheetsIT.java
components/camel-google/camel-google-sheets/src/test/java/org/apache/camel/component/google/sheets/integration/SheetsSpreadsheetsValuesIT.java

CAMEL-16400: split unit and integration tests for camel-google-sheets

---

components/camel-lra/pom.xml
components/camel-lra/src/test/java/org/apache/camel/service/lra/LRACreditIT.java
components/camel-lra/src/test/java/org/apache/camel/service/lra/LRAFailuresIT.java
components/camel-lra/src/test/java/org/apache/camel/service/lra/LRAManualIT.java
components/camel-lra/src/test/java/org/apache/camel/service/lra/LRAOptionsIT.java
components/camel-lra/src/test/java/org/apache/camel/service/lra/LRATimeoutIT.java

CAMEL-16400: split unit and integration tests for camel-lra

---

components/camel-lucene/pom.xml
components/camel-lucene/src/test/java/org/apache/camel/component/lucene/LuceneIndexAndQueryProducerIT.java
components/camel-lucene/src/test/java/org/apache/camel/processor/lucene/LuceneQueryProcessorIT.java

CAMEL-16400: split unit and integration tests for camel-lucene

---

components/camel-google/camel-google-storage/ReadMe.md
components/camel-google/camel-google-storage/pom.xml
components/camel-google/camel-google-storage/src/test/java/org/apache/camel/component/google/storage/integration/ComplexIT.java

CAMEL-16400: split unit and integration tests for camel-google-storage

---

components/camel-stitch/pom.xml
components/camel-stitch/src/test/java/org/apache/camel/component/stitch/StitchTestUtils.java
components/camel-stitch/src/test/java/org/apache/camel/component/stitch/client/integration/StitchClientImplIT.java
components/camel-stitch/src/test/java/org/apache/camel/component/stitch/integration/StitchProducerIT.java
components/camel-stitch/src/test/java/org/apache/camel/component/stitch/operations/integration/StitchProducerOperationsIT.java

CAMEL-16400: split unit and integration tests for camel-stitch

---

components/camel-wordpress/pom.xml

CAMEL-16400: split unit and integration tests for camel-wordpress

---

components/camel-bonita/pom.xml
components/camel-bonita/src/test/java/org/apache/camel/component/bonita/integration/BonitaProducerManualIT.java

CAMEL-16400: adjust manual integration tests for camel-bonita

---

components/camel-spring-redis/pom.xml
components/camel-spring-redis/src/test/java/org/apache/camel/component/redis/integration/RedisComponentSpringManualIT.java
components/camel-spring-redis/src/test/java/org/apache/camel/component/redis/integration/RedisConsumerManualIT.java
components/camel-spring-redis/src/test/java/org/apache/camel/component/redis/integration/RedisProducerManualIT.java
components/camel-spring-redis/src/test/java/org/apache/camel/component/redis/processor/idempotent/RedisStringIdempotentRepositoryManualIT.java

CAMEL-16400: adjust manual integration tests for camel-spring-redis

---

components/camel-smpp/pom.xml
components/camel-smpp/src/test/java/org/apache/camel/component/smpp/integration/SmppComponentManualIT.java
components/camel-smpp/src/test/java/org/apache/camel/component/smpp/integration/SmppComponentSpringManualIT.java
components/camel-smpp/src/test/java/org/apache/camel/component/smpp/integration/SmppConsumerReconnectManualIT.java
components/camel-smpp/src/test/java/org/apache/camel/component/smpp/integration/SmppProducerReconnectManualIT.java

CAMEL-16400: adjust manual integration tests for camel-smpp

---

components/camel-beanstalk/pom.xml
components/camel-beanstalk/src/test/java/org/apache/camel/component/beanstalk/integration/BeanstalkCamelITSupport.java
components/camel-beanstalk/src/test/java/org/apache/camel/component/beanstalk/integration/BuryProducerIntegrationIT.java
components/camel-beanstalk/src/test/java/org/apache/camel/component/beanstalk/integration/ConsumerIntegrationIT.java
components/camel-beanstalk/src/test/java/org/apache/camel/component/beanstalk/integration/DeleteProducerIntegrationIT.java
components/camel-beanstalk/src/test/java/org/apache/camel/component/beanstalk/integration/PutProducerIntegrationIT.java
components/camel-beanstalk/src/test/java/org/apache/camel/component/beanstalk/integration/ReleaseProducerIntegrationIT.java
components/camel-beanstalk/src/test/java/org/apache/camel/component/beanstalk/integration/TouchProducerIntegrationIT.java

CAMEL-16400: adjust manual integration tests for camel-beanstalk

---

components/camel-as2/camel-as2-component/pom.xml

CAMEL-16400: split unit and integration tests for camel-as2

---

camel-dependencies/pom.xml
components/camel-microprofile/camel-microprofile-fault-tolerance/src/main/java/org/apache/camel/component/microprofile/faulttolerance/FaultToleranceProcessor.java
components/camel-microprofile/camel-microprofile-health/src/test/java/org/apache/camel/microprofile/health/CamelMicroProfileHealthCheckRepositoryTest.java
components/camel-microprofile/camel-microprofile-health/src/test/java/org/apache/camel/microprofile/health/CamelMicroProfileHealthCheckTest.java
components/camel-microprofile/camel-microprofile-health/src/test/java/org/apache/camel/microprofile/health/CamelMicroProfileHealthTestSupport.java
components/camel-microprofile/camel-microprofile-metrics/src/main/java/org/apache/camel/component/microprofile/metrics/event/notifier/exchange/MicroProfileMetricsExchangeEventNotifier.java
components/camel-microprofile/camel-microprofile-metrics/src/test/java/org/apache/camel/component/microprofile/metrics/MicroProfileMetricsMetadataTest.java
components/camel-opentracing/src/main/java/org/apache/camel/opentracing/OpenTracingTracingStrategy.java
components/camel-opentracing/src/test/java/org/apache/camel/opentracing/ThirdPartyInstrumentationIntegrationTest.java
parent/pom.xml

CAMEL-16028: Upgrade to MicroProfile 4

---

components/camel-consul/src/main/java/org/apache/camel/component/consul/cloud/ConsulServiceDiscovery.java

fixes CAMEL-16526
I chose to catch connection errors and log a warning. If clients need a connection to a service registered in that particular consul, they can report the correct error that no service candidate was found, rather than running into a difficult to understand NPE.

CAMEL-16526: Log and ignore connection issues in ConsulServiceDiscovery

---

components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirOperationIT.java
tooling/maven/camel-api-component-maven-plugin/src/main/java/org/apache/camel/maven/AbstractApiMethodGeneratorMojo.java

camel-16400: suffix with IT when auto-generating integration test code

---

components/camel-twilio/pom.xml
components/camel-twilio/src/test/java/org/apache/camel/component/twilio/AbstractTwilioTestSupport.java
components/camel-twilio/src/test/java/org/apache/camel/component/twilio/AccountIT.java
components/camel-twilio/src/test/resources/test-options.properties

CAMEL-16400: adjust manual integration tests for camel-twilio

---

components/camel-corda/pom.xml
components/camel-corda/src/test/java/org/apache/camel/component/corda/CordaConsumerITSupport.java
components/camel-corda/src/test/java/org/apache/camel/component/corda/CordaConsumerNetworkMapFeedIT.java
components/camel-corda/src/test/java/org/apache/camel/component/corda/CordaConsumerStartTrackedFlowDynamicIT.java
components/camel-corda/src/test/java/org/apache/camel/component/corda/CordaConsumerStateMachineFeedIT.java
components/camel-corda/src/test/java/org/apache/camel/component/corda/CordaConsumerTransactionMapFeedIT.java
components/camel-corda/src/test/java/org/apache/camel/component/corda/CordaConsumerVaultTrackByCriteriaIT.java
components/camel-corda/src/test/java/org/apache/camel/component/corda/CordaConsumerVaultTrackByIT.java
components/camel-corda/src/test/java/org/apache/camel/component/corda/CordaConsumerVaultTrackByWithPagingSpecIT.java
components/camel-corda/src/test/java/org/apache/camel/component/corda/CordaConsumerVaultTrackByWithSortingIT.java
components/camel-corda/src/test/java/org/apache/camel/component/corda/CordaConsumerVaultTrackIT.java
components/camel-corda/src/test/java/org/apache/camel/component/corda/CordaITSupport.java
components/camel-corda/src/test/java/org/apache/camel/component/corda/CordaProducerIT.java

CAMEL-16400: adjust manual integration tests for camel-corda

---

components/camel-splunk-hec/pom.xml
components/camel-splunk-hec/src/test/java/org/apache/camel/component/splunkhec/integration/SplunkHECIT.java

CAMEL-16400: adjust manual integration tests for camel-splunk-hec

---

components/camel-opentracing/pom.xml
components/camel-opentracing/src/test/java/org/apache/camel/opentracing/ThirdPartyInstrumentationIT.java
components/camel-opentracing/src/test/java/org/apache/camel/opentracing/integration/InterprocessIT.java

CAMEL-16400: adjust manual integration tests for camel-opentracing

---

components/camel-zendesk/pom.xml
components/camel-zendesk/src/test/java/org/apache/camel/component/zendesk/AbstractZendeskTestSupport.java
components/camel-zendesk/src/test/java/org/apache/camel/component/zendesk/ZendeskTicketIT.java

CAMEL-16400: adjust manual integration tests for camel-zendesk

---

components/camel-jbpm/pom.xml
components/camel-jbpm/src/test/java/org/apache/camel/component/jbpm/JBPMComponentIT.java
components/camel-jbpm/src/test/java/org/apache/camel/component/jbpm/workitem/CamelWorkItemHandlerIT.java

CAMEL-16400: split unit and integration tests for camel-jbpm

---

components/camel-spring-batch/pom.xml
components/camel-spring-batch/src/test/java/org/apache/camel/component/spring/batch/SpringBatchIT.java

CAMEL-16400: adjust manual integration tests for camel-spring-batch

---

components/camel-telegram/pom.xml
components/camel-telegram/src/test/java/org/apache/camel/component/telegram/integration/TelegramServiceIT.java
components/camel-telegram/src/test/java/org/apache/camel/component/telegram/integration/TelegramServiceProxyIT.java

CAMEL-16400: split unit and integration tests for camel-telegram

---

components/camel-soroush/pom.xml
components/camel-soroush/src/test/java/org/apache/camel/component/soroushbot/component/ConsumerAutoDownloadFileTest.java
components/camel-soroush/src/test/java/org/apache/camel/component/soroushbot/component/ConsumerAutoReconnectAfterIdleTimeoutTest.java
components/camel-soroush/src/test/java/org/apache/camel/component/soroushbot/component/ConsumerCamelConcurrentTest.java
components/camel-soroush/src/test/java/org/apache/camel/component/soroushbot/component/ConsumerExceptionHandledWithErrorHandlerTest.java
components/camel-soroush/src/test/java/org/apache/camel/component/soroushbot/component/ConsumerMultiThreadTest.java
components/camel-soroush/src/test/java/org/apache/camel/component/soroushbot/component/ConsumerNativeConcurrentTest.java
components/camel-soroush/src/test/java/org/apache/camel/component/soroushbot/component/ConsumerQueueCapacityPerThreadTest.java
components/camel-soroush/src/test/java/org/apache/camel/component/soroushbot/component/ConsumerRetryOnConnectionFailureTest.java
components/camel-soroush/src/test/java/org/apache/camel/component/soroushbot/component/ConsumerTest.java
components/camel-soroush/src/test/java/org/apache/camel/component/soroushbot/component/HandleExceptionWithErrorHandlerTest.java
components/camel-soroush/src/test/java/org/apache/camel/component/soroushbot/service/SoroushServiceIT.java

CAMEL-16400: split unit and integration tests for camel-soroush

---

components/camel-dropbox/pom.xml
components/camel-dropbox/src/test/java/org/apache/camel/component/dropbox/integration/DropboxTestSupport.java
components/camel-dropbox/src/test/java/org/apache/camel/component/dropbox/integration/consumer/DropboxConsumerGetSingleIT.java
components/camel-dropbox/src/test/java/org/apache/camel/component/dropbox/integration/consumer/DropboxConsumerSearchQueryIT.java
components/camel-dropbox/src/test/java/org/apache/camel/component/dropbox/integration/producer/DropboxProducerDelIT.java
components/camel-dropbox/src/test/java/org/apache/camel/component/dropbox/integration/producer/DropboxProducerGetFolderIT.java
components/camel-dropbox/src/test/java/org/apache/camel/component/dropbox/integration/producer/DropboxProducerGetSingleIT.java
components/camel-dropbox/src/test/java/org/apache/camel/component/dropbox/integration/producer/DropboxProducerMoveIT.java
components/camel-dropbox/src/test/java/org/apache/camel/component/dropbox/integration/producer/DropboxProducerPutSingleFileIT.java
components/camel-dropbox/src/test/java/org/apache/camel/component/dropbox/integration/producer/DropboxProducerSearchQueryIT.java
components/camel-dropbox/src/test/resources/test-options.properties

CAMEL-16400: split unit and integration tests for camel-dropbox

---

components/camel-facebook/pom.xml
components/camel-facebook/src/test/java/org/apache/camel/component/facebook/CamelFacebookTestSupport.java
components/camel-facebook/src/test/java/org/apache/camel/component/facebook/FacebookComponentConsumerIT.java
components/camel-facebook/src/test/java/org/apache/camel/component/facebook/FacebookComponentPageIdProducerIT.java
components/camel-facebook/src/test/java/org/apache/camel/component/facebook/FacebookComponentProducerIT.java
components/camel-facebook/src/test/java/org/apache/camel/component/facebook/FacebookEndpointIT.java
components/camel-facebook/src/test/java/org/apache/camel/component/facebook/TestUserMethodsIT.java
components/camel-facebook/src/test/resources/test-options.properties

CAMEL-16400: split unit and integration tests for camel-facebook

---

components/camel-digitalocean/pom.xml
components/camel-digitalocean/src/test/java/org/apache/camel/component/digitalocean/integration/DigitalOceanComponentIT.java
components/camel-digitalocean/src/test/java/org/apache/camel/component/digitalocean/integration/DigitalOceanTestSupport.java
components/camel-digitalocean/src/test/resources/test-options.properties

CAMEL-16400: split unit and integration tests for camel-digitalocean

---

components/camel-ldap/pom.xml
components/camel-ldap/src/test/java/org/apache/camel/component/ldap/LdapRouteManualIT.java
components/camel-ldap/src/test/java/org/apache/camel/component/ldap/LdapRouteTwoManualIT.java

CAMEL-16400: adjust manual integration tests for camel-ldap

---

components/camel-zipkin/pom.xml
components/camel-zipkin/src/test/java/org/apache/camel/zipkin/scribe/ZipkinABCRouteScribeManualIT.java
components/camel-zipkin/src/test/java/org/apache/camel/zipkin/scribe/ZipkinAutoConfigureScribeManualIT.java
components/camel-zipkin/src/test/java/org/apache/camel/zipkin/scribe/ZipkinMulticastRouteScribeManualIT.java
components/camel-zipkin/src/test/java/org/apache/camel/zipkin/scribe/ZipkinOneRouteFallbackScribeManualIT.java
components/camel-zipkin/src/test/java/org/apache/camel/zipkin/scribe/ZipkinOneRouteScribeManualIT.java
components/camel-zipkin/src/test/java/org/apache/camel/zipkin/scribe/ZipkinSimpleRouteScribeManualIT.java
components/camel-zipkin/src/test/java/org/apache/camel/zipkin/scribe/ZipkinTimerRouteScribeManualIT.java
components/camel-zipkin/src/test/java/org/apache/camel/zipkin/scribe/ZipkinTwoRouteScribeManualIT.java

CAMEL-16400: adjust manual integration tests for camel-zipkin

---

components/camel-weather/pom.xml
components/camel-weather/src/test/java/org/apache/camel/component/weather/BaseWeatherConsumerIT.java
components/camel-weather/src/test/java/org/apache/camel/component/weather/CurrentWeatherConsumerHtmlIT.java
components/camel-weather/src/test/java/org/apache/camel/component/weather/CurrentWeatherConsumerIT.java
components/camel-weather/src/test/java/org/apache/camel/component/weather/CurrentWeatherConsumerXmlIT.java
components/camel-weather/src/test/java/org/apache/camel/component/weather/CurrentWeatherMadridConsumerIT.java
components/camel-weather/src/test/java/org/apache/camel/component/weather/CurrentWeatherMadridProducerIT.java
components/camel-weather/src/test/java/org/apache/camel/component/weather/Forecast7WeatherMadridConsumerIT.java
components/camel-weather/src/test/java/org/apache/camel/component/weather/WeatherQueryTest.java

CAMEL-16400: split unit and integration tests for camel-weather

---

components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/customresources/KubernetesCustomResourcesProducer.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/producer/KubernetesCustomResourcesProducerTest.java

Kubernetes Custom Resources - listCustomResourcesByLabels operation doesn't use the given labels for filtering the resource instances so it returns the same list of instances as the listCustomResources operation.

[CAMEL-16529] Fix Kubernetes Custom Resources - listCustomResourcesByLabels

---

components/camel-aws/camel-aws2-athena/src/test/java/org/apache/camel/component/aws2/athena/AthenaComponentTest.java
components/camel-aws/camel-aws2-athena/src/test/java/org/apache/camel/component/aws2/athena/AthenaEndpointTest.java

camel-aws2-athena: fixed CI issues due to spliting unit/integration tests (camel-16400)

---

components/camel-ldif/pom.xml
components/camel-ldif/src/test/java/org/apache/camel/component/ldif/LdifRouteIT.java

CAMEL-16400: adjust manual integration tests for camel-ldif

---

docs/user-manual/modules/ROOT/pages/user-stories.adoc

based on https://github.com/apache/camel/pull/5436
There is still a bunch of eleme,nts which are relatively old and i'm nto sure that they are still relevant but the links are still avlid and the information is still there so kept them for now.

Categorize developer tooling user stories and clean page

---

docs/user-manual/modules/ROOT/pages/camel-catalog.adoc

Include links to mentioned projects in Camel Catalog documentation page

---

test-infra/camel-test-infra-azure-common/src/test/java/org/apache/camel/test/infra/azure/common/services/AzuriteContainer.java

camel-test-infra-azure-common: update Azurite container to 3.11.0

---

components/camel-digitalocean/src/main/java/org/apache/camel/component/digitalocean/producer/DigitalOceanBlockStoragesProducer.java

CAMEL-16491: fix get blockstorage by name

---

components/camel-digitalocean/src/main/java/org/apache/camel/component/digitalocean/producer/DigitalOceanAccountProducer.java
components/camel-digitalocean/src/main/java/org/apache/camel/component/digitalocean/producer/DigitalOceanActionsProducer.java
components/camel-digitalocean/src/main/java/org/apache/camel/component/digitalocean/producer/DigitalOceanBlockStoragesProducer.java
components/camel-digitalocean/src/main/java/org/apache/camel/component/digitalocean/producer/DigitalOceanDropletsProducer.java
components/camel-digitalocean/src/main/java/org/apache/camel/component/digitalocean/producer/DigitalOceanFloatingIPsProducer.java
components/camel-digitalocean/src/main/java/org/apache/camel/component/digitalocean/producer/DigitalOceanImagesProducer.java
components/camel-digitalocean/src/main/java/org/apache/camel/component/digitalocean/producer/DigitalOceanKeysProducer.java
components/camel-digitalocean/src/main/java/org/apache/camel/component/digitalocean/producer/DigitalOceanRegionsProducer.java
components/camel-digitalocean/src/main/java/org/apache/camel/component/digitalocean/producer/DigitalOceanSizesProducer.java
components/camel-digitalocean/src/main/java/org/apache/camel/component/digitalocean/producer/DigitalOceanSnapshotsProducer.java
components/camel-digitalocean/src/main/java/org/apache/camel/component/digitalocean/producer/DigitalOceanTagsProducer.java

CAMEL-16536: digitalocean - suppress getOut warning

---

components/camel-chatscript/pom.xml
components/camel-chatscript/src/test/java/org/apache/camel/component/ChatScriptComponentManualIT.java

CAMEL-16400: adjust manual integration tests for camel-chatscript

---

components/camel-bindy/src/test/java/org/apache/camel/dataformat/bindy/fixed/multibytes/BindyCountGraphemeTest.java

CAMEL-16543: Added test for bindy countGrapheme

---

components/camel-log/src/main/docs/log-component.adoc

Changed SLF4J main name casing and fixed typo

---

components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarConsumer.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/utils/PulsarUtils.java

- simplify exception handling when stopping consumers
- consolidate duplicate consumer start up logic

(chores): camel-pulsar cleanups

---

components/camel-chatscript/pom.xml
components/camel-chatscript/src/test/java/org/apache/camel/component/ChatScriptComponentIT.java
test-infra/camel-test-infra-chatscript/pom.xml
test-infra/camel-test-infra-chatscript/src/test/java/org/apache/camel/test/infra/chatscript/common/ChatScriptProperties.java
test-infra/camel-test-infra-chatscript/src/test/java/org/apache/camel/test/infra/chatscript/services/ChatScriptLocalContainerService.java
test-infra/camel-test-infra-chatscript/src/test/java/org/apache/camel/test/infra/chatscript/services/ChatScriptRemoteService.java
test-infra/camel-test-infra-chatscript/src/test/java/org/apache/camel/test/infra/chatscript/services/ChatScriptService.java
test-infra/camel-test-infra-chatscript/src/test/java/org/apache/camel/test/infra/chatscript/services/ChatScriptServiceFactory.java
test-infra/pom.xml

- Added a test infra for ChatScript
- Automated the IT test for ChatScript

camel-chatscript: chores

---

components/camel-jt400/pom.xml
components/camel-jt400/src/main/docs/jt400-component.adoc
components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400Component.java
components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400Configuration.java
components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400Constants.java
components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400Endpoint.java
components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400MsgQueueConsumer.java
components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400MsgQueueProducer.java

Adding message queue enhancements for IBM i per https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-16417 (namely the ability to reply to inquiry messages from a camel route) and doing slight doc cleanup.

[CAMEL-16417] IBM i Message Queue enhancements

---

test-infra/camel-test-infra-mosquitto/src/test/java/org/apache/camel/test/infra/mosquitto/services/MosquittoLocalContainerService.java
test-infra/camel-test-infra-mosquitto/src/test/resources/mosquitto.conf

Update mosquitto version

---

components/camel-kafka/src/main/docs/kafka-component.adoc

Fix retried typo in kafka-component.adoc

---

components/camel-consul/src/test/java/org/apache/camel/component/consul/MockAgentTest.java
components/camel-consul/src/test/java/org/apache/camel/component/consul/MockCatalogTest.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/InterceptSendToEndpointProcessor.java

fixes CAMEL-16567
* added test
* made InterceptSendToEndpointProcessor CamelContextAware to fix mocking problem

[CAMEL-16567]: Set CamelContext on producer to fix mocking problem

---

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/client/DefaultCompositeApiClient.java

Fixes [CAMEL-16574](https://issues.apache.org/jira/browse/CAMEL-16574).

CAMEL-16574: Fixed NPE Exception On Empty Response

---

dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/pom.xml
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/EndpointConsumerDeserializersResolver.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/EndpointProducerDeserializersResolver.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/ModelDeserializers.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/ModelDeserializersResolver.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/ErrorHandlerBuilderDeserializer.java
dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/pom.xml
dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/src/main/java/org/apache/camel/maven/dsl/yaml/GenerateYamlDeserializersMojo.java
dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/src/main/java/org/apache/camel/maven/dsl/yaml/GenerateYamlSupportMojo.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/camel-yaml-dsl.json
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/ErrorHandlerTest.groovy

CAMEL-16486: camel-yaml-dsl-deserializers ErrorHandlerBuilder can parse only Ref

---

components/camel-openapi-java/src/main/java/org/apache/camel/openapi/RestOpenApiReader.java
components/camel-openapi-java/src/test/java/org/apache/camel/openapi/RestOpenApiProcessorTest.java
core/camel-core-model/src/main/java/org/apache/camel/model/rest/RestDefinition.java
core/camel-core-model/src/main/java/org/apache/camel/model/rest/VerbDefinition.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/ModelXmlParserGeneratorMojo.java

[CAMEL-16558] Openapi deprecate endpoint

---

core/camel-api/src/main/java/org/apache/camel/RouteTemplateContext.java
core/camel-core-engine/src/main/java/org/apache/camel/impl/DefaultModel.java
core/camel-core-model/src/main/java/org/apache/camel/model/DefaultRouteTemplateContext.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/pom.xml
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/ModelDeserializers.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/ModelDeserializersResolver.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/BeansDeserializer.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/CustomResolver.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/NamedBeanDefinition.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/NamedBeanDeserializer.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/OutputAwareFromDefinition.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/OutputAwareFromDefinitionDeserializer.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/RouteTemplateDefinitionDeserializer.java
dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/src/main/java/org/apache/camel/maven/dsl/yaml/GenerateYamlSchemaMojo.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/camel-yaml-dsl.json
dsl/camel-yaml-dsl/camel-yaml-dsl/src/main/java/org/apache/camel/dsl/yaml/YamlRoutesBuilderLoader.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/KameletTest.groovy
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/RouteTemplateTest.groovy
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/support/model/MySetBody.groovy

CAMEL-16584 support for route template in YAML DSL

---

components/camel-aws/camel-aws2-sns/src/main/java/org/apache/camel/component/aws2/sns/Sns2Component.java
components/camel-aws/camel-aws2-sns/src/test/java/org/apache/camel/component/aws2/sns/SnsComponentTest.java

Thanks and credits to the unit test provided by Ben Campion on the
ticket CAMEL-16586

CAMEL-16586: prevent messages from different endpoints to end up in the same topic

---

components/camel-openstack/src/main/java/org/apache/camel/component/openstack/common/AbstractOpenstackEndpoint.java

[CAMEL-16587] Fix creation of V3 Client

---

components/camel-aws2-sns/src/main/java/org/apache/camel/component/aws2/sns/Sns2Component.java
components/camel-aws2-sns/src/test/java/org/apache/camel/component/aws2/sns/SnsComponentTest.java

Thanks and credits to the unit test provided by Ben Campion on the ticket CAMEL-16586

CAMEL-16586: prevent messages from different endpoints to end up in the same topic (backport)

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/models/routeTemplate.json
catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/models/templateParameter.json
core/camel-core-engine/src/main/java/org/apache/camel/impl/DefaultModel.java
core/camel-core-model/src/generated/resources/org/apache/camel/model/routeTemplate.json
core/camel-core-model/src/generated/resources/org/apache/camel/model/templateParameter.json
core/camel-core-model/src/main/java/org/apache/camel/model/RouteTemplateDefinition.java
core/camel-core-model/src/main/java/org/apache/camel/model/RouteTemplateParameterDefinition.java
core/camel-core/src/test/java/org/apache/camel/builder/RouteTemplateOptionalValueTest.java
core/camel-xml-io/src/generated/java/org/apache/camel/xml/in/ModelParser.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/ModelDeserializers.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/camel-yaml-dsl.json
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/RouteTemplateTest.groovy

CAMEL-16604: route template parameter should be able to be marked explicit as required.

CAMEL-16604

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd
dsl/camel-yaml-dsl/camel-yaml-dsl-common/src/main/java/org/apache/camel/dsl/yaml/common/YamlDeserializerSupport.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/main/java/org/apache/camel/dsl/yaml/KameletRoutesBuilderLoader.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/KameletLoaderTest.groovy

YAML DSL: support Kamelet optional parameter

---

core/camel-core-model/src/main/java/org/apache/camel/model/RouteTemplateScriptDefinition.java
core/camel-support/src/main/java/org/apache/camel/support/SupplierRegistry.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/ModelDeserializers.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/RouteTemplateDefinitionDeserializer.java
dsl/camel-yaml-dsl/camel-yaml-dsl/pom.xml
dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/camel-yaml-dsl.json
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/KameletTest.groovy
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/RouteTemplateTest.groovy

Fix for lucas PR

---

camel-core/src/main/java/org/apache/camel/util/FileUtil.java
camel-core/src/test/java/org/apache/camel/util/FileUtilTest.java

See https://issues.apache.org/jira/browse/CAMEL-16622.
Add https to the exclusion for path compating.

CAMEL-16622 : Fix for version 2.x

---

core/camel-api/src/main/java/org/apache/camel/Exchange.java

improve Exchange javadoc regarding when getFromEndpoint returning null

---

camel-dependencies/pom.xml
parent/pom.xml

Implementation of https://issues.apache.org/jira/browse/CAMEL-16637
Upgrade Deep Java Library to the latest version (0.11.0)

Upgrade DJL to 0.11.0

---

components/camel-ldif/pom.xml
components/camel-ldif/src/test/java/org/apache/camel/component/ldif/LdifRouteIT.java
components/camel-ldif/src/test/java/org/apache/camel/component/ldif/LdifTestSupport.java
components/camel-ldif/src/test/resources/org/apache/camel/component/ldif/AddDuplicate.ldif
components/camel-ldif/src/test/resources/org/apache/camel/component/ldif/AddDuplicateSetup.ldif
components/camel-ldif/src/test/resources/org/apache/camel/component/ldif/AddOne.ldif
components/camel-ldif/src/test/resources/org/apache/camel/component/ldif/DeleteOne.ldif
components/camel-ldif/src/test/resources/org/apache/camel/component/ldif/DeleteOneSetup.ldif
components/camel-ldif/src/test/resources/org/apache/camel/component/ldif/ModDn.ldif
components/camel-ldif/src/test/resources/org/apache/camel/component/ldif/ModDnSetup.ldif
components/camel-ldif/src/test/resources/org/apache/camel/component/ldif/ModRdn.ldif
components/camel-ldif/src/test/resources/org/apache/camel/component/ldif/ModRdnSetup.ldif
components/camel-ldif/src/test/resources/org/apache/camel/component/ldif/Modify.ldif
components/camel-ldif/src/test/resources/org/apache/camel/component/ldif/ModifySetup.ldif
test-infra/camel-test-infra-openldap/pom.xml
test-infra/camel-test-infra-openldap/src/test/java/org/apache/camel/test/infra/openldap/common/OpenldapProperties.java
test-infra/camel-test-infra-openldap/src/test/java/org/apache/camel/test/infra/openldap/services/OpenldapLocalContainerService.java
test-infra/camel-test-infra-openldap/src/test/java/org/apache/camel/test/infra/openldap/services/OpenldapRemoteService.java
test-infra/camel-test-infra-openldap/src/test/java/org/apache/camel/test/infra/openldap/services/OpenldapService.java
test-infra/camel-test-infra-openldap/src/test/java/org/apache/camel/test/infra/openldap/services/OpenldapServiceFactory.java
test-infra/pom.xml

Uncomment and fill this section if your PR is not trivial

[OPENLDAP-CONTAINER] Run IT tests on Docker

---

components/camel-salesforce/camel-salesforce-component/src/main/docs/salesforce-component.adoc

CAMEL-13095 - Additional info for queryAll in Salesforce component

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/header-language.adoc
core/camel-core-languages/src/main/docs/modules/languages/pages/header-language.adoc
docs/components/modules/languages/pages/header-language.adoc

Header language

---

docs/user-manual/modules/ROOT/pages/getting-started.adoc

Updated broken link

---

components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/list/HazelcastListProducer.java
components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/set/HazelcastSetProducer.java
components/camel-hazelcast/src/test/java/org/apache/camel/component/hazelcast/HazelcastListProducerTest.java
components/camel-hazelcast/src/test/java/org/apache/camel/component/hazelcast/HazelcastSetProducerTest.java

Add getAll() method to HazelCastSet and HazelCastList and also update of the tests without mock, but testing the actual methods
- [x ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [x ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [ x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x ] Run `mvn clean install -Psourcecheck` in your module with source check …

CAMEL-16482: HazelCastSet and HazelCastList getAll() added and tests modified

---

docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_11.adoc

CAMEL-16643: Updated the migration guide

---

components/camel-ahc/pom.xml
components/camel-amqp/pom.xml
components/camel-atomix/pom.xml
components/camel-iec60870/pom.xml
components/camel-lumberjack/pom.xml
components/camel-netty-http/pom.xml
components/camel-netty/pom.xml
parent/pom.xml

make use of netty bom

---

components/camel-jbpm/src/main/java/org/apache/camel/component/jbpm/JBPMOperation.java
components/camel-jbpm/src/main/java/org/apache/camel/component/jbpm/JBPMProducer.java
components/camel-jbpm/src/test/java/org/apache/camel/component/jbpm/JBPMComponentIT.java

Jira: https://issues.apache.org/jira/browse/CAMEL-16468
extract the enum JBPMOperation to public and extract the operation to a proper class

[CAMEL-16468] camel-jbpm - Expose org.apache.camel.component.jbpm.JBPMProducer.Operation

---

tooling/openapi-rest-dsl-generator/src/main/java/org/apache/camel/generator/openapi/SpringBootProjectSourceCodeGenerator.java

Instead of configuring RequestMapping with "/" this change allows inserting custom paths. Usually the "/" conflicts with /actuator/hawtio. On the other hand, there may be paths that we don't want to be handled by the Controller. ** https://github.com/apache/camel/pull/5625

Allow customizing SpringBoot @RequestMapping paths

---

tooling/maven/camel-restdsl-openapi-plugin/src/main/docs/camel-restdsl-openapi-plugin.adoc

Update documentation about how to produces custom RequestMapping on controller.

Document allow customizing SpringBoot @RequestMapping paths

---

tooling/maven/camel-restdsl-openapi-plugin/src/main/docs/camel-restdsl-openapi-plugin.adoc

Correct indentation for property requestMappingValues

Correct indentation after update docs

---

camel-dependencies/pom.xml
components/camel-opentelemetry/pom.xml
components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/OpenTelemetrySpanAdapter.java
components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/OpenTelemetryTracer.java
components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/propagators/OpenTelemetryGetter.java
components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/propagators/OpenTelemetrySetter.java
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/SpanTestData.java
parent/pom.xml

I checked camel-spring-boot and it looked ok. I'll open a minor follow up PR for camel-karaf.

CAMEL-16437: Upgrade OpenTelemetry to 1.2.0

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerManualCommitIT.java

Uncomment and fill this section if your PR is not trivial
@omarsmak

Test manual commit when rebalancing in kafka occur

---

test-infra/camel-test-infra-couchbase/src/test/java/org/apache/camel/test/infra/couchbase/services/CouchbaseServiceFactory.java

camel-test-infra-couchbase: fixed incorrect couchbase service name

---

camel-dependencies/pom.xml
parent/pom.xml

See https://github.com/apache/camel-quarkus/issues/2207 and https://github.com/Azure/azure-sdk-for-java/issues/18876

Upgrade to azure-bom 1.0.3

---

components/camel-huaweicloud-functiongraph/src/main/docs/hwcloud-functiongraph-component.adoc

Corrections and updates to HuaweiCloud FunctionGraph component documentation.
1. Corrected typos
2. Added default value for FunctionPackage option

Corrections and updates to documentation

---

components/pom.xml
test-infra/camel-test-infra-common/src/test/java/org/apache/camel/test/infra/common/services/ContainerEnvironmentUtil.java
test-infra/camel-test-infra-common/src/test/java/org/apache/camel/test/infra/common/services/ContainerService.java

CAMEL-16698: do log when unable to determine docker availability

---

dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/pom.xml
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/ModelDeserializers.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/ModelDeserializersResolver.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/CustomResolver.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/RouteTemplateBeanDefinitionDeserializer.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/camel-yaml-dsl.json
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/KameletTest.groovy
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/RouteTemplateTest.groovy

yaml-dsl: make it simple to configure route local beans

---

components/camel-zipkin/src/main/java/org/apache/camel/zipkin/ZipkinServerResponseAdapter.java

Fix Nullable Throwable#getMessage NPE on SpanCustomizer#tag method
https://issues.apache.org/jira/browse/CAMEL-16715

camel-zipkin - ZipkinServerResponseAdapter NPE fix

---

components/camel-aws/camel-aws2-ddb/src/test/java/org/apache/camel/component/aws2/ddb/localstack/AWS2DeleteTableRuleIT.java
components/camel-aws/camel-aws2-ddb/src/test/java/org/apache/camel/component/aws2/ddb/localstack/AWS2DescribeTableRuleIT.java
components/camel-aws/camel-aws2-ddb/src/test/java/org/apache/camel/component/aws2/ddb/localstack/AWS2UpdateTableByIdRuleIT.java

Adding simple test for DeleteTable, DescribeTable and UpdateTable(ById) operations.

feature(camel-aws-ddb): Add tests for table operations. 

---

core/camel-core-engine/src/main/docs/modules/eips/pages/enterprise-integration-patterns.adoc

Fixed small typo

---

components/camel-huawei/camel-huaweicloud-iam/src/test/java/org/apache/camel/component/huaweicloud/iam/GetGroupUsersFunctionalTest.java
components/camel-huawei/camel-huaweicloud-iam/src/test/java/org/apache/camel/component/huaweicloud/iam/GetUserFunctionalTest.java
components/camel-huawei/camel-huaweicloud-iam/src/test/java/org/apache/camel/component/huaweicloud/iam/ListGroupsFunctionalTest.java
components/camel-huawei/camel-huaweicloud-iam/src/test/java/org/apache/camel/component/huaweicloud/iam/ListUsersFunctionalTest.java

Adding functional test cases to the Huawei Cloud IAM component
JIRA - https://issues.apache.org/jira/browse/CAMEL-16717

CAMEL-16717: Adding functional test cases

---

components/camel-caffeine/src/test/java/org/apache/camel/component/caffeine/cache/CaffeineCacheProducerTest.java
components/camel-caffeine/src/test/java/org/apache/camel/component/caffeine/cache/CaffeineCacheRemovaListenerProducerTest.java
components/camel-caffeine/src/test/java/org/apache/camel/component/caffeine/loadcache/CaffeineLoadCacheProducerTest.java
components/camel-cxf/src/test/java/org/apache/camel/component/cxf/jaxrs/CxfRsAsyncProducerTest.java
components/camel-git/src/test/java/org/apache/camel/component/git/producer/GitProducerTest.java
components/camel-google/camel-google-drive/src/test/java/org/apache/camel/component/google/drive/DriveFilesIT.java
components/camel-google/camel-google-functions/src/test/java/org/apache/camel/component/google/functions/unit/GoogleCloudFunctionsConfigurationTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsEndpointConfigurationTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/RequestReplyWithProducerIssueTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/tx/QueueToQueueRequestReplyTransactionTest.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaProducerTest.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/producer/KubernetesCustomResourcesProducerTest.java
components/camel-lucene/src/test/java/org/apache/camel/component/lucene/LuceneIndexAndQueryProducerIT.java
components/camel-milo/src/test/java/org/apache/camel/component/milo/MiloClientCachingConnectionManagerTest.java
components/camel-mina/src/test/java/org/apache/camel/component/mina/MinaTcpLineDelimiterUsingPlainSocketTest.java
components/camel-mina/src/test/java/org/apache/camel/component/mina/MinaTcpWithInOutUsingPlainSocketTest.java
components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/api/utils/VersionTest.java
components/camel-sjms/src/test/java/org/apache/camel/component/sjms/SjmsEndpointTest.java
components/camel-sjms2/src/test/java/org/apache/camel/component/sjms2/Sjms2EndpointTest.java
components/camel-test/camel-test-junit5/src/test/java/org/apache/camel/test/AvailablePortFinderTest.java
components/camel-test/camel-test/src/test/java/org/apache/camel/test/AvailablePortFinderTest.java
core/camel-core/src/test/java/org/apache/camel/util/ResourceLoaderTest.java
core/camel-core/src/test/java/org/apache/camel/util/StringHelperTest.java

Assertions cleanups

---

dsl/camel-yaml-dsl/camel-yaml-dsl/src/main/java/org/apache/camel/dsl/yaml/YamlRoutesBuilderLoaderSupport.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/AggregateTest.groovy
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/FilterTest.groovy
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/KameletLoaderTest.groovy
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/KameletTest.groovy
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/LoopTest.groovy
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/SplitTest.groovy

CAMEL-16693: make YamlDeserializationMode.FLOW the default deserialization mode

---

components/camel-atmosphere-websocket/src/main/java/org/apache/camel/component/atmosphere/websocket/WebsocketComponent.java
components/camel-bean/src/main/java/org/apache/camel/component/bean/MethodInfo.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/format/factories/DefaultFactoryRegistry.java
components/camel-cmis/src/main/java/org/apache/camel/component/cmis/CMISProducer.java
components/camel-http-common/src/main/java/org/apache/camel/http/common/DefaultHttpBinding.java
components/camel-http-common/src/main/java/org/apache/camel/http/common/DefaultHttpRegistry.java
components/camel-milo/src/main/java/org/apache/camel/component/milo/server/internal/CamelNamespace.java
components/camel-olingo2/camel-olingo2-api/src/main/java/org/apache/camel/component/olingo2/api/impl/Olingo2AppImpl.java
components/camel-optaplanner/src/main/java/org/apache/camel/component/optaplanner/OptaPlannerEndpoint.java
components/camel-quartz/src/main/java/org/apache/camel/component/quartz/QuartzComponent.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/dto/composite/SObjectNode.java
components/camel-salesforce/camel-salesforce-maven-plugin/src/main/java/org/apache/camel/maven/GenerateMojo.java
components/camel-xpath/src/main/java/org/apache/camel/language/xpath/XPathBuilder.java
core/camel-api/src/main/java/org/apache/camel/catalog/PropertiesValidationResult.java

Use computeIfAbsent, computeIfPresent and putIfAbsent to simplify code
conditionally operating on Maps.

(chores) Simplifies map access/put logic

---

components/camel-aws/camel-aws-secrets-manager/src/main/java/org/apache/camel/component/aws/secretsmanager/client/impl/SecretsManagerClientIAMOptimized.java
components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/firehose/client/impl/KinesisFirehoseClientIAMOptimizedImpl.java
components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/client/impl/KinesisClientIAMOptimizedImpl.java
components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Endpoint.java
components/camel-aws/camel-aws2-sns/src/main/java/org/apache/camel/component/aws2/sns/client/impl/Sns2ClientIAMOptimized.java
components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/client/impl/Sqs2ClientIAMOptimized.java
components/camel-aws/camel-aws2-sts/src/main/java/org/apache/camel/component/aws2/sts/client/impl/STS2ClientIAMOptimized.java
components/camel-aws/camel-aws2-translate/src/main/java/org/apache/camel/component/aws2/translate/client/impl/Translate2ClientIAMOptimized.java
components/camel-google/camel-google-storage/src/main/java/org/apache/camel/component/google/storage/GoogleCloudStorageConsumer.java
components/camel-grpc/src/main/java/org/apache/camel/component/grpc/GrpcProducer.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/SalesforceComponent.java
components/camel-servicenow/camel-servicenow-component/src/main/java/org/apache/camel/component/servicenow/releases/helsinki/HelsinkiServiceNowMiscProcessor.java
components/camel-servicenow/camel-servicenow-component/src/main/java/org/apache/camel/component/servicenow/releases/helsinki/HelsinkiServiceNowTableProcessor.java
components/camel-test/camel-test-spring-junit5/src/main/java/org/apache/camel/test/spring/junit5/CamelSpringTestSupport.java
core/camel-core-engine/src/main/java/org/apache/camel/impl/lw/LightweightRuntimeCamelContext.java
core/camel-xml-io-util/src/main/java/org/apache/camel/xml/io/util/XmlStreamReader.java
core/camel-xml-io/src/main/java/org/apache/camel/xml/io/MXParser.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PrepareAssemblyMojo.java

(chores) removed unused variables

---

components/camel-chatscript/src/main/java/org/apache/camel/component/chatscript/ChatScriptBot.java
components/camel-dropbox/src/main/java/org/apache/camel/component/dropbox/util/DropboxPropertyManager.java
components/camel-weather/src/main/java/org/apache/camel/component/weather/WeatherConfiguration.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PackageArchetypeCatalogMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/XRefCheckMojo.java
tooling/maven/sync-properties-maven-plugin/src/main/java/org/apache/camel/maven/sync/properties/SyncPropertiesMojo.java

This ensures they are closed even if exceptions are thrown

(chores) Use try-with-resources for a few components

---

components/camel-tarfile/src/main/java/org/apache/camel/processor/aggregate/tarfile/TarAggregationStrategy.java

- Rework the code to use try-with-resources to avoid leaking them even if exceptions are thrown
-------
Sending this one separately as it required a bit more work to adjust use twr.

(chores) camel-tarfile cleanup

---

components/camel-asn1/src/main/java/org/apache/camel/dataformat/asn1/ASN1DataFormat.java
components/camel-asn1/src/main/java/org/apache/camel/dataformat/asn1/ASN1GenericIterator.java
components/camel-asn1/src/main/java/org/apache/camel/dataformat/asn1/ASN1Splitter.java

- removed unused variables
- removed unused methods
- use try-with-resources to avoid leaking resources
- use more specific exceptions when suitable

(chores) camel-asn1: code cleanups

---

components/camel-docker/src/main/java/org/apache/camel/component/docker/DockerComponent.java
components/camel-docker/src/main/java/org/apache/camel/component/docker/consumer/DockerEventsConsumer.java
components/camel-docker/src/main/java/org/apache/camel/component/docker/consumer/DockerStatsConsumer.java
components/camel-docker/src/main/java/org/apache/camel/component/docker/producer/AsyncDockerProducer.java
components/camel-docker/src/main/java/org/apache/camel/component/docker/producer/DockerProducer.java

- removed unused variables
- removed unused parameters
- avoid unlikely (but still possible) NPEs
- removed exceptions not thrown from method signatures

(chores) camel-docker cleanup

---

components/camel-elasticsearch-rest/src/main/java/org/apache/camel/component/elasticsearch/ElasticsearchComponent.java
components/camel-elasticsearch-rest/src/main/java/org/apache/camel/component/elasticsearch/ElasticsearchEndpoint.java
components/camel-elasticsearch-rest/src/main/java/org/apache/camel/component/elasticsearch/ElasticsearchProducer.java
components/camel-elasticsearch-rest/src/main/java/org/apache/camel/component/elasticsearch/ElasticsearchRestComponentVerifierExtension.java
components/camel-elasticsearch-rest/src/main/java/org/apache/camel/component/elasticsearch/ElasticsearchScrollRequestIterator.java
components/camel-elasticsearch-rest/src/main/java/org/apache/camel/component/elasticsearch/converter/ElasticsearchActionRequestConverter.java

- removed unused variables
- removed unused parameters
- avoid unlikely (but still possible) NPEs
- removed exceptions not thrown from method signatures

(chores) camel-elasticsearch-rest cleanup

---

components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/CamelFTPParserFactory.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpUtils.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpsOperations.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/RemoteFileConsumer.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/RemoteFileEndpoint.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/SftpOperations.java

- removed unused imports
- simplified exception handling
- used log markers in some log messages
- removed exceptions not thrown from method signatures

(chores) camel-ftp cleanup

---

components/camel-paho/src/main/java/org/apache/camel/component/paho/PahoComponent.java
components/camel-paho/src/main/java/org/apache/camel/component/paho/PahoComponentVerifierExtension.java

- ensure the client is closed to avoid leaking resources during credentials verification
- avoid shadowing the configuration object when duplicating it at endpoint creation

(chores) camel-paho cleanup

---

components/camel-soroush/src/main/java/org/apache/camel/component/soroushbot/component/SoroushBotEndpoint.java

- ensure resources are closed to avoid leaking them

(chores) camel-soroush cleanup

---

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/AS2ClientConnection.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/AS2ServerConnection.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/AS2ServerManager.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/ApplicationPkcs7SignatureEntity.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/DispositionNotificationMultipartReportEntity.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/MultipartReportEntity.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/protocol/ResponseMDN.java
components/camel-as2/camel-as2-component/src/main/java/org/apache/camel/component/as2/internal/AS2ConnectionHelper.java
components/camel-as2/camel-as2-component/src/test/resources/log4j2.properties

- removed exceptions not thrown from method signatures
- adjusted the log configuration to send test logs to file

(chores) camel-as2: code cleanups

---

components/camel-atmos/src/main/java/org/apache/camel/component/atmos/core/AtmosAPIFacade.java
components/camel-atmos/src/main/java/org/apache/camel/component/atmos/integration/producer/AtmosDelProducer.java

(chores) camel-atmos: cleanup unused throws

---

components/camel-asterisk/src/main/java/org/apache/camel/component/asterisk/AsteriskEndpoint.java
components/camel-asterisk/src/main/java/org/apache/camel/component/asterisk/AsteriskProducer.java

(chores) camel-asterisk: cleanup unused throws

---

components/camel-atomix/src/main/java/org/apache/camel/component/atomix/client/AbstractAtomixClientComponent.java
components/camel-atomix/src/main/java/org/apache/camel/component/atomix/client/map/AtomixMapProducer.java
components/camel-atomix/src/main/java/org/apache/camel/component/atomix/client/messaging/AtomixMessagingProducer.java
components/camel-atomix/src/main/java/org/apache/camel/component/atomix/client/multimap/AtomixMultiMapProducer.java
components/camel-atomix/src/main/java/org/apache/camel/component/atomix/client/queue/AtomixQueueProducer.java
components/camel-atomix/src/main/java/org/apache/camel/component/atomix/client/set/AtomixSetProducer.java
components/camel-atomix/src/main/java/org/apache/camel/component/atomix/client/value/AtomixValueProducer.java
components/camel-atomix/src/main/java/org/apache/camel/component/atomix/cluster/AtomixClusterHelper.java
components/camel-atomix/src/main/java/org/apache/camel/component/atomix/cluster/AtomixClusterView.java

- remove unused throws
- use more specific ones when applicable

(chores) camel-atomix cleanup throws

---

components/camel-corda/src/main/java/org/apache/camel/component/corda/CordaProducer.java

- remove unused throws
- use more specific ones when applicable

(chores) camel-corda cleanup throws

---

components/camel-hl7/src/main/java/org/apache/camel/component/hl7/HL721Converter.java
components/camel-hl7/src/main/java/org/apache/camel/component/hl7/HL722Converter.java
components/camel-hl7/src/main/java/org/apache/camel/component/hl7/HL7231Converter.java
components/camel-hl7/src/main/java/org/apache/camel/component/hl7/HL723Converter.java
components/camel-hl7/src/main/java/org/apache/camel/component/hl7/HL724Converter.java
components/camel-hl7/src/main/java/org/apache/camel/component/hl7/HL7251Converter.java
components/camel-hl7/src/main/java/org/apache/camel/component/hl7/HL725Converter.java
components/camel-hl7/src/main/java/org/apache/camel/component/hl7/HL726Converter.java
components/camel-hl7/src/main/java/org/apache/camel/component/hl7/HL7GenericMessageConverter.java
components/camel-hl7/src/main/java/org/apache/camel/component/hl7/HL7MLLPDecoder.java

(chores) camel-hl7 cleanup unused throws

---

dsl/camel-yaml-dsl/camel-yaml-dsl/pom.xml
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/issues/KameletTemplatingTest.groovy

yaml-dsl: add test for kamelet template action

---

tooling/maven/camel-maven-plugin/src/main/java/org/apache/camel/maven/RunMojo.java

Reverts one of the changes introduced by the commit 6d233b66756a109d4c414b8b917bb9c95859d7d6 which was causing the plugin to fail

Fix camel-maven-plugin error breaking the CI

---

components/camel-huawei/camel-huaweicloud-functiongraph/src/main/docs/hwcloud-functiongraph-component.adoc
components/camel-huawei/camel-huaweicloud-functiongraph/src/main/java/org/apache/camel/FunctionGraphEndpoint.java
components/camel-huawei/camel-huaweicloud-smn/src/main/docs/hwcloud-smn-component.adoc
components/camel-huawei/camel-huaweicloud-smn/src/main/java/org/apache/camel/component/huaweicloud/smn/SimpleNotificationEndpoint.java

Updates to title and description in documentation for Huawei Cloud's FunctionGraph and SMN components.
- include Huawei Cloud in titles
- update 'SimpleNotification' to 'Simple Message Notification'
- change description of SMN component

Huawei Documentation Updates

---

components/camel-http/src/main/java/org/apache/camel/component/http/HttpProducer.java

I didn't test that fix 🙃, but I assume it would work correctly

Fix incorrect read from InputStream

---

components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/fixed/BindyFixedLengthDataFormat.java
components/camel-crypto/src/main/java/org/apache/camel/converter/crypto/PGPDataFormat.java

(chores) Fix formatting issues on camel-bindy and camel-crypto

---

components/camel-bean/src/main/java/org/apache/camel/component/bean/ProxyHelper.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/BindyAbstractFactory.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/BindyCsvFactory.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/BindyFixedLengthFactory.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/BindyKeyValuePairFactory.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/util/AnnotationModelLoader.java
components/camel-caffeine/src/main/java/org/apache/camel/component/caffeine/cache/CaffeineCacheProducer.java
components/camel-caffeine/src/main/java/org/apache/camel/component/caffeine/load/CaffeineLoadCacheProducer.java
components/camel-consul/src/main/java/org/apache/camel/component/consul/endpoint/AbstractConsulProducer.java
components/camel-crypto/src/main/java/org/apache/camel/converter/crypto/PGPDataFormat.java
components/camel-cxf-transport/src/main/java/org/apache/camel/component/cxf/transport/CamelDestination.java
components/camel-docker/src/main/java/org/apache/camel/component/docker/DockerClientFactory.java

components: components/camel-bean, components/camel-bindy,
components/camel-caffeine, components/camel-consul,
components/camel-cxf-transport, components/camel-docker

(chores) Cleanup unused throws

---

components/camel-jta/src/main/java/org/apache/camel/jta/JtaTransactionErrorHandlerReifier.java
components/camel-jta/src/main/java/org/apache/camel/jta/JtaTransactionPolicy.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/cloud/KubernetesClientServiceDiscovery.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/cluster/KubernetesClusterServiceTest.java

(chores) Formatting fixes for camel-jta and camel-kubernetes

---

components/camel-ldap/src/test/java/org/apache/directory/server/core/integ5/DSAnnotationProcessor.java
components/camel-ldap/src/test/java/org/apache/directory/server/core/integ5/DirectoryExtension.java
components/camel-ldap/src/test/java/org/apache/directory/server/core/integ5/ServerAnnotationProcessor.java
components/camel-ldif/src/test/java/org/apache/directory/server/core/integ5/DSAnnotationProcessor.java
components/camel-ldif/src/test/java/org/apache/directory/server/core/integ5/DirectoryExtension.java
components/camel-ldif/src/test/java/org/apache/directory/server/core/integ5/ServerAnnotationProcessor.java
components/camel-lucene/src/main/java/org/apache/camel/component/lucene/LuceneConfiguration.java
components/camel-lucene/src/main/java/org/apache/camel/component/lucene/LuceneIndexer.java

components: camel-ldap, camel-ldif, camel-lucene

(chores) Formatting fixes

---

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/SalesforceProducer.java

Can this be squeezed in for 3.11?

CAMEL-16388: camel-salesforce: add deprecation warnings for XML format.

---

components/camel-jcr/src/main/java/org/apache/camel/component/jcr/JcrProducer.java
components/camel-shiro/src/main/java/org/apache/camel/component/shiro/security/ShiroSecurityTokenInjector.java
components/camel-solr/src/main/java/org/apache/camel/component/solr/SolrComponent.java
components/camel-solr/src/main/java/org/apache/camel/component/solr/SolrConfiguration.java
components/camel-tagsoup/src/main/java/org/apache/camel/dataformat/tagsoup/TidyMarkupDataFormat.java
components/camel-twitter/src/main/java/org/apache/camel/component/twitter/util/TwitterConverter.java
components/camel-xmlsecurity/src/main/java/org/apache/camel/component/xmlsecurity/api/DefaultXmlSignature2Message.java
components/camel-xmlsecurity/src/main/java/org/apache/camel/component/xmlsecurity/api/XAdESSignatureProperties.java
components/camel-xmlsecurity/src/main/java/org/apache/camel/component/xmlsecurity/processor/XmlSignerProcessor.java
components/camel-xmlsecurity/src/main/java/org/apache/camel/component/xmlsecurity/processor/XmlVerifierProcessor.java
components/camel-xslt-saxon/src/main/java/org/apache/camel/component/xslt/saxon/XsltSaxonHelper.java
components/camel-xslt/src/main/java/org/apache/camel/component/xslt/XsltBuilder.java

components:
components/camel-xmlsecurity components/camel-twitter components/camel-solr/ components/camel-shiro  components/camel-jcr components/camel-tagsoup components/camel-xslt-saxon/ components/camel-xslt

(chores) Cleanup throws

---

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/SalesforceComponent.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/dto/Limits.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/dto/approval/ApprovalResult.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/utils/LocalDateTimeDeserializer.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/utils/LocalDateTimeSerializer.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/utils/OffsetDateTimeDeserializer.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/utils/OffsetDateTimeSerializer.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/client/AbstractClientBase.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/processor/BulkApiProcessor.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/processor/BulkApiV2Processor.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/streaming/SubscriptionHelper.java

(chores) Cleaned up unused throws in salesforce component

---

components/camel-aws/camel-aws2-ddb/src/main/java/org/apache/camel/component/aws2/ddb/QueryCommand.java
components/camel-aws/camel-aws2-ddb/src/main/java/org/apache/camel/component/aws2/ddb/ScanCommand.java

This prevents an SdkAutoConstructMap from being sent to the consumer.
Followup for https://github.com/apache/camel/pull/5748

(aws2-ddb) Check hasLastEvaluatedKey before setting the value.

---

dsl/camel-kamelet-main/pom.xml
dsl/camel-kamelet-main/src/test/java/org/apache/camel/main/MavenGavTest.java

Add test cases for the MavenGav class

---

components/camel-box/camel-box-component/pom.xml
components/camel-box/camel-box-component/src/main/java/org/apache/camel/component/box/BoxConfiguration.java
components/camel-box/camel-box-component/src/test/java/org/apache/camel/component/box/BoxSharedConnectionTest.java

CAMEL-16764: Fix resolution of shared BoxAPIConnection

---

components/camel-activemq/src/main/java/org/apache/camel/component/activemq/ActiveMQConfiguration.java

(chores) camel-activemq: avoid using a generic runtime exception

---

components/camel-arangodb/src/main/java/org/apache/camel/component/arangodb/ArangoDbProducer.java

(chores) camel-arangodb: avoid using a generic runtime exception

---

components/camel-box/camel-box-api/pom.xml
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxCollaborationsManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxCommentsManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxEventLogsManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxEventsManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxFilesManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxFoldersManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxGroupsManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxSearchManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxTasksManager.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxUsersManager.java

(chores) camel-box: avoid using a generic runtime exception

---

components/camel-amqp/src/main/java/org/apache/camel/component/amqp/AMQPConnectionDetails.java

(chores) camel-amqp: avoid using a generic runtime exception

---

components/camel-huawei/camel-huaweicloud-obs/src/main/java/org/apache/camel/component/huaweicloud/obs/OBSEndpoint.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/CreateBucketFunctionalTest.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/CreateBucketJsonFunctionalTest.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/CreateBucketPojoFunctionalTest.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/DeleteBucketFunctionalTest.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/ListBucketsFunctionalTest.java

Adding functional test cases to the Huawei Cloud OBS component

CAMEL-16758: Adding functional tests to OBS

---

components/camel-elasticsearch-rest/src/main/docs/elasticsearch-rest-component.adoc

The index type is not supported in the new version of the component.

elasticsearch-rest-component endpoint options

---

components/camel-huawei/camel-huaweicloud-obs/src/main/docs/hwcloud-obs-component.adoc
components/camel-huawei/camel-huaweicloud-obs/src/main/java/org/apache/camel/component/huaweicloud/obs/OBSProducer.java
components/camel-huawei/camel-huaweicloud-obs/src/main/java/org/apache/camel/component/huaweicloud/obs/constants/OBSOperations.java
components/camel-huawei/camel-huaweicloud-obs/src/main/java/org/apache/camel/component/huaweicloud/obs/constants/OBSProperties.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/CheckBucketFunctionalTest.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/CheckBucketTest.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/constants/OBSOperationsTest.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/constants/OBSPropertiesTest.java

Adding an operation to the Huawei Cloud OBS component:
- checkBucketExists

CAMEL-16758: Add Huawei Cloud OBS operation

---

components/camel-huawei/camel-huaweicloud-obs/src/main/docs/hwcloud-obs-component.adoc
components/camel-huawei/camel-huaweicloud-obs/src/main/java/org/apache/camel/component/huaweicloud/obs/OBSProducer.java
components/camel-huawei/camel-huaweicloud-obs/src/main/java/org/apache/camel/component/huaweicloud/obs/constants/OBSOperations.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/BucketMetadataFunctionalTest.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/BucketMetadataTest.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/constants/OBSOperationsTest.java

Adding an operation to the Huawei Cloud OBS component:
- getBucketMetadata

CAMEL-16758: Add getBucketMetadata operation to OBS component

---

components/camel-huawei/camel-huaweicloud-obs/src/main/docs/hwcloud-obs-component.adoc
components/camel-huawei/camel-huaweicloud-obs/src/main/java/org/apache/camel/component/huaweicloud/obs/OBSProducer.java
components/camel-huawei/camel-huaweicloud-obs/src/main/java/org/apache/camel/component/huaweicloud/obs/constants/OBSOperations.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/ListObjectsFunctionalTest.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/ListObjectsJsonFunctionalTest.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/ListObjectsJsonTest.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/ListObjectsMaxTest.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/ListObjectsPojoFunctionalTest.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/ListObjectsPojoTest.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/ListObjectsTest.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/constants/OBSOperationsTest.java

Adding an operation to the Huawei Cloud OBS component:
- listObjects

CAMEL-16758: Add listObjects operation to OBS component

---

components/camel-digitalocean/src/main/java/org/apache/camel/component/digitalocean/producer/DigitalOceanActionsProducer.java
components/camel-digitalocean/src/main/java/org/apache/camel/component/digitalocean/producer/DigitalOceanBlockStoragesProducer.java
components/camel-digitalocean/src/main/java/org/apache/camel/component/digitalocean/producer/DigitalOceanDropletsProducer.java
components/camel-digitalocean/src/main/java/org/apache/camel/component/digitalocean/producer/DigitalOceanFloatingIPsProducer.java
components/camel-digitalocean/src/main/java/org/apache/camel/component/digitalocean/producer/DigitalOceanImagesProducer.java
components/camel-digitalocean/src/main/java/org/apache/camel/component/digitalocean/producer/DigitalOceanKeysProducer.java
components/camel-digitalocean/src/main/java/org/apache/camel/component/digitalocean/producer/DigitalOceanSnapshotsProducer.java
components/camel-digitalocean/src/main/java/org/apache/camel/component/digitalocean/producer/DigitalOceanTagsProducer.java

(chores) camel-digitalocean: avoid using generic exceptions

---

components/camel-huawei/camel-huaweicloud-obs/src/main/docs/hwcloud-obs-component.adoc
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/CreateBucketJsonFunctionalTest.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/CreateBucketPojoFunctionalTest.java

Updating documentation and code comments for Huawei Cloud OBS component

Huawei OBS Documentation Updates

---

components/camel-git/src/main/java/org/apache/camel/component/git/producer/GitProducer.java

(chores) camel-git: avoid using generic exceptions

---

components/camel-ahc-ws/src/main/java/org/apache/camel/component/ahc/ws/WsEndpoint.java

(chores) camel-ahc-ws: avoid using generic exceptions

---

core/camel-core-processor/src/main/java/org/apache/camel/processor/LoopProcessor.java

CAMEL-16794: race condition in LoopProcessor

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/json-validator-component.adoc
components/camel-json-validator/src/main/docs/json-validator-component.adoc
docs/components/modules/ROOT/pages/json-validator-component.adoc

Documentation to reflect [CAMEL-16779] [CAMEL-16780] [CAMEL-16781]

camel-json-validator documentation update

---

components/camel-kafka/src/main/docs/kafka-component.adoc

Adding a sample to topicIsPattern consuming option

---

test-infra/camel-test-infra-common/src/test/java/org/apache/camel/test/infra/common/TestUtils.java

(chores) camel-test-infra-common: use standard lib method for generating a bounded random integer

---

components/camel-consul/src/main/java/org/apache/camel/component/consul/ConsulClientConfiguration.java
components/camel-consul/src/main/java/org/apache/camel/component/consul/ConsulRegistry.java
components/camel-consul/src/main/java/org/apache/camel/component/consul/endpoint/AbstractConsulProducer.java

(chores) camel-consul: avoid using generic exceptions

---

components/camel-jms/src/main/java/org/apache/camel/component/jms/JmsConsumer.java
components/camel-jms/src/main/java/org/apache/camel/component/jms/JmsEndpoint.java
components/camel-jms/src/main/java/org/apache/camel/component/jms/reply/ReplyManagerSupport.java

(chores) camel-jms: remove unused method parameter

---

components/camel-telegram/src/main/docs/telegram-component.adoc

camel-telegram: fixed outdated reference to method that was renamed

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConfiguration.java

Fixing some typos in param name and comments

---

components/camel-ahc/src/main/java/org/apache/camel/component/ahc/AhcComponent.java
components/camel-ahc/src/main/java/org/apache/camel/component/ahc/DefaultAhcBinding.java
components/camel-ahc/src/main/java/org/apache/camel/component/ahc/helper/AhcHelper.java

- Remove unused method parameters
- Remove explicit toString call in logging
- Rework bodyGenerator code to avoid leaking resources in unusual
situations
- Simplify serialization allowed check

(chores) camel-ahc: code cleanups

---

components/camel-telegram/src/main/java/org/apache/camel/component/telegram/service/TelegramServiceRestBotAPIAdapter.java

(chores) camel-telegram: avoid using generic exceptions

---

components/camel-azure/camel-azure-cosmosdb/src/main/java/org/apache/camel/component/azure/cosmosdb/CosmosDbProducer.java
components/camel-etcd/src/main/java/org/apache/camel/component/etcd/policy/EtcdRoutePolicy.java
components/camel-facebook/src/main/java/org/apache/camel/component/facebook/FacebookProducer.java
components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/policy/HazelcastRoutePolicy.java
components/camel-irc/src/main/java/org/apache/camel/component/irc/IrcConfiguration.java
components/camel-openapi-java/src/main/java/org/apache/camel/openapi/RestOpenApiReader.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQConsumer.java
components/camel-servicenow/camel-servicenow-maven-plugin/src/main/java/org/apache/camel/maven/CamelServiceNowGenerateMojo.java
components/camel-vertx/camel-vertx-kafka/camel-vertx-kafka-component/src/main/java/org/apache/camel/component/vertx/kafka/operations/VertxKafkaConsumerOperations.java
components/camel-xpath/src/main/java/org/apache/camel/language/xpath/XPathLanguage.java
core/camel-api/src/main/java/org/apache/camel/spi/LanguageCustomizer.java
core/camel-core-model/src/main/java/org/apache/camel/model/language/XPathExpression.java
core/camel-support/src/main/java/org/apache/camel/support/PropertyBindingSupport.java
core/camel-support/src/main/java/org/apache/camel/support/ResourceHelper.java
tooling/maven/camel-api-component-maven-plugin/src/main/java/org/apache/camel/maven/AbstractApiMethodGeneratorMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PrepareCatalogMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/generics/GenericsUtil.java

(chores) Remove unused private methods

---

components/camel-ignite/pom.xml
components/camel-ignite/src/test/java/org/apache/camel/component/ignite/AbstractIgniteTest.java
test-infra/camel-test-infra-ignite/pom.xml
test-infra/camel-test-infra-ignite/src/test/java/org/apache/camel/test/infra/ignite/common/IgniteProperties.java
test-infra/camel-test-infra-ignite/src/test/java/org/apache/camel/test/infra/ignite/services/IgniteEmbeddedService.java
test-infra/camel-test-infra-ignite/src/test/java/org/apache/camel/test/infra/ignite/services/IgniteRemoteService.java
test-infra/camel-test-infra-ignite/src/test/java/org/apache/camel/test/infra/ignite/services/IgniteService.java
test-infra/camel-test-infra-ignite/src/test/java/org/apache/camel/test/infra/ignite/services/IgniteServiceFactory.java
test-infra/pom.xml

Convert ignite component to the test infra

---

components/camel-ignite/src/main/java/org/apache/camel/component/ignite/cache/IgniteCacheContinuousQueryConsumer.java
components/camel-ignite/src/main/java/org/apache/camel/component/ignite/compute/IgniteComputeProducer.java
components/camel-ignite/src/main/java/org/apache/camel/component/ignite/events/IgniteEventsEndpoint.java

- Avoid shadowing variables
- Remove unused variables
- Use specific exceptions where possible
- Use log markers

(chores) camel-ignite: code cleanups

---

components/camel-http/src/main/docs/http-component.adoc
components/camel-http/src/main/java/org/apache/camel/component/http/HttpEndpoint.java

Adding custom user agent to apache http client
JIRA - https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-16237?filter=allopenissues

CAMEL-16237 : Allow to easily set user-agent on component level

---

dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

CamelJBang: fixed displaying the help argument on request

---

components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/config_maps/KubernetesConfigMapsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/customresources/KubernetesCustomResourcesProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/deployments/KubernetesDeploymentsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/hpa/KubernetesHPAProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/job/KubernetesJobProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/namespaces/KubernetesNamespacesProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/nodes/KubernetesNodesProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/persistent_volumes/KubernetesPersistentVolumesProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/persistent_volumes_claims/KubernetesPersistentVolumesClaimsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/pods/KubernetesPodsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/resources_quota/KubernetesResourcesQuotaProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/secrets/KubernetesSecretsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/service_accounts/KubernetesServiceAccountsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/services/KubernetesServicesProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/openshift/build_configs/OpenshiftBuildConfigsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/openshift/builds/OpenshiftBuildsProducer.java

(chores) camel-kubernetes: remove unused parameters

---

dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/examples/jms-amqp-10-sink-binding.yaml
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

- implemented support for --stop for stopping on demand
- added support for maxMessages for stopping after a certain number of
messages have been processed

camel-jbang: made the stop options more flexible

---

components/camel-git/src/main/java/org/apache/camel/component/git/producer/GitProducer.java

(chores) camel-git: remove unused method parameters

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/AbstractSearch.java
dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

This is mostly to make it easier to test future changes
- includes a hidden CLI option so we can override the default
github:apache

camel-jbang: added support for using different repositories

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/AbstractSearch.java

camel-jbang-core: removed a bogus sysout from the AbstractSearch class

---

components/camel-huawei/camel-huaweicloud-obs/pom.xml
components/camel-huawei/camel-huaweicloud-obs/src/main/docs/hwcloud-obs-component.adoc
components/camel-huawei/camel-huaweicloud-obs/src/main/java/org/apache/camel/component/huaweicloud/obs/OBSConsumer.java
components/camel-huawei/camel-huaweicloud-obs/src/main/java/org/apache/camel/component/huaweicloud/obs/OBSEndpoint.java
components/camel-huawei/camel-huaweicloud-obs/src/main/java/org/apache/camel/component/huaweicloud/obs/OBSUtils.java
components/camel-huawei/camel-huaweicloud-obs/src/main/java/org/apache/camel/component/huaweicloud/obs/constants/OBSConstants.java
components/camel-huawei/camel-huaweicloud-obs/src/main/java/org/apache/camel/component/huaweicloud/obs/constants/OBSHeaders.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/DownloadDeleteFunctionalTest.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/DownloadFunctionalTest.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/DownloadMoveExistsFunctionalTest.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/DownloadMoveFunctionalTest.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/DownloadSingleFunctionalTest.java
components/camel-huawei/camel-huaweicloud-obs/src/test/java/org/apache/camel/component/huaweicloud/obs/constants/OBSHeadersTest.java

Adding a consumer endpoint to the Huawei Cloud OBS component to allow users read objects from OBS buckets.

CAMEL-16758: Add Consumer Endpoint to OBS

---

docs/user-manual/modules/faq/pages/how-do-i-configure-endpoints.adoc

Add a note to cover RAW corner cases

---

components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FileToFtpsExplicitSSLWithClientAuthIT.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FileToFtpsExplicitSSLWithoutClientAuthIT.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FileToFtpsExplicitTLSWithClientAuthIT.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FileToFtpsExplicitTLSWithoutClientAuthIT.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FileToFtpsImplicitSSLWithClientAuthIT.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FileToFtpsImplicitSSLWithoutClientAuthIT.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FileToFtpsImplicitTLSWithClientAuthIT.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FileToFtpsImplicitTLSWithoutClientAuthIT.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FileToFtpsWithCustomKeyAndTrustStorePropertiesIT.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FileToFtpsWithCustomTrustStorePropertiesIT.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FileToFtpsWithDefaultSettingsIT.java

CAMEL-16784:Disable some ftp tests

"CAMEL-16784:Disable some ftp tests"

---

components/camel-djl/src/main/java/org/apache/camel/component/djl/model/CustomImageClassificationPredictor.java
components/camel-djl/src/main/java/org/apache/camel/component/djl/model/CustomObjectDetectionPredictor.java
components/camel-djl/src/main/java/org/apache/camel/component/djl/model/ModelPredictorProducer.java
components/camel-djl/src/main/java/org/apache/camel/component/djl/model/ZooImageClassificationPredictor.java
components/camel-djl/src/main/java/org/apache/camel/component/djl/model/ZooObjectDetectionPredictor.java

- Use specific exceptions instead of generic ones
- Remove unuse exceptions for method signatures

(chores) camel-djl: cleanup exceptions

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/AbstractSearch.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/exceptions/ResourceDoesNotExist.java
dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

- fixed typo in exception
- improve error handling for when the remote resource does not exist
- remove unused code

(chores) camel-jbang: code cleanups

---

components/camel-huawei/camel-huaweicloud-obs/src/main/docs/hwcloud-obs-component.adoc

Update documentation for Huawei Cloud OBS component

Huawei OBS Documentation Update

---

components/camel-file/src/main/docs/file-component.adoc

fix: update inbox to the correct spelling.

---

components/camel-file/src/main/docs/file-component.adoc

fix: update spelling of inbox in the example.

---

docs/user-manual/modules/ROOT/nav.adoc
docs/user-manual/modules/ROOT/pages/camel-jbang.adoc

More to come in subsequent PRs ... more features are added and examples are moved to camel-examples

camel-jbang: added Camel JBang documentation

---

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/templates/VelocityTemplateParser.java
dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

camel-jbang: adjusted to automatically name the generated Kamelet

---

parent/pom.xml

Upgrade kotlin to version 1.5.21

---

components/camel-leveldb-legacy/src/main/java/org/apache/camel/component/leveldb/LevelDBAggregationRepository.java
components/camel-leveldb-legacy/src/main/java/org/apache/camel/component/leveldb/LevelDBFile.java
components/camel-leveldb/src/main/java/org/apache/camel/component/leveldb/LevelDBAggregationRepository.java
components/camel-leveldb/src/main/java/org/apache/camel/component/leveldb/LevelDBFile.java

- components: camel-leveldb and camel-leveldb-legacy

(chores) cleanup exceptions leveldb components

---

components/camel-as2/camel-as2-api/pom.xml
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/ApplicationPkcs7MimeCompressedDataEntity.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/ApplicationPkcs7MimeEnvelopedDataEntity.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/ApplicationPkcs7SignatureEntity.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/util/EntityUtils.java

- Use specific exceptions instead of generic ones
- Remove unuse exceptions for method signatures

(chores) camel-as2: cleanup exceptions

---

core/camel-base/src/main/docs/properties-component.adoc

as a newbie to camel I had a hard time finding the method `resolveProperty`. I used `this.getContext().resolvePropertyPlaceholders("{{myProperty}}");`. This code reads itself much better: `this.getContext().getPropertiesComponent().resolveProperty("pFile20WorkingDir").orElseThrow();`. It also allows us to give default values via the `Optional` type and eases error handling.

Update properties-component.adoc tip: use method `resolveProperty`

---

components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/SftpOperations.java

SftpOperations.java, log msg spelling fix Strick -> Strict

---

components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/config_maps/KubernetesConfigMapsConsumer.java

CAMEL-16841: prevent an NPE when stopping camel-kubernetes config map

---

components/camel-kubernetes/src/main/docs/kubernetes-config-maps-component.adoc

CAMEL-16838: remove invalid query parameters from camel-kubernetes documentation

---

components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/cloud/KubernetesDnsSrvServiceDiscovery.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/cluster/lock/KubernetesLeadershipController.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/config_maps/KubernetesConfigMapsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/customresources/KubernetesCustomResourcesProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/deployments/KubernetesDeploymentsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/hpa/KubernetesHPAProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/job/KubernetesJobProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/nodes/KubernetesNodesProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/persistent_volumes/KubernetesPersistentVolumesProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/persistent_volumes_claims/KubernetesPersistentVolumesClaimsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/pods/KubernetesPodsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/replication_controllers/KubernetesReplicationControllersProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/resources_quota/KubernetesResourcesQuotaProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/secrets/KubernetesSecretsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/service_accounts/KubernetesServiceAccountsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/services/KubernetesServicesProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/openshift/build_configs/OpenshiftBuildConfigsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/openshift/builds/OpenshiftBuildsProducer.java

(chores) camel-kubernetes: avoid using generic exceptions and remove unused ones

---

components/camel-kubernetes/README.md

camel-kubernetes: fixed commands in test documentation

---

components/camel-kubernetes/src/main/docs/kubernetes-config-maps-component.adoc

I think it would be good to also fix the documentation so it avoids any confusion if the user refers to it

backport CAMEL-16838: remove invalid query parameters from camel-kubernetes documentation (#5920)

---

components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/KubernetesHelper.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/config_maps/KubernetesConfigMapsConsumer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/customresources/KubernetesCustomResourcesConsumer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/deployments/KubernetesDeploymentsConsumer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/hpa/KubernetesHPAConsumer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/namespaces/KubernetesNamespacesConsumer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/nodes/KubernetesNodesConsumer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/pods/KubernetesPodsConsumer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/replication_controllers/KubernetesReplicationControllersConsumer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/services/KubernetesServicesConsumer.java

backport CAMEL-16843: prevent an NPE when stopping camel-kubernetes consumers (#5924)

---

camel-dependencies/pom.xml
components/camel-kubernetes/README.md
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/customresources/KubernetesCustomResourcesProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/deployments/KubernetesDeploymentsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/job/KubernetesJobProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/pods/KubernetesPodsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/replication_controllers/KubernetesReplicationControllersProducer.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/consumer/integration/KubernetesPodsConsumerIT.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/producer/KubernetesCustomResourcesProducerTest.java
components/camel-kubernetes/src/test/resources/log4j2.properties
components/camel-kubernetes/src/test/resources/org/apache/camel/component/kubernetes/producer/sample-cr.json
parent/pom.xml

This upgrades it to 5.6.0 (the latest versio at the time I started migrating). There's a new one, but it also requires further changes from this, so let's do it in 2 steps

CAMEL-16847: upgrade fabric8's  Kubernetes client to the latest version

---

camel-dependencies/pom.xml
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/config_maps/KubernetesConfigMapsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/hpa/KubernetesHPAProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/nodes/KubernetesNodesProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/persistent_volumes/KubernetesPersistentVolumesProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/persistent_volumes_claims/KubernetesPersistentVolumesClaimsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/secrets/KubernetesSecretsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/service_accounts/KubernetesServiceAccountsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/services/KubernetesServicesProducer.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/consumer/integration/KubernetesReplicationControllersConsumerIT.java
components/camel-kubernetes/src/test/java/org/apache/camel/component/kubernetes/consumer/integration/KubernetesServicesConsumerIT.java
parent/pom.xml

This finishes the 2-step client upgrade by bumping the client version to 5.7.0

CAMEL-16847: upgrade fabric8's Kubernetes client to the latest version

---

components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/KubernetesCategory.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/KubernetesConstants.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/KubernetesHelper.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/KubernetesOperations.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/cloud/KubernetesClientServiceDiscovery.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/deployments/KubernetesDeploymentsConsumer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/hpa/KubernetesHPAConsumer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/namespaces/KubernetesNamespacesConsumer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/namespaces/KubernetesNamespacesProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/nodes/KubernetesNodesConsumer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/persistent_volumes/KubernetesPersistentVolumesProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/pods/KubernetesPodsConsumer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/replication_controllers/KubernetesReplicationControllersConsumer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/services/KubernetesServicesConsumer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/openshift/build_configs/OpenshiftBuildConfigsProducer.java
components/camel-kubernetes/src/main/java/org/apache/camel/component/openshift/builds/OpenshiftBuildsProducer.java

- streamlined classes/interfaces holding constants
- replaced duplicated logic with code on ObjectHelper class
- removed duplicated labels logic that is now available in the
Kubernetes Client
- removed unused parameters

(chores) camel-kubernetes: code cleanup

---

catalog/camel-route-parser/src/main/java/org/apache/camel/parser/helper/XmlLineNumberParser.java

(chores) camel-route-parser: use specific exceptions instead of generic ones

---

components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/BindyAbstractDataFormat.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/BindyAbstractFactory.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/BindyCsvFactory.java

- Replace some reflection logic with reusable code from ReflectionHelper
- Logging cleanups

(chores) camel-bindy: minor cleanups

---

components/camel-huawei/camel-huaweicloud-dms/src/main/docs/hwcloud-dms-component.adoc
components/camel-huawei/camel-huaweicloud-dms/src/main/java/org/apache/camel/component/huaweicloud/dms/DMSEndpoint.java
components/camel-huawei/camel-huaweicloud-dms/src/main/java/org/apache/camel/component/huaweicloud/dms/DMSProducer.java
components/camel-huawei/camel-huaweicloud-dms/src/main/java/org/apache/camel/component/huaweicloud/dms/DmsClient.java
components/camel-huawei/camel-huaweicloud-dms/src/main/java/org/apache/camel/component/huaweicloud/dms/DmsMeta.java
components/camel-huawei/camel-huaweicloud-dms/src/main/java/org/apache/camel/component/huaweicloud/dms/constants/DMSOperations.java
components/camel-huawei/camel-huaweicloud-dms/src/main/java/org/apache/camel/component/huaweicloud/dms/models/DeleteInstanceRequest.java
components/camel-huawei/camel-huaweicloud-dms/src/main/java/org/apache/camel/component/huaweicloud/dms/models/DeleteInstanceResponse.java
components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/DeleteInstanceTest.java
components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/ListInstancesTest.java
components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/TestConfiguration.java
components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/constants/DMSPropertiesTest.java

Adding an operation to the Huawei Cloud DMS component:
- deleteInstance
JIRA - https://issues.apache.org/jira/browse/CAMEL-16876

CAMEL-16876: Add delete instance to DMS component

---

dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

camel-jbang: align features to ensure they match the same version of CamelJBang by default

---

dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

Revert "camel-jbang: align features to ensure they match the same version of CamelJBang by default"

---

components/camel-huawei/camel-huaweicloud-dms/src/main/docs/hwcloud-dms-component.adoc
components/camel-huawei/camel-huaweicloud-dms/src/main/java/org/apache/camel/component/huaweicloud/dms/DMSEndpoint.java
components/camel-huawei/camel-huaweicloud-dms/src/main/java/org/apache/camel/component/huaweicloud/dms/DMSProducer.java
components/camel-huawei/camel-huaweicloud-dms/src/main/java/org/apache/camel/component/huaweicloud/dms/DmsClient.java
components/camel-huawei/camel-huaweicloud-dms/src/main/java/org/apache/camel/component/huaweicloud/dms/DmsMeta.java
components/camel-huawei/camel-huaweicloud-dms/src/main/java/org/apache/camel/component/huaweicloud/dms/constants/DMSConstants.java
components/camel-huawei/camel-huaweicloud-dms/src/main/java/org/apache/camel/component/huaweicloud/dms/constants/DMSProperties.java
components/camel-huawei/camel-huaweicloud-dms/src/main/java/org/apache/camel/component/huaweicloud/dms/models/ClientConfigurations.java
components/camel-huawei/camel-huaweicloud-dms/src/main/java/org/apache/camel/component/huaweicloud/dms/models/CreateInstanceRequest.java
components/camel-huawei/camel-huaweicloud-dms/src/main/java/org/apache/camel/component/huaweicloud/dms/models/CreateInstanceRequestBody.java
components/camel-huawei/camel-huaweicloud-dms/src/main/java/org/apache/camel/component/huaweicloud/dms/models/CreateInstanceResponse.java
components/camel-huawei/camel-huaweicloud-dms/src/main/java/org/apache/camel/component/huaweicloud/dms/models/UpdateInstanceRequest.java
components/camel-huawei/camel-huaweicloud-dms/src/main/java/org/apache/camel/component/huaweicloud/dms/models/UpdateInstanceRequestBody.java
components/camel-huawei/camel-huaweicloud-dms/src/main/java/org/apache/camel/component/huaweicloud/dms/models/UpdateInstanceResponse.java
components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/CreateInstanceJsonTest.java
components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/CreateInstanceKafkaTest1.java
components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/CreateInstanceKafkaTest2.java
components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/CreateInstancePojoTest.java
components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/CreateInstanceRmqTest1.java
components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/CreateInstanceRmqTest2.java
components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/TestConfiguration.java
components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/UpdateInstanceJsonTest.java
components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/UpdateInstancePojoTest.java
components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/constants/DMSConstantsTest.java
components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/constants/DMSOperationsTest.java
components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/constants/DMSPropertiesTest.java

Adding 2 operations to the Huawei Cloud DMS component:
- createInstance
- updateInstance
JIRA - https://issues.apache.org/jira/browse/CAMEL-16876

CAMEL-16876: Add Create and Update instance to DMS

---

components/camel-debezium/camel-debezium-common/camel-debezium-common-component/src/main/java/org/apache/camel/component/debezium/DebeziumConstants.java
components/camel-debezium/camel-debezium-common/camel-debezium-common-component/src/main/java/org/apache/camel/component/debezium/DebeziumEndpoint.java
components/camel-debezium/camel-debezium-common/camel-debezium-common-component/src/test/java/org/apache/camel/component/debezium/DebeziumEndpointTest.java

issue links: https://issues.apache.org/jira/browse/CAMEL-16882

CAMEL-16882 Add ddl sql output in header

---

components/camel-huawei/camel-huaweicloud-dms/src/main/docs/hwcloud-dms-component.adoc

Update documentation for Huawei Cloud DMS component

Huawei DMS Doc Update

---

components/camel-cm-sms/src/test/java/org/apache/camel/component/cm/test/CMConfigurationTest.java
components/camel-cm-sms/src/test/java/org/apache/camel/component/cm/test/CMMessageTest.java
components/camel-cm-sms/src/test/java/org/apache/camel/component/cm/test/CMTest.java
components/camel-cm-sms/src/test/java/org/apache/camel/component/cm/test/SMSMessageTest.java

- Cleanup/simplify assertions
- Remove unused exceptions declarations
- Remove commented code

(chores) camel-cm-sms: cleanup test code

---

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/EntityParser.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/util/HttpMessageUtils.java

Improve NPE handling and information in some unlikely, but still possible, situations

(chores) camel-as2-api: improve NPE handling

---

components/camel-bindy/src/test/java/org/apache/camel/dataformat/bindy/format/factories/BigDecimalFormatFactoryTest.java
components/camel-facebook/src/test/java/org/apache/camel/component/facebook/data/FacebookMethodsTypeHelperTest.java
components/camel-grok/src/test/java/org/apache/camel/component/grok/GrokPatternsTest.java
components/camel-http/src/test/java/org/apache/camel/component/http/HttpInvalidConfigurationTest.java
components/camel-http/src/test/java/org/apache/camel/component/http/HttpInvalidHttpClientConfigurationTest.java
components/camel-jetty/src/test/java/org/apache/camel/component/jetty/HttpProducerJMXBeansIssueTest.java
components/camel-jooq/src/test/java/org/apache/camel/component/jooq/JooqXMLTest.java
components/camel-jt400/src/test/java/org/apache/camel/component/jt400/Jt400DataQueueConsumerTest.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaConsumerTest.java
components/camel-leveldb-legacy/src/test/java/org/apache/camel/component/leveldb/LevelDBSetupTest.java
components/camel-leveldb/src/test/java/org/apache/camel/component/leveldb/LevelDBSetupTest.java
components/camel-microprofile/camel-microprofile-metrics/src/test/java/org/apache/camel/component/microprofile/metrics/MicroProfileMetricsHelperTest.java
components/camel-milo/src/test/java/org/apache/camel/component/milo/server/ServerLocalTest.java
components/camel-milo/src/test/java/org/apache/camel/component/milo/server/ServerSetSecurityPoliciesTest.java

components: camel-bindy, camel-facebook, camel-grok, camel-http,
camel-jetty, camel-jooq, camel-jt400, camel-kafka, camel-leveldb,
camel-leveldb-legacy, camel-microprofile, camel-milo

(chores) fixed missing assertions in test code

---

components/camel-grape/src/main/java/org/apache/camel/component/grape/FilePatchesRepository.java
components/camel-minio/src/main/java/org/apache/camel/component/minio/MinioProducer.java

(chores) fix resource leaks in camel-grape and camel-minio

---

components/camel-rss/src/main/java/org/apache/camel/component/rss/RssUtils.java

(chores) camel-rss: fix a resource leak reading from XML

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/AbstractGeneratorMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/ComponentDslMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointDslMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/GenerateEndpointUriFactoryMojo.java

(chores) camel-maven-plugin: fix resource leak when finding files

---

components/camel-jsonpath/src/main/docs/jsonpath-language.adoc

Inline Simple exceptions => Inline Simple expressions

Fix typo in section title

---

tooling/maven/camel-javadoc-plugin/src/main/java/org/apache/maven/plugins/javadoc/CamelJavadocJar.java
tooling/maven/camel-javadoc-plugin/src/main/java/org/apache/maven/plugins/javadoc/StaleHelper.java
tooling/maven/camel-maven-plugin/src/main/java/org/apache/camel/maven/PrepareFatJarMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PackageJandexMojo.java
tooling/maven/camel-resources-plugin/src/main/java/org/apache/camel/maven/resources/CopyResources.java

(chores) tooling: fix resource leaks while processing stream of files/dirs

---

components/camel-mllp/src/main/java/org/apache/camel/component/mllp/internal/TcpServerBindThread.java

Add a comment in the code and simplify it a bit to avoid an impression
that there is a leak.

(chores) camel-mllp: add note about not a leak

---

components/camel-mllp/src/main/java/org/apache/camel/component/mllp/MllpTcpClientProducer.java

Add a comment in the code and simplify it a bit to avoid a false impression that the socket resources are not being closed.

(chores) camel-mllp: add note about not a leak on the socket

---

docs/user-manual/modules/ROOT/pages/testing.adoc

Took me a good 15 minutes to realise the component had a typo
- Fix a small typo in the camel-testcontainers-junit5 and camel-testcontainers-junit5 module links.

[Docs] Fix typo in testing docs

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PackageJaxbMojo.java

(chores) camel-maven-plugin: fix a possible leak when creating the filesystem

---

core/camel-core-languages/src/main/docs/modules/languages/pages/simple-language.adoc
docs/user-manual/modules/ROOT/pages/route-template.adoc
docs/user-manual/modules/ROOT/pages/using-propertyplaceholder.adoc

This is the main branch version of #6039
I think applying this first will let us upgrade camel-website to antora 3 and then add the jsonpath changes.

[website] fix some attribute problems (main)

---

components/camel-kafka/src/main/docs/kafka-component.adoc
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/serde/KafkaSerdeHelper.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/CustomHeaderDeserializer.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerFullIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentTestSupport.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentWithCustomSerializerIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentWithProcessorIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerTopicIsPatternIT.java
docs/components/modules/ROOT/pages/kafka-component.adoc

CAMEL-16914: simplify handling of numeric headers for idempotency support

Backport CAMEL-16914

---

test-infra/README.md

CAMEL-16926: added details about running test-infra with Podman

---

components/camel-kafka/src/main/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepository.java

CAMEL-16928: avoid blocking in the idempotent repository

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConfiguration.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaProducer.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaProducerTest.java

- replaced reference to deprecated configuration constant
- cleanup generating Kafka properties from endpoint configuration
- replaced reference to deprecated configuration constant
- removed usage of deprecated hasOut/getOut methods
- do not assert a primitive for null

(chores) camel-kafka: code cleanups

---

core/camel-util/src/main/java/org/apache/camel/util/ObjectHelper.java

cleanup ObjectHelper utility

---

components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/NettyHttpHelper.java
components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpProducerHttpPathTest.java

CAMEL-16957: Do not append slash to an empty path

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/KafkaRecordProcessor.java

- avoid recreating the result object everytime
- move the poll log message out of the hot path loop
- remove duplicated message
- minor cleanups to avoid running expensive calls when in debug

(chores) camel-kafka: minor cleanups:

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/KafkaRecordProcessor.java

- consolidate common code
- adjust the hash map containing the last processed offset to not use a
concurrent collection (the instance is only accessed within the local
consumer thread and should be safe using a non-concurrent collection)

(chores) camel-kafka: fixes and cleanups

---

components/camel-huawei/camel-huaweicloud-smn/pom.xml

CAMEL-16980 - Added commons-lang3 dependency to Huawei SMN component
https://issues.apache.org/jira/browse/CAMEL-16980
commons-lang3-version needs to be added to camel-huaweicloud-smn component to  resolve compilation issues at line https://github.com/apache/camel/blob/main/components/camel-huawei/camel-huaweicloud-smn/src/main/java/org/apache/camel/component/huaweicloud/smn/SimpleNotificationProducer.java#L35

CAMEL-16980 - Added commons-lang3 dependency to Huawei SMN component

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/PartitionAssignmentListener.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/SeekPolicyResumeStrategy.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerFullIT.java

camel-kafka: fix integration test failing on CI

---

core/camel-main/src/main/docs/main.adoc
core/camel-main/src/test/java/org/apache/camel/main/MainBeansClassStaticFactoryMethodTest.java

Add support for @Schema annotation parameters "description" and "example".

[CAMEL-16986] Add support for description and example in @Schema annotation

---

components/camel-spring-redis/src/main/docs/spring-redis-component.adoc

Issue: https://issues.apache.org/jira/browse/CAMEL-16989

CAMEL-16989 Spring-redis: Add header constans to the doc

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/MockConsumerInterceptor.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerFullIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentWithCustomSerializerIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentWithProcessorIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerManualCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerTopicIsPatternIT.java

Enable the idempotent tests by default after fixing problems in a few of
our tests

(chores) camel-kafka: fix test issues and enable more tests

---

docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_12.adoc

CAMEL-16993: included recent changes on camel-kafka to the migration guide

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerFullIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentTestSupport.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentWithCustomSerializerIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentWithProcessorIT.java
components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryPersistenceIT.java

camel-kafka: test fixes for remote mode and Kafka 3.0

---

camel-core/src/main/docs/modules/languages/pages/simple-language.adoc
components/camel-elsql/src/main/docs/elsql-component.adoc
docs/components/antora.yml
docs/components/modules/ROOT/pages/elsql-component.adoc

Link to latest released EIP. 
Fix one in-component link.
Fix some AsciiDoc syntax.

[CAMEL-16992] Link to latest released EIP. ++

---

components/camel-djl/src/main/docs/djl-component.adoc
components/camel-djl/src/main/java/org/apache/camel/component/djl/model/ZooImageClassificationPredictor.java

camel-djl: remove commented code and fix broken links in documentation

---

components/camel-aws/camel-aws2-lambda/src/main/java/org/apache/camel/component/aws2/lambda/Lambda2Producer.java
components/camel-aws/camel-aws2-lambda/src/test/java/org/apache/camel/component/aws2/lambda/integration/LambdaCreateGetAliasIT.java

CAMEL-17007: fix getAlias operation in camel-aws2-lambda

---

components/camel-http/src/main/java/org/apache/camel/component/http/HttpProducer.java
components/camel-jetty/src/test/java/org/apache/camel/component/jetty/HttpProducerOkStatusCodeRangeTest.java
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/NettyHttpProducer.java
components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpOkStatusCodeTest.java
components/camel-vertx/camel-vertx-http/src/main/java/org/apache/camel/component/vertx/http/VertxHttpEndpoint.java
components/camel-vertx/camel-vertx-http/src/test/java/org/apache/camel/component/vertx/http/VertxHttpThrowExceptionOnFailureTest.java

Fixes CAMEL-17008 in all affected components

CAMEL-17008: okStatusCodeRange single value

---

components/camel-aws/camel-aws2-lambda/src/main/docs/aws2-lambda-component.adoc
components/camel-aws/camel-aws2-lambda/src/main/java/org/apache/camel/component/aws2/lambda/Lambda2Producer.java
components/camel-aws/camel-aws2-lambda/src/test/java/org/apache/camel/component/aws2/lambda/integration/LambdaAliasesIT.java

CAMEL-17012: Fix listAliases operation in camel-aws2-lambda

---

dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/pom.xml
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

camel-jbang: work-around not updating during release build

---

core/camel-core/src/test/java/org/apache/camel/processor/MdcClearingTest.java

CAMEL-17009 Test reproducing a bug

---

components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryPersistenceIT.java

I believe this will also fix the CI flakiness on this one.

camel-kafka: increase test coverage for the idempotent repository

---

components/camel-atlasmap/pom.xml
components/camel-atlasmap/src/main/docs/atlasmap-component.adoc

CAMEL-17023 Do not bundle Atlasmap DFDL module

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerFullIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentTestSupport.java

camel-kafka: remove bogus sleeps on the test code

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaProducer.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/producer/support/KeyValueHolderIterator.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/producer/support/ProducerUtil.java

CAMEL-17026: reorganize the code iterator-related code on the producer

---

core/camel-support/src/main/java/org/apache/camel/support/ScheduledPollConsumer.java

camel-support: fixed formatting issue

---

core/camel-support/src/main/java/org/apache/camel/support/task/BackgroundTask.java

CAMEL-17121: fixed missing reset the Thread's interrupt status

---

components/camel-mongodb-gridfs/src/main/java/org/apache/camel/component/mongodb/gridfs/GridFsConsumer.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/IterationBoundedBudget.java

CAMEL-17121: converted mongodb-gridfs to the repeatable tasks

---

components/camel-openapi-java/src/main/java/org/apache/camel/openapi/DefaultRestDefinitionsResolver.java
components/camel-openapi-java/src/main/java/org/apache/camel/openapi/OpenApiHelper.java
components/camel-openapi-java/src/main/java/org/apache/camel/openapi/OpenApiRestProducerFactory.java
components/camel-openapi-java/src/main/java/org/apache/camel/openapi/RestModelConverters.java
components/camel-openapi-java/src/main/java/org/apache/camel/openapi/RestOpenApiReader.java
components/camel-openapi-java/src/main/java/org/apache/camel/openapi/RestOpenApiSupport.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/DynamicRouterProcessor.java

CAMEL-17151: Eliminated double slash in api-doc path.

---

components/camel-openapi-java/pom.xml

Running test in parallel on my machine I got this performance increase from ~2 minutes to ~40 seconds

[CAMEL-17155] Run tests in parallel

---

components/camel-sql/src/main/java/org/apache/camel/processor/aggregate/jdbc/JdbcAggregationRepository.java

When concurrent threads try to start aggregation with the same key at the same time, one should get an OptimisticLockingExeption instead of a NullPointerException

CAMEL-15723

---

components/camel-jetty/src/test/java/org/apache/camel/component/jetty/rest/RestJettyContentTypeTest.java
components/camel-servlet/src/test/java/org/apache/camel/component/servlet/rest/RestServletContentTypeTest.java
components/camel-undertow/src/test/java/org/apache/camel/component/undertow/rest/RestUndertowContentTypeTest.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/RestBindingAdvice.java

Added tests for this in jetty, servlet and undertow components

[CAMEL-17159] Changes to support multiple valid content types

---

components/camel-optaplanner/src/main/java/org/apache/camel/component/optaplanner/OptaPlannerProducer.java

Also comes with a small typo fix.

CAMEL-17121: converted camel-optaplanner for repeatable tasks

---

core/camel-support/src/main/java/org/apache/camel/support/task/BackgroundTask.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/Budget.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/IterationBudget.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/IterationTimeBoundedBudget.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/TimeBoundedBudget.java
core/camel-support/src/test/java/org/apache/camel/support/task/BackgroundIterationTimeTaskTest.java

CAMEL-17121: fixed time+iteration bounded support for background tasks

---

core/camel-support/src/main/java/org/apache/camel/support/task/BackgroundTask.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/Budget.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/Budgets.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/IterationBudget.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/IterationTimeBoundedBudget.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/IterationTimeBoundedBudgetBuilder.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/TimeBoundedBudget.java
core/camel-support/src/test/java/org/apache/camel/support/task/BackgroundIterationTimeTaskTest.java

Depends on #6394 
Obs.: I'm just queueing work to merge once the release preparation is complete and we can merge to main.

CAMEL-17121: added support for timed tasks w/ unlimited duration

---

components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitConsumer.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQConsumer.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQEndpoint.java

CAMEL-17121: converted camel-rabbitmq to repeatable tasks

---

components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppConsumer.java

CAMEL-17121: converted camel-smpp to the repeatable tasks

---

components/camel-soroush/src/main/java/org/apache/camel/component/soroushbot/component/SoroushBotAbstractConsumer.java
components/camel-soroush/src/main/java/org/apache/camel/component/soroushbot/component/SoroushBotEndpoint.java
components/camel-soroush/src/main/java/org/apache/camel/component/soroushbot/component/SoroushBotSendMessageProducer.java
components/camel-soroush/src/main/java/org/apache/camel/component/soroushbot/utils/ExponentialBackOffStrategy.java
components/camel-soroush/src/main/java/org/apache/camel/component/soroushbot/utils/FixedBackOffStrategy.java
components/camel-soroush/src/main/java/org/apache/camel/component/soroushbot/utils/LinearBackOffStrategy.java
core/camel-support/src/main/java/org/apache/camel/support/task/ForegroundTask.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/IterationBoundedBudget.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/IterationBoundedBudgetBuilder.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/IterationTimeBoundedBudget.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/backoff/BackOffStrategy.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/backoff/FixedBackOffStrategy.java
core/camel-support/src/test/java/org/apache/camel/support/task/TaskTestSupport.java

~Marking as draft since it depends on #6397 (I'm just releasing my backlog)~

CAMEL-17121: converted camel-soroush to use the repeatable tasks

---

components/camel-cbor/src/main/docs/cbor-dataformat.adoc
components/camel-hl7/src/main/docs/hl7-dataformat.adoc
components/camel-hl7/src/main/java/org/apache/camel/component/hl7/HL7DataFormat.java
components/camel-jackson-avro/src/main/docs/avro-jackson-dataformat.adoc
components/camel-jackson-protobuf/src/main/docs/protobuf-jackson-dataformat.adoc
components/camel-jackson/src/main/java/org/apache/camel/component/jackson/AbstractJacksonDataFormat.java
components/camel-jackson/src/main/java/org/apache/camel/component/jackson/JacksonDataFormat.java
components/camel-jacksonxml/src/main/docs/jacksonxml-dataformat.adoc
components/camel-jacksonxml/src/main/java/org/apache/camel/component/jacksonxml/JacksonXMLDataFormat.java
components/camel-mongodb/src/main/docs/mongodb-component.adoc

Fix wrong HTTP links and docs

---

components/camel-splunk/src/main/java/org/apache/camel/component/splunk/support/SplunkDataReader.java

CAMEL-17121: converted camel-splunk to repeatable tasks where appropriate

---

components/camel-zookeeper/src/main/java/org/apache/camel/component/zookeeper/cluster/ZooKeeperClusterView.java

CAMEL-17121: converted camel-zookeeper to repeatable tasks

---

core/camel-support/src/main/java/org/apache/camel/support/cache/DefaultProducerCache.java

Obs.: I am running more extensive tests for this one, so it may be better to wait ... but preliminary reviews are welcome.

CAMEL-17121: converted the default producer cache to use repeatable tasks

---

core/camel-support/src/main/java/org/apache/camel/support/task/ForegroundTask.java

CAMEL-17221: added support for a repeatable task that stops upon return

---

components/camel-jms/src/main/java/org/apache/camel/component/jms/reply/ReplyManagerSupport.java

CAMEL-17121: converted camel-jms reply manager to repeatable tasks

---

components/camel-directvm/src/main/java/org/apache/camel/component/directvm/DirectVmBlockingProducer.java
core/camel-support/src/main/java/org/apache/camel/support/task/ForegroundTask.java

CAMEL-17121: converted directvm to the repeatable tasks

---

components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/reply/ReplyManagerSupport.java

CAMEL-17121: converted camel-rabbitmq reply manager to repeatable tasks

---

components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppConsumer.java
components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppProducer.java
components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppUtils.java

CAMEL-17121: converted camel-smpp producer to the repeatable tasks

---

dsl/camel-xml-jaxb-dsl-test/jbpm/src/test/java/org/apache/camel/component/jbpm/server/CamelKieServerExtensionTest.java

Hi @davsclaus I had to update the test in order to handle this issue [CAMEL-17116](https://issues.apache.org/jira/browse/CAMEL-17116)

[CAMEL-17176] Fix error in unit test

---

components/camel-directvm/src/main/java/org/apache/camel/component/directvm/DirectVmBlockingProducer.java

CAMEL-17121: present the awaitConsumer from blocking indefinitely

---

core/camel-support/src/main/java/org/apache/camel/support/task/BackgroundTask.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/BudgetBuilder.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/Budgets.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/IterationBoundedBudget.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/IterationBudget.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/IterationTimeBoundedBudget.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/TimeBoundedBudget.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/TimeBudget.java

- Added documentation details
- Fixed typos
- Fixed/improved log messages
- Used final for a few variables

CAMEL-17121: final cleanups

---

core/camel-core/src/test/java/org/apache/camel/component/direct/DirectProducerBlockingTest.java
core/camel-core/src/test/java/org/apache/camel/component/directvm/DirectVmProducerBlockingTest.java
core/camel-core/src/test/java/org/apache/camel/component/seda/SedaBlockWhenFullTest.java
core/camel-core/src/test/java/org/apache/camel/component/seda/SedaConfigureTest.java
core/camel-core/src/test/java/org/apache/camel/component/seda/SedaDefaultBlockWhenFullTest.java
core/camel-core/src/test/java/org/apache/camel/impl/DefaultProducerTemplateNonBlockingAsyncTest.java
core/camel-core/src/test/java/org/apache/camel/processor/DeadLetterChannelRedeliverWithDelayBlockingTest.java
core/camel-core/src/test/java/org/apache/camel/processor/async/AsyncEndpointRoutingSlipBeanNonBlockingTest.java

(chores) Ensures some of the core tests have timeouts

---

core/camel-support/src/main/java/org/apache/camel/support/cache/DefaultProducerCache.java
core/camel-support/src/main/java/org/apache/camel/support/task/BackgroundTask.java
core/camel-support/src/main/java/org/apache/camel/support/task/ForegroundTask.java
core/camel-support/src/main/java/org/apache/camel/support/task/Task.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/Budget.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/IterationBoundedBudget.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/IterationTimeBoundedBudget.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/TimeBoundedBudget.java
core/camel-support/src/test/java/org/apache/camel/support/task/BackgroundTaskTest.java
core/camel-support/src/test/java/org/apache/camel/support/task/ForegroundTaskTest.java
core/camel-support/src/test/java/org/apache/camel/support/task/ForegroundTimeTaskTest.java

CAMEL-17121: added support for accounting and reporting the elapsed time

---

core/camel-support/src/main/java/org/apache/camel/support/task/BackgroundTask.java
core/camel-support/src/main/java/org/apache/camel/support/task/ForegroundTask.java
core/camel-support/src/test/java/org/apache/camel/support/task/BackgroundTaskTest.java

This prevents the tests from failing due to scheduling, drifts and
precision differences between different systems.
It also ensures that the task elapsed time represents the task
duration with greater precision

CAMEL-17188: evaluate test executions within a range

---

docs/user-manual/modules/faq/pages/how-do-i-retry-processing-a-message-from-a-certain-point-back-or-an-entire-route.adoc

Correct typos

---

components/camel-zookeeper/src/main/java/org/apache/camel/component/zookeeper/cluster/ZooKeeperClusterService.java

(chores) camel-zookeeper: fixed typo

---

core/camel-core-engine/src/main/docs/antora.yml
docs/components/antora.yml

See https://github.com/apache/camel-website/issues/670

docs release update to 3.13.x

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java

Remaining part of the ticket fix

CAMEL-17131: avoid duplicate initialization of the Kafka consumer

---

docs/user-manual/modules/ROOT/pages/release-guide-website.adoc

See https://github.com/apache/camel-website/issues/670
I believe I have followed the instructions as (now) written.

update guide to updating website on releases

---

components/camel-couchbase/src/test/java/org/apache/camel/component/couchbase/integration/CouchbaseIntegrationTestBase.java

CAMEL-15520: cleanup a deprecation in camel-couchbase test

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java

(chores) camel-kafka: fixed missing parameter in a log message

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/KafkaRecordProcessor.java

(chores) camel-kafka: ensure some log messages in the hot path are guarded

---

components/camel-servicenow/camel-servicenow-component/src/main/java/org/apache/camel/component/servicenow/releases/helsinki/HelsinkiServiceNowScorecardProcessor.java
components/camel-servicenow/camel-servicenow-component/src/main/java/org/apache/camel/component/servicenow/releases/helsinki/HelsinkiServiceNowServiceCatalogCartsProcessor.java
components/camel-servicenow/camel-servicenow-component/src/main/java/org/apache/camel/component/servicenow/releases/helsinki/HelsinkiServiceNowServiceCatalogCategoriesProcessor.java
components/camel-servicenow/camel-servicenow-component/src/main/java/org/apache/camel/component/servicenow/releases/helsinki/HelsinkiServiceNowServiceCatalogItemsProcessor.java
components/camel-servicenow/camel-servicenow-component/src/main/java/org/apache/camel/component/servicenow/releases/helsinki/HelsinkiServiceNowServiceCatalogProcessor.java
components/camel-servicenow/camel-servicenow-component/src/main/java/org/apache/camel/component/servicenow/releases/helsinki/HelsinkiServiceNowTableProcessor.java
components/camel-soroush/src/main/java/org/apache/camel/component/soroushbot/component/SoroushBotEndpoint.java
components/camel-spring-rabbitmq/src/main/java/org/apache/camel/component/springrabbit/SpringRabbitMQConsumer.java

Components: camel-servicenow, camel-soroush, camel-spring-rabbitmq

(chores) removed unused exceptions

---

components/camel-soroush/src/test/java/org/apache/camel/component/soroushbot/support/SoroushMockServer.java

(chores) camel-soroush: avoid using fixed ports for the tests

---

components/camel-hbase/src/main/java/org/apache/camel/component/hbase/HBaseProducer.java
components/camel-hbase/src/test/java/org/apache/camel/component/hbase/HBaseProducerIT.java

(chores) minor camel-hbase cleanups

---

components/camel-kudu/src/test/java/org/apache/camel/component/kudu/AbstractKuduTest.java
components/camel-kudu/src/test/java/org/apache/camel/component/kudu/IntegrationKuduConfiguration.java

This includes a fix for false negative test errors when a required client library (ncurses) is missing

(chores) minor camel-kudu fixes and cleanups

---

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/streaming/SubscriptionHelper.java

(chores) camel-salesforce: fix a potential NPE

---

components/camel-jetty/pom.xml
components/camel-jetty/src/test/java/org/apache/camel/component/jetty/HttpStreamCacheFileResponseTest.java
components/camel-jetty/src/test/java/org/apache/camel/component/jetty/HttpToFileTest.java
components/camel-jetty/src/test/java/org/apache/camel/component/jetty/file/JettyFileConsumerTest.java

(chores) camel-jetty: replace Thread.sleep with Awaitility in tests

---

components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/integration/RabbitMQConsumerReplyToIT.java
components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/integration/RabbitMQDeadLetterRoutingKeyIT.java
components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/integration/RabbitMQProducerIT.java

(chores) camel-rabbitmq: replace Thread.sleep with Awaitility in tests

---

core/camel-core/src/test/java/org/apache/camel/support/DefaultTimeoutMapTest.java
core/camel-management/src/test/java/org/apache/camel/management/ManagedRouteStopWithAbortAfterTimeoutTest.java
core/camel-management/src/test/java/org/apache/camel/management/ManagedThreadPoolTest.java

(chores) replace Thread.sleep with Awaitility in core tests

---

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java

CAMEL-17230: added support for loading unpublished local Kamelets

---

components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Consumer.java
components/camel-aws/camel-aws2-s3/src/test/java/org/apache/camel/component/aws2/s3/integration/S3ConsumerIncludeBodyIT.java

This reverts commit ad296097c48558ffdf938fd8646bbeb6e7fd6320.

CAMEL-17232: Revert "Camel-AWS2-S3: When includeBody is false

---

components/camel-couchbase/src/test/java/org/apache/camel/component/couchbase/integration/ConsumeMessagesWithLimitIT.java

(chores) camel-couchbase: fixed incorrect usage of JUnit 4 annotations

---

components/camel-swagger-java/src/test/java/org/apache/camel/swagger/ParameterAssert.java
components/camel-swagger-java/src/test/java/org/apache/camel/swagger/RestSwaggerArrayEnumTest.java

I am separating this one as it as a few more changes than the others

(chores) camel-swagger-java: simplified assertions and fixed missing predicates

---

core/camel-core/src/test/java/org/apache/camel/processor/intercept/InterceptFromRouteTestSupport.java
core/camel-core/src/test/java/org/apache/camel/processor/intercept/InterceptFromWithPredicateTest.java

Several interpect tests were being skipped because the base classes was
missing Junit annotations. This makes runnable 14 tests that depended on that.

(chores) camel-core: fixed intercept tests

---

components/camel-couchbase/src/test/java/org/apache/camel/component/couchbase/CouchbaseEndpointTest.java
components/camel-csimple-joor/src/test/java/org/apache/camel/language/csimple/joor/OriginalSimpleTest.java
components/camel-debezium/camel-debezium-common/camel-debezium-maven-plugin/src/test/java/org/apache/camel/maven/config/ConnectorConfigGeneratorTest.java
components/camel-git/src/test/java/org/apache/camel/component/git/producer/GitProducerTest.java
components/camel-http/src/test/java/org/apache/camel/component/http/HttpDisableStreamCacheTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsTransferExceptionTest.java
components/camel-kamelet/src/test/java/org/apache/camel/component/kamelet/KameletRouteTest.java
components/camel-mina/src/test/java/org/apache/camel/component/mina/MinaCustomCodecTest.java
components/camel-mina/src/test/java/org/apache/camel/component/mina/MinaInOutWithForcedNoResponseTest.java
components/camel-mina/src/test/java/org/apache/camel/component/mina/MinaNoResponseFromServerTest.java
components/camel-mina/src/test/java/org/apache/camel/component/mina/MinaVMCustomCodecTest.java
components/camel-mllp/src/test/java/org/apache/camel/component/mllp/internal/MllpSocketBufferWriteTest.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/meta/integration/MongoDbMetaExtensionIT.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyRequestTimeoutTest.java
components/camel-spring-batch/src/test/java/org/apache/camel/component/spring/batch/SpringBatchEndpointTest.java
components/camel-sql/src/test/java/org/apache/camel/component/sql/SqlEndpointMisconfigureDataSourceTest.java
components/camel-stitch/src/test/java/org/apache/camel/component/stitch/client/StitchClientBuilderTest.java
components/camel-vertx/camel-vertx-http/src/test/java/org/apache/camel/component/vertx/http/VertxHttpSerializedBodyTest.java

These could cause false positives/negatives if the exception is thrown
by a different method than the one under test.
Components:
- camel-couchbase, camel-csimple-joor, camel-debezium, camel-couchbase,
camel-git, camel-http, camel-http, camel-jms, camel-kamelet, camel-mina,
camel-mllp, camel-mongodb, camel-netty, camel-mina, camel-sql,
camel-spring-batch, camel-stitch, camel-vertx-http

(chores) test-cleanups: fixed incorrect assertions for exceptions

---

components/camel-aws/camel-aws-secrets-manager/src/test/java/org/apache/camel/component/aws/secretsmanager/integration/AwsSecretsManagerBaseTest.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/integration/Aws2SQSBaseTest.java
components/camel-google/camel-google-bigquery/src/test/java/org/apache/camel/component/google/bigquery/unit/BaseBigQueryTest.java
components/camel-google/camel-google-bigquery/src/test/java/org/apache/camel/component/google/bigquery/unit/sql/GoogleBigQuerySQLProducerBaseTest.java
components/camel-google/camel-google-functions/src/test/java/org/apache/camel/component/google/functions/unit/GoogleCloudFunctionsBaseTest.java
components/camel-google/camel-google-storage/src/test/java/org/apache/camel/component/google/storage/unit/GoogleCloudStorageBaseTest.java
components/camel-influxdb/src/test/java/org/apache/camel/component/influxdb/AbstractInfluxDbTest.java
components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/routepolicy/AbstractMicrometerRoutePolicyTest.java
components/camel-mina/src/test/java/org/apache/camel/component/mina/BaseMinaTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/BaseNettyTest.java
components/camel-nitrite/src/test/java/org/apache/camel/component/nitrite/AbstractNitriteTest.java
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/BaseQuartzTest.java
components/camel-quartz/src/test/java/org/apache/camel/routepolicy/quartz/NoBuilderTest.java
components/camel-thrift/src/test/java/org/apache/camel/component/thrift/ThriftProducerBaseTest.java
components/camel-undertow/src/test/java/org/apache/camel/component/undertow/BaseUndertowTest.java
components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/XmppBaseContainerTest.java

This should prevent them from being misunderstood and/or directly instantiated as test classes

(chores) test-cleanups: make base test classes abstract

---

components/camel-mllp/src/test/java/org/apache/camel/component/mllp/internal/MllpSocketBufferWriteTest.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/meta/integration/MongoDbMetaExtensionIT.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyRequestTimeoutTest.java
components/camel-vertx/camel-vertx-http/src/test/java/org/apache/camel/component/vertx/http/VertxHttpSerializedBodyTest.java

(chores) fixed formatting issues

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/KameletMain.java

CAMEL-17230: cleanup loading unpublished local Kamelets

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java

CAMEL-17244: avoid creating multiple consumers if already connected

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaProducerTest.java

CAMEL-17241: fixed incorrect exception test

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java

CAMEL-17245: prevent bogus commit calls when shutting down camel-kafka

---

dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

CAMEL-17248: added camel-kamelets as a runtime dependency for camel-jbang

---

docs/user-manual/modules/ROOT/pages/improving-the-documentation.adoc
docs/user-manual/modules/faq/pages/how-do-i-edit-the-website.adoc
docs/user-manual/modules/faq/pages/how-does-the-website-work.adoc

I think this is a more realistic guide to how to work on the documentation than what it replaces.  It also is an experiment about a simpler way to get a website PR/preview build.

rewrite improving-the-documentation.adoc

---

core/camel-api/src/main/java/org/apache/camel/health/HealthCheckResolver.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/KameletYamlRoutes.java

Fix CAMEL-17252: https://issues.apache.org/jira/browse/CAMEL-17252

[CAMEL-17252] fix Error in KameletYamlRoutes while loading routes based on kemelets without dependencies.

---

components/camel-splunk-hec/src/main/java/org/apache/camel/component/splunkhec/SplunkHECEndpoint.java
components/camel-splunk-hec/src/test/java/org/apache/camel/component/splunkhec/SplunkHECEndpointTest.java

Improves URI validation messages for hostname and adds support for using an IPv4 address as hostname on Splunk HEC component.

CAMEL-17269: camel-splunk-hec IPv4 hostname

---

test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/ContainerLocalKafkaService.java
test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/KafkaServiceFactory.java

camel-test-infra-kafka: added support for CP 7 which should bring Kafka 3

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerAsyncManualCommitIT.java

CAMEL-17285: manual commit factories should be registered

---

components/camel-kafka/pom.xml

Given the longer support time for 3.14, it might be good to have those running by default.

(chores) camel-kafka: added automated forward compatibility tests with Kafka 3

---

components/camel-xchange/src/test/java/org/apache/camel/component/xchange/account/AccountProducerTest.java
components/camel-xchange/src/test/java/org/apache/camel/component/xchange/market/MarketDataProducerTest.java
components/camel-xchange/src/test/java/org/apache/camel/component/xchange/metadata/MetaDataProducerTest.java

Keep these tests disabled by default because they require external credentials. The assumeTrue is at prior to the test execution is not sufficient to guarantee it won't run or fail if credentials are missing.

(chores) camel-xchange: disable tests

---

core/camel-endpointdsl/src/test/java/org/apache/camel/builder/endpoint/AwsS3PollEnrichTest.java

Do test for no throws when possible

(chores) camel-endpointdsl: assertions cleanups

---

components/camel-dataset/src/main/java/org/apache/camel/component/dataset/DataSetEndpoint.java

(chores) camel-dataset: reduce verbosity of debug message

---

components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Producer.java

CAMEL-17158- AWS2 - Respect queue delay while sending messages to SQS

---

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc

Add documentation debugging with jbang

---

camel-dependencies/pom.xml
parent/pom.xml

Bump mybatis 3.5.8

---

components/camel-mina/src/test/java/org/apache/camel/component/mina/BaseMinaTest.java
components/camel-mina/src/test/java/org/apache/camel/component/mina/MinaSslContextParametersTcpTest.java
components/camel-mina/src/test/java/org/apache/camel/component/mina/MinaSslGlobalContextParametersTcpTest.java

Issue https://issues.apache.org/jira/browse/CAMEL-16141

CAMEL-16141 Investigate failing mina tests on JDK >= 11

---

pom.xml

to benefit from https://issues.apache.org/jira/browse/FELIX-6404

upgrade Felix maven-bundle-plugin

---

components/camel-salesforce/camel-salesforce-component/src/main/docs/salesforce-component.adoc

I won't mention who changed an adoc without checking if it broke the site.

fix untested adoc edits

---

components/camel-nsq/src/main/docs/nsq-component.adoc

Default nsq producer port is 4150 @astefanutti

Fix nsq doc

---

camel-dependencies/pom.xml
parent/pom.xml

This fixes the security issue https://nvd.nist.gov/vuln/detail/CVE-2021-45105

Update log 4js version to 2.17

---

docs/local-build.sh
docs/source-map.yml
docs/source-watch.yml

3.14.x local/partial build setup

---

docs/local-build.sh
docs/source-map.yml
docs/source-watch.yml

3.13.x local/partial build setup

---

docs/local-build.sh
docs/source-map.yml
docs/source-watch.yml

3.12.x local/partial build setup

---

docs/local-build.sh
docs/source-map.yml
docs/source-watch.yml

3.11.x local/partial build setup

---

docs/local-build.sh
docs/source-map.yml
docs/source-watch.yml

cf https://github.com/apache/camel-website/pull/727

3.7.x local/partial build setup

---

parent/pom.xml

Upgrade to log4j 2.17.0

---

parent/pom.xml

Upgrade log4j to 2.17.0

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade logback to 1.2.9 (https://jira.qos.ch/browse/LOGBACK-1591)

Upgrade logback to 1.2.9 (https://jira.qos.ch/browse/LOGBACK-1591)

---

parent/pom.xml

Upgrade to logback 1.2.9 (https://jira.qos.ch/browse/LOGBACK-1591)

Upgrade to logback 1.2.9 (https://jira.qos.ch/browse/LOGBACK-1591)

---

core/camel-core-engine/src/main/docs/modules/eips/pages/enrich-eip.adoc

Fixed incorrectly typed method parameter names.

---

docs/README_local_build.adoc
docs/local-build.sh
docs/source-watch.yml

Sets up new docs local-build for camel main. See apache/camel-website#731

update to docs local build v2

---

docs/README_local_build.adoc
docs/local-build.sh
docs/source-watch.yml

Sets up new docs local-build for camel 3.14.x. See apache/camel-website#731

Camel 3.14.x local build v2

---

docs/README_local_build.adoc
docs/local-build.sh
docs/source-watch.yml

Sets up new docs local-build for camel 3.13.x. See apache/camel-website#731

Camel 3.13.x local build v2

---

docs/README_local_build.adoc
docs/local-build.sh
docs/source-watch.yml

Sets up new docs local-build for camel 3.12.x. See apache/camel-website#731

Camel 3.12.x local build v2

---

docs/README_local_build.adoc
docs/local-build.sh
docs/source-watch.yml

Sets up new docs local-build for camel 3.11.x. See apache/camel-website#731

Camel 3.11.x local build v2

---

docs/README_local_build.adoc
docs/local-build.sh
docs/source-watch.yml

Sets up new docs local-build for camel 3.7.x. See apache/camel-website#731

Camel 3.7.x local build v2

---

docs/user-manual/modules/ROOT/pages/improving-the-documentation.adoc
docs/user-manual/modules/ROOT/pages/release-guide-website.adoc

See https://github.com/apache/camel-website/issues/731.  Update website local build instructions.

AFTER camel-website #740:instructions for new 3-target local build

---

.github/workflows/master-push-build.yml

See https://issues.apache.org/jira/browse/CAMEL-17409

CAMEL-17409: run master-push-build.yml workflow on this branch (3.7.x)

---

.github/workflows/master-push-build.yml

See https://issues.apache.org/jira/browse/CAMEL-17409

CAMEL-17409: run master-push-build.yml workflow on this branch (3.13.x)

---

.github/workflows/master-push-build.yml

See https://issues.apache.org/jira/browse/CAMEL-17409

CAMEL-17409: run master-push-build.yml workflow on this branch (3.12.x)

---

.github/workflows/master-push-build.yml

See https://issues.apache.org/jira/browse/CAMEL-17409

CAMEL-17409: Camel 3.11.x GitHub push workflow (3.11.x)

---

dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

cc @lburgazzoli @davsclaus @orpiske

Use latest camel-kamelets version 0.6.0

---

docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_15.adoc
docs/user-manual/modules/ROOT/pages/camel-jbang.adoc
jbang-catalog.json

CAMEL-17370: use a shorter name for CamelJBang as it is simpler

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/KafkaRecordProcessor.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/KafkaRecordProcessorFacade.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/ProcessingResult.java

This should simplify supporting CAMEL-10152 when we implement it

CAMEL-10152: minor refactoring to camel-kafka

---

camel-dependencies/pom.xml
parent/pom.xml

Bump mybatis 3.5.8  backport to camel-3.14.x

---

catalog/camel-csimple-maven-plugin/src/main/java/org/apache/camel/maven/GenerateMojo.java

Just a simple duplication cleanup I found while looking for something else

(chores) camel-csimple-maven-plugin: cleanup code duplication

---

components/camel-cdi/pom.xml
components/camel-jmx/pom.xml
components/camel-jpa/pom.xml
components/camel-kubernetes/pom.xml
components/camel-soap/pom.xml

CAMEL-17429: removed JDK 9 profiles (component poms)

---

tests/camel-itest/pom.xml
tests/camel-itest/src/test/java/org/apache/camel/itest/doc/DataFormatComponentConfigurationAndDocumentationTest.java
tests/camel-itest/src/test/java/org/apache/camel/itest/doc/DirectComponentConfigurationAndDocumentationTest.java
tests/camel-itest/src/test/java/org/apache/camel/itest/doc/EipDocumentationTest.java
tests/camel-itest/src/test/java/org/apache/camel/itest/doc/GroovyLanguageConfigurationAndDocumentationTest.java
tests/camel-itest/src/test/java/org/apache/camel/itest/doc/SimpleLanguageConfigurationAndDocumentationTest.java
tests/camel-itest/src/test/java/org/apache/camel/itest/doc/StringDataFormatConfigurationAndDocumentationTest.java
tooling/maven/camel-eip-documentation-enricher-maven-plugin/pom.xml

CAMEL-17429: removed JDK 9 profiles (itests / toolling)

---

pom.xml

I think Javadoc often causes problems during releases, so it might be good to double check this one.

CAMEL-17429: adjust doclint for Java 11

---

parent/pom.xml

CAMEL-17432: replace compiler source and target flags with release

---

pom.xml

CAMEL-17431: prevent Apache parent java source and target version from leaking

---

pom.xml

CAMEL-17429: removed JDK 8 profile on the base pom

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
dsl/camel-jbang/camel-jbang-main/examples/earthquake.yaml
dsl/camel-kamelet-main/pom.xml
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/KameletMain.java

cc @davsclaus 
Just a beginning attempt

DO NOT MERGE: Camel-JFR for camel-jbang attempt

---

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelJBangMain.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Create.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Project.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/generator/CamelJbangGenerator.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/generator/PomDependency.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/generator/PomProperty.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/generator/QuarkusGenerator.java
dsl/camel-jbang/camel-jbang-core/src/main/resources/generator/quarkus-pom.ftl
dsl/camel-kamelet-main/pom.xml

CAMEL-17345: camel-jbang create maven project

---

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/SalesforceEndpointConfig.java
tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/JavadocHelper.java
tooling/camel-tooling-util/src/test/java/org/apache/camel/tooling/util/JavadocHelperTest.java

CAMEL-17433 fix JavadocHelper (main)

---

tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/JavadocHelper.java
tooling/camel-tooling-util/src/test/java/org/apache/camel/tooling/util/JavadocHelperTest.java

CAMEL-17433 fix JavadocHelper (3.14.x)

---

tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/JavadocHelper.java
tooling/camel-tooling-util/src/test/java/org/apache/camel/tooling/util/JavadocHelperTest.java

CAMEL-17433 fix JavadocHelper (3.13.x)

---

tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/JavadocHelper.java
tooling/camel-tooling-util/src/test/java/org/apache/camel/tooling/util/JavadocHelperTest.java

CAMEL-17433 fix JavadocHelper (3.12.x)

---

tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/JavadocHelper.java
tooling/camel-tooling-util/src/test/java/org/apache/camel/tooling/util/JavadocHelperTest.java

CAMEL-17433 fix JavadocHelper (3.11.x)

---

tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/JavadocHelper.java
tooling/camel-tooling-util/src/test/java/org/apache/camel/tooling/util/JavadocHelperTest.java

CAMEL-17433 fix JavadocHelper (3.7.x)

---

core/camel-core-engine/src/main/docs/modules/eips/pages/enterprise-integration-patterns.adoc

See https://issues.apache.org/jira/browse/CAMEL-17434

CAMEL-17434 update attachments$ usage (main)

---

core/camel-core-engine/src/main/docs/modules/eips/pages/enterprise-integration-patterns.adoc

See https://issues.apache.org/jira/browse/CAMEL-17434

CAMEL-17434 update to attachment$ usage (3.14.x)

---

core/camel-core-engine/pom.xml
core/camel-management-api/pom.xml
core/camel-management/pom.xml
parent/pom.xml

Obs.: there's more, but I am separating in smaller PRs to make it easier to review.

CAMEL-17429: removed JDK 9 profiles

---

components/camel-hdfs/pom.xml

(chores) camel-hdfs: adjust Windows build profile name to match others in the code

---

components/camel-jetty/pom.xml

(chores) camel-jetty: fixed incorrect scope for awaitility

---

components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Component.java
components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Endpoint.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/SqsComponentClientRegistryTest.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/SqsComponentConfigurationTest.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/integration/Aws2SQSBaseTest.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/integration/SqsDeadletterWithClientRegistryLocalstackIT.java

Issue: https://issues.apache.org/jira/browse/CAMEL-17437
Partial revert of ad116075001fa6f1d2c53faa0d05f9c17bfc8d80
I started verifying other aws components, to validate potential error (CAMEL-17437) in them. I discovered that I made a mistake in the junit test (issue reproducer). Since the test was fixed, it is obvious that the issue is not happening at all. This PR reverts changes brought my previous PR (https://github.com/apache/camel/pull/6668) and keeps the fixed version of the test (integration test using deadletter). I'm sorry for wrongly reported issue.

Fixed deadletter test in sqs and revert of previous fix of CAMEL-17437

---

tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/JavadocHelper.java
tooling/camel-tooling-util/src/test/java/org/apache/camel/tooling/util/JavadocHelperTest.java

Revert "CAMEL-17433 fix JavadocHelper (3.11.x)"

---

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/SalesforceEndpointConfig.java
tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/JavadocHelper.java
tooling/camel-tooling-util/src/test/java/org/apache/camel/tooling/util/JavadocHelperTest.java

Revert "CAMEL-17433 fix JavadocHelper (main)"

---

.github/workflows/master-pr-build.yml

I am just trying something while I wait for builds to complete.

Checkstyle fail fast

---

components/camel-tagsoup/pom.xml

(chores) use a single profile name for the IBM JDK

---

NOTICE.txt

Updated Notice file

---

components/camel-dozer/pom.xml
components/camel-grpc/pom.xml
components/camel-jetty/pom.xml
components/camel-jmx/pom.xml
components/camel-jta/pom.xml
components/camel-microprofile/camel-microprofile-metrics/pom.xml
components/camel-netty-http/pom.xml
components/camel-salesforce/camel-salesforce-component/pom.xml
components/camel-soap/pom.xml
components/camel-spring-redis/pom.xml
components/camel-spring-ws/pom.xml
components/camel-spring-xml/pom.xml
core/camel-api/pom.xml
core/camel-core/pom.xml
docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_15.adoc
parent/pom.xml
tooling/openapi-rest-dsl-generator/pom.xml
tooling/swagger-rest-dsl-generator/pom.xml

This is the first part of the dependency cleanup. It moves them to the dependency management section so that they are not included by default in all modules.

CAMEL-17435: dependency cleanup

---

components/camel-spring-ws/src/test/java/org/apache/camel/component/spring/ws/filter/impl/BasicMessageFilterTest.java
parent/pom.xml

Java 17 test fixes for Spring

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/AbstractGenerateConfigurerMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PrepareCatalogMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/UpdateReadmeMojo.java

(chores) camel-package-maven-plugin: removed code duplications

---

parent/pom.xml
test-infra/camel-test-infra-infinispan/src/test/java/org/apache/camel/test/infra/infinispan/services/InfinispanLocalContainerService.java

(chores) camel-infinispan: updates to version 13.0.5-Final-1

---

components/camel-ahc-ws/src/test/java/org/apache/camel/component/ahc/ws/WsProducerConsumerTest.java

(chores) camel-ahc-ws: remove a few Thread.sleep calls

---

catalog/camel-catalog-lucene/src/main/java/org/apache/camel/catalog/lucene/LuceneSuggestionStrategy.java
components/camel-lucene/src/main/java/org/apache/camel/component/lucene/LuceneConfiguration.java
components/camel-lucene/src/main/java/org/apache/camel/component/lucene/LuceneIndexer.java
components/camel-lucene/src/main/java/org/apache/camel/processor/lucene/LuceneQueryProcessor.java
components/camel-lucene/src/test/java/org/apache/camel/processor/lucene/LuceneQueryProcessorIT.java

- removed unused exceptions
- do not use hard-coded path separators
- decreased scope of member variable
- removed unused totalHitsThreshold parameter in the query processor constructor

(chores) camel-lucene: code cleanups

---

components/camel-jclouds/src/main/docs/jclouds-component.adoc

jclouds is now an apache projects.

Update jclouds-component.adoc with correct jclouds URL as jclouds is now an Apache project.

---

components/camel-jsonpath/src/main/docs/jsonpath-language.adoc
components/camel-leveldb/src/main/docs/leveldb.adoc

Updating documentation links as some of the projects have moved from code.google.com to github.

---

components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppConsumer.java
components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppProducer.java
components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppUtils.java
components/camel-smpp/src/test/java/org/apache/camel/component/smpp/integration/SmppConsumerReconnectManualIT.java
components/camel-smpp/src/test/java/org/apache/camel/component/smpp/integration/SmppProducerReconnectManualIT.java
core/camel-support/src/main/java/org/apache/camel/support/task/BackgroundTask.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/TimeBoundedBudget.java
core/camel-support/src/test/java/org/apache/camel/support/task/BackgroundIterationTimeTaskTest.java

CAMEL-17472: do comply with unlimited duration tasks

---

components/camel-aws/camel-aws2-s3/src/main/docs/aws2-s3-component.adoc

Issue: https://issues.apache.org/jira/browse/CAMEL-17478

CAMEL-17478 camel-aws2-s3: Aws credentials are mandatory for downloadLink 

---

components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppConsumer.java
components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppProducer.java
components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppUtils.java
components/camel-smpp/src/test/java/org/apache/camel/component/smpp/integration/SmppConsumerReconnectManualIT.java
components/camel-smpp/src/test/java/org/apache/camel/component/smpp/integration/SmppProducerReconnectManualIT.java
core/camel-support/src/main/java/org/apache/camel/support/task/BackgroundTask.java
core/camel-support/src/main/java/org/apache/camel/support/task/budget/TimeBoundedBudget.java
core/camel-support/src/test/java/org/apache/camel/support/task/BackgroundIterationTimeTaskTest.java

Backport CAMEL-17472

---

.github/workflows/master-pr-build.yml
.github/workflows/master-push-build.yml

(chores) Upgrade PR and push GH actions to v2 when available

---

components/camel-opentracing/src/main/docs/opentracing.adoc
components/camel-zipkin/src/main/docs/zipkin.adoc
core/camel-core-engine/src/main/docs/modules/eips/pages/change-data-capture.adoc
core/camel-core-engine/src/main/docs/modules/eips/pages/kamelet-eip.adoc
core/camel-core-processor/src/main/java/org/apache/camel/processor/package.html
core/camel-xml-jaxp/src/main/java/org/apache/camel/converter/jaxp/package.html
docs/user-manual/modules/ROOT/pages/configuring-route-startup-ordering-and-autostartup.adoc
docs/user-manual/modules/ROOT/pages/error-handler.adoc
docs/user-manual/modules/ROOT/pages/examples.adoc
docs/user-manual/modules/ROOT/pages/exception-clause.adoc
docs/user-manual/modules/ROOT/pages/exchange-pooling.adoc
docs/user-manual/modules/ROOT/pages/release-guide.adoc
docs/user-manual/modules/ROOT/pages/route-reload.adoc
docs/user-manual/modules/ROOT/pages/route-template.adoc
docs/user-manual/modules/ROOT/pages/using-propertyplaceholder.adoc

* Fix broken links
* Fix typos
* Propose Java/XML code easier to understand regarding the context (less unrelated code)
* Fix indentation issues
* Fix Admonition marker 
* Fix links pointing to the branch master instead of main

Small documentation improvements

---

components/camel-jms/src/main/java/org/apache/camel/component/jms/EndpointMessageListener.java
components/camel-jms/src/main/java/org/apache/camel/component/jms/InOnlyMessageSentCallback.java
components/camel-jms/src/main/java/org/apache/camel/component/jms/reply/ReplyManagerSupport.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/ConsumeJmsBytesMessageTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/ConsumeJmsMapMessageTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/ConsumeJmsObjectMessageTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsInOutTransferExchangeTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsIncludeAllJMSXPropertiesTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsMessageBodySetNullTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsNotIncludeAllJMSXPropertiesTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/ActiveMQPropagateSerializableHeadersTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsToFileMessageIdTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/tx/QueueToProcessorTransactionTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/tx/QueueToQueueRequestReplyTransactionTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/tx/QueueToQueueTransactionTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/tx/QueueToQueueTransactionWithoutDefineTransactionManagerTest.java

cleanup the camel-jms codebase a bit

---

catalog/camel-report-maven-plugin/src/main/docs/camel-report-maven-plugin.adoc
docs/user-manual/modules/ROOT/pages/advice-with.adoc
docs/user-manual/modules/ROOT/pages/camel-component-maven-plugin.adoc
docs/user-manual/modules/ROOT/pages/clustering.adoc
docs/user-manual/modules/ROOT/pages/endpoint-annotations.adoc
docs/user-manual/modules/ROOT/pages/notify-builder.adoc
docs/user-manual/modules/ROOT/pages/rest-dsl.adoc
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/GenerateConfigurerMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/GenerateTestConfigurerMojo.java

* Fix wrong system property name
* Fix typos
* Fix incorrect test descriptions

Small documentation improvements (part 2)

---

components/camel-disruptor/src/main/docs/disruptor-component.adoc
components/camel-disruptor/src/main/docs/disruptor-vm-component.adoc

Suggested Grammar correction.
documentation appears to be breaking statement midway. Please review prior to merging.

Disruptor documentation update

---

components/camel-http/src/main/docs/http-component.adoc

Fixed typo in example code

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java

CAMEL-17493: ignore safe exceptions when unsubscribing

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/PartitionAssignmentListener.java

CAMEL-17509: fix invalid topic info displayed when using topic patterns

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/PartitionAssignmentListener.java

Backport the fixes for Camel Kafka. We probably want to wait for #6755
to finish building/testing before merging ...

Backport Camel Kafka fixes

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/DefaultKafkaManualCommit.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/DefaultKafkaManualSyncCommit.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaManualCommit.java

(chores) camel-kafka: remove deprecated methods

---

components/camel-olingo4/camel-olingo4-api/src/main/java/org/apache/camel/component/olingo4/api/impl/Olingo4AppImpl.java

https://issues.apache.org/jira/browse/CAMEL-17506
Note: there a no unit tests in this component, only integration tests which depends on an external service http://services.odata.org/TripPinRESTierService whose schema has no entity with a complex key

[CAMEL-17506] read query with key predicate returns one entity

---

components/camel-bean/src/main/docs/bean-language.adoc
components/camel-joor/src/main/docs/joor-language.adoc
components/camel-saxon/src/main/docs/xquery-language.adoc
components/camel-xpath/src/main/docs/xpath-language.adoc
core/camel-core-engine/src/main/docs/modules/eips/pages/intercept.adoc
core/camel-core-engine/src/main/docs/modules/eips/pages/split-eip.adoc
core/camel-core-engine/src/main/docs/modules/eips/pages/throttle-eip.adoc
core/camel-core-languages/src/main/docs/modules/languages/pages/simple-language.adoc
docs/user-manual/modules/ROOT/pages/bean-binding.adoc
docs/user-manual/modules/ROOT/pages/exchange-pooling.adoc
docs/user-manual/modules/ROOT/pages/http-session-handling.adoc
docs/user-manual/modules/ROOT/pages/lambda-route-builder.adoc
docs/user-manual/modules/ROOT/pages/languages.adoc
docs/user-manual/modules/ROOT/pages/oncompletion.adoc
docs/user-manual/modules/ROOT/pages/predicate.adoc
docs/user-manual/modules/ROOT/pages/processor.adoc
docs/user-manual/modules/ROOT/pages/route-configuration.adoc
docs/user-manual/modules/ROOT/pages/route-controller.adoc
docs/user-manual/modules/ROOT/pages/route-policy.adoc

* Fix typos
* Fix incorrect test code snippets

Small documentation improvements (part 3)

---

components/camel-spring/src/main/docs/spring-summary.adoc
core/camel-api/src/main/java/org/apache/camel/spi/TypeConverterRegistry.java
core/camel-core-engine/src/main/docs/modules/eips/pages/message-expiration.adoc
core/camel-core-engine/src/main/docs/modules/eips/pages/multicast-eip.adoc
core/camel-core-engine/src/main/docs/modules/eips/pages/split-eip.adoc
docs/user-manual/modules/ROOT/pages/route-reload.adoc
docs/user-manual/modules/ROOT/pages/route-template.adoc
docs/user-manual/modules/ROOT/pages/stream-caching.adoc
docs/user-manual/modules/ROOT/pages/threading-model.adoc
docs/user-manual/modules/ROOT/pages/type-converter.adoc

* Fix typos
* Fix incorrect test code snippets

Small documentation improvements (part 4)

---

tooling/maven/sync-properties-maven-plugin/pom.xml
tooling/maven/sync-properties-maven-plugin/src/main/java/org/apache/camel/maven/sync/properties/SyncPropertiesMojo.java

This pull request proposes  _polishing up_ the Javadoc description of the otherwise functionally correct [_SyncPropertiesMojo_](https://bit.ly/syncPropsMojo).

CAMEL-17527: Polish the grammar of SyncPropertiesMojo's documentation

---

archetypes/camel-archetype-cdi/src/main/resources/archetype-resources/pom.xml
archetypes/camel-archetype-component/src/main/resources/archetype-resources/pom.xml
archetypes/camel-archetype-dataformat/src/main/resources/archetype-resources/pom.xml
archetypes/camel-archetype-java/src/main/resources/archetype-resources/pom.xml
archetypes/camel-archetype-main/src/main/resources/archetype-resources/pom.xml
archetypes/camel-archetype-spring/src/main/resources/archetype-resources/pom.xml

(chores) Adjust archetypes so that generated projects use Java 11 at minimum

---

tooling/maven/camel-api-component-maven-plugin/src/main/java/org/apache/camel/maven/AbstractApiMethodGeneratorMojo.java

(chores) camel-api-component-maven-plugin: removed unused exceptions

---

components/camel-optaplanner/src/test/resources/org/apache/camel/component/optaplanner/daemonSolverConfig.xml
components/camel-optaplanner/src/test/resources/org/apache/camel/component/optaplanner/solverConfig.xml
parent/pom.xml

CAMEL-17379: upgrade to optaplanner 8.16.0.Final

---

components/camel-hazelcast/pom.xml
components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/set/HazelcastSetProducer.java

Fix typo in HazelcastSetProducer and disable JDK11 warning

---

core/camel-core-engine/src/main/docs/modules/eips/pages/setHeader-eip.adoc

Updating setHeader-eip.adoc to include a sample of fluent syntax.

adding an example to setHeader-eip.adoc

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/models.properties
catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/models/doSwitch.json
catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd
core/camel-core-engine/src/main/docs/modules/eips/examples/json/doSwitch.json
core/camel-core-engine/src/main/docs/modules/eips/nav.adoc
core/camel-core-engine/src/main/docs/modules/eips/pages/choice-eip.adoc
core/camel-core-engine/src/main/docs/modules/eips/pages/switch-eip.adoc
core/camel-core-languages/src/main/java/org/apache/camel/language/simple/SimpleLanguage.java
core/camel-core-model/src/generated/resources/META-INF/services/org/apache/camel/model.properties
core/camel-core-model/src/generated/resources/org/apache/camel/model/doSwitch.json
core/camel-core-model/src/generated/resources/org/apache/camel/model/jaxb.index
core/camel-core-model/src/main/java/org/apache/camel/model/ProcessorDefinition.java
core/camel-core-model/src/main/java/org/apache/camel/model/SwitchDefinition.java
core/camel-core-reifier/src/main/java/org/apache/camel/reifier/ProcessorReifier.java
core/camel-core-reifier/src/main/java/org/apache/camel/reifier/SwitchReifier.java
core/camel-core/src/test/java/org/apache/camel/builder/RouteTemplateSwitchTest.java
core/camel-core/src/test/java/org/apache/camel/model/ChoiceDefinitionTest.java
core/camel-core/src/test/java/org/apache/camel/processor/DoSwitchTest.java
core/camel-xml-io/src/generated/java/org/apache/camel/xml/in/ModelParser.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/ModelDeserializers.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/ModelDeserializersResolver.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/camel-yaml-dsl.json
dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/camelYamlDsl.json
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/SwitchTest.groovy

Switch eip

---

components/camel-debezium/camel-debezium-mongodb/src/main/docs/debezium-mongodb-component.adoc
components/camel-debezium/camel-debezium-mongodb/src/test/java/org/apache/camel/component/debezium/DebeziumMongodbComponentTest.java
components/camel-debezium/camel-debezium-mysql/src/main/docs/debezium-mysql-component.adoc
components/camel-debezium/camel-debezium-mysql/src/test/java/org/apache/camel/component/debezium/DebeziumMySqlComponentTest.java
components/camel-debezium/camel-debezium-postgres/src/main/docs/debezium-postgres-component.adoc
components/camel-debezium/camel-debezium-postgres/src/test/java/org/apache/camel/component/debezium/DebeziumPostgresComponentTest.java
components/camel-debezium/camel-debezium-sqlserver/src/main/docs/debezium-sqlserver-component.adoc
components/camel-debezium/camel-debezium-sqlserver/src/test/java/org/apache/camel/component/debezium/DebeziumSqlserverComponentTest.java

Updating documentation and test cases to use databaseHistoryFileFilename.

correcting documentation and test cases

---

parent/pom.xml

CAMEL-17284: upgrade Kafka clients to 3.1.0

---

core/camel-core-engine/src/main/docs/modules/eips/pages/message.adoc

Grammar Of Docs Updated

---

core/camel-core-engine/src/main/docs/modules/eips/pages/resequence-eip.adoc

typo fixed

---

components/camel-huawei/camel-huaweicloud-obs/src/main/java/org/apache/camel/component/huaweicloud/obs/OBSConsumer.java

Minor cleanup ... mostly to test something on my end.

(chores) camel-huawei: use log markers

---

components/camel-jms/src/main/java/org/apache/camel/component/jms/JmsMessage.java
components/camel-sjms/src/main/java/org/apache/camel/component/sjms/SjmsMessage.java
components/camel-spring-integration/src/main/java/org/apache/camel/component/spring/integration/SpringIntegrationMessage.java
core/camel-core/src/test/java/org/apache/camel/processor/transformer/TransformerRouteTest.java
core/camel-support/src/main/java/org/apache/camel/support/AbstractExchange.java
core/camel-support/src/main/java/org/apache/camel/support/MessageHelper.java
core/camel-support/src/main/java/org/apache/camel/support/MessageSupport.java
core/camel-support/src/test/java/org/apache/camel/support/AbstractExchangeTest.java
core/camel-support/src/test/java/org/apache/camel/support/MessageHelperTest.java

Backport of https://github.com/apache/camel/pull/6866 for 3.14

CAMEL-17579: Preserve the data type of a message on copy

---

core/camel-support/src/test/java/org/apache/camel/support/AbstractExchangeTest.java

Backport of #6866 for 3.14 (part 3)

CAMEL-17579: Fix checkstyle violation

---

components/camel-spring-xml/src/test/resources/org/apache/camel/spring/impl/transformer/SpringTransformerRouteTest.xml

Fix test related to https://github.com/apache/camel/pull/6866

CAMEL-17579: Add the missing config needed for SpringTransformerRouteTest

---

components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteAggregationRepositoryIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteAggregationRepositoryOperationsIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteConfigurationIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteConsumerIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteCustomListenerIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteIdempotentRepositoryIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteProducerIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteQueryConsumerIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteQueryProducerIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteQueryTestSupport.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteTestSupport.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/cluster/AbstractInfinispanRemoteClusteredIT.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/cluster/InfinispanRemoteClusteredTestSupport.java
components/camel-infinispan/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/remote/cluster/InfinispanRemoteClusteredViewIT.java
components/camel-infinispan/camel-infinispan/src/test/resources/infinispan/client-mac.properties

[CAMEL-17589]Enable ITests of camel-infinispan on MacOSX

---

components/camel-controlbus/src/main/docs/controlbus-component.adoc

fix typo in Control Bus docs

---

components/camel-hdfs/src/test/java/org/apache/camel/component/hdfs/integration/HdfsAppendIT.java
components/camel-hdfs/src/test/resources/hdfs-mac-test.xml

[CAMEL-16387]camel-hdfs: AppendTest fails on Mac

---

camel-dependencies/pom.xml
parent/pom.xml

Just trying to fix one of the dependabot warnings.

Update mina to 2.1.5 due to CVE-2021-41973

---

components/camel-zookeeper-master/src/test/java/org/apache/camel/component/zookeepermaster/MasterEndpointTest.java
components/camel-zookeeper-master/src/test/java/org/apache/camel/component/zookeepermaster/MasterQuartzEndpointTest.java
components/camel-zookeeper-master/src/test/java/org/apache/camel/component/zookeepermaster/group/GroupTest.java
components/camel-zookeeper-master/src/test/java/org/apache/camel/component/zookeepermaster/group/ZookeeprContainer.java

[CAMEL-17597]Enable camel-zookeeper-master : GroupTest on mac

---

.github/workflows/codeql-analysis.yml

(chores) experimental ci: remove redundant workflow in CodeQL analysis

---

.github/workflows/codeql-analysis.yml

(chores) experimental ci: fix cache usage and apply minor cleanups

---

docs/user-manual/modules/ROOT/nav.adoc
docs/user-manual/modules/ROOT/pages/test-infra.adoc

Fixed navigation and link issues in test-infra documentation

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/AbstractGenerateConfigurerMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointUriFactoryGenerator.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/GenerateEndpointUriFactoryMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PackageComponentMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PrepareAssemblyMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PrepareCatalogMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PropertyConfigurerGenerator.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/SchemaGeneratorMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/UpdateReadmeMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/generics/GenericsUtil.java

(chores) camel-package-maven-plugin cleanups

---

docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_16.adoc

CAMEL-17625: improve migration documentation

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointDslMojo.java

camel-maven-package-plugin: second round of cleanups

---

init/camel-bundle-plugin/src/main/java/org/apache/felix/bundleplugin/ManifestPlugin.java

(chores) camel-bundle-plugin: a few minor cleanups

---

components/camel-cxf/src/test/java/org/apache/camel/component/cxf/AbstractCXFGreeterRouterTest.java
components/camel-ref/src/main/java/org/apache/camel/component/ref/RefEndpoint.java

[CAMEL-17618]follow up fix and re-enable failure test

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/SchemaGeneratorMojo.java

(chores) camel-package-maven-plugin: remove duplicated code

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojo.java

(chores) camel-package-maven-plugin: removed bogus debug message

---

tooling/maven/camel-javadoc-plugin/src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
tooling/maven/camel-maven-plugin/src/main/java/org/apache/camel/maven/PrepareFatJarMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/AbstractGenerateConfigurerMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/ComponentDslMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointDslMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/GenerateEndpointUriFactoryMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PrepareAssemblyMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PrepareCamelMainDocMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PrepareExampleMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PrepareParentPomMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/UpdateReadmeMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/ValidateComponentMojo.java
tooling/maven/sync-properties-maven-plugin/src/main/java/org/apache/camel/maven/sync/properties/SyncPropertiesMojo.java

Along with the other cleanups, it seems to bring some improvements to the plugin execution. 
Execution time before all the cleanups:
```
camel-bundle-plugin:manifest (bundle-manifest) ........... [176.321s]
camel-package-maven-plugin:generate (generate) ........... [118.200s]
```
With the other cleanups + this one:
```
camel-bundle-plugin:manifest (bundle-manifest) ........... [140.743s]
camel-package-maven-plugin:generate (generate) ........... [88.600s]
```

chores: use guarded logs for debug messages in plugins

---

Jenkinsfile

(chores) ci: use suggestion from SonarCloud to improve analysis time

---

tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/PackageHelper.java
tooling/camel-util-json/src/main/java/org/apache/camel/util/json/Jsoner.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/ComponentDslMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointDslMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PrepareExampleMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/generics/PackagePluginUtils.java

Also replace one slow method (sampled below as `testReadCustom`) with a faster one (`testJavaNativeWithAppend`). 
Doesn't really help in the grand scheme of things, but the new code is cleaner. 
```
MyBenchmark.testReadCustom                   thrpt   15   466.568 ± 1.880  ops/ms
MyBenchmark.testJavaNativeWithAppend         thrpt   15  1306.446 ± 9.873  ops/ms
```

More camel-package-maven-plugin cleanups

---

core/camel-core/src/test/java/org/apache/camel/support/RouteWatcherReloadStrategyTest.java

Just a bit more testing to be sure... Thanks @davsclaus for moving and simplifying the test!

[CAMEL-17651] enhance test

---

components/camel-huawei/camel-huaweicloud-frs/src/main/docs/hwcloud-frs-component.adoc
components/camel-huawei/camel-huaweicloud-frs/src/main/java/org/apache/camel/component/huaweicloud/frs/FaceRecognitionEndpoint.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/FaceRecognitionInvalidParamsTest.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/mock/FaceDetectionWithImageBae64AndMockClientTest.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/mock/FaceDetectionWithImageFileAndMockClientTest.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/mock/FaceDetectionWithImageUrlAndMockClientTest.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/mock/FaceVerificationWithImageBae64AndMockClientTest.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/mock/FaceVerificationWithImageFileAndMockClientTest.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/mock/FaceVerificationWithImageUrlAndMockClientTest.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/mock/FrsClientMock.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/mock/LiveDetectionWithVideoBae64AndMockClientTest.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/mock/LiveDetectionWithVideoFileAndMockClientTest.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/mock/LiveDetectionWithVideoUrlAndMockClientTest.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/mock/MockResult.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/real/FaceDetectionWithImageBae64Test.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/real/FaceDetectionWithImageFileTest.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/real/FaceDetectionWithImageUrlTest.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/real/FaceVerificationWithImageBae64Test.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/real/FaceVerificationWithImageFileTest.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/real/FaceVerificationWithImageUrlTest.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/real/LiveDetectionWithVideoBae64Test.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/real/LiveDetectionWithVideoFileTest.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/real/LiveDetectionWithVideoUrlTest.java

Modify document of HuaweiCloud Face Recognition Service (FRS) Component and add some test cases

CAMEL-17683: Modify document of HuaweiCloud Face Recognition Service (FRS) Component and add some test cases

---

.github/workflows/pmd-analysis.yml

Add PMD scanning for PR code

---

components/camel-micrometer/src/main/docs/micrometer-component.adoc

CAMEL-17680: fixed invalid references to the camel-metrics component URI

---

components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/MicrometerEndpoint.java

CAMEL-17679: remove references to unsupported metrics types

---

components/camel-micrometer/src/main/docs/micrometer-component.adoc
components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/MicrometerEndpoint.java

Backport micrometer fixes

---

bom/camel-bom/pom.xml
catalog/camel-allcomponents/pom.xml
components/camel-xmpp/pom.xml
parent/pom.xml

CAMEL-17621 + CAMEL-17692: camel-testcontainers leftovers

---

tooling/maven/camel-javadoc-plugin/src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
tooling/maven/camel-restdsl-openapi-plugin/src/main/java/org/apache/camel/maven/generator/openapi/AbstractGenerateMojo.java

Minor maven plugin cleanups

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/AbstractGenerateMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/SchemaHelper.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/dsl/component/ComponentsDslMetadataRegistry.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/generics/OwbParametrizedTypeImpl.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/generics/OwbTypeVariableImpl.java

- use a cleaner equality check
- camel-package-maven-plugin: simplify

(chores) camel-package-maven-plugin: minor cleanups

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/AbstractGenerateMojo.java

(chores) camel-package-maven-plugin: removed an unused private method

---

components/camel-opentelemetry/src/main/docs/opentelemetry.adoc

Added required step for Spring Boot and how to use OpenTelemetry agent

Improve documentation for OpenTelemetry component

---

core/camel-core-engine/src/main/docs/modules/eips/pages/resume-strategies.adoc
core/camel-core-processor/src/main/java/org/apache/camel/processor/resume/ResumableCompletion.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/resume/ResumableProcessor.java
core/camel-core/src/test/java/org/apache/camel/component/file/FileConsumerResumeFromOffsetStrategyTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/FileConsumerResumeStrategyTest.java

This makes it possible to define the resume strategy at the beginning of
the route.

CAMEL-15562: adjust the resumable processing to run at the end of the route

---

components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/Kinesis2Consumer.java

CAMEL-17186: convert AWS Kinesis to Resume API v2

---

core/camel-core-engine/src/main/docs/modules/eips/pages/resume-strategies.adoc

CAMEL-17117: added details about supported components for the resume API

---

core/camel-core-processor/src/main/java/org/apache/camel/processor/resume/DelegatingResumeStrategy.java

CAMEL-17733: added a builtin delegating resume strategy

---

components/camel-bean-validator/src/main/java/org/apache/camel/component/bean/validator/ValidatorFactories.java
components/camel-bean/src/main/java/org/apache/camel/component/bean/BeanInfo.java
components/camel-bean/src/main/java/org/apache/camel/component/bean/ConstantTypeBeanHolder.java
components/camel-cron/src/main/java/org/apache/camel/component/cron/CronHelper.java
components/camel-jcache/src/main/java/org/apache/camel/component/jcache/JCacheHelper.java
components/camel-knative/camel-knative-component/src/main/java/org/apache/camel/component/knative/KnativeComponent.java
components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpServer.java
components/camel-reactive-streams/src/main/java/org/apache/camel/component/reactive/streams/ReactiveStreamsHelper.java
components/camel-saga/src/main/java/org/apache/camel/component/saga/SagaProducer.java
core/camel-support/src/main/java/org/apache/camel/support/CamelContextHelper.java

CAMEL-15520: fixed deprecated usages of CamelContextHelper.findByType

---

components/camel-fhir/camel-fhir-api/src/main/java/org/apache/camel/component/fhir/api/FhirHistory.java
components/camel-file/src/main/java/org/apache/camel/component/file/GenericFile.java
components/camel-language/src/main/java/org/apache/camel/component/language/LanguageProducer.java

CAMEL-15520: fixed deprecated usages of Exchange.getOut/getIn

---

camel-dependencies/pom.xml
components/camel-jcache/pom.xml
parent/pom.xml

Upgrade Hazelcast to 5.1

---

components/camel-kafka/pom.xml
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumerHealthCheck.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerHealthCheckIT.java
core/camel-health/src/main/java/org/apache/camel/impl/health/AbstractHealthCheck.java

CAMEL-17727: camel-kafka - Add readiness health check for kafka consumer

---

dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/src/main/java/org/apache/camel/maven/dsl/yaml/GenerateYamlSupportMojo.java

Fix for https://issues.apache.org/jira/browse/CAMEL-17741
A field annotated with `@XmlElement` without the attribute `name` should have as XML name its name according to the JAXB specification which is not currently the case.
* Rewrite the method `fieldName` to make sure that the attribute name of the annotation `@XmlRootElement` is only retrieved in case if a field is annotated with `@XmlElementRef` (or `@DslProperty`) as stated by the spec
* Remove the annotation `@XmlValue` from the method `fieldName` as it doesn't hold any name
* Remove the method `annotationValue` for a `MethodInfo` as it was not used

CAMEL-17741: Improper way to get the default name of a field annotated with XmlElement

---

components/camel-quartz/src/test/java/org/apache/camel/component/quartz/SpringQuartzPersistentStoreRestartAppChangeOptionsTest.java
components/camel-quartz/src/test/resources/org/apache/camel/component/quartz/SpringQuartzPersistentStoreRestartAppChangeCronExpressionTest1.xml
components/camel-quartz/src/test/resources/org/apache/camel/component/quartz/SpringQuartzPersistentStoreRestartAppChangeCronExpressionTest2.xml
components/camel-quartz/src/test/resources/org/apache/camel/component/quartz/SpringQuartzPersistentStoreRestartAppChangeCronExpressionTest3.xml
components/camel-quartz/src/test/resources/org/apache/camel/component/quartz/SpringQuartzPersistentStoreRestartAppChangeOptionsTest1.xml
components/camel-quartz/src/test/resources/org/apache/camel/component/quartz/SpringQuartzPersistentStoreRestartAppChangeOptionsTest2.xml

Issue https://issues.apache.org/jira/browse/CAMEL-17742

CAMEL-17742 Camel-quartz: fix and enable disabled test

---

components/camel-arangodb/src/main/java/org/apache/camel/component/arangodb/ArangoDbProducer.java
components/camel-azure/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/operations/BlobContainerOperationsTest.java
components/camel-azure/camel-azure-storage-datalake/src/test/java/org/apache/camel/component/azure/storage/datalake/operations/DataLakeFileSystemOperationTest.java
components/camel-azure/camel-azure-storage-queue/src/test/java/org/apache/camel/component/azure/storage/queue/operations/QueueOperationsTest.java
components/camel-azure/camel-azure-storage-queue/src/test/java/org/apache/camel/component/azure/storage/queue/operations/integration/QueueOperationsIT.java
components/camel-cometd/src/main/java/org/apache/camel/component/cometd/CometdConsumer.java
components/camel-schematron/src/test/java/org/apache/camel/component/schematron/SchematronEndpointTest.java
components/camel-schematron/src/test/java/org/apache/camel/component/schematron/processor/SchematronProcessorTest.java
components/camel-wordpress/src/test/java/org/apache/camel/component/wordpress/api/service/impl/ignored/WordpressServiceCategoriesAdapterIT.java
components/camel-wordpress/src/test/java/org/apache/camel/component/wordpress/api/service/impl/ignored/WordpressServiceCommentsAdapterIT.java
components/camel-wordpress/src/test/java/org/apache/camel/component/wordpress/api/service/impl/ignored/WordpressServiceTagsAdapterIT.java
components/camel-xmpp/src/main/java/org/apache/camel/component/xmpp/XmppEndpoint.java
core/camel-core-model/src/main/java/org/apache/camel/builder/BuilderSupport.java
dsl/camel-java-joor-dsl/src/test/java/org/apache/camel/dsl/java/joor/JavaRoutesBuilderLoaderTest.java
dsl/camel-xml-io-dsl/src/test/java/org/apache/camel/dsl/xml/io/XmlRoutesBuilderLoaderTest.java
dsl/camel-xml-jaxb-dsl/src/test/java/org/apache/camel/dsl/xml/jaxb/JaxbXmlRoutesBuilderLoaderTest.java

CAMEL-15520: fixed deprecated warnings

---

components/camel-gora/src/main/java/org/apache/camel/component/gora/GoraProducer.java
components/camel-gora/src/test/java/org/apache/camel/component/gora/GoraProducerTest.java

CAMEL-15520: cleanup deprecation warnings in camel-gora

---

components/camel-ahc/src/main/java/org/apache/camel/component/ahc/DefaultAhcBinding.java

CAMEL-15520: cleanup deprecation warnings in camel-ahc

---

components/camel-arangodb/src/test/java/org/apache/camel/component/arangodb/integration/BaseArangoDb.java
components/camel-azure/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/operations/BlobOperationsTest.java
components/camel-http-common/src/main/java/org/apache/camel/http/common/HttpCommonEndpoint.java
components/camel-jetty-common/src/main/java/org/apache/camel/component/jetty/JettyHttpComponent.java
components/camel-lra/src/main/java/org/apache/camel/service/lra/LRASagaRoutes.java
components/camel-schematron/src/test/java/org/apache/camel/component/schematron/SchematronComponentTest.java
components/camel-servlet/src/main/java/org/apache/camel/component/servlet/ServletComponent.java
components/camel-spring-ws/src/main/java/org/apache/camel/component/spring/ws/bean/CamelEndpointDispatcher.java
components/camel-test/camel-test-spring/src/test/java/org/apache/camel/test/spring/CamelSpringOverridePropertiesForPropertyInjectTest.java
components/camel-wordpress/src/test/java/org/apache/camel/component/wordpress/api/service/impl/ignored/WordpressServiceTaxonomyAdapterIT.java

CAMEL-15520: fixed several deprecation warnings

---

test-infra/camel-test-infra-cassandra/src/test/java/org/apache/camel/test/infra/cassandra/services/CassandraLocalContainerService.java

CAMEL-17761: do respect user-provided Cassandra containers

---

components/camel-arangodb/src/main/java/org/apache/camel/component/arangodb/ArangoDbProducer.java
components/camel-azure/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/operations/BlobOperationsTest.java
components/camel-azure/camel-azure-storage-queue/src/main/java/org/apache/camel/component/azure/storage/queue/QueueConsumer.java
components/camel-cxf-transport/src/main/java/org/apache/camel/component/cxf/common/message/CxfMessageHelper.java
components/camel-gson/src/main/java/org/apache/camel/component/gson/GsonDataFormat.java
components/camel-jackson/src/main/java/org/apache/camel/component/jackson/AbstractJacksonDataFormat.java
components/camel-jaxb/src/main/java/org/apache/camel/converter/jaxb/JaxbDataFormat.java
components/camel-jaxb/src/test/java/org/apache/camel/jaxb/MyNotificationService.java
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/NettyHttpConverter.java
components/camel-sjms/src/main/java/org/apache/camel/component/sjms/consumer/EndpointMessageListener.java
core/camel-support/src/main/java/org/apache/camel/support/AbstractExchange.java
tooling/camel-util-json/src/main/java/org/apache/camel/util/json/Yylex.java

CAMEL-15520: more deprecation cleanup fixes

---

components/camel-metrics/src/test/java/org/apache/camel/component/metrics/AbstractMetricsProducerTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/CounterEndpointTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/CounterProducerTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/CounterRouteTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/GaugeEndpointTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/GaugeProducerTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/HistogramEndpointTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/HistogramProducerTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/HistogramRouteTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/MeterEndpointTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/MeterProducerTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/MeterRouteTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/MetricComponentSpringTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/MetricsComponentRouteTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/MetricsComponentTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/MetricsEndpointTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/MetricsTypeTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/TimerEndpointTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/TimerProducerTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/TimerRouteTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/messagehistory/ExceptionRouteMetricsMessageHistoryTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/messagehistory/ManagedMessageHistoryTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/messagehistory/MetricsMessageHistoryTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/routepolicy/ManagedMetricsRoutePolicyTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/routepolicy/MetricsRoutePolicyMulticastSubRouteTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/routepolicy/MetricsRoutePolicySubRouteTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/routepolicy/MetricsRoutePolicyTest.java
components/camel-metrics/src/test/java/org/apache/camel/component/metrics/spi/InstrumentedThreadPoolFactoryTest.java

CAMEL-17763: cleaned up unused exceptions in camel-metrics

---

components/camel-quartz/src/main/java/org/apache/camel/component/quartz/QuartzEndpoint.java
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzSimpleRouteTest.java

Issue: https://issues.apache.org/jira/browse/CAMEL-17764

CAMEL-17764 changed types of job detail to Strings

---

test-infra/camel-test-infra-cassandra/src/test/java/org/apache/camel/test/infra/cassandra/services/CassandraLocalContainerService.java

CAMEL-17761: do respect user-provided Cassandra containers (backport)

---

components/camel-azure/camel-azure-cosmosdb/src/test/java/org/apache/camel/component/azure/cosmosdb/integration/CosmosDbConsumerIT.java
components/camel-azure/camel-azure-cosmosdb/src/test/java/org/apache/camel/component/azure/cosmosdb/integration/CosmosDbProducerIT.java
components/camel-azure/camel-azure-cosmosdb/src/test/java/org/apache/camel/component/azure/cosmosdb/integration/operations/CosmosDbContainerOperationsIT.java
components/camel-azure/camel-azure-eventhubs/src/test/java/org/apache/camel/component/azure/eventhubs/EventHubsComponentTest.java
components/camel-azure/camel-azure-eventhubs/src/test/java/org/apache/camel/component/azure/eventhubs/integration/EventHubsConsumerIT.java
components/camel-azure/camel-azure-eventhubs/src/test/java/org/apache/camel/component/azure/eventhubs/integration/EventHubsProducerIT.java
components/camel-azure/camel-azure-servicebus/src/test/java/org/apache/camel/component/azure/servicebus/ServiceBusEndpointTest.java
components/camel-azure/camel-azure-servicebus/src/test/java/org/apache/camel/component/azure/servicebus/integration/ServiceBusConsumerTest.java
components/camel-azure/camel-azure-servicebus/src/test/java/org/apache/camel/component/azure/servicebus/integration/ServiceBusProducerTest.java
components/camel-azure/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/BlobComponentTest.java
components/camel-azure/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BlobChangeFeedOperationsIT.java
components/camel-azure/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BlobCopyProducerIt.java
components/camel-azure/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BlobProducerIT.java
components/camel-azure/camel-azure-storage-datalake/src/test/java/org/apache/camel/component/azure/storage/datalake/integration/DataLakeProducerIT.java
components/camel-azure/camel-azure-storage-queue/src/test/java/org/apache/camel/component/azure/storage/queue/QueueComponentTest.java
components/camel-azure/camel-azure-storage-queue/src/test/java/org/apache/camel/component/azure/storage/queue/QueueTestUtils.java
components/camel-azure/camel-azure-storage-queue/src/test/java/org/apache/camel/component/azure/storage/queue/integration/StorageQueueConsumerIT.java
components/camel-azure/camel-azure-storage-queue/src/test/java/org/apache/camel/component/azure/storage/queue/integration/StorageQueueProducerIT.java

CAMEL-17763: cleanup unused exceptions in test code (Azure components)

---

core/camel-core/src/test/java/org/apache/camel/component/bean/BeanCreateBodyExceptionTest.java

(chores) tests: improve assertion test

---

components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/NettyHttpConverter.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/Netty2978IssueTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyBacklogTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyConcurrentTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyConsumerClientModeReconnectTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyConsumerClientModeReuseChannelTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyConsumerClientModeTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyCustomPipelineFactoryAsynchTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyCustomPipelineFactorySynchTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyDisconnectTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyGlobalSSLContextParametersTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyInOutCloseChannelWhenCompleteTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyOptionTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettySSLClasspathTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettySSLConsumerClientModeTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettySSLContextParametersTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettySSLPassphaseBeanTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettySSLTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyTCPSyncNotLazyChannelTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyTCPSyncTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyTcpWithInOutUsingPlainSocketTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyUDPSyncTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyUdpWithInOutUsingPlainSocketTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/ObjectSerializationTest.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/UnsharableCodecsConflicts2Test.java
components/camel-netty/src/test/java/org/apache/camel/component/netty/UnsharableCodecsConflictsTest.java

CAMEL-15520: fix a few deprecations in netty components

---

components/camel-cxf-transport/src/test/java/org/apache/camel/component/cxf/transport/CamelConduitTest.java
components/camel-cxf-transport/src/test/java/org/apache/camel/component/cxf/transport/JaxWSCamelConduitTest.java
components/camel-cxf-transport/src/test/java/org/apache/camel/component/cxf/transport/JaxWSCamelDestinationTest.java

CAMEL-15520: fixed deprecations in camel-cxf-transport

---

components/camel-azure/camel-azure-storage-datalake/src/test/java/org/apache/camel/component/azure/storage/datalake/operations/DataLakeDirectoryOperationTest.java
components/camel-azure/camel-azure-storage-queue/src/test/java/org/apache/camel/component/azure/storage/queue/operations/QueueOperationsTest.java
components/camel-sql/src/test/java/org/apache/camel/component/sql/SqlProducerUseMessageBodyForSqlTest.java

CAMEL-15520: last round of deprecation fixes (leftovers)

---

components/camel-grpc/src/test/java/org/apache/camel/component/grpc/GrpcConsumerSecurityTest.java
components/camel-grpc/src/test/java/org/apache/camel/component/grpc/GrpcProducerSecurityTest.java

(chores) fix camel-grpc test failures on CI

---

components/camel-aws/camel-aws2-athena/src/main/java/org/apache/camel/component/aws2/athena/Athena2Producer.java
components/camel-aws/camel-aws2-ec2/src/main/java/org/apache/camel/component/aws2/ec2/AWS2EC2Producer.java
components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Consumer.java
components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/DataLakeConfigurationOptionsProxy.java
components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/operations/DataLakeFileSystemOperations.java

(chores) logging cleanups

---

components/camel-barcode/src/main/java/org/apache/camel/dataformat/barcode/BarcodeDataFormat.java
components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxFoldersManager.java
components/camel-cm-sms/src/main/java/org/apache/camel/component/cm/CMProducer.java
components/camel-cometd/src/main/java/org/apache/camel/component/cometd/CometdBinding.java
components/camel-drill/src/main/java/org/apache/camel/component/drill/DrillProducer.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpOperations.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/RemoteFileConsumer.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/SftpOperations.java
components/camel-influxdb/src/main/java/org/apache/camel/component/influxdb/InfluxDbProducer.java
components/camel-jasypt/src/main/java/org/apache/camel/component/jasypt/JasyptPropertiesParser.java
components/camel-jsch/src/main/java/org/apache/camel/component/scp/ScpOperations.java
components/camel-zookeeper/src/main/java/org/apache/camel/component/zookeeper/ZooKeeperProducer.java
components/camel-zookeeper/src/main/java/org/apache/camel/component/zookeeper/cloud/ZooKeeperServiceRegistry.java
components/camel-zookeeper/src/main/java/org/apache/camel/component/zookeeper/cluster/ZooKeeperClusterService.java

(chores) logging cleanups (other components)

---

components/camel-slack/src/main/docs/slack-component.adoc

Camel-Slack: Improved information about consumer and permissions

---

components/camel-paho-mqtt5/src/test/java/org/apache/camel/component/paho/mqtt5/PahoMqtt5ComponentMqtt5Test.java
components/camel-paho-mqtt5/src/test/java/org/apache/camel/component/paho/mqtt5/PahoMqtt5ComponentVerifierExtensionTest.java
components/camel-paho-mqtt5/src/test/java/org/apache/camel/component/paho/mqtt5/PahoMqtt5OverrideTopicMqtt5Test.java
components/camel-paho-mqtt5/src/test/java/org/apache/camel/component/paho/mqtt5/PahoMqtt5ReconnectAfterFailureTest.java
components/camel-paho-mqtt5/src/test/java/org/apache/camel/component/paho/mqtt5/PahoMqtt5ToDSendDynamicTest.java
components/camel-paho-mqtt5/src/test/java/org/apache/camel/component/paho/mqtt5/PahoMqtt5ToDTest.java
components/camel-paho/src/test/java/org/apache/camel/component/paho/PahoComponentTest.java
components/camel-paho/src/test/java/org/apache/camel/component/paho/PahoComponentVerifierExtensionTest.java
components/camel-paho/src/test/java/org/apache/camel/component/paho/PahoOverrideTopicTest.java
components/camel-paho/src/test/java/org/apache/camel/component/paho/PahoReconnectAfterFailureTest.java
components/camel-paho/src/test/java/org/apache/camel/component/paho/PahoToDSendDynamicTest.java
components/camel-paho/src/test/java/org/apache/camel/component/paho/PahoToDTest.java

CAMEL-17763: cleaned up unused exceptions (Paho components)

---

components/camel-tarfile/src/main/docs/tarFile-dataformat.adoc
components/camel-zipfile/src/main/docs/zipFile-dataformat.adoc

Fix typo in camel-tarfile and camel-zipfile docs

---

components/camel-atmos/src/test/java/org/apache/camel/component/atmos/integration/producer/AtmosProducerGetFolderTest.java

(chores) camel-atmos: replace sysout with logger

---

components/camel-atmos/src/test/java/org/apache/camel/component/atmos/AtmosConsumerTest.java
components/camel-atmos/src/test/java/org/apache/camel/component/atmos/integration/consumer/AtmosConsumerGetSingleTest.java
components/camel-atmos/src/test/java/org/apache/camel/component/atmos/integration/producer/AtmosProducerDelTest.java
components/camel-atmos/src/test/java/org/apache/camel/component/atmos/integration/producer/AtmosProducerGetFolderTest.java
components/camel-atmos/src/test/java/org/apache/camel/component/atmos/integration/producer/AtmosProducerGetSingleTest.java
components/camel-atmos/src/test/java/org/apache/camel/component/atmos/integration/producer/AtmosProducerMoveTest.java
components/camel-atmos/src/test/java/org/apache/camel/component/atmos/integration/producer/AtmosProducerPutFolderWithRemotePathTest.java
components/camel-atmos/src/test/java/org/apache/camel/component/atmos/integration/producer/AtmosProducerPutSingleFileTest.java
components/camel-atmos/src/test/java/org/apache/camel/component/atmos/integration/producer/AtmosProducerPutSingleFileWithRemotePathTest.java

CAMEL-17763: cleaned up unused exceptions in camel-atmos

---

components/camel-atmosphere-websocket/src/test/java/org/apache/camel/component/atmosphere/websocket/TestClient.java
components/camel-atom/src/test/java/org/apache/camel/component/atom/JettyTestServer.java
components/camel-attachments/src/test/java/org/apache/camel/attachment/BeanMethodWithExchangeTest.java
components/camel-attachments/src/test/java/org/apache/camel/attachment/WireTapTest.java
components/camel-avro-rpc/camel-avro-rpc-component/src/test/java/org/apache/camel/avro/impl/KeyValueProtocolImpl.java
components/camel-avro-rpc/camel-avro-rpc-component/src/test/java/org/apache/camel/component/avro/processors/ReflectionInOnlyProcessor.java
components/camel-avro-rpc/camel-avro-rpc-component/src/test/java/org/apache/camel/component/avro/processors/ReflectionInOutProcessor.java
components/camel-avro/src/test/java/org/apache/camel/dataformat/avro/AvroGenericMarshaAndUnmarshaTest.java
components/camel-avro/src/test/java/org/apache/camel/dataformat/avro/AvroMarshalAndUnmarshallTest.java
components/camel-barcode/src/test/java/org/apache/camel/dataformat/barcode/BarcodeUnmarshalTest.java
components/camel-bean-validator/src/test/java/org/apache/camel/component/bean/validator/CustomValidationProviderResolverTest.java
components/camel-bean/src/test/java/org/apache/camel/component/bean/BeanInfoTest.java
components/camel-beanstalk/src/test/java/org/apache/camel/component/beanstalk/EndpointTest.java
components/camel-beanstalk/src/test/java/org/apache/camel/component/beanstalk/ProducerTest.java
components/camel-beanstalk/src/test/java/org/apache/camel/component/beanstalk/TestExchangeCopyProcessor.java
components/camel-beanstalk/src/test/java/org/apache/camel/component/beanstalk/integration/BuryProducerIntegrationIT.java
components/camel-beanstalk/src/test/java/org/apache/camel/component/beanstalk/integration/DeleteProducerIntegrationIT.java
components/camel-beanstalk/src/test/java/org/apache/camel/component/beanstalk/integration/PutProducerIntegrationIT.java
components/camel-beanstalk/src/test/java/org/apache/camel/component/beanstalk/integration/ReleaseProducerIntegrationIT.java
components/camel-beanstalk/src/test/java/org/apache/camel/component/beanstalk/integration/TouchProducerIntegrationIT.java

CAMEL-17763: cleaned up unused exceptions

---

components/camel-slack/src/main/docs/slack-component.adoc

Slack doc 

---

core/camel-api/src/main/java/org/apache/camel/ResumableSet.java

CAMEL-17762: void unnecessary array copies

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/PartitionAssignmentListener.java

CAMEL-17798 - Offsets resetting when another Camel node is shutdown

---

components/camel-file/src/main/java/org/apache/camel/component/file/FileConsumer.java
components/camel-file/src/main/java/org/apache/camel/component/file/consumer/FileResumeSet.java
components/camel-kafka/src/main/java/org/apache/camel/processor/resume/kafka/AbstractKafkaResumeStrategy.java
core/camel-api/src/main/java/org/apache/camel/ResumableSet.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/resume/ResumableCompletion.java

CAMEL-17762: resume API fixes and cleanups

---

core/camel-api/src/main/java/org/apache/camel/CamelContextLifecycle.java

(chores) doc: fix broken link in the JavaDoc documentation

---

components/camel-attachments/src/main/docs/attachments.adoc

Fix typo in camel-attachments

---

components/camel-mail/src/main/java/org/apache/camel/component/mail/MailConsumer.java

https://issues.apache.org/jira/browse/CAMEL-17812

CAMEL-17812: Unfetchable mails should not be counted as part of a poll

---

components/camel-kafka/src/main/java/org/apache/camel/processor/resume/kafka/AbstractKafkaResumeStrategy.java

I might need this for working w/ the master component and the resume API

CAMEL-17762: expose the Kafka's consumer/producer for more complex use cases

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerHealthCheckIT.java

CAMEL-17813: camel-kafka - update KafkaConsumerHealthCheckIT

---

components/camel-master/src/main/java/org/apache/camel/component/master/MasterConsumer.java

This adds the initial bits to include clustering support for the resume
API. 
Demo:
[![asciicast](https://asciinema.org/a/478055.svg)](https://asciinema.org/a/478055)

CAMEL-17810: add initial support for the resume API with the master component

---

catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/ValidateMojo.java

(chores) cleanups for camel-report-maven-plugin

---

components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/AbstractFhirTestSupport.java
test-infra/camel-test-infra-fhir/src/test/java/org/apache/camel/test/infra/fhir/services/FhirLocalSingletonContainerService.java
test-infra/camel-test-infra-fhir/src/test/java/org/apache/camel/test/infra/fhir/services/FhirServiceFactory.java

https://issues.apache.org/jira/browse/CAMEL-17838
Full camel-fhir build with IT tests used to run in ~ 10 min and now ~ 1min30s
Thanks !

[CAMEL-17838] create single FHIR sever when running IT

---

catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/ReportPluginCommon.java
catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/RouteCoverageMojo.java
catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/ValidateMojo.java

(chores) camel-report-maven-plugin: consolidate route/validation mojo code

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/BaseEmbeddedKafkaTestSupport.java
docs/user-manual/modules/ROOT/pages/test-infra.adoc
test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/StrimziContainer.java
test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/ZookeeperContainer.java

CAMEL-17843: improve camel-test-infra-kafka support for ARM

---

components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/integration/SqsProducerSendByteArrayLocalstackIT.java

(chores) Fixed checkstyle on camel-aws2-sqs

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConfiguration.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaComponentTest.java

Obs.: there's room for further improvements on the way we configure the
Kafka client, but this should prevent the warnings for now.

CAMEL-17615: filter unused options in the Kafka client to prevent warnings

---

components/camel-kafka/pom.xml
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/BaseEmbeddedKafkaTestSupport.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerFullIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerHealthCheckIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerManualCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerTopicIsPatternIT.java
test-infra/camel-test-infra-fhir/src/test/java/org/apache/camel/test/infra/fhir/services/FhirLocalSingletonContainerService.java
test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/ContainerLocalSingletonKafkaService.java
test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/KafkaServiceFactory.java

https://issues.apache.org/jira/browse/CAMEL-17845
Speeds up from ~14 min to ~4 min for a full build with IT
I've also fixed a couple of flaky ITs. KafkaConsumerTopicIsPatternIT is still failing for me locally when I run it with other tests (was failing before too),  requires further investigation. 
Thanks !

[CAMEL-17845] Use single Kafka server when running IT

---

test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/ContainerLocalKafkaService.java
test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/ContainerLocalSingletonKafkaService.java

(chores) camel-test-infra-kafka: use a common constant for the Kafka 3 image name

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java
components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryEagerIT.java
components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryNonEagerIT.java
components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryPersistenceIT.java

Multiple Kafka minor fixes

---

components/camel-infinispan/camel-infinispan/src/main/docs/infinispan-component.adoc

Fix typo in infinispan example

---

docs/user-manual/modules/faq/pages/how-do-i-change-the-logging.adoc

Correct link for log4j.properties

---

core/camel-core-engine/src/main/docs/antora.yml
docs/components/antora.yml
docs/source-map.yml

There are corresponding PRs in the Camel Spring Boot and Camel Karaf projects:
- https://github.com/apache/camel-spring-boot/pull/484
- https://github.com/apache/camel-karaf/pull/131

Website changes after 3.16.0 release

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerTopicIsPatternIT.java

https://issues.apache.org/jira/browse/CAMEL-17845
thanks !

[CAMEL-17845] fix KafkaConsumerTopicIsPatternIT

---

components/camel-arangodb/src/test/java/org/apache/camel/component/arangodb/integration/BaseArangoDb.java
components/camel-hbase/src/test/java/org/apache/camel/component/hbase/CamelHBaseTestSupport.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/AbstractMongoDbITSupport.java
test-infra/camel-test-infra-arangodb/src/test/java/org/apache/camel/test/infra/arangodb/services/ArangoDBServiceFactory.java
test-infra/camel-test-infra-hbase/src/test/java/org/apache/camel/test/infra/hbase/services/HBaseServiceFactory.java
test-infra/camel-test-infra-mongodb/src/test/java/org/apache/camel/test/infra/mongodb/services/MongoDBServiceFactory.java

Add singleton support for more test infra services:

---

components/camel-mail/src/main/docs/mail-component.adoc

Adding samples on how to set `cc`, `bcc` and `reply-to` headers for sending emails.

camel-email - Add more header samples in docs

---

docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_17.adoc

CAMEL-17802: added migration documentation

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/PollExceptionStrategy.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/errorhandler/BridgeErrorStrategy.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/errorhandler/DiscardErrorStrategy.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/errorhandler/KafkaErrorStrategies.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/errorhandler/ReconnectErrorStrategy.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/errorhandler/RetryErrorStrategy.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/errorhandler/SeekUtil.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/errorhandler/StopErrorStrategy.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentIT.java

CAMEL-17051: pre-work

---

components/camel-oaipmh/src/test/java/org/apache/camel/oaipmh/OAIPMHComponentConsumerHTTPSTest.java
components/camel-oaipmh/src/test/java/org/apache/camel/oaipmh/OAIPMHComponentConsumerParticularCaseTest.java
components/camel-oaipmh/src/test/java/org/apache/camel/oaipmh/OAIPMHComponentConsumerTest.java
components/camel-oaipmh/src/test/java/org/apache/camel/oaipmh/OAIPMHComponentProducerGetRecordTest.java
components/camel-oaipmh/src/test/java/org/apache/camel/oaipmh/OAIPMHComponentProducerOnlyFirstLoopTest.java
components/camel-oaipmh/src/test/java/org/apache/camel/oaipmh/OAIPMHComponentProducerOnlyFirstTest.java
components/camel-oaipmh/src/test/java/org/apache/camel/oaipmh/OAIPMHComponentProducerTest.java

CAMEL-17763: cleanup unused exceptions in camel-oaipmh

---

components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppConsumer.java
components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppProducer.java

This is a WIP and available for the user to help diagnose and fix the
issue

CAMEL-17859: increase logs in critical smpp code for diagnosing the issue root cause

---

components/camel-ahc-ws/src/test/java/org/apache/camel/component/ahc/ws/WsProducerConsumerTest.java
components/camel-ahc-ws/src/test/java/org/apache/camel/component/ahc/ws/WsProducerTest.java
components/camel-ahc-ws/src/test/java/org/apache/camel/component/ahc/ws/WsProducerTestBase.java
components/camel-ahc-ws/src/test/java/org/apache/camel/component/ahc/ws/WsProducerUsingStreamingTest.java
components/camel-ahc-ws/src/test/java/org/apache/camel/component/ahc/ws/WssProducerTest.java

CAMEL-17763: cleanup unused exceptions in camel-ahc-ws

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerAsyncManualCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/commit/KafkaConsumerAsyncCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/commit/KafkaConsumerNoopCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/commit/KafkaConsumerSyncCommitIT.java

(chores) camel-kafka: fix commit integration tests not running by default

---

components/camel-any23/src/test/java/org/apache/camel/dataformat/any23/Any23DataFormatHTTPTest.java
components/camel-bonita/src/test/java/org/apache/camel/component/bonita/api/BonitaAPITest.java
components/camel-bonita/src/test/java/org/apache/camel/component/bonita/api/BonitaAuthFilterConnectionTest.java
components/camel-bonita/src/test/java/org/apache/camel/component/bonita/api/BonitaAuthFilterTest.java
components/camel-bonita/src/test/java/org/apache/camel/component/bonita/integration/BonitaProducerManualIT.java
components/camel-braintree/src/test/java/org/apache/camel/component/braintree/AddOnGatewayIT.java
components/camel-braintree/src/test/java/org/apache/camel/component/braintree/AddressGatewayIT.java
components/camel-braintree/src/test/java/org/apache/camel/component/braintree/ClientTokenGatewayIT.java
components/camel-braintree/src/test/java/org/apache/camel/component/braintree/CreditCardVerificationGatewayIT.java
components/camel-braintree/src/test/java/org/apache/camel/component/braintree/CustomerGatewayIT.java
components/camel-braintree/src/test/java/org/apache/camel/component/braintree/DiscountGatewayIT.java
components/camel-braintree/src/test/java/org/apache/camel/component/braintree/DisputeGatewayIT.java
components/camel-braintree/src/test/java/org/apache/camel/component/braintree/DocumentUploadGatewayIT.java
components/camel-braintree/src/test/java/org/apache/camel/component/braintree/MerchantAccountGatewayIT.java
components/camel-braintree/src/test/java/org/apache/camel/component/braintree/PaymentMethodGatewayIT.java
components/camel-braintree/src/test/java/org/apache/camel/component/braintree/PaymentMethodNonceGatewayIT.java
components/camel-braintree/src/test/java/org/apache/camel/component/braintree/PlanGatewayIT.java
components/camel-braintree/src/test/java/org/apache/camel/component/braintree/ReportGatewayIT.java
components/camel-braintree/src/test/java/org/apache/camel/component/braintree/SettlementBatchSummaryGatewayIT.java
components/camel-braintree/src/test/java/org/apache/camel/component/braintree/SubscriptionGatewayIT.java
components/camel-braintree/src/test/java/org/apache/camel/component/braintree/TransactionGatewayIT.java
components/camel-braintree/src/test/java/org/apache/camel/component/braintree/WebhookNotificationGatewayIT.java
components/camel-caffeine-lrucache/src/test/java/org/apache/camel/component/caffeine/lrucache/CaffeineLRUCacheTest.java
components/camel-caffeine-lrucache/src/test/java/org/apache/camel/component/caffeine/lrucache/CaffeineLRUSoftCacheTest.java
components/camel-caffeine/src/test/java/org/apache/camel/component/caffeine/loadcache/CaffeineLoadCacheTestSupport.java
components/camel-caffeine/src/test/java/org/apache/camel/component/caffeine/processor/idempotent/CaffeineIdempotentRepositoryWithSplitTest.java

CAMEL-17763: miscelaneuous components

---

core/camel-health/src/main/java/org/apache/camel/impl/health/ContextHealthCheck.java
docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_17.adoc

Camel 17515

---

components/camel-google/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubConsumer.java

Backport of CAMEL-17901 to Camel 3.14

Fix PubSub concurrent access error on shutdown

---

bom/camel-bom/pom.xml
parent/pom.xml

CAMEL-17879: remove camel-jing leftovers

---

components/camel-stax/src/test/java/org/apache/camel/component/stax/IssueWithWrongEncodingTest.java
components/camel-stax/src/test/java/org/apache/camel/component/stax/StAXComponentRefTest.java
components/camel-stax/src/test/java/org/apache/camel/component/stax/StAXComponentTest.java
components/camel-stax/src/test/java/org/apache/camel/component/stax/StAXJAXBIteratorExpressionTest.java
components/camel-stax/src/test/java/org/apache/camel/component/stax/StAXXPathSplitChoicePerformanceTest.java

Testing the new changes on the workflow

CAMEL-17763: cleanup unused exceptions in camel-stax

---

docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_17.adoc

CAMEL-17879: added documentation about components that were removed

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConfiguration.java

Continuation of CAMEL-17615 to factor in `SASL_SSL`.

CAMEL-17615: Ensure Kafka SSL configuration is applied for SASL_SSL protocol

---

core/camel-api/src/main/java/org/apache/camel/spi/ExceptionHandler.java

(chores) Fixed a typo in the javadoc comment

---

components/camel-sql/src/main/docs/sql-component.adoc

Fix typo optimistick -> optimistic

---

components/camel-zookeeper/src/main/docs/zookeeper-component.adoc

Fix ZooKeeper link

---

components/camel-quartz/src/main/java/org/apache/camel/pollconsumer/quartz/QuartzScheduledPollConsumerScheduler.java

Fixes bug in camel-quartz component, changed unscheduleTask method in QuartzScheduledPollConsumerScheduler, to check deleteJob property and isJobStoreClustered.

CAMEL-17940: Fixes bug in camel-quartz component

---

components/camel-hazelcast/src/test/java/org/apache/camel/component/hazelcast/HazelcastSedaTransferExchangeTest.java
components/camel-mock/src/main/java/org/apache/camel/component/mock/MockEndpoint.java

Fix for https://issues.apache.org/jira/browse/CAMEL-17945
While working on [CAMEL-17921](https://issues.apache.org/jira/browse/CAMEL-17921), I noticed that the test `HazelcastSedaTransferExchangeTest` was unstable and should be fixed.
* Rewrite the test `testExchangeTransferDisabled` to use the new method `expectedNoHeaderReceived` instead of asserting for an `AssertionError`
* Cleanup the test class by renaming properly the methods annotated with `@BeforeAll` and `@AfterAll` (not related to the issue)
* Cleanup the test class by resetting the mock endpoint in a method annotated with `@AfterEach` (not related to the issue)
* Cleanup the test class by removing exception in the throw declaration when not needed (not related to the issue)

CAMEL-17945: Fix the unstable test HazelcastSedaTransferExchangeTest

---

components/camel-mock/src/main/java/org/apache/camel/component/mock/MockEndpoint.java

Fix for https://issues.apache.org/jira/browse/CAMEL-17948 (part 2)
The first fix had impact on several test cases, so we had to find a better fix.
* Restore the previous code that makes the thread waits only when the received counter was not at the expected value
* Make the thread wait completion only on `reset` to have a limited impact especially on tests that are not with the scope `PER_CLASS`

CAMEL-17948: Wait for completion on reset

---

components/camel-netty/src/main/java/org/apache/camel/component/netty/NettyConverter.java

CAMEL-17962: cleanup duplicated charset features in camel-netty

---

docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_17.adoc

The list of removed components was removed. This adds it back to the
documentation.

CAMEL-17879: re-added documentation about components that were removed

---

tooling/maven/camel-api-component-maven-plugin/src/main/java/org/apache/camel/maven/JavaSourceApiMethodGeneratorMojo.java
tooling/maven/camel-api-component-maven-plugin/src/main/java/org/apache/camel/maven/JavaSourceParser.java

CAMEL-17894: simplify building the data buffer by reading all file data at once

---

dsl/camel-jbang/camel-jbang-core/pom.xml
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelJBangMain.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CodeGenerator.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CodeRestGenerator.java
dsl/camel-jbang/camel-jbang-main/examples/open-api.json

First prototype of REST DSL generator for camel-jbang
https://issues.apache.org/jira/browse/CAMEL-17984

CAMEL-17984 Camel-jbang REST DSL generator

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PackageJaxbMojo.java

CAMEL-17894: minor jaxb plugin cleanups

---

core/camel-core/src/test/java/org/apache/camel/util/ResourceHelperTest.java
core/camel-support/src/main/java/org/apache/camel/support/ResourceHelper.java

https://issues.apache.org/jira/browse/CAMEL-17985

CAMEL-17985: fixed support for "ref:" scheme in ResourceHelper

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/AbstractGenerateConfigurerMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/GenerateInvokeOnHeaderMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/ModelXmlParserGeneratorMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PackageJaxbMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/SchemaGeneratorMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/SpiGeneratorMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/UpdateEagerClassloadedHelper.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/generics/JandexStore.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/generics/PackagePluginUtils.java

CAMEL-17894: more relatively minor cleanups

---

core/camel-core/src/test/java/org/apache/camel/builder/xml/XsltUriResolverTest.java

https://issues.apache.org/jira/browse/CAMEL-17985
Added unit test for XsltUriResolver using ref: scheme

CAMEL-17985: added unit test for XsltUriResolver using ref: scheme

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/SchemaGeneratorMojo.java

CAMEL-17894: read all file data at once to avoid costlier buffer building in Roster class

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/KafkaRecordProcessorFacade.java

CAMEL-17051: the consumer should commit when a pausable error happens

---

tooling/openapi-rest-dsl-generator/src/main/java/org/apache/camel/generator/openapi/RestDslYamlGenerator.java
tooling/openapi-rest-dsl-generator/src/test/java/org/apache/camel/generator/openapi/RestDslYamlGeneratorV3SimpleWithRoutesTest.java
tooling/openapi-rest-dsl-generator/src/test/resources/OpenApiV3PetstoreSimpleWithRoutesYaml.txt

https://issues.apache.org/jira/browse/CAMEL-17995
REST DSL YAML Generator could optionally generate **routes** in addition to **rest**

CAMEL-17995. REST DSL YAML Generator should optionally generate routes

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/AbstractGeneratorMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/ModelXmlParserGeneratorMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PackageComponentMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PackageJandexMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/SpiGeneratorMojo.java

CAMEL-17894: more fixes

---

components/camel-kafka/pom.xml
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/pause/KafkaPausableConsumerCircuitBreakerIT.java
core/camel-core-engine/src/main/docs/modules/eips/pages/resume-strategies.adoc

CAMEL-17051: added a test and documentation for pausable along with circuit breaker EIP

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CodeRestGenerator.java

https://issues.apache.org/jira/browse/CAMEL-18001

CAMEL-18001. Support route generation from OpenAPi in jbang

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointDslMojo.java

CAMEL-17894: avoid compiling the regex everytime

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerHealthCheckIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerLastRecordHeaderIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/commit/KafkaConsumerNoopCommitIT.java

(chores) camel-kafka: fix a few flaky tests

---

dsl/camel-jbang/camel-jbang-core/pom.xml
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelJBangMain.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Image.java
parent/pom.xml

https://issues.apache.org/jira/browse/CAMEL-18006

CAMEL-18006. camel-jbang package image command

---

dsl/camel-jbang/camel-jbang-core/pom.xml
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Build.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelJBangMain.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Deploy.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Image.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Kubernetes.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/KubernetesHelper.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Resource.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Undeploy.java

First prototype of camel-jbang deploy/undeploy command works with minikube
https://issues.apache.org/jira/browse/CAMEL-18008

CAMEL-18008. camel-jbang deploy/undeploy command

---

components/camel-cassandraql/src/main/java/org/apache/camel/component/cassandra/CassandraConsumer.java
components/camel-cassandraql/src/main/java/org/apache/camel/component/cassandra/consumer/support/CassandraResumeStrategy.java
components/camel-cassandraql/src/test/java/org/apache/camel/component/cassandra/integration/CassandraComponentResumeStrategyIT.java
core/camel-core-engine/src/main/docs/modules/eips/pages/resume-strategies.adoc

CAMEL-17963: added resume support for Cassandra CQL

---

tooling/maven/bom-generator-maven-plugin/src/main/java/org/apache/camel/maven/bom/generator/BomGeneratorMojo.java
tooling/maven/camel-api-component-maven-plugin/src/test/java/org/apache/camel/maven/AbstractGeneratorMojoTest.java
tooling/maven/camel-eip-documentation-enricher-maven-plugin/src/test/java/org/apache/camel/maven/CamelSpringNamespaceTest.java
tooling/maven/camel-eip-documentation-enricher-maven-plugin/src/test/java/org/apache/camel/maven/EipDocumentationEnricherMojoTest.java
tooling/maven/camel-eip-documentation-enricher-maven-plugin/src/test/java/org/apache/camel/maven/ResourceUtils.java
tooling/maven/camel-eip-documentation-enricher-maven-plugin/src/test/java/org/apache/camel/maven/XmlHelperTest.java
tooling/maven/camel-javadoc-plugin/src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java
tooling/maven/camel-maven-plugin/src/main/java/org/apache/camel/maven/PrepareFatJarMojo.java
tooling/maven/camel-maven-plugin/src/main/java/org/apache/camel/maven/RunMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/AbstractGenerateConfigurerMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/AbstractGenerateMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/UpdateEagerClassloadedHelper.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/UpdateMainHelper.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/UpdateSensitizeHelper.java
tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/EndpointHelperTest.java
tooling/maven/camel-restdsl-openapi-plugin/src/main/java/org/apache/camel/maven/generator/openapi/AbstractGenerateMojo.java

CAMEL-17894: a few more minor cleanups on the plugins

---

components/camel-sql/pom.xml
components/camel-sql/src/main/java/org/apache/camel/processor/aggregate/jdbc/JdbcAggregationRepository.java
components/camel-sql/src/test/java/org/apache/camel/processor/aggregate/jdbc/JdbcRemoveConfirmOrderAggregateTest.java
components/camel-sql/src/test/resources/org/apache/camel/processor/aggregate/jdbc/JdbcSpringDataSource.xml
core/camel-api/src/main/java/org/apache/camel/spi/RecoverableAggregationRepository.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/aggregate/AggregateProcessor.java

Add a new method to RecoverableAggregateRepository which returns a boolean
to indicate if the exchange was successfully removed from the completed
repository. If the remove failed, retry it in the RecoverTask, but do not
redeliver the exchange.
Add a unit test (provided by Benjamin Bonnet) to simulate this condition.

CAMEL-17613: Race condition in AggregateProcessor with Jdbc Repository

---

components/camel-couchbase/pom.xml
components/camel-couchbase/src/main/java/org/apache/camel/component/couchbase/CouchbaseConsumer.java
components/camel-couchbase/src/main/java/org/apache/camel/component/couchbase/CouchbaseResumeStrategy.java
components/camel-couchbase/src/test/java/org/apache/camel/component/couchbase/integration/ConsumeResumeStrategyIT.java
core/camel-core-engine/src/main/docs/modules/eips/pages/resume-strategies.adoc

CAMEL-17963: added resume support for Couchbase

---

components/camel-netty/src/main/java/org/apache/camel/component/netty/NettyConfiguration.java

CAMEL-17992: don't overwrite ssl from configuration with uri

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java

This prevents the code from throwing ConcurrentModificationException
when suspnding

CAMEL-18003: fix incorrect concurrent access to the Kafka consumer
