core/camel-core-engine/src/main/docs/modules/eips/pages/message-router.adoc
Fix message router example description so that it refers to the same endpoint as the example's code
=> Fix message router example description

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java
closing the consumer in case of reconnect. the consumer is re-instantiated in the following doInit() and the "old" consumer needs to be closed to release file descriptor resources.
=> CAMEL-16832: camel-kafka - file descriptor leak

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java
Both retry & reconnect states need to be set carefully. Prior this change, retry=true is always true (unless PollOnError is set to STOP) and this retry state still avoids that the consumer is closed in the finally block. I temporarily set it to false in the RECONNECT case (so the consumer is closed) and reset it later to continue polling. Probably better to merge those states into a single enum (potential future improvement).
Also I recognized that the consumer may leak if the service is being stopped, while not being in the poll routine (i.e. while retrying/reconnecting/sleeping).
Best regards
Jens
=> CAMEL-16832: camel-kafka - file descriptor leak contd.

components/camel-file/src/main/java/org/apache/camel/component/file/GenericFilePollingConsumer.java, core/camel-core/src/test/java/org/apache/camel/component/file/FileConsumePollEnrichFileIdleEventTest.java
When the  file endpoint is used with option sendEmptyMessageWhenIdle=true in pollEnrich, an empty event is queued but is never read. So on the next call, even if a real file is present, the empty event is returned. The correction forces the empty event to be consumed. I also added a unit test.
=> CAMEL-16874: fix bug with sendEmptyMessages and pollEnrich

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc, dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java, dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java
This depends on apache/camel-kamelets#465
Basically it simplifies initializing new bindings from the CLI using Camel JBang. 
[![asciicast](https://asciinema.org/a/431329.svg)](https://asciinema.org/a/431329)
*Note*: the arguments on the screencast are slightly different, but the functionality is the same.
=> Added support for initializing Kamelet bindings from Camel JBang

docs/user-manual/modules/ROOT/pages/rest-dsl.adoc
Added information about how to allow custom XML/JSon Content-Type headers when automatic binding from POJO to JSon/JAXB takes place.
Changes to documentation based on discussion in the following thread:
https://lists.apache.org/thread.html/r5e82fecd501a3b5ed25844fded1124bf2f3d48a8fdb97556dd5d0f70%40%3Cusers.camel.apache.org%3E
Not sure if the information is placed at the best position in the documentation but I couldn't figure out a better place.
=> Using custom Content-Type headers with RestDSL

components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/utils/message/PulsarMessageHeaders.java, components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/utils/message/PulsarMessageUtils.java
Pulsar tracks message redelivery to its consumers as a property on their `Message`. It would be helpful to know about the redelivery count in Camel. This adds a new `PulsarMessageHeader` to track the Pulsar redelivery count. This is a separate redelivery than the redelivery that Camel itself would handle and thus is a different property than the `Excange.REDELIVERY_COUNTER` property
=> Set pulsar redelivery count in exchange headers

components/camel-jt400/src/main/docs/jt400-component.adoc, components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400Constants.java, components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400MsgQueueConsumer.java
Added some more enhancements to the message queue receiving capability of the JT400 component:
- Added message severity to the headers, as that has been a commonly-requested filter criteria
- Added the `QueuedMessage` object to the headers, so if a processor wants to do more involved operations, like loading the message from the message file to retrieve help text, that option is available
=> (trivial) camel-jt400: add message severity and message object

components/camel-jt400/src/main/docs/jt400-component.adoc, components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400PgmProducer.java
Added usability improvements to the program call support as documented in [the referenced JIRA issue](https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-16907).
Also, snuck in some doc improvements:
- Stopped referring to it as "remote program call" as we have a lot of people running Camel on IBM i now
- Removed the 'type' path parameter (it's not required since the type is inferred from the path)
- added a more practical program call example
=> [CAMEL-16907] camel-jt400 program call usability and doc improvements

components/camel-docker/pom.xml
In the latest docker-java `com.github.jnr:*` deps seem to be no longer used. So now it's not only just superfluous but also brings unnecessary pseudo dep to a x86 native lib `com.github.jnr:jnr-x86asm`. Let's remove them.
=> camel-docker - Remove unnecessary deps to jnr (java native runtime)

components/camel-jackson/src/main/java/org/apache/camel/component/jackson/converter/JacksonTypeConverters.java, components/camel-jackson/src/test/java/org/apache/camel/component/jackson/converter/JacksonConversionsBufferTest.java, components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpSupport.java
With this PR we're fixing the problem described in [CAMEL-16906](https://issues.apache.org/jira/browse/CAMEL-16906) and we'll be able to use `jackson` dataformat unmarshal with `platform-http`. If we're happy with the approach, the solution will have to be replicated to all dataformats, as, each of them know how to convert the body `Map` (or the object that is used by the marshal process) into the `ByteBuffer` as expected by the `platform-http`.
I've tried to look for a generic solution directly on the platform-http component to minimize the impact, but I doubt there is a way to know beforehand how all the dataformats will work (unless we assume they always unmarshal the body to a `Map`).
Ref [CAMEL-16906](https://issues.apache.org/jira/browse/CAMEL-16906)
=> fix(dataformat): conversion to ByteBuffer 

components/camel-mock/src/main/java/org/apache/camel/component/mock/MockEndpoint.java, core/camel-core/src/test/java/org/apache/camel/component/mock/MockEndpointTest.java
Remove the code which evaluates Expression or Predicate values.
Modify MockEndpointTest cases which checked for this (TBD if these cases should simply be removed instead.)
Checked other core and component tests which might have relied on this and didn't find any.
=> CAMEL-16905: remove obsolete code from MockEndpoint

components/camel-kafka/src/main/docs/kafka-component.adoc, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/serde/KafkaSerdeHelper.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/CustomHeaderDeserializer.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerFullIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentTestSupport.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentWithCustomSerializerIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentWithProcessorIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerTopicIsPatternIT.java, docs/components/modules/ROOT/pages/kafka-component.adoc
Added tests, utilities methods and documentation explaining how to handle indexes based on numeric headers along with idempotency.
=> CAMEL-16914: simplify handling of numeric headers for idempotency support

camel-core/src/main/docs/modules/ROOT/pages/direct-vm-component.adoc
DirectVmEndpoint:43 "failIfNoConsumers" is at "true" but doc for 2.x says the default is "false" :
https://github.com/apache/camel/blob/camel-2.x/camel-core/src/main/java/org/apache/camel/component/directvm/DirectVmEndpoint.java
https://github.com/apache/camel/blob/camel-2.25.x/camel-core/src/main/java/org/apache/camel/component/directvm/DirectVmEndpoint.java
=> Update direct-vm-component.adoc : DirectVmEndpoint / bad default value for failIfNoConsumers

core/camel-core/src/test/java/org/apache/camel/support/processor/DefaultMaskingFormatterTest.java, core/camel-support/src/main/java/org/apache/camel/support/processor/DefaultMaskingFormatter.java
Log masking formatter preserves the quotes used in the source data when masking keyValue pairs. Supported are no quotes, single quotes and normal quotes.
=> [CAMEL-16931] Change DefaultMaskingFormatter to preserve quotes in keyValue data

components/camel-jt400/src/main/docs/jt400-component.adoc
The `Program Call` section should be a peer of the sections above and below it, not a subheading for connection pooling. Sorry for missing in my last round of updates.
=> (trivial) tiny tweak to jt400 component doc

components/camel-hl7/src/main/docs/hl7terser-language.adoc
The "HL7 Acknowledgement expression" example can make it look like this negative ack  will be used for MLLP to send back. 
I had a difficult finding a way to set a custom ack without going low-level into HL7 itself. This example demonstrates you can reuse what Camel already provides but have to set it explicitly.
=> Setting custom MLLP ack using HL7 ack example

components/camel-mongodb/src/main/docs/mongodb-component.adoc
Documentation for MongoDB-component changed: some operations have another syntax, than it was in documentation before changes.
=> camel-mongodb documentation changed

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/SalesforceComponent.java, components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/SalesforceHttpClient.java, components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/client/AbstractClientBase.java, components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/RestApiIntegrationTest.java, components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/internal/client/AbstractClientBaseTest.java
This issue is caused by the fact that the Jetty client uses a single thread to invoke completion listeners, and camel reuses that thread (if in synchronous mode) for subsequent operations before returning from AsyncCallback.done(). Result is a deadlock.
I solved this by quickly passing the Jetty response to another thread, using Jetty's thread pool. Would like some eyeballs on this please.
=> CAMEL-16877: camel-salesforce: Fix timeouts occurring in synchronous/transacted routes

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/KafkaRecordProcessor.java
- avoid rebuilding the processor for every polled record
- make the exception processor method private
- remove unused variables
- make the reconnect variable not volatile as it is unnecessary and
local to the thread
- make the retry variable not volatile as it is unnecessary
- avoid recreating the poll duration variable
- stop creating the lock in the inner loop and move it to the main loop
- remove unnecessary parameter thread ID in some methods as it is already available as a member variable to the record processors
- stop overwriting the local lastResult parameter
- fix an incorrect point of commit
=> (chores) camel-kafka: cleanups related to CAMEL-16949

components/camel-spring/src/main/java/org/apache/camel/spring/CamelContextFactoryBean.java, components/camel-spring/src/test/java/org/apache/camel/spring/config/CamelProxyDeadlockTest.java, components/camel-spring/src/test/resources/org/apache/camel/spring/config/CamelProxyDeadlockTest.xml
Fixes spring creating multiple camel contexts, affecting DefaultReactiveExecutor/Worker resulting in deadlock
=> CAMEL-16927 fixes spring creating multiple camel contexts resulting in deadlock

docs/components/antora.yml
Camel 2.x eips module is not part of components component so eip references need to go to latest.  eip-vc attribute added to components component descriptor.
=> [CAMEL-16992] Camel 2.x cant stay in version

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/models/batch-config.json, catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/models/faultToleranceConfiguration.json, catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/models/hystrixConfiguration.json, catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/models/resilience4jConfiguration.json, catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/models/stream-config.json, core/camel-core-engine/src/main/docs/modules/eips/examples/json/batch-config.json, core/camel-core-engine/src/main/docs/modules/eips/examples/json/faultToleranceConfiguration.json, core/camel-core-engine/src/main/docs/modules/eips/examples/json/hystrixConfiguration.json, core/camel-core-engine/src/main/docs/modules/eips/examples/json/resilience4jConfiguration.json, core/camel-core-engine/src/main/docs/modules/eips/examples/json/stream-config.json, core/camel-core-model/src/generated/resources/org/apache/camel/model/config/batch-config.json, core/camel-core-model/src/generated/resources/org/apache/camel/model/config/stream-config.json, core/camel-core-model/src/generated/resources/org/apache/camel/model/faultToleranceConfiguration.json, core/camel-core-model/src/generated/resources/org/apache/camel/model/hystrixConfiguration.json, core/camel-core-model/src/generated/resources/org/apache/camel/model/resilience4jConfiguration.json, core/camel-core-model/src/main/java/org/apache/camel/model/FaultToleranceConfigurationDefinition.java, core/camel-core-model/src/main/java/org/apache/camel/model/HystrixConfigurationDefinition.java, core/camel-core-model/src/main/java/org/apache/camel/model/Resilience4jConfigurationDefinition.java, core/camel-core-model/src/main/java/org/apache/camel/model/config/BatchResequencerConfig.java, core/camel-core-model/src/main/java/org/apache/camel/model/config/StreamResequencerConfig.java
This fixes the website build, broken with some of the recent "Polished EIPs and make their categorization simpler for tooling." work. With  the 'eip' label restored, the json files are symlinked so they can be used in the corresponding eip pages.
=> add eip back to eip models labels

components/camel-aws/camel-aws2-ddb/src/main/docs/aws2-ddbstream-component.adoc
If I've understood CAMEL-16837 correctly, the 'batch consumers' stuff in `aws2-ddbstream` is not currently functional.
There was a proposal to mention this in the CQ extension docs. But I figured it made more sense to remove it from the compoent docs, until it's fully implemented / supported.
=> CAMEL-16837: Remove reference to non-functional aws2-ddbstream batch consumers

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerTopicIsPatternIT.java
- prevent the code from reusing the same topic as previous test
- ensure the mock interceptor is cleared before the test
=> camel-kafka: fix flaky kafka test KafkaConsumerTopicIsPatternIT

components/camel-jdbc/src/main/java/org/apache/camel/component/jdbc/JdbcProducer.java
Although it would be advisable to have the statement auto-closing, in
this case it prevents the result set from being post-processed. This
causes a failure subsequently, when the result set from the statement is
used to iterate over the results.
=> camel-jdbc: auto-closing the statement prevents post-processing

components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/SftpConfiguration.java, components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/SftpEndpoint.java, components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/SftpOperations.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpChmodDirectoryIT.java, core/camel-api/src/main/java/org/apache/camel/spi/ManagementStrategy.java
For the sftp component a possibility to set the permission (chmod) also on an new created path.
Only for the producer.
SFTP api feature: channel.chmod(permissions, directory);
Implemented within an helper method
=> CAMEL-17037: added for sftp producer chmodDirectory functionality

components/camel-bean-validator/src/main/java/org/apache/camel/component/bean/validator/BeanValidatorProducer.java, components/camel-bean-validator/src/test/java/org/apache/camel/component/bean/validator/BeanValidatorRouteTest.java
This PR implements CAMEL-16946.
The bean-validator component checks if the body is of type Iterable. If so, then each element will be validated. Otherwise, the single element will be validated.
The corresponding tests have been changed to parameterized tests. Each test is executed with a single bean as well as with a collection of beans.
=> CAMEL-16946:  bean-validator,  validate all elements if body is of type Iterable

components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpSSLHandshakeErrorTest.java
The fix for the CAMEL-16718 changed the exception returned
(commit ref: 4845cf938e423355ea96ed7a3e1942fcceac2de3), so now the
SSLHandshakeException is not on the cause of the original exception, but
instead is the exception itself.
-- 
This one was failing for a while on CI. I think this will fix it.
=> CAMEL-16718: fix camel-netty-http test case

components/camel-hl7/src/main/docs/hl7-dataformat.adoc
This PR intent is to fix this formatting typo:
=> fix formatting typo in hl7-dataformat.adoc

components/camel-hl7/src/main/docs/hl7-dataformat.adoc
sorry in relation to previous PR https://github.com/apache/camel/pull/6363
I didn't realize there was also another formatting typo @oscerd 
This PR intent is to fix this formatting problem in this table:
=> fix formatting in table of hl7-dataformat.adoc

docs/user-manual/modules/faq/pages/how-can-i-stop-a-route-from-a-route.adoc
Hi guys,
This article looks outdated.
line 151 contains: exchange.getContext().stopRoute("myRoute");
Meanwhile there is no method stopRoute(String) in org.apache.camel.CamelContext
I suggest this call instead^
exchange.getContext().getRouteController().stopRoute("myRoute");
=> Proposed changes in the article on stopping a route programmatically

components/camel-ftp/pom.xml, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/services/SftpEmbeddedService.java
Issue: https://issues.apache.org/jira/browse/CAMEL-17163
Sshd 2.6.0+ removes weaker security settings from the default configuration - https://issues.apache.org/jira/browse/SSHD-1004
This PR brings a quick fix, which enables deprecated cipher and signature (which is ok for the server running in the test scope)
Better fix could probably be to use stronger security during the test and get rid of the deprecated cipher and signature.
=> camel-ftp - Upgrade to SSHD 2.7.x

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultReactiveExecutor.java
Fix log message to show the Runnable being executed and not the Runnable which caused the queue to be run.
=> Fix incorrect log message

components/camel-aws/camel-aws2-ddb/src/main/java/org/apache/camel/component/aws2/ddb/Ddb2Endpoint.java
=> CAMEL-17121: converted camel-aws2-ddb to repeatable tasks

components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/OpenTelemetryTracer.java
I had a setup where I was trying to use Camel's auto-instrumentation for my workflow. On my services that created a `RouteBuilder`, I had no troubles generating telemetry. However, for my services that only sent messages using a `ProducerTemplate` outside of a predefined route, I encountered a `NullPointerException` when `camel-opentelemetry` was attempting to create that span. 
After looking into the stack trace, I found that `spanFromExchange.getBaggage()` was null. So when they are trying to update the current OpenTelemetry `Context` with it, it would throw that exception and the operation was not traced.
By doing a null check on the `Baggage` before using it to populate the `Context`, it can be ensured that the `Span` would be built when there is no parent span.
=> Builds current otel context depending on the exchange's baggage state

docs/components/modules/ROOT/partials/component-endpoint-options.adoc
See https://github.com/apache/camel-website/pull/667
=> With inline anchor name column can be non-'a'

components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Producer.java
Don't log a warning if this is the first part of a multipart upload.
If this is the first part of the file, then filePosition will be zero and we will attempt to skip zero bytes. This change avoids the call to skip entirely for the first part.
https://issues.apache.org/jira/browse/CAMEL-17204
Uncomment and fill this section if your PR is not trivial
=> [CAMEL-17204] Fix warning message for S3 multipart uploads

components/camel-salesforce/camel-salesforce-component/src/main/docs/salesforce-component.adoc
salesforce component documentation- 
getting TIMER_COUNTER not working with  in.getHeader ,changed to exchange.getHeader instead.
=> salesforce component doc-  getting TIMER_COUNTER not working with  in.getHeader 

components/camel-zookeeper/src/main/java/org/apache/camel/component/zookeeper/cluster/ZooKeeperClusterView.java, docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_14.adoc
This allows different routes to have separate leaders based on the namespace defined (i.e. "master:namespace1" and "master:namespace2" could run on separate cluster members, as long as they are each running on only one). The camel-consul component already works this way in conjunction with the camel-master component.
=> CAMEL-17226 Add namespace to path used for leadership election when using Zookeeper with Master component

components/camel-corda/pom.xml, parent/pom.xml
I did not create a Jira for this as it's loosely related to CAMEL-17237.
If you have exclusions for a dependency defined in `camel-parent` and add additional ones in the component POM. Then the ones defined in the component will override those defined in `camel-parent`. So they all need to be defined in one place for things to work properly.
=> camel-corda: Combine corda-rpc exclusions in one place

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaProducer.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/producer/support/KafkaProducerCallBack.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/producer/support/KafkaProducerMetadataCallBack.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/producer/support/KeyValueHolderIterator.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/producer/support/ProducerUtil.java
Includes:
- rework the producer to reduce the number of allocations and GC
pressure
- replace AtomicInteger with LongAdder to reduce risk of contention in AtomicInteger (and a minor improvement in performance)
- logging improvements in the hot path
- rework the callbacks to prevent creating threads unnecessarily
- avoid creating arrays/collections for the delegating callback
- use collection singleton for single-item arrays when possible
- cleanup to use generics in some of the code
- use an assert to check the internal worker pool for not being null as it seems faster
- do a single pass of the set when iterating over it to get the propagated headers
- cleanup the record iterator to simplify and reduce calls to getHeader
=> CAMEL-17240: cleanup the camel-kafka producer code

components/camel-http/src/main/java/org/apache/camel/component/http/HttpComponent.java, components/camel-http/src/test/java/org/apache/camel/component/http/HeaderFilteringTest.java
I had to change HeaderFilteringTest because it did a GET with a body and this didn't work after I added httpMethod to the endpoint properties. But you shouldn't send a body with a GET anyway, so this seems to be the right way to do the test...
=> CAMEL-17267 Adding httpMethod to endpoint properties

components/camel-jsonpath/src/main/docs/jsonpath-language.adoc
setHeader element was incorrectly closed by a transform tag.
(trivial PR).
=> Invalid XML

core/camel-support/src/main/java/org/apache/camel/support/FileWatcherResourceReloadStrategy.java, core/camel-support/src/main/java/org/apache/camel/support/RouteWatcherReloadStrategy.java, docs/user-manual/modules/ROOT/pages/camel-maven-plugin.adoc, tooling/maven/camel-maven-plugin/src/main/java/org/apache/camel/maven/DevMojo.java, tooling/maven/camel-maven-plugin/src/main/java/org/apache/camel/maven/RunMojo.java
As discussed in https://issues.apache.org/jira/browse/CAMEL-17310 there are some issues with live reload, I'll try to investigate more
=> [CAMEL-17310] Add dev goal to enable live reloading

components/camel-jackson/src/main/java/org/apache/camel/component/jackson/AbstractJacksonDataFormat.java
If an ObjectMapper from the registry is used, useList=true has no
effect.
I've got some concerns about changes in the generated files. It seems like there's some back and forth battle:
- collectionType vs collectionTypeName
- unmarshalType vs unmarshalTypeName
Looks like these definitions are coming from somewhere else, maybe here https://github.com/apache/camel/blob/main/core/camel-core-model/src/main/java/org/apache/camel/model/dataformat/JsonDataFormat.java
Looks like maybe you get different result for these generated files depending on where they're generated from. Not clear to me.
=> CAMEL-17336: camel-jackson: useList has no effect

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/SalesforceException.java, components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/client/DefaultRestClient.java, components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/RestApiIntegrationTest.java, components/camel-salesforce/it/resources/salesforce/classes/MerchandiseRestResource.cls
In case of non-2xx responses to Apex REST requests, preserve the
response content since it won't necessarily be in the standard
salesforce exception format.
Is it a terrible idea to return an InputStream in the Exception? Very possible that it would only get closed when the exception gets GC'd. I believe it's always a ByteArrayInputStream, so at least no file/socket handles are involved. I'd like to avoid returning the response content as the message body. Since this is for exceptional situations, I think it makes sense to use an exception and preserve the `in` message body for logging/debugging capabilities.
=> CAMEL-13180: camel-salesforce: Custom errors

examples/camel-example-google-pubsub/pom.xml, examples/camel-example-kafka/pom.xml, examples/camel-example-restlet-jdbc/pom.xml
There are a few examples that have hardcoded log4j versions - they should probably be inheriting the log4j 2.16 version from camel-parent.
=> CAMEL-17327 Remove hardcoded log4j versions from google-pubsub / kafka/restlet-jdbc examples

examples/camel-example-google-pubsub/pom.xml, examples/camel-example-kafka/pom.xml, examples/camel-example-restlet-jdbc/pom.xml
There are a few examples that have hardcoded log4j versions - they should probably be inheriting the log4j 2.16 version from camel-parent.      Cherry pick of the commit to the 2.x branch over to the release branch.
=> CAMEL-17327 Remove hardcoded log4j versions from google-pubsub / kafka /restlet-jdbc examples 

docs/local-build.sh, docs/source-map.yml, docs/source-watch.yml
This works now although there are some spurious errors from camel-spring-boot branches we don't want.
Once I upgrade the camel-website dependencies (https://github.com/apache/camel-website/pull/727) the errors will be gone.
=> main local/partial build setup

core/camel-management-api/src/main/java/org/apache/camel/api/management/mbean/ManagedBacklogDebuggerMBean.java, core/camel-management/src/main/java/org/apache/camel/management/mbean/ManagedBacklogDebugger.java, core/camel-management/src/test/java/org/apache/camel/management/BacklogDebuggerTest.java, docs/user-manual/modules/ROOT/pages/backlog-debugger.adoc
Just like setting and removing message headers, there should be a setting and removing exchange properties functionality. This PR adds the implementation.
=> [CAMEL-17371] Set and remove Exchange Properties

docs/user-manual/modules/ROOT/pages/improving-the-documentation.adoc, docs/user-manual/modules/ROOT/pages/release-guide-website.adoc
This updates the doc build instructions to explain how to do local builds using the local-build.sh in many subproject by now and how to set up a docs PR simply.
=> update doc build instructions to explain local-build.sh etc

archetypes/camel-archetype-endpointdsl/src/main/resources/archetype-resources/src/main/java/MyRouteBuilder.java
The GenericFileExist proxy was removed in
c73b6ed0db1db3bddee4c6f9f067a60677191181. This adjust the code to use
the actual one from the file component.
=> Fix archetype DSL integration test

components/camel-stub/src/main/docs/stub-component.adoc
In the Stub component docs, one of the links to the VM component mistakenly points to the Stub component.
This PR fixes this reference to point to the VM component page.
=> Fix wrong link in stub component docs

parent/pom.xml
Upgrade log4j - > 2.17.1 and pax logging to 1.11.13 (version which contains log4j 2.17.1)
=> Upgrade log4j and pax-logging

components/camel-fhir/camel-fhir-component/src/main/java/org/apache/camel/component/fhir/FhirComponent.java, components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirConfigurationIT.java, components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirSimpleIT.java, core/camel-support/src/main/java/org/apache/camel/support/component/AbstractApiComponent.java
=> CAMEL-17373: Fix FhirComponent startup

components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Component.java, components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Endpoint.java, components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/SqsComponentClientRegistryTest.java, components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/SqsComponentConfigurationTest.java, components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/integration/SqsDeadletterWithClientRegistryLocalstackIT.java
Issue: https://issues.apache.org/jira/browse/CAMEL-17437
Problem was caused by less severe problem - one validation was executed too early. 
Validation of sqs client has to be done after endpoint configuration, to cover a case when client is autowired.
I fixed several tests which covers this validation + added a new junit integration test using deadletter and autowired client.
=> CAMEL-17437 Camel-aws2-sqs: Deadletter fails with sqs client from registry 

core/camel-management-api/src/main/java/org/apache/camel/api/management/mbean/ManagedBacklogDebuggerMBean.java, core/camel-management/src/main/java/org/apache/camel/management/mbean/ManagedBacklogDebugger.java, core/camel-management/src/test/java/org/apache/camel/management/BacklogDebuggerTest.java, docs/user-manual/modules/ROOT/pages/backlog-debugger.adoc
This PR resolves the https://issues.apache.org/jira/browse/CAMEL-17444
The message history is exposed as a List of Maps containing String pairs, so that the tooling can use it in debugging and displaying stack traces.
=> ManagedDebugger exposes Message History 

tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/JavadocHelper.java, tooling/camel-tooling-util/src/test/java/org/apache/camel/tooling/util/JavadocHelperTest.java
=> Revert "CAMEL-17433 fix JavadocHelper (3.14.x)"

tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/JavadocHelper.java, tooling/camel-tooling-util/src/test/java/org/apache/camel/tooling/util/JavadocHelperTest.java
=> Revert "CAMEL-17433 fix JavadocHelper (3.13.x)"

tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/JavadocHelper.java, tooling/camel-tooling-util/src/test/java/org/apache/camel/tooling/util/JavadocHelperTest.java
=> Revert "CAMEL-17433 fix JavadocHelper (3.12.x)"

tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/JavadocHelper.java, tooling/camel-tooling-util/src/test/java/org/apache/camel/tooling/util/JavadocHelperTest.java
=> Revert "CAMEL-17433 fix JavadocHelper (3.7.x)"

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc
This would allow you to directly execute the yaml file on *nix systems to run the examples.
=> feat: add shebang comments to yaml examples

components/camel-mock/src/main/docs/mock-component.adoc, components/camel-spring-xml/pom.xml, core/camel-core-engine/src/main/docs/modules/eips/pages/eventDrivenConsumer-eip.adoc, core/camel-core-engine/src/main/docs/modules/eips/pages/process-eip.adoc, docs/user-manual/modules/ROOT/pages/book-getting-started.adoc
While reading the getting started page, I realized that some links pointed to the Javadoc were broken.
* Replace URLs of type `http://camel.apache.org/maven/current/${component-name}/apidocs` with `http://javadoc.io/doc/org.apache.camel/${component-name}/latest` everywhere in the project
=> Fix the javadoc paths

docs/user-manual/modules/faq/pages/why-the-name-camel.adoc
Some links point to web pages that don't exist anymore
* Removed the broken links. 
**NB:** The other possibility could have been to rely on web.archive.org like for example (https://web.archive.org/web/20131108024540/http://www.fao.org/sd/EGdirect/EGan0006.htm) but I felt that it was not really needed in this context WDYT?
=> Remove broken links in why camel

components/camel-cdi/src/main/docs/cdi.adoc, docs/user-manual/modules/faq/pages/how-do-i-configure-endpoints.adoc
The way to reference a bean from an Endpoint URI has changed and should be described the same way in the documentation.
* Align the sections `Referring beans from Endpoint URIs` in the doc to remain consistent
**NB:** In case of CDI, I changed `#bean:id` for `#bean:name` because in CDI, we refer a bean by its name so it was confusing. Hopping that you agree with me 😃
=> Align doc regarding ref beans from Endpoint URI

docs/gulpfile.js
The update to modern Antora file layout missed some gulp files, including this for 3.7.x.  Just in case someone runs it, lets fix it.
=> update gulp file to put images in correct location

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java
=> CAMEL-17489: camel-kafka - Unsubscribe before closing the consumer

core/camel-core-engine/src/main/docs/modules/eips/pages/marshal-eip.adoc, core/camel-core-engine/src/main/docs/modules/eips/pages/unmarshal-eip.adoc
The description of the example used for the marshal and un-marshal EIP doesn't seem to match with the actual route defined.
* Use `marshal` instead of `unmarshal` and vice versa
=> Fix the route of the example of the marshal/unmarshal EIP

core/camel-util/src/main/java/org/apache/camel/util/URISupport.java, core/camel-util/src/test/java/org/apache/camel/util/URISupportTest.java
The unintended behaviour is described in issue CAMEL-17452. I am making this PR as per the suggestion of Claus Ibsen.
This pull request is a slight modification of the SECRETS regular expression pattern in URISupport, to be more strict when masking passwords, so as to not mask whole subsets of the URI.
Short summary is that the SECRETS regex-pattern will match on braces (")" or "}"), even if they are not a part of the password parameter.
=> CAMEL-17452 Fix bug in URISupport#sanitizeUri

camel-dependencies/camel-dependencies-pom-template.xml
This proposed file change is kind of related to "[_3rd party dependency or pom.xml refers to bintray_](https://bit.ly/caml16787)". 
It is not obvious exactly which artifacts in Camel's dependency graph have a transient dependency on `org.apache.any23:apache-any23:2.4`
For some reason or another though, at least three dependencies trigger an attempt to download `org.apache.any23:apache-any23:2.4`:
1. `com.google.guava:guava`
2. `com.google.code.findbugs:jsr305`
3. `org.slf4j:slf4j-api`
Those download attempts try to resolve `apache-any23:2.4`'s pom. That pom is [_configured with a bintray repository that is unreachable_](https://bit.ly/any2324).
That unreachable bintray repository [_has been removed from `org.apache.any23:apache-any23:2.6`_](https://bit.ly/any2326).
This pull request …
=> CAMEL-16787: Align apache-any23 version with version in parent pom

dsl/camel-yaml-dsl/camel-yaml-dsl/src/main/docs/yaml-dsl.adoc
Same issue https://issues.apache.org/jira/browse/CAMEL-17253
marshal and unmarshal do not have data-format-type field
=> CAMEL-17253: Remove misleading docs

components/camel-graphql/src/main/java/org/apache/camel/component/graphql/GraphqlEndpoint.java, components/camel-jbpm/src/main/java/org/apache/camel/component/jbpm/server/CamelKieServerExtension.java, components/camel-jira/src/main/java/org/apache/camel/component/jira/oauth/OAuthAsynchronousHttpClientFactory.java, components/camel-schematron/src/main/java/org/apache/camel/component/schematron/processor/ClassPathURIResolver.java
Fix resource loading calls to pass in calling classes class loader so that they work as expected in OSGi enviroments.
- [ x ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL-17524) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [ x] Each commit in the pull request should have a meaningful subject line and body.
- [ x] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [ x] Write a pull request description that is detailed enough to understand what the pull request does, how, and …
=> CAMEL-17524 fix resource loading so it works in OSGi

core/camel-core-engine/src/main/docs/modules/eips/pages/setHeader-eip.adoc
Updating setHeader-eip.adoc to include a sample of fluent syntax.
=> adding an example to setHeader-eip.adoc

docs/user-manual/modules/faq/pages/how-do-i-import-routes-from-other-xml-files.adoc
The links to the example of how to import routes from another XML files are broken.
* Fix typos
* Fix links to the examples that are now in `camel-spring-xml` instead of `camel-spring`
=> Fix the links in the import routes page

components/camel-jms/src/main/java/org/apache/camel/component/jms/JmsMessage.java, components/camel-sjms/src/main/java/org/apache/camel/component/sjms/SjmsMessage.java, components/camel-spring-integration/src/main/java/org/apache/camel/component/spring/integration/SpringIntegrationMessage.java, core/camel-core/src/test/java/org/apache/camel/processor/transformer/TransformerRouteTest.java, core/camel-support/src/main/java/org/apache/camel/support/AbstractExchange.java, core/camel-support/src/main/java/org/apache/camel/support/MessageHelper.java, core/camel-support/src/main/java/org/apache/camel/support/MessageSupport.java, core/camel-support/src/test/java/org/apache/camel/support/AbstractExchangeTest.java, core/camel-support/src/test/java/org/apache/camel/support/MessageHelperTest.java
The data type of a message is lost when it is copied which causes issue when the data transformer can only be found thanks to the provided data type.
* Add an utility method `copyBody(Message source, Message target)` to copy the body of a message to another message while taking care of the data type internally when applicable
* Modify the different implementations of  `copyFrom(org.apache.camel.Message that)` to replace `setBody` with `copyBody` to preserve the data type
* Modify the implementation of `AbstractExchange#copy()` to replace `setBody` with `copyBody` to preserve the data type
=> [CAMEL-17579] Preserve the data type of a message on copy

core/camel-support/src/test/java/org/apache/camel/support/AbstractExchangeTest.java
Backport of #6866 for 3.14 (part 2)
=> CAMEL-17579: Add the missing implementation of setBeanPostProcessor in MyCamelContext

components/camel-aws/camel-aws2-ses/src/main/java/org/apache/camel/component/aws2/ses/Ses2Configuration.java, components/camel-aws/camel-aws2-ses/src/main/java/org/apache/camel/component/aws2/ses/Ses2Constants.java, components/camel-aws/camel-aws2-ses/src/main/java/org/apache/camel/component/aws2/ses/Ses2Producer.java, components/camel-aws/camel-aws2-ses/src/test/java/org/apache/camel/component/aws2/ses/SesComponentConfigurationTest.java
Implements [camel-17610](https://issues.apache.org/jira/browse/CAMEL-17610)
Adds support for CC and BCC type of destinations. Updates tests too.
=> aws2-ses: Add support for CC and BCC addresses

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/AbstractGenerateConfigurerMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/AbstractGenerateMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/AbstractGeneratorMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointDslMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointUriFactoryGenerator.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/MvelHelper.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PackageArchetypeCatalogMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PackageDataFormatMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PrepareAssemblyMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PrepareCatalogMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PrepareExampleMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PrepareParentPomMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PropertyConfigurerGenerator.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/SchemaGeneratorMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/UpdateReadmeMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/XRefCheckMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/dsl/DslHelper.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/dsl/component/ComponentDslBuilderFactoryGenerator.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/dsl/component/ComponentDslInnerImplBuilderGenerator.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/dsl/component/ComponentsBuilderFactoryGenerator.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/dsl/component/ComponentsDslMetadataRegistry.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/generics/ClassUtil.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/generics/GenericsUtil.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/generics/OwbGenericArrayTypeImpl.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/generics/OwbTypeVariableImpl.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/generics/OwbWildcardTypeImpl.java
=> (chores) Another round of cleanups for the camel-maven-package-plugin

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/AbstractGenerateConfigurerMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointDslMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/TypeConverterLoaderGeneratorMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/generics/PackagePluginUtils.java
=> Last round of cleanups for the camel-maven-package-plugin

docs/user-manual/modules/ROOT/pages/testing.adoc
The website build is [broken](https://ci-builds.apache.org/job/Camel/job/Camel.website/job/main/753/) due the next error:
```
➤ YN0000: [09:01:06.980] ERROR (asciidoctor): target of xref not found: components:others:test-cdi-junit5.adoc
➤ YN0000:     file: docs/user-manual/modules/ROOT/pages/testing.adoc
➤ YN0000:     source: https://github.com/apache/camel.git (refname: main, start path: docs/user-manual)
```
After a deeper investigation, it is due to the fact that the page `testing` from `user-manual` tries to access to the page `test-cdi-junit5` from the latest release while it is new and thus not yet released so not yet available.
* Revert the changes in the page `testing` from `user-manual`
* Prepare the changes to apply once 3.16 is released
=> Remove the link to CDI JUnit5 as not yet released

components/camel-mail/src/test/java/org/apache/camel/dataformat/mime/multipart/MimeMultipartDataFormatTest.java
monitors that multiple attachments with different charsets marshal and unmarshal doesn't damage non-ascii characters. Currently it doesn't.
=> add test for multiple text attachments but different charsets

components/camel-csv/src/test/java/org/apache/camel/dataformat/csv/CsvMarshalHeaderTest.java, components/camel-csv/src/test/java/org/apache/camel/dataformat/csv/CsvMarshalHeaderWithCustomMarshallFactoryTest.java, components/camel-salesforce/camel-salesforce-maven-plugin/src/test/java/org/apache/camel/maven/CamelSalesforceMojoIntegrationTest.java, components/camel-solr/src/test/java/org/apache/camel/component/solr/SolrCloudFixture.java, core/camel-core/src/test/java/org/apache/camel/component/file/FileConsumerSuspendAndResumeTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FileConsumerSuspendTest.java, core/camel-core/src/test/java/org/apache/camel/processor/FileIdempotentTrunkStoreTest.java, core/camel-core/src/test/java/org/apache/camel/processor/FileRollbackOnCompletionTest.java, core/camel-core/src/test/java/org/apache/camel/support/processor/idempotent/FileIdempotentStoreOrderingTest.java, core/camel-xml-io/src/test/java/org/apache/camel/xml/in/ModelParserTest.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Project.java, tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/PackageHelper.java, tooling/camel-tooling-util/src/test/java/org/apache/camel/tooling/util/PackageHelperTest.java, tooling/maven/camel-api-component-maven-plugin/src/main/java/org/apache/camel/maven/ApiComponentGeneratorMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PackageModelMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PrepareCatalogMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/UpdateSensitizeHelper.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/ValidateComponentMojo.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/XRefCheckMojo.java
Fix for https://issues.apache.org/jira/browse/CAMEL-17607
The methods  `walk`, `lines`, `newDirectoryStream` and `list` of the class `Files` produce a `Stream`  that needs to be closed otherwise we end-up with a resource leak. 
The goal of this PR is to spot the places in the code where those methods are used without closing the stream and fix the leaks by closing the streams thanks to a try-with-resource-statement.
**NB:** No need to close a `Stream` opened while calling a `flatMap` as it will be closed automatically.
=> CAMEL-17607: Close streams created from the class Files to avoid leaks

catalog/camel-csimple-maven-plugin/src/main/java/org/apache/camel/maven/GenerateMojo.java, tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/Strings.java, tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/FileUtil.java, tooling/maven/bom-generator-maven-plugin/src/main/java/org/apache/camel/maven/bom/generator/DependencySet.java, tooling/maven/bom-generator-maven-plugin/src/main/java/org/apache/camel/maven/bom/generator/ExternalBomConflictCheck.java, tooling/maven/bom-generator-maven-plugin/src/main/java/org/apache/camel/maven/bom/generator/ExternalBomConflictCheckSet.java, tooling/maven/camel-api-component-maven-plugin/src/main/java/org/apache/camel/maven/AbstractApiMethodGeneratorMojo.java, tooling/maven/camel-api-component-maven-plugin/src/main/java/org/apache/camel/maven/ApiComponentGeneratorMojo.java, tooling/maven/camel-api-component-maven-plugin/src/main/java/org/apache/camel/maven/JavaSourceParser.java, tooling/maven/camel-eip-documentation-enricher-maven-plugin/src/main/java/org/apache/camel/maven/EipDocumentationEnricherMojo.java
=> Maven plugin cleanups

core/camel-core-model/src/generated/resources/org/apache/camel/model/rest/jaxb.index, core/camel-core-model/src/main/java/org/apache/camel/model/rest/VerbDefinition.java, core/camel-xml-io/src/generated/java/org/apache/camel/xml/in/ModelParser.java, docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_16.adoc, dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/ModelDeserializers.java, dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/ModelDeserializersResolver.java, dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/camel-yaml-dsl.json, dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/camelYamlDsl.json, dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/RestTest.groovy
This also affects the generated XML model which also will only accept
the XML elements for different methods such as get, put and post.
Remove test cases in RestTest.groovy using verb.
=> CAMEL-17308: Remove "verb" as an allowed CAMEL REST YAML element.

components/camel-debezium/camel-debezium-mysql/src/test/java/org/apache/camel/component/debezium/DebeziumMySqlComponentTest.java, core/camel-support/src/main/java/org/apache/camel/support/PropertyBindingSupport.java
Issue: https://issues.apache.org/jira/browse/CAMEL-17658
Problem is caused not entirely by debezium component. Automatic properties configuration can "trim" property in specific cases.
- Let say, that we have a property **map.A.B=value**, where  **map** is an URI property defined as ` @UriParam(label = "common", prefix = "map.", multiValue = true,`. Automatic configuration initialization will detect a HashMap object as a **map** property, but then it executes "set property A=value into HashMap (and property B is ignored)"
- I'm trying to change mechanism to not ignore the remaining part of the property name and execute "set property A.B=value into HashMap"
I'm not sure whether this change could be approved, Therefore this is only draft and I'd like to see whether there will be some …
=> CAMEL-17658 camel-debezium: additionalProperties are trimmed

archetypes/camel-archetype-main/src/main/resources-filtered/META-INF/maven/archetype-metadata.xml, archetypes/camel-archetype-main/src/main/resources/archetype-resources/ReadMe.txt, archetypes/camel-archetype-main/src/main/resources/archetype-resources/pom.xml, archetypes/camel-archetype-main/src/main/resources/archetype-resources/src/test/java/MyApplicationTest.java, archetypes/camel-archetype-main/src/test/resources/projects/build-it/archetype.properties, archetypes/camel-archetype-main/src/test/resources/projects/run-it/archetype.properties
Fix for https://issues.apache.org/jira/browse/CAMEL-17682
A new module has been added allowing to test Camel Main applications, so an example of test should be added to the corresponding archetype.
* Use the test dependency `camel-test-main-junit5` instead of `camel-test` to test the application
* Configure surefire to use a version that supports JUnit 5
* Remove an unused import
=> CAMEL-17682: Use the new test-main module in camel-archetype-main

components/camel-google/camel-google-storage/src/main/java/org/apache/camel/component/google/storage/GoogleCloudStorageProducer.java, components/camel-google/camel-google-storage/src/test/java/org/apache/camel/component/google/storage/unit/ProducerStoreFileTest.java, components/camel-google/camel-google-storage/src/test/resources/tostore/FileToStore.txt
Refactor and simplify code for calculating content-length to
avoid NPE and unnecessary work.
Create the Blob directly from InputStream.
Add a unit test for these cases.
=> CAMEL-17702: fix NPE and improve handling for Content-Length

components/camel-test/camel-test-main-junit5/src/main/docs/test-main-junit5.adoc, components/camel-test/camel-test-main-junit5/src/main/java/org/apache/camel/test/main/junit5/CamelMainContext.java, components/camel-test/camel-test-main-junit5/src/main/java/org/apache/camel/test/main/junit5/CamelMainExtension.java, components/camel-test/camel-test-main-junit5/src/main/java/org/apache/camel/test/main/junit5/CamelMainTest.java, components/camel-test/camel-test-main-junit5/src/main/java/org/apache/camel/test/main/junit5/Configure.java, components/camel-test/camel-test-main-junit5/src/main/java/org/apache/camel/test/main/junit5/DebuggerCallback.java, components/camel-test/camel-test-main-junit5/src/main/java/org/apache/camel/test/main/junit5/ReplaceInRegistry.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/annotation/AdviceRouteTest.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/annotation/ConfigureTest.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/annotation/DumpRouteCoverageTest.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/annotation/MockEndpointTest.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/annotation/MockEndpointsAndSkipTest.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/annotation/OverridePropertiesTest.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/annotation/ReplaceBeanFromFieldTest.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/annotation/ReplaceBeanFromMethodTest.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/annotation/ReplaceRouteFromTest.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/annotation/SupportParameterizedTest.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/annotation/SupportRepeatedTest.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/annotation/TestInstanceDefaultTest.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/annotation/TestInstancePerClassTest.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/annotation/TestInstancePerMethodTest.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/annotation/WithDebuggerCallbackTest.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/annotation/WithMainClassTest.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/annotation/custom/LoadCustomConfigurationDefaultPackageTest.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/annotation/custom/LoadCustomConfigurationSamePackageTest.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/annotation/other/MyOtherConfiguration.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/annotation/other/MyOtherMainClass.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/legacy/ConfigureTest.java
Relates to https://issues.apache.org/jira/browse/CAMEL-17690
Some end-users could want to organize their tests using Nested tests thus it could be interesting to support them at least in the annotated approach.
* Consider the annotations on all the nested test classes instead of the only the current class
* Adapt the code to add the values of all **multivalued** attributes ordered from the outermost to the innermost
* Adapt the code to use only the value of the innermost for **mono-valued** attributes including `propertyPlaceholderLocations` as it is coupled to `propertyPlaceholderFileName`
* Adapt the code to support the annotations `ReplaceInRegistry` and `Configure` in nested test classes
* Fix the expected format of the attributes `properties` and `replaceRouteFromWith` to have …
=> CAMEL-17690: Add support of Nested tests

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/models/unmarshal.json, catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd, components/camel-jackson/src/test/java/org/apache/camel/component/jackson/JacksonJsonDataFormatTest.java, components/camel-jackson/src/test/java/org/apache/camel/component/jackson/JacksonMarshalTest.java, components/camel-jackson/src/test/java/org/apache/camel/component/jackson/JacksonObjectMapperTest.java, components/camel-jackson/src/test/java/org/apache/camel/component/jackson/SpringJacksonAllowNullBodyTest.java, components/camel-jackson/src/test/resources/org/apache/camel/component/jackson/SpringJacksonAllowNullBodyTest.xml, core/camel-core-engine/src/main/docs/modules/eips/pages/unmarshal-eip.adoc, core/camel-core-model/src/generated/resources/org/apache/camel/model/unmarshal.json, core/camel-core-model/src/main/java/org/apache/camel/builder/DataFormatClause.java, core/camel-core-model/src/main/java/org/apache/camel/model/ProcessorDefinition.java, core/camel-core-model/src/main/java/org/apache/camel/model/UnmarshalDefinition.java, core/camel-core-reifier/src/main/java/org/apache/camel/reifier/UnmarshalReifier.java, core/camel-core/src/test/java/org/apache/camel/model/XmlParseTest.java, core/camel-core/src/test/java/org/apache/camel/processor/UnmarshalProcessorTest.java, core/camel-core/src/test/resources/org/apache/camel/model/routeWithTidyMarkupDataFormatAndAllowNullBody.xml, core/camel-support/src/main/java/org/apache/camel/support/processor/UnmarshalProcessor.java, core/camel-xml-io/src/generated/java/org/apache/camel/xml/in/ModelParser.java, dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/ModelDeserializers.java, dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/camel-yaml-dsl.json, dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/camelYamlDsl.json, dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/UnmarshalTest.groovy
Fix for https://issues.apache.org/jira/browse/CAMEL-17720
It is common to unmarshal data to json via Jackson, and the DataFormat we have will then fail if the message body is empty. We should add an option that can be turned on to allow null body and ideally propose the same option for all Dataformats.
* Add the new option `allowNullBody` at unmarshal EIP level to be able to apply it for all existing DataFormat
* Skip the call to the method `unmarshal` if `allowNullBody` is `true` and the body is `null`
* Add `allowNullBody` to the Java DSL
=> CAMEL-17720: Add option to allow unmarshalling null body

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd, components/camel-spring-xml/src/test/java/org/apache/camel/spring/RoutePreconditionTest.java, components/camel-spring-xml/src/test/resources/org/apache/camel/spring/RoutePreconditionTest.properties, components/camel-spring-xml/src/test/resources/org/apache/camel/spring/RoutePreconditionTest.xml, core/camel-core-engine/src/main/java/org/apache/camel/impl/DefaultCamelContext.java, core/camel-core-model/src/main/java/org/apache/camel/model/RouteDefinition.java, core/camel-core-model/src/main/java/org/apache/camel/model/RouteTemplateDefinition.java, core/camel-core/src/test/java/org/apache/camel/builder/RouteTemplatePreconditionTest.java, core/camel-core/src/test/java/org/apache/camel/processor/RoutePreconditionTest.java, core/camel-xml-io/src/generated/java/org/apache/camel/xml/in/ModelParser.java, docs/user-manual/modules/ROOT/pages/routes.adoc, dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/RouteDefinitionDeserializer.java, dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/camel-yaml-dsl.json, dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/camelYamlDsl.json, dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/RoutesTest.groovy
Fix for https://issues.apache.org/jira/browse/CAMEL-17555
To make route templates (aka kamelets) more flexible it can benefit that we allow to declare routes whether they should be included or excluded. This allows to parameterize these routes and therefore only include them if the template has a parameter included for this.
* Add a new parameter called `precondition` allowing to provide a predicate in Simple language to evaluate in order to know if a given route should be excluded or not.
* Remove the definition of the route if the `precondition` fails
=> CAMEL-17555: Flag to include/exclude routes in route templates

catalog/camel-catalog/pom.xml, core/camel-core-all/pom.xml, core/pom.xml
Fix for https://issues.apache.org/jira/browse/CAMEL-17759
There is a race condition in the parallel build that could cause inconsistencies in the catalog.
* Add a new artifact that depends on all core artifacts called `camel-core-all`
* Add a dependency to `camel-core-all` in `camel-catalog` to ensure that the catalog won't be generated before some core artifacts like the console.
=> CAMEL-17759: Prevent inconsistencies in the catalog due to the parallel build

camel-dependencies/pom.xml, parent/pom.xml, tooling/maven/camel-component-maven-plugin/pom.xml, tooling/parent/pom.xml
Fix for https://issues.apache.org/jira/browse/CAMEL-17320
Upgrading `maven-plugin-plugin` add warnings in the log of the build due to the scope of Maven dependencies that must always be `provided`
* Upgrade `maven-plugin-plugin` and `maven-plugin-annotations` to the latest existing version which is `3.6.4`
* Set the scope of the Maven dependencies to `provided` directly into the dependency management section to have it fix globally in one file
* Add missing dependencies in `camel-component-maven-plugin` to avoid compilation failures
* Add some Maven dependencies to the dependency management section to enforce the scope to `provided` that were initially transitive dependencies
The log of the build doesn't contain anymore warning messages complaining about the scope of Maven dependencies
=> CAMEL-17320: Upgrade maven-plugin-plugin to 3.6.4

components/camel-cm-sms/src/main/java/org/apache/camel/component/cm/CMConstants.java, components/camel-cm-sms/src/main/java/org/apache/camel/component/cm/CMSenderOneMessageImpl.java, components/camel-cm-sms/src/test/java/org/apache/camel/component/cm/test/CMTest.java
Issue: https://issues.apache.org/jira/browse/CAMEL-17768
=> CAMEL-17768 Camel-cm-sms: Handle changed error message correctly

components/camel-zipfile/src/main/java/org/apache/camel/dataformat/zipfile/ZipIterator.java
This PR is to add a check for null during `ZipIterator` creation which will prevent the assignment of a `new ZipInputStream(new BufferedInputStream(inputStream))` to `zipInputStream` variable. 
Such case may occur when a message is converted to `InputStream` but no `TypeConverter` is present (e.g in `ZipSplitter`)
=> CAMEL-17774 Added check for null inputStream

core/camel-api/src/generated/java/org/apache/camel/spi/Metadata.java, tooling/maven/camel-package-maven-plugin/pom.xml, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojo.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojoTest.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/endpoint/SomeEndpointWithFilter.java, tooling/spi-annotations/src/main/java/org/apache/camel/spi/Metadata.java
Fix for https://issues.apache.org/jira/browse/CAMEL-16628 (part 2)
Some Constants class are shared with several endpoints, we need a mechanism allowing to filter the message headers by endpoint's scheme.
* Add the new element `applicableFor` to `@Metadata` to provide the list of schemes for which the metadata is applicable.
* Enable the IT as the plugin updates have been published (not related to this need)
=> CAMEL-16628: Add applicableFor to Metadata to filter header by scheme

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojo.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojoTest.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/endpoint/SomeEndpointUsingEnumConstants.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/endpoint/SomeEnumConstants.java
Fix for https://issues.apache.org/jira/browse/CAMEL-16628 (part 3)
There are components that define their constants in an enum so it should be supported too.
* Check if the header class is an enum and if so accept any field annotated with `@Metadata`
* Use the name of the field as header name in case of an enum
=> CAMEL-16628: Allow to define headers in an enum

components/camel-validator/src/main/java/org/apache/camel/component/validator/DefaultLSResourceResolver.java, core/camel-core/src/test/java/org/apache/camel/ValidatorExternalResourceTest.java, core/camel-core/src/test/resources/org/apache/camel/component/validator/xsds/customer.xsd, core/camel-core/src/test/resources/org/apache/camel/component/validator/xsds/order.xsd, core/camel-core/src/test/resources/org/apache/camel/component/validator/xsds/product.xsd
In order to reproduce this issue I had to expose xsd from my github https://raw.githubusercontent.com/Croway/test-xsd/main/chapter04ord1.xsd I don't know if it is worth to move those xsd's into camel-validator resource folder and reference those, in case I'll update this PR.
@luigidemasi
=> [CAMEL-17857] camel-validator: remote xsd import

components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpConsumer.java, components/camel-platform-http-vertx/src/test/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpEngineTest.java
It might be another option to add a [CorsHandler](https://github.com/vert-x3/vertx-web/blob/master/vertx-web/src/main/java/io/vertx/ext/web/handler/impl/CorsHandlerImpl.java) from vertx-web. But it looks like a little different with the camel [RestBindingAdvice::setCORSHeader](https://github.com/apache/camel/blob/main/core/camel-core-processor/src/main/java/org/apache/camel/processor/RestBindingAdvice.java#L518). My current fix is a trick to bypass [the consumes checking when body is empty](https://github.com/vert-x3/vertx-web/blob/master/vertx-web/src/main/java/io/vertx/ext/web/impl/RouteState.java#L1025).
=> CAMEL-17865: camel-platform-http-vertx - Fix CORS conflict in Camel REST

components/camel-google/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubConsumer.java
As described in [CAMEL-17871](https://issues.apache.org/jira/browse/CAMEL-17871), this PR allows for gracefully cancelling synchronous pull Google PubSub consumers.
=> [CAMEL-17871] Google Pubsub -  Graceful shutdown for synchronous pull consumers

docs/user-manual/modules/ROOT/pages/testing.adoc
The links to the new JUnit5 modules were commented as Camel 3.16 was not yet release otherwise the website build fail. As Camel 3.16 has been, we can now put them back.
* Uncomment new links
* Remove old links
=> Add the new links to JUnit5 modules as released

components/camel-sql/src/main/java/org/apache/camel/component/sql/SqlProducer.java, components/camel-sql/src/test/java/org/apache/camel/component/sql/CamelSqlEmptyResultTest.java, components/camel-sql/src/test/java/org/apache/camel/component/sql/SqlGeneratedKeysInLoopTest.java
CamelSqlGeneratedKeyRows is not populated if already exists because input
headers were overwriting the new output header.
Change code to set headers on input message instead of using deprecated
getOut() method. Ensure that input body is set to null in case of EMPTY_RESULT
on SelectOne queries.
=> CAMEL-17866: fix CamelSqlGeneratedKeyRows issue.

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojo.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojoTest.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/endpoint/SomeEndpointWithJavadocAsDescription.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/endpoint/SomeEnumConstants.java
Fix for https://issues.apache.org/jira/browse/CAMEL-17896
There are components that describe already their headers in the Javadoc so it could be interesting to be able to extract the Javadoc of those header and use it as description of the header instead of duplicating the description.
* Adapt the code to be able to parse not only `JavaClassSource` but `JavaSource` to be able to support enumerations too. 
* Add a new method called `getHeaderFieldJavadoc` to extract the Javadoc from a field in case of a class or interface or an Enum constant in case of an enum
=> CAMEL-17896: Extract the description of an header from the Javadoc by default

components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQDeclareSupport.java, components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQEndpoint.java, components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/integration/RabbitMQProducerIT.java
Force passive declaration before binding pre-existing queue and exchange.
Will only be applied when skipQueueBind=false and the other skip declarations are set to true
Issue tracker: https://issues.apache.org/jira/browse/CAMEL-17892
=> CAMEL-17892: perform binding even when declarations were skipped

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojo.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojoTest.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/endpoint/SomeCommonConstants.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/endpoint/SomeEndpointUsingInterfaceConstants.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/endpoint/SomeEndpointWithHeaderClassHierarchy.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/endpoint/SomeEndpointWithHeaderInterfaceHierarchy.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/endpoint/SomeInterfaceConstants.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/endpoint/SomeInterfaceWithCommonConstants.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/endpoint/SomeInterfaceWithSpecificConstants.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/endpoint/SomeSpecificConstants.java
Fix for https://issues.apache.org/jira/browse/CAMEL-17898
Some components define their common headers in base class and the specific headers in specific classes that extend the base class. So we need to make evolve the code extracting the metadata of the headers in order to retrieve header definitions from the super classes and implemented interfaces too.
* Retrieve the header definitions in a loop that iterates over all the super classes until `Object.class` and all the implemented interfaces
=> CAMEL-17898: Allow to retrieve header definitions from super classes

components/camel-mail/src/main/docs/mail-component.adoc
Missing sample code restored from Wayback Machine <https://web.archive.org/web/20160818235148/http://camel.apache.org:80/mail.html>
=> CAMEL-17917 Add missing sample code to camel-mail docs

core/camel-api/src/generated/java/org/apache/camel/spi/UriEndpoint.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojo.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojoTest.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/endpoint/SomeEndpointUsingEnumConstantsByField.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/endpoint/SomeEndpointUsingEnumConstantsByMethod.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/endpoint/SomeEnumConstantsByField.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/endpoint/SomeEnumConstantsByMethod.java, tooling/spi-annotations/src/main/java/org/apache/camel/spi/UriEndpoint.java
Fix for https://issues.apache.org/jira/browse/CAMEL-17918
When the headers class is an enum, so far the name of the headers can only be the name of the values of the enum which is not enough in some particular use cases. The idea of this improvement is to be able to provide the name of the field or method to invoke in order to get the name of the corresponding header.
* Add a new element called `headersNameProvider` to the annotation `UriEndpoint` in order to be able to provide the name of the field to get or the name of the method to invoke to get the name of the header
* Add a dedicated method allowing to get the name of an header from a field.
=> CAMEL-17918: Define the header name provider in case the headers class is an enum

components/camel-web3j/src/main/java/org/apache/camel/component/web3j/Web3jProducer.java
Fix for https://issues.apache.org/jira/browse/CAMEL-17922
The default value supplier of the header MIX_DIGEST is the value of the option headerPowHash while we would rather expect mixDigest.
* Set the proper method name as default value supplier
=> CAMEL-17922: Fix default value supplier for header MIX_DIGEST

core/camel-api/src/generated/java/org/apache/camel/spi/UriEndpoint.java, docs/components/modules/ROOT/examples/js/camel.js, docs/components/modules/ROOT/partials/component-endpoint-headers.adoc, tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/ComponentModel.java, tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/JsonMapper.java, tooling/camel-tooling-model/src/test/java/org/apache/camel/tooling/model/JsonMapperTest.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojo.java, tooling/maven/camel-package-maven-plugin/src/test/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojoTest.java, tooling/spi-annotations/src/main/java/org/apache/camel/spi/UriEndpoint.java
Fix for https://issues.apache.org/jira/browse/CAMEL-17923
In the documentation of an header only the name of the header is provided but the good practice is to use the related constant instead of using a string directly, so we should rather propose the name of the constant that holds the name of the header to avoid typos and to ease potential future renaming.
* Add the field `constantName` to the model of the header that will contain the name of the header in the next formats:
* In case of an interface or a class: `${declaring-class-name}#${constant-name}`
* In case of an enum and `headersNameProvider` is set to a name of field: `${declaring-class-name}#${enum-constant-name}@${field-name}`
* In case of an enum and `headersNameProvider` is set to a name of method: …
=> CAMEL-17923: Add the name of the constant to the header model

components/camel-mock/src/main/java/org/apache/camel/component/mock/MockEndpoint.java
Fix for https://issues.apache.org/jira/browse/CAMEL-17948
While working on [CAMEL-17945](https://issues.apache.org/jira/browse/CAMEL-17945), I realized that the tests with the scope PER_CLASS leveraging the MockEndpoint to define their assertions can fail randomly because of a race condition issue. Indeed, with the current code, a message of a previous test method can potentially call the method countDown on the latch of the following test method causing unexpected behavior.
* When at least one message is expected, always wait until the latch is released to prevent conflicts of messages of different test methods
* Convert the counter to an `AtomicInteger` to guarantee the rest of an increment
* Use a fixed value of the counter when getting the `Processor` to avoid potential race condition …
=> CAMEL-17948: Force waiting before checking the asserts of the mock

docs/components/modules/ROOT/examples/js/camel.js, docs/gulpfile.js
Fix for https://issues.apache.org/jira/browse/CAMEL-17961
The build of the website fails due to a missing JS file that has actually been removed by the Regen for commit https://github.com/apache/camel/commit/23c90548a3d1386176c59d7489c94c4b1506e291 when executing the gulpfile script.
* Re-add the JS file
* Add `js` as type of file to keep by the gulpfile script
=> CAMEL-17961: Re-add the JS file for the documentation

components/camel-hazelcast/src/test/java/org/apache/camel/component/hazelcast/HazelcastQueueConsumerPollTest.java, components/camel-hazelcast/src/test/java/org/apache/camel/component/hazelcast/HazelcastQueueConsumerTest.java
Fix for https://issues.apache.org/jira/browse/CAMEL-17952
The tests `HazelcastQueueConsumerPollTest` and `HazelcastQueueConsumerTest` fail on Github when the quick test is launched against the Hazelcast component
* `HazelcastQueueConsumerPollTest`: As no message is expected set `sleepForEmptyTest` to 2 seconds as it is the timeout used in this case
* `HazelcastQueueConsumerTest`: Get rid of the argument capture as it must be defined sooner to avoid the race condition issue causing the test failure
=> CAMEL-17952: Fix Hazelcast unstable tests

components/camel-ahc-ws/src/test/java/org/apache/camel/component/ahc/ws/WsProducerConsumerTest.java
https://issues.apache.org/jira/browse/CAMEL-17948 (regression in test)
The changes made in https://github.com/apache/camel/pull/7430 caused a regression in `WsProducerConsumerTest` that needs to be fixed
* Reset the mocks directly after the assertion checks to avoid race conditions issues in the rest of the test
=> CAMEL-17948: Fix regression in WsProducerConsumerTest

tooling/openapi-rest-dsl-generator/src/main/java/org/apache/camel/generator/openapi/RestDslYamlGenerator.java, tooling/openapi-rest-dsl-generator/src/test/resources/OpenApiV3PetstoreSimpleYaml.txt, tooling/openapi-rest-dsl-generator/src/test/resources/OpenApiV3PetstoreWithRestComponentYaml.txt, tooling/openapi-rest-dsl-generator/src/test/resources/OpenApiV3PetstoreYaml.txt
Fix for https://issues.apache.org/jira/browse/CAMEL-17989
=> Fix CAMEL-17989

core/camel-support/src/main/java/org/apache/camel/converter/stream/FileInputStreamCache.java
[CAMEL-17990] added missing java 8 InputStream delegates for readxxx  methods, mark and reset logic left out on purpose because of the existing StreamCache behaviour
=> [CAMEL-17990] missing InputStream delegates for 3.14.x

core/camel-support/src/main/java/org/apache/camel/converter/stream/FileInputStreamCache.java
[CAMEL-17990] added missing java 11 InputStream delegates for readxxx and transferTo methods, mark and reset logic left out on purpose because of the existing StreamCache behaviour
=> [CAMEL-17990] implement Java 8 and java 11 missing InputStream delegates

.github/workflows/master-pr-build.yml, CONTRIBUTING.md, components/pom.xml, core/pom.xml, docs/user-manual/modules/ROOT/pages/building.adoc, dsl/camel-componentdsl/pom.xml, dsl/camel-endpointdsl/pom.xml, dsl/pom.xml, parent/pom.xml, test-infra/pom.xml, tests/pom.xml, tooling/pom.xml
Folks, I'd like to hear your opinions about this rather disruptive
change. 
The motivation for removing those 2 plugins from the default build
execution is because they are very slow. On my test machine, this
reduces the build time by between 3 to 4 minutes with "normal Maven"
(roughly 7.6% improvement). The numbers with Maven Daemon are not so 
dramatic, but still reduces a bit (varying a lot here, but roughly
between 20 to 60 seconds). 
The (possible) downside is that this stops the code from automatically
reformatting the code and sorting the imports by default (ie.: when
running `mvn -Pfastinstall install`). 
Instead, this introduces a new profile `format` that can be run
along side the `fastinstall` to do the same. 
Because this can be disruptive to the workflow of others, I'd like …
=> CAMEL-17894: stop running impsort and checkstyle by default

init/camel-bundle-plugin/pom.xml
Fix for https://issues.apache.org/jira/browse/CAMEL-17864
The scope of some dependencies of the plugin camel-bundle-plugin should be `provided` instead of `compile` which causes an error message in the build log that should be fixed.
* Forces the scope of the problematic dependencies by adding them explicitly as dependencies of the plugin
The error message is absent from the build log
=> CAMEL-17864: Fix the scope of the deps of the camel-bundle-plugin

docs/user-manual/modules/ROOT/pages/advice-with.adoc
Fixes errors as seen [here](https://camel.apache.org/manual/advice-with.html#_replacing_route_endpoints)
=> Doc fix: Update code examples to correctly use advice argument 

components/camel-grpc/pom.xml
Fix for https://issues.apache.org/jira/browse/CAMEL-17832
The Grpc component doesn't work with Netty 4.1.75.
* Don't force anymore the version of Netty to `4.1.72.Final` in order to use `4.1.76.Final` instead as it works properly with it
=> CAMEL-17832: camel-grpc - Upgrade to Netty 4.1.76

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumerHealthCheck.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/TaskHealthState.java
=> CAMEL-18019: ensure some fields in the Kafka record fetcher are safe for concurrent read

camel-dependencies/pom.xml, components/camel-djl/src/test/java/org/apache/camel/component/djl/training/MnistTraining.java, parent/pom.xml
Fix for https://issues.apache.org/jira/browse/CAMEL-17537
There is newer version of deep learning, we should upgrade
* Upgrade the version of djl in all the related pom files
* Call `Engine` instead of `Device` as stated in [the release note of the 0.13.0](https://github.com/deepjavalibrary/djl/releases/tag/v0.13.0)
* Remove the unused logger (not related to the current issue)
=> CAMEL-17537: camel-djl - Upgrade to 0.16.0

camel-dependencies/pom.xml, parent/pom.xml
Fix for https://issues.apache.org/jira/browse/CAMEL-18000
osgi should work again with this release
* Upgrade the version of johnzon in all the related pom files
=> CAMEL-18000: camel-johnzon - Upgrade to 1.2.17

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelJBangMain.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/PropertiesHelper.java
https://issues.apache.org/jira/browse/CAMEL-18023
=> CAMEL-18023. camel-jbang command options from application.properties

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/AbstractCommitManager.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/AsyncCommitManager.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/CommitManager.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/CommitToOffsetManager.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/DefaultKafkaManualAsyncCommit.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/DefaultKafkaManualAsyncCommitFactory.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/DefaultKafkaManualCommit.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/DefaultKafkaManualCommitFactory.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/DefaultKafkaManualSyncCommit.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/KafkaAsyncManualCommit.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/KafkaManualCommitFactory.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/NoopCommitManager.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/OffsetCache.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/SyncCommitManager.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/KafkaRecordProcessor.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/KafkaRecordProcessorFacade.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/PartitionAssignmentListener.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/consumer/OffsetCacheTest.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/pause/KafkaPausableConsumerIT.java, docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_17.adoc
=> CAMEL-18024: rework the last processed offset tracking

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/errorhandler/KafkaErrorStrategies.java
=> CAMEL-18020: fix a possible NPE due to uninitialized consumer in poll exception strategies

components/camel-salesforce/camel-salesforce-maven-plugin/src/main/resources/sobject-pojo.vm
MultiSelectPicklistConverter does not exist anymore. But generated DTOs still import it and cause an error.
=> Remove non-exist MultiSelectPicklistConverter

components/camel-atom/src/main/java/org/apache/camel/component/atom/UpdatedDateFilter.java, components/camel-irc/src/main/java/org/apache/camel/component/irc/IrcConfiguration.java
=> (chores) code cleanup: remove unused private methods in components

components/camel-openapi-java/src/main/java/org/apache/camel/openapi/RestModelConverters.java, components/camel-openapi-java/src/test/java/org/apache/camel/openapi/RestOpenApiV3XOfTest.java, components/camel-openapi-java/src/test/java/org/apache/camel/openapi/model/AllOfForm.java, components/camel-openapi-java/src/test/java/org/apache/camel/openapi/model/AllOfFormWrapper.java, components/camel-openapi-java/src/test/java/org/apache/camel/openapi/model/AnyOfForm.java, components/camel-openapi-java/src/test/java/org/apache/camel/openapi/model/AnyOfFormWrapper.java, components/camel-openapi-java/src/test/java/org/apache/camel/openapi/model/OneOfForm.java, components/camel-openapi-java/src/test/java/org/apache/camel/openapi/model/OneOfFormWrapper.java, components/camel-openapi-java/src/test/java/org/apache/camel/openapi/model/XOfFormA.java, components/camel-openapi-java/src/test/java/org/apache/camel/openapi/model/XOfFormB.java
Added support for oneOf, anyOf and allOf OpenAPI annotations for Rest OpenApi spec generation
OpenAPI specification reference:
https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not
=> CAMEL-18040 Added support for oneOf, anyOf and allOf OpenAPI annotations for Rest OpenApi spec generation

components/camel-azure/camel-azure-storage-blob/src/main/java/org/apache/camel/component/azure/storage/blob/BlobUtils.java
CAMEL-17861: adapt method to determine size of stream
the old version loaded the entire bytestream into memory to determine its length
new implementation is copied from: 
https://github.com/apache/camel/blob/abb1ad84fac520b00339533a2eafdeb901e22d87/components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/utils/AWS2S3Utils.java#L83
=> CAMEL-17861

dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/RouteConfigurationTest.groovy
I just realized there is no test checking the on-completion part on yaml dsl, so I added this small piece to the existing tests.
=> test(dsl): Adding on-completion test for camel yaml dsl

components/camel-kafka/src/main/docs/kafka-component.adoc
=> Add doc for kafka transaction

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelJBangMain.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Profile.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/PropertiesHelper.java
`camel@apache/camel package uber-jar` by default uses `application.properties`
`camel@apache/camel package uber-jar --profile dev` uses `dev.properties`
`camel@apache/camel package uber-jar --profile test` uses `test.properties` 
`camel@apache/camel package uber-jar --profile prod` uses `prod.properties` 
filename=profile
=> camel-jbang. profile option for *.properties

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerAsyncManualCommitIT.java
Reading this comment [1] I noticed this test has been marked as
disabled, but it has been running well on my own CI. 
Re-enabling it for checking on Apache CI.
1. https://github.com/apache/camel/pull/7518#issuecomment-1128825463
=> (chores) camel-kafka: re-enable async manual test

core/camel-core-languages/src/main/java/org/apache/camel/language/simple/SimpleExpressionBuilder.java, core/camel-core/src/test/java/org/apache/camel/language/simple/SimpleTest.java, core/camel-core/src/test/java/org/apache/camel/language/simple/myconverter/MyCustomDate.java, core/camel-core/src/test/java/org/apache/camel/language/simple/myconverter/MyCustomDateConverter.java, core/camel-core/src/test/resources/META-INF/services/org/apache/camel/TypeConverter
Here's the pull request fixing https://issues.apache.org/jira/browse/CAMEL-18119
FYI, I have the following error when running sourcecheck, I have not idea what's wrong with my formatting.
```
File 'camel\core\camel-core\src\test\java\org\apache\camel\language\simple\myconverter\MyCustomDate.java' has not been previously formatted.  Please format file and commit before running validation!
```
Thank you
=> [CAMEL-18119] Allow Simple expressions to render any Object that can be converted to Date

components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Producer.java, components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/AmazonSQSClientMock.java, components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/SqsProducerDeleteQueueTest.java, components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/SqsProducerPurgeTest.java
Issue: https://issues.apache.org/jira/browse/CAMEL-18123
Cherry-picked: 93e1af09397f89b5adb399df7803e0ccd3002eae
=> CAMEL-18123 Aws2-sqs: Operations Purge and Delete requires header

camel-dependencies/pom.xml, components/camel-google/camel-google-calendar/pom.xml, components/camel-google/camel-google-drive/pom.xml, components/camel-google/camel-google-mail/pom.xml, components/camel-google/camel-google-sheets/pom.xml, components/camel-jira/pom.xml, parent/pom.xml
- Upgrading google-oauth-client to 1.33.3
- add a new property to represent google-oauth-client - unfortunately, there's no 1.33.3 version for com.google.api-client:google-api-client, so we need to use a different version than google-api-client-version
=> Upgrade google-oauth-client to 1.33.3

.github/workflows/alternative-os-build.yml
A user in the community reported to me about a build error when trying
to build Camel on Windows. Since we don't have that on the CI nor it
seems to be widely used in the community, I added this weekly build to
build Camel on Windows and Mac once a week.
=> (chores) ci: added support for building Camel on alternative OSes

components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/CamelTestSupport.java, components/camel-test/camel-test-junit5/src/test/java/org/apache/camel/test/junit5/CamelTestSupporOneContextForAllTest.java
fixes https://issues.apache.org/jira/browse/CAMEL-18201
This PR adds an option to turn  off the context stopping. It is possible by junit5's `ConfigurationProperty` (which falls back also to system variable - used in the junit test). If context does not stop automatically method `doSetUp` is not called if context already exists.
I added 2 tests to cover both option values (off and on).
=> CAMEL-18201 Enhance CamelTestSupport to turn off context stopping

components/camel-knative/camel-knative-component/src/main/java/org/apache/camel/component/knative/KnativeEndpoint.java, components/camel-knative/camel-knative-component/src/test/java/org/apache/camel/component/knative/KnativeComponentTest.java, components/camel-knative/camel-knative-component/src/test/resources/environment.json, components/camel-knative/camel-knative-component/src/test/resources/environment_classic.json
* Only use the configuration name when endpoint.kind=sink
* Log a debug message when using a "default" knative resource name
* Set a "default" name when there is no name
* [camel k PR #3373](https://github.com/apache/camel-k/pull/3373) depends on this fix
=> Fix camel-knative endpoint for events

camel-dependencies/pom.xml, parent/pom.xml
There is no support for Kotlin 1.7.x in Camel Quarkus yet & I couldn't find any workaround to make things work. Hence reverting the upgrade until there is support for 1.7.
=> Revert "CAMEL-18203: Upgrade to Kotlin 1.7.0"

components/camel-test/camel-test-main-junit5/src/main/docs/test-main-junit5.adoc, components/camel-test/camel-test-main-junit5/src/main/java/org/apache/camel/test/main/junit5/CamelMainExtension.java, components/camel-test/camel-test-main-junit5/src/main/java/org/apache/camel/test/main/junit5/CamelMainTest.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/annotation/WithUseJMXTest.java, components/camel-test/camel-test-main-junit5/src/test/java/org/apache/camel/test/main/junit5/legacy/WithUseJMXTest.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultChannel.java
Fix for https://issues.apache.org/jira/browse/CAMEL-18214
When enabling the [test debugger](https://camel.apache.org/manual/debugger.html#_debugging_camel_routes) by using the isUseDebugger in test, the [BacklogDebugger](https://camel.apache.org/manual/backlog-debugger.html) is no more available. it would be nice to have both that can work at the same time.
* Modifies the logic in `DefaultChannel#initChannel` to be able to accept the 2 debuggers if they can be found.
* Add the ability to enable JMX in `camel-test-main-junit5` as it was not yet possible and is needed to be able to use the `BacklogDebugger`
Tested with success with `camel-test-junit5`, `camel-test-main-junit5` and `camel-test-spring-junit5` but should work with all test components but CDI
=> CAMEL-18214: Allow Backlog Debugger and test debugger to work at the same time

components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/CamelTestSupport.java, components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/TestSupport.java, components/camel-test/camel-test-main-junit5/src/main/java/org/apache/camel/test/main/junit5/CamelMainExtension.java, components/camel-test/camel-test-spring-junit5/src/main/java/org/apache/camel/test/spring/junit5/CamelAnnotationsHandler.java
Fix for https://issues.apache.org/jira/browse/CAMEL-18215
When `camel-debug` is on the classpath, the intent is to use the `Camel Backlog Debugger` which is based on JMX.
It would be nice in tests that we do not need to override the method `useJmx` as it is implicitly needed by `camel-debug`.
* Adds the method `isCamelDebugPresent` to the utility class `CamelTestSupport` to detect `camel-debug` before initializing the Camel context.
* Calls this new method in all Camel test JUnit 5 components to automatically enable JMX when `camel-debug` is detected
Tested with success with `camel-test-junit5`, `camel-test-main-junit5` and `camel-test-spring-junit5`. Won't work with all Camel test JUnit 4 components.
=> CAMEL-18215: camel-test - Enable JMX when camel-debug is detected

core/camel-base-engine/src/main/java/org/apache/camel/impl/debugger/BacklogDebugger.java, core/camel-management/src/test/java/org/apache/camel/management/BacklogDebuggerTest.java, docs/user-manual/modules/ROOT/pages/debugger.adoc
Fix for https://issues.apache.org/jira/browse/CAMEL-18217 (part 2)
What has been done in the first part of this feature is good but for the sake of simplicity it is also interesting to have the ability to configure it using a System property.
* Allow to use the system property `org.apache.camel.debugger.suspend` to configure the `suspend mode`
* Ensure that the environment variable takes precedence over the system property
* Add the corresponding test and doc.
* Remove the log message that was for debugging purpose
It is now possible to configure the `suspend mode` using the system property `org.apache.camel.debugger.suspend`.
=> CAMEL-18217: debugger - Allow to suspend messages using a system property

catalog/camel-catalog-maven/src/main/java/org/apache/camel/catalog/maven/DefaultMavenArtifactProvider.java, catalog/camel-catalog-maven/src/main/java/org/apache/camel/catalog/maven/MavenVersionManager.java, tests/camel-itest-cdi/src/main/java/org/apache/camel/itest/cdi/MyRoutes.java
=> (chores) improve differentiation of unrelated logging variables

tooling/maven/camel-maven-plugin/src/main/docs/camel-maven-plugin.adoc, tooling/maven/camel-maven-plugin/src/main/java/org/apache/camel/maven/DebugMojo.java, tooling/maven/camel-maven-plugin/src/main/java/org/apache/camel/maven/RunMojo.java
Fix for https://issues.apache.org/jira/browse/CAMEL-18223
The textual route Debugger has several requirements to make it work properly thus it could be interesting to propose a new maven goal to the camel plugin to set up everything automatically. 
* Add `DebugMojo` for the goal `debug` to add `camel-debug` to the classpath automatically, to enable JMX and to configure the suspend mode
* Rewrite `RunMojo` to have access to all the artifacts that we have in the classpath in order to easily detect `camel-debug` and retrieve the Camel version.
Launching an application with `mvn camel:debug` is enough to debug Camel routes. Tested successfully with https://github.com/apache/camel-examples/tree/main/examples/main
=> CAMEL-18223: camel-plugin - Propose a goal to debug with the textual route debugger

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/ComponentDslMojo.java
Running ComponentDslMojo programmatically outside of camel-package-maven-plugin is difficult because of how jsonDir is being set.     Need to check if jsonDir is null, camelDirectory() provides a mechanism for discovering it if it is not set correctly.
=> Try to discover the jsonDir if it is null

catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/ValidateMojo.java
=> (chores) camel-report-maven-plugin: remove duplicated code for building error messages

core/camel-core-model/src/main/java/org/apache/camel/model/ResequenceDefinition.java
Resequence definition must use precise time definition, otherwise the
milliseconds get rounded to zero which causes tests such as the ones
in ResequenceStreamNotIgnoreInvalidExchangesTest to fail.
Ref: cf65ab21dbe3cfa598fcb83e7397c5c39718b3a4
----
This should fix some of our CI issues with the resequencer tests.
=> CAMEL-18237: fix incorrect round-to-zero

core/camel-base-engine/src/main/java/org/apache/camel/impl/debugger/BacklogDebugger.java, core/camel-management/src/test/java/org/apache/camel/management/BacklogDebuggerTest.java
fixes https://issues.apache.org/jira/browse/CAMEL-18260
While investigating on https://github.com/camel-tooling/camel-idea-plugin/issues/734, I realized that is was actually due to the fact that when a change is made on an exchange, the corresponding backlog tracer event message is not modified such that the change is not reflected in the debugger variables. 
* Adds the new method `refreshBacklogTracerEventMessage` to refresh the content of the message when the exchange is modified
* Fixes warnings raised by IntelliJ (not related to the issue)
The changes are reflected directly on the `BacklogTracerEventMessage` as we can see in the screenshot below:
=> CAMEL-18260: debugger - Reflect exchange changes on BacklogTracerEventMessage

core/camel-management/pom.xml
Fix for https://issues.apache.org/jira/browse/CAMEL-18263
The tests `testSuspendModeConfiguredWithBoth` and `testSuspendModeConfiguredWithEnvVariable` of `BacklogDebuggerTest` are both failing on Java 17 as we can see here https://ci-builds.apache.org/job/Camel/job/Camel%20JDK16/job/main/334/testReport/junit/org.apache.camel.management/
* Adds a new maven profile enabled on Java 17+ to open the required packages
=> CAMEL-18263: Fix tests of BacklogDebuggerTest failing on Java 17

tooling/maven/camel-restdsl-openapi-plugin/src/main/docs/camel-restdsl-openapi-plugin.adoc
Typo fixed in table, inconsistent number of columns.
=> Update camel-restdsl-openapi-plugin.adoc to fix an inconsistent number of columns.

components/camel-test/camel-test-spring-junit5/src/test/java/org/apache/camel/test/issues/AdviceWithOnExceptionTransacted.java, components/camel-test/camel-test-spring-junit5/src/test/resources/org/apache/camel/test/issues/AdviceWithOnExceptionTransacted.xml, core/camel-core-model/src/main/java/org/apache/camel/builder/AdviceWithTasks.java
If node parent is of type RouteDefinition and every output is abstract, then use last output for further advice processing.
=> CAMEL-18278: Get outputs from last abstract parent

dsl/camel-endpointdsl/pom.xml
The hadoop-common dependency causes the code to instantiate a different
Logger type which, leads to an invalid evaluation of the log level. This
causes the exchange formatter to not run which causes the test to fail.
This was introduced by upgrading hadoop libraries in 7fdf3ac65fb8d57682a565b9f31a03d046a182e0
=> (chores) ci: fixes invalid log instantiation

core/camel-api/src/main/java/org/apache/camel/spi/SynchronizationVetoable.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultUnitOfWork.java, core/camel-core-processor/src/main/java/org/apache/camel/processor/OnCompletionProcessor.java, core/camel-support/src/main/java/org/apache/camel/support/SynchronizationAdapter.java
When synchronizations are handed over, add a method to allow some housekeeping
to be performed. In the OnCompletionProcessor.OnCompletionSynchronizationAfterConsumer
this method stores the routeId on the Exchange.
=> CAMEL-18275: Address issue of completions not being run in SEDA pipeline

components/camel-jetty/src/test/java/org/apache/camel/component/jetty/ExcludeCipherSuitesTest.java, components/camel-jetty/src/test/java/org/apache/camel/component/jetty/ExplicitHttpsSslContextParametersRouteTest.java, components/camel-jetty/src/test/java/org/apache/camel/component/jetty/HttpsAsyncRouteTest.java, components/camel-jetty/src/test/java/org/apache/camel/component/jetty/HttpsRouteAddSslConnectorPropertiesTest.java, components/camel-jetty/src/test/java/org/apache/camel/component/jetty/HttpsRouteSetupWithSystemPropsTest.java, components/camel-jetty/src/test/java/org/apache/camel/component/jetty/HttpsRouteTest.java, components/camel-jetty/src/test/java/org/apache/camel/component/jetty/HttpsRouteWithSslConnectorPropertiesTest.java, components/camel-jetty/src/test/java/org/apache/camel/component/jetty/SpringHttpsRouteTest.java, components/camel-jetty/src/test/java/org/apache/camel/component/jetty/TwoCamelContextWithJettyRouteTest.java
Some of junit-tests in component camel-jetty are broken. In this PR their functionality is restored.
Note: these unit-tests will be very helpful for some big changes like [Migration to Jakarta EE ](https://github.com/apache/camel/pull/7116).
=> Errors in Unit-tests for camel-jetty component are solved

core/camel-core/src/test/java/org/apache/camel/language/XPathRouteConcurrentBigTest.java
fixes https://issues.apache.org/jira/browse/CAMEL-18349
Another approach would be to change the limit for the security property via System.properties. 
Current change seems to be simpler and doesn't change the functionality of the test.
=> CAMEL-18349 Lower the count of XPath operators for XPathRouteConcurrentBigTest.

camel-dependencies/pom.xml, components/camel-google/camel-google-pubsub/pom.xml, parent/pom.xml
Fix for https://issues.apache.org/jira/browse/CAMEL-18344
To be able to re-include the feature `camel-google-pubsub` in camel-karaf, I would need to make the bundle more flexible by opening the version of guava
* Indicates a starting version of google guava to allow more recent versions that are also compatible
=> CAMEL-18344: camel-google-pubsub - Open guava version for OSGI bundle

components/camel-knative/camel-knative-http/pom.xml
backporting https://github.com/apache/camel/pull/8204 for 3.18.x
=> Upgrade vert.x Web Client version for knative component (#8204)

camel-dependencies/pom.xml, parent/pom.xml, pom.xml
I think Camel is affected by SUREFIRE-2096 (and, maybe, the related
issues mentioned on the ticket), causing longer test run times and the
fork timeout issues.
=> Revert surefire + failsafe updates

components/camel-aws/camel-aws2-s3/src/test/java/org/apache/camel/component/aws2/s3/integration/S3MultipartUploadOperationIT.java
Small change to prevent IDEs from indexing binary files, making it
slower to use them. Also remove one unused test file from minio for the
same purpose.
=> (chores) rename or remove to prevent indexing

buildingtools/src/main/resources/notice-supplements.xml, components/camel-cxf/camel-cxf-common/src/main/java/org/apache/camel/component/cxf/converter/CachedCxfPayload.java, components/camel-spring-ws/src/main/java/org/apache/camel/component/spring/ws/SpringWebserviceHelper.java, core/camel-core/src/test/java/org/apache/camel/builder/xml/XPathTest.java, core/camel-xml-jaxp/src/main/java/org/apache/camel/converter/jaxp/XmlConverter.java
https://github.com/apache/camel/compare/main...cunningt:camel:morexalanremoval?expand=1#diff-a45e30e0e6a08fbf84385cefeb5061c392f999feb13cb1d0aefb49b2eeadfad0 : I think the xalan entry can be removed now that xalan is not being included in camel-eip-documentation-enricher-maven-plugin (xalan is not used anywhere else inside of tooling)
https://github.com/apache/camel/compare/main...cunningt:camel:morexalanremoval?expand=1#diff-6e42f7bb9284d62714d0b1dac53fb58b16cfae965a91e7e87f3461037841bc51 : I think can be removed because this is a xalan-specific / non-JDK case?
https://github.com/apache/camel/compare/main...cunningt:camel:morexalanremoval?expand=1#diff-761b735e3a131740e351452e7430479cc3fa479e80bb8b7ba43c56c877dc83ae : I think can be removed because this is a xalan-specific / non-JDK …
=> CAMEL-18346 Remove xalan-specific code / references

components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FtpServerTestSupport.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpServerTestSupport.java, test-infra/camel-test-infra-common/src/test/java/org/apache/camel/test/infra/common/services/AbstractTestService.java, test-infra/camel-test-infra-ftp/src/test/java/org/apache/camel/test/infra/ftp/services/FtpRemoteService.java, test-infra/camel-test-infra-ftp/src/test/java/org/apache/camel/test/infra/ftp/services/FtpService.java, test-infra/camel-test-infra-ftp/src/test/java/org/apache/camel/test/infra/ftp/services/FtpServiceFactory.java, test-infra/camel-test-infra-ftp/src/test/java/org/apache/camel/test/infra/ftp/services/embedded/FtpEmbeddedService.java, test-infra/camel-test-infra-ftp/src/test/java/org/apache/camel/test/infra/ftp/services/embedded/SftpEmbeddedService.java
=> CAMEL-16488: ensure resource setup/cleanup on the right time

components/camel-hdfs/pom.xml
Exclude org.slf4j:slf4j-reload4j coming in from hadoop common - it is causing multiple SLF4J bindings in the camel-hdfs tests and logback errors in the camel-spring-boot camel-hdfs-starter tests.
Excluding slf4j-reload4j removes the multiple SLF4J bindings logging and the logback error in camel-spring-boot integration tests.     Tests pass locally for me with this change.
```
[INFO] Running org.apache.camel.component.hdfs.integration.HdfsConsumerIntegrationIT
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/tcunning/.m2/repository/org/slf4j/slf4j-reload4j/1.7.36/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/tcunning/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.18.0/log4j …
```
=> Exclude org.slf4j:slf4j-reload4j to avoid logback warnings/errors

camel-dependencies/pom.xml, components/camel-coap/pom.xml, parent/pom.xml
Upgrade californium version, provide separate version for newly available version of scandium
camel-coap tests all pass locally
=> Upgrade californium version, provide separate version for newly available version of scandium

components/camel-file/src/main/java/org/apache/camel/component/file/strategy/GenericFileRenameExclusiveReadLockStrategy.java
=> Rename strategy filesystem exception

components/camel-google/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubComponent.java, components/camel-google/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubEndpoint.java
As described in CAMEL-18503, this PR provides the possibility to configure the max ack extension period on a Google PubSub consumer route.
=> [CAMEL-18503] Configure max ack extension period in PubSub subscriber

components/camel-coap/pom.xml
fixes https://issues.apache.org/jira/browse/CAMEL-18505
I'm excluding californium-legal and element-connector with version 2.7.2 and adding it as 2.7.3 to prevent conflict.
(I can not change  <californium-version>2.7.2</californium-version> to 2.7.3, because org.eclipse.californium:element-connector-tcp-netty:jar:2.7.3 does not exists)
I used `californium-scandium-version` as a version number for   californium-legal and element-connector, I can not find a better name of that property. But in the future, once all californium dependencies will have the same version, property will be removed. So I think it is acceptable.
=> CAMEL-18505 Camel-coap: Version conflict (californium-legal and californium-connector)

core/camel-support/src/main/java/org/apache/camel/support/CamelContextHelper.java
fixes for https://issues.apache.org/jira/browse/CAMEL-11252
As of today components/endpoints and so on can be retrieved/removed from the camel context by id but it would be nice to have a more flexible way to retrieve them.
* Add 2 utility methods to `CamelContextHelper` in order to get components and endpoints with a predicate
=> CAMEL-11252: camel-core : allow to retrieve components/endpoints list with a predicate

core/camel-core/src/test/java/org/apache/camel/impl/health/RouteHealthCheckTest.java, core/camel-health/src/main/java/org/apache/camel/impl/health/RouteHealthCheck.java
Fixes bug [CAMEL-18514](https://issues.apache.org/jira/browse/CAMEL-18514).
=> CAMEL-18514: camel-health - health check for not automatically started routes should always be up

parent/pom.xml
fixes https://issues.apache.org/jira/browse/CAMEL-18520
I aligned versions of google-secret-manager to com.google.cloud/libraries-bom/25.4.0 (which dictates versions to other google dependencies)
@oscerd What do you think about it? (The fix removes conflicts from the issue and make sense to me)
=> CAMEL-18520 Google-secrets-manager:resolved conflicts

camel-dependencies/pom.xml, components/camel-hbase/pom.xml, parent/pom.xml, test-infra/camel-test-infra-hbase/pom.xml
Thought it'd be good to backport to 3.18.x if possible as there's a few security related fixes.
=> CAMEL-18535: Upgrade HBase to 2.5.0

components/camel-http/src/test/java/org/apache/camel/component/http/HttpSendDynamicAwareUriWithSpacesTest.java
The toD optimisation does not work when a path variable contains a space.
The HTTP component correctly encodes spaces to %20, but the HttpSendDynamicAware does not follow this logic.
This triggers an URISyntaxException because java.net.URI  (on line 168) does not accept an unencoded URL.
It might be worthwhile to add some logging when an URISyntaxException is handled. Currently, it goes unnoticed.
=> Adds tests to demonstrate bug within the toD optimisation

test-infra/camel-test-infra-nats/src/test/java/org/apache/camel/test/infra/nats/services/NatsLocalContainerService.java
This reverts commit e1695527bd6869b77c23403df28ae3743bfd0fa8.
Container for 2.9.0 seems to break TLS tests. It appears something may
have changed on the new version and it needs to be adjusted to work
with our tests.
=> Revert "Upgrade Nats Image for test-infra to version 2.9.0"

.github/workflows/component-pr.yaml, .github/workflows/main-checkstyle-build.yml, .github/workflows/main-push-build.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

.github/workflows/alternative-os-build.yml, .github/workflows/component-pr.yaml, .github/workflows/depsreview.yaml, .github/workflows/generic-pr.yaml, .github/workflows/main-checkstyle-build.yml, .github/workflows/main-push-build.yml, .github/workflows/pr-build.yml
Prevent camel workflows from running on forks like camel-quarkus does https://github.com/apache/camel-quarkus/commit/a4174460f67bfb792d331512abbab928c7d71dd5
=> Prevent CI workflows from running on forks

camel-dependencies/pom.xml, components/camel-etcd3/pom.xml, parent/pom.xml
Fix for https://issues.apache.org/jira/browse/CAMEL-18560
Since the latest version of jetcd-all (0.5.11), new versions of jetcd have been released but as individual artifacts.
* Set the new version of jetcd in the parent and dependencies pom
* Change the name of the artifact for  `jetcd-core`
=> CAMEL-18560: camel-etcd3 - Upgrade jetcd to 0.7.3

camel-dependencies/pom.xml, components/camel-etcd3/pom.xml, parent/pom.xml
Related to https://issues.apache.org/jira/browse/CAMEL-18560
Merging https://github.com/apache/camel/pull/8436 causes a build failure in camel-spring-boot project with an error or type:
```
[INFO] --- camel-spring-boot-generator-maven-plugin:3.19.0-SNAPSHOT:prepare-spring-boot-starter (generate) @ camel-etcd3-starter ---
org.apache.maven.artifact.versioning.OverConstrainedVersionException: The artifact has no valid ranges
io.grpc:grpc-core:jar:1.47.0
Path to dependency: 
1) org.apache.camel:camel-etcd3:pom:3.19.0-SNAPSHOT
2) io.etcd:jetcd-core:jar:0.7.3
3) io.etcd:jetcd-grpc:jar:0.7.3
```
This is due to a conflict of grpc version used by jetcd-grpc (1.48.0) and the one used by vertx-grpc (1.47.0).
* Align the grpc versions to `1.47.0`
* Exclude grpc from jetcd-core
The build passes:
``` …
```
=> CAMEL-18560: camel-etcd3 - Align the grpc version of jetcd-grpc with vertx-grpc

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/KafkaRecordProcessorFacade.java
When "breakOnFirstError" = "true", if an error occurs on the first message in a set of polled messages, then the offset is set to -1, causing all messages to be refetched and not only the one which failed. Modify KafkaFetchRecords to remember the result returned from the the processing of the previous batch when processing a new batch of polled messages.
=> CAMEL-18350: fix bug causing all messages to be reconsumed

components/camel-elasticsearch/src/main/java/org/apache/camel/component/es/ElasticsearchProducer.java
Fix for https://issues.apache.org/jira/browse/CAMEL-18580
In Camel 3.19, a new component based on the Java Api Client has been proposed. This component provides a blocking producer which could be improved by leveraging the asynchronous client to propose a non-blocking/asynchronous producer instead.
* Rewrites the code of the process method to use the `ElasticsearchAsyncClient` instead of `ElasticsearchClient`
* Removes the volatile keyword from the field `sniffer` as it is always written before and read after the volatile field `client` (piggybacking)
* Uses a mutex to prevent concurrent initialization of the client
* Fixes the error message when no operation has been set
=> CAMEL-18580: camel-elasticsearch - Propose an async producer

.github/workflows/main-checkstyle-build.yml, .github/workflows/main-push-build.yml, .github/workflows/pr-build.yml
Related to https://issues.apache.org/jira/browse/CAMEL-18582
The build regularly fails due to write lock issues, an investigation is required to fix or workaround the problem.
* Add the flag to provide the stack trace to all mvnd commands
=> CAMEL-18582: add the flag to provide the stack trace to all mvnd cmds

buildingtools/src/main/resources/notice-supplements.xml, camel-dependencies/pom.xml, components/camel-cxf/camel-cxf-common/src/main/java/org/apache/camel/component/cxf/converter/CachedCxfPayload.java, components/camel-fop/pom.xml, components/camel-spring-ws/src/main/java/org/apache/camel/component/spring/ws/SpringWebserviceHelper.java, components/camel-xmlsecurity/pom.xml, core/camel-core-engine/pom.xml, core/camel-core/src/test/java/org/apache/camel/builder/xml/XPathTest.java, core/camel-management-api/pom.xml, core/camel-management/pom.xml, core/camel-xml-jaxp/src/main/java/org/apache/camel/converter/jaxp/XmlConverter.java, parent/pom.xml, tooling/maven/camel-eip-documentation-enricher-maven-plugin/pom.xml, tooling/maven/camel-eip-documentation-enricher-maven-plugin/src/test/java/org/apache/camel/maven/integration/EIPDocumentationMojoTest.java
https://issues.apache.org/jira/browse/CAMEL-18346
xalan was removed in camel-3.19.0 - could we cherry pick this back to the 3.18.x LTS branch?
=> CAMEL-18346 Remove use of xalan

.github/workflows/pr-build.yml, .mvn/jvm.config
Fix for https://issues.apache.org/jira/browse/CAMEL-18582
Since we upgraded mvnd to 0.8, the locking of the artifacts is now made by default with a file locking (https://github.com/apache/maven-mvnd/pull/508) which causes regular build failures due to write lock issues.
* Change the named lock factory for a JVM-local implementation based on `ReentrantReadWriteLocks` which is more or less what we had in version 0.7
* Increase the lock timeout to 5 minutes
* Generate a thread dump on lock issue
=> CAMEL-18582: Prevent build failures due to write lock issues

.github/workflows/main-checkstyle-build.yml, .github/workflows/main-push-build.yml, .github/workflows/pr-build.yml, .mvn/jvm.config
Related to https://issues.apache.org/jira/browse/CAMEL-18582
After a deeper analysis, it appears that the build failures are indirectly due to errors of type `I/O exception (java.net.SocketException) caught when processing request to {s}->https://repo.maven.apache.org:443: Connection timed out (Read failed)`  which has for consequences to keep the lock on the artifacts for more than 15 minutes such that the build ends up with a lock issue since the lock timeout is only of 5 minutes.
* Increase the lock timeout to 15 minutes
* Set the read timeout to 5 minutes
* Remove the step that generates a thread dump since it is not due to a deadlock
=> CAMEL-18582: Update timeouts to prevent write lock issues

.mvn/jvm.config
Related to https://issues.apache.org/jira/browse/CAMEL-18582
With the latest fix, we now get errors of type `SocketTimeoutException: Read timed out` indicating that the runner loses regularly the connection with maven central for some period of time but as it can recover it, to workaround it, we need to make sure that it can retry when it faces this kind of error.
* Use `default` as retry handler instead of `standard` to be able to change the non-retryable classes
* By default, `SocketTimeoutException` as a subclass of `InterruptedIOException` is part of the non-retryable classes which is the reason why no retries are made, so we need to redefine the non-retryable classes without `InterruptedIOException` to make sure that it will retry in case of `Read timed out`
=> CAMEL-18582: Remove SocketTimeoutException from non retryable classes

components/camel-cxf/camel-cxf-soap/src/main/java/org/apache/camel/component/cxf/jaxws/DefaultCxfBinding.java, components/camel-cxf/camel-cxf-soap/src/test/java/org/apache/camel/component/cxf/jaxws/DefaultCxfBindingTest.java
Issue: https://issues.apache.org/jira/browse/CXF-8762
Actually, there are two SOAPAction headers.
1. SOAPAction Camel header (stored top-level in the context)
2. SOAPAction Protocol header (stored in the context inside PROTOCOL_HEADERS)
The value inside PROTOCOL_HEADERS is used in CXF when creating a HTTP request. It should be quoted as stated in this specification. http://www.ws-i.org/Profiles/BasicProfile-1.1.html#SOAPAction_HTTP_Header
I believe we should leave the value stored top-level in the context unquoted, since it has nothing to do with the HTTP protocol. Because of that, I'm removing the quotes inside _propagateHeadersFromCxfToCamel_.
Any comment are welcome.
=> [CXF-8762] CXF client sends the SOAPAction header without quotes

components/camel-box/camel-box-component/src/main/java/org/apache/camel/component/box/BoxConfiguration.java, components/camel-box/camel-box-component/src/test/java/org/apache/camel/component/box/BoxSharedConnectionTest.java
The test `org.apache.camel.component.box.BoxSharedConnectionTest.testEndpointUsesSharedConnection` fails continuously on Jenkins indicating that there is a regression so it needs to be fixed.
* Modify the implementation of the `equals` of the class `BoxConfiguration` to support subclasses like `org.apache.camel.component.box.BoxFilesManagerEndpointConfiguration`
* Cleanup the code of the test class (not related to the regression)
=> CAMEL-18608: camel-box - Fix the regression with shared connection

components/camel-etcd3/src/main/java/org/apache/camel/component/etcd3/processor/aggregate/Etcd3AggregationRepository.java
The test `org.apache.camel.component.etcd3.AggregateEtcd3ManualTest.testABC` regularly fails on the Jenkins build so it needs to be fixed.
* Ensure that the commit of a transaction is made synchronously to prevent aggregation miss
=> CAMEL-18608: camel-etcd3 - Synchronous commits in aggregation

components/camel-spark/pom.xml
The spark test fails with JDK 17 on Jenkins and should be fixed.
* Add the missing `--add-opens`
* Upgrade to the latest maintenance version of scala `2.12` to have the fix for https://github.com/scala/bug/issues/12419 which makes the test fails
=> CAMEL-18608: camel-spark - Fix compatibility issues with JDK 17

components/camel-rest-openapi/src/main/docs/rest-openapi-component.adoc
Updated PetStore example to reference existing spring-boot example, and removed references to Undertow. Also fixed some typos in the source snippets.
=> Doc update for camel-rest-openapi component

components/camel-swagger-java/src/test/java/org/apache/camel/swagger/ParameterAssert.java, components/camel-swagger-java/src/test/java/org/apache/camel/swagger/RestSwaggerArrayEnumTest.java, tooling/swagger-rest-dsl-generator/src/test/java/org/apache/camel/generator/swagger/RestDslXmlGeneratorTest.java
It fixes bug in usage of `asserThat` in swagger tests which missed evaluation of condition.
=> Fix asserts in swagger tests

.github/actions/quick-test/quick-test.sh, .github/workflows/component-pr.yaml, .github/workflows/generic-pr/label-config.yml, .github/workflows/main-checkstyle-build.yml, .github/workflows/pr-build.yml
We have to backport the set of Github CI fixes from last week because the feature is going to be deprecated. As such, our PR testing on this branch could work. 
This brings all of the fixes, GH cleanups and related changes I implemented last week. 
Note: there's 3 commits on core + components that are here with the intention of testing the patch set.
=> (backport) Github CI fixes

core/camel-core/src/test/java/org/apache/camel/util/ObjectHelperTest.java, core/camel-support/src/main/java/org/apache/camel/support/ObjectHelper.java
Fix for https://issues.apache.org/jira/browse/CAMEL-16354
Using `Scanner` to use for splitting could potentially be optimized for more basic splitting by single char as we do for commas.
The Scanner creates a lot of object allocations with reg exp patterns and whatnot that is way overkill.
* Fix warnings in `ObjectHelperTest`
* Add new tests to improve the code coverage of `ObjectHelper.createIterable`
* Improve the performance in case the separator is a literal or a pattern
**JMH Settings/Environment**
```
```
**Literal Separator**
```
Benchmark                                          (type)  Mode  Cnt       Score     Error  Units
MyBenchmark.newSplitterWithSpecificSeparator         TINY  avgt   15      98.854 ±   0.592  ns/op
MyBenchmark.newSplitterWithSpecificSeparator        SMALL …
```
=> CAMEL-16354: camel-core - Optimize Splitters using Scanner

components/camel-caffeine/src/main/java/org/apache/camel/component/caffeine/DefaultCaffeineSendDynamicAware.java, components/camel-file/src/main/java/org/apache/camel/component/file/GenericFileEndpoint.java, components/camel-file/src/main/java/org/apache/camel/component/file/GenericFileOnCompletion.java, components/camel-http-base/src/main/java/org/apache/camel/http/base/HttpSendDynamicAware.java, components/camel-http/src/main/java/org/apache/camel/component/http/HttpProducer.java, components/camel-jsch/src/main/java/org/apache/camel/component/scp/ScpOperations.java
Replacing some `String.indexOf(s) > 0` for `String.contains(s)`
There are 5 others like this in core and tooling so despite simple I dont know if I should touch on it.
[Sonar rule here](https://rules.sonarsource.com/java/RSPEC-2692)
=> (chores) Sonar's issues cleanups

components/camel-file/src/main/java/org/apache/camel/component/file/GenericFileEndpoint.java
The tests `FtpConsumerDoneFileNameStepwiseIT` and `FtpConsumerDoneFileNameIT` are failing systematically on the Jenkins build indicating that there is regression to fix.
* Restore the previous test to check if it is a prefix to avoid getting true when it starts with `${`.
* Add the `NOSONAR` tag indicating that it is expected and must be ignored by sonar.
=> CAMEL-18608: camel-file - Fix is done file checker

components/camel-git/src/test/java/org/apache/camel/component/git/GitTestSupport.java
- Tests fail if init.defaultBranch is different from master
- Some config in .gitconfig user file may affect tests
=> Camel-git: fix environmental contamination and default branch for tests

components/camel-swift/src/main/docs/swiftMt-dataformat.adoc, components/camel-swift/src/main/docs/swiftMx-dataformat.adoc
Related to https://issues.apache.org/jira/browse/CAMEL-14832
The Spring Boot starter is available so the doc can refer to it.
* Add the `camel-spring-boot-name` to the doc files
* Improve the doc to indicate the libs used behind the scenes and the type of object produced by the marshallers.
=> CAMEL-14832: camel-swift - Add the SB name and more details to the doc

test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSContainer.java
Temporary workaround for https://issues.apache.org/jira/browse/CAMEL-18660
The test `Kinesis2ConsumerHealthCustomClientTest systematically` fails on Jenkins due to a rate limit issue caused by an incomplete docker image of LocalStack.
* Downgrade the version of the docker image of LocalStack to a version that contains kinesis-mock
=> CAMEL-18660: Downgrade LocalStack to prevent rate limit issues

parent/pom.xml
Cherry-picked commit to bump Jettison from version `1.5.0` to `1.5.1`
=> 3.18.x: Bump Jettison to version 1.5.1

parent/pom.xml
Cherry-picked commit to bump Jettison from version `1.4.1` to `1.5.1`
=> 3.14.x: Bump Jettison to version 1.5.1

components/camel-soap/pom.xml, components/camel-soap/src/main/java/org/apache/camel/dataformat/soap/Soap11DataFormatAdapter.java, components/camel-soap/src/main/java/org/apache/camel/dataformat/soap/Soap12DataFormatAdapter.java, components/camel-soap/src/main/java/org/apache/camel/dataformat/soap/name/ElementNameStrategy.java, components/camel-soap/src/main/java/org/apache/camel/dataformat/soap/name/QNameStrategy.java, components/camel-soap/src/main/java/org/apache/camel/dataformat/soap/name/ServiceInterfaceStrategy.java, components/camel-soap/src/main/java/org/apache/camel/dataformat/soap/name/TypeNameStrategy.java, components/camel-soap/src/main/java/org/apache/camel/dataformat/soap/name/XmlRootElementPreferringElementNameStrategy.java, components/camel-soap/src/test/java/org/apache/camel/converter/soap/name/ServiceInterfaceStrategyTest.java, components/camel-soap/src/test/resources/org/apache/camel/dataformat/soap/TestService.wsdl
Duplicated SOAP-Exceptions QNames did lead to random selection of corresponding
java exceptions in the unmarshal codepath.
CXF handle this correctly.
With this patch we always lookup by SOAPAction and QName if SOAPAction is available.
=> SOAP-Fault to Java Exception also lookups by SOAPAction

camel-dependencies/pom.xml, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Bind.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelCommand.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Init.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Pipe.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java, parent/pom.xml
https://issues.apache.org/jira/browse/CAMEL-18716
This implements file path completion for `<file>` argument, not only for commands that refer to exisitng files:
- `camel run`
- `camel pipe`
but also for ones that create a new file:
- `camel init`
- `camel bind`.
It's because even though they create new files users might want to create them under an exisitng directory, or with the same prefix/suffix as the existing ones. In those cases file path completion still helps.
=> CAMEL-18716: camel-jbang - Provide completion for positional file path parameters

catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/RouteCoverageMojo.java
Fixes https://issues.apache.org/jira/browse/CAMEL-18730
After generating the route coverage of the tests, if we launch the maven command `mvn camel-report:route-coverage`, the plugin fails due to an import issue.
* Remove the bad import and replace it with `List.of`.
Tested against the example `main`:
```
$ mvn camel-report:route-coverage
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------< org.apache.camel.example:camel-example-main >-------------
[INFO] Building Camel :: Example :: Main 3.20.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- camel-report-maven-plugin:3.20.0-SNAPSHOT:route-coverage (default-cli) @ camel-example-main ---
[INFO] Discovered 1 routes
[INFO] Route coverage summary:
Class: …
```
=> CAMEL-18730: camel-report-maven-plugin - Fix import issue

test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/ContainerLocalKafkaService.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/StrimziContainer.java
- Confluent ones to 7.2.2
- Strimzi ones to latest-3.3.1
=> (chores) test-infra-kafka: upgrade Kafka images

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportQuarkus.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/RuntimeUtil.java
This pull request fixes [CAMEL-18719](https://issues.apache.org/jira/browse/CAMEL-18719)
=> Fixed Camel 18719 : camel-jbang - Adding the dependency of camel-quarkus-core creates two entries in exported POM.xml

components/camel-hyperledger-aries/src/main/docs/hyperledger-aries-component.adoc, components/camel-hyperledger-aries/src/main/java/org/apache/camel/component/aries/Constants.java, components/camel-hyperledger-aries/src/main/java/org/apache/camel/component/aries/handler/PresentProofServiceHandler.java, components/camel-hyperledger-aries/src/main/java/org/apache/camel/component/aries/handler/WalletServiceHandler.java, components/camel-hyperledger-aries/src/test/java/org/apache/camel/component/aries/ConnectionlessProofTest.java
Added two Aries services: `/present-proof/create-request` (similar to `/present-proof/send-request`, but doesn't require connection upfront) and `/wallet/get-did-endpoint` (to populate service decorator with endpoint for proof presentation).
=> Hyperledger Aries - connectionless proofs

components/camel-hdfs/src/main/java/org/apache/camel/component/hdfs/HdfsCompressionCodec.java, components/camel-hdfs/src/test/java/org/apache/camel/component/hdfs/HdfsProducerTest.java
camel-hdfs currently supports gzip and bzip2 compression, but HDFS itself supports some other codecs.
This PR adds snappy compression feature to the producer.
=> CAMEL-18749: camel-hdfs: Add Snappy compression support

dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java, dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java
This will let you install Camel 3.18.3 `camel` cli with this command:
```
jbang app install install camel@apache/camel/camel-3.18.x
```
=> camel-jbang - Upgrade to Camel 3.18.3

components/camel-openapi-java/src/main/java/org/apache/camel/openapi/RestModelConverters.java, components/camel-openapi-java/src/test/java/org/apache/camel/openapi/User.java
Trivial change
The generation of the Schema produce a warn log when it should not for the boolean type : 
`WARN  RestModelConverters            - Encountered unexpected type boolean in processing schema.`
The OpenApi spec says : https://swagger.io/docs/specification/data-models/data-types
```
string (this includes dates and files)
number
integer
boolean
array
object
```
Since it just an error log, it's hard to test, so I added a boolean in the User.java, the log is no longer there.
=> CAMEL-18761 camel-open-api - Warning log when using boolean type

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc
`camel export` command directory parameter should be `-dir` instead of `--dir`
=> Fix the camel project export dir option typo

components/camel-cdi/src/main/java/org/apache/camel/cdi/CdiCamelExtension.java, components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/CamelTestSupport.java, components/camel-test/camel-test-junit5/src/test/java/org/apache/camel/test/junit5/CamelTestSupportOneContextForAllTest.java, core/camel-api/src/main/java/org/apache/camel/spi/RoutesLoader.java, core/camel-core-model/src/main/java/org/apache/camel/builder/RouteBuilder.java, dsl/camel-xml-io-dsl/src/test/java/org/apache/camel/dsl/xml/io/XmlMainTemplatedRouteFromDifferentDSLTest.java, dsl/camel-xml-io-dsl/src/test/resources/org/apache/camel/main/xml/camel-my-route-template.xml
Fix https://issues.apache.org/jira/browse/CAMEL-18764 (part 2)
The first fix allowing to build a templated route from a template defined using a different DSL, makes [several tests fail](https://ci-builds.apache.org/job/Camel/job/Apache%20Camel/job/main/810/testReport/) that should be fixed:
* org.apache.camel.cdi.templatedroute.TemplatedRouteTest.sendMessageToInbound
* org.apache.camel.component.kamelet.TemplatedRouteKameletTest.testKamelet
* org.apache.camel.dsl.yaml.TemplatedRouteTest.create templated route
* org.apache.camel.dsl.yaml.TemplatedRouteTest.create templated-route
* Add missing calls to the new method `addTemplatedRoutes` ensuring that it is called once all the route templates are added to the context
* Provide the Camel context when it is known to `populateTemplatedRoutes` …
=> CAMEL-18764: camel-core - Add unit test and fix regressions

components/camel-resilience4j/src/test/java/org/apache/camel/component/resilience4j/ResiliencePooledRouteOkTest.java
I have created a new test class called ResiliencePooledRouteOkTest where the context is pooled to increase code coverage.
Specifically, doBuild() method in ResilienceProcessor class got increased coverage for if (pooled) statement.
You can compare the original coverage and its analysis with the improved one on the screenshots. 
Original:
Improved:
=> [camel-resilience4j] Increase test coverage making a context pooled

core/camel-support/src/main/java/org/apache/camel/support/task/BackgroundTask.java, core/camel-support/src/main/java/org/apache/camel/support/task/BlockingTask.java, core/camel-support/src/main/java/org/apache/camel/support/task/ForegroundTask.java, core/camel-support/src/test/java/org/apache/camel/support/task/BackgroundIterationTimeTaskTest.java
The changes in this PR fix a bug in the BackgroundTask class which results in a thread that loops forever doing nothing but log a warning. 
The fix is essentially ending the thread when the budget as been consumed. What that means is dependent on the actual implementation of the Budget instance that is passed to the BackgroundThread. It may mean that the `maxDuration` has been exceeded or that the task has been run for `maxIteration` times.
The new implementation saves the result of the runTaskWrapper method in an wrapper instance so that it can be used as return value of the run method implementation.
This is necessary because the Future, returned by the scheduleAtFixedRate method can't be …
=> CAMEL-18766 Fixes bug in camel-support

docs/user-manual/modules/ROOT/pages/camel-maven-archetypes.adoc
The archetype was moved as part of CAMEL-15695 but this part of the
documentation was left behind
=> CAMEL-18770: move the blueprint archetype information to Camel Karaf

components/camel-gson/src/test/java/org/apache/camel/component/gson/GsonFieldNamePolicyTest.java, components/camel-gson/src/test/java/org/apache/camel/component/gson/GsonMarshalExclusionTest.java, components/camel-gson/src/test/java/org/apache/camel/component/gson/SpringGsonFieldNamePolicyTest.java
Flaky Tests found using [NonDex](https://github.com/TestingResearchIllinois/NonDex) by running the commands -
`
mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.camel.component.gson.GsonFieldNamePolicyTest#testMarshalPojo
`
`
mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.camel.component.gson.GsonMarshalExclusionTest#testMarshalAndUnmarshalPojoWithAnotherExclusion
`
`
mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.camel.component.gson.GsonMarshalExclusionTest#testMarshalAndUnmarshalPojoWithExclusion
`
`
mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.camel.component.gson.SpringGsonFieldNamePolicyTest#testMarshalPojo
`
The logged failures were-
```
[ERROR] …
```
=> Fix Flaky Tests Caused by JSON permutations

docs/main/modules/getting-started/pages/index.adoc
=> (chores) documentation: fixes some typos and cleanup redundant terms

test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSContainer.java
Fix for https://issues.apache.org/jira/browse/CAMEL-18660
The test `Kinesis2ConsumerHealthCustomClientTest systematically` fails on Jenkins due to a rate limit issue caused by an incomplete docker image of LocalStack.
* Upgrade the version of the docker image of LocalStack to the most recent version that contains kinesis-mock
=> CAMEL-18660: Upgrade LocalStack to 1.3.0 that contains kinesis-mock

camel-dependencies/pom.xml, components/camel-debezium/camel-debezium-common/camel-debezium-common-component/pom.xml, parent/pom.xml
Upgrade kafka-clients versions in two places ...
- camel-debezium kafka-clients 3.0.0->3.0.2
- camel-vertx-kafka kafka-clients 2.8.1->2.8.2
Ran tests on camel-debezium, camel-kafka, camel-vertx, passed.
=> Upgrade kafka-clients versions

components/camel-zipfile/pom.xml, components/camel-zipfile/src/test/java/org/apache/camel/processor/aggregate/zipfile/ZipAggregationStrategySplitTest.java, core/camel-core-processor/src/main/java/org/apache/camel/processor/MulticastProcessor.java
Handing over the completions in the MultiCastProcessor solves an issue, where temporary files were not cleaned up after using a route with a "Split Definition"
Detaisl can be found in CAMEL-18739
=> CAMEL-18739 fix by handing over the completion to the original exchange

components/camel-ahc/src/main/java/org/apache/camel/component/ahc/AhcEndpoint.java, components/camel-ahc/src/main/java/org/apache/camel/component/ahc/AhcProducer.java, components/camel-ahc/src/test/java/org/apache/camel/component/ahc/AhcRecipientListInOnlyWithTryBlockTest.java, components/camel-ahc/src/test/java/org/apache/camel/component/ahc/AhcRecipientListInOutWithTryBlockTest.java, components/camel-ahc/src/test/java/org/apache/camel/component/ahc/AhcRecipientListTest.java
Fix for bug CAMEL-18816.
Problem is caused by the fact that  `createProducer()` method in `AhcEndpoint` class may be executed before `doStart()` method.
This PR contains 3 tests that reproduce a problem and a fix based on solution from HttpEndpoint/HttpDestination.
Creation of `client` field in `AhcEndpoint` has been moved from `doStart()` method to `getOrCreateClient()` method. This `getOrCreateClient()` method is invoked from `AhcProducer(AhcEndpoint endpoint)` constructor.
=> CAMEL-18816: camel-ahc component crashes when traffic starts too early

components/camel-cdi/src/test/java/org/apache/camel/cdi/test/CamelEventNotifierTest.java, components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/CurrentSpanTest.java, components/camel-tracing/src/main/java/org/apache/camel/tracing/Tracer.java
As follow-up with https://github.com/apache/camel/pull/8713
=> CAMEL-18661: clean-ups

components/camel-test/camel-test/src/main/java/org/apache/camel/test/junit4/CamelTestSupport.java, components/camel-wal/src/main/java/org/apache/camel/component/wal/LogWriter.java, core/camel-console/src/main/java/org/apache/camel/impl/console/DefaultDevConsoleRegistry.java, core/camel-core-model/src/main/java/org/apache/camel/builder/AdviceWithTasks.java, core/camel-health/src/main/java/org/apache/camel/impl/health/DefaultHealthCheckRegistry.java
Solving lasts sonar issues about [use of Collection.isEmpty() to test for emptiness ](https://sonarcloud.io/organizations/apache/rules?open=java%3AS1155&rule_key=java%3AS1155).
=> (chores) Lasts sonar issues about replace size() > 0 by !isEmpty()

components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/CamelOpenTelemetryTestSupport.java, components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/CurrentSpanTest.java, components/camel-opentelemetry/src/test/resources/log4j2.properties, components/camel-tracing/src/main/java/org/apache/camel/tracing/ActiveSpanManager.java, components/camel-tracing/src/main/java/org/apache/camel/tracing/Tracer.java
Follow up for #8713 and #8911.
Fixes flaky `CurrentSpanTest.testContextDoesNotLeak` test.
I was able to repro failures locally and with this change, they are no longer reproducible (tried on 1000 iterations).
There are several problems:
1. We can't guarantee that `ExchangeAsyncProcessingStartedEvent` is fired once and only if a span was created previously
2. We can't guarantee that span ends on the same thread it was started, i.e. scope is closed on the same thread
3. Due to concurrency in async scenarios we can call close on scope two times
As a result, we're closing scopes multiple times and from the wrong threads. Changing these on Camel side, AFAIK would be quite difficult.
Unfortunately, OTel scope closing works differently than I thought - …
=> Tracing: fix flaky test and add scope checks before closing

dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java, dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java
Backport #8914 to 3.20.x branch. With this now users can do:
```
jbang app install camel@apache/camel/camel-3.20.x
```
to install the latest 3.20.x version of Camel JBang.
=> camel-jbang - Upgrade to Camel 3.20.0 (3.20.x)

components/camel-as2/camel-as2-api/pom.xml, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/EntityParser.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/io/AS2SessionInputBuffer.java, components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/AS2MessageTest.java, components/camel-as2/pom.xml
... otherwise you will get `java.nio.charset.MalformedInputException: Input length = 1` when content transfer encoding is binary. This PR mainly does AS2SessionInputBuffer.setCharsetDecoder(null) instead when charset is not specified so it doesn't reach MalformedInputException. Then it convert returned result back to byte[] from String when charset is not specified. String were required to find multipart boundaries. Generally this PR keeps previous behavior otherwise, i.e. when charset is specified. It also tests all 8 different situations for encrypt, sign and compress via a parameterized test. as2-lib third-party library is used for these tests as at the moment, binary content transfer encoding is not supported by Camel AS2 client. …
=> [CAMEL-15111] Fixes bug in camel-as2 via not forcing ascii charset when not specified

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/util/HttpMessageUtils.java, components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/AS2MessageTest.java
In order to support different orders of compression and signature, this PR checks if the mimeEntity is a compressed entity before throwing unknown entity exception - both compression before and after signature are allowed according to the RFC https://datatracker.ietf.org/doc/html/rfc5402/#section-3
=> [CAMEL-18842] Checks for compression before throwing exception

docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_11.adoc
Typo: The # char is not correctly escaped in the migration guide. This leads to the # not being displayed but only formating the following word and possibly causing confusion on how to use it.
=> Typo in migration guide

components/camel-plc4x/src/main/java/org/apache/camel/component/plc4x/Plc4XConsumer.java, components/camel-plc4x/src/main/java/org/apache/camel/component/plc4x/Plc4XEndpoint.java, components/camel-plc4x/src/main/java/org/apache/camel/component/plc4x/Plc4XProducer.java, components/camel-plc4x/src/test/java/org/apache/camel/component/plc4x/Plc4XEndpointTest.java, components/camel-plc4x/src/test/java/org/apache/camel/component/plc4x/Plc4XProducerTest.java
I do not have a JIRA account yet, so I could not create a JIRA ticket. I did create a issue over on the plc4x GitHub: [plc4x-bug-713](https://github.com/apache/plc4x/issues/713).
I moved establishment of the connection to the doStart() method instead of the constructor of the Endpoint. See the issue above for more information.
=> camel-plc4x: Connection now established in doStart() of Producer/Consumer instead of constructors

components/camel-plc4x/src/main/java/org/apache/camel/component/plc4x/Plc4XProducer.java
I do not have a JIRA account yet, so I could not create a JIRA ticket. I will create a ticket as soon as I have an account.
Because the CompletableFuture in the process() method of the Plc4XProducer didn't have a timeout, it sometimes got stuck there. Resulting in no more write requests being processed. I added a timeout of 5000 ms because the first process sometimes takes a couple of seconds to complete.
I also changed some deprecated methods for non-deprecated ones.
=> camel-plc4x: Added timeout to future in process() method of Plc4XProducer and fixed deprecated Camel methods

docs/main/modules/working-with-camel-core/pages/index.adoc, docs/user-manual/modules/ROOT/pages/java-dsl.adoc, docs/user-manual/modules/ROOT/pages/routes.adoc
- also categorize generic guides for components and data processing
=> (chores) documentation: reorganize the route documentation

dsl/camel-java-joor-dsl/src/main/java/org/apache/camel/dsl/java/joor/ClassRoutesBuilderLoader.java, dsl/camel-java-joor-dsl/src/main/java/org/apache/camel/dsl/java/joor/Helper.java, dsl/camel-java-joor-dsl/src/main/java/org/apache/camel/dsl/java/joor/JavaJoorClassLoader.java, dsl/camel-java-joor-dsl/src/main/java/org/apache/camel/dsl/java/joor/JavaRoutesBuilderLoader.java, dsl/camel-java-joor-dsl/src/main/java/org/apache/camel/dsl/java/joor/MultiCompile.java
Fixes https://issues.apache.org/jira/browse/CAMEL-18860
To ease the native compilation of routes written using the Java DSL, we need to adapt the code to be able to reuse some parts of the existing code.
* Move the reusable methods `asClassName` and `determineName` to a helper class
* Allow providing compilation options when compiling to give the ability to set the classpath
* Fix some violations
=> CAMEL-18860: java-joor-dsl - Adapt the code for native compilation

components/camel-kafka/src/main/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepository.java, components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryPersistenceIT.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/RedpandaTransactionsEnabledContainer.java
Updates the Redpanda container image to 22.3.10 which enables transactions by default and sets consumer group init delay to 0 to avoid initial consumption delays seen in tests.
Additionally 22.3.10 includes better broker side coordination when creating topics with autocreate set to true which was causing test races.
More details here: https://github.com/redpanda-data/redpanda/issues/7084
=> CAMEL-18620: Fix Redpanda integration tests

components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/AsyncJmsProducerExceptionInTXTest.java, components/camel-jms/src/test/resources/org/apache/camel/component/jms/issues/broker.xml, components/camel-jms/src/test/resources/org/apache/camel/component/jms/issues/camelBrokerClient.xml
Invalidates CAMEL-4616.
I think that the test provided by this PR proves that camel JMS doesn't loose messages in transaction when AtiveMQ uses `async send` internally and also asynchronously fails. See the test comments to understand what the pull request does, how, and why.
=> [CAMEL-4616] camel-jms: test not loosing messages in async TX sends

components/camel-jms/src/test/resources/org/apache/camel/component/jms/issues/broker.xml, components/camel-jms/src/test/resources/org/apache/camel/component/jms/issues/camelBrokerClient.xml
fixes flaky test introduced by #9015 via separating brokers to two different brokers instead of using a shared broker.
=> fix CAMEL-4616 flaky test

dsl/camel-java-joor-dsl/src/main/java/org/apache/camel/dsl/java/joor/Helper.java
fix for https://issues.apache.org/jira/browse/CAMEL-18864 (part 2)
Since `ClassRoutesBuilderLoader` has been removed the method `Helper#asClassName` is no more used and thus can be removed.
* Remove the useless method `Helper#asClassName`
=> CAMEL-18864: java-joor-dsl - Remove method Helper#asClassName

camel-dependencies/pom.xml, parent/pom.xml
The upgrade breaks the idempotent repository due to KAFKA-14553.
Ref.: 8738cb71bc387ca1d55ed775726f5b8bcea58a5b
=> CAMEL-18839: reverts upgrade to Kafka 3.3.1

camel-dependencies/pom.xml, parent/pom.xml
The upgrade breaks the idempotent repository due to https://issues.apache.org/jira/browse/KAFKA-14553.
Ref.: 8738cb71bc387ca1d55ed775726f5b8bcea58a5b
=> (backport) CAMEL-18839: reverts upgrade to Kafka 3.3.1

components/camel-as2/camel-as2-component/src/main/java/org/apache/camel/component/as2/AS2Consumer.java, components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2ServerManagerIT.java
I found that the MDN that is sent from the AS2 server component has fixed header values for From and the Subject-prefix.
Looking in the code for AS2Consumer, I saw a TODO to read this values from configuration.
I've solved the TODO by reading the "From" value from the configuration field "from" with a fallback to the configuration field "server". So if nothing is configured for the endpoint, the value is nearly the same as before.
For the Subject-prefix I'm reading the "subject" from the configuration. If not configured on the endpoint, null is taken as value. This should be OK because the class ResponseMDN already has a fallback for generating the subject when the prefix is null.
Also I've added a unit test in AS2ServerManagerIT to test the default values and overrides from the endpoint …
=> Solving TODO in AS2 component

components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Consumer.java, components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/SqsConsumerExtendMessageVisibilityTest.java
When using message extending feature together with Threads EIP, it was possible to completely block the consumer (deadlock) if the message extend executor task queue would be filled up.
This could be triggered by the default threads profile where the message queue size is set to 1000 tasks.
On default settings, the consumer would consume: `max queue size`+`max threads`+`consumer thread` = 1000+20+1 concurrent tasks. The extender queue size however is only 1000. The `consumer thread` is due to `CallerRuns` policy.
There is no way to register that the consumer is called from a route which uses threads EIP, and thus we have two options for preventing this blocking behavior. Either increase the maxQueue size to something very high - or make it unbound.
I went with the latter as I believe it …
=> CAMEL-18780: Prevent blocking sqs consumer when using message extend

components/camel-pulsar/pom.xml
This fixes the pulsar errors caused by the upgrade to SL4F 2.
*Note*: there's a few failures that have been [caused by the upgrade to Pulsar 2.11.0](https://ci-builds.apache.org/job/Camel/job/Camel%20JDK17/job/main/521/) and still need to be fixed.
=> CAMEL-18932: fixed camel-pulsar tests due to sl4fj upgrade

camel-dependencies/pom.xml
The change updates the dependencies to support the Spring Boot 2.7.8 update: https://github.com/apache/camel-spring-boot/pull/711.
=> Update dependencies for Spring Boot 2.7.8 update

parent/pom.xml
Updating parent dependencies for the Spring Boot update to version 2.7.8 (see https://github.com/apache/camel-spring-boot/pull/711).
=> Spring Boot 2.7.8 parent dependencies

components/camel-rest-openapi/src/test/java/org/apache/camel/component/rest/openapi/HttpsTest.java, components/camel-rest-openapi/src/test/java/org/apache/camel/component/rest/openapi/HttpsV3Test.java, components/camel-rest-openapi/src/test/java/org/apache/camel/component/rest/openapi/WireMockJettyServerFactory.java
Use the method JettyHttpServer.buildSslContextFactory in the new WireMock version to avoid having to override createHttpConnector.
=> Simplify creation of SSL context for WireMock Jetty server.

camel-dependencies/pom.xml, components/camel-aws/camel-aws2-ses/pom.xml, components/camel-google/camel-google-mail/pom.xml, components/camel-mail/pom.xml, parent/pom.xml, tests/test-bundles/mock-javamail_1.7/pom.xml
August 18, 2021 - Jakarta Mail implementation moves to Eclipse Angus
https://eclipse-ee4j.github.io/angus-mail/
We are already importing the last version of **angus-mail** 1.1.0
=> CAMEL-18961 change sun-mail to angus-mail

core/camel-core/src/test/java/org/apache/camel/component/file/FileConsumerAbsolutePathTest.java, core/camel-core/src/test/java/org/apache/camel/component/file/FileProducerFileExistAppendNoFileBeforeTest.java
[FileConsumerAbsolutePathTest.java](https://github.com/apache/camel/compare/main...Croway:core-fix-flaky-test?expand=1#diff-8074c392d0272d82ae27b8a04b0c8982e66c3304bc106b17e9e2bab0ffd3b584) was failing on CI, while [FileProducerFileExistAppendNoFileBeforeTest.java](https://github.com/apache/camel/compare/main...Croway:core-fix-flaky-test?expand=1#diff-9aea9351eb88d2e13c3d4804927b954a48c6ee0df428069ca1da164281af3c81) was failing locally when executing all file test in sequence.
=> Fix File flaky test

components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQMessagePublisher.java
In a scenario with a high message publishing rate and a full queue the publisher will get "nack" (not acknowledged) as feedback from RabbitMQ. 
The method `Channel#waitForConfirmsOrDie(long)` in https://github.com/rabbitmq/rabbitmq-java-client/blob/main/src/main/java/com/rabbitmq/client/impl/ChannelN.java#L241 will close the channel. This closed channel is then given back to the channel pool.  Next time the channel is taken out of the pool it is detected as closed and will be removed. So a new channel needs to be opened and this too will be closed directly after usage when the same queue is still full. There will be a high rate of opened and closed communication channels and the channel pool gets unusable. 
This is described as high channel churn …
=> Prevent high channel churn in a queue full scenario

camel-dependencies/pom.xml, parent/pom.xml, test-infra/camel-test-infra-pulsar/src/test/java/org/apache/camel/test/infra/pulsar/services/PulsarLocalContainerService.java
seems like that consumer.pause() does not work as expected in 2.11.0, https://github.com/apache/pulsar/issues/19320
=> CAMEL-18974: Downgrade pulsar

components/camel-joor/src/main/java/org/apache/camel/language/joor/JoorCompiler.java, components/camel-joor/src/main/java/org/apache/camel/language/joor/JoorLanguage.java
Fix for https://issues.apache.org/jira/browse/CAMEL-18977
With the current code base, it is hard to change the behavior of the jOOR language in order to move most of the logic at build time and/or at static initialization time, without having to use ugly hacks like reflection. The goal of this task is to make the code more flexible to avoid using hacks. 
* Add a constructor to the class `JoorLanguage` to be able to inject specific jOOR compiler and jOOR script compiler
* Add getters for the jOOR compiler and jOOR script compiler
* Make the method `evalCode` public to give access to the generated code.
=> CAMEL-18977: camel-joor - Make the code more flexible for native mode

components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FromFileToFtpSplitParallelIT.java
Fix CI failure
```
Cancelling nested steps due to timeout
Sending interrupt signal to process
```
as you can see from https://ci-builds.apache.org/job/Camel/job/Camel%20JDK17/job/main/554/consoleText the test org.apache.camel.component.file.remote.integration.FromFileToFtpSplitParallelIT started the execution but didn't complete, locally I couldn't reproduce the same issue, but from time to time the test would hang during the shutdown of the route, I didn't notice any hang using the not-parallel tag.
=> Execute test sequentially

components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/RemoteFileIgnoreDoPollErrorTest.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/UriConfigurationTest.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FromFtpFilterIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FromFtpRemoteFileFilterDirectoryIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FromFtpRemoteFileFilterIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FtpConsumerProcessStrategyIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FtpProducerConcurrentIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FtpProducerDoneFileNameIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FtpProducerTempFileExistIssueIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpConsumerProcessStrategyIT.java
- simplify assertions
- cleanup raw usages of parameterized objects
=> (chores) camel-ftp: test cleanups

components/camel-plc4x/src/main/java/org/apache/camel/component/plc4x/Plc4XEndpoint.java, components/camel-plc4x/src/test/java/org/apache/camel/component/plc4x/Plc4XComponentTest.java
After [this comment](https://github.com/apache/camel/pull/9254#issuecomment-1410312534) by @davsclaus I looked further into the Plc4XComponentTest which was inconsistently passing/failing. These changes should fix it.
=> camel-plc4x: Fixed inconsistently passing/failing unit test (CAMEL-18861)

parent/pom.xml
Remove duplicate jakarta-enterprise-cdi-api-version property
=> jakarta-enterprise-cdi-api-version property is listed twice in parent/pom.xml

docs/user-manual/modules/ROOT/pages/camel-4-migration-guide.adoc
Add note to migration guide about hapi-fhir upgrade
=> CAMEL-18915: add note to migration guide about hapi-fhir upgrade

camel-dependencies/pom.xml, components/camel-zookeeper-master/src/main/java/org/apache/camel/component/zookeepermaster/group/internal/ZooKeeperGroup.java, parent/pom.xml
One test in camel spring boot failed due to the curator version used, zookeeper:3.8.1 used in camel is not compatible with curator:4.3.0.
Updating the curator version solves issues on camel-spring-boot and tests on camel-zookeeper and camel-zookeeper-master are successful. ListenerContainer was deprecated in 4.x  and removed in 5.x.
=> Bump curator version

camel-dependencies/pom.xml, components/camel-google/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubProducer.java, parent/pom.xml
Upgrade Google Cloud libraries-bom to 26.1.6 to contain this fix for native build: https://github.com/googleapis/gax-java/commit/ccaf26537a189dacb9b3bb58760a4c6f6cd48a87
=> Upgrade Google Cloud libraries-bom to 26.1.6

components/camel-sql/src/main/java/org/apache/camel/processor/idempotent/jdbc/JdbcMessageIdRepository.java, components/camel-sql/src/main/java/org/apache/camel/processor/idempotent/jdbc/JdbcOrphanLockAwareIdempotentRepository.java, components/camel-sql/src/test/java/org/apache/camel/processor/idempotent/jdbc/JdbcMessageIdRepositoryTest.java
Rewrote `JdbcOrphanLockAwareIdempotentRepository::insert` to not rely on an exception. The exception caused problems with postgresql databases if `autosave=always` was not set.
=> Rewrite JdbcOrphanLockAwareIdempotentRepository::insert to not rely on exception

components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/OpenTelemetryTracer.java, components/camel-tracing/src/main/java/org/apache/camel/tracing/Tracer.java
Here we improve on the first [PR-9341](https://github.com/apache/camel/pull/9341)
- init of ContextPropagators is moved to it's own init method
- unnecessary code for init if **GlobalOpenTelemetry.get()** should fail is removed
GlobalOpenTelemetry.get() always falls itself back to **OpenTelemetry.noop()** so no need for us to try that ourselves.
=> Split init of contextPropagators to separate method.

camel-dependencies/pom.xml, components/camel-elasticsearch/src/test/java/org/apache/camel/component/es/integration/ElasticsearchTestSupport.java, parent/pom.xml
Fix for https://issues.apache.org/jira/browse/CAMEL-19070
The integration tests of the component `camel-elasticsearch` fail on the build pipeline and need to be fixed.
* Upgrade elasticsearch (server and client) to the latest version
* Increase the startup timeout from 60 seconds to 90 seconds to fit with a slow-build pipeline
=> CAMEL-19070: camel-elasticsearch - Increase startup timeout

core/camel-core-processor/src/main/java/org/apache/camel/processor/MulticastProcessor.java, core/camel-core/src/test/java/org/apache/camel/processor/MulticastCorrelationIdTest.java
Remove the correlationId from `subExchange` before copying the multicast result to the original Exchange. This seemed preferable to removing the id after it has been copied. This way an already present id will remain on the original exchange.
If this is fine I can also provide a PR for 3.x .
=> CAMEL-19066: Do not copy correlationId after multicast

test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/common/TestAWSCredentialsProvider.java
Changing the length of the password by at least 16 bytes, allows AWS test executions in FIPS enabled environments
=> Make AWS test credentials FIPS compliant

core/camel-core-processor/src/main/java/org/apache/camel/processor/Enricher.java, core/camel-core/src/test/java/org/apache/camel/processor/enricher/EnricherCorrelationIdTest.java
Do not copy correlationId to the result exchange after Enricher EIP.
=> CAMEL-19066: Do not copy correlationId after Enricher

core/camel-core/pom.xml, core/camel-core/src/test/java/org/apache/camel/builder/ExchangeBuilderTest.java, core/camel-core/src/test/java/org/apache/camel/catalog/RuntimeCamelCatalogTest.java, core/camel-core/src/test/java/org/apache/camel/component/log/LogEndpointTest.java, core/camel-core/src/test/java/org/apache/camel/impl/CamelProduceInterfaceEventNotifierTest.java, core/camel-core/src/test/java/org/apache/camel/impl/event/CamelEventsTimestampEnabledTest.java, core/camel-core/src/test/java/org/apache/camel/impl/event/EventNotifierEventsTest.java, core/camel-core/src/test/java/org/apache/camel/impl/event/EventNotifierExchangeCompletedTest.java, core/camel-core/src/test/java/org/apache/camel/impl/event/EventNotifierExchangeSentTest.java, core/camel-core/src/test/java/org/apache/camel/impl/event/EventNotifierFailureHandledEventsTest.java, core/camel-core/src/test/java/org/apache/camel/impl/event/EventNotifierIgnoreCamelContextInitEventsTest.java, core/camel-core/src/test/java/org/apache/camel/impl/event/EventNotifierRedeliveryEventsTest.java, core/camel-core/src/test/java/org/apache/camel/impl/event/EventNotifierServiceStoppingFailedEventTest.java, core/camel-core/src/test/java/org/apache/camel/impl/event/MultipleEventNotifierEventsTest.java, core/camel-core/src/test/java/org/apache/camel/impl/event/SimpleEventNotifierEventsTest.java, core/camel-core/src/test/java/org/apache/camel/processor/NavigateRouteTest.java, core/camel-core/src/test/resources/log4j2.properties, core/camel-support/src/main/java/org/apache/camel/throttling/ThrottlingExceptionRoutePolicy.java
fixes https://issues.apache.org/jira/browse/CAMEL-18988
Since we upgraded to surefire + failsafe M8, some of our tests have started to fail with `OutOfMemoryException`.
After a deeper analysis using JProfiler, it appears that there is no significant memory leak, only small ones, especially some `DefaultCamelContext` leaks.
* Restore the log level to info
* Fix main `DefaultCamelContext` leaks except for the Simple expression cache and the cache in `DefaultParameterMappingStrategy`.
* Add JVM options to allow future analysis if it happens again
=> CAMEL-18988: camel-core - tests failing due to OOM

core/camel-core-engine/src/main/docs/modules/eips/pages/aggregate-eip.adoc
Chapter CompletionAwareAggregationStrategy is not up-to-date, because CompletionAwareAggregationStrategy interface was removed in Camel 3.x and onCompletion method is now part of AggregationStrategy interface. See commit e441457951b7d7cb6ede65a62fd8460a6485e322.
=> Outdated reference to CompletionAwareAggregationStrategy in aggregate-eip.adoc

camel-dependencies/pom.xml, components/camel-aws/camel-aws-secrets-manager/pom.xml, components/camel-aws/camel-aws2-kms/pom.xml, components/camel-aws/camel-aws2-lambda/pom.xml, components/camel-aws/camel-aws2-sns/pom.xml, components/camel-bindy/pom.xml, core/camel-core/pom.xml, core/camel-core/src/test/resources/junit-platform.properties, parent/pom.xml
fixes https://issues.apache.org/jira/browse/CAMEL-18988 (part 2)
Since we upgraded to surefire + failsafe M8, some of our tests have started to fail with `OnOutOfMemoryError`.
In practice, only the JVM option `-XX:+HeapDumpOnOutOfMemoryError` is needed as a thread dump can be extracted from an `hprof` file.
* Ensure that an `hprof` file is always generated on OOME
* Remove duplicated JVM options
* Reduce the max pool size of the thread pool used to launch the tests to limit the impact on memory since there is no real memory leak so the OOMEs are likely due to an excessive amount of threads 
The heap size doesn't exceed 1 Go during the tests whereas it could reach 1.5 Go before the change.
=> CAMEL-18988: camel-core - tests failing due to OOM (part 2)

components/camel-bean/pom.xml, components/camel-bean/src/main/java/org/apache/camel/component/bean/BeanInfo.java, components/camel-bean/src/test/java/org/apache/camel/component/bean/BeanProcessorOverloadedMethodsWithBracketsTest.java, core/camel-core/src/test/java/org/apache/camel/processor/BeanProcessorOverloadedMethodsWithBracketsTest.java
BeanInfo.java should use StringHelper.betweenOuterPair instead of StringHelper.between while choosing overloaded method.
=> [CAMEL-19075] camel-bean. Incorrect choice of overloaded method with several arguments, if one of them has brackets.

tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/ExampleModel.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PrepareExampleMojo.java
The `camel-examples` project's [examples/README.adoc](https://github.com/apache/camel-examples/blob/main/examples/README.adoc) file contains some broken links. This is happening because some examples are grouped in a folder, for example the [aws](https://github.com/apache/camel-examples/tree/main/examples/aws) folder. The change I made provides a way for Mojo to correctly prepare example links when there is a grouping of examples by folder.
Reference: apache/camel-examples#123
=> Change Mojo for example projects

docs/main/modules/getting-started/pages/index.adoc
While reading the getting started documentation I found a typo. 
I fixed it in this PR.
=> Fix typo in getting started page

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultUnitOfWork.java, core/camel-support/src/main/java/org/apache/camel/support/MessageSupport.java
This one brings a bit more noticeable improvements: 
```
-- Patch
Mean: 469451.00000000006
Geometric mean: 469365.419127074
Standard deviation: 9040.590633858474
-- 4.0.0-M1
Mean: 428228.7589285715
Geometric mean: 427689.07627717144
Standard deviation: 21213.428138606254
```
=> CAMEL-19060: avoid extra work

components/camel-seda/src/main/java/org/apache/camel/component/seda/SedaEndpoint.java
This one seems to add a very small (but still measurable) throughput improvement for Seda by avoiding a few synchronized calls. It's part of several other perf patches I will be sending 
Compared w/ 4.0.0-M1 (both w/ 4 consumers and 1 producer): 
```
--- Patch
Mean: 484459.8571428573
Geometric mean: 484272.99632561835
Standard deviation: 13570.203212282813
--- 4.0.0-M1
Mean: 480957.58035714296
Geometric mean: 479545.8325907664
Standard deviation: 33212.22104132737
```
=> (perf chores) camel-seda: cache queue reference to avoid costly operations in the hot path

core/camel-support/src/main/java/org/apache/camel/support/cache/DefaultProducerCache.java, core/camel-support/src/main/java/org/apache/camel/support/cache/ServicePool.java
With this one, we get another nice performance improvement:
```
--- 4.0.0-SNAPSHOT (w/ single shot initialization check + local cache)
Minimum: 652933.0
Maximum: 763599.0
Mean: 720940.8750000001
Geometric mean: 720782.7857395237
Standard deviation: 14897.378438658043
-- 4.0.0-SNAPSHOT (w/ single shot initialization check) 
Minimum: 604363.0
Maximum: 738706.0
Mean: 690079.2589285716
Geometric mean: 689914.539795926
Standard deviation: 14777.32031672733
-- 4.0.0-SNAPSHOT (w/ current patches)
Minimum: 666288.0
Maximum: 736833.0
Mean: 682849.5803571424
Geometric mean: 682692.0184731855
Standard deviation: 14906.813491217838
-- 4.0.0-M1
Minimum: 314709.0
Maximum: 504790.0
Mean: 437547.0535714286
Geometric mean: 436218.60520058003
Standard deviation: 32919.50500783796
```
=> CAMEL-19058: adjust producer caching to reduce impacts of false sharing

components/camel-micrometer/src/main/docs/micrometer-component.adoc, components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/DistributionStatisticConfigFilter.java, components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/MicrometerConstants.java, components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/routepolicy/MicrometerRoutePolicy.java, components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/routepolicy/MicrometerRoutePolicyConfiguration.java, components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/routepolicy/MicrometerRoutePolicyFactory.java, components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/routepolicy/MicrometerRoutePolicyNamingStrategy.java, components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/messagehistory/ManagedMessageHistoryTest.java, components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/routepolicy/AbstractMicrometerRoutePolicyTest.java, components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/routepolicy/MicrometerRoutePolicyConfigrationTest.java, components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/routepolicy/SharedMicrometerRoutePolicyTest.java
Features for MicrometerRoutePolicy
Repair test
Allow users to use one MicrometerRoutePolicy instance for multiple routes. This is especially useful when using OSGI XML
Allow users to disable additional counters
Allow users to set up timers with advanced micrometer API settings
Written for all this tests
=> [CAMEL-19101] Features for Camel-Micrometer

camel-dependencies/pom.xml, parent/pom.xml
Update dependencies for the Spring Boot update to version 3.0.4.
Spring Boot 3.0.4 dependency updates are listed in https://github.com/spring-projects/spring-boot/releases/tag/v3.0.4.
Also see: https://github.com/apache/camel-spring-boot/pull/771
=> CAMEL-19110: Update with Spring Boot 3.0.4 dependencies

components/camel-dhis2/camel-dhis2-component/pom.xml
An invalid version is specified in the DHIS2 component `pom.xml`:
```
<groupId>org.apache.camel</groupId>
<artifactId>camel-api-component-maven-plugin</artifactId>
<version>${camelVersion}</version>
```
=> Fix version property in DHIS2 component

components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpConsumer.java, components/camel-platform-http-vertx/src/test/java/org/apache/camel/component/platform/http/vertx/VertxPlatformMultipleContentTypeTest.java
fixes https://issues.apache.org/jira/browse/CAMEL-19113
It would be nice to apply this fix also for `camel-3.18.x` branch.
=> CAMEL-19113 Platform-http-vertx: consume with comma separated values does not work

catalog/camel-catalog/src/main/java/org/apache/camel/catalog/CamelCatalog.java, catalog/camel-catalog/src/main/java/org/apache/camel/catalog/DefaultCamelCatalog.java, catalog/camel-catalog/src/test/java/org/apache/camel/catalog/CamelCatalogTest.java, catalog/camel-catalog/src/test/resources/org/apache/camel/catalog/bar/foo.txt, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Export.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportSpringBoot.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/CatalogLoader.java
=> CAMEL-19120: Export configurable template

components/camel-jms/src/test/java/org/apache/camel/component/jms/tx/JMSTransactionErrorHandlerTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/tx/JMSTransactionIsTransactedRedeliveredTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/tx/JMSTransactionRollbackTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/tx/JMSTransactionalClientTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/tx/JMSTransactionalClientWithRollbackTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/tx/TransactionErrorHandlerBuilderAsSpringBeanTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/tx/TransactionErrorHandlerCustomerSpringParserTest.java, components/camel-jms/src/test/resources/org/apache/camel/component/jms/tx/JMSTransactionErrorHandlerTest.xml, components/camel-jms/src/test/resources/org/apache/camel/component/jms/tx/JMSTransactionIsTransactedRedeliveredTest.xml, components/camel-jms/src/test/resources/org/apache/camel/component/jms/tx/JMSTransactionRollbackTest.xml, components/camel-jms/src/test/resources/org/apache/camel/component/jms/tx/JMSTransactionalClientTest.xml, components/camel-jms/src/test/resources/org/apache/camel/component/jms/tx/JMSTransactionalClientWithRollbackTest.xml, components/camel-jms/src/test/resources/org/apache/camel/component/jms/tx/TransactionErrorHandlerBuilderAsSpringBeanTest.xml, components/camel-jms/src/test/resources/org/apache/camel/component/jms/tx/TransactionErrorHandlerCustomerSpringParserTest.xml
Do not reuse queues and topic names to avoid concurrent tests from disturbing each other
=> (chores) camel-jms: avoid sharing unsafe resources

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
Given that `commandLine()` does not work on all platforms due to the following note `Note that the returned executable pathname and the arguments may be truncated on some platforms due to system limitations.` use picocli commandLine api.
=> Remove ProcessHandle...commandLine() usage

components/camel-dhis2/camel-dhis2-component/src/main/docs/dhis2-component.adoc, components/camel-dhis2/camel-dhis2-component/src/test/java/org/apache/camel/component/dhis2/Environment.java
Set bind mode to read-only which might resolve the Docker container permission error in the camel-dhis2 component during the Jenkins build.
=> CAMEL-19050: set bind mode to read-only in order to resolve permission error in Docker container

components/camel-spring-rabbitmq/src/main/docs/spring-rabbitmq-component.adoc, components/camel-spring-rabbitmq/src/main/java/org/apache/camel/component/springrabbit/DefaultMessagePropertiesConverter.java, components/camel-spring-rabbitmq/src/main/java/org/apache/camel/component/springrabbit/SpringRabbitMQConstants.java
=> deliveryTag -> For manual ack

components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/DataLakeComponent.java, components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/DataLakeConfiguration.java, components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/DataLakeConfigurationOptionsProxy.java, components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/DataLakeConstants.java, components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/DataLakeExchangeHeaders.java, components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/client/DataLakeClientFactory.java, components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/client/DataLakeFileClientWrapper.java, components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/operations/DataLakeDirectoryOperations.java, components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/operations/DataLakeFileOperations.java, components/camel-azure/camel-azure-storage-datalake/src/test/java/org/apache/camel/component/azure/storage/datalake/operations/DataLakeFileOperationTest.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/version/VersionList.java
- see CAMEL-19152 for a detailed description
- patched validateConfiguration() method in the component to accept string based configuration of auth parameters in addition to Java objects
- Added SAS token-based authentication as well as the usage of the default identity if enabled (disabled by default, prioritised if enabled)
=> Azure Data Lake - CAMEL-19152 additional file client header field + CAMEL-18636 additional auth options

components/camel-http-common/src/main/java/org/apache/camel/http/common/HttpHelper.java, components/camel-http/src/test/java/org/apache/camel/component/http/helper/HttpHelperTest.java
Fix for https://issues.apache.org/jira/browse/CAMEL-19171
When the endpoint URI has a trailing slash and the path starts with a slash, the generated URI contains 2 slashes instead of only one which was accepted by HttpComponents v4 but it is rejected by HttpComponents v5.
* Skip one slash one, when the endpoint URI has a trailing slash and the path to append starts with a slash
* Add a unit test to cover the use case
=> CAMEL-19171: camel-http - Prevent duplicating slashes in generated URI

camel-dependencies/pom.xml, components/camel-snakeyaml/src/main/java/org/apache/camel/component/snakeyaml/SnakeYAMLDataFormat.java, components/camel-snakeyaml/src/main/java/org/apache/camel/component/snakeyaml/custom/CustomClassLoaderConstructor.java, components/camel-snakeyaml/src/test/java/org/apache/camel/component/snakeyaml/SnakeYAMLDoSTest.java, parent/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/main/java/org/apache/camel/maven/generator/openapi/AbstractGenerateMojo.java
Fix for  https://issues.apache.org/jira/browse/CAMEL-19130
In order to get the latest improvements and bug fixes, we need to upgrade to snakeyaml 2.
* Updated the version of snakeyaml
* Upgared `camel-snakeyaml` and `camel-restdsl-openapi-plugin`
* Fixed some violations raised
=> CAMEL-19130: Upgrade to snakeyaml 2.x

tooling/openapi-rest-dsl-generator/pom.xml
There are some failing tests that seem to be related to the pom cleanup https://ci-builds.apache.org/job/Camel/job/Camel%20JDK17/job/main/688/testReport/org.apache.camel.generator.openapi/
* Add `jackson-databind`
* Exclude `jackson-core` from `apicurio-data-models` to prevent version conflicts
=> CAMEL-19062: openapi-rest-dsl-generator - Add jackson databind

components/camel-jira/src/main/java/org/apache/camel/component/jira/consumer/AbstractJiraConsumer.java, components/camel-jira/src/main/java/org/apache/camel/component/jira/consumer/NewCommentsConsumer.java, components/camel-jira/src/main/java/org/apache/camel/component/jira/consumer/NewIssuesConsumer.java, components/camel-jira/src/main/java/org/apache/camel/component/jira/consumer/WatchUpdatesConsumer.java, components/camel-jira/src/test/java/org/apache/camel/component/jira/consumer/NewCommentsConsumerTest.java, components/camel-jira/src/test/java/org/apache/camel/component/jira/consumer/NewIssuesConsumerTest.java, components/camel-jira/src/test/java/org/apache/camel/component/jira/consumer/WatchUpdatesConsumerTest.java
Backport #9589 to `camel-3.x`
- Issues returned are already ordered descendant - do not revert the order of issues a 2nd time
- Make sure to exit polling loop early when no further issues are returned (total # of issues returned is lower than query page size)
- Avoid duplicates in returned issue list
- Adjust query page size according to given max results limitation
- Fix ordering of mocked issue return values in unit tests (mocks should return issues in descendant order)
- Add more unit tests on new issues consumer (testing filter offset, pagination, duplicates)
=> CAMEL-19174: camel-jira - Fix duplicate messages created by Jira consumer

components/camel-infinispan/camel-infinispan-embedded/src/test/java/org/apache/camel/component/infinispan/embedded/InfinispanEmbeddedClusteredConsumerTest.java, components/camel-infinispan/camel-infinispan-embedded/src/test/java/org/apache/camel/component/infinispan/embedded/spring/SpringInfinispanEmbeddedIdempotentRepositorySpringTest.java
[Some tests](https://ci-builds.apache.org/job/Camel/job/Camel%20JDK17/job/main/692/testReport/) are failing on Jenkins because Infinispan doesn't support Jakarta Transactions
* Disable the tests that depend on JTA
=> Disable Infinispan tests depending on JTA

parent/pom.xml, pom.xml
Replaced a deprecated Maven property (ref: https://maven.apache.org/surefire-archives/surefire-2.22.1/maven-failsafe-plugin/verify-mojo.html#skipExec)
=> CAMEL-15520: replace deprecated maven property maven.test.skip.exec

components/camel-observation/src/main/java/org/apache/camel/observation/MicrometerObservationSpanAdapter.java, components/camel-observation/src/test/java/org/apache/camel/observation/ABCRouteTest.java, components/camel-observation/src/test/java/org/apache/camel/observation/CustomComponentNameRouteTest.java, components/camel-observation/src/test/java/org/apache/camel/observation/MulticastParallelRouteTest.java, components/camel-observation/src/test/java/org/apache/camel/observation/SpanProcessorsTest.java
without this change we are always creating an event when a log happens within a route. That corresponds to a log on a span and a counter on a metrics. The log statement is arbitrary and logs on spans should be meaningful and short in name. Same thing for metric names that should of super low cardinality. Since we can't ensure that the log statement follows these requirements (nor should we) we think that we should not set those entries on spans and create such counters.
=> Not setting events for log methods on routes

components/camel-azure/camel-azure-servicebus/src/main/java/org/apache/camel/component/azure/servicebus/ServiceBusConsumer.java, components/camel-azure/camel-azure-servicebus/src/main/java/org/apache/camel/component/azure/servicebus/client/ServiceBusClientFactory.java
If an exception occurred during Exchange processing, the exception must be rethrown in the message receive and error handlers to trigger the `ServiceBusReceiverAsyncClient` to abandon the message so that the message is requeued.
Fixes [CAMEL-19155](https://issues.apache.org/jira/browse/CAMEL-19155).
=> Explicitly complete/abandon Azure Service Bus messages

components/camel-aws/camel-aws2-cw/src/test/java/org/apache/camel/component/aws2/cw/CwComponentConfigurationTest.java
Remove accessKey configuration to make createEndpointWithoutSecretKeyAndAccessKeyConfiguration test correct
=> (chores) camel-aws2-cw: fix test for configuration without options

components/camel-http/src/test/java/org/apache/camel/component/http/HttpsAuthenticationTest.java
We would like to ensure that it is possible to manage authentication with a custom `httpContext`.
* Add a unit test to cover the use case where a custom `httpContext` is used to configure the authentication.
=> CAMEL-19184: camel-http - Add test for authentication with httpContext

components/camel-groovy/src/main/java/org/apache/camel/language/groovy/GroovyLanguage.java
Fix for https://issues.apache.org/jira/browse/CAMEL-19189
To use the Groovy language in native, we need to adapt the current code to be able to provide all the pre-compiled groovy classes at build time.
* Add a `Builder` class to be able to create an immutable instance of `GroovyLanguage` with all the precompiled Groovy expressions
=> CAMEL-19189: camel-groovy - Adapt the code for native mode

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd, components/camel-dynamic-router/src/main/java/org/apache/camel/component/dynamicrouter/DynamicRouterProcessor.java, components/camel-dynamic-router/src/test/java/org/apache/camel/component/dynamicrouter/DynamicRouterProcessorTest.java, components/camel-dynamic-router/src/test/java/org/apache/camel/component/dynamicrouter/integration/DynamicRouterSingleRouteTwoParticipantsIT.java, components/camel-dynamic-router/src/test/java/org/apache/camel/component/dynamicrouter/support/DynamicRouterTestSupport.java
CAMEL-19198: Added sorting logic to ensure dynamic router eip component filters are evaluated in order of their priority property
When filters are evaluated, the filters are now sorted by priority before being evaluated.  I will also submit a pull request for the 3.x branch.
- [x ] I formatted the code using `mvn -Pformat,fastinstall install && mvn …
=> CAMEL-19198: Added sorting logic to ensure dynamic router eip component filters are evaluated in order of their priority property

camel-dependencies/pom.xml, parent/pom.xml
This PR upgrades Hadoop to 3.3.5 for ensuring the HDFS component still works with the latest version of Hadoop. It's tested by the following command:
```
$ ./mvnw clean verify -f components/camel-hdfs/pom.xml
```
This PR doesn't require the corresponding JIRA issue since it's just a single dependency upgrade.
=> Upgrade Hadoop to version 3.3.5

test-infra/camel-test-infra-pulsar/src/test/java/org/apache/camel/test/infra/pulsar/services/PulsarLocalContainerService.java
This PR aligns the Pulsar container version used in the integration test with the dependency version. It's tested by the following commands:
```
$ ./mvnw clean install -f test-infra/camel-test-infra-pulsar/pom.xml
$ ./mvnw clean verify -f components/camel-pulsar/pom.xml
```
This PR doesn't require the corresponding JIRA issue since it's just a container version upgrade.
=> Align all Pulsar versions to 2.11.0

camel-dependencies/pom.xml, parent/pom.xml
This PR removes unnecessary property from parent/pom.xml in accordance with the deprecation of the Spark component. It is tested by the following command:
```
$ ./mvnw clean install -Pfastinstall
```
This PR doesn't require the corresponding JIRA issue since it's just a single property removal.
=> Remove unnecessary property due to deprecating the Spark component

components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/MicrometerConstants.java
The existing JavaClassName style naming convention is not in keeping with the Micrometer naming convention.
See https://micrometer.io/docs/concepts#_naming_meters for details.
=> CAMEL-19193 - Follow Micrometer meter naming conventions

components/camel-aws/camel-aws-cloudtrail/pom.xml, components/camel-aws/camel-aws-secrets-manager/pom.xml, components/camel-aws/camel-aws2-athena/pom.xml, components/camel-aws/camel-aws2-cw/pom.xml, components/camel-aws/camel-aws2-ddb/pom.xml, components/camel-aws/camel-aws2-ec2/pom.xml, components/camel-aws/camel-aws2-ecs/pom.xml, components/camel-aws/camel-aws2-eks/pom.xml, components/camel-aws/camel-aws2-iam/pom.xml, components/camel-aws/camel-aws2-lambda/pom.xml, components/camel-aws/camel-aws2-mq/pom.xml, components/camel-aws/camel-aws2-msk/pom.xml, components/camel-aws/camel-aws2-s3/pom.xml, components/camel-aws/camel-aws2-ses/pom.xml, components/camel-aws/camel-aws2-sns/pom.xml, components/camel-aws/camel-aws2-sqs/pom.xml, components/camel-dropbox/pom.xml, components/camel-google/camel-google-mail/pom.xml, components/camel-paho-mqtt5/pom.xml, components/camel-paho/pom.xml, components/camel-servicenow/camel-servicenow-component/pom.xml, components/camel-slack/pom.xml, components/camel-twitter/pom.xml, components/camel-undertow/pom.xml
There were a couple that couldn't be removed: 
- camel-aws2-kinesis
- camel-aws2-kms
- camel-aws2-sts
- camel-http
- camel-minio
- camel-salesforce
=> (chores) remove core-catalog dependency added as part of CAMEL-14499

components/camel-groovy/src/main/java/org/apache/camel/language/groovy/GroovyExpression.java, components/camel-groovy/src/main/java/org/apache/camel/language/groovy/GroovyShellFactory.java, components/camel-groovy/src/test/java/org/apache/camel/language/groovy/GroovyShellFactoryTest.java
When using groovy script, we sometime need to config some global variables without pollute the camelContext and exchange,  that say,  in every script we want to use not only the request, response, context, but also some other global variables, and don't want to put them in the header etc.
So we need a interface method to meet this request.
=> provide a way to define global groovy variables

components/camel-observation/src/main/java/org/apache/camel/observation/MicrometerObservationTracer.java, components/camel-observation/src/test/java/org/apache/camel/observation/ABCRouteTest.java, components/camel-observation/src/test/java/org/apache/camel/observation/CamelMicrometerObservationTestSupport.java, components/camel-observation/src/test/java/org/apache/camel/observation/ClientRecipientListRouteTest.java, components/camel-observation/src/test/java/org/apache/camel/observation/CurrentSpanTest.java, components/camel-observation/src/test/java/org/apache/camel/observation/CustomComponentNameRouteTest.java, components/camel-observation/src/test/java/org/apache/camel/observation/MulticastParallelRouteTest.java, components/camel-observation/src/test/java/org/apache/camel/observation/MulticastRouteTest.java, components/camel-observation/src/test/java/org/apache/camel/observation/RouteConcurrentTest.java, components/camel-observation/src/test/java/org/apache/camel/observation/SpanProcessorsTest.java, components/camel-observation/src/test/java/org/apache/camel/observation/TwoServiceTest.java, components/camel-observation/src/test/java/org/apache/camel/observation/TwoServiceWithExcludeTest.java, components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/ABCRouteTest.java, components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/ClientRecipientListRouteTest.java, components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/CurrentSpanTest.java, components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/CustomComponentNameRouteTest.java, components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/MulticastParallelRouteTest.java, components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/MulticastRouteTest.java, components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/RouteConcurrentTest.java, components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/SpanProcessorsTest.java, components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/TwoServiceTest.java, components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/TwoServiceWithExcludeTest.java, components/camel-opentracing/pom.xml, components/camel-tracing/src/main/java/org/apache/camel/tracing/Tracer.java
this PR fixes the issue in production code and  updates tests for Micrometer Observations. 
IMPORTANT: OpenTracing module has its tests skipped with this PR
fixes https://issues.apache.org/jira/browse/CAMEL-19124
=> Tracer doesn't continue spans for AbstractInternalSpanDecorator

components/camel-hdfs/src/main/docs/hdfs-component.adoc, components/camel-hdfs/src/main/java/org/apache/camel/component/hdfs/DefaultHdfsFile.java, components/camel-hdfs/src/main/java/org/apache/camel/component/hdfs/HdfsWritableFactories.java, components/camel-hdfs/src/main/java/org/apache/camel/component/hdfs/WritableType.java, components/camel-hdfs/src/test/java/org/apache/camel/component/hdfs/HdfsProducerTest.java
The HDFS component supports most of Hadoop Writables corresponding to Java primary types, but it only doesn't support ShortWritable for some reason. This PR adds that support to the HDFS component.
=> CAMEL-19214: camel-hdfs - Add ShortWritable support to the HDFS component

components/camel-kudu/src/main/java/org/apache/camel/component/kudu/KuduConstants.java, components/camel-kudu/src/main/java/org/apache/camel/component/kudu/KuduProducer.java, components/camel-kudu/src/main/java/org/apache/camel/component/kudu/KuduUtils.java, components/camel-kudu/src/test/java/org/apache/camel/component/kudu/KuduScanTest.java
Currently, the scan operation of the Kudu producer scans entire table and sets the whole results to the message body, but it's inefficient or not practical if the table is large. This PR adds predicate support to the scan operation so that users can filter the results.
=> CAMEL-19216: camel-kudu - add predicate support to the scan operation

components/camel-kudu/src/main/java/org/apache/camel/component/kudu/KuduConstants.java, components/camel-kudu/src/main/java/org/apache/camel/component/kudu/KuduProducer.java, components/camel-kudu/src/main/java/org/apache/camel/component/kudu/KuduUtils.java, components/camel-kudu/src/test/java/org/apache/camel/component/kudu/KuduScanTest.java
In addition to CAMEL-19216, this PR adds the following functionalities to the scan operation of the Kudu producer for more efficient scanning:
* filter columns
* limit the number of results
=> CAMEL-19219: camel-kudu - add projection and limit support to the scan operation

core/camel-api/src/main/java/org/apache/camel/ExtendedCamelContext.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultCamelContextExtension.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/SimpleCamelContext.java, core/camel-core-engine/src/generated/java/org/apache/camel/impl/ExtendedCamelContextConfigurer.java, core/camel-core-engine/src/main/java/org/apache/camel/impl/lw/LightweightCamelContextExtension.java, core/camel-main/src/main/java/org/apache/camel/main/DefaultConfigurationConfigurer.java, dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/KameletMain.java
This is a proposed way to make the access to the ExtendedExchange plugins uniform. At first, this only implements this for the CliConnectorFactory. If accepted, I'll implement the same pattern for the others.
=> CAMEL-15105: make the CLI ConnectorFactory a plugin of the context

tooling/maven/camel-api-component-maven-plugin/src/main/resources/api-collection.vm
https://issues.apache.org/jira/browse/CAMEL-19233
Removed explicit generic types, fixed duplicated import, made use of EnumMap instead of HashMap.
Tested on my beloved AS2.  I rebuilt the plugin and changed the file as2.json. That triggered the regeneration of the sources in the build of AS2. New AS2ApiCollection file is OK.
Please note that the regeneration of the sources for collections must be forced.
=> CAMEL-19233: changed code generation for <component>ApiCollection

core/camel-util/src/main/java/org/apache/camel/util/URISupport.java, core/camel-xml-io/src/main/java/org/apache/camel/xml/in/BaseParser.java, core/camel-xml-io/src/test/java/org/apache/camel/xml/in/ModelParserTest.java, core/camel-xml-jaxb/src/main/java/org/apache/camel/xml/jaxb/JaxbHelper.java
CAMEL-19173.
In new XML DSLs removes spaces before parameter names, so long URIs can be split into lines, similar to https://camel.apache.org/manual/faq/how-do-i-configure-endpoints.html#HowdoIconfigureendpoints-Configuringlongurisusingnewlines
=> CAMEL-19173 - Splitting long uris in XML DSLs

dsl/camel-java-joor-dsl/src/main/java/org/apache/camel/dsl/java/joor/CompilationUnit.java, dsl/camel-java-joor-dsl/src/test/java/org/apache/camel/dsl/java/joor/CompilationUnitTest.java
Fix for https://issues.apache.org/jira/browse/CAMEL-19245
Up to now, the only way to get the inner and anonymous classes that have been compiled is by using reflection/introspection while it could be simplified by adding new methods.
* Add a method allowing to get all the compiled classes.
* Add some unit tests to ensure that it works as expected
=> CAMEL-19245: camel-java-joor-dsl - Provide the compiled classes

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/AS2SignedDataGenerator.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/util/AS2HeaderUtils.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/util/DispositionNotificationContentUtils.java, components/camel-bean-validator/src/main/java/org/apache/camel/component/bean/validator/BeanValidationException.java, components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/BindyKeyValuePairFactory.java, components/camel-cm-sms/src/main/java/org/apache/camel/component/cm/client/SMSMessage.java, components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400PgmProducer.java, components/camel-kamelet/src/main/java/org/apache/camel/component/kamelet/Kamelet.java, components/camel-nats/src/main/java/org/apache/camel/component/nats/NatsConfiguration.java, components/camel-olingo4/camel-olingo4-api/src/main/java/org/apache/camel/component/olingo4/api/impl/Olingo4AppImpl.java, components/camel-snmp/src/main/java/org/apache/camel/component/snmp/SnmpConverters.java, components/camel-xpath/src/main/java/org/apache/camel/language/xpath/DefaultNamespaceContext.java
Replaced the concatenation as an argument of StringBuilder.append() call with the chain of StringBuilder.append() calls. Converted single char strings to chars. PR for components
Under the hood each string concatenation is translated to a temporary StringBuilder and for the result its toString() value is assigned. We can avoid these temp StringBuilders.
=> Replaced the concatenation as an argument of StringBuilder.append() calls

tooling/openapi-rest-dsl-generator/src/main/java/org/apache/camel/generator/openapi/MethodBodySourceCodeEmitter.java, tooling/openapi-rest-dsl-generator/src/main/java/org/apache/camel/generator/openapi/OperationVisitor.java, tooling/openapi-rest-dsl-generator/src/main/java/org/apache/camel/generator/openapi/RestDefinitionEmitter.java
Fix for code inspection "initial size for Collection.toArray() should be zero". Related to performance. PR for tooling
#Justification
Reports Collection.toArray() calls not in the preferred style, and suggests applying the preferred style.
There are two styles to convert a collection to an array:
A pre-sized array, for example, c.toArray(new String[c.size()])
An empty array, for example, c.toArray(new String[0])
In older Java versions, using a pre-sized array was recommended, as the reflection call necessary to create an array of proper size was quite slow.
However, since late updates of OpenJDK 6, this call was intrinsified, making the performance of the empty array version the same, and sometimes even better, compared to the pre-sized version. Also, passing a pre-sized array is …
=> Fix for code inspection "initial size for Collection.toArray() should  be zero". Related to performance. PR for tooling

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/util/AS2HeaderUtils.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/util/DispositionNotificationContentUtils.java, components/camel-bean/src/main/java/org/apache/camel/component/bean/BeanInfo.java, components/camel-couchbase/src/main/java/org/apache/camel/component/couchbase/CouchbaseEndpoint.java, components/camel-disruptor/src/main/java/org/apache/camel/component/disruptor/DisruptorReference.java, components/camel-facebook/src/main/java/org/apache/camel/component/facebook/FacebookConsumer.java, components/camel-facebook/src/main/java/org/apache/camel/component/facebook/FacebookEndpoint.java, components/camel-facebook/src/main/java/org/apache/camel/component/facebook/FacebookProducer.java, components/camel-facebook/src/main/java/org/apache/camel/component/facebook/data/FacebookMethodsTypeHelper.java, components/camel-flink/src/main/java/org/apache/camel/component/flink/DataSetFlinkProducer.java, components/camel-flink/src/main/java/org/apache/camel/component/flink/annotations/AnnotatedDataSetCallback.java, components/camel-gson/src/main/java/org/apache/camel/component/gson/GsonDataFormat.java, components/camel-jetty-common/src/main/java/org/apache/camel/component/jetty/JettyHttpComponent.java, components/camel-jsonpath/src/main/java/org/apache/camel/jsonpath/easypredicate/EasyPredicateParser.java, components/camel-mail/src/main/java/org/apache/camel/component/mail/MailBinding.java, components/camel-mail/src/main/java/org/apache/camel/component/mail/MailConsumer.java, components/camel-mail/src/main/java/org/apache/camel/component/mail/MailConverters.java, components/camel-mock/src/main/java/org/apache/camel/component/mock/MockValueBuilder.java, components/camel-robotframework/src/main/java/org/apache/camel/component/robotframework/RobotFrameworkArguments.java, components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/SalesforceReportResultsToListConverter.java, components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/client/AbstractClientBase.java, components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppDataSmCommand.java, components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppSubmitMultiCommand.java, components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppSubmitSmCommand.java, components/camel-soap/src/main/java/org/apache/camel/dataformat/soap/name/ServiceInterfaceStrategy.java, components/camel-spring-main/src/main/java/org/apache/camel/spring/Main.java
Fix for code inspection "initial size for Collection.toArray() should be zero". Related to performance. PR for components
#Justification
Reports Collection.toArray() calls not in the preferred style, and suggests applying the preferred style.
There are two styles to convert a collection to an array:
A pre-sized array, for example, c.toArray(new String[c.size()])
An empty array, for example, c.toArray(new String[0])
In older Java versions, using a pre-sized array was recommended, as the reflection call necessary to create an array of proper size was quite slow.
However, since late updates of OpenJDK 6, this call was intrinsified, making the performance of the empty array version the same, and sometimes even better, compared to the pre-sized version. Also, passing a pre-sized array is …
=> Fix for code inspection "initial size for Collection.toArray() should be zero". PR for components

core/camel-api/src/main/java/org/apache/camel/support/jsse/BaseSSLContextParameters.java, core/camel-api/src/main/java/org/apache/camel/support/jsse/FilterParameters.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/IntrospectionSupport.java, core/camel-base/src/main/java/org/apache/camel/impl/converter/AnnotationTypeConverterLoader.java, core/camel-core-catalog/src/main/java/org/apache/camel/catalog/impl/AbstractCamelCatalog.java, core/camel-core-xml/src/main/java/org/apache/camel/core/xml/AbstractCamelContextFactoryBean.java, core/camel-management/src/main/java/org/apache/camel/management/DefaultManagementAgent.java, core/camel-management/src/main/java/org/apache/camel/management/mbean/ManagedEventNotifier.java, core/camel-support/src/main/java/org/apache/camel/support/PropertyBindingSupport.java, core/camel-support/src/main/java/org/apache/camel/support/builder/ValueBuilder.java, core/camel-support/src/main/java/org/apache/camel/support/component/ApiMethodHelper.java, core/camel-support/src/main/java/org/apache/camel/support/component/ApiMethodParser.java, core/camel-support/src/main/java/org/apache/camel/support/management/MBeanInfoAssembler.java, core/camel-util/src/main/java/org/apache/camel/util/AntPathMatcher.java, core/camel-util/src/main/java/org/apache/camel/util/HostUtils.java, core/camel-util/src/main/java/org/apache/camel/util/StringQuoteHelper.java
Fix for code inspection "initial size for Collection.toArray() should be zero". Related to performance. PR for core
#Justification
Reports Collection.toArray() calls not in the preferred style, and suggests applying the preferred style.
There are two styles to convert a collection to an array:
A pre-sized array, for example, c.toArray(new String[c.size()])
An empty array, for example, c.toArray(new String[0])
In older Java versions, using a pre-sized array was recommended, as the reflection call necessary to create an array of proper size was quite slow.
However, since late updates of OpenJDK 6, this call was intrinsified, making the performance of the empty array version the same, and sometimes even better, compared to the pre-sized version. Also, passing a pre-sized array is dangerous …
=> Fix for code inspection "initial size for Collection.toArray() should be zero". PR for core

tooling/maven/camel-restdsl-openapi-plugin/src/it/expanded-v3-yaml/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-dto-v3/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-dto/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-v3-yaml/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-v3/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-xml-dto-v3/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-xml-dto/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-xml-v3/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-xml/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-yaml-dto-v3/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-yaml-kamelet-v3/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-yaml-v3/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/main/java/org/apache/camel/maven/generator/openapi/AbstractGenerateMojo.java
Generated DTOs will be generated without timestamp since swagger-codegen does not fully support jakarta yet.
Should we use openapi codegen maven plugin instead of swagger?
=> Use jakarta API in ITs

components/camel-ignite/src/main/java/org/apache/camel/component/ignite/IgniteConstants.java, components/camel-ignite/src/main/java/org/apache/camel/component/ignite/cache/IgniteCacheOperation.java, components/camel-ignite/src/main/java/org/apache/camel/component/ignite/cache/IgniteCacheProducer.java, components/camel-ignite/src/test/java/org/apache/camel/component/ignite/IgniteCacheTest.java
Currently, the Ignite Cache component doesn't support some operations provided by Ignite itself. This PR adds the REPLACE operation to the producer as the first step.
=> CAMEL-19286: camel-ignite - Support the REPLACE operation in the Ignite Cache Producer

components/camel-micrometer/src/main/docs/micrometer-component.adoc
Add the default Camel metrics on the micrometer component documentation.
=> doc: Add default camel metrics to micrometer component

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/SyncCommitManager.java
Bug CAMEL-18985 is caused by [SyncCommitManager.commit()](https://github.com/apache/camel/blob/camel-3.20.x/components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/SyncCommitManager.java#L48) method which doesn't have logic to check whether auto-commit is enabled. As result of this [KafkaConsumer.commitSync()](https://kafka.apache.org/33/javadoc/org/apache/kafka/clients/consumer/KafkaConsumer.html#commitSync()) method is getting called in scope of the [KafkaFetchRecords.startPolling()](https://github.com/apache/camel/blob/camel-3.20.x/components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java#L343) method. The `KafkaConsumer.commitSync()` method commits offsets returned on the *last* `poll()` for all the subscribed list of topics …
=> [CAMEL-18985] Updated `SyncCommitManager` to perform offsets auto-commit only if it's enabled.

core/camel-support/src/main/java/org/apache/camel/support/AbstractExchange.java
Java's `System.arraycopy` is instrinsified, so, in theory, it should provide better performance (when supported/available on the platform/etc) at best and equivalent performance to the existing one at worst.
Running on my test HW, it seems to indicate a small performance gain compared to existing code:
W/ this:
`
Geometric mean: 714894.9672412889
Standard deviation: 39656.14503166896
`
Baseline
`
Geometric mean: 666166.262717514
Standard deviation: 53664.56234237712
` 
But it was not an extensive test, so the results are probably overly dramatic here.
=> (chores) performance: use native array copying which may benefit from intrinsic functions

core/camel-core-processor/src/main/java/org/apache/camel/processor/Enricher.java, core/camel-core-processor/src/main/java/org/apache/camel/processor/MulticastProcessor.java, core/camel-core/src/test/java/org/apache/camel/processor/enricher/EnricherCorrelationIdTest.java
Previously (before patch d4626e9d9c82c490bf8a49e09c34b6d54492824a) the "copying" of the array was actually a merge operation. Due to the changes of the referenced patch, the code now fully copies the array.
This patch reworks the way correlation IDs are copied, introduced as part of CAMEL-19066, to retain the original correlation ID and behave like the previous code where this is needed.
=> (chores) camel-core: fix correlation ID handling.

components/camel-attachments/src/main/java/org/apache/camel/attachment/DefaultAttachmentMessage.java, components/camel-jms/src/main/java/org/apache/camel/component/jms/JmsMessage.java, components/camel-jms/src/main/java/org/apache/camel/component/jms/JmsMessageHelper.java, components/camel-sjms/src/main/java/org/apache/camel/component/sjms/SjmsMessage.java, components/camel-sjms/src/main/java/org/apache/camel/component/sjms/jms/JmsMessageHelper.java, core/camel-api/src/main/java/org/apache/camel/Message.java, core/camel-api/src/main/java/org/apache/camel/trait/message/MessageTrait.java, core/camel-api/src/main/java/org/apache/camel/trait/message/RedeliveryTraitPayload.java, core/camel-support/src/main/java/org/apache/camel/support/AbstractExchange.java, core/camel-support/src/main/java/org/apache/camel/support/DefaultMessage.java, core/camel-support/src/main/java/org/apache/camel/support/DefaultPooledExchange.java, core/camel-support/src/main/java/org/apache/camel/support/MessageHelper.java, core/camel-support/src/main/java/org/apache/camel/support/MessageSupport.java, core/camel-support/src/test/java/org/apache/camel/support/MessageHelperTest.java
This introduces a trait that works similarly to the internal properties one in the Exchange so that we carry certain details about the message without relying on type specifications.
Among other things this:
- avoids unnecessarily recreating the DefaultMessage multiple times
- moved the data type aware checks out of the hot path
- reworks the isTransactedRedelivered to avoid costlier checks for specific message types
This superseds the proposed changes on #9432.
Additionally, this implements the same pattern of using an array for
internal properties as we already do on the Exchange. Subsequently, my
idea is to abstract this complex array manipulation in an specific class
so we can reuse code and simplify maintenance.
=> CAMEL-19058: rework the Message to avoid hitting the type-check scalability issue

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
Resolved an issue - jbang just ignored `beans.yaml` from example and added it as classpath resource instead of route definition.
=> CAMEL-19306: camel-jbang - added beans definition as known yaml file

components/camel-as2/camel-as2-component/pom.xml
@oscerd @davsclaus 
The nightly build may fail because of this line in POM. Found this issue while back porting HTTPS for AS2 into came-3.x branch
You may want to ask: how could it happen? I disabled auto reimport of the project in the event of POM changes and forgot to reload it manually.
My bad, sorry
=> CAMEL-17946 candidate hotfix for AS2 POM. Sorry

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/AS2ClientManager.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/AS2MediaType.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/AS2MimeType.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/ApplicationEDIFACTEntity.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/ApplicationEDIX12Entity.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/ApplicationEntity.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/ApplicationXMLEntity.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/EntityParser.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/util/EntityUtils.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/util/HttpMessageUtils.java, components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/AS2MessageTest.java, components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/util/EntityUtilsTest.java, components/camel-as2/camel-as2-component/src/main/java/org/apache/camel/component/as2/AS2Configuration.java, components/camel-as2/camel-as2-component/src/main/java/org/apache/camel/component/as2/AS2Consumer.java, components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2ClientManagerIT.java, components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2ServerManagerIT.java
Introduced content-type application/xml for AS2.
Related to https://issues.apache.org/jira/browse/CAMEL-17495
Request for changes for "text/xml" was mentioned in the dialog in jira, but I can't see this type in RFC https://www.ietf.org/rfc/rfc4130.txt. So I didn't add support for "text/xml".
The class ApplicationEDIEntity was renamed to ApplicationEntity because now the common part of content type is "application/" after I added the type "application/xml". ApplicationEntity is parent for ApplicationXMLEntity among EDI specific classes.
Added a test for sender and for receiver. Tested against Mendelson, these changes in the property file aren't included.
=> CAMEL-17495 Added support of media type "application/xml" for AS2 component

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/AS2ClientManager.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/AS2MediaType.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/AS2MimeType.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/ApplicationEDIFACTEntity.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/ApplicationEDIX12Entity.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/ApplicationEntity.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/ApplicationXMLEntity.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/EntityParser.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/util/EntityUtils.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/util/HttpMessageUtils.java, components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/AS2MessageTest.java, components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/util/EntityUtilsTest.java, components/camel-as2/camel-as2-component/src/main/java/org/apache/camel/component/as2/AS2Configuration.java, components/camel-as2/camel-as2-component/src/main/java/org/apache/camel/component/as2/AS2Consumer.java, components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2ClientManagerIT.java, components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2ServerManagerIT.java
Back ported into the branch camel-3.x
I used this PR as a basis https://github.com/apache/camel/pull/9999
Related to https://issues.apache.org/jira/browse/CAMEL-17495
The tests pass OK, sending to Mendelson server is OK
=> CAMEL-17495 Backport from the main branch. Added support of media type "application/xml" for AS2 component

core/camel-support/src/main/java/org/apache/camel/support/DefaultUuidGenerator.java, core/camel-support/src/main/java/org/apache/camel/support/MessageSupport.java
- Avoid setting the context twice (and a type check as well)
- Use final where possible
=> (chores) Minor cleanups

pom.xml
Excluding `camel-allcomponents` the resulting graph in dependency-track is much clear
=> Avoid duplicates when generating SBOM

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/MDCUnitOfWork.java, core/camel-support/src/main/java/org/apache/camel/support/UnitOfWorkHelper.java
Only the MDCUnitOfWork class implements the Service interface, so move the clear() call to the done method and avoid the type check
=> CAMEL-19319: fix a type check cache miss on the UnitOfWorkHelper

components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpBridgeEncodedPathTest.java, components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpGetWithParamAsExchangeHeaderTest.java
Tests were hanging in a couple of places. Cherry-picked some commits that seem to fix things.
=> Fix camel-netty-http tests for 3.18.x

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelCommand.java
=> CAMEL-19313: resolve option placeholder

core/camel-support/src/main/java/org/apache/camel/support/cache/DefaultProducerCache.java
This reworks the patch originally added on  907a9d0c08d40c5308bb440ec9ebaaa4d7544dc4 so that there is no side effect when handling singleton endpoints
=> CAMEL-19102: cache the producer and endpoint locally to avoid hitting the type check scalability issue

components/camel-observation/src/main/java/org/apache/camel/observation/MicrometerObservationTracer.java, parent/pom.xml
Camel Tracing assumes that you can close the scope multiple times. By fixing Micrometer Tracing's parent span checking we've broken it here. What we have to do is to temporarily put the parent span in scope again so that the what is represented in the parent observation is the same as what is there in thread local
=> Upgrades micrometer

components/camel-snmp/pom.xml, components/camel-snmp/src/test/java/org/apache/camel/component/snmp/TrapTest.java
minor change following https://github.com/apache/camel/pull/10101
1 occurrence of Thread.sleep is replaced with Awaitility.
=> CAMEL-19298 Snmp replacing Thread.sleep with Awaitility

core/camel-core/src/test/java/org/apache/camel/component/bean/BeanInfoAMoreComplexOverloadedTest.java, core/camel-core/src/test/java/org/apache/camel/component/bean/BeanInfoOverloadedWithSubTypeParamTest.java, core/camel-core/src/test/java/org/apache/camel/impl/ProducerCacheNonSingletonTest.java, core/camel-core/src/test/java/org/apache/camel/impl/engine/DefaultSupervisingRouteControllerTest.java, core/camel-core/src/test/java/org/apache/camel/impl/engine/IntrospectionSupportTest.java, core/camel-core/src/test/java/org/apache/camel/issues/RouteStartupFailShouldStopAlsoIssueTest.java, core/camel-core/src/test/java/org/apache/camel/processor/ConsumerRouteIdAwareTest.java, core/camel-core/src/test/java/org/apache/camel/processor/PipelineStepWithEventTest.java, core/camel-core/src/test/java/org/apache/camel/processor/onexception/OnExceptionUseOriginalMessageStreamTest.java, core/camel-main/src/test/java/org/apache/camel/main/MainSupervisingRouteControllerFilterFailToStartRouteTest.java, core/camel-main/src/test/java/org/apache/camel/main/MainSupervisingRouteControllerTest.java, core/camel-main/src/test/java/org/apache/camel/main/MainSupportCommandLineTest.java, core/camel-main/src/test/java/org/apache/camel/main/MainVetoTest.java, core/camel-management/src/test/java/org/apache/camel/management/LoadTimerTest.java, core/camel-management/src/test/java/org/apache/camel/management/ManagedNonManagedServiceTest.java, core/camel-management/src/test/java/org/apache/camel/management/ManagedRouteRestartTest.java, core/camel-management/src/test/java/org/apache/camel/management/ManagedSupervisingRouteControllerTest.java, core/camel-management/src/test/java/org/apache/camel/management/ManagedThrottlingExceptionRoutePolicyTest.java
These are mostly cosmetic, but help reduce noise when generating code quality reports
=> (chores) camel-core: use static inner classes in tests

core/camel-core-model/src/main/java/org/apache/camel/builder/NotifyBuilder.java, core/camel-core/src/test/java/org/apache/camel/processor/PipelineStepWithEventTest.java
This should avoid them keeping a reference to the parent class, which provides a very small memory usage reduction in some cases
=> (chores) camel-core: use static inner classes

components/camel-observation/pom.xml, components/camel-observation/src/test/java/org/apache/camel/observation/RouteConcurrentTest.java
This also parallelizes the other tests, so it runs faster
=> (chores) camel-observation: fix RouteConcurrentTest which needs to run in isolation

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractDynamicRegistry.java, core/camel-core/src/test/java/org/apache/camel/impl/DefaultEndpointRegistryTest.java
=> CAMEL-19295 - Concurrency issues with dynamicMap in AbstractDynamicRegistry

components/camel-undertow/pom.xml, components/camel-undertow/src/test/java/org/apache/camel/component/undertow/UndertowHttpsSpringTest.java
The test uses a generic certificate that would fail the validation
Thanks Freeman for providing the fix
=> CAMEL-19365: disable endpoint verification

components/camel-rest-openapi/src/main/java/org/apache/camel/component/rest/openapi/RestOpenApiEndpoint.java, components/camel-rest-openapi/src/test/java/org/apache/camel/component/rest/openapi/RestOpenApiBean.java, components/camel-rest-openapi/src/test/java/org/apache/camel/component/rest/openapi/RestOpenApiComponentTest.java
fixes https://issues.apache.org/jira/browse/CAMEL-19364
The swagger.io.v3 library accepts String uri locations for parsing OpenApi.json file. Therefore if "classpath:", "bean:", .. format is used for the url, the library can not resolve the data. (Previously used implementation - Apucurito - was accepting inputStream -> which allowd Camel to handle resolving in the component. 
This PR fixes the problem on Camel side by resolviing the URI of the data in a way that Sawgger API can find them. In case of "bean:" it means to copy data provided by the bean into tmp file and send URI of the file to the Swagger API.
I'd say that this fix is temporary (yet working completely) until the time, the swagger.io.v3 changes API to provide an input stream instead of location String)
I added tests to cover …
=> CAMEL-19364 Rest-openapi: lookup mechanism does not work 

components/camel-file/src/main/java/org/apache/camel/component/file/strategy/FileChangedExclusiveReadLockStrategy.java
If a file is copied with the original lastModified date, files are processes instantly. Also the file change detection is disabled if a copy takes more than minAge time. Instead of comparing startTime with lastModified on each iteration we are comparing it with now(). If files are created anew this should be the same behaviour, and files copied with preserved lastModifed are still correctly checked.
=> CAMEL-19378: File Changed ReadLock Strategy with minAge only looks for lastModified

docs/user-manual/modules/ROOT/pages/notify-builder.adoc
Just a simple typo fix in the documentation.
In the "Notifybuilder API" explanation, the description of `matches` has the "This operation returns immediately" phrase repeated.
=> Remove duplicate phrase in notify-builder.adoc

core/camel-core/src/test/java/org/apache/camel/impl/DefaultEndpointRegistryTest.java, core/camel-core/src/test/java/org/apache/camel/support/DefaultLRUCacheFactoryTest.java, core/camel-support/src/main/java/org/apache/camel/support/DefaultLRUCacheFactory.java
=> CAMEL-19295: Basic thread-safe LRU cache

camel-dependencies/pom.xml, components/camel-elasticsearch/pom.xml, parent/pom.xml
The integration tests of the component `camel-elasticsearch` fail due to a `NoClassDefFoundError: com/fasterxml/jackson/core/StreamReadConstraints`, this class has actually a different package name in Jackson 2.15.
* Downgrade the version of Jackson specifically for the component `camel-elasticsearch` until a version of `elasticsearch-java` supports Jackson 2.15.
=> camel-elasticsearch: Downgrade the jackson version to 2.14.3

core/camel-util/src/main/java/org/apache/camel/util/URIScanner.java, core/camel-util/src/main/java/org/apache/camel/util/URISupport.java
On my test machine, the throughput for a test that resolves the URI every single time (as is usual) increased by about 30k exchanges/sec (~3% improvement). In a test machine, I see the following with JMH:
Baseline:
```
Benchmark                               Mode  Cnt       Score      Error  Units
URISupportTest.normalizeFastUri           ss   20   71344.492 ± 1473.562  us/op
URISupportTest.normalizeFastUriWithRAW    ss   20  106508.881 ± 5621.090  us/op
```
This patch:
```
Benchmark                               Mode  Cnt      Score      Error  Units
URISupportTest.normalizeFastUri           ss   20  61024.779 ± 2892.150  us/op
URISupportTest.normalizeFastUriWithRAW    ss   20  96992.700 ± 6245.092  us/op
```
=> (chores) camel-util: cleanups and perf improvements

buildingtools/src/main/resources/camel-checkstyle-suppressions.xml
A checkstyle issue is raised which prevents the build to pass.
```
[camel-xml-io-dsl] [INFO] --- maven-checkstyle-plugin:3.1.2:checkstyle (default-cli) @ camel-xml-io-dsl ---
[camel-xml-io-dsl] [INFO] Starting audit...
[ERROR] /home/runner/work/camel/camel/dsl/camel-xml-io-dsl/src/generated/resources/META-INF/services/org/apache/camel/routes-loader/camel.xml:1: Missing a header - not enough lines in file. [RegexpHeader]
```
* Aligns the checkstyle configuration with the one of Camel 4.
=> CAMEL-19296: Configure checkstyle to prevent the violation

test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/ContainerLocalKafkaService.java
The name of the docker image of Kafka is misspelled
* Fixes the typo
=> CAMEL-19401: camel-test-infra-kafka - Fix Kafka docker image name

components/camel-cxf/camel-cxf-common/src/main/java/org/apache/camel/component/cxf/converter/CxfPayloadConverter.java
Fixes https://issues.apache.org/jira/browse/CAMEL-19399 (3.18)
If an error occurs while converting a value thanks to the CxfPayloadConverter, the value null is returned to let other fallback converters to try but if there are no such fallback converters, the cache of converters will keep the information that no converter exists which is not incorrect.
* Returns `MISS_VALUE` instead of `null` in case of an error to ensure that the result won't be stored in the cache.
=> CAMEL-19399: camel-cxf - Don't add entry in Converter cache on error

test-infra/camel-test-infra-artemis/src/test/java/org/apache/camel/test/infra/artemis/services/ArtemisService.java, test-infra/camel-test-infra-messaging-common/src/test/java/org/apache/camel/test/infra/messaging/services/MessagingServiceBuilder.java
Fix a typo in Artemis Test Infra configuration properties
=> Artemis test-infra typo on configuration properties

test-infra/camel-test-infra-artemis/src/test/java/org/apache/camel/test/infra/artemis/services/ArtemisService.java, test-infra/camel-test-infra-messaging-common/src/test/java/org/apache/camel/test/infra/messaging/services/MessagingServiceBuilder.java
Fix a typo in Artemis Test Infra configuration properties. Same fix as #10236.
=> Artemis test-infra typo on configuration properties (main branch)

components/camel-elasticsearch/src/test/java/org/apache/camel/component/es/integration/ElasticsearchScrollSearchIT.java, components/camel-elasticsearch/src/test/java/org/apache/camel/component/es/integration/ElasticsearchSizeLimitIT.java, components/camel-elasticsearch/src/test/java/org/apache/camel/component/es/integration/ElasticsearchTestSupport.java, test-infra/camel-test-infra-elasticsearch/src/test/java/org/apache/camel/test/infra/elasticsearch/common/ElasticSearchProperties.java, test-infra/camel-test-infra-elasticsearch/src/test/java/org/apache/camel/test/infra/elasticsearch/services/ElasticSearchLocalContainerService.java, test-infra/camel-test-infra-elasticsearch/src/test/java/org/apache/camel/test/infra/elasticsearch/services/ElasticSearchService.java, test-infra/camel-test-infra-elasticsearch/src/test/java/org/apache/camel/test/infra/elasticsearch/services/ElasticSearchServiceFactory.java, test-infra/camel-test-infra-elasticsearch/src/test/java/org/apache/camel/test/infra/elasticsearch/services/RemoteElasticSearchService.java
Fixes https://issues.apache.org/jira/browse/CAMEL-19400
The build on Jenkins takes between 7h and 8h which is much too long especially when we know that the max duration allowed is about 9 h.
* Adds a `SingletonService` to the `ElasticSearchServiceFactory`
* Adds the management of the authentication to the `ElasticSearchService`
* Adds the integration tests to use a singleton service to start only once an ES instance
In my local machine, with the old approach, the tests take about 200 seconds while it now takes about 50 seconds.
=> CAMEL-19400: camel-elasticsearch - Use singleton service to speed up

dsl/camel-endpointdsl/pom.xml
In the case of a parallel build, since `camel-catalog` is not explicitly defined as a dependency of `camel-endpointdsl`, they could be built in parallel which causes error of the following type:
```
[ERROR] Failed to execute goal org.apache.camel:camel-package-maven-plugin:4.0.0-SNAPSHOT:generate-endpoint-dsl (generate-endpoint-dsl) on project camel-endpointdsl: Execution generate-endpoint-dsl of goal org.apache.camel:camel-package-maven-plugin:4.0.0-SNAPSHOT:generate-endpoint-dsl failed: Error reading json file: /home/runner/work/camel/camel/dsl/camel-endpointdsl/target/../../../catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/lpr.json -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal …
```
=> Add camel-catalog as dependency to prevent parallel build failures

components/camel-sjms/src/test/java/org/apache/camel/component/sjms/consumer/JmsPollingConsumerTest.java
The test `JmsPollingConsumerTest.testJmsPollingConsumerNoWait` always [fails on Jenkins](https://ci-builds.apache.org/job/Camel/job/Camel%20JDK17/job/main/902/testReport/org.apache.camel.component.sjms.consumer/JmsPollingConsumerTest/testJmsPollingConsumerNoWait/) and needs to be fixed.
* Consumes messages produced to avoid side effects on other tests
* Uses the common pool instead of creating a new thread pool
=> CAMEL-18608: camel-sjms - Consumes messages before other tests

.github/actions/incremental-build/action.yaml, .github/actions/incremental-build/incremental-build.sh, .github/actions/install-mvnd/action.yml, .github/workflows/pr-build-main.yml
The build launched for each PR is much too long, let's experiment with an incremental build. The idea is to build only what is needed.
* Adds 2 new jobs that are the counterpart of `checkstyle` and `build` in incremental mode. As they are experimental, if they fail, it won't block the merge
* Builds everything like before if there are too many projects affected
* Launches the checkstyle command only on the affected projects
* Launches the fast build on the affected projects, their dependencies, and eventually the projects that depend on them
* Launches the test on the affected projects, and eventually the projects that depend on them
* Ignores changes in folder whose name starts with a dot like `.github`
Related Job: https://github.com/apache/camel/actions/runs/5214747419
| Command | …
=> Add an incremental build

core/camel-support/src/main/java/org/apache/camel/converter/stream/FileInputStreamCache.java
Do not use protected members on class marked as final
=> (chores) core: fix visibility mismatch

core/camel-support/src/main/java/org/apache/camel/support/CamelContextHelper.java
The method parseInt throws an NPE in case of null and the string has been checked for that alread
=> (chores) core: cleanup duplicated code

core/camel-support/src/main/java/org/apache/camel/support/component/ApiMethodHelper.java
List contains all can have O(M*N) complexity and it can be faster to simply create a HashSet and use it instead
=> (chores) core: list containsAll may perform poorly

components/camel-spring-rabbitmq/src/main/java/org/apache/camel/component/springrabbit/DefaultMessagePropertiesConverter.java, components/camel-spring-rabbitmq/src/main/java/org/apache/camel/component/springrabbit/SpringRabbitMQConstants.java, components/camel-spring-rabbitmq/src/test/java/org/apache/camel/component/springrabbit/integration/RabbitMQConsumerQueuesIT.java, components/camel-spring-rabbitmq/src/test/java/org/apache/camel/component/springrabbit/integration/RabbitMQProducerIT.java
The goal is to support all the most important RabbitMQ message properties by default (without the need to provide a custom ``MessagePropertiesConverter``). Those include the removed RabbitMQ component's message properties. Can simplify migration of applications from RabbitMQ to Spring RabbitMQ, which is a necessary step for migrating to Camel 4.
I had to modify how content type and timestamp were already handled. I found it better to use new Spring RabbitMQ constants rather than exchange constants. This is a more consistent approach imo. Both are optional and application-specific, like most of the other message properties.
This PR also includes a copy-paste bug fix in the method ``appendInputHeader``.
=> CAMEL-19417: camel-spring-rabbitmq - convert all message properties by default

components/camel-cxf/camel-cxf-soap/src/main/docs/cxf-component.adoc
The snippet was recently added by me. I must admit I was translating the Spring XML to Java rather mechanically and have not noticed that the whole section is about Spring XML. Sorry for the noise.
=> Remove a pointless Quarkus Java snippet inside a Spring XML docs section

components/camel-gson/pom.xml, components/camel-huawei/camel-huaweicloud-functiongraph/pom.xml, components/camel-huawei/camel-huaweicloud-iam/pom.xml, components/camel-huawei/camel-huaweicloud-obs/pom.xml, components/camel-ironmq/pom.xml, components/camel-pubnub/pom.xml, components/camel-slack/pom.xml, components/camel-splunk/pom.xml, components/camel-thrift/pom.xml, parent/pom.xml
https://issues.apache.org/jira/browse/CAMEL-19442
Motivation: building and testing individual components with distinct Gson versions leads to inconsistencies.
=> CAMEL-19442 - Manage Gson to build and test with a single deterministic version

components/camel-kafka/src/main/docs/kafka-component.adoc
Adding some explanation in camel-kafka documentation about how to setting kerberos config file (krb5.conf).
@orpiske as we talked about this relates to https://issues.apache.org/jira/browse/CAMEL-19412
=> CAMEL-19412: doc how to setting kerby file at camel-kafka

components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/BindyCsvFactory.java, components/camel-file/src/main/java/org/apache/camel/component/file/GenericFileSendDynamicAware.java, components/camel-openapi-java/src/main/java/org/apache/camel/openapi/RestOpenApiSupport.java
Solving some sonar issues about [replacing  String::replaceAll by String::replace](https://sonarcloud.io/organizations/apache/rules?open=java%3AS5361&rule_key=java%3AS5361).
=> (chores) Replace String::replaceAll by String::replace

camel-dependencies/pom.xml, components/camel-swift/pom.xml, parent/pom.xml
Fixes https://issues.apache.org/jira/browse/CAMEL-19408 (part 2)
After migrating to Upgrade to SRU2022-10.0.0, some tests failed due to [a reflection issue when serializing the MX messages in JSON ](https://github.com/prowide/prowide-iso20022/pull/83#issuecomment-1580150900).
* Upgrades to SRU2022-10.0.1 that contains the bug fix
* Removes the temporary workaround
=> CAMEL-19408: camel-swift - Upgrade to SRU2022-10.0.1

camel-dependencies/pom.xml, parent/pom.xml
We found an issue with *bouncycastle* 1.73 where it would fail checksum validation during pgp encryption/decryption. This is a regression from 1.72.2, and it appears to be fixed in 1.74.
=> CAMEL-19458: Bouncycastle 1.74 update

camel-dependencies/pom.xml, components/camel-etcd3/pom.xml, components/camel-grpc/pom.xml, components/camel-opentelemetry/pom.xml, components/camel-salesforce/camel-salesforce-component/pom.xml, parent/pom.xml
https://issues.apache.org/jira/browse/CAMEL-19451
We currently have grpc-version at 1.54.0 in camel-parent and it is used in several components. However gRPC artifacts are pulled also by some other components as transitive dependencies. The lack of dependency management causes that several different versions of gRPC artifacts are downloaded and used throughout Camel.
=> CAMEL-19451 - Import grpc-bom to build and test with a single deterministic set of gRPC dependencies

components/camel-spring-rabbitmq/src/main/java/org/apache/camel/component/springrabbit/SpringRabbitMQEndpoint.java
Fixes CAMEL-19373.
AsyncRabbitTemplate uses the receiveTimeout property for reply timeout.
> You can set the receiveTimeout property on the template to time out replies (it defaults to 30000 - 30 seconds). If a timeout occurs, the future is completed with an AmqpReplyTimeoutException.
(https://docs.spring.io/spring-amqp/reference/html/#async-template)
=> CAMEL-19373: camel-spring-rabbitmq - Fix reply timeout

components/camel-dynamic-router/src/test/java/org/apache/camel/component/dynamicrouter/DynamicRouterProducerTest.java
Adding dynamic router eip component asynchronous mode test because it was removed.
=> CAMEL-19457: Re-adding test because it was removed instead of fixed.

camel-dependencies/pom.xml, parent/pom.xml, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/ContainerLocalKafkaService.java
Fix for https://issues.apache.org/jira/browse/CAMEL-19464
Kafka 3.5 has just been released, we would like to upgrade to the latest version.
* Updates the version of Kafka to `3.5.0`
* Updates the version of the docker image to `confluentinc/cp-kafka:7.4.0`
=> CAMEL-19464: camel-kafka - Upgrade to 3.5.x

camel-dependencies/pom.xml, components/camel-elasticsearch/pom.xml, parent/pom.xml, test-infra/camel-test-infra-elasticsearch/src/test/java/org/apache/camel/test/infra/elasticsearch/services/ElasticSearchLocalContainerService.java
Fix for https://issues.apache.org/jira/browse/CAMEL-19490
Elastic search 8.8 has just been released, we would like to upgrade to the latest version.
* Updates the version of Elastic Search to `8.8.1`
* Updates the version of the docker image to `docker.elastic.co/elasticsearch/elasticsearch:8.8.1`
* Uses the default version of Jackson which is `2.15` as it is the version expected by the elastic search client
=> CAMEL-19490: camel-elasticsearch - Upgrade to 8.8.x

.mvn/extensions.xml
This PR addresses the requests on camel-dev ML to keep the old `fastinstall` profile in some form for backwards compatibility reasons. Hence this PR adds a small maven extension that does just that: when `-Pfastinstall` is present among maven command line arguments, the `full` profile is made inactive programmatically. Passing `-Dquickly` does the same.
=> Handle -Pfastinstall as an alias of -Dquickly

docs/main/modules/contributing/nav.adoc, docs/main/modules/contributing/pages/index.adoc
Given our recent build changes, I'm taking sometime this week to organize the contribution documentation. 
Some details are noted here: apache/camel-website#1017
=> (chores) doc: reorganize the contributing documentation

core/camel-core/src/test/java/org/apache/camel/processor/ThrottlerTest.java
This test is time-bound and that does not run well in shared environments
=> (chores) camel-core: prevent ThrottlerTest from running on GH

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/health/KafkaConsumerHealthCheckIT.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/health/KafkaHealthCheckTestSupport.java
The test was successful because 2 kafka instances were running, therefore the failure on P/Z.
@Balavva-Mirji
=> Fix test and use single kafka instance

components/camel-bean/src/main/java/org/apache/camel/component/bean/AbstractBeanProcessor.java
This ensures that the done callback will be called (or, at least, tried to be called) in the case of unhandled exceptions (a few rare cases involving Throwables)
=> CAMEL-19497: prevent unhandled exceptions from blocking indefinitely

core/camel-xml-io/src/main/java/org/apache/camel/xml/io/MXParser.java
=> CAMEL-19492: Fix modifier orders to comply with the JLS

components/camel-salesforce/pom.xml
v1.56.0 of the protoc-gen-grpc-jave now supports s390x. So supporting camel-salesforce components back on s390x.
=> Camel-Salesforce: s390x support

components/camel-lra/src/main/java/org/apache/camel/service/lra/LRAClient.java, components/camel-lra/src/main/java/org/apache/camel/service/lra/LRASagaService.java, components/camel-lra/src/test/java/org/apache/camel/service/lra/LRAClientTest.java, components/camel-lra/src/test/java/org/apache/camel/service/lra/LRASagaServiceTest.java
As a follow up on #10498 
The Saga EIP pattern is using rest based communication for interaction with the lra-coordinator (e.g. narayana). Although there are ways to secure the communication with the coordinator, this is not supported by the underlying code. Also, it is not possible to easily override some implementations, since they are created by internal constructors.
This change is targeting, that one can override (influence) the creation of the LRAClient in the LRASagaService. With this "extension", it is then possible to override some default behavior and for example you can set the HttpClient and use your own adjusted instance with an Authenticator or ssl-settings.
=> Add possibility to override LRAClient

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd, components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/HttpClientInitializerFactory.java, components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpSSLSNITest.java
Allows the SSL Server Name Indication to be configured using the SSLContextParameters.
=> CAMEL-19502 Netty4-http SNI configuration using SSLContextParameters

tooling/maven/camel-package-maven-plugin/src/it/HeaderSupport/pom.xml
This should force the integration test to use Java 17 as the base version
=> (chores) camel-package-maven-plugin: ensure a modern version of the compiler plugin

camel-dependencies/pom.xml, parent/pom.xml
This PR upgrades Hadoop to 3.3.6 so as to make sure the existing code works with the latest version of Hadoop.
No corresponding JIRA issue since it's just a dependency upgrade.
In addition to the command above, I ensured the existing tests succeeded with the following:
```
$ ./mvnw clean install -f test-infra/camel-test-infra-hdfs/pom.xml
$ ./mvnw clean install -f components/camel-hdfs/pom.xml
```
=> Upgrade to Hadoop 3.3.6

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/dataformats/parquetAvro.json, catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/models/parquetAvro.json, catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd, components/camel-parquet-avro/src/generated/resources/org/apache/camel/dataformat/parquet/avro/parquetAvro.json, components/camel-parquet-avro/src/main/docs/parquetAvro-dataformat.adoc, components/camel-parquet-avro/src/main/java/org/apache/camel/dataformat/parquet/avro/ParquetAvroDataFormat.java, components/camel-parquet-avro/src/test/java/org/apache/camel/dataformat/parquet/avro/ParquetAvroMarshalCompressionCodecTest.java, core/camel-core-model/src/generated/resources/org/apache/camel/model/dataformat/parquetAvro.json, core/camel-core-model/src/main/java/org/apache/camel/model/dataformat/ParquetAvroDataFormat.java, core/camel-xml-io/src/generated/java/org/apache/camel/xml/in/ModelParser.java, core/camel-xml-io/src/generated/java/org/apache/camel/xml/out/ModelWriter.java, core/camel-yaml-io/src/generated/java/org/apache/camel/yaml/out/ModelWriter.java, dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/generated/java/org/apache/camel/dsl/yaml/deserializers/ModelDeserializers.java, dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camel-yaml-dsl.json, dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camelYamlDsl.json
This PR adds other compression codecs than gzip to the Parquet-Avro data format for marshaling.
=> CAMEL-19571 - camel-parquet-avro: Add other compression codecs than gzip

components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpChangedReadLockIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpChmodDirectoryIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpChmodIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpConsumeTemplateIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpConsumerAutoCreateIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpConsumerDisconnectIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpConsumerProcessStrategyIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpConsumerWithCharsetIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpMoveWithOutMessageTest.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpProduceTempFileIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpProducerFileWithPathIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpProducerFileWithPathNoStepwiseIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpProducerMoveExistingIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpProducerWithCharsetIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpSetCipherIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpSetOperationsIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpSimpleConsumeIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpSimpleConsumeNoStartingDirIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpSimpleConsumeNotStepwiseIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpSimpleConsumeRecursiveIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpSimpleConsumeRecursiveNotStepwiseIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpSimpleConsumeStreamingIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpSimpleConsumeStreamingPartialReadIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpSimpleConsumeStreamingWithMultipleFilesIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpSimpleConsumeThroughProxyIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpSimpleIPV6ConsumeIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpSimpleProduceDisconnectIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpSimpleProduceIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpSimpleProduceThroughProxyIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/sftp/integration/SftpUseListFalseIT.java
=> CAMEL-19438: added missing knownHostsFile parameter

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/dataformats/parquetAvro.json, catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/models/parquetAvro.json, catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd, components/camel-parquet-avro/src/generated/resources/org/apache/camel/dataformat/parquet/avro/parquetAvro.json, components/camel-parquet-avro/src/main/docs/parquetAvro-dataformat.adoc, components/camel-parquet-avro/src/main/java/org/apache/camel/dataformat/parquet/avro/ParquetAvroDataFormat.java, components/camel-parquet-avro/src/test/java/org/apache/camel/dataformat/parquet/avro/ParquetAvroDataFormatWithoutUnmarshalTypeTest.java, core/camel-core-model/src/generated/resources/org/apache/camel/model/dataformat/parquetAvro.json, core/camel-core-model/src/main/java/org/apache/camel/model/dataformat/ParquetAvroDataFormat.java
This PR add a new functionality to camel-parquet-avro for (un)marshalling with Avro's GenericRecord instead of POJO so that users don't need to define a POJO corresponding to Parquet file's data structure.
=> CAMEL-19586: camel-parquet-avro - Allow users to unmarshal Parquet file into Avro's GenericRecords

core/camel-core/src/test/java/org/apache/camel/component/file/FileProducerCharsetUTFOptimizedTest.java
- separate test setup from execution
- add data cleanup after execution
=> (chores) camel-core: FileProducerCharsetUTFOptimizedTest cleanup

.github/workflows/component-pr.yaml, .github/workflows/pr-build-camel-3.yml, .github/workflows/pr-build-main.yml
The message still appears for PRs targeted to the main branch whereas the quick test is no more used
* Enable the workflow only for Camel 3
* Ignores github actions changes
=> (chores) cli: remove quick test in main

components/camel-observation/src/test/java/org/apache/camel/observation/CamelMicrometerObservationTestSupport.java, components/camel-observation/src/test/resources/log4j2.properties, components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/CamelOpenTelemetryTestSupport.java, components/camel-opentelemetry/src/test/resources/log4j2.properties, components/camel-tracing/src/main/java/org/apache/camel/tracing/ActiveSpanManager.java, components/camel-tracing/src/main/java/org/apache/camel/tracing/Tracer.java
the problem we have is that one of the spans in one of the tests (most probably MulticastRouteTest) is not being closed and the span is left in the test thread. Due to this other tests are failing.
This PR removes the workaround that conditionally closes scopes. With these changes we're always closing scopes even multiple times.
related to pr gh-10539
closes https://issues.apache.org/jira/browse/CAMEL-19569
=> Adding additional logging to scope creation and closing

core/camel-core/src/test/java/org/apache/camel/component/file/FilePollEnrichNoWaitTest.java
- adjust to send the messages earlier
- increase timeouts for reduced flakiness on slow hosts
=> (chores) camel-core: file test fixes and cleanups

core/camel-core/src/test/java/org/apache/camel/processor/ResequenceStreamNotIgnoreInvalidExchangesTest.java
- cleanup assertions
- increase timeouts for less flakiness on slow horts
=> (chores) camel-core: test cleanups on ResequenceStreamNotIgnoreInvalidExchangesTest

camel-dependencies/pom.xml, parent/pom.xml
Backporting upgrade from main to fix:
org.apache.xmlgraphics:batik-bridge (batik-bridge-1.15.jar)  │ CVE-2022-41704 │          │ 1.15              │ 1.16                           │ Apache XML Graphics Batik vulnerable to code execution via  │
│                                                              │                │          │                   │                                │ SVG                                                         │
│                                                              │                │          │                   │                                │ https://avd.aquasec.com/nvd/cve-2022-41704                  │
├──────────────────────────────────────────────────────────────┤                │          │                   │ …
=> Upgrade batik version to 1.16 (#9718)

components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/DefaultNettyHttpBinding.java
Netty seems to complain about the content-type header when dealing with multipart messages. This disables the header validation so that those headers can go through.
=> CAMEL-19568: disable header validation on camel-netty-http

camel-dependencies/pom.xml, parent/pom.xml
Main is already updated to Californium 2.8.0. This updates to Californium 2.7.4 to fix https://nvd.nist.gov/vuln/detail/CVE-2022-39368
I will open separate PRs for 3.21.x/3.20.x
=> Updating californium to 2.7.4

camel-dependencies/pom.xml, parent/pom.xml
Fixing two CVE issues:
com.hazelcast:hazelcast (hazelcast-5.2.1.jar) │ CVE-2023-33264 │ MEDIUM   │ 5.2.1             │ 5.0.4, 5.1.6, 5.2.3 │ Improper password mask
org.json:json (hazelcast-5.2.1.jar)           │ CVE-2022-45688 │ HIGH     │ 20220320          │ 20230227            │ json stack overflow vulnerability
Already fixed on main.
=> Updating Hazelcast to 5.2.4

camel-dependencies/pom.xml, parent/pom.xml
drill-jdbc-all shades many dependencies. 1.19.0 on 3.x downwards contains CVEs in jackson-databind (e.g. https://nvd.nist.gov/vuln/detail/CVE-2020-365180, guava, Netty, etc.
=> Updating drill to 1.21.1

camel-dependencies/pom.xml, parent/pom.xml
Backporting a fix for https://nvd.nist.gov/vuln/detail/CVE-2023-33008
=> Upgrade Johnzon JsonB to version 1.2.21

components/camel-aws/camel-aws2-kinesis/src/main/docs/aws2-kinesis-component.adoc
=> Consumer missed part fix

components/camel-xchange/src/test/java/org/apache/camel/component/xchange/account/AccountProducerTest.java, components/camel-xchange/src/test/java/org/apache/camel/component/xchange/market/MarketDataProducerTest.java, components/camel-xchange/src/test/java/org/apache/camel/component/xchange/metadata/MetaDataProducerTest.java
These tests do not run reliably on ASF CI, failing due to HTTP 415.
=> (chores) camel-xchange: prevent tests from running on ASF CI

tooling/maven/camel-package-maven-plugin/pom.xml
Removed the maven-compat dependency that was causing deprecation warnings.
=> [CAMEL-19462] remove maven-compat

docs/user-manual/modules/ROOT/pages/route-template.adoc
Fix the warning check:
```
YN0000: [build:antora  ] [build:antora-perf] [07:04:34.320] WARN (asciidoctor): skipping reference to missing attribute: color
```
=> fix(docs): add code notation

.github/actions/component-test/action.yaml, .github/actions/component-test/component-test.sh, .github/workflows/pr-comment.yml
When there are too many components to test, only the affected projects are tested so it can still be useful to be able to decide explicitly which components to test
* Restore the `component-test` github action since it can still be useful in some specific cases
=> (chores) ci: restore component-test

test-infra/camel-test-infra-artemis/src/test/java/org/apache/camel/test/infra/artemis/services/AbstractArtemisEmbeddedService.java, test-infra/camel-test-infra-artemis/src/test/java/org/apache/camel/test/infra/artemis/services/ArtemisAMQPService.java, test-infra/camel-test-infra-artemis/src/test/java/org/apache/camel/test/infra/artemis/services/ArtemisTCPAllProtocolsService.java, test-infra/camel-test-infra-artemis/src/test/java/org/apache/camel/test/infra/artemis/services/ArtemisVMService.java
- increase the maximum disk usage accepted: use the same disk size use configuration originally added as part of change 9d0108757c4f6c27817dd0ce4a07ad93abcff511
- prevent blocking on disk full: use the same disk-full behavior originally added as part of change dd18711c75992f6d8e279c1a260c1f5b56ff2739
=> (chores) camel-test-infra-artemis: hardening cleanups

components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsInOnlyDisableTimeToLiveTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsInOutDisableTimeToLiveTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/MyCoolBean.java
This reuses the same approach from another commit and applies to another similar test (ref.: 2396b3c4b8d7f1df0b411330e5497fb16bc669d0)
=> (chores) came-jms: avoid failing the test due to session being closed

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaProducer.java
The camel kafka component when provided with a custom worker pool is not used.
The KafkaProducer.java code in doStart() function doesn't check the configuration of whether a custom worker pool is provided or not. It directly goes ahead and creates a new one. This is now fixed by adding a check and using the worker pool if provided.
=> CAMEL-19650: Camel Kafka doesn't honor 'workerPool' configuration

components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirCapabilitiesIT.java, components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirConfigurationIT.java, components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirCreateIT.java, components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirCustomClientConfigurationIT.java, components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirDeleteIT.java, components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirExtraParametersIT.java, components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirHistoryIT.java, components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirLoadPageIT.java, components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirMetaIT.java, components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirOperationIT.java, components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirPatchIT.java, components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirReadIT.java, components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirSearchIT.java, components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirSimpleIT.java, components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirTransactionIT.java, components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirUpdateIT.java, components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirValidateIT.java, components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/Hl7v2PatientToFhirPatientIT.java
These tests are extremely slow and resource intensive, causing flakiness when running on the CI (which has slow nodes).
=> CAMEL-19659: prevent camel-fhir integration tests from running on ASF CI

test-infra/camel-test-infra-artemis/src/test/java/org/apache/camel/test/infra/artemis/services/ArtemisVMService.java
When running with a lot of threads, sometimes the tests hang while the broker is auto-deleting queues/addresses
=> CAMEL-19666: stop auto-deleting queues

components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsPriorityConsumerTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsProducerConcurrentTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsProducerConcurrentWithReplyTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsRequestReplyExclusiveReplyToConcurrentTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsRequestReplyTempQueueMultipleConsumersTest.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsRouteRequestReplyTest.java
- isolate test creating threads outside of the Pool
- isolate tests creating too many threads
=> CAMEL-19669: isolate heavy tests

parent/pom.xml
The upgrade was originally blocked by ARTEMIS-4338, but the issue is now resolved.
=> CAMEL-19561: upgrade Artemis to version 2.30.0

components/camel-olingo2/camel-olingo2-component/pom.xml
I'm getting the following error in building RC2 locally : 
```
[INFO] --- archetype:3.2.1:generate (generate-my-car-service) @ camel-olingo2 ---
[INFO] Generating project in Batch mode
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.036 s
[INFO] Finished at: 2023-07-28T11:08:52-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-archetype-plugin:3.2.1:generate (generate-my-car-service) on project camel-olingo2: Cannot invoke "org.apache.maven.artifact.repository.ArtifactRepository.getUrl()" because "repository" is null -> [Help 1]
[ERROR] …
```
=> Add archetypeCatalog setting of local to prevent repository==null error in generation

components/camel-csimple-joor/src/test/java/org/apache/camel/language/csimple/joor/OriginalSimpleTest.java
Re-enable some tests that are likely stable while disabling a few failing tests pending investigation in CAMEL-19681.
=> CAMEL-19680: re-enable camel-joor stable tests

components/camel-plc4x/src/test/java/org/apache/camel/component/plc4x/Plc4XComponentTagTest.java, components/camel-plc4x/src/test/java/org/apache/camel/component/plc4x/Plc4XComponentTest.java
Send synchronously to avoid the unpredictable behavior of sending async and not checking the result
=> (chores) camel-plc4x: fix test flakiness

test-infra/camel-test-infra-zookeeper/src/test/java/org/apache/camel/test/infra/zookeeper/services/ZooKeeperContainer.java
This PR upgrades Zookeeper Testcontainers to 3.8 for aligning its version with the one used by the camel-zookeeper component.
No corresponding JIRA issue since it's just a minor container version upgrade.
=> Upgrade Zookeeper Testcontainers to 3.8

parent/pom.xml
This PR removes unused property about jcommander version from parent/pom.xml.
No corresponding JIRA issue since it's just an unused property removal.
=> Remove unnecessary jcommander version property

test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/StrimziContainer.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/ZookeeperContainer.java
=> (chores) camel-test-infra-kafka: zookeeper container should be the same one used by Kafka

core/camel-api/src/main/java/org/apache/camel/ExchangeExtension.java, core/camel-support/src/main/java/org/apache/camel/support/ExchangeHelper.java, core/camel-support/src/main/java/org/apache/camel/support/ExtendedExchangeExtension.java
This could cause it to lose attachments when using multicast EIP
=> CAMEL-19675: fixed not copying safe copy properties

components/camel-velocity/src/main/docs/velocity-component.adoc
allowTemplateFromHeader=true is necessary to make the Velocity Context available from headers
=> Fix velocity-component.adoc

dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/pom.xml, tooling/maven/bom-generator-maven-plugin/pom.xml, tooling/maven/camel-api-component-maven-plugin/pom.xml, tooling/maven/camel-eip-documentation-enricher-maven-plugin/pom.xml, tooling/maven/sync-properties-maven-plugin/pom.xml
Updates to address the warning "Plugin depends on plexus-container-default, which is EOL"
1. Removed plexus-container-default dependencies from camel plugins.
2. Removed plexus dependencies since they are no longer used and doxia-site-renderer depends on plexus-container-default. Doxia hasn't been used in camel-api-component-maven-plugin since org.apache.camel.maven.DocumentGeneratorMojo was removed in camel-3.6.0
=> [Camel-19462] remove plexus-container-default

tooling/maven/bom-generator-maven-plugin/src/main/java/org/apache/camel/maven/bom/generator/BomGeneratorMojo.java
Removed the read-only element from parameters used or intended to be used in POM-specific configuration. otherwise maven displays a warning.
=> [CAMEL-19462] remove read-only element from parameters configured by the user

core/camel-api/src/main/java/org/apache/camel/support/jsse/JsseParameters.java
Add checks that keystore/trustore resources realy exists. We should call exist() method because in some cases resolveResource returns ResourceSupport object.
=> Jsse fix res check

components/camel-google/camel-google-bigquery/ReadMe.md
The links in the readme are not in the right format consequently they are not clickable
* Apply the markdown format to the links which is `[Link text Here](https://link-url-here.org)`
=> (chores) camel-google-bigquery: fix links in readme

camel-dependencies/pom.xml, components/camel-google/camel-google-bigquery/pom.xml, parent/pom.xml
Fixes https://issues.apache.org/jira/browse/CAMEL-19695 for (3.20)
The component `camel-google-bigquery` indirectly depends on `org.json:json:jar:20200518:compile` which has a know CVE https://nvd.nist.gov/vuln/detail/CVE-2022-45688 that can be fixed by upgrading it to `20230227` or higher.
* Add `org.json:json:20230618` to the dependencyManagement section
* Replace `org.json:json:20200518` with `org.json:json:20230618` in `camel-google-bigquery`
=> CAMEL-19695: camel-google-bigquery - Bump org.json to 20230618 (3.20)

camel-dependencies/pom.xml, components/camel-google/camel-google-bigquery/pom.xml, parent/pom.xml
Fixes https://issues.apache.org/jira/browse/CAMEL-19695 for (3.21)
The component `camel-google-bigquery` indirectly depends on `org.json:json:jar:20200518:compile` which has a know CVE https://nvd.nist.gov/vuln/detail/CVE-2022-45688 that can be fixed by upgrading it to `20230227` or higher.
* Add `org.json:json:20230618` to the dependencyManagement section
* Replace `org.json:json:20200518` with `org.json:json:20230618` in `camel-google-bigquery`
=> CAMEL-19695: camel-google-bigquery - Bump org.json to 20230618 (3.21)

camel-dependencies/pom.xml, components/camel-google/camel-google-bigquery/pom.xml, parent/pom.xml
Fixes https://issues.apache.org/jira/browse/CAMEL-19695 for (3.22)
The component `camel-google-bigquery` indirectly depends on `org.json:json:jar:20200518:compile` which has a know CVE https://nvd.nist.gov/vuln/detail/CVE-2022-45688 that can be fixed by upgrading it to `20230227` or higher.
* Add `org.json:json:20230618` to the dependencyManagement section
* Replace `org.json:json:20200518` with `org.json:json:20230618` in `camel-google-bigquery`
=> CAMEL-19695: camel-google-bigquery - Bump org.json to 20230618 (3.22)

Jenkinsfile.jdk17, Jenkinsfile.ppc64le, Jenkinsfile.s390x
The code is now auto-formatted by default and this prints a lot of bogus output
=> (chores) ci: remove the checkstyle stage

components/camel-jpa/src/main/java/org/apache/camel/component/jpa/JpaComponent.java
Follow up https://github.com/apache/camel/pull/10954
Refactor JpaComponent and make it easier to remove `DefaultTransactionStrategy` in graal static analysis. It could be helpful for camel-quarkus PR
- https://github.com/apache/camel-quarkus/pull/5147
=> CAMEL-19225: camel-jpa - Refactor JpaComponent

components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/AvailablePortFinder.java, components/camel-zookeeper-master/src/test/java/org/apache/camel/component/zookeepermaster/group/GroupIT.java, components/camel-zookeeper-master/src/test/java/org/apache/camel/component/zookeepermaster/group/internal/ZooKeeperGroupTest.java, components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/cloud/integration/ZooKeeperServiceCallRouteIT.java, components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/cloud/integration/ZooKeeperServiceDiscoveryIT.java, components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/cloud/integration/ZooKeeperServiceRegistrationITBase.java, parent/pom.xml
The zookeeper tests were flaky because the nextAvailablePort was picked but the server is started later in the test, therefore there are case were the same port would be picked, that is why getNextRandomAvailable was created.
=> bump zookeeper version to 3.9.0

core/camel-xml-io-util/src/main/java/org/apache/camel/xml/io/util/XmlStreamDetector.java
=> (chores) camel-xml-io-util: use isEmpty

components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/CamelTestSupport.java, components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/TestSupport.java
- make a few static variables final
- remove methods checking for older Java versions
=> (chores) camel-test-junit5: minor cleanups

components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/SqsBatchConsumerConcurrentConsumersIT.java
On some systems, there's a chance that the concurrent consumers will round-robin and, as such, consume all messages sent. Nonetheless, they would still be consumed in batches.
=> (chores) camel-aws2-sqs: fixed flaky test SqsBatchConsumerConcurrentConsumersIT

components/camel-whatsapp/src/main/java/org/apache/camel/component/whatsapp/model/TemplateMessage.java, components/camel-whatsapp/src/main/java/org/apache/camel/component/whatsapp/model/TemplateMessageRequest.java
There is a bad spellig in whatsapp-component class `org.apache.camel.component.whatsapp.model.TempalteMessage`. I have changed the name to `org.apache.camel.component.whatsapp.model.TemplateMessage`.
This is my first contribution to the project.
=> fixed bad spelling in whatsapp-component TemplateMessage

components/camel-xchange/src/test/java/org/apache/camel/component/xchange/account/AccountProducerTest.java, components/camel-xchange/src/test/java/org/apache/camel/component/xchange/market/MarketDataProducerTest.java, components/camel-xchange/src/test/java/org/apache/camel/component/xchange/metadata/MetaDataProducerTest.java
The camel-xchange tests keep hitting the address https://fapi.binance.com/fapi/v1/exchangeInfo which both abuse the owner of the address and contribute to their flakiness.
=> CAMEL-19751: disable misbehaved camel-xchange tests

core/camel-util/src/main/java/org/apache/camel/util/StringHelper.java
While cleaning up my performance test scripts, I was playing with StringHelper micro-optimizations and I came up with a few improvements. Of course, they are almost irrelevant on the big picture, but since they are so small and non-intrusive, I think they are worth it. 
Camel 4.0.0:
```
Benchmark                                          Mode  Cnt  Score    Error  Units
StringHelperTest.testIsClassNameNegative           avgt   10  0.034 ±  0.001  us/op
StringHelperTest.testIsClassNamePositive           avgt   10  0.308 ±  0.001  us/op
StringHelperTest.testRemoveLeadingAndEndingQuotes  avgt   10  0.037 ±  0.001  us/op
StringHelperTest.testRemoveQuotes                  avgt   10  0.098 ±  0.001  us/op
StringHelperTest.testXmlEncode                     avgt   10  0.170 ±  0.001  us/op
``` …
=> (chores) camel-util: micro-optimizations to StringHelper

core/camel-util/src/main/java/org/apache/camel/util/StringHelper.java
Camel 4.0.0
```
Benchmark                                          Mode  Cnt  Score    Error  Units
StringHelperTest.testCapitalize                    avgt   10  0.129 ±  0.001  us/op
StringHelperTest.testDashToCamelCaseNegative       avgt   10  0.144 ±  0.001  us/op
StringHelperTest.testDashToCamelCasePositive       avgt   10  0.141 ±  0.002  us/op
```
Camel 4.1.0-SNAPSHOT
```
Benchmark                                          Mode  Cnt  Score    Error  Units
StringHelperTest.testCapitalize                    avgt   10  0.035 ±  0.001  us/op
StringHelperTest.testDashToCamelCaseNegative       avgt   10  0.021 ±  0.001  us/op
StringHelperTest.testDashToCamelCasePositive       avgt   10  0.029 ±  0.001  us/op
```
=> (chores) camel-util: more aggressive micro-optimizations to StringHelper#capitalize

core/camel-util/src/main/java/org/apache/camel/util/StringHelper.java
Avoid the overhead of creating multiple String objects by lower casing on the fly
Camel 4.0.0
```
Benchmark                                           Mode  Cnt  Score    Error  Units
StringHelperTest.testCamelCaseToDashNegative        avgt   10  0.112 ±  0.001  us/op
StringHelperTest.testCamelCaseToDashPositive        avgt   10  0.236 ±  0.001  us/op
```
Camel 4.1.0-SNAPSHOT
```
Benchmark                                           Mode  Cnt  Score    Error  Units
StringHelperTest.testCamelCaseToDashNegative        avgt   10  0.111 ±  0.001  us/op
StringHelperTest.testCamelCaseToDashPositive        avgt   10  0.177 ±  0.001  us/op
```
=> (chores) camel-util: simplify StringHelper camelCaseToDash

dsl/camel-xml-io-dsl/src/main/java/org/apache/camel/dsl/xml/io/XmlRoutesBuilderLoader.java, dsl/camel-xml-io-dsl/src/test/java/org/apache/camel/dsl/xml/io/XmlLoadTest.java, dsl/camel-xml-io-dsl/src/test/resources/org/apache/camel/dsl/xml/io/routeConfig.xml, dsl/camel-xml-io-dsl/src/test/resources/org/apache/camel/dsl/xml/io/routeWithRouteConfig.xml
The CamelContext has to be set on the RoutesDefinition in the builder and not on the one returned from the ModelParser which is discarded.
Added a test to demonstrate the issue.
=> CAMEL-19766: Fix issue with not setting routeConfiguration on XML routes

components/camel-mail/src/test/java/org/apache/camel/component/mail/RawMailMessageTest.java
I am working on research that investigates test smell refactoring in which we identify alternative implementations of test cases, study how commonly used these refactorings are, and assess how acceptable they are in practice.
The first smell is when inappropriate assertions are used, while there exist better alternatives. For example, in [RawMailMessageTest.java](https://github.com/apache/camel/commit/f777f422ea24b21022a89d6a425f5ed0f211b8ea#diff-04960f3b28d9765e85f40286d286eee23603cb949def41f69a79b7af1a65fb0a), I refactored `assertTrue(!headers.isEmpty());` using `assertFalse(headers.isEmpty());` instead.
The second smell is known as Assertion Roulette, where a test method has multiple asserts and some or all of them have no explanatory messages, which can sometimes make it difficult to …
=> Refactor assertTrue(!) with assertFalse & Add explanatory messages

components/camel-http/src/main/java/org/apache/camel/component/http/HttpProducer.java, components/camel-http/src/test/java/org/apache/camel/component/http/HttpProducerContentTypeWithCharsetTest.java, components/camel-http/src/test/java/org/apache/camel/component/http/HttpProducerWithSpecialCharsBodyTest.java
**The problem**
In Apache HttpComponents  5 StringEntity class became immutable and now requires different utilization than before. Earlier on, it was possible to instantiate an instance with charset only and updating the content type afterwards. Doing so, a temporary TEXT_PLAIN content type with given charset was used during String-to-byte-array conversion.
Now that StringEntity became immutable, the content type must be provided right at the instantiation. In order to ensure the correct encoding, the charset of the content type instance has to be already set correctly at this point. This is the point at which false treatment can currently take place. In case the provided content type has no charset information, the StringEntity constructor falls back to ISO 8859-1 format, no matter what …
=> CAMEL-19768: Ensure content is encoded with expected charset

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/VersionHolder.java
Use the static holder pattern to obtain the Camel version without relying on manual locks and volatile variables
=> (chores) camel-core: cleanup obtaining Camel version information

components/camel-jms/src/main/java/org/apache/camel/component/jms/JmsSendDynamicAware.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsToFullyQualifiedQueueNameTest.java
CAMEL-19777
Fixes handling of FQQN with `.toD` endpoint:
```
// DOES NOT WORK
.setHeader("fqqn", constant("addr::q1"))
.toD("jms:queue:${header.fqqn}");
```
=> CAMEL-19777: Fix usage of FQQN with toD

core/camel-core-processor/src/main/java/org/apache/camel/processor/transformer/DataTypeProcessor.java, core/camel-management/src/main/java/org/apache/camel/management/DefaultManagementObjectStrategy.java
- Avoid ClassCastException when DataTypeProcessor is used as part of a ProcessorDefinition
- Allows users to reference the DataTypeProcessor as a normal processor in a route as an addition to using it in TransformDefinition
=> chore: Allow DataTypeProcessor used as processor definition

dsl/camel-yaml-dsl/camel-yaml-dsl/src/main/java/org/apache/camel/dsl/yaml/YamlRoutesBuilderLoader.java, dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/KameletBindingLoaderIntegrationSpecTest.groovy, dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/PipeLoaderIntegrationSpecTest.groovy
- Enhance YAML DSL to support Integration specification as part of a pipe/binding
- Integration spec adds configuration, traits and dependencies to the pipe/binding
=> CAMEL-19805: Support IntegrationSpec as part of Pipe/KameletBinding

dsl/camel-yaml-dsl/camel-yaml-dsl/src/main/java/org/apache/camel/dsl/yaml/YamlRoutesBuilderLoader.java, dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/KameletBindingLoaderIntegrationSpecTest.groovy, dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/PipeLoaderIntegrationSpecTest.groovy
Backport #11236 to 4.0.x
- Enhance YAML DSL to support Integration specification as part of a pipe/binding
- Integration spec adds configuration, traits and dependencies to the pipe/binding
=> [Backport 4.0.x] CAMEL-19805: Support IntegrationSpec as part of Pipe/KameletBinding

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Init.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogKamelet.java, dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/VersionHelper.java, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/run-custom-camel-version.tmpl, dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/KameletMain.java, dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/DependencyDownloaderKamelet.java, dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/DependencyDownloaderRoutesLoader.java, dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/KnownKameletRoutesBuilderLoader.java, dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/util/VersionHelper.java
The PR improves the camel-kamelets version handling in Camel JBang and makes sure to consistently use the same version in all `camel-kamelets-*` libraries (e.g. camel-kamelets, camel-kamelets-utils, camel-kamelets-catalog, and so on). 
Users either set the version via system properties `-Dcamel-kamelets.version=` or via command line setting `--kamelets-version=` when using Camel JBang. As a fallback the value gets derived from the version used by the library `camel-kamelets` on the current JVM classpath (only when none of the user settings should be set).
- Avoids inconsistent versions on camel-kamelets dependencies (e.g. camel-kamelets-utils library)
- Make sure to use same version for camel-kamelets and camel-kamelets-utils dependency
- Add `--kamelets-version` setting on Camel JBang …
=> CAMEL-19798: Consistently set camel-kamelets version in Camel JBang

components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/Kinesis2Consumer.java, components/camel-aws/camel-aws2-kinesis/src/test/java/org/apache/camel/component/aws2/kinesis/KinesisConsumerClosedShardWithFailTest.java, components/camel-aws/camel-aws2-kinesis/src/test/java/org/apache/camel/component/aws2/kinesis/integration/KinesisConsumerIT.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/clients/KinesisUtils.java
Adapt the handling of closed streams.
Modify KinesisUtils to be able to create a stream with multiple shards. Modify KinesisConsumerIT to test a stream with 2 shards.
=> CAMEL-19811: restore multi-shard handling.

components/camel-infinispan/camel-infinispan-common/src/test/java/org/apache/camel/component/infinispan/InfinispanProducerTestSupport.java, components/camel-saxon/src/generated/java/org/apache/camel/converter/saxon/SaxonConverterLoader.java, components/camel-saxon/src/main/java/org/apache/camel/converter/saxon/SaxonConverter.java, components/camel-vertx/camel-vertx-common/src/generated/java/org/apache/camel/component/vertx/common/CamelVertxCommonBulkConverterLoader.java, core/camel-api/src/main/java/org/apache/camel/TypeConverter.java, core/camel-api/src/main/java/org/apache/camel/converter/TypeConvertible.java, core/camel-api/src/main/java/org/apache/camel/spi/TypeConverterRegistry.java, core/camel-base/src/generated/java/org/apache/camel/converter/CamelBaseBulkConverterLoader.java, core/camel-base/src/main/java/org/apache/camel/impl/converter/CoreTypeConverterRegistry.java, core/camel-base/src/main/java/org/apache/camel/impl/converter/DefaultTypeConverter.java, core/camel-base/src/main/java/org/apache/camel/impl/converter/TypeResolverHelper.java, core/camel-core/src/test/java/org/apache/camel/converter/ConverterTest.java, core/camel-core/src/test/java/org/apache/camel/impl/CustomBulkTypeConvertersTest.java, core/camel-support/src/generated/java/org/apache/camel/converter/stream/StreamCacheBulkConverterLoader.java, core/camel-util/src/main/java/org/apache/camel/util/DoubleMap.java, core/camel-xml-jaxp/src/generated/java/org/apache/camel/converter/jaxp/CamelXmlJaxpBulkConverterLoader.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/TypeConverterLoaderGeneratorMojo.java
This is preliminary work that should simplify moving away from an Exception-based logic for type handling
It refactors the type conversion code so that it is preloaded to a Map, which store type conversion pairs. This map is checked whenever there is a type conversion, by matching the requested pair (from/to) with the known conversions on the Map.
Among other things, it reduces the incidence of runtime type detection and tries to let the compiler decide the method whenever it is possible
This builds on top of the work done on #10271.
=> CAMEL-19398: refactor the core type-converter

components/camel-seda/src/main/java/org/apache/camel/component/seda/SedaComponent.java, core/camel-api/src/main/java/org/apache/camel/Endpoint.java, core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/BasePackageScanResolver.java, core/camel-core-catalog/src/main/java/org/apache/camel/catalog/impl/AbstractCamelCatalog.java, core/camel-core/src/test/java/org/apache/camel/builder/xml/XPathTransformTest.java, core/camel-management/src/main/java/org/apache/camel/management/DefaultManagementObjectNameStrategy.java, core/camel-support/src/main/java/org/apache/camel/converter/stream/CipherPair.java, core/camel-support/src/main/java/org/apache/camel/support/DefaultEndpoint.java, core/camel-support/src/main/java/org/apache/camel/support/PropertyBindingSupport.java, core/camel-support/src/main/java/org/apache/camel/support/component/SendDynamicAwareSupport.java, core/camel-util/src/main/java/org/apache/camel/util/InetAddressUtil.java, core/camel-util/src/main/java/org/apache/camel/util/OgnlHelper.java, core/camel-util/src/main/java/org/apache/camel/util/StringHelper.java, core/camel-util/src/main/java/org/apache/camel/util/URISupport.java
Use the StringHelper before method as it avoids traversing the string twice and is already defined on StringHelper
=> (chores) camel-core: replace duplicated code

components/camel-atmosphere-websocket/src/main/java/org/apache/camel/component/atmosphere/websocket/WebsocketEndpoint.java, components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/utils/AWS2S3Utils.java, components/camel-azure/camel-azure-files/src/main/java/org/apache/camel/component/file/azure/FilesConfiguration.java, components/camel-azure/camel-azure-files/src/main/java/org/apache/camel/component/file/azure/FilesURIStrings.java, components/camel-disruptor/src/main/java/org/apache/camel/component/disruptor/DisruptorComponent.java, components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpComponent.java, components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/SftpComponent.java, components/camel-jms/src/main/java/org/apache/camel/component/jms/JmsSendDynamicAware.java, components/camel-jsch/src/main/java/org/apache/camel/component/scp/ScpComponent.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaSendDynamicAware.java, components/camel-mllp/src/main/java/org/apache/camel/component/mllp/MllpTcpClientProducer.java, components/camel-mllp/src/main/java/org/apache/camel/component/mllp/internal/TcpServerAcceptThread.java, components/camel-mllp/src/main/java/org/apache/camel/component/mllp/internal/TcpServerBindThread.java, components/camel-mllp/src/main/java/org/apache/camel/component/mllp/internal/TcpServerConsumerValidationRunnable.java, components/camel-mllp/src/main/java/org/apache/camel/component/mllp/internal/TcpSocketConsumerRunnable.java, components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/handlers/HttpServerMultiplexChannelHandler.java, components/camel-paho-mqtt5/src/main/java/org/apache/camel/component/paho/mqtt5/PahoMqtt5SendDynamicAware.java, components/camel-paho/src/main/java/org/apache/camel/component/paho/PahoSendDynamicAware.java, components/camel-sjms/src/main/java/org/apache/camel/component/sjms/SjmsSendDynamicAware.java, components/camel-spring-rabbitmq/src/main/java/org/apache/camel/component/springrabbit/SpringRabbitMQSendDynamicAware.java, components/camel-stax/src/main/java/org/apache/camel/language/xtokenizer/XMLTokenExpressionIterator.java, components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/CamelTestSupport.java, components/camel-undertow/src/main/java/org/apache/camel/component/undertow/handlers/RestRootHandler.java
Use the StringHelper before method as it avoids traversing the string twice and is already defined on StringHelper
=> (chores) camel-components: replace duplicated code

components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/stream/AWS2S3StreamUploadProducer.java, components/camel-aws/camel-aws2-s3/src/test/java/org/apache/camel/component/aws2/s3/integration/S3StreamUploadMultipartAsyncIT.java, components/camel-aws/camel-aws2-s3/src/test/java/org/apache/camel/component/aws2/s3/integration/S3StreamUploadOperationAsyncIT.java
Small exchanges are batched when individual exchanges are less than the batch-size, requiring processing state information to held between processing of each exchange. 
This state information has been moved to a State class that is guarded by synchronized blocks whenever it is access so that exchanges can be processed asynchronously.   
Asynchronous versions of existing unit tests have been added. 
Large files are still chunked down and sent as chunks, and state information is confined to the processing method.
=> CAMEL-17027 make camel-aws-s3 threadsafe so it can be used concurrently

dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/src/main/java/org/apache/camel/maven/dsl/yaml/GenerateYamlSchemaMojo.java, dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camelYamlDsl.json, dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/MarshalTest.groovy, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-yaml-dto-v3/verify.groovy, tooling/openapi-rest-dsl-generator/src/main/java/org/apache/camel/generator/openapi/RestDslYamlGenerator.java, tooling/openapi-rest-dsl-generator/src/test/resources/OpenApiV3PetstoreWithRestComponentYaml.txt
* Fixed openapi-rest generator to use `restConfiguration`
* Fixed YAML DSL schema to use camelCase properties deeper in the schema composition
Following up previous PR #11245, fixes kebab-case leftover.
https://issues.apache.org/jira/browse/CAMEL-19703
=> [CAMEL-19703] Follow up: Align kebab-case properties usage to camelCase

components/camel-dhis2/camel-dhis2-component/src/test/java/org/apache/camel/component/dhis2/Dhis2GetIT.java
Add a work-around for a test that is returning invalid data when running
along with the others.
=> camel-dhis2: fix flaky test

core/camel-core/src/test/java/org/apache/camel/processor/ConvertBodyTest.java
I am not even sure if it's worth keeping this AIX stuff on the code base (is anyone building/testing Camel there?), but let's clean it up.
=> (chores) camel-core: cleanup skipping tests on AIX

components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/stream/AWS2S3StreamUploadProducer.java
Potential race condition when processing concurrent exchanges.
When processing multiple small exchanges in quick succession and there was no shared-state to aggregate exchanges, if an initial exchange acquired the lock and set the shared state and a subsequent exchange immediately followed after the lock was released the data would be lost.
=> Camel 17027 make aws streaming thread safe

components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2ClientManagerIT.java
In 3.20, a compilation error is raised by the build due to the application entity class used.
* Update the unit test to set the correct application entity class
=> CAMEL-19731: AS2 - Set the correct application entity class

components/camel-netty/src/main/docs/netty-component.adoc
[Someone from the community](https://stackoverflow.com/questions/76991186/cannot-resolve-method-setsslcontextparameters-in-nettycomponent) raised the fact that the code snippet describing how to configure SSL in the netty component is invalid/outdated and should be fixed.
* Set the SSL configuration from the `NettyConfiguration` instead of `NettyComponent`
=> camel-netty - Fix doc about SSL configuration

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/PubSubApiConsumer.java, components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/client/PubSubApiClient.java, components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/PubSubApiTest.java, components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/internal/pubsub/SendOneMessagePubSubServer.java
This makes the following changes:
- Reconnect automatically with sensible defaults if we get an error before receiving the first message
- Expose an API for updating the initialReplayId. At first, this might sound silly. "initialReplayId" is effectively a constant, right? But there's a notable exception in cases where the client restarts the route dynamically and may pull a new replay id from another source. This can happen in the case of clustering, where only one route is active at a time and failover may occur.
- Expose an API to force plaintext via the consumer. This is for a similar reason to the existing method, but also makes it available to other test frameworks. We use a fake grpc endpoint to test the service and this will simplify that work.
- [x ] I checked that the commit is …
=> CAMEL-19783: Added reconnection, even if a message has not yet been received

core/camel-core/src/test/java/org/apache/camel/support/AbstractExchangeTest.java, core/camel-support/src/main/java/org/apache/camel/support/AbstractExchange.java, core/camel-support/src/main/java/org/apache/camel/support/DefaultExchange.java, core/camel-support/src/main/java/org/apache/camel/support/DefaultPooledExchange.java, core/camel-support/src/main/java/org/apache/camel/support/ExtendedExchangeExtension.java
Preliminary work for consolidating the way we copy exchanges. More work will be done in the upcoming weeks, and this is kicking it off. 
As an added bonus, this brings a small, but measurable performance gain as it does less (duplicated) work: 
**4.1.0-SNAPSHOT**:
```
DirectConcurrentTest.directConcurrentTest                   avgt   15   9.457 ± 0.032  us/op
```
**4.0.0**:
```
DirectConcurrentTest.directConcurrentTest                   avgt   15  11.018 ± 0.032  us/op
```
=> CAMEL-19801: pre-work for cleaning up copying exchanges

test-infra/camel-test-infra-elasticsearch/src/test/java/org/apache/camel/test/infra/elasticsearch/services/ElasticSearchLocalContainerService.java
fix https://issues.apache.org/jira/browse/CAMEL-19834
=> [CAMEL-19834] fix camel-test-infra-elasticsearch container start fails if ca cert is not present

core/camel-api/src/main/java/org/apache/camel/support/jsse/KeyStoreParameters.java
Fixes https://issues.apache.org/jira/browse/CAMEL-19840 for 3.20
If `KeyStoreParameters` are configured with an incorrect path for the key store file, at runtime, we end up with an error that can be more or less easy to understand depending on the underlying component for which SSL has been configured.
* Add a warning when the key store file cannot be found
=> CAMEL-19840: camel-core-api - Warn when the key store cannot be found

camel-dependencies/pom.xml, parent/pom.xml
CVE fixes, same reason as main PR
=> Updating Kudu to 1.17.0 (#11323) (#11324)

components/camel-platform-http-vertx/src/main/docs/platform-http-vertx.adoc, components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpConstants.java, components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpSupport.java, components/camel-platform-http-vertx/src/test/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpEngineTest.java
Hopefully this is ok to be considered for backport. It's a pretty minor change.
=> [4.0.x] CAMEL-19816: Add headers to camel-platform-http-vertx for the connection local and remote address

components/camel-seda/src/main/java/org/apache/camel/component/seda/SedaEndpoint.java
- Removing the cached queue references caused a regression in camel-zookeeper-master. This brings back the cached references (reverts: d66469d6ac7243f0ae790c41a500965b885d3180)
- Avoid keeping cached stalled references (ref: CAMEL-19815)
=> CAMEL-19842: fix not creating/refreshing seda queues

core/camel-support/src/main/java/org/apache/camel/support/AbstractExchange.java
This should fix WireTapTest in camel-attachments, which relies on deep copies to work
=> CAMEL-19801: fixed missing deep-copy

camel-dependencies/pom.xml, parent/pom.xml
A fix for:
| org.glassfish:jakarta.el (jakarta.el-3.0.3.jar)             │ CVE-2021-28170 │ MEDIUM   │ affected │ 3.0.3             │               │ jakarta-el: ELParserTokenManager enables invalid EL expressions to be evaluate  https://avd.aquasec.com/nvd/cve-2021-28170                   │
=> Updating Jakarta El to 3.0.4

components/camel-telegram/src/main/java/org/apache/camel/component/telegram/service/TelegramServiceRestBotAPIAdapter.java, components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/CamelTestSupport.java, core/camel-core-model/src/main/java/org/apache/camel/model/RouteDefinitionHelper.java, core/camel-support/src/main/java/org/apache/camel/support/EndpointHelper.java, core/camel-util/src/main/java/org/apache/camel/util/URISupport.java, test-infra/camel-test-infra-core/src/test/java/org/apache/camel/test/infra/core/MockUtils.java
This should simplify consolidating duplicate code from camel-core-catalog
=> CAMEL-19868: removed unused exception in URISupport.normalizeUri

core/camel-core-catalog/src/main/java/org/apache/camel/catalog/impl/AbstractCamelCatalog.java, core/camel-core-catalog/src/main/java/org/apache/camel/catalog/impl/CatalogHelper.java
The AbstractCamelCatalog needs to be able to parse some endpoint properties manually, so that certain groups of characters and URI items are properly evaluated.
=> CAMEL-19868: parse manually when necessary

components/camel-spring-rabbitmq/src/main/java/org/apache/camel/component/springrabbit/DefaultMessagePropertiesConverter.java, components/camel-spring-rabbitmq/src/main/java/org/apache/camel/component/springrabbit/MessagePropertiesConverter.java, components/camel-spring-rabbitmq/src/main/java/org/apache/camel/component/springrabbit/SpringRabbitMQComponent.java
if i use java code to config spring-rabbitmq component headerfilterstrategy, the doinit() method of SpringRabbitMQComponent will be executed before i config headerfilterstrategy, so the DefaultMessagePropertiesConverter may reference headerfilterStrategy the old value。
=> CAMEL-19859: camel-spring-rabbitmq set headerfilter not effective

components/camel-jooq/pom.xml
Fixes https://issues.apache.org/jira/browse/CAMEL-19871 for 4.1
There are many test dependencies of the camel-joor component for which no scope has been set which pulls useless dependencies at runtime.
* Add the test scope to all test dependencies to avoid getting the default scope which is compile
=> CAMEL-19871: camel-jooq - Set the proper scope to all test dependencies

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/DispositionMode.java, components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/util/DispositionNotificationContentUtilsTest.java
- The third party AS2 server returning the MDN response with disposition field case insensitive which is as per the spec (https://www.ietf.org/rfc/rfc4130.txt) but camel as2 validates this field with case sensitive hence it fails.
=> CAMEL-19870: Camel AS2 Should accept MDN field name Disposition as case insensitive

components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/CreateInstanceKafka1Test.java, components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/CreateInstanceKafka2Test.java, components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/CreateInstanceKafkaFunctional1Test.java, components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/CreateInstanceKafkaFunctional2Test.java, components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/CreateInstanceRmq1Test.java, components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/CreateInstanceRmq2Test.java, components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/CreateInstanceRmqFunctional1Test.java, components/camel-huawei/camel-huaweicloud-dms/src/test/java/org/apache/camel/component/huaweicloud/dms/CreateInstanceRmqFunctional2Test.java
These tests did not follow the correct naming convention for tests and were not being executed.
=> (chores) camel-huaweicloud-dms: fixed tests that were named incorrectly

components/camel-azure/camel-azure-storage-blob/src/main/java/org/apache/camel/component/azure/storage/blob/operations/BlobOperations.java, components/camel-azure/camel-azure-storage-queue/src/main/java/org/apache/camel/component/azure/storage/queue/QueueConsumer.java
Logging the exchange can alter its internal state.
Also void potentially slow code paths that require significantly deep calls to resolve logging parameters
* camel-azure-storage-blob
* camel-azure-storage-queue
=> (chores) camel-azure: avoid slow code paths

components/camel-test/camel-test-spring-junit5/src/test/java/org/apache/camel/test/issues/AdviceWithOnExceptionTransactedTest.java, core/camel-core/src/test/java/org/apache/camel/issues/TwoTimerWithJMXIssueTest.java
These tests were skipped because their names did not match the convention setup on surefire
=> (chores) fixed incorrectly named tests

.github/actions/incremental-build/incremental-build.sh
A change in an integration test where we have a complete project with a pom file can be seen as a project to test while we rather expect to test its parent project
* Exclude integration test project from project root to test
=> (chore) ci: exclude integration tests

tooling/maven/camel-package-maven-plugin/pom.xml, tooling/maven/camel-package-maven-plugin/src/it/HeaderSupport/invoker.properties
The integration test of the project camel-package-maven-plugin fails regularly on the GH CI, so it needs to be investigated and fixed.
* Display log file content in case of a failure
* Increase the heap size of the IT
=> Fix integration test of camel-package-maven-plugin

components/camel-aws/camel-aws2-redshift/src/main/docs/aws2-redshift-data-component.adoc
Fix for https://github.com/apache/camel/pull/11429#issuecomment-1725632495 to update spring boot component name for aws2 redshift
=> Updated spring boot component name for aws redshift

parent/pom.xml
Hope this is ok to backport. The upgrade fixes an issue in BigQuery & PubSub with native compilation on GraalVM.
=> [4.0.x] Upgrade Google Cloud libraries-bom to 26.23.0

components/camel-openapi-java/src/main/java/org/apache/camel/openapi/RestOpenApiReader.java, components/camel-openapi-java/src/test/java/org/apache/camel/openapi/RestOpenApiReaderTest.java
In RestOpenApiReader.class, while aggregating the tags for api-doc, the HashMap was used instead of LinkedHashMap, which broke the original order of the tags. A LinkedHashMap is used now instead. There is no way of sorting the tags after that, and their order influences, for example, the UI of the swagger.
=> CAMEL-19888 Preserve openapi tags order while generating api-doc

core/camel-base/src/main/java/org/apache/camel/impl/converter/CoreTypeConverterRegistry.java
Note: this changes the behavior for converting string to boolean when invalid data is passed. Previously the code would return `null`. With this, it defaults to `false`. 
Obs.: keeping as a draft as I would like @davsclaus opinion on this (and he is on PTO).
=> CAMEL-19398: use Java's builtin custom boolean parser

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/DependencyCopy.java
not found yet how to test it
Fix to respect absolute path for output directory for `camel dependency copy` command
=> CAMEL-19895 - Fix to respect absolute path for output directory for `camel dependency copy` command

core/camel-api/src/main/java/org/apache/camel/spi/TypeConverterRegistry.java, core/camel-base/src/main/java/org/apache/camel/impl/converter/CoreTypeConverterRegistry.java, core/camel-base/src/main/java/org/apache/camel/impl/converter/NoopTypeConverterStatistics.java, core/camel-base/src/main/java/org/apache/camel/impl/converter/TypeConverterStatistics.java, core/camel-console/src/main/java/org/apache/camel/impl/console/TypeConverterConsole.java, core/camel-core/src/test/java/org/apache/camel/impl/TypeConverterRegistryStatisticsEnabledNoStreamCachingTest.java, core/camel-core/src/test/java/org/apache/camel/impl/TypeConverterRegistryStatisticsEnabledTest.java, core/camel-management-api/src/main/java/org/apache/camel/api/management/mbean/ManagedTypeConverterRegistryMBean.java, core/camel-management/src/main/java/org/apache/camel/management/mbean/ManagedTypeConverterRegistry.java
This reverts commit db7e5221b1f8df7c795782778c83e283c3a3c866.
This change seems to break some expectations from Spring XML (i.e; verified on SpringTypeConverterRegistryStatisticsEnabledTest) and can break backwards compatibility.
=> Revert "CAMEL-19398: remove isStatisticsEnabled (#11494)"

tooling/maven/camel-restdsl-openapi-plugin/src/it/customized-v3/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/customized/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/expanded-v3-yaml/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-dto-v3/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-dto/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-v3-yaml/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-v3/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-xml-dto-v3/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-xml-dto/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-xml-v3/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-xml/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-yaml-dto-v3/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-yaml-kamelet-v3/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple-yaml-v3/pom.xml, tooling/maven/camel-restdsl-openapi-plugin/src/it/simple/pom.xml, tooling/openapi-rest-dsl-generator/src/main/java/org/apache/camel/generator/openapi/RestDslSourceCodeGenerator.java, tooling/openapi-rest-dsl-generator/src/test/resources/MyRestRoute.txt, tooling/openapi-rest-dsl-generator/src/test/resources/MyRestRouteFilter.txt, tooling/openapi-rest-dsl-generator/src/test/resources/MyRestRouteFilterV3.txt, tooling/openapi-rest-dsl-generator/src/test/resources/MyRestRouteV3.txt, tooling/openapi-rest-dsl-generator/src/test/resources/OpenApiPetstore.txt, tooling/openapi-rest-dsl-generator/src/test/resources/OpenApiPetstoreWithRestComponent.txt, tooling/openapi-rest-dsl-generator/src/test/resources/OpenApiV3Petstore.txt, tooling/openapi-rest-dsl-generator/src/test/resources/OpenApiV3PetstoreWithRestComponent.txt
https://issues.apache.org/jira/browse/CAMEL-19892
=> CAMEL-19892: openapi-rest-dsl-generator - Use jakarta instead of javax

archetypes/camel-archetype-api-component/src/main/resources/archetype-resources/pom.xml, archetypes/camel-archetype-component/src/main/resources/archetype-resources/pom.xml, archetypes/camel-archetype-dataformat/src/main/resources/archetype-resources/pom.xml, archetypes/camel-archetype-java/src/main/resources/archetype-resources/pom.xml, archetypes/camel-archetype-main/src/main/resources/archetype-resources/pom.xml, archetypes/camel-archetype-spring/src/main/resources/archetype-resources/pom.xml
=> (chores) archetypes: should use 17 as the base Java version

docs/main/modules/getting-started/pages/index.adoc
The part of the "Routes" section of the getting-started guide that reads "a predicate that tests if the body of the matches" seems to be missing the word "message" between "the body of the" and "matches". The purpose of this PR is to the add that word to that part of the guide in order to make it slightly clearer.
=> (chores) doc: add missing word in getting-started guide

dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java, dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java
=> Update CamelJBang.java from 4.0.0 to 4.0.1

components/camel-observation/src/main/java/org/apache/camel/observation/MicrometerObservationSpanAdapter.java, components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/OpenTelemetrySpanAdapter.java, components/camel-tracing/src/main/java/org/apache/camel/tracing/SpanAdapter.java, components/camel-tracing/src/main/java/org/apache/camel/tracing/Tag.java, components/camel-tracing/src/main/java/org/apache/camel/tracing/TagConstants.java, components/camel-tracing/src/main/java/org/apache/camel/tracing/decorators/AbstractMessagingSpanDecorator.java, components/camel-tracing/src/main/java/org/apache/camel/tracing/decorators/AbstractSpanDecorator.java, components/camel-tracing/src/main/java/org/apache/camel/tracing/decorators/ElasticsearchSpanDecorator.java, components/camel-tracing/src/test/java/org/apache/camel/tracing/MockSpanAdapter.java, components/camel-tracing/src/test/java/org/apache/camel/tracing/decorators/AbstractHttpSpanDecoratorTest.java, components/camel-tracing/src/test/java/org/apache/camel/tracing/decorators/AbstractMessagingSpanDecoratorTest.java, components/camel-tracing/src/test/java/org/apache/camel/tracing/decorators/AbstractSpanDecoratorTest.java, components/camel-tracing/src/test/java/org/apache/camel/tracing/decorators/CqlSpanDecoratorTest.java, components/camel-tracing/src/test/java/org/apache/camel/tracing/decorators/ElasticsearchSpanDecoratorTest.java, components/camel-tracing/src/test/java/org/apache/camel/tracing/decorators/JdbcSpanDecoratorTest.java, components/camel-tracing/src/test/java/org/apache/camel/tracing/decorators/MongoDBSpanDecoratorTest.java, components/camel-tracing/src/test/java/org/apache/camel/tracing/decorators/SqlSpanDecoratorTest.java
Updated camel-tracing to use open telemetry semantic conventions
Following on from this pr: https://github.com/apache/camel/pull/11354
=> CAMEL-19812 use open telemetry naming conventions

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_1.adoc
Added a note in the 4.1 upgrade guide regarding the deprecation of the Tag Enum used in `camel-tracing`.
=> CAMEL-19812 add note to 4.1 upgrade guide for Tag deprecation

core/camel-core-model/src/main/java/org/apache/camel/builder/PredicateClause.java
This should avoid an unnecessary object allocation
=> (chores) camel-core-model: fold method reference

core/camel-main/src/main/java/org/apache/camel/main/MainCommandLineSupport.java
=> (chores) camel-main: use static inner class

core/camel-core-processor/src/main/java/org/apache/camel/processor/Splitter.java
Remove preserveExchangeId from copyAndPrepareSubExchange as it is always true
=> (chores) camel-core: cleanup parameter with constant value

components/camel-as2/camel-as2-component/src/main/java/org/apache/camel/component/as2/AS2Component.java, components/camel-box/camel-box-component/src/main/java/org/apache/camel/component/box/BoxComponent.java, components/camel-braintree/src/main/java/org/apache/camel/component/braintree/BraintreeComponent.java, components/camel-dhis2/camel-dhis2-component/src/main/java/org/apache/camel/component/dhis2/Dhis2Component.java, components/camel-fhir/camel-fhir-component/src/main/java/org/apache/camel/component/fhir/FhirComponent.java, components/camel-google/camel-google-calendar/src/main/java/org/apache/camel/component/google/calendar/GoogleCalendarComponent.java, components/camel-google/camel-google-drive/src/main/java/org/apache/camel/component/google/drive/GoogleDriveComponent.java, components/camel-google/camel-google-mail/src/main/java/org/apache/camel/component/google/mail/GoogleMailComponent.java, components/camel-google/camel-google-sheets/src/main/java/org/apache/camel/component/google/sheets/GoogleSheetsComponent.java, components/camel-olingo2/camel-olingo2-component/src/main/java/org/apache/camel/component/olingo2/Olingo2Component.java, components/camel-olingo4/camel-olingo4-component/src/main/java/org/apache/camel/component/olingo4/Olingo4Component.java, components/camel-twilio/src/main/java/org/apache/camel/component/twilio/TwilioComponent.java, components/camel-zendesk/src/main/java/org/apache/camel/component/zendesk/ZendeskComponent.java, core/camel-support/src/main/java/org/apache/camel/support/component/AbstractApiComponent.java
Deprecate constructor using unused parameters and introduce new ones
=> (chores) camel-core: remove unused parameters in AbstractApiComponent

docs/user-manual/modules/ROOT/pages/camel-4x-upgrade-guide-4_1.adoc, dsl/camel-jbang/camel-jbang-core/src/main/resources/templates/xml.tmpl
Generate the xml route with the`camel` root tag instead of `route`
=> CAMEL-19773 camel-jbang - use camel root tag in generated xml route

core/camel-core/src/test/java/org/apache/camel/component/file/FileConsumerThreadsInProgressIssueTest.java
On Windows, filenames cannot have `\r` and `\n`
=> Fix FileConsumerThreadsInProgressIssueTest on Windows

core/camel-core-model/src/main/java/org/apache/camel/builder/RouteBuilder.java, core/camel-core-model/src/main/java/org/apache/camel/model/CatchDefinition.java, core/camel-core-model/src/main/java/org/apache/camel/model/ProcessorDefinition.java, core/camel-core-model/src/main/java/org/apache/camel/model/RouteConfigurationDefinition.java, core/camel-support/src/main/java/org/apache/camel/support/component/AbstractApiComponent.java
This should vet, protect/reduce the potential for heap pollution problems
=> (chores) camel-core: vet and/or improve methods with varargs
