components/camel-mail/src/main/java/org/apache/camel/component/mail/DefaultJavaMailSender.java
... and I know it's just a typo =) but might be helpful if somebody is grepping the log for "Mime", like me today ;-) so I submit this ultrasmall PR in the hope it may give a little help to somebody else tomorrow :-P
=> Low priority / typo fix 

components/camel-scr/src/main/java/org/apache/camel/scr/AbstractCamelRunner.java, components/camel-scr/src/test/java/org/apache/camel/scr/AbstractCamelRunnerTest.java, components/camel-scr/src/test/java/org/apache/camel/scr/ConcreteCamelRunner.java, components/camel-scr/src/test/java/org/apache/camel/scr/internal/ScrHelperTest.java, components/camel-scr/src/test/resources/componentDefinitionExample.xml
Here's the same CAMEL-9166 prefixing and backward compatibility fix for 2.15.x branch.
=> CAMEL-9166 for 2.15.x

components/camel-scr/src/main/java/org/apache/camel/scr/ScrHelper.java, components/camel-scr/src/test/java/org/apache/camel/scr/ScrHelperTest.java, components/camel-scr/src/test/resources/componentDefinitionExample.xml
CAMEL-9181 for master branch.
https://issues.apache.org/jira/browse/CAMEL-9181
=> CAMEL-9181: Simplify ScrHelper

components/camel-scr/src/main/java/org/apache/camel/scr/internal/ScrHelper.java, components/camel-scr/src/test/java/org/apache/camel/scr/internal/ScrHelperTest.java, components/camel-scr/src/test/resources/componentDefinitionExample.xml
CAMEL-9181 for 2.15.x branch.
https://issues.apache.org/jira/browse/CAMEL-9181
=> CAMEL-9181: Simplify ScrHelper for 2.15.x

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConfiguration.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaEndpoint.java
The two new consumer properties I added are:
* 'offsets.storage'
* 'dual.commit.enabled'
http://kafka.apache.org/documentation.html#consumerconfigs
=> Added two new consumer properties for the kafka component

platforms/karaf/features/src/main/resources/features.xml
https://issues.apache.org/jira/browse/CAMEL-9265
=> CAMEL-9265 Use servicemix-specs version of jsr311-api

components/camel-aws/src/main/docs/aws-s3.adoc, components/camel-aws/src/main/java/org/apache/camel/component/aws/s3/S3Configuration.java, components/camel-aws/src/main/java/org/apache/camel/component/aws/s3/S3Endpoint.java, components/camel-aws/src/test/java/org/apache/camel/component/aws/s3/S3ComponentConfigurationTest.java, components/camel-aws/src/test/java/org/apache/camel/component/aws/s3/S3IncludeBodyTest.java
For your consideration:
CAMEL-9507 Add includeBody option to camel-aws S3 consumer
https://issues.apache.org/jira/browse/CAMEL-9507
=> CAMEL-9507 Add includeBody option to camel-aws S3 consumer

components/camel-cdi/pom.xml, components/camel-cdi/src/main/java/org/apache/camel/cdi/CdiCamelBeanPostProcessor.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/CdiCamelExtension.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/CdiSpiHelper.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/ContextName.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/Uri.java, components/camel-cdi/src/main/resources/META-INF/beans.xml, components/camel-cdi/src/test/java/org/apache/camel/cdi/test/MultiContextEventEndpointTest.java, components/camel-cdi/src/test/java/org/apache/camel/cdi/test/ProgrammaticLookupTest.java, examples/camel-example-cdi-metrics/README.md, examples/camel-example-cdi-metrics/src/test/java/org/apache/camel/example/cdi/metrics/CdiMetricsTest.java, examples/camel-example-cdi-osgi/README.md, examples/camel-example-cdi-osgi/pom.xml, examples/camel-example-cdi-osgi/src/test/java/org/apache/camel/example/cdi/osgi/CdiOsgiIT.java, examples/camel-example-cdi-properties/README.md, examples/camel-example-cdi-properties/src/test/java/org/apache/camel/example/cdi/properties/CdiPropertiesTest.java, examples/camel-example-cdi-rest-servlet/README.md, examples/camel-example-cdi-rest-servlet/src/test/java/org/apache/camel/example/cdi/rest/servlet/CdiRestServletTest.java, examples/camel-example-cdi/README.md, tests/camel-itest-cdi/src/test/java/org/apache/camel/itest/cdi/CamelCdiTest.java
=> Camel CDI - Improved support for programmatic lookup

camel-core/src/main/java/org/apache/camel/util/Time.java
Time#minutes(long)
Time#hours(long)
Time#days(long)
=> fix incorrect Time factory methods

components/camel-amqp/src/main/docs/amqp.adoc
Minor typo in hostname.  Also added a CDI based example.
=> Minor doc fixes for AMQP, fixed a typo and added CDI configuration.

camel-core/src/main/java/org/apache/camel/processor/exceptionpolicy/DefaultExceptionPolicyStrategy.java
=> Updated DefaultExceptionPolicyStrategy documentation

components/camel-flink/pom.xml, components/camel-flink/src/main/java/org/apache/camel/component/flink/DataStreamCallback.java, components/camel-flink/src/main/java/org/apache/camel/component/flink/DataStreamFlinkProducer.java, components/camel-flink/src/main/java/org/apache/camel/component/flink/FlinkComponent.java, components/camel-flink/src/main/java/org/apache/camel/component/flink/FlinkEndpoint.java, components/camel-flink/src/main/java/org/apache/camel/component/flink/Flinks.java, components/camel-flink/src/main/java/org/apache/camel/component/flink/VoidDataStreamCallback.java, components/camel-flink/src/test/java/org/apache/camel/component/flink/FlinkProducerTest.java
Hello @davsclaus ,
I have enhanced the `camel-flink` producer implementation to support `Flink datastream`. 
Please review.
=> [CAMEL-9869] Create Apache Flink Component

components/camel-bindy/src/main/docs/bindy.adoc
CAMEL-9954: added documentation for changes in 2.18.0
=> Camel 9954 documentation

components/camel-cxf/src/main/java/org/apache/camel/component/cxf/CxfEndpoint.java, components/camel-cxf/src/main/java/org/apache/camel/component/cxf/common/AbstractHostnameVerifierEndpointConfigurer.java, components/camel-cxf/src/main/java/org/apache/camel/component/cxf/common/AbstractSslEndpointConfigurer.java, components/camel-cxf/src/main/java/org/apache/camel/component/cxf/common/AbstractTLSClientParameterConfigurer.java, components/camel-cxf/src/main/java/org/apache/camel/component/cxf/jaxrs/ChainedCxfRsEndpointConfigurer.java, components/camel-cxf/src/main/java/org/apache/camel/component/cxf/jaxrs/CxfRsEndpoint.java, components/camel-cxf/src/main/java/org/apache/camel/component/cxf/jaxrs/CxfRsEndpointConfigurer.java, components/camel-cxf/src/main/java/org/apache/camel/component/cxf/jaxrs/CxfRsProducer.java, components/camel-cxf/src/main/java/org/apache/camel/component/cxf/jaxrs/HostnameVerifierCxfRsEndpointConfigurer.java, components/camel-cxf/src/main/java/org/apache/camel/component/cxf/jaxrs/SslCxfRsEndpointConfigurer.java, components/camel-cxf/src/test/java/org/apache/camel/component/cxf/CXFTestSupport.java, components/camel-cxf/src/test/java/org/apache/camel/component/cxf/jaxrs/CxfRsSslProducerTest.java, components/camel-cxf/src/test/resources/org/apache/camel/component/cxf/jaxrs/CxfRsSpringSslProducer.xml
Introduced Camel SSL-Context for cxfrs
I think the three abstract class that are introduced should be refactored to composition in stead of extension.
But I think for now this solution will work and maybe can close CAMEL-9046
=> CAMEL-9046: Implement Camel SSL-Context for cxfrs

components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/MongoDbTailingProcess.java
CAMEL-9826: Removed while loop and introduced CountDownLatch to wait for stop
=> CAMEL-9826: used CountDownLatch to wait for stop

parent/pom.xml, platforms/karaf/features/src/main/resources/features.xml
As requested for CAMEL-10002.
Removed netty41-version placeholder
=> removed netty41-version placeholder

components/camel-mina2/src/main/java/org/apache/camel/component/mina2/Mina2Consumer.java, components/camel-mina2/src/main/java/org/apache/camel/component/mina2/Mina2Producer.java, components/camel-mina2/src/main/java/org/apache/camel/component/mina2/Mina2TextLineDelimiter.java, components/camel-mina2/src/test/java/org/apache/camel/component/mina2/Mina2ClientModeTcpTextlineDelimiterTest.java, components/camel-mina2/src/test/java/org/apache/camel/component/mina2/Mina2DisconnectRaceConditionTest.java, components/camel-mina2/src/test/java/org/apache/camel/component/mina2/Mina2EncodingTest.java, components/camel-mina2/src/test/java/org/apache/camel/component/mina2/Mina2ExchangeTimeOutTest.java, components/camel-mina2/src/test/java/org/apache/camel/component/mina2/Mina2NoResponseFromServerTest.java, components/camel-mina2/src/test/java/org/apache/camel/component/mina2/Mina2ProducerShutdownMockTest.java, components/camel-mina2/src/test/java/org/apache/camel/component/mina2/Mina2ReverseProtocolHandler.java, components/camel-mina2/src/test/java/org/apache/camel/component/mina2/Mina2TransferExchangeOptionTest.java
Synchronizing on close method in handler
=> CAMEL-10024: sync on close and deprecation

tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/arquillian/ArquillianSyncBootJarLauncher.java, tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/util/ArquillianPackager.java
Added some tweaks to the classloaders to adapt to the new jar structure of spring-boot 1.4.0 jar structure.
Now the integration tests should (at least) start again.
=> CAMEL-10119: Fixed integration tests for spring-boot 1.4.0.RELEASE

components/camel-bam/src/test/profiles/eclipselink/META-INF/persistence.xml, components/camel-bam/src/test/profiles/eclipselink/META-INF/spring/spring.xml, components/camel-bam/src/test/profiles/hibernate/META-INF/persistence.xml, components/camel-bam/src/test/profiles/hibernate/META-INF/spring/spring.xml, components/camel-bam/src/test/profiles/openjpa/META-INF/persistence.xml, components/camel-bam/src/test/profiles/openjpa/META-INF/spring/spring.xml, components/camel-bam/src/test/resources/org/apache/camel/bam/spring.xml, components/camel-ibatis/src/test/resources/SqlMapConfig.xml, components/camel-ibatis/src/test/resources/org/apache/camel/component/ibatis/Account.xml, components/camel-mybatis/src/test/resources/SqlMapConfig.xml, components/camel-mybatis/src/test/resources/org/apache/camel/component/mybatis/Account.xml, tests/camel-itest-spring-boot/src/main/java/org/apache/camel/itest/springboot/ITestApplication.java, tests/camel-itest-spring-boot/src/main/java/org/apache/camel/itest/springboot/ITestXmlConfiguration.java, tests/camel-itest-spring-boot/src/test/resources/arquillian.xml, tests/camel-itest-spring-boot/src/test/resources/components/bam-persistence.xml, tests/camel-itest-spring-boot/src/test/resources/components/bam-spring.xml, tests/camel-itest-spring-boot/src/test/resources/components/ibatis-SqlMapConfig.xml, tests/camel-itest-spring-boot/src/test/resources/components/mybatis-SqlMapConfig.xml, tests/camel-itest-spring-boot/src/test/resources/spring-logback.xml
=> CAMEL-10197: Fixed and added license headers

components/camel-sjms/pom.xml, parent/pom.xml, tests/camel-itest/pom.xml, tests/camel-itest/src/test/resources/jbossts-properties.xml, tests/camel-itest/src/test/resources/org/apache/camel/itest/sql/FromJmsToJdbcIdempotentConsumerToJmsXaTest.xml, tests/camel-itest/src/test/resources/org/apache/camel/itest/tx/Jms2RequiresNewTest-context.xml
Camel-sjms depended on atomikos but it were not used in tests. Deleted.
=> CAMEL-10204: Using Narayana for testing (Atomikos deleted)

parent/pom.xml
upgrade hawtdispatch-version to 1.22
=> fix CAMEL-10249

camel-core/src/main/java/org/apache/camel/processor/ThrowExceptionProcessor.java
Provide code as written in https://issues.apache.org/jira/browse/CAMEL-10253
=> Fix CAMEL-10253: Add check on null

components/camel-websocket/src/main/java/org/apache/camel/component/websocket/WebsocketComponent.java, components/camel-websocket/src/test/java/org/apache/camel/component/websocket/WebsocketEndpointConfigurationTest.java
Fixes https://issues.apache.org/jira/browse/CAMEL-10342
=> CAMEL-10342: correctly set the web socket parameters

camel-core/src/main/java/org/apache/camel/impl/DefaultCamelContext.java, camel-core/src/test/java/org/apache/camel/impl/CamelContextAddRouteDefinitionsFromXmlTest.java, camel-core/src/test/resources/org/apache/camel/impl/route4_error.xml, camel-core/src/test/resources/org/apache/camel/impl/route4_ok.xml
Thanks @Fabryprog for the unit test and initial solution
=> CAMEL-10418 - Fix route removal logic in case of duplicated id.

components/camel-git/src/main/java/org/apache/camel/component/git/producer/GitProducer.java, components/camel-git/src/test/java/org/apache/camel/component/git/producer/GitProducerTest.java
Preferred working on separate branches instead of master as it moves a lot. Sorry for that. You can accept PRs the order you want, I'll fix the conflicts as soon as master changes...
=> CAMEL-10502 - Camel-git : Copy headers from in to out

components/camel-git/src/test/java/org/apache/camel/component/git/GitTestSupport.java, components/camel-git/src/test/java/org/apache/camel/component/git/consumer/GitConsumerTest.java, components/camel-git/src/test/java/org/apache/camel/component/git/producer/GitProducerTest.java
Preferred working on separate branches instead of master as it moves a lot. Sorry for that. You can accept PRs the order you want, I'll fix the conflicts as soon as master changes...
Couldn't create jira issue 'cause server's down.
=> CAMEL-10506 - Camel-git : Refactor unit tests using Jgit instead of camel-git

components/camel-atmos/src/main/docs/atmos-component.adoc
camel-atmos documentation polishing
=> CAMEL-8418

components/camel-cdi/src/main/java/org/apache/camel/cdi/CdiCamelConfiguration.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/CdiCamelConfigurationEvent.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/CdiCamelExtension.java, components/camel-cdi/src/test/java/org/apache/camel/cdi/test/CdiCamelConfigurationTest.java
See https://issues.apache.org/jira/browse/CAMEL-10391 for details
=> CAMEL-10391 Created a mechanism to configure Camel CDI via CDI event.

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/SalesforceComponent.java
Fixed warning message formatting.
=> CAMEL-10519 Disable TLSv1.0 in camel-salesforce

parent/pom.xml
tests (of course ;)) pass locally
=> Upgrade jsmpp to version 2.3.2

components/camel-spring-ws/src/main/java/org/apache/camel/component/spring/ws/SpringWebserviceConfiguration.java, components/camel-spring-ws/src/main/java/org/apache/camel/component/spring/ws/SpringWebserviceProducer.java, components/camel-spring-ws/src/test/java/org/apache/camel/component/spring/ws/SoapAttachmentResponseProcessor.java, components/camel-spring-ws/src/test/java/org/apache/camel/component/spring/ws/SoapResponseAttachmentTest.java, components/camel-spring-ws/src/test/resources/org/apache/camel/component/spring/ws/SoapResponseAttachmentTest-context.xml
@oscerd Here is the requested PR for 2.18.x
=> CAMEL-10679

platforms/spring-boot/components-starter/pom.xml
https://issues.apache.org/jira/browse/CAMEL-10717
=> CAMEL-10717 Fix relativePath in camel/platforms/spring-boot/components-starter/pom.xml

examples/camel-example-twitter-salesforce/README.md, examples/camel-example-twitter-salesforce/src/main/java/org/apache/camel/example/mention/Contact.java, examples/camel-example-twitter-salesforce/src/main/resources/application.properties
Adds documentation to the example.
=> CAMEL-10804 Create a Salesforce example

camel-core/pom.xml, components/camel-bindy/pom.xml, components/camel-elsql/pom.xml, components/camel-netty-http/pom.xml, components/camel-netty4/pom.xml, components/camel-spring-boot/pom.xml, components/camel-sql/pom.xml, parent/pom.xml
https://issues.apache.org/jira/browse/CAMEL-10141.
This PR makes more modules pass their tests in Java 9.
=> Camel 10141

components/camel-hl7/pom.xml, components/camel-mail/pom.xml, components/camel-soap/pom.xml, components/camel-spring-cloud-netflix/pom.xml, components/camel-spring-cloud/pom.xml, components/camel-syslog/pom.xml, connectors/examples/beverage-component/pom.xml, connectors/examples/foo-bar-wine-example/pom.xml, platforms/spring-boot/components-starter/pom.xml
https://issues.apache.org/jira/browse/CAMEL-10141
Make more Java 9 tests pass
=> Camel-10141 Make more Java 9 tests pass

parent/pom.xml
https://issues.apache.org/jira/browse/CAMEL-11153
=> CAMEL-11153: Add missing protobuf-guava-version declaration for camel-protobuf karaf feature

parent/pom.xml
https://issues.apache.org/jira/browse/CAMEL-11166
=> CAMEL-11166: make camel-package-maven-plugin work on Java 9

examples/camel-example-cxf-osgi/README.md
Possible fix for:
https://issues.apache.org/jira/browse/CAMEL-11059
=> camel-spring-dm feature removed :CAMEL-11059

parent/pom.xml
As requested in #1704. PR for the 2.19.x branch.
=> CAMEL-11309: Add camel-olingo4 and camel-rest-swagger to BOM

components/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/actuate/endpoint/CamelRoutesEndpoint.java, components/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/actuate/endpoint/CamelRoutesEndpointAutoConfiguration.java, components/camel-spring-boot/src/main/resources/META-INF/spring.factories, components/camel-spring-boot/src/test/java/org/apache/camel/spring/boot/actuate/endpoint/ActuatorTestRoute.java, components/camel-spring-boot/src/test/java/org/apache/camel/spring/boot/actuate/endpoint/CamelRoutesEndpointTest.java
See https://issues.apache.org/jira/browse/CAMEL-11335
=> CAMEL-11335: Add Actuator endpoint for exposing Camel routes

components/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/actuate/endpoint/CamelRoutesEndpoint.java
Add route state details as discussed in PR #1719.
=> CAMEL-11335: Add route state details

components/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/CamelAutoConfiguration.java, components/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/CamelConfigurationProperties.java
[CAMEL-11384] Added  auto configuration for turning on MDC logging
=> CAMEL-11384:Added the option for useMDCLogging

components/camel-sql/src/main/docs/sql-stored-component.adoc, components/camel-sql/src/main/java/org/apache/camel/component/sql/stored/BatchCallableStatementCreatorFactory.java, components/camel-sql/src/main/java/org/apache/camel/component/sql/stored/TemplateStoredProcedure.java, components/camel-sql/src/main/java/org/apache/camel/component/sql/stored/template/ast/OutParameter.java, components/camel-sql/src/main/java/org/apache/camel/component/sql/stored/template/generated/SSPTParser.java, components/camel-sql/src/main/java/org/apache/camel/component/sql/stored/template/grammar/sspt.jj, components/camel-sql/src/test/java/org/apache/camel/component/sql/stored/ParserTest.java
* Added docs and output parameter scale and type name
=> CAMEL-11393: sql-stored - Add support for typeNames and scale in grammar

platforms/karaf/commands/src/main/resources/OSGI-INF/blueprint/camel-commands.xml
https://issues.apache.org/jira/browse/CAMEL-11417
Thanks,
Saravanakumar
=> CAMEL-11417: Fixed tab completion for route-reset-stats command

parent/pom.xml, platforms/karaf/features/src/main/resources/features.xml
https://issues.apache.org/jira/browse/CAMEL-11453
Thanks!
=> CAMEL-11453 fix camel-box feature

components/camel-grpc/src/main/docs/grpc-component.adoc, components/camel-grpc/src/main/java/org/apache/camel/component/grpc/GrpcComponent.java, components/camel-grpc/src/main/java/org/apache/camel/component/grpc/GrpcConfiguration.java, components/camel-grpc/src/main/java/org/apache/camel/component/grpc/GrpcConsumer.java, components/camel-grpc/src/main/java/org/apache/camel/component/grpc/GrpcEndpoint.java, components/camel-grpc/src/main/java/org/apache/camel/component/grpc/GrpcProducer.java, components/camel-grpc/src/main/java/org/apache/camel/component/grpc/GrpcUtils.java, components/camel-grpc/src/test/java/org/apache/camel/component/grpc/GrpcConsumerAggregationTest.java, components/camel-grpc/src/test/java/org/apache/camel/component/grpc/GrpcConsumerConcurrentTest.java, components/camel-grpc/src/test/java/org/apache/camel/component/grpc/GrpcConsumerPropagationTest.java, components/camel-grpc/src/test/java/org/apache/camel/component/grpc/GrpcProducerAsyncTest.java, components/camel-grpc/src/test/java/org/apache/camel/component/grpc/GrpcProducerStreamingTest.java, components/camel-grpc/src/test/java/org/apache/camel/component/grpc/GrpcProducerSyncTest.java, components/camel-grpc/src/test/proto/pingpong.proto
@nicolaferraro , could you please to look at this PR. I've changed an URI format to be component consumer and producer more cloud service friendly. Thank you.
=> CAMEL-11456: Make the camel-grpc component more cloud service friendly

components/camel-sql/src/main/docs/sql-stored-component.adoc, components/camel-sql/src/main/java/org/apache/camel/component/sql/stored/CallableStatementWrapperFactory.java, components/camel-sql/src/main/java/org/apache/camel/component/sql/stored/SqlStoredEndpoint.java, components/camel-sql/src/main/java/org/apache/camel/component/sql/stored/TemplateStoredProcedure.java, components/camel-sql/src/test/java/org/apache/camel/component/sql/stored/CallableStatementWrapperTest.java, components/camel-sql/src/test/java/org/apache/camel/component/sql/stored/TemplateCacheTest.java
CAMEL-11319: sql-stored - Add support for function
=> CAMEL-11463 (cherry picked from commit 239c7438a47ad8b93f75ba2de62e0580799aed69)

components/camel-netty/src/main/docs/netty-component.adoc, components/camel-netty/src/test/resources/org/apache/camel/component/netty/SpringNettyUseSharedWorkerThreadPoolTest.xml, components/camel-netty4/src/main/docs/netty4-component.adoc, components/camel-netty4/src/test/resources/org/apache/camel/component/netty4/SpringNettyUseSharedWorkerThreadPoolTest.xml
Fixed minor typos in files related to camel-netty and camel-netty4 component
=> fixed minor typos.

components/camel-leveldb/src/main/java/org/apache/camel/component/leveldb/LevelDBFile.java
Fix for issue discussed in:
https://issues.apache.org/jira/browse/CAMEL-11623
Pretty straightforward, no additional changes.
=> CAMEL-11623: Catch throwable

components/camel-paho/src/main/docs/paho-component.adoc, components/camel-paho/src/main/java/org/apache/camel/component/paho/PahoEndpoint.java
https://issues.apache.org/jira/browse/CAMEL-11631
=> CAMEL-11631, Camel-Paho Missiong reconnect logic

components/camel-mongodb-gridfs/src/main/java/org/apache/camel/component/mongodb/gridfs/GridFsProducer.java
PR for https://issues.apache.org/jira/browse/CAMEL-11648
=> CAMEL-11648: gridfs skip metadata field if it is null

components/camel-aws/src/main/java/org/apache/camel/component/aws/s3/S3Producer.java
Changed S3Producer to use S3Constants.S3_OPERATION instead of EC2Constants.OPERATION
=> Fix S3Producer

examples/camel-example-restlet-jdbc/src/main/resources/xml-rest-dsl.xml
Fix typo on naming conventions.
=> Fix typo on rest endpoints

components/camel-atmosphere-websocket/src/main/java/org/apache/camel/component/atmosphere/websocket/CamelWebSocketServlet.java, components/camel-atmosphere-websocket/src/main/java/org/apache/camel/component/atmosphere/websocket/WebsocketConsumer.java, components/camel-atmosphere-websocket/src/test/java/org/apache/camel/component/atmosphere/websocket/WebsocketCamelRouterTestSupport.java, components/camel-atmosphere-websocket/src/test/java/org/apache/camel/component/atmosphere/websocket/WebsocketCamelRouterWithInitParamTestSupport.java
This commit will fix the problem with initialisation of Atmosphere framework and gives ability to use this component with combination of spring boot. It is important for now to keep version of atmosphere 2.4.10
=> CAMEL-11725 applied a new way of Atmosphere Framework initialization

components/camel-bonita/pom.xml, components/camel-bonita/src/main/docs/bonita-component.adoc, components/camel-bonita/src/main/java/org/apache/camel/component/bonita/api/BonitaAPIBuilder.java, components/camel-bonita/src/main/java/org/apache/camel/component/bonita/api/filter/BonitaAuthFilter.java, components/camel-bonita/src/main/java/org/apache/camel/component/bonita/api/util/BonitaAPIUtil.java, components/camel-bonita/src/main/java/org/apache/camel/component/bonita/producer/BonitaProducer.java, components/camel-bonita/src/test/java/org/apache/camel/component/bonita/integration/BonitaIntegrationTestSupport.java, components/camel-bonita/src/test/java/org/apache/camel/component/bonita/integration/BonitaProducerIntegrationTest.java, components/camel-bonita/src/test/resources/test-options.properties, platforms/spring-boot/components-starter/camel-bonita-starter/pom.xml
https://issues.apache.org/jira/browse/CAMEL-11383
=> CAMEL-11383: Replace Jersey JAX-RS client with CXF in Bonita component

platforms/karaf/features/src/main/resources/features.xml
=> CAMEL-11695: fix Karaf feature for test

platforms/karaf/features/src/main/resources/features.xml
https://issues.apache.org/jira/browse/CAMEL-11768
=> CAMEL-11768: camel-itest-karaf - CamelDockerTest fails

components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpConfiguration.java, components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpConsumer.java, components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpUtils.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/FtpSimpleConsumeDirectoryParseWithAbsoluteDepthNoStepwiseTest.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/FtpUtilsExtractDirNameFromAbsolutePathTest.java
parser ends up with absolute paths
=> CAMEL-11754 - add option to extract file name if ftp client directory

components/camel-atmosphere-websocket/pom.xml, components/camel-atmosphere-websocket/src/test/java/org/apache/camel/component/atmosphere/websocket/MemoryWebSocketStoreTest.java, components/camel-aws/pom.xml, components/camel-aws/src/test/java/org/apache/camel/component/aws/sqs/SqsEndpointTest.java
Migrate camel-atmosphere-websocket from easymock to mockito.
=> CAMEL-11845: Migrate easymock and powermock to mockito

components/camel-atomix/src/main/docs/atomix-map-component.adoc, components/camel-atomix/src/main/docs/atomix-messaging-component.adoc, components/camel-atomix/src/main/docs/atomix-multimap-component.adoc, components/camel-atomix/src/main/docs/atomix-queue-component.adoc, components/camel-atomix/src/main/docs/atomix-set-component.adoc, components/camel-atomix/src/main/docs/atomix-value-component.adoc, components/camel-atomix/src/main/java/org/apache/camel/component/atomix/client/map/AtomixMapEndpoint.java, components/camel-atomix/src/main/java/org/apache/camel/component/atomix/client/messaging/AtomixMessagingEndpoint.java, components/camel-atomix/src/main/java/org/apache/camel/component/atomix/client/multimap/AtomixMultiMapEndpoint.java, components/camel-atomix/src/main/java/org/apache/camel/component/atomix/client/queue/AtomixQueueEndpoint.java, components/camel-atomix/src/main/java/org/apache/camel/component/atomix/client/set/AtomixSetEndpoint.java, components/camel-atomix/src/main/java/org/apache/camel/component/atomix/client/value/AtomixValueEndpoint.java
=> CAMEL-11936 - Fix syntax for Atomix component

platforms/camel-catalog/src/main/java/org/apache/camel/catalog/SimpleValidationResult.java
=> Set deprecation annotations to SimpleValidationResult

components/camel-spring-redis/src/main/docs/spring-redis-component.adoc
Hi - I'm contributing a fix to the ASCII-doc documentation with a simple fix to a URL. Can you review it when you get a chance?
=> FUSEDOC-1898 updated redis URL

components/camel-restlet/src/main/java/org/apache/camel/component/restlet/DefaultRestletHost.java, components/camel-restlet/src/main/java/org/apache/camel/component/restlet/RestletComponent.java, components/camel-restlet/src/main/java/org/apache/camel/component/restlet/RestletHost.java, components/camel-restlet/src/main/java/org/apache/camel/component/restlet/RestletHostOptions.java
https://issues.apache.org/jira/browse/CAMEL-12011
=> CAMEL-12011: Add RestletHost abstraction for creation of Restlet server

components/camel-google-bigquery/pom.xml, components/camel-google-pubsub/pom.xml
Adressed https://issues.apache.org/jira/browse/CAMEL-12017 - added the dependency explicitly.
=> CAMEL-12017: Added httpclient dependency

components/camel-coap/src/main/java/org/apache/camel/coap/CamelCoapResource.java, components/camel-coap/src/test/java/org/apache/camel/coap/CoAPRestComponentTest.java
https://issues.apache.org/jira/browse/CAMEL-12029
=> CAMEL-12029: Return 4.05 response if no consumers were found for the request method

camel-core/src/main/java/org/apache/camel/builder/ExpressionClause.java, camel-core/src/main/java/org/apache/camel/model/ProcessorDefinition.java, camel-core/src/test/java/org/apache/camel/builder/ExpressionClauseSupplierTest.java, camel-core/src/test/java/org/apache/camel/model/ProcessDefinitionSetBodyTest.java
Enhanced setBody DSL with new methods accepting supplier and function argument, to align with Java 8 APIs.
=> CAMEL-11532 Java DSL enhancement to accept supplier and function arguments

examples/camel-example-olingo4-blueprint/README.md, examples/camel-example-olingo4-blueprint/pom.xml, examples/camel-example-olingo4-blueprint/src/main/java/org/apache/camel/example/olingo4/blueprint/Olingo4TestConfiguration.java, examples/camel-example-olingo4-blueprint/src/main/resources/OSGI-INF/blueprint/odata.xml, examples/camel-example-olingo4-blueprint/src/main/resources/data/person1.json, examples/camel-example-olingo4-blueprint/src/main/resources/data/person2json, examples/pom.xml
https://issues.apache.org/jira/browse/CAMEL-12064
Thanks!
=> [CAMEL-12064] Create camel-example-olingo4-blueprint example

components/camel-ribbon/src/main/java/org/apache/camel/component/ribbon/cloud/RibbonServiceDefinition.java, examples/camel-example-cassandra-kubernetes/ReadMe.md
Signed-off-by: eric-lee-ltk <dagang.li@huawei.com>
=> fixed typo

components/camel-sap-netweaver/src/main/docs/sap-netweaver-component.adoc
Fixes https://issues.apache.org/jira/browse/CAMEL-12102
=> Add "command" header to the example

camel-core/src/main/java/org/apache/camel/processor/WireTapProcessor.java
Thanks Bas Claessen, @davsclaus s review is important 👍
=> CAMEL-12108 - PR on behalf of Bas Claessen

camel-core/src/main/java/org/apache/camel/impl/ThrottlingExceptionRoutePolicy.java, camel-core/src/test/java/org/apache/camel/processor/ThrottlingExceptionRoutePolicyKeepOpenOnInitTest.java, camel-core/src/test/java/org/apache/camel/processor/ThrottlingExceptionRoutePolicyOpenViaConfigTest.java
PR for https://issues.apache.org/jira/browse/CAMEL-12125
=> [CAMEL-12125] add keepOpen to endpoint circuit breaker

components/camel-bean-validator/src/main/docs/bean-validator-component.adoc
Hi - I'm contributing a fix to the ASCII-doc documentation. Can you please review it?
https://issues.jboss.org/browse/FUSEDOC-1921
=> FUSE-DOC-1921 added info for XML route definition

docs/user-manual/en/building.adoc
see http://camel.apache.org/camel-2200-release.html#Camel2.20.0Release-Importantchangestoconsiderwhenupgrading
=> Indicate new Maven version requirement 3.3.3 for Camel 2.20 build

components/camel-dns/src/main/docs/dns-component.adoc, components/camel-dns/src/main/java/org/apache/camel/component/dns/policy/DnsActivation.java, components/camel-dns/src/main/java/org/apache/camel/component/dns/policy/DnsActivationPolicy.java, components/camel-dns/src/test/java/org/apache/camel/component/dns/policy/DnsActivationTest.java
Allows to start/stop routes based on CNAMEs
=> CAMEL-12177 - Adding Dns Activation policy

components/camel-xmlsecurity/src/main/java/org/apache/camel/component/xmlsecurity/api/XAdESSignatureProperties.java, components/camel-xmlsecurity/src/test/java/org/apache/camel/component/xmlsecurity/XAdESSignaturePropertiesTest.java
of XADES element DataObjectFormat
=> CAMEL-12181: XML Signature: '#' missing in ObjectReference attribute 

components/camel-xchange/src/main/docs/xchange-component.adoc, components/camel-xchange/src/main/java/org/apache/camel/component/xchange/XChangeComponent.java, components/camel-xchange/src/main/java/org/apache/camel/component/xchange/XChangeConfiguration.java, components/camel-xchange/src/main/java/org/apache/camel/component/xchange/XChangeEndpoint.java, components/camel-xchange/src/main/java/org/apache/camel/component/xchange/XChangeMarketDataProducer.java, components/camel-xchange/src/main/java/org/apache/camel/component/xchange/XChangeMetaDataProducer.java, components/camel-xchange/src/test/java/org/apache/camel/component/xchange/market/TickerConsumerTest.java, components/camel-xchange/src/test/java/org/apache/camel/component/xchange/metadata/MetaDataConsumerTest.java
=> [XChange] Get the list of supported currency pairs

components/camel-undertow/src/test/java/org/apache/camel/component/undertow/ws/TestClient.java, components/camel-undertow/src/test/java/org/apache/camel/component/undertow/ws/UndertowWsConsumerRouteTest.java, components/camel-undertow/src/test/java/org/apache/camel/component/undertow/ws/UndertowWsProducerRouteRestartTest.java, components/camel-undertow/src/test/java/org/apache/camel/component/undertow/ws/UndertowWsProducerRouteTest.java, components/camel-undertow/src/test/java/org/apache/camel/component/undertow/ws/UndertowWsTwoRoutesTest.java, components/camel-undertow/src/test/java/org/apache/camel/component/undertow/ws/UndertowWsTwoRoutesToSameEndpointSendToAllHeaderTest.java, components/camel-undertow/src/test/java/org/apache/camel/component/undertow/ws/UndertowWsTwoRoutesToSameEndpointTest.java, components/camel-undertow/src/test/java/org/apache/camel/component/undertow/ws/UndertowWssRouteTest.java
https://issues.apache.org/jira/browse/CAMEL-12247
=> [CAMEL-12247] camel-undertow not compatible with ahc-version 2.3.0

components/camel-bindy/src/main/docs/bindy-dataformat.adoc
=> Add description of align attribute for DataField

components/camel-jasypt/src/main/docs/jasypt.adoc
Hi - I'm contributing a fix to the ASCII-doc documentation. Can you please review it?
=> FUSE-DOC-1249 include dependency for Apache Karaf

components/camel-box/camel-box-component/src/main/docs/box-component.adoc
Changes in the camel-box component
: https://issues.jboss.org/browse/FUSEDOC-2320
=> FUSEDOC-2320: minor fixed in camel-box

parent/pom.xml
Upgrade to jackson-databind 2.8.11.1
=> Upgrade to jackson-databind 2.8.11.1

components/camel-cxf/src/main/java/org/apache/camel/component/cxf/jaxrs/CxfRsProducer.java, components/camel-cxf/src/test/java/org/apache/camel/component/cxf/jaxrs/CxfRsProducerEndpointConfigurerTest.java
With this change CxfRsProducer configures CxfRsEndpointConfigurer while using the Proxy API (invokeProxyClient)
=> CAMEL-12399: CxfRsProducer configures CxfRsEndpointConfigurer while using the Proxy API

docs/user-manual/en/building.adoc
=> Camel 12403: Updated build instructions

components/camel-cxf/src/main/docs/cxf-component.adoc
Hello - updated the documentation for the CXF component to address JIRA issue fusedoc-1940. Can you kindle review my edits?  Thank you!
=> fusedoc-1940 updates to CXF component doc

camel-core/src/main/java/org/apache/camel/Route.java, camel-core/src/main/java/org/apache/camel/impl/DefaultRoute.java, camel-core/src/main/java/org/apache/camel/model/ProcessorDefinition.java, camel-core/src/main/java/org/apache/camel/model/RouteDefinition.java, camel-core/src/test/java/org/apache/camel/model/RouteGroupTest.java, camel-core/src/test/java/org/apache/camel/model/XmlRouteGroupTest.java, camel-core/src/test/resources/org/apache/camel/model/routeGroup.xml
@davsclaus I need to practice a little bit to get back to camel so do you mind doing a review ? :)
=> CAMEL-11669: Routes : add 'group'

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/DefaultKafkaManualCommit.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java
partitionLastOffset value always remains -1 so consumer.commitSync is never called in method commitOffset
=> Fixed the Defect manual commit not working

components/camel-http/src/main/java/org/apache/camel/component/http/HttpComponent.java, components/camel-http4/src/main/java/org/apache/camel/component/http4/HttpComponent.java, components/camel-netty4-http/src/main/java/org/apache/camel/component/netty4/http/NettyHttpComponent.java, components/camel-netty4-http/src/test/java/org/apache/camel/component/netty4/http/rest/RestNettyProducerThrowExceptionErrorTest.java, components/camel-restlet/src/main/java/org/apache/camel/component/restlet/RestletComponent.java, components/camel-restlet/src/test/java/org/apache/camel/component/restlet/RestletProducerThrowExceptionErrorTest.java, components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowComponent.java, components/camel-undertow/src/test/java/org/apache/camel/component/undertow/rest/RestUndertowProducerThrowExceptionErrorTest.java
CAMEL-12442:rest-dsl - Rest producer should use RestConfiguration
=> CAMEL-12442:rest-dsl - Rest producer should use RestConfiguration

archetypes/camel-archetype-spring-boot/src/main/resources/archetype-resources/src/main/resources/application.properties, components/camel-spring-boot/src/test/resources/application.properties, examples/camel-example-rabbitmq/src/main/resources/application.properties, examples/camel-example-spring-boot-clustered-route-controller/cluster-node/src/main/resources/application.properties, examples/camel-example-spring-boot-health-checks/application/src/main/resources/application.properties, examples/camel-example-spring-boot-master/src/main/resources/application.properties, examples/camel-example-spring-boot-supervising-route-controller/src/main/resources/application.properties, examples/camel-example-spring-boot-xml/src/main/resources/application.properties
I guess there is no more remaining changes required considering SB 2 upgrade.
=> CAMEL-12383 - changes regarding SB 2.0 upgrade

components/camel-aws/src/main/java/org/apache/camel/component/aws/s3/S3Producer.java
See https://issues.apache.org/jira/browse/CAMEL-12487
=> CAMEL-12487: S3Producer must close the streams it opens

apache-camel/pom.xml, apache-camel/src/main/descriptors/common-bin.xml, bom/camel-bom/pom.xml, components/camel-rxjava2/pom.xml, components/camel-rxjava2/src/main/docs/rxjava2-component.adoc, components/camel-rxjava2/src/main/java/org/apache/camel/component/rxjava2/engine/RxJavaCamelProcessor.java, components/camel-rxjava2/src/main/java/org/apache/camel/component/rxjava2/engine/RxJavaStreamsConstants.java, components/camel-rxjava2/src/main/java/org/apache/camel/component/rxjava2/engine/RxJavaStreamsService.java, components/camel-rxjava2/src/main/java/org/apache/camel/component/rxjava2/engine/RxJavaStreamsServiceFactory.java, components/camel-rxjava2/src/main/resources/META-INF/LICENSE.txt, components/camel-rxjava2/src/main/resources/META-INF/NOTICE.txt, components/camel-rxjava2/src/main/resources/META-INF/services/org/apache/camel/reactive-streams/rxjava2, components/camel-rxjava2/src/test/java/org/apache/camel/component/rxjava2/engine/RxJavaStreamsServiceBackpressureTest.java, components/camel-rxjava2/src/test/java/org/apache/camel/component/rxjava2/engine/RxJavaStreamsServiceEventTypeTest.java, components/camel-rxjava2/src/test/java/org/apache/camel/component/rxjava2/engine/RxJavaStreamsServiceSubscriberTest.java, components/camel-rxjava2/src/test/java/org/apache/camel/component/rxjava2/engine/RxJavaStreamsServiceTest.java, components/camel-rxjava2/src/test/java/org/apache/camel/component/rxjava2/engine/RxJavaStreamsServiceTestSupport.java, components/camel-rxjava2/src/test/java/org/apache/camel/component/rxjava2/engine/suport/TestSubscriber.java, components/camel-rxjava2/src/test/resources/log4j2.properties, components/pom.xml, parent/pom.xml, platforms/spring-boot/components-starter/camel-rxjava2-starter/pom.xml, platforms/spring-boot/components-starter/camel-rxjava2-starter/src/main/resources/META-INF/LICENSE.txt, platforms/spring-boot/components-starter/camel-rxjava2-starter/src/main/resources/META-INF/NOTICE.txt, platforms/spring-boot/components-starter/camel-rxjava2-starter/src/main/resources/META-INF/spring.provides, platforms/spring-boot/components-starter/pom.xml, platforms/spring-boot/spring-boot-dm/camel-spring-boot-dependencies/pom.xml
I've just fixed backpressure issues on top of the work by @lburgazzoli.
=> CAMEL-10806: Add a RxJava2 module

components/camel-cxf/src/main/java/org/apache/camel/component/cxf/CxfProducer.java
Correct a typo in a local variable.
=> Correct typo

camel-core/src/main/docs/rest-dsl.adoc, components/camel-jetty9/src/test/java/org/apache/camel/component/jetty/rest/RestJettyAcceptTest.java, components/camel-jetty9/src/test/java/org/apache/camel/component/jetty/rest/RestJettyContentTypeTest.java, components/camel-jetty9/src/test/java/org/apache/camel/component/jetty/rest/RestJettyRequiredBodyTest.java, components/camel-jetty9/src/test/java/org/apache/camel/component/jetty/rest/RestJettyRequiredHttpHeaderTest.java, components/camel-jetty9/src/test/java/org/apache/camel/component/jetty/rest/RestJettyRequiredQueryParameterTest.java
@davsclaus 
This come as a late review as I was not able to grab free time earlier. Could you please comment ?
=> CAMEL-11162: Corrected doc and alleviated tests

components/camel-cxf/src/main/java/org/apache/camel/component/cxf/CxfConsumer.java, components/camel-cxf/src/main/java/org/apache/camel/component/cxf/jaxrs/CxfRsInvoker.java, components/camel-cxf/src/test/java/org/apache/camel/component/cxf/CxfConsumerContinuationTimeoutTest.java
=> CAMEL-12577: Re-apply CAMEL-12104 Unintuitive default cxf timeout

camel-core/src/main/java/org/apache/camel/processor/aggregate/AggregateProcessor.java
AggregateProcessor doStop() method changed to call shutdown() instead of
shutdownNow()
=> CAMEL-12588 Fix Improvement

Jenkinsfile
=> Revert "[CAMEL-12593] Active deploy profile when deploying"

camel-core/src/main/docs/rest-dsl.adoc
Fix: https://issues.apache.org/jira/browse/CAMEL-11783
=> Add back the section: "Configuring Rest DSL"

components/camel-jaxb/src/main/java/org/apache/camel/converter/jaxb/JaxbDataFormat.java
See https://issues.apache.org/jira/browse/CAMEL-12653.
=> [CAMEL-12653] Pass given 'Exchange' to type converter

components/camel-dozer/src/main/java/org/apache/camel/component/dozer/BaseConverter.java, components/camel-dozer/src/main/java/org/apache/camel/component/dozer/DozerConfiguration.java, components/camel-dozer/src/main/java/org/apache/camel/component/dozer/DozerEndpoint.java, components/camel-dozer/src/main/java/org/apache/camel/converter/dozer/DozerBeanMapperConfiguration.java, components/camel-dozer/src/main/java/org/apache/camel/converter/dozer/DozerThreadContextClassLoader.java, components/camel-dozer/src/main/java/org/apache/camel/converter/dozer/DozerTypeConverter.java, components/camel-dozer/src/main/java/org/apache/camel/converter/dozer/DozerTypeConverterLoader.java, components/camel-dozer/src/main/java/org/apache/camel/converter/dozer/MapperFactory.java, components/camel-dozer/src/test/java/org/apache/camel/converter/dozer/DozerTestArtifactsFactory.java, components/camel-dozer/src/test/java/org/apache/camel/converter/dozer/DozerTypeConverterDTOTest.java, components/camel-dozer/src/test/java/org/apache/camel/converter/dozer/DozerTypeConverterTest.java, components/camel-dozer/src/test/resources/application-context-map-id.xml, components/camel-dozer/src/test/resources/application-context.xml, parent/pom.xml
- https://issues.apache.org/jira/browse/CAMEL-12693
=> [CAMEL-12693] Upgraded camel-dozer to dozer v6.3.0

parent/pom.xml, tests/camel-itest-spring-boot/pom.xml, tests/camel-itest-spring-boot/src/main/java/org/apache/camel/itest/springboot/ITestConfig.java, tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/util/ArquillianPackager.java, tests/camel-itest-spring-boot/src/test/java/org/apache/camel/itest/springboot/util/BOMResolver.java
Please see details in https://issues.apache.org/jira/browse/CAMEL-12687?focusedCommentId=16563134&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16563134
=> CAMEL-12687 - upgrade shrinkwrap and arquillian versions

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/dto/bulk/ContentType.java
Added JSON to JobInfo ContentType. Documented here: https://developer.salesforce.com/docs/atlas.en-us.api_asynch.meta/api_asynch/asynch_api_reference_jobinfo.htm
=> CAMEL-12703: camel-salesforce - Added JSON as a valid contentType

docs/user-manual/en/SUMMARY.md, docs/user-manual/en/camel-boot.adoc, docs/user-manual/en/camel-jar-dependencies.adoc, docs/user-manual/en/error-handling-in-camel.adoc
@oscerd @onderson Hope it aligns with what you've worked on.
=> CAMEL-11497: Update user guide toc in summary and migrate some pages

components/camel-script/pom.xml, platforms/karaf/features/src/main/resources/features.xml
I have it running with this PR in karaf-itests and also manual install in karaf 4.1.2. Could one double-check please ?
More context in [CAMEL-12715](https://issues.apache.org/jira/browse/CAMEL-12715).
=> CAMEL-12715: Fixed camel-script dependencies

components/camel-olingo2/camel-olingo2-component/pom.xml
=> CAMEL-12549 - upgrade groovy for olingo2

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java
Check  isAllowManualCommit before setting the state
(Fix the manual commit for the state)
Sorry for my previous pull request i think now is the right solution without adding parameters to the component.
=> CAMEL-12732 Take into account isAllowManualCommit

parent/pom.xml
- https://issues.apache.org/jira/browse/CAMEL-12768
=> CAMEL-12768: Upgraded dozer to 6.4.1

components/camel-spark/src/main/docs/spark-component.adoc, components/camel-spark/src/main/java/org/apache/camel/component/spark/DataFrameCallback.java, components/camel-spark/src/main/java/org/apache/camel/component/spark/DataFrameSparkProducer.java, components/camel-spark/src/main/java/org/apache/camel/component/spark/HiveSparkProducer.java, components/camel-spark/src/main/java/org/apache/camel/component/spark/SparkEndpoint.java, components/camel-spark/src/test/java/org/apache/camel/component/spark/SparkProducerTest.java, parent/pom.xml
Upgraded Spark to 2.3.1. Did not see any issues with itests for Karaf and osgi.
=> CAMEL-11325: Upgraded Apache Spark to 2.3.1

components/camel-cxf/src/main/java/org/apache/camel/component/cxf/CxfEndpoint.java, components/camel-cxf/src/main/java/org/apache/camel/component/cxf/CxfSpringEndpoint.java
https://issues.apache.org/jira/browse/CAMEL-12829
=> CAMEL-12829: An autocreated CXF Bus not shut down in CxfSpringEndpoint

components/camel-salesforce/camel-salesforce-component/src/main/docs/salesforce-component.adoc
FUSEDOC-2261 Added documentation for Bulk and Rest APIs.
=> FUSEDOC-2261 Added content for some of the Bulk and Rest APIs

components/camel-salesforce/camel-salesforce-component/src/main/docs/salesforce-component.adoc
Added content for getReportDescription API.
=> FUSEDOC-2261 - Added content for remaining API.  

components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/SftpOperations.java
=> CAMEL-12848 - handle differently on windows for fa

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/SalesforceComponent.java
setting default idletimeout as per the suggestion in the ticket.
=> CAMEL-12484: setting default idletimeout for httpclient

components/camel-swagger-java/src/main/java/org/apache/camel/swagger/RestSwaggerProcessor.java, components/camel-swagger-java/src/main/java/org/apache/camel/swagger/RestSwaggerSupport.java, components/camel-swagger-java/src/main/java/org/apache/camel/swagger/servlet/RestSwaggerServlet.java
This PR addresses the issue described on https://issues.apache.org/jira/browse/CAMEL-12855
=> CAMEL-12855 - camel-swagger-java not honoring the x-forwarded-[host,proto,prefix] headers.

tooling/maven/camel-restdsl-swagger-plugin/src/main/docs/camel-restdsl-swagger-plugin.adoc
Included "supports JSON and YAML" for the specificationUri.
=> Updated specificationUri description

docs/user-manual/en/backlog-tracer.adoc, docs/user-manual/en/faq.adoc, docs/user-manual/en/faq/exception-beandefinitionstoreexception.adoc, docs/user-manual/en/faq/exception-javaxnamingnoinitialcontextexception.adoc, docs/user-manual/en/faq/exception-orgapachecamelnosuchendpointexception.adoc, docs/user-manual/en/faq/exception-orgxmlsaxsaxparseexception.adoc, docs/user-manual/en/faq/how-do-i-enable-debug-logging.adoc, docs/user-manual/en/faq/how-do-i-invoke-camel-routes-from-jbi.adoc, docs/user-manual/en/faq/how-do-i-make-my-jms-endpoint-transactional.adoc, docs/user-manual/en/faq/how-do-i-set-the-mep-when-interacting-with-jbi.adoc, docs/user-manual/en/faq/how-do-i-use-java-14-logging.adoc, docs/user-manual/en/faq/how-do-i-use-log4j.adoc, docs/user-manual/en/faq/how-do-the-direct-event-seda-and-vm-endpoints-compare.adoc, docs/user-manual/en/faq/how-do-the-timer-and-quartz-endpoints-compare.adoc, docs/user-manual/en/faq/memory-leak-when-adding-and-removing-routes-at-runtime.adoc, docs/user-manual/en/faq/why-do-camel-throw-so-many-noclassdeffoundexception-on-startup.adoc, docs/user-manual/en/faq/why-does-camel-use-too-many-threads-with-producertemplate.adoc, docs/user-manual/en/faq/why-does-maven-not-download-dependencies.adoc, docs/user-manual/en/faq/why-does-my-jms-route-only-consume-one-message-at-once.adoc, docs/user-manual/en/graceful-shutdown.adoc
https://issues.apache.org/jira/browse/CAMEL-11497
All FAQs are migrated by this commit.
=> CAMEL-11497: Migrate FAQ - remaining questions

docs/user-manual/en/SUMMARY.md, docs/user-manual/en/user-stories.adoc
https://issues.apache.org/jira/browse/CAMEL-11497
=> CAMEL-11497: Migrate User Stories

examples/camel-example-servlet-tomcat-no-spring/README.md
Removed duplicate url for servlet.
=> Updated readme.txt

components/camel-jgroups/src/main/docs/jgroups-component.adoc
=> Improved doc to use master api for singleton route usecase

camel-core/src/main/docs/rest-dsl.adoc
=> renamed apiProperties to apiProperty in camel-core/src/main/docs/rest-dsl.adoc

components/camel-swagger-java/src/main/java/org/apache/camel/swagger/RestSwaggerSupport.java
=> CAMEL-12926: fixed null pointer exceptions accessing swagger url inlueprint projects

camel-core/src/main/java/org/apache/camel/processor/RestBindingAdvice.java
- Support for the catchAll */* MimeType
- Added some logs to ease debugging when clientRequestValidation is
turned on
=> UPDATED RestBindingAdvice

examples/camel-example-kafka/README.adoc
Fix typo at Kafka Example Read me.
=> Fix typo at READMe.adoc 

parent/pom.xml, platforms/karaf/features/src/main/resources/features.xml
=> Upgrading johnzon to 1.1.10

components/camel-core-osgi/src/main/java/org/apache/camel/core/osgi/OsgiCamelContextHelper.java, components/camel-core-osgi/src/main/java/org/apache/camel/core/osgi/OsgiDefaultCamelContext.java
Split the onContextStop issue out of CAMEL-12969.
=> CAMEL-12987: Ensure onContextStop is called on the OsgiServiceRegistry.

camel-core/src/test/java/org/apache/camel/processor/RouteStartupOrderLastTest.java, docs/user-manual/en/configuring-route-startup-ordering-and-autostartup.adoc, docs/user-manual/en/getting-started.adoc, docs/user-manual/en/graceful-shutdown.adoc
https://issues.apache.org/jira/browse/CAMEL-12988
Also includes a commit for CAMEL-11497, which is the required artifact for the fix to be based on.
=> CAMEL-12988: Update doc to clarify how to specify routes to start up last

components/camel-spring-boot/src/main/docs/spring-boot.adoc
=> Fix broken links

platforms/karaf/features/src/main/resources/features.xml, tests/camel-itest-karaf/src/test/java/org/apache/camel/itest/karaf/CamelRestSwaggerTest.java
CAMEL-13023:Add camel-rest-swagger as Karaf feature
=> "CAMEL-13023:Add camel-rest-swagger as Karaf feature"

camel-core/src/main/java/org/apache/camel/reifier/ToDynamicReifier.java, camel-core/src/main/java/org/apache/camel/runtimecatalog/impl/Pair.java, camel-core/src/main/java/org/apache/camel/runtimecatalog/impl/URISupport.java, camel-core/src/main/java/org/apache/camel/runtimecatalog/impl/UnsafeUriCharactersEncoder.java, camel-core/src/main/java/org/apache/camel/support/DefaultComponent.java, camel-core/src/test/java/org/apache/camel/issues/EndpointWithRawUriParameterTest.java, camel-util/src/main/java/org/apache/camel/util/Pair.java, camel-util/src/main/java/org/apache/camel/util/URIScanner.java, camel-util/src/main/java/org/apache/camel/util/URISupport.java, camel-util/src/main/java/org/apache/camel/util/UnsafeUriCharactersEncoder.java, camel-util/src/test/java/org/apache/camel/util/URISupportTest.java, platforms/camel-catalog/pom.xml
Also fixes compile error at camel-catalog
https://issues.apache.org/jira/browse/CAMEL-12982
=> CAMEL-12982: Support RAW{} syntax in URISupport (again)

camel-core/src/main/java/org/apache/camel/impl/DefaultComponent.java, camel-core/src/main/java/org/apache/camel/model/ToDynamicDefinition.java, camel-core/src/main/java/org/apache/camel/runtimecatalog/Pair.java, camel-core/src/main/java/org/apache/camel/runtimecatalog/URISupport.java, camel-core/src/main/java/org/apache/camel/runtimecatalog/UnsafeUriCharactersEncoder.java, camel-core/src/main/java/org/apache/camel/util/Pair.java, camel-core/src/main/java/org/apache/camel/util/URIScanner.java, camel-core/src/main/java/org/apache/camel/util/URISupport.java, camel-core/src/main/java/org/apache/camel/util/UnsafeUriCharactersEncoder.java, camel-core/src/test/java/org/apache/camel/issues/EndpointWithRawUriParameterTest.java, camel-core/src/test/java/org/apache/camel/util/URISupportTest.java, platforms/camel-catalog/pom.xml, platforms/camel-catalog/src/main/java/org/apache/camel/catalog/Pair.java, platforms/camel-catalog/src/main/java/org/apache/camel/catalog/URISupport.java, platforms/camel-catalog/src/main/java/org/apache/camel/catalog/UnsafeUriCharactersEncoder.java
https://issues.apache.org/jira/browse/CAMEL-12982
This is for Camel 2.24.0.
=> CAMEL-12982: Support RAW{} syntax in URISupport

platforms/commands/commands-core/src/main/java/org/apache/camel/commands/AbstractLocalCamelController.java
karaf route-profile command improvement
=> CAMEL-13093

examples/camel-example-cdi-cassandraql/pom.xml, examples/camel-example-cdi/pom.xml
CAMEL-13131: Removed duplicated dependencies
=> CAMEL-13131: Removed duplicated dependencies

components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/MongoDbEndpoint.java
CAMEL-13125 : Removal of stop method from MongoDbEndpoint
=> CAMEL-13125 : Removal of stop method from MongoDbEndpoint

components/camel-http4/src/main/docs/http4-component.adoc
Replaced 'httpClient.cookiePolicy' with httpClient.cookieSpec in the Disabling Cookies section.
=> FUSEDOC-2877 Updated Disabling Cookies section.

parent/pom.xml
Now the OSGi features also works and the karaf feature validation passes
=> Upgrade mvel and jpbm/optaplanner/drools etc.

core/camel-core/src/test/java/org/apache/camel/component/properties/PropertiesComponentDefaultFunctionsTest.java
Was assuming JAVA_HOME exists which is standard but not mandatory.
=> CAMEL-13297 Pick env: variable at random for test

components/camel-lra/src/test/java/org/apache/camel/service/lra/AbstractLRATestSupport.java, components/camel-lra/src/test/java/org/apache/camel/service/lra/LRAFailuresIT.java, components/camel-lra/src/test/java/org/apache/camel/service/lra/LRAManualIT.java, components/camel-lra/src/test/java/org/apache/camel/service/lra/LRATimeoutIT.java
https://issues.apache.org/jira/browse/CAMEL-13353
I verify these tests with the Narayana 5.9.3.Final and they are fixed
=> [CAMEL-13353] Update to re-enable the camel-lra integration tests

components/camel-twitter/src/main/java/org/apache/camel/component/twitter/directmessage/DirectMessageConsumerHandler.java
https://issues.apache.org/jira/browse/CAMEL-13387
=> CAMEL-13387 camel-twitter-direct-message doesn't filter by filterOld parameter

components/camel-service/src/main/java/org/apache/camel/component/service/ServiceEndpoint.java
https://issues.apache.org/jira/browse/CAMEL-13388
=> CAMEL-13388: Wrong removing parameters logic in ServiceComponent.

tooling/maven/camel-maven-plugin/src/main/docs/camel-maven-plugin.adoc, tooling/maven/camel-maven-plugin/src/main/java/org/apache/camel/maven/RouteCoverageMojo.java
Here is our attempt to fix the issue with xml code coverage
=> CAMEL-13345 - added option to generate jacocoXml report to sonarQube

components/camel-jdbc/src/main/docs/jdbc-component.adoc
=> typo on camel-jdbc doc

components/camel-dozer/pom.xml, components/camel-dozer/src/main/java/org/apache/camel/component/dozer/DozerProducer.java, components/camel-saxon/src/test/java/org/apache/camel/component/xquery/XQueryURLBasedConcurrencyTest.java, components/camel-saxon/src/test/resources/log4j2.properties, core/camel-core/src/main/java/org/apache/camel/impl/AbstractCamelContext.java, core/camel-core/src/main/java/org/apache/camel/impl/transformer/DataFormatTransformer.java, core/camel-core/src/main/java/org/apache/camel/model/DataFormatDefinition.java, core/camel-core/src/main/java/org/apache/camel/model/MarshalDefinition.java, core/camel-core/src/main/java/org/apache/camel/model/UnmarshalDefinition.java, core/camel-core/src/main/java/org/apache/camel/model/dataformat/BindyDataFormat.java, core/camel-core/src/main/java/org/apache/camel/model/dataformat/BoonDataFormat.java, core/camel-core/src/main/java/org/apache/camel/model/dataformat/CryptoDataFormat.java, core/camel-core/src/main/java/org/apache/camel/model/dataformat/CustomDataFormat.java, core/camel-core/src/main/java/org/apache/camel/model/dataformat/FlatpackDataFormat.java, core/camel-core/src/main/java/org/apache/camel/model/dataformat/GzipDataFormat.java, core/camel-core/src/main/java/org/apache/camel/model/dataformat/JacksonXMLDataFormat.java, core/camel-core/src/main/java/org/apache/camel/model/dataformat/JibxDataFormat.java, core/camel-core/src/main/java/org/apache/camel/model/dataformat/JsonDataFormat.java, core/camel-core/src/main/java/org/apache/camel/model/dataformat/SerializationDataFormat.java, core/camel-core/src/main/java/org/apache/camel/model/dataformat/StringDataFormat.java, core/camel-core/src/main/java/org/apache/camel/model/dataformat/TidyMarkupDataFormat.java, core/camel-core/src/main/java/org/apache/camel/model/dataformat/XStreamDataFormat.java, core/camel-core/src/main/java/org/apache/camel/model/dataformat/YAMLDataFormat.java, core/camel-core/src/main/java/org/apache/camel/model/dataformat/ZipDataFormat.java, core/camel-core/src/main/java/org/apache/camel/reifier/MarshalReifier.java, core/camel-core/src/main/java/org/apache/camel/reifier/UnmarshalReifier.java, core/camel-core/src/test/java/org/apache/camel/impl/transformer/TransformerContractTest.java, core/camel-core/src/test/java/org/apache/camel/impl/transformer/TransformerRouteTest.java
.. and some cleanup related to that
=> eager lookup data formats and bind to registry so the dataformats can be looked up and used

examples/camel-example-widget-gadget-java/README.md, examples/camel-example-widget-gadget-xml/README.md
This PR fixes minor documentation problems I found when working on a separate PR.
=> Fixed invalid markdown links to ActiveMQ website

components/camel-metrics/src/main/java/org/apache/camel/component/metrics/routepolicy/MetricsRoutePolicy.java, components/camel-metrics/src/main/java/org/apache/camel/component/metrics/routepolicy/MetricsRoutePolicyFactory.java
... and expose token constants for namePattern
=> Expose namePattern in MetricsRoutePolicyFactory

components/camel-box/camel-box-component/src/test/java/org/apache/camel/component/box/AbstractBoxTestSupport.java, components/camel-box/camel-box-component/src/test/java/org/apache/camel/component/box/BoxUsersManagerIntegrationTest.java, components/camel-box/camel-box-component/src/test/resources/test-options.properties
Issue: https://issues.apache.org/jira/browse/CAMEL-13478
Un-ignored some tests.
Added comments to explain how to run them.
Fixed some smaller issues with failing tests and not cleaning after execution.
=> [CAMEL-13478] camel-box, review BoxUsersManagerIntegrationTest for unnecassary ignored test and some possible problems

examples/camel-example-pojo-messaging/pom.xml, examples/camel-example-pojo-messaging/src/main/java/org/apache/camel/example/pojo/DistributeRecordsBean.java, examples/camel-example-pojo-messaging/src/main/java/org/apache/camel/example/pojo/SendFileRecordsToQueueBean.java, examples/camel-example-pojo-messaging/src/main/resources/META-INF/spring/camel-context.xml, examples/camel-example-pojo-messaging/src/test/java/org/apache/camel/example/pojo/CamelContextTest.java
Addressing https://issues.apache.org/jira/browse/CAMEL-13444
=> CAMEL-13444 Renaming package

components/camel-cdi/pom.xml, parent/pom.xml, tests/camel-itest-cdi/pom.xml
Completely remove weld1 and weld2.
=> CAMEL-13234: Remove dependencies weld1 and weld2

components/camel-swagger-java/src/main/docs/swagger-java.adoc
`outTypeList` and `typeList` were deprecated.
=> Update deprecated method

core/camel-base/src/main/java/org/apache/camel/language/simple/ast/SimpleFunctionExpression.java, core/camel-core/src/test/java/org/apache/camel/language/simple/SimpleTest.java, docs/user-manual/modules/ROOT/pages/simple-language.adoc
As described here: https://issues.apache.org/jira/browse/CAMEL-13534
The original PR: https://github.com/apache/camel/pull/2923 has been closed as there was an issue with the rebase
=> Camel-13534 add colon as alternative syntax style

components/camel-mongodb3/src/main/java/org/apache/camel/component/mongodb3/MongoDbTailingProcess.java
Fix broken test: `MongoDbTailableCursorConsumerTest`
=> Fix mongodb tests

parent/pom.xml, platforms/spring-boot/spring-boot-dm/camel-spring-boot-dependencies/pom.xml, pom.xml
=> Upgrade xerces version

components/camel-jira/src/main/java/org/apache/camel/component/jira/consumer/NewIssuesConsumer.java, components/camel-jira/src/main/java/org/apache/camel/component/jira/producer/UpdateIssueProducer.java
as querying jira with "id > lastId" the backend jira throws an error when lastId = -1
=> Only poll after the initial load, 

components/camel-barcode/src/main/docs/barcode-dataformat.adoc, components/camel-bean-validator/src/main/docs/bean-validator-component.adoc, components/camel-bean/src/main/docs/bean-component.adoc, components/camel-bean/src/main/docs/class-component.adoc, components/camel-beanstalk/src/main/docs/beanstalk-component.adoc, components/camel-bindy/src/main/docs/bindy-dataformat.adoc, components/camel-caffeine/src/main/docs/caffeine-cache-component.adoc, components/camel-caffeine/src/main/docs/caffeine-loadcache-component.adoc, components/camel-cdi/src/main/docs/cdi.adoc, components/camel-chatscript/src/main/docs/chatscript-component.adoc, components/camel-chunk/src/main/docs/chunk-component.adoc, components/camel-coap/src/main/docs/coap-component.adoc, components/camel-cometd/src/main/docs/cometd-component.adoc, components/camel-consul/src/main/docs/consul-component.adoc, components/camel-controlbus/src/main/docs/controlbus-component.adoc, components/camel-corda/src/main/docs/corda-component.adoc, components/camel-couchdb/src/main/docs/couchdb-component.adoc, components/camel-crypto/src/main/docs/pgp-dataformat.adoc, components/camel-csv/src/main/docs/csv-dataformat.adoc, components/camel-cxf-transport/src/main/docs/cxf-transport.adoc, components/camel-cxf/src/main/docs/cxf-component.adoc, components/camel-cxf/src/main/docs/cxfrs-component.adoc
More documentation cleaned up ("camel-b..." and "camel-c...") http://issues.apache.org/jira/browse/CAMEL-13480
=> CAMEL-13480

components/camel-twitter/src/main/docs/twitter-search-component.adoc, components/camel-twitter/src/main/java/org/apache/camel/component/twitter/search/TwitterSearchEndpoint.java
https://issues.apache.org/jira/browse/CAMEL-13649
=> CAMEL-13649 Enhance documentation for twitter search of multiple words

components/camel-saxon/src/main/docs/xquery-component.adoc
Based on https://stackoverflow.com/questions/56592191/how-to-access-exchange-headers-in-the-xquery/56592371?noredirect=1#comment99761977_56592371
=> adding an example about using camel headers

camel-core/src/main/java/org/apache/camel/util/FileUtil.java, camel-core/src/test/java/org/apache/camel/util/FileUtilTest.java
PR for Windows network UNC paths not treated correctly (File2/tempPrefix)
=> PR for CAMEL-13667 (2.x branch)

components/camel-microprofile-config/pom.xml, components/camel-microprofile-config/src/main/docs/microprofile-config.adoc, components/camel-microprofile-config/src/main/java/org/apache/camel/component/microprofile/config/CamelMicroProfilePropertiesSource.java, components/camel-microprofile-config/src/main/resources/META-INF/services/org/apache/camel/properties-source-factory, components/camel-microprofile-config/src/test/java/org/apache/camel/component/microprofile/config/CamelMicroProfilePropertiesSourceTest.java, components/camel-microprofile-config/src/test/resources/log4j2.properties, components/camel-properties/src/main/java/org/apache/camel/component/properties/PropertiesComponent.java, components/camel-properties/src/main/java/org/apache/camel/component/properties/PropertiesSource.java, core/camel-base/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java, core/camel-core/src/test/java/org/apache/camel/component/properties/PropertiesComponentEIPChoiceSimpleTest.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/SpringBootStarterMojo.java
Properties component should work with Eclipse MicroProfile Config
=> Camel 13705

components/camel-corda/src/main/java/org/apache/camel/component/corda/CordaEndpoint.java
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>
=> CAMEL-13716 - fixed wrong syntax for corda endpoints

components/camel-atomix/src/main/java/org/apache/camel/component/atomix/client/AbstractAtomixClientProducer.java, components/camel-bean/src/main/java/org/apache/camel/component/bean/MethodInfo.java, components/camel-flink/src/main/java/org/apache/camel/component/flink/annotations/AnnotatedDataSetCallback.java, components/camel-spark/src/main/java/org/apache/camel/component/spark/annotations/AnnotatedRddCallbackProxy.java, core/camel-core/src/test/java/org/apache/camel/util/ObjectHelperTest.java, core/camel-support/src/main/java/org/apache/camel/support/IntrospectionSupport.java, core/camel-util/src/main/java/org/apache/camel/util/ObjectHelper.java
Same as https://github.com/apache/camel/pull/3015 but for master.
Also used safe method instead of setting accessible where possible.
Full test run for:
- core
- camel-spark
- camel-flink
- camel-atomix
=> Fix NPE at component.bean.MethodInfo.invoke (master)

components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarEndpoint.java, components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarProducer.java, components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/utils/consumers/CommonCreationStrategyImpl.java
Signed-off-by: Lars Heinemann <lhein.smx@gmail.com>
This is a change proposal. I haven't tested it in all details. Please make sure to review the change carefully.
=> CAMEL-13718 - fixed wrong syntax for pulsar endpoints

core/camel-cloud/pom.xml
=> CAMEL-13733-update pom.xml to use camel-core-engin

camel-core/src/main/java/org/apache/camel/support/TokenXMLExpressionIterator.java, camel-core/src/test/java/org/apache/camel/language/TokenXMLPairNamespaceMultilineSplitTest.java, camel-core/src/test/java/org/apache/camel/language/TokenXMLPairNamespaceSplitChildNamespaceTest.java, camel-core/src/test/java/org/apache/camel/language/TokenXMLPairNamespaceSplitTest.java
CAMEL-13795: Fixing the issue of already declared namespaces within the child
I have also align the tests classes
=> CAMEL-13795: Fixing the issue of already declared namespaces within the child

components/camel-infinispan/src/main/docs/infinispan-component.adoc
ready for your review: copied content from the RH Data Grid documentation
=> updating the infinispan documentation

components/camel-spring-boot/src/main/java/org/apache/camel/spring/boot/SpringTypeConverter.java
Reuse isArrayOrCollection method instead of rewriting the condition i guess it was an oversight
=> use isArrayOrCollection

components/camel-jms/src/main/java/org/apache/camel/component/jms/JmsEndpoint.java, components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsEndpointConfigurationTest.java
@davsclaus : Cherry pick to camel-2.x branch of #3103
=> CAMEL-13864: Allow subscriptionName to be set for non-durable shared subscription

components/camel-pulsar/src/main/docs/pulsar-component.adoc, components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarProducer.java, components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/configuration/PulsarConfiguration.java
Initial camel-pulsar did not expose many of the configuration options for Pulsar producers. This PR adds the rest.
Additional PR against master has also been created.
=> Increase configuration options for Pulsar

docs/user-manual/modules/ROOT/pages/team.adoc
Proof of donation: https://github.com/osinka/camel-beanstalk/issues/8
=> Add myself to the list of contributors

docs/user-manual/modules/ROOT/pages/team.adoc
My (small) contribution so far: https://github.com/apache/camel/commits?author=dimitrisli
and looking forward to much more.
=> Adding contributor name

docs/user-manual/modules/ROOT/pages/team.adoc
https://github.com/apache/camel/pull/2903 My small changes so far. Hoping to get more involved.
=> Adding myself to Contributors

components/camel-elasticsearch-rest/src/main/docs/elasticsearch-rest-component.adoc
=> Spelling Correction

components/camel-debezium/src/main/docs/debezium-component.adoc
Update debezium-component.adoc to fix some typos and enhance some information about the message body
=> Update debezium-component.adoc to fix some typos and add some info

docs/user-manual/modules/ROOT/pages/commercial-camel-offerings.adoc
Hi, I would like to add Yupiik on the commercial support page.
@jbonofre can you review please?
Thanks!
=> Add Yupiik in the commercial support page

components/camel-microprofile-metrics/src/main/docs/microprofile-metrics-component.adoc, components/camel-microprofile-metrics/src/main/java/org/apache/camel/component/microprofile/metrics/MicroProfileMetricsComponent.java, components/camel-microprofile-metrics/src/main/java/org/apache/camel/component/microprofile/metrics/MicroProfileMetricsConstants.java, components/camel-microprofile-metrics/src/main/java/org/apache/camel/component/microprofile/metrics/MicroProfileMetricsExchangeRecorder.java, components/camel-microprofile-metrics/src/main/java/org/apache/camel/component/microprofile/metrics/MicroProfileMetricsGaugeProducer.java, components/camel-microprofile-metrics/src/main/java/org/apache/camel/component/microprofile/metrics/event/notifier/MicroProfileMetricsEventNotifierNamingStrategy.java, components/camel-microprofile-metrics/src/main/java/org/apache/camel/component/microprofile/metrics/event/notifier/context/MicroProfileMetricsCamelContextEventNotifier.java, components/camel-microprofile-metrics/src/main/java/org/apache/camel/component/microprofile/metrics/event/notifier/context/MicroProfileMetricsCamelContextEventNotifierNamingStrategy.java, components/camel-microprofile-metrics/src/main/java/org/apache/camel/component/microprofile/metrics/event/notifier/exchange/MicroProfileMetricsExchangeEventNotifier.java, components/camel-microprofile-metrics/src/main/java/org/apache/camel/component/microprofile/metrics/event/notifier/exchange/MicroProfileMetricsExchangeEventNotifierNamingStrategy.java, components/camel-microprofile-metrics/src/main/java/org/apache/camel/component/microprofile/metrics/event/notifier/route/MicroProfileMetricsRouteEventNotifier.java, components/camel-microprofile-metrics/src/main/java/org/apache/camel/component/microprofile/metrics/gauge/AtomicIntegerGauge.java, components/camel-microprofile-metrics/src/main/java/org/apache/camel/component/microprofile/metrics/gauge/LambdaGauge.java, components/camel-microprofile-metrics/src/main/java/org/apache/camel/component/microprofile/metrics/gauge/SimpleGauge.java, components/camel-microprofile-metrics/src/main/java/org/apache/camel/component/microprofile/metrics/message/history/MicroProfileMetricsMessageHistory.java, components/camel-microprofile-metrics/src/main/java/org/apache/camel/component/microprofile/metrics/message/history/MicroProfileMetricsMessageHistoryNamingStrategy.java, components/camel-microprofile-metrics/src/main/java/org/apache/camel/component/microprofile/metrics/route/policy/MicroProfileMetricsRoutePolicy.java, components/camel-microprofile-metrics/src/main/java/org/apache/camel/component/microprofile/metrics/route/policy/MicroProfileMetricsRoutePolicyNamingStrategy.java, components/camel-microprofile-metrics/src/test/java/org/apache/camel/component/microprofile/metrics/MicroProfileMetricsExchangeRecorderTest.java, components/camel-microprofile-metrics/src/test/java/org/apache/camel/component/microprofile/metrics/MicroProfileMetricsGaugeTest.java, components/camel-microprofile-metrics/src/test/java/org/apache/camel/component/microprofile/metrics/MicroProfileMetricsTestSupport.java, components/camel-microprofile-metrics/src/test/java/org/apache/camel/component/microprofile/metrics/event/notifier/context/MicroProfileMetricsCamelContextEventNotifierTest.java, components/camel-microprofile-metrics/src/test/java/org/apache/camel/component/microprofile/metrics/event/notifier/exchange/MicroProfileMetricsExchangeEventNotifierTest.java, components/camel-microprofile-metrics/src/test/java/org/apache/camel/component/microprofile/metrics/event/notifier/route/MicroProfileMetricsRouteEventNotifierTest.java, components/camel-microprofile-metrics/src/test/java/org/apache/camel/component/microprofile/metrics/message/history/MicroProfileMetricsMessageHistoryTest.java, components/camel-microprofile-metrics/src/test/java/org/apache/camel/component/microprofile/metrics/route/policy/MicroProfileMetricsRoutePolicyTest.java, docs/components/modules/ROOT/pages/microprofile-metrics-component.adoc
https://issues.apache.org/jira/browse/CAMEL-13977
=> CAMEL-13977: Expose additional Camel metrics from MicroProfile metrics component

examples/camel-example-spring-boot-rest-jpa/pom.xml
Fixed IntelliJ project file generation.
=> CAMEL-11834: camel-example-spring-boot-rest-jpa

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/AS2Header.java, components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/protocol/ResponseMDN.java
CAMEL-13976 :  iAllow AS2 Component to reply disposition type failed in the MDN for the 2.x branch
=> Camel 13976  reply disposition type failed

components/camel-debezium/src/main/docs/debezium-component.adoc, examples/camel-example-debezium/README.adoc
Just adding in the documentation about the dependency
=> camel-debezium: Add in the documentation about the dependency inclusion

core/camel-base/src/main/java/org/apache/camel/impl/engine/ServicePool.java
https://issues.apache.org/jira/browse/CAMEL-14000
Thanks!
=> CAMEL-14000 - remove Endpoint from Map when corresponding Pool is empty

components/camel-azure/src/main/docs/azure-blob-component.adoc
Fixes client code sample in user documentation for Camel Azure Blob component, and some minor tidy up.
=> Fix azure blob client sample in docs

components/camel-http/src/main/docs/http-component.adoc
https://issues.apache.org/jira/browse/CAMEL-13930
=> CAMEL-13930 - Improve the camel-http docs

components/camel-hdfs/src/main/java/org/apache/camel/component/hdfs/HdfsConsumer.java
https://issues.apache.org/jira/browse/CAMEL-14021
=> CAMEL-14021: Fix HDFS polling conumer message processing

docs/user-manual/modules/ROOT/pages/pojo-producing.adoc
and = should be == for heading level
=> similar fix, remove @ from anchor

core/camel-main/src/main/java/org/apache/camel/main/MainListener.java, core/camel-main/src/main/java/org/apache/camel/main/MainListenerSupport.java, core/camel-main/src/test/java/org/apache/camel/main/MainExample.java
So main listener can be used by code extending for BaseMainSupport
=> Replace MainSupport with BaseMainSupport in MainListener

components/camel-bindy/src/main/docs/bindy-dataformat.adoc, components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/BindyAbstractDataFormat.java, components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/csv/BindyCsvDataFormat.java, components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/fixed/BindyFixedLengthDataFormat.java, components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/kvp/BindyKeyValuePairDataFormat.java, components/camel-bindy/src/test/java/org/apache/camel/dataformat/bindy/csv/BindyComplexCsvUnmarshallEmptyStreamTest.java, components/camel-bindy/src/test/resources/org/apache/camel/dataformat/bindy/csv/BindyComplexCsvUnmarshallEmptyStreamTest-context.xml, core/camel-core-engine/src/main/java/org/apache/camel/model/dataformat/BindyDataFormat.java, core/camel-core-engine/src/main/java/org/apache/camel/reifier/dataformat/BindyDataFormatReifier.java, docs/components/modules/ROOT/pages/bindy-dataformat.adoc, platforms/spring-boot/components-starter/camel-bindy-starter/src/main/java/org/apache/camel/dataformat/bindy/csv/springboot/BindyCsvDataFormatConfiguration.java, platforms/spring-boot/components-starter/camel-bindy-starter/src/main/java/org/apache/camel/dataformat/bindy/fixed/springboot/BindyFixedLengthDataFormatConfiguration.java, platforms/spring-boot/components-starter/camel-bindy-starter/src/main/java/org/apache/camel/dataformat/bindy/kvp/springboot/BindyKeyValuePairDataFormatConfiguration.java
Add allowEmptyStream option to the camel-bindy dataformat.
=> CAMEL-13392 camel-bindy - Add allowEmptyStream option

apache-camel/pom.xml, apache-camel/src/main/descriptors/common-bin.xml, bom/camel-bom/pom.xml, components/camel-microprofile-health/pom.xml, components/camel-microprofile-health/src/main/docs/microprofile-health-component.adoc, components/camel-microprofile-health/src/main/java/org/apache/camel/microprofile/health/AbstractCamelMicroProfileHealthCheck.java, components/camel-microprofile-health/src/main/java/org/apache/camel/microprofile/health/AbstractCamelMicroProfileLivenessCheck.java, components/camel-microprofile-health/src/main/java/org/apache/camel/microprofile/health/AbstractCamelMicroProfileReadinessCheck.java, components/camel-microprofile-health/src/main/java/org/apache/camel/microprofile/health/CamelMicroProfileContextCheck.java, components/camel-microprofile-health/src/main/java/org/apache/camel/microprofile/health/CamelMicroProfileLivenessCheck.java, components/camel-microprofile-health/src/main/java/org/apache/camel/microprofile/health/CamelMicroProfileReadinessCheck.java, components/camel-microprofile-health/src/test/java/org/apache/camel/microprofile/health/CamelMicroProfileHealthCheckRepositoryTest.java, components/camel-microprofile-health/src/test/java/org/apache/camel/microprofile/health/CamelMicroProfileHealthCheckTest.java, components/camel-microprofile-health/src/test/java/org/apache/camel/microprofile/health/CamelMicroProfileHealthTestSupport.java, components/camel-microprofile-health/src/test/resources/log4j2.properties, components/pom.xml, components/readme.adoc, docs/components/modules/ROOT/nav.adoc, docs/components/modules/ROOT/pages/microprofile-health-component.adoc, parent/pom.xml, platforms/spring-boot/spring-boot-dm/camel-spring-boot-dependencies/pom.xml, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/SpringBootStarterMojo.java
https://issues.apache.org/jira/browse/CAMEL-13875
=> CAMEL-13875: Support for MicroProfile Health

components/camel-zipkin/src/main/docs/zipkin.adoc
https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line
=> reformats to ventilated prose

docs/user-manual/modules/ROOT/pages/bean-binding.adoc
=> removes '@' from anchor, since breaks heading

docs/pom.xml
https://issues.apache.org/jira/browse/CAMEL-14082
=> CAMEL-14082 Update to fix the parent version

components/camel-as2/camel-as2-api/pom.xml, components/camel-box/camel-box-api/pom.xml, components/camel-fhir/camel-fhir-api/pom.xml, components/camel-linkedin/camel-linkedin-api/pom.xml, components/camel-olingo2/camel-olingo2-api/pom.xml, components/camel-olingo4/camel-olingo4-api/pom.xml
https://issues.apache.org/jira/browse/CAMEL-14081
=> CAMEL-14081 Update to add locale en in javadoc configuration

components/camel-debezium/camel-debezium-maven-plugin/src/main/java/org/apache/camel/maven/config/ConnectorConfigField.java, examples/camel-example-debezium/src/main/java/org/apache/camel/example/debezium/DebeziumMySqlConsumerToKinesis.java
Nothing much here, just a minor change to make camel-debezium work after the new configurations generator
=> Fix camel-debezium after the new configurations

components/camel-debezium/camel-debezium-maven-plugin/src/main/java/org/apache/camel/maven/config/ConnectorConfigGenerator.java
=> CAMEL-14087: Fix for serverId is generated everytime when mvn clean install is triggered

components/camel-seda/src/main/docs/seda-component.adoc
To fix the issue reported in the jira ticket https://issues.apache.org/jira/browse/CAMEL-13992
=> Updated Seda-component.adoc

components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/handlers/HttpClientChannelHandler.java, components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpClientExpectContinueTest.java, components/camel-netty/src/main/java/org/apache/camel/component/netty/NettyConstants.java, components/camel-netty/src/main/java/org/apache/camel/component/netty/handlers/ClientChannelHandler.java
=> CAMEL-14069 Update to ignore the 100-Continue response and continue to

components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowComponent.java, components/camel-undertow/src/test/java/org/apache/camel/component/undertow/UndertowNoAutoStartupTest.java
Fixes https://github.com/apache/camel-k-runtime/issues/172
=> Undertow does not shut down properly in webhook route policy

docs/user-manual/modules/ROOT/pages/faq.adoc, docs/user-manual/modules/ROOT/pages/faq/how-do-i-become-a-committer.adoc, docs/user-manual/modules/ROOT/pages/faq/how-do-i-edit-the-website.adoc, docs/user-manual/modules/ROOT/pages/index.adoc, docs/user-manual/modules/ROOT/pages/support.adoc
Point to Contributing page instead of CONTRIBUTING.md on GitHub.
=> CAMEL-14061 camel-website - Add page for contributing

components/camel-debezium-common/camel-debezium-maven-plugin/src/main/java/org/apache/camel/maven/config/ConnectorConfigField.java, components/camel-debezium-common/camel-debezium-maven-plugin/src/test/java/org/apache/camel/maven/config/ConnectorConfigFieldTest.java, components/camel-debezium-postgres/src/main/docs/debezium-postgres-component.adoc, core/camel-endpointdsl/src/main/java/org/apache/camel/builder/endpoint/dsl/DebeziumPostgresEndpointBuilderFactory.java, platforms/spring-boot/components-starter/camel-debezium-postgres-starter/src/main/java/org/apache/camel/component/debezium/springboot/DebeziumPostgresComponentConfiguration.java
This will fix if we have field names with underscore from Debezium that we generate the correct camel case field names
=> CAMEL-14130: Fix underscore field name in debezium maven plugin

core/camel-support/src/main/java/org/apache/camel/support/ObjectHelper.java, core/camel-util/src/main/java/org/apache/camel/util/Scanner.java
Internal use of non threadsafe map wrapped with synchronized block,
extracted some static patterns into class static block
https://issues.apache.org/jira/browse/CAMEL-14136
=> CAMEL-14136: Fix ConcurrentModificationException in Scanner

components/camel-grpc/pom.xml, components/camel-jira/pom.xml, components/camel-pubnub/pom.xml, components/camel-swagger-java/pom.xml, examples/camel-example-grpc-kubernetes/hello-camel-grpc-client-kubernetes/pom.xml, examples/camel-example-grpc-kubernetes/hello-camel-grpc-server-kubernetes/pom.xml, examples/camel-example-grpc-kubernetes/pom.xml, examples/camel-example-spring-boot-grpc/hello-camel-grpc-client/pom.xml, examples/camel-example-spring-boot-grpc/hello-camel-grpc-server/pom.xml, parent/pom.xml, platforms/karaf/features/src/main/resources/features.xml
https://issues.apache.org/jira/browse/CAMEL-14140
=> [CAMEL-14140] Remove global dependency on outdated guava

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/UpdateReadmeMojo.java
This will the component producer and consumer info, below the version (I thought that is a suitable place for it), for example:
```
[[twitter-timeline-component]]
= Twitter Timeline Component
*Since Camel 2.10*
// HEADER START
*Both Producer and Consumer are supported*
// HEADER END
..
``` 
Note this first will check if we have `// HEADER START // HEADER END` in the docs, then it will just update similar to the component options. In case we don't have it, it will insert it after the first version.
=> CAMEL-13825: Add consumer and producer info to the component docs

docs/user-manual/modules/ROOT/pages/message-translator.adoc
The link to XQuery was pointed to Velocity.
=> Fix link to XQuery

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaProducer.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaProducerTest.java
This shall address CAMEL-14233, whereby if {{kafka.OVERRIDE_TOPIC}} header is set on multiple exchanges that fed on an aggregation, this will be ignored and camel-kafka will just forward to the default topic. This PR shall fix this.
=> CAMEL-14233: Fix Overriden topics when using aggregation on Exchanges or Messages

components/camel-pg-replication-slot/src/main/java/org/apache/camel/component/pg/replication/slot/PgReplicationSlotConsumer.java
if PG connection got lost while trying to send the status to PG, the reconnect logic will never be called and the exchange will be reprocessed forever.
After we receive the payload from PostgreSQL, we keep it in memory so we can process it again and again in case the processing of the exchange fails. After the successful completion of the exchange, we (1) send the status to PostgreSQL, (2) reset the payload, and (3) we receive the next
one.
If for some reason we lose the connection while trying to do step 2, the payload will never get reset, and it will be processed forever. We need to reset the payload first so in case of failure in updating the status, the next poll will reconnect and receive the next payload. The next status update cover both payload as LSNs are sequential.
=> pg-replication-slot component fix: reconnect logic might fail if it happens while sending the status. 

core/camel-base/src/main/java/org/apache/camel/processor/ContractAdvice.java
Fix a nullPointerException in convertIfRequired when boddy is null
=> [CAMEL-14267] Fix a nullPointerException in convertIfRequired

components/camel-jms/src/main/docs/jms-component.adoc
Camel will automatic setup a consumer -> Camel will automatically setup a consumer
=> Fix grammar

parent/pom.xml
Fixed "Hidding" to "Hiding" in the documentation navigation source.
=> Fix typos in documentation navigation

apache-camel/pom.xml
Add a property for tarLongFileMode so it can be set by -D
=> Add property for tarLongFileMode

components/camel-avro/src/main/java/org/apache/camel/component/avro/AvroEndpoint.java, components/camel-aws-kinesis/src/main/java/org/apache/camel/component/aws/kinesis/KinesisConsumer.java, components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxFilesManager.java, components/camel-consul/src/main/java/org/apache/camel/component/consul/cluster/ConsulClusterView.java, components/camel-crypto-cms/src/main/java/org/apache/camel/component/crypto/cms/sig/SignedDataVerifier.java, components/camel-google-mail/src/main/java/org/apache/camel/component/google/mail/stream/GoogleMailStreamConsumer.java, components/camel-google-mail/src/main/java/org/apache/camel/component/google/mail/stream/GoogleMailStreamEndpoint.java, components/camel-guava-eventbus/src/main/java/org/apache/camel/component/guava/eventbus/CamelEventHandler.java, components/camel-hbase/src/main/java/org/apache/camel/component/hbase/processor/idempotent/HBaseIdempotentRepository.java, components/camel-http-common/src/main/java/org/apache/camel/http/common/DefaultHttpBinding.java, components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/config_maps/KubernetesConfigMapsConsumer.java, components/camel-ldap/src/main/java/org/apache/camel/component/ldap/LdapProducer.java, components/camel-milo/src/main/java/org/apache/camel/component/milo/server/internal/CamelServerItem.java, components/camel-mllp/src/main/java/org/apache/camel/component/mllp/MllpComponent.java, components/camel-mllp/src/main/java/org/apache/camel/component/mllp/MllpEndpoint.java, components/camel-mllp/src/main/java/org/apache/camel/component/mllp/MllpTcpClientProducer.java, components/camel-netty/src/main/java/org/apache/camel/component/netty/NettyProducer.java, components/camel-optaplanner/src/main/java/org/apache/camel/component/optaplanner/OptaPlannerEndpoint.java, components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/client/DefaultCompositeApiClient.java, components/camel-soap/src/main/java/org/apache/camel/dataformat/soap/name/MethodInfo.java, components/camel-soroush/src/main/java/org/apache/camel/component/soroushbot/component/SoroushBotEndpoint.java, components/camel-undertow/src/main/java/org/apache/camel/component/undertow/DefaultUndertowHttpBinding.java, components/camel-undertow/src/main/java/org/apache/camel/component/undertow/handlers/CamelPathTemplateHandler.java, components/camel-xslt/src/main/java/org/apache/camel/component/xslt/XsltBuilder.java, core/camel-base/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java, core/camel-core-engine/src/main/java/org/apache/camel/reifier/InterceptReifier.java, core/camel-core-engine/src/main/java/org/apache/camel/reifier/InterceptSendToEndpointReifier.java
This shall address some issues being reported by lgtm as here: https://lgtm.com/projects/g/apache/camel/alerts/?sort=name&dir=ASC&mode=list&tag=correctness%2Clogic%2Creliability , plus some logical changes, e.g: iterator to forloop or simplify 
Please take a look and see if they make sense
=> CAMEL-14312: Address some issues reported by lgtm

components/camel-jms/src/test/resources/org/apache/camel/component/jms/jmsRouteUsingSpring.xml, docs/user-manual/modules/ROOT/examples/components/camel-jms/src/test/resources/org/apache/camel/component/jms/jmsRouteUsingSpring.xml
I missed to update also the source file that was copied to the Antora folder in #3446. This PR rectifies this.
=> making include referencing example marked by tag

components/camel-kafka/pom.xml, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaProducer.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaProducerTest.java
PR as requested in CAMEL-14233
=> CAMEL-14360 - Allow overriding of message key and partition key for ggregated kafka messages

components/camel-pdf/src/main/java/org/apache/camel/component/pdf/PdfProducer.java
For the create operation this is definitely the right thing to do.
For the append and extractText operations this is a change in behavior, as the `PDDocument` object can no longer be used after these operations (e.g. for another operation).
=> CAMEL-14355: PDF producer should close PDF documents

docs/components/modules/ROOT/pages/file-component.adoc
This is the combination of features to be used for a scenario where the file in use needs to have read-write access from the code.
Reading the file in a route using pollEnrich and updating the data in the same file so that you get the updated data when the file is accessed again.
=> Avoiding file auto-deletion; Read-Write access enabling and Reading the file inside a route

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointDslMojo.java
This commit improve a little the performances of EndpointDslMojo by
listing and parsing component specific endpoint factories only once.
In addition, this commit introduces:
- options to control the generation of the endpoint dsl interfaces
- an option to control the package name where to generate component
specific endpoint factories
- an option to control the package name where to generate the endpoint
dsl interfaces
Those changes are needed to use the mojo for component hosted outside
the camel repo and to give a change to at least generate component
specific endpoint factories. Such endpoint factories won't be availabe
in the generic EndpointRouteBuilder but at least developer have a way
to use a fluent endpoint builder even for such components.
=> Improve EndpointDslMojo

components/camel-jira/src/main/java/org/apache/camel/component/jira/JiraConstants.java, components/camel-jira/src/main/java/org/apache/camel/component/jira/JiraEndpoint.java, components/camel-jira/src/main/java/org/apache/camel/component/jira/JiraType.java, components/camel-jira/src/main/java/org/apache/camel/component/jira/producer/AddIssueLinkProducer.java, components/camel-jira/src/main/java/org/apache/camel/component/jira/producer/AddWorkLogProducer.java, components/camel-jira/src/main/java/org/apache/camel/component/jira/producer/FetchCommentsProducer.java, components/camel-jira/src/main/java/org/apache/camel/component/jira/producer/FetchIssueProducer.java, components/camel-jira/src/test/java/org/apache/camel/component/jira/Utils.java, components/camel-jira/src/test/java/org/apache/camel/component/jira/producer/AddIssueLinkProducerTest.java, components/camel-jira/src/test/java/org/apache/camel/component/jira/producer/AddWorkLogProducerTest.java, components/camel-jira/src/test/java/org/apache/camel/component/jira/producer/FetchCommentsProducerTest.java, components/camel-jira/src/test/java/org/apache/camel/component/jira/producer/FetchIssueProducerTest.java, core/camel-endpointdsl/src/main/java/org/apache/camel/builder/endpoint/dsl/JiraEndpointBuilderFactory.java
- Added AddIssueLinkProducer, AddWorkLogProducer, FetchCommentsProducer & FetchCommentsProducer
- Updated JiraConstants, JiraEndpoint & JiraType to enable the new producers
- Added tests to verify the new producers
=> CAMEL-14443 new camel-jira producers

components/camel-jdbc/src/main/docs/jdbc-component.adoc
Hi, 
I was checking the Gitter channel and someone says that there was no example for configuring a JDBC DataSource. I recalled that also for me was difficult to find out how to do it. 
I 've only done this with XML Spring configuration, I suppose this is the right place to put this example if not, let me know. 
:)
=> Added a DataSource configuration example.

components/camel-webhook/src/main/java/org/apache/camel/component/webhook/WebhookComponent.java, components/camel-webhook/src/test/java/org/apache/camel/component/webhook/WebhookUriEncodingTest.java, components/camel-webhook/src/test/java/org/apache/camel/component/webhook/support/TestEndpoint.java
https://issues.apache.org/jira/browse/CAMEL-14459
=> CAMEL-14459 - camel-webhook - RAW() parameter value handling in delegated URI

docs/user-manual/modules/ROOT/pages/camel-3-migration-guide.adoc
Showing the same in both old and new
=> groupID change is wrong

docs/components/modules/ROOT/pages/bean-component.adoc, docs/components/modules/ROOT/pages/cxfrs-component.adoc, docs/components/modules/ROOT/pages/dataset-component.adoc, docs/components/modules/ROOT/pages/dataset-test-component.adoc, docs/components/modules/ROOT/pages/jpa-component.adoc, docs/components/modules/ROOT/pages/log-component.adoc, docs/components/modules/ROOT/pages/mock-component.adoc, docs/components/modules/ROOT/pages/scp-component.adoc, docs/components/modules/ROOT/pages/stomp-component.adoc, docs/components/modules/ROOT/pages/xpath-language.adoc, docs/user-manual/modules/ROOT/pages/eventDrivenConsumer-eip.adoc, docs/user-manual/modules/ROOT/pages/process-eip.adoc, docs/user-manual/modules/ROOT/pages/rollback-eip.adoc
Last set of bulk fixes or broken Javadoc links.
=> CAMEL-14482: Fix broken Javadocs on Camel Components

docs/components/modules/ROOT/pages/bean-component.adoc, docs/components/modules/ROOT/pages/cxfrs-component.adoc, docs/components/modules/ROOT/pages/dataset-component.adoc, docs/components/modules/ROOT/pages/dataset-test-component.adoc, docs/components/modules/ROOT/pages/jpa-component.adoc, docs/components/modules/ROOT/pages/log-component.adoc, docs/components/modules/ROOT/pages/mock-component.adoc, docs/components/modules/ROOT/pages/scp-component.adoc, docs/components/modules/ROOT/pages/stomp-component.adoc, docs/components/modules/ROOT/pages/xpath-language.adoc, docs/user-manual/modules/ROOT/pages/eventDrivenConsumer-eip.adoc, docs/user-manual/modules/ROOT/pages/process-eip.adoc, docs/user-manual/modules/ROOT/pages/rollback-eip.adoc
=> Revert "CAMEL-14482: Fix broken Javadocs on Camel Components"

docs/user-manual/modules/ROOT/pages/getting-started.adoc
Added hyperlink to redirect to CamelContext page
=> Added hyperlink to CamelContext page

docs/user-manual/modules/ROOT/pages/getting-started.adoc
These reference links in the document helps in redirecting to the different pages. Instead of searching each section.
=> Added Reference Links

components/camel-gson/pom.xml, components/camel-gson/src/main/java/org/apache/camel/component/gson/GsonConstants.java, components/camel-gson/src/main/java/org/apache/camel/component/gson/GsonDataFormat.java, components/camel-gson/src/test/java/org/apache/camel/component/gson/GsonDataFormatTest.java, components/camel-gson/src/test/java/org/apache/camel/component/gson/GsonUnmarshalTypeFromHeaderTest.java, components/camel-gson/src/test/java/org/apache/camel/component/gson/SpringGsonUnmarshalTypeFromHeaderTest.java, components/camel-gson/src/test/resources/org/apache/camel/component/gson/SpringGsonUnmarshalTypeFromHeaderTest.xml
Ticket [CAMEL-14630](https://issues.apache.org/jira/browse/CAMEL-14630)
=> CAMEL-14630: Added the unmarshal type from header feature

components/camel-servlet/src/main/java/org/apache/camel/component/servlet/DefaultHttpRegistry.java
added synchronized blocks so that registry is now thread-safe
[CAMEL-14639](https://issues.apache.org/jira/browse/CAMEL-14639)
=> DefaultHttpRegistry thread safety

components/camel-jcache/src/main/docs/jcache-component.adoc
=> typo at jcache-component.adoc

docs/user-manual/modules/ROOT/pages/dsl.adoc
Updated references for easy navigation and to know more, instead of searching for it.
=> Updated the reference

docs/user-manual/modules/ROOT/pages/team.adoc
Adding my name "Bahaa Zaid" to the contributor list.
I have contributed the `pg-replication-slot` component.
https://github.com/apache/camel/pull/3005
Thanks.
=> Inclusion in contributor list

components/camel-mvel/src/main/docs/mvel-component.adoc
=> fix MVEL link

components/camel-hbase/pom.xml, components/camel-hbase/src/test/java/org/apache/camel/component/hbase/CamelHBaseFilterTest.java, components/camel-hbase/src/test/java/org/apache/camel/component/hbase/CamelHBaseTestSupport.java, components/camel-hbase/src/test/java/org/apache/camel/component/hbase/HBaseConsumerTest.java, components/camel-hbase/src/test/java/org/apache/camel/component/hbase/HBaseContainer.java, components/camel-hbase/src/test/java/org/apache/camel/component/hbase/HBaseConvertionsTest.java, components/camel-hbase/src/test/java/org/apache/camel/component/hbase/HBaseProducerTest.java, components/camel-hbase/src/test/java/org/apache/camel/component/hbase/processor/idempotent/HBaseIdempotentRepositoryTest.java
=> CAMEL-14576: camel-hbase - Test using test containers

components/camel-aws2-cw/src/main/java/org/apache/camel/component/aws2/cw/Cw2Endpoint.java, components/camel-aws2-ddb/src/main/java/org/apache/camel/component/aws2/ddb/Ddb2Endpoint.java, components/camel-aws2-ddb/src/main/java/org/apache/camel/component/aws2/ddbstream/Ddb2StreamEndpoint.java, components/camel-aws2-ec2/src/main/java/org/apache/camel/component/aws2/ec2/AWS2EC2Endpoint.java, components/camel-aws2-ecs/src/main/java/org/apache/camel/component/aws2/ecs/ECS2Endpoint.java, components/camel-aws2-eks/src/main/java/org/apache/camel/component/aws2/eks/EKS2Endpoint.java, components/camel-aws2-iam/src/main/java/org/apache/camel/component/aws2/iam/IAM2Endpoint.java, components/camel-aws2-kms/src/main/java/org/apache/camel/component/aws2/kms/KMS2Endpoint.java, components/camel-aws2-mq/src/main/java/org/apache/camel/component/aws2/mq/MQ2Endpoint.java, components/camel-aws2-msk/src/main/java/org/apache/camel/component/aws2/msk/MSK2Endpoint.java, components/camel-aws2-ses/src/main/java/org/apache/camel/component/aws2/ses/Ses2Endpoint.java, components/camel-aws2-sns/src/main/java/org/apache/camel/component/aws2/sns/Sns2Endpoint.java, components/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Endpoint.java, components/camel-aws2-translate/src/main/java/org/apache/camel/component/aws2/translate/Translate2Endpoint.java
Raised as per review comments in [PR](https://github.com/apache/camel/pull/3655)
Thanks,
Saravanakumar
=> CAMEL-14749: Fixed proxy config issue in 3.1.x branch

components/camel-crypto/src/main/docs/crypto-dataformat.adoc, components/camel-flatpack/src/main/docs/flatpack-dataformat.adoc, components/camel-hl7/src/main/docs/hl7-dataformat.adoc, components/camel-jetty9/src/main/docs/jetty-component.adoc, components/camel-josql/src/main/docs/sql-language.adoc, components/camel-mina/src/main/docs/mina-component.adoc, components/camel-mina2/src/main/docs/mina2-component.adoc, components/camel-quickfix/src/main/docs/quickfix-component.adoc, components/camel-salesforce/camel-salesforce-component/src/main/docs/salesforce-component.adoc, components/camel-syslog/src/main/docs/syslog-dataformat.adoc, components/fix-eip-xrefs.sh, docs/components/modules/ROOT/pages/index.adoc, docs/components/modules/ROOT/pages/jetty-component.adoc, docs/components/modules/ROOT/pages/mina-component.adoc, docs/components/modules/ROOT/pages/mina2-component.adoc, docs/components/modules/ROOT/pages/quickfix-component.adoc, docs/components/modules/ROOT/pages/salesforce-component.adoc, docs/components/modules/dataformats/pages/crypto-dataformat.adoc, docs/components/modules/dataformats/pages/flatpack-dataformat.adoc, docs/components/modules/dataformats/pages/hl7-dataformat.adoc, docs/components/modules/dataformats/pages/syslog-dataformat.adoc, docs/components/modules/languages/pages/sql-language.adoc
oops, I thought I'd already done this.
=> Resolves CAMEL-14784: fix xrefs in camel-2.x branch.

components/camel-elytron/pom.xml, components/camel-elytron/src/main/docs/elytron-component.adoc, docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide.adoc
Issue: https://issues.apache.org/jira/browse/CAMEL-14584
Unnecessary transitive dependencies were removed from org.wildfly.security:wildfly-elytron in pom.
Doc and upgrade doc is updated.
[ ] Write a pull request description that is detailed enough …
=> CAMEL-14584 camel-elytron - Only use the JARs really needed

components/camel-spring/pom.xml, core/camel-core-engine/pom.xml, core/camel-management-api/pom.xml, core/camel-management/pom.xml, core/camel-util/pom.xml, pom.xml
Added a camel.javadoc.offline to support building camel behind a firewall.
https://issues.apache.org/jira/browse/CAMEL-14687
[x ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
[ x] Each commit in the pull request should have a meaningful subject line and body.
[ x] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
[x ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
[ x] …
=> CAMEL-14687 Add camel.javadoc.offline

components/camel-tika/src/main/java/org/apache/camel/component/tika/TikaComponent.java, components/camel-tika/src/main/java/org/apache/camel/component/tika/TikaProducer.java
Issue: https://issues.apache.org/jira/browse/CAMEL-14833
Improvement for usage of different parser (not autodetectParser)  inside tika component.
There is no need for a new test because functionality is not changed.
[ ] Write a pull request …
=> CAMEL-14833 camel-tika: enhance TikaProducer to be easoly extensible

core/camel-support/src/main/java/org/apache/camel/support/component/ApiMethodParser.java, tooling/maven/camel-api-component-maven-plugin/src/main/java/org/apache/camel/maven/AbstractApiMethodGeneratorMojo.java, tooling/maven/camel-api-component-maven-plugin/src/test/java/org/apache/camel/component/test/TestProxy.java, tooling/maven/camel-api-component-maven-plugin/src/test/resources/test-proxy-signatures.txt
=> CAMEL-14626 : api maven plugin - Cannot load <T> class

docs/user-manual/modules/ROOT/pages/clustering.adoc
=> Fix "clutser" -> "cluster" typos

components/camel-telegram/pom.xml
https://issues.apache.org/jira/browse/CAMEL-14865
=> CAMEL-14865: camel-telegram - Add the jackson-core dependency

components/camel-telegram/pom.xml
https://issues.apache.org/jira/browse/CAMEL-14865
=> CAMEL-14865: camel-telegram - Add the jackson-core dependency for 2.25.x

core/camel-support/src/main/java/org/apache/camel/support/LRUCacheFactory.java
=> Fixed typo in name of class displayed on log

components/camel-jetty/src/main/docs/jetty-component.adoc
I've added 2 dedicated examples for a Blueprint XML definition of
1. SSL context parameters
2. Security parameters for basic authentication
[ ] Write a pull request description that is detailed enough to understand what the pull request does, how, …
=> Added Blueprint examples for SSL and basic auth

core/camel-componentdsl/src/generated/resources/metadata.json, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/dsl/component/ComponentsDslMetadataRegistry.java
It fixes the race condition in the metadata.json since I was wrapping the component model which is not needed since is done now in the jsonmapper
[ ] Write a pull request description that is detailed enough to understand what the pull request does, …
=> CAMEL-14876: Remove not needed component model wrapper to fix race condition in the metadata.json

components/camel-test-spring/src/main/docs/test-spring.adoc, docs/components/modules/ROOT/pages/test-spring.adoc
=> Fixes CAMEL-14899: fix xrefs to point to current version

components/camel-jetty/src/main/docs/jetty-component.adoc
Removal of unnecessary route id
[ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic …
=> Minor change in section "Blueprint based configuration of endpoint"

components/camel-azure/src/generated/resources/org/apache/camel/component/azure/blob/azure-blob.json, components/camel-azure/src/main/docs/azure-blob-component.adoc, components/camel-azure/src/main/java/org/apache/camel/component/azure/blob/BlobServiceEndpoint.java, core/camel-componentdsl/src/generated/java/org/apache/camel/builder/component/ComponentsBuilderFactory.java, core/camel-componentdsl/src/generated/java/org/apache/camel/builder/component/dsl/AzureBlobComponentBuilderFactory.java, core/camel-componentdsl/src/generated/resources/metadata.json, core/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/dsl/BlobServiceEndpointBuilderFactory.java
=> Add legacy and a note into the doc about the legacy azure component

docs/user-manual/modules/ROOT/pages/Endpoint-dsl.adoc
Adding the maven statement
[ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic …
=> Enhancing the implementation

components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpSupport.java
Ref: https://github.com/apache/camel-k-runtime/issues/301
[x] Run `mvn clean install -Psourcecheck` in your module with source check …
=> Backport fix for camel-platform-http-vertx

docs/user-manual/modules/ROOT/pages/processor.adoc
Reusability is not mentioned. Mentioned that.
[ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to …
=> Added point for anonymous inner classes usage

components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpServer.java, components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpServerConfiguration.java, components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpServerSupport.java, components/camel-platform-http-vertx/src/test/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpEngineTest.java
[X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
[X] Each commit in the pull request should have a meaningful subject line and body.
[X] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
[X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
[X] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no …
=> CAMEL-14925: Add CORS support to VertxPlatformHttpServer

tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/BaseModel.java, tooling/camel-tooling-model/src/main/java/org/apache/camel/tooling/model/JsonMapper.java
https://issues.apache.org/jira/browse/CAMEL-14924
=> CAMEL-14924: Introduce nativeSupported on BaseModel

parent/pom.xml, tooling/maven/camel-package-maven-plugin/pom.xml
=> chore: replace dependencies versions with properties

tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/ReflectionHelper.java, tooling/maven/camel-package-maven-plugin/pom.xml, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/GenerateConfigurerMojo.java
=> CAMEL-14933: Remove dependencies on spring in GenerateConfigurerMojo

components/camel-groovy/pom.xml, components/camel-groovy/src/main/docs/groovy-language.adoc, components/camel-groovy/src/main/java/org/apache/camel/language/groovy/GroovyExpression.java, components/camel-groovy/src/main/java/org/apache/camel/language/groovy/GroovyShellFactory.java, components/camel-groovy/src/test/java/org/apache/camel/language/groovy/GroovyShellFactoryTest.java
Add file name customization to complied classes generated from Groovy expressions for debugging purposes.
=> CAMEL-14938: Added file name customization method to GroovyShellFactory for compiled classes

core/camel-base/src/main/java/org/apache/camel/processor/Enricher.java, core/camel-core/src/test/java/org/apache/camel/processor/enricher/EnricherAggregateStreamingTest.java
CAMEL-14972: Enricher does not reset stream cache for aggregator
[X ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
[X ] Each commit in the pull request should have a meaningful subject line and body.
[X ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
[X ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
[X ] Run `mvn clean install -Psourcecheck` in your module with …
=> CAMEL-14972: Enricher does not reset stream cache for aggregator

core/camel-core/src/test/java/org/apache/camel/processor/enricher/EnricherAggregateStreamingTest.java
Small fix of style error.
[ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic …
=> fix of check style

apache-camel/src/main/descriptors/common-bin.xml, components/camel-undertow-spring-security/pom.xml, components/camel-undertow-spring-security/src/main/docs/undertow-spring-security-component.adoc, components/camel-undertow-spring-security/src/main/java/org/apache/camel/component/spring/security/SpringSecurityConfiguration.java, components/camel-undertow-spring-security/src/main/java/org/apache/camel/component/spring/security/SpringSecurityProvider.java, components/camel-undertow-spring-security/src/main/java/org/apache/camel/component/spring/security/keycloak/KeycloakJwtAuthenticationConverter.java, components/camel-undertow-spring-security/src/main/java/org/apache/camel/component/spring/security/keycloak/KeycloakRealmRoleConverter.java, components/camel-undertow-spring-security/src/main/java/org/apache/camel/component/spring/security/keycloak/KeycloakUsernameSubClaimAdapter.java, components/camel-undertow-spring-security/src/main/resources/META-INF/services/org.apache.camel.component.undertow.spi.UndertowSecurityProvider, components/camel-undertow-spring-security/src/test/java/org/apache/camel/component/spring/security/AbstractSpringSecurityBearerTokenTest.java, components/camel-undertow-spring-security/src/test/java/org/apache/camel/component/spring/security/MockFilter.java, components/camel-undertow-spring-security/src/test/java/org/apache/camel/component/spring/security/SpringSecurityBearerTokenTest.java, components/camel-undertow-spring-security/src/test/resources/log4j2.properties, components/camel-undertow/src/main/docs/undertow-component.adoc, components/camel-undertow/src/main/java/org/apache/camel/component/undertow/DefaultUndertowHost.java, components/pom.xml, docs/components/modules/ROOT/nav.adoc, docs/components/modules/ROOT/pages/undertow-component.adoc, docs/components/modules/ROOT/pages/undertow-spring-security-component.adoc, parent/pom.xml
Issue: https://issues.apache.org/jira/browse/CAMEL-14977
Improvement contains a new undertowSecurityProvider for spring security 5.
It contains provider and its configuration, a few helper classes for keycloak scenario and basic mock tests.
As a part of the changes is a small extension of camel-undertow doc, about property requireServletContext
and addition of undeployment of servlet in http://defaultundertowhost.java.
This change will be followed by improvement (https://issues.apache.org/jira/browse/CAMEL-14962), which will bring starter or some kind of helper for starter.
@davsclaus I'm facing one problem with servlet api version. If I use servlet api 3.1 which is used on whole camel, execution of tests fails with `java.lang.NoClassDefFoundError: javax/servlet/http/MappingMatch`. My …
=> CAMEL-14977: Create camel-undertow-spring-security component

components/camel-undertow-spring-security/src/test/java/org/apache/camel/component/spring/security/AbstractSpringSecurityBearerTokenTest.java
Issue: https://issues.apache.org/jira/browse/CAMEL-14988
Removed unnecessary code which causes troubles in runtime
[ ] Run `mvn clean …
=> CAMEL-14988 camel-undertow-spring-security: don't create file in meta-inf

components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowConsumer.java, components/camel-undertow/src/test/java/org/apache/camel/component/undertow/spi/SecurityProviderWithoutProviderTest.java
Issue: https://issues.apache.org/jira/browse/CAMEL-14987
test is present.
[ ] Run `mvn clean install -Psourcecheck` in your module …
=> CAMEL-14987 camel-undertow: more strict in case of missing security provider

components/camel-undertow-spring-security/src/main/java/org/apache/camel/component/spring/security/SpringSecurityProvider.java, components/camel-undertow-spring-security/src/test/java/org/apache/camel/component/spring/security/MockFilter.java, components/camel-undertow-spring-security/src/test/java/org/apache/camel/component/spring/security/NoTokenTest.java
Issue: https://issues.apache.org/jira/browse/CAMEL-14986
There is a chance in case of wrong configuration of spring-security that there will be no authentication token in context. In that case security provider has to deny access.
Test is added.
Also some logging is added.
[ ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the …
=> CAMEL-14986 camel-undertow-spring-security: more strict

components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpServer.java
=> CAMEL-15004: Make VertxPlatformHttpServer public

core/camel-core/src/test/java/org/apache/camel/support/PropertyBindingSupportConfigurerTest.java, core/camel-support/src/main/java/org/apache/camel/support/PropertyBindingSupport.java
=> CAMEL-15003: PropertyBindingSupport fails for anonymous classes

core/camel-main/pom.xml, core/camel-main/src/main/java/org/apache/camel/main/BaseMainSupport.java, core/camel-main/src/main/java/org/apache/camel/main/MainHelper.java, core/camel-main/src/test/java/org/apache/camel/main/MainPropertyPlaceholderTest.java, core/camel-main/src/test/java/org/apache/camel/main/MainPropertyPlaceholderWithEnvTest.java, core/camel-main/src/test/java/org/apache/camel/main/MainPropertyPlaceholderWithSystemTest.java, core/camel-main/src/test/resources/initial.properties, core/camel-main/src/test/resources/override.properties, core/camel-main/src/test/resources/user.properties, parent/pom.xml
=> CAMEL-15006: Allow to configure camel-main's properties locations using system properties and env vars

apache-camel/pom.xml, parent/pom.xml, pom.xml, tooling/maven/camel-javadoc-plugin/pom.xml
=> Upgrade plugins to have better reproducible builds

apache-camel/pom.xml, parent/pom.xml, pom.xml, tooling/maven/camel-javadoc-plugin/pom.xml
=> Revert "Upgrade plugins to have better reproducible builds"

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/BaseEmbeddedKafkaTest.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaConsumerBatchSizeTest.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaConsumerFullTest.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaConsumerLastRecordHeaderTest.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaConsumerManualCommitTest.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaConsumerRebalanceTest.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaConsumerTopicIsPatternTest.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaProducerFullTest.java
Fix the failing testcontainers tests for kafka
[ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to …
=> CAMEL-14957: Fix Kafka testcontainers integration tests

components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/format/factories/DefaultFactoryRegistry.java, components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/format/factories/ZonedDateTimeFormatFactory.java, components/camel-bindy/src/test/java/org/apache/camel/dataformat/bindy/model/date/BindyDatePatternCsvUnmarshallTest.java
=> [CAMEL-15024] Add support for ZonedDateTime in camel-bindy

core/camel-main/src/main/java/org/apache/camel/main/MainCommandLineSupport.java, core/camel-main/src/main/java/org/apache/camel/main/MainSupport.java
=> camel-main: move Option from MainSupport to MainCommandLineSupport

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java
=> CAMEL-15055 Exception is missed

tooling/openapi-rest-dsl-generator/src/main/java/org/apache/camel/generator/openapi/SpringBootProjectSourceCodeGenerator.java, tooling/swagger-rest-dsl-generator/src/main/java/org/apache/camel/generator/swagger/SpringBootProjectSourceCodeGenerator.java
[x ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
[x ] Each commit in the pull request should have a meaningful subject line and body.
[x ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
[ x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
[ x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are …
=> Fix rest DSL controller generation when requestUri starts with slash

components/camel-aws-s3/src/main/docs/aws-s3-component.adoc
First I read I tought uri format only allowed arn, but once I readet with more detail it was clear that it allows both "bucketName" or "arn"
I copied the style from activemq, I think is clearer :)
[ ] Write a pull request description that is detailed …
=> Format in uri documentation

tooling/openapi-rest-dsl-generator/src/test/resources/SpringBootRestController.txt, tooling/swagger-rest-dsl-generator/src/test/resources/SpringBootRestController.txt
PR #3821
https://builds.apache.org/job/Camel/job/master/2215/testReport/
=> [CAMEL-15058] Fix failing rest DSL tests

components/camel-direct/src/main/java/org/apache/camel/component/direct/DirectEndpoint.java
Adding default value for failIfNoConsumers option
=> Adding default value

docs/user-manual/modules/ROOT/pages/rest-dsl.adoc
Adding xml dsl for input and output binding to POJOs
[ ] Run `mvn clean install -Psourcecheck` in your module with source check …
=> Adding xml dsl for binding section

components/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubConsumer.java
=> CAMEL-15064: Fix camel-google-pubsub not receiving messages due to unwanted thread termination

components/camel-kafka/pom.xml, parent/pom.xml
=> CAMEL-15089: camel-kafka - remove the kafka_2.12

camel-dependencies/pom.xml
Old version Fastjson has a serious security problem, which will cause RCE
https://www.anquanke.com/post/id/199527
https://www.cnblogs.com/tr1ple/p/12348886.html
https://github.com/jas502n/fastjson-1.2.58-rce
[ ] Write a pull request description that …
=> Old Fastjson has a serious security problem

docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_3.adoc
=> CAMEL-15005: add migration instructions

components/camel-sql/src/main/java/org/apache/camel/processor/aggregate/jdbc/DefaultJdbcOptimisticLockingExceptionMapper.java, components/camel-sql/src/main/java/org/apache/camel/processor/aggregate/jdbc/JdbcAggregationRepositoryNew.java
Same as #3851, but for `2.25.x` branch.
=> [CAMEL-7810] Use OptimisticLockingException for version conflicts (2.25.x)

core/camel-api/src/main/java/org/apache/camel/spi/OnCamelContextEvent.java, core/camel-api/src/main/java/org/apache/camel/spi/OnCamelContextInitialized.java, core/camel-api/src/main/java/org/apache/camel/spi/OnCamelContextStart.java, core/camel-api/src/main/java/org/apache/camel/spi/OnCamelContextStop.java, core/camel-base/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java, core/camel-core-engine/src/main/java/org/apache/camel/builder/RouteBuilder.java, core/camel-core/src/test/java/org/apache/camel/impl/LifecycleStrategyDiscoveryTest.java, core/camel-main/src/test/java/org/apache/camel/main/ContextEventsTest.java, core/camel-support/src/main/java/org/apache/camel/support/LifecycleStrategySupport.java
From https://github.com/apache/camel-k-runtime/issues/324
[ ] Run `mvn clean install -Psourcecheck` in your module with source check …
=> Add a way to easily call a bean method when a camel lifecycle event happen

components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/MongoDbEndpoint.java
Adjust the exception message to highlight that the collection is missing on the DB
[x] Run `mvn clean install -Psourcecheck` in your …
=> Improve the exception message if the collection does not exist on the database

components/camel-rest-openapi/src/main/java/org/apache/camel/component/rest/openapi/RestOpenApiEndpoint.java
=> camel-rest-openapi: minor code cleanup

components/camel-bean/src/main/java/org/apache/camel/component/bean/BeanEndpoint.java, components/camel-dataformat/src/main/java/org/apache/camel/component/dataformat/DataFormatEndpoint.java, components/camel-dozer/src/main/java/org/apache/camel/component/dozer/DozerEndpoint.java, components/camel-file/src/main/java/org/apache/camel/component/file/GenericFileConsumer.java, components/camel-file/src/main/java/org/apache/camel/component/file/GenericFileEndpoint.java, components/camel-sql/src/main/java/org/apache/camel/component/sql/SqlConsumer.java, components/camel-sql/src/main/java/org/apache/camel/component/sql/SqlProducer.java, components/camel-sql/src/main/java/org/apache/camel/component/sql/stored/SqlStoredEndpoint.java, components/camel-sql/src/main/java/org/apache/camel/component/sql/stored/SqlStoredProducer.java, components/camel-sql/src/main/java/org/apache/camel/processor/aggregate/jdbc/JdbcAggregationRepository.java, components/camel-stream/src/main/java/org/apache/camel/component/stream/StreamEndpoint.java, components/camel-timer/src/main/java/org/apache/camel/component/timer/TimerConsumer.java, components/camel-timer/src/main/java/org/apache/camel/component/timer/TimerEndpoint.java, components/camel-xslt/src/main/java/org/apache/camel/component/xslt/XsltAggregationStrategy.java, components/camel-xslt/src/main/java/org/apache/camel/component/xslt/XsltEndpoint.java
https://issues.apache.org/jira/browse/CAMEL-14805 
* camel-bean
* camel-dataformat
* camel-dozer
* camel-file
* camel-sql
* camel-stream
* camel-timer
* camel-xslt
=> CAMEL-14805: Component - Use doInit for wiring instead of doStart

docs/user-manual/modules/ROOT/nav.adoc, docs/user-manual/modules/ROOT/pages/component-dsl.adoc, docs/user-manual/modules/ROOT/pages/index.adoc
Add a doc about the component-dsl
=> CAMEL-14634: Add component-dsl doc

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/streaming/SubscriptionHelper.java
[X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
[X] Each commit in the pull request should have a meaningful subject line and body.
[X] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
[X] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
[X] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no …
=> CAMEL-15117: camel-salesforce - prevent NPE during stop

parent/pom.xml
=> chore(deps): update testcontainers to v1.14.3

docs/user-manual/modules/ROOT/pages/rest-dsl.adoc
Corrected xml tags syntax in XML DSL
=> REST DSL documentation update

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/UpdateReadmeMojo.java
AemieJ's work on organizing the component files into groups needs a little help so the `:group:` attribute doesn't get overwritten by the generation process.
This adds a hardcoded list of attribute names whereby attributes by those names will be preserved through the generation process, moved to the end of the list of attributes.
=> Relates to CAMEL-14910: Allow specific manually maintained attributes in component adoc headers

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java
In KafkaConsumer, clear lastProcessedOffset if Exception on partition Revoked
=> Camel 14935 kafka exception

components/camel-iec60870/src/main/docs/iec60870-client-component.adoc, components/camel-iec60870/src/main/docs/iec60870-server-component.adoc
CrossRef: https://github.com/wildfly-extras/wildfly-camel/issues/2965
=> [CAMEL-15149] Invalid UTF8 character in iec60870-server.json

core/camel-base/src/main/java/org/apache/camel/processor/errorhandler/ExceptionPolicy.java, core/camel-core-engine/src/main/java/org/apache/camel/reifier/errorhandler/ErrorHandlerReifier.java
=> Camel 15151

components/camel-aws2-kinesis/src/test/java/org/apache/camel/component/aws2/kinesis/KinesisConsumerClosedShardWithFailTest.java
the one i missed in https://github.com/apache/camel/pull/3894
=> CAMEL-15153: fixing KinesisConsumerClosedShardWithFailTest

core/camel-util/src/main/java/org/apache/camel/util/backoff/BackOff.java
=> CAMEL-15147 camel-core - Supervising route nicer logging

components/camel-grpc/src/main/java/org/apache/camel/component/grpc/GrpcConstants.java, components/camel-grpc/src/main/java/org/apache/camel/component/grpc/GrpcConsumer.java, components/camel-grpc/src/main/java/org/apache/camel/component/grpc/server/BindableServiceFactory.java, components/camel-grpc/src/main/java/org/apache/camel/component/grpc/server/DefaultBindableServiceFactory.java, components/camel-grpc/src/main/java/org/apache/camel/component/grpc/server/GrpcMethodHandler.java
https://issues.apache.org/jira/browse/CAMEL-15144
=> CAMEL-15144: Add capability to customize BindableService class generation

tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/CamelVersionHelper.java, tooling/camel-tooling-util/src/test/java/org/apache/camel/tooling/util/CamelVersionHelperTest.java
Increase the size of the version in parsing to support longer camel version numbers.
[ x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
[ x] Each commit in the pull request should have a meaningful subject line and body.
[ x] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
[x ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
[x ] Run `mvn clean install -Psourcecheck` …
=> CAMEL-15175 Support longer camel version numbers

components/camel-azure-storage-blob/src/main/docs/azure-storage-blob-component.adoc, components/camel-azure-storage-blob/src/main/java/org/apache/camel/component/azure/storage/blob/BlobConstants.java, components/camel-azure-storage-blob/src/main/java/org/apache/camel/component/azure/storage/blob/BlobExchangeHeaders.java, components/camel-azure-storage-blob/src/main/java/org/apache/camel/component/azure/storage/blob/operations/BlobOperations.java, components/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/BlobProducerIT.java, components/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/operations/BlobOperationsIT.java
=> CAMEL-15181: Change Created Azure headers

components/camel-telegram/src/main/java/org/apache/camel/component/telegram/TelegramEndpoint.java
Add **default**  statement for unknown proxy type.
=> [CAMEL-15188] Fix checkstyle

components/camel-aws2-eks/src/main/docs/aws2-eks-component.adoc, docs/components/modules/ROOT/pages/aws2-eks-component.adoc
=> Minimal useful change to test backport github action

components/camel-aws2-ecs/src/main/docs/aws2-ecs-component.adoc, docs/components/modules/ROOT/pages/aws2-ecs-component.adoc
=> Minimal useful docs update for testing backport gh action

components/camel-aws2-kinesis/src/main/docs/aws2-kinesis-component.adoc, docs/components/modules/ROOT/pages/aws2-kinesis-component.adoc
=> Added a little note about AWS-Kinesis batch support

docs/user-manual/modules/ROOT/pages/release-guide.adoc
=> Reorder the release guide section

components/camel-netty/src/main/java/org/apache/camel/component/netty/NettyProducer.java, components/camel-netty/src/main/java/org/apache/camel/component/netty/handlers/ClientChannelHandler.java
* add back the codes which removes the "timeout" handler after receiving the response
* add the "timeout" handler when activating from the connection pool
=> CAMEL-15195 backport to 3.4.x

camel-dependencies/pom.xml, components/camel-djl/pom.xml, components/camel-djl/src/main/docs/djl-component.adoc, parent/pom.xml
Implementation of https://issues.apache.org/jira/browse/CAMEL-15221
Upgrade Deep Java Library to the latest version (0.5.0)
Deep Java Library engine implements with MxNet, Pytorch and Tensorflow.
Engines dependencies scope is set to test for tests. 
Engine implementation configuration is documented.
=> CAMEL-15221: Upgrade to Deep Java Library 0.5.0

docs/user-manual/modules/ROOT/pages/exception-clause.adoc
=> Typo mistake about HTTP

CONTRIBUTING.md
Fixing Dead Links & removing reference to wiki in CONTRIBUTING.md file.
=> Removing dead links & IRC reference

components/camel-cdi/src/main/java/org/apache/camel/cdi/transaction/MandatoryJtaTransactionPolicy.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/transaction/NeverJtaTransactionPolicy.java
=> CAMEL-15251: camel-cdi fix the mandatory and never transaction policy

components/camel-http/src/main/java/org/apache/camel/component/http/HttpComponent.java, components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/NettyHttpComponent.java, components/camel-openapi-java/src/main/java/org/apache/camel/openapi/OpenApiRestProducerFactory.java, components/camel-swagger-java/src/main/java/org/apache/camel/swagger/SwaggerRestProducerFactory.java, components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowComponent.java
=> RestProducerFactory: match RestConfiguration by producer component

components/camel-djl/src/main/docs/djl-component.adoc
=> CAMEL-15216 : Omit the warning of section levels

components/camel-zookeeper/src/main/java/org/apache/camel/component/zookeeper/ZooKeeperCuratorHelper.java, components/camel-zookeeper/src/test/java/org/apache/camel/component/zookeeper/ZooKeeperCuratorHelperTest.java
Fix reversed order of arguments maxRetries and maxSleepMs in constructor
call of ExponentialBackoffRetry in ZooKeeperCuratorHelper.createCurator
[ ] Write a pull request description that is detailed enough to understand what the pull request does, …
=> [CAMEL-15262] Fix argument order in new ExponentialBackoffRetry call in ZooKeeperCuratorHelper

components/camel-debezium-common/camel-debezium-common-component/src/main/java/org/apache/camel/component/debezium/DebeziumConsumer.java, components/camel-debezium-common/pom.xml
=> CAMEL-14777: Replace Debezium EmbeddedEngine instance with DebeziumEngine APIs

components/camel-kafka/src/main/docs/kafka-component.adoc, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConstants.java, components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumer.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaConsumerLastRecordHeaderTest.java
=> CAMEL-15228: add end signal for polls

components/camel-cdi/pom.xml, components/camel-cdi/src/main/java/org/apache/camel/cdi/transaction/TransactionalJtaTransactionPolicy.java
=> CAMEL-14918 - camel-cdi: Avoid @Resource injection

components/camel-jira/src/test/java/org/apache/camel/component/jira/producer/TransitionIssueProducerTest.java, parent/pom.xml
Update version of jira-rest-client-api
=> CAMEL-15272 Bump version for jira-rest-client-api

docs/user-manual/modules/ROOT/pages/route-template.adoc, docs/user-manual/modules/faq/pages/how-do-i-configure-endpoints.adoc
=> [CAMEL-15216] Fix asciidoc WARNINGs in camel-website

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/client/DefaultBulkApiClient.java, components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/streaming/ReplayExtension.java, components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/streaming/SubscriptionHelper.java, components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/internal/streaming/ReplayExtensionTest.java
=> CAMEL-15233: Fix Replay Extension to correctly get replayId from message

components/camel-kudu/pom.xml, docs/pom.xml
Tested on Windows 10, Ubuntu and CI ( https://builds.apache.org/view/C/view/Apache%20Camel/job/Camel/job/CAMEL-15284/1/ ).
[ ] Run …
=> CAMEL-15284: Fix camel-kudu and docs Windows build

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/barcode-dataformat.adoc, catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/durable-subscriber.adoc, catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/netty-component.adoc, catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/pgp-dataformat.adoc, components/camel-apns/src/main/docs/apns-component.adoc, components/camel-barcode/src/main/docs/barcode-dataformat.adoc, components/camel-cm-sms/src/main/docs/cm-sms-component.adoc, components/camel-crypto/src/main/docs/pgp-dataformat.adoc, components/camel-netty/src/main/docs/netty-component.adoc, core/camel-core-engine/src/main/docs/modules/eips/pages/durable-subscriber.adoc, docs/components/modules/ROOT/pages/apns-component.adoc, docs/components/modules/ROOT/pages/cm-sms-component.adoc, docs/components/modules/ROOT/pages/netty-component.adoc, docs/components/modules/dataformats/pages/barcode-dataformat.adoc, docs/components/modules/dataformats/pages/pgp-dataformat.adoc, docs/user-manual/modules/ROOT/pages/books.adoc, docs/user-manual/modules/ROOT/pages/exception-clause.adoc, docs/user-manual/modules/ROOT/pages/parameter-binding-annotations.adoc, docs/user-manual/modules/ROOT/pages/pojo-consuming.adoc, docs/user-manual/modules/ROOT/pages/security.adoc, docs/user-manual/modules/ROOT/pages/spring-remoting.adoc
This PR fixes some broken anchors with in valid characters and a broken image.
=> [CAMEL-15285] fix broken anchors and images

core/camel-core/src/test/java/org/apache/camel/impl/VanillaUuidGeneratorTest.java, core/camel-support/src/main/java/org/apache/camel/support/VanillaUuidGenerator.java
=> Move FastUuidGenerator from camel-quarkus

components/camel-reactive-streams/src/main/java/org/apache/camel/component/reactive/streams/ReactiveStreamsCamelSubscriber.java, components/camel-reactive-streams/src/main/java/org/apache/camel/component/reactive/streams/ReactiveStreamsHelper.java, components/camel-reactive-streams/src/main/java/org/apache/camel/component/reactive/streams/api/CamelReactiveStreamsService.java, components/camel-reactive-streams/src/main/java/org/apache/camel/component/reactive/streams/engine/CamelPublisher.java, components/camel-reactive-streams/src/main/java/org/apache/camel/component/reactive/streams/engine/CamelSubscription.java, components/camel-reactive-streams/src/main/java/org/apache/camel/component/reactive/streams/engine/DefaultCamelReactiveStreamsService.java, components/camel-reactive-streams/src/main/java/org/apache/camel/component/reactive/streams/engine/DelayedMonoPublisher.java, components/camel-reactive-streams/src/main/java/org/apache/camel/component/reactive/streams/engine/UnwrappingPublisher.java, components/camel-reactive-streams/src/main/java/org/apache/camel/component/reactive/streams/util/BodyConverter.java, components/camel-reactive-streams/src/main/java/org/apache/camel/component/reactive/streams/util/ConvertingPublisher.java, components/camel-reactive-streams/src/main/java/org/apache/camel/component/reactive/streams/util/ConvertingSubscriber.java, components/camel-reactive-streams/src/main/java/org/apache/camel/component/reactive/streams/util/MonoPublisher.java, components/camel-reactive-streams/src/test/java/org/apache/camel/component/reactive/streams/support/ReactiveStreamsTestService.java, components/camel-reactor/src/main/java/org/apache/camel/component/reactor/engine/ReactorStreamsService.java, components/camel-reactor/src/test/java/org/apache/camel/component/reactor/engine/ReactorStreamsServiceBackpressureTest.java, components/camel-reactor/src/test/java/org/apache/camel/component/reactor/engine/ReactorStreamsServiceTest.java, components/camel-rxjava/src/main/java/org/apache/camel/component/rxjava/engine/RxJavaCamelProcessor.java, components/camel-rxjava/src/main/java/org/apache/camel/component/rxjava/engine/RxJavaStreamsService.java, components/camel-rxjava/src/test/java/org/apache/camel/component/rxjava/engine/RxJavaStreamsServiceTest.java
=> camel-reactive-stream: cleanup

core/camel-base/src/main/docs/properties-component.adoc, docs/components/modules/ROOT/pages/properties-component.adoc
=> minor grammar fix

components/camel-opentracing/src/main/java/org/apache/camel/opentracing/propagation/CamelMessagingHeadersExtractAdapter.java
Signed-off-by: Ruben <ruben.vp8510@gmail.com>
[ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to …
=> [CAMEL-15022] Convert []byte header to string

components/camel-mongodb/pom.xml
=> correct typo on profiles for camel-mongodb component

docs/user-manual/modules/ROOT/pages/getting-started.adoc
The link was broken, so I fixed it.
=> Repair link to dzone article

components/camel-jetty-common/src/main/java/org/apache/camel/component/jetty/JettyHttpComponent.java, components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/NettyHttpComponent.java, components/camel-servlet/src/main/java/org/apache/camel/component/servlet/ServletComponent.java, components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowComponent.java
=> don't fail the component init/start if there's no rest configuration

components/camel-jetty-common/src/main/java/org/apache/camel/component/jetty/JettyHttpComponent.java, components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/NettyHttpComponent.java, components/camel-servlet/src/main/java/org/apache/camel/component/servlet/ServletComponent.java, components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowComponent.java
=> don't fail the component init/start if there's no rest configuration (3.4.x)

components/camel-azure/src/generated/resources/org/apache/camel/component/azure/blob/azure-blob.json, components/camel-azure/src/generated/resources/org/apache/camel/component/azure/queue/azure-queue.json, components/camel-azure/src/main/docs/azure-blob-component.adoc, components/camel-azure/src/main/docs/azure-queue-component.adoc, components/camel-azure/src/main/java/org/apache/camel/component/azure/blob/BlobServiceComponent.java, components/camel-azure/src/main/java/org/apache/camel/component/azure/blob/BlobServiceEndpoint.java, components/camel-azure/src/main/java/org/apache/camel/component/azure/queue/QueueServiceComponent.java, components/camel-azure/src/main/java/org/apache/camel/component/azure/queue/QueueServiceEndpoint.java, core/camel-componentdsl/src/generated/java/org/apache/camel/builder/component/ComponentsBuilderFactory.java, core/camel-componentdsl/src/generated/java/org/apache/camel/builder/component/dsl/AzureBlobComponentBuilderFactory.java, core/camel-componentdsl/src/generated/java/org/apache/camel/builder/component/dsl/AzureQueueComponentBuilderFactory.java, core/camel-componentdsl/src/generated/resources/metadata.json, core/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/StaticEndpointBuilders.java, core/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/dsl/BlobServiceEndpointBuilderFactory.java, core/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/dsl/QueueServiceEndpointBuilderFactory.java
To reduce the maintenance overhead, I'd like to deprecate the legacy azure components and focus the efforts on the new one instead
=> CAMEL-15318: Deprecate the legacy Azure components

components/camel-vertx-http/src/main/java/org/apache/camel/component/vertx/http/VertxHttpComponent.java, components/camel-vertx-http/src/main/java/org/apache/camel/component/vertx/http/VertxHttpEndpoint.java
Follows up on @lburgazzoli review comments in #4029.
=> CAMEL-15283: Ensure managed vertx instances are closed on shutdown

components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/utils/AutoConfiguration.java
=> [CAMEL-15315] Fix Pulsar AutoConfiguration.ensureNamespace()

components/camel-slack/src/main/java/org/apache/camel/component/slack/SlackConsumer.java
Includes:
- fix a NPE thrown when the slack conversation.list request fails
- report missing scopes when polling data from Slack
[x] …
=> CAMEL-15326: fix incorrect handling of API responses

components/camel-slack/src/main/java/org/apache/camel/component/slack/SlackConsumer.java
Includes:
- fix a NPE thrown when the slack conversation.list request fails
- report missing scopes when polling data from Slack
[x] …
=> Backport CAMEL-15326: fix incorrect handling of API responses (#4033)

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointDslMojo.java
Call setPublic on methods used for the static builders in StaticEndpointBuilders (camel-endpointdsl)
=> [CAMEL-15314] Maven tooling: make dsl static builders public in EndpointDslMojo

core/camel-xml-io/src/main/java/org/apache/camel/xml/in/BaseParser.java, core/camel-xml-io/src/test/java/org/apache/camel/xml/in/ModelParserTest.java
=> CAMEL-15346 Let xml-io pass the namespace info to NamespaceAware

core/camel-xml-io/src/test/java/org/apache/camel/xml/in/ModelParserTest.java
=> Camel-XML-Io: Fixed build

components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/internal/streaming/SubscriptionHelperTest.java
=> Camel-Salesforce: Fixed test

Jenkinsfile
=> Remove checkstyle check in Jenkinsfile

docs/user-manual/modules/ROOT/pages/team.adoc
Corrects typo in team table alignment.
=> Removes column character misaligning names

components/camel-aws-kinesis/src/main/java/org/apache/camel/component/aws/kinesis/KinesisConsumer.java
Proposed fix for CAMEL-15358
[x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic …
=> CAMEL-15358: avoid an IndexOutOfBoundsException if there are no shards

components/camel-aws-kinesis/src/main/java/org/apache/camel/component/aws/kinesis/KinesisConsumer.java
Backport fix from master
[x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks …
=> CAMEL-15358: avoid an IndexOutOfBoundsException if there are no shards (#4065)

components/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/Kinesis2Consumer.java
Proposed fix for CAMEL-15369
[x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic …
=> CAMEL-15369: avoid an IndexOutOfBoundsException if there are no shards AWS SDK v2

components/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/Kinesis2Consumer.java
Backports fix on #4070 to 3.4.x
Ref: CAMEL-15369: avoid an IndexOutOfBoundsException if there are no shards AWS SDK v2
[x] Run `mvn …
=> CAMEL-15369: backport to 3.4.x

components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/OpenTelemetryTracer.java
Signed-off-by: Ruben <ruben.vp8510@gmail.com>
This PR allows to inject an opentelemetry TracerProviderFactory via SPI.
=> Allow the use of SPI to load Opentelemetry trace provider factory

camel-dependencies/pom.xml, components/camel-activemq/pom.xml, components/camel-asterisk/pom.xml, components/camel-hdfs/pom.xml, parent/pom.xml
removing remaining traces of log4j1
=> CAMEL-14317: remove log4j1

components/camel-cxf/src/main/java/org/apache/camel/component/cxf/jaxrs/CxfRsProducer.java, components/camel-cxf/src/test/java/org/apache/camel/component/cxf/jaxrs/CxfRsProducerTest.java
=> [CAMEL-15370] CxfRsProducer: All but last value of query parameter with multiple values are lost

components/camel-minio/src/main/java/org/apache/camel/component/minio/MinioChecks.java, components/camel-minio/src/test/java/org/apache/camel/component/minio/integration/MinioComponentIntegrationTest.java, components/camel-minio/src/test/java/org/apache/camel/component/minio/integration/MinioConsumerIntegrationTest.java
There has been a known issue in minio consumer implementation which is now solved
=> Resolved a TODO in camel minio component integration test

components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/OpenTelemetrySpanAdapter.java, parent/pom.xml
Use opentelemetry 0.7 semantic conventions.
=> [CAMEL-15386] Bump opentelemetry version to 0.7

components/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Endpoint.java
Tested with AWS local and remote using the Camel Kafka Connector AWS 2 SQS. 
[x] Run `mvn clean install -Psourcecheck` in your module …
=> CAMEL-15391: override the endpoint if a custom AWS Host is provided

docs/components/modules/ROOT/pages/bean-component.adoc
Within this document there is a reference to a "Bean Binding" mechanism. I have added a link to the documentation explaining the mechanism.
=> Added reference to Bean Binding documentation

components/camel-aws-s3/src/main/java/org/apache/camel/component/aws/s3/client/impl/S3ClientIAMOptimizedImpl.java, components/camel-aws-s3/src/main/java/org/apache/camel/component/aws/s3/client/impl/S3ClientStandardImpl.java
I was reviewing the S3 code and came across this code. It seems to be unreachable. 
[x] Run `mvn clean install -Psourcecheck` in your …
=> Removes unreachable branch on camel-aws-s3 client implementations

components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxCollaborationsManager.java, components/camel-box/camel-box-component/src/test/java/org/apache/camel/component/box/BoxCollaborationsManagerTest.java
[x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no …
=> CAMEL-15424: fix a possible NPE on camel-box-api when adding a new collaborator

components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxCollaborationsManager.java, components/camel-box/camel-box-component/src/test/java/org/apache/camel/component/box/BoxCollaborationsManagerTest.java
[x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no …
=> Backport CAMEL-15424: fix a possible NPE on camel-box-api when adding a new collaborator

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/SalesforceLoginConfig.java, components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/SalesforceLoginConfigTest.java
[x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no …
=> Backport CAMEL-15425: prevent SalesforceLoginConfig from leaking the user password

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/SalesforceLoginConfig.java, components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/SalesforceLoginConfigTest.java
[x] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are no …
=> CAMEL-15425: prevent SalesforceLoginConfig from leaking the user password

core/camel-xml-jaxp/src/main/java/org/apache/camel/converter/jaxp/XmlConverter.java, core/camel-xml-jaxp/src/main/java/org/apache/camel/support/builder/xml/XMLConverterHelper.java
Just a fix for a few minor logging issues. 
Note: I also noticed that some log messages create an array that, I believe, are unnecessary. I have left them in place, but logged this as [CAMEL-15431](https://issues.apache.org/jira/browse/CAMEL-15431). Later I will review and submit a PR fixing those as well.
[x] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where …
=> CAMEL-15430: fix incorrect log placeholders

core/camel-api/src/main/java/org/apache/camel/spi/LifecycleStrategy.java, core/camel-api/src/main/java/org/apache/camel/spi/OnCamelContextInitialized.java, core/camel-api/src/main/java/org/apache/camel/spi/OnCamelContextInitializing.java, core/camel-api/src/main/java/org/apache/camel/spi/OnCamelContextStarted.java, core/camel-api/src/main/java/org/apache/camel/spi/OnCamelContextStarting.java, core/camel-api/src/main/java/org/apache/camel/spi/OnCamelContextStopped.java, core/camel-api/src/main/java/org/apache/camel/spi/OnCamelContextStopping.java, core/camel-base/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java, core/camel-base/src/main/java/org/apache/camel/impl/engine/OnCamelContextLifecycleStrategy.java, core/camel-core/src/test/java/org/apache/camel/impl/LifecycleStrategyDiscoveryTest.java, core/camel-main/src/main/java/org/apache/camel/main/MainLifecycleStrategy.java, core/camel-main/src/test/java/org/apache/camel/main/ContextEventsTest.java, core/camel-management/src/main/java/org/apache/camel/management/JmxManagementLifecycleStrategy.java, core/camel-support/src/main/java/org/apache/camel/support/LifecycleStrategySupport.java, docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_5.adoc
I'm sure I messed something and the code is full of typos my eyes can't see.
@davsclaus @gnodet mind reviewing ?
=> Lifecycle enhancements

components/camel-oaipmh/pom.xml, components/camel-oaipmh/src/main/java/org/apache/camel/oaipmh/handler/Harvester.java, components/camel-oaipmh/src/test/java/org/apache/camel/oaipmh/OAIPMHComponentConsumerHTTPSTest.java, components/camel-oaipmh/src/test/java/org/apache/camel/oaipmh/OAIPMHComponentConsumerParticularCaseTest.java, components/camel-oaipmh/src/test/java/org/apache/camel/oaipmh/OAIPMHComponentConsumerTest.java, components/camel-oaipmh/src/test/java/org/apache/camel/oaipmh/OAIPMHComponentProducerGetRecordTest.java, components/camel-oaipmh/src/test/java/org/apache/camel/oaipmh/OAIPMHComponentProducerOnlyFirstLoopTest.java, components/camel-oaipmh/src/test/java/org/apache/camel/oaipmh/OAIPMHComponentProducerOnlyFirstTest.java, components/camel-oaipmh/src/test/java/org/apache/camel/oaipmh/OAIPMHComponentSpringTest.java, components/camel-oaipmh/src/test/resources/spring/SpringOAIPMHTest.xml, docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_5.adoc
Some minor improvements for the camel-oaipmh component:
Upgrate Junit from 4 to 5 in tests.
Add XML Spring test
[ ] Run `mvn clean …
=> [CAMEL-15253] camel-oaipmh : Improvements to the component

components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpOperations.java, components/camel-irc/src/main/java/org/apache/camel/component/irc/IrcComponent.java, components/camel-jms/src/main/java/org/apache/camel/component/jms/reply/QueueReplyManager.java, components/camel-jms/src/main/java/org/apache/camel/component/jms/reply/ReplyManagerSupport.java, components/camel-quartz/src/main/java/org/apache/camel/component/quartz/QuartzEndpoint.java, components/camel-quartz/src/main/java/org/apache/camel/pollconsumer/quartz/QuartzScheduledPollConsumerScheduler.java, components/camel-spring/src/main/java/org/apache/camel/spring/spi/TransactionErrorHandler.java, components/camel-xmpp/src/main/java/org/apache/camel/component/xmpp/XmppConsumer.java, core/camel-api/src/main/java/org/apache/camel/support/jsse/SSLContextParameters.java, core/camel-support/src/main/java/org/apache/camel/support/DefaultScheduledPollConsumerScheduler.java, core/camel-xml-jaxp/src/main/java/org/apache/camel/support/builder/xml/XMLConverterHelper.java
Proposed fix for the aforementioned issue.
=> CAMEL-15431: remove redundant array creation on some log messages

tests/camel-itest/src/test/java/org/apache/camel/itest/http/HttpEndpointTest.java, tests/camel-itest/src/test/java/org/apache/camel/itest/http/HttpMaxConnectionPerHostTest.java, tests/camel-itest/src/test/java/org/apache/camel/itest/http/HttpTestServer.java
This replaces the HTTP test server with the stock one from HttpComponents.
Not all warnings are fixed as some of the them are on JMS and other tests and I'd rather fix them in a separate PR for easier review.
=> camel-itests: fix deprecation warnings

docs/user-manual/modules/ROOT/pages/health-check.adoc
As i read through the documentation I found a typo which I fixed here.
Also I think that you meant 'suffix' in the 'Health Checks' section.
[x] Write a pull request description that is detailed enough to understand what the pull request does, how, …
=> Typo & contentual changes.

components/camel-sjms/src/test/java/org/apache/camel/component/sjms/ReconnectInOutProducerTest.java, components/camel-sjms/src/test/java/org/apache/camel/component/sjms/consumer/AsyncConsumerInOutTest.java, components/camel-sjms/src/test/java/org/apache/camel/component/sjms/consumer/InOutSynchronousConsumerTest.java, components/camel-sjms/src/test/java/org/apache/camel/component/sjms/producer/InOutQueueProducerAsyncLoadTest.java, components/camel-sjms/src/test/java/org/apache/camel/component/sjms/producer/InOutQueueProducerSyncLoadTest.java, components/camel-sjms/src/test/java/org/apache/camel/component/sjms/producer/InOutQueueProducerTest.java
=> camel-sjms: fixed usage of deprecated inOut method

components/camel-smpp/src/test/java/org/apache/camel/component/smpp/AbstractSmppCommandTest.java, components/camel-smpp/src/test/java/org/apache/camel/component/smpp/SmppConfigurationTest.java, components/camel-smpp/src/test/java/org/apache/camel/component/smpp/SmppConnectionFactoryTest.java, components/camel-smpp/src/test/java/org/apache/camel/component/smpp/SmppConsumerTest.java, components/camel-smpp/src/test/java/org/apache/camel/component/smpp/SmppProducerLazySessionCreationTest.java, components/camel-smpp/src/test/java/org/apache/camel/component/smpp/SmppProducerTest.java
Fixed most of the ones in this component. The remaining warnings change the behavior of the code and cause test failures, so leaving them for later.
=> camel-smpp: fixed deprecation warnings

components/camel-ahc/src/main/java/org/apache/camel/component/ahc/AhcProducer.java, components/camel-jaxb/src/main/java/org/apache/camel/converter/jaxb/FallbackTypeConverter.java, components/camel-jetty/src/main/java/org/apache/camel/component/jetty9/JettyContentExchange9.java, components/camel-jms/src/main/java/org/apache/camel/component/jms/JmsBinding.java, components/camel-jpa/src/main/java/org/apache/camel/processor/idempotent/jpa/JpaMessageIdRepository.java, components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/utils/consumers/FailoverConsumerStrategy.java, components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/utils/consumers/KeySharedConsumerStrategy.java, components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/utils/consumers/SharedConsumerStrategy.java, components/camel-resteasy/src/main/java/org/apache/camel/component/resteasy/ResteasyProducer.java, components/camel-resteasy/src/main/java/org/apache/camel/component/resteasy/servlet/ResteasyCamelServlet.java, components/camel-sjms/src/main/java/org/apache/camel/component/sjms/jms/JmsBinding.java, components/camel-telegram/src/main/java/org/apache/camel/component/telegram/service/TelegramServiceRestBotAPIAdapter.java, core/camel-xml-jaxp/src/main/java/org/apache/camel/converter/jaxp/XmlConverter.java, core/camel-xml-jaxp/src/main/java/org/apache/camel/support/builder/xml/XMLConverterHelper.java
Include changes for:
* camel-ahc
* camel-jaxb
* camel-jetty
* camel-jms
* camel-jpa
* camel-pulsar
* camel-resteasy
* camel-sjms
* camel-telegram
* core/camel-xml-jaxp
=> CAMEL-15430: fixes missing or incorrect log place holders

core/camel-core/src/test/java/org/apache/camel/util/PredicateAssertHelperTest.java
Just a very small assert cleanup
=> camel-core: migrate throwable check to JUnit 5 assertion format

components/camel-jpa/src/test/java/org/apache/camel/processor/jpa/JpaCronSchedulerTest.java, components/camel-jpa/src/test/java/org/apache/camel/processor/jpa/JpaFlushOnSendTest.java, components/camel-jpa/src/test/java/org/apache/camel/processor/jpa/JpaPollingConsumerLockEntityTest.java, components/camel-jpa/src/test/java/org/apache/camel/processor/jpa/JpaPollingConsumerTest.java, components/camel-jpa/src/test/java/org/apache/camel/processor/jpa/JpaPollingConsumerTimeoutTest.java, components/camel-jpa/src/test/java/org/apache/camel/processor/jpa/JpaPreConsumedTest.java, components/camel-jpa/src/test/java/org/apache/camel/processor/jpa/JpaProducerConcurrentTest.java, components/camel-jpa/src/test/java/org/apache/camel/processor/jpa/JpaProducerFindEntityTest.java, components/camel-jpa/src/test/java/org/apache/camel/processor/jpa/JpaProducerNoBodyTest.java, components/camel-jpa/src/test/java/org/apache/camel/processor/jpa/JpaProducerPassingEntityManagerTest.java, components/camel-jpa/src/test/java/org/apache/camel/processor/jpa/JpaProducerRemoveTest.java, components/camel-jpa/src/test/java/org/apache/camel/processor/jpa/JpaRouteConsumeLockEntityTest.java, components/camel-jpa/src/test/java/org/apache/camel/processor/jpa/JpaRouteEndpointTest.java, components/camel-jpa/src/test/java/org/apache/camel/processor/jpa/JpaRouteMaximumResultsTest.java, components/camel-jpa/src/test/java/org/apache/camel/processor/jpa/JpaRouteSharedEntityManagerTest.java, components/camel-jpa/src/test/java/org/apache/camel/processor/jpa/JpaRouteSkipLockedEntityTest.java, components/camel-jpa/src/test/java/org/apache/camel/processor/jpa/JpaRouteTest.java, components/camel-jpa/src/test/java/org/apache/camel/processor/jpa/JpaRoutemaxMessagesPerPollTest.java, components/camel-jpa/src/test/java/org/apache/camel/processor/jpa/JpaWireTapTest.java
Another round of cleanup for warnings. A few remain in the module, but they need to be investigated further. 
=> camel-jpa: remove usages of SpringRouteBuilder in most places

components/camel-aws-sdb/src/test/java/org/apache/camel/component/aws/sdb/AmazonSDBClientMock.java, components/camel-aws-sdb/src/test/java/org/apache/camel/component/aws/sdb/DomainMetadataCommandTest.java, components/camel-aws-sdb/src/test/java/org/apache/camel/component/aws/sdb/ListDomainsCommandTest.java, components/camel-aws-sdb/src/test/java/org/apache/camel/component/aws/sdb/SdbComponentConfigurationTest.java, components/camel-aws-sdb/src/test/java/org/apache/camel/component/aws/sdb/SdbComponentSpringTest.java, components/camel-aws-sdb/src/test/java/org/apache/camel/component/aws/sdb/SdbComponentTest.java, components/camel-aws-sdb/src/test/java/org/apache/camel/component/aws/sdb/integration/SdbComponentIntegrationTest.java
- fixed usages of integer wrapper
- fixed usages of long wrapper
=> camel-aws-sdb: fixed usages of deprecated wrapper types

pom.xml
[ x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
[x ] Each commit in the pull request should have a meaningful subject line and body.
[x ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
[x ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and there are …
=> CAMEL-15490 Specify source 8 for maven-javadoc-plugin

components/camel-cdi/pom.xml, components/camel-cdi/src/main/java/org/apache/camel/cdi/transaction/TransactionalJtaTransactionPolicy.java
=> backport to 3.4.x CAMEL-14918 - camel-cdi: Avoid @Resource injection (#3971)

components/camel-spring/src/test/java/org/apache/camel/spring/interceptor/MixedPropagationTransactedTest.java, components/camel-spring/src/test/java/org/apache/camel/spring/interceptor/MixedTransactionPropagationTest.java
Another set of small fixes for some warnings (this time on camel-spring)
=> camel-spring: fix warnings due to usage of deprecated wrapper types

components/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/InfinispanProducerTest.java
=> camel-infinispan: fixed deprecation warnings about wrapper types in test code

components/camel-azure-storage-queue/src/generated/resources/org/apache/camel/component/azure/storage/queue/azure-storage-queue.json, components/camel-azure-storage-queue/src/main/docs/azure-storage-queue-component.adoc, components/camel-azure-storage-queue/src/main/java/org/apache/camel/component/azure/storage/queue/QueueEndpoint.java, core/camel-componentdsl/src/generated/resources/metadata.json, core/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/StaticEndpointBuilders.java, core/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/dsl/QueueEndpointBuilderFactory.java
=> Camel-15499 3.4.x

components/camel-quartz/src/main/docs/quartz-component.adoc
Fixed a small typo in the Configuring misfire instructions section.
[ ] Run `mvn clean install -Psourcecheck` in your module with …
=> Fix query param typo

components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/format/factories/IntegerFormatFactory.java, components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/format/factories/LongFormatFactory.java, components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/format/factories/ShortFormatFactory.java, components/camel-cxf/src/test/java/org/apache/camel/component/cxf/jaxrs/testbean/Order.java, components/camel-gora/src/test/java/org/apache/camel/component/gora/utils/GoraUtilsTest.java, components/camel-jclouds/src/test/java/org/apache/camel/component/jclouds/JcloudsBlobStoreProducerTest.java, components/camel-jclouds/src/test/java/org/apache/camel/component/jclouds/JcloudsSpringBlobstoreTest.java, components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpStreamTest.java, components/camel-spring-ws/src/test/java/org/apache/camel/component/spring/ws/security/ProducerWss4JSecurityHeaderTest.java, components/camel-spring/src/test/java/org/apache/camel/spring/remoting/MyMultiArgument.java, core/camel-core/src/test/java/org/apache/camel/component/bean/DefaultParameterMappingStrategyTest.java, core/camel-core/src/test/java/org/apache/camel/impl/DefaultProducerTemplateTest.java
Include changes for:
- core/camel-core
- camel-bindy
- camel-cxf
- camel-gora
- camel-jclouds
- camel-netty-http
- camel-spring
- camel-spring-ws
=> Fixed usages of deprecated wrapper types constructors

docs/components/modules/ROOT/pages/index.adoc
Spelling correction
[ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass …
=> Document Update

docs/user-manual/modules/ROOT/pages/release-guide.adoc
Spelling change from "enviroment" to "environment"
[ ] Run `mvn clean install -Psourcecheck` in your module with source check enabled …
=> Document change

docs/components/modules/ROOT/pages/azure-storage-queue-component.adoc
=> Fix url misspelling in azure-storage-queue example

components/camel-crypto/src/main/docs/pgp-dataformat.adoc
https://issues.redhat.com/browse/FUSEDOC-4135
https://issues.redhat.com/browse/FUSEDOC-4136
https://issues.redhat.com/browse/FUSEDOC-4137
Fixed small typos in the pgp-dataformat.adoc
=> Fixed small typos that were reported via DDF tool.

docs/user-manual/modules/ROOT/pages/uuidgenerator.adoc
=> add missing documentation about SimpleUuidGenerator

core/camel-core-engine/src/main/java/org/apache/camel/model/FaultToleranceConfigurationCommon.java
changes made from "The value are in seconds and the default is 5 seconds." to "The values are in seconds and the default value is 5 seconds."
[ ] Write a pull request description that is detailed enough to understand what the pull request does, how, …
=> Update the comments of document section

archetypes/camel-archetype-java/src/main/resources/archetype-resources/pom.xml
=> CAMEL-15525: fix incorrect main class name

archetypes/camel-archetype-java/src/main/resources/archetype-resources/pom.xml
=> CAMEL-15525: fix incorrect main class name (#4204)

components/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Consumer.java
JIRA issue: https://issues.apache.org/jira/browse/CAMEL-15530
=> [CAMEL-15530] fixes bug in camel aws2-s3 component

components/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Consumer.java
JIRA issue: https://issues.apache.org/jira/browse/CAMEL-15530
=> [CAMEL-15530] fixes bug in camel aws2-s3 component in camel-3.4.x

components/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Consumer.java, pom.xml
See https://github.com/apache/camel/runs/1109005262
[x] Run `mvn clean install -Psourcecheck` in your module with source check …
=> fix the broken mvn sourcecheck step in build

components/camel-cdi/src/main/java/org/apache/camel/cdi/transaction/TransactionalJtaTransactionPolicy.java
=> CAMEL-15504: Support alternative JNDI locations for TransactionManager

CONTRIBUTING.md, docs/user-manual/modules/ROOT/nav.adoc, docs/user-manual/modules/ROOT/pages/contributing.adoc, docs/user-manual/modules/ROOT/pages/index.adoc, docs/user-manual/modules/ROOT/pages/support.adoc
=> Switch from Gitter to Zulip

core/camel-core/src/test/java/org/apache/camel/processor/MulticastParallelTimeoutStreamCachingTest.java, core/camel-support/src/main/java/org/apache/camel/converter/stream/FileInputStreamCache.java
[X] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes. …
=> CAMEL-15532: Stream Cache file not deleted

components/camel-disruptor/src/main/java/org/apache/camel/component/disruptor/DisruptorWaitStrategy.java
=> disruptor: expose information about the class that DisruptorWaitStrategy wraps

docs/user-manual/modules/ROOT/pages/using-propertyplaceholder.adoc
[ ] Run `mvn clean install -Psourcecheck` in your module with source check …
=> Fix missing word in Using Property Placeholder documentation

.github/workflows/master-pr-build.yml, .github/workflows/master-push-build.yml
=> CAMEL-15536: Fail Github Action if git tree is dirty

components/camel-telegram/src/main/java/org/apache/camel/component/telegram/TelegramProducer.java
=> CAMEL-15534 - Camel-telegram wrongly parse chatId from headers

components/camel-mvel/src/main/java/org/apache/camel/language/mvel/RootObject.java, components/camel-mvel/src/test/java/org/apache/camel/language/mvel/MvelResourceTest.java, components/camel-mvel/src/test/resources/mymvel.txt
https://issues.apache.org/jira/browse/CAMEL-15548
=> CAMEL-15548: Easier access to headers in mvel templates

components/camel-ssh/src/main/docs/ssh-component.adoc
=> doc(ssh): mention the explicit usage of bouncycastle over eddsa

core/camel-endpointdsl/src/main/java/org/apache/camel/builder/endpoint/AbstractEndpointBuilder.java, core/camel-endpointdsl/src/test/java/org/apache/camel/builder/endpoint/EndpointQueryParamTest.java
=> CAMEL-15547 Wrong URI with http dsl and query parameters

core/camel-test-infra/camel-test-infra-common/pom.xml, core/camel-test-infra/camel-test-infra-common/src/test/java/org/apache/camel/test/infra/common/TestUtils.java, core/camel-test-infra/camel-test-infra-kafka/pom.xml, core/camel-test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/services/kafka/ContainerLocalKafkaService.java, core/camel-test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/services/kafka/KafkaService.java, core/camel-test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/services/kafka/KafkaServiceFactory.java, core/camel-test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/services/kafka/RemoteKafkaService.java, core/camel-test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/services/kafka/StrimziContainer.java, core/camel-test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/services/kafka/StrimziService.java, core/camel-test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/services/kafka/ZookeeperContainer.java, core/camel-test-infra/camel-test-infra-parent/pom.xml, core/camel-test-infra/pom.xml, core/pom.xml, parent/pom.xml
Moves part of the Kafka test infrastructure from the Camel Kafka Connector to Camel Core
=> Moves the Kafka test infrastructure

.github/pull_request_template.md
Very small change to the PR template so that it renders as list and generates a prettier checklist.
=> Uses a list for the PR template so it renders prettier when used

components/camel-aws-xray/src/test/java/org/apache/camel/component/aws/xray/CustomComponentTest.java, components/camel-freemarker/src/main/java/org/apache/camel/component/freemarker/FreemarkerComponent.java, components/camel-freemarker/src/main/java/org/apache/camel/component/freemarker/FreemarkerEndpoint.java, components/camel-freemarker/src/test/java/org/apache/camel/component/freemarker/FreemarkerEndpointTest.java, components/camel-ironmq/src/test/java/org/apache/camel/component/ironmq/IronMQComponentSpringTest.java, components/camel-ironmq/src/test/java/org/apache/camel/component/ironmq/IronMQComponentTest.java, components/camel-servlet/src/test/java/org/apache/camel/component/servlet/ServletTransferExceptionTest.java, components/camel-twitter/src/test/java/org/apache/camel/component/twitter/UserProducerInOutTest.java
Includes:
- camel-freemaker: fixed typo
- camel-freemaker: fixed usage of deprecated constructor
- camel-servlet: fixed usage of deprecated method
- camel-twitter: fixed usage of deprecated inOut method
- camel-ironmq: fixed usage of deprecated getOut method
- camel-aws-xray: fixed usage of deprecated inOnly method
=> Small cleanups spread across a few components

components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxCollaborationsManager.java, components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxCommentsManager.java, components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxEventLogsManager.java, components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxEventsManager.java, components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxFilesManager.java, components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxFoldersManager.java, components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxGroupsManager.java, components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxTasksManager.java, components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxUsersManager.java
=> camel-box: adjust the code to respect platform independent line separator

core/camel-base/src/main/java/org/apache/camel/component/properties/AbstractLocationPropertiesSource.java
=> Backporting to 3.4.x for CAMEL-15571

components/camel-cm-sms/src/test/java/org/apache/camel/component/cm/test/CMConfigurationTest.java, components/camel-cm-sms/src/test/java/org/apache/camel/component/cm/test/CMMessageTest.java, components/camel-cm-sms/src/test/java/org/apache/camel/component/cm/test/CMTest.java, components/camel-cm-sms/src/test/java/org/apache/camel/component/cm/test/CamelTestConfiguration.java, components/camel-cm-sms/src/test/java/org/apache/camel/component/cm/test/SMSMessageTest.java
=> camel-cm-sms: fix warning about deprecated methods in test code

components/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Endpoint.java
=> CAMEL-15526: Camel-AWS2-S3: Consume Gzip file from S3 not working

components/camel-sjms/src/main/java/org/apache/camel/component/sjms/batch/SjmsBatchConsumer.java, components/camel-sjms/src/test/java/org/apache/camel/component/sjms/batch/SjmsBatchConsumerTest.java
=> CAMEL-15580: SJMS Batch Consumer startup race condition

core/camel-main/src/main/java/org/apache/camel/main/DefaultRoutesCollector.java, core/camel-main/src/test/java/org/apache/camel/main/xml/MainXmlRestsTest.java, core/camel-main/src/test/resources/org/apache/camel/main/xml/camel-rests.xml
This time without introducing a circular dependency...
=> CAMEL-15581: Fix loading of XML rest definitions with camel-main

core/camel-health/src/main/java/org/apache/camel/impl/health/ContextHealthCheck.java, core/camel-health/src/main/java/org/apache/camel/impl/health/DefaultHealthCheckRegistry.java, core/camel-health/src/main/java/org/apache/camel/impl/health/HealthCheckRegistryRepository.java, core/camel-health/src/main/java/org/apache/camel/impl/health/RouteHealthCheck.java, core/camel-health/src/test/java/org/apache/camel/impl/health/DefaultHealthCheckRegistryTest.java, core/camel-health/src/test/java/org/apache/camel/impl/health/HealthCheckTest.java, core/camel-health/src/test/java/org/apache/camel/impl/health/ReadinessAndLivenessTest.java
[TASK](https://issues.apache.org/jira/browse/CAMEL-15585)
I found some things that i think should look a little better, no new functionality, just small refactor.
=> CAMEL-15585 - Camel Core health small refactor.

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/aws2-eventbridge-component.adoc, components/camel-aws2-eventbridge/src/main/docs/aws2-eventbridge-component.adoc, docs/components/modules/ROOT/pages/aws2-eventbridge-component.adoc
Lets open PRs, to be sure check will always pass. MVHA Make @valdar happy again.
=> Aws2 eventbridge docs update

components/camel-aws2-cw/pom.xml, components/camel-aws2-cw/src/test/java/org/apache/camel/component/aws2/cw/localstack/Aws2CwBaseTest.java, components/camel-aws2-cw/src/test/java/org/apache/camel/component/aws2/cw/localstack/CwComponentLocalstackTest.java
- [] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
=> Camel-AWS2-Cloudwatch: Added Testcontainers with localstack test

components/camel-aws2-kms/pom.xml, components/camel-aws2-kms/src/test/java/org/apache/camel/component/aws2/kms/localstack/Aws2KmsBaseTest.java
=> Camel-AWS2-KMS: Fixes wrong container and profile names

core/camel-core-engine/src/main/java/org/apache/camel/model/ProcessorDefinition.java
=> Update Javadoc for link to the pipeline EIP documentation Web page (previous link was broken)

components/camel-aws2-sts/pom.xml, components/camel-aws2-sts/src/test/java/org/apache/camel/component/aws2/sts/localstack/Aws2StsBaseTest.java, components/camel-aws2-sts/src/test/java/org/apache/camel/component/aws2/sts/localstack/StsGetFederartionTokenLocalstackTest.java, components/camel-aws2-sts/src/test/java/org/apache/camel/component/aws2/sts/localstack/StsGetFederationTokenLocalstackTest.java, components/camel-aws2-sts/src/test/java/org/apache/camel/component/aws2/sts/localstack/StsGetSessionTokenLocalstackTest.java
=> Sts localstack

components/camel-aws2-sts/src/test/java/org/apache/camel/component/aws2/sts/localstack/StsAssumeRoleLocalstackTest.java
=> Camel-AWS2-STS: Added a localstack test for AssumeRole operation

components/camel-aws2-lambda/pom.xml, components/camel-aws2-lambda/src/test/java/org/apache/camel/component/aws2/lambda/localstack/Aws2LambdaBaseTest.java, components/camel-aws2-lambda/src/test/java/org/apache/camel/component/aws2/lambda/localstack/LambdaCreateFunctionLocalstackTest.java
=> Aws2 lambda first spike test

components/camel-aws2-lambda/src/test/java/org/apache/camel/component/aws2/lambda/localstack/LambdaGetFunctionLocalstackTest.java
=> Camel-AWS2-Lambda: Added localstack test for GetFunction

catalog/camel-route-parser/src/main/java/org/apache/camel/parser/helper/CamelXmlTreeParserHelper.java, catalog/camel-route-parser/src/main/java/org/apache/camel/parser/model/CamelNodeDetails.java, catalog/camel-route-parser/src/test/java/org/apache/camel/parser/xml/XmlParseTreeTest.java
=> CAMEL-15610 - avoid NPE in CamelXmlTreeParserHelper.parseCamelRouteTree

components/camel-aws2-lambda/src/test/java/org/apache/camel/component/aws2/lambda/localstack/LambdaDeleteFunctionLocalstackTest.java, components/camel-aws2-lambda/src/test/java/org/apache/camel/component/aws2/lambda/localstack/LambdaListFunctionsLocalstackTest.java, components/camel-aws2-lambda/src/test/java/org/apache/camel/component/aws2/lambda/localstack/LambdaPublishVersionLocalstackTest.java
=> Aws2 lambda tests

catalog/camel-route-parser/src/main/java/org/apache/camel/parser/helper/CamelJavaTreeParserHelper.java, catalog/camel-route-parser/src/test/java/org/apache/camel/parser/java/MyPartialRoute.java, catalog/camel-route-parser/src/test/java/org/apache/camel/parser/java/RoasterJavaPartialRouteDslTest.java
RouteBuilderParser.parseRouteBuilderTree
This is useful for Tooling that have to deal with incomplete routes
=> [CAMEL-15621] Support partial routes containing only the "from" for

components/camel-atmosphere-websocket/src/test/java/org/apache/camel/component/atmosphere/websocket/WebsocketRouteTest.java, components/camel-bindy/src/test/java/org/apache/camel/dataformat/bindy/fixed/headerfooter/BindySimpleFixedLengthHeaderFooterTest.java, components/camel-bindy/src/test/java/org/apache/camel/dataformat/bindy/fixed/skipheader/BindyFixedLengthHeaderFooterSkipHeaderTest.java, components/camel-cm-sms/src/test/java/org/apache/camel/component/cm/test/CMMessageTest.java, components/camel-cm-sms/src/test/java/org/apache/camel/component/cm/test/CMTest.java, components/camel-jetty/src/test/java/org/apache/camel/component/jetty/JettyStreamCacheIssueTest.java, components/camel-ldif/src/test/java/org/apache/camel/component/ldif/LdifRouteTest.java, components/camel-servlet/src/test/java/org/apache/camel/component/servlet/ServletCamelRouterTestSupport.java, core/camel-core/src/test/java/org/apache/camel/component/bean/BeanMethodWithStringParameterTest.java, core/camel-management/src/test/java/org/apache/camel/issues/DynamicRouterConvertBodyToIssueTest.java
Signed-off-by: Miguel Serra <serramiguel1@gmail.com>
=> CAMEL-15626: Use StringBuilder instead of StringBuffer

init/camel-format-plugin/pom.xml, init/camel-format-plugin/src/main/java/net/revelc/code/formatter/FormatterMojo.java, init/camel-format-plugin/src/main/java/net/revelc/code/formatter/ValidateMojo.java, pom.xml
=> CAMEL-15638: Print detailed diff if source validation fails

docs/user-manual/modules/ROOT/pages/commercial-camel-offerings.adoc
Change to Commercial Support page, update offering for OpenLogic.
=> Updating OpenLogic commercial support description

core/camel-core/src/test/java/org/apache/camel/issues/SedaFileIdempotentIssueTest.java, core/camel-core/src/test/java/org/apache/camel/processor/IdempotentConsumerConcurrentTest.java, core/camel-core/src/test/java/org/apache/camel/processor/async/AsyncProcessorAwaitManagerInterruptWithRedeliveryTest.java, core/camel-core/src/test/java/org/apache/camel/processor/resequencer/ResequencerRunner.java, core/camel-util/src/test/java/org/apache/camel/util/concurrent/AsyncCompletionServiceTest.java
=> Prevent stackTraces from leaking to stdout for test code on core

components/camel-twitter/src/main/java/org/apache/camel/component/twitter/consumer/DefaultTwitterConsumer.java, components/camel-twitter/src/main/java/org/apache/camel/component/twitter/consumer/TwitterEventType.java, components/camel-twitter/src/main/java/org/apache/camel/component/twitter/directmessage/TwitterDirectMessageEndpoint.java, components/camel-twitter/src/main/java/org/apache/camel/component/twitter/search/SearchConsumerHandler.java, components/camel-twitter/src/main/java/org/apache/camel/component/twitter/timeline/AbstractStatusConsumerHandler.java, components/camel-twitter/src/main/java/org/apache/camel/component/twitter/timeline/TwitterTimelineEndpoint.java, components/camel-twitter/src/main/java/org/apache/camel/component/twitter/util/TwitterConverter.java, components/camel-twitter/src/test/java/org/apache/camel/component/twitter/SearchByExchangeDirectTest.java, components/camel-twitter/src/test/java/org/apache/camel/component/twitter/UriConfigurationTest.java
[TASK](https://issues.apache.org/jira/browse/CAMEL-15651)
I did a little refactor, no major changes.
=> CAMEL-15651 - camel twitter refactor.

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/BaseEmbeddedKafkaTest.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/ContainerLocalKafkaService.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/KafkaService.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/KafkaServiceFactory.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/RemoteKafkaService.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/StrimziContainer.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/StrimziService.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/ZookeeperContainer.java
I think this is more consistent with how the rest of Camel code base name the packages.
=> (chore): rename the package for camel-test-infra-kafka for greater consistency

components/camel-file/src/main/java/org/apache/camel/component/file/GenericFilePollingConsumer.java, core/camel-support/src/main/java/org/apache/camel/support/ScheduledPollEndpoint.java
=> CAMEL-15558 pollEnrich timeout issue

parent/pom.xml
=> "CAMEL-14736:Upgrade to Hadoop 3.x"

parent/pom.xml, test-infra/camel-test-infra-aws-common/pom.xml, test-infra/camel-test-infra-aws-common/src/test/java/org/apache/camel/test/infra/aws/common/AWSCommon.java, test-infra/camel-test-infra-aws-common/src/test/java/org/apache/camel/test/infra/aws/common/AWSConfigs.java, test-infra/camel-test-infra-aws-common/src/test/java/org/apache/camel/test/infra/aws/common/services/AWSService.java, test-infra/camel-test-infra-aws-v1/pom.xml, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/clients/AWSClientUtils.java, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/common/TestAWSCredentialsProvider.java, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSKinesisLocalContainerService.java, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSLocalContainerService.java, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSRemoteService.java, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSS3LocalContainerService.java, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSSNSLocalContainerService.java, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSSQSLocalContainerService.java, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSServiceFactory.java
This simplifies using localstack containers as well as the actual AWS
service as part of the tests
=> Migrated the AWS Test infra from Camel Kafka Connector

test-infra/camel-test-infra-aws-v2/pom.xml, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/clients/AWSSDKClientUtils.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/common/TestAWSCredentialsProvider.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSContainer.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSKinesisLocalContainerService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSLocalContainerService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSRemoteService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSS3LocalContainerService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSSQSLocalContainerService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSServiceFactory.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/Service.java, test-infra/pom.xml
This simplifies using localstack containers as well as the actual AWS
service as part of the tests
=> Migrated the AWS SDK v2 Test infra from Camel Kafka Connector

components/camel-univocity-parsers/src/generated/java/org/apache/camel/dataformat/univocity/UniVocityCsvDataFormatConfigurer.java, components/camel-univocity-parsers/src/generated/java/org/apache/camel/dataformat/univocity/UniVocityFixedWidthDataFormatConfigurer.java, components/camel-univocity-parsers/src/generated/java/org/apache/camel/dataformat/univocity/UniVocityTsvDataFormatConfigurer.java, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PackageDataFormatMojo.java
=> CAMEL-15666: Fix PackageDataFormatMojo handling of classes with generic types

core/camel-main/src/main/java/org/apache/camel/main/DefaultConfigurationProperties.java
Removal of duplicate key words
=> Removal of duplicate key words

Jenkinsfile, Jenkinsfile.deploy, Jenkinsfile.full.pipeline, Jenkinsfile.jdk11, Jenkinsfile.jdk14
=> Jenkinsfile JDK INFRA update

components/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Producer.java
=> Camel 15678 3.4.x

components/camel-box/camel-box-api/src/main/java/org/apache/camel/component/box/api/BoxFilesManager.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/transaction/TransactionalJtaTransactionPolicy.java, components/camel-chatscript/src/main/java/org/apache/camel/component/chatscript/ChatScriptBot.java, components/camel-cmis/src/main/java/org/apache/camel/component/cmis/CMISProducer.java, components/camel-cometd/src/main/java/org/apache/camel/component/cometd/CometdComponent.java, components/camel-couchdb/src/main/java/org/apache/camel/component/couchdb/CouchDbChangesetTracker.java, components/camel-crypto-cms/src/main/java/org/apache/camel/component/crypto/cms/crypt/EnvelopedDataDecryptor.java, components/camel-cxf/src/main/java/org/apache/camel/component/cxf/CxfEndpoint.java, components/camel-cxf/src/main/java/org/apache/camel/component/cxf/feature/AbstractDataFormatFeature.java, components/camel-cxf/src/main/java/org/apache/camel/component/cxf/jaxrs/CxfRsProducer.java, components/camel-dataset/src/main/java/org/apache/camel/component/dataset/DataSetEndpoint.java, components/camel-disruptor/src/main/java/org/apache/camel/component/disruptor/DisruptorReference.java, components/camel-dns/src/main/java/org/apache/camel/component/dns/policy/DnsActivation.java, components/camel-dns/src/main/java/org/apache/camel/component/dns/policy/DnsActivationPolicy.java, components/camel-docker/src/main/java/org/apache/camel/component/docker/consumer/DockerStatsConsumer.java, components/camel-exec/src/main/java/org/apache/camel/component/exec/impl/DefaultExecCommandExecutor.java, components/camel-file/src/main/java/org/apache/camel/component/file/GenericFileConsumer.java, components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpOperations.java, components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/RemoteFileConsumer.java, components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/RemoteFilePollingConsumerPollStrategy.java, components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/RemoteFileProducer.java, components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/strategy/FtpChangedExclusiveReadLockStrategy.java, components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/strategy/SftpChangedExclusiveReadLockStrategy.java, components/camel-google-bigquery/src/main/java/org/apache/camel/component/google/bigquery/GoogleBigQueryConnectionFactory.java, components/camel-irc/src/main/java/org/apache/camel/component/irc/IrcEndpoint.java, components/camel-irc/src/main/java/org/apache/camel/component/irc/IrcLogger.java
Minor cleanups that can wait for merge once we open for 3.7. 
- replaced concatenations with log markers
- removed unnecessary debugging guards
Components: camel-cdi, camel-chatscript, camel-cmis, camel-cometd,
camel-couchdb, camel-crypto-cms, camel-box, camel-cxf, camel-dataset,
camel-disruptor, camel-dns, camel-docker, camel-docker, camel-file,
camel-ftp, camel-google-bigquery, camel-irc
=> (chore) Cleaned up log messages

CONTRIBUTING.md
Made necessary typo, grammatical, punctuation fixes at several places in the CONTRIBUTING.md file.
=> Proofread CONTRIBUTING file with appropriate edits

README.md
Corrected typo, grammatical, punctuations at multiple places in the file: Improved readability, language coherence to benefit the prospective readers.
=> Proofread README file with multiple fixes

components/camel-resteasy/src/main/java/org/apache/camel/component/resteasy/ResteasyProducer.java
=> camel-resteasy: remove unnecessary extra eval

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/json-johnzon-dataformat.adoc, components/camel-johnzon/src/generated/resources/org/apache/camel/component/johnzon/json-johnzon.json, components/camel-johnzon/src/main/docs/json-johnzon-dataformat.adoc, docs/components/modules/dataformats/pages/json-johnzon-dataformat.adoc, tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PackageDataFormatMojo.java
=> [CAMEL-15691] ensure johnzon format doc does not inherit inaccurate jackson doc

components/camel-bonita/src/main/java/org/apache/camel/component/bonita/api/util/BonitaAPIUtil.java
=> camel-bonita: do close the FileOutputStream even if there's an exception

components/camel-mock/src/main/java/org/apache/camel/component/mock/MockEndpoint.java
=> Warn if the MockEndpoint's latch did not finish within the specified time

components/camel-tika/src/main/java/org/apache/camel/component/tika/TikaProducer.java
https://tika.apache.org/0.5/documentation.html
=> Close inputStream

Jenkinsfile, Jenkinsfile.deploy, Jenkinsfile.full.pipeline, Jenkinsfile.jdk11, Jenkinsfile.jdk12, Jenkinsfile.jdk14
=> Jdk namings

Jenkinsfile, Jenkinsfile.daily
=> Jdk 2.25.x namings

components/camel-joor/src/main/docs/joor-language.adoc
=> Minor typo in camel Joor documentation

components/camel-aws2-s3/src/main/docs/aws2-s3-component.adoc
=> Updated documentation to show custom S3 component configuration in registry

components/camel-azure-storage-blob/src/main/java/org/apache/camel/component/azure/storage/blob/BlobConsumer.java, components/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/BlobConsumerIT.java
=> CAMEL-15680: [camel-azure] Add integration test

platforms/karaf/features/src/main/resources/features.xml
=> [CAMEL-15705] correcting the xstream bundle name

components/camel-aws2-sqs/README.md, components/camel-aws2-sqs/pom.xml, components/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/integration/SqsComponentIntegrationTest.java, components/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/integration/SqsConsumerMessageIntegrationTest.java, components/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/integration/SqsProducerBatchSendFifoIntegrationTest.java, components/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/integration/SqsProducerBatchSendIntegrationTest.java, components/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/integration/SqsProducerDeleteMessageIntegrationTest.java, components/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/integration/TestSqsConfiguration.java, components/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/localstack/Aws2SQSBaseTest.java, components/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/localstack/SqsComponentLocalstackTest.java, components/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/localstack/SqsConsumerMessageLocalstackTest.java, components/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/localstack/SqsProducerBatchSendFifoLocalstackTest.java, components/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/localstack/SqsProducerBatchSendLocalstackTest.java, components/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/localstack/SqsProducerDeleteMessageLocalstackTest.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/clients/AWSSDKClientUtils.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/common/SystemPropertiesAWSCredentialsProvider.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/common/TestAWSCredentials.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSLocalContainerService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSRemoteService.java
=> Migrates the camel-aws2-sqs integration tests to the shared test infra

components/camel-opentracing/src/main/java/org/apache/camel/opentracing/OpenTracingTracer.java, components/camel-opentracing/src/test/java/org/apache/camel/opentracing/ThirdPartyInstrumentationIntegrationTest.java
Providing a test to reproduce CAMEL-15710 and a suggestion for its fix. There is a TODO in code to be addressed by the reviewers if they agree on the general approach - implementing a properly encapsulated solution would likely require public API changes to pass `tracer` into the `ActiveSpanManager` methods.
=> CAMEL-15710: Initial support for Open Tracing integration with third-party tracing

components/camel-opentracing/src/main/java/org/apache/camel/opentracing/ActiveScopeManager.java, components/camel-opentracing/src/main/java/org/apache/camel/opentracing/OpenTracingTracer.java
#4490 does not cover all the cases. While performing end-to-end tests with this snapshot, I found that traces were still not aggregating correctly. This PR fixes the problem.
I am not sure why the tests did not catch this issue, so unfortunately cannot provide better automatic coverage.
=> CAMEL-15710: Fixing onExchangeBegin/onExchangeEnd

components/camel-opentracing/src/main/java/org/apache/camel/opentracing/OpenTracingSpanAdapter.java, components/camel-opentracing/src/main/java/org/apache/camel/opentracing/OpenTracingTracer.java, components/camel-opentracing/src/main/java/org/apache/camel/opentracing/OpenTracingTracingStrategy.java, components/camel-opentracing/src/test/java/org/apache/camel/opentracing/ThirdPartyInstrumentationIntegrationTest.java
=> CAMEL-15710: Activate OpenTracing spans to allow third-parties to integrate into Camel-initiated traces

components/camel-atomix/README.md, components/camel-atomix/src/test/java/org/apache/camel/component/atomix/client/map/AtomixMapConsumerTest.java, components/camel-atomix/src/test/java/org/apache/camel/component/atomix/client/map/AtomixMapNodesProducerTest.java, components/camel-atomix/src/test/java/org/apache/camel/component/atomix/client/map/AtomixMapProducerTest.java, components/camel-atomix/src/test/java/org/apache/camel/component/atomix/client/messaging/AtomixMessagingTest.java, components/camel-atomix/src/test/java/org/apache/camel/component/atomix/client/multimap/AtomixMultiMapProducerTest.java, components/camel-atomix/src/test/java/org/apache/camel/component/atomix/client/queue/AtomixQueueConsumerTest.java, components/camel-atomix/src/test/java/org/apache/camel/component/atomix/client/queue/AtomixQueueProducerTest.java, components/camel-atomix/src/test/java/org/apache/camel/component/atomix/client/set/AtomixSetConsumerTest.java, components/camel-atomix/src/test/java/org/apache/camel/component/atomix/client/set/AtomixSetProducerTest.java, components/camel-atomix/src/test/java/org/apache/camel/component/atomix/client/value/AtomixValueConsumerTest.java, components/camel-atomix/src/test/java/org/apache/camel/component/atomix/client/value/AtomixValueProducerTest.java
- prevent NPEs from hiding other test errors/failures
- added a note about required adjustments necessary for running the tests
- removed calls to deprecated clearAll method on test code
=> Minor fixes and improvements to the camel-atomix test code:

components/camel-cassandraql/pom.xml, components/camel-cassandraql/src/test/java/org/apache/camel/component/cassandra/BaseCassandraTest.java, parent/pom.xml, test-infra/camel-test-infra-cassandra/pom.xml, test-infra/camel-test-infra-cassandra/src/test/java/org/apache/camel/test/infra/cassandra/services/CassandraLocalContainerService.java, test-infra/camel-test-infra-cassandra/src/test/java/org/apache/camel/test/infra/cassandra/services/CassandraService.java, test-infra/camel-test-infra-cassandra/src/test/java/org/apache/camel/test/infra/cassandra/services/CassandraServiceFactory.java, test-infra/camel-test-infra-cassandra/src/test/java/org/apache/camel/test/infra/cassandra/services/RemoteCassandraService.java
- moved the Cassandra test service infra-structure from CKC
- converted the camel-cassandra component tests to use the reusable test-infra
=> Make the Cassandra test infra-structure reusable

test-infra/camel-test-infra-cassandra/pom.xml
=> Fixed missing packaging configuration for the Cassandra test infra

test-infra/camel-test-infra-aws-common/pom.xml, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSLocalContainerService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSLocalContainerService.java, test-infra/camel-test-infra-cassandra/src/test/java/org/apache/camel/test/infra/cassandra/services/CassandraLocalContainerService.java, test-infra/camel-test-infra-cassandra/src/test/java/org/apache/camel/test/infra/cassandra/services/CassandraService.java, test-infra/camel-test-infra-common/pom.xml, test-infra/camel-test-infra-common/src/test/java/org/apache/camel/test/infra/common/services/ContainerService.java, test-infra/camel-test-infra-common/src/test/java/org/apache/camel/test/infra/common/services/TestService.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/ContainerLocalKafkaService.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/KafkaService.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/StrimziService.java
This allow them to have greater flexibility about how they can be used
and reduce some duplications on their interfaces.
=> Unify the test service interfaces

components/camel-mongodb/src/main/docs/mongodb-component.adoc
- use headings where applicable
- add use of constant() - current examples do not compile as they are documented
=> improve MongoDB component documentation

components/camel-csv/src/test/java/org/apache/camel/dataformat/csv/CsvUnmarshalCommentMarkerSpringTest.java, components/camel-csv/src/test/resources/org/apache/camel/dataformat/csv/CsvUnmarshalCommentMarkerSpringTest-context.xml, core/camel-support/src/main/java/org/apache/camel/support/EndpointHelper.java
=> [CAMEL-15749] Unable to configure hash symbol as commentMarker for csv data format 

core/camel-main/src/main/java/org/apache/camel/main/BaseMainSupport.java
=> CAMEL-15768: camel-main - Remove enabled from the lraProperties

docs/components/modules/ROOT/pages/index.adoc, docs/components/modules/dataformats/pages/index.adoc, docs/components/modules/languages/pages/index.adoc, docs/components/modules/others/pages/index.adoc
=> resolves CAMEL-15773: workaround bogus xref-validator nav file reclassification

components/camel-elasticsearch-rest/pom.xml, components/camel-elasticsearch-rest/src/test/java/org/apache/camel/component/elasticsearch/ElasticsearchBaseTest.java, parent/pom.xml, test-infra/camel-test-infra-elasticsearch/pom.xml, test-infra/camel-test-infra-elasticsearch/src/test/java/org/apache/camel/test/infra/elasticsearch/services/ElasticSearchLocalContainerService.java, test-infra/camel-test-infra-elasticsearch/src/test/java/org/apache/camel/test/infra/elasticsearch/services/ElasticSearchService.java, test-infra/camel-test-infra-elasticsearch/src/test/java/org/apache/camel/test/infra/elasticsearch/services/ElasticSearchServiceFactory.java, test-infra/camel-test-infra-elasticsearch/src/test/java/org/apache/camel/test/infra/elasticsearch/services/RemoteElasticSearchService.java
Also adjust the elasticsearch component tests to use the new infra
=> Moved the Elasticsearch test service infra-structure from CKC

components/camel-cassandraql/src/test/java/org/apache/camel/component/cassandra/BaseCassandraTest.java, test-infra/camel-test-infra-cassandra/src/test/java/org/apache/camel/test/infra/cassandra/services/CassandraLocalContainerService.java, test-infra/camel-test-infra-cassandra/src/test/java/org/apache/camel/test/infra/cassandra/services/CassandraService.java, test-infra/camel-test-infra-cassandra/src/test/java/org/apache/camel/test/infra/cassandra/services/RemoteCassandraService.java
=> (chore) cleanup the Cassandra test infra interfaces

parent/pom.xml, test-infra/camel-test-infra-couchbase/pom.xml, test-infra/camel-test-infra-couchbase/src/test/java/org/apache/camel/test/infra/couchbase/services/CouchbaseLocalContainerService.java, test-infra/camel-test-infra-couchbase/src/test/java/org/apache/camel/test/infra/couchbase/services/CouchbaseRemoteService.java, test-infra/camel-test-infra-couchbase/src/test/java/org/apache/camel/test/infra/couchbase/services/CouchbaseService.java, test-infra/camel-test-infra-couchbase/src/test/java/org/apache/camel/test/infra/couchbase/services/CouchbaseServiceFactory.java, test-infra/pom.xml
Move the Couchbase test infra from Camel Kafka Connector so it can be reused
The tests are not migrated yet due to CAMEL-15789
=> Migrates the Couchbase test infrastructure

test-infra/camel-test-infra-elasticsearch/pom.xml
=> (chore) Remove unnecessary dependency from the ElasticSearch test infra

components/camel-mock/src/main/java/org/apache/camel/component/mock/AssertionClause.java
Initialize mock predicates before use.
=> CAMEL-15808: init predicates added to AssertionClause

tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/srcgen/Field.java, tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/srcgen/JavaClass.java
=> CAMEL-15817: Add comment support to srcgen Field

archetypes/camel-archetype-component/src/main/resources/archetype-resources/src/main/java/EventBusHelper.java, archetypes/camel-archetype-component/src/main/resources/archetype-resources/src/main/java/__name__Endpoint.java
=> CAMEL-15829 - fix typo "implementy" in Camel component maven archetype

archetypes/camel-archetype-component/src/main/resources/archetype-resources/src/main/java/EventBusHelper.java
=> CAMEL-15830 - fix order of specifier to respect Java Language

archetypes/camel-archetype-component/src/main/resources/archetype-resources/src/main/java/__name__Component.java, archetypes/camel-archetype-component/src/main/resources/archetype-resources/src/main/java/__name__Consumer.java
when using Camel Component Maven archetype
=> CAMEL-15831 - remove unused import in generated class

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/json-jsonb-dataformat.adoc, components/camel-jsonb/src/main/docs/json-jsonb-dataformat.adoc
fixes https://issues.apache.org/jira/browse/CAMEL-15819
=> CAMEL-15819 Camel-jsonb: Artifact 'johnzon-jsonb' is required with default settings.

test-infra/camel-test-infra-aws-v2/pom.xml, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/clients/AWSSDKClientUtils.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSContainer.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSLocalContainerService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSSNSLocalContainerService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSServiceFactory.java
=> Added service for AWS v2 SNS

test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSLocalContainerService.java
=> Ensures AWS v1 container initialization is handled via JUnit 5 lifecycle

components/camel-aws2-sns/pom.xml, components/camel-aws2-sns/src/test/java/org/apache/camel/component/aws2/sns/localstack/Aws2SNSBaseTest.java, components/camel-aws2-sns/src/test/java/org/apache/camel/component/aws2/sns/localstack/SnsTopicProducerLocalstackTest.java
=> Migrates the AWS v2 SNS tests to the new test-infra

components/camel-aws2-sns/src/main/java/org/apache/camel/component/aws2/sns/Sns2Component.java, components/camel-aws2-sns/src/main/java/org/apache/camel/component/aws2/sns/Sns2Endpoint.java, components/camel-aws2-sns/src/test/java/org/apache/camel/component/aws2/sns/localstack/SnsTopicProducerCustomConfigLocalstackTest.java, components/camel-aws2-sns/src/test/java/org/apache/camel/component/aws2/sns/localstack/TestSnsConfiguration.java
Includes a reproducer for CAMEL-15840
=> CAMEL-15840: avoid keeping duplicate copies of the configuration object in camel-aws2-sns

test-infra/camel-test-infra-azure-common/pom.xml, test-infra/camel-test-infra-azure-common/src/test/java/org/apache/camel/test/infra/azure/common/AzureConfigs.java, test-infra/camel-test-infra-azure-common/src/test/java/org/apache/camel/test/infra/azure/common/AzureCredentialsHolder.java, test-infra/camel-test-infra-azure-common/src/test/java/org/apache/camel/test/infra/azure/common/services/AzureService.java, test-infra/camel-test-infra-azure-common/src/test/java/org/apache/camel/test/infra/azure/common/services/AzureServices.java, test-infra/camel-test-infra-azure-common/src/test/java/org/apache/camel/test/infra/azure/common/services/AzureStorageService.java, test-infra/camel-test-infra-azure-common/src/test/java/org/apache/camel/test/infra/azure/common/services/AzuriteContainer.java, test-infra/camel-test-infra-azure-storage-blob/pom.xml, test-infra/camel-test-infra-azure-storage-blob/src/test/java/org/apache/camel/test/infra/azure/storage/blob/services/AzureStorageBlobLocalContainerService.java, test-infra/camel-test-infra-azure-storage-blob/src/test/java/org/apache/camel/test/infra/azure/storage/blob/services/AzureStorageBlobRemoteService.java, test-infra/camel-test-infra-azure-storage-blob/src/test/java/org/apache/camel/test/infra/azure/storage/blob/services/AzureStorageBlobServiceFactory.java, test-infra/camel-test-infra-azure-storage-queue/pom.xml, test-infra/camel-test-infra-azure-storage-queue/src/test/java/org/apache/camel/test/infra/azure/storage/queue/services/AzureStorageQueueLocalContainerService.java, test-infra/camel-test-infra-azure-storage-queue/src/test/java/org/apache/camel/test/infra/azure/storage/queue/services/AzureStorageQueueRemoteService.java, test-infra/camel-test-infra-azure-storage-queue/src/test/java/org/apache/camel/test/infra/azure/storage/queue/services/AzureStorageQueueServiceFactory.java, test-infra/pom.xml
Includes:
- service for Azure storage queue
- service for Azure storage blob
=> Added test infra for Azure services

components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/test/infra/services/QpidEmbeddedService.java, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSLocalContainerService.java, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSRemoteService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSLocalContainerService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSRemoteService.java, test-infra/camel-test-infra-azure-common/src/test/java/org/apache/camel/test/infra/azure/common/services/AzureStorageService.java, test-infra/camel-test-infra-azure-storage-blob/src/test/java/org/apache/camel/test/infra/azure/storage/blob/services/AzureStorageBlobLocalContainerService.java, test-infra/camel-test-infra-azure-storage-blob/src/test/java/org/apache/camel/test/infra/azure/storage/blob/services/AzureStorageBlobRemoteService.java, test-infra/camel-test-infra-azure-storage-queue/src/test/java/org/apache/camel/test/infra/azure/storage/queue/services/AzureStorageQueueLocalContainerService.java, test-infra/camel-test-infra-azure-storage-queue/src/test/java/org/apache/camel/test/infra/azure/storage/queue/services/AzureStorageQueueRemoteService.java, test-infra/camel-test-infra-cassandra/src/test/java/org/apache/camel/test/infra/cassandra/common/CassandraProperties.java, test-infra/camel-test-infra-cassandra/src/test/java/org/apache/camel/test/infra/cassandra/services/CassandraLocalContainerService.java, test-infra/camel-test-infra-cassandra/src/test/java/org/apache/camel/test/infra/cassandra/services/RemoteCassandraService.java, test-infra/camel-test-infra-common/src/test/java/org/apache/camel/test/infra/common/services/TestService.java, test-infra/camel-test-infra-couchbase/src/test/java/org/apache/camel/test/infra/couchbase/common/CouchbaseProperties.java, test-infra/camel-test-infra-couchbase/src/test/java/org/apache/camel/test/infra/couchbase/services/CouchbaseLocalContainerService.java, test-infra/camel-test-infra-couchbase/src/test/java/org/apache/camel/test/infra/couchbase/services/CouchbaseRemoteService.java, test-infra/camel-test-infra-elasticsearch/src/test/java/org/apache/camel/test/infra/elasticsearch/common/ElasticSearchProperties.java, test-infra/camel-test-infra-elasticsearch/src/test/java/org/apache/camel/test/infra/elasticsearch/services/ElasticSearchLocalContainerService.java, test-infra/camel-test-infra-elasticsearch/src/test/java/org/apache/camel/test/infra/elasticsearch/services/RemoteElasticSearchService.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/common/KafkaProperties.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/ContainerLocalKafkaService.java, test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/StrimziService.java, test-infra/camel-test-infra-mongodb/src/test/java/org/apache/camel/test/infra/mongodb/common/MongoDBProperties.java, test-infra/camel-test-infra-mongodb/src/test/java/org/apache/camel/test/infra/mongodb/services/MongoDBLocalContainerService.java, test-infra/camel-test-infra-mongodb/src/test/java/org/apache/camel/test/infra/mongodb/services/MongoDBRemoteService.java, test-infra/camel-test-infra-rabbitmq/src/test/java/org/apache/camel/test/infra/rabbitmq/services/RabbitMQLocalContainerService.java, test-infra/camel-test-infra-rabbitmq/src/test/java/org/apache/camel/test/infra/rabbitmq/services/RabbitMQRemoteService.java, test-infra/camel-test-infra-rabbitmq/src/test/java/org/apache/camel/test/infra/rabbitmq/services/RabbitMQService.java
=> Ensure that test-infra properties are registered and accessible outside of test

components/camel-cdi/pom.xml, components/camel-cdi/src/main/java/org/apache/camel/cdi/AnnotatedDelegate.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/AnnotatedMemberDelegate.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/AnnotatedMethodDelegate.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/AnnotatedTypeDelegate.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/BeanDelegate.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/CamelBeanInjectionTarget.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/CamelContextInjectionTarget.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/CamelContextProducer.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/CdiCamelConfigurationEvent.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/CdiCamelInjector.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/CdiEventConsumer.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/CdiEventEndpoint.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/CdiEventNotifier.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/CdiEventProducer.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/ForwardingObserverMethod.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/ListParameterizedType.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/SyntheticBean.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/SyntheticBeanAttributes.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/XmlCdiBeanFactory.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/XmlErrorHandlerFactoryBean.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/XmlFactoryBeanInjectionTarget.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/XmlProxyFactoryBean.java, components/camel-cdi/src/main/java/org/apache/camel/cdi/XmlServiceExporterBean.java
=> [CAMEL-15725] setting up basic OSGi-CDI metadata in the manifest

test-infra/camel-test-infra-artemis/pom.xml, test-infra/camel-test-infra-artemis/src/test/java/org/apache/camel/test/infra/artemis/services/ArtemisContainer.java, test-infra/camel-test-infra-artemis/src/test/resources/org/apache/camel/test/infra/artemis/services/Dockerfile, test-infra/camel-test-infra-dispatch-router/pom.xml, test-infra/camel-test-infra-dispatch-router/src/test/java/org/apache/camel/test/infra/dispatch/router/services/DispatchRouterContainer.java, test-infra/camel-test-infra-dispatch-router/src/test/resources/org/apache/camel/test/infra/dispatch/router/services/Dockerfile, test-infra/camel-test-infra-messaging-common/pom.xml, test-infra/camel-test-infra-messaging-common/src/test/java/org/apache/camel/test/infra/messaging/common/MessagingProperties.java, test-infra/camel-test-infra-messaging-common/src/test/java/org/apache/camel/test/infra/messaging/services/MessagingContainer.java, test-infra/camel-test-infra-messaging-common/src/test/java/org/apache/camel/test/infra/messaging/services/MessagingLocalContainerService.java, test-infra/camel-test-infra-messaging-common/src/test/java/org/apache/camel/test/infra/messaging/services/MessagingRemoteService.java, test-infra/camel-test-infra-messaging-common/src/test/java/org/apache/camel/test/infra/messaging/services/MessagingService.java, test-infra/camel-test-infra-messaging-common/src/test/java/org/apache/camel/test/infra/messaging/services/MessagingServiceBuilder.java, test-infra/pom.xml
Includes:
- test infra based on Apache Artemis
- test infra based on Qpid
Also, it's pluggable. Can work with other containers (such as the RabbitMQ one already available in the project)
=> Add test infra from message brokers

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java
=> When "its" means "it is" it MUST have an apostrophe ("it's").

components/camel-hdfs/pom.xml, components/camel-hdfs/src/test/java/org/apache/camel/component/hdfs/integration/HdfsAppendTest.java, test-infra/camel-test-infra-hdfs/pom.xml, test-infra/camel-test-infra-hdfs/src/test/java/org/apache/camel/test/infra/hdfs/v2/common/HDFSProperties.java, test-infra/camel-test-infra-hdfs/src/test/java/org/apache/camel/test/infra/hdfs/v2/services/ContainerLocalHDFSService.java, test-infra/camel-test-infra-hdfs/src/test/java/org/apache/camel/test/infra/hdfs/v2/services/DataNodeContainer.java, test-infra/camel-test-infra-hdfs/src/test/java/org/apache/camel/test/infra/hdfs/v2/services/HDFSPorts.java, test-infra/camel-test-infra-hdfs/src/test/java/org/apache/camel/test/infra/hdfs/v2/services/HDFSService.java, test-infra/camel-test-infra-hdfs/src/test/java/org/apache/camel/test/infra/hdfs/v2/services/HDFSServiceFactory.java, test-infra/camel-test-infra-hdfs/src/test/java/org/apache/camel/test/infra/hdfs/v2/services/HadoopBaseContainer.java, test-infra/camel-test-infra-hdfs/src/test/java/org/apache/camel/test/infra/hdfs/v2/services/NameNodeContainer.java, test-infra/camel-test-infra-hdfs/src/test/java/org/apache/camel/test/infra/hdfs/v2/services/RemoteHDFSService.java, test-infra/camel-test-infra-hdfs/src/test/resources/org/apache/camel/test/infra/hdfs/v2/services/Dockerfile, test-infra/camel-test-infra-hdfs/src/test/resources/org/apache/camel/test/infra/hdfs/v2/services/core-site.xml, test-infra/camel-test-infra-hdfs/src/test/resources/org/apache/camel/test/infra/hdfs/v2/services/hdfs-site.xml, test-infra/camel-test-infra-hdfs/src/test/resources/org/apache/camel/test/infra/hdfs/v2/services/run-datanode.sh, test-infra/camel-test-infra-hdfs/src/test/resources/org/apache/camel/test/infra/hdfs/v2/services/run-namenode.sh, test-infra/pom.xml
Also converted one test case to the new infra
=> Added test infra services for HDFS v2

components/camel-salesforce/camel-salesforce-maven-plugin/README.md, components/camel-salesforce/camel-salesforce-maven-plugin/src/main/java/org/apache/camel/maven/GenerateMojo.java, components/camel-salesforce/camel-salesforce-maven-plugin/src/main/resources/sobject-pojo.vm
In salesforce, if a relationship field has the same field name as the
child relationship name, the generated DTOs end up with invalid Java
code. This commit allows the user to specify a child relationship name
suffix in order to disambiguate the field name and child relationship
name.
=> CAMEL-14480: camel-salesforce: Conflicting relationship names.

components/camel-salesforce/camel-salesforce-maven-plugin/src/main/java/org/apache/camel/maven/GenerateMojo.java, components/camel-salesforce/camel-salesforce-maven-plugin/src/main/resources/sobject-pojo.vm
Escape strings generated from salesforce field labels.
=> CAMEL-15855: camel-salesforce Escape field labels.

docs/user-manual/modules/ROOT/pages/servlet-tomcat-example.adoc
Trivial change that fixes broken links. The link was broken when examples were moved out of Camel Distribution.
=> Fix broken link at Servlet Tomcat Examples

components/camel-pgevent/pom.xml, components/camel-pgevent/src/test/java/org/apache/camel/pgevent/PgEventTestSupport.java, parent/pom.xml, test-infra/camel-test-infra-jdbc/pom.xml, test-infra/camel-test-infra-jdbc/src/test/java/org/apache/camel/test/infra/jdbc/common/JDBCProperties.java, test-infra/camel-test-infra-jdbc/src/test/java/org/apache/camel/test/infra/jdbc/services/JDBCLocalContainerService.java, test-infra/camel-test-infra-jdbc/src/test/java/org/apache/camel/test/infra/jdbc/services/JDBCRemoteService.java, test-infra/camel-test-infra-jdbc/src/test/java/org/apache/camel/test/infra/jdbc/services/JDBCService.java, test-infra/camel-test-infra-jdbc/src/test/java/org/apache/camel/test/infra/jdbc/services/JDBCServiceBuilder.java, test-infra/pom.xml
Also converted the camel-pgevent test cases to use the new infra
=> Added test-infra services for JDBC

components/camel-arangodb/pom.xml, components/camel-arangodb/src/test/java/org/apache/camel/component/arangodb/BaseArangoDbTest.java, test-infra/camel-test-infra-arangodb/pom.xml, test-infra/camel-test-infra-arangodb/src/test/java/org/apache/camel/test/infra/arangodb/common/ArangoDBProperties.java, test-infra/camel-test-infra-arangodb/src/test/java/org/apache/camel/test/infra/arangodb/services/ArangoDBLocalContainerService.java, test-infra/camel-test-infra-arangodb/src/test/java/org/apache/camel/test/infra/arangodb/services/ArangoDBRemoteService.java, test-infra/camel-test-infra-arangodb/src/test/java/org/apache/camel/test/infra/arangodb/services/ArangoDBService.java, test-infra/camel-test-infra-arangodb/src/test/java/org/apache/camel/test/infra/arangodb/services/ArangoDBServiceFactory.java, test-infra/camel-test-infra-arangodb/src/test/java/org/apache/camel/test/infra/arangodb/services/ArangoDbContainer.java, test-infra/pom.xml
Also migrates the camel-arangodb tests to the shared test infra
=> Adds test infra for ArangoDB

components/camel-aws-sqs/src/test/java/org/apache/camel/component/aws/sqs/integration/SqsComponentIntegrationTest.java, components/camel-aws-sqs/src/test/java/org/apache/camel/component/aws/sqs/integration/SqsConsumerMessageIntegrationTest.java, components/camel-aws-sqs/src/test/java/org/apache/camel/component/aws/sqs/integration/SqsProducerBatchSendFifoIntegrationTest.java, components/camel-aws-sqs/src/test/java/org/apache/camel/component/aws/sqs/integration/SqsProducerBatchSendIntegrationTest.java, components/camel-aws-sqs/src/test/java/org/apache/camel/component/aws/sqs/integration/SqsProducerDeleteMessageIntegrationTest.java, components/camel-aws2-sns/src/test/java/org/apache/camel/component/aws2/sns/localstack/Aws2SNSBaseTest.java, components/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/integration/SqsComponentIntegrationTest.java, components/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/integration/SqsConsumerMessageIntegrationTest.java, components/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/integration/SqsProducerBatchSendFifoIntegrationTest.java, components/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/integration/SqsProducerBatchSendIntegrationTest.java, components/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/integration/SqsProducerDeleteMessageIntegrationTest.java, components/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/localstack/Aws2SQSBaseTest.java, test-infra/camel-test-infra-aws-common/src/test/java/org/apache/camel/test/infra/aws/common/services/AWSService.java, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSKinesisLocalContainerService.java, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSLocalContainerService.java, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSRemoteService.java, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSS3LocalContainerService.java, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSSNSLocalContainerService.java, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSSQSLocalContainerService.java, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSServiceFactory.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSKinesisLocalContainerService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSLocalContainerService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSRemoteService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSS3LocalContainerService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSSNSLocalContainerService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSSQSLocalContainerService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSServiceFactory.java
=> Decouple AWS2 clients from the test-infra services

components/camel-aws2-cw/pom.xml, components/camel-aws2-cw/src/test/java/org/apache/camel/component/aws2/cw/localstack/Aws2CwBaseTest.java, test-infra/camel-test-infra-aws-v2/pom.xml, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/clients/AWSSDKClientUtils.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSCloudWatchLocalContainerService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSServiceFactory.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/Service.java
Also migrates the camel-aws2-cw tests to the new test infra
=> Added test infra for AWS v2 Cloud Watch

components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/ApprovalIntegrationTest.java, components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/CompositeApiBatchIntegrationTest.java, components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/RestApiIntegrationTest.java, components/camel-salesforce/it/resources/salesforce/profiles/System Administrator With Hard Delete.profile
Some integration tests were still broken from the JUnit 5 conversion.
=> camel-salesforce: Fix integration tests.

components/camel-apns/src/test/java/org/apache/camel/component/apns/ApnsConsumerIdleMessageTest.java, components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/AS2MessageTest.java, components/camel-as2/camel-as2-component/src/test/java/org/apache/camel/component/as2/AS2ServerManagerIntegrationTest.java, components/camel-asn1/src/test/java/org/apache/camel/dataformat/asn1/ASN1DataFormatWithStreamIteratorByteArrayTest.java, components/camel-asn1/src/test/java/org/apache/camel/dataformat/asn1/ASN1DataFormatWithStreamIteratorClassTest.java, components/camel-asn1/src/test/java/org/apache/camel/dataformat/asn1/ASN1DataFormatWithStreamTest.java, components/camel-asn1/src/test/java/org/apache/camel/dataformat/asn1/SpringASN1DataFormatRouteTest.java, components/camel-atmosphere-websocket/src/test/java/org/apache/camel/component/atmosphere/websocket/WebsocketRouteWithInitParamTest.java, components/camel-atom/src/test/java/org/apache/camel/component/atom/AtomPollingConsumerIdleMessageTest.java, components/camel-aws-s3/src/test/java/org/apache/camel/component/aws/s3/S3ConsumerCronTest.java, components/camel-aws-s3/src/test/java/org/apache/camel/component/aws/s3/S3ConsumerIdleMessageTest.java, components/camel-aws-sqs/src/test/java/org/apache/camel/component/aws/sqs/SqsConsumerIdleMessageTest.java, components/camel-aws-sqs/src/test/java/org/apache/camel/component/aws/sqs/SqsDoesNotExtendMessageVisibilityTest.java, components/camel-barcode/src/test/java/org/apache/camel/dataformat/barcode/BarcodeDataFormatTest.java, components/camel-bindy/src/test/java/org/apache/camel/dataformat/bindy/fix/BindySimpleKeyValuePairUnicodeNextLineTest.java, components/camel-bindy/src/test/java/org/apache/camel/dataformat/bindy/fixed/headerfooter/BindySimpleFixedLengthHeaderFooterTest.java
Affected components: camel-apns, camel-as2, camel-asn1,
camel-atmosphere-websocket, camel-atom, camel-aws-s3, camel-aws-sqs,
camel-barcode, camel-bindy
=> (chores) Simplified assertions

test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSKinesisLocalContainerService.java, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSLocalContainerService.java, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSS3LocalContainerService.java, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSSNSLocalContainerService.java, test-infra/camel-test-infra-aws-v1/src/test/java/org/apache/camel/test/infra/aws/services/AWSSQSLocalContainerService.java
=> Use the edge port on the AWS v1 test infra to help fix test errors on the Camel Kafka Connector

components/camel-aws2-ec2/pom.xml, components/camel-aws2-ec2/src/test/java/org/apache/camel/component/aws2/ec2/localstack/Aws2EC2BaseTest.java, test-infra/camel-test-infra-aws-v2/pom.xml, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/clients/AWSSDKClientUtils.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSEC2LocalContainerService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSServiceFactory.java
=> Migrates the camel-aws2-ec2 tests to the shared test infra

components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/FhirTransactionIT.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/FtpConsumerWithCharsetTest.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/FtpPollingConsumerIdleMessageTest.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/FtpProducerFileWithCharsetTest.java, components/camel-google-calendar/src/test/java/org/apache/camel/component/google/calendar/CalendarCalendarListIntegrationTest.java, components/camel-google-calendar/src/test/java/org/apache/camel/component/google/calendar/CalendarCalendarsIntegrationTest.java, components/camel-google-drive/src/test/java/org/apache/camel/component/google/drive/DriveFilesIntegrationTest.java, components/camel-google-mail/src/test/java/org/apache/camel/component/google/mail/GmailUsersLabelsIntegrationTest.java, components/camel-google-pubsub/src/test/java/org/apache/camel/component/google/pubsub/integration/BodyTypesTest.java
Components: camel-fhir, camel-ftp, camel-google-calendar,
camel-google-drive, camel-google-mail, camel-google-pubsub
=> Simplified assertions

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/dto/SearchResult2.java, components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/processor/JsonRestProcessor.java, components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/processor/XmlRestProcessor.java
CAMEL-15866: salesforce: Support new SOSL search result
=> CAMEL-15866: salesforce: Support new SOSL search result

components/camel-http-common/src/main/java/org/apache/camel/http/common/CamelServlet.java, components/camel-servlet/src/main/docs/servlet-component.adoc, components/camel-servlet/src/test/java/org/apache/camel/component/servlet/CustomThreadsServletAsyncTest.java, components/camel-servlet/src/test/java/org/apache/camel/component/servlet/ExposedServletEndpointURIToJMXTest.java, components/camel-servlet/src/test/resources/org/apache/camel/component/servlet/example-camelContext-pool.xml
=> [CAMEL-11731] ensure camel-servlet can be used in really async mode

components/camel-aws2-eventbridge/pom.xml, components/camel-aws2-eventbridge/src/test/java/org/apache/camel/component/aws2/eventbridge/localstack/Aws2EventbridgeBaseTest.java, test-infra/camel-test-infra-aws-v2/pom.xml, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/clients/AWSSDKClientUtils.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSEventBridgeLocalContainerService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSServiceFactory.java
=> Migrates the camel-aws2-eventbridge tests to the shared test infra

components/camel-aws2-iam/pom.xml, components/camel-aws2-iam/src/test/java/org/apache/camel/component/aws2/iam/localstack/Aws2IAMBaseTest.java, test-infra/camel-test-infra-aws-v2/pom.xml, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/clients/AWSSDKClientUtils.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSIAMLocalContainerService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSServiceFactory.java
=> Migrates the camel-aws2-iam tests to the shared test infra

components/camel-aws2-kms/pom.xml, components/camel-aws2-kms/src/test/java/org/apache/camel/component/aws2/kms/localstack/Aws2KmsBaseTest.java, test-infra/camel-test-infra-aws-v2/pom.xml, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/clients/AWSSDKClientUtils.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSKMSLocalContainerService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSServiceFactory.java
=> Migrates the camel-aws2-kms tests to the shared test infra

components/camel-disruptor/src/test/java/org/apache/camel/component/disruptor/DirectRequestReplyAndDisruptorInOnlyTest.java, components/camel-disruptor/src/test/java/org/apache/camel/component/disruptor/DisruptorUnitOfWorkTest.java, components/camel-disruptor/src/test/java/org/apache/camel/component/disruptor/DisruptorWaitForTaskAsPropertyTest.java, components/camel-disruptor/src/test/java/org/apache/camel/component/disruptor/DisruptorWaitForTaskIfReplyExpectedTest.java, components/camel-disruptor/src/test/java/org/apache/camel/component/disruptor/DisruptorWaitForTaskNeverTest.java, components/camel-disruptor/src/test/java/org/apache/camel/component/disruptor/vm/DisruptorVmWaitForTaskIfReplyExpectedTest.java, components/camel-disruptor/src/test/java/org/apache/camel/component/disruptor/vm/DisruptorVmWaitForTaskNewerTest.java
=> camel-disruptor: fixed deprecations in test code

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/BaseEmbeddedKafkaTest.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaProducerFullTest.java, components/camel-kafka/src/test/java/org/apache/kafka/clients/consumer/KafkaConsumerTest.java
=> camel-kafka: fixed deprecations in test code

components/camel-ehcache/src/test/java/org/apache/camel/component/ehcache/EhcacheProducerTest.java
=> camel-ehcache: fixed deprecations in test code

components/camel-aws2-lambda/pom.xml, components/camel-aws2-lambda/src/test/java/org/apache/camel/component/aws2/lambda/localstack/Aws2LambdaBaseTest.java, test-infra/camel-test-infra-aws-v2/pom.xml, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/clients/AWSSDKClientUtils.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSLambdaLocalContainerService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSServiceFactory.java
=> Migrates the camel-aws2-lambda tests to the shared test infra

test-infra/camel-test-infra-artemis/pom.xml, test-infra/camel-test-infra-aws-common/pom.xml, test-infra/camel-test-infra-aws-v1/pom.xml, test-infra/camel-test-infra-aws-v2/pom.xml, test-infra/camel-test-infra-azure-common/pom.xml, test-infra/camel-test-infra-azure-storage-blob/pom.xml, test-infra/camel-test-infra-azure-storage-queue/pom.xml, test-infra/camel-test-infra-cassandra/pom.xml, test-infra/camel-test-infra-common/pom.xml, test-infra/camel-test-infra-couchbase/pom.xml, test-infra/camel-test-infra-dispatch-router/pom.xml, test-infra/camel-test-infra-elasticsearch/pom.xml, test-infra/camel-test-infra-hdfs/pom.xml, test-infra/camel-test-infra-jdbc/pom.xml, test-infra/camel-test-infra-kafka/pom.xml, test-infra/camel-test-infra-messaging-common/pom.xml, test-infra/camel-test-infra-mongodb/pom.xml, test-infra/camel-test-infra-parent/pom.xml, test-infra/camel-test-infra-rabbitmq/pom.xml, test-infra/pom.xml
=> Fixed incorrect formatting of license header in test-infra pom files

components/camel-aws2-s3/pom.xml, components/camel-aws2-s3/src/test/java/org/apache/camel/component/aws2/s3/localstack/Aws2S3BaseTest.java
=> Migrates the camel-aws2-s3 tests to the shared test infra

components/camel-atom/src/test/java/org/apache/camel/component/atom/AtomProducerTest.java, components/camel-azure/src/test/java/org/apache/camel/component/azure/blob/BlobServiceUtilTest.java, components/camel-azure/src/test/java/org/apache/camel/component/azure/queue/QueueServiceUtilTest.java, components/camel-bindy/src/test/java/org/apache/camel/dataformat/bindy/fixed/marshall/simple/BindySimpleFixedLengthMarshallWithNoClipTest.java, components/camel-braintree/src/test/java/org/apache/camel/component/braintree/CustomerGatewayIntegrationTest.java, components/camel-cxf-transport/src/test/java/org/apache/camel/component/cxf/transport/CamelDestinationTest.java, components/camel-cxf/src/test/java/org/apache/camel/component/cxf/AbstractCXFGreeterRouterTest.java, components/camel-cxf/src/test/java/org/apache/camel/component/cxf/util/CxfEndpointUtilsTest.java, components/camel-disruptor/src/test/java/org/apache/camel/component/disruptor/DisruptorConcurrentConsumersNPEIssueTest.java, components/camel-dozer/src/test/java/org/apache/camel/component/dozer/CustomMapperTest.java, components/camel-elytron/src/test/java/org/apache/camel/component/elytron/ElytronBearerTokenTest.java
Avoids false positives when the expected exception is thrown by a
different method other than the one under test.
Components: camel-atom, camel-azure, camel-bindy, camel-braintree,
camel-cxf-transport, camel-cxf, camel-disruptor, camel-dozer,
camel-elytron
=> (chores) Simplified exception testing

components/camel-aws2-sts/pom.xml, components/camel-aws2-sts/src/test/java/org/apache/camel/component/aws2/sts/localstack/Aws2StsBaseTest.java, test-infra/camel-test-infra-aws-v2/pom.xml, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/clients/AWSSDKClientUtils.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSSTSLocalContainerService.java, test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSServiceFactory.java
=> Migrates the camel-aws2-sts tests to the shared test infra

components/camel-azure-storage-blob/pom.xml, components/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BaseIT.java, test-infra/camel-test-infra-azure-common/src/test/java/org/apache/camel/test/infra/azure/common/services/AzureStorageService.java, test-infra/camel-test-infra-azure-storage-blob/pom.xml, test-infra/camel-test-infra-azure-storage-blob/src/test/java/org/apache/camel/test/infra/azure/storage/blob/clients/AzureStorageBlobClientUtils.java
=> Migrates the camel-azure-storage-blob tests to the shared test infra

components/camel-jaxb/src/test/java/org/apache/camel/converter/jaxb/JaxbDataFormatSchemaValidationSpringTest.java, components/camel-jaxb/src/test/java/org/apache/camel/converter/jaxb/JaxbDataFormatSchemaValidationTest.java, components/camel-jaxb/src/test/java/org/apache/camel/converter/jaxb/JaxbDataFormatSchemaValidationWithObjectFactoryTest.java, components/camel-jaxb/src/test/java/org/apache/camel/example/JAXBConvertTest.java, components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/MongoDbReadPreferenceOptionTest.java, components/camel-servicenow/camel-servicenow-component/src/test/java/org/apache/camel/component/servicenow/ServiceNowTableTest.java, components/camel-snakeyaml/src/test/java/org/apache/camel/component/snakeyaml/SnakeYAMLDoSTest.java
Avoids false positives when the expected exception is thrown by a different method other than the one under test.
Components: camel-jaxb, camel-mongodb, camel-servicenow, camel-snakeyaml
=> Simplified exception testing

components/camel-graphql/src/main/docs/graphql-component.adoc, components/camel-graphql/src/main/java/org/apache/camel/component/graphql/GraphqlEndpoint.java
=> [CAMEL-15872] JWT Authorization Type Configuration Option to GraphQL Component

components/camel-salesforce/camel-salesforce-maven-plugin/src/main/java/org/apache/camel/maven/GenerateMojo.java, components/camel-salesforce/camel-salesforce-maven-plugin/src/main/resources/sobject-pojo.vm, components/camel-salesforce/camel-salesforce-maven-plugin/src/test/resources/generated/With_Reference__c.java
Include all related objects in generated DTOs
=> CAMEL-15884: camel-salesforce: DTO generation fix

components/camel-consul/pom.xml, components/camel-consul/src/test/java/org/apache/camel/component/consul/ConsulHealthTest.java, components/camel-consul/src/test/java/org/apache/camel/component/consul/ConsulRegistryTest.java, components/camel-consul/src/test/java/org/apache/camel/component/consul/ConsulTestSupport.java, components/camel-consul/src/test/java/org/apache/camel/component/consul/cloud/ConsulDefaultServiceCallRouteTest.java, components/camel-consul/src/test/java/org/apache/camel/component/consul/cloud/ConsulRibbonServiceCallRouteTest.java, components/camel-consul/src/test/java/org/apache/camel/component/consul/cloud/ConsulServiceCallWithRegistrationTest.java, components/camel-consul/src/test/java/org/apache/camel/component/consul/cloud/ConsulServiceDiscoveryTest.java, components/camel-consul/src/test/java/org/apache/camel/component/consul/cloud/ConsulServiceRegistrationTestBase.java, components/camel-consul/src/test/java/org/apache/camel/component/consul/cloud/ConsulServiceRegistryTest.java, components/camel-consul/src/test/java/org/apache/camel/component/consul/cloud/SpringConsulServiceCallRouteTest.java, components/camel-consul/src/test/java/org/apache/camel/component/consul/cluster/ConsulClusteredRoutePolicyFactoryTest.java, components/camel-consul/src/test/java/org/apache/camel/component/consul/cluster/ConsulClusteredRoutePolicyTest.java, components/camel-consul/src/test/java/org/apache/camel/component/consul/cluster/ConsulMasterTest.java, components/camel-consul/src/test/resources/org/apache/camel/component/consul/cloud/SpringConsulDefaultServiceCallRouteTest.xml, components/camel-consul/src/test/resources/org/apache/camel/component/consul/cloud/SpringConsulExpressionServiceCallRouteTest.xml, components/camel-consul/src/test/resources/org/apache/camel/component/consul/cloud/SpringConsulRibbonServiceCallRouteTest.xml, test-infra/camel-test-infra-consul/pom.xml, test-infra/camel-test-infra-consul/src/test/java/org/apache/camel/test/infra/consul/common/ConsulProperties.java, test-infra/camel-test-infra-consul/src/test/java/org/apache/camel/test/infra/consul/services/ConsulLocalContainerService.java, test-infra/camel-test-infra-consul/src/test/java/org/apache/camel/test/infra/consul/services/ConsulRemoteService.java, test-infra/camel-test-infra-consul/src/test/java/org/apache/camel/test/infra/consul/services/ConsulService.java, test-infra/camel-test-infra-consul/src/test/java/org/apache/camel/test/infra/consul/services/ConsulServiceFactory.java, test-infra/pom.xml
=> Migrates consul component to the new test-infra

components/camel-google-pubsub/src/test/java/org/apache/camel/component/google/pubsub/integration/AckModeNoneTest.java, components/camel-netty/src/test/java/org/apache/camel/component/netty/NettyUdpConnectedSendTest.java
Components: camel-google-pubsub, camel-netty
=> Fixed usage of deprecated junit ordering classes

components/camel-google-pubsub/pom.xml, components/camel-google-pubsub/src/test/java/org/apache/camel/component/google/pubsub/PubsubTestSupport.java, components/camel-google-pubsub/src/test/java/org/apache/camel/component/google/pubsub/integration/BodyTypesTest.java, components/camel-google-pubsub/src/test/java/org/apache/camel/component/google/pubsub/integration/GroupedExchangeRoundtripTest.java, test-infra/camel-test-infra-google-pubsub/pom.xml, test-infra/camel-test-infra-google-pubsub/src/test/java/org/apache/camel/test/infra/google/pubsub/common/GooglePubSubProperties.java, test-infra/camel-test-infra-google-pubsub/src/test/java/org/apache/camel/test/infra/google/pubsub/services/GooglePubSubLocalContainerService.java, test-infra/camel-test-infra-google-pubsub/src/test/java/org/apache/camel/test/infra/google/pubsub/services/GooglePubSubRemoteService.java, test-infra/camel-test-infra-google-pubsub/src/test/java/org/apache/camel/test/infra/google/pubsub/services/GooglePubSubService.java, test-infra/camel-test-infra-google-pubsub/src/test/java/org/apache/camel/test/infra/google/pubsub/services/GooglePubSubServiceFactory.java, test-infra/pom.xml
=> Migrates google-pubsub component to the new test-infra

camel-dependencies/pom.xml, catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/google-bigquery-component.adoc, catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/google-bigquery-sql-component.adoc, components/camel-google-bigquery/pom.xml, components/camel-google-bigquery/src/main/docs/google-bigquery-component.adoc, components/camel-google-bigquery/src/main/docs/google-bigquery-sql-component.adoc, components/camel-google-bigquery/src/main/java/org/apache/camel/component/google/bigquery/GoogleBigQueryConnectionFactory.java, components/camel-google-bigquery/src/main/java/org/apache/camel/component/google/bigquery/GoogleBigQueryConstants.java, components/camel-google-bigquery/src/main/java/org/apache/camel/component/google/bigquery/GoogleBigQueryEndpoint.java, components/camel-google-bigquery/src/main/java/org/apache/camel/component/google/bigquery/GoogleBigQueryProducer.java, components/camel-google-bigquery/src/main/java/org/apache/camel/component/google/bigquery/sql/GoogleBigQuerySQLEndpoint.java, components/camel-google-bigquery/src/main/java/org/apache/camel/component/google/bigquery/sql/GoogleBigQuerySQLProducer.java, components/camel-google-bigquery/src/test/java/org/apache/camel/component/google/bigquery/integration/BigQueryTestSupport.java, components/camel-google-bigquery/src/test/java/org/apache/camel/component/google/bigquery/unit/BaseBigQueryTest.java, components/camel-google-bigquery/src/test/java/org/apache/camel/component/google/bigquery/unit/GoogleBigQueryProducerTest.java, components/camel-google-bigquery/src/test/java/org/apache/camel/component/google/bigquery/unit/sql/GoogleBigQuerySQLComponentTest.java, components/camel-google-bigquery/src/test/java/org/apache/camel/component/google/bigquery/unit/sql/GoogleBigQuerySQLProducerBaseTest.java, components/camel-google-bigquery/src/test/java/org/apache/camel/component/google/bigquery/unit/sql/GoogleBigQuerySQLProducerWithParamersTest.java, components/camel-google-bigquery/src/test/java/org/apache/camel/component/google/bigquery/unit/sql/GoogleBigQuerySQLProducerWithPatternTest.java, components/camel-google-bigquery/src/test/resources/schema/simple-table.json, docs/components/modules/ROOT/pages/google-bigquery-component.adoc, docs/components/modules/ROOT/pages/google-bigquery-sql-component.adoc, docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_7.adoc, parent/pom.xml
=> CAMEL-15873: Upgrade google-cloud-bigquery dependencies

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/utils/UrlUtils.java
Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>
=> Fix some style issues

camel-dependencies/pom.xml, components/camel-google-pubsub/pom.xml, parent/pom.xml
=> CAMEL-15896: Upgrade google-cloud-pubsub to 1.109.0

components/camel-opentelemetry/pom.xml, components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/AttributeProcessor.java, components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/OpenTelemetrySpanAdapter.java, components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/OpenTelemetryTracer.java, components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/propagators/OpenTelemetryGetter.java, components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/CamelOpenTelemetryTestSupport.java, components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/SpanTestData.java, components/camel-tracing/src/main/java/org/apache/camel/tracing/ExtractAdapter.java, components/camel-tracing/src/main/java/org/apache/camel/tracing/propagation/CamelHeadersExtractAdapter.java, components/camel-tracing/src/main/java/org/apache/camel/tracing/propagation/CamelMessagingHeadersExtractAdapter.java, parent/pom.xml
Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>
This PR is about updating opentelemetry to the most recent version (at this time is 0.11)
=> [CAMEL-15894] - Update to opentelemetry 0.11

components/camel-etcd/pom.xml, components/camel-etcd/src/test/java/org/apache/camel/component/etcd/cloud/EtcdServiceCallRouteTest.java, components/camel-etcd/src/test/java/org/apache/camel/component/etcd/cloud/EtcdServiceDiscoveryTest.java, components/camel-etcd/src/test/java/org/apache/camel/component/etcd/support/EtcdTestSupport.java, components/camel-etcd/src/test/java/org/apache/camel/component/etcd/support/SpringEtcdTestSupport.java, components/camel-etcd/src/test/resources/org/apache/camel/component/etcd/cloud/SpringEtcdServiceCallDefaultRouteTest.xml, components/camel-etcd/src/test/resources/org/apache/camel/component/etcd/cloud/SpringEtcdServiceCallRouteTest.xml, test-infra/camel-test-infra-etcd/pom.xml, test-infra/camel-test-infra-etcd/src/test/java/org/apache/camel/test/infra/etcd/common/EtcDProperties.java, test-infra/camel-test-infra-etcd/src/test/java/org/apache/camel/test/infra/etcd/services/EtcDLocalContainerService.java, test-infra/camel-test-infra-etcd/src/test/java/org/apache/camel/test/infra/etcd/services/EtcDRemoteService.java, test-infra/camel-test-infra-etcd/src/test/java/org/apache/camel/test/infra/etcd/services/EtcDService.java, test-infra/camel-test-infra-etcd/src/test/java/org/apache/camel/test/infra/etcd/services/EtcDServiceFactory.java, test-infra/pom.xml
=> Migrates etcd component to the new test-infra

components/camel-hbase/pom.xml, components/camel-hbase/src/test/java/org/apache/camel/component/hbase/CamelHBaseTestSupport.java, components/camel-hbase/src/test/java/org/apache/camel/component/hbase/processor/idempotent/HBaseIdempotentRepositoryTest.java, test-infra/camel-test-infra-hbase/pom.xml, test-infra/camel-test-infra-hbase/src/test/java/org/apache/camel/test/infra/hbase/common/HBaseProperties.java, test-infra/camel-test-infra-hbase/src/test/java/org/apache/camel/test/infra/hbase/services/HBaseContainer.java, test-infra/camel-test-infra-hbase/src/test/java/org/apache/camel/test/infra/hbase/services/HBaseLocalContainerService.java, test-infra/camel-test-infra-hbase/src/test/java/org/apache/camel/test/infra/hbase/services/HBaseService.java, test-infra/camel-test-infra-hbase/src/test/java/org/apache/camel/test/infra/hbase/services/HBaseServiceFactory.java, test-infra/pom.xml
=> Migrates camel-hbase to the new test infra

components/camel-salesforce/camel-salesforce-maven-plugin/README.md, components/camel-salesforce/camel-salesforce-maven-plugin/src/main/java/org/apache/camel/maven/GenerateMojo.java, components/camel-salesforce/camel-salesforce-maven-plugin/src/main/resources/sobject-picklist.vm, components/camel-salesforce/camel-salesforce-maven-plugin/src/test/java/org/apache/camel/maven/CamelSalesforceMojoIntegrationTest.java, components/camel-salesforce/camel-salesforce-maven-plugin/src/test/java/org/apache/camel/maven/CamelSalesforceMojoOutputTest.java, components/camel-salesforce/camel-salesforce-maven-plugin/src/test/resources/case.json, components/camel-salesforce/camel-salesforce-maven-plugin/src/test/resources/generated/Case.java, components/camel-salesforce/camel-salesforce-maven-plugin/src/test/resources/generated/Case_PickListAccentMarkEnum.java, components/camel-salesforce/camel-salesforce-maven-plugin/src/test/resources/generated/Case_PickListSlashEnum.java, components/camel-salesforce/camel-salesforce-maven-plugin/src/test/resources/generated/Case_PickListValueOverrideEnum.java
Ability to override picklist enum value generation.
=> CAMEL-15856: camel-salesforce custom enum values

components/camel-infinispan/pom.xml, components/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/testcontainers/InfinispanTestContainerSupport.java, components/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/testcontainers/InfinispanTestContainersConsumerTest.java, components/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/testcontainers/InfinispanTestContainersContainsKeyProducerTest.java, components/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/testcontainers/InfinispanTestContainersGetOrDefaultProducerTest.java, components/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/testcontainers/InfinispanTestContainersIdempotentRepositoryTest.java, components/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/testcontainers/InfinispanTestContainersProducerTest.java, components/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/testcontainers/InfinispanTestContainersPutIfAbsentProducerTest.java, components/camel-infinispan/src/test/java/org/apache/camel/component/infinispan/testcontainers/InfinispanTestContainersRemoveProducerTest.java, test-infra/camel-test-infra-infinispan/pom.xml, test-infra/camel-test-infra-infinispan/src/test/java/org/apache/camel/test/infra/infinispan/common/InfinispanProperties.java, test-infra/camel-test-infra-infinispan/src/test/java/org/apache/camel/test/infra/infinispan/services/InfinispanLocalContainerService.java, test-infra/camel-test-infra-infinispan/src/test/java/org/apache/camel/test/infra/infinispan/services/InfinispanRemoteService.java, test-infra/camel-test-infra-infinispan/src/test/java/org/apache/camel/test/infra/infinispan/services/InfinispanService.java, test-infra/camel-test-infra-infinispan/src/test/java/org/apache/camel/test/infra/infinispan/services/InfinispanServiceFactory.java, test-infra/pom.xml
=> Migrates camel-infinispan to the new test infra

camel-dependencies/pom.xml, catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/avro-component.adoc, components/camel-avro-rpc/src/main/docs/avro-component.adoc, components/camel-avro-rpc/src/test/java/org/apache/camel/component/avro/AvroConsumerTestSupport.java, components/camel-avro-rpc/src/test/java/org/apache/camel/component/avro/AvroNettyConsumerTest.java, components/camel-avro-rpc/src/test/java/org/apache/camel/component/avro/AvroNettyProducerTest.java, components/camel-avro-rpc/src/test/java/org/apache/camel/component/avro/AvroNettySpringConsumerTest.java, components/camel-avro-rpc/src/test/java/org/apache/camel/component/avro/AvroProducerTestSupport.java, components/camel-avro-rpc/src/test/java/org/apache/camel/component/avro/ConsumerRouteType.java, components/camel-avro-rpc/src/test/java/org/apache/camel/component/avro/ProducerRouteType.java, components/camel-avro-rpc/src/test/resources/org/apache/camel/component/avro/netty-consumer/base.xml, components/camel-avro-rpc/src/test/resources/org/apache/camel/component/avro/netty-consumer/reflect.xml, components/camel-avro-rpc/src/test/resources/org/apache/camel/component/avro/netty-consumer/specific.xml, components/camel-avro-rpc/src/test/resources/org/apache/camel/component/avro/netty-consumer/specificProcessor.xml, components/camel-avro-rpc/src/test/resources/org/apache/camel/component/avro/netty-consumer/specificProcessorWrong.xml, docs/components/modules/ROOT/pages/avro-component.adoc, parent/pom.xml
fixes: https://issues.apache.org/jira/browse/CAMEL-15879
Upgrade to newer avro brings change from netty3 to netty4. This brings graceful connection closing, which takes longer time (it takes about 4 seconds - https://github.com/apache/avro/commit/d2d5663076d9c4a5b92b7102a21217a5c8cf6115#diff-3b49ec5d308d4a1ed5a80c9c41fc6c5c2173985033470c6531a9a1fb93a72edaR111). I've refactored test to minimize number of netty connection closes.  Even with thisd optimization, there is need to close netty server 36 times (for all tests in the module).
Which means that the time taken by all the tests is much higher. On my local computer it takes **0:29** before upgrade and **2:44** after upgrade. I'm not sure whether it is acceptable or if some tests should be moved among slower tests.
**Unfortunately it is …
=> CAMEL-15879 Update avro version to 1.10.x (1.10.0)

components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/MicrometerConstants.java, components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/routepolicy/MicrometerRoutePolicy.java, components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/routepolicy/MicrometerRoutePolicyNamingStrategy.java, components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/routepolicy/ManagedMicrometerRoutePolicyTest.java, components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/routepolicy/MicrometerRoutePolicyMulticastSubRouteTest.java, components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/routepolicy/MicrometerRoutePolicySubRouteTest.java
=> CAMEL-15908: Add additional exchange metrics to MicrometerRoutePolicy

components/camel-minio/pom.xml, components/camel-minio/src/test/java/org/apache/camel/component/minio/integration/MinioComponentTest.java, components/camel-minio/src/test/java/org/apache/camel/component/minio/integration/MinioConsumerTest.java, components/camel-minio/src/test/java/org/apache/camel/component/minio/integration/MinioCopyObjectOperationTest.java, components/camel-minio/src/test/java/org/apache/camel/component/minio/integration/MinioDeleteBucketOperationTest.java, components/camel-minio/src/test/java/org/apache/camel/component/minio/integration/MinioListObjectsOperationTest.java, components/camel-minio/src/test/java/org/apache/camel/component/minio/integration/MinioObjectRangeOperationTest.java, test-infra/camel-test-infra-minio/pom.xml, test-infra/camel-test-infra-minio/src/test/java/org/apache/camel/test/infra/minio/common/MinioProperties.java, test-infra/camel-test-infra-minio/src/test/java/org/apache/camel/test/infra/minio/services/MinioLocalContainerService.java, test-infra/camel-test-infra-minio/src/test/java/org/apache/camel/test/infra/minio/services/MinioRemoteService.java, test-infra/camel-test-infra-minio/src/test/java/org/apache/camel/test/infra/minio/services/MinioService.java, test-infra/camel-test-infra-minio/src/test/java/org/apache/camel/test/infra/minio/services/MinioServiceFactory.java, test-infra/pom.xml
=> Migrates camel-minio to the new test infra

components/camel-nsq/pom.xml, test-infra/camel-test-infra-nsq/pom.xml, test-infra/camel-test-infra-nsq/src/test/java/org/apache/camel/test/infra/nsq/common/NsqProperties.java, test-infra/camel-test-infra-nsq/src/test/java/org/apache/camel/test/infra/nsq/services/NsqLocalContainerService.java, test-infra/camel-test-infra-nsq/src/test/java/org/apache/camel/test/infra/nsq/services/NsqRemoteService.java, test-infra/camel-test-infra-nsq/src/test/java/org/apache/camel/test/infra/nsq/services/NsqService.java, test-infra/camel-test-infra-nsq/src/test/java/org/apache/camel/test/infra/nsq/services/NsqServiceFactory.java, test-infra/pom.xml
=> Migrates camel-nsq to the new test infra

components/camel-azure-storage-blob/src/main/java/org/apache/camel/component/azure/storage/blob/BlobConfigurationOptionsProxy.java, components/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BlobConsumerITTest.java, components/camel-azure-storage-blob/src/test/resources/azurite.properties, test-infra/camel-test-infra-azure-common/src/test/java/org/apache/camel/test/infra/azure/common/services/AzuriteContainer.java
=> Fix the disabled test and some minor cleanups

core/camel-core-languages/src/main/java/org/apache/camel/language/csimple/CSimpleLanguage.java
A draft to discuss some possible improvements
=> csimple language: support fully pre-compiled use case

components/camel-pulsar/pom.xml, components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarConsumerAcknowledgementTest.java, components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarConsumerDeadLetterPolicyTest.java, components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/PulsarConsumerReadCompactedTest.java, parent/pom.xml, test-infra/camel-test-infra-pulsar/pom.xml, test-infra/camel-test-infra-pulsar/src/test/java/org/apache/camel/test/infra/pulsar/common/PulsarProperties.java, test-infra/camel-test-infra-pulsar/src/test/java/org/apache/camel/test/infra/pulsar/services/PulsarLocalContainerService.java, test-infra/camel-test-infra-pulsar/src/test/java/org/apache/camel/test/infra/pulsar/services/PulsarRemoteService.java, test-infra/camel-test-infra-pulsar/src/test/java/org/apache/camel/test/infra/pulsar/services/PulsarService.java, test-infra/camel-test-infra-pulsar/src/test/java/org/apache/camel/test/infra/pulsar/services/PulsarServiceFactory.java, test-infra/pom.xml
=> Migrates camel-pulsar to the new test infra

components/camel-xmpp/pom.xml, components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/XmppBaseContainerTest.java, components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/XmppDeferredConnectionTest.java, components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/XmppMultiUserChatTest.java, components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/XmppProducerConcurrentTest.java, components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/XmppRobustConnectionTest.java, components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/XmppRouteChatTest.java, components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/XmppRouteMultipleProducersSingleConsumerTest.java, components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/XmppRouteTest.java, components/camel-xmpp/src/test/java/org/apache/camel/component/xmpp/XmppTestUtil.java, test-infra/camel-test-infra-xmpp/pom.xml, test-infra/camel-test-infra-xmpp/src/test/java/org/apache/camel/test/infra/xmpp/common/XmppProperties.java, test-infra/camel-test-infra-xmpp/src/test/java/org/apache/camel/test/infra/xmpp/services/XmppLocalContainerService.java, test-infra/camel-test-infra-xmpp/src/test/java/org/apache/camel/test/infra/xmpp/services/XmppRemoteService.java, test-infra/camel-test-infra-xmpp/src/test/java/org/apache/camel/test/infra/xmpp/services/XmppServerContainer.java, test-infra/camel-test-infra-xmpp/src/test/java/org/apache/camel/test/infra/xmpp/services/XmppService.java, test-infra/camel-test-infra-xmpp/src/test/java/org/apache/camel/test/infra/xmpp/services/XmppServiceFactory.java, test-infra/pom.xml
=> Migrates camel-xmpp to the new test infra

components/camel-pg-replication-slot/pom.xml, components/camel-pg-replication-slot/src/test/java/org/apache/camel/component/pg/replication/slot/integration/PgReplicationSlotCamelTest.java, test-infra/camel-test-infra-postgres/pom.xml, test-infra/camel-test-infra-postgres/src/test/java/org/apache/camel/test/infra/postgres/common/PostgresProperties.java, test-infra/camel-test-infra-postgres/src/test/java/org/apache/camel/test/infra/postgres/services/PostgresLocalContainerService.java, test-infra/camel-test-infra-postgres/src/test/java/org/apache/camel/test/infra/postgres/services/PostgresRemoteService.java, test-infra/camel-test-infra-postgres/src/test/java/org/apache/camel/test/infra/postgres/services/PostgresService.java, test-infra/camel-test-infra-postgres/src/test/java/org/apache/camel/test/infra/postgres/services/PostgresServiceFactory.java, test-infra/pom.xml
=> Migrates camel-pg-replication-slot to the new test infra

components/camel-couchdb/pom.xml, components/camel-couchdb/src/test/java/org/apache/camel/component/couchdb/CouchDbCrudTest.java, test-infra/camel-test-infra-couchdb/pom.xml, test-infra/camel-test-infra-couchdb/src/test/java/org/apache/camel/test/infra/couchdb/common/CouchDbProperties.java, test-infra/camel-test-infra-couchdb/src/test/java/org/apache/camel/test/infra/couchdb/services/CouchDbLocalContainerService.java, test-infra/camel-test-infra-couchdb/src/test/java/org/apache/camel/test/infra/couchdb/services/CouchDbRemoteService.java, test-infra/camel-test-infra-couchdb/src/test/java/org/apache/camel/test/infra/couchdb/services/CouchDbService.java, test-infra/camel-test-infra-couchdb/src/test/java/org/apache/camel/test/infra/couchdb/services/CouchDbServiceFactory.java, test-infra/pom.xml
=> Migrates camel-couchdb to the new test infra

components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/csv/BindyCsvDataFormat.java, components/camel-bindy/src/test/java/org/apache/camel/dataformat/bindy/csv/BindyTabSeparatorTest.java
Removed trailing tabs trimming for tab separator
=> CAMEL-15920 - removed trailing tabs trimming for tab separator

components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/FromFtpDirectoryToBinaryFilesTest.java, components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/FtpsServerTestSupport.java
=> (chores) Improve logging in camel-ftp tests to debug CI issues

components/camel-csimple-joor/src/main/java/org/apache/camel/language/csimple/joor/JoorCSimpleCompiler.java, core/camel-core-languages/src/main/java/org/apache/camel/language/csimple/CSimpleCodeGenerator.java, core/camel-core-languages/src/main/java/org/apache/camel/language/csimple/CSimpleLanguage.java, core/camel-core-languages/src/main/java/org/apache/camel/language/csimple/CSimpleSupport.java, core/camel-core/src/test/java/org/apache/camel/language/csimple/HighPredicate.java, core/camel-core/src/test/java/org/apache/camel/language/csimple/MedPredicate.java, tests/camel-jmh/src/test/java/org/apache/camel/itest/jmh/CSimpleScript1.java, tests/camel-jmh/src/test/java/org/apache/camel/itest/jmh/CSimpleScript2.java, tests/camel-jmh/src/test/java/org/apache/camel/itest/jmh/CSimpleScript3.java
Improve the 100% build time compiled use case
=> CAMEL-15704: camel-csimple - Compiled simple language

docs/user-manual/modules/ROOT/pages/team.adoc
=> Updated committers list to include myself

docs/user-manual/modules/ROOT/pages/contributing.adoc, test-infra/README.md
=> Added documentation about the test-infra

docs/user-manual/modules/ROOT/pages/contributing.adoc
=> Fixed minor typos in the contributing guide

core/camel-main/src/main/java/org/apache/camel/main/SimpleMain.java
=> Fix SimpleMain oversight on doStop method (3.7.x)

test-infra/camel-test-infra-couchbase/src/test/java/org/apache/camel/test/infra/couchbase/services/CouchbaseLocalContainerService.java
Ensure other couchbase services use fixed ports otherwise some tests may
throw timeout issues when querying or searching for data
=> Fix upsert timeouts issues when using the couchbase test-infra

components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/HazelcastDefaultComponent.java
=> CAMEL-15947: client mode : search the instance using HazelcastClient

components/camel-test-cdi/src/main/docs/test-cdi.adoc
=> Corrected small error in java code on test-cdi.adoc

core/camel-management/src/main/java/org/apache/camel/management/mbean/ManagedPollEnricher.java
=> [CAMEL-15949] Added missing method getSupportExtendedInformation for ManagedPollEnricher

docs/components/modules/ROOT/pages/telegram-component.adoc
=> change ? to &

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd, core/camel-core-model/src/main/java/org/apache/camel/model/DataFormatDefinitionAware.java, core/camel-core-model/src/main/java/org/apache/camel/model/MarshalDefinition.java, core/camel-core-model/src/main/java/org/apache/camel/model/UnmarshalDefinition.java
=> core: add a DataFormatDefinitionAware interface to mark processors that support data formats

core/camel-core-model/src/main/java/org/apache/camel/model/loadbalancer/CustomLoadBalancerDefinition.java
=> core: add CustomLoadBalancerDefinition(String) constructor

core/camel-core-model/src/main/java/org/apache/camel/builder/BuilderSupport.java
=> add back the removed jsonpath method without result type

components/camel-http-common/src/main/java/org/apache/camel/http/common/HttpSendDynamicAware.java, components/camel-http4/src/test/java/org/apache/camel/component/http4/HttpSendDynamicAwareRawParameterTest.java
Added resolve parameter values before building query string.
=> CAMEL-15974: Fix RAW parameters resolution in HttpSendDynamicAware

core/camel-core-engine/src/main/docs/modules/eips/pages/intercept.adoc
=> Fix typo intercpt -> intercept

core/camel-core-engine/src/main/docs/modules/eips/pages/intercept.adoc
=> Fix typo: intercpt -> intercept

components/camel-redis/pom.xml, components/camel-redis/src/test/java/org/apache/camel/component/redis/processor/aggregate/AggregateRedisTest.java, test-infra/camel-test-infra-redis/pom.xml, test-infra/camel-test-infra-redis/src/test/java/org/apache/camel/test/infra/redis/common/RedisProperties.java, test-infra/camel-test-infra-redis/src/test/java/org/apache/camel/test/infra/redis/services/RedisLocalContainerService.java, test-infra/camel-test-infra-redis/src/test/java/org/apache/camel/test/infra/redis/services/RedisRemoteService.java, test-infra/camel-test-infra-redis/src/test/java/org/apache/camel/test/infra/redis/services/RedisService.java, test-infra/camel-test-infra-redis/src/test/java/org/apache/camel/test/infra/redis/services/RedisServiceFactory.java, test-infra/pom.xml
=> Ported camel-redis test to camel-test-infra

components/camel-docker/src/main/java/org/apache/camel/component/docker/consumer/DockerEventsConsumer.java, components/camel-docker/src/main/java/org/apache/camel/component/docker/consumer/DockerStatsConsumer.java, components/camel-docker/src/main/java/org/apache/camel/component/docker/producer/AsyncDockerProducer.java, components/camel-docker/src/test/java/org/apache/camel/component/docker/headers/AttachContainerCmdHeaderTest.java, components/camel-docker/src/test/java/org/apache/camel/component/docker/headers/BuildImageCmdHeaderTest.java, components/camel-docker/src/test/java/org/apache/camel/component/docker/headers/ExecStartCmdHeaderTest.java, components/camel-docker/src/test/java/org/apache/camel/component/docker/headers/LogContainerCmdHeaderTest.java, components/camel-docker/src/test/java/org/apache/camel/component/docker/headers/PullImageCmdHeaderTest.java, components/camel-docker/src/test/java/org/apache/camel/component/docker/headers/PushImageCmdHeaderTest.java, components/camel-docker/src/test/java/org/apache/camel/component/docker/headers/WaitContainerCmdHeaderTest.java, components/camel-docker/src/test/java/org/apache/camel/component/docker/it/DockerNettyCmdExecFactoryTest.java, components/camel-docker/src/test/java/org/apache/camel/component/docker/it/DockerProducerTest.java, components/camel-docker/src/test/java/org/apache/camel/component/docker/it/DockerStatsConsumerTest.java
- adjusted some classes for Junit 5 compatibility
- removed several deprecated callback classes
- adjusted test cases to match the updated classes
- simplified execution of a few IT cases
=> camel-docker: cleaned up deprecations related to outdated docker-java api calls

components/camel-vertx/src/main/java/org/apache/camel/component/vertx/VertxComponent.java
=> (chore) camel-vertx: fixed usage of deprecated vertx APIs

catalog/camel-catalog-maven/src/main/java/org/apache/camel/catalog/maven/DefaultMavenArtifactProvider.java, catalog/camel-catalog-maven/src/main/java/org/apache/camel/catalog/maven/MavenVersionManager.java, components/camel-csimple-joor/src/main/java/org/apache/camel/language/csimple/joor/JoorCSimpleCompiler.java, components/camel-joor/src/main/java/org/apache/camel/language/joor/JoorCompiler.java, components/camel-kubernetes/src/main/java/org/apache/camel/component/kubernetes/cluster/lock/impl/ConfigMapLeaseResourceManager.java, components/camel-sjms/src/main/java/org/apache/camel/component/sjms/batch/SjmsBatchConsumer.java, components/camel-swagger-java/src/main/java/org/apache/camel/swagger/RestSwaggerProcessor.java, core/camel-management/src/main/java/org/apache/camel/management/DefaultManagementAgent.java, core/camel-support/src/main/java/org/apache/camel/converter/stream/FileInputStreamCache.java
Adjust logging code to use log markers instead of concatenating strings
=> (chores) cross component logging fixes

core/camel-main/src/main/java/org/apache/camel/main/BaseMainSupport.java, core/camel-util/src/main/java/org/apache/camel/util/SensitiveUtils.java, core/camel-util/src/test/java/org/apache/camel/util/SensitiveUtilsTest.java
This should simplify identify and filtering sensitive strings and resolve issues like apache/camel-kafka-connector#159
=> Make the sensitive string check easier to reuse so that we can eval and filter them

core/camel-main/src/main/java/org/apache/camel/main/BaseMainSupport.java, core/camel-util/src/main/java/org/apache/camel/util/SensitiveUtils.java, core/camel-util/src/test/java/org/apache/camel/util/SensitiveUtilsTest.java
Backporting because we'll need this fix on CKC
=> (backport) Make the sensitive string check easier to reuse so that we can eval and filter them (#4834)

Jenkinsfile
=> Jenkinsfile build: Point to branch camel-3.7.x

Jenkinsfile.deploy
=> Jenkinsfile.deploy: Point to camel-3.7.x branch

Jenkinsfile.jdk11, Jenkinsfile.jdk14, Jenkinsfile.jdk16
=> Oscerd patch 1

core/camel-util/src/main/java/org/apache/camel/util/SensitiveUtils.java, core/camel-util/src/test/java/org/apache/camel/util/SensitiveUtilsTest.java
=> make use of HashSet#contains instead of streaming + regex which is slower

core/camel-util/src/main/java/org/apache/camel/util/SensitiveUtils.java, core/camel-util/src/test/java/org/apache/camel/util/SensitiveUtilsTest.java
=> Backport sensitive utils improvements

components/camel-activemq/src/main/java/org/apache/camel/component/activemq/ActiveMQConfiguration.java
=> camel-activemq: remove unnecessary exception rethrow

components/camel-aws-s3/src/main/java/org/apache/camel/component/aws/s3/S3Component.java, components/camel-aws-s3/src/main/java/org/apache/camel/component/aws/s3/client/S3ClientFactory.java, components/camel-bean/src/main/java/org/apache/camel/component/bean/BeanComponent.java, components/camel-bean/src/main/java/org/apache/camel/component/bean/BeanEndpoint.java, components/camel-crypto-cms/src/main/java/org/apache/camel/component/crypto/cms/common/CryptoCmsMarshallerAbstract.java, components/camel-crypto-cms/src/main/java/org/apache/camel/component/crypto/cms/sig/SignedDataCreator.java, components/camel-docker/src/main/java/org/apache/camel/component/docker/DockerClientFactory.java, components/camel-dozer/src/main/java/org/apache/camel/converter/dozer/MapperFactory.java, components/camel-fhir/camel-fhir-api/src/main/java/org/apache/camel/component/fhir/api/ExtraParameters.java
Components: camel-aws-s3, camel-bean, camel-crypto-cms, camel-docker,
camel-dozer, camel-fhir
This should avoid NPEs in the very unlikely case some of those values are null
=> (chores) Avoid NPE in autoboxing

camel-dependencies/pom.xml, parent/pom.xml, pom.xml
=> Move impsort-maven-plugin-version declaration to the parent pom level

components/camel-milo/src/main/java/org/apache/camel/component/milo/server/internal/CamelNamespace.java
[JIRA issue]https://issues.apache.org/jira/browse/CAMEL-16009
=> [CAMEL-16009] remove the duplicate

test-infra/camel-test-infra-artemis/src/test/java/org/apache/camel/test/infra/artemis/services/ArtemisContainer.java
=> Fixed invalid AMQP endpoint for the Artemis test infra

camel-dependencies/pom.xml
More info: https://github.com/junit-team/junit4/blob/HEAD/doc/ReleaseNotes4.13.1.md
=> Dependency vulnerability. junit-version to 4.13.1

test-infra/camel-test-infra-artemis/src/test/java/org/apache/camel/test/infra/artemis/services/ArtemisContainer.java
=> (backport) CAMEL-16014: fixed invalid AMQP endpoint for the Artemis test infra (#4860)

.github/workflows/master-pr-build.yml
=> Remove the gh action for checking uncommitted file for the moment

test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/StrimziService.java
=> CAMEL-16023: ensure resources are released after the test execution

camel-dependencies/pom.xml, parent/pom.xml
=> Bump Xstream 1.4.15

parent/pom.xml
https://issues.apache.org/jira/browse/CAMEL-16027
=> CAMEL-16027: Put camel-xml-jaxp above the marker of components:START

test-infra/camel-test-infra-azure-storage-queue/pom.xml, test-infra/camel-test-infra-azure-storage-queue/src/test/java/org/apache/camel/test/infra/azure/storage/queue/clients/AzureStorageClientUtils.java
=> Added reusable Azure storage queue client utils for the test infra

test-infra/README.md
=> Extended the test infra documentation with details about how to implement and use new modules

pom.xml
=> CAMEl-16031 - Upgrade Groovy from 2.5.5 to 2.5.14

components/camel-testcontainers-junit5/src/main/java/org/apache/camel/test/testcontainers/junit5/ContainerAwareTestSupport.java, components/camel-testcontainers-junit5/src/main/java/org/apache/camel/test/testcontainers/junit5/ContainerPropertiesFunction.java, components/camel-testcontainers-junit5/src/main/java/org/apache/camel/test/testcontainers/junit5/Containers.java, components/camel-testcontainers-junit5/src/main/java/org/apache/camel/test/testcontainers/junit5/Wait.java, components/camel-testcontainers-junit5/src/test/java/org/apache/camel/test/testcontainers/junit5/ContainerAwareTestSupportIT.java, components/camel-testcontainers-spring-junit5/src/main/java/org/apache/camel/test/testcontainers/spring/junit5/ContainerAwareSpringTestSupport.java, components/camel-testcontainers-spring-junit5/src/test/java/org/apache/camel/test/testcontainers/spring/junit5/ContainerAwareSpringTestSupportIT.java, components/camel-testcontainers-spring/src/main/java/org/apache/camel/test/testcontainers/spring/ContainerAwareSpringTestSupport.java, components/camel-testcontainers-spring/src/test/java/org/apache/camel/test/testcontainers/spring/ContainerAwareSpringTestSupportIT.java, components/camel-testcontainers/src/main/java/org/apache/camel/test/testcontainers/ContainerAwareTestSupport.java, components/camel-testcontainers/src/main/java/org/apache/camel/test/testcontainers/ContainerPropertiesFunction.java, components/camel-testcontainers/src/main/java/org/apache/camel/test/testcontainers/Containers.java, components/camel-testcontainers/src/main/java/org/apache/camel/test/testcontainers/Wait.java, components/camel-testcontainers/src/test/java/org/apache/camel/test/testcontainers/ContainerAwareTestSupportIT.java
=> Marked the camel testcontainers components as deprecated

catalog/camel-catalog-lucene/src/main/java/org/apache/camel/catalog/lucene/LuceneSuggestionStrategy.java
=> Ensure Lucene's ByteBuffersDirectory is closed after use

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/AS2AsynchronousMDNManager.java
The class is auto closeable and the flush is already performed during
close
=> (chores) Cleanup closing the resources on the AS2AsynchronousMDNManager

components/camel-sjms/src/main/java/org/apache/camel/component/sjms/TransactionOnCompletion.java
=> Prevent an NPE during equality check on camel-sjms component

parent/pom.xml
=> Upgrade Flink to version 1.11.3

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaComponent.java, components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaComponentTest.java
Will port the fix as well to 3.7.x branch
=> CAMEL-16043: Fix additionalProperties option in camel-kafka

core/camel-xml-jaxb/pom.xml
- [x ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [ x] Each commit in the pull request should have a meaningful subject line and body.
- [x ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [x ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and …
=> CAMEL-16040: Add package imports to xml jaxb to allow swagger generation

components/camel-jsonata/src/main/docs/jsonata-component.adoc
Update documentation due to wrong reference.
=> Update jsonata-component.adoc - Wrong param description

components/camel-beanstalk/src/main/java/org/apache/camel/component/beanstalk/BeanstalkConsumer.java, components/camel-beanstalk/src/main/java/org/apache/camel/component/beanstalk/BeanstalkProducer.java, components/camel-beanstalk/src/main/java/org/apache/camel/component/beanstalk/processors/BuryCommand.java, components/camel-beanstalk/src/main/java/org/apache/camel/component/beanstalk/processors/DeleteCommand.java, components/camel-beanstalk/src/main/java/org/apache/camel/component/beanstalk/processors/KickCommand.java, components/camel-beanstalk/src/main/java/org/apache/camel/component/beanstalk/processors/PutCommand.java, components/camel-beanstalk/src/main/java/org/apache/camel/component/beanstalk/processors/ReleaseCommand.java, components/camel-beanstalk/src/main/java/org/apache/camel/component/beanstalk/processors/TouchCommand.java
- Make it easier to spot which of the act calls raise would raise the Exception
- Remove unnecessary String formatting around logs
- Remove unnecessary log guards
=> (chores) camel-beanstalk: cleanups

components/camel-bean/src/main/java/org/apache/camel/component/bean/MethodInfo.java
=> camel-bean: prevent a NPE if parametersExpression is null

components/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Consumer.java, components/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Endpoint.java
=> Camel 16068 3.7.x

components/camel-activemq/src/main/java/org/apache/camel/component/activemq/ActiveMQComponent.java, components/camel-ahc/src/main/java/org/apache/camel/component/ahc/helper/AhcHelper.java, components/camel-avro-rpc/src/main/java/org/apache/camel/component/avro/AvroListener.java, components/camel-aws-s3/src/main/java/org/apache/camel/component/aws/s3/S3Consumer.java, components/camel-aws-swf/src/main/java/org/apache/camel/component/aws/swf/CamelWorkflowDefinition.java, components/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Consumer.java, components/camel-bean/src/main/java/org/apache/camel/component/bean/AbstractBeanProcessor.java, components/camel-bean/src/main/java/org/apache/camel/component/bean/DefaultBeanProcessorFactory.java, components/camel-bean/src/main/java/org/apache/camel/component/bean/MethodInfo.java, components/camel-bean/src/main/java/org/apache/camel/language/bean/BeanExpression.java, components/camel-beanstalk/src/main/java/org/apache/camel/component/beanstalk/BeanstalkProducer.java, components/camel-cm-sms/src/main/java/org/apache/camel/component/cm/CMSenderOneMessageImpl.java, components/camel-consul/src/main/java/org/apache/camel/component/consul/ConsulRegistry.java, components/camel-cxf-transport/src/main/java/org/apache/camel/component/cxf/common/header/CxfHeaderFilterStrategy.java, components/camel-cxf-transport/src/main/java/org/apache/camel/component/cxf/transport/CamelDestination.java, components/camel-cxf/src/main/java/org/apache/camel/component/cxf/CxfConsumer.java, components/camel-cxf/src/main/java/org/apache/camel/component/cxf/CxfEndpoint.java, components/camel-cxf/src/main/java/org/apache/camel/component/cxf/CxfProducer.java, components/camel-cxf/src/main/java/org/apache/camel/component/cxf/DefaultCxfBinding.java, components/camel-directvm/src/main/java/org/apache/camel/component/directvm/DirectVmProducer.java
=> Avoid catching Throwable because it could also catch Java Errors that shouldn't be handled

components/camel-facebook/src/main/java/org/apache/camel/component/facebook/FacebookConsumer.java, components/camel-facebook/src/main/java/org/apache/camel/component/facebook/FacebookProducer.java, components/camel-facebook/src/main/java/org/apache/camel/component/facebook/data/FacebookMethodsTypeHelper.java, components/camel-file-watch/src/main/java/org/apache/camel/component/file/watch/FileWatchConsumer.java, components/camel-file/src/main/java/org/apache/camel/component/file/GenericFile.java, components/camel-file/src/main/java/org/apache/camel/component/file/GenericFilePollingConsumer.java, components/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubConsumer.java, components/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/consumer/CamelMessageReceiver.java, components/camel-optaplanner/src/main/java/org/apache/camel/component/optaplanner/OptaPlannerProducer.java, components/camel-quartz/src/main/java/org/apache/camel/component/quartz/CamelJob.java, components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQComponent.java, components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQConsumer.java, components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQProducer.java, components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/reply/CorrelationTimeoutMap.java, components/camel-sjms/src/main/java/org/apache/camel/component/sjms/SjmsConsumer.java, components/camel-sjms/src/main/java/org/apache/camel/component/sjms/SjmsHelper.java, components/camel-sjms/src/main/java/org/apache/camel/component/sjms/SjmsMessage.java, components/camel-sjms/src/main/java/org/apache/camel/component/sjms/SjmsProducer.java, components/camel-sjms/src/main/java/org/apache/camel/component/sjms/TransactionOnCompletion.java, components/camel-sjms/src/main/java/org/apache/camel/component/sjms/consumer/EndpointMessageListener.java, components/camel-sjms/src/main/java/org/apache/camel/component/sjms/consumer/SimpleMessageListenerContainer.java
Includes changes to the following components: camel-facebook, camel-file-watch
camel-file, camel-google-pubsubl, camel-google-pubsub,
camel-optaplanner, camel-rabbitmq, camel-quartz, camel-sjms
=> (chores) avoid catching Throwable as it can lead to unexpected situations

components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/HazelcastComponentHelper.java, components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/atomicnumber/HazelcastAtomicnumberProducer.java, components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/list/HazelcastListProducer.java, components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/map/HazelcastMapProducer.java, components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/multimap/HazelcastMultimapProducer.java, components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/queue/HazelcastQueueProducer.java, components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/replicatedmap/HazelcastReplicatedmapConsumer.java, components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/ringbuffer/HazelcastRingbufferProducer.java, components/camel-hazelcast/src/test/java/org/apache/camel/component/hazelcast/HazelcastCamelTestSupport.java, components/camel-hazelcast/src/test/java/org/apache/camel/component/hazelcast/HazelcastReplicatedmapConsumerTest.java
cherry-pick from master commit
=> CAMEL-16018: HazelcastReplicatedConsumer not receiving events (#4868)

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/milo-client-component.adoc, components/camel-milo/src/main/docs/milo-client-component.adoc, components/camel-milo/src/main/java/org/apache/camel/component/milo/client/MiloClientConnection.java, components/camel-milo/src/main/java/org/apache/camel/component/milo/client/MiloClientEndpoint.java, components/camel-milo/src/main/java/org/apache/camel/component/milo/client/MiloClientProducer.java, components/camel-milo/src/main/java/org/apache/camel/component/milo/client/internal/SubscriptionManager.java, components/camel-milo/src/test/java/org/apache/camel/component/milo/ReadValuesClientTest.java, docs/components/modules/ROOT/pages/milo-client-component.adoc
=> camel-milo: added possibility to read node values via producer.

components/camel-milo/src/main/java/org/apache/camel/component/milo/client/MiloClientProducer.java, components/camel-milo/src/test/java/org/apache/camel/component/milo/ReadValuesClientTest.java
Fixes issues with this PR breaking `master` due to checkstyle coding issues in `camel-milo`
=> Fixes checkstyle coding issues with camel-milo

components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowConsumer.java, components/camel-undertow/src/test/java/org/apache/camel/component/undertow/rest/RestUndertowContentTypeTest.java
----
https://issues.apache.org/jira/browse/CAMEL-16077
=> CAMEL-16077: camel-undertow - not respect content-type specified by REST DSL produces when body returns null

components/camel-aws2-sns/src/main/java/org/apache/camel/component/aws2/sns/Sns2Configuration.java
=> CAMEL-16079-3.7.x

components/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/CamelTestSupport.java
Includes:
- cleanup log messages
- avoid catching Throwable because it could also catch Java Errors that shouldn't be handled
- rename a context variable to avoid confusion with the class member one
- use a lambda to simplify sendBody
- remove from the method signature exceptions that are never thrown
=> (chores) camel-test-junit5: cleanups

components/camel-atlasmap/src/main/java/org/apache/camel/component/atlasmap/AtlasMapEndpoint.java
- use log markers for logging instead of concatenating strings
- evaluation of the datasource variable would always result in true
- remove unnecessary array creation for logging
=> (chores) camel-atlasmap: cleanups

components/camel-aws2-s3/src/main/docs/aws2-s3-component.adoc, components/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Constants.java, components/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Endpoint.java
=> [CAMEL-16108] The S3 metadata is included in the Exchange as a Header

components/camel-sql/src/main/java/org/apache/camel/component/sql/SqlHelper.java
Close InputStream after we are done with it.
=> Close SqlHelper InputStream

README.md
=> README update for testing Backport action

README.md
=> Revert "README update for testing Backport action"

catalog/camel-catalog/src/main/java/org/apache/camel/catalog/DefaultCamelCatalog.java
=> Remove unused variable

components/camel-aws2-eventbridge/src/main/java/org/apache/camel/component/aws2/eventbridge/EventbridgeProducer.java, components/camel-aws2-sns/src/main/java/org/apache/camel/component/aws2/sns/Sns2Endpoint.java, components/camel-google-bigquery/src/main/java/org/apache/camel/component/google/bigquery/sql/SqlHelper.java, components/camel-jsch/src/main/java/org/apache/camel/component/scp/ScpOperations.java, components/camel-validator/src/main/java/org/apache/camel/component/validator/DefaultLSResourceResolver.java
=> Close InputStreams after usage.

core/camel-api/src/main/java/org/apache/camel/spi/XMLRoutesDefinitionLoader.java, core/camel-xml-io/src/main/java/org/apache/camel/xml/in/ModelParserXMLRoutesDefinitionLoader.java, core/camel-xml-jaxb/src/main/java/org/apache/camel/xml/jaxb/JaxbHelper.java, core/camel-xml-jaxb/src/main/java/org/apache/camel/xml/jaxb/JaxbModelToXMLDumper.java, core/camel-xml-jaxb/src/main/java/org/apache/camel/xml/jaxb/JaxbXMLRoutesDefinitionLoader.java
=> api: remove createModelFromXml from XMLRoutesDefinitionLoader

components/camel-slack/pom.xml, components/camel-slack/src/main/java/org/apache/camel/component/slack/SlackConsumer.java, components/camel-slack/src/main/java/org/apache/camel/component/slack/SlackProducer.java
Re-use http client and consume response.
=> Slack: Re-use http client and consume response

components/camel-websocket-jsr356/pom.xml
Simple upgrade to fix the unit tests when running with the `tia` profile.
=> Upgrade meecrowave-junit

parent/pom.xml
=> Upgrade Elytron-web to 1.8.0.Final

components/camel-docker/src/main/java/org/apache/camel/component/docker/producer/AsyncDockerProducer.java, components/camel-docker/src/main/java/org/apache/camel/component/docker/producer/DockerProducer.java
Close requests to release resources
=> camel-docker: Close requests to release resources

tooling/maven/camel-restdsl-swagger-plugin/src/main/docs/camel-restdsl-swagger-plugin.adoc
=> Fix typo ibraries -> libraries

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/docs/salesforce-component.adoc, components/camel-salesforce/camel-salesforce-component/src/main/docs/salesforce-component.adoc, components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/client/CompositeApiClient.java, components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/client/DefaultCompositeApiClient.java, components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/processor/CompositeApiProcessor.java, components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/CompositeApiIntegrationTest.java, components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/RawPayloadTest.java, docs/components/modules/ROOT/pages/salesforce-component.adoc
=> CAMEL-16086: Salesforce raw composite requires

parent/pom.xml
Upgrade of cassandra driver to 4.10.0, to be aligned with cassandra-quarkus 1.0.0 (https://github.com/datastax/cassandra-quarkus), which allow camel-quarkus extension for cassandra (https://github.com/apache/camel-quarkus/issues/1355) to be finished.
=> Upgrade of Cassandra Java Driver to 4.10.0

components/camel-pubnub/pom.xml, components/camel-rest-openapi/pom.xml, components/camel-rest-openapi/src/test/java/org/apache/camel/component/rest/openapi/Jetty94ServerFactory.java, components/camel-rest-swagger/pom.xml, components/camel-rest-swagger/src/test/java/org/apache/camel/component/rest/swagger/Jetty94ServerFactory.java, parent/pom.xml
=> Upgraded wiremock to 2.27.2

test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSSQSLocalContainerService.java
=> camel-test-infra-aws-v2: remove SQS container override since 0.12.6 is now the default

camel-dependencies/pom.xml, parent/pom.xml
=> CAMEL-15635: Fixed some Kudu tests that were failing with JDK >= 12

test-infra/camel-test-infra-hdfs/src/test/resources/org/apache/camel/test/infra/hdfs/v2/services/Dockerfile
Includes:
- updated Hadoop container to use a newer Fedora version
- reduce used disk space
- removed deprecated elements
------
Saves about 200Mb of the final container size.
=> camel-test-infra-hdfs: Hadoop test container cleanups

test-infra/camel-test-infra-dispatch-router/src/test/resources/org/apache/camel/test/infra/dispatch/router/services/Dockerfile
Includes:
- updated container to use a newer Fedora version
- reduce used disk space
- removed deprecated elements
----
Saves about 220 Mb of container size
=> camel-test-infra-qpid: qpid-dispatch router test container cleanups

test-infra/camel-test-infra-artemis/src/test/resources/org/apache/camel/test/infra/artemis/services/Dockerfile
Includes:
- updated container to use a newer Fedora version
- reduce used disk space
- removed deprecated elements
----
Saves about 35Mb of the container size.
=> camel-test-infra-artemis: Apache Artemis container cleanups

components/camel-aws2-sns/src/main/java/org/apache/camel/component/aws2/sns/Sns2Configuration.java, components/camel-aws2-sns/src/test/java/org/apache/camel/component/aws2/sns/SnsComponentConfigurationTest.java
=> CAMEL-16079
