components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaProducer.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaTransactionIT.java

https://issues.apache.org/jira/browse/CAMEL-15016
- add kafka transaction policy
- init kafka transaction if ```additional-properties[transactional.id]``` is set.
example route
```
@BindToRegistry("kafkaTransaction")
private KafkaTransactionPolicy policy = new KafkaTransactionPolicy();
from("direct:kafkaTransaction")
.transacted("kafkaTransaction")
.to("kafka:testTransaction?additional-properties[transactional.id]=1234&additional-properties[enable.idempotence]=true&additional-properties[retries]=5");
```

CAMEL-15016 support kafka transactions

---

components/camel-sql/src/main/docs/sql-component.adoc
components/camel-sql/src/main/java/org/apache/camel/processor/idempotent/jdbc/JdbcMessageIdRepository.java

- Add constraint to the table creation by default
- Update documentation for JdbcMessageIdRepository

Add default constraint creation; improve docs

---

components/camel-hl7/pom.xml
parent/pom.xml

chore : add a special hapi-base-version so different versions of hapi-base and hapi-structures can be used

chore : add a a special hapi-base-version so different versions of hapi-base and hapi-structures can be used

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Version.java

(chores) fix checkstyle in camel-jbang

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Image.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Manifest.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/PropertiesHelper.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Version.java

Fix for https://issues.apache.org/jira/browse/CAMEL-18023

CAMEL-18023. Fix for prefix and formating

---

components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryPersistenceIT.java

(chores) camel-kafka: fix flaky idempotent test

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaProducer.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/errorhandler/KafkaErrorStrategies.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/errorhandler/ReconnectErrorStrategy.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/errorhandler/StopErrorStrategy.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/KafkaResumable.java
components/camel-kafka/src/main/java/org/apache/camel/processor/resume/kafka/AbstractKafkaResumeStrategy.java

camel-kafka: minor cleanups

---

camel-dependencies/pom.xml
parent/pom.xml

Issue: https://issues.apache.org/jira/browse/CAMEL-18047
Update of jakarta.mail to 1.6.7 and generated file modified by the change.

CAMEL-18047 Upgrade jakarta.mail to 1.6.7

---

components/camel-jsonpath/src/main/java/org/apache/camel/jsonpath/JsonPathEngine.java
components/camel-jsonpath/src/main/java/org/apache/camel/jsonpath/JsonPathExpression.java
components/camel-jsonpath/src/test/java/org/apache/camel/jsonpath/CustomObjectMapper.java
components/camel-jsonpath/src/test/java/org/apache/camel/jsonpath/JsonPathCustomMapperTest.java
components/camel-jsonpath/src/test/java/org/apache/camel/jsonpath/SpringJsonPathCustomReadMapperBeanTest.java
components/camel-jsonpath/src/test/resources/bignumbers.json
components/camel-jsonpath/src/test/resources/org/apache/camel/jsonpath/SpringJsonPathCustomReadMapperBeanTest.xml

Add unit tests showing use of custom ObjectMapper for both parsing
and serialization.

CAMEL-17956: use registered ObjectMapper when parsing json.

---

camel-dependencies/pom.xml
components/camel-azure/camel-azure-cosmosdb/src/main/java/org/apache/camel/component/azure/cosmosdb/CosmosDbComponent.java
components/camel-azure/camel-azure-eventhubs/src/main/java/org/apache/camel/component/azure/eventhubs/client/EventHubsClientFactory.java
components/camel-azure/camel-azure-storage-blob/pom.xml
components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/operations/DataLakeFileOperations.java
components/camel-azure/camel-azure-storage-datalake/src/test/java/org/apache/camel/component/azure/storage/datalake/component/DataLakeComponentTest.java
components/camel-azure/camel-azure-storage-datalake/src/test/java/org/apache/camel/component/azure/storage/datalake/integration/DataLakeFileOperationIT.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/RuntimeUtil.java
parent/pom.xml

CAMEL-18068: upgrade to com.azure:azure-sdk-bom:1.2.1

---

pom.xml

see https://issues.apache.org/jira/browse/CAMEL-18075

[CAMEL-18075] upgrade maven-bundle-plugin

---

components/camel-tracing/src/main/java/org/apache/camel/tracing/decorators/CqlSpanDecorator.java
components/camel-tracing/src/main/java/org/apache/camel/tracing/decorators/IronmqSpanDecorator.java
components/camel-tracing/src/main/java/org/apache/camel/tracing/decorators/JmsSpanDecorator.java
components/camel-tracing/src/main/java/org/apache/camel/tracing/decorators/NsqSpanDecorator.java
components/camel-tracing/src/main/java/org/apache/camel/tracing/decorators/SqlSpanDecorator.java
components/camel-tracing/src/test/java/org/apache/camel/tracing/MockSpanAdapter.java
components/camel-tracing/src/test/java/org/apache/camel/tracing/decorators/AbstractHttpSpanDecoratorTest.java
components/camel-tracing/src/test/java/org/apache/camel/tracing/decorators/CometdSpanDecoratorTest.java
components/camel-tracing/src/test/java/org/apache/camel/tracing/decorators/CqlSpanDecoratorTest.java
components/camel-tracing/src/test/java/org/apache/camel/tracing/decorators/IronmqSpanDecoratorTest.java
components/camel-tracing/src/test/java/org/apache/camel/tracing/decorators/JmsSpanDecoratorTest.java
components/camel-tracing/src/test/java/org/apache/camel/tracing/decorators/KafkaSpanDecoratorTest.java
components/camel-tracing/src/test/java/org/apache/camel/tracing/decorators/SqlSpanDecoratorTest.java
components/camel-tracing/src/test/java/org/apache/camel/tracing/decorators/StompSpanDecoratorTest.java

Cleanup camel-tracing codebase a bit

---

components/camel-openapi-java/src/main/java/org/apache/camel/openapi/RestModelConverters.java
components/camel-openapi-java/src/main/java/org/apache/camel/openapi/RestOpenApiReader.java
components/camel-openapi-java/src/test/java/org/apache/camel/openapi/RestOpenApiReaderTest.java
components/camel-openapi-java/src/test/java/org/apache/camel/openapi/RestOpenApiV3XOfTest.java
components/camel-openapi-java/src/test/java/org/apache/camel/openapi/model/OneOfForm.java
components/camel-openapi-java/src/test/java/org/apache/camel/openapi/model/OneOfFormWrapper.java
components/camel-openapi-java/src/test/java/org/apache/camel/openapi/model/XOfFormA.java
components/camel-openapi-java/src/test/java/org/apache/camel/openapi/model/XOfFormB.java

CAMEL-18066: Added discriminator support for oneOf, anyOf, allOf
CAMEL-18065: Added operation multi-tag support

CAMEL-18066, CAMEL-18065

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java

The run method is a little bit to large, causing checkstyle to fail

(chores) camel-jbang: fix checkstyle issue

---

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc

Fix few minor typos in Camel JBang documentation

---

components/camel-mongodb/src/generated/java/org/apache/camel/component/mongodb/converters/MongoDbBasicConvertersLoader.java
components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/converters/MongoDbBasicConverters.java
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbTypeConvertersTest.java

[CAMEL-18072] mongodb: add a type converter to convert from byte[] to Document

---

docs/user-manual/modules/ROOT/pages/getting-started.adoc

Changed "walk through" link text to be grammatically correct.

Update walk through link text

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/PropertiesHelper.java

Align PropertiesHelper with CamelJBangMain command change.
COMMAND_PREFIX = "camel"

Align PropertiesHelper with CamelJBangMain

---

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc

markdown style was used but it is an AsciiDoc file

Fix link syntax in Camel JBang debugging section

---

components/camel-aws/camel-aws2-kinesis/src/test/java/org/apache/camel/component/aws2/kinesis/integration/KinesisComponentManualIT.java

fixes  https://issues.apache.org/jira/browse/CAMEL-17994

CAMEL-17994 Camel-aws2-kinesis: Integration test does not work

---

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultStreamCachingStrategy.java

(chores) Minor cosmetic change on camel-base-engine to make checkstyle happy

---

components/camel-paho/src/main/java/org/apache/camel/component/paho/PahoConfiguration.java

When reading the documentation it was confusing why all of the LWT options had the same description and one had to carefully read the descriptions to find that it contains description for each of the options. This should be more clear what each option does.

[docs] Update LWT section to clarify what each option does

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Deploy.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Image.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/KubernetesHelper.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Undeploy.java

Username and password and/or token to push image / build to/in OpenShift/Kubernetes

Fixed login for OpenShift and Minikube

---

dsl/camel-yaml-dsl/camel-yaml-dsl/src/main/java/org/apache/camel/dsl/yaml/YamlRoutesBuilderLoader.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/IntegrationLoaderTest.groovy
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/RoutesBackwardsCompatibleTest.groovy
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/support/YamlTestSupport.groovy

CAMEL-18109: camel-yaml-dsl - Backwards compatible with route and steps

---

components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppBinding.java
components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppUtils.java
components/camel-smpp/src/test/java/org/apache/camel/component/smpp/SmppBindingTest.java
components/camel-smpp/src/test/java/org/apache/camel/component/smpp/SmppUtilsTest.java

The complete issue description can be found here: https://issues.apache.org/jira/browse/CAMEL-18110
I want this issue to be merged with the camel-3.14.x (LTS) branch but I had some problems with the auto-generated files.
The first commit resolves this issue, the other 2 are some minor issues I found along the way.

CAMEL-18110: DeliverSm message payload opt param fix

---

core/camel-core-model/src/main/java/org/apache/camel/builder/EndpointConsumerBuilder.java
core/camel-core-model/src/main/java/org/apache/camel/builder/EndpointProducerBuilder.java
core/camel-core-model/src/main/java/org/apache/camel/model/ProcessorDefinition.java
core/camel-core-reifier/src/main/java/org/apache/camel/reifier/ToDynamicReifier.java
core/camel-core-reifier/src/main/java/org/apache/camel/reifier/WireTapReifier.java
core/camel-xml-jaxb/src/main/java/org/apache/camel/xml/jaxb/JaxbHelper.java
dsl/camel-endpointdsl/src/main/java/org/apache/camel/builder/endpoint/AbstractEndpointBuilder.java
dsl/camel-endpointdsl/src/test/java/org/apache/camel/builder/endpoint/RawUrlPollEnrichTest.java
dsl/camel-endpointdsl/src/test/java/org/apache/camel/builder/endpoint/RawUrlWireTapDslTest.java

fixes https://issues.apache.org/jira/browse/CAMEL-17723
Hi @davsclaus , I implemented  the proposal from the https://issues.apache.org/jira/browse/CAMEL-17723 about raw-url (not encoded).
Simple JUnit covers the basic scenario. (`RawUrlPollEnrichTest`)
Do you think of any problems, which may be caused by not encoded urls in java DSL? (I was thinking about some possible security implications but I can not come with an example, where it could cause any damage)

CAMEL-17723 camel-ssh - Dynamic Header is not resolved in pollCommand.

---

components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Producer.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/AmazonSQSClientMock.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/SqsProducerDeleteQueueTest.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/SqsProducerPurgeTest.java

fixes https://issues.apache.org/jira/browse/CAMEL-18123

CAMEL-18123 Aws2-sqs: Operations Purge and Delete requires header

---

parent/pom.xml

Bump swagger-openapi3 to 2.1.13

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/DefaultKafkaManualAsyncCommit.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerAsyncManualCommitIT.java

This also includes a fix for a broken test case for the Async manual
commit.

CAMEL-18135: fixed incorrect sync commit of the async manual commit

---

components/camel-jmx/pom.xml
init/camel-bundle-plugin/pom.xml
parent/pom.xml
pom.xml

https://issues.apache.org/jira/browse/CAMEL-18136

[CAMEL-18136] use recent Bnd

---

components/camel-aws/camel-aws-secrets-manager/src/test/java/org/apache/camel/component/aws/secretsmanager/integration/SecretsManagerRotateSecretProducerLocalstackIT.java

(chores) camel-aws-secrets-manager: disable a test due to missing lambda

---

Jenkinsfile.s390x

Adding jenkinsfile to run jenkins job on s390x node using jdk11 
We have removed camel-kudu and docs module as these are not supported on s390x.

s390x jenkinsfile

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/KafkaProducerTest.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerAsyncManualCommitIT.java

camel-kafka test fixes

---

components/camel-netty-http/pom.xml
components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpAccessHttpRequestAndResponseBeanTest.java
components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpSimpleBasicAuthConstraintMapperTest.java
components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpSimpleBasicAuthTest.java
components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpSimplePooledExchangeTest.java

(chores) camel-netty-http: fix test execution on Github actions

---

components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/DefaultNettyHttpBinding.java
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/NettyHttpProducer.java
components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpLoopErrorTest.java

Signed-off-by: Rhuan Rocha <rhuan080@gmail.com>
- Fix the  [CAMEL-17949](https://issues.apache.org/jira/browse/CAMEL-17949)

CAMEL-17949 -  Infinite loop when setting retries

---

components/camel-azure/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BlobCopyProducerManualIT.java
components/camel-crypto/src/test/java/org/apache/camel/converter/crypto/HMACAccumulatorTest.java
components/camel-fhir/camel-fhir-component/src/test/java/org/apache/camel/component/fhir/UrlFetcherTest.java
components/camel-geocoder/src/test/java/org/apache/camel/component/geocoder/GeoCoderProxyManualIT.java
components/camel-http/src/test/java/org/apache/camel/component/http/HttpProducerLoadManualIT.java
components/camel-jetty/src/test/java/org/apache/camel/component/jetty/HttpProducerJMXBeansIssueManualIT.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsSendToAlotOfDestinationWithSameEndpointTest.java
components/camel-jmx/src/test/java/org/apache/camel/component/jmx/JMXObjectPropertiesTest.java
components/camel-mina/pom.xml
components/camel-mina/src/test/java/org/apache/camel/component/mina/MinaProducerShutdownManualIT.java
components/camel-nats/src/test/java/org/apache/camel/component/nats/NatsConsumerStopTest.java
components/camel-nats/src/test/java/org/apache/camel/component/nats/integration/NatsAuthProducerIT.java
components/camel-nats/src/test/java/org/apache/camel/component/nats/integration/NatsAuthTokenProducerIT.java
components/camel-nats/src/test/java/org/apache/camel/component/nats/integration/NatsProducerIT.java

This prevents bogus warnings for tests in SonarCloud.

Missing assertion fixes and proper manual IT test naming

---

components/camel-minio/src/main/java/org/apache/camel/component/minio/MinioConsumer.java

CAMEL-17100: minio consumer is slow at starting

---

components/camel-netty-http/pom.xml
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/DefaultNettyHttpBinding.java
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/NettyHttpProducer.java
components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpAccessHttpRequestAndResponseBeanTest.java
components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpLoopErrorTest.java
components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpSimpleBasicAuthConstraintMapperTest.java
components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpSimpleBasicAuthTest.java
components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpSimplePooledExchangeTest.java

Backport CAMEL-17949 and netty-http test fixes

---

components/camel-cxf/src/test/java/org/apache/camel/component/cxf/mtom/CxfJavaMtomProducerPayloadTest.java
components/camel-cxf/src/test/java/org/apache/camel/component/cxf/mtom/CxfMtomConsumerTest.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/mock/FaceVerificationWithImageBae64AndMockClientTest.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/mock/FaceVerificationWithImageFileAndMockClientTest.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/mock/FaceVerificationWithImageUrlAndMockClientTest.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/mock/LiveDetectionWithVideoBae64AndMockClientTest.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/mock/LiveDetectionWithVideoFileAndMockClientTest.java
components/camel-huawei/camel-huaweicloud-frs/src/test/java/org/apache/camel/component/huaweicloud/frs/mock/LiveDetectionWithVideoUrlAndMockClientTest.java

Fixed assertion order in camel-cxf and camel-huaweicloud-frs

---

components/camel-aws/camel-aws2-kinesis/src/test/java/org/apache/camel/component/aws2/kinesis/integration/KinesisConsumerIT.java

(chores) camel-aws2-kinesis: add IT for AWS Kinesis consumer

---

components/camel-aws/camel-aws2-kinesis/src/test/java/org/apache/camel/component/aws2/kinesis/integration/KinesisConsumerIT.java
components/camel-aws/camel-aws2-kinesis/src/test/java/org/apache/camel/component/aws2/kinesis/integration/KinesisConsumerResumeIT.java
test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/clients/KinesisUtils.java

CAMEL-18127: added integration test for Resume with AWS Kinesis

---

components/camel-spring-xml/src/test/java/org/apache/camel/spring/impl/converter/MyConverters.java
components/camel-spring-xml/src/test/java/org/apache/camel/spring/impl/converter/SpringTypeConvertersOverrideTest.java
components/camel-spring-xml/src/test/resources/log4j2.properties
components/camel-spring-xml/src/test/resources/org/apache/camel/spring/impl/converter/SpringTypeConvertersOverrideTest.xml

Unit test to reproduce bug in CAMEL-18160

---

components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/consumer/KinesisDefaultResumeAdapter.java
components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/consumer/KinesisOffset.java
components/camel-couchdb/src/main/java/org/apache/camel/component/couchdb/CouchDbChangesetTracker.java
components/camel-file/src/main/java/org/apache/camel/component/file/GenericFileConverter.java
components/camel-file/src/main/java/org/apache/camel/component/file/consumer/adapters/AbstractFileResumeAdapter.java
components/camel-file/src/main/java/org/apache/camel/component/file/consumer/adapters/DefaultFileOffsetResumeAdapter.java
components/camel-file/src/main/java/org/apache/camel/component/file/consumer/adapters/FileOffset.java
components/camel-file/src/main/java/org/apache/camel/component/file/consumer/adapters/FileResumeAdapterDelegate.java
components/camel-file/src/main/java/org/apache/camel/component/file/consumer/adapters/FileSet.java
components/camel-kafka/src/main/java/org/apache/camel/processor/resume/kafka/SingleNodeKafkaResumeStrategy.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerWithResumeRouteStrategyIT.java
core/camel-api/src/main/java/org/apache/camel/resume/Offset.java
core/camel-api/src/main/java/org/apache/camel/resume/OffsetKey.java
core/camel-api/src/main/java/org/apache/camel/resume/Resumable.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/resume/ResumableCompletion.java
core/camel-support/src/main/java/org/apache/camel/support/resume/OffsetKeys.java
core/camel-support/src/main/java/org/apache/camel/support/resume/Offsets.java
core/camel-support/src/main/java/org/apache/camel/support/resume/Resumables.java

CAMEL-18161: cleanup method names

---

components/camel-atom/pom.xml
components/camel-atom/src/test/java/org/apache/camel/component/atom/AtomPollingConsumerIdleMessageTest.java
components/camel-chatscript/pom.xml
components/camel-chatscript/src/test/java/org/apache/camel/component/ChatScriptComponentIT.java
components/camel-ignite/src/test/java/org/apache/camel/component/ignite/IgniteEventsTest.java
components/camel-ignite/src/test/java/org/apache/camel/component/ignite/IgniteMessagingTest.java
components/camel-mongodb/pom.xml
components/camel-mongodb/src/test/java/org/apache/camel/component/mongodb/integration/MongoDbTailableCursorConsumerIT.java

(chores) removed a few usages of Thread.sleep in test code

---

components/camel-cassandraql/src/test/java/org/apache/camel/processor/aggregate/cassandra/CassandraAggregationRepositoryIT.java
components/camel-cassandraql/src/test/java/org/apache/camel/processor/aggregate/cassandra/NamedCassandraAggregationRepositoryIT.java

(chores) camel-cassandraql: disable flaky tests on MacOS

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/BaseExport.java

chore: fix checkstyle

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/cql.json
components/camel-cassandraql/src/generated/resources/org/apache/camel/component/cassandra/cql.json
components/camel-cassandraql/src/main/java/org/apache/camel/component/cassandra/CassandraConstants.java
components/camel-cassandraql/src/main/java/org/apache/camel/component/cassandra/CassandraConsumer.java
components/camel-cassandraql/src/main/java/org/apache/camel/component/cassandra/consumer/support/CassandraResumeAdapter.java
components/camel-cassandraql/src/main/java/org/apache/camel/component/cassandra/consumer/support/DefaultCassandraResumeAdapter.java
components/camel-cassandraql/src/test/java/org/apache/camel/component/cassandra/integration/CassandraComponentResumeStrategyIT.java
core/camel-api/src/main/java/org/apache/camel/resume/ResumeAction.java

CAMEL-18127: make the resume actions reusable by other components

---

.github/workflows/alternative-os-build.yml

(chores) ci: do not fail fast on the matrix build for alternative OSes

---

tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/UpdateReadmeMojo.java

CAMEL-18181: prevent non-printable characters from breaking the doc generation

---

components/camel-slack/src/main/docs/slack-component.adoc
docs/user-manual/modules/ROOT/pages/parameter-binding-annotations.adoc

Fixing a couple of typos in the documentation

Typos in documentation

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/errorhandler/BridgeErrorStrategy.java

CAMEL-17424: do handle Authorization/Authentication issues when failling to poll

---

.gitattributes

Fore LF line endings in .adoc files during checkout.

CAMEL-18180 - Force LF endings in .adoc files

---

.github/workflows/alternative-os-build.yml
camel-dependencies/pom.xml
parent/pom.xml

More windows fixes

---

components/camel-jaxb/src/main/docs/jaxb-dataformat.adoc

Small fixes on JAXB DataFormat documentation.

---

docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_18.adoc

Signed-off-by: Rhuan Rocha <rhuan080@gmail.com>
Updating doc to notify the renaming of `keyResource`option

CAMEL-18170 - Updating Google Drive doc.

---

core/camel-api/src/main/java/org/apache/camel/Message.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultFluentProducerTemplate.java

Small fixes to error messages.

---

components/camel-mllp/src/test/java/org/apache/camel/test/tcp/JavaSocketManualTests.java
components/camel-mybatis/pom.xml
components/camel-mybatis/src/test/java/org/apache/camel/component/mybatis/MyBatisConsumerIdleMessageTest.java
components/camel-mybatis/src/test/java/org/apache/camel/component/mybatis/MyBatisQueueTest.java
components/camel-mybatis/src/test/java/org/apache/camel/component/mybatis/MyBatisShutdownAllTasksTest.java
components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpBasicAuthConstraintMapperTest.java
components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpBasicAuthCustomSecurityAuthenticatorTest.java
components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpSuspendResume503Test.java
components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpSuspendResumeTest.java
components/camel-netty/pom.xml
components/camel-netty/src/test/java/org/apache/camel/component/netty/ErrorDuringGracefullShutdownTest.java
components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/integration/RabbitMQDeadLetterRoutingKeyIT.java
components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/integration/RabbitMQProducerIT.java
components/camel-rabbitmq/src/test/java/org/apache/camel/component/rabbitmq/integration/spring/RabbitMQSpringIntTest.java

(chores) Thread.sleep cleanups in tests

---

components/camel-cassandraql/src/test/java/org/apache/camel/component/cassandra/integration/CassandraComponentConsumerIT.java
components/camel-cassandraql/src/test/java/org/apache/camel/component/cassandra/integration/CassandraComponentProducerIT.java
components/camel-cassandraql/src/test/java/org/apache/camel/component/cassandra/integration/CassandraComponentProducerUnpreparedIT.java
components/camel-cassandraql/src/test/java/org/apache/camel/processor/aggregate/cassandra/CassandraAggregationRepositoryIT.java
components/camel-cassandraql/src/test/java/org/apache/camel/processor/aggregate/cassandra/NamedCassandraAggregationRepositoryIT.java
components/camel-cassandraql/src/test/java/org/apache/camel/processor/idempotent/cassandra/CassandraIdempotentRepositoryIT.java
components/camel-cassandraql/src/test/java/org/apache/camel/processor/idempotent/cassandra/NamedCassandraIdempotentRepositoryIT.java

(chores) camel-cassandra: remove unecessary calls to String.format

---

components/camel-infinispan/camel-infinispan/src/main/docs/infinispan-component.adoc
components/camel-infinispan/camel-infinispan/src/main/java/org/apache/camel/component/infinispan/remote/InfinispanRemoteConfiguration.java

(docs) Fix formatting and clarify operations in infinispan docs

---

core/camel-core/src/test/java/org/apache/camel/processor/aggregator/AggregateCompletionOnlyTwoTest.java

(chores) camel-core: fix flaky test

---

Jenkinsfile

Also avoid overwriting analysis data from the main branch

Add analysis support for Camel 3.14.x

---

components/camel-sjms/src/main/java/org/apache/camel/component/sjms/SjmsComponent.java

[CAMEL-18195] Add setExceptionListener(...) to SjmsComponent

---

catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/RouteCoverageMojo.java
catalog/camel-route-parser/src/main/java/org/apache/camel/parser/RouteBuilderParser.java
catalog/camel-route-parser/src/main/java/org/apache/camel/parser/XmlRestDslParser.java
catalog/camel-route-parser/src/main/java/org/apache/camel/parser/XmlRouteParser.java
catalog/camel-route-parser/src/main/java/org/apache/camel/parser/helper/CamelJavaParserHelper.java
catalog/camel-route-parser/src/main/java/org/apache/camel/parser/helper/CamelJavaRestDslParserHelper.java
catalog/camel-route-parser/src/main/java/org/apache/camel/parser/helper/CamelJavaTreeParserHelper.java
catalog/camel-route-parser/src/main/java/org/apache/camel/parser/helper/CamelXmlRestDslParserHelper.java
catalog/camel-route-parser/src/main/java/org/apache/camel/parser/helper/CamelXmlTreeParserHelper.java
catalog/camel-route-parser/src/test/java/org/apache/camel/parser/java/RoasterChoiceRouteBuilderConfigureTest.java
catalog/camel-route-parser/src/test/java/org/apache/camel/parser/java/RoasterJavaDslTest.java
catalog/camel-route-parser/src/test/java/org/apache/camel/parser/java/RoasterJavaDslTwoRoutesTest.java
catalog/camel-route-parser/src/test/java/org/apache/camel/parser/java/RoasterJavaPartialRouteDslTest.java
catalog/camel-route-parser/src/test/java/org/apache/camel/parser/xml/XmlRestDslTest.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/AS2ClientManager.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/AS2ServerConnection.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/AS2ServerManager.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/EntityParser.java
components/camel-as2/camel-as2-api/src/test/java/org/apache/camel/component/as2/api/entity/EntityParserTest.java
components/camel-as2/camel-as2-component/src/main/java/org/apache/camel/component/as2/AS2Consumer.java
components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/multimap/HazelcastMultimapProducer.java
components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/replicatedmap/HazelcastReplicatedmapProducer.java
components/camel-mina/src/main/java/org/apache/camel/component/mina/MinaConsumer.java
components/camel-mina/src/main/java/org/apache/camel/component/mina/MinaProducer.java
components/camel-mllp/src/main/java/org/apache/camel/component/mllp/internal/TcpServerConsumerValidationRunnable.java
components/camel-mllp/src/main/java/org/apache/camel/component/mllp/internal/TcpSocketConsumerRunnable.java
components/camel-servlet/src/main/java/org/apache/camel/component/servlet/ServletComponent.java

(chores) removed unused method parameters

---

components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/consumer/KinesisDefaultResumeAdapter.java
components/camel-azure/camel-azure-key-vault/src/main/java/org/apache/camel/component/azure/key/vault/KeyVaultProducer.java
components/camel-hashicorp-vault/src/main/java/org/apache/camel/component/hashicorp/vault/HashicorpVaultProducer.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/errorhandler/SeekUtil.java
components/camel-zookeeper/src/main/java/org/apache/camel/component/zookeeper/cluster/ZooKeeperClusterService.java
core/camel-api/src/main/java/org/apache/camel/support/jsse/AliasedX509ExtendedKeyManager.java
core/camel-health/src/main/java/org/apache/camel/impl/health/DefaultHealthChecksLoader.java
dsl/camel-java-joor-dsl/src/main/java/org/apache/camel/dsl/java/joor/ClassRoutesBuilderLoader.java
dsl/camel-java-joor-dsl/src/main/java/org/apache/camel/dsl/java/joor/JavaRoutesBuilderLoader.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/GitHubHelper.java

Relatively minor cleanups

---

components/camel-lumberjack/pom.xml
components/camel-lumberjack/src/test/java/org/apache/camel/component/lumberjack/LumberjackMultiThreadTest.java
components/camel-lumberjack/src/test/java/org/apache/camel/component/lumberjack/io/LumberjackChannelInitializerTest.java
components/camel-mina/src/test/java/org/apache/camel/component/mina/MinaUdpNoCamelTest.java

(chores) test fixes and cleanups

---

components/camel-jq/src/main/java/org/apache/camel/language/jq/JqExpression.java
components/camel-jq/src/main/java/org/apache/camel/language/jq/JqFunctions.java
components/camel-jq/src/test/java/org/apache/camel/language/jq/JqExpressionFromHeaderAsStringTest.java
components/camel-jq/src/test/java/org/apache/camel/language/jq/JqExpressionFromHeaderTest.java
components/camel-jq/src/test/java/org/apache/camel/language/jq/JqExpressionHeaderFnTest.java
components/camel-jq/src/test/java/org/apache/camel/language/jq/JqExpressionPojoTest.java
components/camel-jq/src/test/java/org/apache/camel/language/jq/JqExpressionPropertyFnTest.java
components/camel-jq/src/test/java/org/apache/camel/language/jq/JqExpressionSimpleTest.java
components/camel-jq/src/test/java/org/apache/camel/language/jq/JqExpressionTest.java

camel-jq: add a function to retrieve value from Exchange properties

---

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/MultipartMimeEntity.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/util/EntityUtils.java
components/camel-aws/camel-aws-xray/src/main/java/org/apache/camel/component/aws/xray/decorators/messaging/AbstractMessagingSegmentDecorator.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/BindyKeyValuePairFactory.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/kvp/BindyKeyValuePairDataFormat.java
components/camel-cometd/src/main/java/org/apache/camel/component/cometd/CometdComponent.java
components/camel-cometd/src/main/java/org/apache/camel/component/cometd/CometdEndpoint.java
components/camel-cxf/src/main/java/org/apache/camel/component/cxf/DefaultCxfBinding.java
components/camel-cxf/src/main/java/org/apache/camel/component/cxf/interceptors/RawMessageWSDLGetInterceptor.java
components/camel-cxf/src/main/java/org/apache/camel/component/cxf/jaxrs/CxfRsInvoker.java
components/camel-cxf/src/main/java/org/apache/camel/component/cxf/jaxrs/CxfRsProducer.java
components/camel-google/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubComponent.java
components/camel-google/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubEndpoint.java
components/camel-google/camel-google-storage/src/main/java/org/apache/camel/component/google/storage/GoogleCloudStorageProducer.java
components/camel-gora/src/main/java/org/apache/camel/component/gora/GoraProducer.java
components/camel-gora/src/main/java/org/apache/camel/component/gora/utils/GoraUtils.java
components/camel-hashicorp-vault/src/main/java/org/apache/camel/component/hashicorp/vault/HashicorpVaultProducer.java
components/camel-iec60870/src/main/java/org/apache/camel/component/iec60870/AbstractIecComponent.java
components/camel-influxdb/src/main/java/org/apache/camel/component/influxdb/InfluxDbProducer.java
components/camel-irc/src/main/java/org/apache/camel/component/irc/IrcBinding.java
components/camel-irc/src/main/java/org/apache/camel/component/irc/IrcComponent.java
components/camel-irc/src/main/java/org/apache/camel/component/irc/IrcMessage.java
components/camel-irc/src/main/java/org/apache/camel/component/irc/IrcProducer.java
components/camel-leveldb/src/main/java/org/apache/camel/component/leveldb/serializer/AbstractLevelDBSerializer.java
components/camel-leveldb/src/main/java/org/apache/camel/component/leveldb/serializer/DefaultLevelDBSerializer.java
components/camel-mongodb-gridfs/src/main/java/org/apache/camel/component/mongodb/gridfs/GridFsEndpoint.java

Remove unused method parameters and fix CAMEL-18202

---

components/camel-kafka/src/main/java/org/apache/camel/processor/resume/kafka/KafkaResumeStrategyConfiguration.java
components/camel-kafka/src/main/java/org/apache/camel/processor/resume/kafka/KafkaResumeStrategyConfigurationBuilder.java
components/camel-kafka/src/main/java/org/apache/camel/processor/resume/kafka/MultiNodeKafkaResumeStrategy.java
components/camel-kafka/src/main/java/org/apache/camel/processor/resume/kafka/SingleNodeKafkaResumeStrategy.java
core/camel-api/src/main/java/org/apache/camel/resume/Cacheable.java
core/camel-api/src/main/java/org/apache/camel/resume/ResumeStrategy.java
core/camel-api/src/main/java/org/apache/camel/resume/ResumeStrategyConfiguration.java
core/camel-api/src/main/java/org/apache/camel/resume/ResumeStrategyConfigurationBuilder.java
core/camel-core-reifier/src/main/java/org/apache/camel/reifier/ResumableReifier.java
core/camel-support/src/main/java/org/apache/camel/support/resume/BasicResumeStrategyConfigurationBuilder.java

CAMEL-18128: initial implementation

---

Jenkinsfile

(chores) ci: avoid deploying to the Maven repo for regular build

---

components/camel-mongodb-gridfs/src/main/java/org/apache/camel/component/mongodb/gridfs/GridFsEndpoint.java

(backport) CAMEL-18202: fix incorrectly setting the initial delay

---

components/camel-debug/src/main/java/org/apache/camel/component/debug/JmxConnectorService.java
components/camel-google/camel-google-bigquery/src/main/java/org/apache/camel/component/google/bigquery/sql/GoogleBigQuerySQLProducer.java
components/camel-jira/src/main/java/org/apache/camel/component/jira/consumer/AbstractJiraConsumer.java
components/camel-jira/src/main/java/org/apache/camel/component/jira/consumer/NewIssuesConsumer.java
components/camel-mock/src/main/java/org/apache/camel/component/mock/TimeClause.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQMessageConverter.java
components/camel-test/camel-test-spring-junit5/src/main/java/org/apache/camel/test/spring/junit5/RouteCoverageDumper.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java
core/camel-console/src/main/java/org/apache/camel/impl/console/DefaultDevConsolesLoader.java

(chores) log message cleanups

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade Mybatis to version 3.5.10

---

docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_18.adoc

Camel-18170 - google calendar doc

---

components/camel-http-common/src/main/java/org/apache/camel/http/common/DefaultHttpRegistry.java
components/camel-http-common/src/main/java/org/apache/camel/http/common/HttpServletResolveConsumerStrategy.java
components/camel-http/src/main/java/org/apache/camel/component/http/HttpComponent.java
components/camel-http/src/main/java/org/apache/camel/component/http/HttpProducer.java
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/NettyHttpHelper.java
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/NettyHttpProducer.java
components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpSupport.java
components/camel-resteasy/src/main/java/org/apache/camel/component/resteasy/ResteasyComponent.java

(chores) removed unused parameters (http-related components)

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportQuarkus.java

(chores) camel-jbang: fixed checkstyle

---

docs/user-manual/modules/ROOT/pages/debugger.adoc

Include more examples of debugger using the BacklogDebugger

---

components/camel-netty/src/main/java/org/apache/camel/component/netty/NettyHelper.java
components/camel-netty/src/main/java/org/apache/camel/component/netty/NettyProducer.java
components/camel-netty/src/main/java/org/apache/camel/component/netty/handlers/ServerChannelHandler.java

(chores) camel-netty: removed unused parameters

---

camel-dependencies/pom.xml
components/camel-as2/camel-as2-api/pom.xml
components/camel-asn1/pom.xml
components/camel-asn1/src/main/docs/asn1-dataformat.adoc
components/camel-crypto/pom.xml
components/camel-fop/pom.xml
components/camel-ftp/pom.xml
components/camel-jsch/pom.xml
components/camel-pdf/pom.xml
components/camel-ssh/pom.xml
components/camel-ssh/src/main/docs/ssh-component.adoc
components/camel-xmlsecurity/pom.xml
parent/pom.xml

CAMEL-18122: Upgrade to bouncycastle 1.71

---

components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/NettyHttpComponent.java
components/camel-netty/src/main/java/org/apache/camel/component/netty/handlers/ServerChannelHandler.java

(chores) Removes a few more unused parameters in netty code

---

components/camel-test/camel-test-spring-junit5/src/main/java/org/apache/camel/test/spring/junit5/CamelAnnotationsHandler.java
components/camel-test/camel-test-spring-junit5/src/main/java/org/apache/camel/test/spring/junit5/CamelSpringBootExecutionListener.java
components/camel-test/camel-test-spring-junit5/src/main/java/org/apache/camel/test/spring/junit5/CamelSpringTestContextLoader.java
components/camel-test/camel-test-spring/src/main/java/org/apache/camel/test/spring/CamelAnnotationsHandler.java
components/camel-test/camel-test-spring/src/main/java/org/apache/camel/test/spring/CamelSpringDelegatingTestContextLoader.java
components/camel-test/camel-test-spring/src/main/java/org/apache/camel/test/spring/CamelSpringTestContextLoader.java

(chores) removed unused parameters in camel-test

---

components/camel-spring-security/src/main/java/org/apache/camel/component/spring/security/DefaultAuthenticationAdapter.java
components/camel-spring-xml/src/main/java/org/apache/camel/spring/xml/ContextScanRouteBuilderFinder.java
components/camel-spring/src/main/java/org/apache/camel/spring/spi/TransactionErrorHandlerReifier.java

(chores) spring components: removed or documented unused parameters

---

core/camel-main/src/main/java/org/apache/camel/main/BaseMainSupport.java
core/camel-main/src/main/java/org/apache/camel/main/DefaultRoutesCollector.java
core/camel-main/src/main/java/org/apache/camel/main/MainSupportModelConfigurer.java

(chores) camel-core-main: removed unused parameters

---

components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/CamelTestSupport.java

fixes https://issues.apache.org/jira/browse/CAMEL-18219
The same check as is for spring boot makes sense also for quarkus.

Enhance CamelTestSupport with a check to not run on quarkus

---

components/camel-jira/src/main/java/org/apache/camel/component/jira/producer/AddIssueProducer.java
components/camel-jira/src/main/java/org/apache/camel/component/jira/producer/UpdateIssueProducer.java
components/camel-jira/src/main/java/org/apache/camel/component/jira/producer/WatcherProducer.java
components/camel-jira/src/test/java/org/apache/camel/component/jira/Utils.java
components/camel-jira/src/test/java/org/apache/camel/component/jira/producer/AddIssueProducerTest.java
components/camel-jira/src/test/java/org/apache/camel/component/jira/producer/TransitionIssueProducerTest.java
components/camel-jira/src/test/java/org/apache/camel/component/jira/producer/UpdateIssueProducerTest.java
components/camel-jira/src/test/java/org/apache/camel/component/jira/producer/WatcherProducerTest.java

* the "components" field was not updated due to a bug in handling the
field
* Added tests for the component field
* Fixed the "components" field description
https://issues.apache.org/jira/browse/CAMEL-18218

Fix camel-jira not adding components field (3.14.x branch)

---

components/camel-corda/src/main/java/org/apache/camel/component/corda/CordaProducer.java
components/camel-infinispan/camel-infinispan-common/src/main/java/org/apache/camel/component/infinispan/InfinispanProducer.java
components/camel-seda/src/main/java/org/apache/camel/component/seda/SedaProducer.java
components/camel-web3j/src/main/java/org/apache/camel/component/web3j/Web3jProducer.java
core/camel-support/src/main/java/org/apache/camel/support/EventDrivenPollingConsumer.java
core/camel-support/src/main/java/org/apache/camel/support/ExchangeHelper.java
core/camel-support/src/main/java/org/apache/camel/support/HeaderSelectorProducer.java
core/camel-support/src/main/java/org/apache/camel/support/builder/TokenPairExpressionIterator.java

Also updates camel-corda, camel-infinispan and camel-web3j to adjust the
calls to the affected methods.

(chores) camel-support: removed unused parameters

---

components/camel-atmos/src/main/java/org/apache/camel/component/atmos/dto/AtmosFileUploadResult.java

(chores) camel-atmos: minor cleanups

---

components/camel-cxf/src/test/java/org/apache/camel/component/cxf/CxfConsumerWithTryCatchTest.java
components/camel-cxf/src/test/java/org/apache/camel/component/cxf/CxfSimpleRouterWithUnwrappedStyleTest.java
components/camel-cxf/src/test/java/org/apache/camel/component/cxf/jaxrs/JettyCxfRsRouterTest.java

(chores) camel-cxf: fixed incorrectly disabled tests

---

components/camel-openstack/src/test/java/org/apache/camel/component/openstack/it/OpenstackCinderVolumeTest.java
components/camel-openstack/src/test/java/org/apache/camel/component/openstack/it/OpenstackGlanceTest.java
components/camel-openstack/src/test/java/org/apache/camel/component/openstack/it/OpenstackKeystoneDomainTest.java
components/camel-openstack/src/test/java/org/apache/camel/component/openstack/it/OpenstackKeystoneGroupTest.java
components/camel-openstack/src/test/java/org/apache/camel/component/openstack/it/OpenstackKeystoneProjectTest.java
components/camel-openstack/src/test/java/org/apache/camel/component/openstack/it/OpenstackKeystoneRegionTest.java
components/camel-openstack/src/test/java/org/apache/camel/component/openstack/it/OpenstackKeystoneUserTest.java
components/camel-openstack/src/test/java/org/apache/camel/component/openstack/it/OpenstackNeutronNetworkTest.java

(chores) camel-openstack: fixed missing assertions

---

components/camel-spring-xml/src/test/java/org/apache/camel/spring/management/JmxInstrumentationWithConnectorTest.java
components/camel-spring-xml/src/test/java/org/apache/camel/spring/processor/SpringLoopDoWhileTest.java
components/camel-spring-xml/src/test/java/org/apache/camel/spring/xml/SpringXmlRouteBuilderTest.java

(chores) camel-spring-xml: fixed incorrectly disabled tests

---

core/camel-core/src/test/java/org/apache/camel/component/log/DefaultExchangeFormatterTest.java
core/camel-core/src/test/java/org/apache/camel/component/log/LogMaskTest.java
core/camel-core/src/test/java/org/apache/camel/component/log/LogRouteTest.java

(chores) camel-core: fixed missing or incorrect assertions

---

components/camel-jira/src/test/java/org/apache/camel/component/jira/producer/AddIssueProducerTest.java

(chores) camel-jira: fixed invalid assertion

---

components/camel-olingo2/camel-olingo2-component/src/test/java/org/apache/camel/component/olingo2/Olingo2AppAPITest.java

(chores) camel-olingo2: fixed missing assertions

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Export.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportCamelMain.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportQuarkus.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportSpringBoot.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/RuntimeUtil.java

(chores) camel-jbang: fixed leaky streams

---

core/camel-core-engine/src/main/docs/modules/eips/pages/message-bus.adoc

[MessageBus] Fix doc link

---

components/camel-kamelet/src/main/docs/kamelet-component.adoc
components/camel-microprofile/camel-microprofile-fault-tolerance/src/main/docs/microprofile-fault-tolerance.adoc

IIUC, in kamelet component the `templateId` is `setMyBody` - based on definition of path parameter `templateId`

Typos in kamelet component and added link in MicroProfile Fault Tolerance component documentation

---

core/camel-core-engine/src/main/docs/modules/eips/pages/pipeline-eip.adoc

Fix pipeline eip doc

---

core/camel-core-engine/src/main/docs/modules/eips/pages/pollEnrich-eip.adoc

Fix example in pollEnrich eip doc

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/KafkaRecordProcessor.java

The exception is already processed by the error handler and set on the Exchange but not propagated.
This change was introduced in the refactoring b86c25511c9a02690547f4b45d645d18f56a3866.

CAMEL-17925: Process exception in exchange and not only in catch.

---

components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsAutoStartupTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsMultipleConsumersTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsAnotherCustomJMSReplyToTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsReplyToLoopIssueTest.java

(chores) camel-jms: removed a few Thread.sleep in tests

---

core/camel-api/src/main/java/org/apache/camel/resume/cache/ResumeCache.java
core/camel-support/src/main/java/org/apache/camel/support/resume/AdapterHelper.java

(chores) resume-api: use constants for referring to the bean names

---

components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsDurableTopicTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsInOutFixedReplyQueueTimeoutTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsInOutFixedReplyQueueTimeoutUseMessageIDAsCorrelationIDTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsInOutIndividualRequestTimeoutTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsRequestReplyTempQueueMultipleConsumersTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsConcurrentConsumersTest.java

It should be safe, but if anyone has time, it would be good to review these.

(chores) camel-jms: more test cleanups

---

docs/user-manual/modules/ROOT/pages/debugger.adoc

before PR: ![Screenshot from 2022-06-28 13-44-48](https://user-images.githubusercontent.com/1105127/176170671-52c619dd-d086-4dc7-b6a2-eaf34debc063.png)

Render unordered list in doc correctly

---

core/camel-core-engine/src/main/docs/modules/eips/pages/resume-strategies.adoc

CAMEL-18128: added a few details about configuring the builtin strategies

---

components/camel-paho-mqtt5/src/main/docs/paho-mqtt5-component.adoc

[DOCS] Fix typos in paho-mqtt5 component docs

---

core/camel-core-engine/src/main/docs/modules/eips/pages/message-dispatcher.adoc

Polished docs

---

components/camel-jms/src/test/java/org/apache/camel/component/jms/temp/JmsReconnectManualTest.java

(chores) camel-jms: renamed manual test

---

camel-dependencies/pom.xml
parent/pom.xml

CAMEL-18247: Upgrade to test-containers 1.17.3

---

components/camel-hbase/src/main/java/org/apache/camel/component/hbase/HBaseProducer.java
components/camel-hbase/src/main/java/org/apache/camel/component/hbase/mapping/CellMappingStrategyFactory.java

camel-hbase: fix deprecation warnings

---

components/camel-quartz/pom.xml
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzAutoStartTest.java
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzRouteRestartTest.java
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/SpringQuartzPersistentStoreRestartRouteTest.java
components/camel-quartz/src/test/java/org/apache/camel/routepolicy/quartz/CronScheduledRoutePolicyTest.java
components/camel-quartz/src/test/java/org/apache/camel/routepolicy/quartz/SimpleScheduledRoutePolicyTest.java

- Fix a few test cases that were not being run
- A couple of Thread.sleep removals
- Cleanup some exception tests

(chores) camel-quartz: test cleanups

---

components/camel-saxon/src/main/docs/xquery-component.adoc
components/camel-timer/src/main/docs/timer-component.adoc

- XQuery component: typo, broken link to w3schools tutorial
- Timer component: typos, formatting of parameters

Documentation of XQuery, Timer components - typos and formatting

---

components/camel-gora/pom.xml

CAMEL-18246: Upgrade hadoop-common version in camel-gora

---

components/camel-jq/src/main/java/org/apache/camel/language/jq/JqExpression.java
components/camel-jq/src/test/java/org/apache/camel/language/jq/JqExpressionTest.java

jq: don't load additional functions for provided Scope instance

---

catalog/camel-route-parser/src/main/java/org/apache/camel/parser/RouteBuilderParser.java
catalog/camel-route-parser/src/main/java/org/apache/camel/parser/helper/CamelJavaParserHelper.java
catalog/camel-route-parser/src/main/java/org/apache/camel/parser/helper/CamelJavaRestDslParserHelper.java

(chores) camel-route-parser: remove duplicated parsing-related code

---

components/camel-jolt/src/main/java/org/apache/camel/component/jolt/JoltEndpoint.java
parent/pom.xml

Upgrade to Jolt version 0.1.7

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerHealthCheckIT.java

Also comes with a small log message cleanup

CAMEL-18237: fix camel health integration test

---

components/camel-kafka/src/main/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepository.java
components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryEagerIT.java
components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryNonEagerIT.java
components/camel-kafka/src/test/java/org/apache/camel/processor/idempotent/kafka/KafkaIdempotentRepositoryPersistenceIT.java

This removes the counter from the KafkaIdempotentRepository since duplicates are already correctly accounted for in the IdempotentConsumer class

CAMEL-18253: prevent the code from reporting an invalid number of duplicates

---

core/camel-core/src/test/java/org/apache/camel/processor/OnCompletionBridgeErrorHandler.java
core/camel-support/src/main/java/org/apache/camel/support/BridgeExceptionHandlerToErrorHandler.java

@davsclaus : Maybe last commit for 3.18 LTS if okay for you?

CAMEL-18252: Add exception to exchange as property CamelExceptionCaught

---

camel-dependencies/pom.xml
parent/pom.xml

CAMEL-18246: Upgrade hadoop3-version to 3.3.3

---

core/camel-support/src/main/java/org/apache/camel/support/ObjectHelper.java
core/camel-support/src/main/java/org/apache/camel/support/builder/TokenXMLExpressionIterator.java
core/camel-support/src/main/java/org/apache/camel/support/management/MixinRequiredModelMBean.java

Simple cleanup to test some changes on my setup :)

(chores) camel-support: removed redundant conditions

---

core/camel-support/src/main/java/org/apache/camel/support/IntrospectionSupport.java

(chores) camel-support: a few more minor cleanups

---

components/camel-activemq/src/main/java/org/apache/camel/component/activemq/ActiveMQQueueEndpoint.java
components/camel-aws/camel-aws-secrets-manager/src/main/java/org/apache/camel/component/aws/secretsmanager/SecretsManagerPropertiesFunction.java
components/camel-aws/camel-aws2-ddb/src/main/java/org/apache/camel/component/aws2/ddbstream/Ddb2StreamComponentVerifierExtension.java
components/camel-cxf/camel-cxf-transport/src/main/java/org/apache/camel/component/cxf/transport/CamelOutputStream.java
components/camel-jms/src/main/java/org/apache/camel/component/jms/JmsEndpoint.java
components/camel-jms/src/main/java/org/apache/camel/component/jms/JmsQueueEndpoint.java
components/camel-mllp/src/main/java/org/apache/camel/component/mllp/MllpConfiguration.java
core/camel-api/src/main/java/org/apache/camel/spi/PackageScanClassResolver.java
dsl/camel-dsl-support/src/main/java/org/apache/camel/dsl/support/RouteBuilderLoaderSupport.java

(chores) removed unused imports

---

core/camel-core/src/generated/resources/META-INF/services/org/apache/camel/other.properties
core/camel-core/src/generated/resources/core.json
core/camel-core/src/test/java/org/apache/camel/builder/ExceptionBuilderTest.java

(chores) camel-core: fix misleading test failure messages

---

core/camel-util/src/test/java/org/apache/camel/util/URISupportTest.java
core/camel-util/src/test/java/org/apache/camel/util/concurrent/SizedScheduledExecutorServiceTest.java

(chores) camel-util: cleanup exception tests

---

components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/FtpConsumer.java

Minor cleanup on the FTP Consumer to reduce complexity (and to see if
our infra is finally stable after 3.18 release)

(chores) camel-ftp: minor FtpConsumer cleanup

---

core/camel-base-engine/src/main/java/org/apache/camel/impl/debugger/BacklogDebugger.java
core/camel-management/src/test/java/org/apache/camel/management/BacklogDebuggerTest.java

Backport of https://github.com/apache/camel/pull/7991 in branch 3.18 for https://issues.apache.org/jira/browse/CAMEL-18260

CAMEL-18260: debugger - Reflect exchange changes on BacklogTracerEventMessage

---

core/camel-support/src/main/java/org/apache/camel/support/ResourceHelper.java

https://issues.apache.org/jira/browse/CAMEL-18266

CAMEL-18266 - camel-support: add bean in schema checking

---

components/camel-aws/camel-aws2-eventbridge/src/test/java/org/apache/camel/component/aws2/eventbridge/localstack/EventbridgeDeleteRuleIT.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/integration/SqsProducerSendByteArrayLocalstackIT.java

✅ [CAMEL-18281] Fix failing aws test

---

components/camel-azure/camel-azure-key-vault/src/main/java/org/apache/camel/component/azure/key/vault/KeyVaultPropertiesFunction.java
components/camel-hashicorp-vault/src/main/java/org/apache/camel/component/hashicorp/vault/HashicorpVaultPropertiesFunction.java
core/camel-main/src/main/java/org/apache/camel/main/DefaultConfigurationConfigurer.java

💄 [CAMEL-18282] Fix checkstyle errors

---

dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

[CAMEL-18283] Upgrade Camel to 3.18.0 by default for Camel JBang

---

components/camel-aws/camel-aws2-ddb/src/main/docs/aws2-ddb-component.adoc

📝 Add aws ddb examples

---

docs/user-manual/modules/ROOT/pages/clustering.adoc

Polish clustering docs

---

test-infra/camel-test-infra-couchbase/src/test/java/org/apache/camel/test/infra/couchbase/services/CouchbaseLocalContainerService.java

✅ [CAMEL-18295] Restore couchbase IT tests

---

camel-dependencies/pom.xml
parent/pom.xml

Hello, most of the upgrades are minor version updates, but the graphql one is quite a big one, camel-graphql tests are successful, is it enough?

⬆️ [CAMEL-18294] Align to spring boot 2.7.2

---

components/camel-github/src/main/java/org/apache/camel/component/github/producer/ClosePullRequestProducer.java
components/camel-github/src/main/java/org/apache/camel/component/github/producer/PullRequestCommentProducer.java
components/camel-jira/src/main/java/org/apache/camel/component/jira/producer/AddIssueProducer.java
components/camel-pubnub/src/main/java/org/apache/camel/component/pubnub/PubNubProducer.java
components/camel-twitter/src/main/java/org/apache/camel/component/twitter/timeline/UserProducer.java
core/camel-support/src/main/java/org/apache/camel/support/ExchangeHelper.java

CAMEL-17760: consolidate copy-exchange-if-capable logic

---

components/camel-file/src/main/java/org/apache/camel/component/file/FileConsumer.java
components/camel-file/src/main/java/org/apache/camel/component/file/GenericFile.java

Issue: https://issues.apache.org/jira/browse/CAMEL-18285

[CAMEL-18285] Lazy-loading for file length and last modified attributes

---

components/camel-smpp/src/main/java/org/apache/camel/component/smpp/AbstractSmppCommand.java
components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppCancelSmCommand.java
components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppDataSmCommand.java
components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppQuerySmCommand.java
components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppReplaceSmCommand.java
components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppSubmitMultiCommand.java
components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppSubmitSmCommand.java
components/camel-smpp/src/test/java/org/apache/camel/component/smpp/AbstractSmppCommandTest.java

(chores) camel-smpp: remove duplicated result message logic

---

components/camel-soap/src/main/java/org/apache/camel/dataformat/soap/name/ServiceInterfaceStrategy.java

Fix error message

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConsumerHealthCheck.java
components/camel-microprofile/camel-microprofile-health/src/main/java/org/apache/camel/microprofile/health/CamelMicroProfileHealthHelper.java

- Fix potential NPE
- Don't add null values in HealthCheck.Result details

Fix potential NPE in Kafka health checks

---

docs/user-manual/modules/ROOT/pages/debugger.adoc

seems an empty line is required with most of the renderers of asciidoc

Fix layout for list in doc page for debugger

---

components/camel-mina/src/main/java/org/apache/camel/component/mina/MinaConsumer.java

(chores) camel-mina: cleaned up duplicated code

---

Jenkinsfile
Jenkinsfile.jdk11
Jenkinsfile.jdk17

(chores) ci: do run Build and Install stage for LTS branches

---

Jenkinsfile
Jenkinsfile.jdk11
Jenkinsfile.jdk17

(chores) ci: fix up the JDK based builds on Apache CI

---

components/camel-http-base/pom.xml
components/camel-http-base/src/main/java/org/apache/camel/http/base/HttpHelper.java
components/camel-http-base/src/test/java/org/apache/camel/http/base/HttpHelperTest.java
components/camel-jetty-common/src/main/java/org/apache/camel/component/jetty/JettyRestHttpBinding.java
components/camel-netty-http/src/main/java/org/apache/camel/component/netty/http/RestNettyHttpBinding.java
components/camel-servlet/src/main/java/org/apache/camel/component/servlet/ServletRestHttpBinding.java
components/camel-undertow/src/main/java/org/apache/camel/component/undertow/RestUndertowHttpBinding.java

(chores) http components: consolidate placeholder eval logic

---

.github/workflows/pr-build.yml

(chores) ci: perform CI builds for the LTS branches on PRs

---

components/camel-cxf/camel-cxf-rest/src/main/java/org/apache/camel/component/cxf/jaxrs/CxfRsProducer.java
components/camel-cxf/camel-cxf-soap/src/main/java/org/apache/camel/component/cxf/jaxws/CxfConsumer.java
components/camel-cxf/camel-cxf-soap/src/main/java/org/apache/camel/component/cxf/jaxws/CxfProducer.java
components/camel-cxf/camel-cxf-spring-soap/src/main/java/org/apache/camel/component/cxf/spring/jaxws/CxfSpringEndpoint.java

(chores) camel-cxf: avoid shadowing variables

---

components/camel-kafka/src/main/docs/kafka-component.adoc
components/camel-test/src/main/docs/test.adoc

Doc fixes in camel 2.x 

---

core/camel-core-engine/src/main/docs/modules/eips/pages/choice-eip.adoc

Fix typo YAML DS -> YAML DSL in doc

---

dsl/camel-endpointdsl/src/test/java/org/apache/camel/builder/endpoint/BaseEndpointDslTest.java
dsl/camel-endpointdsl/src/test/java/org/apache/camel/builder/endpoint/DumpRoutesTest.java
dsl/camel-endpointdsl/src/test/java/org/apache/camel/builder/endpoint/FileConsumeCharsetTest.java
dsl/camel-endpointdsl/src/test/java/org/apache/camel/builder/endpoint/FileDelayTest.java

This helps prevents misbehaved tests from causing other tests to fail

(chores) camel-endpointdsl: use unique data directory for tests

---

components/camel-hl7/pom.xml
parent/pom.xml

chore : add a a special hapi-base-version so different versions of hapi-base and hapi-structures can be used (#7519)

---

core/camel-core-engine/src/main/docs/modules/eips/pages/pipeline-eip.adoc

Update pipeline-eip.adoc - fix Java example snippet

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java

This fixes 2 small and related issues: 
- CAMEL-17947: remove unnecessary consumer close
- CAMEL-18327: remove unnecessary consumer unsubscription
We probably need to backport these to 3.18 and (I guess) 3.14.

CAMEL-17947 + CAMEL-18327

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/TaskHealthState.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerBadPortHealthCheckIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerBadPortSupervisingHealthCheckIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerUnresolvableHealthCheckIT.java

CAMEL-18333: camel-kafka - better error messages during health check

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/TaskHealthState.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerBadPortHealthCheckIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerBadPortSupervisingHealthCheckIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerUnresolvableHealthCheckIT.java

Backport several Kafka fixes

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerAsyncManualCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerBadPortHealthCheckIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerBadPortSupervisingHealthCheckIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerFullIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerHealthCheckIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentWithCustomSerializerIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentWithProcessorIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerTopicIsPatternIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerUnresolvableHealthCheckIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/commit/KafkaConsumerAsyncCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/commit/KafkaConsumerNoopCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/commit/KafkaConsumerSyncCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/pause/KafkaPausableConsumerCircuitBreakerIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/pause/KafkaPausableConsumerIT.java

Hopefully this fixes some of the flaky tests we have (at least they
stopped being flaky on my test box)

(chores) camel-kafka: fix flaky tests

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerAsyncManualCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerBadPortHealthCheckIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerBadPortSupervisingHealthCheckIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerFullIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerHealthCheckIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentWithCustomSerializerIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentWithProcessorIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerTopicIsPatternIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerUnresolvableHealthCheckIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/commit/KafkaConsumerNoopCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/commit/KafkaConsumerSyncCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/pause/KafkaPausableConsumerCircuitBreakerIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/pause/KafkaPausableConsumerIT.java
test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/KafkaServiceFactory.java
test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/StrimziService.java

These should improve the execution time of the Kafka tests. Also contains a fix for CAMEL-18347.

Kafka test improvements

---

test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/ContainerLocalKafkaService.java

Provided by CP 7.2.1
https://docs.confluent.io/platform/current/release-notes/index.html

(chores) camel-test-infra-kafka: upgrade Kafka 3 test image to 3.2.0

---

components/camel-arangodb/src/test/java/org/apache/camel/component/arangodb/integration/BaseArangoDb.java
test-infra/camel-test-infra-arangodb/src/test/java/org/apache/camel/test/infra/arangodb/services/ArangoDBServiceFactory.java
test-infra/camel-test-infra-hbase/src/test/java/org/apache/camel/test/infra/hbase/services/HBaseServiceFactory.java
test-infra/camel-test-infra-mongodb/src/test/java/org/apache/camel/test/infra/mongodb/services/MongoDBServiceFactory.java

CAMEL-18347: fixes for different test infra services

---

components/camel-couchbase/src/test/java/org/apache/camel/component/couchbase/integration/CouchbaseIntegrationTestBase.java
components/camel-couchdb/src/test/java/org/apache/camel/component/couchdb/integration/CouchDbTestSupport.java
test-infra/camel-test-infra-couchdb/src/test/java/org/apache/camel/test/infra/couchdb/services/CouchDbServiceFactory.java

More test fixes and improvements

---

components/camel-arangodb/src/test/java/org/apache/camel/component/arangodb/integration/BaseArangoDb.java
test-infra/camel-test-infra-arangodb/src/test/java/org/apache/camel/test/infra/arangodb/services/ArangoDBServiceFactory.java
test-infra/camel-test-infra-hbase/src/test/java/org/apache/camel/test/infra/hbase/services/HBaseServiceFactory.java
test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/KafkaServiceFactory.java
test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/StrimziService.java
test-infra/camel-test-infra-mongodb/src/test/java/org/apache/camel/test/infra/mongodb/services/MongoDBServiceFactory.java

Also contains related fixes that make the tests work with those fixes

Backport CAMEL-18347

---

components/camel-kafka/pom.xml
test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/KafkaServiceFactory.java

Defaults to Kafka 3 for testing

---

camel-dependencies/pom.xml
parent/pom.xml

CAMEL-18353: Upgrade to JUnit 5.9.0

---

components/camel-bean-validator/src/main/docs/bean-validator-component.adoc

Use latest version doc

---

core/camel-core/src/test/java/org/apache/camel/processor/OnCompletionAfterChainedSedaRoutes.java
core/camel-core/src/test/java/org/apache/camel/processor/OnCompletionBeforeChainedSedaRoutes.java

Test amendments to the #8105 following-up [this discussion](https://github.com/apache/camel/pull/8105#discussion_r936853481).

CAMEL-18275: Amend the OnCompletion Chained Seda Routes tests to check the order of competions execution

---

components/camel-kafka/src/main/java/org/apache/camel/processor/resume/kafka/SingleNodeKafkaResumeStrategy.java

CAMEL-18362 + minor fixes

---

components/camel-file/src/main/docs/file-component.adoc
components/camel-ftp/src/main/docs/ftp-component.adoc

Add an example to https://camel.apache.org/components/3.18.x/ftp-component.html#_filtering_using_ant_path_matcher @oscerd , is the example enough?

📝 Add Ant missing example

---

camel-dependencies/pom.xml
parent/pom.xml

CAMEL-17748: Upgrade to apache any23 2.7

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade apache spark to 3.2.2

---

camel-dependencies/pom.xml
parent/pom.xml

cherry pick of jython upgrade from main; upgrade camel-dependencies jython version as well

Upgrade jython version to 2.7.2

---

components/camel-file/src/main/java/org/apache/camel/component/file/consumer/adapters/FileResumeAdapterDelegate.java
components/camel-kafka/src/main/java/org/apache/camel/processor/resume/kafka/KafkaResumeStrategyConfiguration.java
components/camel-kafka/src/main/java/org/apache/camel/processor/resume/kafka/KafkaResumeStrategyConfigurationBuilder.java
components/camel-kafka/src/main/java/org/apache/camel/processor/resume/kafka/SingleNodeKafkaResumeStrategy.java

CAMEL-18362 + CAMEL-18371

---

components/camel-file/src/main/java/org/apache/camel/component/file/consumer/adapters/FileResumeAdapterDelegate.java

(Backport) CAMEL-18371: do load the cache when resuming with the file component

---

components/camel-kafka/src/main/java/org/apache/camel/processor/resume/kafka/KafkaResumeStrategyConfiguration.java
components/camel-kafka/src/main/java/org/apache/camel/processor/resume/kafka/KafkaResumeStrategyConfigurationBuilder.java
components/camel-kafka/src/main/java/org/apache/camel/processor/resume/kafka/MultiNodeKafkaResumeStrategy.java
components/camel-kafka/src/main/java/org/apache/camel/processor/resume/kafka/SingleNodeKafkaResumeStrategy.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerAsyncManualCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerBadPortHealthCheckIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerBadPortSupervisingHealthCheckIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerFullIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerHealthCheckIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentWithCustomSerializerIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerIdempotentWithProcessorIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerTopicIsPatternIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerUnresolvableHealthCheckIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/commit/KafkaConsumerNoopCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/commit/KafkaConsumerSyncCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/pause/KafkaPausableConsumerCircuitBreakerIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/pause/KafkaPausableConsumerIT.java

Backport multiple Kafka fixes for the resume API

---

components/camel-couchbase/src/test/java/org/apache/camel/component/couchbase/integration/CouchbaseIntegrationTestBase.java
test-infra/camel-test-infra-couchbase/src/test/java/org/apache/camel/test/infra/couchbase/services/CouchbaseServiceFactory.java

Also fix the current issue on our CI and make the tests run much faster

CAMEL-18381: added support for singleton services for camel-test-infra-couchbase

---

components/camel-kamelet/src/main/java/org/apache/camel/component/kamelet/KameletComponent.java
components/camel-kamelet/src/test/java/org/apache/camel/component/kamelet/KameletGlobalPropertiesTest.java

Camel 18370

---

components/camel-spring-xml/src/test/java/org/apache/camel/spring/processor/idempotent/FileConsumerIdempotentLoadStoreTest.java
core/camel-core-model/src/main/java/org/apache/camel/builder/NotifyBuilder.java

CAMEL-15520: removed the deprecated NotifyBuilder.matchesMockWaitTime

---

test-infra/camel-test-infra-artemis/src/test/java/org/apache/camel/test/infra/artemis/services/ArtemisContainer.java
test-infra/camel-test-infra-aws-v2/src/test/java/org/apache/camel/test/infra/aws2/services/AWSContainer.java
test-infra/camel-test-infra-azure-common/src/test/java/org/apache/camel/test/infra/azure/common/services/AzureStorageService.java
test-infra/camel-test-infra-couchdb/src/test/java/org/apache/camel/test/infra/couchdb/services/CouchDbLocalContainerService.java
test-infra/camel-test-infra-dispatch-router/src/test/java/org/apache/camel/test/infra/dispatch/router/services/DispatchRouterContainer.java
test-infra/camel-test-infra-fhir/src/test/java/org/apache/camel/test/infra/fhir/services/FhirLocalContainerService.java
test-infra/camel-test-infra-google-pubsub/src/test/java/org/apache/camel/test/infra/google/pubsub/services/GooglePubSubLocalContainerService.java
test-infra/camel-test-infra-hdfs/src/test/java/org/apache/camel/test/infra/hdfs/v2/services/ContainerLocalHDFSService.java
test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/StrimziContainer.java
test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/StrimziService.java
test-infra/camel-test-infra-mongodb/src/test/java/org/apache/camel/test/infra/mongodb/services/MongoDBLocalContainerService.java
test-infra/camel-test-infra-openldap/src/test/java/org/apache/camel/test/infra/openldap/services/OpenldapLocalContainerService.java
test-infra/camel-test-infra-redis/src/test/java/org/apache/camel/test/infra/redis/services/RedisLocalContainerService.java
test-infra/camel-test-infra-xmpp/src/test/java/org/apache/camel/test/infra/xmpp/services/XmppServerContainer.java
test-infra/camel-test-infra-zookeeper/src/test/java/org/apache/camel/test/infra/zookeeper/services/ZooKeeperContainer.java

CAMEL-15520: replaced deprecated getContainerIpAddress with getHost in test-infra

---

components/camel-google/camel-google-bigquery/src/main/java/org/apache/camel/component/google/bigquery/sql/GoogleBigQuerySQLProducer.java
components/camel-google/camel-google-bigquery/src/test/resources/sql/delete.sql
components/camel-google/camel-google-bigquery/src/test/resources/sql/insert.sql

fixes https://issues.apache.org/jira/browse/CAMEL-18393

CAMEL-18393 Camel-bigquery: NPE if select * is requested

---

components/camel-jms/src/test/java/org/apache/camel/component/jms/AbstractPersistentJMSTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/ConsumerTemplateJmsSelectorTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsAsyncStartListenerTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsAsyncStartStopListenerTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsAutoStartupTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsConsumeTemplateTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsDeadLetterChannelInOutTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsDurableTopicTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsProducerDisableReplyToTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsRouteDeliveryModePreserveQoSTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsSetBodyNullErrorHandlerUseOriginalMessageTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsSuspendResumeTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsThrottlingInflightRoutePolicyTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsToDSendDynamicTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsToDSendDynamicTwoDisabledTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsToDSendDynamicTwoTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/ManagedJmsEndpointTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/TwoConsumerOnSameQueueTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/TwoConsumerOnSameTopicTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/async/AsyncConsumerInOutTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsDirectStartupOrderIssueTest.java
test-infra/camel-test-infra-activemq/src/test/java/org/apache/camel/test/infra/activemq/services/ActiveMQEmbeddedServiceBuilder.java
test-infra/camel-test-infra-activemq/src/test/java/org/apache/camel/test/infra/activemq/services/ActiveMQPersistentVMService.java
test-infra/camel-test-infra-activemq/src/test/java/org/apache/camel/test/infra/activemq/services/ActiveMQServiceFactory.java

Convert persistent JMS tests to the test-infra

---

components/camel-sql/src/main/java/org/apache/camel/component/sql/SqlProducer.java

This is a proposed fix for the issue described on the Jira ticket: [CAMEL-18399](https://issues.apache.org/jira/browse/CAMEL-18399)

CAMEL-18399: Fix PreparedStatement NullPointerException

---

core/camel-core-model/src/main/java/org/apache/camel/builder/RouteBuilder.java
core/camel-core-model/src/main/java/org/apache/camel/builder/RouteBuilderLifecycleStrategy.java
core/camel-core/src/test/java/org/apache/camel/builder/RouteBuilderTest.java

feat: add a global route builder interceptors

---

components/camel-jms/src/test/java/org/apache/camel/component/jms/AbstractPersistentJMSTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/ConsumerTemplateJmsSelectorTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsAsyncStartListenerTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsAsyncStartStopListenerTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsAutoStartupTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsConsumeTemplateTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsDeadLetterChannelInOutTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsDurableTopicTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsProducerDisableReplyToTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsRouteDeliveryModePreserveQoSTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsSetBodyNullErrorHandlerUseOriginalMessageTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsSuspendResumeTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsThrottlingInflightRoutePolicyTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsToDSendDynamicTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsToDSendDynamicTwoDisabledTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsToDSendDynamicTwoTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/ManagedJmsEndpointTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/TwoConsumerOnSameQueueTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/TwoConsumerOnSameTopicTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsDirectStartupOrderIssueTest.java

(chores) camel-jms: consolidate duplicate test code

---

components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsLoadBalanceFailoverWithForceSendOriginalJmsMessageTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsOnCompletionAndInterceptAndOnExceptionTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsOnCompletionTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsRoutingSlipInOutTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/ManagedJmsEndpointTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/ReplyToDestinationSelectorNameTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/SimpleJmsRequestReplyExclusiveReplyToTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/SimpleJmsRequestReplySharedReplyToTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/async/AsyncConsumerFalseTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/async/AsyncConsumerInOutTwoTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/async/AsyncConsumerTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsInOutRoutingSlipTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsInOutUseMessageIDasCorrelationIDTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsMessageHeaderContentBasedRouterTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsReplyToLoopIssueTest.java

Some spring tests seem broken. They will be fixed by a separate PR.

(chores) camel-jms: rename a few resources to ensure uniqueness

---

camel-dependencies/pom.xml
parent/pom.xml

Update hadoop3 version to 3.3.4

---

camel-dependencies/pom.xml
parent/pom.xml

Cherry pick from main to camel-3.18.x LTS

Upgrade apache spark to 3.2.2 (#8139)

---

components/camel-jms/src/test/java/org/apache/camel/component/jms/ActiveMQOriginalDestinationTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/CamelJmsTestHelper.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsMessageBodySetNullTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsRouteRequestReplyTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/SpringJmsRoutingSlipInOutTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsConcurrentConsumerInOnlyTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsTransactedDeadLetterChannelHandlerRollbackOnExceptionTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsTransactedOnExceptionRollbackOnExceptionTest.java
components/camel-jms/src/test/resources/org/apache/camel/component/jms/SpringJmsRoutingSlipInOutTest.xml
test-infra/camel-test-infra-activemq/src/test/java/org/apache/camel/test/infra/activemq/common/ConnectionFactoryHelper.java
test-infra/camel-test-infra-activemq/src/test/java/org/apache/camel/test/infra/activemq/services/ActiveMQEmbeddedServiceBuilder.java
test-infra/camel-test-infra-activemq/src/test/java/org/apache/camel/test/infra/activemq/services/ActiveMQServiceFactory.java

(chores) camel-jms: remove remaining duplicated code and consolidate pooled tests

---

components/camel-controlbus/src/main/docs/controlbus-component.adoc

[CAMEL-18403] Fix controlbus example in docs

---

camel-dependencies/pom.xml
parent/pom.xml

Cherry pick from main to 3.18.x LTS branch

Update hadoop3 version to 3.3.4 (#8172)

---

parent/pom.xml

https://github.com/spring-projects/spring-boot/releases/tag/v2.7.3

Align to spring boot 2.7.3

---

camel-dependencies/pom.xml
parent/pom.xml
pom.xml

SUREFIRE-1831, which was blocking the upgrade, was resolved.

Update Maven Surefire, Failsafe and Surefire report plugin versions

---

core/camel-core/src/test/java/org/apache/camel/component/log/ConsumingAppender.java
core/camel-core/src/test/java/org/apache/camel/component/log/LogBodyWithNewLineTest.java

Avoid LogBodyWithNewLineTest adding messages from other tests to log file.
Replace use of deprecated method to build LoggerConfig.

CAMEL-18413: improve tests using log4j2 appenders

---

camel-dependencies/pom.xml
parent/pom.xml

Align to spring-boot 2.7.3, cherry pick from main, ran build to sync camel-dependencies.

Align to spring boot 2.7.3 (#8186)

---

camel-dependencies/pom.xml
parent/pom.xml

Hibernate version goes from 5.4.32.Final -> 5.6.10.Final - is that okay?    All the other version changes looked minor.

Align to spring-boot 2.6.11

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/BaseEmbeddedKafkaTestSupport.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerAsyncManualCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerFullIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerHealthCheckIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/commit/KafkaConsumerAsyncCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/commit/KafkaConsumerNoopCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/commit/KafkaConsumerSyncCommitIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/health/KafkaConsumerBadPortHealthCheckIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/health/KafkaConsumerBadPortSupervisingHealthCheckIT.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/health/KafkaConsumerUnresolvableHealthCheckIT.java

(chores) camel-kafka: stop enforcing a test lifecycle unless required

---

core/camel-management/src/main/java/org/apache/camel/management/mbean/ManagedBacklogDebugger.java
core/camel-util/src/main/java/org/apache/camel/util/StopWatch.java
core/camel-util/src/test/java/org/apache/camel/util/StopWatchTest.java

CAMEL-18417: use a monotonic clock source for the StopWatch

---

core/camel-core/src/test/java/org/apache/camel/CamelParallelExecutionStrategy.java
core/camel-core/src/test/resources/junit-platform.properties

Use 1024 as maximum pool size and add a saturate predicate.

CAMEL-18420: adapt CamelParallelExecutionStrategy for Junit 5.9.0

---

components/camel-couchbase/src/test/java/org/apache/camel/component/couchbase/integration/ConsumeMessagesWithLimitIT.java
components/camel-couchbase/src/test/java/org/apache/camel/component/couchbase/integration/ConsumeResumeStrategyIT.java
components/camel-couchbase/src/test/java/org/apache/camel/component/couchbase/integration/CouchbaseIntegrationTestBase.java
components/camel-couchbase/src/test/java/org/apache/camel/component/couchbase/integration/ProduceMessagesSimpleIT.java
components/camel-couchbase/src/test/java/org/apache/camel/component/couchbase/integration/RemoveMessagesIT.java

Couchbase has been failing consistently on CI for a while. Hopefully
this will help fix the issue.

(chores) camel-couchbase: rework setup to fix CI issues

---

components/camel-paho/src/test/java/org/apache/camel/component/paho/PahoComponentTest.java
components/camel-paho/src/test/java/org/apache/camel/component/paho/PahoOverrideTopicTest.java
components/camel-paho/src/test/java/org/apache/camel/component/paho/PahoToDSendDynamicTest.java
components/camel-paho/src/test/java/org/apache/camel/component/paho/PahoToDTest.java

Recent refactoring in camel-test-infra-activemq (such as
49af0f8ddce5a69ff73320753946c81a6463c91f) require adjusting the test
service lifecycle

(chores) camel-paho: fixed tests

---

components/camel-amqp/src/test/java/org/apache/camel/component/amqp/AMQPRouteTest.java
components/camel-amqp/src/test/java/org/apache/camel/component/amqp/artemis/AMQPEmbeddedBrokerTest.java

Recent refactoring in camel-test-infra-activemq (such as
49af0f8) require adjusting the test service lifecycle

(chores) camel-amqp: fixed tests

---

components/camel-chatscript/src/test/java/org/apache/camel/component/ChatScriptComponentIT.java
test-infra/camel-test-infra-chatscript/src/test/java/org/apache/camel/test/infra/chatscript/services/ChatScriptLocalContainerService.java
test-infra/camel-test-infra-chatscript/src/test/java/org/apache/camel/test/infra/chatscript/services/ChatScriptService.java

(chores) camel-chatscript test fixes + camel-test-infra-chatscript fixes

---

components/camel-jms/pom.xml
components/camel-jms/src/test/java/org/apache/camel/component/jms/ActiveMQOriginalDestinationTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsAsyncStartListenerTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsBatchResequencerJMSPriorityTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsDeadLetterQueueUsingTransferExchangeTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsDefaultTaskExecutorTypeTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsMessageCreatedStrategyComponentTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsMessageCreatedStrategyEndpointTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsMessageIDNotOverridenAMQTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsPollingConsumerTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsProducerConcurrentWithReplyTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsRequestReplyExclusiveReplyToConcurrentTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsRouteUsingJMSXGroupTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsSelectorInTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsSetBodyNullErrorHandlerUseOriginalMessageTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsSimpleRequestLateReplyTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsStreamMessageTypeNoStreamCachingTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsStreamMessageTypeTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsTransferExchangeTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/ProduceMessageConverterTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsBlockedAsyncRoutingEngineTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsCustomJMSReplyToIssueTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsInOnlyIssueTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsInOutPersistentReplyQueueTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsToFileMessageIdTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/TransactionErrorHandlerRedeliveryDelayTest.java
components/camel-jms/src/test/resources/org/apache/camel/component/jms/issues/TransactionErrorHandlerRedeliveryDelayTest-context.xml
test-infra/camel-test-infra-activemq/pom.xml
test-infra/camel-test-infra-activemq/src/test/java/org/apache/camel/test/infra/activemq/services/ActiveMQEmbeddedServiceBuilder.java

(chores) camel-jms: test/stability cleanups

---

components/camel-ftp/pom.xml

(chores) camel-ftp: increase an overly aggressive fork timeout

---

components/camel-google/camel-google-bigquery/src/main/docs/google-bigquery-sql-component.adoc
components/camel-google/camel-google-bigquery/src/main/java/org/apache/camel/component/google/bigquery/sql/GoogleBigQuerySQLProducer.java
components/camel-google/camel-google-bigquery/src/test/java/org/apache/camel/component/google/bigquery/unit/sql/GoogleBigQuerySQLProducerWithParamersTest.java
docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_19.adoc

fixes https://issues.apache.org/jira/browse/CAMEL-18382

CAMEL-18382: Google-bigquery - allow different value types from headers

---

components/camel-couchbase/src/test/java/org/apache/camel/component/couchbase/integration/CouchbaseIntegrationTestBase.java

Couchbase tests remain flaky on CI, so trying one more fix to see if it
becomes stable

(chores) camel-couchbase: another CI fix

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade 3.14.x LTS branch version to 5.10.2.

Upgrade kubernetes-client / kubernetes-model to 5.10.2

---

camel-dependencies/pom.xml
parent/pom.xml

Ran camel-flink tests on jdk11, passed.

Upgrade scala to 2.11.12

---

core/camel-core-model/src/main/java/org/apache/camel/builder/BuilderSupport.java

Adding this method allows to check if any errorHandlerFactory exists, before to be initialized by the getErrorHandlerFactory method (which set a default one if it does not exists).

feat(core): hasErrorHandlerFactory helper method

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade snakeyaml to 1.31 - should go to LTS branches as well (will add cherry-pick PRs once processed)

Upgrade snakeyaml to 1.31

---

camel-dependencies/pom.xml
parent/pom.xml

Cherry pick to 3.18.x LTS branch

Upgrade snakeyaml to 1.31 (#8242)

---

components/camel-jms/src/main/java/org/apache/camel/component/jms/DefaultQueueBrowseStrategy.java
components/camel-jms/src/main/java/org/apache/camel/component/jms/EndpointMessageListener.java
components/camel-jms/src/main/java/org/apache/camel/component/jms/JmsMessageHelper.java
components/camel-jms/src/main/java/org/apache/camel/component/jms/JmsPollingConsumer.java
components/camel-jms/src/main/java/org/apache/camel/component/jms/reply/QueueReplyManager.java
components/camel-jms/src/main/java/org/apache/camel/component/jms/reply/ReplyManagerSupport.java
components/camel-jms/src/main/java/org/apache/camel/component/jms/reply/TemporaryQueueReplyManager.java
components/camel-jms/src/main/java/org/apache/camel/component/jms/reply/UseMessageIdAsCorrelationIdMessageSentCallback.java

(chores) camel-jms: minor cleanups

---

camel-dependencies/pom.xml
components/camel-fop/pom.xml
components/camel-xmlsecurity/pom.xml
core/camel-core-engine/pom.xml
core/camel-management-api/pom.xml
core/camel-management/pom.xml
parent/pom.xml
tooling/maven/camel-eip-documentation-enricher-maven-plugin/pom.xml
tooling/maven/camel-eip-documentation-enricher-maven-plugin/src/test/java/org/apache/camel/maven/integration/EIPDocumentationMojoTest.java

Remove use of xalan : remove profiles, remove from camel-eip-documentation-enricher-maven-plugin, remove from camel-xmlsecurity
camel-fop tests pass for me without xalan-serializer.
https://issues.apache.org/jira/browse/CAMEL-18346

CAMEL-18346 Remove use of xalan : remove profiles, remove from camel-eip-documentation-enricher-maven-plugin, remove from camel-xmlsecurity

---

components/camel-jms/pom.xml
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsDurableTopicTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsInOnlyWithReplyToHeaderTopicTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsInOutFixedReplyQueueTimeoutTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsInOutIndividualRequestTimeoutTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsInOutTransferExchangeTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsPollingConsumerTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsProducerConcurrentTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsProducerConcurrentWithReplyTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsRequestReplyCorrelationTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsRequestReplyExclusiveReplyToTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsRequestReplyProcessRepliesConcurrentUsingThreadsTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsRouteUsingJMSXGroupTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsRouteWithInOnlyAndMultipleAcksTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsRouteWithInOnlyTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsRoutingSlipInOutTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/async/AsyncConsumerInOutTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsInOnlyIssueTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsInOutUseMessageIDasCorrelationIDTest.java
test-infra/camel-test-infra-activemq/src/test/java/org/apache/camel/test/infra/activemq/common/ConnectionFactoryHelper.java
test-infra/camel-test-infra-activemq/src/test/java/org/apache/camel/test/infra/activemq/services/AbstractActiveMQEmbeddedService.java
test-infra/camel-test-infra-activemq/src/test/java/org/apache/camel/test/infra/activemq/services/ActiveMQPersistentVMService.java
test-infra/camel-test-infra-activemq/src/test/java/org/apache/camel/test/infra/activemq/services/ActiveMQService.java
test-infra/camel-test-infra-activemq/src/test/java/org/apache/camel/test/infra/activemq/services/ActiveMQServiceFactory.java
test-infra/camel-test-infra-activemq/src/test/java/org/apache/camel/test/infra/activemq/services/ActiveMQVMService.java
test-infra/camel-test-infra-common/src/test/java/org/apache/camel/test/infra/common/services/SingletonService.java

(chores) camel-jms + camel-test-infra-activemq: more fixes

---

components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsDurableTopicTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsInOutFixedReplyQueueTimeoutTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsInOutFixedReplyQueueTimeoutUseMessageIDAsCorrelationIDTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsPollingConsumerTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsRequestReplyProcessRepliesConcurrentUsingThreadsTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/TwoConsumerOnSameTopicTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/async/AsyncConsumerInOutTest.java
components/camel-jms/src/test/java/org/apache/camel/component/jms/issues/JmsInOutExclusiveTopicTest.java

(chores) camel-jms: A few more fixes

---

components/camel-jms/pom.xml

(chores) camel-jms: increase the fork timeout

---

camel-dependencies/pom.xml
components/camel-azure/camel-azure-cosmosdb/pom.xml
components/camel-azure/camel-azure-eventhubs/pom.xml
components/camel-azure/camel-azure-key-vault/pom.xml
components/camel-azure/camel-azure-servicebus/pom.xml
components/camel-azure/camel-azure-storage-blob/pom.xml
components/camel-azure/camel-azure-storage-datalake/pom.xml
components/camel-azure/camel-azure-storage-queue/pom.xml
components/camel-azure/pom.xml
parent/pom.xml
test-infra/camel-test-infra-azure-common/src/test/java/org/apache/camel/test/infra/azure/common/services/AzuriteContainer.java
test-infra/camel-test-infra-azure-storage-blob/pom.xml
test-infra/camel-test-infra-azure-storage-datalake/pom.xml
test-infra/camel-test-infra-azure-storage-queue/pom.xml

CAMEL-18452: Integrate azure-sdk-bom in a non-conflicting manner

---

components/camel-jetty/src/test/java/org/apache/camel/component/jetty/HttpReturnDataNotInputStreamConvertableTest.java

CAMEL-15475: fix deprecation message in camel-jetty

---

dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/pom.xml
tooling/maven/camel-package-maven-plugin/pom.xml

Since 3.15 Camel supports Java 11 and newer, so it would always be active by default.

CAMEL-18465: remove unnecessary 'jigsaw' profile

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/dozer.json
components/camel-dozer/pom.xml
components/camel-dozer/src/generated/resources/META-INF/services/org/apache/camel/component.properties
components/camel-dozer/src/generated/resources/org/apache/camel/component/dozer/dozer.json
components/camel-dozer/src/main/docs/dozer-component.adoc
components/camel-dozer/src/main/java/org/apache/camel/component/dozer/DozerComponent.java
dsl/camel-componentdsl/src/generated/java/org/apache/camel/builder/component/ComponentsBuilderFactory.java
dsl/camel-componentdsl/src/generated/java/org/apache/camel/builder/component/dsl/DozerComponentBuilderFactory.java
dsl/camel-componentdsl/src/generated/resources/metadata.json
dsl/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/StaticEndpointBuilders.java
dsl/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/dsl/LanguageEndpointBuilderFactory.java

CAMEL-18455: dozer project is deprecated and unmaintained

---

components/camel-salesforce/camel-salesforce-component/src/main/docs/salesforce-component.adoc
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/SalesforceException.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/processor/AbstractRestProcessor.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/processor/AbstractSalesforceProcessor.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/processor/CompositeSObjectCollectionsProcessor.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/processor/JsonRestProcessor.java
components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/RestApiIntegrationTest.java

Sniff the response to detect SObject type.
@davsclaus Let me know what you think of this approach.

CAMEL-16642: camel-salesforce: Detect SObject type

---

camel-dependencies/pom.xml
parent/pom.xml

CAMEL-18121: Upgrade to Kafka 3.2.1

---

components/camel-ftp/pom.xml

(chores) camel-ftp: prevent hanging the build for too long

---

components/camel-aws/camel-aws2-ddb/src/main/docs/aws2-ddb-component.adoc

📝 Add missing paragraph content

---

components/camel-ftp/pom.xml

There's a few more tweaks to send, but this alone should provide some
improvements. On my test machine, the execution time drops by a half (~3
min to 1:30 min).

CAMEL-16488: parallelized FTP tests

---

components/camel-couchbase/src/test/java/org/apache/camel/component/couchbase/integration/ConsumeMessagesWithLimitIT.java
components/camel-couchbase/src/test/java/org/apache/camel/component/couchbase/integration/ConsumeResumeStrategyIT.java

For some reason these tests do not run at all in Apache CI. However they
seem to work well in (most of?) other places. So, temporarily
disabling them because of this persistent flakiness

(chores) camel-couchbase: disable some tests only on Apache CI

---

components/camel-knative/camel-knative-component/src/main/java/org/apache/camel/component/knative/ce/AbstractCloudEventProcessor.java

CAMEL-18473: correct knative CloudEvent time format

---

components/camel-knative/camel-knative-component/src/main/java/org/apache/camel/component/knative/ce/AbstractCloudEventProcessor.java

cherry-pick for PR https://github.com/apache/camel/pull/8306

CAMEL-18473: correct knative CloudEvent time format (#8306)

---

components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FtpPollEnrichBridgeErrorHandlerIT.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FtpServerTestSupport.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FtpsServerExplicitSSLWithClientAuthTestSupport.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FtpsServerExplicitSSLWithoutClientAuthTestSupport.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FtpsServerExplicitTLSWithClientAuthTestSupport.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FtpsServerExplicitTLSWithoutClientAuthTestSupport.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FtpsServerImplicitSSLWithClientAuthTestSupport.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FtpsServerImplicitSSLWithoutClientAuthTestSupport.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FtpsServerImplicitTLSWithClientAuthTestSupport.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FtpsServerImplicitTLSWithoutClientAuthTestSupport.java
test-infra/camel-test-infra-common/src/test/java/org/apache/camel/test/infra/common/services/AbstractTestService.java
test-infra/camel-test-infra-ftp/src/test/java/org/apache/camel/test/infra/ftp/services/FtpService.java
test-infra/camel-test-infra-ftp/src/test/java/org/apache/camel/test/infra/ftp/services/FtpServiceFactory.java
test-infra/camel-test-infra-ftp/src/test/java/org/apache/camel/test/infra/ftp/services/embedded/EmbeddedConfiguration.java
test-infra/camel-test-infra-ftp/src/test/java/org/apache/camel/test/infra/ftp/services/embedded/EmbeddedConfigurationBuilder.java
test-infra/camel-test-infra-ftp/src/test/java/org/apache/camel/test/infra/ftp/services/embedded/FtpEmbeddedService.java
test-infra/camel-test-infra-ftp/src/test/java/org/apache/camel/test/infra/ftp/services/embedded/FtpsEmbeddedService.java
test-infra/camel-test-infra-ftp/src/test/java/org/apache/camel/test/infra/ftp/services/embedded/SftpEmbeddedService.java

camel-ftp: more test cleanups

---

parent/pom.xml

camel-box/camel-any23/camel-oaipmh/camel-cm-sms tests all pass locally

Upgrade jsoup to 1.15.3

---

components/camel-bindy/src/main/docs/bindy-dataformat.adoc

📝 Update doc with supported java version

---

core/camel-core-engine/src/main/java/org/apache/camel/impl/DefaultCamelContext.java
core/camel-core/src/test/java/org/apache/camel/issues/DynamicallyConcurrentlyAddRoutesTest.java

Obtain the lock on `model` before locking `camelContext` in `removeRoute` to avoid a potential deadlock with concurrent `addRoutes` calls.

[CAMEL-18472] lock 'model' in 'removeRoute' first to avoid deadlock

---

components/camel-ahc-ws/pom.xml
components/camel-ahc-ws/src/test/java/org/apache/camel/component/ahc/ws/WsProducerConsumerTest.java
components/camel-ahc-ws/src/test/java/org/apache/camel/component/ahc/ws/WsProducerTest.java
components/camel-ahc-ws/src/test/java/org/apache/camel/component/ahc/ws/WsProducerTestBase.java
components/camel-ahc-ws/src/test/java/org/apache/camel/component/ahc/ws/WsProducerUsingStreamingTest.java
components/camel-ahc-ws/src/test/java/org/apache/camel/component/ahc/ws/WssProducerTest.java
components/camel-ahc-ws/src/test/resources/log4j2.properties
test-infra/camel-test-infra-jetty/pom.xml
test-infra/camel-test-infra-jetty/src/test/java/org/apache/camel/test/infra/jetty/common/JettyProperties.java
test-infra/camel-test-infra-jetty/src/test/java/org/apache/camel/test/infra/jetty/services/JettyConfiguration.java
test-infra/camel-test-infra-jetty/src/test/java/org/apache/camel/test/infra/jetty/services/JettyConfigurationBuilder.java
test-infra/camel-test-infra-jetty/src/test/java/org/apache/camel/test/infra/jetty/services/JettyEmbeddedService.java
test-infra/camel-test-infra-jetty/src/test/java/org/apache/camel/test/infra/jetty/services/JettyService.java
test-infra/pom.xml

Adds the test infra + converts camel-ahc-ws

CAMEL-18456: consolidate Jetty usages in test code

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade PostgreSQL JDBC Driver to 42.4.1

Upgrade PostgreSQL JDBC Driver to 42.4.1

---

components/camel-atmosphere-websocket/pom.xml
components/camel-atmosphere-websocket/src/test/java/org/apache/camel/component/atmosphere/websocket/TestClient.java
components/camel-atmosphere-websocket/src/test/java/org/apache/camel/component/atmosphere/websocket/WebsocketCamelRouterTestSupport.java
components/camel-atmosphere-websocket/src/test/java/org/apache/camel/component/atmosphere/websocket/WebsocketCamelRouterWithInitParamTestSupport.java
components/camel-atmosphere-websocket/src/test/java/org/apache/camel/component/atmosphere/websocket/WebsocketRouteWithInitParamTest.java
components/camel-atmosphere-websocket/src/test/resources/log4j2.properties
test-infra/camel-test-infra-jetty/src/test/java/org/apache/camel/test/infra/jetty/services/JettyConfiguration.java

CAMEL-18456: convert camel-atmosphere-websocket to test-infra

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/cmis.json
components/camel-cmis/pom.xml
components/camel-cmis/src/generated/resources/META-INF/services/org/apache/camel/component.properties
components/camel-cmis/src/generated/resources/org/apache/camel/component/cmis/cmis.json
components/camel-cmis/src/main/docs/cmis-component.adoc
dsl/camel-componentdsl/src/generated/java/org/apache/camel/builder/component/ComponentsBuilderFactory.java
dsl/camel-componentdsl/src/generated/java/org/apache/camel/builder/component/dsl/CmisComponentBuilderFactory.java
dsl/camel-componentdsl/src/generated/resources/metadata.json

CAMEL-18495: deprecate CMIS component since Apache Chemistry is retired

---

components/camel-ahc-ws/pom.xml
components/camel-atmosphere-websocket/pom.xml

CAMEL-18456: fix scopes

---

components/camel-xchange/README.adoc
components/camel-xchange/pom.xml
components/camel-xchange/src/main/java/org/apache/camel/component/xchange/XChangeComponent.java
components/camel-xchange/src/test/java/org/apache/camel/component/xchange/XChangeTestSupport.java
components/camel-xchange/src/test/java/org/apache/camel/component/xchange/account/AccountProducerTest.java
components/camel-xchange/src/test/java/org/apache/camel/component/xchange/market/MarketDataProducerTest.java
components/camel-xchange/src/test/java/org/apache/camel/component/xchange/metadata/MetaDataProducerTest.java
components/camel-xchange/src/test/resources/mappings/account.json
components/camel-xchange/src/test/resources/mappings/currencies.json
components/camel-xchange/src/test/resources/mappings/ticker01.json
components/camel-xchange/src/test/resources/mappings/ticker02.json
components/camel-xchange/src/test/resources/mappings/tickerBTCUSDT_01.json

fixes: https://issues.apache.org/jira/browse/CAMEL-18484
Configuration of the test is described in README.adoc.
1 test does not work with mocked backend so far (recording of the binance api fails - it is now disabled without real credentials (see https://issues.apache.org/jira/browse/CAMEL-18486). This test was already disabled without real credentials, so this PR does not worsen coverage.

CAMEL-18484 Camel-xchange: Enable mock testing without real account

---

components/camel-jms/src/test/java/org/apache/camel/component/jms/JmsSuspendResumeTest.java

Minor cleanup to test something ...

(chores) camel-jms: remove a Thread.sleep call

---

components/camel-http/pom.xml
components/camel-http/src/test/java/org/apache/camel/component/http/HttpProducerSessionTest.java
test-infra/camel-test-infra-jetty/src/test/java/org/apache/camel/test/infra/jetty/services/JettyConfiguration.java
test-infra/camel-test-infra-jetty/src/test/java/org/apache/camel/test/infra/jetty/services/JettyConfigurationBuilder.java

CAMEL-18456: converted camel-http to camel-test-infra-jetty

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade milo-version to 0.6.8, ran tests locally on milo component.

Upgrade milo-version to 0.6.8

---

camel-dependencies/pom.xml
parent/pom.xml

This is a full version bump - tests succeed locally for me (camel-elytron, camel-undertow-spring-security, integration tests).

Upgrade nimbus-jose-jwt to 9.22

---

components/camel-platform-http/pom.xml
components/camel-platform-http/src/test/java/org/apache/camel/component/platform/http/JettyServerTest.java
test-infra/camel-test-infra-jetty/src/test/java/org/apache/camel/test/infra/jetty/services/JettyConfiguration.java
test-infra/camel-test-infra-jetty/src/test/java/org/apache/camel/test/infra/jetty/services/JettyConfigurationBuilder.java
test-infra/camel-test-infra-jetty/src/test/java/org/apache/camel/test/infra/jetty/services/JettyEmbeddedService.java

CAMEL-18456: converted camel-platform-http tests to camel-test-infra-jetty

---

parent/pom.xml

Upgrade Deep Java Library to the latest version (0.19.0)

Upgrade DJL to 0.19.0

---

components/camel-elytron/pom.xml

CAMEL-17448: remove unused test dependencies in camel-elytron

---

components/camel-websocket/pom.xml
components/camel-websocket/src/test/java/org/apache/camel/component/websocket/WebsocketClientCamelRouteTest.java
components/camel-websocket/src/test/java/org/apache/camel/component/websocket/WebsocketComponentRouteExampleTest.java
components/camel-websocket/src/test/java/org/apache/camel/component/websocket/WebsocketConsumerRouteTest.java
components/camel-websocket/src/test/java/org/apache/camel/component/websocket/WebsocketProducerRouteExampleTest.java
components/camel-websocket/src/test/java/org/apache/camel/component/websocket/WebsocketProducerRouteRestartTest.java
components/camel-websocket/src/test/java/org/apache/camel/component/websocket/WebsocketRouteExampleTest.java
components/camel-websocket/src/test/java/org/apache/camel/component/websocket/WebsocketSSLClientAuthRouteExampleTest.java
components/camel-websocket/src/test/java/org/apache/camel/component/websocket/WebsocketSSLContextGlobalRouteExampleTest.java
components/camel-websocket/src/test/java/org/apache/camel/component/websocket/WebsocketSSLContextInUriRouteExampleTest.java
components/camel-websocket/src/test/java/org/apache/camel/component/websocket/WebsocketSSLRouteExampleTest.java
components/camel-websocket/src/test/java/org/apache/camel/component/websocket/WebsocketStaticTest.java
components/camel-websocket/src/test/java/org/apache/camel/component/websocket/WebsocketTwoRoutesExampleTest.java
components/camel-websocket/src/test/java/org/apache/camel/component/websocket/WebsocketTwoRoutesToSIndividualAndBroadcastEndpointExampleTest.java
components/camel-websocket/src/test/java/org/apache/camel/component/websocket/WebsocketTwoRoutesToSameEndpointExampleTest.java
test-infra/camel-test-infra-common/src/test/java/org/apache/camel/test/infra/common/http/WebsocketTestClient.java

CAMEL-18506: removed usages of the Async HTTP client from camel-websocket

---

camel-dependencies/pom.xml
parent/pom.xml

Update elytron to 1.15.4.Final and update elytron-web to 1.10.2.Final
camel-elytron tests pass locally

Upgrade elytron version (1.15.4.Final) and elytron-web (1.10.2.Final) version

---

camel-dependencies/pom.xml
components/camel-coap/pom.xml
parent/pom.xml

Cherry picks of commits from main branch over to 3.18.x LTS branch of recent significant version change commits.

Cherrypicks

---

components/camel-box/camel-box-component/src/main/java/org/apache/camel/component/box/internal/BoxConnectionHelper.java

request_token is empty (_var request_token = '';_), and not needed anymore, I've executed the test with my account and they are successful

[CAMEL-18530] Camel box cannot authorize

---

components/camel-knative/camel-knative-component/src/main/docs/knative-component.adoc

Improving knative documentation for ProducerTemplate usage

---

components/camel-activemq/pom.xml

Also created CAMEL-18539 for the future.

CAMEL-17448: removed used dependencies in camel-activemq

---

components/camel-any23/src/test/java/org/apache/camel/dataformat/any23/Any23TestSupport.java

(chores) camel-any23: removed duplicated code

---

components/camel-atmos/src/main/docs/atmos-component.adoc

(chores) camel-atmos: fixed invalid link in documentation

---

.github/actions/install-mvnd/action.yml

(chores) ci: upgrade Apache Maven Daemon to 0.8.1

---

components/camel-bindy/pom.xml

CAMEL-17448: removed unused dependencies on camel-bindy

---

components/camel-cassandraql/pom.xml

CAMEL-17448: removed unused dependencies on camel-cassandraql

---

components/camel-chatscript/pom.xml
components/camel-cm-sms/pom.xml
components/camel-cometd/pom.xml

CAMEL-17448: removed unused dependencies

---

components/camel-elasticsearch-rest/pom.xml

CAMEL-17448: removed unused dependencies on camel-elasticsearch-rest

---

components/camel-resourceresolver-github/pom.xml
components/camel-whatsapp/pom.xml

CAMEL-17448: more unused dependencies

---

components/camel-cxf/camel-cxf-rest/pom.xml
components/camel-cxf/camel-cxf-soap/pom.xml
components/camel-cxf/camel-cxf-spring-soap/pom.xml
components/camel-cxf/camel-cxf-transport/pom.xml

CAMEL-17448: removed unused dependencies in CXF components

---

.github/workflows/asf-snapshots-deploy.yml
.github/workflows/backport.yml
.github/workflows/master-pr-build.yml
.github/workflows/master-push-build.yml

Cherry pick to 3.14.x LTS branch

Prevent CI workflows from running on forks (#8435)

---

camel-dependencies/pom.xml
components/camel-azure/camel-azure-storage-blob/src/main/java/org/apache/camel/component/azure/storage/blob/client/BlobClientWrapper.java
components/camel-azure/camel-azure-storage-blob/src/main/java/org/apache/camel/component/azure/storage/blob/operations/BlobOperations.java
components/camel-azure/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BlobOperationsIT.java
parent/pom.xml

Upgrade to azure-sdk-bom version 1.2.6

---

components/camel-jackson/src/test/java/org/apache/camel/component/jackson/JacksonFeaturesTest.java
components/camel-jackson/src/test/java/org/apache/camel/component/jackson/JacksonMarshalNamingStrategyTest.java

✅ Add tests

---

components/camel-platform-http/src/test/java/org/apache/camel/component/platform/http/JettyCustomPlatformHttpConsumer.java

Platform-http: Remove vert.x specific code from Jetty example

---

camel-dependencies/pom.xml
parent/pom.xml

Align 3.14.x LTS branch dependencies to match spring-boot-dependencies 2.6.12

Align to dependencies to spring-boot 2.6.12

---

components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/TestSupport.java
components/camel-xmlsecurity/src/test/java/org/apache/camel/component/xmlsecurity/ECDSASignatureTest.java
components/camel-xmlsecurity/src/test/java/org/apache/camel/component/xmlsecurity/SignatureAlgorithmTest.java
components/camel-xmlsecurity/src/test/java/org/apache/camel/component/xmlsecurity/SignatureDigestMethodTest.java
components/camel-xmlsecurity/src/test/java/org/apache/camel/component/xmlsecurity/XAdESSignaturePropertiesTest.java
components/camel-xmlsecurity/src/test/java/org/apache/camel/component/xmlsecurity/XmlSignatureTest.java

(chores) Removed outdated Java 1.8 checks in tests

---

catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/ValidateMojo.java
components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Configuration.java
components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Consumer.java
components/camel-azure/camel-azure-storage-datalake/src/test/java/org/apache/camel/component/azure/storage/datalake/integration/DataLakeProducerIT.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/format/factories/BigDecimalFormatFactory.java
components/camel-jsonpath/src/main/java/org/apache/camel/jsonpath/JsonStream.java
components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/eventnotifier/MicrometerRouteEventNotifier.java

(chores) Multiple minor cleanups

---

components/camel-lra/pom.xml
components/camel-lra/src/main/java/org/apache/camel/service/lra/LRAClient.java
components/camel-lra/src/test/java/org/apache/camel/service/lra/AbstractLRATestSupport.java
components/camel-lra/src/test/java/org/apache/camel/service/lra/LRAOptionsIT.java
core/camel-core-model/src/main/java/org/apache/camel/model/SagaDefinition.java

* Use JDK11 HttpClient
* Fix test
* Use correct printDuration for durations < 1s

CAMEL-18578: camel-lra use JDK11 client

---

camel-dependencies/pom.xml
parent/pom.xml

Update Debezium to 1.9.6.Final

---

camel-dependencies/pom.xml
parent/pom.xml

Cherry pick from main (https://github.com/apache/camel/commit/cadadcfd2da10aea4c1f2e68d2eaf00556501e8c) to camel-3.18.x LTS branch

Upgrade milo-version to 0.6.8 (#8354)

---

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/AS2ServerConnection.java
components/camel-jira/src/main/java/org/apache/camel/component/jira/JiraVerifierExtension.java
dsl/camel-java-joor-dsl/src/main/java/org/apache/camel/dsl/java/joor/JavaRoutesBuilderLoader.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/util/CamelJBangSettingsHelper.java

(chores) More cleanups

---

components/camel-scheduler/src/main/docs/scheduler-component.adoc

Fix typo in docs

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java

[camel-18327] resuming from last committed offset

---

camel-dependencies/pom.xml
parent/pom.xml

Cherry pick from main to LTS branch

Upgrade scala-library to 2.13.9 (#8476)

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade protobuf to 3.19.6

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/support/KafkaRecordProcessor.java

[camel-18588] Added condition to only commit offset if it is not -1

---

core/camel-base/src/main/java/org/apache/camel/converter/ObjectConverter.java

I need a quick cleanup to test mvnd action fixes, this one seems like a
simple/quick one

(chores) camel-base: removed unused exceptions in the ObjectConverter

---

components/camel-lra/src/main/java/org/apache/camel/service/lra/LRAClient.java

Thanks @JiriOndrusek for spotting this via camel-quarkus integration tests

🚑 Fix camel-lra endpoints

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java

[camel-18587] Added condition to only commit offset if it is not already  paused

---

components/camel-arangodb/src/main/java/org/apache/camel/component/arangodb/ArangoDbComponent.java
components/camel-ehcache/src/main/java/org/apache/camel/component/ehcache/EhcacheComponent.java
components/camel-git/src/main/java/org/apache/camel/component/git/consumer/AbstractGitConsumer.java
components/camel-git/src/main/java/org/apache/camel/component/git/producer/GitProducer.java
components/camel-google/camel-google-functions/src/main/java/org/apache/camel/component/google/functions/GoogleCloudFunctionsComponent.java
components/camel-printer/src/main/java/org/apache/camel/component/printer/PrinterProducer.java

Components:
- camel-arangodb
- camel-ehcache
- camel-git
- camel-printer
--- 
Testing some GH Action changes due to https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

(chores) avoid shadowing variables

---

components/camel-kafka/src/main/java/org/apache/camel/processor/resume/kafka/SingleNodeKafkaResumeStrategy.java
core/camel-api/src/main/java/org/apache/camel/resume/ResumeStrategy.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/resume/TransientResumeStrategy.java

CAMEL-18148: Added support for running callbacks on offset updates

---

components/camel-mail/src/main/java/org/apache/camel/component/mail/MailConfiguration.java
components/camel-mail/src/main/java/org/apache/camel/component/mail/MailMessage.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitConsumer.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQComponent.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQMessagePublisher.java
components/camel-rabbitmq/src/main/java/org/apache/camel/component/rabbitmq/RabbitMQProducer.java

More cleanups (testing GH actions)

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConfiguration.java

Minor clenaups (GH actions test)

---

.github/workflows/component-pr.yaml
core/camel-xml-io-util/src/main/java/org/apache/camel/xml/io/util/XmlStreamReader.java

(chores) camel-xml-io-util: avoid shadowing variables

---

components/camel-sjms/src/main/java/org/apache/camel/component/sjms/SjmsProducer.java
components/camel-sjms/src/main/java/org/apache/camel/component/sjms/SjmsTemplate.java

(chores) camel-sjms: avoid shadowing variables

---

components/camel-pdf/src/main/java/org/apache/camel/component/pdf/text/DefaultLineBuilderStrategy.java
components/camel-servlet/src/main/java/org/apache/camel/component/servlet/ServletComponent.java
components/camel-twitter/src/main/java/org/apache/camel/component/twitter/search/SearchProducer.java

Minor cleanups (GH actions test)

---

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java

(chores) camel-base: avoid shadowing variables

---

components/camel-google/camel-google-secret-manager/src/main/java/org/apache/camel/component/google/secret/manager/GoogleSecretManagerComponent.java
components/camel-google/camel-google-secret-manager/src/main/java/org/apache/camel/component/google/secret/manager/GoogleSecretManagerProducer.java
components/camel-google/camel-google-secret-manager/src/test/java/org/apache/camel/component/google/secret/manager/integration/GoogleSecretManagerPropertiesNoEnvSourceTestIT.java
components/camel-google/camel-google-secret-manager/src/test/java/org/apache/camel/component/google/secret/manager/integration/GoogleSecretManagerPropertiesSourceTestIT.java

Fixed:
- shadowing member variables
- removing unused imports and fields
- removing unused local variables

(chores) camel-google-secret-manager: fixing a few code violations from SonarCloud

---

components/camel-rest-swagger/src/main/java/org/apache/camel/component/rest/swagger/RestSwaggerEndpoint.java

Fixed:
- shadowing member variables
- override equals in subclass that add fields

(chores) camel-rest-swagger: fixing a few code violations from SonarCloud

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade corda-rpc to 4.9.3 - I've run a full build and run the tests on camel-corda and I don't see any issues.

Upgrade corda-rpc to 4.9.3

---

components/camel-rest-openapi/src/main/docs/rest-openapi-component.adoc

Cherry-pick from main branch to 3.18.x

Doc update for camel-rest-openapi component (#8550)

---

parent/pom.xml

Cherry pick commons-text upgrade to 1.10.0 to 3.18.x LTS branch

Upgrade Commons-text to version 1.10.0

---

components/camel-jpa/src/main/java/org/apache/camel/component/jpa/DefaultTransactionStrategy.java
components/camel-jpa/src/main/java/org/apache/camel/component/jpa/DeleteHandler.java
components/camel-jpa/src/main/java/org/apache/camel/component/jpa/JpaComponent.java
components/camel-jpa/src/main/java/org/apache/camel/component/jpa/JpaConsumer.java
components/camel-jpa/src/main/java/org/apache/camel/component/jpa/JpaPollingConsumer.java
components/camel-jpa/src/main/java/org/apache/camel/component/jpa/JpaProducer.java
components/camel-jpa/src/main/java/org/apache/camel/processor/idempotent/jpa/JpaMessageIdRepository.java
components/camel-jpa/src/test/java/org/apache/camel/component/jpa/JpaComponentTest.java
components/camel-jpa/src/test/java/org/apache/camel/component/jpa/JpaEndpointTest.java
components/camel-jpa/src/test/java/org/apache/camel/component/jpa/JpaTest.java
components/camel-jpa/src/test/java/org/apache/camel/component/jpa/JpaWithNamedQueryAndParametersTest.java
components/camel-jpa/src/test/java/org/apache/camel/processor/jpa/JpaRouteSharedEntityManagerTest.java

Solving some pointings of sonar.

Cleanup jpa component

---

components/camel-jsonpath/src/main/docs/jsonpath-language.adoc
components/camel-jsonpath/src/main/java/org/apache/camel/jsonpath/JsonPathExpression.java
components/camel-jsonpath/src/main/java/org/apache/camel/jsonpath/JsonPathLanguage.java
components/camel-jsonpath/src/test/java/org/apache/camel/jsonpath/JsonPathLanguageTest.java
core/camel-core-model/src/main/java/org/apache/camel/builder/ExpressionClause.java
core/camel-core-model/src/main/java/org/apache/camel/builder/ExpressionClauseSupport.java
core/camel-core-model/src/main/java/org/apache/camel/model/language/JsonPathExpression.java
core/camel-core-reifier/src/main/java/org/apache/camel/reifier/language/JsonPathExpressionReifier.java

Issue: https://issues.apache.org/jira/browse/CAMEL-18612
Please, check that I didn't miss any place to inlude/support the new _unpackArray_ option.
Also, the option name is only a proposal. Another proposals are:
- unwrapSingleArray (original)
- unwrapArray
- unwrapSingleElements
- unpackSingleArray
- unpackArray
- unpackSingleElements
Which is the best?

[CAMEL-18612] Inconsistency in JsonPath component causes problems with databinding

---

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/internal/streaming/SubscriptionHelper.java
components/camel-sql/src/main/java/org/apache/camel/processor/aggregate/jdbc/JdbcAggregationRepository.java
components/camel-zookeeper/src/main/java/org/apache/camel/component/zookeeper/ZooKeeperProducer.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/KameletMain.java

(chores) Use log markers instead of concatenation

---

components/camel-saxon/src/main/java/org/apache/camel/component/xquery/XQueryBuilder.java
components/camel-saxon/src/main/java/org/apache/camel/converter/saxon/SaxonConverter.java
components/camel-xslt-saxon/pom.xml
components/camel-xslt-saxon/src/test/java/org/apache/camel/component/xslt/SaxonXsltFeatureRouteTest.java
components/camel-xslt-saxon/src/test/java/org/apache/camel/component/xslt/SaxonXsltMessageTerminateTest.java
parent/pom.xml

[CAMEL-15616] Upgrade to Saxon-HE 11.4 (tests pass)

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaFetchRecords.java

(backport) [camel-18627] added null check to check if there was previously committed offset before resuming

---

docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_19.adoc

Add note about AHC components removed in 3.19

---

components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Consumer.java
components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Producer.java

chore(aws-s3): fix deprecation warning

---

components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/SftpOperations.java
components/camel-irc/src/main/java/org/apache/camel/component/irc/CamelSSLIRCConnection.java
tooling/maven/camel-javadoc-plugin/src/main/java/org/apache/maven/plugins/javadoc/AbstractJavadocMojo.java

- camel-ftp
- camel irc
- camel-javadoc-plugin

(chores) removed unused assignments

---

catalog/camel-catalog-maven/src/main/java/org/apache/camel/catalog/maven/DefaultMavenArtifactProvider.java

(chores) camel-catalog-maven: reduce method complexity

---

components/camel-aws/camel-aws2-kinesis/src/test/java/org/apache/camel/component/aws2/kinesis/Kinesis2ConsumerHealthCustomClientTest.java

(chores) camel-aws2-kinesis: disable flaky tests on Github

---

camel-dependencies/pom.xml
parent/pom.xml

⬆️ Upgrade hsqldb

---

components/camel-aws/camel-aws2-kms/pom.xml
components/camel-aws/camel-aws2-kms/src/test/java/org/apache/camel/component/aws2/kms/localstack/KmsCreateKeyIT.java
components/camel-aws/camel-aws2-kms/src/test/java/org/apache/camel/component/aws2/kms/localstack/KmsDisableKeyIT.java
components/camel-aws/camel-aws2-kms/src/test/java/org/apache/camel/component/aws2/kms/localstack/KmsListKeysIT.java

(chores) camel-aws2-kms: adjust memory settings and JVM behavior for the tests

---

components/camel-aws/camel-aws2-lambda/pom.xml
components/camel-aws/camel-aws2-lambda/src/test/java/org/apache/camel/component/aws2/lambda/integration/LambdaAliasesIT.java
components/camel-aws/camel-aws2-lambda/src/test/java/org/apache/camel/component/aws2/lambda/integration/LambdaDeleteFunctionIT.java
components/camel-aws/camel-aws2-lambda/src/test/java/org/apache/camel/component/aws2/lambda/integration/LambdaListFunctionsIT.java

(chores) camel-aws2-lambda: disable flaky test on Github

---

components/camel-google/camel-google-bigquery/src/main/java/org/apache/camel/component/google/bigquery/GoogleBigQueryConfiguration.java
components/camel-google/camel-google-bigquery/src/test/java/org/apache/camel/component/google/bigquery/unit/BaseBigQueryTest.java

fixes https://issues.apache.org/jira/browse/CAMEL-18648

CAMEL-18648: Google-bigquery - fixed Exception during endpoint creation

---

components/camel-aws/camel-aws-secrets-manager/pom.xml
components/camel-aws/camel-aws-secrets-manager/src/test/java/org/apache/camel/component/aws/secretsmanager/integration/SecretsManagerCreateSecretProducerLocalstackIT.java
components/camel-aws/camel-aws-secrets-manager/src/test/java/org/apache/camel/component/aws/secretsmanager/integration/SecretsManagerDescribeSecretProducerLocalstackIT.java
components/camel-aws/camel-aws-secrets-manager/src/test/java/org/apache/camel/component/aws/secretsmanager/integration/SecretsManagerProducerListSecretsLocalstackIT.java
components/camel-aws/camel-aws-secrets-manager/src/test/java/org/apache/camel/component/aws/secretsmanager/integration/SecretsManagerUpdateSecretProducerLocalstackIT.java

(chores) camel-aws2-secrets-manager: fix/disable flaky test on Github

---

.github/actions/quick-test/quick-test.sh

Waiting for the AWS test fixes for GH before merging this ...

(chores) ci: allow testing AWS components separately

---

components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/Kinesis2Consumer.java
components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Consumer.java
components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Consumer.java

Testing if GH actions will test AWS components individually.

(chores) Minor cleanups to test CI changes

---

components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/RecordStringConverter.java

(chores) camel-aws: minor cleanups to test CI changes

---

components/camel-aws/camel-aws2-sts/src/main/java/org/apache/camel/component/aws2/sts/STS2Component.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/CamelInternalProcessor.java

(chores) minor cleanups to test CI changes (scenario 3)

---

core/camel-api/src/main/java/org/apache/camel/spi/ResourceLoader.java
core/camel-api/src/main/java/org/apache/camel/support/jsse/JsseParameters.java
core/camel-core/src/test/java/org/apache/camel/support/jsse/KeyManagersParametersTest.java
core/camel-core/src/test/java/org/apache/camel/support/jsse/KeyStoreParametersTest.java
core/camel-core/src/test/java/org/apache/camel/support/jsse/TrustManagersParametersTest.java

Camel 18665

---

components/camel-vertx/camel-vertx-common/src/main/java/org/apache/camel/component/vertx/common/VertxHelper.java
core/camel-api/src/main/java/org/apache/camel/support/jsse/SSLContextParameters.java

fixes https://issues.apache.org/jira/browse/CAMEL-18680
Code is already covered by the tests.

Wrong initialization of KeyStoreParameters causes IllegalArgumentException

---

components/camel-google/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubConsumer.java
components/camel-google/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/consumer/AcknowledgeSync.java

fixes: https://issues.apache.org/jira/browse/CAMEL-18447

CAMEL-18447 Camel-pubsub: AsyncTaskException: Asynchronous task failes

---

components/camel-vertx/camel-vertx-http/src/main/java/org/apache/camel/component/vertx/http/VertxHttpHelper.java
components/camel-vertx/camel-vertx-http/src/test/java/org/apache/camel/component/vertx/http/VertxHttpSendDynamicAwareTest.java

chore(vertx-http-cleanup): replace deprecated methods

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade spring-security to 5.7.5

Upgrade spring-security to 5.7.5

---

core/camel-core-engine/src/main/docs/modules/eips/pages/pollEnrich-eip.adoc
docs/user-manual/modules/ROOT/pages/rest-dsl.adoc
docs/user-manual/modules/faq/pages/how-do-i-import-rests-from-other-xml-files.adoc

CAMEL-18694 - Fix documentation to use new path attribute instead of uri

---

components/camel-ldap/src/main/java/org/apache/camel/component/ldap/LdapProducer.java

CAMEL-18696: camel-ldap - Make filter a bit easier to use

---

catalog/camel-allcomponents/pom.xml
components/camel-mail-microsoft-oauth/pom.xml
components/camel-mail-microsoft-oauth/src/main/docs/mail-microsoft-oauth.adoc
components/camel-mail-microsoft-oauth/src/main/java/org/apache/camel/component/mail/microsoft/authenticator/MicrosoftExchangeOnlineOAuth2MailAuthenticator.java
components/camel-mail/pom.xml
components/camel-mail/src/main/docs/mail-component.adoc
components/pom.xml
parent/pom.xml

moved the authenticator to a new module

[CAMEL-18684]: Add Microsoft Exchange Online OAuth2 Mail Authenticator

---

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelJBangMain.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Complete.java

Fix for https://issues.apache.org/jira/browse/CAMEL-18673

CAMEL-18673: camel-jbang - Provide shell completion for camel CLI

---

components/camel-openapi-java/src/main/java/org/apache/camel/openapi/RestModelConverters.java
components/camel-openapi-java/src/main/java/org/apache/camel/openapi/RestOpenApiReader.java
components/camel-openapi-java/src/test/java/org/apache/camel/openapi/ComplexTypesTest.java
components/camel-openapi-java/src/test/java/org/apache/camel/openapi/model/CustomDataWithSchemaAnnotation.java
components/camel-openapi-java/src/test/java/org/apache/camel/openapi/model/SampleComplexRequestTypeWithSchemaAnnotation.java
components/camel-openapi-java/src/test/java/org/apache/camel/openapi/model/SampleComplexResponseTypeWithSchemaAnnotation.java
components/camel-openapi-java/src/test/resources/org/apache/camel/openapi/V2SchemaForComplexTypesRequestWithSchemaAnnotation.json
components/camel-openapi-java/src/test/resources/org/apache/camel/openapi/V2SchemaForComplexTypesResponseWithSchemaAnnotation.json
components/camel-openapi-java/src/test/resources/org/apache/camel/openapi/V3SchemaForComplexTypesRequestWithSchemaAnnotation.json
components/camel-openapi-java/src/test/resources/org/apache/camel/openapi/V3SchemaForComplexTypesResponseWithSchemaAnnotation.json

Add custom ModelResolver to generate x-className extension 
Use x-className extension to make correct type reference

[CAMEL-18711] OpenAPI Schema references not generating correctly

---

parent/pom.xml

Backport of eab0922607ccc1621920164d6c860e079f281a0e

Upgrade Pulsar to version 2.10.2

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java

@davsclaus Sorry for breaking your cool demo!  This should fix the bug when running the following:
```
$ camel run <file> --console
```

CAMEL-18716: camel-jbang - Fix reading options after parameters for run

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade ivy to version 2.5.1

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade scandium version to 2.7.4

Upgrade scandium version to 2.7.4

---

components/camel-dns/src/test/java/org/apache/camel/component/dns/cloud/DnsServiceDiscoveryTest.java

✅ Gmail xmpp was dismissed, use jabber

---

core/camel-core-engine/src/main/docs/modules/eips/partials/eip-options.adoc
docs/components/modules/dataformats/partials/dataformat-options.adoc
docs/components/modules/languages/partials/language-options.adoc

Corrects "false" not shown for EIP option defaults and all default values for options for languages and dataformats

CAMEL-18724: fix display of default values in website

---

components/camel-dataset/src/main/java/org/apache/camel/component/dataset/DataSetConsumer.java

(chores) camel-dataset: avoid checking data set index when creating the exchanges

---

components/camel-ftp/src/main/docs/ftp-component.adoc

Trivial fix to camel-ftp docs: delete out of place text

camel-ftp: fix docs

---

docs/user-manual/modules/ROOT/pages/using-propertyplaceholder.adoc

trivial: fix typo in property-placeholder docs

property-placeholder: fix doc typo

---

camel-dependencies/pom.xml
dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/pom.xml
dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/src/main/java/org/apache/camel/maven/dsl/yaml/GenerateYamlDeserializersMojo.java
parent/pom.xml
tooling/maven/camel-package-maven-plugin/pom.xml
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/GenerateInvokeOnHeaderMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/TypeConverterLoaderGeneratorMojo.java

Change maven group to io.smallrye.
Adapt to minor API changes in Jandex 3.

CAMEL-18707: Upgrade to Jandex 3.0.3

---

camel-dependencies/pom.xml
components/camel-activemq/pom.xml
components/camel-aws/camel-aws2-cw/pom.xml
dsl/camel-jbang/camel-jbang-core/pom.xml
parent/pom.xml
pom.xml

Maven 4 is a bit more restrictive, so the build should be cleaned a bit

Fix build problems

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade jettison to 1.5.2

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade grpc to 1.48.2 and upgrade ${grpc-protobuf-version} to the version in io.grpc:grpc-protobuf

Upgrade grpc/protobuf to 1.48.2/3.21.7

---

camel-dependencies/pom.xml
dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/pom.xml
dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/src/main/java/org/apache/camel/maven/dsl/yaml/GenerateYamlDeserializersMojo.java
dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/src/main/java/org/apache/camel/maven/dsl/yaml/GenerateYamlSupportMojo.java
parent/pom.xml
tooling/maven/camel-package-maven-plugin/pom.xml
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/GenerateInvokeOnHeaderMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/TypeConverterLoaderGeneratorMojo.java

CAMEL-18707: upgrade to Jandex 3

---

dsl/camel-js-dsl/src/main/java/org/apache/camel/dsl/js/JavaScriptRoutesBuilderLoader.java

- [x ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/CAMEL) filed for the change (usually before you start working on it).  Trivial changes like typos do not require a JIRA issue.  Your pull request should address just this issue, without pulling in other changes.
- [x ] Each commit in the pull request should have a meaningful subject line and body.
- [x ] If you're unsure, you can format the pull request title like `[CAMEL-XXX] Fixes bug in camel-file component`, where you replace `CAMEL-XXX` with the appropriate JIRA issue.
- [x ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x ] Run `mvn clean install -Psourcecheck` in your module with source check enabled to make sure basic checks pass and …

allow ES modules in JS DSL

---

components/camel-thrift/README.md

In components/camel-thrift/README.md, the steps for building thrift compiler is described as follows.
```
sudo ./bootstrap.sh
export CXXFLAGS='-Os -ffunction-sections -Wl,--gc-sections -fno-asynchronous-unwind-tables -Wl,--strip-all'
sudo ./configure --without-c_glib --without-java --without-python --without-ruby --without-nodejs --disable-libs --disable-tests --disable-tutorial --disable-shared --enable-static
sudo make check
sudo make install
```
But these commands are unnecessarily verbose.
* `sudo`s are not required except for the last one
* `CXXFLAGS` doesn't seem to be necessary, at least for recent Thrift releases
* The `--disable-libs` option supercedes other `--without-*` options. Other `--disable-*` options also seem to be unnecessary
* `make check` is not mandatory, only `make` …

docs - Simplify steps for building thrift compiler

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/hbase.json
components/camel-hbase/pom.xml
components/camel-hbase/src/generated/resources/META-INF/services/org/apache/camel/component.properties
components/camel-hbase/src/generated/resources/org/apache/camel/component/hbase/hbase.json
components/camel-hbase/src/main/docs/hbase-component.adoc
dsl/camel-componentdsl/src/generated/java/org/apache/camel/builder/component/ComponentsBuilderFactory.java
dsl/camel-componentdsl/src/generated/java/org/apache/camel/builder/component/dsl/HbaseComponentBuilderFactory.java
dsl/camel-componentdsl/src/generated/resources/metadata.json
dsl/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/StaticEndpointBuilders.java
dsl/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/dsl/HBaseEndpointBuilderFactory.java

camel-hbase: deprecate the component

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/components/spark.json
components/camel-spark/pom.xml
components/camel-spark/src/generated/resources/META-INF/services/org/apache/camel/component.properties
components/camel-spark/src/generated/resources/org/apache/camel/component/spark/spark.json
components/camel-spark/src/main/docs/spark-component.adoc
dsl/camel-componentdsl/src/generated/java/org/apache/camel/builder/component/ComponentsBuilderFactory.java
dsl/camel-componentdsl/src/generated/java/org/apache/camel/builder/component/dsl/SparkComponentBuilderFactory.java
dsl/camel-componentdsl/src/generated/resources/metadata.json
dsl/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/StaticEndpointBuilders.java
dsl/camel-endpointdsl/src/generated/java/org/apache/camel/builder/endpoint/dsl/SparkEndpointBuilderFactory.java

CAMEL-18756: deprecate the spark component

---

components/camel-elasticsearch/src/main/docs/elasticsearch-component.adoc

📝 Add SB Autoconfiguration paragraph

---

components/camel-hdfs/pom.xml
components/camel-hdfs/src/main/java/org/apache/camel/component/hdfs/HdfsCompressionCodec.java
components/camel-hdfs/src/test/java/org/apache/camel/component/hdfs/HdfsProducerTest.java

CAMEL-18762: camel-hdfs - Add LZ4 and Zstd compression support

---

components/camel-milo/src/main/java/org/apache/camel/component/milo/client/MiloClientProducer.java
components/camel-milo/src/main/java/org/apache/camel/component/milo/client/internal/SubscriptionManager.java

In our usecase we need to get the response from the server when writing values to OPC UA via Milo. 
I've tried to ask on [zulipchat|https://camel.zulipchat.com/#narrow/stream/257298-camel/topic/Result.20from.20camel-milo.20endpoint] and also create an issue on jira without any response.
I tried to run a clean build in the component directory but tests failed both on master and my branch

[CAMEL-18618] Milo component: Return status from write

---

components/camel-hdfs/src/main/java/org/apache/camel/component/hdfs/HdfsNormalFileHandler.java

CAMEL-18776: camel-hdfs - Fix HdfsNormalFileHandler to handle temporary file path correctly

---

components/camel-mail/src/test/java/org/apache/camel/component/mail/MailAttachmentNamesTest.java
components/camel-mail/src/test/java/org/apache/camel/component/mail/MailBindingAttachmentFileTest.java

Remove references to junit 4 in camel-mail

---

camel-dependencies/pom.xml
components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/SetCorrelationContextProcessor.java
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/SpanProcessorsTest.java
parent/pom.xml

- Will separately look into `camel-opentelemetry-starter` and provide PR by it's related repo if required.

Upgrade opentelemetry to the version 1.20.1

---

test-infra/README.md

Fix a broken link to the test-infra document

---

components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/AttributeProcessor.java
components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/GetCorrelationContextProcessor.java
components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/OpenTelemetrySpanAdapter.java
components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/SetCorrelationContextProcessor.java
components/camel-opentelemetry/src/main/java/org/apache/camel/opentelemetry/propagators/OpenTelemetryGetter.java
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/ABCRouteTest.java
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/CamelOpenTelemetryTestSupport.java
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/ClientRecipientListRouteTest.java
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/CustomComponentNameRouteTest.java
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/MulticastParallelRouteTest.java
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/MulticastRouteTest.java
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/RouteConcurrentTest.java
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/SpanProcessorsTest.java
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/TestSEDASpanDecorator.java
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/TwoServiceTest.java
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/TwoServiceWithExcludeTest.java

As per conversation in https://github.com/apache/camel/pull/8830 with couple of additional tiny cleanups

Cleanup the camel-opentelemetry codebase a bit

---

components/camel-kafka/pom.xml
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/BaseEmbeddedKafkaAuthTestSupport.java
components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerAuthIT.java
components/camel-kafka/src/test/resources/kafka-jaas.config
test-infra/camel-test-infra-kafka/src/test/java/org/apache/camel/test/infra/kafka/services/ContainerLocalAuthKafkaService.java

camel-kafka: added an auth-based IT test

---

camel-dependencies/pom.xml
parent/pom.xml

Update PostgreSQL JDBC Driver to 42.4.3

---

components/camel-jaxb/src/main/java/org/apache/camel/converter/jaxb/JaxbDataFormat.java
components/camel-jgroups/src/main/java/org/apache/camel/component/jgroups/JGroupsFilters.java
components/camel-jgroups/src/main/java/org/apache/camel/component/jgroups/cluster/JGroupsLockClusterView.java
components/camel-jmx/src/main/java/org/apache/camel/component/jmx/JMXConsumer.java
components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpConsumer.java
components/camel-knative/camel-knative-http/src/main/java/org/apache/camel/component/knative/http/KnativeHttpSupport.java
components/camel-metrics/src/main/java/org/apache/camel/component/metrics/messagehistory/MetricsMessageHistoryService.java

Solving some sonar issues about [replacing inner classes with lambdas](https://rules.sonarsource.com/java/tag/java8/RSPEC-1604).

(chores) replacing more inner classes with lambda

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java

Besides KameletBinding we can also run Camel K Integration custom resources via JBang

CAMEL-18800 - Support Camel K integration in JBang run command

---

components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/SftpConfiguration.java

Update documentation for applicable algorithms supported according to http://www.jcraft.com/jsch/README.
Will remove a reference to ed25519 as that's not supported by the used jsch library.

CAMEL-18804 update documentation camel-sftp component

---

docs/main/modules/getting-started/pages/index.adoc

(chores) documentation: initial cleanup of fundamentals

---

docs/main/modules/getting-started/pages/index.adoc

(chores) documentation: add a section about creating the project

---

core/camel-api/src/main/java/org/apache/camel/cloud/ServiceHealth.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractDynamicRegistry.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/ProvisionalEndpointRegistry.java
core/camel-base/src/main/java/org/apache/camel/component/properties/PropertiesComponent.java
core/camel-util/src/main/java/org/apache/camel/util/OgnlHelper.java
core/camel-util/src/main/java/org/apache/camel/util/URIScanner.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/KnownKameletRoutesBuilderLoader.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojo.java

More sonar issues cleanup.
Now about [this rule](https://sonarcloud.io/organizations/apache/rules?open=java%3AS1596&rule_key=java%3AS1596)

(chores) replace raw empty collections by generic one

---

docs/main/modules/getting-started/pages/index.adoc

- Also cleanup a few sections ahead to reduce duplications

(chores) documentation: complement documentation about understanding the sample project

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade woodstox-core to 6.4.0 - ran the tests on camel-spring-xml/camel-stax and they pass.

Upgrade woodstox-core to 6.4.0

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade commons-net to 3.9.0, passed tests on camel-cxf/* and camel-ftp

Upgrade commons-net to 3.9.0

---

camel-dependencies/pom.xml
parent/pom.xml

Update hbase to 2.5.2

---

camel-dependencies/pom.xml
parent/pom.xml

Update sshd-version to 2.9.2, ran tests on camel-jsch / camel-ssh

Update sshd-version to 2.9.2

---

components/camel-hyperledger-aries/src/main/java/org/apache/camel/component/aries/handler/PresentProofServiceHandler.java

[Hyperledger-Aries] Add support for service=present-proof/send-proposal

---

core/camel-core-model/src/main/java/org/apache/camel/model/RouteDefinitionHelper.java

Fix related to following discussion: https://lists.apache.org/thread/70j2ftwdym70q5yvq6jllo07f3w693f7

CAMEL-18812 Fix REST DSL configuration placeholder for id

---

components/camel-http/src/main/java/org/apache/camel/component/http/HttpComponent.java

Wrong method was mistakenly invoked, fixed

CAMEL-16262 fixed automaticRetriesDisabled option setting in http component

---

components/camel-hbase/src/main/docs/hbase-component.adoc
components/camel-hbase/src/main/java/org/apache/camel/component/hbase/HBaseConstants.java
components/camel-hbase/src/main/java/org/apache/camel/component/hbase/HBaseProducer.java
components/camel-hbase/src/test/java/org/apache/camel/component/hbase/HBaseProducerIT.java

CAMEL-18817: camel-hbase - Support append and increment operations in the producer

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade to couchbase 3.4.1

---

components/camel-hbase/pom.xml

fixes https://issues.apache.org/jira/browse/CAMEL-18819

CAMEL-18819 hbase: excluded audience-annotations from zookeeper

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade to kubernetes client 6.3.1

---

tests/camel-itest/src/test/java/org/apache/camel/itest/sql/FromJmsToJdbcIdempotentConsumerToJmsTest.java
tests/camel-itest/src/test/java/org/apache/camel/itest/sql/FromJmsToJdbcIdempotentConsumerToJmsXaTest.java

There were 2 negative tests being disabled in 2013:
https://github.com/apache/camel/commit/aaf3eb9174df2bc1c897d8f6cf5575b2aa9a5c19
They are re-enabled today:
https://github.com/apache/camel/commit/e5899213a4cc2464b382d7fafd2f961a18ab7ebb
And run pretty fast (so no need to wait up to 30 or 40 seconds anymore)
This PR attempts to cleanup these tests a bit.

cleanup tests after enabling by the previous commit

---

components/camel-kudu/pom.xml

I propose merging it after #8918 so that we can ensure its fix works as expected.

CAMEL-18827: camel-kudu - Fix unit test failure with JDK 17

---

.github/actions/install-packages/action.yml
.github/workflows/pr-build.yml

CAMEL-18826: camel-kudu - Install libtinfo on CI to execute all Kudu's unit tests

---

components/camel-kudu/src/main/docs/kudu-component.adoc

It's a follow-up for #8921. Tested locally with running `cd docs; ./local-build.sh`.

CAMEL-18828 (addendum): camel-kudu - Update the component reference

---

components/camel-aws/camel-aws-cloudtrail/src/main/java/org/apache/camel/component/aws/cloudtrail/CloudtrailConsumer.java
components/camel-aws/camel-aws-secrets-manager/src/main/java/org/apache/camel/component/aws/secretsmanager/vault/CloudTrailReloadTriggerTask.java
components/camel-exec/src/main/java/org/apache/camel/component/exec/impl/DefaultExecCommandExecutor.java
components/camel-ftp/src/main/java/org/apache/camel/component/file/remote/SftpOperations.java
components/camel-google/camel-google-calendar/src/main/java/org/apache/camel/component/google/calendar/BatchGoogleCalendarClientFactory.java

Solving some sonar issues about [use of Collection.isEmpty() to test for emptiness ](https://sonarcloud.io/organizations/apache/rules?open=java%3AS1155&rule_key=java%3AS1155).

(chores) replace size() > 0 by !isEmpty()

---

components/camel-google/camel-google-drive/src/main/java/org/apache/camel/component/google/drive/BatchGoogleDriveClientFactory.java
components/camel-google/camel-google-mail/src/main/java/org/apache/camel/component/google/mail/BatchGoogleMailClientFactory.java
components/camel-google/camel-google-sheets/src/main/java/org/apache/camel/component/google/sheets/BatchGoogleSheetsClientFactory.java
components/camel-olingo4/camel-olingo4-api/src/main/java/org/apache/camel/component/olingo4/api/impl/Olingo4AppImpl.java
components/camel-test/camel-test-spring/src/main/java/org/apache/camel/test/spring/CamelAnnotationsHandler.java

Solving some more sonar issues about [use of Collection.isEmpty() to test for emptiness ](https://sonarcloud.io/organizations/apache/rules?open=java%3AS1155&rule_key=java%3AS1155).

(chores) More of replace size() > 0 by !isEmpty()

---

dsl/camel-jbang/camel-jbang-main/dist/CamelJBang.java
dsl/camel-jbang/camel-jbang-main/src/main/jbang/main/CamelJBang.java

camel-jbang - Upgrade to Camel 3.20.0

---

core/camel-core-engine/src/main/docs/modules/eips/pages/log-eip.adoc

Fix spelling mistake of `LoggingLevel`

Fix spelling mistake

---

camel-dependencies/pom.xml
parent/pom.xml

CAMEL-18839: Upgrade to Kafka 3.3.1

---

core/camel-core-engine/src/main/docs/modules/eips/pages/eventDrivenConsumer-eip.adoc

The xref is pointing to a file which I believe is incorrect.

Fix polling consumer incorrect xref in Event Driven Consumer

---

camel-dependencies/pom.xml
parent/pom.xml
test-infra/camel-test-infra-solr/src/test/java/org/apache/camel/test/infra/solr/services/SolrLocalContainerService.java

Align all Lucene and Solr versions to 8.11.2

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade Spark to 3.3.1

---

components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarConfiguration.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/PulsarProducer.java
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/integration/PulsarProducerInIT.java

Currently, Pulsar producer can't send a message larger than maxMessageSize. This PR enables the producer to chunk such a message for overcoming this limitation.

CAMEL-18863: camel-pulsar - Support chunking to enable sending a large message

---

components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3Producer.java

fixes https://issues.apache.org/jira/browse/CAMEL-18868

CAMEL-18868 Aws2-s3: CreateDownloadLink does not work with useDefaultCredentialsProvider

---

components/camel-sjms/pom.xml
components/camel-sjms2/pom.xml
components/camel-sjms2/src/test/java/org/apache/camel/component/sjms2/SimpleJms2ComponentTest.java
components/camel-sjms2/src/test/java/org/apache/camel/component/sjms2/Sjms2ComponentRestartTest.java
components/camel-sjms2/src/test/java/org/apache/camel/component/sjms2/Sjms2EndpointNameOverrideTest.java
components/camel-sjms2/src/test/java/org/apache/camel/component/sjms2/Sjms2EndpointTest.java
components/camel-sjms2/src/test/java/org/apache/camel/component/sjms2/support/Jms2TestSupport.java
parent/pom.xml
test-infra/camel-test-infra-artemis/src/test/java/org/apache/camel/test/infra/artemis/services/AbstractArtemisEmbeddedService.java
test-infra/camel-test-infra-artemis/src/test/java/org/apache/camel/test/infra/artemis/services/ArtemisService.java
test-infra/camel-test-infra-artemis/src/test/java/org/apache/camel/test/infra/artemis/services/ArtemisServiceFactory.java
test-infra/camel-test-infra-artemis/src/test/java/org/apache/camel/test/infra/artemis/services/ArtemisTCPAllProtocolsService.java

CAMEL-18779: Refactor sjms2

---

.github/workflows/pr-build.yml

(chores) ci: include camel-3.x on PR actions

---

camel-dependencies/pom.xml
parent/pom.xml
test-infra/camel-test-infra-cassandra/src/test/java/org/apache/camel/test/infra/cassandra/services/CassandraLocalContainerService.java

Ensured that all existing unit and integration tests for Cassandra passed.

Upgrade Cassandra to 4.1.0

---

core/camel-core/src/test/java/org/apache/camel/impl/DefaultComponentAutowiredFalseTest.java
core/camel-support/src/main/java/org/apache/camel/support/DefaultEndpoint.java

fixes https://issues.apache.org/jira/browse/CAMEL-18878
Fix + JUnit test

CAMEL-18878 Autowiring on endpoint works even if is disabled on component

---

components/camel-paho/pom.xml
components/camel-paho/src/test/java/org/apache/camel/component/paho/PahoComponentTest.java
components/camel-paho/src/test/java/org/apache/camel/component/paho/PahoOverrideTopicTest.java
components/camel-paho/src/test/java/org/apache/camel/component/paho/PahoReconnectAfterFailureTest.java
components/camel-paho/src/test/java/org/apache/camel/component/paho/PahoTestSupport.java
components/camel-paho/src/test/java/org/apache/camel/component/paho/PahoToDSendDynamicTest.java
components/camel-paho/src/test/java/org/apache/camel/component/paho/PahoToDTest.java
test-infra/camel-test-infra-artemis/src/test/java/org/apache/camel/test/infra/artemis/services/AbstractArtemisEmbeddedService.java
test-infra/camel-test-infra-artemis/src/test/java/org/apache/camel/test/infra/artemis/services/ArtemisMQTTService.java
test-infra/camel-test-infra-artemis/src/test/java/org/apache/camel/test/infra/artemis/services/ArtemisServiceFactory.java

I'll backport this PR on main branch later on.

CAMEL-18779: Paho

---

parent/pom.xml

(chores) build: enable auto-format by default

---

pom.xml

(chores) camel 4: use Java 17 as the minimum version

---

.github/pull_request_template.md

(chores) camel 4: adjust the contribution template to help users identify the correct branch

---

components/camel-mllp/pom.xml
components/camel-mllp/src/test/java/org/apache/camel/component/mllp/MllpTcpServerConsumerTransactionTest.java

CAMEL-18892: Restore MLLP tests

---

dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/MavenDependencyDownloader.java
dsl/camel-kamelet-main/src/test/java/org/apache/camel/main/MavenDependencyResolverTest.java
parent/pom.xml

[CAMEL-18880] Upgrade to maven-resolver 1.9.2 (and prepare for 1.9.4)

---

parent/pom.xml

CAMEL-18887:camel-kotlin - Upgrade to 1.8

---

.github/workflows/push-build-camel-3.yml
.github/workflows/push-build-main.yml

- Use different branches
- Adjust messages
- Adjust labels

(chores) ci: adjust regen bot for Camel 3 / 4

---

camel-dependencies/pom.xml
components/camel-attachments/pom.xml
parent/pom.xml

Jakarta Migration: Fixed Mail tests

---

camel-dependencies/pom.xml
components/camel-solr/pom.xml
parent/pom.xml

It seems it needs a provider for Jakarta Mail Specification 2.1+

camel-solr: fixed tests for Jakarta / Camel 4

---

components/pom.xml

Enable camel stomp

---

camel-dependencies/pom.xml
parent/pom.xml

CAMEL-18932: Upgrade to slf4j-api 2.0.6

---

dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/MavenDependencyDownloader.java
parent/pom.xml

[CAMEL-18880] Upgrade to maven-resolver 1.9.4

---

components/camel-cxf/camel-cxf-spring-rest/pom.xml
components/camel-cxf/camel-cxf-spring-soap/pom.xml
components/camel-cxf/camel-cxf-spring-soap/src/test/java/org/apache/camel/component/cxf/jms/CxfEndpointJMSConsumerTest.java
components/camel-cxf/camel-cxf-spring-soap/src/test/resources/org/apache/camel/component/cxf/jms/camel-context.xml

CXF tests - use artemis

---

docs/user-manual/modules/ROOT/pages/jmx.adoc

Fixed typos and reworded some sentences in JMX doc

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade rest assured

---

parent/pom.xml

Add pom type to the camel-core-all entry in parent/pom.xml

Add <type>pom</type to camel-core-all (no JAR)

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaConsumerAuthIT.java

This test runs OK locally, but fails on Apache CI.

(chores) camel-kafka: disable connection check test on Apache CI

---

test-infra/camel-test-infra-minio/src/test/java/org/apache/camel/test/infra/minio/services/MinioLocalContainerService.java

The test was failing on the CI due to `XMinioServerNotInitialized`, though minio/health/ready exists, liveness probe can be used https://min.io/docs/minio/linux/operations/monitoring/healthcheck-probe.html#node-liveness

Use live healthcheck from doc

---

dsl/camel-kotlin-dsl/src/main/docs/kotlin-dsl.adoc

There is a small typo in the extension of a sample file

Update kotlin-dsl-adoc 

---

pom.xml

Please, do not squash these, as it would make bisecting problems with these - if any - harder.

(chores) Upgrade a few Maven test plugins

---

components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Endpoint.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/AmazonSQSClientMock.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/SqsProducerDelayedQueueuTest.java

fixes https://issues.apache.org/jira/browse/CAMEL-18968

CAMEL-18968 Camel-aws2-sqs - Queue url might stay empty 

---

components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Endpoint.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/AmazonSQSClientMock.java
components/camel-aws/camel-aws2-sqs/src/test/java/org/apache/camel/component/aws2/sqs/SqsProducerDelayedQueueuTest.java

fixes https://issues.apache.org/jira/browse/CAMEL-18968
cherry-picked c34f248aa816e7389aa0a078365b98a99d86c7fb (from https://github.com/apache/camel/pull/9192)

CAMEL-18968 Camel-aws2-sqs - Queue url might stay empty.

---

camel-dependencies/pom.xml
components/camel-pulsar/src/test/java/org/apache/camel/component/pulsar/integration/PulsarSuspendRouteIT.java
parent/pom.xml

Update pulsar version and align test to pulsar one, in 2.11.0 the behaviour of the producer changed, though one test needed to be updated, for more information https://github.com/apache/pulsar/issues/19320

Update pulsar version

---

components/camel-aws/camel-aws-secrets-manager/src/test/java/org/apache/camel/component/aws/secretsmanager/integration/SecretsManagerCreateSecretProducerLocalstackIT.java
components/camel-aws/camel-aws-secrets-manager/src/test/java/org/apache/camel/component/aws/secretsmanager/integration/SecretsManagerDescribeSecretProducerLocalstackIT.java
components/camel-aws/camel-aws-secrets-manager/src/test/java/org/apache/camel/component/aws/secretsmanager/integration/SecretsManagerProducerListSecretsLocalstackIT.java
components/camel-aws/camel-aws-secrets-manager/src/test/java/org/apache/camel/component/aws/secretsmanager/integration/SecretsManagerRotateSecretProducerLocalstackIT.java
components/camel-aws/camel-aws-secrets-manager/src/test/java/org/apache/camel/component/aws/secretsmanager/integration/SecretsManagerUpdateSecretProducerLocalstackIT.java
components/camel-aws/camel-aws2-ddb/src/test/java/org/apache/camel/component/aws2/ddbstream/Ddb2StreamConsumerHealthCustomClientTest.java
components/camel-aws/camel-aws2-kinesis/src/test/java/org/apache/camel/component/aws2/kinesis/Kinesis2ConsumerHealthCustomClientTest.java
components/camel-aws/camel-aws2-kms/src/test/java/org/apache/camel/component/aws2/kms/localstack/KmsCreateKeyIT.java
components/camel-aws/camel-aws2-kms/src/test/java/org/apache/camel/component/aws2/kms/localstack/KmsDisableKeyIT.java
components/camel-aws/camel-aws2-kms/src/test/java/org/apache/camel/component/aws2/kms/localstack/KmsListKeysIT.java
components/camel-aws/camel-aws2-lambda/src/test/java/org/apache/camel/component/aws2/lambda/integration/LambdaAliasesIT.java
components/camel-aws/camel-aws2-lambda/src/test/java/org/apache/camel/component/aws2/lambda/integration/LambdaDeleteFunctionIT.java
components/camel-aws/camel-aws2-lambda/src/test/java/org/apache/camel/component/aws2/lambda/integration/LambdaListFunctionsIT.java
components/camel-aws/camel-aws2-sns/src/test/java/org/apache/camel/component/aws2/sns/integration/SnsTopicProducerIT.java

(chores) tests: fixed disabled reasons for multiple tests

---

core/camel-core/src/test/java/org/apache/camel/component/bean/BeanChoseMethodWithMatchingTypeAndSkipSettersTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/cluster/FileLockClusteredRoutePolicyFactoryTest.java
core/camel-core/src/test/java/org/apache/camel/component/file/cluster/FileLockClusteredRoutePolicyTest.java
core/camel-core/src/test/java/org/apache/camel/processor/SplitCustomExpressionTest.java
core/camel-core/src/test/java/org/apache/camel/processor/SplitRefCustomExpressionTest.java
core/camel-core/src/test/java/org/apache/camel/processor/async/MyAsyncComponent.java
core/camel-core/src/test/java/org/apache/camel/processor/transformer/TransformerRouteTest.java

- remove unnecessary override
- simplify list creation
- use try-with-resources

(chores) camel-core: tests cleanups

---

components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FromFileToFtpSplitParallelIT.java

- prevent running on nodes without enough resources
- size the pool to the number of available processors

(chores) camel-ftp: cleanup FromFileToFtpSplitParallelIT

---

camel-dependencies/pom.xml
core/camel-core-engine/src/main/docs/modules/eips/pages/toD-eip.adoc
parent/pom.xml
tests/camel-partial-classpath-test/pom.xml

Remove activemq references

---

components/camel-plc4x/src/main/docs/plc4x-component.adoc
components/camel-plc4x/src/main/java/org/apache/camel/component/plc4x/Plc4XConsumer.java
components/camel-plc4x/src/main/java/org/apache/camel/component/plc4x/Plc4XEndpoint.java
components/camel-plc4x/src/main/java/org/apache/camel/component/plc4x/Plc4XPollingConsumer.java
components/camel-plc4x/src/main/java/org/apache/camel/component/plc4x/Plc4XProducer.java
components/camel-plc4x/src/test/java/org/apache/camel/component/plc4x/Plc4XComponentTest.java
components/camel-plc4x/src/test/java/org/apache/camel/component/plc4x/Plc4XEndpointTest.java
components/camel-plc4x/src/test/java/org/apache/camel/component/plc4x/Plc4XProducerTest.java

I made several pull requests for improvements to the plc4x component which were merged into main. I'd like my changes to also be included in the next camel 3 release, so I want to merge them into 3.x too. 
I made no changes compared to the pull requests merged into main.

camel-plc4x: plc4x improvements in camel 3 (CAMEL-18861)

---

dsl/camel-xml-io-dsl/src/main/java/org/apache/camel/dsl/xml/io/XmlRoutesBuilderLoader.java
dsl/camel-xml-io-dsl/src/test/java/org/apache/camel/dsl/xml/io/XmlRoutesBuilderLoaderTest.java

CAMEL-19006: parse templatedRoutes without XML namespace

---

test-infra/camel-test-infra-azure-common/src/test/java/org/apache/camel/test/infra/azure/common/services/AzuriteContainer.java

This PR upgrades Azurite to the current latest version.
This change is a minor upgrade of test container and doesn't need a JIRA issue.

Upgrade Azurite to 3.21.0

---

components/camel-gson/src/main/java/org/apache/camel/component/gson/GsonDataFormat.java
components/camel-gson/src/test/java/org/apache/camel/component/gson/SpringGsonJsonDataFormatTest.java
components/camel-gson/src/test/java/org/apache/camel/component/gson/TestPojo.java
components/camel-gson/src/test/resources/org/apache/camel/component/gson/SpringGsonJsonDataFormatTest.xml
core/camel-core-model/src/main/java/org/apache/camel/model/dataformat/JsonDataFormat.java
core/camel-core-reifier/src/main/java/org/apache/camel/reifier/dataformat/JsonDataFormatReifier.java

PR for https://issues.apache.org/jira/browse/CAMEL-19009

CAMEL-19009: camel-gson - Date Format with GsonBuilder

---

components/camel-snmp/src/main/java/org/apache/camel/component/snmp/SnmpTrapProducer.java
components/camel-snmp/src/test/java/org/apache/camel/component/snmp/AbstractTrapTest.java
components/camel-snmp/src/test/java/org/apache/camel/component/snmp/Snmpv1TrapTest.java
components/camel-snmp/src/test/java/org/apache/camel/component/snmp/Snmpv2TrapTest.java

CAMEL-18980: Fix snmp  V1

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade wildfly-elytron to from 1.15.4.Final to 1.15.15.Final, ran tests on camel-elytron, passed

Upgrade wildfly-elytron to 1.15.15.Final

---

components/camel-test/camel-test-junit5/src/main/java/org/apache/camel/test/junit5/CamelTestSupport.java

fixes https://issues.apache.org/jira/browse/CAMEL-19047

CAMEL-19047 CamelTestSupport (junit5) - some checks does not work with Lifecycle.PER_CLASS

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogBaseCommand.java

Camel-Jbang catalog output in JSON
https://issues.apache.org/jira/browse/CAMEL-19044

Implements CAMEL-19044

---

core/camel-core/src/test/java/org/apache/camel/processor/SagaTimeoutTest.java
core/camel-support/src/main/java/org/apache/camel/saga/InMemorySagaCoordinator.java

CAMEL-19031: Check current saga status is RUNNING before add a step

---

core/camel-core-processor/src/main/java/org/apache/camel/processor/saga/SagaProcessor.java
core/camel-core/src/test/java/org/apache/camel/processor/SagaPropagationTest.java

CAMEL-19068: remove SAGA_LONG_RUNNING_ACTION in out Message

---

components/camel-kafka/src/test/java/org/apache/camel/component/kafka/integration/KafkaSagaIT.java

CAMEL-19065: camel-kafka - Add KafkaSagaIT test

---

camel-dependencies/pom.xml
components/camel-tracing/src/main/java/org/apache/camel/tracing/ActiveSpanManager.java
parent/pom.xml

As https://github.com/open-telemetry/opentelemetry-java/issues/5055 seems to be fixed.

remove the ScopeWrapper workaround

---

parent/pom.xml

[CAMEL-19092] Upgrade to maven-resolver 1.9.5

---

core/camel-main/src/main/java/org/apache/camel/main/MainDurationEventNotifier.java

Mostly minor fixes, but do seem to provide some improvements overall:
```
-- Patch:
Mean: 528232.0625000002
Geometric mean: 518388.324464431
Standard deviation: 97022.2449142631
-- 4.0.0-M1 
Mean: 451989.19642857154
Geometric mean: 451657.5975966994
Standard deviation: 17755.625310286025
```

CAMEL-19060 + CAMEL-19058: minor improvements

---

components/camel-salesforce/camel-salesforce-codegen/src/main/java/org/apache/camel/component/salesforce/codegen/AbstractSalesforceExecution.java
components/camel-salesforce/camel-salesforce-codegen/src/main/java/org/apache/camel/component/salesforce/codegen/GenerateExecution.java

Fix deprecated API and properties in camel-salesforce-codegen

---

parent/pom.xml
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/PackageArchetypeCatalogMojo.java

check style was broken, I repair it

[Camel 19106] repair check style for 3.x

---

components/camel-micrometer/src/main/docs/micrometer-component.adoc
components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/DistributionStatisticConfigFilter.java
components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/MicrometerConstants.java
components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/routepolicy/MicrometerRoutePolicy.java
components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/routepolicy/MicrometerRoutePolicyConfiguration.java
components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/routepolicy/MicrometerRoutePolicyFactory.java
components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/routepolicy/MicrometerRoutePolicyNamingStrategy.java
components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/messagehistory/ManagedMessageHistoryTest.java
components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/routepolicy/AbstractMicrometerRoutePolicyTest.java
components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/routepolicy/MicrometerRoutePolicyConfigrationTest.java
components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/routepolicy/SharedMicrometerRoutePolicyTest.java

PR for main
PR for 3.x  - https://github.com/apache/camel/pull/9454/
* repair micrometer test
* CAMEL-19101 Features for Camel-Micrometer
* CAMEL-19101 code formatted passed
(cherry picked from commit ebc59c3e7b3a8197c2a7d01580e595a720c0494e)

CAMEL-19101: Features for Camel-Micrometer (#9454)

---

components/camel-platform-http-vertx/src/main/java/org/apache/camel/component/platform/http/vertx/VertxPlatformHttpConsumer.java
components/camel-platform-http-vertx/src/test/java/org/apache/camel/component/platform/http/vertx/VertxPlatformMultipleContentTypeTest.java

fixes https://issues.apache.org/jira/browse/CAMEL-19113
cherry-picked https://github.com/apache/camel/commit/c08a40c17a44cc48df896a0e81a1bce403b4709d

CAMEL-19113 Platform-http-vertx: consume (comma separated) does not work

---

core/camel-core-engine/src/main/docs/modules/eips/pages/saga-eip.adoc

Fix saga-eip timeout description

---

catalog/camel-catalog/src/main/java/org/apache/camel/catalog/CamelCatalog.java
catalog/camel-catalog/src/main/java/org/apache/camel/catalog/DefaultCamelCatalog.java
catalog/camel-catalog/src/test/java/org/apache/camel/catalog/CamelCatalogTest.java
catalog/camel-catalog/src/test/resources/org/apache/camel/catalog/bar/foo.txt
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Export.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportCamelMain.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportQuarkus.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportSpringBoot.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogComponent.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogDataFormat.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogDoc.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogLanguage.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/catalog/CatalogOther.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/CatalogLoader.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/DownloadListener.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/MavenDependencyDownloader.java

CAMEL-19120 export configurable template backport

---

parent/pom.xml

CAMEL-19126: camel-fhir upgrade to 6.4.2

---

Jenkinsfile.ppc64le

Added CI support in Jenkins for ppc64le arch

---

components/camel-dhis2/camel-dhis2-component/src/main/docs/dhis2-component.adoc

CAMEL-19050: doc correction

---

core/camel-core/src/test/java/org/apache/camel/builder/ExpressionBuilderConcurrencyTest.java
core/camel-support/src/main/java/org/apache/camel/support/builder/ExpressionBuilder.java

Signed-off-by: Rhuan Rocha <rhuan080@gmail.com>
Fixing the issue https://issues.apache.org/jira/projects/CAMEL/issues/CAMEL-19014

CAMEL-19014 - Fixing issue about concurrence on the SimpleLanguage

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelJBangMain.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/version/VersionCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/version/VersionGet.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/version/VersionList.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/VersionHelper.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/DependencyDownloader.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/MavenDependencyDownloader.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/util/VersionHelper.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/util/XmlHelper.java

CAMEL-19128: camel-jbang - Add version command

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/CommandLineHelper.java

Print user configuration values

---

dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CamelCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/common/CommandLineHelper.java

backport https://github.com/apache/camel/pull/9520

Print config values 3x

---

camel-dependencies/pom.xml

Fix https://issues.apache.org/jira/browse/CAMEL-18870

[CAMEL-18870] Error while generating OSGi manifest

---

components/camel-jdbc/src/main/docs/jdbc-component.adoc

Fix the named parameters example

---

components/camel-vertx/camel-vertx-http/src/main/docs/vertx-http-component.adoc

vertx-http: fix documentation

---

components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/BindyCsvFactory.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/annotation/CsvRecord.java
components/camel-bindy/src/test/java/org/apache/camel/dataformat/bindy/csv/BindySimpleCsvQuotingOnlyWhenNeededTest.java
components/camel-bindy/src/test/resources/org/apache/camel/dataformat/bindy/csv/BindyDoubleQuotesInFieldCsvUnmarshallTest-context.xml
components/camel-bindy/src/test/resources/org/apache/camel/dataformat/bindy/csv/BindySingleQuotesWithDoubleQuotesInFieldCsvUnmarshallTest-context.xml

Cherry-picks from commits in https://github.com/apache/camel/pull/9546

CAMEL-19143: Added option to quote fields only when necessary

---

dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/MavenDependencyDownloader.java

Ignore artifacts that do not exists on repository

Download only existing artifacts

---

dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/MavenDependencyDownloader.java

backport https://github.com/apache/camel/pull/9563

Safe download artifacts

---

components/camel-olingo4/camel-olingo4-component/src/main/java/org/apache/camel/component/olingo4/Olingo4Endpoint.java
components/camel-olingo4/camel-olingo4-component/src/test/java/org/apache/camel/component/olingo4/Olingo4RouteTest.java

CAMEL-19150: camel-olingo4 - Fix missing olingo4 endpoint property names

---

components/camel-olingo2/camel-olingo2-component/src/main/java/org/apache/camel/component/olingo2/Olingo2Endpoint.java

CAMEL-19169: camel-olingo2 - Fix missing olingo2 endpoint property names

---

components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/DataLakeComponent.java
components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/DataLakeConfiguration.java
components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/DataLakeConfigurationOptionsProxy.java
components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/DataLakeConstants.java
components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/DataLakeExchangeHeaders.java
components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/client/DataLakeClientFactory.java
components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/client/DataLakeFileClientWrapper.java
components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/operations/DataLakeDirectoryOperations.java
components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/operations/DataLakeFileOperations.java
components/camel-azure/camel-azure-storage-datalake/src/test/java/org/apache/camel/component/azure/storage/datalake/operations/DataLakeFileOperationTest.java

Backport of CAMEL-19152, CAMEL-18636 to main

CAMEL-19152, CAMEL-18636: Backport to main

---

components/camel-jira/src/main/java/org/apache/camel/component/jira/consumer/AbstractJiraConsumer.java
components/camel-jira/src/main/java/org/apache/camel/component/jira/consumer/NewCommentsConsumer.java
components/camel-jira/src/main/java/org/apache/camel/component/jira/consumer/NewIssuesConsumer.java
components/camel-jira/src/main/java/org/apache/camel/component/jira/consumer/WatchUpdatesConsumer.java
components/camel-jira/src/test/java/org/apache/camel/component/jira/consumer/NewCommentsConsumerTest.java
components/camel-jira/src/test/java/org/apache/camel/component/jira/consumer/NewIssuesConsumerTest.java
components/camel-jira/src/test/java/org/apache/camel/component/jira/consumer/WatchUpdatesConsumerTest.java

- Issues returned are already ordered descendant - do not revert the order of issues a 2nd time
- Make sure to exit polling loop early when no further issues are returned (total # of issues returned is lower than query page size)
- Avoid duplicates in returned issue list
- Adjust query page size according to given max results limitation
- Fix ordering of mocked issue return values in unit tests (mocks should return issues in descendant order)
- Add more unit tests on new issues consumer (testing filter offset, pagination, duplicates)

CAMEL-19174: camel-jira - Fix duplicate messages created by Jira consumer

---

components/camel-couchbase/src/main/docs/couchbase-component.adoc

Fix minor documentation issues found during a review of the Couchbase component source code by your friends at Couchbase :-)
The product name is styled as "Couchbase" (not "CouchBase").
Reference:  https://www.couchbase.com
Couchbase Server 7.0 is the earliest version with full support for scopes and collections. (This feature was present in 6.5 only in "Developer Preview" mode, which is not intended for production use. If I recall correctly, modern versions of the Java SDK are not compatible with some aspects of the early developer preview implementation).
References:
* https://docs.couchbase.com/server/7.0/introduction/whats-new.html#whats-new-server-700
* https://docs.couchbase.com/server/6.5/developer-preview/preview-mode.html
Scopes and collections are supported in Couchbase Server …

Tiny doc update for Couchbase component

---

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/AS2ClientConnection.java
components/camel-consul/src/main/java/org/apache/camel/component/consul/endpoint/ConsulEventConsumer.java
components/camel-iec60870/src/main/java/org/apache/camel/component/iec60870/client/ClientConnection.java
components/camel-jcache/src/main/java/org/apache/camel/component/jcache/JCacheConsumer.java
components/camel-mock/src/main/java/org/apache/camel/component/mock/MockEndpoint.java
components/camel-netty/src/main/java/org/apache/camel/component/netty/ClientModeTCPNettyServerBootstrapFactory.java
components/camel-netty/src/main/java/org/apache/camel/component/netty/NettyHelper.java

Solving some sonar issues about [replacing inner classes with lambdas](https://rules.sonarsource.com/java/tag/java8/RSPEC-1604).

(chores) More of replacing inner classes with lambda

---

components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/DataLakeConfigurationOptionsProxy.java
components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/DataLakeConstants.java
components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/DataLakeExchangeHeaders.java
components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/client/DataLakeFileClientWrapper.java
components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/operations/DataLakeDirectoryOperations.java
components/camel-azure/camel-azure-storage-datalake/src/main/java/org/apache/camel/component/azure/storage/datalake/operations/DataLakeFileOperations.java
components/camel-azure/camel-azure-storage-datalake/src/test/java/org/apache/camel/component/azure/storage/datalake/operations/DataLakeFileOperationTest.java

Pls. see https://issues.apache.org/jira/browse/CAMEL-19152

CAMEL-19152 - Add file client header and flush option

---

docs/user-manual/modules/ROOT/pages/camel-4-migration-guide.adoc

Update Camel 4 Migration Guide: Add Dozer to removed components

---

parent/pom.xml
pom.xml

(cherry picked from commit b6a21448c60c3920856ca776593c2e3948711de4)

CAMEL-15520: replace deprecated maven property maven.test.skip.exec

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade graphql/hibernate versions (alignment with spring-boot-dependencies 2.7.10)

Upgrade graphql/hibernate versions (alignment with spring-boot-dependencies 2.7.10)

---

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/InternalServiceHelper.java

This helps further work to decouple and standardize the extension/plugin management

CAMEL-15105: move handling of internal services to a separate class

---

camel-dependencies/pom.xml
core/camel-util/src/main/java/org/apache/camel/util/SensitiveUtils.java
parent/pom.xml

Update impsort-maven-plugin to be compatible with maven 3.9

Update impsort for maven 3.9

---

camel-dependencies/pom.xml
parent/pom.xml

This PR upgrades Flink to 1.17.0 for ensuring Camel's Flink component works with the latest version of Flink. It's tested by the following command:
```
$ ./mvnw clean verify -f components/camel-flink/pom.xml
```
This PR doesn't require the corresponding JIRA issue since it's just a single dependency upgrade.

Upgrade Flink to version 1.17.0

---

docs/user-manual/modules/ROOT/pages/dsl.adoc

Added reference to groovy dsl

---

camel-dependencies/pom.xml
parent/pom.xml

CAMEL-19139: Add Build-Date in MANIFEST.MF

---

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java

I broke JMX enable/disable logic with one of the changes. This should fix the logic.

(chores) camel-base-engine: fix JMX enable/disable logic

---

core/camel-core-engine/src/main/docs/modules/eips/pages/intercept.adoc

Minor fix in Intercept component documentation.

Fix interceptSendToEndpoint closing tags.

---

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/EntityParser.java

`main` branch
https://issues.apache.org/jira/browse/CAMEL-19221
- [ x] I formatted the code using `mvn -Pformat,fastinstall install && mvn -Psourcecheck`

removed unused variable in EntityParser CAMEL-19221

---

components/camel-bean/src/main/java/org/apache/camel/component/bean/AbstractCamelInvocationHandler.java
components/camel-freemarker/src/test/java/org/apache/camel/component/freemarker/FreemarkerTemplateInHeaderTest.java
components/camel-google/camel-google-calendar/src/test/java/org/apache/camel/component/google/calendar/CalendarCalendarListIT.java
components/camel-velocity/src/test/java/org/apache/camel/component/velocity/VelocityTemplateInHeaderTest.java

Added for components early exit from loop when the condition is met

Added for components early exit from loop when the condition is met

---

components/camel-caffeine/src/test/java/org/apache/camel/component/caffeine/cache/CaffeineCacheTestSupport.java
components/camel-file/src/main/java/org/apache/camel/component/file/consumer/adapters/DefaultDirectoryEntriesResumeAdapter.java
components/camel-mllp/src/test/java/org/apache/camel/test/junit/rule/mllp/MllpServerResource.java
components/camel-salesforce/camel-salesforce-component/src/test/java/org/apache/camel/component/salesforce/AnalyticsApiIntegrationTest.java

Fixed number of args in logging strings

Fixed number of args in logging strings

---

core/camel-core-processor/src/main/java/org/apache/camel/processor/FatalFallbackErrorHandler.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/errorhandler/RedeliveryErrorHandler.java
core/camel-core-xml/src/main/java/org/apache/camel/core/xml/AbstractCamelContextFactoryBean.java

Added for CORE classes early exit from loop when the condition is met

Added for CORE classes early exit from loop when the condition is met

---

components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/AS2CompressionAlgorithm.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/AS2EncryptionAlgorithm.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/AS2MicAlgorithm.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/AS2DispositionType.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/DispositionMode.java
components/camel-as2/camel-as2-api/src/main/java/org/apache/camel/component/as2/api/entity/Importance.java
components/camel-caffeine/src/main/java/org/apache/camel/component/caffeine/EvictionType.java
components/camel-docker/src/main/java/org/apache/camel/component/docker/DockerOperation.java
components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/HazelcastOperation.java
components/camel-hazelcast/src/main/java/org/apache/camel/component/hazelcast/queue/HazelcastQueueConsumerMode.java
components/camel-hl7/src/main/java/org/apache/camel/component/hl7/HL7Charset.java
components/camel-jt400/src/main/java/org/apache/camel/component/jt400/Jt400Configuration.java
components/camel-olingo2/camel-olingo2-api/src/main/java/org/apache/camel/component/olingo2/api/impl/UriType.java
components/camel-pulsar/src/main/java/org/apache/camel/component/pulsar/utils/consumers/SubscriptionInitialPosition.java
components/camel-smpp/src/main/java/org/apache/camel/component/smpp/SmppCommandType.java
components/camel-spring-ws/src/main/java/org/apache/camel/component/spring/ws/type/EndpointMappingType.java
components/camel-telegram/src/main/java/org/apache/camel/component/telegram/TelegramMediaType.java
components/camel-telegram/src/main/java/org/apache/camel/component/telegram/TelegramParseMode.java
components/camel-zookeeper/src/main/java/org/apache/camel/component/zookeeper/NaturalSortComparator.java

fixed results of inspection "non-final fields in enum"

fixed results of inspection "non-final fields in enum"

---

components/camel-arangodb/src/main/java/org/apache/camel/component/arangodb/ArangoDbProducer.java
components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2Endpoint.java
components/camel-azure/camel-azure-cosmosdb/src/main/java/org/apache/camel/component/azure/cosmosdb/CosmosDbProducer.java
components/camel-azure/camel-azure-servicebus/src/main/java/org/apache/camel/component/azure/servicebus/ServiceBusConsumer.java
components/camel-azure/camel-azure-servicebus/src/main/java/org/apache/camel/component/azure/servicebus/ServiceBusProducer.java
components/camel-fhir/camel-fhir-component/src/main/java/org/apache/camel/component/fhir/FhirEndpoint.java
components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/MongoDbProducer.java
components/camel-xj/src/main/java/org/apache/camel/component/xj/XJConstants.java
core/camel-core-reifier/src/main/java/org/apache/camel/reifier/errorhandler/ErrorHandlerReifier.java

fixed results of inspection "HashMap can be substituted with EnumMap"

fixed results of inspection "HashMap can be substituted with EnumMap"

---

components/camel-file-watch/src/main/java/org/apache/camel/component/file/watch/FileWatchEndpoint.java
components/camel-file/src/main/java/org/apache/camel/component/file/FileEndpoint.java
components/camel-google/camel-google-pubsub/src/main/java/org/apache/camel/component/google/pubsub/GooglePubsubComponent.java
components/camel-infinispan/camel-infinispan-embedded/src/main/java/org/apache/camel/component/infinispan/embedded/InfinispanEmbeddedConsumer.java
components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/MongoDbComponent.java
components/camel-platform-http/src/main/java/org/apache/camel/component/platform/http/spi/Method.java

fixed results of inspection "HashSet can be replaced with EnumSet"

fixed results of inspection "HashSet can be replaced with EnumSet"

---

components/camel-olingo2/camel-olingo2-api/src/main/java/org/apache/camel/component/olingo2/api/impl/UriType.java
components/camel-quartz/src/test/java/org/apache/camel/component/quartz/QuartzManuallyTriggerJobTest.java
core/camel-util/src/main/java/org/apache/camel/util/HostUtils.java
dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/src/main/java/org/apache/camel/maven/dsl/yaml/GenerateYamlSupportMojo.java
dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/src/main/java/org/apache/camel/maven/dsl/yaml/support/ToolingSupport.java

replaced iterated addition to collection with bulk operation

replaced iterated addition to collection with bulk operation

---

components/camel-aws/camel-aws2-ddb/src/main/java/org/apache/camel/component/aws2/ddbstream/ShardList.java
components/camel-box/camel-box-component/src/main/java/org/apache/camel/component/box/internal/BoxConnectionHelper.java
components/camel-cxf/camel-cxf-rest/src/main/java/org/apache/camel/component/cxf/jaxrs/CxfRsComponent.java
components/camel-facebook/src/main/java/org/apache/camel/component/facebook/FacebookConsumer.java
components/camel-facebook/src/main/java/org/apache/camel/component/facebook/data/ReadingBuilder.java
components/camel-jetty/src/test/java/org/apache/camel/component/jetty/HttpHeaderCaseTest.java
components/camel-jmx/src/main/java/org/apache/camel/component/jmx/JMXEndpoint.java
components/camel-ldap/src/test/java/org/apache/directory/server/core/integ5/ServerAnnotationProcessor.java
components/camel-ldif/src/test/java/org/apache/directory/server/core/integ5/ServerAnnotationProcessor.java
components/camel-mock/src/main/java/org/apache/camel/component/mock/MockEndpoint.java
components/camel-netty-http/src/test/java/org/apache/camel/component/netty/http/NettyHttpHeaderCaseTest.java
components/camel-olingo2/camel-olingo2-component/src/main/java/org/apache/camel/component/olingo2/Olingo2Consumer.java
components/camel-olingo2/camel-olingo2-component/src/main/java/org/apache/camel/component/olingo2/Olingo2Index.java
components/camel-olingo2/camel-olingo2-component/src/main/java/org/apache/camel/component/olingo2/Olingo2Producer.java
components/camel-olingo4/camel-olingo4-component/src/main/java/org/apache/camel/component/olingo4/Olingo4Consumer.java
components/camel-olingo4/camel-olingo4-component/src/main/java/org/apache/camel/component/olingo4/Olingo4Index.java
components/camel-olingo4/camel-olingo4-component/src/main/java/org/apache/camel/component/olingo4/Olingo4Producer.java
components/camel-spring-xml/src/test/java/org/apache/camel/spring/scan/ScanTestSupport.java
components/camel-zookeeper-master/src/main/java/org/apache/camel/component/zookeepermaster/group/internal/ZooKeeperGroup.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/debugger/BacklogTracer.java
core/camel-base/src/main/java/org/apache/camel/converter/CollectionConverter.java
core/camel-core-model/src/main/java/org/apache/camel/builder/NotifyBuilder.java
core/camel-core/src/test/java/org/apache/camel/processor/SplitterPojoTest.java
core/camel-support/src/main/java/org/apache/camel/support/component/AbstractApiConsumer.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Run.java
dsl/camel-yaml-dsl/camel-yaml-dsl-maven-plugin/src/main/java/org/apache/camel/maven/dsl/yaml/GenerateYamlSupportMojo.java

replaced addAll() calls with parametrized constructor calls

replaced addAll() calls with parametrized constructor calls

---

components/camel-google/camel-google-pubsub/src/test/java/org/apache/camel/component/google/pubsub/unit/PubsubProducerTest.java
components/camel-mllp/src/test/java/org/apache/camel/test/junit/rule/mllp/MllpClientResource.java

fixed string format

---

components/camel-splunk/src/main/java/org/apache/camel/component/splunk/support/TcpDataWriter.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/SimpleCamelContext.java
core/camel-core/src/test/java/org/apache/camel/CamelParallelExecutionStrategy.java

fixed non-functional usage of Optional.isPresent()

fixed non-functional usage of Optional.isPresent()

---

core/camel-xml-io/src/main/java/org/apache/camel/xml/io/MXParser.java

simplified boolean conditions

---

components/camel-azure/camel-azure-storage-blob/src/main/java/org/apache/camel/component/azure/storage/blob/BlobConfigurationOptionsProxy.java
components/camel-azure/camel-azure-storage-blob/src/test/java/org/apache/camel/component/azure/storage/blob/integration/BlobConsumerIT.java

Currently, prefix is ignored. This is a bug detailed in [Zulip chat thread](https://camel.zulipchat.com/#narrow/stream/257298-camel/topic/CamelAzureBlob.20endpoint.20prefix). Once the pr is merged, prefix usage should be fixed. 
Step skipped, entire project build kept failing with message: 
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.10.1:compile (default-compile) on project camel-any23: Compilation failure: Compilation failure: 
[ERROR] error: error reading /Users/paulbogdanidorasi/.m2/repository/org/apache/tika/tika-parser-image-module/2.3.0/tika-parser-image-module-2.3.0.jar; zip file is empty
[ERROR] error: error reading /Users/paulbogdanidorasi/.m2/repository/org/apache/tika/tika-parser-mail-module/2.3.0/tika-parser-mail-module-2.3.0.jar; zip file …

CAMEL-19224: Fix blob consumer prefix usage

---

components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/BindyFixedLengthFactory.java
components/camel-box/camel-box-component/src/test/java/org/apache/camel/component/box/BoxFilesManagerIT.java
components/camel-cometd/src/main/java/org/apache/camel/component/cometd/CometdConsumer.java
components/camel-hdfs/src/test/java/org/apache/camel/component/hdfs/HdfsProducerTest.java
components/camel-http-common/src/main/java/org/apache/camel/http/common/CamelServlet.java
components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaConfiguration.java
components/camel-mllp/src/test/java/org/apache/camel/test/junit/rule/mllp/MllpServerResource.java
components/camel-netty/src/main/java/org/apache/camel/component/netty/handlers/ClientChannelHandler.java
components/camel-undertow/src/main/java/org/apache/camel/component/undertow/UndertowProducer.java
components/camel-xmlsecurity/src/main/java/org/apache/camel/component/xmlsecurity/api/XmlSignatureHelper.java
components/camel-zookeeper/src/main/java/org/apache/camel/component/zookeeper/cluster/ZooKeeperClusterView.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/WebSpherePackageScanClassResolver.java
core/camel-core-model/src/main/java/org/apache/camel/builder/PredicateClause.java
core/camel-util/src/main/java/org/apache/camel/util/AntPathMatcher.java
core/camel-util/src/main/java/org/apache/camel/util/StringHelper.java

simplified boolean expressions

simplified boolean expressions

---

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultCamelContextExtension.java

These ones w/ the exchange-related SPI need more careful refactoring. For now, just cleaning up their ownership.

CAMEL-15105: part 17

---

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java

Just a minor one to test the CI changes

(chores) Minor cleanup

---

catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/RouteCoverageMojo.java
components/camel-debezium/camel-debezium-common/camel-debezium-common-component/src/test/java/org/apache/camel/component/debezium/DebeziumConsumerTest.java
components/camel-google/camel-google-pubsub/src/test/java/org/apache/camel/component/google/pubsub/PubsubTestSupport.java
components/camel-mllp/src/test/java/org/apache/camel/component/mllp/MllpProducerConsumerLoopbackTest.java
components/camel-mllp/src/test/java/org/apache/camel/component/mllp/MllpTcpServerConsumerMulitpleTcpPacketTest.java
components/camel-mongodb/src/main/java/org/apache/camel/component/mongodb/verifier/MongoComponentVerifierExtension.java

removed redundant calls of String.format()

removed redundant calls of String.format()

---

core/camel-core-engine/src/main/java/org/apache/camel/impl/DefaultCamelContext.java
core/camel-core/src/test/java/org/apache/camel/util/CaseInsensitiveMapTest.java
core/camel-support/src/main/java/org/apache/camel/support/DefaultExchangeHolder.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/ListHealth.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/XRefCheckMojo.java
tooling/openapi-rest-dsl-generator/src/main/java/org/apache/camel/generator/openapi/RestDslYamlGenerator.java

optimized map iteration: entrySet() instead of keySet(). In one case loop was substituted with parametrised constructor call

optimized map iteration: entrySet() instead of keySet()

---

components/camel-micrometer/src/main/java/org/apache/camel/component/micrometer/MicrometerConstants.java
docs/user-manual/modules/ROOT/pages/camel-3x-upgrade-guide-3_21.adoc

CAMEL-19193 - Follow Micrometer meter naming conventions

---

components/camel-cm-sms/src/main/java/org/apache/camel/component/cm/CMSenderOneMessageImpl.java

fix for the issue "assignment to a catch block parameter"
Used a local var for assignment

fix for the issue "assignment to a catch block parameter"

---

components/camel-zookeeper/src/main/java/org/apache/camel/component/zookeeper/operations/FutureEventDrivenOperation.java

removed unread local StringBuilder instance

removed unread local StringBuilder instance

---

components/camel-platform-http/src/main/java/org/apache/camel/component/platform/http/PlatformHttpComponent.java
components/camel-zookeeper-master/src/main/java/org/apache/camel/component/zookeepermaster/group/internal/ZooKeeperGroup.java

reacted on inspection "set.removeAll(list) calls may work slowly"
Ref post: https://stackoverflow.com/questions/28671903/the-hashsett-removeall-method-is-surprisingly-slow

reacted on inspection "set.removeAll(list) calls may work slowly"

---

components/camel-reactive-streams/src/main/java/org/apache/camel/component/reactive/streams/ReactiveStreamsComponent.java
components/camel-sql/src/generated/java/org/apache/camel/component/sql/stored/template/generated/TokenMgrError.java
core/camel-xml-io/src/main/java/org/apache/camel/xml/io/MXParser.java

static methods don't need final keyword, it's senseless

static methods don't need final keyword, it's senseless

---

components/camel-zeebe/src/main/docs/zeebe-component.adoc
components/camel-zeebe/src/main/java/org/apache/camel/component/zeebe/ZeebeComponent.java
components/camel-zeebe/src/test/java/org/apache/camel/component/zeebe/ZeebeComponentTest.java

Ported fixes from main to 3.x
- [ x] I formatted the code using `mvn -Pformat,fastinstall install && mvn -Psourcecheck`

Fixed default host and port for zeebe service and improved documentation

---

dsl/camel-java-joor-dsl/src/main/java/org/apache/camel/dsl/java/joor/MultiCompile.java
tooling/camel-tooling-maven/src/main/java/org/apache/camel/tooling/maven/MavenDownloaderImpl.java
tooling/camel-tooling-maven/src/main/java/org/apache/camel/tooling/maven/MavenGav.java
tooling/camel-tooling-maven/src/main/java/org/apache/camel/tooling/maven/support/DIRegistry.java

String.equalsTo("") replaced with String.isEmpty(). The latter is more efficient. Separate commit for core and tooling
In MavenDownloaderImpl combined two similar IF blocks and removed useless assignment

String.equalsTo("") replaced with String.isEmpty() in core and tooling

---

core/camel-core-xml/src/main/java/org/apache/camel/core/xml/AbstractCamelContextFactoryBean.java

Removed empty List of RouteBuilders and the related loop. This loop does nothing.

Removed empty List of RouteBuilders and the related loop.

---

components/camel-soap/src/main/java/org/apache/camel/dataformat/soap/SoapDataFormat.java

Removed empty List headerParts and the related loop. This loop does nothing.

Removed empty List headerParts and the related loop

---

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/dto/composite/SObjectBatch.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/dto/composite/SObjectComposite.java
components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/api/dto/composite/SObjectTree.java
components/camel-zookeeper/src/main/java/org/apache/camel/component/zookeeper/ZooKeeperCuratorConfiguration.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultInflightRepository.java
core/camel-cloud/src/main/java/org/apache/camel/impl/cloud/StaticServiceDiscovery.java
core/camel-core-catalog/src/main/java/org/apache/camel/catalog/impl/AbstractCamelCatalog.java
core/camel-support/src/main/java/org/apache/camel/component/extension/verifier/ResultErrorHelper.java
core/camel-support/src/main/java/org/apache/camel/support/component/ApiCollection.java

Reacted on inspection "subsequent calls can be fused into Stream API chain"

Reacted on inspection "subsequent calls can be fused into Stream API chain

---

dsl/camel-endpointdsl/src/main/java/org/apache/camel/builder/endpoint/AbstractEndpointBuilder.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Bind.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportBaseCommand.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/ExportSpringBoot.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Init.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/Pipe.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/process/AvailablePortFinder.java
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/download/KnownKameletRoutesBuilderLoader.java
dsl/camel-yaml-dsl/camel-yaml-dsl-common/src/main/java/org/apache/camel/dsl/yaml/common/YamlDeserializerSupport.java

Fixed results of inspection "redundant local variable". Inlining of variables is the solution. PR for dsl

Fixed results of inspection "redundant local variable" for dsl

---

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultFactoryFinder.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultFluentProducerTemplate.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/IntrospectionSupport.java
core/camel-base/src/main/java/org/apache/camel/component/properties/AbstractLocationPropertiesSource.java
core/camel-base/src/main/java/org/apache/camel/converter/CollectionConverter.java
core/camel-core-catalog/src/main/java/org/apache/camel/catalog/impl/AbstractCamelCatalog.java
core/camel-core-languages/src/main/java/org/apache/camel/language/csimple/CSimpleExpressionParser.java
core/camel-core-languages/src/main/java/org/apache/camel/language/csimple/CSimplePredicateParser.java
core/camel-core-languages/src/main/java/org/apache/camel/language/simple/SimpleExpressionBuilder.java
core/camel-core-languages/src/main/java/org/apache/camel/language/simple/SimpleTokenizer.java
core/camel-core-model/src/main/java/org/apache/camel/model/rest/RestsDefinition.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/SendDynamicAwareResolver.java
core/camel-core-processor/src/main/java/org/apache/camel/processor/errorhandler/RedeliveryErrorHandler.java
core/camel-core-reifier/src/main/java/org/apache/camel/reifier/LoadBalanceReifier.java
core/camel-core-reifier/src/main/java/org/apache/camel/reifier/MulticastReifier.java
core/camel-core-reifier/src/main/java/org/apache/camel/reifier/OnCompletionReifier.java
core/camel-main/src/main/java/org/apache/camel/main/BaseMainSupport.java
core/camel-main/src/main/java/org/apache/camel/main/DefaultConfigurationConfigurer.java
core/camel-management/src/main/java/org/apache/camel/management/mbean/ManagedBrowsableEndpoint.java
core/camel-support/src/main/java/org/apache/camel/converter/stream/FileInputStreamCache.java
core/camel-support/src/main/java/org/apache/camel/support/builder/ExpressionBuilder.java
core/camel-support/src/main/java/org/apache/camel/support/language/DefaultAnnotationExpressionFactory.java
core/camel-util/src/main/java/org/apache/camel/util/BaseOrderedProperties.java
core/camel-util/src/main/java/org/apache/camel/util/concurrent/ThreadHelper.java

Fixed results of inspection "redundant local variable". Inlining of variables is the solution. PR for core

Fixed results of inspection "redundant local variable" for core

---

tooling/camel-tooling-maven/src/main/java/org/apache/camel/tooling/maven/support/DIRegistry.java
tooling/camel-tooling-util/src/main/java/org/apache/camel/tooling/util/Version.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/EndpointSchemaGeneratorMojo.java
tooling/maven/camel-package-maven-plugin/src/main/java/org/apache/camel/maven/packaging/UpdateReadmeMojo.java
tooling/openapi-rest-dsl-generator/src/main/java/org/apache/camel/generator/openapi/RestDslYamlGenerator.java

Fixed results of inspection "redundant local variable". Inlining of variables is the solution. PR for tooling

Fixed results of inspection "redundant local variable" for tooling

---

catalog/camel-report-maven-plugin/src/main/java/org/apache/camel/maven/RouteCoverageMojo.java
catalog/camel-route-parser/src/main/java/org/apache/camel/parser/model/CamelNodeDetails.java
components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/BindyFixedLengthFactory.java
components/camel-sql/src/main/java/org/apache/camel/processor/aggregate/jdbc/ClusteredJdbcAggregationRepository.java
components/camel-sql/src/main/java/org/apache/camel/processor/aggregate/jdbc/ClusteredPostgresAggregationRepository.java
components/camel-sql/src/main/java/org/apache/camel/processor/aggregate/jdbc/JdbcAggregationRepository.java
components/camel-sql/src/main/java/org/apache/camel/processor/aggregate/jdbc/PostgresAggregationRepository.java
core/camel-base-engine/src/main/java/org/apache/camel/impl/debugger/DefaultBacklogTracerEventMessage.java
core/camel-core-languages/src/main/java/org/apache/camel/language/simple/types/SimpleIllegalSyntaxException.java
core/camel-support/src/main/java/org/apache/camel/support/MessageHelper.java
core/camel-util/src/main/java/org/apache/camel/util/FileUtil.java
tooling/camel-util-json/src/main/java/org/apache/camel/util/json/Jsoner.java

Optimization of loops with the only action of appending a string several times. For this case String.repeat() method was introduced in java 11

Optimization of loops with the only action of appending a string several times

---

core/camel-main/src/main/java/org/apache/camel/main/MainConfigurationProperties.java

Replaced string concatenation in loop with StringJoiner. PR for core

Replaced string concatenation in loop with StringJoiner. PR for core

---

components/camel-cxf/camel-cxf-soap/src/main/java/org/apache/camel/component/cxf/jaxws/DefaultCxfBinding.java

Replaced string concatenation in loop with StringJoiner. PR for compnents

Replaced string concatenation in loop with StringJoiner. PR for compnents

---

components/camel-jdbc/src/main/java/org/apache/camel/component/jdbc/JdbcProducer.java

CAMEL-19256: camel-jdbc - close stmt in the finnal block

---

parent/pom.xml

Upgrade Hazelcast for ensuring the current code works with the latest version of it and addressing some CVEs.
Tested by the following commands:
```
$ ./mvnw clean install -Pfastinstall,format
$ ./mvnw clean install -f components/camel-hazelcast/pom.xml
$ ./mvnw clean install -f components/camel-jcache/pom.xml
```
It's just a minor dependency upgrade so it's not needed to file a JIRA issue.

Upgrade Hazelcast to 5.2.3

---

docs/user-manual/modules/faq/pages/what-platforms-are-supported.adoc

JDK 8 support was dropped in the 3.15.x branch

---

components/camel-jdbc/src/main/java/org/apache/camel/component/jdbc/JdbcProducer.java

CAMEL-19256: camel-jdbc - close stmt in the finnal block (#9827) for camel-3.x

---

parent/pom.xml

Upgraded from picocli 4.7.1 to 4.7.2. Ticket : CAMEL-19265

Upgrade to Picoli 4.7.2

---

core/camel-api/src/main/java/org/apache/camel/spi/CamelEvent.java
core/camel-api/src/main/java/org/apache/camel/spi/EventFactory.java
core/camel-base/src/main/java/org/apache/camel/impl/event/ExchangeAsyncProcessingStartedEvent.java
core/camel-support/src/main/java/org/apache/camel/support/SimpleEventNotifierSupport.java
docs/user-manual/modules/ROOT/pages/camel-4-migration-guide.adoc

Change camel-opentelemtry references to camel-opentelemetry

Change camel-opentelemtry references to camel-opentelemetry

---

camel-dependencies/pom.xml
parent/pom.xml

Update saxon to 11.5
- [CAMEL-19278](https://issues.apache.org/jira/browse/CAMEL-19278)
- [ x] I formatted the code using `mvn -Pformat,fastinstall install && mvn -Psourcecheck`

CAMEL-19278: Update saxon to 11.5

---

components/camel-spring-ldap/src/main/java/org/apache/camel/component/springldap/SpringLdapProducer.java

fixes https://stackoverflow.com/questions/76072376/how-to-create-yaml-dsl-route-in-apache-camel-to-query-ldap-properties/76079092#76079092

CAMEL-19293: set dn only once

---

components/camel-microprofile/camel-microprofile-metrics/src/main/docs/microprofile-metrics-component.adoc

Add the default Camel metrics on the microprofile metrics component documentation.

doc: Add default camel metrics to microprofile metrics component

---

core/camel-xml-io/src/main/java/org/apache/camel/xml/io/MXParser.java
core/camel-xml-io/src/main/java/org/apache/camel/xml/io/XmlPullParser.java

doc: info about the origins of XML Pull Parser classes

---

Jenkinsfile.ppc64le
components/camel-consul/pom.xml

Added ppc64le supported consul image

---

core/camel-base/src/main/java/org/apache/camel/impl/converter/CoreTypeConverterRegistry.java

Breaking down a few larger methods in order to help the profiler to give more meaningful information.

Converter cleanups

---

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultReactiveExecutor.java

This should help the profiler to provide useful information

(chores) camel-base-engine: break a few large methods

---

components/camel-cxf/camel-cxf-soap/src/main/docs/cxf-component.adoc

Backport doc updates from main

fix up MTOM doc for camel-cxf-soap

---

core/camel-support/src/main/java/org/apache/camel/support/AbstractExchange.java
core/camel-support/src/main/java/org/apache/camel/support/DefaultPooledExchange.java
core/camel-support/src/main/java/org/apache/camel/support/MessageSupport.java

This should make it simpler to abstract their complexity while maintaining reasonable performance (as they are used in many parts within the hot path)

CAMEL-19058: wrap some internal properties in an EnumMap

---

components/camel-ldap/src/main/docs/ldap-component.adoc

The following changes have been made to the LDAP component user guide:
* Fixed typos in sample code
* Removed deprecated API calls in credentials example
* Migrated the SSL example from Blueprint to Spring Boot.

camel-ldap: Updated documentation

---

components/camel-azure/camel-azure-cosmosdb/pom.xml
components/camel-azure/camel-azure-cosmosdb/src/main/java/org/apache/camel/component/azure/cosmosdb/CosmosDbComponent.java
components/camel-azure/camel-azure-cosmosdb/src/main/java/org/apache/camel/component/azure/cosmosdb/CosmosDbConfiguration.java
components/camel-azure/camel-azure-cosmosdb/src/main/java/org/apache/camel/component/azure/cosmosdb/client/CosmosDbClientFactory.java

See https://issues.apache.org/jira/browse/CAMEL-19325: Adding support for default identity authentication. @oscerd : I removed the validation part for the authentication, as you did for the datalake last time in a similiar case. Hope that's fine.

CAMEL-19325: Add default identity support

---

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/DefaultInflightRepository.java

This seems to help (mostly?) consumers when there is heavy contention. For instance, with Disruptor on a 6 consumer / 3 producer thread configuration:
```
GEOMETRIC MEAN (RATE):
Test: 1041550.6594790532 | Baseline: 703258.587167714
Delta: 338292.0723113392
The geometric mean rate was greater for the test than for the baseline
```
Where "Test" is this patch and "Baseline" is 4.0.0-M3.

CAMEL-19060: use LongAdder in DefaultInflightRepository to reduce contention

---

camel-dependencies/pom.xml
components/camel-spring-redis/pom.xml
components/camel-spring-redis/src/test/java/org/apache/camel/component/redis/integration/RedisConsumerManualIT.java
components/camel-spring-redis/src/test/java/org/apache/camel/component/redis/integration/RedisProducerManualIT.java
parent/pom.xml

Bump jedis and data spring redis version and restore integration tests

Bump jedis and spring data redis version

---

components/camel-huawei/camel-huaweicloud-frs/src/main/java/org/apache/camel/component/huaweicloud/frs/FaceRecognitionEndpoint.java
components/camel-huawei/camel-huaweicloud-imagerecognition/src/main/java/org/apache/camel/component/huaweicloud/image/ImageRecognitionEndpoint.java

Change display names for hwcloud to be more user friendly

---

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/CamelInternalProcessor.java

This should help the profiler to provide more useful information

(chores): break the before method on the StreamCachingAdvice

---

components/camel-mybatis/src/main/docs/mybatis-component.adoc

CAMEL-19352: improve mybatis doc

---

camel-dependencies/pom.xml
parent/pom.xml

This also fixes the CI issues on the PGP component

Upgrade bouncy castle to 1.73

---

components/camel-mybatis/src/main/java/org/apache/camel/component/mybatis/MyBatisBeanProducer.java
components/camel-mybatis/src/test/java/org/apache/camel/component/mybatis/bean/MyBatisBeanWrongMethodTest.java

Handle exception thrown in beanProcessor.process

---

components/camel-aws/camel-aws-cloudtrail/src/main/java/org/apache/camel/component/aws/cloudtrail/CloudtrailConsumerHealthCheck.java
components/camel-aws/camel-aws-secrets-manager/src/main/java/org/apache/camel/component/aws/secretsmanager/SecretsManagerClientHealthCheck.java
components/camel-aws/camel-aws2-athena/src/main/java/org/apache/camel/component/aws2/athena/Athena2ClientHealthCheck.java
components/camel-aws/camel-aws2-cw/src/main/java/org/apache/camel/component/aws2/cw/Cw2ClientHealthCheck.java
components/camel-aws/camel-aws2-ddb/src/main/java/org/apache/camel/component/aws2/ddb/Ddb2ClientHealthCheck.java
components/camel-aws/camel-aws2-ec2/src/main/java/org/apache/camel/component/aws2/ec2/AWS2EC2HealthCheck.java
components/camel-aws/camel-aws2-ecs/src/main/java/org/apache/camel/component/aws2/ecs/ECS2ClientHealthCheck.java
components/camel-aws/camel-aws2-eks/src/main/java/org/apache/camel/component/aws2/eks/EKS2ClientHealthCheck.java
components/camel-aws/camel-aws2-eventbridge/src/main/java/org/apache/camel/component/aws2/eventbridge/EventbridgeClientHealthCheck.java
components/camel-aws/camel-aws2-iam/src/main/java/org/apache/camel/component/aws2/iam/IAM2HealthCheck.java
components/camel-aws/camel-aws2-kinesis/src/main/java/org/apache/camel/component/aws2/kinesis/Kinesis2ConsumerHealthCheck.java
components/camel-aws/camel-aws2-lambda/src/main/java/org/apache/camel/component/aws2/lambda/Lambda2ClientHealthCheck.java
components/camel-aws/camel-aws2-mq/src/main/java/org/apache/camel/component/aws2/mq/MQ2ClientHealthCheck.java
components/camel-aws/camel-aws2-msk/src/main/java/org/apache/camel/component/aws2/msk/MSK2HealthCheck.java
components/camel-aws/camel-aws2-s3/src/main/java/org/apache/camel/component/aws2/s3/AWS2S3ConsumerHealthCheck.java
components/camel-aws/camel-aws2-ses/src/main/java/org/apache/camel/component/aws2/ses/Ses2HealthCheck.java
components/camel-aws/camel-aws2-sns/src/main/java/org/apache/camel/component/aws2/sns/Sns2HealthCheck.java
components/camel-aws/camel-aws2-sqs/src/main/java/org/apache/camel/component/aws2/sqs/Sqs2ConsumerHealthCheck.java
components/camel-aws/camel-aws2-translate/src/main/java/org/apache/camel/component/aws2/translate/Translate2ClientHealthCheck.java

CAMEL-19314 - Fixing the connection pool shutdown when aws health checks are used

---

components/camel-observation/src/main/java/org/apache/camel/observation/MicrometerObservationTracer.java

shouldn't happen but better be safe than sorry

Adds a null guard against parentObservation

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd
core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractDynamicRegistry.java
core/camel-core/src/test/java/org/apache/camel/impl/DefaultEndpointRegistryTest.java

Revert "CAMEL-19295 - Concurrency issues with dynamicMap in AbstractDynamicRegistry"

---

core/camel-api/src/main/java/org/apache/camel/ValueHolder.java
core/camel-util/src/main/java/org/apache/camel/util/URIScanner.java
core/camel-util/src/main/java/org/apache/camel/util/URISupport.java
core/camel-util/src/test/java/org/apache/camel/util/URIScannerTest.java
dsl/camel-endpointdsl/src/main/java/org/apache/camel/builder/endpoint/AbstractEndpointBuilder.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/KameletDeserializer.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/main/java/org/apache/camel/dsl/yaml/YamlRoutesBuilderLoader.java

- Brings a few minor cleanups to the URISupport, URIScanner
- Adds a unit test for the URIScanner

(chores) camel-util: code cleanups

---

core/camel-core/src/test/java/org/apache/camel/impl/DefaultEndpointRegistryTest.java
core/camel-core/src/test/java/org/apache/camel/impl/DefaultProducerCacheTest.java
core/camel-core/src/test/java/org/apache/camel/support/DefaultLRUCacheFactoryTest.java
core/camel-support/src/main/java/org/apache/camel/support/DefaultLRUCacheFactory.java

Backport of https://github.com/apache/camel/pull/10157 for Camel 3.21

CAMEL-19295: Basic thread-safe LRU cache

---

dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/RouteTemplateDefinitionDeserializer.java
dsl/camel-yaml-dsl/camel-yaml-dsl-deserializers/src/main/java/org/apache/camel/dsl/yaml/deserializers/TemplatedRouteDefinitionDeserializer.java
dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camel-yaml-dsl.json
dsl/camel-yaml-dsl/camel-yaml-dsl/src/generated/resources/schema/camelYamlDsl.json
dsl/camel-yaml-dsl/camel-yaml-dsl/src/test/groovy/org/apache/camel/dsl/yaml/KameletLoaderTest.groovy

Fixes: https://issues.apache.org/jira/browse/CAMEL-19392

[CAMEL-19392] Correct template bean definition schema

---

core/camel-core-processor/src/main/java/org/apache/camel/processor/transformer/DataFormatTransformer.java
core/camel-core-reifier/src/main/java/org/apache/camel/reifier/transformer/CustomTransformerReifier.java
core/camel-core-reifier/src/main/java/org/apache/camel/reifier/transformer/TransformerReifier.java

- Fixes CustomTransformerReifier classname
- Fixes unused `input` variable in DataFormatTransformer

Fix typo in classname and avoid unused variable

---

.github/actions/component-test/component-test.sh
.github/workflows/pr-comment-main.yml

Modifications:
* Add more log messages to ease debugging
* Limit the most to trigger the workflow by adding more tests
* Checkout the current branch instead of the head

Add more log message to the component-test action

---

components/camel-bean/src/main/docs/bean-component.adoc

Fix typo in bean-component.adoc

---

dsl/camel-endpointdsl/pom.xml

remove the dependency which is got into pom after https://github.com/apache/camel/pull/10218

remove jakarta mail dep from pom

---

dsl/camel-yaml-dsl/camel-yaml-dsl-common/src/main/java/org/apache/camel/dsl/yaml/common/YamlDeserializationContext.java

Solving some sonar issues about [replacing inner classes with lambdas](https://rules.sonarsource.com/java/tag/java8/RSPEC-1604).

(chores) replacing inner classes with lambda

---

components/camel-velocity/src/main/java/org/apache/camel/component/velocity/CamelVelocityDelegateClassLoader.java
components/camel-velocity/src/main/java/org/apache/camel/component/velocity/VelocityEndpoint.java

CAMEL-19140 : fix typo and update deprected property name from constants

---

components/camel-cxf/camel-cxf-soap/src/main/docs/cxf-component.adoc

Backport of https://github.com/apache/camel/pull/10266

[3.18.x] Add Java snippets on CXF component page, normalize formating markup, re-indent examples

---

components/camel-cxf/camel-cxf-soap/src/main/docs/cxf-component.adoc

Backport of https://github.com/apache/camel/pull/10266

[3.20.x] Add Java snippets on CXF component page, normalize formating markup, re-indent examples

---

components/camel-leveldb/src/main/docs/leveldb.adoc
components/camel-sql/src/main/docs/sql-component.adoc

Fix typo in sql-component.adoc leveldb.adoc

---

docs/user-manual/modules/ROOT/pages/camel-jbang.adoc
dsl/camel-kamelet-main/src/main/java/org/apache/camel/main/KameletMain.java
dsl/camel-kamelet-main/src/test/java/org/apache/camel/main/KameletMainTest.java
dsl/camel-kamelet-main/src/test/java/org/apache/camel/main/app/Greeter.java
dsl/camel-kamelet-main/src/test/resources/org/apache/camel/main/xml/spring-camel2.xml
dsl/camel-xml-io-dsl/src/main/docs/java-xml-io-dsl.adoc

[CAMEL-18189] Add documentation about <bean> support

---

pom.xml

Upgrade Maven Surefire and Failsafe plugin from 3.1.0 to 3.1.2

---

tooling/maven/camel-eip-documentation-enricher-maven-plugin/pom.xml
tooling/maven/camel-eip-documentation-enricher-maven-plugin/src/main/java/org/apache/camel/maven/DocumentationEnricher.java

as recommended in Javadoc
https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/text/WordUtils.html

Migrate deprecated method from commons-lang3 to commons-text

---

components/camel-file/src/main/java/org/apache/camel/component/file/FileOperations.java
components/camel-file/src/main/java/org/apache/camel/component/file/strategy/GenericFileProcessStrategySupport.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FromFileToFtpDefaultRootRenameStrategyIT.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FromFtpDirectoryToBinaryFilesIT.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FromFtpSetNamesWithMultiDirectoriesIT.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FromFtpToBinaryFileIT.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FromFtpToBinaryFilesIT.java
components/camel-ftp/src/test/java/org/apache/camel/component/file/remote/integration/FtpSimpleConsumeStreamingStepwiseIT.java
core/camel-base/src/generated/java/org/apache/camel/converter/CamelBaseBulkConverterLoader.java
core/camel-base/src/main/java/org/apache/camel/converter/IOConverter.java
core/camel-core/src/test/java/org/apache/camel/converter/ConverterTest.java
docs/user-manual/modules/ROOT/pages/camel-4-migration-guide.adoc

CAMEL-19435: camel-core - Remove converter: String -> java.io.File

---

components/camel-cxf/camel-cxf-soap/src/main/docs/cxf-component.adoc

Backport of https://github.com/apache/camel/pull/10342

[3.20.x] Remove a pointless Quarkus Java snippet inside a Spring XML docs section

---

components/camel-cxf/camel-cxf-soap/src/main/docs/cxf-component.adoc

Backport of https://github.com/apache/camel/pull/10342

[3.18.x] Remove a pointless Quarkus Java snippet inside a Spring XML docs section

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade to kafka 3.4.1

---

pom.xml

- https://issues.apache.org/jira/browse/SUREFIRE-1831 has been fixed in 3.0.0-M6 based on the fix version of duplicate
https://issues.apache.org/jira/browse/SUREFIRE-1809
- https://issues.apache.org/jira/browse/SUREFIRE-2096 has been fixed in 3.0.0-M8

Upgrade Maven Surefire and Failsafe plugin from 3.0.0-MX to 3.1.2

---

components/camel-salesforce/camel-salesforce-component/src/main/java/org/apache/camel/component/salesforce/SalesforceConsumer.java

CAMEL-19409: Allow clients to manually restart the subscription

---

components/camel-caffeine/pom.xml
components/camel-infinispan/camel-infinispan-embedded/pom.xml
parent/pom.xml

https://issues.apache.org/jira/browse/CAMEL-19440
Motivation: avoid testing and runtime inconsistencies

CAMEL-19440 - Manage caffeine to build and test with a single deterministic version

---

components/camel-elasticsearch/src/main/java/org/apache/camel/component/es/converter/ElasticsearchActionRequestConverter.java
components/camel-http-common/src/main/java/org/apache/camel/http/common/CamelServlet.java
components/camel-http-common/src/test/java/org/apache/camel/http/common/CamelServletTest.java
core/camel-support/src/main/java/org/apache/camel/support/RestConsumerContextPathMatcher.java
core/camel-support/src/test/java/org/apache/camel/support/RestConsumerContextPathMatcherTest.java

1. throw exception when duplicate servlet path occur in create stage.
2. throw exception when ambiguous path occur in rest requesting stage.

should servlet and rest throw exceptions when duplicate and ambiguous paths occur

---

camel-dependencies/pom.xml
parent/pom.xml

CAMEL-19468: Upgrade saxon to 12.2

---

core/camel-core/src/test/java/org/apache/camel/processor/WireTapAbortPolicyTest.java

WireTapAbortPolicyTest is flaky

---

core/camel-core/src/test/java/org/apache/camel/processor/SplitParallelTimeoutTest.java

Originally introduced by 13798aa92b575a2b968ea776974bef1d4bdd76a6

(chores) ci: fix flakyness on split test

---

components/camel-hashicorp-vault/pom.xml

Added ppc64le supported hashicorp-vault image
Enable test execution for power arch

Added ppc64le supported hashicorp-vault image

---

camel-dependencies/pom.xml
components/camel-snakeyaml/src/main/java/org/apache/camel/component/snakeyaml/SnakeYAMLDataFormat.java
components/camel-snakeyaml/src/main/java/org/apache/camel/component/snakeyaml/custom/CustomClassLoaderConstructor.java
components/camel-snakeyaml/src/test/java/org/apache/camel/component/snakeyaml/SnakeYAMLDoSTest.java
dsl/camel-jbang/camel-jbang-core/src/main/java/org/apache/camel/dsl/jbang/core/commands/CodeRestGenerator.java
parent/pom.xml
tooling/maven/camel-restdsl-openapi-plugin/src/main/java/org/apache/camel/maven/generator/openapi/AbstractGenerateMojo.java

This reverts commit 78aabad4e5684add922c23e6c25d6ce6be49a1af.

Revert "CAMEL-19130: Upgrade to snakeyaml 2.x (#10450)"

---

Jenkinsfile.deploy

Is this the right way to do it @orpiske?

Fixup Workaround INFRA-24713 in the deploy script rather than for all possible builds

---

core/camel-core-model/src/main/java/org/apache/camel/model/ChoiceDefinition.java

Fixes https://issues.apache.org/jira/browse/CAMEL-19330

[CAMEL-19330] Dump model for Choice should have otherwise last

---

camel-dependencies/pom.xml
parent/pom.xml

CAMEL-19505 - Upgrade Azure SDK BOM to version 1.2.14

---

camel-dependencies/pom.xml
parent/pom.xml

CAMEL-19506 - Upgrade Huawei-cloud SDK core and related to 3.1.45

---

catalog/camel-catalog/src/generated/resources/org/apache/camel/catalog/schemas/camel-spring.xsd
components/camel-elytron/pom.xml
parent/pom.xml

CAMEL-19507 - Upgrade Wildfly Elytron to version 1.20.4.Final

---

components/camel-csimple-joor/src/test/java/org/apache/camel/language/csimple/joor/OriginalSimpleTest.java
core/camel-core-languages/src/main/docs/modules/languages/pages/simple-language.adoc
core/camel-core-languages/src/main/java/org/apache/camel/language/csimple/CSimpleHelper.java
core/camel-core-languages/src/main/java/org/apache/camel/language/simple/ast/SimpleFunctionExpression.java
core/camel-core/src/test/java/org/apache/camel/language/simple/SimpleTest.java
core/camel-support/src/main/java/org/apache/camel/support/builder/ExpressionBuilder.java
tooling/maven/camel-package-maven-plugin/pom.xml

Fix https://issues.apache.org/jira/browse/CAMEL-19479

[CAMEL-19479] Add `threadId` to simple language

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.94

---

components/camel-bindy/src/main/java/org/apache/camel/dataformat/bindy/BindyFixedLengthFactory.java

Camel-Bindy: Use isEmpty instead of comparing with empty String

---

camel-dependencies/pom.xml
components/camel-grpc/pom.xml
components/camel-protobuf/pom.xml
components/camel-salesforce/camel-salesforce-component/pom.xml
core/camel-support/src/main/java/org/apache/camel/converter/stream/InputStreamCache.java
parent/pom.xml

https://issues.apache.org/jira/browse/CAMEL-19558

CAMEL-19558 - Manage protobuf to build and test with a single deterministic version

---

camel-dependencies/pom.xml
components/camel-jt400/pom.xml
parent/pom.xml

Jt400 dependency upgrade

---

camel-dependencies/pom.xml
catalog/camel-catalog-maven-grape/pom.xml
catalog/camel-catalog-maven/pom.xml
catalog/camel-report-maven-plugin/pom.xml
components/camel-as2/camel-as2-api/pom.xml
components/camel-atom/pom.xml
components/camel-base64/pom.xml
components/camel-crypto/pom.xml
components/camel-github/pom.xml
components/camel-google/camel-google-mail/pom.xml
components/camel-kubernetes/pom.xml
components/camel-oaipmh/pom.xml
components/camel-rss/pom.xml
components/camel-xmlsecurity/pom.xml
parent/pom.xml
tooling/camel-tooling-maven/pom.xml

https://issues.apache.org/jira/browse/CAMEL-19559

Manage commons-codec to build and test with a single deterministic version

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/consumer/errorhandler/ReconnectErrorStrategy.java

When an authentication error is thrown by Kafka, this could cause an endless loop in the client. Potentially affecting the Kafka broker due to an excessive connection retries in a short period.
This prevents authentication related errors to cause this.

CAMEL-19285: prevent Kafka client from entering an endless loop

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.96

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.97

---

parent/pom.xml

Upgrade Openstack4j to version 3.11

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade GraalJS to version 22.3.2

---

init/camel-bundle-plugin/src/main/java/org/apache/felix/bundleplugin/ManifestPlugin.java
parent/pom.xml
pom.xml
tooling/maven/camel-package-maven-plugin/pom.xml

Fix some Reproducible Builds issues see on 3.21.0 release: https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/camel/camel/README.md

improve reproducible builds

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade Fastjson to version 2.0.34

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade Jsonapi to version 0.12

---

components/camel-micrometer/pom.xml
components/camel-micrometer/src/test/java/org/apache/camel/component/micrometer/eventnotifier/MicrometerExchangeEventNotifierTest.java
components/camel-observation/pom.xml
components/camel-observation/src/test/java/org/apache/camel/observation/CamelMicrometerObservationTestSupport.java
components/camel-observation/src/test/java/org/apache/camel/observation/CurrentSpanTest.java
components/camel-opentelemetry/pom.xml
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/CamelOpenTelemetryTestSupport.java
components/camel-opentelemetry/src/test/java/org/apache/camel/opentelemetry/CurrentSpanTest.java
parent/pom.xml

https://issues.apache.org/jira/browse/CAMEL-19560

CAMEL-19560 - Manage micrometer artifacts to build and test with a single deterministic set of versions

---

camel-dependencies/pom.xml
components/camel-parquet-avro/src/main/java/org/apache/camel/dataformat/parquet/avro/ParquetAvroDataFormat.java
parent/pom.xml

This PR upgrades Parquet to the latest version for ensuring the current component works with it and addressing some CVEs. It also removes unnecessary code from ParquetAvroDataFormat.java.
No corresponding JIRA issue since it's just a dependency upgrade (and unnecessary code removal)

Upgrade to Parquet 1.13.1

---

pom.xml

merging PR #10557 , the only remaining update is the maven-release-plugin version and configuration
rebuilding 4.0.0-RC1, https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/org/apache/camel/camel/camel-4.0.0-RC1.diffoscope
the vast majority of issues are due to Jandex index
a few minor issue remain on 5 artifacts...

improve release process

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.98

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade DNSJava to version 3.5.2

---

camel-dependencies/pom.xml
components/camel-flink/pom.xml
parent/pom.xml

The recent version of Flink is independent on Scala ([FLINK-23986](https://issues.apache.org/jira/browse/FLINK-23986)), so we can remove that unused dependency.
No corresponding JIRA issue since it's just a dependency removal.

Remove unnecessary dependency from camel-flink

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade Jolt to version 0.1.8

---

camel-dependencies/pom.xml
parent/pom.xml

Upgrade asn1bean to version 1.14.0

---

parent/pom.xml
test-infra/camel-test-infra-pulsar/src/test/java/org/apache/camel/test/infra/pulsar/services/PulsarLocalContainerService.java

This PR upgrades Pulsar to 3.0.0 so as to make sure the current code works with that version and address some CVEs.
No corresponding JIRA issue since it's just a dependency upgrade

Upgrade to Pulsar 3.0.0

---

parent/pom.xml

Upgrade Json Schema Validator to version 1.0.85

---

components/camel-google/camel-google-functions/pom.xml
parent/pom.xml

CAMEL-19572 - Camel-Google-Cloud components: Upgrade to a new Libraries BOM

---

parent/pom.xml

Upgrade Minio to version 8.5.4

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.99

---

parent/pom.xml
test-infra/camel-test-infra-nats/src/test/java/org/apache/camel/test/infra/nats/services/NatsLocalContainerService.java

Upgrade Jnats to version 2.16.13

---

parent/pom.xml

Upgrade Zxing to version 3.5.1

---

parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.100

---

parent/pom.xml

Upgrade bouncycastle 1.75

---

parent/pom.xml

Upgrade Pubnub Gson to version 6.3.6

---

parent/pom.xml

Upgrade junit

---

parent/pom.xml

Upgrade PDFBox to version 2.0.29

---

core/camel-base-engine/src/main/java/org/apache/camel/impl/engine/AbstractCamelContext.java
core/camel-cloud/src/main/java/org/apache/camel/impl/cloud/DefaultServiceDefinition.java
core/camel-core-catalog/src/main/java/org/apache/camel/catalog/impl/TimePatternConverter.java

(chores) camel-core: removed unnecessary boxing/unboxing

---

core/camel-core-catalog/src/main/java/org/apache/camel/catalog/impl/AbstractCamelCatalog.java

(chores) camel-core-catalog: consolidate duplicated code

---

core/camel-core-catalog/src/main/java/org/apache/camel/catalog/impl/AbstractCamelCatalog.java
parent/pom.xml

Upgrade AWS SDK v2 to version 2.20.101

---

parent/pom.xml

Upgrade Docker Java to version 3.3.2

---

parent/pom.xml

Upgrade Johnzon JsonB to version 1.2.21

---

components/camel-kafka/src/main/java/org/apache/camel/component/kafka/KafkaComponent.java

CAMEL-19444. Fixed a few grammar errors on code comments in camel-kafka

---

components/camel-git/src/main/java/org/apache/camel/component/git/producer/GitProducer.java
parent/pom.xml

Upgrade Jgit to version 6.6.0.202305301015-r

---

parent/pom.xml
test-infra/camel-test-infra-elasticsearch/src/test/java/org/apache/camel/test/infra/elasticsearch/services/ElasticSearchLocalContainerService.java

Upgrade elasticsearch 8.8.2

---

parent/pom.xml

Upgrade dlj 0.22.1

---

components/camel-caffeine/src/test/java/org/apache/camel/component/caffeine/cache/CaffeineCacheFromScratchStatsCounterTest.java
components/camel-caffeine/src/test/java/org/apache/camel/component/caffeine/cache/CaffeineCacheProducerMultiOperationSameCacheTest.java
components/camel-caffeine/src/test/java/org/apache/camel/component/caffeine/cache/CaffeineCacheTestSupport.java
components/camel-caffeine/src/test/java/org/apache/camel/component/caffeine/loadcache/CaffeineLoadCacheProducerMultiOperationSameCacheTest.java
components/camel-caffeine/src/test/java/org/apache/camel/component/caffeine/loadcache/CaffeineLoadCacheTestSupport.java
components/camel-caffeine/src/test/java/org/apache/camel/component/caffeine/processor/idempotent/CaffeineIdempotentRepositoryTest.java

- removed unused code
- use final where possible
- fixed typos

CAMEL-19446: code cleanups on camel-caffeine

---

parent/pom.xml

Upgrade InfluxDB Client Java to version 6.9.0

---

parent/pom.xml

Upgrade MongoDB Java Driver to version 4.10.1

---

parent/pom.xml

Upgrade Huawei cloud core to version 3.1.47
